ReleaseNotes-2.11, docs/api/api/configuration.rng, src/api/public/apidocs-new/components/schemas/configuration.yaml
=> Add tos_url to configuration schema

dist/obs-server.spec, dist/setup-appliance.sh, dist/system-user-obsapidelayed.conf, dist/system-user-obsrun.conf, dist/system-user-obsservicerun.conf, dist/systemd/obs-clockwork.service, dist/systemd/obs-delayedjob-queue-consistency_check.service, dist/systemd/obs-delayedjob-queue-default.service, dist/systemd/obs-delayedjob-queue-issuetracking.service, dist/systemd/obs-delayedjob-queue-mailers.service, dist/systemd/obs-delayedjob-queue-project_log_rotate.service, dist/systemd/obs-delayedjob-queue-quick@.service, dist/systemd/obs-delayedjob-queue-releasetracking.service, dist/systemd/obs-delayedjob-queue-staging.service, dist/systemd/obs-sphinx.service, docs/api/api/constraints.rng, docs/api/api/constraints.xml, src/backend/BSDispatcher/Constraints.pm, src/backend/BSXML.pm, src/backend/bs_dispatch, src/backend/bs_repserver, src/backend/bs_worker, src/backend/testdata/constraint/kernel, src/backend/testdata/constraint/tensorflow, src/backend/testdata/test_dispatcher, src/backend/testdata/workerinfo/large, src/backend/testdata/workerinfo/medium
WIP
* Fix obs-server 2.10.11 package for openSUSE 15.3
* switch system user generation to sysuser-tools
* back-porting cpu flag exclude constraint (ARM32/64)
=> Prepare Release 2.10.11

src/backend/BSSched/PublishRepo.pm, src/backend/BSSrcServer/Modulemd.pm, src/backend/bs_publish
=> [backend] implement modulemd publishing 

src/api/app/models/bs_request.rb, src/api/app/models/project/embargo_handler.rb, src/api/spec/models/project/embargo_handler_spec.rb
Extract code to check if a maintenance release is embargoed from the BsRequest model and move it to a helper class named `Project::EmbargoHandler` 
=> Embargo handler

.circleci/config.yml, docker-compose.yml, src/api/db/migrate/001_initial_database.rb, src/api/docker-files/Dockerfile, src/api/docker-files/Dockerfile.minitest, src/api/spec/support/capybara.rb
=> Adopt CI/dev-env to unified 15.3 containers

src/backend/BSSched/Modulemd.pm
=> [backend] define %_module_build 1 for modulemd builds

docs/api/api/api.txt, src/api/app/models/bs_request.rb
via additional keep_packages_locked cgi parameter
jsc#OBS-134
=> [api] allow to keep packages locked on mr request revoke

src/backend/BSProductXML.pm
=> [backend] products: add option for using latest rpm based on version

src/api/Procfile
=> We dropped mailcatcher from the containers

src/api/app/controllers/webui/feeds_controller.rb, src/api/app/views/webui/feeds/commits.atom.builder
Single line text instead of multi line HTML. Useful if you just want to know what's going on.
=> Introduces a terse commit feed view

src/api/app/components/copy_to_clipboard_input_component.html.haml, src/api/app/components/copy_to_clipboard_input_component.rb, src/api/app/controllers/webui/users/tokens_controller.rb, src/api/app/policies/token_policy.rb, src/api/app/views/webui/users/tokens/_create.js.erb, src/api/app/views/webui/users/tokens/_update.js.erb, src/api/app/views/webui/users/tokens/edit.html.haml, src/api/app/views/webui/users/tokens/new.html.haml, src/api/spec/controllers/webui/users/tokens_controller_spec.rb
=> Regenerate the Token String in the UI

src/backend/BSSched/Checker.pm, src/backend/BSSched/Modulemd.pm
This is a prerequistite to putting the module information into
the :full tree.
=> [backend] automatically enable the module we're building for

src/api/app/services/scm_exception_handler.rb, src/api/app/services/scm_status_reporter.rb, src/api/config/initializers/zeitwerk.rb
=> Rescue Octokit and Gitlab exceptions and report to errbit

src/api/app/models/token/workflow.rb, src/api/app/models/workflow.rb, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/raises_a_user-friendly_error_message.yml, src/api/spec/models/token/workflow_spec.rb, src/api/spec/models/workflow_spec.rb
The workflow should be the responsible of calling its steps, this way it
has better control on the step execution.
=> Refactor the Workflow step calling responsibility

src/backend/BSSched/BuildJob/Aggregate.pm
But make sure that the aggregated rpms belong to the same module/stream.
=> [backend] BuildJob/Aggregate: also aggregate modulemd data if present

src/api/app/models/workflow.rb, src/api/app/models/workflow/step.rb, src/api/spec/models/workflow_spec.rb, src/api/spec/support/files/workflows.yml
See the [developer documentation](https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration#branches-filter) for branches filter.
=> Implement branches filter for workflows

src/api/app/controllers/concerns/triggerable.rb, src/api/app/controllers/trigger_controller.rb, src/api/app/controllers/webui/users/token_triggers_controller.rb, src/api/app/models/token/workflow.rb, src/api/app/models/workflow.rb, src/api/app/models/workflow/step/rebuild_package.rb, src/api/app/policies/token/workflow_policy.rb, src/api/spec/cassettes/Workflow_Step_RebuildPackage/1_1.yml, src/api/spec/cassettes/Workflow_Step_RebuildPackage/user_has_no_permission_to_trigger/1_2_1.yml, src/api/spec/cassettes/Workflow_Step_RebuildPackage/user_has_no_permission_to_trigger_rebuild/1_2_1.yml, src/api/spec/controllers/concerns/triggerable_spec.rb, src/api/spec/models/workflow/step/rebuild_package_step_spec.rb
See the [developer documentation](https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration#rebuild-a-package) for the `rebuild_package` step.
=> Implement rebuild_package step

src/api/app/models/workflow/step/configure_repositories.rb, src/api/spec/models/workflow/step/configure_repositories_spec.rb
=> Support push events in configure_repositories step

src/api/app/components/sponsors_component.html.haml, src/api/app/components/sponsors_component.rb, src/api/app/helpers/webui/sponsor_helper.rb, src/api/app/views/layouts/webui/_sponsors.html.haml, src/api/app/views/layouts/webui/webui.html.haml, src/api/spec/components/previews/sponsors_component_preview.rb, src/api/spec/components/sponsors_component_spec.rb
Move sponsors related code to a `ViewComponent`
=> Create and use Sponsors ViewComponent

.circleci/config.yml
=> Update brakeman to match dockerfile version

src/api/app/queries/notifications_finder.rb
=> Do one less query to the database with select

src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/long_text.js, src/api/app/assets/stylesheets/webui/application.scss, src/api/app/assets/stylesheets/webui/long-text.scss, src/api/app/views/webui/users/notifications/_notifications_list.html.haml
=> Click and reveal long project and package combinations

docs/api/api/tokenlist.rng, docs/api/api/tokenlist.xml, src/api/app/controllers/person/token_controller.rb, src/api/app/controllers/webui/users/tokens_controller.rb, src/api/app/models/token.rb, src/api/app/models/token/rebuild.rb, src/api/app/models/token/release.rb, src/api/app/models/token/rss.rb, src/api/app/models/token/service.rb, src/api/app/models/token/workflow.rb, src/api/app/views/person/token/index.xml.builder, src/api/app/views/webui/users/tokens/_update.js.erb, src/api/app/views/webui/users/tokens/edit.html.haml, src/api/app/views/webui/users/tokens/new.html.haml, src/api/db/data/20211027143134_backfill_name_from_tokens.rb, src/api/db/data_schema.rb, src/api/db/migrate/20211027141958_add_name_to_tokens.rb, src/api/db/schema.rb, src/api/public/apidocs-new/components/schemas/person_tokens.yaml, src/api/public/apidocs-new/paths/person_login_token.yaml, src/api/spec/controllers/webui/users/tokens_controller_spec.rb
=> Allow users to name their tokens

dist/t/spec/features/0030_project_spec.rb, dist/t/spec/features/0040_package_spec.rb
To test this changes, please follow the developer documentation: https://github.com/openSUSE/open-build-service/wiki/Run-OpenQA-smoketest-locally
=> Adapt smoketests run in openQA to changes made in unstable

src/api/app/components/token_card_component.html.haml, src/api/app/components/token_card_component.rb, src/api/app/views/webui/users/tokens/index.html.haml, src/api/spec/components/token_card_component_spec.rb
We want to move away from simply showing db data in a table.
WIP: Maybe some specs and fine tuning
Before:
After:
=> Refactor out table of token index UI

src/api/test/functional/search_controller_test.rb
=> Fix spelling in comments

src/backend/bs_signer
I.e. do not retry them but fail the build instead.
=> [backend] bs_signer: make some signing errors fatal

src/api/app/components/token_card_component.html.haml, src/api/spec/components/token_card_component_spec.rb
=> Add token id to tokens index and remove quotes from last trigger on paragraph

.obs/workflows.yml
Modifies the repositories filter in the `.obs/workflows.yml`:
- Replace SLE_15_SP3 with 15.3
- Remove openSUSE_Factory whose build is being constantly unresolvable.
=> Adapt workflows yml

src/api/app/models/token/workflow.rb, src/api/app/models/workflow_run.rb, src/api/db/migrate/20211110142710_create_workflow_runs.rb, src/api/db/schema.rb
=> Add workflow runs model and table

src/backend/bs_repserver
We need to distinguish "never released" and "released with no
setrelease".
=> [backend] another tweak for the setrelease mechanism

src/api/app/controllers/trigger/errors.rb, src/api/app/controllers/trigger_workflow_controller.rb, src/api/app/models/token/workflow.rb, src/api/app/models/workflow_run.rb, src/api/spec/controllers/trigger_workflow_controller_spec.rb, src/api/spec/factories/workflow_runs.rb, src/api/spec/models/token/workflow_spec.rb
TODO:
1. [x] Initialize workflow run
2. [x] Track workflow run (success/fail)
3. [x] Add specs
=> Track workflow runs

src/api/app/services/scm_status_reporter.rb, src/api/spec/services/scm_status_reporter_spec.rb
Fixes #11818
If the repository doesn't exist, we destroy the `EventSubscription` associated with that. If the repository is accessible again, after the first push, a new `EventSubscription` will be created.
=> Remove EventSubscription for token and package if repository doesnt

src/api/app/models/workflow.rb, src/api/spec/models/workflow_spec.rb
This will be used in #11832, but it's easy to review here without all the other changes.
This is safe to be merged since it doesn't change how workflows run.
Documentation for this:
- [Developer](https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration#event-filter)
- [User](https://github.com/openSUSE/obs-docu/pull/205)
=> Support push events for tags in event filter of OBS workflows

src/api/app/views/webui/workflow_runs/index.html.haml
=> Minor improvements for the workflow runs UI

src/backend/bs_publish
- copy instead of linking
- patching file name to match the shortened one
- resign (no symlink either anymore)
=> [backend] fix sha256 file for static symlinks

src/api/app/views/layouts/webui/_top_navigation_search.html.haml
Reverts openSUSE/open-build-service#11887
Fixes #11894
=> Revert "Autofocus into the search input field"

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/code_and_summary.yaml, src/api/public/apidocs-new/components/schemas/kiwi.yaml, src/api/public/apidocs-new/paths/source_branch.yaml, src/api/public/apidocs-new/paths/source_createmaintenanceincident.yaml, src/api/public/apidocs-new/paths/source_orderkiwirepos.yaml
=> Add OpenAPI specifications for source cmd

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_createpatchinfo.yaml
`/source/{project_name}?cmd=createpatchinfo`
=> Add '/source/{project_name}?cmd=createpatchinfo' endpoint

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_cmd_createkey.yaml, src/api/public/apidocs-new/paths/source_project_cmd_createmaintenanceincident.yaml
=> OpenAPI specifications for source project cmd createkey/createmaintenanceincident

src/backend/BSSrcServer/Service.pm, src/backend/bs_servicedispatch
Split out the dispatch event generation, the service deamon
interaction and the notification sending into new functions.
=> [backend] refactor service run handling

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_extendkey.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_move.yaml
=> OpenAPI specifications for source project cmd extendkey/move

src/api/public/apidocs-new/OBS-v2.10.50.yaml
Just two tiny self-explanatory fixes.
=> Improve grammar/spelling in the OpenAPI docs

docs/api/api/package.rng, docs/api/api/project.rng, src/api/app/models/bs_request_action_submit.rb, src/api/app/models/package.rb, src/api/app/models/project.rb, src/api/app/models/project/update_from_xml_command.rb, src/api/app/views/models/_package.xml.builder, src/api/app/views/models/_project.xml.builder, src/api/db/migrate/20211214111900_add_scmsync_elements_for_packages_and_projects.rb, src/api/db/schema.rb, src/backend/BSXML.pm, src/backend/bs_srcserver
and supporting submit requests with git based packages.
=> scm support: turn title hack into meta element

src/api/app/models/remote_project.rb
This should have been included in #11981.
=> Add missing change from migration AddScmsyncElementsForPackagesAndProjects

src/api/app/views/layouts/webui/_places.html.haml
Also hide the link if the notifications_redesign is disabled.
Closes #11904
=> Add counter to "Tasks" link under "Places"

src/api/app/models/owner_search/assignee.rb
Get rid of the following abbreviations in variable names: m, prj, pkg, p, b.
Rename "maintainer" to "package_owner": "maintainer" can be misleading, because it can also be "bugowner" depending on the configuration.
=> Expand abbreviations in `OwnerSearch::Assignee` model

src/api/app/models/branch_package.rb
Extract code to private helper methods
=> Extract code from BranchPackage#create_branch_packages

dist/clouduploader.rb
Rubocop complains about this on master
=> Fix Style/FileWrite rubocop in clouduploader module

src/api/app/models/package_build_status.rb, src/api/spec/cassettes/PackageBuildStatus/_current_dir/1_3_1.yml, src/api/spec/cassettes/PackageBuildStatus/_current_dir/1_3_2.yml, src/api/spec/cassettes/PackageBuildStatus/_gather_md5sums/1_2_1.yml, src/api/spec/cassettes/PackageBuildStatus/_gather_md5sums/1_2_2.yml, src/api/spec/cassettes/PackageBuildStatus/_new/1_1_1.yml, src/api/spec/cassettes/PackageBuildStatus/gather_target_packages/1_4_1.yml, src/api/spec/cassettes/PackageBuildStatus/gather_target_packages/1_4_2.yml, src/api/spec/models/package_build_status_spec.rb
Add spec for the public API from `PackageBuildStatus` "model"
=> Add spec for PackageBuildStatus model

src/api/spec/cassettes/PackageBuildStatus/_check_everbuilt/no_job_history/1_5_1_1.yml, src/api/spec/cassettes/PackageBuildStatus/_check_everbuilt/no_job_history/1_5_1_2.yml, src/api/spec/cassettes/PackageBuildStatus/_check_everbuilt/with_job_history/1_5_2_1.yml, src/api/spec/models/package_build_status_spec.rb
Increase the coverage on class `PackageBuildStatus`
=> Add spec for method PackageBuildStatus#check_everbuilt

src/backend/BSDispatcher/Constraints.pm
It was not merged into the result of prjconf and per package constraints
fixes obs#12069
=> [backend] fix memoryperjob constraints

src/api/spec/services/scm_status_reporter_spec.rb
To follow the patterns used in all other specs
=> Move allow and subject instantiation to a before block

src/backend/BSConSign.pm, src/backend/BSPublisher/Registry.pm, src/backend/bs_repserver
See https://github.com/sigstore/cosign
=> [backend] Implement "cosign" signatures

docs/api/api/issue_trackers.xml, src/api/db/seeds.rb, src/api/test/fixtures/issue_trackers.yml, src/api/test/functional/issue_trackers_controller_test.rb
Not sure I did it right, but if so, please merge
=> Add Eclipse Bugzilla to the list of issue trackers

KankuFile, dist/functions.setup-appliance.sh
- updated Kankufile to 15.4
- fix for apache startup problem in 15.4
=> [dist] updated Kankufiles

src/api/app/components/workflow_run_header_component.html.haml, src/api/app/components/workflow_run_header_component.rb, src/api/app/components/workflow_run_row_component.html.haml, src/api/app/components/workflow_run_row_component.rb, src/api/app/controllers/webui/workflow_runs_controller.rb, src/api/app/policies/workflow_run_policy.rb, src/api/app/views/webui/workflow_runs/_breadcrumb_items.html.haml, src/api/app/views/webui/workflow_runs/index.html.haml, src/api/app/views/webui/workflow_runs/show.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/components/workflow_run_header_component_spec.rb, src/api/spec/components/workflow_run_row_component_spec.rb, src/api/spec/policies/workflow_run_policy_spec.rb
=> Implement a workflow run show view

.obs/workflows.yml, src/api/app/models/workflow/step/configure_repositories.rb, src/api/spec/models/workflow/step/configure_repositories_spec.rb
=> Support multiple repository paths in configure_repositories

src/api/app/models/concerns/multibuild_package.rb, src/api/app/models/package.rb, src/api/spec/cassettes/ImageTemplates/branching/branch_Kiwi_image_template.yml, src/api/spec/cassettes/ImageTemplates/branching/branch_image_template.yml, src/api/spec/cassettes/Package/_file_exists_/_multibuild_file_should_exist/1_4_1_1.yml, src/api/spec/cassettes/Package/_file_exists_/with_more_than_one_file/returns_false_if_the_file_does_not_exist.yml, src/api/spec/cassettes/Package/_file_exists_/with_more_than_one_file/returns_true_if_the_file_exist.yml, src/api/spec/cassettes/Package/_file_exists_/with_one_file/returns_false_if_the_file_does_not_exist.yml, src/api/spec/cassettes/Package/_file_exists_/with_one_file/returns_true_if_the_file_exist.yml, src/api/spec/cassettes/Package/_has_icon_/returns_false_if_the_icon_does_not_exist.yml, src/api/spec/cassettes/Package/_has_icon_/returns_true_if_the_icon_exist.yml, src/api/spec/cassettes/Package/_ignored_requests/when_the_package_has_an_ignored_requests_file/parses_the_content_as_YAML_and_returns_a_hash.yml
Only expand sources when asking for multibuild packages
Fixes #12152
=> Do not expand sources by default on Package#file_exists? method

src/api/app/models/workflow.rb, src/api/app/models/workflow/step/set_flags.rb, src/api/spec/models/workflow/step/set_flags_step_spec.rb
Added a step to set flags. With this new step, it's possible to set flags for a project or package. Limiting the flag to a certain repository or architecture is possible as well.
=> Add step `set_flags`

src/api/app/components/workflow_artifacts_per_step_component.rb, src/api/app/components/workflow_run_detail_component.html.haml, src/api/app/components/workflow_run_detail_component.rb, src/api/spec/components/previews/workflow_artifacts_per_step_component_preview.rb, src/api/spec/components/workflow_artifacts_per_step_component_spec.rb
Implement view component to display the artifacts per step.
As a first approach, the view looks like this:
This is a follow-up of https://github.com/openSUSE/open-build-service/pull/12120.
**TODO:**
=> Workflow artifacts UI

src/backend/bs_srcserver
Use expanded view on checkconstraints to work also on plain links (no branch)
=> [backend] fix checkconstraints on plain links

src/api/app/components/workflow_run_filter_component.html.haml
Lets give the users of the workflow runs a brief explanation
about the meaning of the different filter sections.
=> Add a little popover description to workflow run filter categories

src/api/app/controllers/search_controller.rb, src/api/app/models/owner_search/base.rb
Lookup the owner definition in owner search, except this got
disabled in root project or via parameter.
=> [api] take care of devel package definition in owner search

src/backend/BSXML.pm, src/backend/bs_worker
As introduced in https://github.com/openSUSE/obs-build/pull/777
=> [backend] add cpusteal statistics

src/backend/bs_publish
in the buildnumber that we want to remove we can have a.b.c
like for the quarterly builds
=> [backend] bs_publish allow for a third digit

src/api/spec/components/notification_avatars_component_spec.rb
Flaky specs are listed in CircleCI:
https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests
=> Fix flaky spec in NotificationAvatarsComponent

src/api/app/instrumentations/workflow_instrumentation.rb
To answer questions in the SCM/CI integration like:
- Which filter is the most used?
- Are more workflows defined for push or pull request events?
=> Instrument filters in Workflow model

src/api/app/instrumentations/scm_webhook_instrumentation.rb, src/api/app/models/scm_webhook.rb
To answer questions in the SCM/CI integration like:
- Which SCM is the most used?
- Which webhook event is the most frequent?
=> Instrument ScmWebhook

src/api/app/mixins/has_relationships.rb, src/api/app/models/event/relationship.rb, src/api/app/models/event/relationship_create.rb, src/api/app/models/event/relationship_delete.rb, src/api/app/models/relationship.rb, src/api/spec/models/relationship_spec.rb
=> Add events for creating and deleting relationships

src/api/app/controllers/source_controller.rb
take care about
- optional repository flags
- project links
=> [api] fix project copy

src/api/app/models/event/relationship_create.rb, src/api/app/models/event/relationship_delete.rb
This should have been included in #12269.
=> Add missing annotations for Event::Relationship*

src/backend/call-service-in-container
fix problems with podman changes between 2.1.1 and 3.4.4
=> [backend] workaround podman bug #boo 1196751

src/api/app/views/webui/request/show.html.haml
=> Append action id to the xml_id to make a unique tab_pane_id

src/api/app/controllers/group_controller.rb, src/api/app/controllers/person_controller.rb
See https://github.com/ruby/uri/commit/61c6a47ebf1f2726b60a2bbd70964d64e14b1f98
=> Replace URI.unescape with CGI.unescape

dist/t/osc/fixtures/obs-testpackage-2.8._service, dist/t/osc/fixtures/obs-testpackage._service
SEE https://github.blog/2021-09-01-improving-git-protocol-security-github/
for details
=> fixing broken tests using "git://" protocol

.circleci/conditional_config.yml, src/api/lib/tasks/dev.rake
It wasn't invoking our `rake dev:lint:apidocs` rake task...
=> Ensure the CI runs our apidocs linter

src/backend/bs_srcserver
* skip blocked items and do not abort
* fix regexp handling as well
=> [backend] fix sourcepublich blocklist handling

src/api/lib/tasks/dev.rake, src/api/spec/factories/packages.rb
Project with link, multibuild package and packages with local and remote links.
=> Adapt rails task to add special projects and packages

src/backend/BSRepServer/Checker.pm, src/backend/BSSched/BuildJob/Package.pm, src/backend/BSSched/Checker.pm
Also remove duplicated code by moving the sysroot expansion from
the Checker to BuildJob/Package.
=> [backend] support Debian's Multi-Arch indicator for cross build

src/api/app/controllers/webui/users/beta_features_controller.rb, src/api/app/views/webui/users/beta_features/index.html.haml, src/api/spec/features/webui/users/beta_features_spec.rb
=> Do not display rolled-out beta features on Manage Beta Features page

dist/systemd/obs-clockwork.service, dist/systemd/obs-sphinx.service, src/api/Procfile, src/api/bin/rails
Instead of relying on the commands being in the path
=> Use the application binstubs

src/api/lib/obsapi/markdown_renderer.rb, src/api/spec/helpers/webui/markdown_helper_spec.rb
=> Add support to render usernames with dots

src/api/app/components/workflow_artifacts_per_step_component.rb, src/api/app/controllers/concerns/triggerable.rb, src/api/app/models/token/workflow.rb, src/api/app/models/workflow.rb, src/api/app/models/workflow/step.rb, src/api/app/models/workflow/step/errors.rb, src/api/app/models/workflow/step/rebuild_package.rb, src/api/app/models/workflow/step/trigger_services.rb, src/api/app/policies/token/workflow_policy.rb, src/api/app/services/workflows/artifacts_collector.rb, src/api/spec/components/previews/workflow_artifacts_per_step_component_preview.rb, src/api/spec/components/workflow_artifacts_per_step_component_spec.rb, src/api/spec/factories/workflow_artifacts_per_step.rb, src/api/spec/models/workflow/step/trigger_services_spec.rb, src/api/spec/services/workflows/artifacts_collector_spec.rb
This PR implement a step that enables users to trigger services through their workflows.
*TODO*
=> Add trigger service step

src/backend/bs_getbinariesproxy, src/backend/bs_worker
Also refactor cacheid calculation.
=> [backend] switch cacheid calculation to sha256

src/api/app/models/bs_request_permission_check.rb
revoke or supersede still needs to work
=> [api] fix non-accept with OBS:CreatorCannotAcceptOwnRequests

dist/obs-bundled-gems.spec, dist/setup-appliance.sh, dist/t/Gemfile.lock, src/api/Gemfile.lock
Also bring back the test for the rake version and make sure the correct alternative is set on the appliance
=> Downgrade rake to 13.0.1

src/api/app/views/webui/users/tokens/new.html.haml
=> Broken token type selection in Token create webui

dist/t/Makefile
It's easier to keep things up to date in one place...
=> Move setup/test tasks from openQA test suite here

src/api/config/initializers/airbrake.rb
So far we have instrumentation for exceptions that happen in ActionController.
There are many more exceptions occuring outside of this component as you can
see on errbit. Let's instrument those too.
=> Instrument more exceptions

dist/obs-server.spec, src/backend/Makefile, src/backend/t/0015-BSSched-EventSource-Directory.t
This package is required to ensure that obs-server and test cases fit together while testing the appliance
=> Fix backend tests

src/backend/bs_worker, src/backend/t/1000-bs_worker.t
=> Add builder, invocation and metadata to provenance file

src/backend/bs_publish
Use --discard-additional-metadata only together with --update, it has no
effect otherwise
=> [backend] avoid warnings from createrepo

src/backend/bs_worker, src/backend/t/1000-bs_worker.t
And delete the digest for now as nobody can use it.
=> [backend] slsa: also map uri in the configSource

ReleaseNotes-2.10.15
~DO NOT MERGE: Depends on https://github.com/openSUSE/open-build-service/pull/12530~
=> Add release notes for 2.10.15

dist/obsscheduler, src/backend/bs_admin
We also accept an optional wait timeout. If the timeout is
reached, bs_admin exits with status 2.
=> [backend] add bs_admin --shutdown-all-schedulers option

.obs/workflows.yml
We switchted to SP4 last week.
=> Let's test the OS that we deploy on

src/api/app/models/event/base.rb
As some users might not understand the concept of "relationship", I propose to add some descriptions to the relationship events.
=> Add description for relationship events

src/api/app/components/notification_filter_component.html.haml, src/api/app/components/notification_filter_component.rb, src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/queries/notifications_finder.rb
=> Add notification filters for Relationship records

src/api/app/jobs/measurements_job.rb
Some interesting numbers about our event subscriptions.
=> Measure EventSubscription count

dist/obsworker, dist/sysconfig.obs-server, src/backend/bs_worker
Supporting qemu:$arch as VM_TYPE
=> [backend] Add support for qemu system emulated builds via bs_worker

src/api/db/schema.rb
Make the charset explicit. utf8 is an alias for utf8mb3.
See https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html and https://mariadb.com/kb/en/unicode/
=> Update table schema

src/api/app/models/issue_tracker.rb
Due to https://github.com/openSUSE/open-build-service/pull/11351.
=> Update Issues model table schema comments

src/backend/BSConSign.pm, src/backend/BSPublisher/Container.pm, src/backend/BSPublisher/Registry.pm, src/backend/BSRPC.pm, src/backend/bs_regpush
We do one "bs_regpush -l" call to get the complete state of a repository on a registry. We then only call bs_regpush for the containers that need to be uploaded.
=> [backend] Speed up container publishing

src/backend/BSPublisher/Container.pm
Reduce logging, print time spent in repo query, make messages
more consistent.
=> [backend] polish container pushing a bit

src/api/app/jobs/accept_requests_job.rb
This job is not used in the codebase in any place.
=> Remove not used AcceptRequestsJob job definition

src/api/app/controllers/webui/webui_controller.rb
=> Fix rendering not found package for AJAX requests

src/api/app/models/attrib.rb
This was changed wrongly in 525a2aca10fce3ddfe41854b02f0d137e3c47102.
=> Fix names of validation methods in model Attrib

src/api/.rubocop_todo.yml, src/api/app/models/bs_request_action.rb, src/api/app/models/bs_request_action/errors.rb
Giving the user a hint which package is actually causing the issue of a lacking target
=> [api] improve error message

.circleci/conditional_config.yml, .circleci/config.yml
If the PR does not change the bundle, there is no need to check
for a rake/rack mismatch in CI.
=> Run rake/rack tests only if the bundle changes

src/api/app/models/user.rb
=> Workaround after_destroy_commit loosing Thread variables

src/api/app/models/user.rb
Reverts openSUSE/open-build-service#12798
=> Revert "Workaround after_destroy_commit loosing Thread variables"

docs/api/api/api.txt, src/api/app/controllers/person_controller.rb, src/api/public/apidocs-new/paths/person.yaml, src/api/test/functional/person_controller_test.rb
also adding the route to api docu at all
=> [api] support listing of confirmed users only

src/api/config/initializers/airbrake.rb
No need to track this, it's a broken client.
Fixes #12814
=> Ignore ActionDispatch::Http::MimeNegotiation::InvalidType

src/api/app/helpers/maintenance_helper.rb, src/api/app/models/project.rb
=> Some more URL escape fun

src/api/config/initializers/flipper.rb
We want customers to test this, so it's added to the beta program as explained in our developer wiki:
https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles#you-want-customers-to-test-your-feature
I also added the feature toggle to our developer wiki in the [Feature Toggles Planning](https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles#feature-toggles-planning) table.
Preview of the changes in the UI:
=> Add feature toggle "request_show_redesign"

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_build_results.html.haml, src/api/app/views/webui/request/beta_show_tabs/_changes.html.haml, src/api/app/views/webui/request/beta_show_tabs/_mentioned_issues.html.haml, src/api/app/views/webui/request/beta_show_tabs/_overview.html.haml, src/api/config/routes/webui_routes.rb
=> Create skeleton for the request show page redesign

ReleaseNotes-2.10.17
Regarding https://github.com/openSUSE/open-build-service/pull/12846
=> Add tzinfo update to 2.10.17 release notes

src/api/app/controllers/webui/request_controller.rb
Also move searching for the request to the beginning of the method, to fail fast and first in case that the request is not found.
See this thread of comments: https://github.com/openSUSE/open-build-service/pull/12844#discussion_r926929787
=> Clarify how exceptions are caught in request#add_review

src/api/app/controllers/concerns/webui/rescue_handler.rb, src/api/app/controllers/source/errors.rb, src/api/app/controllers/source_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/packages/files_controller.rb, src/api/app/models/package.rb, src/api/app/models/package/errors.rb, src/api/app/models/service.rb, src/api/app/views/webui/package/_files_view.html.haml, src/api/app/views/webui/package/_side_links.html.haml, src/api/app/views/webui/package/side_links/_show_scmsync.html.haml
They are maintained on the SCM...
=> Can not store files in SCM bridged packages

src/backend/BSXML.pm
properly reflect API changes in /person data for new watchlist
=> [backend] BSXML.pm update person structure for new watchlist features

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/beta_show.html.haml
There is no change in their design, since actions are the same across the application.
Preview of the changes:
=> Add actions to request show redesign

src/api/app/assets/javascripts/webui/request.js, src/api/app/components/sourcediff_component.html.haml, src/api/app/components/sourcediff_component.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_changes.html.haml, src/api/app/views/webui/request/request_action_changes.js.erb, src/api/config/brakeman.ignore, src/api/config/routes/webui_routes.rb, src/api/spec/cassettes/SourcediffComponent/with_a_request_with_a_submit_action/renders_the_diff.yml, src/api/spec/components/previews/sourcediff_component_preview.rb, src/api/spec/components/sourcediff_component_spec.rb
=> Introduce Changes tab for requests show redesign

src/api/config/environments/development.rb
To the classes we use in associations
=> Limit the classes we eager load in development

README.md
=> Clarify possible confusion about the docker-compose setup

.circleci/conditional_config.yml, src/api/lib/tasks/dev.rake
Make sure we can boot the app in production.
=> Load the app in production

src/api/app/components/bs_request_history_element_component.html.haml
=> Fix history alignment

src/api/app/views/webui/request/beta_show.html.haml
Add info about request source and target packages and also a sentence about release if there is any.
For now, all of this is displayed in the Overview tab of the redesigned request show page.
**Before redesign:**
**After redesign:**
=> Add info about request source and target packages

src/api/app/components/bs_request_activity_timeline_component.html.haml, src/api/app/components/bs_request_history_element_component.html.haml
Fixes #12917
Those changes should have been included in #12908.
=> Use the correct route in view components for request_show_redesign

src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_build_results.html.haml, src/api/app/views/webui/request/beta_show_tabs/_mentioned_issues.html.haml
Preview:
Message at the top of the page + Build Results:
Mentioned Issues:
=> Mention limitations of the request show redesign

src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml
=> Rename Overview tab to Conversation

src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/request_show_redesign/add_review.js, src/api/app/assets/stylesheets/request_show_redesign/add_review.scss, src/api/app/assets/stylesheets/webui/application.scss, src/api/app/components/add_review_collapsible_component.html.haml, src/api/app/components/add_review_collapsible_component.rb, src/api/app/components/add_review_dropdown_component.html.haml, src/api/app/components/add_review_dropdown_component.rb, src/api/app/components/request_decision_component.html.haml, src/api/app/components/request_decision_component.rb, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml
=> Add review functionality to request beta show view

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/beta_show.html.haml
Signed-off-by: Rubhan Azeem <rubhanazeem@gmail.com>
=> Display "Changes" tab only for requests with changes

src/api/app/components/bs_request_overview_avatars_component.html.haml, src/api/app/components/bs_request_overview_avatars_component.rb
=> Display count of hidden avatars when listing reviewers

src/api/app/views/webui/request/beta_show.html.haml, src/api/config/initializers/flipper.rb
It's now part of the beta program again.
=> Enable back the request_show_redesign feature toggle

src/api/app/views/layouts/webui/_places.html.haml, src/api/test/functional/webui/spider_test.rb
=> Fix the flipper link

src/api/app/components/status_message_component.html.haml, src/api/app/controllers/webui/status_messages_controller.rb, src/api/app/policies/webui/status_message_policy.rb, src/api/app/views/webui/status_messages/edit.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/policies/webui/status_message_policy_spec.rb
Just got tired of going in the Rails console... :smile:
Previews:
=> Edit status messages in the web UI

dist/obs-server.spec, docs/api/api/api.txt, src/api/app/controllers/application_controller.rb, src/api/app/controllers/build_controller.rb, src/api/app/controllers/public_controller.rb, src/api/app/controllers/source_controller.rb, src/api/config/routes/api_routes.rb, src/backend/BSSrcServer/SQLite.pm, src/backend/BSSrcServer/ScmsyncDB.pm, src/backend/bs_srcserver
Allowing to trigger source updates based on scmsync URL's
Provide build results based on scmsync URL's
The api is just validating a correct configured shared cookie.
It might get bypassed later on when git server gets integrated
into the infrastructure. therefore the api docu is commented out.
=> [backend][api] scmsync tracking interfaces

src/api/app/views/webui/main/_latest_updates.html.haml, src/api/app/views/webui/main/index.html.haml, src/api/app/views/webui/package/_commit_item.html.haml, src/api/app/views/webui/package/_files_view.html.haml, src/api/app/views/webui/package/revisions.html.haml, src/api/app/views/webui/project/_form.html.haml, src/api/app/views/webui/project/_monitor_control.html.haml, src/api/app/views/webui/project/monitor.html.haml, src/api/app/views/webui/project/new.html.haml, src/api/app/views/webui/project/show_actions/_request_to_release.html.haml, src/api/app/views/webui/projects/pulse/_pulse_list_requests.html.haml, src/api/app/views/webui/shared/user_or_groups_roles/_index.html.haml
This is fixing some of the offenses which were disabled in #12977. More will be fixed in following PRs.
=> Fix offenses for haml-lint InstanceVariables check

src/api/app/components/sourcediff_component.html.haml, src/api/app/components/sourcediff_component.rb, src/api/app/components/sourcediff_tab_component.html.haml, src/api/app/components/sourcediff_tab_component.rb, src/api/app/views/layouts/webui/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/_bottom_navigation_collapse.html.haml, src/api/app/views/layouts/webui/_footer.html.haml, src/api/app/views/layouts/webui/_left_navigation.html.haml, src/api/app/views/layouts/webui/_left_navigation_nobody.html.haml, src/api/app/views/layouts/webui/_places.html.haml, src/api/app/views/layouts/webui/webui.html.haml, src/api/app/views/webui/kiwi/images/_preferences.html.haml, src/api/app/views/webui/kiwi/images/_preferences_form.html.haml, src/api/app/views/webui/kiwi/images/_profiles.html.haml, src/api/app/views/webui/kiwi/images/edit.html.haml, src/api/app/views/webui/package/_live_build_log_controls.html.haml, src/api/app/views/webui/package/_revision_diff_detail.html.haml, src/api/app/views/webui/package/live_build_log.html.haml, src/api/app/views/webui/package/rdiff.html.haml, src/api/app/views/webui/request/request_action.js.erb, src/api/app/views/webui/request/request_action_changes.js.erb
Please have a look at every commit to easily distinguish the changes from each other.
=> Address haml-lint's InstanceVariables check in partials and view components

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/channel/channel.yaml, src/api/public/apidocs-new/components/schemas/channel/collection.yaml, src/api/public/apidocs-new/paths/search_channel.yaml, src/api/public/apidocs-new/paths/search_channel_binary.yaml, src/api/public/apidocs-new/paths/search_channel_binary_id.yaml
=> Document search channel endpoints

src/api/app/models/concerns/staging_project.rb, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
The release-tools do this to avoid some race that might occur.
https://github.com/openSUSE/openSUSE-release-tools/commit/a354d6c88206a708014d68ef46f02e238a36d4e3
=> Enable to 'force' acceptable staging projects

dist/obsstoragesetup
where the file exists already but has 0 bytes
=> also try to get authorized_keys file in the special case

src/api/config/initializers/wrap_parameters.rb
This reverts commit 00631e2f737e6e3e334957c61eb646d81a5bc536.
Fixes #13018.
=> Revert "Configure parameter parsers with ActionDispatch::Request.parameter_parsers="

.github/workflows/scorecards.yml
Scans for software security best practices.
https://github.com/ossf/scorecard & https://securityscorecards.dev/
=> Add ossf-scorecard action

src/api/app/services/scm_exception_handler.rb, src/api/app/services/scm_exception_message.rb
=> Add Gitlab exception message for BadGateway

src/api/lib/tasks/dev.rake, src/api/lib/tasks/multiple_actions_request.rake
=> Add rake task to create a request with multiple actions

src/api/app/views/webui/request/beta_show.html.haml
Multi action requests are now supported.
=> Adapt message about request workflow redesing beta on request#show

src/api/app/models/bs_request_action.rb
=> Check presence of package or source_rev

src/api/app/controllers/webui/comments_controller.rb, src/api/spec/controllers/webui/comments_controller_spec.rb
Recover from errors when commenting on a request. 
We were recovering from errors by redirecting the flow to the main page, as we do with non-AJAX flows. Now we just show the error details on the comment box, if there are any.
Here you can see how the commenting box behaves when there is an error:
Fixes #10630
=> Recover from errors when commenting on a BsRequest

dist/obsworker, src/api/app/controllers/application_controller.rb, src/api/app/lib/backend/connection.rb, src/api/config/options.yml.example
* enable SSL when https scheme is specified
* Allow to disable cert verification in options.yml
belongs to OBS-210
=> [api] fix access to backend via SSL

src/api/app/components/workflow_run_filter_component.html.haml, src/api/app/views/webui/distributions/new.html.haml
This warning started to appear after #13131 was merged.
=> Fix Layout/MultilineHashBraceLayout haml_lint warnings

src/api/app/controllers/concerns/webui/rescue_handler.rb
=> Render expects a full file name

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/source/projects.yaml, src/api/public/apidocs-new/paths/source.yaml
Document OpenAPI specifications for `/source` to get the list of projects or the list of deleted projects
=> OpenAPI specifications for get source

src/api/app/controllers/webui/distributions_controller.rb
Local distributions should have precendence over remote ones
=> Sort remote Distributions last

src/backend/BSPublisher/Container.pm
Too much refactoring, too little time...
=> [backend] bs_publish: fix typo in cosign args generation

src/backend/bs_publish
=> [backend] create output dir before reconstruct_container - backport

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/source/project_files.yaml, src/api/public/apidocs-new/paths/source_project_name_project.yaml
API specifications for `GET 'source/:project/_project'`
=> OpenAPI specifications to list project files

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/source/attributes.yaml, src/api/public/apidocs-new/paths/source_project_name_attribute_name.yaml
Specifications for `GET,POST,DELETE source/:project/_attribute/(:attribute) `
=> OpenAPI specifications for project's attributes

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name.yaml
Specifications for ` DELETE source/:project`
=> OpenAPI specifications to delete project

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_pubkey.yaml
Specifications for `GET,DELETE 'source/:project/_pubkey'`
=> OpenAPI specification to read and delete pubkey

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/source/project_pattern.yaml, src/api/public/apidocs-new/paths/source_project_name_pattern.yaml
API specifications for `GET 'source/:project/_pattern'`
=> OpenAPI specifications to list patterns of a project

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_config.yaml
Specifications for `GET,PUT source/:project/_config`
=> OpenAPI specifications for source project config

src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml
Bugfix for https://github.com/openSUSE/open-build-service/pull/13226#issuecomment-1282536696
=> Let the 'ask for a review' button be visible always

src/api/app/components/sourcediff_component.html.haml, src/api/app/components/sourcediff_tab_component.html.haml, src/api/app/helpers/application_helper.rb, src/api/app/views/webui/package/_revision_diff_detail.html.haml, src/api/app/views/webui/request/beta_show.html.haml
Tab selection and diff URL for multi-action requests were not working fine. This PR makes the diff URL unique for multi-action requests.
=> Generalize tab selection and diff URL for multi action request

src/api/app/models/bs_request.rb, src/api/app/models/event/comment_for_request.rb, src/api/app/models/event/request.rb
Event::Request is the only consumer...
=> Move BsRequest.actions_summary to Event::Request

src/api/app/policies/token_policy.rb, src/api/spec/components/token_card_component_spec.rb, src/api/spec/policies/token_policy_spec.rb
=> Don't allow unconfirmed users to trigger tokens through webui

src/backend/bs_regpush
The OCI API standard defines this method and newer registry versions implement it.
=> [backend] bs_regpush: try to directly delete tags

src/api/app/models/product.rb
=> Make `expand` boolean, in `GET /source/<project>` API endpoint

src/api/app/views/webui/projects/pulse/_pulse_list.html.haml
Rubocop started to complain about Style/RedundantEach.
=> Remove redundant `each` from _pulse_list.html.haml

src/api/public/apidocs-new/paths/source_project_name_cmd_copy.yaml
This is a follow up to #13296.
=> Document resign parameter for `POST /source/{project_name}?cmd=copy`

src/api/lib/tasks/dev/lint.rake
Sometimes it's helpful to check JavaScript only.
=> Add task for JavaScript linter separately

src/backend/BSSched/EventHandler.pm, src/backend/BSSched/Lookat.pm, src/backend/BSSrcServer/Remote.pm, src/backend/bs_sched
We only delayed med type elements before. Some projects generate a lot of high events over time, which led to the med event delay mechanism no longer being effective.
=> [backend] support delaying of lookat elements of type high

src/api/app/models/event_subscription.rb, src/api/app/models/workflow_run.rb
I realized this was missing when I looked at #13377.
=> Add event_subscriptions association in WorkflowRun

src/api/app/assets/stylesheets/webui/collapsible-text.scss, src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_mentioned_issues.html.haml
Preview with zero mentioned issues:
Preview with some mentioned issues:
=> List mentioned issues in the request show redesign

src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/request_show_redesign/rpm_lint_results.js, src/api/app/assets/stylesheets/webui/build-results.scss, src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_rpm_lint.html.haml, src/api/app/views/webui/request/beta_show_tabs/_rpm_lint_result.html.haml
=> Fill RPM lint tab

src/api/app/controllers/webui/request_controller.rb, src/api/spec/cassettes/Bootstrap_Requests/for_a_request_with_a_deleted_target_project/does_not_show_the_project_maintainers.yml, src/api/spec/features/webui/requests_spec.rb
=> Do not try fetching the project maintainers for a deleted project

docker-compose.yml
This changed in https://build.opensuse.org/request/show/1035893
=> Fix path of memcached binary

src/api/app/components/notification_action_description_component.rb, src/api/app/helpers/event_mailer_helper.rb, src/api/app/views/event_mailer/relationship_create.html.haml, src/api/app/views/event_mailer/relationship_create.text.erb, src/api/app/views/event_mailer/relationship_delete.html.haml, src/api/app/views/event_mailer/relationship_delete.text.erb, src/api/spec/components/notification_action_description_component_spec.rb, src/api/spec/factories/notification.rb, src/api/spec/mailers/event_mailer_spec.rb
=> Specify the group which is concerned by an event in notifications/emails

src/api/app/views/webui/package/_deps.html.haml, src/backend/BSXML.pm, src/backend/bs_repserver
This reverts commit 3939c0d1395059204b483bbd370183bfe2b6afa4.
=> Revert "Display file list in the binary view"

src/api/test/functional/product_test.rb, src/api/test/unit/product_test.rb
Partially fixes and related to #13464.
=> Fix minitest class name

docs/api/api/constraints.rng, src/backend/BSDispatcher/Constraints.pm, src/backend/BSXML.pm, src/backend/testdata/constraint/sandbox_xen, src/backend/testdata/constraintprj/enforce_secure, src/backend/testdata/test_dispatcher
We may have a definition in prjconf and in the packge. Usually they conflict, but if one of them is the "secure" one and may also be good with a package level constraint for sandbox.
=> [backend] support multiple sandbox constraints

src/api/app/assets/javascripts/webui/request.js
=> Move the viewport back to lists of comments once the diffs are loaded

src/api/.rubocop_todo.yml, src/api/app/controllers/webui/users/tokens_controller.rb, src/api/app/models/token.rb, src/api/app/models/token/rebuild.rb, src/api/app/models/token/release.rb, src/api/app/models/token/rss.rb, src/api/app/models/token/service.rb, src/api/app/models/token/workflow.rb, src/api/app/services/workflows/yaml_downloader.rb, src/api/app/services/workflows/yaml_to_workflows_service.rb, src/api/app/views/webui/users/tokens/_update.js.erb, src/api/app/views/webui/users/tokens/edit.html.haml, src/api/app/views/webui/users/tokens/new.html.haml, src/api/app/views/webui/users/tokens/show.html.haml, src/api/db/migrate/20221208125517_add_workflow_configuration_path_to_tokens.rb, src/api/db/schema.rb
Add a field in the token form to configure a custom path for the workflows configuration file.
Make sure you have enabled the `trigger_workflow` feature flag.
=> Configure workflows file path in the token

src/backend/bs_worker
It works on a x86-64-v4 build host :)
=> [backend] x86-64-v4 found and validated

src/api/app/instrumentations/workflow_instrumentation.rb, src/api/app/models/token/workflow.rb
This allow us to know how often this setting is used to provide a different value than the default.
=> Instrument workflow configuration path

src/api/app/instrumentations/workflow_placeholder_variables_instrumentation.rb, src/api/app/services/workflows/yaml_to_workflows_service.rb
With those metrics, I will create panels in our [monitoring](https://obs-measure.opensuse.org/d/GRaKLnm7k/scm-ci-integration?orgId=1).
=> Instrument workflow placeholder variables

src/api/app/components/workflow_run_detail_component.html.haml, src/api/spec/components/workflow_run_detail_component_spec.rb
Fix https://trello.com/c/tFUkVvrt
=> Hide empty blocks if content value is empty

src/api/.jshintrc, src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/badge.js, src/api/app/views/webui/package/_side_links.html.haml, src/api/app/views/webui/package/side_links/_create_badge.html.haml, src/api/spec/cassettes/Bootstrap_Requests_Submissions/submit_package/not_setting_a_target_package/creates_a_BsRequest_with_the_source_package_name.yml, src/api/spec/cassettes/Bootstrap_Requests_Submissions/submit_package/setting_a_target_package/creates_a_BsRequest_with_target_package_name.yml, src/api/spec/cassettes/Packages/Viewing_a_package_that/has_derived_packages.yml, src/api/spec/cassettes/Packages/adding_a_valid_file.yml, src/api/spec/cassettes/Packages/behaves_like_bootstrap_user_tab/group_roles/Add_role_to_group.yml, src/api/spec/cassettes/Packages/behaves_like_bootstrap_user_tab/group_roles/Remove_role_from_group.yml, src/api/spec/cassettes/Packages/behaves_like_bootstrap_user_tab/user_roles/Add_role_to_user.yml, src/api/spec/cassettes/Packages/behaves_like_bootstrap_user_tab/user_roles/Remove_role_from_user.yml, src/api/spec/cassettes/Packages/branching_a_package_from_another_users_project/with_AutoCleanup.yml, src/api/spec/cassettes/Packages/branching_a_package_from_another_users_project/without_AutoCleanup.yml, src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml, src/api/spec/cassettes/Packages/triggering_package_rebuild/via_binaries_view.yml
This is a companion PR to #13169, it's based on it, but I want this PR to be just about the selector.
=> Add a badge selector

src/api/app/controllers/webui/users/tokens_controller.rb, src/api/app/instrumentations/workflow_instrumentation.rb, src/api/app/models/token.rb, src/api/app/models/token/rebuild.rb, src/api/app/models/token/release.rb, src/api/app/models/token/rss.rb, src/api/app/models/token/service.rb, src/api/app/models/token/workflow.rb, src/api/app/services/workflows/yaml_downloader.rb, src/api/app/views/webui/users/tokens/_update.js.erb, src/api/app/views/webui/users/tokens/edit.html.haml, src/api/app/views/webui/users/tokens/new.html.haml, src/api/app/views/webui/users/tokens/show.html.haml, src/api/config/brakeman.ignore, src/api/db/migrate/20221216234231_add_workflow_configuration_url_to_tokens.rb, src/api/db/schema.rb, src/api/spec/models/token/workflow_spec.rb, src/api/spec/services/workflows/yaml_downloader_spec.rb
From now on, the workflows configuration file doesn't need to be inside the repository. We can specify any other accessible URL.
=> Take workflow configuration file from external URL

.github/workflows/brakeman.yml, src/api/app/models/cloud/azure/configuration.rb, src/api/config/brakeman.ignore, src/api/docker-files/Dockerfile
=> Update brakeman to 5.4.0

src/api/app/components/status_message_component.html.haml, src/api/app/helpers/webui/main_helper.rb
It makes the helper a tiny bit simpler.
=> Pass severity directly to icon helper

src/api/app/components/watchlist_component.rb, src/api/app/components/watchlist_icon_component.html.haml, src/api/app/components/watchlist_icon_component.rb, src/api/app/views/layouts/webui/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/_top_navigation.html.haml, src/api/app/views/webui/package/_basic_info.html.haml, src/api/app/views/webui/project/_basic_info.html.haml, src/api/app/views/webui/request/_show_overview.html.haml, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/watched_items/toggle_watched_item.js.erb, src/api/spec/components/previews/watchlist_icon_component_preview.rb, src/api/spec/components/watchlist_icon_component_spec.rb, src/api/spec/features/webui/projects_spec.rb
To make it easier to add a project/package/request to the watchlist, we offer an icon next to its title.
Replace bookmark icon with eye icon for watchlist:
When the item is not on the watchlist yet:
When the item is already on the watchlist:
=> Add item to watchlist from show view

src/api/.rubocop_todo.yml, src/api/app/controllers/source_project_controller.rb
There was a missing handling discovered in
https://github.com/openSUSE/osc/issues/1197
=> [api] support listing of deleted packages for remote projects

docs/api/api/link.rng, docs/api/api/link.xml
=> Fix cicount schema and add documentation to link.rng

src/api/app/controllers/webui/packages/files_controller.rb, src/api/app/views/webui/package/view_file.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/cassettes/Webui_Packages_FilesController/POST_update/as_ajax_request/modifies_an_existing_file/1_2_1_1_1.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_update/as_ajax_request/modifies_an_existing_file/1_2_1_1_2.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_update/as_ajax_request/modifies_an_existing_file/1_2_1_1_3.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_update/as_non-ajax_request/modifies_an_existing_file/1_2_2_1_1.yml, src/api/spec/controllers/webui/packages/files_controller_spec.rb, src/api/spec/features/webui/packages_spec.rb
This is splitting up #13281 into smaller PRs, this one makes the view_file view use update method instead of create method
=> Move modifying files to an update method

src/api/app/models/badge.rb, src/api/config/routes/webui_routes.rb, src/api/spec/models/badge_spec.rb
States that aren't succeeded or failed don't really factor into the final badge anyway
Fixes #13582
=> Filter out the irrelevant states in the badge

src/api/app/assets/stylesheets/webui/bs5-shims.scss, src/api/app/assets/stylesheets/webui/collapsible-text.scss, src/api/app/components/bs_request_comment_component.html.haml, src/api/app/components/sourcediff_component.html.haml, src/api/app/components/sourcediff_tab_component.html.haml, src/api/app/components/status_message_component.html.haml, src/api/app/views/webui/groups/_group_members.html.haml, src/api/app/views/webui/main/_latest_updates.html.haml, src/api/app/views/webui/main/_status_messages.html.haml, src/api/app/views/webui/monitor/_building.html.haml, src/api/app/views/webui/monitor/_workers_table.html.haml, src/api/app/views/webui/package/_commit_item.html.haml, src/api/app/views/webui/package/rdiff.html.haml, src/api/app/views/webui/project/_monitor_control.html.haml, src/api/app/views/webui/projects/pulse/show.html.haml, src/api/app/views/webui/request/_action_text.html.haml, src/api/app/views/webui/request/_actions_details.html.haml, src/api/app/views/webui/request/beta_show_tabs/_build_status.html.haml, src/api/app/views/webui/search/_results_owner.html.haml, src/api/app/views/webui/shared/_buildresult_box.html.haml, src/api/app/views/webui/user/_edit_dialog.html.haml, src/api/app/views/webui/users/notifications/index.html.haml, src/api/app/views/webui/users/tokens/edit.html.haml, src/api/app/views/webui/workflow_runs/index.html.haml
This is a part of https://github.com/openSUSE/open-build-service/pull/13602, updating float classes
=> Float shim for bootstrap 5 migration

src/api/app/assets/stylesheets/webui/bs5-shims.scss, src/api/app/components/build_result_for_architecture_component.html.haml, src/api/app/views/webui/image_templates/index.html.haml, src/api/app/views/webui/monitor/_workers_table.html.haml, src/api/app/views/webui/monitor/index.html.haml, src/api/app/views/webui/project/keys_and_certificates.html.haml, src/api/app/views/webui/repositories/_dod_repository_card_content.html.haml, src/api/app/views/webui/repositories/_repository_entry.html.haml, src/api/app/views/webui/request/_action_text.html.haml, src/api/app/views/webui/staging/projects/_broken_packages.html.haml, src/api/app/views/webui/staging/projects/_checks.html.haml, src/api/app/views/webui/staging/projects/_status_items.html.haml, src/api/app/views/webui/users/tokens/show.html.haml
This is a part of https://github.com/openSUSE/open-build-service/pull/13602, updating font-weight classes with fw
=> Font-weight shim for bootstrap 5 migration

src/api/app/views/webui/attribute/_issue_fields.html.haml, src/api/app/views/webui/attribute/_value_fields.html.haml, src/api/app/views/webui/attribute/new.html.haml, src/api/app/views/webui/monitor/_events.html.haml, src/api/app/views/webui/patchinfo/form/_binaries.html.haml, src/api/app/views/webui/search/owner.html.haml, src/api/app/views/webui/users/token_triggers/show.html.haml, src/api/app/views/webui/users/tokens/edit.html.haml, src/api/app/views/webui/users/tokens/new.html.haml, src/api/app/views/webui/users/tokens/show.html.haml
https://getbootstrap.com/docs/5.0/migration/#forms
=> Replace form-row with row for bootstrap 5 migration

src/api/app/assets/stylesheets/webui/bs5-shims.scss
I missed a character and the style wasn't applied correctly, this should fix the issue
=> Correct the badge shim

src/api/app/assets/stylesheets/webui/bs5-shims.scss, src/api/app/views/layouts/webui/_bottom_navigation.html.haml
This is a part of https://github.com/openSUSE/open-build-service/pull/13602, updating border classes
=> Border shim for bootstrap 5 migration

src/api/app/controllers/webui/package_controller.rb, src/api/app/helpers/webui/package_helper.rb, src/api/app/helpers/webui/packages/binaries_helper.rb, src/api/spec/helpers/webui/package_helper_spec.rb, src/api/spec/helpers/webui/packages/binaries_helper_spec.rb
A part of #13564, to make this a bit easier to review
=> Move binary methods to its own helper

src/api/app/views/webui/workflow_runs/index.html.haml
This class doesn't really make sense to be there
=> Remove accordion class from workflow_runs

src/api/app/components/fuzzy_time_component.html.haml, src/api/app/components/fuzzy_time_component.rb, src/api/app/helpers/webui/maintenance_incident_helper.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui/main/_latest_updates.html.haml, src/api/app/views/webui/package/_commit_item.html.haml, src/api/app/views/webui/package/_fileinfo.html.haml, src/api/app/views/webui/package/_revision_diff_footer.html.haml, src/api/app/views/webui/projects/pulse/_pulse_list_entry.html.haml, src/api/app/views/webui/projects/pulse/_pulse_list_requests.html.haml, src/api/app/views/webui/request/_show_side_links.html.haml, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/shared/bs_requests/index.json.erb, src/api/spec/components/fuzzy_time_component_spec.rb, src/api/spec/components/previews/fuzzy_time_component_preview.rb
Introduce a view component to deal with displaying date/time
=> Introduce FuzzyTime as component

src/api/app/assets/stylesheets/webui/comments.scss, src/api/app/assets/stylesheets/webui/requests.scss, src/api/app/views/webui/comment/_content.html.haml, src/api/app/views/webui/patchinfo/show.html.haml, src/api/app/views/webui/request/_request_history.html.haml, src/api/app/views/webui/request/_request_history_element.html.haml, src/api/spec/features/webui/comments_spec.rb, src/api/spec/features/webui/requests_spec.rb
Removes media component entirely from the application
=> Remove the media component for bootstrap 5 migration

src/api/app/components/status_message_component.html.haml, src/api/app/views/layouts/webui/_status_message_announcement.html.haml, src/api/app/views/webui/configuration/_tabs.html.haml, src/api/app/views/webui/main/_status_messages.html.haml, src/api/app/views/webui/status_messages/edit.html.haml, src/api/app/views/webui/status_messages/index.html.haml, src/api/app/views/webui/status_messages/new.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/status_messages_controller_spec.rb
Part of #13574
Before:
```
$ bundle exec rails routes --controller=Webui::StatusMessagesController
Prefix Verb   URI Pattern                         Controller#Action
preview_status_messages POST   /status_messages/preview(.:format)  webui/status_messages#preview
status_messages GET    /status_messages(.:format)          webui/status_messages#index
POST   /status_messages(.:format)          webui/status_messages#create
new_status_message GET    /status_messages/new(.:format)      webui/status_messages#new
edit_status_message GET    /status_messages/:id/edit(.:format) webui/status_messages#edit
status_message PATCH  /status_messages/:id(.:format)      webui/status_messages#update
PUT    /status_messages/:id(.:format)      webui/status_messages#update
DELETE /status_messages/:id(.:format) …
```
=> Rename web UI routes for status messages to news items

src/api/config/initializers/airbrake.rb
=> Ignore errors, based on their message, for which we cannot do anything 

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/source/product_list.yaml, src/api/public/apidocs-new/components/schemas/source/project_packages.yaml, src/api/public/apidocs-new/components/schemas/source/verbose_product_list.yaml, src/api/public/apidocs-new/paths/source_project_name.yaml
Link for reviewers in the review-app: https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newdocument_source_project/apidocs-new/index.html#/Sources%20-%20Packages/get_source__project_name_
=> Document GET /source/{project_name} endpoint with OpenAPI

src/api/lib/tasks/dev.rake, src/api/lib/tasks/dev/news.rake, src/api/lib/tasks/dev/notifications.rake, src/api/lib/tasks/dev/requests.rake, src/api/lib/tasks/dev/staging.rake, src/api/lib/tasks/dev/workflows.rake
In some of our development rake tasks we have several checks to ensure we only run those tasks against a development environment.
This PR DRY's that.
=> Refactor environment check

src/api/app/views/webui/request/_action_text.html.haml, src/api/app/views/webui/request/_actions_details.html.haml
For reviewers, see https://obs-reviewlab.opensuse.org/dmarcoux-request-multiple-actions-hint/request/show/9
Before:
After:
=> Improve UX of new request#show

src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml
|Before|After|
|:---|:---|
|![Screenshot from 2023-01-16 10-12-57](https://user-images.githubusercontent.com/114928900/212640979-91c07ba6-c433-4972-995f-7b39386a4026.png)|![Screenshot from 2023-01-16 10-13-39](https://user-images.githubusercontent.com/114928900/212640984-557f1ddf-fc02-4194-925f-6c7c8b65f373.png)|
=> Align request timeline with the comment card

src/api/app/views/webui/request/beta_show.html.haml
|Before|After|
|:---|:---|
|![Screenshot from 2023-01-16 10-22-19](https://user-images.githubusercontent.com/114928900/212642753-b3bcd41a-36ee-4d87-9aef-e1ae21ebee83.png)|![Screenshot from 2023-01-16 10-22-08](https://user-images.githubusercontent.com/114928900/212642748-c608f5f2-f183-48db-947e-fa69922cc1a3.png)|
=> Colour the superseded by links in a badge correctly

src/api/app/models/review.rb
Fixes #13706, makes sure that project exists before checking for staging project
=> Make sure project exists when checking if it's staging

src/api/app/services/diff_parser.rb, src/api/spec/services/diff_parser_spec.rb
=> Fix loop over diff content

src/api/app/assets/stylesheets/webui/accordion-reviews-component.scss, src/api/app/assets/stylesheets/webui/application.scss, src/api/app/components/accordion_reviews_component.html.haml, src/api/app/components/accordion_reviews_component.rb, src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml, src/api/spec/components/previews/accordion_reviews_component_preview.rb
=> Show reviews summary to help users take a decision on a request

src/api/app/components/notification_component.html.haml, src/api/app/components/notification_component.rb, src/api/app/views/webui/users/notifications/_notifications_list.html.haml, src/api/lib/rubocop/cop/view_component/avoid_global_state.rb, src/api/spec/lib/rubocop/cop/view_component/avoid_global_state_spec.rb
Offense messages are also now more descriptive.
=> Run ViewComponent::AvoidGlobalState in view component templates

src/api/app/policies/group_policy.rb, src/api/app/views/webui/groups/_group_members.html.haml, src/api/spec/policies/group_policy_spec.rb
This facilitates collaboration.
Preview:
=> Display group email to logged-in users

src/api/app/views/webui/request/_action_text.html.haml, src/api/app/views/webui/request/_actions_details.html.haml
[Screencast from 2023-01-24 12-34-20.webm](https://user-images.githubusercontent.com/114928900/214281509-171e3a43-8ada-42e8-990a-5742ef8828cf.webm)
=> Make the action header in the action selection dropdown sticky

src/api/app/components/workflow_run_filter_component.html.haml, src/api/app/components/workflow_run_filter_link_component.rb, src/api/app/views/webui/workflow_runs/index.html.haml, src/api/spec/components/workflow_run_filter_link_component_spec.rb
This is intended to fix #13790
|Before|After|
|:---|:---|
|![Screenshot from 2023-02-02 14-35-23](https://user-images.githubusercontent.com/114928900/216339502-004eb5da-ef1c-48ea-ab76-3df56fb137b6.png)|![Screenshot from 2023-02-02 14-34-08](https://user-images.githubusercontent.com/114928900/216339494-ab5decb8-a01d-41bd-909d-a4ae69145097.png)|
=> Improve the look of the workflow_runs index

src/api/lib/tasks/dev.rake, src/api/lib/tasks/dev/requests.rake
This PR adds a sample request with a couple of maintenance incident request actions and a delete submit type
=> Create a maintenance incident action

src/api/app/controllers/webui/request_controller.rb, src/api/app/models/review.rb, src/api/spec/cassettes/Bootstrap_Requests/a_request_submitted_against_a_staging_project/sets_badge_for_sr.yml, src/api/spec/features/webui/requests_spec.rb
While reviewing another PR, @hennevogel noticed that the staging badge displays when a review is created for a staging project that's not necessarily a staging project of the current target project. This should fix that
=> Ensure that the staging badge displays when submitted against a staging project

src/backend/BSSrcServer/Signkey.pm
The former rsa@2048 is no longer deemed as good enough by the security folks.
=> [backend] use rsa@4096 for new project keys

src/api/app/models/event/relationship.rb
=> Prevent crashes for access-protected projects/packages

src/api/app/controllers/webui/packages/files_controller.rb, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/adding_a_file_that_doesn_t_exist_yet/1_1_3_1.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/adding_a_file_that_doesn_t_exist_yet/1_1_3_2.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/adding_a_file_that_doesn_t_exist_yet/1_1_3_3.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/uploading_a_file_from_remote_URL/1_1_5_1.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/uploading_a_file_from_remote_URL/1_1_5_2.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/uploading_a_file_from_remote_URL/creates_a_valid_service_file.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/uploading_a_utf-8_file/1_1_4_1.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/uploading_a_utf-8_file/1_1_4_2.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/uploading_a_utf-8_file/creates_the_file.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/with_an_invalid_filename/fails_with_a_backend_error_message.yml, src/api/spec/cassettes/Webui_Packages_FilesController/POST_create/without_any_uploaded_file_data/fails_with_an_error_message.yml, src/api/spec/controllers/webui/packages/files_controller_spec.rb
That path is no longer used as far as I can tell, so it can be safely removed
=> Remove xhr path from files post

src/api/app/views/webui/groups/_group_members.html.haml, src/api/spec/features/webui/groups_spec.rb
We just use the card component developed in https://github.com/openSUSE/open-build-service/pull/13809 (it's a follow up)
=> Use card components for group members

src/backend/BSPublisher/Container.pm, src/backend/BSPublisher/Registry.pm, src/backend/BSSched/BuildJob/Aggregate.pm, src/backend/bs_regpush
We now support .spdx.json and .cyclonedx.json instead of .sbom.json. Please make complaints to Adrian.
=> [backend] support both spdx and cyclonedx sbom files

src/backend/BSPublisher/Container.pm, src/backend/BSSched/BuildJob/Aggregate.pm, src/backend/bs_publish, src/backend/bs_regpush
This seems to be what the cyclonedx folks prefer.
=> [backend] Use .cdx.json instead of .cyclonedx.json

src/api/app/assets/stylesheets/webui/application.scss, src/api/app/assets/stylesheets/webui/tokens.scss, src/api/app/components/card_component.html.haml, src/api/app/components/card_component.rb, src/api/app/components/token_card_component.html.haml, src/api/app/views/webui/users/tokens/index.html.haml
Based on top of https://github.com/openSUSE/open-build-service/pull/13809 to make use of the new default component in the token instances
A preview is available [here](https://obs-reviewlab.opensuse.org/ncounter-token-card/my/tokens)
=> Use card component for token card

.gitmessage
Add myself to .gitmessage
as part of onboarding
=> Add myself to .gitmessage

src/api/app/assets/stylesheets/request_show_redesign/add_review.scss, src/api/app/components/add_review_collapsible_component.html.haml, src/api/app/views/webui/request/beta_show_tabs/_conversation_aside.html.haml
| Desktop  |  Mobile |
|---|---|
| ![before-desktop](https://user-images.githubusercontent.com/1102934/220674804-526ed08c-2f8c-484f-8bbf-319cd1497474.png)  | ![before-mobile](https://user-images.githubusercontent.com/1102934/220674815-409d58b1-34af-4f31-b458-c41dd479dab8.png)  |
| Desktop  |  Mobile |
|---|---|
| ![now-desktop](https://user-images.githubusercontent.com/1102934/220847556-f51932b3-4695-4211-ae5c-a188eb5575c9.png)  | ![now-mobile](https://user-images.githubusercontent.com/1102934/220847568-6a9b4301-b8c2-4790-8b59-ef354e5cfa6d.png)  |
=> Size the "Give a review" component based on the screen

src/api/spec/factories/history_elements.rb
We need more complete HistoryElement factories for further testing.
=> Extend history elements factories

src/api/spec/components/bs_request_history_element_component_spec.rb
We had implemented the component but not the specs. Here they are.
=> Add BsRequestHistoryElementComponent specs

src/api/app/controllers/webui/search_controller.rb
Fixes #13868.
- With an invalid value of the `page` parameter, the first page of the results is shown: https://obs-reviewlab.opensuse.org/eduardoj-fix_13868/search?search_text=another&page=some_random_text
- With a very big value of the `page` parameter, the first page of the results is shown: https://obs-reviewlab.opensuse.org/eduardoj-fix_13868/search?search_text=another&page=100000
=> Ignore invalid values for `page` parameter in searches

src/api/app/views/webui/request/_action_text.html.haml, src/api/app/views/webui/request/_actions_details.html.haml
*Before:*
*After:*
- https://obs-reviewlab.opensuse.org/eduardoj-featuresupport_action_add_role/request/show/9
=> Show Add Role request actions in the multi action dropdown

README.md
=> Add build result badge to the readme

src/api/public/apidocs-new/components/parameters/request.yaml
...  for the `/request?view=collection` API endpoints.
Related to #13911.
=> Complete the documentation of the `project` and `package` parameters

src/api/spec/components/bs_request_comment_component_spec.rb, src/api/spec/factories/comments.rb
We had implemented the component but not the specs. Here they are.
=> Add specs for BsRequestCommentComponent

src/api/app/components/diff_component.html.haml, src/api/app/views/webui/comment/_comment_list.html.haml, src/api/app/views/webui/comment/_new.html.haml, src/api/app/views/webui/request/_add_inline_comment.html.haml, src/api/app/views/webui/request/inline_comment.js.erb
Depends on #13912
Minimizes the new comment field in the line comment section.
=> Minimize the new comment entry in line comment section

src/api/spec/cassettes/Bootstrap_Requests_Submissions/submit_package/submit_several_packages_at_once/shows_the_beta_version_of_the_requests_page.yml, src/api/spec/cassettes/Bootstrap_Requests_Submissions/submit_package/when_under_the_beta_program/submit_several_packages_at_once_against_a_factory_staging_project/shows_the_beta_version_of_the_requests_page.yml, src/api/spec/cassettes/Webui_Requests_SubmissionsController/POST_create/superseeding_a_request_that_does_not_exist/1_1_4_1.yml, src/api/spec/features/webui/requests/submissions_spec.rb, src/api/spec/support/beta.rb
This PR adds a feature spec to test the main features of the request show page under the beta flag.
=> Feature specs to test most used request show features

src/api/app/assets/stylesheets/webui/requests.scss, src/api/app/components/action_seen_by_user_component.html.haml, src/api/app/components/fuzzy_time_component.rb, src/api/app/views/webui/request/_actions_details.html.haml, src/api/app/views/webui/request/beta_show.html.haml, src/api/spec/components/fuzzy_time_component_spec.rb, src/api/spec/features/webui/requests_spec.rb
Address https://trello.com/c/1Pg8ZhVO
**New or Review**
**Revoke or declined**
**Accepted**
**Multi action**
**Superseeding**
**Staged**
**Auto accept**
**Superseded**
=>  Request header section: reorganize information

src/api/spec/features/webui/requests/submissions_spec.rb
$subject
Since https://github.com/openSUSE/open-build-service/pull/13941 some text has changed.
Spec tests are to be adapted with this PR
=> Adapt test to the new rendered text

src/backend/BSSched/Checker.pm, src/backend/BSSched/RPC.pm, src/backend/BSSched/Remote.pm
This can be use to only recheck if all needed remote resources are present.
=> [backend] add setchanged_unless_othersinprogress method

docs/api/api/api.txt
=> apidocs: Document 2 params as bool

dist/obs-bundled-gems.spec
We need to point obs-server to the updated rack version
=> Update bundled gem rack version

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/attribute_name.yaml, src/api/public/apidocs-new/paths/source_project_name_package_name_attribute_attribute_name.yaml
With the attribute name specified in the parameters, this endpoint displays the attribute of the package.
- Go to Attributes tab in the package tab
- Add one attribute
`curl -u Admin:opensuse -H 'Content-Type: application/xml; charset=utf-8' -X  GET 'http://localhost:3000/source/home:Admin/ad/_attribute/OBS:MakeOriginOlder'`
=> Document `GET /source/{project_name}/{package_name}/_attribute/{attribute_name}` endpoint

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/responses/unknown_project_or_package_or_file.yaml, src/api/public/apidocs-new/paths/source_project_name_package_name_file_name.yaml
Access to the documented endpoint in the review-app through [this link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newsource_package_get/apidocs-new/index.html#/Sources%20-%20Files/get_source__project_name___package_name_).
**GET**
- run `curl -u foo:bar -H 'Content-Type: application/xml; charset=utf-8' -X GET 'http://localhost:3000/source/home:Admin/hello_world/hello_world.changes'` to retrieve the content of the `hello_world.changes` file
- check if the content of the file matches the webUI one
**DELETE**
- run `curl -u foo:bar -H 'Content-Type: application/xml; charset=utf-8' -X DELETE 'http://localhost:3000/source/home:Admin/hello_world/hello_world.changes'` to delete the `hello_world.changes` file
- check if the file got deleted (either in the webUI, or by retrieving the …
=> Document /source/{project_name}/{package_name}/{file_name} endpoints with OpenAPI

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_branch.yaml, src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_linktobranch.yaml
Old api links:
https://build.opensuse.org/apidocs/index#60
https://build.opensuse.org/apidocs/index#71
Links for reviewers:
https://obs-reviewlab.opensuse.org/hellcp-work-apidocs-sources-package-branch/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_branch
https://obs-reviewlab.opensuse.org/hellcp-work-apidocs-sources-package-branch/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_linktobranch
=> Document POST `/source/{project_name}/{package_name}?cmd={branch,linktobranch}` endpoints

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/responses/unknown_project_or_package_or_attribute.yaml, src/api/public/apidocs-new/components/schemas/source/attributes.yaml, src/api/public/apidocs-new/paths/source_project_name_package_name_binary_filename_attribute_name.yaml
Specifications for `GET/DELETE source/:project/:package/:binary/_attribute/:attribute`
=> OpenAPI specifications for source files attributes

src/api/app/components/diff_list_component.html.haml, src/api/app/components/diff_list_component.rb
=> Expand diffs that contain comments by default

src/api/app/views/webui/request/beta_show.html.haml
See https://github.com/openSUSE/open-build-service/pull/13961#discussion_r1150391197
For some reason these changes never got  merged, but they were supposed to.
=> Better wording toward common usage

src/api/app/controllers/webui/request_controller.rb, src/api/app/helpers/webui/request_helper.rb, src/api/app/views/webui/request/_action_text.html.haml, src/api/app/views/webui/request/_actions_details.html.haml, src/api/lib/tasks/dev/requests.rake, src/api/spec/cassettes/Request_with_change_devel_actions/there_was_a_previous_devel_package/displays_the_description_and_mentions_the_previous_devel_package.yml, src/api/spec/cassettes/Request_with_change_devel_actions/there_was_no_previous_devel_package/displays_the_description_but_does_not_mentions_the_previous_devel_package.yml, src/api/spec/factories/bs_request_actions.rb, src/api/spec/factories/bs_requests.rb, src/api/spec/features/webui/requests/change_devel_actions_spec.rb
The new type of request action is now displayed in the dropdown like this:
And this is the information displayed:
https://obs-reviewlab.opensuse.org/saraycp-change_devel_request/request/show/9/request_action/36
=> Support change devel requests

src/api/.rubocop_todo.yml, src/api/app/controllers/webui/users/tokens_controller.rb, src/api/spec/controllers/webui/users/tokens_controller_spec.rb
Follow-up for https://github.com/openSUSE/open-build-service/pull/14080
=> Do not redirect, use render and reinitialize

src/api/app/assets/stylesheets/webui/bootstrap_variables/colors.scss, src/api/app/assets/stylesheets/webui/sidebar-collapsible.scss
Give more feedback about mouse hovering the navigation-bar menu on the left
=> Highlight hover navigation-bar menu entry

src/api/app/views/webui/request/beta_show.html.haml
Fix for https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6437cc7c84bf4604fe23e2b6
=> Bugfix: inizialize the badge component first

src/api/app/models/issue_tracker.rb
We can't set args in the proxy because it's overriding the args we provide later, so instead we have a common set of args that gets set to the appropriate user and api_key values
=> Move bugzilla_args into its own function

src/api/app/components/avatar_component.html.haml, src/api/app/components/avatar_component.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/spec/components/avatar_component_spec.rb, src/api/spec/components/previews/avatar_component_preview.rb
Displays a user avatar with alt and title. Circle shape is optional. Size and CSS classes can be customized.
This component can be used wherever we need to display only the avatar and will be used in another component that shows both the avatar and a link.
Use the view components previews to check how it looks.
=> Define AvatarComponent

src/api/app/views/notifications/comment_for_request.text.erb
=> Fix message template for request actions

src/backend/BSContar.pm, src/backend/BSPublisher/Container.pm, src/backend/BSPublisher/Registry.pm, src/backend/BSRepServer/Containertar.pm, src/backend/bs_publish, src/backend/bs_regpush, src/backend/bs_worker
We store the compression format in the containerinfo's layer_compression element.
=> [backend] support non-gzip compression for containers

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/status_messages.yaml
Specifications for GET status/messages
=> OpenAPI specifications for GET status/messages

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/staging/managers_group.yaml, src/api/public/apidocs-new/paths/staging_staging_workflow_project_workflow.yaml
=> Document all the  `/staging/{staging_workflow_project}/workflow` endpoints

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/status_messages.yaml
- Fix order of endpoints. Sort them alphabetically
- Fix "Status Messages" section
=> Couple of fixes for the apidocs new documentation

src/backend/BSContar.pm, src/backend/BSPublisher/Container.pm, src/backend/BSPublisher/Registry.pm, src/backend/bs_regpush
By adding new functions to BSContar:
- blobid()
- create_config_data()
- create_dist_manifest_data()
- create_dist_manifest_list_data()
=> [backend] container publishing: remove more duplicated code

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/staging/backlog.yaml, src/api/public/apidocs-new/paths/staging_project_name_backlog.yaml
Endpoint: GET `staging/{project_name}/backlog`
- You have ProjectA
- You create a Staging Workflow for ProjectA (go to the Staging tab on the show page of the project and follow the steps)
- Create a submit request towards any package of ProjectA
- Check the backlog now, the newly created submit request will be part of it.
https://obs-reviewlab.opensuse.org/saraycp-staging_backlog_endpoint/apidocs-new/index.html#/Staging%20Workflow/get_staging__project_name__backlog
=> Document staging backlog endpoint with OpenAPI

dist/systemd/obsclouduploadserver.service, dist/systemd/obsclouduploadworker.service, dist/systemd/obsdeltastore.service, dist/systemd/obsdispatcher.service, dist/systemd/obsdodup.service, dist/systemd/obsgetbinariesproxy.service, dist/systemd/obsnotifyforward.service, dist/systemd/obspublisher.service, dist/systemd/obsredis.service, dist/systemd/obsrepserver.service, dist/systemd/obsscheduler.service, dist/systemd/obsscheduler@.service, dist/systemd/obsservice.service, dist/systemd/obsservicedispatch.service, dist/systemd/obssigner.service, dist/systemd/obssourcepublish.service, dist/systemd/obssrcserver.service, dist/systemd/obsstoragesetup.service, dist/systemd/obswarden.service, dist/systemd/obsworker.service, dist/systemd/obsworker@.service
or some services do not bind correctly on startup
=> [dist] systemd services: wait for network getting online

src/api/public/apidocs-new/components/responses/status_message_no_permission.yaml, src/api/public/apidocs-new/components/responses/validation_error.yaml, src/api/public/apidocs-new/components/schemas/status_message.yaml, src/api/public/apidocs-new/paths/status_messages.yaml
Specifications for POST status/messages
=> OpenAPI specifications for POST status/messages

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/staging/excluded_requests.yaml, src/api/public/apidocs-new/paths/staging_project_name_excluded_requests.yaml
=> Document all the `/staging/{project_name}/excluded_requests` endpoints

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/staging_project_name_staging_projects_staging_project_name_copy_staging_project_copy_name.yaml
=> Post staging project copy

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/comment.yaml, src/api/public/apidocs-new/components/schemas/comments.yaml, src/api/public/apidocs-new/paths/comments_user.yaml
Continuation of the previous comments PR, documentation on the endpoint that lets you see the currently logged in user's comments
=> Document user comments endpoint

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/responses/not_found.yaml, src/api/public/apidocs-new/paths/status_messages_id.yaml
specifications for GET/DELETE status/message/{id}
=> OpenAPI specifications GET/DELETE status/message/{id}

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/staging_project_name_staging_projects_staging_project_name_accept.yaml
=> Post staging project accept

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/staging_project_name_staged_requests.yaml
Endpoint: DELETE `/staging/{project_name}/staged_requests`
Please, review and merge https://github.com/openSUSE/open-build-service/pull/14253 first.
=> Document DELETE staged requests endpoint

src/backend/bs_worker
=> [backend] record epoch/version/release/arch in _buildenv

src/api/app/views/layouts/webui/_places.html.haml, src/api/app/views/layouts/webui/_top_navigation.html.haml, src/api/app/views/webui/user/_basic_info.html.haml, src/api/app/views/webui/user/_edit_account_form.html.haml
Follow up PR #14178.
Check the navigation areas for large and small viewports. Check the profile area too.
=> Use avatar component in navigation and profile areas

src/api/app/controllers/webui/request_controller.rb, src/api/app/helpers/webui/request_helper.rb, src/api/app/views/webui/request/_breadcrumb_items.html.haml, src/api/app/views/webui/request/_request_tabs.html.haml, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_changes.html.haml, src/api/app/views/webui/request/changes.html.haml, src/api/config/routes/webui_routes.rb
This PR is a follow-up of multiple PR's. Please only consider last two commits when reviewing
=> Convert changes tab to a separate action

src/backend/BSServer.pm
With the old code one socket would not be handled at all if the other socket was flooded with connections.
=> [backend] BSServer: handle both sockets if select returns

src/backend/BSStdServer.pm
Add support for two http header elements:
- trusted_peerip_header: the ip of the client
- trusted_subjectdn_header: the verified subject dn of the cert
=> [backend] mode https->http proxy support

src/api/app/controllers/webui/request_controller.rb
Refactoring to deduplicate the same piece of code used in more than one place.
=> Deduplicate notification handling in request controller

src/backend/BSServer.pm, src/backend/BSServerEvents.pm, src/backend/BSStdServer.pm, src/backend/BSWatcher.pm
This is an interval timer, i.e. it is restared if we make progress. We use a timeout of 2 minutes for now.
Also increase the request reply timeout from 10 seconds to 1 minute.
=> [backend] AJAX: implement a stream reply timeout

src/backend/BSRepServer/Remote.pm
We only did it in the scheduler, thus all buildinfo requests used the slow AJAX view=cache method.
=> [backend] implement solvstate optimization in the repo server

src/backend/BSSSL.pm, src/backend/BSWatcher.pm
We must not block the AJAX server for too long.
=> [backend] Implement a ssl connect timeout in async mode

src/api/app/controllers/source_controller.rb, src/api/app/models/branch_package.rb, src/api/db/attribute_descriptions.rb, src/api/db/data_schema.rb, src/api/test/fixtures/attrib_types.yml, src/api/test/functional/attributes_test.rb
- opt-in for channel branching
- patchinfo manual release support using timestamps
patch from adrian, applied in IBS since Sep 2019
=> [api] Alternative maintenance workflow

src/api/lib/tasks/dev/test_data/maintenance.rb, src/api/spec/controllers/webui/patchinfo_controller_spec.rb, src/api/spec/controllers/webui/project_controller_spec.rb, src/api/spec/factories/patchinfo.rb, src/api/spec/factories/project.rb, src/api/spec/features/webui/patchinfo_spec.rb
=> Create patchinfo factory

src/api/lib/tasks/dev/test_data/maintenance.rb
Run `bundle exec rake dev:test_data:create` locally. It should create a maintenance **release** request with Number 15, which contains actions from 2 projects, 2 packages and 2 patchinfos.
=> Set up maintenance release request in development environment

src/backend/bs_repserver
it just wiped the first architecture
=> [backend] fix wipeallarch mechanic

docs/api/api/api.txt, src/api/app/controllers/source_controller.rb, src/api/app/controllers/trigger_controller.rb, src/api/app/helpers/maintenance_helper.rb, src/api/app/models/bs_request_action_maintenance_release.rb, src/api/app/models/owner_search/missing.rb, src/api/app/models/repository.rb, src/api/app/models/token/errors.rb, src/api/app/models/token/release.rb, src/api/public/apidocs-new/paths/trigger_operation.yaml, src/api/spec/cassettes/Token_Release/_call/when_the_release_target_is_provided_through_parameters/when_the_architecture_is_provided_through_parameters_and_is_included_in_the_target_repository/triggers_the_release_process_in_the_backend.yml, src/api/spec/cassettes/Token_Release/_call/when_the_release_target_is_provided_through_parameters/when_the_architecture_is_provided_through_parameters_and_is_not_included_in_the_target_repository/does_not_trigger_the_release_process_in_the_backend.yml, src/api/spec/cassettes/Token_Release/_call/when_the_release_target_is_provided_through_parameters/when_the_target_project_targetrepository_filter_source_repository_and_arch_parameters_are_provided/triggers_the_release_process_in_the_backend.yml, src/api/spec/cassettes/Token_Release/_call/when_the_release_target_is_provided_through_parameters/when_the_user_can_not_modify_the_target_repository/does_not_trigger_the_release_process_in_the_backend.yml, src/api/spec/controllers/trigger_controller_spec.rb, src/api/spec/controllers/webui/users/token_triggers_controller_spec.rb, src/api/spec/models/token/release_spec.rb
This is replacing https://github.com/openSUSE/open-build-service/pull/12563, had to skip a commit and needed a rebase
=> Fix and extend release mechanics

src/api/lib/tasks/dev/test_data/maintenance.rb, src/api/spec/factories/bs_requests.rb, src/api/spec/helpers/webui/request_helper_spec.rb, src/api/spec/models/project_spec.rb, src/api/spec/support/shared_contexts/a_project_with_maintenance_statistics.rb
~This pull request depends/"is based" on #14372.~
=> Modify request with maintenance release actions factory

src/api/lib/tasks/dev/test_data/maintenance.rb, src/api/spec/factories/bs_requests.rb
This way we can use that as a proper factory
=> Extract a trait to accept last incident request in a factory

src/api/app/components/add_review_dropdown_component.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/policies/bs_request_policy.rb, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_ask_for_review.html.haml, src/api/app/views/webui/request/beta_show_tabs/_conversation_aside.html.haml, src/api/spec/policies/bs_request_policy_spec.rb
This code is for authorization and therefore should be in a
pundit policy.
Extracted out of https://github.com/openSUSE/open-build-service/pull/14318 to ease review
=> Create `can_add_reviews?` pundit policy and use in request beta views

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/limit_10.yaml, src/api/public/apidocs-new/components/schemas/latest_added.yaml, src/api/public/apidocs-new/components/schemas/latest_updated.yaml, src/api/public/apidocs-new/components/schemas/most_active.yaml, src/api/public/apidocs-new/components/schemas/statistics/package.yaml, src/api/public/apidocs-new/components/schemas/statistics/project.yaml, src/api/public/apidocs-new/paths/statistics_latest_added.yaml, src/api/public/apidocs-new/paths/statistics_latest_updated.yaml, src/api/public/apidocs-new/paths/statistics_most_active_packages.yaml, src/api/public/apidocs-new/paths/statistics_most_active_projects.yaml
GET /statistics/latest_updated stands out as more involved, since it has additional parameters, the rest is fairly simple
=> Document supported statistics endpoints

src/backend/BSRPC.pm, src/backend/BSSSL.pm, src/backend/BSWatcher.pm
This was lost in commit 748882e4174db8a0694719cd7b16da9089656b34
=> [backend] bring back connect_timeout setting in BSWatcher

src/backend/BSRepServer.pm, src/backend/BSSSL.pm, src/backend/BSStdServer.pm, src/backend/BSWatcher.pm, src/backend/BSXML.pm, src/backend/bs_repserver
This should help when dod repos change and lots of build jobs try to download new packages.
=> [backend] implement a pool/repo cache for the AJAX repserver

src/api/public/apidocs-new/paths/build_project_name_repository_name_architecture_name_package_name_file_name.yaml
You can test this endpoint making `home:Admin/hello_world` to build successfully on a local development instance and then issuing a delete request for the filename `hello_world.rpm`
=> Document the delete build artifacts endpoint

src/backend/BSSrcServer/Service.pm, src/backend/bs_service, src/backend/bs_srcserver
Use package url meta element for now to transfer the information.
Ideally we should found a new element, but it would break external OBS instances
=> [backend] Make use of projectscmsync functionality in scm bridge

Makefile, dist/obs-server.spec
See https://build.opensuse.org/package/show/home:krauselukas:branches:OBS:Server:Unstable/obs-server for the test build with the changes from the PR applied
=> Move call to `resolve_swagger_yaml.rb` script to Makefile

.obs/workflows.yml
link_package can't run source services anymore...
=> Adapt testbuild workflow to 14437

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/project_status.yaml, src/api/public/apidocs-new/paths/status_project_name.yaml
Documentation for `/status/project/:project_name`
=> OpenAPI specifications for project status

src/api/public/apidocs/README.md
What is it and how can you change it?
=> Add developer docu to the OpenAPI directory

.circleci/config.yml
This is now needed according to circle-ci support
=> Add continuation orb

.circleci/config.yml
We face issues in circle ci, lets see if its related to changes in this orb introduced 3 days ago.
=> Switch back to path-filtering orb version 0.1.5

.circleci/config.yml
This reverts commit 0f4f0d8af463f7eb594ae7f045c9035d354b53ae.
=> Revert "Switch back to path-filtering orb version 0.1.5"

src/api/public/apidocs/OBS-v2.10.50.yaml, src/api/public/apidocs/paths/statistics_deprecated_not_documented.yaml
Deprecate non-documented statistics endpoints.
=> Deprecate multiple statistics endpoints

src/api/public/apidocs/OBS-v2.10.50.yaml, src/api/public/apidocs/components/schemas/source/sourceinfo.yaml, src/api/public/apidocs/components/schemas/source/sourceinfolist.yaml, src/api/public/apidocs/paths/source_project_name_view_info.yaml
Link to the documented endpoint in the review-app [here](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newsource_project_view_info/apidocs/index.html#/Sources%20-%20Projects/get_source__project_name__view_info).
=> Document `GET '/source/:project?view=info` API endpoint

src/api/app/views/event_mailer/comment_for_package.html.haml, src/api/app/views/event_mailer/comment_for_package.text.erb, src/api/app/views/event_mailer/comment_for_project.html.haml, src/api/app/views/event_mailer/comment_for_project.text.erb, src/api/app/views/event_mailer/comment_for_request.html.haml, src/api/app/views/event_mailer/comment_for_request.text.erb
Let's send people to the right place directly
Fixes #14494
=> Include comment anchors in comment event mails

src/api/config/initializers/airbrake.rb
Ignore more backend errors - similar to #8199
except now the message is
<status code="400"> <summary>home:regataos/gcc12: conflict in file gcc12.spec</summary> </status>
=> Ignore more backend errors

src/backend/bs_dodup
This is experimental and subject to change.
=> [backend] support a directory containing dod pubkeys

src/api/app/jobs/worker_measurements_job.rb
Send metrics about daemon availability via RabbitMQ+telegraf into influxdb+grafana
This patch allows us to do alerting when a required backend service becomes unavailable.
=> Send metrics about daemon availability

src/api/app/components/comment_component.rb
This should have been addressed in #14582.
=> Do the assigments only if we need them

src/api/app/components/bs_request_activity_timeline_component.rb, src/api/app/controllers/comments_controller.rb
Follow up to #14602. See this comment: https://github.com/openSUSE/open-build-service/pull/14602#pullrequestreview-1514045146
=> Improve query to retrieve comments for request actions

src/api/app/components/bs_request_activity_timeline_component.rb, src/api/app/controllers/comments_controller.rb, src/api/app/models/comment.rb, src/api/app/views/webui/comment/_comment_list.html.haml
Make code more compact and improve legibility.
Follow-up to #14602 and #14608.
=> Create scope for comments on actions for a specific request

src/api/app/controllers/webui/request_controller.rb
New tag for bs_request_action type to instrument BsRequestActions per type for request_workflow_redesign beta feature
=> Instrument bs_request_actions by type

src/api/app/models/user.rb, src/api/db/migrate/20230712141001_drop_user_registrations.rb, src/api/db/schema.rb
Also drop never reachable code.
=> Drop unused `user_registrations` table

src/api/.haml-lint.yml, src/api/.haml-lint_todo.yml, src/api/lib/haml-lint/custom_linters/set_pagetitle_in_view.rb
This is due to [the latest](https://github.com/sds/haml-lint/pull/415) `haml-lint` upgrade.
=> Fix custom linter SetPagetitleInView

src/api/app/views/layouts/webui/_left_navigation.html.haml, src/api/app/views/webui/distributions/_breadcrumb_items.html.haml, src/api/app/views/webui/distributions/new.html.haml, src/api/app/views/webui/package/_fileinfo.html.haml, src/api/app/views/webui/package/_job_status.html.haml, src/api/app/views/webui/package/_rpmlint_result.html.haml, src/api/app/views/webui/package/live_build_log.html.haml, src/api/app/views/webui/package/statistics.html.haml, src/api/app/views/webui/project/_edit_comment.html.haml, src/api/app/views/webui/repositories/_add_repository_path_modal.html.haml, src/api/app/views/webui/search/_search_for.html.haml, src/api/app/views/webui/shared/_requests_state_and_type_form.html.haml, src/api/app/views/webui/staging/shared/_legend.html.haml, src/api/app/views/webui/staging/workflows/_status_problems.html.haml
HAML-Lint is complaining in master, after HAML-Lint was updated.
=> Address HAML-Lint TrailingEmptyLines complains

.circleci/config.yml
Related to this comment: https://github.com/openSUSE/open-build-service/pull/14658#issuecomment-1640156672
=> Run HAML-Lint in our CI when HAML rubygems get updated

src/api/app/models/workflow.rb, src/api/app/models/workflow/step.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/models/workflow/step/link_package_step.rb, src/api/app/models/workflow/step/rebuild_package.rb, src/api/app/models/workflow/step/trigger_services.rb, src/api/app/services/workflows/scm_event_subscription_creator.rb
=> Refactor the step event subscription

src/api/app/views/webui/package/_commit_item.html.haml
=> Bugfix: request number is the identifier

src/api/lib/tasks/migrate_options_yml.rake
Fixes #14678.
Borrowed code from @danidoni, from this commit: 30424968eaadbc1140166327a36cda86bb029950.
=> Use `aliases: true` to avoid yaml loading errors

src/backend/bs_worker
=> [backend] bs_worker: fix undefined variable reference

src/api/app/views/webui/projects/signing_keys/show.html.haml
Just another way to identify keys
=> Also show GPG Key User ID

.circleci/conditional_config.yml, .obs/workflows.yml
As we use SLES 15 SP5 in production.
=> Run our SCM/CI Workflow Against 15.5

src/api/app/components/notification_filter_component.html.haml, src/api/app/components/notification_filter_link_component.html.haml, src/api/app/components/notification_filter_link_component.rb, src/api/spec/components/notification_filter_link_component_spec.rb
Follow up for consistency with https://github.com/openSUSE/open-build-service/pull/14720
Before:
After:
=> Notifications menu enhancements

src/api/app/components/workflow_run_request_action_filter_component.html.haml, src/api/app/components/workflow_run_row_component.html.haml
- more space between the workflow run title and the badge
- align the apply button to the select box group
Before:
After:
=> Workflow run content UI enhancements

src/api/app/models/bs_request_permission_check.rb
Fixes #3687.
To reproduce the steps in the development environment (using `dosc` instead of `osc`), having the packages `home:Admin/ea` and `home:Admin/et`, follow these steps:
```
dosc changedevelrequest home:Admin ea home:Admin et
dosc -H rq accept $REQUEST_ID -m ok
dosc deletereq home:Admin et
```
At this point this comand:
```
dosc -H rq accept $REQUEST_ID -m ok -f
POST /request/$REQUEST_ID?cmd=changestate&newstate=accepted&force=1
```
will return this error, **before** the changes:
```
HTTP Error 400: Bad Request
delete_error
Package is used by following packages as devel package: home:Admin/ea
```
**After** the changes of this pull request, it should return something similar to:
```
Result of change request state: ok
Request:    22
Created by: Admin
Actions:
delete: …
```
=> Honor the `force` parameter when accepting a delete request

.obs/workflows.yml
link_package can't run source services anymore...
=> Switch to branch_package and test 15.4 build

src/api/app/services/workflows/yaml_downloader.rb, src/api/spec/controllers/trigger_workflow_controller_spec.rb, src/api/spec/services/workflows/yaml_downloader_spec.rb
This PR ensures the support of private GitHub repos for SCM/CI integration.
=> Support private GitHub repos for SCM/CI integration

src/api/app/models/workflow_run.rb
payload is no deep symbolized keys
=> Fix hash dig in event_source_message

src/api/app/views/webui/repositories/_repository_card_content.html.haml
=> Flush content of path details for each repository

src/api/config/routes/webui_routes.rb
=> Fix typo in redirect in the webui routes

.github/workflows/gitleaks.yml, .gitleaksignore, gitleaks.toml
Gitleaks is a SAST tool for detecting hardcoded secrets like passwords, api keys, and tokens.
=> Introduces gitleaks

src/backend/BSRepServer/DoD.pm
This fixes issues with e.g. AmazonLinux2023 repositories that use relative URLs. Fixes #14654.
=> Normalize URLs before trying to download them.

src/api/app/controllers/webui/groups/users_controller.rb
=> Add missing `@` to the variable containing the user

src/api/app/controllers/worker/command_controller.rb
obs#14844
Fixes https://github.com/openSUSE/open-build-service/issues/14844
=> [api] fix multibuild flavors for checkconstraints

src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_with_patchinfo/displays_information_on_type_of_request.yml, src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_with_patchinfo/has_patchinfo_submission.yml, src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_with_patchinfo/when_accepting_request/creates_maintenance_incident_project.yml, src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_with_patchinfo/when_accepting_request/succeeds.yml, src/api/spec/features/beta/webui/maintenance_workflow_spec.rb
Continuing where #14857 left off
=> Add a maintenance request with patchinfo spec

src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_with_patchinfo/displays_information_on_type_of_request.yml, src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_with_patchinfo/has_patchinfo_submission.yml, src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_with_patchinfo/when_accepting_request/creates_maintenance_incident_project.yml, src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_with_patchinfo/when_accepting_request/succeeds.yml, src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_without_patchinfo/displays_information_on_type_of_request.yml, src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_without_patchinfo/when_accepting_request/creates_maintenance_incident_project.yml, src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_without_patchinfo/when_accepting_request/succeeds.yml, src/api/spec/features/beta/webui/maintenance_workflow_spec.rb
This prevented running the spec from scratch.
=> Correct the name of the patchinfo package

src/api/app/components/chart_component.rb
Fix for https://github.com/openSUSE/open-build-service/issues/14867
=> Bugfix: skip if project not found

src/api/app/controllers/person/token_controller.rb, src/api/spec/controllers/person/token_controller_spec.rb
=> Improve token creation error message

src/api/app/controllers/person/token_controller.rb, src/api/spec/controllers/person/token_controller_spec.rb
Some more corner cases have to be tackled before we finally introduce the changes in #14888 .
=> Revert PR 14888

src/api/app/components/report_component.rb
This PR fixes the reportable_type passed into the report component
=> Fix reportable-type for report component

src/api/app/models/user.rb, src/api/db/data/20230920125132_add_moderator_to_roles.rb, src/api/db/data_schema.rb, src/api/db/seeds.rb
=> Add role "Moderator" to roles table

src/api/app/models/event/base.rb
Now the error message explains exactly what is happening.
=> Improve error message when during event creation

src/api/app/models/decision.rb, src/api/app/models/report.rb, src/api/app/models/user.rb, src/api/db/migrate/20230921133606_create_decisions.rb, src/api/db/schema.rb
This new model represents the decision a moderator takes regarding a report.
The decision can be "cleared" (0) or "favor" (1).
One report can have only one decision but one specific decision can affect many reports.
Try out in Rails console:
- Make sure you have a  Report and a User
- `Decision.create!(moderator: User.first, reason: 'Reason A', kind: 'favor')`
-  `Decision.first.reports << Report.first`
- `Report.first.decision`
- `User.first.decisions`
-  `User.first.decisions.first.reports`
- ... play around with all the possible combinations (deleting, trying to create with missing parameters, etc.)
=> Create new model Decision

src/api/app/controllers/webui/project_controller.rb
buildresult is a controller action, re-using it as variable is a desaster bound
to happen...
=> Do not use action as "local" variable 

src/api/lib/tasks/dev.rake, src/api/lib/tasks/dev/reports.rake
Based on #14921
**Testing tips**
1. bundle exec rake dev:test_data:create
2. rails c
3. Decision.count # There should be 4 decisions
4. Decision.first.reports # The first decision applies to two reports
=> Add test data for decisions

src/api/app/queries/notifications_finder.rb
=> Implement filters for decision events

src/api/app/models/event/cleared_decision.rb, src/api/app/models/event/create_report.rb, src/api/app/models/event/favored_decision.rb
These annotations should have been included when creating these event models.
=> Add missing Schema information sections

src/api/public/apidocs/paths/source_branch.yaml
=> Document `update_project_attribute` for `POST /source?cmd=branch` API endpoint

docs/api/api/tokenlist.rng, docs/api/api/tokenlist.xml, src/api/public/apidocs/components/schemas/person_tokens.yaml, src/api/public/apidocs/paths/person_login_token.yaml
Fixes #14811.
This should have been added in #12434.
=> Fix documentation of tokens' list API endpoint

src/api/app/controllers/comments_controller.rb, src/api/public/apidocs/paths/comments_request_id.yaml
=> Improve error message for request not found

src/api/app/assets/stylesheets/webui/bootstrap_variables/colors.scss, src/api/app/assets/stylesheets/webui/card-component.scss, src/api/app/assets/stylesheets/webui/modals.scss, src/api/app/assets/stylesheets/webui/timeline.scss, src/api/app/components/sign_up_component.html.haml, src/api/app/views/layouts/webui/_login_form.html.haml, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/rpm_lint.html.haml, src/api/app/views/webui/shared/_buildresult_box.html.haml
Makes sure that no matter the changes, the color of the overlays stay consistent with the background. This should fix #15013
=> Replace bg-white with contextual bg classes

src/api/app/controllers/person/token_controller.rb, src/api/public/apidocs/paths/person_login_token_id.yaml
=> Improve error message for token not found

src/api/app/assets/javascripts/webui/report.js, src/api/app/controllers/webui/reports_controller.rb, src/api/app/models/report.rb, src/api/app/views/webui/shared/_report_modal.html.haml, src/api/db/migrate/20231005074105_add_category_to_report.rb, src/api/db/schema.rb
This implements model changes and UI for reporting with categories
=> Implement report categories

src/backend/BSRPC.pm, src/backend/BSServer.pm, src/backend/bs_srcserver
- support maxage check in the server
- probe old socket for EOF before trying keepalive
=> [backend] improve keepalive implementation

src/api/app/controllers/build/file_controller.rb
Please read the description of the commit to know the reasoning behind the changes.
This popped up after investigating #14478 for the following endpoints:
- `GET /build/{project_name}/{repository_name}/{architecture_name}/{package_name}/_buildenv`
- `GET /build/{project_name}/{repository_name}/{architecture_name}/{package_name}/_statistics`
This is a refactoring pull request previous to changes planned to address #14478.
The code removed in this PR was introduced in #2924.
- Build a rpm package in your development environment.
- Check that calling an API enpoint to download a binary file makes the `regexp` method to return `false` always. This is the example of API endpoint call that I used: `curl -i -u Admin:opensuse "http://localhost:3000/build/home:Admin/15.5/x86_64/ctris/ctris-0.42.1-l …
=> Remove unreachable code in build/file controller

src/api/app/models/decision.rb, src/api/app/models/report.rb, src/api/app/queries/reports_finder.rb
Nothing fancy, just the usual callbacks in models to track what happened. With this information, I plan on having panels in our Grafana instance to answer the following questions:
=> Instrument the content moderation feature

src/api/app/controllers/person/token_controller.rb
Fix https://github.com/openSUSE/open-build-service/issues/14810
tl;dr
Handle and reject requests when `token`'s `operation` values are not valid.
Long version:
The former issue #14810 hits this scenario:
- user wants to create an `rss_token`
- he finds `token`'s endpoints to use
- he submit a `create token` request with an `operation` parameter value which is meant to be for an `rss` token
- eventually the `create token` allows any `operation` value in a fallback creating a `service token`, which is far away from the user's goal
The problem can be solved by two different actions:
1. document the `rss_token` creation (because at the moment I couldn't find it)
2. prevent creating a `token` if the `operation` value has no meaningful value (AKA only if it matches one of the possible values or …
=> Handle invalid request token operation values

src/api/app/controllers/webui/comment_locks_controller.rb, src/api/app/policies/comment_lock_policy.rb, src/api/config/routes/webui_routes.rb
Implements a controller that allows for creating and removing comment locks
=> Implement comment locking controller actions

src/api/app/views/webui/comment/_comment_field.html.haml, src/api/app/views/webui/shared/_locking_dialog.html.haml
=> Modal to lock comments on project|package|request

src/api/app/components/button_component.html.haml, src/api/app/components/button_component.rb, src/api/spec/components/button_component_spec.rb, src/api/spec/components/previews/button_component_preview.rb
Introduce button core [component](https://viewcomponent.org/) in order to standardize and reuse it
Previews available at http://obs-reviewlab.opensuse.org/ncounter-core-components/rails/view_components/button_component
Same as https://github.com/openSUSE/open-build-service/pull/15032
=> Core components: button

src/api/app/jobs/send_event_emails_job.rb
I'm trying to get more info into what is happening in the issue #6872. This should help to identify what is wrong exactly in emails causing issues.
=> Send email body in error reporting to help debug

src/api/app/controllers/status/required_checks_controller.rb, src/api/spec/controllers/status/required_checks_controller_spec.rb
=> Check existence of required check properly

src/api/app/components/bs_request_state_badge_component.rb, src/api/app/components/notification_component.html.haml, src/api/app/components/watched_items_list_component.html.haml, src/api/app/views/webui/request/_request_header.html.haml, src/api/app/views/webui/request/_show_overview.html.haml
=> Pass directly `state` instead of passing a request

src/api/app/controllers/source_controller.rb, src/api/app/models/project.rb
Instead of a single option opts hash...
=> Make includeallpackages a boolean keyword argument

src/backend/BSSched/PublishRepo.pm, src/backend/bs_srcserver, src/backend/bs_worker
Do not crash when the file name gets too big.
=> [backend] limit file name size of deltas when publishing

src/api/app/models/package.rb
- package -> package_name
- pkg -> package
- project -> project_name_or_object
- prj -> project
=> Use speaking variable names

src/api/app/controllers/trigger/errors.rb, src/api/app/controllers/trigger_controller.rb, src/api/spec/controllers/trigger_controller_spec.rb
For the operations rebuild, release and runservice
Fixes #12813
=> Enforce the presence of a package name in trigger#create

src/api/app/models/workflow/step/set_flags.rb, src/api/spec/models/workflow/step/set_flags_step_spec.rb
=> Write to backend for set_flag step

src/api/app/components/workflow_run_detail_component.html.haml
All titleized and of the same size.
**Before:**
=> Unify headers in the workflow run view

src/api/Gemfile, src/api/spec/support/capybara.rb
=> Prevent selenium-webdriver from being auto required

src/api/.rubocop_todo.yml, src/api/app/lib/suse/permission.rb, src/api/app/models/bs_request_action_maintenance_incident.rb, src/api/app/models/configuration.rb, src/api/app/models/issue_tracker.rb, src/api/app/models/project.rb, src/api/spec/controllers/webui/project_controller_spec.rb, src/api/spec/jobs/consistency_check_job_spec.rb, src/api/test/functional/source_controller_test.rb
=> Autocorrect some RuboCop offenses (IV)

src/backend/BSRPC.pm, src/backend/BSSigAuth.pm, src/backend/BSWatcher.pm
=> [backend] BSRPC: refactor cookiestore handling

src/api/spec/components/chart_component_spec.rb
Add missing code coverage for the chart component
=> Chart data test coverage

src/backend/bs_worker, src/backend/t/1000-bs_worker.t
Trying to reuse as much as possible from kiwi product building code.
TODO: localkiwi mode pendant if needed.
=> [backend] bs_worker: support product compose build mode

src/api/app/models/unregistered_user.rb, src/api/app/models/user.rb, src/api/db/migrate/20231120182646_add_rss_secret_to_user.rb, src/api/db/schema.rb
In preparation of introducing User.rss_secret
=> Add User.rss_secret column

src/api/app/components/bs_request_activity_timeline_component.rb
Fixes #15216.
Also fixes part of #15241. Thanks @hellcp-work for [the clue](https://github.com/openSUSE/open-build-service/issues/15241#issuecomment-1820627198).
=> Fix reply duplication

src/api/.database_consistency.todo.yml, src/api/app/models/unregistered_user.rb, src/api/app/models/user.rb, src/api/db/migrate/20231120182646_add_rss_secret_to_user.rb, src/api/db/schema.rb
Otherwise every new User will have an rss_secret generated.
=> Change User.rss_secret to default to ''

src/api/.database_consistency.todo.yml, src/api/app/models/unregistered_user.rb, src/api/app/models/user.rb, src/api/db/migrate/20231120182646_add_rss_secret_to_user.rb, src/api/db/schema.rb
Doesn't work either. Have to think about it more...
=> Revert "Change User.rss_secret to default to ''"

src/api/app/components/chart_component.html.haml, src/api/app/components/chart_component.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/services/action_build_results_service/chart_data_extractor.rb, src/api/app/views/webui/request/beta_show.html.haml, src/api/spec/components/chart_component_spec.rb, src/api/spec/components/previews/chart_component_preview.rb, src/api/spec/services/action_build_results_service/chart_data_extractor_spec.rb
Component has been refactored:
- raw data computation and extrapolation has moved away to a service
- logic conditions reduced and simplified
- filtering and mapping collections over loop computations
=> Reduce cognitive complexity of Chart component

src/api/app/controllers/source_controller.rb
Could be either a typo or a remote instance
=> [api] fix crash on invalid repository

src/backend/bs_publish
XXX-Media1 => XXX
XXX-Media2 => XXX-Source
XXX-Media3 => XXX-Debug
=> [backend] bs_publisher: support new media naming for slepool

src/api/spec/models/event_subscription/find_for_event_spec.rb
=> Simplify test for subscriptions creation

src/api/app/controllers/person_controller.rb, src/api/app/helpers/authentication_protocol_helper.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/lib/authenticator.rb, src/api/app/models/configuration.rb, src/api/app/views/layouts/webui/_login_form.html.haml, src/api/app/views/layouts/webui/_top_navigation.html.haml, src/api/app/views/webui/session/_form.html.haml
To retire the various implementations around the code base.
=> Introduces Configuration.proxy_auth_mode_enabled?

src/api/app/lib/backend/test/tasks.rb
Reduce duplication offenses reported by codeclimate.
Also, remove a method which was never used.
=> Refactor methods to run backend test tasks

src/api/spec/cassettes/Reports/reporting_a_comment_on_a_package/for_a_user_who_is_not_the_author/displays_the_You_reported_this_comment_message_instantly.yml, src/api/spec/cassettes/Reports/reporting_a_comment_on_a_package/for_a_user_who_is_the_author/does_not_display_the_report_link.yml, src/api/spec/cassettes/Reports/reporting_a_comment_on_a_project/for_a_user_who_is_not_the_author/displays_the_You_reported_this_comment_message_instantly.yml, src/api/spec/cassettes/Reports/reporting_a_comment_on_a_project/for_a_user_who_is_the_author/does_not_display_the_report_link.yml, src/api/spec/cassettes/Reports/reporting_a_comment_on_a_request/for_a_user_who_is_not_the_author/displays_the_You_reported_this_comment_message_instantly.yml, src/api/spec/cassettes/Reports/reporting_a_comment_on_a_request/for_a_user_who_is_the_author/does_not_display_the_report_link.yml, src/api/spec/cassettes/Reports/reporting_a_package/for_a_user_who_is_maintainer/does_not_display_the_report_link.yml, src/api/spec/cassettes/Reports/reporting_a_package/for_a_user_who_is_not_a_maintainer/displays_the_You_reported_this_package_message_instantly.yml, src/api/spec/cassettes/Reports/reporting_a_project/for_a_user_who_is_a_maintainer/does_not_display_the_report_link.yml, src/api/spec/cassettes/Reports/reporting_a_project/for_a_user_who_is_not_a_maintainer/displays_the_You_reported_this_project_message_instantly.yml, src/api/spec/features/beta/webui/reports_spec.rb
Test that user cannot report themself or the comments, projects and
packages they own.
=> Extend reports feature spec with more user roles

src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/canned_responses.js, src/api/app/components/canned_responses_dropdown_component.html.haml, src/api/app/components/canned_responses_dropdown_component.rb, src/api/app/components/reports_modal_component.html.haml, src/api/app/components/reports_modal_component.rb, src/api/app/controllers/webui/users/canned_responses_controller.rb, src/api/app/models/canned_response.rb, src/api/app/models/user.rb, src/api/app/policies/canned_response_policy.rb, src/api/app/views/webui/comment/_comment_field.html.haml, src/api/app/views/webui/user/_index_actions.html.haml, src/api/app/views/webui/user/index_actions/_manage_canned_responses.haml, src/api/app/views/webui/users/canned_responses/_breadcrumb_items.html.haml, src/api/app/views/webui/users/canned_responses/edit.html.haml, src/api/app/views/webui/users/canned_responses/index.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/cassettes/Comments/can_be_created_using_canned_responses.yml, src/api/spec/components/previews/canned_responses_dropdown_component_preview.rb, src/api/spec/factories/canned_responses.rb, src/api/spec/features/webui/canned_responses_spec.rb, src/api/spec/features/webui/comments_spec.rb
Depends on #15293 
To test:
1. Go to your profile
2. Click on canned responses in the sidebar
3. Create a new canned response
4. Open anything with an ability to comment on
5. See the comment box have an ability to use canned responses
=> Implement UI for canned responses feature

src/api/db/migrate/20231204093136_create_appeals.rb, src/api/db/schema.rb
This will support the implementation of the Appeal model.
=> Create the appeals table

src/api/app/helpers/webui/reportables_helper.rb, src/api/app/models/decision.rb, src/api/app/models/event/cleared_decision.rb, src/api/app/models/event/favored_decision.rb, src/api/app/views/event_mailer/cleared_decision.html.haml, src/api/app/views/event_mailer/cleared_decision.text.erb, src/api/app/views/event_mailer/create_report.html.haml, src/api/app/views/event_mailer/favored_decision.html.haml, src/api/app/views/event_mailer/favored_decision.text.erb, src/api/spec/factories/decisions.rb, src/api/spec/factories/event_subscriptions.rb, src/api/spec/mailers/event_mailer_spec.rb
=> Email notifications for events related to decisions

src/api/app/components/bs_request_comment_component.html.haml, src/api/app/components/token_card_component.html.haml, src/api/app/components/workflow_artifacts_per_step_component.rb, src/api/app/views/webui/patchinfo/form/_binaries.html.haml, src/api/app/views/webui/request/build_results.html.haml, src/api/app/views/webui/request/rpm_lint.html.haml, src/api/app/views/webui/shared/_buildresult_box.html.haml, src/api/app/views/webui/users/tokens/show.html.haml, src/api/spec/components/previews/card_component_preview.rb
This should have been included when migrating to Bootstrap 5.0.
=> Fix CSS class for italic font style

src/api/app/models/appeal.rb, src/api/app/models/event/appeal_created.rb, src/api/db/migrate/20231211120635_add_missing_foreign_key_constraints_to_appeals.rb, src/api/db/schema.rb
Extracted from https://github.com/openSUSE/open-build-service/pull/15319
This PR implement the Appeal Model and the corresponding Event required to trigger the notifications.
=> Add appeal model and event

src/api/app/services/action_build_results_service/chart_data_extractor.rb, src/api/spec/services/action_build_results_service/chart_data_extractor_spec.rb
=> Check if the request has any actions first

src/api/spec/services/action_build_results_service/chart_data_extractor_spec.rb
Lines 55 and 56 are testing the same thing
=> Drop redundant test

src/api/app/controllers/webui/appeals_controller.rb, src/api/app/policies/appeal_policy.rb, src/api/app/views/webui/appeals/_breadcrumb_items.html.haml, src/api/app/views/webui/appeals/_list_decision.html.haml, src/api/app/views/webui/appeals/_list_reports.html.haml, src/api/app/views/webui/appeals/new.html.haml, src/api/app/views/webui/appeals/show.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/factories/appeal.rb, src/api/spec/policies/appeal_policy_spec.rb
This is extracted from https://github.com/openSUSE/open-build-service/pull/15319
*TODO*
=> Create appeals controller, routes and views

src/api/app/controllers/trigger_controller.rb, src/api/app/controllers/trigger_workflow_controller.rb
We inherit from TriggerController in TriggerWorkflowController just for one `before_action`. We don't use anything else from TriggerController. This does not make much sense anymore.
=> Decouple the two /trigger controllers

src/api/app/policies/appeal_policy.rb, src/api/spec/policies/appeal_policy_spec.rb
=> Prevent appealing a decision for reports with a now-deleted reportable

src/api/app/assets/javascripts/webui/report.js, src/api/app/components/reports_notice_component.rb, src/api/app/models/bs_request.rb, src/api/app/policies/bs_request_policy.rb, src/api/app/policies/report_policy.rb, src/api/app/views/webui/request/_report_request.html.haml, src/api/app/views/webui/request/_request_header.html.haml, src/api/app/views/webui/request/_show_actions.html.haml, src/api/app/views/webui/request/beta_show.html.haml
- https://obs-reviewlab.opensuse.org/ncounter-report-a-request/request/show/1
- Click on the left side action link to `Report a Request`
- A modal dialog pops up
- Fill the report form at your wishes
- Submit the report
- Reload the Request page (to be improved by an autorefresh/autoupdate)
- Check at the Request header: a message about `You reported this request` is visible now
---
=> Report a request

src/api/app/components/notification_action_description_component.rb, src/api/app/components/notification_notifiable_link_component.rb, src/api/app/services/notification_service/notifier.rb
=> Implement notifications for reported request events

src/api/app/controllers/concerns/check_and_remove_repositories.rb, src/api/app/controllers/source_controller.rb, src/api/app/controllers/source_project_controller.rb, src/api/app/controllers/source_project_meta_controller.rb
Just moving code around to make more clear what an action is and what not.
=> Refactoring source controller

src/api/app/controllers/source_controller.rb
See [this discussion](https://github.com/openSUSE/open-build-service/pull/15406#discussion_r1433726996).
=> Fix typo: opossite -> opposite

src/api/.rubocop_todo.yml, src/api/spec/controllers/source_attribute_controller_spec.rb, src/api/spec/controllers/staging/staged_requests_controller_spec.rb, src/api/spec/controllers/webui/feeds_controller_spec.rb, src/api/spec/controllers/webui/project_controller_spec.rb, src/api/spec/controllers/webui/projects/rebuild_times_controller_spec.rb, src/api/spec/controllers/webui/repositories_controller_spec.rb, src/api/spec/controllers/webui/staging/projects_controller_spec.rb, src/api/spec/controllers/webui/staging/workflows_controller_spec.rb, src/api/spec/controllers/webui/users_controller_spec.rb, src/api/spec/jobs/send_event_emails_job_spec.rb, src/api/spec/models/attrib_spec.rb, src/api/spec/models/backend/file_spec.rb, src/api/spec/models/bs_request_action/differ/source_package_finder_spec.rb, src/api/spec/models/full_text_search_spec.rb, src/api/spec/models/kiwi/image_spec.rb, src/api/spec/models/package_spec.rb, src/api/spec/models/review_spec.rb, src/api/spec/models/status_message_spec.rb, src/api/spec/models/user_spec.rb, src/api/spec/models/workflow/step/configure_repositories_spec.rb, src/api/spec/models/workflow/step/set_flags_step_spec.rb, src/api/spec/services/notification_service/notifier_spec.rb
=> Autocorrect RSpec/MatchArray RuboCop offenses

src/api/app/controllers/webui/comments_controller.rb
=> Change local comment variables to instance variables in comments controller

src/api/app/services/rpmlint_log_extractor.rb
=> Fix channel parameter for rpmlint log metrics

src/api/app/assets/stylesheets/webui/diff.scss, src/api/app/components/bs_request_comment_component.html.haml, src/api/app/components/diff_component.html.haml, src/api/app/controllers/webui/comments_controller.rb, src/api/app/views/webui/comment/beta/_comments_thread.html.haml, src/api/app/views/webui/request/_inline_comment.html.haml, src/api/spec/cassettes/Comments_with_diff/reply_comment/when_under_the_beta_program/displays_the_changes_after_adding_a_new_comment.yml, src/api/spec/features/webui/requests/diff_comments_spec.rb
This removes the issue of diffs disappearing on actions on comments. Depends on #15500
=> Make diffs on comments render consistently

src/backend/BSBearer.pm, src/backend/BSRepServer/Registry.pm, src/backend/bs_dodup
=> [backend] support the proxy setting for DoD containers

src/backend/bs_publish
=> [backend] final publish .ova files

src/api/app/views/webui/user/_basic_info.html.haml, src/api/app/views/webui/users/show.html.haml
=> Show user state on user's page, only for admin users

src/api/app/controllers/webui/image_templates_controller.rb, src/api/spec/controllers/webui/image_templates_controller_spec.rb, src/api/spec/features/webui/image_templates_spec.rb
We want to provide access to the image templates page only to authenticated users.
=> Add authentication to the image templates page

src/api/db/migrate/20240201082303_add_blocked_from_commenting_to_users.rb, src/api/db/schema.rb
This field will be used to define if a user is blocked from creating comments.
=> Add column `blocked_from_commenting` to table users

src/backend/BSContar.pm, src/backend/BSPublisher/Container.pm, src/backend/BSPublisher/Registry.pm, src/backend/bs_worker
This should make publishing a tiny bit faster and the code more readable.
=> [backend] refactor container handling in in internal registry

src/api/app/controllers/webui/users_controller.rb, src/api/app/models/unregistered_user.rb, src/api/app/models/user.rb, src/api/app/policies/comment_policy.rb, src/api/app/views/webui/user/_basic_info.html.haml
These are two screenshots of the user interface after the changes of this pull request are applied:
=> Introduce blocking users from commenting

src/api/app/components/bs_request_comment_component.html.haml, src/api/app/components/bs_request_comment_component.rb, src/api/app/controllers/webui/users_controller.rb, src/api/app/helpers/webui/reportables_helper.rb, src/api/app/models/comment.rb, src/api/app/views/webui/user/_comments.html.haml, src/api/app/views/webui/user/_involvement_and_activity.html.haml, src/api/app/views/webui/users/show.html.haml
=> Revert "List all comments for a specific user #15542"

src/api/db/migrate/20240207080349_add_blocked_from_commenting_index_to_users.rb, src/api/db/schema.rb
Queries for this field will be performed in new users' measurements. See #15613.
=> Index blocking_from_commenting field in users table

src/api/app/views/webui/comment/_comment_list.html.haml, src/api/app/views/webui/comment/_content.html.haml
=> Allow to reply to inline comments

src/api/app/components/build_results_monitor_component.html.haml, src/api/app/components/build_results_monitor_component.rb, src/api/app/components/chart_component.html.haml, src/api/app/components/chart_component.rb, src/api/app/helpers/webui/buildresult_helper.rb
=> Align Build Results design for summary and details

src/backend/BSPublisher/Container.pm, src/backend/BSPublisher/Registry.pm, src/backend/BSSched/BuildJob/Aggregate.pm, src/backend/bs_publish, src/backend/bs_regpush, src/backend/bs_repserver
They must be named <container>.<type>.into.json and contain an intoto statement.
=> [backend] support custom intoto attestations

src/backend/BSSched/BuildJob/Patchinfo.pm
This commit makes the patchinfo generation more similar to product building. It does two things:
- it sorts the architecturs reverse lexicographically if the first arch is 'local'
- it uses orderpackids() for package sorting instead of just calling sort()
=> [backend] Patchinfo: tweak architecture and package ordering

src/api/app/components/notification_component.html.haml, src/api/app/components/notification_component.rb, src/api/app/components/notification_notifiable_link_component.rb, src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/helpers/webui/user_helper.rb, src/api/app/models/notification.rb, src/api/app/models/user.rb, src/api/app/views/webui/users/notifications/_notifications_list.html.haml, src/api/app/views/webui/users/notifications/index.html.haml, src/api/spec/components/notification_notifiable_link_component_spec.rb
- the link
- clicking the link of the non existing user
=> User page link only for non-deleted ones or Admin

src/api/app/models/user.rb
=> Drop stale user scopes

docs/api/api/comment_history.rng, src/api/app/controllers/comments_controller.rb, src/api/app/views/comments/history.xml.builder, src/api/config/routes/api_routes.rb, src/api/public/apidocs/OBS-v2.10.50.yaml, src/api/public/apidocs/components/schemas/comment_history.yaml, src/api/public/apidocs/paths/comment_comment_id_history.yaml, src/api/spec/controllers/comments_controller_spec.rb, src/api/spec/spec_helper.rb
This PR adds the ability to list the history of a comment through the API
=> Create comment history show api

.obs/workflows.yml
=> Trigger services for every push to the branch

.github/labeler.yml, .github/workflows/pull_request_labeler.yml
See the breaking changes here:
https://github.com/actions/labeler?tab=readme-ov-file#breaking-changes-in-v5
See ##15716
=> Bump actions/labeler from 4 to 5

src/backend/bs_publish
=> [backend] fix sequence of signargs in fixsleimage

src/api/.rubocop_todo.yml
=> Enable the RSpec/RepeatedSubjectCall cop again

src/api/spec/db/data/convert_notifications_event_payload_to_json_spec.rb, src/api/spec/db/data/migrate_comment_payload_spec.rb, src/api/spec/jobs/bs_request_action_webui_infos_job_spec.rb, src/api/spec/jobs/bs_request_clean_tasks_cache_job_spec.rb, src/api/spec/jobs/configuration_write_to_backend_job_spec.rb, src/api/spec/jobs/issue_tracker_fetch_issues_job_spec.rb, src/api/spec/jobs/issue_tracker_update_issues_job_spec.rb, src/api/spec/jobs/issue_tracker_write_to_backend_job_spec.rb, src/api/spec/jobs/package_update_if_dirty_job_spec.rb, src/api/spec/jobs/project_create_auto_cleanup_requests_job_spec.rb, src/api/spec/jobs/send_event_emails_job_spec.rb, src/api/spec/jobs/status_history_rescaler_job_spec.rb, src/api/spec/jobs/update_backend_infos_job_spec.rb, src/api/spec/jobs/update_package_meta_job_spec.rb, src/api/spec/jobs/update_packages_if_dirty_job_spec.rb, src/api/spec/jobs/update_released_binaries_job_spec.rb, src/api/spec/lib/authenticator_spec.rb, src/api/spec/lib/backend/api/search_spec.rb, src/api/spec/lib/pretty_nested_errors_spec.rb, src/api/spec/lib/tasks/user_admin_rights_spec.rb
=> Autocorrect RSpec/LeadingSubject RuboCop offenses, part II

src/api/app/controllers/source_project_controller.rb
Fix #15534, fix #15535, and fix #15536.
=> Prevent from crashing when requesting HTML from the API

src/api/spec/controllers/distributions_controller_spec.rb, src/api/spec/controllers/group_controller_spec.rb, src/api/spec/controllers/person/token_controller_spec.rb, src/api/spec/controllers/person_controller_spec.rb, src/api/spec/controllers/search_controller_spec.rb, src/api/spec/controllers/staging/excluded_requests_controller_spec.rb, src/api/spec/controllers/staging/staging_projects_controller_spec.rb, src/api/spec/controllers/statistics/maintenance_statistics_controller_spec.rb, src/api/spec/controllers/status/checks_controller_spec.rb, src/api/spec/controllers/status/reports_controller_spec.rb, src/api/spec/controllers/status_messages_controller_spec.rb, src/api/spec/controllers/trigger_controller_spec.rb, src/api/spec/controllers/webui/architectures_controller_spec.rb, src/api/spec/controllers/webui/cloud/ec2/upload_jobs_controller_spec.rb, src/api/spec/controllers/webui/comments_controller_spec.rb, src/api/spec/controllers/webui/groups/users_controller_spec.rb, src/api/spec/controllers/webui/kiwi/images_controller_spec.rb, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/spec/controllers/webui/packages/binaries_controller_spec.rb, src/api/spec/controllers/webui/project_controller_spec.rb, src/api/spec/controllers/webui/request_controller_spec.rb, src/api/spec/controllers/webui/staging/projects_controller_spec.rb, src/api/spec/controllers/webui/staging/workflows_controller_spec.rb, src/api/spec/controllers/webui/status_messages_controller_spec.rb, src/api/spec/controllers/webui/users/notifications_controller_spec.rb, src/api/spec/controllers/webui/users/tokens_controller_spec.rb, src/api/spec/controllers/worker/status_controller_spec.rb
=> Autocorrect RSpec/LeadingSubject RuboCop offenses, part III

src/api/app/components/bs_request_action_description_component.html.haml, src/api/app/components/bs_request_action_description_component.rb, src/api/app/helpers/webui/request_helper.rb, src/api/app/views/webui/request/_actions_details.html.haml, src/api/spec/components/previews/bs_request_action_description_component_preview.rb
Prepare the environment for https://github.com/openSUSE/open-build-service/pull/15794
=> Bs request action description component

src/api/app/components/sourcediff_component.html.haml, src/api/app/components/sourcediff_component.rb, src/api/app/views/webui/request/changes.html.haml, src/api/app/views/webui/request/request_action_changes.js.erb, src/api/spec/components/previews/sourcediff_component_preview.rb, src/api/spec/components/sourcediff_component_spec.rb
It's not really a parameter, as we always use 0 as index...
=> Remove useless index parameter from SourcediffComponent

src/api/app/components/bs_request_action_description_component.rb, src/api/spec/components/previews/bs_request_action_description_component_preview.rb
Fix https://github.com/openSUSE/open-build-service/issues/15848
=> Missing delegators

docs/api/api/channel.rng, docs/api/api/obs.rng, src/api/app/models/channel.rb, src/api/app/models/channel_binary.rb, src/api/db/migrate/20240319153505_add_supportstatus_superseded_by.rb, src/api/db/schema.rb, src/backend/BSSched/BuildJob/Channel.pm, src/backend/BSSched/BuildJob/Patchinfo.pm, src/backend/BSXML.pm, src/backend/bs_publish, src/backend/examples/createrepo_rpmmd_hook.pm
New support state of "support_superseded" with optional "support_superseded($SUPERSEDING_PACKAGE)"
OBS-301
=> [api][backend] add superseded handling for supportstatus

src/api/app/models/event/comment_for_package.rb, src/api/app/models/event/comment_for_project.rb
By the time we process the event...
Fixes #15855
=> Commented projects/packages might be gone

src/api/app/components/bs_request_history_element_component.html.haml, src/api/app/components/bs_request_history_element_component.rb
=> Expand the message about why the request was declined

src/api/app/models/workflow/step/link_package_step.rb, src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/for_a_new_PR_event/insufficient_permission_for_target_package/1_1_1_7_1.yml, src/api/spec/models/workflow/step/link_package_step_spec.rb
People should not be allowed to create links in Packages they can't write. And we are operating on a Package, so authorize the Package.
=> Fix LinkPackageStep authorization

.github/workflows/dependency-review-action.yml
https://github.com/actions/dependency-review-action
=> Introduces dependency review action

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/_actions_details.html.haml, src/api/app/views/webui/request/_request_header.html.haml, src/api/app/views/webui/request/_request_tabs.html.haml, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/build_results.html.haml, src/api/app/views/webui/request/changes.html.haml, src/api/app/views/webui/request/inline_comment.js.erb, src/api/app/views/webui/request/mentioned_issues.html.haml, src/api/app/views/webui/request/rpm_lint.html.haml
Since #15794 `@action` and `@active_action` and `@bs_request_action` are the same thing, this PR deduplicate them.
=> Deduplicate variables with the same scope

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/_actions_details.html.haml, src/api/app/views/webui/request/_request_header.html.haml, src/api/app/views/webui/request/_request_tabs.html.haml, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/build_results.html.haml, src/api/app/views/webui/request/changes.html.haml, src/api/app/views/webui/request/inline_comment.js.erb, src/api/app/views/webui/request/mentioned_issues.html.haml, src/api/app/views/webui/request/rpm_lint.html.haml
Do not over-create global variables: `@action_id` is used just once.
Depends on https://github.com/openSUSE/open-build-service/pull/15868
=> Extract id from existing object

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/_actions_details.html.haml, src/api/app/views/webui/request/_request_header.html.haml, src/api/app/views/webui/request/_request_tabs.html.haml, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/build_results.html.haml, src/api/app/views/webui/request/changes.html.haml, src/api/app/views/webui/request/inline_comment.js.erb, src/api/app/views/webui/request/mentioned_issues.html.haml, src/api/app/views/webui/request/rpm_lint.html.haml
All the types of `BsRequestAction` are now supported by the beta version too.
Depends on https://github.com/openSUSE/open-build-service/pull/15869
=> Drop supported actions

.github/workflows/dependency-review-action.yml
it fails
https://github.com/openSUSE/open-build-service/actions/runs/8418946907
=> Correct YAML syntax error

src/backend/BSSrcServer/Registry.pm, src/backend/bs_publish
=> [backend] BSSrcServer/Registry: add locking to own/disown repo

src/api/app/services/action_build_results_service/chart_data_extractor.rb
=> Remove nil elements from the array of build results

src/api/app/components/sourcediff_component.html.haml, src/api/app/views/webui/request/build_results.html.haml, src/api/app/views/webui/request/changes.html.haml, src/api/app/views/webui/shared/_loading.haml
The simple ` Loading <something> ...` with the spinning icon is a pattern to be reused: this PR makes it a reusable partial.
PS: this depends on https://github.com/openSUSE/open-build-service/pull/15887 , because that PR introduces two occurrences of this partial. Only the last commit is the target of this current PR
=> Loading partial

src/api/config/crawler-user-agents.json
I noticed this was missing after working on: #11300.
Related to: #10648.
=> Update list of crawler user agents

src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/models/workflow/step/link_package_step.rb, src/api/app/models/workflow/step/set_flags.rb
Help to identify when a store was triggered.
This was already done for the configure_repositories step.
=> Add comments to objects stored in SCM/CI steps

src/backend/bs_srcserver
This will be used for pagination in the web UI.
=> [backend] support a "startbefore" parameter in source _history queries

src/backend/bs_repserver
Support ftp tree and iso names of composer
=> [backend] support product compose name schema on release

src/api/app/controllers/concerns/scm_webhook_headers_data_extractor.rb, src/api/app/controllers/trigger_workflow_controller.rb, src/api/app/services/trigger_controller_service/scm_extractor.rb, src/api/spec/controllers/trigger_workflow_controller_spec.rb
Just some simple refactorings I came across while working on retiring SCMWebhook...
=> Refactoring TriggerWorkflowController

src/api/app/models/branch_package.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/for_a_new_commit_SCM_webhook_event/it_creates_the__branch_request_file/updates_the_url.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_skip_repositories_/when_add_repositories_is_disabled/sets_the_url_of_the_target_project_with_the_event_url_from_the_SCM_payload.yml, src/api/spec/models/workflow/step/branch_package_step_spec.rb
=> Set URL of target project when branching from SCM/CI

src/api/app/components/request_decision_component.html.haml, src/api/app/components/request_decision_component.rb, src/api/app/views/webui/request/beta_show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_conversation_aside.html.haml
Fixes https://github.com/openSUSE/open-build-service/issues/15918
=> Move the request decision hint closer to the decision buttons

src/api/app/models/token/errors.rb, src/api/app/models/token/workflow.rb, src/api/app/services/github_status_reporter.rb, src/api/app/services/gitlab_status_reporter.rb, src/api/app/services/workflows/yaml_downloader.rb, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_a_closed_PR/when_the_token_user_is_authorized/revokes_previous_submit_requests.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_a_newly_opened_PR/creates_a_submit_request.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_a_newly_opened_PR/creates_an_event_subcription.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_a_newly_opened_PR/creates_workflow_artifacts.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_a_push_event/creates_a_submit_request.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_a_push_event/creates_an_event_subcription.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_a_push_event/creates_workflow_artifacts.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_a_tag_push_event/creates_a_submit_request.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_a_tag_push_event/creates_workflow_artifacts.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_an_updated_PR/when_the_token_user_is_authorized/creates_the_workflow_artifact.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_an_updated_PR/when_the_token_user_is_authorized/supersedes_previously_created_submit_request_and_opens_a_new_one.yml, src/api/spec/cassettes/Workflow_Step_SubmitRequest/_call/for_an_updated_PR/when_the_token_user_is_not_authorized/does_not_supersede_the_previously_created_submit_request.yml, src/api/spec/models/token/workflow_spec.rb, src/api/spec/models/workflow/step/submit_request_step_spec.rb, src/api/spec/services/workflows/yaml_downloader_spec.rb
=> Revert "Refactor handling of unauthorized exceptions for SCM clients"

src/api/app/lib/gitea_api/v1/client.rb, src/api/app/services/gitea_status_reporter.rb, src/api/app/services/scm_exception_handler.rb
Not in GiteaStatusReporter that uses the Gitea client.
=> Handle connection errors in Gitea client

src/api/app/services/github_status_reporter.rb
That can happen during talking to github
=> Handle more Faraday connection errors

src/api/app/models/canned_response.rb, src/api/app/models/decision.rb, src/api/app/models/decision_favored_with_comment_moderation.rb, src/api/app/policies/decision_favored_with_comment_moderation_policy.rb, src/api/spec/factories/decision_favored_with_comment_moderation.rb, src/api/spec/models/decision_favored_with_comment_moderation_spec.rb
=> Add favor decision with comment moderation

src/api/app/controllers/webui/users/block_controller.rb, src/api/app/models/comment.rb, src/api/app/models/user.rb, src/api/app/policies/blocked_user_policy.rb, src/api/app/views/webui/user/_basic_info.html.haml, src/api/config/routes/webui.rb
This is how it looks like from inside a user's profile
Blocking a user:
Unblocking a user:
=> Add ui to create and remove user blocks

src/api/app/models/decision.rb
This is the first step in removing a column according to strong migrations
=> Add the Decision kind column to ignored columns

src/backend/bs_worker
Also cleaning up bs_worker compat code for OBS 2.5 and before schedulers.
OBS-307
=> [backend] add option to disable disturl in binaries

src/api/app/services/rpmlint_log_extractor.rb, src/api/spec/services/rpmlint_log_extractor_spec.rb
=> Ensure right encoding before checking for blank

src/api/public/apidocs/OBS-v2.10.50.yaml, src/api/public/apidocs/components/schemas/job_history_list.yaml, src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_jobhistory.yaml
Fixes #15638.
~Depends on #16081.~
=> Document `GET /build/#{project_name}/#{repository_name}/#{architecture_name}/_jobhistory` API endpoint

src/api/public/apidocs/OBS-v2.10.50.yaml, src/api/public/apidocs/components/schemas/image_templates.yaml, src/api/public/apidocs/paths/image_templates.yaml
=> Document `GET /image_templates` API endpoint

docs/api/api/api.txt, src/api/app/controllers/source_controller.rb, src/api/public/apidocs/paths/source_project_name_cmd_extendkey.yaml
Allowing the user to specify the number of days until expiry
=> [api] extendkey: make days parameter accessable

src/api/app/jobs/project_create_auto_cleanup_requests_job.rb, src/api/app/models/bs_request.rb, src/api/app/models/bs_request/find_for/query.rb, src/api/app/models/project.rb, src/api/app/models/staging/workflow.rb, src/api/app/models/user.rb, src/api/app/queries/notifications_finder.rb, src/api/db/data/20200326221616_regenerate_notifications.rb, src/api/spec/models/user_requests_spec.rb
A scope re-implementing `.where` is just obfuscation...
=> Drop BsRequest.in_states

src/api/app/controllers/concerns/webui/notifications_handler.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/reports_controller.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/controllers/webui/users_controller.rb
=> Refactor `handle_notification` method into a concern

src/backend/BSNotify.pm, src/backend/BSUtil.pm
The source server code cannot deal with it.
=> [backend] BSNotify: do not use chunked encoding for the payload

src/api/app/controllers/source_controller.rb, src/api/public/apidocs/OBS-v2.10.50.yaml, src/api/public/apidocs/paths/source_project_name_package_name_cmd_branch.yaml, src/api/public/apidocs/paths/source_project_name_package_name_cmd_fork.yaml, src/api/test/functional/source_controller_test.rb
* Do not insist on write permissions in the source (adapting test case for this as well)
* Complain about existing target package by default. Allowing overwrite via force parameter as the branch command behaves
* Also adding missing force parameter to branch api docu
=> [api] tune fork command error handling

src/api/app/models/canned_response.rb, src/api/app/models/decision_favored_with_user_commenting_restriction.rb
For CannedResponse and DecisionFavoredWithUserCommentingRestriction models.
=> Add missing annotations

src/api/app/models/event/relationship_create.rb, src/api/app/models/event/relationship_delete.rb, src/api/app/models/event/report_for_comment.rb, src/api/app/models/event/report_for_package.rb, src/api/app/models/event/report_for_project.rb, src/api/app/models/event/report_for_request.rb, src/api/app/models/event/report_for_user.rb
In this hash keys have been strings not symbols.
Fix how we access those and make this hash indifferent.
Fixes #16165
=> Fix how we access Event::Base.payload hash

src/api/app/controllers/webui/users_controller.rb, src/api/app/models/configuration.rb, src/api/app/views/webui/user/_basic_info.html.haml, src/api/app/views/webui/user/_index_actions.html.haml, src/api/app/views/webui/user/_info.html.haml, src/api/app/views/webui/users/show.html.haml, src/api/spec/models/configuration_spec.rb
=> Move configuration methods to class methods (II)

src/api/app/models/notification.rb
=> Add missing annotations for notification indexes

src/backend/BSSched/Checker.pm, src/backend/BSSched/PublishRepo.pm
This flag keeps the artefacts of deleted packages published. It is only checked if the project has publishing disabled.
=> [backend] Add "keepobsolete" publish flag

src/api/app/components/request_decision_component.html.haml, src/api/app/models/bs_request_action_submit.rb
Depends on https://github.com/openSUSE/open-build-service/pull/15794#
Refactoring action forward logic
=> Refactoring action forward logic

src/api/app/assets/stylesheets/webui/notifications.scss, src/api/app/components/notification_notifiable_link_component.rb, src/api/app/controllers/webui/appeals_controller.rb, src/api/app/controllers/webui/packages/build_log_controller.rb, src/api/app/controllers/webui/workflow_runs_controller.rb, src/api/app/views/webui/packages/build_log/live_build_log.html.haml
Displays the notification bar on the remaining notification types. Every link should now be covered.
To verify:
1. Create a notification of every type
2. Click on links in notifications
3. Each one should have a notification bar
=> Implement notification bars in remaining views

src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/multi_select.js, src/api/app/components/notification_filter_component.html.haml, src/api/app/views/webui/shared/_check_box.haml, src/api/spec/features/webui/users/notifications_spec.rb
|Before|After|
|:---|:---|
|![Screenshot from 2024-05-31 16-15-22](https://github.com/openSUSE/open-build-service/assets/114928900/bdaff772-329f-4cf5-b237-3e2f7f72e037)|![Screenshot from 2024-05-31 16-14-57](https://github.com/openSUSE/open-build-service/assets/114928900/541b9265-fc77-4b6e-b381-06caa4b6a1f6)|
=> Display projects and group in multi select

src/api/app/components/notification_filter_component.rb
=> Only count unread and read notifications

src/backend/BSSched/BuildJob/KiwiProduct.pm, src/backend/BSSched/BuildJob/ProductCompose.pm
We need to do a rebuild if the updateinfo is changed, e.g. if a patchinfo gets retracted.
=> [backend] put productcompose: add updateinfo.xml to the meta

src/api/app/controllers/webui/users/notifications_controller.rb
Follow up of https://github.com/openSUSE/open-build-service/pull/16257
Bring back the notification counting
=> Reintroduce notifications counting

src/api/app/controllers/webui/users/notifications_controller.rb
Prevent from performing an unnecessary SQL query against the database.
=> Calculate number of read notifications with a substraction

src/api/app/components/workflow_run_filter_component.html.haml, src/api/app/views/webui/workflow_runs/index.html.haml
Do not use an Apply button to submit multiple filters, apply one by one as soon as they are clicked (with just a bit of a delay to collect multiple clicks).
**Note**: the delay has been set to an arbitrary value of **1.5 second** (intended to be "let the user clicks multiple times, but do now wait too long if he is finished clicking")
=> Apply workflowrun filters onclick

src/api/app/components/notification_action_bar_component.html.haml, src/api/app/components/notification_action_bar_component.rb, src/api/app/components/notification_component.html.haml, src/api/app/components/notification_component.rb, src/api/app/components/notification_notifiable_link_component.rb, src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/views/webui/users/notifications/_notifications_list.html.haml, src/api/app/views/webui/users/notifications/_update.js.erb, src/api/app/views/webui/users/notifications/index.html.haml, src/api/spec/components/notification_action_bar_component_spec.rb, src/api/spec/components/notification_component_spec.rb, src/api/spec/components/notification_notifiable_link_component_spec.rb, src/api/spec/components/previews/notification_action_bar_component_preview.rb
Some refactorings I came across while thinking about this controller...
Is based on #16257 and need this to be merged
=> Refactoring Webui::Users::NotificationsController

src/backend/BSSched/BuildJob/Aggregate.pm, src/backend/BSSched/PublishRepo.pm
Use this to make sure we do not delete container blobs that are still needed.
=> [backend] PublishRepo: record all file conflicts in the repoinfo

.gitignore
Also use one style to reference to specific files.
=> Git ignore .ackrc

src/api/app/models/concerns/has_relationships.rb, src/api/app/views/webui/user/_involvement.html.haml
Prevent from performing N+1 queries.
Related to #10332 and #16300.
In your development environment:
- Browse http://localhost:3000/users/Admin
- Note the difference in amount and duration of requests taking a look at the frontend logs.
=> Improve query to check involved item user roles

src/api/app/controllers/webui/search_controller.rb, src/api/app/views/webui/search/owner.html.haml
=> Ignore non-sensical parameters on the search

src/api/app/components/patchinfo_component.html.haml, src/api/app/components/reports_modal_component.html.haml, src/api/app/components/user_avatar_component.rb, src/api/app/views/webui/comment/_history.html.haml, src/api/app/views/webui/reports/show.html.haml, src/api/app/views/webui/request/beta_show_tabs/_conversation_aside.html.haml, src/api/spec/components/user_avatar_component_spec.rb
Prevent from performing a user search by login on each rendering of an user avatar.
=> Refactor UserAvatarComponent component

src/backend/BSRepServer.pm, src/backend/BSSched/BuildResult.pm
Looking for "updateinfo.xml" is not reliable since we added the "no_updateinfo" category.
=> [backend] also detect patchinfo results by the .updateinfodata file

src/api/app/components/build_results_monitor_component.html.haml, src/api/app/services/action_build_results_service/chart_data_extractor.rb, src/api/app/views/webui/shared/_build_status_badge.html.haml, src/api/spec/components/previews/build_results_monitor_component_preview.rb
Fixes https://github.com/openSUSE/open-build-service/issues/16372
=> Bugfix: add missing details information for request build result badge

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/packages/badge_controller.rb, src/api/app/controllers/webui/packages/binaries_controller.rb, src/api/app/controllers/webui/packages/branches_controller.rb, src/api/app/controllers/webui/packages/bs_requests_controller.rb, src/api/app/controllers/webui/packages/build_reason_controller.rb, src/api/app/controllers/webui/packages/files_controller.rb, src/api/app/controllers/webui/packages/job_history_controller.rb, src/api/app/controllers/webui/packages/main_controller.rb, src/api/app/controllers/webui/packages/meta_controller.rb, src/api/app/controllers/webui/repositories_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/spec/controllers/webui/packages/binaries_controller_dependency_spec.rb, src/api/spec/controllers/webui/packages/binaries_controller_destroy_spec.rb, src/api/spec/controllers/webui/packages/binaries_controller_spec.rb, src/api/spec/controllers/webui/packages/build_reason_controller_spec.rb, src/api/spec/controllers/webui/packages/job_history_controller_spec.rb, src/api/spec/controllers/webui/repositories_controller_spec.rb
By moving `set_repository` and `set_architecture` to `Webui::WebuiController`
=> Refactoring Packages::MainController away

src/api/app/controllers/webui/projects/pulse_controller.rb, src/api/app/helpers/webui/project_helper.rb, src/api/app/views/webui/projects/pulse/show.html.haml, src/api/app/views/webui/projects/pulse/show.js.erb
Fixes https://github.com/openSUSE/open-build-service/issues/16221
=> Bugfix: reuse already computed range dates

src/api/app/components/workflow_run_row_component.html.haml, src/api/app/views/webui/workflow_runs/_event_links.html.haml
You can take a look at the workflow runs page in the review-app:
- https://obs-reviewlab.opensuse.org/eduardoj-featurefilter_workflow_runs_by_event_source/my/tokens/1/workflow_runs
=> Filter workflow runs by event source

src/backend/bs_worker, src/backend/t/1000-bs_worker.t
Add flags to capture preinstall/vminstall settings. Use 'sysroot' as intent for sysroot packages.
=> [backend] improve slsa provenance v1 data

src/api/app/components/chart_component.html.haml
Fixes https://github.com/openSUSE/open-build-service/issues/16414
=> Bugfix: undefined local variable for the chart occurrence

src/api/app/services/scm_status_reporter.rb, src/api/spec/models/token/workflow_spec.rb
Closing PR's is something we do not need to report
=> Do not report to the SCM when its not needed

src/api/app/services/user_service/involved.rb
Get rid of redundant guard clauses. Instead, call directly to methods which return a boolean.
=> Small refactoring of service user involved

src/api/app/models/bs_request.rb, src/api/app/models/bs_request_action.rb, src/api/app/policies/bs_request_policy.rb
Fixes https://github.com/openSUSE/open-build-service/issues/16105
=> Bugfix: let source maintainer revoke a request

src/api/app/services/notification_service/notifier.rb
A small refactoring toward conditions readability and logic flow.
=> Refactoring conditions logic for creating notification

src/api/public/apidocs/OBS-v2.10.50.yaml, src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_builddepinfo.yaml, src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_package_name_history.yaml, src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_package_name_status.yaml, src/api/public/apidocs/paths/request_id_cmd_diff.yaml, src/api/public/apidocs/paths/source_project_name_cmd_addchannels.yaml, src/api/public/apidocs/paths/source_project_name_package_name_cmd_collectbuildenv.yaml, src/api/public/apidocs/paths/source_project_name_package_name_cmd_copy.yaml, src/api/public/apidocs/paths/source_project_name_package_name_cmd_createSpecFileTemplate.yaml, src/api/public/apidocs/paths/source_project_name_package_name_cmd_rebuild.yaml, src/api/public/apidocs/paths/statistics_deprecated_not_documented_project_name.yaml, src/api/public/apidocs/paths/statistics_deprecated_not_documented_project_name_package_name.yaml
=> Fix OpenAPI specification to be able to generate code for an API client

src/api/app/models/branch_package.rb
=> [api] fix branching from remote project using extended name option

dist/obs-server.spec
=> [dist] add Requires of procps for obs-api package

src/backend/BSPublisher/Container.pm, src/backend/bs_regpush
--missingok: do not die if the repository does not exist
--with-platforms: add a "platforms" info if the tag is an index
--listidx: list submanifests if the tag is an index
--listidx-noinfo: list submanifests with no extra info
--manifestinfo: show manifestinfo for images
--manifestinfoserver: use a different server for manifestinfo queries
=> [backend] bs_regpush: add a couple of list options

src/api/app/models/project/update_from_xml_command.rb, src/api/test/unit/project_test.rb
=> [api] fix project kind removal

src/api/app/models/project.rb, src/api/db/migrate/20240705121900_change_scmsync_type.rb, src/api/db/schema.rb
We are about to run into the 255 byte limit
=> [api] increase length limit of project scmsync elements

src/api/app/controllers/public_controller.rb
=> Prevent from crashing when requesting JSON from the API

src/api/app/controllers/source_project_meta_controller.rb, src/api/spec/controllers/source_project_meta_controller_spec.rb
=> [api] fix creation of a project above an interconnect project

src/api/app/models/user.rb
Also remove Event Subscriptions.
=> [api] improve cleanup on user removal

src/api/app/models/event/added_user_to_group.rb, src/api/app/models/event/build.rb, src/api/app/models/event/cleared_decision.rb, src/api/app/models/event/comment_event.rb, src/api/app/models/event/create_report.rb, src/api/app/models/event/favored_decision.rb, src/api/app/models/event/removed_user_from_group.rb, src/api/app/models/event/report.rb, src/api/app/models/event/request_create.rb, src/api/app/models/event/request_statechange.rb, src/api/app/models/event/review_wanted.rb, src/api/app/models/event/workflow_run_fail.rb, src/api/app/models/notification.rb, src/api/app/models/notification_bs_request.rb, src/api/app/models/notification_comment.rb, src/api/app/models/notification_group.rb, src/api/app/models/notification_package.rb, src/api/app/models/notification_project.rb, src/api/app/models/notification_report.rb, src/api/app/models/notification_workflow_run.rb, src/api/db/migrate/20240710083919_add_type_column_to_notifications.rb, src/api/db/schema.rb, src/api/lib/tasks/backfill_notifications_type.rake
=> Add the type to the notification model to make it a sti model

src/api/app/assets/stylesheets/webui/requests.scss, src/api/app/controllers/concerns/webui/requests_filter.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/views/layouts/webui/_places.html.haml, src/api/app/views/webui/request/_breadcrumb_items.html.haml, src/api/app/views/webui/request/_request_item.html.haml, src/api/app/views/webui/request/_requests_filter.html.haml, src/api/app/views/webui/request/index.html.haml, src/api/config/routes/webui.rb
Implements the base view for indexing the requests
=> Implement skeleton for request index feature

src/api/app/assets/stylesheets/webui/bootstrap_variables/colors.scss, src/api/app/assets/stylesheets/webui/mixin.scss, src/api/app/assets/stylesheets/webui/requests.scss
=> Highlight on request item hover

src/api/app/assets/stylesheets/webui/bootstrap_variables/colors.scss, src/api/app/assets/stylesheets/webui/mixin.scss, src/api/app/assets/stylesheets/webui/requests.scss, src/api/app/views/webui/request/_request_item.html.haml
As discussed in https://github.com/openSUSE/open-build-service/pull/16523#issuecomment-2238887799
=> Do not reinvent the wheel, boostrap already did it

src/api/app/indices/bs_request_index.rb, src/api/app/jobs/populate_to_sphinx_job.rb, src/api/app/models/bs_request.rb, src/api/app/models/comment.rb, src/api/app/models/review.rb, src/api/spec/components/bs_request_overview_avatars_component_spec.rb, src/api/spec/controllers/staging/staged_requests_controller_spec.rb, src/api/spec/helpers/webui/notification_helper_spec.rb, src/api/spec/models/review_spec.rb, src/api/spec/policies/bs_request_policy_spec.rb
=> Add ThinkingSphinx indices to BsRequest model

README.md
=> Add Repobeats Contribution Analytics to README.md

src/api/app/assets/stylesheets/webui/requests.scss, src/api/app/controllers/concerns/webui/requests_filter.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/_requests_filter.html.haml, src/api/app/views/webui/request/index.html.haml
=> Introduce text search for submit requests

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/_requests_filter.html.haml, src/api/app/views/webui/request/index.html.haml, src/api/spec/features/beta/webui/requests_index_spec.rb
*TODO*:
- ~~Add specs~~
- ~~Rebase to include changes of https://github.com/openSUSE/open-build-service/pull/16528~~
=> Add filter for request creator to request index view

src/api/app/assets/stylesheets/webui/application.scss, src/api/app/assets/stylesheets/webui/label.scss, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui/shared/_label.html.haml
=> Create a label partial

src/api/app/components/workflow_run_filter_component.html.haml, src/api/app/views/webui/request/_requests_filter.html.haml, src/api/app/views/webui/users/notifications/_notification_filter.html.haml
Compare the spacing between each other checkbox, radio, etc. This PR reduces a bit the spacing and aligns it for the 3 occurrences of the same filter pattern UI.
Ps: it might be arguable the workflow_run ones miss a bit of icons, but this is going to be tackled separately later.
=> Filters spacing alignments

src/api/app/controllers/webui/projects/label_templates_controller.rb, src/api/app/policies/label_template_policy.rb, src/api/app/views/webui/projects/label_templates/edit.html.haml, src/api/app/views/webui/projects/label_templates/index.html.haml, src/api/config/routes/webui.rb
Depends on #16615
This is how it looks like
=> Edit label templates

src/api/app/controllers/webui/projects/label_templates_controller.rb, src/api/app/models/label_template.rb, src/api/app/policies/label_template_policy.rb, src/api/app/views/webui/projects/label_templates/index.html.haml
Depends on #16647
**This is how it looks like**
=> Delete label templates

src/api/app/controllers/webui/labels_controller.rb, src/api/app/models/package.rb, src/api/app/policies/package_policy.rb, src/api/app/views/webui/shared/_label_form.html.haml, src/api/app/views/webui/shared/_label_list.html.haml, src/api/config/routes/webui.rb, src/api/spec/controllers/webui/labels_controller_spec.rb
Implements a controller and base shared views for future implementation in package (https://github.com/openSUSE/open-build-service/pull/16630) and request views
=> Create a labels controller and shared views

src/api/app/views/webui/package/show.html.haml, src/api/app/views/webui/shared/_label.html.haml
=> Allow adding labels on packages

src/api/app/models/package.rb, src/api/app/models/project.rb, src/api/app/models/remote_project.rb, src/api/db/migrate/20240808084541_change_report_bug_url_to_string.rb, src/api/db/schema.rb
A limit of `65_535` is a bit excesive for a URL.
=> Change type of `report_bug_url` field from `text` to `string`

src/api/app/controllers/webui/labels_controller.rb, src/api/app/helpers/webui/request_helper.rb, src/api/app/models/bs_request.rb, src/api/app/policies/bs_request_policy.rb, src/api/app/views/webui/request/_request_header.html.haml, src/api/spec/factories/label.rb, src/api/spec/features/beta/webui/requests_labels_spec.rb
=> Labeling requests

src/api/app/models/issue_tracker.rb, src/api/app/models/token.rb, src/api/app/models/token/rebuild.rb, src/api/app/models/token/release.rb, src/api/app/models/token/service.rb, src/api/app/models/token/workflow.rb, src/api/db/migrate/20240808133204_increase_limit_of_url_fields.rb, src/api/db/schema.rb
=> Increase limit of some URL fields

src/api/app/controllers/webui/projects/label_templates_controller.rb, src/api/app/views/webui/projects/label_templates/_form.html.haml, src/api/spec/features/webui/projects/label_template_spec.rb
Depends on #16648
This is a basic test coverage to ensure the happy path for the label template feature does not break
=> Feature tests for label template feature

src/api/.rubocop_todo.yml, src/api/app/controllers/source_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/packages/badge_controller.rb, src/api/app/controllers/webui/projects/maintenance_incidents_controller.rb, src/api/app/helpers/webui/staging/workflow_helper.rb, src/api/app/models/bs_request.rb, src/api/app/models/concerns/multibuild_package.rb, src/api/app/models/maintenance_incident.rb, src/api/app/models/package.rb, src/api/app/models/project.rb, src/api/app/views/webui/staging/workflows/_requests_list.html.haml, src/api/spec/models/badge_spec.rb, src/api/spec/models/concerns/multibuild_package_spec.rb
=> Manually fix Style/OptionalBooleanParameter RuboCop offenses (II)

src/api/.rubocop_todo.yml, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui/configuration/_tabs.html.haml, src/api/app/views/webui/package/_tabs.html.haml, src/api/app/views/webui/project/_tabs.html.haml, src/api/app/views/webui/search/_tabs.html.haml
=> Manually fix Style/OptionalBooleanParameter RuboCop offenses (IV)

src/api/app/controllers/concerns/webui/notifications_filter.rb, src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/models/report.rb, src/api/app/views/webui/users/notifications/_notification_filter.html.haml, src/api/spec/controllers/webui/users/notifications_controller_spec.rb
=> Filter notifications by reports with/without decision and reportable type

src/api/app/assets/javascripts/webui/buildresult.js
=> Identify repository by `name` instead of by `id`

src/api/app/controllers/webui/packages/meta_controller.rb
=> Add missing exceptions to rescue from saving a meta of a package

src/api/.rubocop_todo.yml, src/api/app/helpers/maintenance_helper.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/bs_request_action_maintenance_incident.rb, src/api/app/models/bs_request_action_maintenance_release.rb, src/api/app/models/bs_request_action_release.rb, src/api/app/models/bs_request_action_submit.rb, src/api/test/functional/search_controller_test.rb
=> Manually fix the rest of Naming/AccessorMethodName RuboCop offenses

src/backend/BSSched/BuildJob/Docker.pm
A container can depend on another container in the same project that needs to be built first. Thus, we need to do the expansion before sorting the packages.
=> [backend] Docker: expand container dependencies before sorting packages

src/api/app/models/event_subscription.rb
=> Clarify wording for report and decision subscription UI

src/backend/BSSched/BuildJob/Package.pm, src/backend/BSSched/Lookat.pm
We need to look at the indirect project dependencies as well, so that projects get checked even if they do not have a direct dependency to a changed project. Otherwise projects might get stuck with packages being in the "blocked" state.
=> [backend] extend lookat_next with indirect entries as well

dist/obs-server.spec
Let's recommend it instead of maintain the same deps in two places.
=> [dist] follow deps of build script in obs-worker

src/api/config/initializers/active_storage_cache_control.rb
Making sure that files provided by active storage are cached
=> Cache images from active storage

src/backend/bs_publish
Oops. Should have been in commit b2792e16c1c2c47144e7fb540ebcbc6595df2874
=> [backend] put binaryid in the tracker cache

src/api/app/views/webui/package/_show_actions.html.haml, src/api/app/views/webui/package/show.html.haml, src/api/app/views/webui/project/_show_actions.html.haml, src/api/app/views/webui/project/show.html.haml, src/api/app/views/webui/request/_actions.html.haml, src/api/app/views/webui/request/_lock_unlock_comment.html.haml, src/api/app/views/webui/request/_show_actions.html.haml, src/api/app/views/webui/shared/_lock_unlock_comment.html.haml, src/api/spec/cassettes/CommentLocks/on_a_package/with_comments_locked/a_moderator_user/checks_comments_are_locked.yml, src/api/spec/cassettes/CommentLocks/on_a_package/with_comments_locked/a_moderator_user/unlocks_comments.yml, src/api/spec/cassettes/CommentLocks/on_a_package/with_comments_unlocked/a_moderator_user/checks_comments_are_unlocked.yml, src/api/spec/cassettes/CommentLocks/on_a_package/with_comments_unlocked/a_moderator_user/locks_comments.yml, src/api/spec/cassettes/CommentLocks/on_a_project/with_comments_locked/a_moderator_user/checks_comments_are_locked.yml, src/api/spec/cassettes/CommentLocks/on_a_project/with_comments_locked/a_moderator_user/unlocks_comments.yml, src/api/spec/cassettes/CommentLocks/on_a_project/with_comments_unlocked/a_moderator_user/checks_comments_are_unlocked.yml, src/api/spec/cassettes/CommentLocks/on_a_project/with_comments_unlocked/a_moderator_user/locks_comments.yml, src/api/spec/features/webui/comment_locks_spec.rb
This was missing in the last PR, this reintroduces locking comments everywhere now
=> Make sure project and package comments can be locked

src/backend/BSSched/BuildJob/Docker.pm
We now have an annotation in DoD containers as well, so also check for the "registry_digest" entry.
=> [backend] tweak automatic obsrepositories mode for DoD containers

src/api/app/views/webui/request/_request_item.html.haml
=> Display labels in request index

src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/dropdown.js, src/api/app/views/webui/shared/_label_form.html.haml
Adds the ability to search and close the dropdown with a button
=> Improve the user experience of using the labels dropdown

src/api/app/datatables/package_datatable.rb, src/api/app/helpers/webui/project_helper.rb, src/api/app/views/webui/project/_project_packages.html.haml
=> Make use of Package Labels and filter by them too

src/backend/bs_admin
make it easy to switch a obsservice server to use service containers
=> [backend] avoid useless warnings in bs_admin

src/backend/BSConfig.pm.template
Use new image name of podman images (replacing old docker container name)
=> [dist] fix container_image default in BSConfig.pm.template

src/api/app/components/write_and_preview_component.html.haml, src/api/app/components/write_and_preview_component.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui/package/_edit.html.haml, src/api/app/views/webui/package/new.html.haml, src/api/app/views/webui/project/_edit.html.haml, src/api/app/views/webui/project/_form.html.haml, src/api/app/views/webui/status_messages/edit.html.haml, src/api/app/views/webui/status_messages/new.html.haml, src/api/config/routes/webui.rb
=> Markdown preview for package and project description

src/api/app/controllers/concerns/scmsync_checker.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/packages/files_controller.rb, src/api/spec/controllers/webui/packages/files_controller_spec.rb
Avoid throwing a 500 error.
Fixes #16686.
=> Show an error message for files of a package of a scmsync project

src/api/app/controllers/webui/projects/label_templates_controller.rb, src/api/app/views/webui/projects/label_templates/_preview.html.haml, src/api/app/views/webui/projects/label_templates/copy.html.haml, src/api/app/views/webui/projects/label_templates/index.html.haml, src/api/config/routes/webui.rb, src/api/spec/features/webui/projects/label_template_spec.rb
=> Allow for copying label templates from other projects

src/api/app/controllers/application_controller.rb, src/api/test/functional/request_controller_test.rb
Fixes #10649.
Related to #16886.
=> First, perform user authentication. Then, XML validation

src/backend/bs_worker
The new code should be much easier to understand.
Also fix indentation of updatestatsfromfile().
=> [backend] refactor exit status handling of the build call

src/api/app/controllers/webui/request_controller.rb, src/api/config/routes/webui.rb, src/api/spec/cassettes/Requests_Submissions/submit_package/when_under_the_beta_program/a_request_that_has_a_broken_comment/displays_the_comment_in_the_timeline.yml, src/api/spec/cassettes/Requests_Submissions/submit_package/when_under_the_beta_program/submit_several_packages_at_once_against_a_factory_staging_project/shows_the_beta_version_of_the_requests_page.yml, src/api/spec/helpers/webui/request_helper_spec.rb
Also moves the request show action for beta users to `beta_show`, to make this code simpler, not having to map two routes to the same action.
=> Standardize the URL style for request show pages

src/api/app/components/diff_component.html.haml, src/api/app/components/diff_component.rb, src/api/app/components/diff_list_component.html.haml, src/api/app/components/diff_list_component.rb, src/api/app/components/sourcediff_component.html.haml, src/api/app/controllers/webui/comments_controller.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/lib/routes_helper/routes_constraints.rb, src/api/app/models/comment.rb, src/api/app/views/webui/comment/_comment_field.html.haml, src/api/app/views/webui/request/_add_inline_comment.html.haml, src/api/app/views/webui/request/_inline_comment.html.haml, src/api/app/views/webui/request/inline_comment.js.erb, src/api/db/migrate/20241017103843_add_source_rev_and_target_rev_to_comments.rb, src/api/db/schema.rb, src/api/spec/cassettes/SourcediffComponent/when_testing_the_preview/renders_the_preview.yml, src/api/spec/cassettes/SourcediffComponent/with_a_request_with_a_submit_action/renders_the_diff.yml
Stores additional info in the database to display the correct diff for when the comment was created.
=> Accept source_rev and target_rev attributes in comments

src/backend/BSPublisher/Diffnotify.pm
And add a hack to get the flavor from the disturl if the published package contains no flavor.
=> [backend] Diffnotify: also put the disturl in the binary data

src/api/.rubocop_todo.yml, src/api/app/components/bs_request_activity_timeline_component.rb, src/api/app/components/bs_request_comment_component.html.haml, src/api/app/controllers/webui/comments_controller.rb, src/api/app/models/bs_request_action/differ/for_source.rb, src/api/app/models/bs_request_action_submit.rb, src/api/app/models/comment.rb, src/api/spec/cassettes/Comments_with_diff/reply_comment/when_under_the_beta_program/displays_the_changes_after_adding_a_new_comment.yml
Uses the revs from the comment to display the correct diff.
=> Make use of the revs in the comments to display the right diff

src/api/app/components/request_decision_component.html.haml, src/api/app/components/request_decision_component.rb, src/api/app/controllers/webui/comments_controller.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/models/concerns/build_new_comment.rb, src/api/app/views/webui/request/beta_show.html.haml
This is how it looks like now
https://obs-reviewlab.opensuse.org/danidoni-combine-the-comment-and-the-review-decision-boxes/requests/1
=> Combine the comment and the review decision boxes

src/api/app/components/request_decision_component.html.haml
This is how it looked like before
And this is how it looks like now
=> Add a bit of space above decision buttons

src/api/app/controllers/concerns/webui/requests_filter.rb, src/api/app/controllers/webui/requests_listing_controller.rb, src/api/app/helpers/webui/request_helper.rb, src/api/app/models/bs_request/find_for/base.rb, src/api/app/models/bs_request/find_for/query.rb, src/api/app/views/webui/requests_listing/_requests_filter.html.haml, src/api/app/views/webui/requests_listing/index.html.haml
This PR is based on #17023. It introduces some minor refactoring to make  filtering more general.
=> Refactor request listing

src/api/spec/components/previews/bs_request_action_description_component_preview.rb
`BsRequestActionDescriptionComponent` has no `creator` parameter
=> Fix BsRequestActionDescriptionComponent preview

src/api/app/controllers/concerns/webui/requests_filter.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/requests_listing_controller.rb, src/api/app/helpers/webui/request_helper.rb, src/api/app/models/bs_request/find_for/query.rb, src/api/app/queries/open_requests_finder.rb, src/api/app/views/webui/project/_tabs.html.haml, src/api/app/views/webui/requests_listing/_breadcrumb_items.html.haml, src/api/app/views/webui/requests_listing/index.html.haml, src/api/config/routes/webui.rb, src/api/spec/features/beta/webui/project_requests_spec.rb
Depends on #17025. This PR accomplishes the following tasks:
=> Move project requests to a requests listing 

src/api/app/controllers/concerns/webui/requests_filter.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/requests_listing_controller.rb, src/api/app/views/webui/package/_tabs.html.haml, src/api/app/views/webui/requests_listing/_breadcrumb_items.html.haml, src/api/app/views/webui/requests_listing/index.html.haml, src/api/config/routes/webui.rb, src/api/spec/features/beta/webui/package_requests_spec.rb
Replaces the existing requests list with the new one that was developed over the period of the last few sprints
=> Add the new package request listing page

src/api/app/components/diff_component.html.haml
=> Fix the ability to submit comments on diffs

src/api/app/controllers/webui/request_controller.rb
=> Show notification toolbar missed for some notifications' types

src/api/app/controllers/webui/groups_controller.rb, src/api/app/models/notification_group.rb
=> Show notification toolbar for Group Membership changes

src/api/app/controllers/webui/package_controller.rb
=> Don't try to show users of packages of a scmsync project

src/api/app/controllers/webui/repositories_controller.rb
=> Don't try to manage repositories of packages of scmsync projects

src/api/app/controllers/webui/packages/job_history_controller.rb
=> Don't try to show the job history of a package of a scmsync project

src/api/config/crawler-user-agents.json
=> Update crawlers list

src/api/.rubocop_todo.yml, src/api/app/controllers/concerns/backend_proxy.rb, src/api/app/controllers/source_controller.rb, src/api/app/controllers/webui/projects/rebuild_times_controller.rb, src/api/app/lib/backend/file.rb, src/api/app/lib/backend/logger.rb, src/api/app/lib/backend/test.rb, src/api/app/lib/backend/test/tasks.rb, src/api/config/environment.rb, src/api/config/initializers/secret_token.rb, src/api/config/initializers/tempdir.rb, src/api/lib/tasks/extract.rake, src/api/script/start_test_backend, src/api/spec/shared/contexts/rake.rb, src/api/spec/support/capybara.rb, src/api/spec/support/vcr.rb
See:
- https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsfilepath
- https://railsdoc.github.io/7.0/classes/Rails.html#method-c-root
=> Fix Rails/FilePath RuboCop offenses

src/api/app/models/bs_request_action_release.rb
Allow multiple releases to same target package when it is done for different target repositories.
=> [api] fix release request uniqness validation

src/api/app/views/webui/packages/bs_requests/_breadcrumb_items.html.haml, src/api/app/views/webui/shared/bs_requests/_form.html.haml, src/api/app/views/webui/shared/bs_requests/_request_item.html.haml, src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml
This PR moves the bs_request shared view and partials to shared/bs_requests so they can be used for listing users, projects, and package requests.
=> Move bs_request index and partials to shared/bs_requests folder

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/packages/bs_requests_controller.rb, src/api/app/views/webui/package/_breadcrumb_items.html.haml, src/api/app/views/webui/package/_tabs.html.haml, src/api/app/views/webui/project/side_links/_requests.html.haml
Depends on https://github.com/openSUSE/open-build-service/pull/17143
=> Redirect to the proper route if beta request_index enabled

docs/api/api/obs.rng, src/api/app/models/download_repository.rb, src/api/spec/models/download_repository_spec.rb
as implemented by mls in the backend
=> [api] permit apk DoD repository type

src/api/app/controllers/webui/users/bs_requests_controller.rb
=> Always display the requested view format

src/api/app/views/webui/request/_breadcrumb_items.html.haml
=> Fix link to My requests in breadcrumbs

src/api/app/views/webui/packages/bs_requests/index.html.haml
=> Fix package requests tab page layout

src/api/app/controllers/status/concerns/set_checkable.rb, src/api/app/models/bs_request.rb, src/api/app/models/bs_request/find_for/query.rb, src/api/app/models/concerns/staging_project.rb, src/api/app/models/project.rb, src/api/app/models/user.rb, src/api/spec/models/bs_request_spec.rb
Cleanup `BsRequest` scopes, this class accumulated a lot of cruft scopes during the years...
Best reviewed commit by commit.
=> Refactoring BsRequest scopes

src/api/.haml-lint_todo.yml, src/api/app/controllers/concerns/webui/requests_filter.rb, src/api/app/controllers/webui/packages/bs_requests_controller.rb, src/api/app/controllers/webui/projects/bs_requests_controller.rb, src/api/app/controllers/webui/users/bs_requests_controller.rb, src/api/app/views/webui/packages/bs_requests/index.html.haml, src/api/app/views/webui/projects/bs_requests/index.html.haml, src/api/app/views/webui/shared/bs_requests/_form.html.haml, src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml, src/api/spec/cassettes/Project_Requests/filter_by_staging_projects/for_non_staging_projects/shows_the_staging_requests.yml, src/api/spec/cassettes/Project_Requests/filter_by_staging_projects/for_staging_projects/shows_the_staging_requests.yml, src/api/spec/features/beta/webui/project_requests_spec.rb
This PR introduces a new filter for requests based on staging projects.
=> Staging project filter for requests

src/api/app/assets/stylesheets/webui/requests.scss, src/api/app/views/webui/shared/bs_requests/_form.html.haml, src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml
=> Limit the filter content height and scroll

src/api/app/assets/stylesheets/webui/requests.scss
=> Do not scroll filter content horizontally

src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml
Filter by staging project to the bottom of the filters list: it is expected to be used less than the others.
=> Reorder filters

src/api/app/views/webui/shared/bs_requests/_form.html.haml
=> Make submit search box on mobile more intuitive

src/api/app/views/layouts/webui/_top_navigation_search.html.haml, src/api/app/views/webui/search/index.html.haml, src/api/app/views/webui/search/issue.html.haml, src/api/app/views/webui/search/owner.html.haml, src/api/app/views/webui/shared/_autocomplete.html.haml, src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml, src/api/app/views/webui/user/_involvement.html.haml
=> Make submit search box on mobile more intuitive (II)

src/api/app/datatables/package_datatable.rb
=> Don't hide the labels that don't match the query

src/api/app/controllers/webui/label_templates_controller.rb, src/api/app/models/label_template_global.rb, src/api/app/policies/label_template_global_policy.rb, src/api/app/views/webui/configuration/_tabs.html.haml, src/api/app/views/webui/label_templates/_breadcrumb_items.html.haml, src/api/app/views/webui/label_templates/_form.html.haml, src/api/app/views/webui/label_templates/edit.html.haml, src/api/app/views/webui/label_templates/index.html.haml, src/api/app/views/webui/label_templates/new.html.haml, src/api/config/routes/webui.rb
=> Introduce CRUD for global label templates

src/backend/BSRepServer/DoD.pm, src/backend/bs_dodup
Use the new verify functionality of the query method instead of verifying the apk packages in our code.
=> [backend] BSRepServer/DoD: simplify apk handling

src/api/app/assets/javascripts/webui/project.js, src/api/app/datatables/project_datatable.rb, src/api/app/models/project.rb, src/api/app/views/webui/project/_projects_table.html.haml, src/api/app/views/webui/project/index.html.haml
~~Depends on https://github.com/openSUSE/open-build-service/pull/17275~~
=> Add labels to project datatable and allow to filter and search

dist/systemd/obsgetbinariesproxy.service, dist/systemd/obssourcepublish.service
obsgetbinariesproxy.service
obssourcepublish.service
=> [dist] configure two more critical services to restart after OOM

src/api/config/crawler-user-agents.json
Update the crawler, spider and bot list via `rake voight_kampff:import_user_agents`
=> Update bot list

src/api/.rubocop_todo.yml, src/api/app/components/bs_request_priority_badge_component.rb, src/api/app/controllers/concerns/webui/requests_filter.rb, src/api/app/models/bs_request.rb, src/api/app/models/bs_request/find_for/base.rb, src/api/app/models/bs_request/find_for/query.rb, src/api/app/views/webui/shared/bs_requests/_request_item.html.haml, src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml
=> Filter requests by priority

src/api/app/controllers/concerns/webui/requests_filter.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/models/bs_request/find_for/base.rb, src/api/app/models/bs_request/find_for/query.rb, src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml, src/api/config/routes/webui.rb, src/api/spec/features/beta/webui/requests_index_spec.rb
This PR introduces a new filter `filter by reviewers` for requests search
=> Add filtering option to filter by reviewers

src/api/app/components/notification_action_bar_component.html.haml, src/api/app/views/webui/shared/bs_requests/_form.html.haml, src/api/app/views/webui/users/notifications/_notifications_list.html.haml
=> Search box as part of the list section, fixing borders

src/api/app/models/bs_request_action_submit.rb
Drop the method overriding the existing association
=> Refactoring: target_package_object is an association

src/api/app/components/bs_request_description_component.rb, src/api/app/views/webui/shared/bs_requests/_request_item.html.haml, src/api/spec/components/previews/bs_request_description_component_preview.rb
=> Introduce a more detailed description of multi action requests

src/api/app/models/package.rb, src/api/app/models/project.rb
When projects or packages are deleted, the `source_project_id`, `source_package_id`, `target_project_id`, or `target_package_id` fields in the table `bs_request_actions` could be `NULL`.
Make sure, that when a project or package gets created, the request actions with the same project name or package name get their "*_id" fields updated. This makes sense only for request actions with source or target projects or packages which were previously deleted.
=> Backfill request actions' source and target ids on project and package creation

src/backend/BSKiwiXML.pm
to support version and moduleorder settings for driverupdate
=> [backend] extend KIWI Schema parsing

src/api/spec/cassettes/Workflow/_steps/with_a_supported_step/1_2_1_2.yml, src/api/spec/cassettes/Workflow/_steps/with_one_unsupported_step/1_2_3_2.yml, src/api/spec/controllers/trigger_workflow_controller_spec.rb, src/api/spec/fixtures/files/request_payload_gitea_pull_request_opened.json, src/api/spec/fixtures/files/request_payload_gitea_push.json, src/api/spec/fixtures/files/request_payload_gitea_tag_push.json, src/api/spec/fixtures/files/request_payload_github_pull_request_assigned.json, src/api/spec/fixtures/files/request_payload_github_synchronize.json, src/api/spec/fixtures/files/request_payload_gitlab_pull_request_opened.json, src/api/spec/models/token/workflow_spec.rb, src/api/spec/models/workflow/step/configure_repositories_spec.rb, src/api/spec/models/workflow/step/rebuild_package_step_spec.rb, src/api/spec/models/workflow/step/set_flags_step_spec.rb, src/api/spec/models/workflow/step/trigger_services_spec.rb, src/api/spec/models/workflow/step_spec.rb, src/api/spec/models/workflow_spec.rb, src/api/spec/services/gitea_status_reporter_spec.rb, src/api/spec/services/github_status_reporter_spec.rb, src/api/spec/services/gitlab_status_reporter_spec.rb, src/api/spec/services/workflows/artifacts_collector_spec.rb, src/api/spec/services/workflows/yaml_downloader_spec.rb, src/api/spec/services/workflows/yaml_to_workflows_service_spec.rb
Simplifies viewing and writing tests by moving data outside of them.
=> Replace payload hashes with fixtures

src/api/app/models/token.rb, src/api/app/models/token/rebuild.rb, src/api/app/models/token/release.rb, src/api/app/models/token/service.rb, src/api/app/models/token/workflow.rb, src/api/app/queries/event_subscriptions_finder.rb, src/api/db/migrate/20250217123130_add_enabled_index_to_tokens.rb, src/api/db/schema.rb
=> Prevent not enabled tokens from reporting to SCM's

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/packages/bs_requests_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/projects/bs_requests_controller.rb
Fixes https://github.com/openSUSE/open-build-service/issues/17271
=> Bugfix: redirect beta/non-beta accordingly

src/api/app/models/workflow.rb, src/api/spec/fixtures/files/request_payload_github_pull_request_opened_branch_number.json, src/api/spec/models/workflow_spec.rb
=> Parse workflow's branch filters as strings

src/api/app/controllers/public_controller.rb
This is fixing also creating submit requests from remote devel projects managed in git scmsync.
=> [api] Fix source interconnect to remote scmsync projects

src/api/app/controllers/concerns/webui/requests_filter.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml, src/api/config/routes/webui.rb, src/api/spec/controllers/webui/users/bs_requests_controller_spec.rb
~~[DO NOT MERGE]: Has to be adapted to align with https://github.com/openSUSE/open-build-service/pull/17410~~
=> Add package filter to request index page

src/backend/bs_publish
Repotype: rpm-md:sbom-spdx:sbom-cyclonedx
=> [backend] publish SBOM files in rpm-md repositories

src/api/app/controllers/webui/groups/bs_requests_controller.rb, src/api/app/controllers/webui/users/bs_requests_controller.rb, src/api/app/helpers/webui/request_helper.rb, src/api/app/models/group.rb, src/api/app/views/webui/groups/bs_requests/_breadcrumb_items.html.haml, src/api/app/views/webui/groups/bs_requests/index.html.haml, src/api/app/views/webui/groups/show.html.haml, src/api/app/views/webui/packages/bs_requests/index.html.haml, src/api/app/views/webui/projects/bs_requests/index.html.haml, src/api/app/views/webui/shared/bs_requests/_filter_help_involvement.html.haml, src/api/app/views/webui/users/bs_requests/index.html.haml, src/api/spec/controllers/webui/groups/bs_requests_controller_spec.rb, src/api/spec/models/group_spec.rb
Depends on ~#17426~ ~#17438~
**Before**
**After**
=> Implement requests page for groups

src/api/app/views/webui/shared/bs_requests/_filter_help_project_names.html.haml, src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml
There's almost no added value and we use it only once
=> Remove the _filter_help_project_names partial

ReleaseNotes-2.10.26
=> Create Release Notes for version 2.10.26

src/api/.database_consistency.todo.yml, src/api/app/models/attrib.rb
See
https://github.com/djezzzl/database_consistency/wiki/lengthconstraintchecker for more details
=> Back up attribs binary length constraint with a validation

src/api/lib/tasks/dev/requests.rake
Run the task `rake dev:requests:copy_requests_from_opensuse_factory`
Before you run the task, please enter your username and password to `make_api_request` method.
This task involves copying 10 `new,review` requests from `openSUSE:Factory`. However, this implementation has certain limitations; it will disregard requests associated with staging projects and will solely focus on requests targeting `openSUSE:Factory`. Additionally, users are required to input login details to facilitate API requests.
TODO:
=> Add rake task to generate test data for bs_requests

src/api/spec/features/webui/maintenance_workflow_spec.rb, src/api/spec/support/wait_helpers.rb
See: https://www.rubydoc.info/gems/capybara/3.40.0/Capybara#using_wait_time-class_method
=> Use Capybara.using_wait_time instead our own code

dist/t/spec/features/0040_package_spec.rb, dist/t/spec/support/capybara.rb
Make it easier to run the specs in different systems with different system loads.
Follow up to #17534.
=> Change the way wait for an element to appear

src/api/db/migrate/20250313151625_add_on_delete_cascade_to_values_column_in_attribs_table.rb
=> Don't error on removing a non existent foreign key

src/api/app/views/webui/shared/_lock_unlock_comment.html.haml
Fix https://github.com/openSUSE/open-build-service/issues/16888
=> Bugfix: missing wrapper class for responsive behavior

src/api/app/controllers/webui/request_controller.rb, src/api/app/controllers/webui/session_controller.rb, src/api/app/controllers/webui/staging/excluded_requests_controller.rb, src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/controllers/webui/webui_controller.rb
=> Don't return a boolean value in before filters, II

src/api/app/models/package_issue.rb
Reverts openSUSE/open-build-service#17515
Before, `sql.execute()` didn't create any indexing jobs.
Now, `package.issue_ids = issues.values.flatten.pluck(:id)` triggers the creation of a lot of jobs.
The first doesn't call callbacks, and the second, yes.
Fixes #17593.
=> Revert "Refactor updating issues of a package"

src/api/app/controllers/webui/users_controller.rb
Prevent from race conditions to happen when changing the `in_beta` value of a user.
=> Improve assignment of in_beta value from user parameters

src/api/app/assets/stylesheets/webui/borders.scss, src/api/app/components/request_decision_component.html.haml, src/api/app/views/webui/comment/_comment_field.html.haml
=> Fix: remove preview border

src/api/app/views/layouts/webui/_unread_notifications_counter.html.haml
Additional fix for https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/667c7b0684bf4608c2d88db9
=> Do not crash if count is nil

src/api/app/components/bs_request_history_element_component.html.haml
=> Display what the review was for in the conversation

src/backend/BSSched/EventSource/RemoteWatcher.pm
Broken by accident with commit e18fbe134eeec11ee6a6642f8db35980fce63203
=> [backend] fix client no longer be sent to the lasteventsproxy

src/api/app/assets/javascripts/webui/project_monitor.js, src/api/app/assets/javascripts/webui/request_show_redesign/build_results.js, src/api/app/assets/stylesheets/webui/build-results.scss, src/api/app/assets/stylesheets/webui/project-monitor.scss, src/api/app/views/webui/shared/_build_result_filter.haml
=> Add search capability to filter dropdowns and limit their height

src/api/app/controllers/webui/cloud/azure/upload_jobs_controller.rb, src/api/app/controllers/webui/cloud/ec2/upload_jobs_controller.rb, src/api/app/models/cloud/backend/upload_job.rb, src/api/spec/controllers/webui/projects/meta_controller_spec.rb, src/api/spec/controllers/webui/projects/project_configuration_controller_spec.rb, src/api/spec/models/cloud/upload_job_spec.rb
For instance, see failures in https://app.circleci.com/pipelines/github/openSUSE/open-build-service/24193/workflows/3c39fcf1-42ea-4498-b669-a7ca69772e46/jobs/227950
=> Requirement to OpenStruct needs to be explicit

src/api/app/components/bs_request_history_element_component.html.haml, src/api/spec/components/bs_request_history_element_component_spec.rb, src/api/spec/factories/history_elements.rb
This was missing from the last PR, causing errors. Fixes #17623
=> Use a package/project link helper correctly in a component

src/api/app/components/build_results_monitor_component.rb
=> Refactor filter method by reducing its number of parameters

.circleci/conditional_config.yml, gitleaks.toml, src/api/app/components/bs_request_state_badge_component.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/lib/rails_version.rb, src/api/app/models/concerns/status_checkable.rb, src/api/app/models/event_subscription.rb, src/api/app/models/notification.rb, src/api/app/models/project.rb, src/api/app/models/workflow_artifacts_per_step.rb, src/api/config/environments/test.rb, src/api/test/unit/package_test.rb
Config and code changes (with conditional wrapper where required) in order to not break current 7.0 version and be able to run the `next_rails` version too.
=> Next rails 7.1 dual boot

src/api/app/controllers/webui/decisions_controller.rb, src/api/app/models/decision_favored_with_delete_request.rb
=> Add bs_request link to the successful decision message

src/api/app/assets/javascripts/webui/nav_tabs.js
https://github.com/user-attachments/assets/2f6301e0-74d3-4269-b525-9eb84dfdf9af
=> Fix redirection to a specific tab after blocking or unblocking a user

src/backend/BSSched/BuildRepo.pm, src/backend/BSSched/BuildResult.pm, src/backend/BSSched/EventHandler.pm, src/backend/bs_sched
The new way has been the default since a couple of years.
=> [backend] drop old full tree handling support

src/api/.database_consistency.todo.yml, src/api/app/models/report.rb, src/api/db/migrate/20250414133357_switch_not_null_constraint_from_user_to_reporter_for_reports.rb, src/api/db/schema.rb
1. Add the new column to the reports table (can be null for now). [DONE]
2. Adapt code to write to both columns (user and reporter). [DONE]
3. Back fill the reporter column. [DONE]
4. Switch no null constraint from user to reporter column. <---
5. Remove all references to reports user in the codebase and ignore user_id
column.
6. Delete the user column from the reports table
~~Depends on: https://github.com/openSUSE/open-build-service/pull/17699~~
=> Add no null constraint to reporter column

src/api/app/models/notification_report.rb
This should have been included in #17713.
=> Migrate user to reporter in two places

src/api/lib/tasks/dev/reports.rake
This is something left behind from https://github.com/openSUSE/open-build-service/pull/17713
=> Fix the reporter in the reports rake task

src/api/app/services/webui_controller_service/user_checker.rb, src/api/spec/controllers/webui/session_controller_spec.rb
=> Return authorization error if email header is not present

src/api/app/lib/routes_helper/routes_constraints.rb
This should have been added long time ago.
=> Add route constraint for `request_number` parameter

src/api/app/controllers/webui/labels_controller.rb, src/api/spec/controllers/webui/labels_controller_spec.rb
=> Prevent user-facing exception when no labels are specified.

src/api/public/apidocs/OBS-v2.10.50.yaml, src/api/public/apidocs/paths/labels_projects_project_name.yaml, src/api/public/apidocs/paths/labels_projects_project_name_label_id.yaml
=> Create documentation for global labels API

src/api/app/controllers/label_templates/projects_controller.rb, src/api/config/routes/api.rb, src/api/public/apidocs/OBS-v2.10.50.yaml, src/api/public/apidocs/paths/label_templates_projects_project_name.yaml, src/api/public/apidocs/paths/label_templates_projects_project_name_label_template_id.yaml, src/api/spec/controllers/label_templates/projects_controller_spec.rb
=> Introduce resourceful API endpoints for label templates

src/api/lib/tasks/dev.rake
It used to rely on the call `Rake::Task['db:version'].invoke` that was raising an exception if the database did not exist.
This was changed in Rails 7.2 ([`railties/databases.rake#323`](https://github.com/rails/rails/blob/v7.2.2.1/activerecord/lib/active_record/railties/databases.rake#L323) and its internal implementation), and it does not raise exceptions anymore. There is a proper task to check if the database exists though. Make use of it since Rails 7.2
PS: it is expected that `next_rails-minitest` and `next_rails-rspec` still fail, the fix is to make the [`next_rails-minitest - setup application`](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/24580/workflows/b2691b0a-03e5-417f-92e6-fd8ee51c1c2f/jobs/231294) test to pass, that's the one that creates the …
=> Check if the database exists by its own call in Rails 7.2

src/backend/bs_repserver
Fixes container access by pbuild.
=> [backend] improve handling of DoD containers accessed by path

src/api/app/models/assignment.rb
=> Add validation for an assignment: confirmed assignee

src/api/app/jobs/expire_assignments_job.rb, src/api/config/clock.rb
This job deletes assignments that were created more than 24h ago
Depends on #17802
=> Expire assignments

docs/api/api/assignment.rng, src/api/app/controllers/assignments_controller.rb, src/api/app/models/project.rb, src/api/app/views/assignments/index.xml.builder, src/api/config/routes/api.rb, src/api/public/apidocs/OBS-v2.10.50.yaml, src/api/public/apidocs/components/schemas/assignment.yaml, src/api/public/apidocs/components/schemas/assignments.yaml, src/api/public/apidocs/paths/assignments_projects_project_name.yaml, src/api/public/apidocs/paths/assignments_projects_project_name_packages_package_name.yaml
=> Introduce RESTful API endpoints for assignments

src/api/config/clock.rb
=> Fix ExpireAssignmentsJob name

src/api/app/models/label.rb, src/api/spec/models/label_spec.rb
=> Validate labelable &  label_template association

src/api/app/views/webui/package/_side_links.html.haml, src/api/app/views/webui/package/side_links/_assignments.html.haml, src/api/lib/tasks/dev.rake, src/api/lib/tasks/dev/assignments.rake, src/api/spec/cassettes/Assignments/showing_the_assigment_of_a_package/when_having_an_assignment/shows_the_login_name_of_the_assigned_user.yml, src/api/spec/cassettes/Assignments/showing_the_assigment_of_a_package/when_having_no_assignment/shows_nothing.yml, src/api/spec/factories/assignment.rb, src/api/spec/features/beta/webui/assignments_spec.rb
This is how it looks like
You can see it live here https://obs-reviewlab.opensuse.org/danidoni-implement-show-assignments/package/show/home:Admin/hello_world
=> Show assignments on the package show page

src/api/app/controllers/labels_controller.rb, src/api/app/controllers/webui/labels_controller.rb, src/api/app/policies/label_policy.rb, src/api/spec/controllers/webui/labels_controller_spec.rb, src/api/spec/policies/label_policy_spec.rb
=> Create policy for labels

src/backend/BSRepServer/ProjPacks.pm, src/backend/BSSched/ProjPacks.pm, src/backend/bs_srcserver
=> [backend] switch parameters of the is_in_project macro

src/api/app/controllers/webui/packages/assignments_controller.rb, src/api/app/policies/assignment_policy.rb, src/api/app/views/webui/package/side_links/_assignments.html.haml, src/api/config/routes/webui.rb, src/api/spec/cassettes/Assignments/unassigning_a_package/removes_the_assignment.yml, src/api/spec/features/beta/webui/assignments_spec.rb, src/api/spec/policies/assignment_policy_spec.rb
=> Implement delete assignments

src/api/app/views/webui/projects/pulse/show.html.haml
Drop stale js script, they are leftover from recent refactoring or old hack no longer needed.
=> Fix pulse bug header visibility

src/api/app/models/bs_request.rb, src/api/app/models/bs_request_permission_check.rb, src/api/app/models/staging/staged_requests.rb
Reverts openSUSE/open-build-service#17837
Fixes #17894.
=> Revert "Allow adding review during unstage of declined SR"

src/api/app/components/bs_request_activity_timeline_component.html.haml, src/api/app/components/bs_request_activity_timeline_component.rb, src/api/app/views/webui/request/beta_show.html.haml
=> Hint there is no history in the superseded request

src/api/app/assets/stylesheets/webui/bootstrap_variables/colors.scss, src/api/app/assets/stylesheets/webui/build-results.scss, src/api/app/assets/stylesheets/webui/colors.scss, src/api/app/assets/stylesheets/webui/comments.scss, src/api/app/assets/stylesheets/webui/content-selector-filters.scss, src/api/app/assets/stylesheets/webui/datatables.scss, src/api/app/assets/stylesheets/webui/layout.scss, src/api/app/assets/stylesheets/webui/navbar.scss, src/api/app/assets/stylesheets/webui/sidebar-collapsible.scss, src/api/app/assets/stylesheets/webui/texts.scss, src/api/app/assets/stylesheets/webui/user.scss, src/api/app/helpers/webui/repository_helper.rb, src/api/app/views/webui/package/_commit_item.html.haml
We shouldn't have modified these variables in the first place. We can always define our own ones.
=> Fix Bootstrap gray color definitions

src/backend/BSSrcServer/Scmsync.pm, src/backend/BSSrcServer/Service.pm, src/backend/bs_productconvert, src/backend/bs_srcserver
The API will use this to lock/unlock packages in scmsync projects.
=> [backend] bs_srcserver: add lock/unlock package commands

src/api/app/assets/stylesheets/webui/bootstrap_variables/colors.scss, src/api/app/assets/stylesheets/webui/staging-workflow.scss, src/api/app/views/webui/staging/shared/_legend.html.haml
Fixes #15524.
| Light mode | Dark mode |
| --- | --- |
| ![Screenshot From 2025-05-20 10-39-29](https://github.com/user-attachments/assets/ad1faf06-28cd-4909-b607-17d4ab36e00d) | ![Screenshot From 2025-05-20 10-39-39](https://github.com/user-attachments/assets/e59647fa-656d-42a4-abae-a89e205b8666) |
| Light mode | Dark mode |
| --- | --- |
| ![Screenshot From 2025-05-20 12-39-46](https://github.com/user-attachments/assets/5d517cfb-f312-4f77-a4bd-4060064fcd2e) | ![Screenshot From 2025-05-20 12-39-51](https://github.com/user-attachments/assets/110c5882-c6bb-4b11-be12-f7678bae1c7a) |
=> Improve legend for staging states

src/api/app/helpers/webui/webui_helper.rb, src/api/app/models/user.rb, src/api/app/views/webui/user/_edit_account_form.html.haml, src/api/config/initializers/flipper.rb
Remove `color_themes` feature flag.
=> Rollout "Color Themes"

src/api/app/components/request_decision_component.html.haml
Extracted from https://github.com/openSUSE/open-build-service/pull/17595
=> Use url helper for request decision form

src/api/lib/tasks/dev.rake, src/api/lib/tasks/dev/requests.rake
Extracted from https://github.com/openSUSE/open-build-service/pull/17595
=> Add rake task to create a request which can be forwarded to a devel package

src/api/app/services/action_build_results_service/chart_data_extractor.rb, src/api/spec/services/action_build_results_service/chart_data_extractor_spec.rb
Sort build results so that repositories matching the target project appear at the top of the list
=> Sort build results according to repositories of the target project  

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/package/_rpmlint_result.html.haml
Fixes https://github.com/openSUSE/open-build-service/issues/17954
=> Do not render twice in an action

src/api/app/views/webui/user/_basic_info.html.haml
- drop redundant check
- use policy check instead of checking user variables
=> Enhance user update policy checks

src/api/app/views/webui/groups/show.html.haml
=> Render group legacy tab panes only in non-beta

src/api/app/controllers/webui/request_controller.rb
=> Hide the project maintainer warning for non-maintainers

src/api/app/views/event_mailer/report_for_comment.text.erb, src/api/app/views/event_mailer/report_for_package.text.erb, src/api/app/views/event_mailer/report_for_project.text.erb, src/api/app/views/event_mailer/report_for_user.text.erb
Those were missing, let's introduce them
=> Create text templates for report emails

src/api/app/assets/stylesheets/webui/application.scss, src/api/app/assets/stylesheets/webui/canned-responses.scss, src/api/app/assets/stylesheets/webui/collapsible-text.scss, src/api/app/controllers/webui/users/canned_responses_controller.rb, src/api/app/views/webui/users/canned_responses/edit.html.haml, src/api/app/views/webui/users/canned_responses/index.html.haml, src/api/spec/features/webui/canned_responses_spec.rb
=> Canned response index

src/api/app/models/appeal.rb, src/api/db/migrate/20250612085047_add_unique_index_on_decision_id_field_on_appeals_table.rb, src/api/db/schema.rb
- Go to https://obs-reviewlab.opensuse.org/danidoni-dont-allow-appealling-decisions-multiple-times/decisions/1/appeals/new
- Appeal once
- Go to the url again
- Try to appeal twice.
- It fails with an error preventing you to appeal the same decision twice
=> Don't allow appealling the same decision multiple times

src/api/app/policies/user_policy.rb
When we're not logged in, it makes no sense to let someone update anything...
Fixes #18008
=> Fix user policy when not logged in

src/api/public/apidocs/paths/source_project_name_cmd_remove_flag.yaml, src/api/public/apidocs/paths/source_project_name_cmd_set_flag.yaml, src/api/public/apidocs/paths/source_project_name_cmd_unlock.yaml, src/api/public/apidocs/paths/source_project_name_package_name_cmd_collectbuildenv.yaml, src/api/public/apidocs/paths/source_project_name_package_name_cmd_remove_flag.yaml, src/api/public/apidocs/paths/source_project_name_package_name_cmd_set_flag.yaml, src/api/public/apidocs/paths/source_project_name_package_name_cmd_unlock.yaml, src/api/public/apidocs/paths/worker_cmd_checkconstraints.yaml
These changes should have been included into #18109.
=> Adapt the message returned for a required parameter

src/api/app/controllers/webui/request_controller.rb
=> Add require_login for changes_diff action

src/api/app/assets/stylesheets/webui/application.scss, src/api/app/assets/stylesheets/webui/rpmlint.scss, src/api/app/components/build_results_monitor_component.html.haml, src/api/app/controllers/webui/packages/rpmlint_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/app/views/webui/package/_rpmlint_log.html.haml, src/api/app/views/webui/packages/binaries/_show_statistics_job_history_build_reason.html.haml, src/api/app/views/webui/packages/rpmlint/_breadcrumb_items.html.haml, src/api/app/views/webui/packages/rpmlint/show.html.haml, src/api/app/views/webui/shared/_build_status_badge.html.haml, src/api/app/views/webui/shared/_build_status_badge_links.html.haml, src/api/config/routes/webui.rb
=> Display the rpmlint links in the request more obviously

src/api/app/controllers/application_controller.rb, src/api/app/controllers/source_project_meta_controller.rb
Everything is using User.session now.
=> Drop usage of Authenticator.http_user

src/api/app/controllers/webui/users/notifications_controller.rb
Instead of performing one query per event type and notification type, counting is now done via two grouped queries: one for event types and one for notification types. This reduces the total number of queries from nine to two.
=> Improve counting notifications by grouping queries

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/views/webui/users/notifications/_notification_filter.html.haml, src/api/config/routes/webui.rb, src/api/spec/features/webui/users/notifications_spec.rb
=> Add autocomplete to the projects filter

src/api/app/models/bs_request_action.rb
=> Check the presence of errors before deciding that the diff is not cached

src/api/app/components/chart_component.html.haml
Fixes #18279.
This change should have been included in the update of view_components to 4.0.0. See #18269.
=> Fix rendering of chart_data

src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_and_forward_button/accepts_the_request.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_and_forward_button/does_not_forward_the_action_that_cannot_be_forwarded.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_and_forward_button/does_not_make_the_creator_a_maintainer_on_the_target_package.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_and_forward_button/forwards_the_action_that_can_be_forwarded.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_make_maintainer_and_forward_button/accepts_the_request.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_make_maintainer_and_forward_button/does_not_forward_the_action_that_cannot_be_forwarded.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_make_maintainer_and_forward_button/forwards_the_action_that_can_be_forwarded.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_make_maintainer_and_forward_button/makes_the_creator_a_maintainer_on_the_target_package.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_only_button/accepts_the_request.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_only_button/does_not_forward_anything.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_a_submit_action_that_can_be_forwarded_and_another_that_cannot/and_clicking_on_the_accept_only_button/makes_no_more_maintainers.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_mixed_actions/and_clicking_on_the_accept_and_make_maintainer_button/accepts_the_request.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_mixed_actions/and_clicking_on_the_accept_and_make_maintainer_button/makes_the_creator_a_maintainer_on_the_target_package.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_mixed_actions/and_clicking_on_the_accept_only_button/accepts_the_request.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_request_with_mixed_actions/and_clicking_on_the_accept_only_button/makes_no_more_maintainers.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_submit_request_from_a_new_package/and_clicking_on_the_accept_and_make_maintainer_button/accepts_the_request.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_submit_request_from_a_new_package/and_clicking_on_the_accept_and_make_maintainer_button/makes_the_creator_a_maintainer_on_the_target_package.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_submit_request_from_a_new_package/and_clicking_on_the_accept_only_button/accepts_the_request.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_submit_request_from_a_new_package/and_clicking_on_the_accept_only_button/makes_no_more_maintainers.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_submit_request_from_a_source_package_to_an_existing_target_package/accepts_the_request_and_adds_the_submitter_a_maintainer_when_clicking_the_right_dropdown_button.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_submit_request_from_a_source_package_to_an_existing_target_package/accepts_the_request_and_forwards_it_when_clicking_the_right_dropdown_button.yml, src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/when_using_the_beta_request_show_page/and_sending_a_submit_request_from_a_source_package_to_an_existing_target_package/accepts_the_request_forwards_it_and_make_the_submitter_a_maintainer.yml, src/api/spec/controllers/webui/request_controller_spec.rb
Note: in order to make former https://github.com/openSUSE/open-build-service/pull/17595 smaller and manageable, it has been split into two chunks: https://github.com/openSUSE/open-build-service/pull/18150 for what was required for the feature, and this current PR for what could be postponed. Once https://github.com/openSUSE/open-build-service/pull/18150 is merged, the work on this PR can continue...
TODO:
=> Improve request controller spec

src/api/.rubocop_todo.yml, src/api/spec/controllers/webui/packages/files_controller_spec.rb
Follow up to #18333.
See: https://docs.rubocop.org/rubocop-rails/cops_rails.html#railspluck
=> Autocorrect Rails/Pluck RuboCop offense

src/api/app/helpers/model_helper.rb, src/api/app/lib/backend/connection_helper.rb, src/api/app/models/event/build_fail.rb, src/api/app/models/history_element/request_superseded.rb, src/api/app/models/repository.rb, src/api/app/models/user.rb, src/api/app/services/rpmlint_log_extractor.rb, src/api/spec/mixins/build_log_support_spec.rb
=> Unfreeze strings to prevent warnings (II)

src/api/app/controllers/concerns/backend_proxy.rb, src/api/app/lib/backend/connection.rb
=> Unfreeze strings to prevent warnings (III)

src/api/app/assets/javascripts/webui/packages.js, src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/package/beta/rpmlint_result.html.haml, src/api/spec/controllers/webui/package_controller_spec.rb
=> Add filters for repository and architecture in the RPM lint summary

src/api/app/models/local_build_result/for_package.rb
=> Check info for both array and hash objects

src/api/app/controllers/source_package_command_controller.rb, src/api/app/controllers/webui/packages/files_controller.rb, src/api/app/lib/backend/api/sources/file.rb, src/api/app/lib/backend/api/sources/package.rb, src/api/app/models/package.rb, src/api/app/models/service.rb, src/api/spec/controllers/webui/packages/files_controller_spec.rb
Move file related methods from `Backend::Api::Sources::Package` into its own class.
=> Introduce `Backend::Api::Sources::File`

src/api/spec/cassettes/PackageUpdateIfDirtyJob/_perform/creates_a_BackendPackage_for_the_Package.yml, src/api/spec/cassettes/UpdatePackagesIfDirtyJob/_perform/the_project_is_found/creates_a_BackendPackage_for_the_Package.yml
These cassettes should have been updated after modifying the specs or the underlying code.
Seen while working on #18441.
=> Adjust the cassettes of the specs of package update if dirty jobs

src/api/db/attribute_descriptions.rb, src/api/db/data/20250910132447_anitya_distribution_attribute.rb, src/api/db/data_schema.rb, src/api/db/seeds.rb
Required for further things within this deliverable, let's introduce it now
=> Create AnityaDistro attribute

src/api/app/jobs/create_local_package_version_job.rb, src/api/app/jobs/fetch_local_package_version_job.rb, src/api/app/lib/backend/api/sources/project.rb, src/api/app/models/attrib.rb, src/api/app/models/event/version_change.rb, src/api/config/initializers/flipper.rb
~~[WIP]: We should split the PR into two once everything is settled. First merge and deploy the db migration, then the code parts that write to the newly created table.~~
**DEPENDS ON** https://github.com/openSUSE/open-build-service/pull/18495 BEING MERGED AND DEPLOYED FIRST
=> Create base for version history feature

src/api/app/components/request_decision_component.html.haml
=> Align buttons to the boundaries of the wrapper box

src/api/app/models/package.rb
Reverts openSUSE/open-build-service#18522
Fixes #18542
=> Revert "[api] Fix usage of scmsync projects via project links"

src/api/app/jobs/fetch_upstream_package_version_job.rb, src/api/app/models/attrib.rb, src/api/app/models/package_version_upstream.rb, src/api/config/clock.rb, src/api/spec/cassettes/FetchUpstreamPackageVersionJob/_perform/not_providing_a_project_name/creates_a_package_version_upstream_record_for_all_projects_packages_with_the_attribute_assigned.yml, src/api/spec/cassettes/FetchUpstreamPackageVersionJob/_perform/providing_a_project_name/creates_a_package_version_upstream_record_for_the_projects_packages.yml, src/api/spec/factories/attribs.rb, src/api/spec/jobs/fetch_upstream_package_version_job_spec.rb
This PR implements a delayed job used to fetch the upstream project's version of a package.
=> Create base to fetch the upstream package version

src/api/.rubocop_todo.yml, src/api/app/models/user.rb
See: https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsfindbyorassignmentmemoization
=> Manually fix Rails/FindByOrAssignmentMemoization RuboCop offense

src/api/app/components/comment_component.rb, src/api/app/models/comment.rb
=> Ensure comment body is sanitized on return

src/api/.rubocop_todo.yml, src/api/spec/jobs/issue_tracker_fetch_issues_job_spec.rb, src/api/spec/jobs/issue_tracker_update_issues_job_spec.rb, src/api/spec/lib/backend/connection_helper_spec.rb, src/api/spec/models/project_spec.rb
See: https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecverifieddoubles
=> Manually fix some RSpec/VerifiedDoubles RuboCop offenses
