openSUSE/open-build-service

.circleci/conditional_config.yml
src/api/docker-files/Dockerfile

We don't need to point to the ruby31 branch anymore now that the
changes are merged into master.

Switch container urls back to OSU

---

dist/obs-bundled-gems.spec

It lead to /usr/bin/ruby.ruby3.1 -> /usr/bin/ruby.ruby3.1.ruby3.1
Be more explicit what and where we want to replace things.

shebang replacement was too greedy

---

src/api/app/mixins/has_relationships.rb
src/api/app/models/relationship.rb

The method names `create_event_after_create` and `create_event_before_delete` sound a bit weird to me. Especially in `after_create :create_event_after_create`.
I propose these other names, let me know what you think.

Rename methods to create/delete relationship events

---

src/api/app/models/bs_request/errors.rb
src/api/app/models/bs_request_permission_check.rb
src/api/db/attribute_descriptions.rb
src/api/db/data/20220318123314_add_attribute_to_enforce_request_accepter_and_creator_to_be_a_different_person.rb
src/api/db/data_schema.rb
src/api/db/seeds.rb
src/api/spec/cassettes/BsRequest/_changestate/when_bs_request_is_staged/when_a_staged_bs_request_is_accepted/1_6_5_2_1.yml
src/api/spec/cassettes/BsRequest/_changestate/when_the_request_is_accepted/and_the_target_package_has_an_attribute_to_disallow_acceptance_by_the_creator/and_the_accepter_is_NOT_the_creator/accepts_the_request.yml
src/api/spec/cassettes/BsRequest/_changestate/when_the_request_is_accepted/and_the_target_package_has_an_attribute_to_disallow_acceptance_by_the_creator/and_the_accepter_is_the_creator/triggers_an_error.yml
src/api/spec/cassettes/BsRequest/_changestate/when_the_request_is_accepted/and_the_target_package_has_an_attribute_to_disallow_acceptance_by_the_creator/but_the_accepter_is_NOT_the_creator/accepts_the_request.yml
src/api/spec/cassettes/BsRequest/_changestate/when_the_request_is_accepted/and_the_target_project_has_an_attribute_to_disallow_acceptance_by_the_creator/and_the_accepter_is_NOT_the_creator/accepts_the_request.yml
src/api/spec/cassettes/BsRequest/_changestate/when_the_request_is_accepted/and_the_target_project_has_an_attribute_to_disallow_acceptance_by_the_creator/and_the_accepter_is_the_creator/triggers_an_error.yml
src/api/spec/cassettes/BsRequest/_changestate/when_the_request_is_accepted/and_the_target_project_has_an_attribute_to_disallow_acceptance_by_the_creator/but_the_accepter_is_NOT_the_creator/accepts_the_request.yml
src/api/spec/models/bs_request_spec.rb
src/api/spec/support/database_cleaner.rb

In order to enforce two different reviewers, the approver cannot be the same person than the creator of a request, if the proper attribute is enabled at target project or target package.
1. In the review-app, go to your home project
2. Add an `CreatorCannotAcceptOwnRequests` attribute there.
3. Go to the project's hello-world package
4. Branch it and change the sources so you can submit a request back
5. Go to the request and accept it.
As you have the `CreatorCannotAcceptOwnRequests` attribute set and you are the same approver user as the request's creator user, an error will popup preventing you to approve the request.
If you go now and remove the attribute from the project, you'll be allowed to approve your own request.
You could also approve it with or without the attribute set if you …

Approver cannot be the request creator

---

src/api/app/models/token/workflow.rb
src/api/app/services/scm_initial_status_reporter.rb

On our OBS instance, the generated link will be like `https://build.opensuse.org/my/tokens/1/workflow_runs/1`

Add link to new workflow run in initial reports to SCM

---

src/api/app/components/workflow_run_row_component.rb
src/api/spec/components/workflow_run_header_component_spec.rb
src/api/spec/components/workflow_run_row_component_spec.rb

In the JSON sent by GitLab for a Merge Request Hook event, the number of the MR is given by the field `iid`, not `id`.
The following is a real example, the Merge Request number in the GitLab UI is `#2`, which corresponds to the `iid` field in the JSON output:
```
"object_attributes": {
"id": 147069788,
"iid": 2,
...
}
```
We were using the correct field in the [ScmExtractor](https://github.com/openSUSE/open-build-service/blob/f75807701d4c317fbb5d0370978cd35d628552ac/src/api/app/services/trigger_controller_service/scm_extractor.rb#L60), so I change it in the workflow run components and their specs.
**Edit**: the use of `id` didn't imply any error for the current use case, but it makes more sense to use the field corresponding to the MR number, as we do with PRs.

Use the correct field for the merge request number

---

src/api/app/models/bs_request_permission_check.rb
src/api/app/models/project.rb

It is expected if a project is removed then open requests should transition to the revoked state. When the signed-in user is different than the creator of the request then this is not happening and it fails silently.
Closes #12250

Revoke requests with the permissions of the sender

---

src/api/app/controllers/trigger_controller.rb
src/api/app/controllers/trigger_workflow_controller.rb

Before, validate_params was only skipped when the SCM is supported (GitHub or GitLab). This caused issues whenever a payload from an unsupported SCM didn't pass the checks in validate_params.  For example, Codeberg seems to include `nil` instead of `null` in its JSON payloads. This caused validate_params to raise an exception, preventing us from responding back to the SCM with a helpful error message stating that Codeberg isn't supported.
Fixes #11861

Respond with an error when the SCM is unsupported

---

src/api/app/controllers/concerns/rescue_handler.rb
src/api/app/controllers/trigger_controller.rb
src/api/app/controllers/trigger_workflow_controller.rb
src/api/spec/controllers/trigger_controller_spec.rb
src/api/spec/controllers/trigger_workflow_controller_spec.rb
src/api/test/functional/source_services_test.rb
src/api/test/functional/trigger_controller_test.rb

Fixes #12176
In this PR I'm fixing two issues:
- When user has two valid work flow tokens, but then assigns the wrong ID on the github side
- When user has two valid tokens, but for different types and then assign the wrong ID on the github side

Inform user when the provided token is wrong 

---

src/api/app/models/workflow.rb
src/api/spec/models/workflow_spec.rb

Fix issue #12122
When a PR is closed/merged, we want to remove the temporary project created by the workflow as well as their event subscriptions. These two removals only make sense for steps like `BranchPackageStep` and `LinkPackageStep`. So we prevent processing other steps like `ConfigureRepositories` or `RebuildPackage` (which don't create any temporary project or event subscriptions).
This PR also fixes the EventSuscription removal, since we were passing an incorrect token, so we always got an empty list.
TODO:

Fix error trying to find the target package to be deleted

---

src/api/app/components/workflow_run_row_component.html.haml
src/api/app/components/workflow_run_row_component.rb
src/api/app/models/workflow_run.rb
src/api/lib/tasks/workflows.rake
src/api/spec/lib/tasks/workflows_spec.rb

After many occurrences of the error that we are trying to fix with PR #12345, some workflow runs stayed in 'running' status forever and the temporary projects created by the workflow were not removed as expected even if the corresponding pull request or merge request was closed/merged.
The workflow list looks like this in those cases (the workflow run status is `running` and the PR status is `closed`):
Apart from fixing the errors or catching them correctly, we need to ensure we clean up those projects. This rake task is introduced for that purpose.
~**NOTE:** PR #12345 needs to be merged first before we run this task in production, so we make sure we remove all the cases that happened before the fix.~
**NOTE 2:** Now that some methods are moved from the component to the model, …

Clean up running workflows with closed PRs

---

src/api/app/models/workflow_run.rb
src/api/db/migrate/20220330125635_increase_workflow_runs_request_payload_capacity.rb
src/api/db/schema.rb

When storing large jsons, we've been hitting the column's capacity
limit, so we change the column's type to allow for up to 4GB of data in
the `request_payload` column.
Fixes #11891
**NOTE:** This PR should be merged and deployed during the next maintenance window, as the migration will block the `workflow_runs` table.
**NOTE2**: Looks like the migration takes half a minute more or less against a production database dump
**NOTE3**: Looks like the `json` datatype [triggers some errors](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/6206/workflows/3a596494-d368-4bbd-926e-a4723069e065/jobs/81106) so we go with plain LONGTEXT column data type

Increase request payload column capacity

---

src/api/app/models/workflow_run.rb
src/api/spec/components/workflow_run_header_component_spec.rb
src/api/spec/components/workflow_run_row_component_spec.rb
src/api/spec/lib/tasks/workflows_spec.rb

The workflow run details contain a link to the SCM's repository. Compare these two screenshots of workflow runs with real incoming payloads:
For GitHub-related workflow runs, we are displaying repository names like `foo/bar`.
For GitLab-related workflow runs, we were displaying repository names like `bar`. For consistency, I have decided to get the information from another payload field, so we can also have `foo/bar`.
Apart from the names, if we compare the links (at the bottom of the screenshots), we see that GitLab-related workflow runs used to point to a wrong URL because we were getting the information from a payload field that could contain `git@gitlab.com:foo/bar.git` instead of an HTTP(s) URL. So I'm now using another payload field to get the correct URL.
~**NOTE:** I'll need to …

Get consitent repository name and URL for workflow runs

---

src/backend/BSSched/BuildJob.pm

Substitution needs to be done first before checking for parameter

[backend] fix --enable-ccache functionality

---

src/backend/bs_worker

This can be enabled by setting the "slsaprovenance" BuildFlag.
For now, it just contains the source files in the materials
section.

[backend] start implementing slsa provenance file writing

---

src/api/app/controllers/trigger_controller.rb
src/api/app/controllers/trigger_workflow_controller.rb
src/api/spec/cassettes/TriggerController/_create/when_some_parameters_are_not_strings/still_processes_the_request_without_validating_parameters.yml
src/api/spec/controllers/trigger_controller_spec.rb
src/api/spec/controllers/trigger_workflow_controller_spec.rb

This was removed in the PR #12353 and it was wrong. This controller receives webhooks from SCMs, so skipping this validation is needed.
Specs are also covering what wasn't covered in #12353.

Do not validate params in TriggerController

---

.circleci/config.yml
.gitmodules
docker-compose.yml
src/api/config/routes.rb
src/api/docker-files/Dockerfile
src/api/docker-files/Dockerfile.minitest

After OSU switched to Ruby 3.1 we need to use 2.10 containers.

Use 2.10 containers in CI

---

src/api/app/models/project.rb
src/api/spec/models/project_spec.rb

Assigning User.session creates a thread variable. Thread
variables are not reset in delayed jobs. So whoever ran
the first job also ran all the jobs after it...

Reset User.session

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/workflows.rake
src/api/spec/factories/workflow_runs.rb
src/api/spec/lib/tasks/workflows_spec.rb
src/api/spec/support/files/request_payload_github_pull_request_closed.json
src/api/spec/support/files/request_payload_github_pull_request_opened.json
src/api/spec/support/files/request_payload_github_push.json
src/api/spec/support/files/request_payload_github_tag_push.json
src/api/spec/support/files/request_payload_gitlab_pull_request_closed.json
src/api/spec/support/files/request_payload_gitlab_pull_request_opened.json
src/api/spec/support/files/request_payload_gitlab_push.json
src/api/spec/support/files/request_payload_gitlab_tag_push.json

Create a variety of workflow runs: from both GitHub and GitLab, with different statuses, events and actions.
This task is usually run in development environment and review-app.

Extend task to create workflow runs

---

src/api/app/models/token/workflow.rb
src/api/app/models/workflow.rb
src/api/app/services/workflows/yaml_downloader.rb
src/api/app/validators/workflow_filters_validator.rb
src/api/app/validators/workflow_steps_validator.rb
src/api/spec/controllers/trigger_workflow_controller_spec.rb
src/api/spec/models/token/workflow_spec.rb
src/api/spec/validators/workflow_filters_validator_spec.rb
src/api/spec/validators/workflow_steps_validator_spec.rb

With the changes in this PR, we can drop some errors from the `Errors` table in the user documentation of the SCM/CI integration. This is happening in the PR https://github.com/openSUSE/obs-docu/pull/235.

Improve messages of existing errors in SCM/CI integration

---

src/api/app/components/token_card_component.rb
src/api/app/models/token.rb
src/api/app/models/token/rebuild.rb
src/api/app/models/token/release.rb
src/api/app/models/token/rss.rb
src/api/app/models/token/service.rb
src/api/app/models/token/workflow.rb
src/api/app/views/webui/users/token_triggers/show.html.haml
src/api/app/views/webui/users/tokens/edit.html.haml

Instead of have this class method manually defined in each `Token` class, have it in the parent class in a generic way.
Beside that we standardized the way to access it in the views
From here we have some options:
a) Rename the method to something more useful
b) Move the method `token_name` to the component or transform it in a helper
How to test:
Try to create a new token or edit an existing one

Rework token name

---

src/api/app/components/workflow_run_request_action_filter_component.html.haml
src/api/app/components/workflow_run_request_action_filter_component.rb
src/api/app/controllers/webui/workflow_runs_controller.rb
src/api/app/models/scm_webhook.rb
src/api/app/models/workflow_run.rb
src/api/app/queries/workflow_runs_finder.rb
src/api/app/validators/scm_webhook_event_validator.rb
src/api/app/views/webui/workflow_runs/index.html.haml
src/api/spec/components/workflow_run_request_action_filter_component_spec.rb
src/api/spec/controllers/webui/workflow_runs_controller_spec.rb

Currently, it is not possible to filter workflow runs by action type i.e., we can not filter workflow runs for `pull_requests/merge requests` by actions like `opened`, `closed`, etc. This PR allows us to filter `pull_requests/merge requests` by actions.

Add Workflow Runs filter by pull/merge request action

---

src/api/app/models/workflow/step.rb

The method isn't called anywhere, seems to be a left over.

Remove `report_to_scm` method from workflow step model

---

src/api/app/components/workflow_run_filter_component.html.haml
src/api/app/models/workflow_run.rb
src/api/app/queries/workflow_runs_finder.rb
src/api/spec/queries/workflow_runs_finder_spec.rb

Workflow runs can be filtered now by tag push events (from GitHub and GitLab).
Keep in mind that, for GitHub, push events for tags are in the same event type as push events for commits (it's simply "push"). For GitLab, it's a separate event ("Tag Push Hook").

Add new filter for tag push events

---

dist/obs-server.spec
src/backend/bs_publish

createrepo_c changed the default to keep always old metadata.
At the same time modifyrepo_c got changed to fail when the referenced meta data file
got already removed. This leads to the situation that old meta data stays forever.
Not removing the files is not an option as they would stay forever when
actually should not get generated anymore.
Therefore we require the new version of createrepo_c now to be able to switch
back to the old behaviour.

[backend] fix broken additional metadata with createrepo_c 0.20

---

src/api/app/controllers/trigger_workflow_controller.rb
src/api/app/jobs/report_to_scm_job.rb
src/api/app/models/event_subscription.rb
src/api/app/models/token/workflow.rb
src/api/app/models/workflow.rb
src/api/app/models/workflow/step.rb
src/api/app/services/scm_exception_handler.rb
src/api/app/services/scm_initial_status_reporter.rb
src/api/app/services/scm_status_reporter.rb
src/api/app/services/workflows/yaml_to_workflows_service.rb
src/api/db/migrate/20220413223300_add_workflow_run_to_event_subscription.rb
src/api/db/schema.rb
src/api/spec/models/token/workflow_spec.rb
src/api/spec/models/workflow_spec.rb
src/api/spec/services/scm_status_reporter_spec.rb
src/api/spec/services/workflows/yaml_to_workflows_service_spec.rb

In the past we only wrote the exception raised in the scm status reporter to the logfiles, which are not accessible for the users. In order to help the users to debug, we want to show the errors in the workflow runs UI. For now simply by writing it to the response body. 
*How to test:*
Easiest way to test this is by simply setting up a workflow with a `branch_package` step and to mock the code by raising one of the `Octokit` exceptions if the `SCMStatusReporter#call` or somehow let the reporter fail by for example cutting network connection... 
*TODO:*
~- [ ] "Translate" exception message from Octokit to something meaningful~ (follow up PR)

Track errors from SCMStatusReporter in WorkflowRuns

---

src/api/lib/tasks/workflows.rake

The column was renamed but the rake task code was not modified accordingly.
Follow up https://github.com/openSUSE/open-build-service/pull/12434

Use Token#description in workflows rake task

---

src/api/app/components/watchlist_component.rb

Sort requests by descending number so the most recent ones are on top.

Order watchlist items alphabetically or by number

---

src/api/app/models/package.rb

After the switch from ruby 2.5 to ruby 3.1 we switched from
`URI.escape` to `Addressable::URI.escape` in multiple places
(`URI` is deprecated).
Since anchors are valid parts of URIs, we started using `CGI.escape`
for filenames (see https://github.com/openSUSE/open-build-service/pull/12305#discussion_r826949527).
The problem is that whitespaces are treated differently by `CGI.escape`
compared to the previously used `URI.escape` (they are replaced by `+` signs instead
of using the percent encoding %20).
This clashes now, since files uploaded throught the API are still
'correctly' escaped.
On top of this (not related to the ruby update), files uploaded through
the webui already replaced the whitespace characters with the `+` sign.
Using `ERB::Util.url_encode` reintroduces the previous …

Escape whitespace characters correctly for filepaths

---

src/api/app/models/notification.rb
src/api/spec/models/notification_spec.rb

If a Notification is delivered, we want to track it within our SRE stack

Add instrumentation to track changes on Notification#delivered

---

src/api/app/components/watchlist_component.rb

The sorting was a bit weird when combining uppercase and lowercase names. This is the explanation:
Performing a simple order query like `Project.all.order('name')` will sort the results on a case-sensitive manner (displaying the uppercase ones first).
Using `LOWER` like `Project.all.order('LOWER(name)')` we can sort on a case-insensitive manner. It groups the same letters together but the results mix uppercase and lowercase on a messy way.
The combination of case-insensitive and case-sensitive sorting like `Project.all.order('lower(name), name')` gets exactly what we want.
Follw up https://github.com/openSUSE/open-build-service/pull/12460

Set case-insensitive order for watchlist elements

---

.circleci/config.yml
docker-compose.yml
src/api/docker-files/Dockerfile
src/api/docker-files/Dockerfile.minitest

For docker those two images are the same:
registry.opensuse.org/obs/server/2.10/containers/containers/openbuildservice/backend
registry.opensuse.org/obs/server/unstable/containers/containers/openbuildservice/backend
The are both openbuildservice/backend:latest. So whatever image it finds first, it's going to use.
This lead to strange problems with the dev-env when switching between 2.10 and master branches.

Introduces 210 label for 2.10 images

---

dist/t/0000-check_users_and_group.ts

We still don't want the source file to pass the linter. This is fixing a behaviour introduced with a new version of shellcheck.
See: https://github.com/koalaman/shellcheck/wiki/SC1091#correct-code

Prevent shellcheck from following a source file

---

dist/obs-server.spec
dist/t/osc/fixtures/obs-testpackage-2.8._service
dist/t/osc/fixtures/obs-testpackage._service
src/backend/Makefile
src/backend/t/0015-BSSched-EventSource-Directory.t

* added %{obs_backend_dir} macro
* added obs-backend-testsuite rpm
* changed deprecated git:// url in test cases to https://
* added perl include path "/usr/lib/build" in "src/backend/Makefile"
* fixed expected path in "0015-BSSched-EventSource-Directory.t"

Fix backend tests backport

---

src/backend/bs_publish

If "filelists_ext" option is enabled for the rpmmd repository, it will
call createrepo_c with the --filelists_ext parameter.
This parameter will create a new optional variant of filelists.xml,
named filelists_ext.xml.  This will contain, besides the list of files,
the hash (usually SHA256) registered in the RPM header for this file
(only for file types, not for ghost or dir types).
Additionally, a new field "checksum" will register the hash algorithm
used by librpm for those file entries.
Signed-off-by: Alberto Planas <aplanas@suse.com>

[backend] add "--filelists_ext" parameter for createrepo

---

src/api/app/models/event_subscription.rb
src/api/spec/models/event_subscription_spec.rb

Instrument the EventSubscription model. Send metrics to RabbitMQ always when an event subscription gets enabled/disabled

Add instrumentation to EventSubscription#enabled

---

src/api/app/controllers/person_controller.rb
src/api/app/models/user.rb
src/api/app/policies/user_policy.rb
src/api/app/queries/watchlist_finder.rb
src/api/app/views/models/_user.xml.builder
src/api/app/views/person/_watchlist.xml.builder
src/api/config/routes/api_routes.rb
src/api/spec/controllers/person_controller_spec.rb

`osc -A dosc api -X PUT 'person/Admin' -T person.xml`
- It's backward compatible.
```
<person>
<login>Admin</login>
<email>root@localhost</email>
<realname>OBS Instance Superuser</realname>
<state>confirmed</state>
<globalrole>Admin</globalrole>
<ignore_auth_services>false</ignore_auth_services>
<watchlist>
<project name="MaintenanceProject"/>
<project name="home:Admin"/>
</watchlist>
</person>
```  
```
<person>
<login>Admin</login>
<email>root@localhost</email>
<realname>OBS Instance Superuser</realname>
<state>confirmed</state>
<globalrole>Admin</globalrole>
<ignore_auth_services>false</ignore_auth_services>
<watchlist>
<project name="MaintenanceProject"/>
<project name="home:Admin"/>
<package name="ad" project="home:Admin"/>
<request number="7"/>
</watchlist>
</person>
```
`osc -A …

Implement New Watchlist API

---

src/api/app/assets/javascripts/webui/application.js
src/api/app/assets/javascripts/webui/new_watchlist/collapsible_tooltip.js
src/api/app/assets/stylesheets/webui/new_watchlist/watchlist.scss
src/api/app/components/bs_request_action_source_and_target_component.rb
src/api/app/components/bs_request_state_badge_component.rb
src/api/app/components/notification_action_description_component.rb
src/api/app/components/notification_component.html.haml
src/api/app/components/watched_items_list_component.html.haml
src/api/app/helpers/webui/request_helper.rb
src/api/app/helpers/webui/webui_helper.rb
src/api/app/views/webui/package/_buildstatus.html.haml
src/api/spec/components/notification_notifiable_link_component_spec.rb

The information about source and target projects and packages together with the state of the request, is displayed on a tooltip which is initially collapsed.
On mobile:
Multiple actions request:

Add collapsible tooltips to display more info about requests in watchlist

---

src/api/app/controllers/source_controller.rb

Some operations are still possible and needed. Basically
all read-only commands and active commands which do
not modify local sources.

[api] allow certain commands on scmsync projects

---

src/api/app/assets/javascripts/webui/new_watchlist/collapsible_tooltip.js
src/api/app/assets/stylesheets/webui/new_watchlist/watchlist.scss
src/api/app/components/watched_items_list_component.html.haml
src/api/app/components/watchlist_component.html.haml
src/api/app/views/webui/package/_buildstatus.html.haml

A JS function named `toggleTooltip` already existed in another JS file and this was causing weird behaviour in the UI (displaying tooltips in the wrong places).
So the function is renamed to `toggleCollapsibleTooltip` and the classes are renamed accordingly.

Rename duplicated JS function toggleTooltip

---

src/backend/bs_signer
src/backend/bs_worker

Getting the config from the _buildenv is too flaky. We currently
do not write a buildenv file for some build types and the
xml roundtrip makes me nervous.

[backend] write build config into _slsa_provenance.config

---

src/backend/bs_srcserver
src/backend/bs_worker

We may have multiple rpms (like src rpms) going into the same
place, so we need to replace the old provenance files.

[backend] unlink old provenance files when spreading new ones

---

src/api/app/models/package.rb

Package objects do not exist in such projects
(same behavior as with remote projects)
should fix webui behaviour as well

[api] fix access to build area for git projects

---

src/api/app/controllers/application_controller.rb
src/api/app/controllers/trigger_controller.rb
src/api/app/controllers/webui/users/token_triggers_controller.rb
src/api/app/controllers/webui/webui_controller.rb

Pundit currently throws the following deprecation warning:
`DEPRECATION WARNING: 'include Pundit' is deprecated. Please use
'include Pundit::Authorization' instead.`

Tackle pundit deprecation warning

---

src/api/Gemfile.lock

The update of rake in https://github.com/openSUSE/open-build-service/pull/12530
was not required. Let stick to the previous version.

Switch back to rake 13.0.1

---

src/api/app/components/watched_items_list_component.html.haml

This allows removing any item in the watchlist without having to visit the item page first.
For now, the removal is working without Ajax and without removal confirmation.

Add link to remove watchlist items

---

src/api/app/models/worker_status.rb
src/api/spec/models/worker_status_spec.rb

For modifying the availability of architectures we could use instead the `PUT /configuration` endpoint, or the Web UI page under `Configuration -> Architectures`.
Fixes #9523, fixes #10358, and fixes #11660.

Prevent from updating architectures when retrieving workers' status

---

src/backend/bs_publish

They are picked up when publishing the binary packags, so ignore
them in the main code path.

[backend] do not publish slsa provenance files toplevel

---

src/api/Gemfile
src/api/Gemfile.lock

In order to avoid conflicts between the by bundler activated
stdlib `strscan` version and the one defined by the Gemfile
until https://github.com/rubygems/rubygems/pull/5529 is merged.

Pin strscan gem version to 3.0.1

---

src/api/app/components/notification_action_description_component.rb
src/api/app/components/notification_avatars_component.rb
src/api/app/components/notification_component.html.haml
src/api/app/components/notification_component.rb
src/api/app/components/notification_notifiable_link_component.rb
src/api/app/models/event/base.rb
src/api/app/models/event/relationship.rb
src/api/app/models/event/relationship_create.rb
src/api/app/models/event/relationship_delete.rb
src/api/app/models/event_subscription.rb
src/api/app/models/event_subscription/find_for_event.rb
src/api/app/models/relationship.rb
src/api/app/queries/outdated_notifications_finder/package.rb
src/api/app/queries/outdated_notifications_finder/project.rb
src/api/app/services/notification_service/notifier.rb
src/api/app/services/notification_service/web_channel.rb
src/api/app/services/notified_projects.rb
src/api/spec/models/event_subscription/find_for_event_spec.rb
src/api/spec/services/notification_service/notifier_spec.rb

Receive notifications when a relationship is created or deleted. It is available for any kind of role if the user subscribed to the relationship events.
- Given you have two users ready, `Admin` and `Iggy` for example, with home projects.
- Iggy should enable the notifications for the "Relationship  was created" and "Relationship was deleted" event types.
- Admin should go to its home project and add Iggy as maintainer, for example.
- Iggy should get a notification saying it's been added as maintainer into `home:Admin` project.

Receive notifications for relationships

---

src/api/app/views/event_mailer/relationship_create.html.haml
src/api/app/views/event_mailer/relationship_create.text.erb
src/api/app/views/event_mailer/relationship_delete.html.haml
src/api/app/views/event_mailer/relationship_delete.text.erb
src/api/spec/factories/event_subscriptions.rb
src/api/spec/mailers/event_mailer_spec.rb

Follow up on #12470 
After introducing a new type of event, we need to make it work for email channel as well.

Handle emails for Relationship events

---

docs/api/api/obs.rng
src/api/db/migrate/20210707134455_publish_issues.rb
src/api/db/schema.rb
src/backend/BSSched/BuildJob/Patchinfo.pm
src/backend/BSXML.pm

allow to define issue trackers which should not get exported into
external meta data like updateinfo.xml
OBS-141

[api][backend] allow to disable export of issue trackers

---

src/api/lib/tasks/dev.rake

Create subscriptions to the new relationship events, so notifications of the new type are created.
This is part of the result when we run the task:

Add new subscriptions in notifications rake task

---

src/api/app/controllers/webui/package_controller.rb

We currently receive exceptions in errbit due to packages
that are received through projects that use scmsync.
Those packages are not known by the OBS frontend and set
to `nil`. This crashes in the package#show view, since the code
tries to access package properties on the the nil object.
This is a temporary fix to avoid exceptions in errbit due to
packages tried being accessed through the webui.
Fixes #12552

Avoid code 500 on packages received through an scmsync for package show

---

src/api/app/jobs/measurements_job.rb

We only used fields so far which makes it very hard/slow to query.
Tags are also way easier to mix/match in queries.

Introduce tags for notification counts

---

src/api/app/models/event_subscription.rb

Strings are not hashes. The [influx line protocol](https://docs.influxdata.com/influxdb/v2.2/reference/syntax/line-protocol/) expects a string in a very certain format.

Fix event_subscription measurements

---

src/api/app/services/scm_exception_handler.rb

This exception was not catched yet, translating it to something
meaningful will be part of another PR.

Catch Gitlab::Error::BadRequest in SCMExceptionHandler

---

src/api/app/services/scm_exception_handler.rb

Those exception were not catched yet, translating them to something
meaningful will be part of another PR.

Catch Octokit::BadGateway and Octokit::UnprocessableEntity exception

---

src/api/app/models/bs_request.rb

I believe the commit is pretty self-explanatory, I just bumped into an old typo:
```diff
- review assigend
+ review assigned
```

Fix typo in review assignment comment

---

src/api/app/controllers/webui/users/notifications_controller.rb
src/api/app/models/notification.rb
src/api/spec/models/notification_spec.rb

We want to track the notifications that were delivered (marked as read), not those that changed the 'delivered' field to any value. That's why the instrumentation needed to be adapted.
We now have to perform two bulk updates to be able to distinguish the notifications that are marked as read and those marked as unread.
Please read the commits descriptions for more details.

Fix metrics for notifications

---

src/backend/BSSrcServer/Service.pm

Otherwise runtime mode services won't get executed.

[backend] scmsync: we need to store _service files

---

src/backend/BSRepServer/SLSA.pm

We do this so that the directories do not get too big. We use
the first two characters of the hex digest as directory name.

[backend] SLSA: put provenance binaries in a subdir

---

src/api/app/components/workflow_run_detail_component.html.haml
src/api/app/components/workflow_run_detail_component.rb
src/api/app/models/workflow_run.rb

The content of the request and response tabs belongs to the workflow and
it's better shown together.
__This is how it looks like:__

Merge request response tab into incoming webhook

---

src/api/app/services/scm_exception_handler.rb
src/api/app/services/scm_exception_message.rb
src/api/spec/services/scm_status_reporter_spec.rb

We receive some exceptions from GitHub and GitLab. The error messages in these exceptions are very general. This PR proposes new error messages to help users in debugging process.

Add error messages for SCM exception handler

---

ReleaseNotes-2.10.16

Mention the Nokogiri update in the existing _ReleaseNotes-2.10.16_ file, which is not released yet.

Update release notes for 2.10.16

---

src/api/app/services/scm_status_reporter.rb

Octokit raises this exception when the connection
to github timesout or fails.

Catch faraday connection exception in SCM reporter

---

src/api/lib/tasks/dev.rake

Rubocop deprecated `auto-correct` in favour of `autocorrect` in PR #12636.
So the rake task is adapted and renamed to: `rake dev:lint:rubocop:autocorrect`.

Rename Rubocop auto-correct to autocorrect

---

dist/obs-bundled-gems.spec

[ci skip] So only Major|Minor|Patch

rubygem packaging only produces semver provides

---

src/api/app/components/workflow_run_detail_component.html.haml
src/api/app/components/workflow_run_detail_component.rb
src/api/app/controllers/trigger_workflow_controller.rb
src/api/app/models/scm_status_report.rb
src/api/app/models/workflow_run.rb
src/api/app/services/scm_exception_handler.rb
src/api/app/services/scm_status_reporter.rb
src/api/db/migrate/20220520131205_create_scm_status_reports_table.rb
src/api/db/schema.rb
src/api/spec/factories/workflow_runs.rb
src/api/spec/services/scm_status_reporter_spec.rb

While running a workflow run, we may have errors when sending the statuses to the SCM.
When that happens we save the response into a new `ScmStatusReport` object so we can debug it later.
**This is how it looks like**

Show the scm status request response in the workflow run

---

dist/obsworker

without this patch the obsworker script is breaking with the following
error message:
/usr/sbin/obsworker: line 488: syntax error near unexpected token `;;'
/usr/sbin/obsworker: line 488: `    ;;'

[dist] fixed missing end of if (fi)

---

dist/obs-bundled-gems.spec

Otherwise we can run into conflicts with the version Passenger
requires in production (rubyN.N-rubygem-passenger package).

Require a specific rack version

---

src/api/app/lib/backend/api/sources/package.rb
src/api/app/models/service.rb

The `run_service` method is doing exactly the same as the
`trigger_services` method. Lets stick to one and remove the
duplication.

Delete `run_service` method from backend lib

---

src/api/app/views/webui/users/tokens/show.html.haml

Show the url to trigger the token workflow for easy copying.

Show the token trigger url in token details page

---

src/api/app/models/workflow_run.rb
src/api/spec/models/workflow_run_spec.rb

For the `slice` method to work it needs the `PERMITTED_OPTIONS` array to be unpacked using the `*` operator.

Fix empty scm status report

---

src/api/app/lib/backend/api/sources/package.rb
src/api/app/models/workflow/step/trigger_services.rb
src/api/spec/models/workflow/step/trigger_services_spec.rb

When we trigger a service we can pass a comment. We do so on the trigger_services workflow step, so we will have information about what triggered the service.
Fixes #12400.
This is one possible result:

Add comment when triggering service from step

---

.rubocop.yml

Prevent from showing this warning message when running RuboCop:
```
Warning: obsolete parameter `IgnoredPatterns` (for `Layout/LineLength`) found in .rubocop.yml
`IgnoredPatterns` has been renamed to `AllowedPatterns`.
```
`IgnoredPatterns` was deprecated in favour of `AllowedPatterns` in [RuboCop 1.28](https://github.com/rubocop/rubocop/releases/tag/v1.28.0).

Remove obsoleted parameter `IgnoredPatterns` (for `Layout/LineLength`) found in .rubocop.yml

---

src/api/app/services/trigger_controller_service/scm_extractor.rb
src/api/app/services/workflows/yaml_downloader.rb
src/api/spec/controllers/trigger_workflow_controller_spec.rb
src/api/spec/models/workflow/step/branch_package_step_spec.rb
src/api/spec/models/workflow/step/link_package_step_spec.rb
src/api/spec/models/workflow_spec.rb
src/api/spec/services/trigger_controller_service/scm_extractor_spec.rb
src/api/spec/services/workflows/artifacts_collector_spec.rb

On tag push events from GitHub, we tried to extract the branch name to set the 'target_branch' field. However, the value was not always correct (sometimes we got the tag name instead of the branch name). So we now extract the commit sha as we do with GitLab.
We use 'target_branch' to download the Yaml file. We can do that using either the branch name or the commit sha.

Set commit sha on target_branch for tag pushes

---

src/api/app/components/confirmation_dialog_component.html.haml

Modify ConfirmationDialogComponent to avoid texts going out of the modal like this:
and to have something like this:

Set wrap-text in confirmation modal texts

---

src/api/app/controllers/webui/users/tokens/users_controller.rb
src/api/app/policies/token/workflow_policy.rb

When a user tried to access a list of users of a token (because they knew the URL), these two things used to happen:
- if the user was logged in and wasn't associated to the token -> the page was accessible and it shouldn't
- if the user was **nobody** -> it crashed
We added some authorization to avoid the previous behaviour.
To test this:
- Log in as any user not associated with the token
- Go to localhost:3000/my/tokens/1/users (replace 1 with an ID existing on your DB)
- You shouldn't be able to access it.
- Log out (become **nobody**)
- Go to localhost:3000/my/tokens/1/users (replace 1 with an ID existing on your DB)
- It shouldn't crash
Fixes #12695

Add autorization to token's users index

---

src/api/app/views/webui/users/tokens/users/_breadcrumb_items.html.haml
src/api/app/views/webui/workflow_runs/_breadcrumb_items.html.haml

To have some reference to the token, we add the token id to the breadcrumbs for the workflow runs page and the token's users page.
**Before (without any reference to the token):**
**After:**

Add token id to some breadcrumbs

---

src/api/app/views/webui/users/tokens/new.html.haml

The "service" token type name got renamed from `runservice` to `service`. The automatic selection of the default token type to be created didn't work since then. See #12418.
This pull request updates the default token type, and make use of the default value in the `collection_radio_buttons` helper instead of using JQuery. Now the default token type gets correctly selected.
Fixes #12655.

Update default token type

---

src/api/app/assets/javascripts/webui/delete_confirmation_dialog.js
src/api/app/components/delete_confirmation_dialog_component.html.haml
src/api/app/components/watchlist_component.html.haml
src/api/app/views/webui/users/tokens/users/index.html.haml

Instead of calling the same JS function from different views, we call the JS from the component. It iterates over all the modals in the DOM whose id starts with `#delete`, takes the expected data attributes, if any, and sets those values in the modal content. 
As this code iterates over all deletion modals in the DOM, I would test
- **deleting elements that already call the component**
- add a project to the watchlist
- remove the project from the watchlist using the deletion icon next to the project name
- this should open a modal containing the project name
- click the "Remove" button, and the project should disappear from the list.
- **deleting elements that don't call the component yet**
- go to the same project page
- add a few comments
- delete a comment
- this …

Move JavaScript part into the ConfirmationDialogComponent

---

src/api/app/views/webui/users/tokens/users/index.html.haml

In the token's users page we were rendering one delete confirmation modal per user and per group. That was wrong for two reasons:
- we didn't concatenated the id of the element to the modal id, so we had many elements in the DOM with the same id.
- it's enough to render one model per type of element, as the id of the element is passed in the `action` data attribute (the form URL).

Render modal only once

---

src/backend/BSSched/BuildJob.pm
src/backend/BSXML.pm
src/backend/bs_worker
src/backend/t/1000-bs_worker.t

builder id must not be an internal name, but the configured OBS name instead.
buildType must use a domain registered to us.

[backend] SLSA: minor meta data fixes

---

src/api/app/models/issue_tracker.rb
src/api/test/unit/issue_test.rb

Extracting the CVE issues started failing, and the hardcoded URL became inaccessible. The reason is that it was moved to HTTPS.
I could've also handled the redirection and accessed the URL set in the 'Location' header when the code is '302'. But, as we know the reason and the URL is hardcoded, I prefer to simply fix the URL.
Fixes https://github.com/openSUSE/open-build-service/issues/12747

Change CVE download URL from HTTP to HTTPS

---

src/api/config/application.rb

` Rails.application` is redundant to use inside `application.rb` to access `config`.

Remove unnecessary Rails.application from application.rb

---

src/api/app/models/project/embargo_handler.rb
src/api/spec/models/project/embargo_handler_spec.rb

Before this change, the timezone of an embargo date was ignored.
```
> Time.parse('2022-10-10 10:10:10 CEST').utc
=> 2022-10-10 10:10:10 UTC
```
After this change, the timezone of an embargo date is no longer ignored.
```
> Time.zone.parse('2022-10-10 10:10:10 CEST').utc
=> 2022-10-10 08:10:10 UTC
```
Also throw an error in case that the timezone is not recognized. Otherwise it would take the 'UTC' timezone without erroring.
Related to #12649.

Parse timezone (and abbreviations) for embargo date

---

.circleci/conditional_config.yml
dist/obs-bundled-gems.spec
src/api/Makefile

The system and bundle versions of rake and rack need to match up.
The rake and rack gems are dependencies of passenger that it will load, from the
system, during booting itself. If our bundle versions deviate, then booting our app
will try to load those gems again, which will fail. Which makes for an unbootable
app in production. Which will make people 😠 
See #12756 for a failing example
CI now fails like this
Build now fails like this

Test rack/rake gem versions

---

src/api/app/components/token_card_component.html.haml
src/api/app/views/webui/users/tokens/show.html.haml
src/api/app/views/webui/users/tokens/users/_breadcrumb_items.html.haml
src/api/app/views/webui/users/tokens/users/index.html.haml

The page "Share Token" missed user documentation. This PR adds documentation explaining what is to "Share a token", and how can it be used.
Replace the literal "Users" with "Share". The literal "Users" is not so accurate since the introduction of sharing a token with groups.

Describe what the "Share Token" page is for

---

dist/obs-bundled-gems.spec

No need to escape $ here with $, only needed in the Makefile

Fix rack/rake_version macros

---

dist/obs-bundled-gems.spec

Enforce the use of the defined ruby interpreter in the rake rack version macros

Use of the defined ruby interpreter version

---

src/api/app/models/workflow_run.rb
src/api/spec/models/workflow_run_spec.rb

The status can be `success` or `fail` and represents whether OBS was able to send the report back or not.

Send metrics about ScmStatusReport#status

---

src/api/app/services/scm_exception_handler.rb
src/api/app/services/scm_status_reporter.rb

To track the reason why OBS could not report back to the SCM.

Send metrics about exceptions on ScmStatusReport

---

src/api/app/models/bs_request.rb

User.session is a Thread variable and needs to be reset afterward.
NOTE: This is a backport of #12790 to 2.10

Do not leak the session in auto_accept

---

src/api/app/services/scm_exception_handler.rb
src/api/app/services/scm_status_reporter.rb
src/api/spec/services/scm_status_reporter_spec.rb

One of the exceptions caught by the reporter wasn't stored in a `ScmStatusReport` but in the `WorkflowRun`.
As the exception happens when there is a network glitch between GitHub and Octokit (as mentioned in [this commit](https://github.com/openSUSE/open-build-service/commit/12108241edde4873fcd399b89db51f6726e9adaa)), I don't see why it can not be stored in the `ScmStatusReport` so I adapt the code and apply DRY to the instrumentation.

Report exception to scm status report

---

src/api/app/controllers/source_attribute_controller.rb
src/api/app/models/attrib.rb
src/api/app/models/project/embargo_handler.rb
src/api/spec/models/attrib_spec.rb
src/api/spec/models/project/embargo_handler_spec.rb
src/api/test/functional/maintenance_test.rb

This PR introduces validation for the EmbargoDate attribute.
This means it will be no longer possible to introduce an invalid EmbargoDate attribute.
Anyway, the step of checking for an embargo date when releasing packages still handles the case of invalid embargo dates, which were stored previously in the database. This PR doesn't contain any data migration to modify embargo dates according to the new validation rules.
As a consequence of introducing this validation in the `Attrib` model, some specs were modified to make use of invalid `Attrib` objects. Regarding maintenance minitests, as the case of invalid EmbargoDate attributes is already tested in specs, the minitests were adapted to handle the case of valid EmbargoDate attributes.
To test this PR:
- open the review-app
- go to a …

Introduce validation for EmbargoDate attribute

---

src/api/config/routes/webui_routes.rb

Users containing dots were not redirecting properly, for example
'david.anes' was being detected as 'david' instead.
Fixes #12785

Fix /user/show/:user path

---

src/api/app/models/workflow_run.rb
src/api/app/services/scm_status_reporter.rb

While working in the Grafana panels I realized the metrics I introduced previously can be unified.
From now on, I don't track the metrics inside the methods `save_scm_report_*` but right after they are called, so I can have access to the SCM and the exception and call them only once with all the needed tags.

Unify metrics for ScmStatusReport

---

src/api/spec/support/delayed_job.rb

Add this to your example if you want the ActiveJobs scheduled
in it to perform inline.
```
describe #blah, :perform_active_job do
...
end
```

Introduces perform_active_job example setting

---

src/api/app/models/bs_request_action_delete.rb
src/api/app/models/project.rb

And uses this from BsRequestActionDelete.
Before we have relied on User.run_as in BsRequest.auto_accept
to set User.session (which is a Thread/fiber-local variable).
But in an `after_commit` callback this is not working reliably.
Maybe a race or something with nested transcations or whatnot.
Couldn't figure it out...

Introduces commit_opts[:login] for delete_on_backend

---

src/api/app/models/user.rb
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/sets_the_package.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/sets_the_project.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_not_passing_the_rev_parameter/and_passing_the_page_parameter/returns_the_paginated_revisions_for_the_page_parameter_s_value.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_not_passing_the_rev_parameter/and_passing_the_show_all_parameter/returns_revisions_without_pagination.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_not_passing_the_rev_parameter/returns_revisions_with_the_default_pagination.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_passing_the_rev_parameter/and_passing_the_page_parameter/returns_the_paginated_revisions_for_the_page_parameter_s_value.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_passing_the_rev_parameter/and_passing_the_show_all_parameter/returns_revisions_up_to_rev_parameter_s_value_without_pagination.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_passing_the_rev_parameter/returns_revisions_up_to_rev_parameter_s_value_with_the_default_pagination.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/without_source_access/1_6_1_1.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/without_source_access/1_6_1_2.yml
src/api/spec/controllers/webui/package_controller_spec.rb

This is needed since users sometimes remove themselves from the maintainers of their own home project. It should have never been possible in the first place for users to do this, but here we are. It was quite confusing to users since they could still see the `Create Package` or `Add User` actions, but they were never authorized to do those actions. They should have been able to do them though. This is now addressed.
For now, we can help users by applying this fix. This code from the custom authorization system is called in Pundit, so both authorization systems (custom and Pundit) are covered.
Another important change here is that nothing can prevent a user from managing their home project or a package in their home project. As an example, it was previously possible to prevent users from …

Allow users to manage their own home project and its packages

---

src/api/app/services/github_status_reporter.rb
src/api/app/services/gitlab_status_reporter.rb

I introduced this line to send metrics for exceptions related to the SCM status report:
```
RabbitmqBus.send_to_bus('metrics', "scm_status_report,status=fail,scm=#{@event_subscription_payload[:scm]},exception=#{e} value=1")
```
I wrongly assumed the interpolation (or #to_s) of an Exception object returned its class name. The examples I tested confirmed my assumptions. However, in production we are getting something like this:
```
telegraf_1  | 2022-07-18T06:39:47Z E! [inputs.amqp_consumer] Error in plugin: metric parse error: expected field at 1:68: "scm_status_report,status=fail,scm=gitlab,exception=Server responded with code 403, message: 403 Forbidden. Request URI: https://gitlab.com/api/v4/projects/37880292/statuses/e20492f88e82c193879ec532868e21f2a6067ca8 value=1"
```
The reason is …

Send only exception class name to metrics

---

src/api/app/models/branch_package.rb
src/api/app/models/concerns/scm_sync_enabled_step.rb
src/api/app/models/workflow/step.rb
src/api/app/models/workflow/step/branch_package_step.rb
src/api/app/models/workflow/step/link_package_step.rb
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_package_level/1_1_1_8_2_1.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_package_level/1_1_1_8_2_2.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_package_level/1_1_1_8_2_3.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_package_level/1_1_1_8_2_4.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_package_level/1_1_1_8_2_5.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_project_level/1_1_1_8_1_1.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_project_level/1_1_1_8_1_2.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_project_level/1_1_1_8_1_3.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_project_level/1_1_1_8_1_4.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_project_level/1_1_1_8_1_5.yml
src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_package_level/1_1_1_7_2_1.yml
src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_package_level/1_1_1_7_2_2.yml
src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_package_level/1_1_1_7_2_3.yml
src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_package_level/1_1_1_7_2_4.yml
src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_package_level/1_1_1_7_2_5.yml
src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_project_level/1_1_1_7_1_1.yml
src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_project_level/1_1_1_7_1_2.yml
src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_project_level/1_1_1_7_1_3.yml
src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_project_level/1_1_1_7_1_4.yml
src/api/spec/cassettes/Workflow_Step_LinkPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_project_level/1_1_1_7_1_5.yml
src/api/spec/models/workflow/step/branch_package_step_spec.rb
src/api/spec/models/workflow/step/link_package_step_spec.rb

This PR adds the possibility to rely on the git bridge in the SCM/CI integration of OBS. That means instead of linking or branching packages inside OBS, we are pointing to the correct commit and repository on the SCM for the branch and link package step.
TODO:

Add scmsync to OBS SCM/CI integration

---

src/api/app/controllers/public_controller.rb

controller has it's own usage of CGI.escape not ported. So use
the model method available to build the path.

Allow /public access to files with spaces

---

src/api/Gemfile.lock

This PR removes the need to upgrade nokogiri in #12801. That nokogiri upgrade requires ruby version >= 2.6.0 on [the 2.10 build](https://build.opensuse.org/package/show/OBS:Server:2.10:Staging/obs-server) and we don't want to upgrade ruby right now.

Downgrade nokogiri from 1.13.7 back to 1.13.6

---

src/api/app/controllers/source_controller.rb

only because you can not write to project (may exist and be locked) it does not mean
you can create it when you have write access on the upper level.

[api] sanities permission check

---

src/backend/BSCpio.pm
src/backend/BSSrcrep.pm
src/backend/BSTar.pm

We used to pre-open obscpio files if we are building a cpio list.
This has the disadvantage that we run into the filesystem limit
if we need to send a large number of obscpio files.
This commit adds support for passing a function reference as
file handle to BSCpio and BSTar. We use this to lazily open
obscpio files from the source repository.

[backend] support sending of a large number of obscpio files

---

src/api/app/controllers/application_controller.rb
src/api/app/controllers/concerns/rescue_authorization_handler.rb
src/api/app/controllers/concerns/rescue_handler.rb
src/api/app/controllers/concerns/webui/rescue_handler.rb
src/api/app/controllers/webui/groups_controller.rb
src/api/app/controllers/webui/packages/branches_controller.rb
src/api/app/controllers/webui/webui_controller.rb
src/api/spec/controllers/webui/download_on_demand_controller_spec.rb
src/api/spec/controllers/webui/groups_controller_spec.rb
src/api/spec/controllers/webui/package_controller_spec.rb
src/api/spec/controllers/webui/packages/branches_controller_spec.rb
src/api/spec/controllers/webui/patchinfo_controller_spec.rb
src/api/spec/controllers/webui/project_controller_spec.rb
src/api/spec/controllers/webui/projects/project_configuration_controller_spec.rb
src/api/spec/controllers/webui/repositories_controller_spec.rb
src/api/spec/controllers/webui/staging/projects_controller_spec.rb
src/api/spec/controllers/webui/users_controller_spec.rb
src/api/spec/controllers/webui/webui_controller_spec.rb
src/api/spec/features/webui/attributes_spec.rb
src/api/spec/features/webui/packages_spec.rb
src/api/test/functional/request_controller_test.rb

So you can use `Pundit::NotAuthorizedError.reason` also in the API.
We need that because we have many actions that do not only check
permissions but also processability.

Unify rescue from Pundit::NotAuthorizedError

---

src/api/app/assets/stylesheets/webui/tabs.scss
src/api/app/views/webui/request/beta_show.html.haml

In the request beta_show view, the tabs formed by a list (ul and li) have been adapted to be horizontally scrollable.

Set horizontal scrolling in request redesign

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/controllers/webui/requests/submissions_controller.rb
src/api/app/models/bs_request.rb
src/api/spec/features/webui/requests_spec.rb
src/api/test/functional/request_controller_test.rb

It's confusing any developer who's used to the built-in dynamic finders for ActiveRecord models. If we want a custom exception message for BsRequest#number, we can still do it without overwriting `find_by_number!`.

Do not overwrite dynamic finder find_by_number! for BsRequest

---

src/api/app/views/webui/request/beta_show.html.haml

Slightly adapt the divs and paddings on the skeleton of the request _beta_show_ view.
**Before:**
**After**
DO_NOT_MERGE until PR #12849 is merged.

Improve the style of the request beta_show view

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/controllers/webui/watched_items_controller.rb
src/api/spec/controllers/webui/watched_items_controller_spec.rb

In the API we define `NotFoundError` to add a specific message to a 404 error: _"Make sure you are in the beta program"_.
In the WebUI, even if we set a specific message, it won't be displayed on the error page. So it doesn't make sense to define `NotFoundError`. Therefore we ~raise an `ActiveRecord::RecordNotFound`~ set a flash message and redirect to the root path instead.

Set flash message and redirect instead of raising a non-existant exception NotFoundError

---

src/api/app/controllers/webui/request_controller.rb
src/api/config/brakeman.ignore
src/api/spec/controllers/webui/request_controller_spec.rb

`require_request` is used in a before_filter callback for `changerequest`, `show` and `request_action` actions. The request number has to be passed in the [show](https://github.com/openSUSE/open-build-service/blob/9dbda912de8d0a62aa135f11a7255b00bbb66ca0/src/api/config/routes/webui_routes.rb#L291) and [request_action](https://github.com/openSUSE/open-build-service/blob/9dbda912de8d0a62aa135f11a7255b00bbb66ca0/src/api/config/routes/webui_routes.rb#L297) routes, so it's impossible to not have `number` in the `params`. As for `changerequest`, the request number is also passed in the `params` via a [hidden field](https://github.com/openSUSE/open-build-service/blob/349e41e8a177cd9094d4af8715ebe554f384b28f/src/api/app/views/webui/request/_decision_tab.html.haml#L2) when the form is submitted. …

Simplify require_request method in Webui::RequestController

---

src/api/app/views/webui/request/beta_show.html.haml

The reviewers and other details like _Superseded by 123_ will be displayed in the _Overview_ tab.
Preview of the changes:

Display request creator and creation date in request show redesign

---

src/api/app/views/webui/request/show.html.haml

We should only render the partial if the user is permitted to
add a reviewer to the request.
Realized this while reviewing https://github.com/openSUSE/open-build-service/pull/12869
Its not a big problem, users still cannot add a review when they don't have the permission to do so.

Don't render add_reviewer_modal if user doesn't have permission to do so

---

.circleci/conditional_config.yml

Use less of our CI credits on storage by compressing logs and
capybara dumps. Also makes downloading things faster...

Compress CI artifacts

---

src/api/app/views/webui/request/beta_show.html.haml

Instead of having to look at the _Overview_ tab for this information, it's always available and simply convenient.
Preview of the changes:

Link to superseded request in the state badge

---

src/api/app/policies/workflow_run_policy.rb
src/api/spec/policies/workflow_run_policy_spec.rb

We receive exceptions on the workflow_runs#index endpoint
when the workflow token doesn't exist. Lets return in the used
policy scope to prevent this from happening.
Fixes #12874

Do not crash on workflow run scope when token does not exist

---

src/api/config/initializers/airbrake.rb

We can not really do anything about it on the frontend level.
Fixes #12469

Silence backend error about excessing missing hash entries

---

src/api/public/apidocs-new/paths/published_project_name_repository_name_architecture_name_binary_filename_view_ymp.yaml

Using a reference to the already defined `architecture_name` parameter makes the parameter required, and, for this particular endpoint, this is not the case.
For reviewers:
- Navigate to http://localhost:3000/apidocs-new/index.html#/Published%20Binaries/get_published__project_name___repository_name___architecture_name___binary_filename__view_ymp and check that the `architecture_name` parameter is now not required.

Make architecture_name parameter optional

---

src/api/config/environments/development.rb

In development some `HistoryElements` subtypes do not show when querying the `BsRequest#request_history_elements`.
In development they do not appear because we do not eager load classes, while in production it works flawlessly.

Fix missing HistoryElements

---

src/backend/BSSched/BuildJob/Patchinfo.pm

Prevent from warnings with the form:
`Use of uninitialized value in string eq at /home/frontend/project/src/api/../backend/BSSched/BuildJob/Patchinfo.pm line 694.`
This can be seen in the logs of minitests:

Don't check directly for an unintialized value

---

src/api/.rubocop.yml
src/api/lib/rubocop/cop/view_component/avoid_global_state.rb
src/api/spec/lib/rubocop/cop/view_component/avoid_global_state_spec.rb

This approach is more efficient since only view components are linted, not all files. It's also much more robust, since it relies on the path, not on class names ending with `Component`.
[rubocop-rspec](https://github.com/rubocop/rubocop-rspec/blob/5416f729d4cd0c676334c356a67240dbd2aafd32/config/default.yml#L2-L7) and [rubocop-graphql](https://github.com/DmitryTsepelev/rubocop-graphql/blob/c9303c6b6c136df8f1e4c1ce4b10006c0f43b9a6/config/default.yml#L1-L4) use the same technique.
For reviewers: If you add `params[:something]` to any view component and run `bundle exec rubocop`, it will raise an offense. It doesn't though for other files. This proves the `Include` configuration works.

Run RuboCop cops from ViewComponent namespace only for view components

---

src/api/.rubocop.yml

This was the deprecation warning:
> Warning: obsolete parameter `IgnoredMethods` (for `Style/MethodCallWithArgsParentheses`) found in .rubocop.yml `IgnoredMethods` has been renamed to `AllowedMethods` and/or `AllowedPatterns`.

Fix deprecation warning for RuboCop Style/MethodCallWithArgsParentheses cop

---

src/api/app/views/webui/request/beta_show.html.haml

Nothing is rendered to the right of this heading, so we can safely remove the CSS class.

Remove unneeded class for heading in request show redesign

---

src/api/config/initializers/flipper.rb

It will be enabled back when the feature is usable by beta users.

Disable request_show_redesign feature for beta users

---

src/api/lib/tasks/dev.rake

We sometimes limit features to the staff group, we should
have at least one staff user in the development data.

Put Iggy in the staff group

---

src/api/app/components/bs_request_activity_timeline_component.html.haml
src/api/app/components/bs_request_overview_avatars_component.html.haml
src/api/app/components/bs_request_overview_avatars_component.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/models/review.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_overview.html.haml
src/api/app/views/webui/request/beta_show_tabs/_review_summary.html.haml

Preview of the changes:
For reviewers:
- Log in as `Iggy` / `buildservice`
- Visit https://obs-reviewlab.opensuse.org/rubhanazeem-request-overview/request/show/2
- If you don't see the request show redesign, the feature toggle `request_show_redesign` needs to enabled for the `staff` group in the [Flipper UI](https://obs-reviewlab.opensuse.org/rubhanazeem-request-overview/flipper/features)
- Visit again the request#show page and you should see the redesign now
~**DO NOT MERGE** until we squash the commits.~

Add overview and reviewers information

---

src/api/app/assets/javascripts/webui/comment.js
src/api/app/components/bs_request_activity_timeline_component.html.haml
src/api/app/controllers/webui/comments_controller.rb
src/api/app/models/comment.rb
src/api/app/views/webui/comment/_content.html.haml
src/api/app/views/webui/comment/beta/_comments_thread.html.haml
src/api/app/views/webui/request/beta_show_tabs/_overview.html.haml
src/api/spec/controllers/webui/comments_controller_spec.rb

This changeset handles the creation of new comments, replies, edits and deletions in the beta request show view. 
Comments for Project and Package should behave and look like always.
1. Open a request. You can do it from the [review-app link](https://obs-reviewlab.opensuse.org/danidoni-handle-new-comments-and-replies-correctly-in-the-beta-request-show-page/request/show/2).
2. Go into the notifications page.
3. Open the first request.
4. Create new comments using the 'Add comment' button.
5. Edit existing comments using the 'Edit' button below an existing comment.
6. Reply existing comments using the 'Reply' button below an existing comment.
7. Delete existing comments using the 'Delete' button below an existing comment.

Handle new comments and replies

---

src/api/app/views/webui/request/beta_show.html.haml

This would otherwise cause a 500 error whenever the request doesn't have build results.
Fixes #12936
This is the same approach we use in the "old" request page: https://github.com/openSUSE/open-build-service/blob/44680fe5effdf3fe805fca864fac78ee0b81a8ed/src/api/app/views/webui/shared/_buildresult_box.html.haml#L6-L8
We could potentially rely on the request action type later, but for now, this is good enough.

Show build results only if needed

---

src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml

This made the HTML somewhat hard to follow and caused issues in the layout when the request description is a collapsible text element.
Fixes #12937
Before, with the issue highlighted in the HTML:
After:

Improve HTML in request show redesign's conversation tab

---

src/api/app/views/webui/shared/user_or_groups_roles/_index.html.haml

Without this, it seems to be broken.
Before:
Now:

Display a message when there are no users/groups

---

src/api/app/jobs/measurements_job.rb

With those measurements, we will know which beta features are disabled and how this evolves over the course of time whenever we change those beta features. We will also see spikes in the enabling/disabling of beta features.

Instrument DisabledBetaFeature model

---

src/backend/BSSrcServer/ScmsyncDB.pm

given URL must be normalized in the same way when storing it to DB

[backend] fix scmsync triggering

---

src/api/public/apidocs-new/paths/search.yaml
src/api/public/apidocs-new/paths/search_missing_owner.yaml
src/api/public/apidocs-new/paths/search_owner.yaml
src/api/public/apidocs-new/paths/search_project_id.yaml
src/api/public/apidocs-new/paths/search_published_binary_id.yaml
src/api/public/apidocs-new/paths/search_published_pattern_id.yaml
src/api/public/apidocs-new/paths/search_published_repoinfo_id.yaml

The details of the POST endpoints aren't listed to avoid having outdated information if we update their GET counterparts.

Document deprecated POST search endpoints

---

src/api/app/views/layouts/webui/_footer.html.haml
src/api/app/views/layouts/webui/_left_navigation_nobody.html.haml
src/api/app/views/layouts/webui/_places.html.haml
src/api/app/views/webui/kiwi/images/_preferences.html.haml
src/api/app/views/webui/kiwi/images/_preferences_form.html.haml
src/api/app/views/webui/kiwi/images/_profiles.html.haml
src/api/app/views/webui/main/_latest_updates.html.haml
src/api/app/views/webui/package/_commit_item.html.haml
src/api/app/views/webui/package/_live_build_log_controls.html.haml
src/api/app/views/webui/package/_revision_diff_detail_buttons.html.haml
src/api/app/views/webui/package/_rpmlint_log.html.haml
src/api/app/views/webui/package/_tabs.html.haml
src/api/app/views/webui/project/_form.html.haml
src/api/app/views/webui/project/_monitor_control.html.haml
src/api/app/views/webui/project/_tabs.html.haml
src/api/app/views/webui/project/show_actions/_request_to_release.html.haml
src/api/app/views/webui/projects/pulse/_pulse_list_requests.html.haml
src/api/app/views/webui/shared/user_or_groups_roles/_index.html.haml

Disabling the check on every line which registers an offense allows us to split the fixes in multiple PRs. This makes everything much easier to review.

Temporarily disable haml-lint's InstanceVariables check

---

src/api/app/models/owner_search/base.rb
src/api/lib/api_error.rb

The other search endpoints do not rely on the `limit`parameter, at least not in the same way. They use it for the pagination, so validating the limit only in `OwnerSearch::Base` is fine.

Validate limit in OwnerSearch::Base

---

src/api/spec/README.md

Mostly fixing typos, making it easier to read and removing outdated documentation.
Overall, the README was already in a good state and describing how we work with specs/tests.

Reword spec README

---

.github/labeler.yml

After submitting #12994, I thought this could be automated.

Label PRs as documentation when they contain release notes

---

src/api/public/apidocs-new/paths/search_package.yaml
src/api/public/apidocs-new/paths/search_person.yaml
src/api/public/apidocs-new/paths/search_project.yaml

Also remove that for the match parameter not providing a value will return all packages. This is not the case in those endpoints.
As an example:
```
> osc api "/search/project?match="
Server returned an error: HTTP Error 400: Bad Request
No predicate found in match argument
```

Fix search endpoints where match parameter is required

---

src/api/app/controllers/application_controller.rb
src/api/app/controllers/search_controller.rb
src/api/app/controllers/webui/search_controller.rb
src/api/app/lib/backend/connection.rb
src/api/spec/support/backend.rb
src/api/test/unit/bs_request_test.rb

The `Backend::Test.start` call is only needed when running the minitests. This PR removes the calls to start the test backend from the codebase, not from the tests.
Once the backend test is up, it keeps running until minitests are finished.
Add a call to start the test backend in the first minitest from the group of tests run in the `test:api:group1` group. This makes it possible to run this whole group of tests with a test backend.

Call `Backend::Test.start` only when necessary

---

src/api/script/plugin

It belongs to the initial import of the rails application. It is not used.

Remove obsolete `plugin` script

---

src/api/config/initializers/prefer_xml_over_html.rb
src/api/config/initializers/wrap_parameters.rb

We bring back the changes which were reverted in #13019 and this time, we have a custom Rack middleware to prefer XML over HTML whenever the HTTP header HTTP_ACCEPT isn't set in a request.

Preparation for Rails 7 - Refactor wrap_parameters.rb initializer

---

src/api/app/controllers/webui/request_controller.rb

This is exactly the same as what we already do in the "old" request show page.

Enable the notification toolbar for the request show redesign

---

src/api/spec/requests/default_xml_spec.rb

See more details in the PreferXmlOverHtml initializer.
This PR is related to #13021.

Add test for requests without HTTP_ACCEPT header

---

src/api/app/components/bs_request_overview_avatars_component.html.haml
src/api/app/components/bs_request_overview_avatars_component.rb
src/api/app/views/webui/request/beta_show_tabs/_review_summary.html.haml

Sometimes the package associated with the review is deleted, i.e. after accepting a deletion request. So we stop retrieving those packages and simply display their names as a string.
We do something similar with the deleted projects. Before we didn't display the associated review at all.
As we can't retrieve the users and their avatars, we display the project or package icon as an avatar in the REVIEW section.
**When the project was deleted:**
**When the package was deleted:**

Display review's project/package name as string

---

src/api/app/views/webui/package/_revision_diff_detail_buttons.html.haml

Change missing from previous commit [d1210ac](https://github.com/openSUSE/open-build-service/commit/d1210aca842c01795e262602de6878d137c5e387) where the goal was stopping using `@linkinfo` inside the partial to use `linkinfo` instead.

Replace instance variable by passed local variable

---

src/api/app/components/sourcediff_component.html.haml
src/api/app/components/sourcediff_component.rb
src/api/app/components/sourcediff_tab_component.html.haml
src/api/app/components/sourcediff_tab_component.rb
src/api/app/views/webui/request/request_action.js.erb
src/api/app/views/webui/request/request_action_changes.js.erb

The partial `_revision_diff_detail` is called from the package's controller action `rdiff` (alias `package_rdiff`) or from the request view.
In the first situation, we are setting @linkinfo on the [package controller](https://github.com/openSUSE/open-build-service/blob/334ae03e608468a85b152ce4310571cfc3bb7630/src/api/app/controllers/webui/package_controller.rb#L256) and then it is passed to the partial.
In the second situation, we never set @linkinfo on the [request controller](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/request_controller.rb).
So there is no need to pass @linkinfo to the component in order to always end up passing nil to the partial.
The changes were introduced in [this …

Stop handling linkinfo in sourcediff components

---

dist/munin/obs_worker_cpu_mem
dist/obs_import_srcdebtree
dist/obs_import_srcrpmtree
dist/obsstoragesetup

grep 3.8 starts throwing warnings, and `egrep`/`fgrep` will be dropped long term
https://bugzilla.opensuse.org/show_bug.cgi?id=1203092

Convert usage of egrep to grep -E

---

src/backend/bs_publish
src/backend/bs_repserver
src/backend/bs_signer
src/backend/bs_srcserver

Modern image builder from the systemd project:
https://github.com/systemd/mkosi
Required to ensure the source server finds the recipe, and to allow
the full implementation in obs-build.
Required for: https://github.com/openSUSE/obs-build/pull/861

[backend] add new image format: mkosi

---

src/api/app/assets/stylesheets/webui/timeline.scss
src/api/app/components/bs_request_activity_timeline_component.html.haml
src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/bs_request_history_element_component.html.haml

Relying on the Bootstrap grid isn't needed here, so the templates were also simplified.
Before:
Now:

Expand timeline items all the way to the right

---

src/api/app/assets/javascripts/webui/comment.js
src/api/app/assets/stylesheets/webui/comments.scss
src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/bs_request_history_element_component.html.haml
src/api/app/components/bs_request_history_element_component.rb
src/api/app/views/webui/shared/_collapsible_text.html.haml

With bubbles around comments, we distinguish them from history elements in the request conversation. On top of this, we display different icons for some of the history elements, making them stand out even more. For example, when a review was accepted, we show the same checkmark icon as in the _Reviews_ section.
Preview:

Distinguish comments from history elements in the request conversation

---

src/backend/bs_dodup

The docker registry returns 401 for unknown repositories.

[backend] bs_dodup: treat 401 responses as 404 when querying manifests

---

.github/workflows/brakeman.yml
.github/workflows/pull_request_labeler.yml

This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows.
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes.
Here is an example of the permissions in one of the workflow runs:
https://github.com/openSUSE/open-build-service/runs/8251662522?check_suite_focus=true#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflows:
- brakeman.yml
- pull_request_labeler.yml
The following workflow file already has the least privileged token permission set:
- scorecards.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- GitHub recommends …

ci: add minimum GitHub token permissions for workflows

---

src/api/app/components/bs_request_overview_avatars_component.rb
src/api/app/models/relationship.rb
src/api/spec/components/bs_request_overview_avatars_component_spec.rb

Right now we show all users that have a role assigned on a package,
no matter if the role empowers or requires the user to leave a review
or not. We only want to show user that have a reviewer or maintainer
role on the package. Also if the package has a maintainer or reviewer
assigned we first want to show those and only default to the project
one's if they are missing.
1. Create `Project A` and inside it create `Package A`.
2. Add `Iggy` as `reviewer`.
3. Add `user_1` as `maintainer`.
4. Create `Package B` inside `Project B`.
5. Add `user_2` as `maintainer` of `Package B`.
6. Add `user_3` as `reviewer` of `Package B`.
7. Branch `Package A`, change something and `Submit Request`.
8. In the request, `Add Review` for a package `Package B`.
9. In the request,  the `Review` section should …

Consider maintainer role when showing reviewers for review by_package

---

src/api/app/assets/javascripts/webui/request.js
src/api/app/assets/stylesheets/webui/requests.scss
src/api/app/components/request_decision_component.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/models/bs_request.rb
src/api/app/models/bs_request_action.rb
src/api/app/models/bs_request_action_add_role.rb
src/api/app/models/bs_request_action_change_devel.rb
src/api/app/models/bs_request_action_delete.rb
src/api/app/models/bs_request_action_maintenance_incident.rb
src/api/app/models/bs_request_action_maintenance_release.rb
src/api/app/models/bs_request_action_release.rb
src/api/app/models/bs_request_action_set_bugowner.rb
src/api/app/models/bs_request_action_submit.rb
src/api/app/views/webui/request/_action_text.html.haml
src/api/app/views/webui/request/_actions_details.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_changes.html.haml
src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml
src/api/config/brakeman.ignore
src/api/config/routes/webui_routes.rb

In the beta request show page, we introduced a dropdown to select among different request actions.
How to test?
- Create a request with multiple actions:
`osc --apiurl=http://localhost:3000/ creq -a submit home:Admin hello_world home:Iggy -a submit home:Admin ruby home:Iggy`
or use this
`osc --apiurl=http://localhost:3000 creq $(osc --apiurl=http://localhost:3000 list home:Admin | xargs -I % echo "-a submit home:Admin % home:Iggy" | tr "\n" " ")`
- Open the last request show page in the web UI (with the `request_show_redesign` beta feature enabled)
- You have to see a dropdown on the left. Change between actions.
- You will see some changes
- The text under the title of the request (the one describing the action)
- The Changes tab content changes

Handle multiple BsRequestActionSubmit actions

---

src/api/app/assets/stylesheets/webui/application.scss
src/api/spec/support/shared_examples/features/bootstrap_user_tab.rb

This PR adds two CSS rules:
- scroll offset to let anchor scroll the page but do not scroll behind the fixed top nav bar
- let the scroll happen smoothly and visible, instead of jumping to the offset with no animation
Fixes: https://trello.com/c/m3aezM5E/1953-comment-anchors-dont-account-for-the-height-of-the-top-navbar-m

Set scroll offset for all the pages

---

src/api/app/controllers/source_controller.rb
src/backend/BSSrcServer/ScmsyncDB.pm
src/backend/bs_srcserver

scmsync tags may specify the default branch.
We need to run twice here as it may got specified explicit or not. And the default branch may have changed.

[backend] support triggerscmsync with default branch

---

src/backend/BSSched/Checker.pm

We renamed a variable but forgot to change one place where it was used.
Should have been in commit 9e8f649a22b5d201b279aae7cc82485e685a5c3e

[backend] fix wrong pool usage in crossbuilds

---

src/api/app/views/webui/watched_items/toggle_watched_item.js.erb

We render `DeleteConfirmationDialogComponent` in the layout with `WatchlistComponent`. When an item is added or removed from watchlist the `WatchlistComponent` is rendered again without taking into consideration the `DeleteConfirmationDialogComponent`. This change reset the values used in the delete confirmation modal

Reset values for delete confirmation modal on toggle watched item

---

src/api/app/components/watched_items_list_component.html.haml

When the package or project name is very long and the watchlist bar width is not wide enough, the name breaks and go to the next line at any character as needed. With this PR the name breaks into slices and go to the next line with the entire slice at a meaningful character (for packages the delimiter is `/`, for projects it is `:`)
After:
Fixes: https://trello.com/c/m9bg1tV7

Split package and project name by the slice delimiter only

---

src/api/app/controllers/webui/watched_items_controller.rb

The `@project` variable was not assigned in AJAX requests - it was only assigned in the webui controller. This made not possible to find the package.
Making sure that the `@project` variable is also set for a package in the WatchedItems controller fixes the issue.
How to test the fix, for reviewers:
- Go to a page of a package.
- Click in Watchlist.
- Add/Remove the package from the Watchlist.
- See that the link has changed to Remove/add package from the watchlist.

Fix link of adding/removing a package in watchlist

---

src/backend/bs_signer

An extra `*` means that instead of matching on `mkosi.*` we are matching on `mkosi*`, which happens to include the mkosi package itself, that thus fails as a spurious second build is started.
```
[   29s] lamb13 finished "build mkosi.spec" at Sat Sep 17 22:42:51 UTC 2022.
[   29s]
[   29s] ### VM INTERACTION START ###
[   29s] [   24.170425][    T1] sysrq: Power Off
[   29s] [   24.176008][   T18] reboot: Power down
[   29s] ### VM INTERACTION END ###
[   29s] build: extracting built packages...
[   29s] RPMS/noarch/mkosi-13+186+g769318a-15.1.noarch.rpm
[   29s] SRPMS/mkosi-13+186+g769318a-15.1.src.rpm
[   29s] OTHER/_statistics
[   29s] OTHER/rpmlint.log
[    0s] Using BUILD_ROOT=/var/cache/obs/worker/root_6/.mount
[    0s] Using BUILD_ARCH=x86_64:i686:i586:i486:i386
[    0s] Doing kvm …
```

[backend] mkosi: fix followupfile regex in bs_signer

---

src/api/app/assets/stylesheets/webui/application.scss

We need to remove this property because it affects the logging of build logs. With the presence of this property, the logs get stuck.
Fixes #13086

Remove css property scroll smooth

---

src/api/app/components/watchlist_component.html.haml
src/api/app/components/watchlist_component.rb

The user is already asked for confirmation when deleting an element of the watchlist, clicking on the delete icons. Asking for confirmation was missing, when deleting from the upper link of the watchlist.

Show confirmation dialog when deleting from the upper link from the watchlist

---

docs/api/api/request.rng
src/api/app/models/bs_request.rb
src/api/test/functional/request_controller_test.rb
src/api/test/unit/bs_request_test.rb

Looks like the request API contained the creation timestamps of reviews. This PR brings it back.
Fixes #OBS-215

Provide the timestamp of creation of reviews via API

---

src/api/app/controllers/trigger_workflow_controller.rb
src/api/app/models/scm_webhook.rb

We already have a constant for supported pull/merge request
actions (allowlist). There is no need to create a blocklist
for ignored actions. We can simply make sure the action is not
included in the allowlist. This makes it easier for future
implementations (Gitea), since we don't have to check all possible
actions.

Check pull/merge request action against allowed actions 

---

src/api/app/components/watched_items_list_component.html.haml
src/api/app/components/watched_items_list_component.rb
src/api/app/components/watchlist_component.html.haml
src/api/app/components/watchlist_component.rb
src/api/app/controllers/webui/watched_items_controller.rb
src/api/app/views/layouts/webui/webui.html.haml
src/api/app/views/webui/watched_items/toggle_watched_item.js.erb
src/api/spec/components/watched_items_list_component_spec.rb
src/api/spec/components/watchlist_component_spec.rb

Before this update, we were trying to generalize watch items. This is not correct because the current object could be different from a watched item. That means on a request page current object is the request. Whereas, the watched items could be a package, project, or request.

Track current object in the watchlist

---

src/backend/bs_srcserver

Fix matching iso (.iso OR .iso.report not only iso.report) and the common image formats that we publish.
Came across this while trying to use this view for binary download
```shell
osc api "/build/OBS:Server:Unstable/15.4/x86_64/obs-server/obs-api-2.11~alpha.20220919T123635.aa52f625-150400.14644.3.noarch.rpm?view=publishedpath"
<publishedpath project="OBS:Server:Unstable" repository="15.4">
<path>OBS:/Server:/Unstable/15.4/noarch/obs-api-2.11~alpha.20220919T123635.aa52f625-150400.14644.3.noarch.rpm</path>
<url>https://download.opensuse.org/repositories/OBS:/Server:/Unstable/15.4/noarch/obs-api-2.11~alpha.20220919T123635.aa52f625-150400.14644.3.noarch.rpm</url>
</publishedpath>
```
```shell
osc api "/build/OBS:Server:Unstable/images/x86_64/OBS-Appliance:oem/obs-server.x86_64-2.10.51-oem-Bui …
```

Fix iso/image listing in view=publishedpath

---

src/api/config/initializers/flipper.rb

That makes the feature not to be listed on the beta features configuration page.
TODO in the reference instance as soon as this is deployed:

Remove trigger_workflow from initializer

---

src/api/app/validators/workflow_filters_validator.rb
src/api/spec/validators/workflow_filters_validator_spec.rb

This filter definition is wrong:
```
rebuild_master:
steps:
- rebuild_package:
source_project: home:gyribeiro:containers
source_package: toolbox-osc
project: home:gyribeiro:containers
package: toolbox-osc
filters:
- event: push
```
It should be like:
```
filters:
event: push
```
When we detect something like this, we return a validation error to notify the user.
Fixes #12742

Return an error when filter definition is wrong

---

src/api/app/controllers/application_controller.rb
src/api/app/controllers/concerns/webui/rescue_handler.rb
src/api/spec/controllers/source_controller_spec.rb

Turns for instance this
into this

Display APIError in format.html better

---

src/backend/bs_srcserver

The cache is not used anyway, so no need for the extra work.

[backend] do not try to update the ssl cert if the cache is disabled

---

src/api/lib/tasks/watchlist_migration.rake

Add two rake tasks meant to be used by OBS admins, who want to make easier for OBS intances' users the transition from the project watchlist to the new watchlist.
Please see the description of the commit for details about the tasks added.

Create rake tasks to migrate the old watchlist

---

src/api/app/controllers/source_controller.rb

Calling the API endpoint `/source/:project_name/:package_name?cmd=diff` with `cacheonly` and/or `nodiff` parameters didn't make a difference when retrieving the results from the backend. Both parameters should have been included in the list of parameters accepted by the endpoint above mentioned as they were introduced. Please have a look at the descriptions of the commits for details.

Include `cacheonly` and `nodiff` parameters in package diff

---

src/api/app/assets/stylesheets/webui/coderay.scss

The line class is only applied to highlighted lines, not all of them, so the padding was only applied to those instead of the whole document. This broke the alignment, making diffs harder to read.
Before:
After:

Fix alignment of added/removed lines in CodeRay

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/components/responses/unknown_project_or_package.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_showlinked.yaml

For reviewers, access directly to the documented endpoint in the review app through this [link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newpackage_cmd_showlinked/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_showlinked).

Document package showlinked command with OpenAPI

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_diff.yaml

For reviewers, access directly to the documented endpoint in the review app through this [link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newpackage_cmd_diff/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_diff).

Document package diff command with OpenAPI

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_runservice.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_waitservice.yaml

For reviewers, access directly to the documented endpoint in the review app through these links:
- [runservice](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newpackage_cmd_runservice/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_runservice)
- [waitservice](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newpackage_cmd_runservice/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_waitservice)

Document package services commands with OpenAPI

---

src/backend/bs_publish

Needs also to be backported to 2.10 branch

[backend] create output dir before reconstruct_container

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_undelete.yaml

For reviewers, access directly to the documented endpoint in the review app through this [link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newpackage_cmd_undelete/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_undelete).

Document package undelete command with OpenAPI

---

src/backend/BSSched/BuildJob/Aggregate.pm

We need the .packages, .basepackages, and .report files when publishing containers.

[backend] also aggregate meta files when aggregating containers

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_remove_flag.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_set_flag.yaml

For reviewers, access directly to the documented endpoint in the review app through these links:
- [set_flag](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newpackage_cmd_set_flag_remove_flag/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_set_flag)
- [remove_flag](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newpackage_cmd_set_flag_remove_flag/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_remove_flag)

Document package set_flag/remove_flag commands with OpenAPI

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/components/schemas/revision.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_mergeservice.yaml

For reviewers, access directly to the documented endpoint in the review app through this [link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newpackage_cmd_mergeservice/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_mergeservice).

Document package mergeservice command with OpenAPI

---

src/api/app/controllers/webui/package_controller.rb
src/api/app/models/package.rb
src/api/app/views/webui/package/binaries.html.haml
src/api/spec/features/webui/packages_spec.rb

We need to account for packages that come through project links. The only reasonable place you can know about this is the controller. An instantiated `Package` doesn't know which `Project` it was instantiated with in `Package.get_by_project_and_name`...
Fixes #13147

Move Package.download_url_for_binary back to PackageController

---

src/api/app/views/webui/request/_action_text.html.haml

This PR makes it so that the following information is always visible in the action selector dropdown:
* action type (through `action.name`)
* source_project/source_package (where applicable, only project or both)
* target_project/target_package (plus other targets if included in `action.name`)
* commit information (if available)
1. Create a request with multiple actions
2. Click on `Select Action ▾` button and see a dropdown
3. Dropdown should include all the information specified above wherever applicable

Display relevant information about the actions in the action selector

---

src/api/app/assets/javascripts/webui/request.js
src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/_actions_details.html.haml
src/api/app/views/webui/request/beta_show.html.haml

This PR creates links to different sections of a page with nav-tabs bootstrap elements. Only in the request page of the beta program.
A following pull request will make this same approach general to the application.
Here there is a [link](https://obs-reviewlab.opensuse.org/eduardoj-request_workflow_redesigngeneralize_tab_links/request/show/9) to a request with a couple of actions in the the review-app.

Generalize tab anchor links (I)

---

src/api/app/assets/javascripts/webui/application.js
src/api/app/assets/javascripts/webui/nav_tabs.js
src/api/app/assets/javascripts/webui/user_profile.js
src/api/app/components/workflow_run_detail_component.html.haml
src/api/app/views/webui/comment/_comment_field.html.haml
src/api/app/views/webui/groups/show.html.haml
src/api/app/views/webui/kiwi/_tabs.html.haml
src/api/app/views/webui/kiwi/images/_build_info.html.haml
src/api/app/views/webui/project/show.html.haml
src/api/app/views/webui/request/_actions_details.html.haml
src/api/app/views/webui/request/_handle_request.html.haml
src/api/app/views/webui/request/_request_comments.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/show.html.haml
src/api/app/views/webui/search/_tabs.html.haml
src/api/app/views/webui/shared/_buildresult_box.html.haml
src/api/app/views/webui/user/_involvement.html.haml
src/api/app/views/webui/user/_involvement_and_activity.html.haml
src/api/app/views/webui/users/tasks/index.html.haml

Use the same solution implemented for requests in beta to provide links to show a specific pane of Nav Bootstrap components.
In some cases the pages could be adapted, and the links are generated correctly.
In other cases the pages could not be adapted, so they work as before.
~Still depending on~ Follow up of #13212.
Here there is a list of links to the review-app pages which are examples of the changes in the Nav Bootstrap components of this PR:
- Request show. Try with beta and without beta: [/request/show/9](http://obs-reviewlab.opensuse.org/eduardoj-request_workflow_redesigngeneralize_tab_links_ii/request/show/9)
- Groups show (The name of the group changes with the deployment):
- Go to [User profile](http://obs-reviewlab.opensuse.org/eduardoj-request_workflow_redesigngeneralize_tab_li …

Generalize tab anchor links (II)

---

src/api/app/views/webui/request/_actions.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml

Moving the `Add a request` button within the conversation page, closer to the side link area related to the review section.
Note: the `_actions.html.haml` has been marked `TODO - to drop` because after the roll out of the beta feature redesign, it will be no longer needed.
Fixes https://trello.com/c/p313TsCI

Move review request action button closer to context area

---

src/api/app/assets/javascripts/webui/packages.js
src/api/app/views/webui/package/_revision_diff_detail.html.haml

The definition of the CSS class was removed in commit: 433b7d74a5311269281e524f33d10f52beb5b712
The use of this class should have been also removed in that commit.

Remove use of CSS class details-with-coderay

---

src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_rpm_lint_result.html.haml

This is the first of a series of PRs which implement the Build Results and the RPM Lint sections in the redesigned request page.
In this case, the sections are split into two independent tabs. They don't have actual content yet.
- Enable the beta feature `request_show_redesing` for your user.
- Open a request page.
- Check that the two tabs are there and you can switch tabs without problems.

Add new tab RPM Lint in request page

---

src/api/app/helpers/application_helper.rb
src/api/app/views/webui/package/_revision_diff_detail.html.haml
src/api/app/views/webui/request/beta_show.html.haml

Allow to share a URL referring to a line of a file of the Changes section in requests.
Example of a link pointing to a line of a file in a request, in the [review-app](https://obs-reviewlab.opensuse.org/eduardoj-request_workflow_redesignsharable_urls_for_a_line/request/show/1#diff_0_n4).

Prepend file index to the line link

---

src/api/public/apidocs-new/paths/source_project_name_cmd_freezelink.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_copy.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_mergeservice.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_undelete.yaml

The `user` parameter passed to the backend is always the authorized user in the frontend.
There is no way of changing the `user` parameter for the backend endpoints.

Remove the user parameter from the documentation

---

src/api/app/assets/javascripts/webui/application.js
src/api/app/assets/javascripts/webui/buildresult.js
src/api/app/assets/javascripts/webui/request_show_redesign/build_results.js
src/api/app/controllers/webui/package_controller.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/models/bs_request.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_build_results.html.haml
src/api/app/views/webui/request/beta_show_tabs/_build_status.html.haml

Refactor the bare minimum to make Build Results work in the new request redesigned page, in the new Build Results tab. 
Main changes:
- Extract the code of the build results to their own files, to make it independent of the rpm lint code. 
- Remove previously existing _Build Results_ and _RPM Lint_ tabs.
- Adapt JavaScript accordingly.
- Stop using `index` to identify the different actions in one request.
This is how it looks so far: 
`codeclimate` complains about the long `RequestController#show` action, we are ignoring it during the implementation of `request_show_redesign`.
I'd compare each case with and without the feature flag enabled.
Check different cases:
- When the request contains multiple actions (make sure the source project has working repositories set). …

Isolate and slightly refactor build results' code

---

src/api/app/views/webui/package/rdiff.html.haml

`rdiff` renders `_revision_diff_details` which requires `action_id`

Add action_id to rdiff

---

src/api/app/assets/stylesheets/webui/collapse-component.scss
src/api/app/assets/stylesheets/webui/timeline.scss
src/api/app/components/bs_request_activity_timeline_component.html.haml
src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml

This PR adds an expander/collapser link to toggle visibility of superseded comments and request history.
**Before**
**After**
_Collapsed_
_Expanded_

Show comments and activity from superseded requests

---

src/api/app/views/webui/request/beta_show.html.haml

Right now the line number anchor is replaced with a tab anchor if I reload after selecting a diff. This pr fixes that problem and keep the diff reference attached to the URL

Attach line reference anchor to the URL

---

src/backend/BSASN1.pm
src/backend/BSPublisher/Registry.pm
src/backend/bs_regpush

Mark old manifests/blobs when reusing sigstore data and always use oci mime types.

[backend] fix handling of sigstore data

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_build_results.html.haml
src/api/app/views/webui/request/beta_show_tabs/_rpm_lint_result.html.haml

Sometimes the building/source package is not available from the request page because the package was removed.

Fix issue retrieving building_package

---

src/api/app/assets/javascripts/webui/request_show_redesign/build_results.js
src/api/app/controllers/webui/package_controller.rb
src/api/app/helpers/webui/buildresult_helper.rb
src/api/app/views/webui/request/beta_show_tabs/_build_status.html.haml

On the redesigned request show page, we have a wide area to display the build results, not a small column as we had before.
Please, bear in mind that the code needs a lot of refactoring, but I've just done minimal changes to make it work and fit the new area. A proper refactoring will come soonish.
- Make sure your user has the feature flag `request_show_page` enabled.
- Go to a request page.
- Add many repositories and architectures to the project of the package associated with the request.
- Use the refresh button to see different states of the build results.
- Play around with the question mark icon, the collapse arrow, etc.
`codeclimate` complains about the long `RequestController#show` action, we are ignoring it during the implementation of `request_show_redesign`. …

Redesign UI of the build results tab

---

src/api/app/components/sourcediff_component.html.haml
src/api/app/components/sourcediff_tab_component.html.haml
src/api/app/helpers/application_helper.rb
src/api/app/views/webui/package/_revision_diff_detail.html.haml
src/api/app/views/webui/package/rdiff.html.haml
src/api/app/views/webui/request/_actions_details.html.haml
src/api/app/views/webui/request/beta_show.html.haml

There is no need to include the `action_id` in the fraction identifier (anchor) of the URL. In case of browsing an action, that same action is already included in the URL. Therefore, I reverted the three commits related to this change.
In case we browse a diff line, change `href` attributes of other actions' links to point to the Changes tab.

Fix actions' hrefs when the url contains a line diff

---

src/api/app/controllers/concerns/rescue_authorization_handler.rb
src/api/app/models/token/release.rb
src/api/app/policies/token/release_policy.rb
src/api/spec/controllers/trigger_controller_spec.rb

It failed with an absurd error in the middle of a release when another
releasetarget lacked the permissions.
The `release_package` method of the `MaintenanceHelper` mixin checks
for permission on the given release target/project. But to avoid
incomplete releases, we need to check all release targets of the
collection upfront, before we start to release them one by one.

[api] fix incomplete releases via token

---

src/api/public/apidocs-new/paths/watchlist.yaml

No validation schema is used in this endpoint.

Remove reference to the user.rng schema in the GET watchlist endpoint documentation

---

src/api/app/assets/images/badge-failed.svg
src/api/app/assets/images/badge-percent.svg
src/api/app/assets/images/badge-succeeded.svg
src/api/app/assets/images/badge-unknown.svg
src/api/app/controllers/webui/packages/badge_controller.rb
src/api/app/models/local_build_result/for_package.rb
src/api/app/models/package.rb
src/api/config/routes/webui_routes.rb
src/api/spec/cassettes/Badge/with_failing_and_succeeding_build_results/displays_the_correct_failed_state.yml
src/api/spec/cassettes/Badge/with_failing_and_succeeding_build_results/displays_the_correct_percentage.yml
src/api/spec/cassettes/Badge/with_succeeding_build_results/displays_the_correct_percentage.yml
src/api/spec/cassettes/Badge/with_succeeding_build_results/displays_the_suceeded_state.yml
src/api/spec/cassettes/Badge/without_build_results/displays_the_correct_unknown_state.yml
src/api/spec/cassettes/Badge/without_build_results/displays_the_correct_unknown_state_despite_percent_type.yml
src/api/spec/cassettes/Package/_buildresult/returns_an_object_with_class_LocalBuildResult_ForPackage.yml
src/api/spec/cassettes/Packages/log/download_logfile_succesfully.yml
src/api/spec/features/webui/badge_spec.rb
src/api/spec/features/webui/packages_spec.rb

This adds integration badges for packages
To verify this feature visit `/package/badge/:project/:package.svg` (with optional `percent` and `ratio` type `parameters`)
/package/badge/:project/:package.svg
/package/badge/:project/:package.svg?type=percent
/package/badge/:project/:package.svg?type=ratio
I changed it so that instead of requiring the package, the font is bundled under `app/assets/fonts`.
Fixes #2908 and supersedes #10820

Add the build results badge for the package

---

src/api/spec/features/webui/badge_spec.rb

We can remove the redundant spec type.

Fix RuboCop offense RSpec/Rails/InferredSpecType

---

src/api/app/models/concerns/scm_sync_enabled_step.rb
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_a_package_level_with_a_branch_fragment/1_1_1_8_4_1.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_a_package_level_with_a_branch_fragment/1_1_1_8_4_2.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_a_package_level_with_a_subdir_query/1_1_1_8_3_1.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_a_package_level_with_a_subdir_query/1_1_1_8_3_2.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_a_package_level_with_a_subdir_query_and_a_branch_fragment/1_1_1_8_5_1.yml
src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/when_scmsync_is_active/on_a_package_level_with_a_subdir_query_and_a_branch_fragment/1_1_1_8_5_2.yml
src/api/spec/models/workflow/step/branch_package_step_spec.rb

The SCM workflow creates bogus scmsync URLs when the branched package contains any query or fragment in its url, because the fragment is never removed, it is just appended. To fix this, we use the addressable module to override the fragment via the URI parser instead of doing this ourselves.
This fixes https://github.com/openSUSE/open-build-service/issues/13290

Fix scmsync tag creation for packages with query/fragment in the url

---

src/api/app/controllers/source_controller.rb

... for the `POST /source/{project_name}?cmd=copy API` endpoint
This parameter should have been included in this commit: a19f13e96b1f8f3c405b5062c591640586119e2e

Re-introduce forgotten `resign` parameter

---

src/api/app/models/event_subscription/find_for_event.rb

There is no reason to proceed in the method when there are no receivers for the event for the given role. We can skip and continue with the next receiver_role.

Skip iteration in `FindForEvent#subscriptions` when there are no receivers for the role

---

src/api/public/apidocs-new/paths/source_project_name_cmd_copy.yaml

Document parameters `comment`, `noservice` and `withhistory` for the `POST /source/{project_name}?cmd=copy` endpoint.
Also improve the documentation of this same endpoint.

Document the rest of parameters for `POST /source/{project_name}?cmd=copy`

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/rake_support.rb
src/api/lib/tasks/multiple_actions_request.rake
src/api/lib/tasks/workflows.rake

This is the first in a series of PRs refactoring the dev tasks. The plan is to move some tasks from `dev.rake` to different individual files. They will be placed in the `lib/tasks/dev` directory.
In this first PR, I extract methods that are going to be used by different tasks to a file we can require later.

Extract methods used by many tasks to a file

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/rake_support.rb
src/api/lib/tasks/dev/staging.rake

This is the 5th in a series of PRs refactoring the dev tasks. The plan is to move some tasks from `dev.rake` to different individual files. They will be placed in the `lib/tasks/dev` directory.
In this PR, I move the tasks related to staging to an individual file in `lib/tasks/dev`.

Extract staging tasks

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/notifications.rake
src/api/lib/tasks/dev/rake_support.rb

This is the 4th in a series of PRs refactoring the dev tasks. The plan is to move some tasks from `dev.rake` to different individual files. They will be placed in the `lib/tasks/dev` directory.
In this PR, I move the tasks related to notifications to an individual file in `lib/tasks/dev`.

Extract notifications tasks

---

CONTRIBUTING.md
src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/lint.rake

This is the 7th and last in a series of PRs refactoring the dev tasks. The plan is to move some tasks from `dev.rake` to different individual files. They will be placed in the `lib/tasks/dev` directory.
In this PR, I move the tasks related to linters to an individual file in `lib/tasks/dev`.
Developer, bear in mind that the commonly used rake task `rails dev:lint` is renamed to `rails dev:lint:all`.

Extract linters tasks

---

src/api/app/assets/javascripts/webui/application.js
src/api/app/assets/javascripts/webui/write_and_preview.js
src/api/app/components/write_and_preview_component.html.haml
src/api/app/components/write_and_preview_component.rb
src/api/app/controllers/webui/status_messages_controller.rb
src/api/app/views/webui/status_messages/edit.html.haml
src/api/app/views/webui/status_messages/new.html.haml
src/api/config/routes/webui_routes.rb

The status messages accept markdown. We find it helpful to see a preview before we save it.
**How to test in review-app?**
- Log in as Admin.
- Go to the OBS home page.
- Click on "Create Status Message"
- Add some text applying markdown.
- Click on the _Preview_ tab and check if the markdown is applied correctly.
- Save the status message and check the message is displaying, with the correct markdown applied, in the News section.

Add markdown preview to status message

---

src/api/.rubocop.yml
src/api/app/models/event_subscription/find_for_event.rb

We recently faced an issue where a user received notifications
for events without subscription. In order to identify the source/cause,
debugging output will help to follow the connections between Event,
Subscription and Receiver.
*Example output:*
```
Looking at Admin for 'commenter' and channel 'instant_email'
Skipped receiver Admin, since it is the originator of the event...
People to receive something: []
Looking at Admin for 'source_maintainer' and channel 'instant_email'
Skipped receiver Admin, since it is the originator of the event...
People to receive something: []
Looking at foo, bar for 'target_maintainer' and channel 'instant_email'
Expanding group bar...
Looking at foo, foo for 'target_maintainer' and channel 'instant_email'
Skipped receiver foo, since it is already in the …
```

Add debug mode to EventSubscription::FindForEvent#subscription

---

src/api/app/controllers/webui/request_controller.rb

This happened because issues aren't always defined in the source diffs, so we cannot expect that they are present.

Fix error "no implicit conversion of nil into Hash"

---

src/api/lib/tasks/dev.rake
src/api/spec/factories/bs_request_actions.rb

Provides a BsRequest submit action with a file diff.
- Run the `dev:development_testdata:create` rake task on a local OBS instance.
- Once it finishes, boot up the local instance [as usual](https://github.com/openSUSE/open-build-service/wiki/Development-Environment-Tips-&-Tricks#control-services).
- http://localhost:3000/package/show/home:Admin/package_with_diff is the created package with the file diff.
- Navigate to [its open requests](http://localhost:3000/package/requests/home:Admin/package_with_diff) 
- And check the Changes tab of that request. There you'll find the file diff

Enhance the BsRequestAction factory

---

src/api/app/services/gitlab_status_reporter.rb
src/api/app/services/scm_exception_handler.rb

I've realized this is wrong after looking into #13377.
The payload of GitLab is defined as such:
https://github.com/openSUSE/open-build-service/blob/29fe2bfa66335797cce355f8f70500685056e507/src/api/app/services/trigger_controller_service/scm_extractor.rb#L16-L17
https://github.com/openSUSE/open-build-service/blob/29fe2bfa66335797cce355f8f70500685056e507/src/api/app/services/trigger_controller_service/scm_extractor.rb#L47-L81
This is where the payload is passed to the event subscription:
https://github.com/openSUSE/open-build-service/blob/29fe2bfa66335797cce355f8f70500685056e507/src/api/app/models/workflow/step.rb#L53

Use the correct keys for GitLab in GitlabStatusReporter and SCMExceptionHandler

---

src/api/lib/tasks/dev.rake

Renamed to `dev:test_data:create`.
Updated in `obs-review-apps` which uses this task. Please review the PR [#22](https://github.com/openSUSE/obs-review-apps/pull/22).
Updated the two appearances in the wiki:
- https://github.com/openSUSE/open-build-service/wiki/Notifications#create-notifications-in-your-development-environment
- https://github.com/openSUSE/open-build-service/wiki/Development-Environment-Tips-&-Tricks#create-data-to-play-with-in-development

Rename dev:development_testdata:create task

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/requests.rake

To avoid extending the `dev:test_data:create` task too much, we move the code that creates requests and actions to `lib/tasks/requests.rake` (as tasks) and call them from the previous one.
- Run `rails dev:test_data:create`.
- Run the task independently:  `rails dev:requests:request_with_submit_action_and_diff`.
In both cases, a new `package_with_diff` will be created together with a request associated to that package.

Extract request and action creation to its own file

---

src/api/.rubocop_todo.yml
src/api/app/assets/javascripts/webui/request_show_redesign/build_results.js
src/api/app/assets/stylesheets/request_show_redesign/build_results.scss
src/api/app/assets/stylesheets/webui/application.scss
src/api/app/assets/stylesheets/webui/borders.scss
src/api/app/components/build_result_for_architecture_component.html.haml
src/api/app/components/build_result_for_architecture_component.rb
src/api/app/helpers/webui/buildresult_helper.rb
src/api/app/models/buildresult.rb
src/api/app/views/webui/request/beta_show_tabs/_build_results.html.haml
src/api/app/views/webui/request/beta_show_tabs/_build_status.html.haml
src/api/spec/components/build_result_for_architecture_component_spec.rb
src/api/spec/components/previews/build_result_for_architecture_component_preview.rb

Propose another design for the new build results tab including
- bigger and soberer help icon,
- many results per row in large viewports and minimized content in small ones,
- more descriptive tooltip,
among many other improvements.
TODO:
If you already ran the `development_testdata` rake task you'll have a few requests already, you can see them in the Tasks menu.
Add some repositories to the project related to the request you choose. 
Then go to see the build results. For example, request for `home:Admin/package_b`.
In review-app:
https://obs-reviewlab.opensuse.org/saraycp-improve_new_build_results/request/show/9/request_action/9#tab-pane-build-results

Improve new build results view

---

src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml

To make it clear that this is an "auto-accept" request, I add a badge next to the title.
The details are given in a warning box on top of the decline/accept box.
**Before:**
**After**

Add warning about request auto-acceptance

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/requests.rake

Try it in the development environment with: `bin/rails dev:requests:request_with_build_results`
Example of running the new task in a Rails console:
```
frontend@45673968231d:/obs/src/api> bin/rails dev:requests:request_with_build_results
Creating a request which builds and produces build results...
* Request 17 has been created.
To start the builds confirm or perfom the following steps:
- Create the interconnect with openSUSE.org
- Create a couple of repositories in project home:Iggy or in project home:Iggy:branches:home:Admin
frontend@45673968231d:/obs/src/api> 
```

Add rake task to create request with build results

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/requests.rake
src/api/spec/factories/bs_request_actions.rb

This PR replaces the call to `request_with_submit_action_and_diff` during the data generation by the this new `request_with_multiple_submit_actions_and_diffs` because the new rake task kind of includes the previous one.

Add a multiaction submit request

---

src/api/app/components/notification_filter_component.html.haml
src/api/app/views/webui/users/notifications/index.html.haml

This caused the list of filters to be displayed incorrectly:
A small adjustment in the way list-group is used corrects it:

Correct the usage of list-group in notifications

---

src/api/app/views/webui/package/_deps.html.haml
src/backend/BSXML.pm
src/backend/bs_repserver

This adds displaying file list in the binary view
To verify:
1. Create a package that builds some binaries (I think obs-build only supports file lists in rpm and deb?, so build one of those)
2. Open binary view
3. See list of files in the package
Fixes #613

Display file list in the binary view

---

src/api/Gemfile.lock
src/api/Gemfile.next.lock

The builds in OBS are currently failing because the package updated bundler to 2.3.26, and bundler tries to download that version from the internet (which obviously doesn't work). This should fix that issue

Update the bundler version in Gemfile.lock

---

src/api/app/models/event/base.rb

Before, a database query was sent for each user watching a package/request. Now, it's a single database query for all users watching a package/request, no matter how many users are involved.
I realized that this can be improved after commenting on #13438. See the [discussion](https://github.com/openSUSE/open-build-service/pull/13438#discussion_r1033527555).

Fix N+1 queries when fetching users of a watched package/request

---

src/backend/bs_signer

Do not check the 'result' element, as it is set by the repo server. Also make the error message appended to the log file more informative.

[backend] fix fatal errors not failing sign jobs

---

src/api/app/assets/javascripts/webui/request.js
src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/config/routes/webui_routes.rb

Fixes issue #13443 only for beta, more concretely what refers to this sentence of [this comment](https://github.com/openSUSE/open-build-service/issues/13443#issuecomment-1329586992): 
> With the beta, the [button](https://github.com/openSUSE/open-build-service/blob/b07306d87baffd72a1ba7e51a64b1978a348ddfc/src/api/app/components/sourcediff_component.html.haml#L5) calls the loadChanges() JS function, but this function was removed in https://github.com/openSUSE/open-build-service/commit/2f23bedd1f100e6dcd7ac1ab23f3153982755b29 as part of https://github.com/openSUSE/open-build-service/pull/13029.

Bring back AJAX calls to request changes in beta

---

src/api/app/controllers/person_controller.rb
src/api/app/views/models/_user.xml.builder
src/api/app/views/person/userinfo.xml.builder
src/api/spec/controllers/person_controller_spec.rb
src/api/test/functional/person_controller_test.rb

The `new_watchlist` feature has been enabled for all the users for a while now. It's time to replace the old code by the new one.
This PR only replaces the API's watchlist code.
Play around with these endpoints, they should keep working:
- https://build.opensuse.org/apidocs-new/#/Person/put_person__login__watchlist
- https://build.opensuse.org/apidocs-new/#/Person/get_person__login__watchlist

Replace old watchlist code by code under new_watchlist feature in API

---

src/api/app/models/notification.rb
src/api/app/models/notified_project.rb
src/api/db/migrate/20221123163119_change_notifications_primary_and_foreign_keys_to_bigint.rb
src/api/db/schema.rb

We are adding new notification types which could increase the number of notifications considerably, so we extend the capacity of the primary key (from `int` to `bigint`) to avoid future overflow.
Not only do we extend the `Notification#id` and `NotifiedProject#id` but also the `NotifiedProject#notification_id`.
After running the migration these should be the results (from `int(11)` to `bigint(20)`):
```
MariaDB [api_development]> DESCRIBE notifications id;
+-------+------------+------+-----+---------+----------------+
| Field | Type       | Null | Key | Default | Extra          |
+-------+------------+------+-----+---------+----------------+
| id    | bigint(20) | NO   | PRI | NULL    | auto_increment |
+-------+------------+------+-----+---------+----------------+
```
```
MariaDB …
```

Extend notifications primary and foreign keys capacity

---

src/api/app/models/event_subscription/for_channel_form.rb

This PR enables the subscription to build failure events.
It does not actually delivers the notifications. That is covered in #13447

Enable build failure subscriptions for web channel

---

src/api/app/controllers/webui/project_controller.rb
src/api/config/routes/webui_routes.rb
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_namespace_called_base_/1_14_1_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_namespace_called_base_/behaves_like_a_valid_project_saved/1_14_1_2_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_namespace_called_base_/behaves_like_a_valid_project_saved/1_14_1_2_2.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_called_maintenance_project/1_14_2_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_called_maintenance_project/behaves_like_a_valid_project_saved/1_14_2_2_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_called_maintenance_project/behaves_like_a_valid_project_saved/1_14_2_2_2.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/1_14_3_1_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/1_14_3_1_2.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/1_14_3_2_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/1_14_3_2_2.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/1_14_3_3_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/1_14_3_3_2.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/behaves_like_a_valid_project_saved/1_14_3_1_3_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/behaves_like_a_valid_project_saved/1_14_3_1_3_2.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/behaves_like_a_valid_project_saved/1_14_3_2_3_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/behaves_like_a_valid_project_saved/1_14_3_2_3_2.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/behaves_like_a_valid_project_saved/1_14_3_3_3_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_a_param_that_disables_a_flag/behaves_like_a_param_that_creates_a_disabled_flag/behaves_like_a_valid_project_saved/1_14_3_3_3_2.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_an_invalid_project_data/1_14_4_1.yml
src/api/spec/cassettes/Webui_ProjectController/GET_create/with_an_invalid_project_data/1_14_4_2.yml
src/api/spec/cassettes/Webui_ProjectController/GET_monitor/with_a_project/with_buildresult/without_results/1_22_1_4_2_1.yml
src/api/spec/controllers/webui/project_controller_spec.rb
src/api/spec/controllers/webui/watched_items_controller_spec.rb

We are replacing the old watchlist code with the new one step by step.
In this case, we focus on removing `ProjectController#toggle_watch` which is now replaced by `Webui::WatchedItemsController#toggle_watched_item`.

Remove ProjectController#toggle_watch method

---

src/api/app/models/event_subscription/find_for_event.rb
src/api/app/services/notification_service/web_channel.rb
src/api/spec/services/notification_service/web_channel_spec.rb

`receivers_and_subscriptions` hash did not end up with any groups whatsoever, so the delivery of web notifications about groups wasn't working. This should fix that
1. Create a group and join a user to it
2. Have the group have a role in a project
3. Perform an action that would result in a notification in that project (except for `Event::Relationship*` one, that's addressed in another PR)
4. See if the user got notified about it

Deliver web notification to group members

---

src/api/app/models/bs_request_permission_check.rb

example: The current source revision in SUSE:Maintenance:26696/tar.SUSE_SLE-15_Updateare not on revision e56083b71a6732bddb9cf68337b8bdcd anymore.

[api] fix whitespace in error message

---

src/backend/bs_worker

Backport commit 4defddcfff did miss some conditionals and thus broke emulated builds on 2.10 releases.
This trivial fix adds the missing conditionals and fixes it for me (tested with qemu:ppc64le).

fix emulated build with OBS_VM_TYPE=qemu:$arch in 2.10 branch

---

src/api/app/components/notification_action_description_component.rb
src/api/app/components/notification_component.rb
src/api/app/components/notification_notifiable_link_component.rb
src/api/app/models/event/build.rb
src/api/app/services/notification_service/notifier.rb
src/api/spec/services/notification_service/notifier_spec.rb
src/api/spec/support/shared_contexts/a_user_and_subscriptions_with_defaults.rb

This PR allows subscribers to receive notifications when a package fails to build.
This is how a notification for a package build failure looks like:
This is a follow up of #13428 
Edit: Update screenshot

Receive notifications for build failures

---

src/api/app/models/event_subscription/find_for_event.rb
src/api/spec/mailers/event_mailer_spec.rb
src/api/spec/models/event_subscription/find_for_event_spec.rb

This enables filtering of the `Event::Relationship*` event types based on the type of subscription. This should have been included originally, because as it is, the notification avoids being filtered with the subscription settings for groups, and instead sends mails to all the members of the group.
Fixes #12588

Use the group subscription settings for Event::Relationship*

---

src/api/app/components/notification_action_description_component.rb
src/api/app/components/notification_filter_component.html.haml
src/api/app/components/notification_filter_component.rb
src/api/app/controllers/webui/users/notifications_controller.rb
src/api/app/queries/notifications_finder.rb
src/api/spec/components/notification_filter_component_spec.rb
src/api/spec/controllers/webui/users/notifications_controller_spec.rb
src/api/spec/factories/notification.rb

Now that we can receive notifications for build failure events, we
need a way to filter them from the rest.
This is a follow up of #13447

Implement filters for build fail events

---

src/api/app/models/bs_request.rb

If there is an error at least log it so we can think of how we can get out of this situation.

Log reason for request decline during auto_accept

---

src/api/spec/controllers/search_controller_spec.rb

This should have been removed in commit: a946785979e30d966fd0071e602f573b7b5fe32f.

Drop unused 'find attribute' shared example

---

docs/api/api/constraints.rng
src/backend/bs_worker

No own element as we don't do this for other archs like power neither

[backend] report x86-64 architecture level as well via cpu flags

---

dist/obs-server.spec
dist/obsstoragesetup
dist/obsworker
dist/sysconfig.obs-server
src/backend/bs_worker

Now that https://github.com/openSUSE/obs-build allows to support network for VMs with `--vm-network` param, offer the possibility to enable this in the worker config using the option:
`OBS_VM_ENABLE_NET=true` in `/etc/sysconfig/obs-server`
Needs an `obs-build` version including https://github.com/openSUSE/obs-build/pull/725
It can be needed to build package relying for example on Maven (as its dependency management is pretty broken), i think that many private instances owners would find it useful, i'm personally running similar patches for years:
- https://github.com/algolia/open-build-service/tree/2.10.1-kvm-net
- https://github.com/algolia/obs-build/tree/20191114-kvm-net
Includes also a small fix of the spec file to prevent build failure if some files do not exists.

[backend] support network during (kvm) VM builds

---

src/api/app/models/issue_tracker.rb

A bugzilla issue might get reassigned to a user who is not registered in OBS. Resetting the owner of the issue in that case to avoid dangling issues for a user.

[api] fix bugzilla issue owner, when new owner is unknown

---

src/api/app/models/scm_webhook.rb
src/api/app/models/token/workflow.rb
src/api/app/validators/scm_webhook_event_validator.rb
src/api/spec/models/token/workflow_spec.rb

This should make GitHub display a green status next to ping events when first creating webhooks in repos.
1. Set up testing according to [instructions on the wiki](https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration-Testing)
2. Send out a ping request
3. See a green response in OBS (and/or GitHub depending on the setup)

Support the GitHub ping event

---

src/api/app/services/workflows/yaml_to_workflows_service.rb
src/api/spec/services/workflows/yaml_to_workflows_service_spec.rb
src/api/spec/support/files/multiple_workflows.yml

See the [developer documentation](https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration-Workflows#placeholder-variables) for details on this feature.
Using YAML variables like described [here](https://stackoverflow.com/questions/4150782/use-yaml-with-variables/20467816#20467816) isn't possible. The YAML library errors out with `mapping values are not allowed in this context at line X column Y (Psych::SyntaxError)`. Line _X_ and column _Y_ is wherever there is a YAML variable in a workflows file. This is why we parse the placeholder variables before a workflows file is parsed into YAML.

Support placeholder variables in workflows

---

src/api/config/initializers/flipper.rb

This is to prevent PRs which are removing rolled-out feature toggles too early, like in #13108 (see this [comment](https://github.com/openSUSE/open-build-service/pull/13108#issuecomment-1346437038)).

Clarify when ENABLED_FEATURE_TOGGLES should be changed

---

src/api/app/models/bs_request.rb
src/api/test/unit/bs_request_test.rb

A user who declined a review should also be able to revert it by setting it to new again.
This solves #2923

[api] allow to reopen a declined review

---

src/api/app/services/trigger_controller_service/scm_extractor.rb
src/api/spec/services/trigger_controller_service/scm_extractor_spec.rb

The json payload key `:after` in the webhook of a push event from GitHub contains the sha of the tag itself. Instead we need to use the commit sha the tag is refering to. This is part of `:head_commit => :id`.
Fixes #13206

Use correct commit sha on tag push in scm/ci integration for github

---

src/api/app/controllers/concerns/triggerable.rb
src/api/app/controllers/source/errors.rb
src/api/app/controllers/staging/errors.rb
src/api/app/controllers/trigger/errors.rb
src/api/app/models/bs_request/errors.rb
src/api/app/models/bs_request_action/errors.rb
src/api/app/models/bs_request_action_maintenance_release/errors.rb
src/api/app/models/concerns/project_distribution.rb
src/api/app/models/concerns/scm_sync_enabled_step.rb
src/api/app/models/issue/errors.rb
src/api/app/models/package/errors.rb
src/api/app/models/project/errors.rb
src/api/app/models/token/errors.rb
src/api/app/models/workflow/step/errors.rb
src/api/config/initializers/logging.rb

If we don't make use of `included`, `prepended` or `class_methods` in these modules, we can get rid of using a concern.
Take as a reference the [ActiveSupport::Concern](https://api.rubyonrails.org/classes/ActiveSupport/Concern.html) documentation.

Stop using concerns where they are not needed

---

src/api/app/models/workflow.rb

There is no project that should be deleted for the set_flags step in a workflow, when a PR is closed on the SCM. There for it should be one of the steps that gets rejected when we clean up. This will also fix an issue, since the `target_project_name` method of the `SetFlags` expects to get passed a keyword argument, which all other steps don't.
Fixes #12637

Reject set_flags step when deleting projects after a PR was closed

---

src/api/app/models/workflow/step/set_flags.rb
src/api/spec/models/workflow/step/set_flags_step_spec.rb

In some cases the flag exists by default. For example the
flag of type `publish` always exists, only the status
can differ. In this case the set_flags step was returning
anyways and didn't updated the status.
Fixes https://github.com/openSUSE/open-build-service/issues/12609

Update flag status in set_flags step when flag already exists

---

src/api/app/components/add_review_dropdown_component.html.haml
src/api/app/components/bs_request_history_element_component.html.haml
src/api/app/controllers/webui/request_controller.rb
src/api/app/models/history_element/request_review_added.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_ask_for_review.html.haml
src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml
src/api/app/views/webui/request/beta_show_tabs/_conversation_aside.html.haml

Refactoring:
- do not use a link implementation for an action button, use a proper button instead
- do not group reviews by type (accepted|open|declined), just list them by timeline
Rewording:
- `add review` --> `add reviewer`
Additional changes:
- show _who was added_ as a reviewer in the history

Refactoring "review" side section

---

src/api/app/models/badge.rb
src/api/spec/models/badge_spec.rb

Fixes #13560
Sometimes final results are different than failed and succeeded, but that wasn't handled by the badge code before. This fixes it

Handle results other than success and failure in badge

---

src/api/app/instrumentations/workflow_placeholder_variables_instrumentation.rb
src/api/app/services/workflows/yaml_to_workflows_service.rb

This prevents errors if placeholder variables are changed, renamed, etc...

Rely on constant when mapping placeholder variables

---

src/api/app/policies/cloud/azure/configuration_policy.rb
src/api/app/policies/event_subscription/form_policy.rb
src/api/app/policies/staging/workflow_policy.rb
src/api/app/policies/token_policy.rb
src/api/app/policies/users/patchinfos_policy.rb
src/api/app/policies/users/task_policy.rb
src/api/app/policies/webui/status_message_policy.rb
src/api/app/policies/webui/user_policy.rb
src/api/app/views/webui/main/_status_messages.html.haml

Before, options passed to the policies were simply ignored and the default values were always taken. Only `Staging::WorkflowPolicy` was correct.
I realized this was wrong while pairing with @ncounter as we worked on a feature.

Correctly merge default options in policies

---

src/api/app/views/webui/groups/index.html.haml

This instance variable is not set in Webui::GroupsController and there are no partials beside `_tabs.html.haml` and
`_breadcrumb_items.html.haml` under `app/views/webui/configuration/`, so this can be safely removed.
Co-authored-by: Dario Leidi <dleidi@suse.com>

Remove unneeded variable @namespace in groups#index

---

src/api/app/components/bs_request_history_element_component.html.haml
src/api/app/models/history_element/request_review_added.rb
src/api/spec/components/bs_request_history_element_component_spec.rb

Fixes #13610
The code assumed the `HistoryElement::RequestReviewAdded#description_extension` always contained a review ID, but that's not true for old requests/history_elements.
When the review ID is present:
When the review ID is NOT present:

Avoid errors when description_extension is nil

---

src/api/spec/features/webui/projects_spec.rb

Provide a title and a description for the project which is tested. Otherwise tests compare against nil, throwing this warning:
```
Checking for expected text of nil is confusing and/or pointless since it will always match. Please specify a string or regexp instead. /root/project/src/api/spec/features/webui/projects_spec.rb:14
```

Fix warnings in project feature tests

---

src/api/app/helpers/webui/user_helper.rb
src/api/app/views/webui/users/_delete_dialog.html.haml
src/api/app/views/webui/users/index.html.haml
src/api/spec/features/webui/users/admin_configuration_spec.rb

Instead of generating html code for each modal that asks for removing a user, only one modal is created. Arguments for the modal are passed with "data-*" attributes.
Fixes #13604.

Refactor removing a user

---

src/api/app/views/webui/repositories/_edit_repository_modal.html.haml

Prevent the following warning to be raised:
```
warning: deprecated Object#=~ is called on Repository; it always returns nil
```

Pass a string to valid_xml_id

---

src/api/app/controllers/webui/status_messages_controller.rb
src/api/app/models/status_message.rb
src/api/app/policies/webui/status_message_policy.rb
src/api/app/views/webui/configuration/_tabs.html.haml
src/api/app/views/webui/main/_status_messages.html.haml
src/api/app/views/webui/status_messages/_breadcrumb_items.html.haml
src/api/app/views/webui/status_messages/edit.html.haml
src/api/app/views/webui/status_messages/index.html.haml
src/api/app/views/webui/status_messages/index.js.haml
src/api/app/views/webui/status_messages/new.html.haml
src/api/config/routes/webui_routes.rb
src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/news.rake
src/api/spec/controllers/webui/status_messages_controller_spec.rb

`Manage News` is a new page to you guessed it, manage news / status messages!!! We went with `News` to be consistent with the UI on the homepage which refers to status messages as news. This confusion naming will be aligned in #13574.
The page works with AJAX, we didn't implement a full-text search since this would have increased the scope of the changes. It's accessible from the homepage by clicking on `News` and also from a tab under the `Configuration` page.
Preview:
Closes #13458

Manage News in a dedicated page

---

src/api/app/assets/stylesheets/webui/application.scss
src/api/app/assets/stylesheets/webui/bs5-shims.scss
src/api/app/components/workflow_run_request_action_filter_component.html.haml
src/api/app/views/webui/request/show.html.haml

This is a part of https://github.com/openSUSE/open-build-service/pull/13602, updating sr-only class to visually-hidden

visually-hidden shim for bootstrap 5 migration

---

src/api/app/assets/stylesheets/webui/bs5-shims.scss
src/api/app/views/webui/shared/_repositories_flag_table.html.haml

This is a part of https://github.com/openSUSE/open-build-service/pull/13602, updating table classes

Add table shim for bootstrap 5 migration

---

src/api/app/controllers/webui/groups/users_controller.rb
src/api/app/controllers/webui/groups_controller.rb
src/api/app/policies/groups_user_policy.rb
src/api/app/views/webui/groups/_group_members.html.haml
src/api/spec/controllers/webui/groups_controller_spec.rb
src/api/spec/policies/groups_user_policy_spec.rb

Even if they aren't an admin or a maintainer of the group.
Closes #13406
Example - While logged in as _Iggy_, I can remove myself from the group. The alignment is a bit off in this case, but I didn't want to tackle this in this PR.

Allow users to remove themselves from a group

---

.circleci/conditional_config.yml

This check is not waiting for the database to be up.
It has not been an issue that the database is not up and not ready to run the tests.

Remove check of database in CircleCI

---

src/api/spec/components/notification_action_description_component_spec.rb

Prevent this warning to be thrown in the test suite:
```
The :exact option only has an effect on queries using the XPath#is method. Using it with the query "div.smart-overflow" has no effect.
```

Fix warning in notification spec

---

src/api/app/models/buildresult.rb

The exact literal from the warning is:
```
/root/project/src/api/app/models/buildresult.rb:89: warning: redefining constant Struct::StatusCount
```

Prevent warnings involving Struct::StatusCount from appearing

---

src/api/app/components/status_message_component.html.haml
src/api/app/views/webui/main/_latest_updates.html.haml
src/api/app/views/webui/shared/user_or_groups_roles/_list.html.haml

Discovered while working on bs5, but applies to bs4 as well. It's better to use margins instead of spaces, to avoid issues with link overlap for example

Improving spacing on main page and tables

---

src/backend/BSVerify.pm

[backend] forbid _project as package name in verify_pack()

---

src/api/app/models/package.rb
src/api/app/models/project.rb
src/api/app/models/remote_project.rb
src/api/db/migrate/20230109131251_remove_updated_at_index_from_packages_and_projects.rb
src/api/db/schema.rb

This index is super harmful as it allows only one package operation at the same time and generating this index can take a long time. This leads to timeout errors on package operations easily.
I am not aware where this index would be useful atm.

Remove index on updated_at column in packages and projects tables

---

src/api/app/lib/backend/logger.rb

Prevent this messages from appearing in our test suite:
```
log writing failed. "\xE5" from ASCII-8BIT to UTF-8
```

Log special characters to `backend_access.log`

---

src/api/app/models/project.rb

In [this issue](https://github.com/openSUSE/open-build-service/issues/13544), the project we are trying to restore contains one package called `_meta` that makes the restore code crash because `package.meta.content` is nil in [this line](https://github.com/openSUSE/open-build-service/blob/1989d07ba15697ad561fc53a3d66956d0c555ef7/src/api/app/models/project.rb#L145).
Package names like `_meta` are now forbidden in frontend and backend code. The one in the issue was probably created before we introduced the validations.
We should be able to restore the rest of the packages and the project by ignoring packages whose names are invalid.
Fixes #13544
*NOTE:* it's not worth adding a spec as it requires skipping validations from both [the …

Allow project restoring when package name is invalid

---

src/api/app/views/webui/status_messages/edit.html.haml

This is a follow-up of https://github.com/openSUSE/open-build-service/pull/13649, there was a form adaptation missing.
While renaming the routes from status_message to news_item, this form should've been adapted too.
We need to specify the URL to avoid it taking the default [PATCH] "/status/messages/:id".
**Test**
Try to update a News item (a.k.a status message). It was not possible before this change.

Use news_item route on the update form

---

src/api/lib/tasks/dev/requests.rake

In order to improve the request show page we need to deal with many actions in the `Select Action` dropdown.
Run `rails dev:requests:multiple_actions_request` locally to create a request with 8 submit actions.

Update rake task to create many request actions

---

src/api/app/assets/stylesheets/webui/application.scss
src/api/app/assets/stylesheets/webui/bootstrap_variables/options.scss
src/api/app/views/webui/package/live_build_log.html.haml

This fixes #13689, as well as lacking background in live build log header

Fix live build log after bootstrap 5 migration

---

src/api/app/views/webui/request/beta_show.html.haml

After the upgrade to Bootstrap 5, the `auto-accept` badge was not visible (white on top of white).
Now we use the classes needed to make it look like a badge but with the alert colors.

Fix auto-accept badge for requests

---

src/api/app/assets/stylesheets/webui/requests.scss
src/api/app/controllers/webui/request_controller.rb
src/api/app/models/history_element/request_review_added.rb
src/api/app/models/review.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml
src/api/app/views/webui/request/beta_show_tabs/_conversation_aside.html.haml

Currently when a request gets a review for a staging workflow project, a note is displayed saying that the request is staged in that staging workflow project. This PR expands that a little bit, by displaying that the request is unstaged at first, when submitted to a staging project, staged when the staging manager group accepts the review and staged to a staging workflow project when there's a review for that project.

Display information about the staging workflow in request

---

src/api/app/views/webui/request/_actions_details.html.haml

Especially in dropdowns with a lot of request actions, it's helpful to have the dropdown centred on the current action (the one we are currently displaying on the page).

Scroll towards the current action in the dropdown

---

src/api/app/assets/javascripts/webui/request.js
src/api/app/views/webui/request/_add_reviewer_dialog.html.haml

To test this change please open add review modal and verify the labels and options of the first dropdown

Clarify the meaning of different reviewer types

---

src/api/app/views/webui/package/_revision_diff_detail.html.haml

Aftermath from bs5 migration
|Before|After|
|:---|:---|
|![Screenshot from 2023-01-17 13-25-53](https://user-images.githubusercontent.com/114928900/212898953-7413e351-ce62-47d7-8061-4b71fe8404c3.png)|![Screenshot from 2023-01-17 13-26-17](https://user-images.githubusercontent.com/114928900/212898960-da6823bf-31cd-4696-930f-01ee086f20e2.png)|
This happens with files that don't have a diff, like binaries

Fix overflow in revision diff view

---

src/api/app/components/sourcediff_component.rb
src/api/app/controllers/webui/package_controller.rb
src/api/app/services/sourcediffs_parser.rb

This change was missing when the parser for request diffs was introduced in #13684.

Parse diffs also in Files Changed between revisions

---

src/api/app/assets/stylesheets/webui/flash.scss

Those classes are sometimes extending rules (like with `@extend .alert-warning`) and the rules from `flash.scss` affect those extended rules. This should only be the case for alert elements, which is what we have now with this PR.
Nothing changes visually for the flash messages.

Restrict .alert-* classes to alert elements

---

src/api/app/helpers/webui/request_helper.rb
src/api/spec/helpers/webui/request_helper_spec.rb

After working in #13720, it showed up that rendering the file name for renamed files in diffs was missing or not rendered correctly: the old file name was missing.
This fix applies for both, beta program and non-beta.
**Before:**
**After:**
The issue with the badge style will be fixed as soon as #13720 is merged.

Show old file name for renamed files in diffs

---

src/backend/bs_publish

It would be nice to allow also multiple checksum hashes in parallel, but createrepo_c is not supporting it atm.
Also, the setting to sha512 overrules legacy setting on purpose to be on the safe side.

[backend] Add option to use sha512 for repomd metadata

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml

Make it clearer in the description of the API that clients must provide the xml accept header. Otherwise they could access the Web user interface.
Access the new API documentation page in the review-app through [this link](http://obs-reviewlab.opensuse.org/eduardoj-apidocs_newclarify_xml_headers/apidocs-new/).

Clarify Accept header for API requests

---

src/api/app/views/webui/request/_breadcrumb_items.html.haml

Previously, it would only match on URLs like `/request/show/14`, but not on `/request/show/14/request_action/26`. The second URL example is what we get whenever selecting an action in the `Select Action` dropdown of the request#show page with the `request_show_redesign` feature toggle.
Now, breadcrumbs are displayed for both URLs.

Correctly check for the current page in request breadcrumbs

---

src/api/app/models/package.rb
src/api/lib/tasks/dev.rake

If the issue trackers are not written to the backend, the issues will never be parsed from the changes files or patchinfos.
The  [IssueTrackerWriteToBackendJob](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/jobs/issue_tracker_write_to_backend_job.rb) is in charge of populating the backend with issue trackers from the database. The job is called in an `IssueTracker` `after_save` [callback](https://github.com/openSUSE/open-build-service/blob/12fdb5db6e3fc67c7d83c2cf804c810552a97f8a/src/api/app/models/issue_tracker.rb#L16).
In the development environment, the Issue Trackers are seeded into the database, so there is no callback and the job is never called. That's why we have to call it manually after seeding the database.
Co-authored-by: Eduardo Navarro …

Write issue trackers to backend after seeding them

---

src/api/app/assets/stylesheets/webui/diff.scss
src/api/app/views/webui/package/_revision_diff_detail.html.haml

This could technically support any number of digits, but I didn't want to use `style` in haml, to use the exact number, so this PR only supports up to 10 digits. That should be more than enough for most cases.
|Before|After|
|:---|:---|
|![Screenshot from 2023-01-18 15-35-33](https://user-images.githubusercontent.com/114928900/213199462-ec6d7e58-44a5-4b1f-9b81-57bc9067d7b7.png)|![Screenshot from 2023-01-18 15-36-21](https://user-images.githubusercontent.com/114928900/213199467-3d372d56-43b2-4893-a114-6f4076a171f2.png)|

Make index of the diff fit within the column

---

src/api/.rubocop.yml
src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/requests.rake
src/api/spec/factories/packages.rb
src/api/spec/fixtures/files/factory_package.changes
src/api/spec/fixtures/files/factory_package.spec

In this PR I refactor the task in such a way that:
- It creates a request with several actions (26 of type submit and one of type add_role)
- The involved packages contain changes in their `.changes` files with issue codes, in such a way that it generates Mentioned Issues.
- In addition to the changes in the `.changes`, they introduce changes to the `README.txt`
- Since each package contains a valid `.spec`, the packages will build.
I recommend starting from a clean backend and database, so
```
docker-compose stop; docker-compose rm db backend; rake docker:build; docker-compose up
```
and run the `test_data` task from the container afterwards
```
bundle exec rake dev:test_data:create
```
The output will give you the request number.
Open that request in your browser and …

Task request with mentioned issues and more

---

src/api/app/components/action_seen_by_user_component.html.haml
src/api/app/components/action_seen_by_user_component.rb
src/api/app/controllers/webui/action_seen_by_users_controller.rb
src/api/app/models/bs_request_action.rb
src/api/app/models/user.rb
src/api/app/views/webui/action_seen_by_users/toggle.js.erb
src/api/app/views/webui/request/_action_text.html.haml
src/api/app/views/webui/request/_actions_details.html.haml
src/api/config/routes/webui_routes.rb
src/api/db/migrate/20230116143207_create_bs_request_actions_seen_by_users.rb
src/api/db/schema.rb
src/api/spec/models/bs_request_action_spec.rb

https://trello.com/c/OVu6ybaT
Let the user mark an action request as seen or not in order to be able to not load it back if he already viewed it.

Mark bs_request_action as seen by user

---

src/api/app/assets/stylesheets/webui/links.scss

For consistency with how it used to be prior to the move to Bootstrap 5.

Don't underline urls

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/requests.rake

Changed the existing rake task to create a request with multiple submit requests. Those submit requests come from home:Iggy's packages, that push a sample spec to the backend so they build successfully and produce a diff.
For review purposes I added Leap 15.4 under [home:Iggy](https://obs-reviewlab.opensuse.org/danidoni-multi-action-submit-request-with-build-rpmlint-and-diffs-rake-task/project/show/home:Iggy) to kickstart the building process, you can review the sample request [here](https://obs-reviewlab.opensuse.org/danidoni-multi-action-submit-request-with-build-rpmlint-and-diffs-rake-task/request/show/10).
I recommend starting from a clean backend and database, so
```
docker-compose stop; docker-compose rm db backend; rake docker:build; docker-compose up
```
and run …

Create a request with multi submit actions, builds and diffs

---

src/backend/call-service-in-container

It is always the same cache independ of any used subdir cgi parameter

[backend] fix caching when using with obs_scm_bridge

---

dist/systemd/obsapisetup.service
dist/systemd/obsscheduler@.service
dist/systemd/obsservicedispatch.service
dist/systemd/obssigner.service
dist/systemd/obssourcepublish.service

Esp. obssigner did start before storage was mounted when running without obsstoragesetup service.

[dist] fix some systemd service dependencies

---

src/api/app/controllers/search_controller.rb
src/api/lib/xpath_engine.rb
src/api/spec/controllers/search_controller_spec.rb

Don't use the APIError exception in the XpathEngine parser. Instead, make the search controller throw an APIError exception when an exception is found in XpathEngine.
Prevent from showing detailed Ruby error messages.
Fixes #13657.
Before:
```sh
> osc api '/search/request?match=('
Server returned an error: HTTP Error 400: Bad Request
failed to parse #<NoMethodError: undefined method `[]' for nil:NilClass
contents = contents[1..-2]
^^^^^^^>
```
After:
```sh
> osc api '/search/request?match=('
Server returned an error: HTTP Error 400: Bad Request
Error found searching elements 'request' with xpath predicate: '('.
Detailed error message from parser: failed to parse xpath expression
```

Rearrange exceptions for xpath parser and search controller

---

src/api/app/models/branch_package.rb
src/api/test/test_helper.rb

The logger method can be called from any model. There is no need to redefine it in a model.
From the [official guide](https://guides.rubyonrails.org/debugging_rails_applications.html#sending-messages):
_To write in the current log use the logger.(debug|info|warn|error|fatal|unknown) method from within a controller, model, or mailer._

Remove redundant logger method

---

src/api/app/controllers/source_controller.rb
src/api/app/lib/backend/connection.rb
src/api/public/apidocs-new/components/parameters/diff_file.yaml
src/api/public/apidocs-new/components/parameters/diff_file_deprecated.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_diff.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_linkdiff.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_servicediff.yaml

Introduce a new `file[]` query parameter which allows to filter for several files, for these API endpoints:
- `POST /source/{project_name}/{package_name}?cmd=diff`
- `POST /source/{project_name}/{package_name}?cmd=linkdiff`
- `POST /source/{project_name}/{package_name}?cmd=servicediff`
Also, mark the `file` query parameter as deprecated in the documentation.
Fixes #13543.

Filter package diff by multiple files

---

src/api/lib/xpath_engine.rb
src/api/spec/controllers/search_controller_spec.rb

Parsing XPath string can result in exceptions thrown by the XPath parser.
Catch this exception and answer with a 400 error instead of with a 500.
This PR is a follow up to #13785.
Before:
```sh
> osc api '/search/request?match=)]'
Server returned an error: HTTP Error 500: Internal Server Error
```
After:
```sh
> osc api '/search/request?match=)]'
Server returned an error: HTTP Error 400: Bad Request
Error found searching elements 'request' with xpath predicate: ')]'.
Detailed error message from parser: Garbage component exists at the end: <]>: </request[)]]>
```

Answer with a 400 (bad response) instead of crashing

---

src/api/app/models/token/errors.rb
src/api/app/services/workflows/yaml_to_workflows_service.rb
src/api/spec/services/workflows/yaml_to_workflows_service_spec.rb
src/api/spec/support/files/unparsable_workflows_placeholders.yml

This shows a nicer error when formatting of the workflows yaml fails due to non existent placeholder variable
In order to verify this:
1. Create a workflow
2. Set a workflows.yml containing random invalid placeholder variables (starting with `%`) around the file
3. Trigger a workflow run
4. See it show a nice error telling you what's wrong

Rescue format errors when parsing workflows yaml

---

src/api/app/models/workflow.rb

There is no project that should be restored for the set_flags step in a workflow, when a PR is reopened on the SCM. There for it should be one of the steps that gets rejected when restoring. This will also fix an issue, since the target_project_name method of the SetFlags is private and expects to get passed a keyword argument, which all other steps don't.
Fixes #13338
Very similar to https://github.com/openSUSE/open-build-service/pull/13538

Reject set_flags step when restoring projects after a PR was reopend

---

src/api/app/models/event/service_fail.rb
src/api/app/models/event/service_success.rb

Add monitoring for Event::ServiceFail
Because we need to see in monitoring / be alerted about excessive ServiceFail events
to fix issues before too many users are affected.

Add monitoring for Event::ServiceFail

---

src/api/app/models/branch_package.rb
src/api/test/test_helper.rb

Reverts openSUSE/open-build-service#13761
https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/63e4d91184bf460565f2de6e
My guess is that this there is a problem with this change and auto loading in production...

Revert "Remove redundant logger method"

---

src/api/app/components/workflow_run_row_component.html.haml

On wider viewports, using col-1 ends up taking up 1/12 of the width of the container, while an icon might not need that much space. col-auto adjusts the container to fit the icon inside instead
|Before|After|
|:---|:---|
|![Screenshot from 2023-02-09 13-49-38](https://user-images.githubusercontent.com/114928900/217817467-636b8a6f-c676-4df2-8a87-73e2f321557c.png)|![Screenshot from 2023-02-09 13-49-33](https://user-images.githubusercontent.com/114928900/217817462-fb6c293f-294f-4f7d-a438-3de983e6b0c2.png)|

Make the workflow runs status icon take less space in the list

---

src/api/app/queries/workflow_runs_finder.rb

WorkflowRun finder was using an iterator to count the number of workflow runs grouped by generic event type. The iterator logic was increasing the page loading time.
With this PR the loading time is reduced. These calculations are based on 20000 records
**Before:** loading time was > 6 seconds
**After:** Loading time is < 1 second (~0.17 seconds)

Performance of the workflow runs UI 

---

dist/functions.setup-appliance.sh
src/backend/BSSrcServer/Signkey.pm

fixing cleanup of temporary config file as well
This requires sign 2.7.3 or newer, otherwise a buffer limit will be reached.

[dist] create also a 4k rsa key on the appliance

---

src/backend/bs_publish

This should improve the chances that noarch rpms come from the x86_64 scheduler.

[backend] bs_publish order scheduler archs lexicographically reverse

---

src/api/app/models/workflow_run.rb
src/api/spec/models/workflow_run_spec.rb

Gitea headers also contain headers of GitHub. To identify GitHub it is important to check the absence of gitea headers.

Workflow runs show view displays incorrect SCM name in webhook tab 

---

src/api/app/controllers/person/token_controller.rb
src/api/app/policies/token/rss_policy.rb
src/api/app/policies/token/workflow_policy.rb
src/api/app/policies/token_policy.rb
src/api/app/views/webui/user/_index_actions.html.haml
src/api/spec/components/token_card_component_spec.rb
src/api/spec/controllers/person/token_controller_spec.rb
src/api/spec/controllers/trigger_workflow_controller_spec.rb
src/api/spec/controllers/webui/users/tokens_controller_spec.rb
src/api/spec/policies/token/workflow_policy_spec.rb
src/api/spec/policies/token_policy_spec.rb
src/api/spec/support/beta.rb

After rolling out the `trigger_workflow` feature more than 4 months ago, it's time to clean up the code to remove all the feature flag checks.
Make sure your user is [out of beta](http://localhost:3000/my/beta_features) and try to create/edit/update a workflow token [from the UI](http://localhost:3000/my/tokens) and also trigger one.

Trigger workflow cleanup

---

src/api/app/views/status.xml.builder
src/api/spec/controllers/search_controller_spec.rb

Before, when a null byte had to be shown in an API status message, an exception was thrown. XML doesn't allow rendering null bytes (\u0000).
Now, the string '\u0000' is shown instead, allowing error status messages to be rendered.
This PR is a follow up to #13786.
Before:
```sh
> osc api "/search/request?match=/e%00"
Server returned an error: HTTP Error 500: Internal Server Error
```
After:
```sh
> osc api "/search/request?match=/e%00"
Server returned an error: HTTP Error 400: Bad Request
Error found searching elements 'request' with xpath predicate: '/e\u0000'.
Detailed error message from parser: illegal token X ':document'
```

Prevent null bytes in API status messages from throwing an exception

---

src/api/app/components/card_component.html.haml
src/api/app/components/card_component.rb
src/api/spec/components/previews/card_component_preview.rb

The new **Card** is a [View Component](https://viewcomponent.org/) meant to unify usages of the [Boostrap card](https://getbootstrap.com/docs/5.0/components/card/) when it is a simple element with a title, few actions and a custom content. The implementation uses advantages of [View Component Slots](https://viewcomponent.org/guide/slots.html) and it comes with some [View Component Previews](https://viewcomponent.org/guide/previews.html).
The previews to check out how the component can look like are available [here](https://obs-reviewlab.opensuse.org/ncounter-card-component/rails/view_components/card_component/)

Create a new component for a Card

---

src/api/app/assets/stylesheets/webui/repositories.scss
src/api/app/views/webui/repositories/_dod_repository_card_content.html.haml
src/api/app/views/webui/repositories/_project_repositories.html.haml
src/api/app/views/webui/repositories/_repository_card_content.html.haml
src/api/app/views/webui/repositories/_repository_entry.html.haml

Based on top of https://github.com/openSUSE/open-build-service/pull/13809 to make use of the new default component in the repository instances
A preview is available [here](https://obs-reviewlab.opensuse.org/ncounter-repository-card/repositories/home:Admin)

Use card component for repository card

---

src/api/app/validators/workflow_filters_validator.rb
src/api/spec/validators/workflow_filters_validator_spec.rb

We cannot filter branches for a tag push event, since the tag is referring to a certain commit and has no reference to a branch. Therefore the webhook does not contain the information about the branch.
Fixes #13206
I will add a note to the docs

Disallow branch filters for tag push event

---

src/api/app/jobs/daily_user_activity_measurement_job.rb

Collect more user activity stats
to give us a better view on how much OBS is used across weeks and months.

Collect more user activity stats

---

src/api/app/controllers/trigger_workflow_controller.rb
src/api/app/models/gitea_payload.rb
src/api/app/models/gitea_payload/push.rb
src/api/app/models/github_payload/push.rb
src/api/app/models/scm_webhook.rb
src/api/spec/models/scm_webhook_spec.rb
src/api/spec/services/trigger_controller_service/scm_extractor_spec.rb

When the push event is triggered when a branch/commit got deleted, there is nothing to run the workflow for. In those cases we should simply return and do nothing.
We realized that while working on https://github.com/openSUSE/open-build-service/pull/13847

Ignore github push events for deleted refs

---

src/api/app/views/webui/users/tokens/new.html.haml

This is an improvement on top of #13854, but it can be shipped alone by itself.
- From [Admin's tokens page in the Review App instance](https://obs-reviewlab.opensuse.org/danidoni-prevent-sending-large-token-descriptions/my/tokens)
- Try to create a Service token and try to set a description that is longer than 64 characters
- You should not be able to, as the input field stops at 64 characters preventing you to enter anything else.

Prevent sending large token descriptions

---

src/api/app/models/scm_webhook.rb
src/api/spec/models/scm_webhook_spec.rb

When an upstream branch/commit is deleted, GitLab triggers a Push Hook event.
It makes no sense to try to run a workflow on something removed (i.e. because a merge request was merged or closed and then the branch was removed).
As we do with GitHub [here](https://github.com/openSUSE/open-build-service/pull/13852), we will ignore these kinds of push events.
Unlike GitHub, GitLab doesn't provide a `deleted` field or similar in the payload, so we rely on the `after` field which always contains a commit SHA like this: `0000000000000000000000000000000000000000`.

Ignore GitLab push events for deleted references

---

src/api/test/functional/source_services_test.rb
src/backend/BSSrcServer/Service.pm
src/backend/bs_srcserver

Checking if any service is actually configured to be executed on the server side. Avoid creating a service mark and service run in that case.

[backend] avoid service marks with local only services

---

src/api/app/lib/backend/connection_helper.rb
src/api/spec/lib/backend/connection_helper_spec.rb

This caused users that had files with spaces in packages not to be able to modify them in the frontend. Files would instead be saved with a plus instead of space. This is a follow up to #12466, since that wasn't tackled in that PR, this came up with #13281, as the response from the backend was inconsistent with what we were uploading

Let users save files with spaces in them

---

src/api/app/models/bs_request_action.rb
src/api/app/models/bs_request_actions_seen_by_user.rb
src/api/app/models/user.rb

This feature was implemented in #13702.
Updating specs isn't needed since the method [BsRequestAction#toggle_seen_by](https://github.com/openSUSE/open-build-service/blob/b637d1118d0c9b3a6937959a281fb01cd13e19df/src/api/app/models/bs_request_action.rb#L840-L848) is already covered by [specs](https://github.com/openSUSE/open-build-service/blob/b637d1118d0c9b3a6937959a281fb01cd13e19df/src/api/spec/models/bs_request_action_spec.rb#L400-L433), so associations are correctly defined.

Instrument the "Request Action Seen" feature

---

src/api/app/assets/stylesheets/webui/timeline.scss
src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/bs_request_history_element_component.html.haml
src/api/app/components/bs_request_history_element_component.rb
src/api/app/views/webui/request/beta_show_tabs/_conversation.html.haml

The action, represented by an icon, is displayed first. The icon size was increased to show its importance. Right after, we display the user who did that action.

Follow information hierarchy in conversation timeline

---

src/api/app/assets/javascripts/webui/write_and_preview.js

Since the upgrade to Bootstrap 5 the preview message tab in the [Create News Item](https://build.opensuse.org/news_items/new) page stopped working because Bootstrap 5 doesn't use jQuery anymore.
- Go into the [Create News Item page](https://obs-reviewlab.opensuse.org/danidoni-fix-create-status-preview-tab/news_items/new) logged in as Admin.
- Write some message into the Message box.
- Click on the Preview tab
- You should get you message rendered back in the Preview tab (that does not work right now on [our production instance](https://build.opensuse.org/news_items/new))

Fix preview message tab click under bootstrap 5

---

src/api/app/controllers/webui/package_controller.rb
src/api/app/helpers/webui/package_helper.rb
src/api/app/models/package.rb
src/api/config/initializers/marcel.rb
src/api/spec/helpers/webui/package_helper_spec.rb
src/api/test/unit/package_test.rb

Since we don't get enough information from the backend about the files, we don't know what their mime types are, but we can use Marcel, which is built into Rails nowadays, to guess the mimetypes from the extensions. We could use file content, but that seems inefficient. Sadly due to its license, Marcel uses Apache Tika database for mime information, instead of Freedesktop one, which is more complete, so we need to append some mime configuration in the initializer
This is intended to fix #13613

Use Marcel:Magic instead of hardcoded binary extensions

---

src/api/app/assets/stylesheets/webui/application.scss

Right now selected anchor tags are covered when the notification toolbar is present. Increasing the value by the height of the notification toolbar prevents it from happening.
Now:

Increase `scroll-padding-top` value by height of notification toolbar

---

src/backend/bs_publish

createrepo_c renamed the --filelists_ext to --filelists-ext before the release, and this patch follow the rename.
See #12358 for more information.

[backend] rename "--filelists-ext" parameter for createrepo

---

src/api/spec/components/previews/bs_request_history_element_component_preview.rb

Both `RequestReviewAdded` and `RequestSuperseded` history elements look different from the rest of the history elements' types.  So it's worth having a preview of the first one too.

Add preview for HistoryElement::RequestReviewAdded

---

src/api/app/views/webui/users/tokens/new.html.haml

When dealing with errors on the form, the view would crash with an:
undefined method `token_services_path'
trying to build the form action url, because we don't use tokens but its subclasses (like Token::Service)
Forcing the path ensure we use existing route.
Fixes #13853
- From [Admin's tokens page in the Review App instance](https://obs-reviewlab.opensuse.org/danidoni-fix-token-service-description-too-large-errors/my/tokens)
- Create a Service token and try to set a description that is longer than 64 characters
- It should not crash. It should flash you an error saying that the `Description is too long (maximum is 64 characters).`

Fix form path when dealing with service tokens

---

src/api/app/controllers/application_controller.rb

Make sure that the content of `summary` can be searched for null bytes and replaced with a valid XML string. Valid for the case of an XML status response.
Related to #13788.
Fixes #13883.

Ensure that the status summary is a string

---

src/backend/BSPublisher/Container.pm
src/backend/BSRepServer/Containerinfo.pm

Allow to publish multiple containers with same tag, but for different operating systems via the registry
Avoid conflicts in repository build pool by limiting it to linux OS containers for now.

[backend] container: Allow to publish multi-os

---

src/api/.database_consistency.todo.yml
src/api/app/models/role.rb

database_consistency couldn't find the following association class names, causing it to exit with error, this fixes the issue.

Remove association errors from database_consistency

---

src/api/app/assets/stylesheets/webui/diff.scss

We correctly calculate the max digits but for some reason the line index digits needs a +1 to correctly display diffs
Example of broken diffs: ![image](https://user-images.githubusercontent.com/6298234/220337232-7d8969f0-88b0-4c8f-8106-cc5fd9aa56b9.png)

Fix broken diffs

---

src/backend/call-service-in-container

This patch is required to enable network access in call-service-in-container for cargo_vendor/go_modules services

added cargo_vendor/go_modules to call-service-in-container

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/_actions_details.html.haml
src/api/app/views/webui/request/beta_show.html.haml

Allows you to quickly switch between subsequent actions in a request

Implement next and previous buttons for paginating actions

---

src/api/spec/components/bs_request_activity_timeline_component_spec.rb

We had implemented the component but not the specs. Here they are.

Add specs for BsRequestActivityTimelineComponent

---

src/api/app/views/webui/request/_actions_details.html.haml
src/api/app/views/webui/request/beta_show.html.haml

Fix including `<p>` elements inside other `<p>` elements in the requests and actions views. That results in an invalid HTML, and the HAML parser was preventing this from happening creating `<p></p>` groups of HTML elements.
A series of changes have been made in this pull request:
- Rearrange the title of the card and the text of the card, adjusting margins. Before, all the text belonged to the  `card-title` CSS class.
- Substitute `font-italic` with `fst-italic`. This should have been changed in the migration to Bootstrap 5.
- Wrap simple text not including `<p>` elements into `<p>` elements.
- Wrap the rest of the text groups into `<div>` elements with the following classes: `.d-flex.flex-wrap.mb-3.align-items-center`. That allowed to remove the use of `.align-middle`.

Fix arrangement of request show view HTML elements

---

src/api/spec/components/bs_request_history_element_component_spec.rb
src/api/spec/factories/history_elements.rb

I decided to test, at least once, the elements that are always present after this [conversation](https://github.com/openSUSE/open-build-service/pull/13918#issuecomment-1451664915). Like the icon, time, avatar, etc.
So I extend the specs to do so and apply DRY rule too. I also added the missing `comment` parameter to the factories.
**Tip for reviewers:** don't compare with the previous version, review it as it was a new spec.

Extend specs for BsRequestHistoryElementComponent

---

src/api/spec/components/bs_request_comment_component_spec.rb

I decided to test, at least once, the elements that are always present after this [conversation](https://github.com/openSUSE/open-build-service/pull/13918#issuecomment-1451664915).
So I extend the specs to do so and apply DRY rule too.
**Tip for reviewers:** don't compare with the previous version, review it as it was a new spec.

Extend specs for BsRequestCommentComponent

---

src/api/app/views/webui/request/_action_text.html.haml

The text for the add_role actions seems a bit redundant to me. Sorry I didn't realize before.
What about this?
**Before:**
**After:**

Reduce redundancy on add_role action text

---

src/api/app/controllers/webui/package_controller.rb
src/api/app/controllers/webui/project_controller.rb
src/api/app/views/layouts/webui/_notification_toolbar.html.haml
src/api/app/views/layouts/webui/webui.html.haml
src/api/app/views/webui/request/_actions_details.html.haml

The notification toolbar is used in the project and package roles pages to show a link to go back to the request action.
Also fixes #13890.

Add link to related roles for "Add Role" action

---

src/api/app/controllers/person_controller.rb
src/api/app/controllers/public_controller.rb

`Exception` is the root of Ruby's exception hierarchy. Rescuing from `Exception` will apply rescue to any error, including subclasses such as `SyntaxError`, `LoadError`, and `Interrupt`.
In the controllers of our Rails application, we need to rescue from exceptons thrown from the basecode, not other ones.

Replace rescuing `Exception` with `StandardError`

---

src/api/app/components/watchlist_icon_component.html.haml
src/api/app/views/webui/package/_basic_info.html.haml
src/api/app/views/webui/package/show.html.haml
src/api/app/views/webui/package/update.js.haml
src/api/app/views/webui/project/_basic_info.html.haml
src/api/app/views/webui/project/show.html.haml
src/api/app/views/webui/project/update.js.haml
src/api/app/views/webui/request/beta_show.html.haml

The `watch` button floats right after the title of the context (package | project | request) and this adds noise to the focus (the title) and takes space where sometimes there are badges or other information. Better to reserve a dedicated place for this action button, and detach it a little bit from the center of the page. This PR move it always to the top-right, still in line with the title of the context

Watch button to the top-right

---

src/api/app/assets/stylesheets/webui/application.scss
src/api/app/assets/stylesheets/webui/colors.scss
src/api/app/assets/stylesheets/webui/navbar.scss
src/api/app/views/layouts/webui/_bottom_navigation.html.haml
src/api/app/views/layouts/webui/_bottom_navigation_collapse.html.haml
src/api/app/views/layouts/webui/_left_navigation_collapse_button.html.haml
src/api/app/views/layouts/webui/_top_navigation.html.haml
src/api/app/views/layouts/webui/webui.html.haml

Before these changes, the background colors of the navigation areas were inconsistent. Something that started to happen after the migration to Bootstrap 5.
Compare the Watchlist bar and the top bar, for example.
After these changes, I bring back the dark gray color for all of the navigation areas:
**What happened with the migration?**
We were using `.bg-dark` for the background color of the navigation areas. However, `bg-dark` was `#343a40` in the past ([see v4.6 docu](https://getbootstrap.com/docs/4.6/utilities/colors/#background-color)), but now it is `#212529`, a darker color ([see v5.0 docu](https://getbootstrap.com/docs/5.0/customize/color/#theme-colors)).
Checking the new Sass variables I see Bootstrap still has both colors set in variables.
The new `bg-dark` (`bg-dark = $gray-900 = …

Adjust colors after Bootstrap 5 migration

---

src/api/app/assets/stylesheets/webui/layout.scss
src/api/app/assets/stylesheets/webui/watchlist.scss

Instead of calculating new colors using lighten or darken functions, we better use specific colors already set in Sass variables. Getting the same result:

Use colors set on Sass variables

---

src/api/app/assets/stylesheets/webui/timeline.scss

Since https://github.com/openSUSE/open-build-service/pull/13876 the timeline icon alignment was partially broken. It is fixed now giving the `timeline-item-avatar` a fixed size and aligning the rest accordingly.

Fix: computing timeline icon and avatar alignment

---

src/api/app/assets/stylesheets/webui/comments.scss
src/api/app/assets/stylesheets/webui/timeline.scss
src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/bs_request_history_element_component.html.haml

Tweaking border and background color in order to not grab the focus on the timeline line itself, and give more contrast to the relevant information, like the timeline item avatar and the comment bubble text.

Conversation look and feel - light border and background

---

src/api/app/assets/stylesheets/webui/diff.scss
src/api/app/components/diff_component.html.haml
src/api/app/components/diff_component.rb
src/api/app/components/diff_list_component.html.haml
src/api/app/components/diff_list_component.rb
src/api/app/components/sourcediff_component.html.haml
src/api/app/components/sourcediff_component.rb
src/api/app/controllers/webui/comments_controller.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/models/bs_request_action.rb
src/api/app/models/comment.rb
src/api/app/views/webui/comment/_comment_field.html.haml
src/api/app/views/webui/comment/_comment_list.html.haml
src/api/app/views/webui/comment/_new.html.haml
src/api/app/views/webui/request/_inline_comment.html.haml
src/api/app/views/webui/request/inline_comment.js.erb
src/api/config/routes/webui_routes.rb
src/api/db/migrate/202302224114624_add_diff_ref_to_comments.rb
src/api/db/schema.rb

Depends on #13910 
Allows users to comment on submit request action diffs.
1. Create a submit request with a diff
2. Open changes tab
3. Hover over a line
4. Click a button that shows up
5. Write a comment and save it

Allow commenting on submit request diff lines

---

.rubocop.yml
src/api/.rubocop.yml

This is what we get when running Rubocop in development environment:
> The following RuboCop extension libraries are installed but not loaded in config:
>   * rubocop-capybara
> 
> You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
>   AllCops:
>     SuggestExtensions: false
Indeed, we use Capybara for specs in [dist/t/spec/*](https://github.com/openSUSE/open-build-service/blob/master/dist/t/spec/spec_helper.rb#L4) and in [src/api/specs/*](https://github.com/openSUSE/open-build-service/blob/c883341cade03e28d65d18faa244cf36e2c66360/src/api/spec/browser_helper.rb#L5) so it makes sense to load `rubocop-capybara` in both `.rubocop.yml` config files.

Load rubocop-capybara in config

---

src/api/app/models/comment.rb
src/api/spec/factories/comments.rb
src/api/spec/models/comment_spec.rb

The commentable type is `BsRequestAction` not `BsRequestActionSubmit`. Since it wasn't matching in the `create_event` method, no events got created for comments that have a relation to a request action.
This was introduced in https://github.com/openSUSE/open-build-service/pull/13912 for the comments on request diffs.

Correct commentable type in `create_event` callback on comment creation

---

src/api/app/controllers/search_controller.rb
src/api/config/routes/api_routes.rb

The routes '/search/package_id' and '/search/project_id' are deprecated but still using the same controller methods as the none deprecated ones. In order to track the usage through influxdb-rails and for later removal we can simply point those routes to separated controller methods.

Use separate controller method for deprecated search endpoint routes

---

src/api/app/controllers/source_controller.rb

Prevent cases like `force=0` from being understood as a truth value.
Related to #13302.

Make `force` parameter boolean, in `DELETE /source/<project>/<package>` API endpoint

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_createSpecFileTemplate.yaml

The endpoint is broken since a long time.
See https://github.com/openSUSE/open-build-service/issues/9707 Since there is no plan in fixing it and most likely completly removing it I marked it as deprecated in the new api documentation.

Document deprecated POST `/source/{project_name}/{package_name}?cmd=createSpecFileTemplate` endpoint

---

src/api/app/models/package.rb

This happens when removing a package from:
- from the `DELETE /source/<project>/<package>` API endpoint, if no comment parameter is passed, and
- from the web-ui
The output of `osc log -D project_1 package_1` was:
**Before:**
```
----------------------------------------------------------------------------
r9 | Admin | 2023-03-09 16:43:41 | d41d8cd98f00b204e9800998ecf8427e | None |
1
----------------------------------------------------------------------------
```
**After:**
```
----------------------------------------------------------------------------
r13 | Admin | 2023-03-09 16:49:22 | d41d8cd98f00b204e9800998ecf8427e | None |
package was deleted
----------------------------------------------------------------------------
```
Fixes #1610.

Fix bogus message '1' when deleting a package

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/components/schemas/revision_list.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_history.yaml

Note: the parameters `delete` and `meta` will be recognized as a truthy value not only with the `?delete=1` case, but with the following cases:
- `?delete`
- `?delete=0`
- `?meta`
- `?meta=0`
Access to the documented enpoint in the review-app through [this link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newsource_package_history/apidocs-new/index.html#/Sources%20-%20Packages/get_source__project_name___package_name___history).

Document `GET /source/{project_name}/{package_name}/_history` with OpenAPI

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_commit.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_commitfilelist.yaml

Access to the documented enpoint in the review-app through [this link](https://obs-reviewlab.opensuse.org/bmwiedemann-dod1byy0/apidocs-new/index.html#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_commitfilelist).

Document package commitfilelist command with OpenAPI

---

src/api/app/controllers/source_attribute_controller.rb
src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_attribute.yaml

We already documented the `GET /source/{project_name}/_attribute/{attribute_name}` endpoint. But `GET /source/{project_name}/_attribute` is also accepted but wasn't documented until now.
The endpoint documented in this PR is in charge of listing all the attributes of a project.
- Go to the Attributes tab on the project show page.
- Add some attributes
- Run `curl -u foo:bar -H 'Content-Type: application/xml; charset=utf-8' -X GET 'http://localhost:3000/source/home:Admin/_attribute`

Document GET `/source/{project_name}/_attribute` endpoint

---

src/api/app/controllers/source_attribute_controller.rb
src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_attribute.yaml

The endpoint documented in this PR is in charge of listing all the attributes of a package.
- Go to the Attributes tab on the package show page.
- Add some attributes
- Run `curl -u foo:bar -H 'Content-Type: application/xml; charset=utf-8' -X GET 'http://localhost:3000/source/home:Admin/hello_world/_attribute`

Document  GET `/source/{project_name}/{package_name}/_attribute` endpoint

---

docs/api/api/link.rng
docs/api/api/multibuild.rng
docs/api/api/package.rng
docs/api/api/project.rng

I was parsing the schemas and realized that some elements names are specified differently than others.
This patch fixes the inconsistency so I can parse the schemas consistently.

Fix use of element name in RelaxNG schemas

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_rebuild.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_wipe.yaml

The following two endpoints are broken and have working alternatives on the build side of the api, so we are deprecating them.

Deprecate broken endpoints source rebuild and wipe

---

src/api/app/models/comment.rb
src/api/app/models/event/comment_for_request.rb

Instrumenting the feature introduced in https://github.com/openSUSE/open-build-service/pull/13912
~DO NOT MERGE : We first need to merge https://github.com/openSUSE/open-build-service/pull/13967 in order to create the event on comment creation.~

Gather metrics about comment creation on request action diffs

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_collectbuildenv.yaml

Adds documentation for 2 out of 3 endpoints from my card. I found out that the third endpoint, `?cmd=wipe` isn't even properly defined, so there's no way to use it, not to mention documenting it.
`?cmd=rebuild` has broken repository fetching, so setting a repo value causes an error 500, it works just fine if you don't set repo value. It should be considered for deprecation as mentioned in https://github.com/openSUSE/open-build-service/blob/ba63db9bb6e0bdcbe44205725a6daa5544007912/src/api/app/controllers/source_controller.rb#L849
For reviewers:
https://obs-reviewlab.opensuse.org/hellcp-work-apidocs-sources-package-builds/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_collectbuildenv

Document POST `/source/{project_name}/{package_name}?cmd=collectbuildenv` endpoints

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/components/schemas/source/package_meta.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_meta.yaml

Access to the documented enpoints in the review-app through these links:
- [GET /source/{project_name}/{package_name}/_meta](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newsource_project_package_meta/apidocs-new/index.html#/Sources%20-%20Packages/get_source__project_name___package_name___meta)
- [PUT /source/{project_name}/{package_name}/_meta](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newsource_project_package_meta/apidocs-new/index.html#/Sources%20-%20Packages/put_source__project_name___package_name___meta)

Document `/source/{project_name}/{package_name}/_meta` endpoints with OpenAPI

---

src/api/app/models/project/key_info.rb
src/api/spec/models/project/key_info_spec.rb

We don't handle exceptions coming from the Backend class when attempting to fetch the keyinfo's for a project. This is causing issues since the keyinfos are displayed in the project views, which fail with a http code 500 when any error occurs.
Fixes #14007

Rescue from Backend::Error in Project::KeyInfo

---

src/api/public/apidocs-new/paths/source_project_name_package_name_attribute_attribute_name.yaml

Follow-up of https://github.com/openSUSE/open-build-service/pull/14004. Now add POST and DELETE endpoints to create, update and delete a given attribute of a package.
CURL:
```
curl -u foo:bar -H 'Content-Type: application/xml; charset=utf-8' -X POST 'http://localhost:3000/source/home:Admin/ad/_attribute/OBS:VeryImportantProject' --data @xml.xml
```
Where xml.xml contains:
```
<?xml version="1.0" encoding="UTF-8"?>
<attributes>
<attribute name="ScreenShots" namespace="OBS"></attribute>
</attributes>           
```

Document POST and DELETE  `/source/{project_name}/{package_name}/_attribute/{attribute_name}` endpoints

---

src/api/public/apidocs-new/paths/source_project_name_package_name_attribute.yaml

We can create or update an attribute without passing its attribute name as a parameter. It is enough to pass the information in the request body, with an XML like the following one:
```
<?xml version="1.0" encoding="UTF-8"?>
<attributes>
<attribute name="ScreenShots" namespace="OBS"></attribute>
</attributes>
```
[Link in review-app](https://obs-reviewlab.opensuse.org/saraycp-post_package_attribute_endpoint/apidocs-new/index.html#/Sources%20-%20Packages/post_source__project_name___package_name___attribute).
```
curl -u Admin:opensuse -H 'Content-Type: application/xml; charset=utf-8' -X POST 'http://localhost:3000/source/home:Admin/ad/_attribute' --data @xml.xml
```

Document POST `/source/{project_name}/{package_name}/_attribute` endpoint

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/components/schemas/directory.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name.yaml

Access to the documented enpoint in the review-app through [this link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newsource_package_get/apidocs-new/index.html#/Sources%20-%20Files/get_source__project_name___package_name_).

 Document `GET /source/{project_name}/{package_name}` with OpenAPI

---

src/api/app/components/diff_list_component.html.haml

Set the proper state of collapsed/not collapsed to show the proper arrow up/down in the Request#changes tab.

Set proper collapsed state on loading

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/components/schemas/services.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_getprojectservices.yaml

Access to the documented enpoint in the review-app through [this link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newsource_package_cmd_getprojectservices/apidocs-new/index.html#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_getprojectservices).

Document package command getprojectservices with OpenAPI

---

src/api/public/apidocs-new/paths/source_project_name_attribute.yaml
src/api/public/apidocs-new/paths/source_project_name_attribute_attribute_name.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_attribute.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_attribute_attribute_name.yaml

After reviewing other PRs I realized the `security` part was missing in the PRs I previously opened. So I add it to all of them now.

Add missing security section for attribute endpoints

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_binary_filename_attribute.yaml

Specifications for `GET/POST source/:project/:package/:binary/_attribute/`

OpenAPI specifications for GET/POST source files - without attribute parameter

---

src/backend/t/0160-BSSched-BuildJob-KiwiProduct.t
src/backend/t/0170-BSSched-BuildJob-Package.t
src/backend/t/0360-BSRepServer-BuildInfo-Package.t
src/backend/t/0370-BSRepServer-BuildInfo-KiwiImage.t
src/backend/t/0380-BSRepServer-BuildInfo-KiwiProduct.t
src/backend/t/lib/Test/OBS.pm

With this commit we split the testing of bdeps in the BuildInfo testing into single tests and print got/expected if the test fails. This makes debugging of issues easier in future.

[backend] improved testing bdep

---

src/backend/bs_worker

We also put the import architecture into the binfilter, so that we no longer overwrite binaries if noarch packages were imported.
Also, break up the main download loop into two nested loops to make the code more simple and easier to maintain.

[backend] kiwi product: improve filtering of imported binaries

---

src/api/app/components/diff_list_component.rb

I worked a bit more on this, and decided to forego the ruby logic entirely, only using activerecord to get an optimized query. This here results in
```sql
SELECT DISTINCT `comments`.`diff_ref` FROM `comments` WHERE `comments`.`commentable_id` = id AND `comments`.`commentable_type` = 'BsRequestAction' AND `comments`.`diff_ref` IS NOT NULL
```
which is faster than mapping, uniqing and compacting the records manually

Further optimize getting commented lines by avoiding ruby logic

---

src/api/app/controllers/trigger_workflow_controller.rb
src/api/app/services/trigger_controller_service/scm_extractor.rb
src/api/spec/controllers/trigger_workflow_controller_spec.rb

When we receive events we don't have mapped in the [Scm Payload Extractor map](https://github.com/openSUSE/open-build-service/blob/0134d09bb1a2ef85a37763ab760888aa396a9a44/src/api/app/services/trigger_controller_service/scm_extractor.rb#L3) (for example, a [new branch gets created](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#create)), we end up having no payload extractor (receiving Nil [here](https://github.com/openSUSE/open-build-service/blob/0134d09bb1a2ef85a37763ab760888aa396a9a44/src/api/app/services/trigger_controller_service/scm_extractor.rb#L28)). This nil bubbles up [to the controller](https://github.com/openSUSE/open-build-service/blob/0134d09bb1a2ef85a37763ab760888aa396a9a44/src/api/app/controllers/trigger_workflow_controller.rb#L13) and …

Record unsupported webhook event errors in the workflow

---

src/api/app/assets/javascripts/webui/application.js
src/api/app/assets/javascripts/webui/request_show_redesign/bs_request_actions.js
src/api/app/views/webui/request/_actions_details.html.haml

When moving through the request actions list, we want to keep seeing the same tab we were in.
i.e. we want to keep seeing the Changes tab to compare the changes of the previous, current and subsequent actions.
To do so, append the corresponding anchor the `href` of the links.
This PR also includes a little refactoring on the JS code that was included in the view, as we need to reuse part of the code now.
- Choose a [request with many actions](https://obs-reviewlab.opensuse.org/saraycp-tab-pane-changes-on-buttons/request/show/9).
- Play around with: changing tabs, clicking on Previous, Next, Dropdown...
- The last selected tab should keep selected and visible.

Make the Previous and Next buttons take the tabs into account

---

src/api/app/controllers/webui/request_controller.rb
src/api/config/brakeman.ignore

Also remove three ignored issues in brakeman.

Use sanitized strings for `where` clauses

---

src/api/app/components/diff_component.html.haml

Removing the partial improves performance significantly:
With partial, the rendering time is ~8.6 seconds
Without partial, the rendering time is ~2.8 seconds
This is the package we have used to test: https://build.opensuse.org/package/show/openSUSE:Factory/python-django-axes

Performance improvements for beta request show 

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/beta_show.html.haml

Before, in a multiaction submit request, a supported action was not shown if it was the only action supported and it was not the first action.
Now, in those conditions above mentioned, show the supported action.
For example, for a multiaction submit request where a Delete action is the only supported action, and also the last action (I was doing tests in my development environment, and the Delete action will be soonish supported), this is how it looked like before:
And this is after:

Show supported action types

---

src/api/config/routes/api_routes.rb
src/api/test/functional/interconnect_test.rb
src/api/test/functional/source_controller_test.rb

... from the frontend router.
It always fails with a 404 error and it is not defined in the backend. See: https://github.com/openSUSE/open-build-service/blob/f8f8c2331da85ea844f0ec81f8b883e3ae123491/src/backend/bs_srcserver#L7725

Remove POST /build/{project_name}/{repository_name} API route

---

src/api/config/routes/api_routes.rb

... from the frontend router
It always fails with a 404 error and it is not defined in the backend. See: https://github.com/openSUSE/open-build-service/blob/f8f8c2331da85ea844f0ec81f8b883e3ae123491/src/backend/bs_srcserver#L7726

Remove POST /build/{project_name}/{repository_name}/_buildconfig API route

---

src/api/app/controllers/webui/users/tokens_controller.rb

Fix https://github.com/openSUSE/open-build-service/issues/14081
Handle [this error](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/6402111584bf46052b8464d4) better.
During token creation, before executing the `:create` method, the code-path goes through [`set_package`](https://github.com/openSUSE/open-build-service/blob/master/src/api//app/controllers/webui/users/tokens_controller.rb#L112) and it may happen that the project or the package don't exist. If so, lines [108](https://github.com/openSUSE/open-build-service/blob/master/src/api//app/controllers/webui/users/tokens_controller.rb#L108) or [116](https://github.com/openSUSE/open-build-service/blob/master/src/api//app/controllers/webui/users/tokens_controller.rb#L116) or …

Redirect to proper path instead of rendering partial

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/spec/features/webui/requests/submissions_spec.rb
src/api/spec/features/webui/requests_spec.rb

$subject
Standardize the staging information for the scenarios when a request is open against a project that has a staging  worflow:
- Case A: the request is not assigned to any staging project (this is what it is called a staged request `for_group`). [review-app link of Case A](https://obs-reviewlab.opensuse.org/ncounter-fix-spec-tests/request/show/2)
- Case B: the request is assigned to a staging project in a staging workflow process  (this is what it is called a request `for_project`). [review-app link of Case B](https://obs-reviewlab.opensuse.org/ncounter-fix-spec-tests/request/show/4)
**for group**
**for project**
**for group** - case A
**for project** - case B

Clarify request staging information

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/_action_text.html.haml
src/api/lib/tasks/dev/requests.rake
src/api/spec/features/webui/requests/delete_actions_spec.rb

- Link to a request with multiple actions, being the last two of them delete actions, in the review app, [here](https://obs-reviewlab.opensuse.org/eduardoj-featuredisplay_delete_request_actions/request/show/9).
- Link to a request with two unsupported actions and one delete action in the review app, [here](https://obs-reviewlab.opensuse.org/eduardoj-featuredisplay_delete_request_actions/request/show/11).

Show Delete request actions in the action dropdown

---

src/api/app/assets/javascripts/webui/comment.js
src/api/app/assets/stylesheets/webui/diff.scss
src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/diff_component.html.haml
src/api/app/controllers/webui/comments_controller.rb
src/api/app/views/webui/comment/_comment_list.html.haml
src/api/app/views/webui/comment/_new.html.haml
src/api/app/views/webui/request/_inline_comment.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/inline_comment.js.erb

This uses comment components for rendering comments in the changes tab, in order to avoid issues when rendering comments in the timeline and changes tab at the same time. It migrates the comment components to using delete modal component too.

Use the comment components for rendering comments

---

src/api/app/components/bs_request_activity_timeline_component.rb
src/api/spec/cassettes/Bootstrap_Requests_Submissions/submit_package/when_under_the_beta_program/a_request_that_has_a_broken_comment/displays_the_comment_in_the_timeline.yml
src/api/spec/features/webui/requests/submissions_spec.rb

Before if the diff_ref didn't match the regex, the page would not render, now the regex is tried first so we know if the string we get in diff_ref matches.
https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/642bf86284bf4604fe227a8e

Make sure the regex finds matches for diff_ref

---

src/api/app/views/webui/request/_action_text.html.haml

Fixes #14109.
We checked all the TimeComponent calls to make sure they always receive a Time object. We only found this ocurrence to be modified.

Make sure TimeComponent receives a Time object

---

src/api/public/apidocs-new/swagger-initializer.js

We don't potentially need it, and it performs a requests outside the domain where the documentation is installed.
Before:
After:
The build-test.o.o instance was monkey patched. Access the new API documentation there to see it working.
This cannot be checked in the development enviroment.

Disable swagger.io's online validator link

---

src/api/app/lib/routes_helper/routes_constraints.rb

We can replace the `*` by the `+`. We don't need to take in account the case of not having a digit.
This is a follow-up to 4383013d3e.

Improve line parameter route constraint

---

src/api/app/components/build_result_for_architecture_component.html.haml

[Bootstrap 4.6](https://getbootstrap.com/docs/4.6/components/popovers/#options) accepted one number for the popover's offset.
[Bootstrap 5+](https://getbootstrap.com/docs/5.2/components/popovers/#options) requires two values in string or array format.
- Add at least one repository to the project involved in a request.
- Enable beta.
- Go to the request tab in the beta request show page.
- See the popover when you hover one of the results.
You should see something like this:

Correct popover offset values

---

src/api/test/functional/webui/spider_test.rb

Prevent from throwing this warning in spider tests:
```
DEPRECATED: global use of must_be from test/functional/webui/spider_test.rb:167. Use _(obj).must_be instead. This will fail in Minitest 6.
```
Take a look at the spider tests log of this pull request. The string with the deprecation warning does not appear.

Replace Expectations with Assertions in spider tests

---

src/api/app/components/bs_request_state_badge_component.rb
src/api/app/components/watched_items_list_component.html.haml

Feature to address https://github.com/openSUSE/open-build-service/issues/13187
This PR helps to find out what is the current state of a request in the watchlist without going into details of each, and take decisions afterwards (like deleting or keeping in the watchlist, going to the request page details, etc).
- Go to this [request](https://obs-reviewlab.opensuse.org/ncounter-request-status-watch-list/request/show/4) in the `review-app`
- Add it to the watchlist by hitting the top-right button [Watch]
- Open the watchlist from the top-right navigation bar
- Check out the request in the watchlist with the badge color and text

BsRequest state as a hint in the watchlist

---

src/api/app/assets/javascripts/webui/application.js
src/api/app/assets/javascripts/webui/collapsible_text.js
src/api/app/assets/javascripts/webui/nav_tabs.js
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/shared/_collapsible_text.html.haml
src/api/app/views/webui/user/_involvement.html.haml

In the beta version of a `BsRequest` page the `collapsible-text` is buggy: the culprit is the fact that content is visible only after tabs are loaded and the one selected is rendered. The logic of the `collapsible-text` rely on the `height` of the element where the possible long text is contained so, if the tab is not yet rendered the `height` is computed to `0` and this makes the logic to fail adding the `show-more`/`show-less` button.
This PR fixes first the bug by making sure the `setCollapsible();` is called after the tab content is visible.
Later on the PR refactors the whole `setCollapsible()` logic because it still has corner cases (such as the `click` event that is added more than once to all the elements every time the `setCollapsible()` is called, for instance).

BugFix: collapsible text for request beta

---

src/api/app/assets/stylesheets/webui/colors.scss
src/api/app/assets/stylesheets/webui/requests.scss
src/api/app/components/bs_request_state_badge_component.rb
src/api/app/helpers/webui/notification_helper.rb
src/api/app/views/webui/request/_show_overview.html.haml
src/api/app/views/webui/request/beta_show.html.haml

Follow-up of https://github.com/openSUSE/open-build-service/pull/14118 
Make use of the badge component everywhere is possible
Add a different `code-pull-request` icon next to the `bs_request` status text in the badge

Improve request state badge component

---

.github/workflows/diffend_gem_binary_diff.yml

Github does not show the diff for changes applied to `.gem` files which we receive throug Depfu PR's. To make it easier to review the changes applied to the gems, this Github Action creates links to the tool diffend.io which provides the diff between the two gem versions and creates a comment with those on the corresponding PR.
Current limitations:
- Diffend.io only provides diffs from older to newer gem versions, so it does not work when we downgrade gems right now.
Example output from the gh action:
Example link to diff:
https://my.diffend.io/gems/loofah/2.19.1/2.20.0

Add github action to add comments to binary diff for gem file changes

---

.github/workflows/diffend_gem_binary_diff.yml

In order to allow the creation of the comment with the links to the binary diffs of the modified ruby gems on a PR, we need to grant the github action write permission on pull requests.

Grant write permission for PR's to gem binary diff link github action

---

.github/workflows/diffend_gem_binary_diff.yml

Set the toplevel permission of the used github token to a minimum for the github action workflow and only grant necessary permissions on a job level to increase security.
Reported by https://github.com/openSUSE/open-build-service/security/code-scanning/29

Set minimum github token permission for gh action workflow

---

src/api/app/models/issue_tracker.rb
src/api/config/initializers/filter_parameter_logging.rb
src/api/db/migrate/20230413080503_add_api_key_to_issue_tracker.rb

This is needed because SUSE Bugzilla updated to version 5 without HTTP Basic Authentication. We make sure to authenticate with an api key in addition to the password whenever it's available.

Authenticate bugzilla with api_key

---

.circleci/conditional_config.yml

Improve the legibility of the `run` sections of the CircleCI configuration.

Use the `working_directory` key instead of `cd` commands

---

.github/workflows/comment_diffend_io_links_to_pr.yml
.github/workflows/create_diffend_io_links.yml

In order to allow the creation of comments on PR's that are
coming from forks, we would need to use the `:pull_request_target`
event over the `:pull_request` event. Since the `:pull_request_target`
event comes with more permissions on the target repo, its not recommended to
checkout the code coming from an untrusted fork.
Therefore the gh action workflow is now split into two separate
workflows.
One workflow keeps working on the `:pull_request` event and checksout
the code to perform the diff operation in order to receive gem
name, version etc. Afterwards the informations are saved as artifacts.
The second workflow listens for the `workflow_run` event and gets
triggered after the first one finished successfully, then downloads
the artifacts and finally creates the comment (the …

Split github action workflows into two separate workflows

---

.circleci/conditional_config.yml

RuboCop linter tests take longer than other linters.
Move them to the last position of the sequence of linters. This way, linters fail sooner because the linters that take less time are run first, and therefore, CI steps fail sooner on average when we encounter a linter offense and we use less test cycles.

Rearrange CircleCI linters steps

---

.github/workflows/comment_diffend_io_links_to_pr.yml
.github/workflows/create_diffend_io_links.yml

The PR number is not available in the payload of the `workflow_run` event, when the PR is coming from a fork. To workaround that problem I write the PR number to the artifacts in the first workflow that gets triggered from the `pull_request` event (where the pr number is available) and fetch it in the following one from there.

Hand over PR number between gh action workflows through artifacts

---

src/api/test/functional/maintenance_test.rb

Our minitest suite errors with this message:
```
MaintenanceTests
test_OBS_BranchTarget                                           PASS (1.04s)
test_branch_from_service_pack_WIP                               PASS (2.00s)
test_branch_package                                             PASS (3.07s)
test_branch_package_with_local_link                             PASS (2.21s)
test_copy_from_origin_with_modification_has_write_permission_check PASS (0.17s)
test_copy_project_for_release                                   PASS (3.63s)
test_copy_project_for_release_using_makeoriginolder             PASS (1.69s)
test_copy_project_for_release_with_history                      PASS (1.68s)
test_copy_project_with_history_and_binaries                     FAIL (1.59s)
Expected "1681474478" to not be equal …
```

Fix flickering test in MaintenanceTests minitests

---

src/api/app/components/notification_component.html.haml
src/api/app/components/notification_excerpt_component.rb
src/api/spec/components/notification_excerpt_component_spec.rb
src/api/spec/components/previews/notification_excerpt_component_preview.rb

So the object is passed to the component and not retrieved inside. That makes it possible to not persist any object to use its preview.

Simplify NotificationExcerptComponent

---

src/api/.rubocop.yml
src/api/app/controllers/application_controller.rb
src/api/app/controllers/build/file_controller.rb
src/api/app/controllers/concerns/backend_proxy.rb
src/api/app/controllers/concerns/rescue_authorization_handler.rb
src/api/app/controllers/concerns/webui/rescue_handler.rb
src/api/app/controllers/person_controller.rb
src/api/app/controllers/webui/package_controller.rb
src/api/app/controllers/webui/projects/meta_controller.rb
src/api/app/controllers/webui/webui_controller.rb

The cop got disabled in the past due to some bug. Meanwhile its functional, so we can enable it and remove the offenses.

Enable `Rails/HttpStatus` cop in rubocop main conf and remove offenses

---

src/api/.rubocop.yml
src/api/test/functional/maintenance_test.rb
src/api/test/test_consistency_helper.rb

* Use `require_relative` over concatenating the path to the `test_helper` manually
* Adapt to use string interpolation for everything else

Fix `Style/StringConcatenation` rubocop offense in `test_consistency_helper` and `maintenance_test.rb`

---

src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_getprojectservices.yaml

A very long time ago the `project spaces` wording was added [here](https://github.com/openSUSE/open-build-service/commit/4f931180b9af49ff2208bd50cda3fe4e28ee9e2e#diff-26ef3c22ebd850f7d723186b4a6c94551409c2a7e25742f7a893a6bbd8695797R707), but currently it lost its meaning, and that's why this PR drops the `spaces` slice. Referring to the `project` is fine and clear.

Drop stale doc wording

---

docs/api/api/api.txt
src/api/public/apidocs-new/OBS-v2.10.50.yaml

This PR adds:
- A link in the [legacy API documentation](https://build.opensuse.org/apidocs/index) pointing to the [new one](https://build.opensuse.org/apidocs-new/index.html)
- A link in the [new API documentation](https://build.opensuse.org/apidocs-new/index.html) pointing to the [old one](https://build.opensuse.org/apidocs/index)

Reference legacy and new documentation to each other

---

docs/api/api/api.txt
docs/api/restility/lib/rest_htmlprinter.rb

**Before:**
**After:**
Related to #14196.
In development environment:
- checkout this branch
- enter the `frontend`  container: `docker-compose run --rm --service-ports frontend bash`
- `cd /obs`
- `make -C docs/api/api apidocs`
- browse the file locally (not from the rails puma server) `$LOCAL_REPOSITORY_DIRECTORY/docs/api/html/index.html`

Use a link in legacy API docs to point to the new API documentation

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/components/schemas/source/sourceinfo.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name.yaml
src/api/public/apidocs-new/paths/source_project_name_package_name_view_info.yaml

Take a look to the added endpoint in the review-app [here](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newsource_package_view_info/apidocs-new/index.html#/Sources%20-%20Packages/get_source__project_name___package_name__view_info).

Document GET source package view=info endpoint with OpenAPI

---

src/api/config/routes/api_routes.rb

The Rails controller errors with empty package not found. There isn't any defined in the backend, in `bs_srvserver`.

Remove `POST /build/:project/:repository/:arch` API endpoint

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/components/responses/unknown_project_or_file.yaml
src/api/public/apidocs-new/paths/source_project_name_pattern_file_name.yaml

Access to the documented endpoint in the review-app through
- GET [this link](https://obs-reviewlab.opensuse.org/ncounter-deprecate-pattern-file-api-doc/apidocs-new/index.html#/Sources%20-%20Projects/get_source__project_name___pattern__file_name_)
- PUT [this link](https://obs-reviewlab.opensuse.org/ncounter-deprecate-pattern-file-api-doc/apidocs-new/index.html#/Sources%20-%20Projects/put_source__project_name___pattern__file_name_)
- DELETE [this link](https://obs-reviewlab.opensuse.org/ncounter-deprecate-pattern-file-api-doc/apidocs-new/index.html#/Sources%20-%20Projects/delete_source__project_name___pattern__file_name_)

Document GET PUT DELETE _pattern files as DEPRECATED

---

src/api/config/database.yml.example

Our single host installations lack this and run into trouble with the delayed jobs on database update.

[dist] add reconnect: true to database.yaml.template

---

src/api/.database_consistency.todo.yml
src/api/app/models/notified_project.rb
src/api/db/migrate/20230414085150_add_notified_projects_project_id_index.rb
src/api/db/migrate/20230414151119_add_projects_id_notified_projects_project_id_fk.rb
src/api/db/schema.rb
src/api/spec/db/data/backfill_notified_projects_spec.rb

The second slowest query in the slow log report that you can find in the attached [Trello card](https://trello.com/c/94X2HYZT/2215-not-indexed-queries) examines a lot of rows.
```
SELECT `notified_projects`.* FROM `notified_projects` WHERE `notified_projects`.`project_id` = 474649\G
```
Maybe we are not hitting any index for that query:
```
MariaDB [api_development]> explain SELECT `notified_projects`.* FROM `notified_projects` WHERE `notified_projects`.`project_id` = 24;
+------+-------------+-------------------+------+---------------+------+---------+------+------+-------------+
| id   | select_type | table             | type | possible_keys | key  | key_len | ref  | rows | Extra       |
+------+-------------+-------------------+------+---------------+------+---------+------+------+----- …
```

Add missing index on notified_project's project_id

---

src/api/.database_consistency.todo.yml
src/api/app/models/notified_project.rb
src/api/db/migrate/20230414151119_add_projects_id_notified_projects_project_id_fk.rb
src/api/db/schema.rb

There are some rows on production's notified_projects that reference missing projects in projects table. We need to figure out what to do with those records and how to prevent that from happening again before enforcing this foreign key index.
Fixes #14163

Remove creation of the foreign key on notified_projects project_id

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/components/schemas/staging/staging_project.yaml
src/api/public/apidocs-new/components/schemas/staging/staging_projects.yaml
src/api/public/apidocs-new/components/schemas/staging/workflow_staging_projects.yaml
src/api/public/apidocs-new/paths/staging_project_name_staging_projects.yaml

Endpoints:
- GET `/staging/{project_name}/staging_projects`
- POST `/staging/{project_name}/staging_projects`
Controller: `Staging::StagingProjectsController < Staging::StagingController`
Use Rails task `rails dev:staging:data` to set a staging workflow with two staging projects.

Document GET and POST endpoints for staging projects

---

src/backend/BSContar.pm
src/backend/bs_publish

This makes the publisher collects all .sha256 files into a single signed "SHA256SUMS" file.
Fixes issue #10407

[backend] bs_publish: implement "checksumsfile" repotype

---

dist/obs-server.spec

In order to speed up the loading time of the OpenAPI documentation, we replace the development version of the yaml files with one big yaml file by resolving all references, during the build process.
DO NOT MERGE: This PR depends on https://github.com/openSUSE/open-build-service/pull/14240 to be merged and we have to submit the two rubygems first to the OBS:Server:Unstable project in order to run the script during the build.

Resolve and replace swagger yaml during build process

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml
src/api/public/apidocs-new/components/schemas/staging/backlog.yaml
src/api/public/apidocs-new/components/schemas/staging/request.yaml
src/api/public/apidocs-new/components/schemas/staging/requests_to_stage.yaml
src/api/public/apidocs-new/components/schemas/staging/staged_requests.yaml
src/api/public/apidocs-new/paths/staging_project_name_staging_projects_staging_project_name_staged_requests.yaml

**Reviewing Tips:**
- Open requests towards the original project (which has a staging workflow). You'll see those requests in the backlog.
- Use this endpoint to assign any of those requests to one of the staging projects.
- Play around with listing all the staged requests and "unstage" some of them too.
Controller: Staging::StagedRequestsController < Staging::StagingController

Document staged requests endpoints

---

src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_servicediff.yaml

Make clear that this response returns a `xml/plain` Content-type header.
Also, add example for an empty `view` parameter. This was forgotten to be included in the previous documentation iteration.

Move xml response example to a xml section in new API documentation

---

src/backend/BSSched/RPC.pm
src/backend/bs_sched

This brings rpcs in sync with the watcher handling.

[backend] split xrpc_isfinished from xrpc_resume

---

src/backend/bs_regpush

The size needs to stay numeric so that the generated json is accepted by the registry.

[backend] bs_regpush: do not stringify the size in config_ent

---

src/api/app/controllers/webui/request_controller.rb

Actions related to the beta show should not be accessible for not logged-in users. This PR redirects not logged in users to ols show view.
Fixes #14273

Redirect to old show view if user is not in beta

---

src/api/public/apidocs-new/swagger-initializer.js

We only have one specification to show, so we don't need a specification explorer form.
**Before:**
**After:**
Browse this [link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newdont_show_explorer/apidocs-new/index.html) of the review app.

Don't show the specification file explorer in the Swager-UI interface

---

src/api/app/controllers/webui/request_controller.rb

Make sure `target_project` exists before retrieving its maintainers.
Sometimes `Project.deleted?(@bs_request.target_project_name)` returned false, it means the project is not deleted. But right after the check, when trying to access `target_project.maintainers`,  `target_project` happens to be nil.
The errors tracked in Errbit match exactly the same date and time when a Deletion request was accepted (so when the project was deleted).
My conclusion is that `Project.deleted?` needs a while to reflect reality as it relies on some data in the backend (`_history` file with `deleted: 1`) that probably takes longer to be set. So there is a mismatch for a moment.
Anyway, whatever the reason is, I've refactored the code to not rely on `Project.deleted?` but to always check for the presence of …

Retrieve maintainers if target_project is present

---

src/api/spec/factories/project.rb

Allow to search for maintained packages (`osc maintained`) and create maintenance branches (`osc mbranch`) in the development environment.
**Before:**
```bash
> osc -A http://localhost:3000 maintained apache2
BuildService API error: no packages found by search criteria
>
```
**After:**
```bash
> osc -A http://localhost:3000 maintained apache2
openSUSE:Leap:15.0:Update/apache2
>
```
**References:**
- https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.maintenance_setup.html#id-1.5.10.12.10.3
- https://en.opensuse.org/openSUSE:Package_maintenance#Find_the_package_that_you_need_to_work_with

Fix `update_project` factory

---

src/api/app/mixins/has_relationships.rb
src/api/spec/cassettes/Project/_maintainers/returns_all_the_users_but_user_2_only_once.yml
src/api/spec/cassettes/Project/_maintainers/when_one_of_the_users_is_deleted/still_returns_the_deleted_user.yml
src/api/spec/cassettes/Project/_maintainers/when_the_group_is_deleted/returns_the_deleted_user_but_not_the_deleted_group_s_user.yml
src/api/spec/models/project_spec.rb

Until now, retrieving projects' maintainers that were deleted made the code crash.
Deleted users are displayed everywhere in the application (groups' members, projects' users etc). They are visible but on a special state, "deleted". So there is no reason to stop displaying them in the list of maintainers.
Fixes: #14302
- Create two users
- Make them maintainers of a project
- Delete one of them from Configuration > Manage Users
- Check that `project.maintainers` returns the same users, including the deleted one, without crashing.
TODO:

Allow retrieving deleted maintainers

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/requests.rake

It doesn't make sense to create a request with two `maintenance_incident` actions and also a `delete` action.

Split creation of a request with a delete action in its own rake task

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/_request_tabs.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/build_results.html.haml
src/api/app/views/webui/request/changes.html.haml
src/api/app/views/webui/request/mentioned_issues.html.haml
src/api/app/views/webui/request/rpm_lint.html.haml

`active` could be anything, especially for multiactions request could be the active action, but in this case it was for `active_tab`, therefore the renaming of the variable.

Clarify variable meaning

---

src/api/app/components/bs_request_activity_timeline_component.html.haml
src/api/app/components/bs_request_activity_timeline_component.rb
src/api/app/components/bs_request_history_element_component.html.haml
src/api/app/components/bs_request_history_element_component.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/spec/components/bs_request_history_element_component_spec.rb

Make it more obvious when a user accepted a request, despite
open/pending reviews by extending the text shown for the
`HistoryElement::RequestAccepted` in the conversation timeline
mentioning that the user dismissed pending reviews.
How to test:
1. Create a submit request
2. Add a review for another user/group
3. Accept the request despite the pending review
4. See the note about the dismissed reviews in the conversations timeline

Mention dismissed reviews in request conversation timeline

---

src/api/app/assets/javascripts/webui/request.js
src/api/app/components/sourcediff_component.html.haml

Since the conversion from tabs to separate pages, in the request page the `#changes-tab` id got dropped. Therefore the `loadChanges` is no longer able to fetch the parameters (`request number` and `action id`) properly.
The bug fix passes those parameters on calling the function instead of delegating to the function the search and read of those parameters relying on some other element.

Bug fix: make sure loadChanges receives parameters to build url properly

---

src/api/app/components/sourcediff_component.html.haml
src/api/app/components/sourcediff_component.rb
src/api/app/components/sourcediff_tab_component.html.haml
src/api/app/components/sourcediff_tab_component.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/changes.html.haml
src/api/app/views/webui/request/request_action.js.erb
src/api/app/views/webui/request/request_action_changes.js.erb
src/api/spec/components/previews/sourcediff_component_preview.rb
src/api/spec/components/previews/sourcediff_tab_component_preview.rb
src/api/spec/components/sourcediff_component_spec.rb
src/api/spec/components/sourcediff_tab_component_spec.rb

The logic of that piece of code is to check if the `diff` changes are already computed and cached, or it triggers the async job to fetch them.
The refactoring makes all the access to the request page (no matter which tab) to hit that method so the `diff` will be fetched in advance. The refactoring also renames the `@refresh` variable into some more explicit flag with the name of `@diff_not_cached`, which is in line with the id of the hash retrieved from the backend job.

Refactor request refresh logic

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/requests.rake
src/api/lib/tasks/dev/test_data/maintenance.rake

Move maintenance related development Rails tasks to its own task namespace: `dev:maintenance:...`.
Make it easier to add tasks related to maintenance, such as creating different types of requests related to maintenance for the development environtment.
Now we can call:
- `rake dev:test_data:create`
as we did before, and it will add a basic maintenance environment.

Refactor maintenance related dev tasks

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml

Specifics on other authentication schemes and policies on abusing of rate limiting should not be detailed in the general API documentation. This information is dependant on each instance.
Instead, provide a link to the site main page or refer to the OBS admin.

Generalize rate-limiting and other authentication schemes

---

src/api/app/components/accordion_reviews_component.rb
src/api/app/components/request_decision_component.rb
src/api/app/views/webui/request/beta_show.html.haml

We already have a pundit policy for this, no need to add this logic again to the view component.
Extracted out of https://github.com/openSUSE/open-build-service/pull/14318 to ease review

Use pundit policy for `handle_request?` in request beta view components

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/test_data/maintenance.rb
src/api/spec/factories/maintained_project.rb

Adapt methods to create maintenance setup to set projects' names that better reflect reality and use terminology we are more familiar with.
Run `bundle exec rake dev:test_data:create` to make sure it doesn't crash.
Then check the data is there: 
- openSUSE:Leap:15.4
- openSUSE:Maintenance
- openSUSE:Leap:15.4:Update
- home:Iggy:branches:openSUSE:Leap:15.4:Update
- Outgoing request from home:Iggy:branches:openSUSE:Leap:15.4:Update

Fine tune methods to create maintenance setup

---

src/api/Rakefile
src/api/lib/tasks/dev/lint.rake

Following #14182, this PR makes Rubocop use fuubar progress formatter also.
It would be nice to make `haml-lint` to use fuubar as well, but I found no way of doing it...

Use fuubar for rubocop progress report

---

src/api/Rakefile
src/api/lib/tasks/dev/lint.rake

Reverts openSUSE/open-build-service#14334
On CircleCI there are some scrolling issues that makes harder to get to the point of the issues. We'll fix the issues with fuubar later

Revert "Use fuubar for rubocop progress report"

---

src/api/app/components/diff_component.html.haml
src/api/app/components/diff_component.rb
src/api/app/components/diff_list_component.html.haml
src/api/app/components/diff_list_component.rb
src/api/app/components/sourcediff_component.html.haml
src/api/app/components/sourcediff_component.rb
src/api/app/models/package.rb
src/api/spec/cassettes/ImageTemplates/branching/branch_Kiwi_image_template.yml
src/api/spec/cassettes/ImageTemplates/branching/branch_image_template.yml
src/api/spec/cassettes/Package/_file_exists_/_multibuild_file_should_exist/1_4_1_1.yml
src/api/spec/cassettes/Package/_file_exists_/with_more_than_one_file/returns_false_if_the_file_does_not_exist.yml
src/api/spec/cassettes/Package/_file_exists_/with_more_than_one_file/returns_true_if_the_file_exist.yml
src/api/spec/cassettes/Package/_file_exists_/with_one_file/returns_false_if_the_file_does_not_exist.yml
src/api/spec/cassettes/Package/_file_exists_/with_one_file/returns_true_if_the_file_exist.yml
src/api/spec/cassettes/Package/_has_icon_/returns_false_if_the_icon_does_not_exist.yml
src/api/spec/cassettes/Package/_has_icon_/returns_true_if_the_icon_exist.yml
src/api/spec/cassettes/Package/_ignored_requests/when_the_package_has_an_ignored_requests_file/parses_the_content_as_YAML_and_returns_a_hash.yml
src/api/spec/cassettes/SourcediffComponent/with_a_request_with_a_submit_action/renders_the_diff.yml

Displays links to the source and target files inline with the git range information. I wanted to include anchors for the lines that the range is referring to, but as far as I can tell codemirror doesn't have a simple way of having line ids in html.
To verify this feature:
- Create a request with a diff
- Open changes tab in the beta view
- Click the new icons in the range lines

Display links to source and target files in diffs

---

src/api/app/models/owner_search/missing.rb

caused by maintenance_release projects where the package name got not
shortened

[api] fix duplicates in missing owner results

---

.circleci/conditional_config.yml

Default is to do this when the previous jobs succeeded. Which kind of is the least interesting case to download large logs...

Always compress CI artifacts

---

src/api/app/models/project.rb

raise a proper error (not just crash with 500) when an update project
got configured, but does not exist.
Fixes #10116.

[api] raise a proper error on missconfigured update project

---

src/api/app/components/bs_request_comment_component.html.haml
src/api/app/policies/comment_policy.rb
src/api/app/views/webui/comment/_reply.html.haml
src/api/spec/policies/comment_policy_spec.rb

To verify:
- Create a comment
- Reply to the comment
- Delete the root comment
- You will no longer be able to reply to or delete the root comment even as admin

Disallow deleting and replying to deleted comments

---

src/api/lib/tasks/dev/test_data/maintenance.rb
src/api/spec/factories/project.rb
src/api/spec/features/webui/maintenance_workflow_spec.rb

From the `test_data` rake task we are calling `create_maintenance_setup` which intends to set all the data needed to reproduce the maintenance workflow.
So far it sets three maintenance incident requests and all the elements needed before the request.
- maintained projects
- update project
- maintenance project
- packages
- incident request with one action not accepted
- incident request with multiple actions not accepted
- incident request with multiple actions accepted
- Run `bundle exec rake dev:test_data:create` locally
- You should see three incident requests:
- Number 11: one action,  no patchinfo, not accepted
- Number 12: many actions, with patchinfo, not accepted
- Number 13: many actions, with patchinfo, accepted

Set up maintenance incident request in development environment

---

src/api/lib/tasks/dev/requests.rake

Even if `Faker::Lorem.word` returns the same word twice, the package name won't be repeated by appending the timestamp.

Avoid repeated package's name on rake task

---

src/api/spec/factories/project.rb

Calls to factories `project_with_package` and `project_with_packages` don't include, and don't need the `create_patchinfo` parameter.

Remove `create_patchinfo` parameter in factories

---

src/api/lib/tasks/dev/requests.rake
src/api/lib/tasks/dev/test_data/maintenance.rb

The request doesn't come from a user's branched package but from a package which is "officially" developed on a specific project.
Run `bundle exec rake dev:test_data:create` locally. You should see an incident request with number 14: many actions, with patchinfo, accepted

Cover another case of incident request

---

src/api/app/assets/stylesheets/webui/requests.scss
src/api/app/components/sourcediff_component.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/helpers/webui/request_helper.rb
src/api/app/models/bs_request.rb
src/api/app/views/webui/request/_action_text.html.haml
src/api/app/views/webui/request/_actions_details.html.haml
src/api/app/views/webui/request/_request_header.html.haml
src/api/app/views/webui/request/_request_tabs.html.haml

Adapt the beta request show view to display maintenance incident requests.
**Before:**
**Now:**
- At the top of the page, it is highlighted that the request is a Maintenance Incident Request.
- The names of the projects and packages are not trimmed.
- Display a link to the target release, if present.
- The dropdown's action text only displays the relevant information
Not accepted request. Target is openSUSE:Maintenance.
Accepted request. Target is openSUSE:Maintenance:0.
Run `bundle exec rake dev:test_data:create` to set up all the data you need. Requests with numbers between 11 and 14 are incident ones.
NOTE: specs will be covered in another PR.

Support `maintenance_incident` request actions in beta

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/helpers/webui/request_helper.rb
src/api/app/models/bs_request.rb
src/api/app/views/webui/request/_action_text.html.haml
src/api/app/views/webui/request/_request_header.html.haml
src/api/app/views/webui/request/_request_tabs.html.haml

Adapt the beta request show view to display maintenance release requests.
**Before:**
**Now:**
- At the top of the page, it is highlighted that the request is a Maintenance Release Request.
- The names of the projects and packages are not trimmed.
- The dropdown's action text only displays the relevant information
Run `bundle exec rake dev:test_data:create` to set up all the data you need. Request with number 15 is a release one.
NOTE: specs will be covered in another PR.

Support maintenance release actions in beta

---

src/api/app/components/sourcediff_component.rb

This crashes when for example the source project of a request gets deleted, after the request got accepted.
Fixes #14392
Similar to https://github.com/openSUSE/open-build-service/pull/14380

Handle non-existent project in sourcediff

---

src/api/app/models/token/workflow.rb
src/api/app/models/workflow.rb
src/api/app/validators/workflow_filters_validator.rb
src/api/spec/models/workflow_spec.rb
src/api/spec/validators/workflow_filters_validator_spec.rb

Right now we have an intermix we the validations for a SCM
workflow. When we intialize the `Workflow` class we run
the `WorkflowFiltersValidator`. This validator makes sure that
all filters in the `Workflow` are valid (so basically that every
filter definition in the `workflow.yml` file is correct).
The problem right now is, we cannot check in this validator that
the current webhook event is supported by the filters (in this
case the branches filter for the `tag_push`) since the class is
always intialized no matter if it is meant for the currently incoming
webhook.
If a certain webhook event is meant for the workflow is checked
when we execute the workflow (`Workflow.call`). Here we check
if the event matches the event filter etc.
Therefore we also have to check here if the current event …

Validate supported filter for event on workflow execution

---

src/api/spec/controllers/webui/package_controller_spec.rb

https://app.circleci.com/pipelines/github/openSUSE/open-build-service/12481/workflows/8f0de2b1-88b2-4bc2-905a-e2ddf0c7f9b4/jobs/132665
failed with
1) Webui::PackageController build logs GET #package_live_build_log with a multibuild package is expected to eq 3600
Failure/Error: it { expect(assigns(:buildtime)).to eq(1.hour.to_i) }
expected: 3600
got: 3601
(compared using ==)

Make package_controller_spec test more reliable

---

src/api/public/apidocs-new/paths/build_project_name_repository_name_architecture_name_builddepinfo.yaml

Even if this endpoint is somehow implemented in the backend, it is not tested nor used by `osc`.
Access the [link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newbuild_builddepinfo/apidocs-new/index.html#/Build/post_build__project_name___repository_name___architecture_name___builddepinfo) to the direct deprecated endpoint in the review app.

Deprecate `/build/.../_builddepinfo` POST API endpoint

---

src/api/config/routes/api_routes.rb
src/api/config/routes/webui_routes.rb
src/api/test/functional/webui/spider_test.rb

This is the first step on rolling out the new API documentation.
In this PR:
- create `apidocs-old` routes
- create redirections from `/apidocs` to `/apidocs-old`
1. On a running development environment set up the apidocs:
- `docker-compose exec frontend bash`
- `cd /obs/`
-  `make -C docs/api/api apidocs`
- `cd /obs/src/`
- `ln -s ../doc`
1. Access the new path: http://localhost:3000/apidocs-old/
1. Access the old path. It should redirect to the new path: http://localhost:3000/apidocs/

Start rolling out the new API documentation

---

src/api/public/apidocs-new/paths/build_project_name_repository_name_architecture_name_package_name_buildinfo.yaml
src/api/public/apidocs-new/paths/build_project_name_repository_name_architecture_name_package_name_file_name.yaml
src/api/public/apidocs-new/paths/build_project_name_repository_name_architecture_name_package_name_file_name_view_fileinfo.yaml
src/api/public/apidocs-new/paths/build_project_name_repository_name_architecture_name_package_name_history.yaml
src/api/public/apidocs-new/paths/build_project_name_repository_name_architecture_name_package_name_log.yaml
src/api/public/apidocs-new/paths/build_project_name_repository_name_architecture_name_package_name_status.yaml

It is not required to have an operationId for an endpoint, and if not provided, Swagger will create one from the path.

Remove operationId param from all endpoints

---

src/api/public/apidocs-new/OBS-v2.10.50.yaml

Fix the link pointing back to the legacy documentation in the new API documentation

---

src/api/app/models/project.rb

**Ignore missing keys**
instead of throwing an exception that produces an ugly 500 internal server error for the user, we get a nice red box `'Key not found for project PRJ'`
Fixes #14445

Ignore missing keys

---

src/api/public/apidocs-new/components/schemas/buildinfo.yaml
src/api/public/apidocs-new/paths/build_project_name_repository_name_architecture_name_package_name_buildinfo.yaml

Access with this [link](https://obs-reviewlab.opensuse.org/eduardoj-apidocs_newpost_build_buildinfo/apidocs-new/index.html#/Build/post_build__project_name___repository_name___architecture_name___package_name___buildinfo) the documented endpoint in the review app.

Document `POST /build/.../_buildinfo` endpoint with OpenAPI

---

src/backend/bs_dodup

This can be used by tools like nagios so that failed dod updates can show up in monitioring.

[backend] bs_dodup: maintain a directory containing failed dod updates

---

src/backend/bs_publish

[backend] rename SHA256SUMS.sig to SHA256SUMS.gpg

---

src/api/app/controllers/source_controller.rb

Somewhere lost in refactoring. Was ignored when target was manually specified

[api] add architecture filter on release

---

src/api/public/apidocs/paths/source_project_name_package_name_cmd_release.yaml

The endpoint accepts the the arch parameter now as well.
Introduced in https://github.com/openSUSE/open-build-service/pull/14432

Add `arch` parameter to `POST /source/<project>/<package>?cmd=release` OpenAPI docs

---

.circleci/config.yml

Reverts openSUSE/open-build-service#14466
This is not needed according to https://circleci.com/docs/using-dynamic-configuration/#execute-specific-workflows-or-steps-based-on-which-files-are-modified

Revert "Add continuation orb"

---

src/api/public/apidocs/OBS-v2.10.50.yaml
src/api/public/apidocs/components/parameters/check_name.yaml
src/api/public/apidocs/components/responses/status_report/delete_project_forbidden.yaml
src/api/public/apidocs/components/responses/status_report/delete_repository_architecture_forbidden.yaml
src/api/public/apidocs/components/responses/status_report/delete_repository_forbidden.yaml
src/api/public/apidocs/paths/status_reports_built_repositories_project_name_repository_name_architecture_name_required_checks_check_name.yaml
src/api/public/apidocs/paths/status_reports_projects_project_name_required_checks_check_name.yaml
src/api/public/apidocs/paths/status_reports_repositories_project_name_repository_name_required_checks_check_name.yaml

This is a continuation of #14470 and so it depends on it. The first commit (which is the 4th after the previous PR's commits) has most of the content, the remaining commits are copies with most of the same content.
To verify:
- Use POST endpoint to create checks
- Use DELETE endpoint to delete checks
- Use GET endpoint to verify they aren't there

Document DELETE required checks api endpoints 

---

src/api/public/apidocs/OBS-v2.10.50.yaml

The "Status Project" section was not added to the `tags` section. It was shown at the end of the page.
Include the "Status Project" section into the `tags` section, alphabetically sorted. This solves the sort issue.
Related to #14450.

API documentation: sort sections alphabetically

---

src/api/app/helpers/webui/staging/workflow_helper.rb

handle a zero `total` value gracefully
to not throw an exception

Avoid division by zero

---

src/api/app/helpers/webui/markdown_helper.rb
src/api/spec/helpers/webui/markdown_helper_spec.rb
src/api/spec/mailers/event_mailer_spec.rb

Bots are spamming us with hyperlinks to unrelated sites to increase their pages' score in search engines. By adding rel="nofollow", this will be disincentivised.
Fixes #14189

Tag hyperlinks with nofollow

---

src/api/app/models/package.rb

closes #14503 
The only possibility of this exception is because of nil values in the directory list.

Filter nil entries from directory list

---

src/api/app/assets/javascripts/webui/comment.js
src/api/app/assets/javascripts/webui/write_and_preview.js
src/api/app/components/write_and_preview_component.html.haml
src/api/app/views/webui/comment/_comment_field.html.haml

Like in #13878, since the upgrade to Bootstrap 5 the preview comment tab in the Project's and Package's page stopped working because Bootstrap 5 doesn't use jQuery anymore.
Additionally we get rid of the previewer com [comments.js](https://github.com/openSUSE/open-build-service/blob/1d66ab1913201d464ae17b9793b8537868633d14/src/api/app/assets/javascripts/webui/comment.js#L115) and use the generic from [write-and-preview.js](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/assets/javascripts/webui/write_and_preview.js)
Fixes #13901
- Go into the [home:Admin's project page](https://obs-reviewlab.opensuse.org/danidoni-fix-comments-preview-tab/project/show/home:Admin) logged in as Admin.
- Write some message into the comments box.
- Click on the Preview tab
- You should …

Fix preview comment tab click under bootstrap 5

---

src/api/app/models/token.rb
src/api/spec/models/token/workflow_spec.rb

A simple validation of validity and accessibility of a workflow token url.
To verify:
- Create or edit a workflow token
- Set the workflow configuration url
Look at the tests for ideas on how to break this nicely

Validate workflow_configuration_url before saving it

---

dist/functions.setup-appliance.sh

Fixes: #14518
'data:schema:load' seems not needed to be called separatly any longer.

[dist] removed 'data:schema:load' from obsapisetup

---

src/api/app/models/workflow.rb

For this step there is also no target project to restore or destroy when a pull request is closed or reopened. We should ignore it as well. Otherwise it throws an error and creates a workflow run with a failed status.

Ignore trigger services step for destroy and restore on pull request event

---

dist/setup-appliance.sh

This is required since opensuse 15.4. Otherwise apache will fail with a config error

[dist] obsapisetup: create openssl key with 4096

---

src/backend/BSSched/ProjPacks.pm

We currently only use the project namespace. Sometimes we must define two distinct projects to be related.

[backend] add a way to specify related projects in BSConfig

---

src/api/app/models/gitea_payload/pull_request.rb

This finishes the former work of not inheriting github payload in gitea classes.

Avoid inheriting github payload in gitea's pull_request

---

src/api/app/components/workflow_run_detail_component.html.haml
src/api/app/components/workflow_run_detail_component.rb
src/api/app/controllers/trigger_workflow_controller.rb
src/api/app/models/workflow_run.rb
src/api/db/migrate/20230615111252_add_configuration_url_and_path_columns_to_workflow_run.rb
src/api/db/schema.rb
src/api/spec/components/workflow_run_detail_component_spec.rb
src/api/spec/factories/workflow_runs.rb

We are extending the WorkflowRun model to make it easier to query by relevant data that helps us debug failed integrations.
Two of the relevant values are stored in  `Token#workflow_configuration_(url|path)`. As we want to know the values stored on those fields when the workflow ran, I added new columns to the `workflow_runs` table.
In the UI, I added a new tab, `Workflow configuration`, where we are going to display all the information related to the workflow configuration file: URL, path, content etc.

Handle config file URL or path easily from workflow run

---

src/api/app/components/workflow_run_detail_component.rb
src/api/app/components/workflow_run_row_component.rb
src/api/app/controllers/trigger_workflow_controller.rb
src/api/app/models/workflow_run.rb
src/api/db/data/20230620110143_backfill_scm_vendor_and_hook_event_in_workflow_run.rb
src/api/db/data_schema.rb
src/api/db/migrate/20230616154316_add_scm_vendor_and_hook_event_columns_to_workflow_run.rb
src/api/db/schema.rb
src/api/spec/components/workflow_run_header_component_spec.rb
src/api/spec/components/workflow_run_row_component_spec.rb
src/api/spec/db/data/backfill_scm_vendor_and_hook_event_in_workflow_run_spec.rb
src/api/spec/factories/workflow_runs.rb
src/api/spec/models/workflow_run_spec.rb

We are extending the WorkflowRun model to make it easier to query by relevant data that helps us debug failed integrations.
The SCM vendor and the hook event are key for us to query. They are now stored in the `workflow_runs` table.
This PR includes a data migration to backfill those values taking the data from `WorkflowRun#request_headers`. 
Nothing changed in the UI as we were displaying that information already:
Based on #14509

Expand workflow run with headers info

---

src/api/app/instrumentations/workflow_instrumentation.rb
src/api/app/models/concerns/workflow_version_matcher.rb
src/api/app/models/workflow.rb
src/api/app/services/workflows/yaml_to_workflows_service.rb
src/api/app/validators/workflow_version_validator.rb
src/api/spec/models/concerns/workflow_version_matcher_spec.rb
src/api/spec/models/workflow_spec.rb
src/api/spec/validators/workflow_version_validator_spec.rb

This PR introduces a small implementation to allow versioning for SCM/CI workflow features and changes. The version scheme I would suggest would be `major.minor`. Major versions for non-backwards compatible features and changes. Minor versions for backwards compatible features and changes (non breaking features). For now I would not enforce to specify a version and would fallback to the latest minor version.
The version is specified on the top level and matches the whole `workflow.yml` file against a specific version:
```
version: '1.1'
workflow:
steps:                                                                                                                                                                                                                                           
- …
```

Allow versioning for SCM/CI workflow features and add support for event aliases (v.1.1)

---

.obs/workflows.yml

After introducing versioning for the SCM/CI workflows, let's use the latest version ourselfs.

Use version '1.1' for OBS SCM/CI workflows

---

src/api/app/instrumentations/workflow_instrumentation.rb

That extra space was confusing Telegraf.
Nothing was showing up on [this Grafana panel](https://obs-measure.opensuse.org/d/FSxgue_4k/scm-ci-integration-long-term?viewPanel=22&orgId=1&from=now-12h&to=now&refresh=5s).

Remove extra space from the measurement

---

src/api/app/controllers/concerns/scm_webhook_payload_data_extractor.rb
src/api/app/models/workflow_run.rb
src/api/db/data/20230623122537_backfill_workflow_run_payload_data.rb
src/api/db/data_schema.rb
src/api/db/migrate/20230621071327_add_payload_data_to_workflow_run.rb
src/api/db/schema.rb
src/api/spec/support/files/request_payload_github_pull_request_opened.json
src/api/spec/support/files/request_payload_github_push.json
src/api/spec/support/files/request_payload_github_tag_push.json

Extend workflow_run DB table to store data from the payload. Extracted from #14527 so we can run this online.
1. We create the fields in the database
2. Getters are still using the `request_payload` field to fetch the data
3. Setters are the default from AR
4. Data migration to backfill data from payload field
5. Getters will [be removed](https://github.com/openSUSE/open-build-service/pull/14527/commits/114aaccc8b9ab2d4333af88fbbc8ed21e3f96629) once the second PR is merged

Introduces workflow run payload fields

---

src/api/app/components/workflow_run_row_component.rb
src/api/app/controllers/concerns/scm_webhook_headers_data_extractor.rb
src/api/app/controllers/trigger_workflow_controller.rb
src/api/app/models/workflow_run.rb
src/api/lib/tasks/dev/workflows.rake
src/api/spec/controllers/trigger_workflow_controller_spec.rb
src/api/spec/factories/workflow_runs.rb
src/api/spec/lib/tasks/workflows_spec.rb
src/api/spec/models/token/workflow_spec.rb
src/api/spec/queries/workflow_runs_finder_spec.rb
src/api/spec/support/files/request_payload_gitlab_pull_request_merged.json

Extract some of the important information that is in the SCM webhook HTTP request (headers/body) into `WorkflowRun` attributes so they are easier to query.

Expand workflow run with payload info

---

src/api/app/models/workflow_run.rb
src/api/app/services/workflows/yaml_to_workflows_service.rb
src/api/db/migrate/20230626092852_add_workflow_configuration_to_workflow_runs.rb
src/api/db/schema.rb

Having the actual Workflow configuration stored may help debug what happened when a Workflow Run fails.

Save the workflow yaml content into the workflow run

---

src/api/lib/tasks/dev/workflows.rake

Fix `dev:test_data:create` task.
<details>
<summary>Otherwise we receive the following errors:</summary>
```
> bin/rake dev:test_data:create
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Dropped database 'api_development'
Dropped database 'api_test'
Created database 'api_development'
Created database 'api_test'
Seeding architectures table...
Seeding roles table...
Seeding users table...
Seeding roles_users table...
Seeding static_permissions table...
Seeding static permissions for admin role in roles_static_permissions table...
Seeding static permissions for maintainer role in roles_static_permissions table...
Seeding static permissions for reader role in roles_static_permissions table...
Seeding static permissions for downloader role in roles_static_permissions …
```

Make use of newly introduced traits in dev tasks

---

src/api/spec/lib/tasks/workflows_spec.rb

Make use of the newly defined `:succeeded` trait

---

dist/t/spec/features/0030_project_spec.rb

15.3 no longer shows up in the distributions list, so it couldn't be selected no matter what.

Correct the dist specs to use an existing Leap release

---

src/api/app/models/event/container_published.rb

An event if a container image is published to a registry.
Jira feature [OBS-243](https://jira.suse.com/browse/OBS-243)

Introduces new ContainerPublished event

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/models/bs_request_action.rb
src/api/app/models/bs_request_action_tab_visibility.rb
src/api/app/views/webui/request/_request_tabs.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/build_results.html.haml
src/api/app/views/webui/request/changes.html.haml
src/api/app/views/webui/request/mentioned_issues.html.haml
src/api/app/views/webui/request/rpm_lint.html.haml
src/api/spec/features/webui/requests_spec.rb

Instead of passing around an array of `action[:type]`s only to decide whether or not to show a request action tab, let the object itself tell about its tabs visibility instead.
This PR refactors the way the request page tabs visibility is computed by moving the logic from an helper to a decorator class, based also on [this discussion](https://github.com/openSUSE/open-build-service/pull/14347#pullrequestreview-1431216663).

Refactoring tab visibility - use decorator instead of helper

---

src/api/app/models/bs_request_action_tab_visibility.rb

We used symbols instead of strings for that array, this only works with direct comparisons and not for checking the contents of the array with `in?`, this fixes #14590

Use the strings instead of symbols in BsRequestActionTabVisibility

---

src/api/spec/features/webui/projects_spec.rb

https://app.circleci.com/pipelines/github/openSUSE/open-build-service/13047/workflows/19fde3a4-9d85-4ab6-93f8-6be2ec378a18/jobs/137231/tests
This is a flaky test because the `click_link('Create Maintenance Incident')` step fires up a possible slow code path that create a new `maintenance_project` and at the end it redirect to the page overview of the very new created project. If the creation and redirect are slow, the following step tries to test for the content of the landing page of the new project, which is not yet rendered, so it fails. Making it wait a bit longer for a reasonable time (the double of the default) should fix the flakiness.

Flaky test depends on page loading time: make it wait a bit longer

---

src/api/app/components/comment_component.rb
src/api/app/controllers/comments_controller.rb
src/api/spec/cassettes/CommentsController/GET_show/of_a_bs_request_action_inline_comment_/with_an_inline_comment/1_1_4_1_1.yml
src/api/spec/cassettes/CommentsController/GET_show/of_a_bs_request_action_inline_comment_/with_an_inline_comment_of_a_removed_target_package/1_1_4_2_1.yml
src/api/spec/controllers/comments_controller_spec.rb
src/api/spec/factories/bs_request_actions.rb

After diff comments were introduced within the beta program, users of the API weren't able to list diff comments.
With the changes proposed, these could be examples of responses of calling the `GET /comments/request/id` API endpoint:
1) Example of a response performed in the development environment. The text of the comment is modified for inline comments:
```xml
<comments request="10">
<comment who="Admin" when="2023-07-03 10:56:52 UTC" id="9">Inline comment for target: 'home:Admin/another_package_with_diff_1688381711', file: 'README.txt', and line: 4:
In this README.txt file I would prefer `# Content` instead of `# New content`.</comment>
<comment who="Admin" when="2023-07-03 10:57:11 UTC" id="10">Inline comment for target: 'home:Admin/another_package_with_diff_1688381711', file: …
```

Show diff comments in the API endpoint `GET /comments/request/id`

---

src/api/app/components/comment_component.rb

Prevent from throwing an error for replies to inline comments. These comments don't fill the `diff_ref` field.
- Create an inline comment for a submit request.
- Reply to this comment with another comment.
- Show the comments for that request using the API endpoint `GET /comments/request/{id}`

API: show replies to inline comments

---

src/api/app/views/webui/comment/_comment_list.html.haml
src/api/app/views/webui/comment/_content.html.haml

After diff comments were introduced within the beta program, users not in the beta program weren't able to see diff comments in the web interface.

Show diff comments in the Web UI, non-beta

---

src/api/app/assets/stylesheets/webui/collapsible-text.scss
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_conversation_aside.html.haml

In the scope of highlighting more the `BsRequest` description, it is a fact that the description itself is the _initial comment_ of the request, so it is the root from where the history starts.
With this PR the description has its own title and box, and the history timeline starts from this box.
By doing this, the aside column with all the other information (reviewers, maintainers, etc) are aligned with the top of the Conversation tab panel.

Request description as part of the conversation history

---

src/api/app/views/webui/request/beta_show.html.haml

More space between the title and the text

---

src/api/app/views/webui/request/_actions_details.html.haml
src/api/spec/features/webui/requests/submissions_spec.rb

The same information was used for the tab titles of the actions in [the former UI](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/views/webui/request/show.html.haml#L34). Users should be familiar with that information as the most important one to distinguish request actions. 
This addresses one of the point mentioned in https://github.com/openSUSE/open-build-service/issues/14440

Show the most relevant information of the current action in the dropdown

---

src/api/app/views/webui/request/beta_show_tabs/_rpm_lint_result.html.haml

For each repository there is one dedicated select box for the related architectures of each. Every time the repository changes, the related select box is shown, and all the others are hidden. Having them wrapped under the same `div` container fixes the bug that the visible architecture select box _seems to move around_ when the repo changes, but actually all the space is taken by all the hidden boxes and when the related one is shown it pops up at a different place.
In the same `div` instead, they place all at the top left position because the others are hidden.
This PR addresses one of the point mentioned in https://github.com/openSUSE/open-build-service/issues/14440
This PR fixes the behavior, but technically speaking, instead of having multiple architectures select boxes one per each …

Wrap all select boxes under the same div container

---

src/api/app/controllers/webui/webui_controller.rb

In 253fce629160e96a74381230e93e0a0a10d0966c @hennevogel  moved setting influx tags into set_influxdb_data. But in WebuiController the filter was running *before* check_user so User.session was *always* nil.
That means for webui requests, both beta and anonymous tags have been wrong since that time. oops... :-(

Fix filter order for set_influxdb_data

---

src/api/lib/haml-lint/custom_linters/set_pagetitle_in_view.rb

Better use `HamlLint::RubyExtraction::ChunkExtractor` instead of `HamlLint::RubyExtractor`. The lastest haml_lint version removed `HamlLint::RubyExtractor`, and it's breaking [our Haml linting phase](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/13199/workflows/592c3ad0-3bfc-42f2-a48c-f607186e3ab9/jobs/138485)
See [this PR](https://github.com/sds/haml-lint/pull/415) for more details

Replace HamlLint::RubyExtractor

---

src/api/.haml-lint.yml

Otherwise it fails in CircleCI.
Kudos to @danidoni, who reported it.
Related to #14638.

Exclude vendor/bundle/ subdirectory from HAML linter

---

src/api/app/models/kiwi/package.rb

```ruby
[1] pry(main)> Kiwi::Package.find(3).package_group.image
Kiwi::Package Load (0.3ms)  SELECT `kiwi_packages`.* FROM `kiwi_packages` WHERE `kiwi_packages`.`id` = 3 LIMIT 1
Kiwi::PackageGroup Load (0.4ms)  SELECT `kiwi_package_groups`.* FROM `kiwi_package_groups` WHERE `kiwi_package_groups`.`id` = 2 LIMIT 1
Kiwi::Image Load (0.3ms)  SELECT `kiwi_images`.* FROM `kiwi_images` WHERE `kiwi_images`.`id` = 1 LIMIT 1
=> #<Kiwi::Image:0x00007f20e2689188
id: 1,
name: "minimal-container-image",
md5_last_revision: "72e9c1a7931aa189a038a5e1fbcc212d",
created_at: Fri, 14 Jul 2023 13:40:06.000000000 UTC +00:00,
updated_at: Fri, 14 Jul 2023 13:40:31.817526000 UTC +00:00,
use_project_repositories: true>
[2] pry(main)> 
```
```ruby
[3] pry(main)> Kiwi::Package.find(3).kiwi_image
Kiwi::Package Load …
```

Fix kiwi_image association in Kiwi::Package model

---

src/api/app/services/workflows/yaml_downloader.rb
src/api/spec/services/workflows/yaml_downloader_spec.rb

Previously we have been using Down gem to download workflows. Down is not able to download workflows from private repos. This PR is using the GitLab client to download private workflow.yaml files.

Download workflow file for private GitLab repositories

---

.circleci/conditional_config.yml

We have switched our production, test, and development environments to Leap 15.4 since some time ago.

Upgrade CircleCI base image to Leap 15.4

---

src/api/app/views/webui/package/binary.html.haml

Fixes #13746
How to test it
1. Create a package, let's say `hello_world`.
2. Create another package, let's say `bye_world`. Add a `Requires: hello_world` in bye_world.spec.
3. Build both packages.
4. Go to `hello_world`, in the `Build results` click on one of the `Architectures` successfully built, you get the `Repository State` page.
5. Click on the `Details` link on one of the `rpm`s. You get the `Detailed Information` page regarding the binary you clicked on.
6. Click on the link under the `Required By` column in the `Provides` table.
7. The link **now works** and will get you the `Detailed Information` page regarding the other binary.

Fix links to dependant packages in package binary page

---

src/api/app/models/workflow/step/rebuild_package.rb
src/api/app/models/workflow/step/trigger_services.rb

Until now we weren't notifying the SCM of the build status triggered by the Trigger Service or the Rebuild Package steps.
- [Set up your environment](https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration-Testing) to set up your environment, but don't trigger the workflow yet.
- Tweak the package so the building fails (I use an `exit(1)` in the `%build` phase)
- Use a `payload.json` like this one:
```
{
"object_kind": "push",
"before": "60cd89df0215ab64cff9b8076a4a3334dce71ba7",
"after": "1873d25e0fb0c245e3ad75aadca1f69fdf5fd70b",
"ref": "refs/heads/master",
"project_id": 16871458,
"project": {
"id": 16871458,
"name": "hello_world",
"web_url": "https://github.com/danidoni/hello_world",
"path_with_namespace": "danidoni/hello_world",
"http_url": …
```

Create event subscription for trigger service and rebuild package workflow steps

---

dist/elastic_build_service_manager.py

See deprecated API route in the documentation: https://api.opensuse.org/apidocs/#/Build/get_build__workerstatus
Found while researching a fix for #14677.

Switch deprecated API route to retrieve worker statuses

---

src/api/app/views/webui/package/revisions.html.haml

One of the conditions is enough to hide the show_all button
Scenario fixed: when pagination pages are just 1 and the user is logged in, the condition was returning `false` because of the `&&`, so the show_all button was visible. But this is wrong because there is no pagination and all the revisions are already visible in the first page.
Before (no pagination, but `Show all` button is visible)
After (no pagination and `Show all` button is **not** visible)

Fix button visibility condition

---

src/api/app/services/workflows/scm_event_subscription_creator.rb

When including the workflow run in the query, we do not get any EventSubscription back, then the `create` part of the `find_or_create_by` kicks in and we end up having tons of notifications.
Follows up https://github.com/openSUSE/open-build-service/pull/14666
- [Set up your environment](https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration-Testing), but don't trigger the workflow yet.
- Use a `workflows.yml` like [this one](https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration-Workflows#rebuild-a-package) to trigger a Rebuild.
- Tweak the package so the building fails (I use an `exit(1)` in the `%build` phase)
- Push some changes against your default branch, let the workflow finish and you should get a :x: next to the …

Reuse existing event subscription to notify SCMs back

---

src/api/app/models/workflow/step/branch_package_step.rb
src/api/app/models/workflow/step/link_package_step.rb
src/api/app/services/workflows/scm_event_subscription_creator.rb

SCMs don't support statuses for tags, so we don't need to report back in ANY case

Never report on Tag Push events

---

src/api/app/views/webui/package/revisions.html.haml

The badge counter in the Revisions page title is buggy:
- it contains the number of the elements visible in the page (i.e. if we are at page 2 of a list of 25 elements with 10 items per page, it reports `10` because it counts the paginated slice only)
- how many items are shown in the page (paginated or not) is not a property to deliver in the title as a badge
- all about pagination should be forwarded and managed by Kaminari
Before
After
(1) 
(2)

Revisions pagination info

---

src/api/app/controllers/trigger_workflow_controller.rb
src/api/app/models/workflow.rb

We started to use Pundit a lot in the various `Workflow::Step`. Authorization failures that happen inside the `Workflow` should be reflected in the `WorkflowRun` and not in the request cycle.
Also: As the `TriggerWorkflowController` takes care about APIErrors and Pundit now, we don't need to handle those exceptions in `Workflow.destroy_target_projects`.

Tell people about Pundit errors in WorkflowRun

---

README.md

- use Leap 15.4 instead of 15.1
- use new repository naming pattern (`15.4` instead of `openSUSE_15.1`)

README.md: use Leap 15.4 instead of 15.1

---

src/backend/BSRPC.pm
src/backend/bs_dodup

And also make rpc timeouts log the url in bs_dodup.

[backend] BSRPC: reduce dns cache ttl to one hour

---

src/backend/BSServerEvents.pm
src/backend/BSWatcher.pm
src/backend/bs_notifyforward

Our naive socket dup does not work for TLS connections. We need to make BSRPC keep the socket instead. But for now, just disable the option.

[backend] bs_notifyforward: disable multirequest mode when using https

---

src/backend/BSServerEvents.pm
src/backend/BSWatcher.pm

Otherwise we might end up in an inconsistent state and add events twice, leading to a assertion error.

[backend] always remove events from the active list when pausing

---

src/backend/bs_srcserver

The old $cgi->{'repository'} seems to be a copy from getprojectsourceinfo(). It worked for all the normal published_path uses, but not if it is called from getproductrepositories(). So use the $repoid argument instead.

[backend] fix concatconfigs call in published_path

---

src/api/app/components/workflow_run_filter_component.html.haml
src/api/app/components/workflow_run_filter_link_component.html.haml
src/api/app/components/workflow_run_filter_link_component.rb

Little improvements on the workflow_run filters menu:
- use the icon of the status type (already in use in the list of entries) in the related filter link
- do not use a badge for the counter of each type, just show a lighter number
- align the counter of each type to the right
Before:
After:

Workflow run menu enhancements

---

src/api/config/application.rb

This being enabled causes strong migrations to complain about a dangerous operation while migrating our older migration, when linting the migrations or generating schema.rb

Disable partial inserts in active record

---

src/api/app/jobs/worker_measurements_job.rb

We still don't use the start time of daemons. We count the ocurrences of daemons instead.
Fixes #14677.
After deploying this fix, this panel should be modified: https://obs-measure.opensuse.org/d/Oh-R4b1Vz/bernhard-s-experiments?orgId=1&viewPanel=29

Don't send metrics of start times of daemons

---

src/api/app/models/workflow/step/submit_request.rb

The first payload is the OBS event payload, not the webhook payload.

Fix initial reporting

---

src/api/app/services/gitea_status_reporter.rb
src/api/app/services/github_status_reporter.rb
src/api/app/services/gitlab_status_reporter.rb
src/api/spec/services/gitea_status_reporter_spec.rb
src/api/spec/services/github_status_reporter_spec.rb
src/api/spec/services/gitlab_status_reporter_spec.rb

Can't have variable things like the requests state in the context. It is used to identify the commit status that has to be updated.

Drop state from commit status context

---

src/backend/BSSrcServer/Service.pm

We need to notify the repservers if it was not a obsscm run *or* there was an error.

[backend] fix logic in notify_repservers call

---

src/backend/BSSrcServer/Scmsync.pm

The scm bridge puts the project's scmsync url into the meta url entry, which leads to package meta commits for all packages if the project git changes.

[backend] Scmsync: ignore url when comparing the package meta

---

src/backend/BSProductXML.pm

To add option for opt-out product build number syncing
New source based BcntSyncTag handling requires new source parsers, therefor update build script reference.

[backend] sync product xml spec

---

src/api/public/apidocs/OBS-v2.10.50.yaml
src/api/public/apidocs/components/schemas/buildenv.yaml
src/api/public/apidocs/components/schemas/buildstatistics.yaml
src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_package_name_buildenv.yaml
src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_package_name_statistics.yaml

You can access a preview of the documented API endpoints in the review-app with the following links:
- [_buildenv](https://obs-reviewlab.opensuse.org/eduardoj-apidocsbuild_package_builenv_statistics/apidocs/index#/Build/get_build__project_name___repository_name___architecture_name___package_name___buildenv)
- [_statistics](https://obs-reviewlab.opensuse.org/eduardoj-apidocsbuild_package_builenv_statistics/apidocs/index#/Build/get_build__project_name___repository_name___architecture_name___package_name___statistics)

Document `GET /build/.../_buildenv` and `_statistics` API endpoints

---

src/api/app/components/chart_component.html.haml

1- Adjust threshold to decide whether to initialize the chart or the simplified UI.
2- Fix the wrapper for results of a single repository when they are many.
Before
After

Request build chart UI fixes

---

src/api/app/components/chart_component.html.haml

CSS class dropped by mistake in 2d8cddb893dba85a3037ee3b4ad571809b341b16
Before
After

Align elements properly so as not to take the entire height

---

src/api/app/jobs/worker_measurements_job.rb

Telegraf can't parse it when partition is empty for 'backend_daemon_status'. It will be 'main' in such cases.

Avoid sending empty partition metric

---

src/api/app/models/user.rb

Currently when we mark a user as spammer we delete the comments associated with the user using `delete_all`.
But this doesn't instantiate the comments first, so it doesn't delete the notification that are assoicated with the comments. We have set the `dependent: :destroy` on the `has_many :comments` on the user model, which defaults to `:delete_all` on a collection proxy, which doesn't call the `destroy` method on the comment. Therefore we have to use the `destroy_all` method.
See: https://api.rubyonrails.org/v7.0.7.2/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-delete_all
Fixes #14874

Use `destroy_all` over `delete_all` in `mark_as_spammer` method

---

src/api/app/assets/javascripts/webui/comment.js

Fixes: #14890
The former code relied on `textarea.cols` which always returned the same value, no matter if the textarea was wider or narrower. Therefore, it didn't match the actual line length.
The new code relies on `clientHeight` and `ScrollHeight` for resizing.
**Before:**
**After:**

Fix comments textarea resize by JS

---

src/api/app/components/delete_confirmation_dialog_component.html.haml
src/api/app/components/delete_confirmation_dialog_component.rb
src/api/app/controllers/webui/users_controller.rb
src/api/app/models/user.rb
src/api/app/views/webui/user/_basic_info.html.haml
src/api/app/views/webui/users/index.html.haml

- Aligns the behavior of the user `delete!` and `mark_as_spammer!` methods
- Add possibility to leave a admin note through the webui
- Add a link for user deletion to the user profile page (for admins only)

Extend user deletion webui

---

src/api/app/views/webui/shared/bs_requests/index.json.erb

The current request listing requires to hit *exactly* the 15x18 pixel region to the icon to get into the detailed listing. nothing else in the whole line links to details. there is no sensible keyboard navigation either.
This improves it to roughly 30x36 which is still far away from the minimum recommended sizes for user interaction elements (44x44) but slightly less insane.

Improve minimum button size of requests link in tables

---

src/api/app/controllers/person/token_controller.rb
src/api/spec/controllers/person/token_controller_spec.rb

Change response code to 400 Bad Request if either "project" or "package" parameters are missing in the `POST /person/<login>/token` request. Also provided a more meaningful response message to the user.
Fixes #14828

Improve token creation error message

---

src/api/app/assets/javascripts/webui/application.js
src/api/app/assets/javascripts/webui/report.js
src/api/app/components/report_component.html.haml
src/api/app/components/report_component.rb
src/api/app/controllers/webui/reports_controller.rb
src/api/app/models/comment.rb
src/api/app/models/package.rb
src/api/app/models/project.rb
src/api/app/models/report.rb
src/api/app/models/user.rb
src/api/app/policies/report_policy.rb
src/api/app/views/webui/comment/_reply.html.haml
src/api/app/views/webui/comment/_show.html.haml
src/api/app/views/webui/package/_show_actions.html.haml
src/api/app/views/webui/package/show.html.haml
src/api/app/views/webui/package/show_actions/_report_package.html.haml
src/api/app/views/webui/reports/create.js.erb
src/api/app/views/webui/user/_basic_info.html.haml
src/api/config/initializers/flipper.rb
src/api/config/routes/webui_routes.rb
src/api/db/migrate/20230907111316_create_reports.rb
src/api/db/schema.rb

This PR covers the implementation of the following things:
There will be a follow-up PR #14898 for the remaining features i.e., 
- [Specs for report policy](https://github.com/openSUSE/open-build-service/pull/14909)
- [Implementation of reporting a project](https://github.com/openSUSE/open-build-service/pull/14898)
- ~Implementation of report listing view~

Initial implementation of reports feature

---

src/backend/BSRepServer/DoD.pm

The parameter in the call is an url, not a path.

[backend] BSRepServer::DoD: fix url normalization

---

src/api/app/models/event_subscription.rb

This should have been included in b731fadcc619f7824a18aa91da7c063a0e749269.

Fix annotation comment in event subscriptions model

---

src/api/app/views/webui/project/_show_actions.html.haml
src/api/app/views/webui/project/show.html.haml
src/api/app/views/webui/project/show_actions/_report_project.html.haml

Follow-up on #14880 
Adds support for reporting projects from the left sidebar

Report projects

---

src/api/app/models/report.rb
src/api/db/migrate/20230915162740_make_reports_reportables_nullable.rb
src/api/db/schema.rb

When a moderator reports any misconduct on any object like comment, project, package or user and then decides to delete that object, we don't want to delete the associated report but nullify it. That's only possible if the database allows it.

Allow object deletion despite of reports

---

src/api/app/components/report_component.html.haml

Depends on #14911.
**Before:**
**After:**

When reporting an object, display a link to the Code of Conduct

---

src/api/.rubocop_todo.yml
src/api/app/assets/javascripts/webui/comment.js
src/api/app/components/bs_request_comment_component.html.haml
src/api/app/controllers/webui/comments_controller.rb
src/api/app/models/comment.rb
src/api/app/models/user.rb
src/api/app/policies/comment_policy.rb
src/api/app/views/webui/comment/_reply.html.haml
src/api/config/routes/webui_routes.rb
src/api/db/migrate/20230918161340_add_moderator_id_and_moderated_at_columns_to_comments.rb
src/api/db/schema.rb
src/api/spec/policies/comment_policy_spec.rb

We are introducing moderation on comments.
Moderators will be able to flag those comments, so a text like _"this comment was considered problematic ..."_ is going to be displayed instead of the original message.

Handle moderation on comments

---

dist/systemd/obs-delayedjob-queue-consistency_check.service
dist/systemd/obs-delayedjob-queue-default.service
dist/systemd/obs-delayedjob-queue-issuetracking.service
dist/systemd/obs-delayedjob-queue-mailers.service
dist/systemd/obs-delayedjob-queue-project_log_rotate.service
dist/systemd/obs-delayedjob-queue-quick@.service
dist/systemd/obs-delayedjob-queue-releasetracking.service
dist/systemd/obs-delayedjob-queue-scm.service
dist/systemd/obs-delayedjob-queue-staging.service

We observed three failed delayed queue services when the database connection went away during maintenance. This needed a manual restart that I want to avoid with this patch.
docs: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

Enable Restart on failure for delayed queue

---

src/backend/BSSched/BuildJob/Package.pm
src/backend/BSSched/Checker.pm

The old location does not work, it just sets every package from a build cycle to the blocked state.

[backend] move cycle blocked setting into handlecycle

---

src/api/app/assets/stylesheets/webui/datatables.scss
src/api/app/assets/stylesheets/webui/requests.scss
src/api/app/views/webui/shared/bs_requests/index.json.erb

A follow-up based on this nice contribution and useful conversation: https://github.com/openSUSE/open-build-service/pull/14908
It's not yet the final state of course, those tables implementation needs to be refactored (or dropped in favor of something else), but for now this PR provides a button with an icon and a text with sufficient area easy to click on
**Before**:
**After**:

Wider button for table request link

---

src/backend/BSSched/BuildJob/Aggregate.pm

The first line of the meta file is supposed to contain the package verifymd5. Also, containers where not part of the meta data at all because of a bogus filename filtering.

[backend] fix aggregate meta generation

---

src/api/app/controllers/webui/packages/job_history_controller.rb
src/api/app/controllers/webui/packages/main_controller.rb
src/api/spec/cassettes/Packages/adding_a_valid_file.yml

We use the set_package before filter in many controllers but use the is_link variable only one view. One less database and one less backend query...

Move is_link variable to the place it's used

---

src/backend/BSSched/RPC.pm
src/backend/BSSrcServer/Srcdiff.pm
src/backend/BSUtil.pm
src/backend/bs_srcserver

You need to do a POST to /issue_trackers with query string cmd=issues and the body containing the text to be scanned.

[backend] support parsing text for issue tracker matchers

---

src/backend/BSXML.pm

We need it when requesting issues for a given text. Should have been in commit 31007e944f37d171ae17d9a7997aa871665d656f

[backend] split BSXML::issues from BSXML::sourcediff

---

src/api/app/models/event/base.rb

Only return users with Admin or Staff roles if there are no moderators present.

Favor moderator as Report notification receivers

---

src/api/app/models/architecture.rb

We use architecture around 30 times in our routes. Not once by id AFAICS...

Introduces Architecture.to_param

---

src/api/app/controllers/concerns/webui/rescue_handler.rb
src/api/app/controllers/webui/webui_controller.rb
src/api/spec/controllers/webui/feeds_controller_spec.rb
src/api/spec/controllers/webui/project_controller_spec.rb
src/api/spec/controllers/webui/projects/maintenance_incident_requests_controller_spec.rb
src/api/spec/controllers/webui/projects/meta_controller_spec.rb
src/api/spec/controllers/webui/projects/project_configuration_controller_spec.rb
src/api/spec/controllers/webui/webui_controller_spec.rb

Instead of sending people to the 404 page, redirect and render a flash message.

Handle Project/Package not found more gracefully

---

src/api/app/components/notification_avatars_component.rb
src/api/app/models/decision.rb
src/api/app/models/event/base.rb
src/api/app/models/event/cleared_decision.rb
src/api/app/models/event/favored_decision.rb
src/api/app/models/event_subscription.rb
src/api/app/queries/outdated_notifications_finder/decision.rb
src/api/app/services/notification_service/notifier.rb
src/api/app/services/notification_service/web_channel.rb
src/api/app/services/notified_projects.rb
src/api/lib/tasks/dev/reports.rake

This PR wires up the events and subscriptions required to get a notification when a Moderator makes a Decision about some Report.
It features very basic notifications, the actual notification is fleshed out in #14976 
The filters required for the notification screen are going to be implemented in #14975

Introduce notifications for decisions on moderated objects

---

src/api/app/components/notification_action_description_component.rb
src/api/app/components/notification_component.rb
src/api/app/components/notification_excerpt_component.rb
src/api/app/components/notification_notifiable_link_component.rb
src/api/app/models/decision.rb
src/api/app/models/event/cleared_decision.rb
src/api/app/models/event/favored_decision.rb
src/api/lib/tasks/dev/reports.rake
src/api/spec/components/notification_action_description_component_spec.rb
src/api/spec/components/notification_notifiable_link_component_spec.rb
src/api/spec/factories/decisions.rb
src/api/spec/factories/notification.rb

The original PR started with a bare-bones implementation of the notification for Decisions. This PR is an improved view for those notifications
Notifications about cleared and favor decisions look like this:
Follows up https://github.com/openSUSE/open-build-service/pull/14967
1. The default test data has some decision notifications, so if you log in with Iggy (the reporter) and go into [the notification area](https://obs-reviewlab.opensuse.org/danidoni-implement-better-notifications-for-report-decisions/my/notifications?type=unread) and scroll down, you'll see some.

Implement better notifications for report decisions

---

src/api/app/controllers/webui/users/notifications_controller.rb
src/api/app/jobs/send_event_emails_job.rb
src/api/app/models/event_subscription/form.rb
src/api/app/models/user.rb
src/api/app/policies/comment_policy.rb
src/api/app/policies/decision_policy.rb
src/api/app/policies/report_policy.rb
src/api/app/services/notification_service/notifier.rb
src/api/spec/factories/users.rb
src/api/spec/policies/comment_policy_spec.rb
src/api/spec/policies/report_policy_spec.rb

In the beginning of the content_moderation feature we considered
user that have the admin or stuff roles to be moderator. But now
we have the dedicated moderator role. So we only should check
for that in the `is_moderator?` method and leave the rest to
the pundit policies.
The authorization logic about if a user should receive notifications
for reports is spread over several places.
Lets move it to a policy to avoid duplication and confusion.
Also in the moderate comment policy we didn't considered the moderator role, 
only staff and admin users.

Align `is_moderator?` method and report pundit policies

---

src/api/app/services/notified_projects.rb

Right now, this function returns a project or a collection of projects depending on the commentable type.

Make NotifiedProjects always return an array

---

src/backend/BSSSL.pm

Otherwise we go into an endless loop as the socket will always be returned as "data available" from the select call.

[backend] BSSSL: fix EOF handling in data_available 

---

src/api/db/data/20200421121610_backfill_notified_projects.rb

Otherwise we get errors like this one:
ActiveRecord::RecordInvalid: Validation failed: Notification These notification and project are already associated
from /usr/lib64/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/active_record/validations.rb:80:in `raise_validation_error'

Notify only projects not already notified

---

src/api/app/models/report.rb

Right after deployment, the reference server had issues because of missing categories. The issues were momentary.
As the same deployment will be done in other instances soon, we better prevent them from having the same issues. While we go on researching what was wrong with the migration (which set default values).
Related to #15004

Prevent issues for missing categories

---

src/api/app/assets/stylesheets/webui/cm2/bootstrap.scss
src/api/app/assets/stylesheets/webui/coderay.scss
src/api/app/assets/stylesheets/webui/diff.scss
src/api/app/assets/stylesheets/webui/tabs.scss
src/api/app/views/webui/request/beta_show.html.haml

- no bottom border for the active tab
- no bottom border for the title header in the request description
- more space for the timeline title header

Bootstrap fixes

---

src/api/db/data/20231004134538_create_a_default_subscription_for_decision_related_events.rb
src/api/db/data_schema.rb

We need to have everyone subscribed automatically to FavoredDecision and ClearedDecision events.

Create a default subscription for Decision-related events

---

src/api/app/controllers/worker/status_controller.rb

Change the headers returned by the `GET /worker/_status` endpoint.
```
Content-Type: application/octet-stream
Content-Disposition: attachment
Content-Transfer-Encoding: binary
```
```
Content-Type: application/xml; charset=utf-8
```
No `Content-Disposition` and `Content-Transfer-Encoding` headers returned.
Partially addresses #14478.
- Perform the following API request before the changes of this pull request and after them, in your development environment:
```
curl -i -u Admin:opensuse -H 'Content-Type: application/xml; charset=utf-8' "http://localhost:3000/worker/_status"
```
- Check the headers returned.

Fix content-type header returned by `GET /worker/_status` API endpoint

---

src/api/db/migrate/20231011135554_create_comment_locks.rb
src/api/db/schema.rb

Extracted from #15015 to avoid issues with database migrations and models being out of sync during the deploy.

Database migrations for comments lock feature

---

src/api/db/schema.rb

This should have been added in a6b70339a0348049a3497b96e0506300dbe05ea3.

Add missing collation in versions table

---

src/api/app/components/notification_action_description_component.rb
src/api/app/components/notification_notifiable_link_component.rb
src/api/app/helpers/webui/reportables_helper.rb
src/api/app/jobs/send_event_emails_job.rb
src/api/app/models/event/base.rb
src/api/app/models/event/create_report.rb
src/api/app/models/event/report.rb
src/api/app/models/event/report_for_comment.rb
src/api/app/models/event/report_for_package.rb
src/api/app/models/event/report_for_project.rb
src/api/app/models/event/report_for_user.rb
src/api/app/models/event_subscription/for_channel_form.rb
src/api/app/models/event_subscription/form.rb
src/api/app/models/report.rb
src/api/app/queries/notifications_finder.rb
src/api/app/services/notification_service/notifier.rb
src/api/app/views/event_mailer/create_report.html.haml
src/api/app/views/event_mailer/report_for_comment.html.haml
src/api/app/views/event_mailer/report_for_package.html.haml
src/api/app/views/event_mailer/report_for_project.html.haml
src/api/app/views/event_mailer/report_for_user.html.haml
src/api/lib/tasks/dev/rake_support.rb
src/api/spec/factories/event_subscriptions.rb
src/api/spec/mailers/event_mailer_spec.rb

This is the first PR to split up the events created by reports. The code still supports the old implementation of the `Event::CreateReport` class. But after this PR is merged we won't produce new records with this anymore, but instead the new STI event classes.
This enables us to safely deploy those changes, then migrate existing records first and finally remove the old implementation.
HOW TO TEST THIS:
1. Create some test data with `bundle exec rake dev:test_data:create`
2. The rake task will produce some reports and corresponding notifications
3. Check that notifications are still produced and the links on those are still working
4. Check the subscription form, it won't show the subscription option for the `Event::CreateReport` anymore, but should show the new ones

Split up report event class

---

src/api/app/controllers/concerns/rescue_handler.rb
src/api/public/apidocs/paths/source_project_name_cmd_undelete.yaml
src/api/public/apidocs/paths/worker_cmd_checkconstraints.yaml

For "Not Found" exceptions happening in the backend, return the `summary` section of that XML response.
Also, adapt the documentation accordingly.
Take a look at the 404 responses for the modified API endpoints in the review-app:
- [POST /source/{project_name}?cmd=undelete](https://obs-reviewlab.opensuse.org/eduardoj-fixapidocs_not_found_responses/apidocs/index#/Sources%20-%20Projects/post_source__project_name__cmd_undelete)
- [POST /worker?cmd=checkconstraints](https://obs-reviewlab.opensuse.org/eduardoj-fixapidocs_not_found_responses/apidocs/index#/Workers/post_worker_cmd_checkconstraints)

Fix "not_found" API responses

---

src/api/app/controllers/issue_trackers_controller.rb
src/api/app/controllers/staging/staged_requests_controller.rb
src/api/app/controllers/staging/staging_controller.rb
src/api/app/controllers/status/required_checks_controller.rb

`errorcode` has a default value when `status` is `404`. Stop setting those options all over the app to their defaults again.
See [here](https://github.com/openSUSE/open-build-service/blob/004d2ff1f9ce1331a01e266163522d6da2e2591d/src/api/app/controllers/application_controller.rb#L151), where errorcode takes its default value.

Stop setting options that are already default, II

---

src/api/.database_consistency.todo.yml
src/api/app/models/package.rb

Add maximum length validation for package url

---

src/api/app/views/webui/packages/files/new.html.haml

Related to #14544.
- Browse one package in the [review-app](http://obs-reviewlab.opensuse.org/eduardoj-fixissue_14544_2).
- Click on the "Add an empty file or service " link
- Enter a very long url in the "File URL:" field, greater than 200 characters.
- Confirm you are able to upload the file.

Increase length limit of URL to upload a file

---

src/api/app/controllers/concerns/rescue_handler.rb

This was duplicated in [this commit](https://github.com/openSUSE/open-build-service/commit/b263c6d33d1a27dc8405c9cd1d8eea707c5f233c#diff-acb1d17436d6c7263161f60f57b01e0f4c12ae09ef956e31e1ff67f813891ac4R411-R428).

Remove redefined handler for `Backend::Error` exceptions

---

src/api/app/controllers/source_controller.rb
src/api/public/apidocs/OBS-v2.10.50.yaml
src/api/public/apidocs/paths/source_project_name_package_name_cmd_wipe.yaml
src/api/test/functional/source_controller_test.rb

Before we throw an the internal exception _"undefined method `package_command_wipe'"_.
The method `package_command_wipe` was never implemented.
Now, calls to API endpoints like `POST /source/home:my_user/my_package?cmd=wipe` result in:
```
<status code="illegal_request">
<summary>invalid_command</summary>
</status>
```
Fixes #13996.

Remove 'wipe' from the list of valid package commands

---

src/api/app/assets/stylesheets/webui/modals.scss
src/api/app/components/modal_component.html.haml
src/api/app/components/modal_component.rb
src/api/spec/components/modal_component_spec.rb
src/api/spec/components/previews/modal_component_preview.rb

Introduce modal core [component](https://viewcomponent.org/) in order to standardize and reuse it.
Previews available at http://obs-reviewlab.opensuse.org/ncounter-modal-core-components/rails/view_components/modal_component
Same as https://github.com/openSUSE/open-build-service/pull/15030

Core component: modal

---

src/api/app/controllers/request_controller.rb

Related to #15011.
```
> osc rq show 123456789
Server returned an error: HTTP Error 404: Not Found
Couldn't find BsRequest with [WHERE `bs_requests`.`number` = ?]
```
```
> osc rq show 123456789
Server returned an error: HTTP Error 404: Not Found
Couldn't find Request with number '123456789'
```

Fix error message for `GET /request/{id}` API endpoint

---

src/api/app/controllers/source_project_controller.rb

This PR improves the error message returned when the `view` parameter has not a valid value for `GET /source/{project_name}` API endpoint requests.
To see the permited values the `view` parameter can be passed to the backend take a look at the backend router, [here](https://github.com/openSUSE/open-build-service/blob/81eca94d4516ac656c842a6e0f845963f88dda09/src/backend/bs_srcserver#L7648).
Fixes #8797.
```
> curl -u Admin:opensuse "http://localhost:3000/source/home:Admin?view"
<status code="400">
<summary>unknown parameter 'view'</summary>
</status>
```
```
> curl -u Admin:opensuse "http://localhost:3000/source/home:Admin?view"
<status code="invalid_parameter">
<summary>Parameter 'view' doesn't accept value ''</summary>
</status>
```

Pass API requests with a valid `view` parameter to the backend

---

src/api/app/controllers/status/required_checks_controller.rb

Fixes #14471.
```
> curl -u Admin:opensuse "http://localhost:3000/status_reports/built_repositories/home:Admin/openSUSE_Tumbleweedd/x86_64f/required_checks"
<status code="not_found">
<summary>Couldn't find repository 'openSUSE_Tumbleweedd'</summary>
</status>
```
```
> curl -u Admin:opensuse "http://localhost:3000/status_reports/built_repositories/home:Admin/openSUSE_Tumbleweed/x86_64f/required_checks"
<status code="not_found">
<summary>Couldn't find architecture 'x86_64f'</summary>
</status>
```
```
> curl -u Admin:opensuse "http://localhost:3000/status_reports/built_repositories/home:Admin/openSUSE_Tumbleweed/i586/required_checks"
<status code="not_found">
<summary>Couldn't find architecture 'i586'</summary>
</status>
```

Fix error messages returned for not found parameters

---

.github/workflows/isolated_migrations.yml

Check if migrations and their related code changes are not included on the same pull request.
Check if the [schema.rb](url) and data_schema.rb files are included in the pull request that introduces a migration or data migration.
You can see this GitHub action working on my [sandbox repository](https://github.com/saraycp/hello_world/pulls).
You will see a few pull requests representing the different scenarios we could have. For example, ["migration only"](https://github.com/saraycp/hello_world/pull/19) fails because the PR contains a migration but not the `schema.rb` changes.

Create Isolated Migrations GitHub action

---

src/api/config/environments/test.rb
src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/minitest.rake
src/api/test/test_helper.rb

Make it possible to run some (like ~97% as of this writing) minitest tests in the container based development environment against the backend that is running there.
```
$ rake dev:minitest:fixtures:create RAILS_ENV=test
$ export RUNNING_MINITEST_WITH_DOCKER=1
$ rake test TEST=test/functional/request_events_test.rb
```
Please be aware: If you are using this you'll be responsible for resetting the state of the backend. Like running
```
$ docker-compose stop backend
$ docker-compose rm -f backend
$ docker-compose up -d backend
```
before and after executing a test as the tests are optimized to be run once.
It'll also not work for tests that "mock" backend functionality. Like the ones using TestHelper.inject_build_job or doing something with OBS_BACKEND_TEMP.
```
$ grep -Hrl OBS_BACKEND_TEMP …
```

Introduces ENV['RUNNING_MINITEST_WITH_DOCKER']

---

src/api/spec/factories/comment_locks.rb
src/api/spec/features/webui/comment_locks_spec.rb

Add comment locking tests:
- on a request with comments enabled:
- on a request with comments disabled:

Comment locking tests

---

src/api/lib/tasks/dev.rake

As the notifications task performs SendEventEmailsJob, it's better called as last step in the dev task to ensure all the possible notifications from previously generated events are created.

Perform notifications task as the last step

---

src/api/app/models/project/update_from_xml_command.rb

`update_linked_projects` calls `FlagHelper.disabled_for?` which only works if the flags are persisted.

Make persistant save

---

src/api/app/views/person/token/index.xml.builder

Because when we create the token, we have to tell the token is of type=runservice, but when we ask about the tokens a user has, we get that same token as kind=service instead.
Fixes https://github.com/openSUSE/open-build-service/issues/15078

Make the token naming consistent

---

src/api/app/models/linked_project.rb
src/api/app/models/package.rb
src/api/app/models/project.rb

- LinkedProject scope to be able ignore remote project links
- Introduces update_project to explicitly avoid the update_instance_or_self trap
- Introduces check_access? instance method, the class method is doing things
we've already done while instantiating

Simplify Project.find_package

---

src/api/app/components/notification_action_description_component.rb

This way we comply with the requirements of codeclimate.
Related to #15084.

Reduce number of lines of `call` method

---

dist/functions.setup-appliance.sh

`hostname -f` didn't show full hostname with "." such as abc.site.com, it'll shows abc, this will case vist problem

[dist] fix can not get full hostname in functions such as abc.site.com

---

src/api/.rubocop_todo.yml
src/api/app/components/notification_avatars_component.rb
src/api/app/components/notification_component.html.haml
src/api/app/components/notification_component.rb
src/api/app/components/notification_excerpt_component.rb
src/api/app/components/notification_filter_component.html.haml
src/api/app/components/notification_filter_component.rb
src/api/app/components/notification_notifiable_link_component.rb
src/api/app/components/workflow_run_row_component.rb
src/api/app/components/workflow_run_status_badge_component.rb
src/api/app/controllers/webui/users/notifications_controller.rb
src/api/app/models/event/base.rb
src/api/app/models/event/workflow_run_fail.rb
src/api/app/models/event_subscription.rb
src/api/app/models/event_subscription/for_channel_form.rb
src/api/app/models/workflow_run.rb
src/api/app/queries/notifications_finder.rb
src/api/app/queries/outdated_notifications_finder/workflow_run.rb
src/api/app/services/notification_service/notifier.rb
src/api/app/services/notification_service/web_channel.rb
src/api/app/services/notified_projects.rb
src/api/lib/tasks/dev/workflows.rake
src/api/spec/models/event/workflow_run_fail_spec.rb
src/api/spec/models/workflow_run_spec.rb

Until now, users who set the SCM/CI integration with OBS had to check the workflow runs list, from time to time, to discover if some workflow runs failed.
From now on, they are going to receive notifications about the failed ones.
The subscriptions page includes the new type of event:
The new type of notifications looks like this:
**NOTES:**
- This PR covers the web channel only. The email channel will be introduced in another PR.
- There is no need to subscribe everyone to the new type of event (`Event::WorkflowRunFail`). We'll use the blog post to encourage people to subscribe so we don't overload their Notifications page.
- At the moment, only the token creator (a.k.a. executor) will receive notifications. The people the owner shared the token with won't receive notifications yet.

Get notified about failed WorkflowRuns

---

src/api/app/components/workflow_artifacts_per_step_component.rb
src/api/app/services/workflows/artifacts_collector.rb
src/api/lib/tasks/dev/workflows.rake
src/api/spec/factories/workflow_artifacts_per_step.rb
src/api/spec/services/workflows/artifacts_collector_spec.rb

Prior to this PR, we were not collecting artifacts for the `set_flag` steps. This PR collects these missing artifacts.

Collect artifacts for set flag step

---

src/api/app/controllers/webui/packages/main_controller.rb

Building the rpmlint.log binary info page (for example) crashes:
https://build.opensuse.org/projects/openSUSE:Factory/packages/telegram-desktop/repositories/standard/binaries/x86_86/rpmlint.log
That url tries to build the index action path but it's not providing the `repository_name` parameter and the Url helper fails.
Fixes #14879

Read repository_name also when bulding the binary path

---

src/api/app/services/gitlab_status_reporter.rb
src/api/app/services/scm_exception_handler.rb

This exception is thrown by httparty, the rubygem used by the Gitlab rubygem. Therefore, we catch this exception only when trying to connect to a Gitlab instance.

Catch OpenSSL::SSL::SSLError exceptions when reporting back to the SCM/CI

---

src/api/app/models/event/workflow_run_fail.rb
src/api/app/models/event_subscription/for_channel_form.rb
src/api/app/models/workflow_run.rb
src/api/app/views/event_mailer/workflow_run_fail.html.haml
src/api/app/views/event_mailer/workflow_run_fail.text.erb
src/api/spec/factories/event_subscriptions.rb
src/api/spec/mailers/event_mailer_spec.rb

Enables the email channel and sets up everything to allow users to receive email notifications regarding failed workflow runs.

Send email notifications for failed workflow runs

---

codecov.yml

It doesn't make much sense to track code coverage of rake tasks used only for development purposes. We don't plan to create tests for them.
See this comment: https://github.com/openSUSE/open-build-service/pull/15094#issuecomment-1782787726

Exclude dev rake tasks from code coverage

---

src/api/app/views/webui/user/index_actions/_change_notifications.haml
src/api/app/views/webui/users/notifications/_index_actions.html.haml

Having actions like "Manage Your Tokens" and "Manage Beta Features", it makes sense to have "Manage Your Notifications" instead of "Change Your Notifications".
Now:

Unify actions texts

---

src/api/app/components/workflow_run_detail_component.rb
src/api/lib/tasks/dev/workflows.rake
src/api/spec/components/workflow_run_detail_component_spec.rb
src/api/spec/factories/workflow_runs.rb

Show all the information available about the `Workflows Configuration File` for a `workflow_run`.
**Existing information**
- Path
- URL
**Additional information**
- File Content
If the workflow configuration file was ~received, parsed and stored by the scm service~ downloadable, it renders now the content of the file in the dedicated workflow run configuration sub-tab.
- Go to review-app or run `rake dev:test_data:create` in dev. env.
- Open any workflow run to see the content of the _Workflow Configuration_ tab (Profile > Manage Tokens > Workflow runs > click on one of the workflow runs)
- [Workflow run with ID 7](https://obs-reviewlab.opensuse.org/ncounter-workflow-config-ui/my/tokens/1/workflow_runs/7#tab-pane-workflow-configuration-tab-content7) has URL and configuration content …

Workflow_configuration: show the file content

---

codecov.yml

Fixes the previous PR https://github.com/openSUSE/open-build-service/pull/15124
According to the [documentation](https://docs.codecov.com/docs/ignoring-paths), the key is `ignore:`.

Fix expression to exclude dev rake tasks from codecov

---

src/api/Gemfile

We don't want to load them into every process.
For example, when running a spec, we don't need the `puma` gem to be loaded.
They are currently loaded here: https://github.com/openSUSE/open-build-service/blob/fea862b7704583bfaf1262a33a3409280d9bc36b/src/api/config/application.rb#L24-L30

Prevent some Ruby gems from being auto required

---

src/api/Gemfile
src/api/spec/lib/rubocop/cop/view_component/avoid_global_state_spec.rb
src/api/spec/lib/rubocop/cop/view_component/class_name_spec.rb
src/api/spec/lib/rubocop/cop/view_component/file_name_spec.rb
src/api/spec/lib/rubocop/cop/view_component/missing_preview_file_spec.rb
src/api/spec/rails_helper.rb
src/api/spec/support/rubocop.rb

Prevent RuboCop Ruby gem from being auto required

---

.github/workflows/isolated_migrations.yml
src/api/.rubocop_todo.yml
src/api/db/data/20170831143534_convert_notifications_event_payload_to_json.rb
src/api/db/migrate/20180516074538_explicitly_set_charset.rb
src/api/db/migrate/20210511201658_add_data_migrations_table.rb

I grouped the fixes for RuboCop offenses for migrations and data migrations.
The "Isolated Migrations" GitHub action was adapted to not complain when there are also changes in the linters configuration.

Autocorrect RuboCop offenses in migrations

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/queries/reviews_finder.rb

Moved out of https://github.com/openSUSE/open-build-service/pull/14318 (outdated and only parts of it still apply).
Part of cleaning up the request controller, I only plan to do this for the request workflow redesign beta endpoints.

Move logic to fetch open reviews to a finder class

---

src/api/app/components/request_decision_component.html.haml
src/api/app/components/request_decision_component.rb

Meanwhile we created a policy for the authorization logic, let's use it in the view component and remove duplicates.
Moved out of https://github.com/openSUSE/open-build-service/pull/14318 (outdated and only parts of it still apply).
Part of cleaning up the request controller, I only plan to do this for the request workflow redesign beta endpoints.

Use `revoke_request` policy in `request_decision_component`

---

src/api/.rubocop_todo.yml
src/api/spec/components/previews/write_and_preview_component_preview.rb

To test please visit `/rails/view_components/write_and_preview_component/for_message_editing` on your localhost

Add missing preview for write_and_preview_component

---

.github/workflows/isolated_migrations.yml
src/api/db/attribute_descriptions.rb
src/api/db/data/20231106165306_add_branch_skip_repositories_to_attrib_types.rb
src/api/db/data/20231107095249_add_planned_release_date_to_attrib_types.rb
src/api/db/data/20231107100650_add_enforce_revisions_in_requests_to_attrib_types.rb
src/api/db/data_schema.rb
src/api/db/seeds.rb

Add missing attribute types to `db/seeds.rb`

---

src/backend/bs_publish

createrepo 1.0.0 switched the default to zstd, however we need to preserve the backward compatibility with old clients so need to hardcode gz unless a zstd option is set.

[backend] change default back to gz for create/modifyrepo

---

src/api/spec/factories/users.rb
src/api/spec/lib/statistics_calculations_spec.rb
src/api/spec/support/database_cleaner.rb

The `first_or_create` call will never create a record because the `description` field is validated from being present.
We don't need to update the `allow_user_to_create_home_project` field to `false`  on every rspec example.
See:
- 79b5e04cb78e2feceb51779b7c8ffff08f7f53d9
- f87366b9287fdc001122c284406c21c0bdc6c429

Remove call to update Configuration in database cleaner

---

src/api/.rubocop_todo.yml
src/api/app/controllers/webui/groups_controller.rb
src/api/app/models/group.rb
src/api/spec/controllers/webui/groups_controller_spec.rb
src/api/spec/models/group_spec.rb

Fix the `replace_members` Group model method and its specs: prevent removal of previous groups users when for, at least one user of the new members to replace, there are validation failures or the user is not found.
Create a transaction when saving group details and group users in the `create` action of the Webui::GroupsController. This helps to guarantee not creating a group when there are group details validation failures, or new users validation failures or not found new users.
Adapt specs of `create` action of the Webui::GroupsController.
The fixed code was introduced in #1574.
Found while trying to address a RuboCop offense in #15186.

Fix `create` action of Webui::GroupsController
