openSUSE/open-build-service

src/api/app/models/configuration.rb

Make use of `Configuration.instance_methods` to prevent from performing a query to the database every time a  configuration parameter is accessed.
```
[1] pry(main)> Configuration.gravatar
Configuration Load (0.6ms)  SELECT `configurations`.* FROM `configurations` ORDER BY `configurations`.`id` ASC LIMIT 1
Configuration Load (0.7ms)  SELECT `configurations`.* FROM `configurations` ORDER BY `configurations`.`id` ASC LIMIT 1
Configuration Load (0.5ms)  SELECT `configurations`.* FROM `configurations` ORDER BY `configurations`.`id` ASC LIMIT 1
=> true
[2] pry(main)>
```
```
[1] pry(main)> Configuration.gravatar
Configuration Load (0.7ms)  SELECT `configurations`.* FROM `configurations` ORDER BY `configurations`.`id` ASC LIMIT 1
Configuration Load (0.5ms)  SELECT `configurations`.* FROM …
```

Don't query the database for configuration fixed fields

---

src/api/app/models/configuration.rb
src/api/public/apidocs/components/schemas/configuration.yaml

The default_tracker configuration parameter is not shown. It must be shown.
```bash
> osc -A http://localhost:3000 api '/configuration' | grep default_tracker
>
```
```bash
> osc -A http://localhost:3000 api '/configuration' | grep default_tracker
<default_tracker>bnc</default_tracker>
>
```

Fix `GET /configuration` to show default_tracker

---

src/api/app/assets/javascripts/webui/request_show_redesign/bs_request_actions.js

The dropdown can contain a long list of actions. Once it is opened, it scrolls towards the active/selected one.
We had this functionality before, it was removed by mistake in commit [a14e43e](https://github.com/openSUSE/open-build-service/pull/14164/commits/a14e43e442e8e87618c2e521ce51a1acc38d0268).

Scroll towards the current request action

---

src/backend/bs_srcserver

Some internal commands can expand to very long parameter lists (e.g. a project with many packages).  While there is no request size limit in the RFC, this can make the query string exceed common limits of many webservers and proxies. [1]
Those limits are actually very valid. To avoid exceeding those limits we move the data into the request body for the POST requests.
[1]: https://stackoverflow.com/questions/686217/maximum-on-http-header-values

[backend] use formurlencode when sending commands

---

src/api/spec/controllers/person/token_controller_spec.rb
src/api/spec/jobs/report_to_scm_job_spec.rb
src/api/spec/models/branch_package/lookup_incident_package_spec.rb
src/api/spec/models/service/name_validator_spec.rb
src/api/spec/requests/kerberos_login_spec.rb
src/api/spec/services/consistency_check_job_service/base_consistency_checker_spec.rb

The `vcr` RSpec flag is `false` by default.

Remove unneeded `vcr: false` assignments

---

src/api/app/views/webui/comment/_comment_field.html.haml

Separate comments buttons properly

---

src/api/app/components/bs_request_comment_component.html.haml

Before, when we uncollapsed the reply form, the Report link went out of place:
Now the links stay in the same place and the form opens below them:
I decided to move links to the right side to minimize the visual noise on the left, where many other elements like lines, icons and avatars are present. The right side is also a good position as it is the place where the reader's eyes usually end up when they finish reading.
- Make sure your user is in beta.
- This is  a good request to test with: https://obs-reviewlab.opensuse.org/saraycp-adjust_reply_and_report_position/request/show/15

Move Reply and Report links to the right on the redesigned request UI

---

src/api/app/controllers/trigger_controller.rb
src/api/app/controllers/trigger_workflow_controller.rb
src/api/public/apidocs/paths/trigger_operation.yaml
src/api/spec/controllers/trigger_controller_spec.rb

It makes no sense to process Workflow Tokens in the `/trigger/runservice` endpoint, so we just 404 when a request like that comes in.
Fixes #13849 
Having a Workflow Token with an id of 1, a `home:Admin` project and a `hello_world` package:
```
osc api -X POST "http://localhost:3000/trigger/runservice?id=1&project=home:Admin&package=hello_world" -a X-Obs-Signature <secret>
```
or
Using the `/apidocs/index.html#/Trigger/post_trigger__operation_`

Do not process workflow tokens in the runservice endpoint

---

src/api/.rubocop.yml
src/api/spec/policies/comment_policy_spec.rb
src/api/spec/policies/group_policy_spec.rb
src/api/spec/policies/status_message_policy_spec.rb
src/api/spec/policies/webui/status_message_policy_spec.rb

This cop is currently not recognizing the pundit rspec helpers.

Disable RSpec/RepeatedExample cop for spec/policies

---

src/api/app/assets/stylesheets/webui/comments.scss
src/api/app/assets/stylesheets/webui/timeline.scss
src/api/app/components/bs_request_activity_timeline_component.html.haml
src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/bs_request_history_element_component.html.haml
src/api/app/components/bs_request_history_element_component.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/spec/components/bs_request_activity_timeline_component_spec.rb
src/api/spec/components/bs_request_comment_component_spec.rb
src/api/spec/components/bs_request_history_element_component_spec.rb

These are the changes so far:
- Nested comments don't show the comment icon. It's displayed only once per comment thread on top of the timeline.
- The name of the commenter and the date are moved inside the comment bubble.
- The comment bubble is moved to the right side of the avatar.
- The comment bubble is more rounded and its arrow is moved to the left.
- The Report and Reply links are moved to the right side, but this comes from PR #15218.
- Any comment/message which is not part of a conversation i.e. the message sent when asking someone to review.
- doesn't have an avatar
- uses a smaller font size
-  is not displayed but can be read when hovering the file icon next to the date.
- Having `wrote` everywhere is redundant now, so it's replaced by a dash.
Please compare the following …

Distinguish conversation from other history elements

---

src/api/.jshintignore
src/api/app/assets/javascripts/webui/application.js
src/api/app/assets/javascripts/webui/request_show_redesign/chart_build_results.js
src/api/app/components/chart_component.html.haml
src/api/app/components/chart_component.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/_chart_build_results.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/config/routes/webui_routes.rb
src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_with_patchinfo/when_accepting_request/succeeds.yml
src/api/spec/cassettes/MaintenanceWorkflow/maintenance_request_without_patchinfo/when_accepting_request/succeeds.yml

**Behavior**:
- if there is no build results, the chart box is completely hidden, and the Refresh button too
- since the beginning of the page load the autorefresh returns the build results every 1 minute
- until there is no data, nothing is shown
- once there is some data, the chart **and** the Refresh button are both visible
- once the Refresh button is clicked, an on-demand refresh is triggered, meanwhile the autorefresh still continues to reload every 1 minute.

Refresh button for request chart build results

---

src/api/app/components/bs_request_comment_component.html.haml

Fixes #15278
To test it:
1. Open a bs_request show
2. Create a comment like shown in https://build.opensuse.org/request/show/1129301

Don't extend the comments beyond the timeline space

---

src/api/app/services/notification_service/notifier.rb

Fixes: #15273
It's weird because there is no subscription for a group + RSS channel in the production database.
That kind of subscription is not even possible through the WebUI.

Fix issue when creating notification with group and RSS

---

src/api/app/components/patchinfo_component.html.haml
src/api/app/components/patchinfo_component.rb
src/api/spec/components/patchinfo_component_spec.rb

Handle patchinfo tags as arrays. Otherwise, the loop crashes when there is only one element (not an array).
Include component specs.
Follow up https://github.com/openSUSE/open-build-service/pull/15257

Patchinfo component fix

---

src/api/app/assets/stylesheets/webui/timeline.scss

Fix three-dots superseded history timeline alignment

---

src/api/app/models/event_subscription/find_for_event.rb
src/api/spec/models/event_subscription/find_for_event_spec.rb

Follow up #15276.
The code crashed with the following combination:
- There is a default subscription to RSS (user or group not specified)
- There are no specific subscriptions of that group with RSS (obviously, it's not possible).
- There is an event whose receiver is a group
- That group has an email
At some point, the code returned the default subscription for RSS as a valid subscription for that receiver. That's wrong because RSS + group is not a valid combination.
You can reproduce the error by adding this test around line 201 of the notifier_spec.rb. It makes little sense to test if "something is not created because it shouldn't", that's why the test is not included in the PR. The specs for FindForEvent#subscriptions are extended to cover this corner case instead.
```
context 'test' …
```

Prevent dealing with RSS subscriptions for groups

---

src/api/db/migrate/20231130094135_create_canned_responses.rb
src/api/db/schema.rb

This adds a table for canned responses, that will be used for storing canned responses

Add canned responses table to the database

---

src/backend/bs_worker

Broken with commit 3f9614b2f230ad28d99f5f5c6f15e321d191f5b8
Also add filling in of missing attributes for productcompose reports.

[backend] fix channel/report generation for kiwi product builds

---

src/api/app/services/notification_service/notifier.rb

This is a follow up to #15290.
Now that subscription of groups to RSSs are prevented, we can now safely rely on the fact that when we deal with RSS channels, the receiver will always be a user.

Remove not needed `try` for no longer existing RSS group subscribers

---

src/api/app/components/notification_notifiable_link_component.rb
src/api/app/models/event/report_for_package.rb
src/api/app/models/event/report_for_project.rb

Include more information in notifications for deleted projects and packages.

Include more information in notifications for deleted reportables

---

src/api/app/helpers/webui/reportables_helper.rb
src/api/spec/mailers/event_mailer_spec.rb

Use `*_url` helpers instead of `*_path` helpers. `*_path` helpers don't recognize the `host` parameter to make URL's absolute.

Fix absolute URL's in link_to_reportables helper

---

src/api/db/data/20231201205533_create_email_subscriptions_for_decision_related_events.rb
src/api/db/data_schema.rb

Use a data migration to do so as all the users involved should be notified.
Follow-up #15308

Add email subscriptions for decision related events

---

src/api/app/components/notification_action_description_component.rb
src/api/app/components/notification_notifiable_link_component.rb
src/api/app/models/event/report_for_comment.rb
src/api/app/models/report.rb

For deleted comments, we don't link to the project/package/request since the comment is gone. It also clearly states that the notification is for a deleted comment.
For all comments, we show in the notification's details who wrote the comment with the `from ABC` text.

Include more information for notifications about deleted comments

---

.github/workflows/pull_request_labeler.yml

This reverts commit 3c4d983e300c9d89a8e0e96be9317d879d1caebd.
See upstream issue: https://github.com/actions/labeler/issues/712

Revert "Bump actions/labeler from 4 to 5"

---

src/backend/BSSched/Checker.pm
src/backend/bs_getbinariesproxy
src/backend/bs_sched

This is needed because the checker does not go out of scope when we do async rpcs, thus we need to release as much memory as possible.

[backend] Checker: free all caches when we finished checking a prp

---

src/api/app/controllers/webui/appeals_controller.rb

While writing the feature specs the policy use for the
AppealsController#new action was not allowing the creation of the
appeals because it was missing the appellant.

Fix the use of the appeal policy

---

src/api/app/assets/javascripts/webui/report.js
src/api/app/controllers/webui/reports_controller.rb
src/api/app/views/webui/shared/_report_modal.html.haml
src/api/spec/cassettes/Reports/reporting_a_comment_on_a_package/for_a_user_who_is_not_the_author/is_possible_to_report_the_both_the_comment_and_its_author.yml
src/api/spec/cassettes/Reports/reporting_a_comment_on_a_project/for_a_user_who_is_not_the_author/is_possible_to_report_both_the_comment_and_its_author.yml
src/api/spec/features/beta/webui/reports_spec.rb

This is an improvement over having to report a comment, then its author by going to their profile. It's simply quicker to do so now, all at once.

Report the author of a comment as well as their comment if wanted

---

src/api/app/models/report.rb
src/api/spec/policies/appeal_policy_spec.rb

Creating a report without a reportable is pointless since what would even be reported in this case? Nothing!
However after its creation, a report doesn't necessarily have a reportable if this reportable is deleted. This is why the validation is only on creation.

Enforce the presence of a reportable on a report's creation

---

src/api/app/views/notifications/build_fail.text.erb
src/api/app/views/notifications/relationship_create.text.erb
src/api/spec/cassettes/Webui_FeedsController/GET_notifications/when_fetching_build_failed_notifications/1_3_3_1.yml
src/api/spec/controllers/webui/feeds_controller_spec.rb

closes #15354
After checking production logs we found there are two missing views `build_fail` and `relationship_create`. This PR adds these two missing views

Add missing notifications rss feed views

---

src/api/public/apidocs/paths/person_register.yaml

Prevent from using a [polluted namespace](https://github.com/openSUSE/open-build-service/blob/e8901089a2eb15bc9907b257562eddda94fdf503/src/api/config/routes/api_routes.rb#L20-L22). A person "register" could exist. It is the same API endpoint as `POST /person`.
See the deprecated API endpoint in the [review-app](https://obs-reviewlab.opensuse.org/eduardoj-documentationdeprecate_person_register/apidocs/index#/Person/post_person_register).

Deprecate `POST /person/register` API endpoint

---

src/api/app/models/event_subscription/form.rb

Admin user should be able to configure all event subscription types, even if they are not participating in the corresponding beta program or do not have the moderator role themself.
How to test this (in your dev env):
1. Login as Admin user
2. Make sure you are not part of the `content_moderation` beta program (http://localhost:3000/my/beta_features)
3. The subscription form should still appear in the admin interface (http://localhost:3000/notifications)
NOTE: I might change the code that checks subscriptions for events that are associated with the content moderation beta program in another PR. I wanted to keep the scope of this PR low. So I didn't wanted to change the naming of things etc. here since there are more events (Decisions, Appeals...) that have to be handled.

Always show subscription form for report events in the admin interface

---

src/api/app/models/event/appeal_created.rb
src/api/app/models/event/base.rb
src/api/app/models/event_subscription/for_channel_form.rb
src/api/app/models/event_subscription/form.rb

Allow user (with moderator role and in the beta program) and admin (for default subscriptions) to configure subscriptions for the `Event::AppealCreated` through the webUI.
- Test as a regular user:
1. Login as a regular user
2. Go to the subscription configuration page (http://localhost:3000/my/subscriptions)
3. The form for the `Event::AppealCreated` should not appear (even if the user is part of the beta program)
- Test as a user with moderator role:
1. Login as a user with moderator role
2. Go to the subscription configuration page (http://localhost:3000/my/subscriptions)
3. The form for the `Event::AppealCreated` should appear (if the moderator is in the beta program)
- Test as admin user for default subscriptions:
1. Login as user with admin role
2. Go to the …

Add subscription form for `Event::AppealCreated` for moderators and admins

---

src/api/app/models/event/report_for_request.rb
src/api/app/models/report.rb
src/api/lib/tasks/dev/reports.rake

When a request is reported, we now get an event called `Event::ReportForRequest`.
1. Open up a development instance
2. Go into some request
3. Click on the "Report Request" link on the left.
4. Run a rails console and run this:
`Event::ReportForRequest.last`
This should get you an event:
- pointing to the reported request 
- reported by the user you were logged in before
Depends on #15370

Implement an event to detect request reporting

---

src/api/app/models/event/base.rb
src/api/app/models/event_subscription.rb
src/api/app/models/event_subscription/for_channel_form.rb
src/api/app/models/event_subscription/form.rb

Users that are participating in the content_moderation beta
program should be able to configure those subscriptions.
Admin should always be able to configure them for the defaults.

Add decision events to subscription configuration form 

---

src/api/app/models/report.rb
src/api/spec/models/report_spec.rb

To test:
Try to add a report(1) to a decision that has one or more reports that point to a different reportable than report(1)

Ensure all reports of a Decision point to the same reportable 

---

src/api/app/models/event/base.rb
src/api/app/models/event_subscription/for_channel_form.rb
src/api/app/models/event_subscription/form.rb

You can now go into [your subscriptions](https://build.opensuse.org/my/subscriptions) page and add yourself to receive events for reported requests. 
You have to be a moderator to be able to subscribe yourself, though.
1. Ensure your user has a "moderator" role.
2. Ensure your user is enrolled into the [beta program](http://localhost:3000/my/beta_features).
3. You can see it in the [review app instance](https://obs-reviewlab.opensuse.org/danidoni-allow-users-to-subscribe-to-reported-requests-events/my/subscriptions)
Depends on #15375

Allow users to subscribe to reported requests events

---

src/api/db/migrate/20231218151408_change_flipper_gates_value_to_text.rb
src/api/db/schema.rb

Upgrading the flipper rubygem to 1.1.2 version, requires running a migration (see #15364). This migration can be created through the following command:
`rails generate flipper:update`
Add this migration, as a result of running the command above, instead of requiring a manual intervention of OBS administrators.
I modified the migration:
1. adding `safety_assured` clauses, and
1. fixing one RuboCop offense.
Giving the number of database records of the table being modified (`flipper_gates`, less than 5 database records) I consider that it is safe to change the type of the column. This will block writes while the table is rewritten, but this shouldn't be a problem.

Add migration after flipper rubygem update

---

src/api/app/models/event/report_for_request.rb

This was generated while running `bundle exec rake db:migrate` on master.

Add missing model annotation for Event::ReportForRequest

---

src/api/app/queries/notifications_finder.rb

We want to include all content moderation events when fetching notifications related to reports. This is adding one which was missing.
This PR depends on #15375 for the `Event::ReportForRequest` event.

Add missing content moderation events to the notifications for reports

---

src/api/spec/controllers/source_attribute_controller_spec.rb
src/api/spec/controllers/source_controller_spec.rb
src/api/spec/controllers/source_project_config_controller_spec.rb
src/api/spec/controllers/source_project_meta_controller_spec.rb
src/api/spec/controllers/source_project_package_meta_controller_spec.rb
src/api/spec/controllers/webui/kiwi/images_controller_spec.rb
src/api/spec/factories/packages.rb
src/api/spec/jobs/issue_tracker_write_to_backend_job_spec.rb
src/api/spec/jobs/update_backend_infos_job_spec.rb
src/api/spec/models/kiwi/image_spec.rb

We already know how to develop using VCR. No need to include a comment on tests which use VCR.
Follow up to #15316.

Remove warning comments about using VCR (II)

---

src/api/app/controllers/webui/webui_controller.rb
src/api/app/helpers/webui/webui_helper.rb
src/api/app/models/concerns/configuration_constants.rb
src/api/app/models/configuration.rb
src/api/config/options.yml.example
src/api/spec/controllers/webui/webui_controller_spec.rb
src/api/spec/models/configuration_spec.rb

Everything but root_path requires auth if Configuration.anonymous is true. No need to send people to :back if it will not work. Send them to the correct login page in proxy mode or directly to root_path instead.
Fixes #15315

Redirect to login page or root if anonymous

---

src/api/app/models/local_build_statistic/for_package.rb

The backend statistics return no results (nil) in some corner cases. We better use `blank?` than `empty?` to cover both empty array and nil.
Fixes: #15404
Apart from this, we have to figure out if returning nil is ok or a regression.

Handle statistics result returning nil

---

src/api/config/initializers/airbrake.rb

When we return an ActionView::MissingTemplate exception, we developers want to be notified. This way we can fix the exception.
Related to #15354.

Don't ignore notifying ActionView::MissingTemplate

---

src/api/public/apidocs/paths/source_project_name.yaml
src/api/public/apidocs/paths/source_project_name_project_file.yaml

- [GET /source/{project_name}](https://obs-reviewlab.opensuse.org/eduardoj-documentationfix_source_project/apidocs/index#/Sources%20-%20Packages/get_source__project_name_)
- [GET /source/{project_name}/_project/{file_name}](https://obs-reviewlab.opensuse.org/eduardoj-documentationfix_source_project/apidocs/index#/Sources%20-%20Projects/get_source__project_name___project__file_name_)
- Create a project. For example: `home:user1:project1`
- Create a package inside the previous project: For example: `home:user1:project1/package1`
- Delete the project
For the first commit, the following API request returns the list of packages of a deleted project:
```
$ curl -u user1:$PASSWORD -H 'accept: application/xml; charset=utf-8' "http://localhost:3000/home:user1:project1?deleted=1"
<directory>
<entry …
```

Fix API documentation related to `/source/{project_name}...` endpoints

---

src/api/app/controllers/trigger_controller.rb
src/api/spec/cassettes/TriggerController/_rebuild/with_project_and_package_parameter/1_1_2_1.yml
src/api/spec/cassettes/TriggerController/_rebuild/with_project_parameter/1_1_3_1.yml
src/api/spec/cassettes/TriggerController/_rebuild/with_token_package/1_1_1_1.yml
src/api/spec/cassettes/TriggerController/_release/with_project_and_package_parameter/1_2_2_1.yml
src/api/spec/cassettes/TriggerController/_release/with_project_parameter/1_2_3_1.yml
src/api/spec/cassettes/TriggerController/_release/with_token_package/1_2_1_1.yml
src/api/spec/cassettes/TriggerController/_runservice/_verfiy_package_params/1_3_3_1.yml
src/api/spec/cassettes/TriggerController/_runservice/with_project_and_package_parameter/1_3_2_1.yml
src/api/spec/cassettes/TriggerController/_runservice/with_token_package/1_3_1_1.yml
src/api/spec/controllers/trigger_controller_spec.rb

This validation made `osc` throw an exception when using `osc trigger` without the `--operation` parameter over a release token.
The reason is that `osc` calls `POST /trigger/runservice` by default when the `operation` is not passed. Even if the `Token#type` is a different one.
We want to introduce this validation, but not now. We will wait until a new version of `osc` is released, with the support of the `POST /trigger` API endpoint.
Follow up to #15414.

Remove validation of token type

---

src/api/app/components/chart_component.html.haml
src/api/app/components/chart_component.rb

Organize the simplified chart_build_result_summary UI

---

CONTRIBUTING.md
README.md
Rakefile
src/api/lib/tasks/dev/minitest.rake

On systems with more recent docker versions, docker-compose may not exist as docker has a compose subcommand now.

Rake docker:build task uses docker compose subcommand

---

src/api/app/controllers/webui/package_controller.rb

The backend output of the rpmlint_log call is properly encoded. We don't need to encode it again.
Before:
```
[...]
less space and be loaded faster. This is usually done automatically at
buildtime by rpm.
Check time report (&gt;1% &amp; &gt;0.1s):
Check                            Duration (in s)   Fraction (in %)  Checked files[...]
```
After:
```
[...]
less space and be loaded faster. This is usually done automatically at
buildtime by rpm.
Check time report (>1% & >0.1s):
Check                            Duration (in s)   Fraction (in %)  Checked files
[...]
```
Fixes #7760.

Don't encode rpmlint log output

---

src/api/app/controllers/webui/package_controller.rb
src/api/app/services/rpmlint_log_extractor.rb
src/api/spec/fixtures/files/rpmlint_log_extractor_expected
src/api/spec/fixtures/files/rpmlint_log_extractor_log
src/api/spec/services/rpmlint_log_extractor_spec.rb

Some failed builds don't generate the `rpmlint.log` file.
Create a service to retrieve information about rpmlint for failed builds from the `_log` internal build file.
Introduce this change under the `request_show_redesign` beta feature.

Extract rpmlint log from build _log files

---

src/api/app/models/history_element/review.rb

This is the same we do HistoryElement::RequestReviewAdded https://github.com/openSUSE/open-build-service/blob/4a20d898a4ff69db1ebe5378591cd6450960e83f/src/api/app/models/history_element/request_review_added.rb#L33
Without this change, we were previously fetching the HistoryElement::Review record which we already had.

Fetch the review from the Review model, not HistoryElement::Review

---

src/api/app/models/history_element/review_accepted.rb

This isn't efficient at all, but right now, we don't have another way to achieve this result. It would involve a major refactor in the creation of history elements related to staging workflows.
~~This PR depends on #15495, so rebase once it has been merged.~~
Before:
Now:

Distinguish HistoryElement::ReviewAccepted for staging workflows from others

---

src/api/app/views/webui/request/beta_show_tabs/_build_status.html.haml

When there are excluded results, the text appears too close to the actual results. This PR adds a bit of spacing between those elements.
_Before_
_After_

Fix small cluttering

---

src/api/public/apidocs/paths/architectures.yaml
src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_builddepinfo.yaml
src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_package_name_jobstatus.yaml
src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_repository.yaml
src/api/public/apidocs/paths/build_project_name_repository_name_buildconfig.yaml
src/api/public/apidocs/paths/configuration.yaml
src/api/public/apidocs/paths/person.yaml
src/api/public/apidocs/paths/person_login.yaml
src/api/public/apidocs/paths/person_login_group.yaml
src/api/public/apidocs/paths/published.yaml
src/api/public/apidocs/paths/published_project_name.yaml
src/api/public/apidocs/paths/published_project_name_repository_name.yaml
src/api/public/apidocs/paths/published_project_name_repository_name_architecture_name.yaml
src/api/public/apidocs/paths/published_project_name_repository_name_architecture_name_binary_filename.yaml
src/api/public/apidocs/paths/published_project_name_repository_name_architecture_name_binary_filename_view_ymp.yaml
src/api/public/apidocs/paths/published_project_name_repository_name_view_status.yaml

The current OpenAPI schema (https://api.opensuse.org/apidocs/OBS-v2.10.50.yaml) doesn't contain valid YAML on multi-line description strings. 
This PR changes the `>` to `|` which results in valid YAML multi-line strings when building the documentation.
```yaml
...
"/architectures":
get:
summary: List all known architectures.
description: 'Get a list of all known architectures known to OBS in general.
This is not the list of architectures provided by this instance. Check the
schedulers element from the `/configuration` route for this.
'
security:
- basic_authentication: []
...
```
```yaml
...
"/architectures":
get:
summary: List all known architectures.
description: |
Get a list of all known architectures known to OBS in general.
This is not the list of architectures provided by this …
```

Fix broken YAML multi-line documentation strings

---

dist/obs-server.spec

The %pre section might fail in OBS since 15.6 if
"systemctl disable obsapidelayed.service"
returns non-zero exit code.
This is caused by using "export SYSTEMD_OFFLINE=1" in build script.

fix for %pre script for 15.6

---

src/api/app/controllers/webui/users/tokens_controller.rb
src/api/app/views/webui/users/tokens/new.html.haml

Hey Friends (yikes! like the CONTRIBUTING.md :) )
actually fixed this one #15403; 
What's wrong with the old code? 
Using the method `Token.token_type`, the class itself changes and the `form_with(@token)` use the new form class to name the params, so the `require(:token)` will throw an error.
But the problems is not always available. You need to make a wrong search on project name or package name.
So setting the type with the `write_attribute(:type)` and removing the `token_type` allow to set the :type back and render correctly the :new partial.
The fix correlated regards the default value for the `:type` in the `radio_buttons`, was hard typed with `service`.

change how to set params type to new token in set_package

---

src/backend/BSX509.pm

We already did this in the past, but since commit
617380990f447497b552f7eb85623334cde39944 passing an undef does not automatically add a NULL.

[backend] BSX509::keydata2pubkey: add a default NULL parameter for rsa

---

src/api/app/helpers/webui/reportables_helper.rb

Fixes: #15532 Fixes: #15533
Do not try to create any link if the `reportable` object is not found/does not exist anymore.

Bugfix: do not create link over a non-existing object

---

src/api/app/components/notification_notifiable_link_component.rb
src/api/app/controllers/webui/users_controller.rb

The notification bar is not available on the user page. The notification bar should be present if a user navigates to the user's profile through the notifications menu

Show notification bar on user page

---

src/api/app/helpers/webui/reportables_helper.rb
src/api/app/models/event/appeal_created.rb
src/api/app/models/event/cleared_decision.rb
src/api/app/models/event/favored_decision.rb
src/api/spec/mailers/event_mailer_spec.rb

In case the `reportable` got already deleted, in the email for `Appeal|Cleared Decision|Favored Decision` event two issues occurres:
- the subject of the email does not contain the `reportable type` due to the lack of the reported object
- the link to the reported object is not available (#15551) but there is no clue about the fact the reported object is gone
This PR addresses those two points from above:
- fetch the `reportable type` from the event `payload_key` value instead
- add a simple text message in the email body about the missing reported object

Improve event email for reportable

---

src/api/app/controllers/webui/webui_controller.rb

The current announcement and the watchlist items are not needed to be fetched in JSON requests.
Seen while working on #15537.
These requests (taken from my development environment) will not show any more for every JSON request:
```
frontend-1 | StatusMessage Load (0.5ms)  SELECT `status_messages`.* FROM `status_messages` WHERE `status_messages`.`severity` = 4 Y created_at DESC LIMIT 1
frontend-1 | ↳ app/models/status_message.rb:40:in `latest_for_current_user'
frontend-1 | StatusMessageAcknowledgement Load (0.5ms)  SELECT `status_message_acknowledgements`.* FROM `status_message_acknowledg25 AND `status_message_acknowledgements`.`user_id` = 1 LIMIT 1
frontend-1 | ↳ app/models/status_message.rb:42:in `latest_for_current_user'
frontend-1 | WatchedItem Pluck (0.4ms)  SELECT …
```

Don't fetch unneeded information for JSON requests

---

src/api/app/models/package.rb
src/api/spec/controllers/person/token_controller_spec.rb

Any token still might exist and they need to be cleaned up. Otherwise we run into a database constraint error.
Discovered by osc test suite.

[api] Fix crash on package removal

---

src/api/app/views/webui/main/_index_actions.html.haml

Some users aren't aware OBS can be used to create images. They only see this link when they enter a project page.

Add link to create a New Image to the main page

---

src/api/app/helpers/webui/user_helper.rb
src/api/app/views/webui/user/_basic_info.html.haml

Related to: #15559.
For a deleted user:
For a deleted user:

Don't show delete links for deleted users in admin pages

---

src/api/app/assets/stylesheets/webui/comments.scss
src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/comment_history_component.html.haml

Fix  #15563
The `position` of the `dropdown` is no longer `absolute`, so `top` and `left` properties are not supposed to be set.

Bugfix: adjust comment edit history dropdown alignment

---

src/api/app/helpers/webui/comment_locks_helper.rb
src/api/app/views/webui/comment/_new.html.haml
src/api/spec/cassettes/CommentLocks/on_a_request/with_comments_locked/lock_alert_for_package/shows_comment_lock_alert.yml
src/api/spec/features/webui/comment_locks_spec.rb

Prior to this PR, the comment lock alert on the package page showed the wrong message `You can remove the lock by clicking on the button below` even when a package is not locked. This PR fixes this message and points out which commendable is locked.
Notes for test: 
1. lock a project
2. go into a package in the project
3. look at the comments
4. the alert should say the project is locked

Point out which commentable is locked in the locked alert

---

src/api/app/controllers/request_controller.rb
src/api/app/lib/backend/api/issue_trackers.rb
src/api/public/apidocs/paths/request_id_cmd_diff.yaml
src/api/test/functional/request_controller_test.rb
src/backend/BSXML.pm

Usually combined with view=xml and withissues=1. Some people have tooling to allow to write some issues in request description instead of sources.
jsc#OBS-272

[api] allow to include request description issues

---

src/api/app/views/webui/comment/_content.html.haml

We show the real name next to the login in the comments on a request, but we show only the login in the comments in packages, projects, etc.
This is how it looks like in a request's comments:
This is how it looked like in a package's comments (for example):

Be consistent in how we render the username in comments

---

src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/bs_request_comment_component.rb
src/api/app/controllers/webui/users_controller.rb
src/api/app/helpers/webui/reportables_helper.rb
src/api/app/models/comment.rb
src/api/app/views/webui/user/_comments.html.haml
src/api/app/views/webui/user/_involvement_and_activity.html.haml
src/api/app/views/webui/users/show.html.haml

We're rendering the comments in a new tab under the user profile, alongside the involvement and the activity.

List all comments for a specific user

---

src/api/app/datatables/package_datatable.rb

Before, an aditional query was performed to check if a package was a link, for each package of a project.
Check if a package is a link by joining the `package_links` table into the query that retrieves the packages of a project.
These are logs from loading a project page ( http://localhost:3000/project/show/home:Admin for this example ) in a development environment:
**Before:**
```
frontend-1  |     ↳ app/controllers/webui/package_controller.rb:32:in `index'                                               
frontend-1  |     Package Load (0.8ms)  SELECT `packages`.* FROM `packages` WHERE `packages`.`id` NOT IN (SELECT `packages`.`id` FROM `packages` WHERE `packages`.`project_id` = 0) AND `packages`.`project_id` = 2 ORDER BY packages.name ASC LIMIT 50 OFFSET 0
[...]
frontend-1  |    ↳ …
```

Prevent N+1 query in project page

---

src/api/app/components/bs_request_comment_component.html.haml
src/api/app/helpers/webui/comments_helper.rb
src/api/app/views/webui/comment/_content.html.haml
src/api/spec/helpers/webui/comments_helper_spec.rb

In order to provide more context to who wrote a comment, we want to render the user role also.
This is how it looks like in the comments on a request:
And this is how it looks like in the comments on a package for example:
1. Go to https://obs-reviewlab.opensuse.org/danidoni-label-user-roles-in-comments/
2. Log in as Iggy, password 'opensuse'
3. Visit https://obs-reviewlab.opensuse.org/danidoni-label-user-roles-in-comments/request/show/1 and check how the badges look like

Show the user roles alongside the comment

---

dist/functions.setup-appliance.sh
dist/obs-server.spec
src/backend/bs_publish

According to the documentation, the correct option for createrepo_c to compress also primary/filelists/other xml files with gz compression is `--general-compress-type=gz`
Taken from `createrepo_c --help`:
```
--general-compress-type=COMPRESSION_TYPE     Which compression type to use (even for primary, filelists and other xml).
```

[backend] change default compression for createrepo to gz

---

src/api/lib/tasks/dev/reports.rake

Request #5 was failing because it was not generating a proper sourcediff, and crashing the application in development.
By adding a source and target packages, we can get the proper sourcediff.
Related to #15562

Fix test data request

---

docs/api/Makefile

We cannot create an .html file from a .xsd file which doesn't exist.

Remove reference to nonexistent .xsd files

---

src/api/app/assets/stylesheets/webui/build-results.scss
src/api/app/components/build_results_monitor_component.html.haml
src/api/app/components/build_results_monitor_component.rb
src/api/app/views/webui/shared/_build_status_badge.html.haml

This displays the build results as a table on larger viewports, so the architectures align in columns
[Screencast from 2024-01-23 11-15-18.webm](https://github.com/openSUSE/open-build-service/assets/114928900/33decba1-b30e-42cf-8a90-ef997915cfcd)

Display the build results as a table on larger viewports

---

src/api/app/assets/stylesheets/webui/diff.scss
src/api/app/controllers/webui/comments_controller.rb
src/api/app/views/webui/comment/beta/_comments_thread.html.haml

Depends on #15501 
After deleting a comment in the changes tab, there was no way to add a comment to the same line without reloading. This aims to fix the issue

Allow commenting on the same line after a comment was deleted from it

---

src/backend/BSContar.pm
src/backend/BSRepServer/Registry.pm

* support uncompressed layers
* rename create_manifest_entry to create_tar_manifest_entry
* add a create_tar_manifest_data function
* split compression <-> mime_type conversion into its own function

[backend] BSContar: more cleanups

---

src/backend/BSSched/ProjPacks.pm

We need this so that the automatic deepcheck trigger works

[backend] make expandflags:macroserial changes critical

---

src/api/app/assets/stylesheets/webui/build-results.scss
src/api/app/components/build_results_monitor_component.html.haml

Displays the monitor with a larger amount of architectures in a less broken way

Fix display of the bs_request monitor with more architectures

---

src/api/app/assets/stylesheets/webui/timeline.scss
src/api/app/components/bs_request_comment_component.html.haml

- form disalignment to the left
- comment body still visible even if in edit mode with the edit form visible
- form is now aligned to the container borders
- the comment body visibility is reverse-toggled from the edit form
The toggling visibility could have been implemented with the [Bootstrap collapse multitarget](https://getbootstrap.com/docs/5.0/components/collapse/#multiple-targets) option, but the `Cancel` button of the form edit couldn't be included in the mechanism, therefore it would have been handled via `js` eitherway. Thus, the decision was to handle both the cases (`showing` and `hiding`) via `js` anyway.

Edit comment form alignment and visibility

---

src/api/app/components/bs_request_comment_component.html.haml

This PR fixes a small spacing issue on the commenter's role badges.
This is how it looked like before:
And this is how it looks like now:

Fix the commenter's badges space issue

---

src/api/app/components/sourcediff_tab_component.rb
src/api/app/helpers/webui/request_helper.rb
src/api/app/views/webui/request/_request_header.html.haml
src/api/app/views/webui/request/changes.html.haml

Fixes #15581
This is how it looked like before
This is how it looks like now

Show the diff against the superseded request

---

src/api/app/assets/javascripts/webui/request_show_redesign/chart_build_results.js
src/api/app/components/chart_component.html.haml

*How to test this:*
1. Create a request that includes a few build results
2. You can patch the following line if the amount of repositories is to low to show the chart summary https://github.com/openSUSE/open-build-service/blob/8fcea11ebc44bc9e0a8000cebdb85d509dd35010/src/api/app/components/chart_component.html.haml#L9
3. Click on the bars in the chart and see that it links to the build result tab and applies the corresponding repository and build state filters
*Note:*
There is currently no way to customize click events directly through Chartkick (and the underlying Chart.js library). I can also not generate the url's server side in ruby and provide them through the data hash that we pass to chartkick (additional keys are simply ignored and thrown away). So I have to generate the URL on …

Link request build summary chart to build result tab

---

src/api/app/assets/stylesheets/webui/build-results.scss
src/api/app/components/build_results_monitor_component.html.haml

Let the build result sub content breathe with space

---

src/api/app/controllers/public_controller.rb
src/api/test/functional/source_controller_test.rb

This is fixing git clone operations where OBS is LFS fallback and the package got deleted.
OBS-285

[api] support source file download of deleted package for obs-lfs-ro

---

src/backend/BSSched/PublishRepo.pm

Like it should have been from the start, except that we didn't have publish flags at that time.

[backend] make singleexport a publish flag

---

docs/api/api/patchinfo.rng
src/backend/BSSched/BuildJob/Patchinfo.pm
src/backend/BSVerify.pm
src/backend/BSXML.pm

To be able collect binaries without creating update meta information.
OBS-298

[backend] patchinfo: allow to skip updateinfo.xml generation

---

src/backend/bs_publish

slepool stripped away the dot from .license directories when build with product composer (since we have no more -Media strings behind build number.

[backend] fix slepool maping for product composer naming

---

src/backend/bs_worker

Local errors lead to the job being returned with a "badhost" result. We do not want that if the job just contains outdated data.

[backend] do not treat missing packages as local error

---

src/api/app/views/webui/users/notifications/_update.js.erb

Fixes #15691
Before this PR you cannot check off a notification, and the rails log shows an error. After applying this, there is no error anymore and the notifications can be checked off.

Fix errors when updating a notification

---

src/api/app/models/event_subscription.rb

When users subscribe to new comment events as `Commenter`., I mean this:
they will receive notifications if they wrote any of the comments in the project/package/request ( commenters) but also when they were **mentioned** in any of those comments. Look at this [code](https://github.com/openSUSE/open-build-service/blob/936644bea0b4d6ae7c7227b9b920d867c1805f25/src/api/app/models/comment.rb#L106).
We need to clarify that. I propose this text:

Add more precise receiver role text for commenter

---

src/backend/bs_repserver

This makes sure that we do not get the logfile of the next job if our job is already done.

[backend] provide jobid when getting the logfile of a running job

---

src/api/app/controllers/webui/request_controller.rb

This fixes an "undefined method `reduce' for nil:NilClass" error.
The fetch has a default option for when the `:sourcediff` key does not exist, but if the sourcediff is actually nil, the reduce fails.
This PR adds a default empty array for the reduce to work.

Fix fetching a nil sourcediff

---

src/api/app/datatables/maintained_project_datatable.rb

We need the `joins` so the 'project name' the datatable looks for is matched against the `projects` table instead of the `maintained_projects` table.
Fixes #15665

Fix maintained projects datatable search

---

src/api/app/services/rpmlint_log_extractor.rb
src/api/spec/services/rpmlint_log_extractor_spec.rb

To avoid errors like "invalid byte sequence in UTF-8" when fetching the rpmlint log file.
Fixes #15700

Scrub the rpmlint log files

---

src/api/app/models/user.rb
src/api/spec/models/user_spec.rb

A piece of code no longer used since 95f73fd76da9636a5ba746217118d87f0e5d44fd

Drop useless code

---

src/api/spec/policies/comment_policy_spec.rb

~~We have to make sure the policy returns false unless it is
a admin/staff/moderator user that attempts to access the history.
Otherwise, in case of a regular user it simply doesn't
match the condition and returns true in the next line if the comment
is not soft deleted.~~
The policy was missing specs.

Add spec for the comment `history?` pundit policy 

---

docs/api/api/api.txt
src/api/app/controllers/source_controller.rb
src/api/app/models/branch_package.rb
src/api/app/models/workflow/step/branch_package_step.rb
src/api/public/apidocs/OBS-v2.10.50.yaml
src/api/public/apidocs/paths/source_fork.yaml
src/api/test/functional/source_controller_test.rb

This can be used to create a test build setup for a scmsync package based on an existing project.
The base package may or may not exist. May or may not use scmsync.
This is mainly implemented inside of BranchPackage class intentionaly, even when this is no source branch technically. But many api parts like repository setup can be shared this way.

[api] implement package fork command

---

src/api/db/migrate/20240227153505_add_decision_kind_to_canned_responses.rb
src/api/db/schema.rb

We'll need to group the canned responses by decision kind later on. The default is null for those canned responses not related to decisions.

Create migration to add decision kind to canned responses

---

src/api/spec/controllers/webui/users_controller_spec.rb

This tests the "happy path" for a moderator and ensures that a moderator cannot update another's users attributes (other then the `:blocked_from_commenting`) since this was possible before fixing it in https://github.com/openSUSE/open-build-service/pull/15702
I already created a card which suggests to split those two scenarios into separate controller methods https://trello.com/c/vUl64ZAE/94-split-update-and-blockfromcommenting-into-two-separate-controller-endpoints

Add controller specs to test moderators blocking users from commenting

---

src/api/app/assets/javascripts/webui/canned_responses.js
src/api/app/components/canned_responses_dropdown_component.html.haml
src/api/app/components/canned_responses_dropdown_component.rb
src/api/app/components/reports_modal_component.html.haml
src/api/app/components/reports_modal_component.rb
src/api/app/controllers/webui/users/canned_responses_controller.rb
src/api/app/models/canned_response.rb
src/api/app/views/webui/comment/_comment_field.html.haml
src/api/app/views/webui/users/canned_responses/edit.html.haml
src/api/app/views/webui/users/canned_responses/index.html.haml
src/api/spec/components/canned_responses_dropdown_component_spec.rb
src/api/spec/factories/canned_responses.rb
src/api/spec/features/webui/canned_responses_spec.rb

Follow-up https://github.com/openSUSE/open-build-service/pull/15703
Canned responses are used for normal comments and also for the moderator's decision reasons.
In the second case, we want to group the responses by  Cleared or Favor, to make it easier for the moderator.
For those responses which are non-decision related, the `decision_kind` column will contain a `null` in the database (default value).
In the decision form, the user sees the decision-related responses only.
In a normal comment form, the user will see the non-decision-related responses.
Creating/editing canned responses:
Using canned responses:

Handle Kind of canned responses

---

src/backend/bs_regpush

If the returned upload location points to a different host, we should not use the old authenticator and blindly send the old auth token.

[backend] bs_regpush do not reuse the authenticator for different hosts

---

dist/t/Makefile

Install git+make+gcc in openQA test
it might be missing from the base image.
[last failed test](https://openqa.opensuse.org/tests/3989948#step/rspec_webui_tests/5)

Install git+make+gcc in openQA test

---

src/api/app/components/reports_modal_component.rb

After our latest changes, users who had canned responses already, won't see them in the dropdown of the decision form. Why? because they have `decision_kind = nil` by default. This means they are considered "generic" and are only displayed in the dropdown of the normal comments.
Now we display the generic canned responses as well in the decision form. This way, users who had canned responses before the latest changes will be able to use them. We now have to recommend them to update the response to move it to the right kind.

Display all kinds of canned responses in decision dropdown

---

src/api/app/assets/javascripts/webui/application.js
src/api/app/assets/javascripts/webui/flash.js
src/api/app/assets/javascripts/webui/network.js

`AJAX` calls handle the `success` case of the request lifecycle, but they don't handle the `error` scenario often (the case when something goes wrong during the request). By design `AJAX` calls are async and silent, thus there is a chance the user cannot see if the call completed or failed eventually.
This PR introduces a global `AJAX` setting to set a default fallback in case the async request returns an error, and this is to present a message to the user about what happened.

Default ajax feedback in case of error 

---

src/api/app/mailers/event_mailer.rb
src/api/spec/mailers/event_mailer_spec.rb
src/api/test/fixtures/event_mailer/repo_delete_request
src/api/test/fixtures/event_mailer/request_event
src/api/test/fixtures/event_mailer/set_bugowner_event
src/api/test/fixtures/event_mailer/tom_declined
src/api/test/fixtures/event_mailer/tom_gets_mail_too

Nowadays this can cause problems with spam filters if the domain does not match the domain of the host the mail is sent from. Although the Internet Message Format RFC says differently...
https://www.rfc-editor.org/rfc/rfc5322#section-3.6.2

Switch From-Header in emails

---

src/api/app/views/webui/users/canned_responses/index.html.haml

To avoid ids which start with number or special character that break the UI.
Instead of validating the `title` format, we better modify the way we create the id.
Thanks @hellcp  for the suggestion.

Change DOM ids for canned responses accordions

---

src/api/app/models/canned_response.rb
src/api/db/migrate/20240307122241_make_canned_responses_title_and_content_not_null.rb
src/api/db/schema.rb

The `title` and the content should be present, it makes little sense otherwise.
For consistency, the database is updated to avoid null values. It's a safe migration according to [strong migrations](https://github.com/ankane/strong_migrations?tab=readme-ov-file#setting-not-null-on-an-existing-column).
**NOTE**: please ignore the Isolated Migrations check, these two commits should go together.

Add validations to canned responses' attributes

---

src/api/.rubocop.yml

Prevent from overlooking Rubocop offenses from this kind in other specs.

Refine exclusions for Style/MultilineBlockChain

---

src/api/app/controllers/comments_controller.rb
src/api/spec/policies/comment_policy_spec.rb

Currently there is not authorization going on, in some cases the `CommentLockingValidator` still prevents comments from being created if permission is insufficient in certain cases. But some things are not handled, for example when a user is blocked for commenting.
This should be handled on the controller level using our pundit policy.
@a-chris thanks bringing this up

Authorize comment `#create` api endpoint

---

src/backend/BSPublisher/Container.pm
src/backend/BSRekor.pm
src/backend/bs_regpush
src/backend/bs_srcserver
src/backend/examples/createrepo_rpmmd_hook.pm

We only need to query the registry about the tags we know, as we do not touch all the other ones anyway.
This also needs a change in bs_regpush as we need to extend the tag list with the cosign tags. This can be enabled by adding '--cosign' to the ps_regpush query call.

[backend] speed up container publishing with noclean

---

src/api/app/views/webui/request/_actions_details.html.haml
src/api/app/views/webui/request/_request_header.html.haml
src/api/app/views/webui/request/build_results.html.haml

It's not set in [Webui::RequestController#build_results](https://github.com/openSUSE/open-build-service/blob/b0ca06d47b8715eada4f689e1865e60c2c8bb8f7/src/api/app/controllers/webui/request_controller.rb#L292), so it's getting nil all the way down.

Removing diff_limit variable

---

src/api/spec/browser_helper.rb
src/api/spec/features/webui/maintenance_workflow_spec.rb
src/api/spec/support/wait_helpers.rb

Accepting the request may take a bit longer than 6 seconds, that is the
default timeout we have configured for Capybara operations.
We introduce a new helper to temporarily execute some code with a different timeout.
See https://github.com/teamcapybara/capybara?tab=readme-ov-file#asynchronous-javascript-ajax-and-friends for more details.

Fix maintenance workflow flaky test

---

dist/t/Makefile

Fix `dbclean` make target (in openQA-like test)
to allow to re-run `make test`

Fix dbclean make target

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/helpers/webui/request_helper.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/changes.html.haml
src/api/app/views/webui/request/mentioned_issues.html.haml
src/api/app/views/webui/request/rpm_lint.html.haml

Prepare the environment for https://github.com/openSUSE/open-build-service/pull/15794

Get rid of a useless parameter

---

src/api/.rubocop_todo.yml
src/api/app/components/diff_list_component.rb
src/api/app/components/sourcediff_tab_component.rb
src/api/app/controllers/webui/kiwi/images_controller.rb
src/api/app/controllers/webui/package_controller.rb
src/api/app/controllers/webui/packages/files_controller.rb
src/api/app/views/webui/package/_breadcrumb_items.html.haml
src/api/app/views/webui/package/_file.html.haml
src/api/app/views/webui/package/rdiff.html.haml
src/api/app/views/webui/packages/files/_breadcrumb_items.html.haml
src/api/app/views/webui/packages/files/show.html.haml
src/api/app/views/webui/packages/files/simple_show.html.haml
src/api/config/routes/webui_routes.rb
src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml
src/api/spec/cassettes/Webui_Kiwi_ImagesController/GET_import_from_package/with_a_kiwi_file/that_is_an_invalid_kiwi_file/1_1_2_2_2.yml
src/api/spec/cassettes/Webui_Kiwi_ImagesController/GET_import_from_package/with_a_kiwi_file/that_is_an_invalid_kiwi_file/redirect_to_project_package_file_path.yml
src/api/spec/cassettes/Webui_Kiwi_ImagesController/GET_import_from_package/with_a_kiwi_file/with_multiple_package_groups/with_the_same_type/1_1_2_4_1_2.yml
src/api/spec/cassettes/Webui_Kiwi_ImagesController/GET_import_from_package/with_a_kiwi_file/with_multiple_package_groups/with_the_same_type/redirect_to_project_package_file_path.yml
src/api/spec/cassettes/Webui_Kiwi_ImagesController/GET_import_from_package/with_a_kiwi_file/with_source_path/with_obsrepository/redirect_to_kiwi_image_show.yml
src/api/spec/cassettes/Webui_Kiwi_ImagesController/GET_import_from_package/with_a_kiwi_file/with_source_path/with_obsrepository_and_others/1_1_2_3_2_2.yml
src/api/spec/cassettes/Webui_Kiwi_ImagesController/GET_import_from_package/with_a_kiwi_file/with_source_path/with_obsrepository_and_others/redirect_to_project_package_file_path.yml
src/api/spec/cassettes/Webui_Packages_FilesController/POST_update/as_ajax_request/modifies_an_existing_file/1_2_1_1_1.yml
src/api/spec/cassettes/Webui_Packages_FilesController/POST_update/as_ajax_request/modifies_an_existing_file/1_2_1_1_2.yml
src/api/spec/cassettes/Webui_Packages_FilesController/POST_update/as_ajax_request/modifies_an_existing_file/1_2_1_1_3.yml
src/api/spec/cassettes/Webui_Packages_FilesController/POST_update/as_non-ajax_request/modifies_an_existing_file/1_2_2_1_1.yml
src/api/spec/controllers/webui/kiwi/images_controller_spec.rb

Move view_file into files controller

---

src/api/app/controllers/person_controller.rb
src/api/app/controllers/source_controller.rb
src/api/app/models/bs_request.rb

When reviewing code, sometimes it goes unnoticed when a method is private if it uses `private: <method_name>`  right after the method definition. On the other hand, it's more straightforward to look up private methods under the `private` keyword instead of searching `private :` all over the file.
This PR moves private methods under the `private` keyword, considered the best practice.

Move private methods after private keyword

---

src/api/app/components/diff_component.html.haml

Fixes #15695
1. Go to https://obs-reviewlab.opensuse.org/danidoni-fix-original-and-submitted-file-icons-in-submit-request-overview
2. Log in as 'Admin'
3. Open [this Submit request's changes](https://obs-reviewlab.opensuse.org/danidoni-fix-original-and-submitted-file-icons-in-submit-request-overview/request/show/4/changes) for example.
4. Click on the red icon to go to the original file.
5. Click on the green icon to go to the submitted file.

Swap the source and the target file link addresses

---

src/api/app/jobs/send_event_emails_job.rb

We can't use assume `email` is a `Mail::Message` when we rescue `StandardError`. `ActionMailer` might fail to produce the `Mail::Message` object somehow already.
- `EventMailer` produces `nil`
- `nil.deliver_now` produces `NoMethodError`
- `email.body` in `Airbrake.notify` will produce `NoMethodError` again

Handle ActionMailer producing nil

---

src/api/spec/cassettes/Requests_Submissions/submit_package/when_under_the_beta_program/submit_several_packages_at_once_against_a_factory_staging_project/shows_the_beta_version_of_the_requests_page.yml
src/api/spec/features/webui/requests/submissions_spec.rb

`bs_request.bs_request_actions.first[:name]` was returning `nil`, and that raised a warning like this one:
```
Checking for expected text of nil is confusing and/or pointless since it will always match. Please specify a string or regexp instead. /obs/src/api/spec/features/webui/requests/submissions_spec.rb:142
```
Obviously that expectation was wrong.

Fix spec warning

---

src/api/app/views/webui/request/_actions_details.html.haml

Use `.bg-body-tertiary` to set a greyish background to the dropdown header. 
Light theme:
Dark theme:
Test it here: https://obs-reviewlab.opensuse.org/saraycp-dropdown_header_bg/request/show/6/request_action/6

Set background to dropdown header

---

docs/api/api/issue_trackers.xml
src/api/db/data/20240321103332_add_savannah_bug_tracker.rb
src/api/db/data_schema.rb
src/api/db/seeds.rb
src/api/test/fixtures/issue_trackers.yml
src/api/test/functional/issue_trackers_controller_test.rb

Track issue labelled as svg#XXX to the GNU Savannah bug tracker: https://savannah.gnu.org/bugs/?XXX.
Fixes issue #13368.

Issue tracker: Add GNU savannah bug tracker.

---

src/api/app/assets/javascripts/webui/request_show_redesign/chart_build_results.js

Let the cursor be a pointer when the chart has values behind because we link the data to the `Build Results` Tab

Let the user know when to click on the build chart

---

src/api/app/components/build_results_monitor_component.html.haml

The repository status is not relevant in requests. Moreover, the badge was confusing having an icon a color that represented something that didn't match the text.
Now it looks like this:

Replace repository status with build result status

---

.github/workflows/set_warnings_about_migrations.yml

It doesn't harm if we ship data migrations together with other changes. The GitHub action won't warn in such a case.

Stop warning when data migration is shipped with other changes

---

src/api/app/components/bs_request_history_element_component.html.haml
src/api/app/models/history_element/request_review_added.rb

When the request has a review by project and that project is a staging one, we display a link to it instead of plain text.
Test with this review-app link: https://obs-reviewlab.opensuse.org/saraycp-staging_project_link/request/show/2
Or do:
- Join beta request redesign
- Add review
- Choose review by project
- Which project? A project which is a staging project already
- You'll see the new link in the conversation

Display link to staging project in conversation

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/_actions_details.html.haml
src/api/app/views/webui/request/_request_header.html.haml
src/api/app/views/webui/request/_request_tabs.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/build_results.html.haml
src/api/app/views/webui/request/changes.html.haml
src/api/app/views/webui/request/inline_comment.js.erb
src/api/app/views/webui/request/mentioned_issues.html.haml
src/api/app/views/webui/request/rpm_lint.html.haml

Depends on https://github.com/openSUSE/open-build-service/pull/15872

Compute actions count instead of using a var of the value

---

src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/_actions_details.html.haml
src/api/app/views/webui/request/_request_header.html.haml
src/api/app/views/webui/request/_request_tabs.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/build_results.html.haml
src/api/app/views/webui/request/changes.html.haml
src/api/app/views/webui/request/inline_comment.js.erb
src/api/app/views/webui/request/mentioned_issues.html.haml
src/api/app/views/webui/request/rpm_lint.html.haml

`@bs_request.bs_request_actions` is available behind the `@actions` variable: reuse it!
Depends on https://github.com/openSUSE/open-build-service/pull/15867

Reuse existing global variable

---

src/api/app/controllers/webui/request_controller.rb

Fix https://github.com/openSUSE/open-build-service/issues/15870
(typo from https://github.com/openSUSE/open-build-service/commit/38b7d36beecd403f2185be2565c8e5253b031161#diff-4240c3b55deedb4b829fef429bfc8fd6832885a1ed59928cabccd613a1494e18L537-L549)

Fix bug: pass the bs_request superseded object, not the number

---

src/api/app/controllers/webui/request_controller.rb

Fix for issue introduced in https://github.com/openSUSE/open-build-service/commit/323a5f156998906d591033be526896a232b4b7e6#diff-4240c3b55deedb4b829fef429bfc8fd6832885a1ed59928cabccd613a1494e18R11-R13 where the first `before_action` is overwritten by the second one

Fix duplicated before_action call

---

docker-compose.ha.yml
docker-compose.minitest.yml
docker-compose.sre.yml
docker-compose.yml

When running `docker compose` commands, prevent this warning from happening: "WARN ... `version` is obsolete"
See: https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-top-level-element

Remove version top-level element from `docker compose` files

---

src/api/app/components/chart_component.html.haml

Currently the click target is really small on the bars in the chart when there is a big margin between the values of the individual results (e.g. 100 Succeeding Builds and 1 Failed Build).
Using a logarithmic scale on the y-axis balances the difference on the bars in the chart.
In order to stay consistent with the ordering of the individual build results types and to distinguish the click target a little more I disabled stacking of the bars.
**With a few more repositories**

Use logarithmic scale for build result summary chart

---

src/api/config/initializers/airbrake.rb

HTTP requests with bad characters are correctly handled returning a bad request (400 code) error. We don't need to be notified about wrong HTTP requests.
Also sort elements of the array. Make it more readable and easier to find elements while inspecting the code.
Fixes #15745.

Ignore notifying `ActionController::BadRequest` errors

---

src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/notification_notifiable_link_component.rb

The notifications about comments on requests used to point to the `Changes`  tab, something which was not working since we started to load a new page per tab.
Now, the link goes to the specific comment in the conversation tab.

Scroll to the specific comment on conversation

---

src/api/app/services/action_build_results_service/chart_data_extractor.rb

Requests with multiple build flavors create duplicate entries on the build results page. This pull request implements a proposed solution to display separate entries for each multi-build flavor to resolve this issue.
Before:
After:

Make separate entries for multibuild packages

---

src/api/app/assets/javascripts/webui/request_show_redesign/add_review.js
src/api/app/components/add_review_collapsible_component.html.haml
src/api/app/components/add_review_dropdown_component.html.haml
src/api/app/components/add_review_dropdown_component.rb
src/api/app/components/bs_request_activity_timeline_component.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/beta_show_tabs/_conversation_aside.html.haml
src/api/spec/components/bs_request_activity_timeline_component_spec.rb

Based on https://github.com/openSUSE/open-build-service/pull/13748 + a fix for the N+1 queries. We already fetch the History Elements for the request timeline. Instead of querying them again for the reviews it makes more sense to filter them in memory.

Show the reviewer why their review was requested

---

src/api/app/assets/javascripts/webui/request.js
src/api/app/components/sourcediff_component.html.haml
src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/request/_changes_content.html.haml
src/api/app/views/webui/request/changes.html.haml
src/api/app/views/webui/request/request_action_changes.js.erb

Applying the common pattern: load the static/text part of the page within the main page request, send an async call right after the page load to fetch the heavy content of the page while a loading message is visible.
Visit https://obs-reviewlab.opensuse.org/ncounter-async-loading-changes/request/show/1/changes

Defer Diff Loading on Changes Tab

---

src/api/app/components/chart_component.html.haml
src/api/app/helpers/webui/buildresult_helper.rb

@saraycp I am afraid we missed this changes in https://github.com/openSUSE/open-build-service/pull/15851, right? It is for the simplified build summary in this case instead.

Replace repository status with build result status (part2)

---

src/backend/bs_repserver

That's in sync with the result you get if you request the binary list.
Fixes remote aggregates that request packages with subdirs, like some kiwi build results.

[backend] skip directories when downloading binaries with view=cpio

---

src/backend/BSSrcServer/ScmsyncDB.pm

Clone urls are usually case insensitive. This means meta may contain a different url then the emitting repo. Doing therefore the lookup case insensitive by converting it to lower case.

[backend] triggerscmsync: find matching git repo case insensitive

---

src/api/app/views/webui/shared/_loading.haml

There are cases where the `wrapper_css` local variable does not exist while rendering the partial.

Missing check condition for a local variable

---

src/api/app/assets/javascripts/webui/comment.js
src/api/app/views/webui/request/request_action_changes.js.erb

Whenever a `js` event is defined as `$('.class-name').on` the event is attached and listened only to already existing HTML objects. We need either to attach those events on the `$(document)`, or to reload them on HTML that comes later on during the lifecycle (via async calls or anything else that generates HTML) after the page load.
This issue occurs for instance on the Request beta Changes page for the inline-comment: the button `Add Comment` never gets enabled because the event `input` on the `textarea` never gets triggered thus the `validateForm` function that enables the button never get triggered too.

Reload js events on async content loaded

---

src/api/app/components/sourcediff_component.html.haml
src/api/app/components/sourcediff_component.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/models/bs_request_action.rb
src/api/app/views/webui/request/_changes_content.html.haml
src/api/spec/components/sourcediff_component_spec.rb

Fix https://github.com/openSUSE/open-build-service/issues/15916
As long as the review-app is not re-genarated, the following steps are already reflected into https://obs-reviewlab.opensuse.org/ncounter-fix-diff-to-superseded-changes/request/show/19/changes?diff_to_superseded=18
1. Go https://obs-reviewlab.opensuse.org/ncounter-fix-diff-to-superseded-changes/package/show/home:Admin/hello_world
2. Branch the package
3. Change some lines in README.txt and save
4. Submit the package (it creates a new submit request)
5. Go back to the branched package and change few more lines in the README.txt again
6. Submit the package again and checking that the submit request supersedes the previous one (a flag to be marked while creating the submit request)
7. Visit the latest submit request page at the …

Keep track of diff_to_superseded parameter in all the cases

---

src/api/public/apidocs/paths/source_project_name_package_name_cmd_branch.yaml

Add missing parameters for `/source/{project_name}/{package_name}?cmd=branch`
as used by `osc branch -f -r 123 ...`
https://github.com/openSUSE/osc/blob/ec363bb/osc/core.py#L6138

apidocs: Add missing params for branch

---

src/api/app/components/workflow_run_filter_component.html.haml
src/api/app/views/webui/distributions/new.html.haml
src/api/app/views/webui/main/_system_status.html.haml
src/api/app/views/webui/shared/_info_popover.haml

A partial to reuse the same template for the question-mark-info-icon-popover.
This PR standardize all the occurrences into one partial template, plus it moves the icon from `fa` to `fa-regular`, that means it moves from
to the following instances: 
---
---

Info popover partial

---

src/api/app/controllers/webui/package_controller.rb
src/api/app/views/webui/package/_file.html.haml
src/api/spec/cassettes/Packages/Viewing_package_with_older_revision/contains_file_from_revision_including_the_revision_parameter.yml
src/api/spec/cassettes/Packages/Viewing_package_with_older_revision/does_not_display_delete_buttons_for_files.yml
src/api/spec/features/webui/packages_spec.rb

We were missing `srcmd5` from the views in case we are displaying a revision. We need it to appear in links in order to link to the right file version. This also removes the delete file link from older revisions.
Fixes #15857

Include revision in the file url

---

src/api/app/models/workflow/step/set_flags.rb
src/api/spec/models/workflow/step/set_flags_step_spec.rb

Fixes #14978.
Before, we only call the `store` method a project or a package when a flag was added. This prevented the backend from starting new builds when a flag was updated.
From now on, call the `store` method when a flag is updated. Therefore, the backend will start new builds.

Store a project definition when a flag is updated

---

src/api/app/assets/stylesheets/webui/colors.scss
src/api/app/assets/stylesheets/webui/mixin.scss

https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder#color_contrast
https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder#change_placeholder_appearance

Enhance the visual difference from placeholder to real input value

---

src/backend/bs_repserver

When doing a copybuild we clobber the arch to 'signer' if something needs to be signed. When we do delayed linking and we want to send the resume, we must use the original architecture.

[backend] do not send resumeproject events to the signer

---

src/api/app/components/workflow_run_filter_component.html.haml

Add `e.g.` to clarify it's a placeholder example, not a real value

Better placeholder text

---

src/api/app/controllers/webui/package_controller.rb
src/api/app/lib/backend/api/sources/package.rb
src/api/app/models/package.rb
src/api/app/views/webui/package/revisions.html.haml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_not_passing_the_rev_parameter/and_passing_the_page_parameter/returns_the_paginated_revisions_for_the_page_parameter_s_value.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_not_passing_the_rev_parameter/and_passing_the_show_all_parameter/returns_revisions_without_pagination.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_not_passing_the_rev_parameter/returns_revisions_with_the_default_pagination.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_passing_the_rev_parameter/and_passing_the_page_parameter/returns_the_paginated_revisions_for_the_page_parameter_s_value.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_passing_the_rev_parameter/and_passing_the_show_all_parameter/returns_revisions_up_to_rev_parameter_s_value_without_pagination.yml
src/api/spec/cassettes/Webui_PackageController/GET_revisions/with_source_access/when_passing_the_rev_parameter/returns_revisions_up_to_rev_parameter_s_value_with_the_default_pagination.yml
src/api/spec/controllers/webui/package_controller_spec.rb

This removes all the caching we did for revisions, replacing it with directly fetching revisions from the backend. Despite the lack of caching, this is faster, since we always fetch just the revisions we need while we need them.
To test this:
1. Visit the package page and check if the revision element is correct
2. Visit the package revisions page and check if the revisions are correct
Fixes #13866

Eliminate caching of revisions and fetch them directly from the backend

---

src/api/app/views/webui/package/update.js.haml
src/api/app/views/webui/project/update.js.haml
src/api/spec/features/webui/packages_spec.rb
src/api/spec/features/webui/projects_spec.rb

When updating the title within an AJAX call, it crashed when the title contained quotes, like `My "new" title`. Escaping the title was missing.
Fixes: #15694

Escape project and package title

---

src/api/app/components/notification_component.rb
src/api/spec/components/notification_component_spec.rb
src/api/spec/factories/notification.rb

Fixes: #15967
The notification about a _new relationship with a package_ displayed the wrong icon. For the _relationship with a project_, it was ok.
The relationship notifications shouldn't take the `notifiable_type` into account, all of them (for project or package) will have the same icon.

Use the proper icon for relationship notifications

---

src/api/app/models/workflow/step/set_flags.rb

Before, we stored (performed one call to the backend) a project or a package for every flag set with the SCM/CI integration set_flag step.
From now on, we store only once for every single project or package.
Seen after working on #15951.

SCM/CI: Improve storing projects and packages for setting flags

---

src/api/app/assets/stylesheets/webui/package-attributes.scss

|Before|After|
|:---|:---|
|![Screenshot from 2024-04-15 12-25-30](https://github.com/openSUSE/open-build-service/assets/114928900/b8d04ff3-a1fe-48c9-b3ea-3777ea985af4)|![Screenshot from 2024-04-15 12-25-15](https://github.com/openSUSE/open-build-service/assets/114928900/ab767ac0-3ec5-4ab3-a7b7-4dd62fdb7a91)|
Fixes #15607

Make the attribute values on dark theme

---

src/api/app/helpers/webui/markdown_helper.rb

Fixes #8049.
For reviewers: https://obs-reviewlab.opensuse.org/eduardoj-fixissue_8049/request/show/16#comment-10

Render text indented by four spaces as code

---

src/api/app/models/branch_package.rb

When only the source is specified, pointing to an extended package name, the release name was ignored. This leaded to double extended package names.

[api] fix special case in branch handling

---

src/api/app/controllers/webui/global_feature_toggles_controller.rb
src/api/app/views/layouts/webui/_places.html.haml
src/api/app/views/webui/configuration/_tabs.html.haml
src/api/app/views/webui/global_feature_toggles/_breadcrumb_items.html.haml
src/api/app/views/webui/global_feature_toggles/index.html.haml
src/api/config/routes/webui.rb

Fixes: #14417
For admins, the Feature Toggle link is moved to a new tab inside Configuration.
Staff users need to use the link but don't have access to Configuration. Therefore, the link stays in the same place for them but uses a clearer text "_Global Feature Toggles_" and opens a confirmation message.
In the future, we could have a section similar to Configuration but only for Staff, something like "Staff Global Settings" to include all the global actions they can do. Right now, it's not worth doing so, just to include the link to Flipper dashboard.

Avoid confusion with Feature Toggles link

---

src/api/app/models/canned_response.rb
src/api/db/migrate/20240418155847_add_decision_type_to_canned_response.rb
src/api/db/schema.rb

This is the first step to rename `decision_kind` to `decision_type` in the table `canned_responses`.
This pull request is safe to merge. Following pull requests will address the next steps described in [renaming a column](https://github.com/ankane/strong_migrations?tab=readme-ov-file#good-2).

Add `decision_type` column to canned responses

---

src/api/public/apidocs/OBS-v2.10.50.yaml
src/api/public/apidocs/paths/source_project_name_project_history.yaml

Documents the project _history endpoint that is used to retrieve history list of a project and its meta

Document project history endpoint

---

src/api/.rubocop_todo.yml
src/api/app/controllers/webui/packages/binaries_controller.rb
src/api/app/lib/backend/api/build_results/binaries.rb
src/api/app/views/webui/packages/binaries/_deps.html.haml
src/api/app/views/webui/packages/binaries/_fileinfo.html.haml
src/api/config/routes/webui.rb

Fixes #613
This displays a list of files inside of a built binary.
It uses datatables, to not slow down the rest of the page.

Display a list of files included in the binary

---

src/api/app/components/workflow_run_filter_component.rb
src/api/app/controllers/webui/workflow_runs_controller.rb
src/api/app/views/webui/workflow_runs/index.html.haml

Fix computing the counts of WorkflowRuns in the filters: do it over the full set of filtered entries, not only on the visible page.

Fix filter counts: consider the full set, not the paginated one

---

src/api/app/controllers/webui/packages/badge_controller.rb

Fixes https://github.com/openSUSE/open-build-service/issues/15427
The issue: when using the flag `lastbuild = true` the `buildresults` contains (among the rest of builds) also the last known build of the disabled repositories/architectures. If it occurs that one of the disabled build failed the last time, this makes the set of builds to contain a `failed` one, thus the badge reflects that. By discarding the disabled ones the badge reflects only the status of the current active set of builds.
E.g.:
- enable build for `15.5` and `SLE_11_SP4`
- say `15.5` build succeeded
- say `SLE_11_SP4` build failed
- the badge reflects the status: `failed`
- disable the build for `SLE_11_SP4`
- the only enabled build is for `15.5` which is succeeding at the moment
- **Before**: the badge reports a build …

Consider only current build results for the badge

---

src/api/app/controllers/webui/users/canned_responses_controller.rb
src/api/db/data/20240419092811_backfill_decision_type_in_canned_responses.rb
src/api/db/data_schema.rb

To be deployed after #16016. DO NOT MERGE.
TODO:

Fill `decision_type` from canned responses with data

---

src/api/app/assets/stylesheets/webui/links.scss
src/api/app/views/webui/comment/_reply.html.haml

The Report button used dark color for the button line and text, which is incompatible with the dark mode. Instead of changing it to use black over white and white over dark, I propose to use the warning color (yellow).
Using the same color in both modes can help users to match the color and the concept of reports, not only because of the consistent button but because the links to reports are also yellow (warning).

Set warning color to Report button

---

src/api/app/components/canned_responses_dropdown_component.html.haml
src/api/app/components/canned_responses_dropdown_component.rb
src/api/app/components/reports_modal_component.rb
src/api/app/controllers/webui/users/canned_responses_controller.rb
src/api/app/models/canned_response.rb
src/api/app/views/webui/comment/_comment_field.html.haml
src/api/app/views/webui/users/canned_responses/edit.html.haml
src/api/app/views/webui/users/canned_responses/index.html.haml
src/api/spec/components/canned_responses_dropdown_component_spec.rb
src/api/spec/controllers/webui/users/canned_responses_controller_spec.rb
src/api/spec/factories/canned_responses.rb
src/api/spec/features/webui/canned_responses_spec.rb

In the code related to canned responses, using the term `kind` doesn't make sense since we start using `Decision#type`. We rename all the related terms.
~DO NOT MERGE. This PR is based on  #16017, which should be deployed before we merge these changes.~

Replace kind with type

---

src/api/app/controllers/webui/decisions_controller.rb
src/api/app/models/decision.rb

Follow up to #16008. Should only be deployed after everything from other PRs is deployed

Get rid of kind from the decision model

---

src/api/app/components/notification_excerpt_component.rb
src/api/app/models/canned_response.rb
src/api/app/models/decision.rb
src/api/app/models/decision_favored_with_delete_request.rb
src/api/app/policies/decision_favored_with_delete_request_policy.rb
src/api/spec/factories/decision_favored_with_delete_request.rb
src/api/spec/models/decision_favored_with_delete_request_spec.rb

When someone reports a Package or a Project and a moderator favors the report, it can additionally create a Delete request for that offending Package or Project.

Implement Favor Decision and create a Delete Request

---

src/api/app/models/blocked_user.rb
src/api/db/migrate/20240423073041_create_blocked_users.rb
src/api/db/schema.rb

Introduces a database table for associating users with whoever they block. We use this for creating associations between users. This way a user can block multiple users.

Create a database table for user blocks

---

src/api/app/views/webui/request/_patchinfo_details.html.haml
src/api/app/views/webui/request/beta_show.html.haml

The source project for maintenance release requests gets deleted in many cases after it is accepted. Therefore we
have to fetch the `patchinfo` from the target in those cases. We also should handle the case of a removed source and target to prevent nil exceptions.
Fixes #16030 
**AFTER**
1. Run `rake dev:test_data:create` in your dev env
2. Navigate to project `openSUSE:Leap:15.4:Update` and add `repository_1` to the project repositories (its missing, and required in order to accept the release request... I will fix this in another PR)
3. Navigate to project `openSUSE:Backports:SLE-15-SP3:Update` and add `repository_2` to the project repositories (same issue as point 2)
4. Navigate to the maintenance release request http://localhost:3000/request/show/12
5. Accept the …

Handle deleted patchinfos in request workflow beta

---

src/api/app/models/canned_response.rb
src/api/db/data/20240419092811_backfill_decision_type_in_canned_responses.rb
src/api/db/migrate/20240424141833_remove_decision_kind_from_canned_responses.rb
src/api/db/schema.rb

Drop the column from the database.
Can't be merged until PR #16015 is deployed in. ~Same staff in IBS, because the column should exist to do the backfill first.~

Remove canned response `decision_kind`

---

src/api/app/components/notification_excerpt_component.rb
src/api/app/models/canned_response.rb
src/api/app/models/decision.rb
src/api/app/models/decision_favored_with_user_commenting_restriction.rb
src/api/app/policies/decision_favored_with_user_commenting_restriction_policy.rb

The moderators decide to favor the report and block the user from commenting

Implement favor decision and block user

---

src/api/app/models/decision.rb
src/api/app/models/decision_cleared.rb
src/api/app/models/decision_favored.rb
src/api/app/models/decision_favored_with_comment_moderation.rb
src/api/app/models/decision_favored_with_delete_request.rb
src/api/app/models/decision_favored_with_user_deletion.rb
src/api/db/data/20240417122944_set_the_decision_type_from_decision_kind.rb
src/api/db/migrate/20240425084914_remove_kind_from_decision.rb
src/api/db/schema.rb

Gets rid of the kind column from this table. Follows the strong migrations guidelines

Remove kind column from the decisions table

---

src/api/.rubocop_todo.yml
src/api/app/controllers/webui/comments_controller.rb
src/api/app/models/report.rb
src/api/app/policies/comment_lock_policy.rb
src/api/app/policies/comment_policy.rb
src/api/app/policies/report_policy.rb
src/api/app/views/webui/reports/show.html.haml
src/api/spec/factories/comments.rb
src/api/spec/policies/comment_lock_policy_spec.rb
src/api/spec/policies/comment_policy_spec.rb
src/api/spec/policies/report_policy_spec.rb

The new report show page now includes the possibility to add comments.
It's a private conversation between moderators/admins/staff/reporter, they all should be free to comment at any time, so we shouldn't allow reports' comments to be locked.

Comments on reports

---

src/api/lib/obsapi/markdown_renderer.rb
src/api/spec/helpers/webui/markdown_helper_spec.rb

Fixes #13513
To verify:
1. Create a comment that includes a string that would be interpreted as markdown (ie. `_test_`) preceded with `@` to create a mention
2. It will correctly render the username inside of the mention

Don't render markdown inside the user mention

---

.gitignore
dist/obs-server.spec
src/api/Makefile
src/api/app/controllers/webui/webui_controller.rb
src/api/config/application.rb
src/api/config/environments/development.rb
src/api/config/environments/production.rb
src/api/config/environments/test.rb
src/api/config/storage.yml
src/api/db/migrate/20240425122946_create_active_storage_tables.active_storage.rb
src/api/db/schema.rb

Allows upload of various images to be used in the frontend. Following https://edgeguides.rubyonrails.org/active_storage_overview.html

Install activestorage into OBS

---

src/api/app/views/webui/reports/show.html.haml

We call the `link_to_reportables` helper on the report show view. This throws an `nil` exception when the reportable is deleted, since the `reportable_type` gets nullified as well. `link_to_reportable` works in on the email notification since the `reportable_type` is still available from the event payload, but we cannot retrieve it from the report record.
Fixes #16062

Do not call `link_to_reportable` if reportable does not exist

---

src/api/app/assets/javascripts/webui/requests_table.js

Fix #16043.
For reference: https://datatables.net/reference/option/columns.responsivePriority
After the changes:

Define a priority for responsive columns

---

src/api/app/components/notification_excerpt_component.rb

Depends on #16040 
This is how it looked like before:

Show the reason in the notification excerpt for the new decision favored types

---

src/backend/BSSched/PublishRepo.pm

Writing the .archsync file may crash the scheduler otherwise.

[backend] PublishRepo: make sure that the :repo directory exists

---

src/backend/bs_repserver

The included files need to be part of the cpio archive for this to work.

[backend] bs_repserver: implement support for rpm's %include statement

---

src/api/app/controllers/webui/package_controller.rb
src/api/app/controllers/webui/project_controller.rb
src/api/app/controllers/webui/reports_controller.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/controllers/webui/users_controller.rb

There is no need to block users from viewing content when
someone is sharing a link from his notifications with the
`notification_id` attached as a query param. The `notification_id`
query param is used to render the notification toolbar for an
authorized users. If someone without authorization is using the
same link, we should simply not render the toolbar, but still show
the content.

Handle `notification_id` query param and notifications toolbar gracefully

---

src/api/app/models/event/base.rb
src/api/app/models/event/build_fail.rb
src/api/app/models/event/comment_for_package.rb
src/api/app/models/event/comment_for_project.rb
src/api/app/models/event/comment_for_request.rb
src/api/app/models/event/request.rb
src/api/app/models/event/request_create.rb
src/api/app/models/event/request_statechange.rb
src/api/app/models/event/review_changed.rb
src/api/app/models/event_subscription.rb
src/api/app/models/event_subscription/for_event_form.rb
src/api/db/data/20240507120255_rename_project_receiver_roles_in_event_subscriptions.rb
src/api/db/data_schema.rb
src/api/spec/db/data/generate_web_notifications_spec.rb
src/api/spec/features/webui/subscriptions_spec.rb
src/api/spec/models/event/base_spec.rb
src/api/spec/models/event_subscription/find_for_event_spec.rb
src/api/spec/models/event_subscription/for_event_form_spec.rb

This is the first step for renaming the following receiver roles:
- `watcher` to `project_watcher`
- `source_watcher` to `source_project_watcher`
- `target_watcher` to `target_project_watcher`

Introduce new names of project receiver roles

---

src/api/app/models/event/base.rb
src/api/app/models/event/build_fail.rb
src/api/app/models/event/comment_for_package.rb
src/api/app/models/event/comment_for_project.rb
src/api/app/models/event/comment_for_request.rb
src/api/app/models/event/request.rb
src/api/app/models/event/request_create.rb
src/api/app/models/event/request_statechange.rb
src/api/app/models/event/review_changed.rb
src/api/app/models/event_subscription.rb
src/api/app/models/event_subscription/for_event_form.rb

This is the second and last step for renaming the following receiver roles:
- `watcher` to `project_watcher`
- `source_watcher` to `source_project_watcher`
- `target_watcher` to `target_project_watcher`

Drop obsolete watcher receiver roles

---

src/api/app/models/user.rb

Reduce the amount of tables that have to be materialized for getting involved packages / requests.

Speed up query

---

src/api/app/controllers/request_controller.rb
src/api/app/controllers/webui/project_controller.rb
src/api/app/models/bs_request.rb
src/api/app/models/bs_request/data_table/find_for_package_query.rb
src/api/app/models/bs_request/data_table/find_for_project_query.rb
src/api/app/models/group.rb

This is the first step of a series of refactorings where queries to BsRequest will be improved and more fine grained.

Drop `find_for` BsRequest scope

---

src/api/app/datatables/project_datatable.rb
src/api/app/models/project.rb

Craft with a scope the join condition of projects and values. This prevent N+1 queries.
Also, remove the loop to render more than one value for the OBS:QualityCategory attribute. This attribute can only keep one value.
The last query (`SELECT attrib_values.* FROM attrib_values INNER JOIN...`) is repeated 25 times.
```
Project Load (0.7ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`id` != 0 AND NOT (name rlike '^home:.+') ORDER BY projects.name ASC LIMIT 25 OFFSET 0
↳ app/datatables/project_datatable.rb:33:in `map'
AttribValue Load (0.5ms)  SELECT `attrib_values`.* FROM `attrib_values` INNER JOIN `attribs` ON `attribs`.`id` = `attrib_values`.`attrib_id` INNER JOIN `attrib_types` ON `attrib_types`.`id` = `attribs`.`attrib_type_id` INNER JOIN `attrib_namespaces` ON …
```

Fix N+1 queries fetching all projects

---

src/api/app/controllers/person/notifications_controller.rb
src/api/public/apidocs/paths/my_notifications.yaml

Try the following endpoints in your development environment:
- http://localhost:3000/my/notifications
- http://localhost:3000/my/notifications?notifications_type
- http://localhost:3000/my/notifications?notifications_type=INVALID_FILTER
- http://localhost:3000/my/notifications?notifications_type=unread

Display unread notifications through the API

---

src/api/app/helpers/webui/user_helper.rb

When `::Configuration.first` is used, it results adding this string to the cache key: `/configurations/1`
Removing this part of the cache key prevents from doing a query to return something which doesn't change after an update of the configuration singleton record.
Logs after browsing http://localhost:3000/users :
```
User Load (0.5ms)  SELECT `users`.`id`, `users`.`login`, `users`.`email`, `users`.`state`, `users`.`realname`, `users`.`owner_id`, `users`.`updated_at`, `users`.`ignore_auth_services` FROM `users` WHERE `users`.`login` != '_nobody_' ORDER BY users.login ASC LIMIT 50 OFFSET 0
↳ app/datatables/user_configuration_datatable.rb:22:in `map'
CACHE Configuration Load (0.1ms)  SELECT `configurations`.* FROM `configurations` ORDER BY `configurations`.`id` ASC LIMIT 1
↳ …
```

Remove unused cache key section

---

src/api/app/controllers/configurations_controller.rb
src/api/app/controllers/public_controller.rb
src/api/app/controllers/webui/code_of_conduct_controller.rb
src/api/app/controllers/webui/feeds_controller.rb
src/api/app/controllers/webui/webui_controller.rb
src/api/app/mailers/admin_mailer.rb
src/api/app/mailers/event_mailer.rb
src/api/app/models/configuration.rb
src/api/app/models/project/remote_url.rb
src/api/app/policies/webui/user_policy.rb
src/api/spec/factories/users.rb
src/api/spec/models/user_spec.rb
src/api/spec/policies/webui/user_policy_spec.rb

Instead of querying the database every time a configuration parameter is read, we make all methods of the Configuration class to pass internally through a new `fetch` method which retrieves the Configuration singleton record from the cache.
Follow up to #16123.

Introduce cache for singleton record of Configuration

---

src/api/.rubocop.yml
src/api/.rubocop_todo.yml
src/api/db/migrate/20240513154336_remove_watched_projects.rb
src/api/db/schema.rb

Since a while, we are using watched_items table to store the Watchlist. It is safe to remove the watched_projects table already.

Remove watched_projects table

---

src/api/app/views/person/notifications/_notification.xml.builder

We still have to decide a format of a notification rendered by the API, in XML. But still this change prevents from showing empty XML elements.
Related to #16135.
http://localhost:3000/my/notifications
```
[...]
<notification id="18">
<title>Build Service Notification</title>
<event_type>relationship_create</event_type>
<comment/>
<description/>
<state/>
<when/>
<who>Iggy</who>
<request_number/>
</notification>
<notification id="14">
<title>Build Service Notification</title>
<event_type>report_for_comment</event_type>
<comment/>
<description/>
<state/>
<when/>
<who/>
<request_number/>
</notification>
<notification id="15">
<title>Workflow run failed on Pull request</title>
<event_type>workflow_run_fail</event_type>
<comment/>
<description/>
<state/>
<when/>
<who/>
<request_number/> …
```

Improve rendering of notifications API

---

src/api/db/migrate/20240513154336_remove_watched_projects.rb

Removing the table implies removing the foreign key as well. There is no need to do it explicitly.
We had issues in deployment as the foreign key wasn't in the database for some reason.

Get rid of unnecessary remove_foreign_key

---

src/backend/BSPublisher/Container.pm
src/backend/bs_regpush

We can use the last result in the query by using the "If-None-Match" http header in the manifest request.

[backend] speed up registry query by storing the last result

---

src/api/app/controllers/person/notifications_controller.rb
src/api/public/apidocs/paths/my_notifications.yaml

Make it possible to use the same filter values defined in the Web-UI for the API.
Related to #16135.
http://localhost:3000/my/notifications?notifications_type=relationships_created
```
<status code="bad_request">
<summary>Filter not supported</summary>
</status>
```
```
<notifications count="1">
<total_pages>1</total_pages>
<current_page>1</current_page>
<notification id="18">
<title>Build Service Notification</title>
<event_type>relationship_create</event_type>
<comment/>
<description/>
<state/>
<when/>
<who>Iggy</who>
<request_number/>
</notification>
</notifications>
```

 Extend types used to filter notifications with the API

---

src/api/db/migrate/20240516133632_add_missing_indexes_to_notifications.rb
src/api/db/schema.rb

They will improve the several queries performed when browsing the notifications page.
I realized these indexes were missing after reviewing #16143.

Add missing indexes in table notifications

---

src/api/test/fixtures/flags.yml
src/backend/BSSched/Checker.pm

This just sets the default for the build flag, you can still enable it again in the project meta data.

[backend] disable builds for maintenance release projects

---

src/api/app/models/notification.rb

Fix notifications filters. Add missing `unread` scope

---

docs/api/api/patchinfo.rng
src/backend/BSSched/BuildJob/Patchinfo.pm
src/backend/BSXML.pm
src/backend/bs_publish

We allow to specify an embargo date in a _patchinfo. This gets also tansfered to internal updateinfo.xml files, but gets stripped at publish time.
It is up to tooling like product-composer to deal with the data.

[backend] allow to specify an embargo in _patchinfo

---

src/api/app/controllers/webui/users/notifications_controller.rb

After the latest changes related to notifications, the oldest notifications were displayed at the top of the list. It's time to make it descending again.

Sort notifications in descending order again

---

src/backend/bs_publish

mapslepool missed main repository, we match now for a suffix of any binary architecture.

[backend] bs_publish: fix mapslepool for product composer

---

src/api/app/models/event/build.rb
src/api/app/models/event/comment_event.rb
src/api/app/models/event/relationship.rb
src/api/app/models/event/relationship_create.rb
src/api/app/models/event/relationship_delete.rb
src/api/app/models/event/report.rb
src/api/app/models/event/report_for_comment.rb
src/api/app/models/event/report_for_package.rb
src/api/app/models/event/report_for_project.rb
src/api/app/models/event/report_for_request.rb
src/api/app/models/event/report_for_user.rb
src/api/app/models/event/request.rb

Every subscribable `Event` has its own `subject` (for RSS and Email) implementation.

Missing event subject

---

src/api/app/models/configuration.rb

We already have another means for updating the configuration of an instance: the API and the Web-UI.
This method was created here: 6ff4d16dd4bf97386e99d9c9b44ac6a28b734fd6 and stopped from being used here: ec1f621bb76b2102c001b34ae4edc2dbc94bf189.

Removed unused method in Configuration model

---

src/api/.rubocop_todo.yml
src/api/app/controllers/webui/feeds_controller.rb
src/api/app/jobs/status_history_rescaler_job.rb
src/api/app/models/bs_request.rb
src/api/app/models/notification.rb
src/api/app/models/project_log_entry.rb
src/api/db/data/20200326221616_regenerate_notifications.rb

Fix Rubocop offense Rails/WhereRange

---

src/api/app/assets/stylesheets/webui/requests.scss
src/api/app/components/bs_request_state_badge_component.rb

Applies to both declined and revoked requests. Pictured below are declined requests
|Before|After|
|:---|:---|
|![Screenshot from 2024-05-22 11-48-57](https://github.com/openSUSE/open-build-service/assets/114928900/d015f293-4ee1-435d-8c24-f9531ddc1d88)|![Screenshot from 2024-05-22 11-48-02](https://github.com/openSUSE/open-build-service/assets/114928900/c7401d7e-bf49-4e02-b6ca-c17f28a4e21b)|
|![Screenshot from 2024-05-22 11-49-12](https://github.com/openSUSE/open-build-service/assets/114928900/569c470f-582c-4dab-a77c-5b6d77d16a62)|![Screenshot from 2024-05-22 11-49-26](https://github.com/openSUSE/open-build-service/assets/114928900/f48f201a-de58-4408-bd21-49a441926cf0)|
This is meant to replicate the feel of https://fontawesome.com/icons/code-pull-request-closed, which we can't use since …

Display a nicer icon for closed requests

---

src/api/app/models/event/request.rb
src/api/test/functional/maintenance_test.rb

The payload hash uses strings as keys, not symbols.

Fix how we access payload in Event::Request

---

src/api/app/components/sign_up_component.html.haml
src/api/app/components/sign_up_component.rb
src/api/app/helpers/webui/user_helper.rb
src/api/app/models/concerns/configuration_constants.rb
src/api/app/models/configuration.rb
src/api/app/views/webui/users/edit.html.haml
src/api/spec/models/configuration_spec.rb

We don't need to retrieve the values stored in the singleton record of the table `configurations` in the database for none of the `ldap_enabled?`, `proxy_auth_mode_enabled?` and `amqp_namespace` methods.
Moving each method to the class methods section prevents from performing unneeded database queries.
Taking the `home:Admin` project page as an example, browsing http://localhost:3000/project/show/home:Admin and taking a look at the frontend log resulted in:
- 3 direct SQL queries to the database:
```
Configuration Load (0.5ms)  SELECT `configurations`.* FROM `configurations` ORDER BY `configurations`.`id` ASC LIMIT 1
```
- 10 cache hits:
```
CACHE Configuration Load (0.1ms)  SELECT `configurations`.* FROM `configurations` ORDER BY `configurations`.`id` ASC LIMIT 1
```
Browsing …

Move configuration methods to class methods

---

src/backend/BSPublisher/Container.pm
src/backend/BSPublisher/Registry.pm
src/backend/bs_publish

We used to read them into memory instead of creating a hard link.

[backend] handle container provenance files like the other attestations

---

src/api/app/models/configuration.rb
src/api/spec/factories/users.rb

Prevent from performing a query to the database to check for an update on the configuration singleton record.

Invalidate configuration cache after update

---

src/api/app/components/notification_action_bar_component.rb
src/api/app/components/notification_filter_component.html.haml
src/api/app/components/notification_filter_component.rb
src/api/app/components/notification_filter_link_component.rb
src/api/app/components/notification_mark_button_component.rb
src/api/app/controllers/concerns/webui/notifications_filter.rb
src/api/app/controllers/person/notifications_controller.rb
src/api/app/controllers/webui/users/notifications_controller.rb
src/api/app/helpers/webui/notification_helper.rb
src/api/app/models/notification.rb
src/api/app/views/person/notifications/index.xml.builder
src/api/app/views/webui/users/notifications/_notifications_list.html.haml
src/api/app/views/webui/users/notifications/index.html.haml
src/api/spec/components/notification_action_bar_component_spec.rb
src/api/spec/components/notification_filter_link_component_spec.rb
src/api/spec/components/notification_mark_button_component_spec.rb
src/api/spec/components/previews/notification_action_bar_component_preview.rb
src/api/spec/controllers/person/notifications_controller_spec.rb
src/api/spec/controllers/webui/users/notifications_controller_spec.rb
src/api/spec/features/webui/users/notifications_spec.rb
src/api/spec/helpers/webui/notification_helper_spec.rb

This will be the foundation where we'll build a better https://github.com/openSUSE/open-build-service/pull/16101.
We decouple the read/unread status of a notification from it's
type (which notifiable it associated to).

Refactor Notification scopes

---

src/api/app/models/bs_request_action_submit.rb

Both methods are used while rendering RequestDecisionComponent's template

Avoid querying the target package twice

---

dist/systemd/obsdispatcher.service
dist/systemd/obsdodup.service
dist/systemd/obspublisher.service
dist/systemd/obsrepserver.service
dist/systemd/obsscheduler@.service
dist/systemd/obsservice.service
dist/systemd/obsservicedispatch.service
dist/systemd/obssigner.service
dist/systemd/obssrcserver.service
dist/systemd/obsworker@.service

Enable restart of critical services when killed via systemd OOM.
Services where a downtime is considered less critical and be catched by monitoring remain to be stop for further analyses.
Verified on openSUSE 15.5 and newer.

[dist] Add OOMPolicy=continue to critical services

---

src/api/app/controllers/webui/status_messages_controller.rb
src/api/app/controllers/webui/webui_controller.rb

We should flash back an error and redirecting the user to the main page instead of crashing.
Fixes #16187

Avoid crashing when checking permissions to create a new status message

---

src/backend/BSSched/BuildJob/Patchinfo.pm
src/backend/BSSched/BuildJob/ProductCompose.pm

This is useful for reducing the binaries the worker has to download. It es especially needed if the package is a patchinfo that contains multiple architectures.
The downside is that the code must match what the product composer code does.

[backend] ProductCompose: implement binary architecture filter

---

src/backend/BSSched/PublishRepo.pm

We do not want to crash the scheduler, but return a meaningful error.

[backend] catch errors in the publish filter

---

src/api/app/models/notification.rb

Notifications about old events stay around for 365 days...
Fixes #16207.

Be backwards compatible with event_payload

---

src/api/app/models/staging/workflow.rb

The manager group of a staging workflow could have lost its review role of the project attached to a staging workflow. That made updating the manager group to throw an error.
Remove reviewer role for old managers role and add reviewer role for new
managers role.
Fixes #16205.

Make sure a changed manager group gets the reviewer role

---

src/api/app/views/webui/staging/workflows/_delete.html.haml

Found while working on #16205.
Currently, cliking on "Cancel" button on the modal for deleting a Staging Workflow not only closes the modal, but also triggers a delete of the Staging Workflow. Clicking on the "Cancel" button should only close the modal.
Fix this behaviour adding a missing `type` attribute in the `button` HTML element.

Make clicking on "Cancel" button not to delete a Staging Workflow

---

src/api/app/views/webui/staging/workflows/_staging_managers_group.html.haml

Before, the id of the staging workflow was passed in the `action` attribute of the form.
Pass the correct url to the form, so the update path could be reached and the managers group updated.
Fixes #16205, the remaining Web UI part.

Fix setting the managers group of a Staging Workflow from the Web UI

---

src/api/app/models/concerns/has_attributes.rb

The `project` method is only valid when the object is a package, if not, we can ask for `render_main_attributes` directly.
Fixes #15664

Fix undefined local variable or method `project`

---

src/api/app/assets/javascripts/webui/notification.js
src/api/app/components/notification_action_bar_component.html.haml
src/api/app/components/notification_mark_button_component.rb
src/api/app/controllers/webui/users/notifications_controller.rb
src/api/spec/components/notification_mark_button_component_spec.rb
src/api/spec/controllers/webui/users/notifications_controller_spec.rb
src/api/spec/features/webui/users/notifications_spec.rb

Matches the action performed in the controller to the button text as specified in:
https://github.com/openSUSE/open-build-service/blob/1abe6b4d4c4b1deda44541966ca2eaaeda86a6b4/src/api/app/components/notification_action_bar_component.rb#L15
This way there is no ambiguity about the action that the user is trying to perform vs what's done in the controller code

Mark as read when button specified mark as read

---

src/api/app/components/notification_filter_component.rb
src/api/app/views/webui/shared/_check_box.haml

Prevent from performing N+1 queries for retrieving the count of notifications a user has for every project.
Fixes #16236.

Don't count notifications for projects

---

src/api/app/components/notification_filter_component.rb

Prevent from performing N+1 queries for retrieveing the count of notifications a user has for every group.
Also, prevent from doing the incomming and outgoing requests queries which, due to their complexity, make the browsing experience for users in the Web-UI no usable.
Fixes #16235.

Don't count notifications for groups and incomming and outgoing requests

---

src/api/lib/tasks/dev/notifications.rake
src/api/lib/tasks/dev/rake_support.rb
src/api/lib/tasks/dev/reports.rake
src/api/spec/factories/event_subscriptions.rb

NOTE: Currently web notifications for appealed decisions are not handled correctly. This is already tracked in the backlog. As soon as this is fixed, the Admin user will receive the notifications for the appeals created in the test data rake task.

Add more test data for notifications (appeal, build failure and role revoked)

---

src/api/app/controllers/webui/users/notifications_controller.rb
src/api/app/controllers/webui/webui_controller.rb
src/api/app/views/layouts/webui/_bottom_navigation.html.haml
src/api/app/views/layouts/webui/_top_navigation.html.haml
src/api/app/views/layouts/webui/_unread_notifications_counter.html.haml
src/api/app/views/layouts/webui/webui.html.haml
src/api/app/views/webui/users/notifications/_update.js.erb

Prevent from performing an SQL query every time the partial is rendered.
Instead, run the SQL query once in the controller and pass the result to the partial as a local variable.

Move the count of unread notifications to the controller

---

src/api/app/views/webui/users/notifications/_notification_filter.html.haml
src/api/app/views/webui/users/notifications/index.html.haml
src/api/spec/features/webui/users/notifications_spec.rb

Do not use an Apply button to submit multiple filters, apply one by one as soon as they are clicked (with just a bit of a delay to collect multiple clicks).
**Note**: the delay has been set to an arbitrary value of **1.5 second** (intended to be "let the user clicks multiple times, but do now wait too long if he is finished clicking")

Apply notification filters onclick

---

SUPPORT.md

* Remove every warning to markdown file.
* Have no warning on mardown lint prevent rendering error.
```bash
markdownlint ./SUPPORT.md
```

Fix typo in markdown

---

src/api/app/components/notification_action_bar_component.rb
src/api/spec/components/notification_action_bar_component_spec.rb

It was missing a value for the `button` parameter.
Fixes #16278

Fix the Mark all as Read/Unread button

---

src/api/app/views/webui/packages/binaries/dependency.html.haml
src/api/app/views/webui/packages/binaries/show.html.haml

Fixes #16271 
Multibuild packages weren't properly covered in show and dependency binary views. This fixes the issue

Make sure binaries show and dependency work on multibuild packages

---

src/api/app/mixins/build_log_support.rb

If the log contained html or xml, it would get rendered. Thankfully we have a sanitizer in front, so this is not a security issue, but it still looks rather weird. Unlike escape_code, ansible doesn't escape html, which is why we have to do this now

Escape html before parsing the log

---

src/api/app/views/webui/user/_basic_info.html.haml

We don't need to render the `edit_account_form` for others (except admins)

Stop another leak of user email

---

src/api/app/models/role.rb

`belongs_to: attrib_type_modifiable_bies` is never used.
In the case of `roles_static_permissions` and `roles_users`, they are used with the `has_and_belongs_to_many` associations below.

Remove unused associations in Role model

---

src/api/app/models/role.rb

In a "one to many" relationship it doesn't make sense to define `belongs_to` associations on both models `Role` and `Relationship` from one to another.
Fix that by defining that a role has many relationships.

Fix association between roles and relationships

---

src/api/app/models/issue_tracker.rb

Checking for an enabled issue tracker is already performed before calling the `update_issue` method. This only happens in two places:
- `self.update_all_issues` method
- `updateissues` rake task
Therefore, we don't need to perform this check again in the methods called by `update_issue`.

Remove redundant issue trackers check for enabled

---

src/api/spec/factories/packages.rb

Creating this remote project ('openSUSE.org:openSUSE:Factory') prevented from building Tumbleweed packages in the development environment.
See: https://github.com/openSUSE/open-build-service/pull/12307#pullrequestreview-910178115
- Checkout this branch
- Reset your development environment with: `bin/rake dev:test_data:create`
- Check that Tumbleweed packages start building

Make Tumbleweed builds work in development environment

---

src/api/spec/components/previews/workflow_artifacts_per_step_component_preview.rb

How tot test it:
Check that both previews are working in the review app:
- https://obs-reviewlab.opensuse.org/danidoni-fix-workflow-artifacts-per-step-component-previews/rails/view_components/workflow_artifacts_per_step_component/with_link_package_step
- https://obs-reviewlab.opensuse.org/danidoni-fix-workflow-artifacts-per-step-component-previews/rails/view_components/workflow_artifacts_per_step_component/with_branch_package_step

Fix WorkflowArtifactsPerStepComponent previews

---

src/api/app/models/event/workflow_run_fail.rb

This is an event only interesting for one user/group, not the public.

Stop publishing workflow events on the message bus

---

src/api/app/views/webui/users/notifications/_notification_filter.html.haml

This makes it easier to recognize that their numbers are already
included in the "Requests" above.
screenshot: http://www.zq1.de/~bernhard/temp/mynotifications2-or8.png (original version was http://www.zq1.de/~bernhard/temp/mynotifications-or8.png )

Indent Incoming+Outgoing Requests

---

src/api/app/assets/javascripts/webui/project_monitor.js
src/api/app/controllers/webui/packages/build_log_controller.rb
src/api/app/views/webui/packages/build_log/_breadcrumb_items.html.haml
src/api/app/views/webui/packages/build_log/live_build_log.html.haml
src/api/app/views/webui/project/monitor.html.haml

Before we solve the problem with package existing only in the backend in general, people want to look at build logs for this case...
It's a slightly less awkward version of #12351 
Fixes #13176
- Enable the interconnect to build.o.o
- Create a project and
-  set `scmsync` to https://github.com/hennevogel/scmsync-project
- add a 15.5 repository
- Wait until the packages built and visit the monitor page

Make it possible to view scmsync'ed package logs

---

src/api/app/helpers/webui/notification_excerpt_helper.rb

Sometimes the text is nil, for example, when a report reason is not filled. That nil will make the `truncate_to_first_new_line` function to crash.

Fix excerpt truncation when text is nil

---

src/api/app/controllers/webui/configuration_controller.rb
src/api/app/models/configuration.rb
src/api/app/views/layouts/webui/_top_navigation.html.haml
src/api/app/views/webui/configuration/index.html.haml

Lets you change the logo in the frontend
For reviewers: https://obs-reviewlab.opensuse.org/hellcp-work-logo-upload-ui/configuration

Allow setting logo in the admin config

---

src/api/app/models/event/added_user_to_group.rb
src/api/app/models/event/appeal_created.rb
src/api/app/models/event/base.rb
src/api/app/models/event/build_fail.rb
src/api/app/models/event/cleared_decision.rb
src/api/app/models/event/comment_for_package.rb
src/api/app/models/event/comment_for_project.rb
src/api/app/models/event/comment_for_request.rb
src/api/app/models/event/favored_decision.rb
src/api/app/models/event/relationship_create.rb
src/api/app/models/event/relationship_delete.rb
src/api/app/models/event/removed_user_from_group.rb
src/api/app/models/event/report_for_comment.rb
src/api/app/models/event/report_for_package.rb
src/api/app/models/event/report_for_project.rb
src/api/app/models/event/report_for_request.rb
src/api/app/models/event/report_for_user.rb
src/api/app/models/event/request_create.rb
src/api/app/models/event/request_statechange.rb
src/api/app/models/event/review_wanted.rb
src/api/app/models/event/service_fail.rb
src/api/app/models/event/workflow_run_fail.rb
src/api/app/views/webui/subscriptions/_subscriptions_form.html.haml

Instead of referencing classes by strings, and then relying on reflection to get the class instances themselves, let's just use the class name directly.
This helps with navigation and refactoring, as well as readability.

Prefer constants for referencing classes.

---

src/api/app/models/user.rb
src/api/spec/models/user_spec.rb
src/api/test/unit/user_test.rb

Users can delete its own home project and they can create subprojects without the parent project being present.
In both cases you would end up having a hierarchy of projects that you were left out without having permission to do anything on them.
This PR allows a user full control over its subprojects.
Fixes #16328

Fix user denied deletion of its own subprojects

---

src/api/app/controllers/webui/request_controller.rb

`User` is consumed [here](https://github.com/openSUSE/open-build-service/blob/5a803518e1d9f885da7ad638b12fdf6b434f6660/src/api/app/components/bs_request_overview_avatars_component.rb#L14) and `Group` is consumed [here](https://github.com/openSUSE/open-build-service/blob/5a803518e1d9f885da7ad638b12fdf6b434f6660/src/api/app/components/bs_request_overview_avatars_component.rb#L25)

Optimize query to avoid N+1 between Review, User and Group

---

src/backend/bs_notar

Just pass it to the sign tool, like with --signtype

[backend] bs_notar: support the --signflavor option

---

src/api/app/components/notification_notifiable_link_component.rb

Otherwise, the code crashes when `who` is not present in the payload.

Add single quotation marks missing in interpolation

---

src/api/app/models/full_text_search.rb

In order to avoid parameter errors when someone tries to inject garbage as parameters, we coerce everything as string.
Avoid errors like
can't quote ActionController::Parameters
Fixes #16264

Coerce the issue_tracker_name to string

---

src/api/app/controllers/webui/monitor_controller.rb
src/api/app/controllers/webui/webui_controller.rb

We don't want to crash with
can't quote ActionController::Parameters
whenever people put garbage inside parameters
Follow up of #16377
Fixes #16379

Coerce sensible params to string

---

src/api/app/controllers/public_controller.rb
src/api/config/routes/api.rb

Required by osc for fetching keys when buildig against remote instances

[api] allow to request keyinfo via /public

---

src/api/app/components/notification_action_bar_component.html.haml
src/api/app/components/notification_component.html.haml
src/api/app/components/notification_component.rb
src/api/app/components/notification_mark_button_component.rb
src/api/app/controllers/person/notifications_controller.rb
src/api/app/controllers/webui/users/notifications_controller.rb
src/api/app/helpers/webui/notification_helper.rb
src/api/app/models/notification.rb
src/api/app/views/webui/users/notifications/_notifications_list.html.haml
src/api/app/views/webui/users/notifications/_page_size_navigation.html.haml
src/api/lib/tasks/dev/notifications.rake
src/api/spec/components/notification_component_spec.rb
src/api/spec/features/webui/users/notifications_spec.rb

Use the kaminari per scope instead of a hand crafted show_more parameter.
Turns this
into this

Introduces page_size to pagination navigation

---

dist/obs-server.spec

instead of adding more if else cases to require python311-ec2imgutils now, just require the actually called binary /usr/bin/ec2uploadimg

update deps for obs-cloud-uploader

---

src/api/app/jobs/update_released_binaries_job.rb
src/api/app/models/repository.rb
src/api/spec/jobs/update_released_binaries_job_spec.rb

By not storing the full BinaryRelease object in the `old_binary_releases` hash
but only the data needed to detect if the BinaryRelease was modified.
In the case it's modified we need to look it up in the database then, but this
should not happen often.
By only iterating through the current and unchanged BinaryRelease of the Repository.

reduce memory need on packtrack data import

---

src/api/app/controllers/webui/search_controller.rb

In order to search by attrib_type_id, ensure we don't try to process garbage coming as parameters
Fixes #16255
**How to test this**
1. Open http://localhost:3000/search?attrib_type_id%5B%24testing%5D=1
2. See it **not** failing with
```
undefined method `to_i' for #<ActionController::Parameters {"$testing"=>"1"} permitted: false>
```

Coerce sensible params to int

---

src/api/app/controllers/webui/users/notifications_controller.rb
src/api/app/views/webui/shared/_check_box.haml
src/api/app/views/webui/shared/_radio_button.haml
src/api/app/views/webui/users/notifications/_notification_filter.html.haml

Fixes: https://github.com/openSUSE/open-build-service/issues/16325
The count of notifications is visible only for `unread` ones in all the filter labels.

BugFix: notification count for unread only

---

src/api/app/policies/package_policy.rb
src/api/app/policies/project_policy.rb
src/api/spec/policies/package_policy_spec.rb

Less layers of indirection (can_source_access -> can -> has_local_permission) and less duplication (has_local_permission already checks the Project of a Package)

Simplify Package/Project source_access policy

---

src/api/.database_consistency.todo.yml
src/api/app/models/comment.rb

Permit to include the projects table in comments queries with commentable. Therefore, N+1 queries are not performed for comments with a project as a commentable.
This will reduce the number of "Project Load" queries performed. See:
- https://obs-measure.opensuse.org/d/OFTlR0ESz/database-queries
- https://obs-measure.opensuse.org/d/influxdb-rails-slowlog-sql/slowlog-by-sql-query

Preload projects on polymorphic commentable

---

src/api/app/models/event/workflow_run_fail.rb
src/api/app/models/event_subscription.rb
src/api/lib/tasks/dev/notifications.rake
src/api/lib/tasks/dev/rake_support.rb
src/api/spec/models/event_subscription/find_for_event_spec.rb

We notify token executors about a workflow run. We are going to notify users and groups the token is shared with.
TODO:

Workflow run notifications

---

src/api/app/controllers/webui/webui_controller.rb

In cases like AJAX queries for build results or RPM lint results, we don't need to set the unread notifications counter.

Don't set unread notifications count on AJAX requests

---

src/api/app/mixins/build_log_support.rb
src/api/spec/mixins/build_log_support_spec.rb

Sometimes we get build logs in UTF-8 with invalid byte sequences. We need to be able to process them without failing.
This PR removes the invalid byte sequences
Fixes #16411

Fix invalid byte sequence in UTF-8 processing build logs

---

src/api/app/components/workflow_run_header_component.rb
src/api/app/views/webui/workflow_runs/show.html.haml

Fixes https://github.com/openSUSE/open-build-service/issues/16420
Option 1: make the `token_id` parameter optional
Option 2: pass the `token_id` parameter to the `WorkflowRunHeaderComponent` too
Choice: Option 2
Reason: keep the interface consistent between the two component bounded by inheritance

Bugfix: missing initialize parameter due to inheritance

---

src/api/app/views/webui/package/side_links/_create_badge.html.haml

The image we render will be overwritten by javascript after loading the page.
On a development environment, browse a page of a package ( http://localhost:3000/package/show/home:Admin/hello_world, for example ). Notice in the logs that the badge is loaded twice.
After the changes, the badge is loaded only once.

Prevent from loading the badge twice

---

src/api/app/services/scm_status_reporter.rb

We can leverage the use of metaprograming for setting the vendor-specific reporter

Refactor a bit of complexity on SCMStatusReporter

---

src/api/app/controllers/webui/repositories_controller.rb

This fixes the "Flag is invalid" errors from
Validation failed: Flags Duplicated flags, Flags is invalid
Related to #7893

Return a Bad Request error when toggling an invalid flag

---

src/api/config/routes/webui.rb

This way, setting users and groups roles for packages work the same way as for projects.
Fixes #16433.
You can use the review-app, and see the roles of a package [here](https://obs-reviewlab.opensuse.org/eduardoj-fixajax_in_users_and_groups_of_packages/package/users/home:Admin/hello_world). None of these actions should return a 500 error:
- Add a user as maintainer (Iggy, for example)
- Add a role to the user Iggy
- Remove a role of the user Iggy
- Remove the user Iggy

Permit AJAX requests to set roles of packages

---

src/api/app/models/attrib_type.rb

Instead of performing two SQL queries, one for counting and another one for retrieving the first element, perform only one query.

Improve searching for an attribute type

---

src/api/spec/services/notification_service/web_channel_spec.rb

In these two cases, using a shared example provides more confusion than clarification.

Refactoring: replace simple shared examples with simple "it" groups

---

src/api/app/models/event/workflow_run_fail.rb
src/api/app/models/token/workflow.rb
src/api/spec/models/event_subscription/find_for_event_spec.rb

Issue: when a token is shared with a userA and a group where the userA is part of, userA receives notification twice.
Explanation: `receiver_roles` are populated in a special way in the `Event::WorkflowRunFail` case: users and group don't have roles on `Token`, the `Token` is **shared** with them instead, and they act like they are the owner too. So in this case, we cannot let the `find_for_event.rb` do it's normal job finding users and group users based on roles and deduct the set of users. We need to send a set of unique users in advance to the `receiver_roles`, so the notification is not sent twice to users they have the token shared directly and they are part of a group the token is shared with too.

Duplicated notifications for receivers occurring multiple times

---

docs/api/api/package.rng
src/api/test/functional/source_controller_test.rb

OBS is not always delivering title and description elements itself anymore (when they come from pure backend projects). So accept package meta also without it to avoid that tooling can not read and write same meta from OBS instances.
Also the order of title and description does not matter to us.
Rest is just indenting fixes.

[api] relax package meta

---

src/api/app/helpers/maintenance_helper.rb

Do not create local links if origin package name contains already a dot. eg. go1.19 or ruby2.13. We check if the origin project has a package with a shortend name.

[api] fix invalid local links on package instantiate

---

docs/api/api/api.txt

Reviewing all places where a CGI parameter can be used multiple times _and_ is exposed via the api.
Some of the /build/_workerstatus parameters are currently not support, but used to be in the past IIRC. However, not documented yet, but we may want to bring these back.

[api] add some missing api parameters

---

docs/api/api/api.txt
src/api/app/controllers/source_controller.rb

it would filter on release before, but fail if not filtered architectures are missing in target

[api] fix handling of architecture filter for release command

---

src/api/app/controllers/source_project_package_meta_controller.rb
src/api/public/apidocs/paths/source_project_name_package_name_meta.yaml

api blocked requests for deleted packages always.

[api] fix delivering of delete package meta data

---

src/api/spec/spec_helper.rb

See
https://github.com/simplecov-ruby/simplecov/blob/main/README.md#getting-started.
It says to put the require at the very top of the file.
Looks like that way the reports are [much more accurate](https://codeclimate.com/github/openSUSE/open-build-service/compare/4ffc8887a964dd597a30d9f822636b3e80f82386...0e04ce832022b5c7c6a16eb1be335c801cac7cbc#ratings).

Move the simplecov to the top of the file

---

src/backend/BSTar.pm

This allows to read tar archives with contain files biggen than 8GByte.

[backend] BSTar: implement overwriting the size via the PAX header

---

src/api/app/helpers/webui/notification_helper.rb
src/api/spec/helpers/webui/notification_helper_spec.rb

Sometimes the text to display in the excerpt is nil and we have nothing to truncate.
Fixes #16492
Fixes #16491

Fix excerpt truncation

---

src/backend/BSRPC.pm
src/backend/bs_repserver

Currently OBS does not support workers connected from IPv6.
This commit enables BSRPC to parse IPv6 hosts, which allows jobs to be dispatched via IPv6.
(Tested on [self-hosted OBS instance for eweOS](https://os-build.ewe.moe))

 [backend] add ipv6 support for workers

---

src/backend/bs_repserver

It stripes by default the build number, what might not be wanted.
Overwriting can be done with setrelease=- query parameter

[backend] allow to opt-out setrelease default behaviour

---

src/api/app/assets/stylesheets/webui/diff.scss

Fixes #16503
Makes sure that the content of the newline isn't moved onto a new line

Make sure that the diff compopnent doesn't newline the content of the diff

---

src/api/app/controllers/webui/request_controller.rb

Pagination to be applied only in the [`index`](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/controllers/webui/request_controller.rb#L37) method, after all the filters are applied, right before returning

Do not paginate requests before filters

---

src/backend/bs_srcserver

The worker cannot run ths bssign script, so we need to do this in the source server.

[backend] getsignkey: use getdefaultpubkey() if _pubkey contains a "1"

---

src/api/app/views/webui/architectures/index.html.haml

Use architecture id instead of name in update method

---

src/api/config/thinking_sphinx.yml.example

As first step, to ensure this is not causing any issue, we are going to enable it only in development environment.
See #11347 and #11374.
As reference: http://www.sphinxsearch.com/docs/current.html#conf-min-infix-len

Introduce wildcard searching in development mode

---

src/api/app/components/notification_component.rb
src/api/app/models/notification.rb
src/api/app/policies/notification_comment_policy.rb
src/api/spec/components/notification_component_spec.rb
src/api/spec/components/notification_mark_button_component_spec.rb
src/api/spec/controllers/person/notifications_controller_spec.rb
src/api/spec/controllers/webui/feeds_controller_spec.rb
src/api/spec/controllers/webui/users/notifications_controller_spec.rb
src/api/spec/db/data/adapt_review_and_duplicated_notifications_spec.rb
src/api/spec/db/data/backfill_notified_projects_spec.rb
src/api/spec/db/data/convert_notifications_event_payload_to_json_spec.rb
src/api/spec/db/data/generate_web_notifications_spec.rb
src/api/spec/db/data/remove_notifications_for_missing_notifiables_spec.rb
src/api/spec/db/data/remove_obsolete_notifications_spec.rb
src/api/spec/factories/notification.rb
src/api/spec/features/webui/users/notifications_spec.rb
src/api/spec/helpers/webui/notification_helper_spec.rb
src/api/spec/jobs/cleanup_notifications_job_spec.rb
src/api/spec/models/notification_spec.rb
src/api/spec/models/user_spec.rb
src/api/spec/policies/notification_comment_policy_spec.rb
src/api/spec/services/notification_service/web_channel_spec.rb

Depends on #16477
This should be merged after #16477 is deployed on our internal instances

Remove the notification specialized class switcher

---

dist/obs-server.spec

This is fixing build issues with newer perl.
Exception is perl-BSSolv which just provides a too old api name

[dist] using perl module provides instead of package names

---

dist/obsstoragesetup

The xm(1) tool no longer exists, so we should not use it anymore when running the OBS appliance as a Xen guest.

[dist] obsstoragesetup: Drop usage of xm(1)

---

src/api/app/controllers/webui/search_controller.rb
src/api/app/models/full_text_search.rb

Recently we introduced an sphinx index for submit requests. Prevent from using this submit request index for searches of projects, packages and issues. This can happen when the query parameter `search_for` is not sent or its value isn't `0`, `1`, or `2`.

Use only project and package sphinx indices for text search

---

src/api/app/controllers/group_controller.rb
src/api/spec/controllers/group_controller_spec.rb
src/api/test/functional/group_test.rb

Instead of crashing, we now raise an InvalidParameterError when receiving an invalid XML when trying to update a group.
Fixes #16434

Fix error when processing bad group updates via xml

---

src/api/app/controllers/concerns/webui/notifications_handler.rb
src/api/app/controllers/webui/package_controller.rb
src/api/app/controllers/webui/project_controller.rb

This change was missing when the policy was renamed from `NotificationPolicy` to `NotificationCommentPolicy`, in #16486.
Fixes #16551.

Use renamed NotificationCommentPolicy

---

src/api/app/models/event/relationship.rb
src/api/db/data/20240724091140_backfill_type_of_relationship_notifications.rb
src/api/db/data_schema.rb

In the last refactoring we missed to set the `type` on notifications related to `RelationshipCreate` and `RelationshipDelete`. Since the deployment, we have `type: nil` on both OBS and IBS.
This makes the notifications page crash because it can't access to methods like `link_path`, `excerpt`, etc.
This PR fixes the code to always set the type and also adds the data migration for the affected notifications.

Fix relationship notifications

---

.circleci/conditional_config.yml
.obs/workflows.yml

This upgrades our CI from 15.5 to 15.6.
I thought about make the CI to detect what we have installed and use one version or the other, but frankly, it's just easier to wait for the maintenance window where our OS will be upgraded and merge this then.

Upgrade our CI to run against 15.6

---

src/api/app/services/rpmlint_log_extractor.rb
src/api/spec/fixtures/files/rpmlint_log_extractor_log
src/api/spec/fixtures/files/rpmlint_log_extractor_log_without_mark
src/api/spec/services/rpmlint_log_extractor_spec.rb

fixes #16555
Currently, if a user has signed up for the Request Show Redesign Beta feature, we display build logs for all repositories if rpmlint logs are not available. This is not correct because it's confusing for reviewers. This PR changes that behavior to show the correct message, indicating that no rpmlint logs are available.

Don't show build logs when rmplint logs are not available

---

dist/obs-server.spec

This is a partial revert of
commit 1e8688bb749a89bb85e0b32f3061560732885f49
to fix image builds in https://build.opensuse.org/package/show/OBS:Server:Unstable/OBS-Appliance
For some reason, Leap's perl-TimeDate package does not Provide perl(TimeDate)

Require perl-TimeDate again

---

src/api/app/assets/stylesheets/webui/requests.scss
src/api/app/controllers/webui/request_controller.rb
src/api/app/helpers/webui/request_helper.rb
src/api/app/models/bs_request.rb
src/api/app/models/bs_request_action.rb
src/api/app/views/webui/request/_request_item.html.haml
src/api/app/views/webui/request/_requests_filter.html.haml
src/api/app/views/webui/request/index.html.haml
src/api/spec/features/beta/webui/requests_index_spec.rb

Implements a way to filter by action types within the new requests view
Depends on #16536

Request action type filter

---

dist/obs-server.spec

This is a fixup on
commit 1e8688bb749a89bb85e0b32f3061560732885f49
to fix image builds in https://build.opensuse.org/package/show/OBS:Server:Unstable/OBS-Appliance
For some reason, Leap's perl-TimeDate package does not Provide perl(TimeDate)

Require perl(Date::Parse)

---

src/api/app/views/webui/request/index.html.haml

Typo fix to match the `id` and the `js` (see below) that look up for it in order to render the `loading` properly and hide the content instead.
```
...
$('#requests-list').hide();
$('#requests-list-loading').removeClass('d-none');
...
```

Id typo fix

---

src/api/spec/cassettes/Webui_RequestController/GET_index/as_user_with_requests/assigns_bs_requests.yml
src/api/spec/cassettes/Webui_RequestController/GET_index/as_user_with_requests/responds_successfully.yml
src/api/spec/cassettes/Webui_RequestController/GET_index/as_user_with_requests_filtering_by_accepted_state/assigns_bs_requests_applying_state_filter.yml
src/api/spec/cassettes/Webui_RequestController/GET_request_action/handling_diff_sizes/with_diff_to_superseded_set/and_the_superseded_request_is_not_superseded/1_5_1_3_2_1.yml
src/api/spec/cassettes/Webui_RequestController/GET_request_action/handling_diff_sizes/with_diff_to_superseded_set/and_the_superseded_request_is_not_superseded/1_5_1_3_2_2.yml
src/api/spec/cassettes/Webui_RequestController/GET_request_action/handling_diff_sizes/with_diff_to_superseded_set/and_the_superseded_request_is_superseded/1_5_1_3_1_1.yml
src/api/spec/controllers/webui/request_controller_spec.rb

**codecov/patch** complained about the lack of tests regarding the newly introduced filter code in the request controller.
Follow-up  #16528.
It doesn't harm to create some simple specs to cover them. Here you are the one for the `state` filter.

Add request controller specs for state filter

---

src/api/app/models/user.rb

The `.where(state: states)` is already applied at the beginning when `result = BsRequest.where(state: states)......`

Deduplicate query criteria

---

src/api/app/views/webui/request/index.html.haml

For some reason, at some point this line of code disappeared.
It is required in order to show the current multiselect values in the filters.

Collect multiselect selections

---

src/backend/BSSrcServer/Scmsync.pm

An atomar git change should also appear atomar to the schedulers. Important for block handling

[backend] suspend scheduler during project scmsync

---

src/api/app/helpers/webui/notification_helper.rb
src/api/spec/helpers/webui/notification_helper_spec.rb

We were not passing what kind of button we had: "mark as read" or "mark as unread"
Fixes: #16587

Fix mark as read button on the notification bar

---

dist/obs-apache24.conf

SP6 apache seems to limit to 1GB, going back to unlimited in our config.

[dist] set body request size limit

---

contrib/start_development_backend

When shutting down the development environment (`Ctrl-C` on a `docker compose` session), the logs of the backend returned (`docker compose logs backend -f`):
```
backend-1  |
backend-1  | cleaning up and exit
backend-1  | Terminating Services
backend-1  | bs_srcserver: no process found
backend-1  | Terminated SRC Server
backend-1  | bs_repserver: no process found
backend-1  | Terminated REP Server
backend-1  | bs_sched: no process found
backend-1  | Terminated Scheduler
backend-1  | bs_dispatch: no process found
backend-1  | Terminated Dispatcher
backend-1  | bs_publish: no process found
backend-1  | Terminated Publisher
backend-1  | bs_service: no process found
backend-1  | Terminated Publisher
backend-1  | bs_signer: no process found
backend-1  | Terminated Signer
backend-1  | …
```

Fix development backend script

---

src/api/app/controllers/webui/package_controller.rb

Sending only the `@package` parameter makes the `package_show_path` helper throw an error.
Noticed while working on #16593.

Fix parameters sent to `package_show_path` helper

---

src/api/app/helpers/webui/notification_helper.rb
src/api/app/views/layouts/webui/_notification_toolbar.html.haml
src/api/spec/helpers/webui/notification_helper_spec.rb

Refactor the notification toolbar helpers to make them simpler

---

src/api/app/views/webui/request/index.html.haml

Right now its not possible to submit the search input field. For all other inputs of the same form we have auto submit implemented through JS. But this makes little sense for the search input.
By adding a hidden submit button we can default to common browser behavior of submitting the form when pressing the enter button on the selected input.
This is just a quick fix to allow usage of the search, but we might should revisit this and align the filter submission behavior. I noted this down here: https://trello.com/c/7onRo4zi/29-revisit-request-search-input-handling

Add hidden submit field to request index filter form

---

src/api/app/models/workflow_run.rb

This PR will only prevent the existence of new Notifications pointing nowhere, we should also clean our reference server from the already existing notifications that point to non-existent WorkflowRun's (given that the number of affected notifications is les than 10 I would do it manually).
See #16586
Fixes #16582

Remove associated notifications when destroying a workflow run

---

src/api/app/models/label_template.rb
src/api/db/migrate/20240805122519_change_label_templates_color_to_string.rb
src/api/db/schema.rb

Rails form field helpers for color expect a string so it's easier if we just use a string field instead of a numeric one.
The field change locks the table during the migration, but as no one is using this table on our reference server it's safe to deploy this whenever we see fit.

Change label_template's color field to string

---

src/api/config/initializers/flipper.rb

*DO NOT MERGE*:
We want to only show this to staff users for now in order to be more agile during the implementation. After all UI parts are connected we can enable this for beta users.

Add `request_index` feature to flipper initializer

---

src/api/app/controllers/webui/projects/label_templates_controller.rb
src/api/app/models/project.rb
src/api/app/policies/label_template_policy.rb
src/api/app/views/webui/project/_basic_info.html.haml
src/api/app/views/webui/project/_tabs.html.haml
src/api/app/views/webui/projects/label_templates/_breadcrumb_items.html.haml
src/api/app/views/webui/projects/label_templates/index.html.haml
src/api/app/views/webui/shared/_label.html.haml
src/api/config/routes/webui.rb

This is how it looks like now
Depends on #16641
**How to test this**
- With the feature flag `labels` on:
- Go to `home:Admin`, there you'll see a tab at the end called `Label templates`. 
- Click on that and you'll be presented with the screen displayed above.
- Without the feature flag `labels` you won't see the tab, nor will you be able to access the page

List label templates on project show

---

src/api/lib/tasks/dev/notifications.rake

One word is not enough to guarantee that no two groups have the same name... Several words will make for more unique names for groups.

Fix group name clash

---

src/api/spec/factories/label_template.rb

Depends on #16642
Sometimes the factory produces colors like "#1fb54" which is not a valid color code (it should be "#01fb54".

Ensure the  factory produces valid color codes

---

src/api/app/views/webui/shared/_label_list.html.haml

This causes collisions with ids between the two, we need to avoid that

Render label templates instead of labels

---

src/api/lib/obsapi/markdown_renderer.rb
src/api/spec/helpers/webui/markdown_helper_spec.rb

The `block_html` callback gets called when a `<pre></pre>` section or a `<script></script>` section is found. This method doesn't get called for `<b>`, `<em>`, `<i>`, `<strong>` or `<u>` elements.
Rely on the default escape policy of the parser, instead of parsing HTML blocks and then leave `<pre></pre>` elements and remove `<script></script>` elements.
A text with this content:
Was rendered like this, before:
And like this, after:

Escape HTML blocks instead of removing them

---

src/api/app/controllers/webui/project_controller.rb
src/api/app/views/webui/package/_basic_info.html.haml
src/api/app/views/webui/project/_basic_info.html.haml
src/api/app/views/webui/shared/_collapsible_text.html.haml

After the changes proposed, entering some text like this editing a project and clicking in "Update":
... will result in:
Fixes #810.

Allow rendering markdown in the description of projects and packages

---

src/api/app/models/decision_cleared.rb
src/api/app/models/decision_favored.rb
src/api/app/models/decision_favored_with_comment_moderation.rb
src/api/app/models/decision_favored_with_delete_request.rb
src/api/app/models/decision_favored_with_user_commenting_restriction.rb
src/api/app/models/decision_favored_with_user_deletion.rb
src/api/spec/features/beta/webui/decisions_spec.rb

Use an appropriate tense in the decision type selector: `favor...` instead of `favored...`. Open any report and try to set a decision to test the change.

Use imperative in the decisions actions

---

src/api/app/models/unregistered_user.rb
src/api/app/models/user.rb
src/api/db/migrate/20240814141544_add_censored_to_users.rb
src/api/db/schema.rb

The final goal is to rename `blocked_from_commenting` to `censored` to avoid confusion with the block user action.
This is the first PR in a series to avoid downtime. The steps are:
1. Add new column `censored` to the users table. :arrow_left:
1. Write to both columns
2. Backfill data from the old column to the new column
3. Move reads from the old column to the new column

Add censored column to the users table

---

src/api/app/controllers/webui/users_controller.rb

Follow-up  #16693
This is the second PR in a series to avoid downtime. The steps are:
1. Add new column `censored` to the users table.
1. Write to both columns  :arrow_left:
2. Backfill data from the old column to the new column
3. Move reads from the old column to the new column
~**DO NOT MERGE** until the previous PR is deployed~ The previous PR is deployed.

Write to censor column

---

src/api/db/data/20240814142031_backfill_censored_on_users.rb
src/api/db/data_schema.rb

Follow-up  #16695
This is the third PR in a series to avoid downtime. The steps are:
1. Add new column `censored` to the users table.
1. Write to both columns 
2. Backfill data from the old column to the new column  :arrow_left:
3. Move reads from the old column to the new column
~**DO NOT MERGE** until the previous PR is deployed~ The previous PR is deployed.

Backfill censored

---

src/api/app/controllers/webui/users_controller.rb
src/api/app/jobs/measurements_job.rb
src/api/app/models/decision_favored_with_user_commenting_restriction.rb
src/api/app/policies/comment_policy.rb
src/api/app/policies/user_policy.rb
src/api/app/views/webui/user/_basic_info.html.haml
src/api/config/routes/webui.rb
src/api/spec/controllers/webui/users_controller_spec.rb
src/api/spec/policies/comment_policy_spec.rb
src/api/spec/policies/user_policy_spec.rb

Follow-up  #16695
This is the second PR in a series to avoid downtime. The steps are:
1. Add new column `censored` to the users table.
1. Write to both columns
2. Backfill data from the old column to the new column
3. Move reads from the old column to the new column  :arrow_left:
4. Stop writing to the old column  :arrow_left:
~**DO NOT MERGE** until the previous PR is deployed~ The previous PR is deployed.

Adapt code to censored

---

src/api/app/controllers/webui/projects/meta_controller.rb

Redirecting back to the previously browsed page could make the browser enter an endless loop.
Redirecting to the root path solves this issue.
Fixes #16138.

Prevent an endless loop after deleting a project

---

src/api/app/components/notification_component.html.haml
src/api/app/components/notification_component.rb
src/api/app/models/notification_report.rb
src/api/spec/components/notification_component_spec.rb

Include user state, reports on user account, and number of reported comments on report user notification. In addition to that, include info about reported number of comments from same user on comment report notifications

Add more info. about reported users in notifications

---

src/api/app/components/notification_component.rb

This is quite easily triggered with report notifications involving a deleted reportable, simply create a report that will trigger a notification and remove the reportable before looking at the moderator's notifications
Fixes #16732.

Make sure the accused exists before rendering a notification involving them

---

src/api/Gemfile
src/api/Gemfile.lock

Upstream maintainers recommend to use a release candidate of a major version. Unpinning the rubygem would allow to upgrade to the major version once it is available.
Related to: #14533 and #16731
See: https://github.com/ilyakatz/data-migrate/issues/325

Unpin `data_migrate` rubygem

---

src/api/app/components/notification_component.html.haml
src/api/app/components/notification_component.rb
src/api/spec/components/notification_component_spec.rb

In order to see at the first glance if a report was already processed and how many additional reports exist for the same reportable.
TODO:
- ~~Add test case to `notification_component_spec`~~
- ~~Depends on https://github.com/openSUSE/open-build-service/pull/16709 (rebase first after it is merged)~~

Add infos about additional reports and decision status to notifications

---

src/api/app/components/notification_component.rb

Don't look up for `reports` if `reportable` is nil
Should fix https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/66c878fc84bf460be37eb0d6

Make sure reportable not nil

---

src/backend/bs_publish

If multiple binaries lead to identical static link names we took a random one (directory node order).
Now we compare the link target mtime and take the latested. More correct would be to implement for each binary type the right sorting method, but that is too much here atm.
obs#13264 issue#13264

[backend] bs_publish: fix static links for multi release targets

---

src/api/app/models/unregistered_user.rb
src/api/app/models/user.rb
src/api/db/data/20240814142031_backfill_censored_on_users.rb
src/api/db/migrate/20240823084727_drop_blocked_from_commenting_from_users.rb
src/api/db/schema.rb

Follow up to #16698.
This is the last PR in a series to avoid downtime. The steps are:
1. Add new column `censored` to the users table.
1. Write to both columns
2. Backfill data from the old column to the new column
3. Move reads from the old column to the new column
5. Drop the old column  :arrow_left:

Drop blocked_from_commenting from users table

---

src/api/app/components/bs_request_comment_component.html.haml
src/api/spec/features/beta/webui/reports_spec.rb

In the comments feed, the report button was placed next to the reply button.  This ran the risk of accidentally reporting when a reply was intended.
This change moves the Report action under the context menu, as it is a less common action and this will prevent accidental reports.
To verify this, report something by clicking Report under the three-dots context menu.

Report button too close to reply button

---

src/api/app/helpers/webui/request_helper.rb

Throwing an exception prevents from showing requests on deleted projects.
Fixes #16670.

Don't throw an exception on project not found

---

src/backend/BSSched/BuildJob/Patchinfo.pm

We now always append the status code to the package name, like we already did with failed packages.

[backend] provide a better hint why a patchinfo build is blocked

---

src/api/app/models/bs_request.rb
src/api/app/views/webui/requests/submissions/new.html.haml

This is a workoaround to prevent notifications from not being sent when the descriptions of the submit requests are very big.

Reduce validation value of the length of a submit request description

---

src/api/app/controllers/search_controller.rb
src/api/app/jobs/project_create_auto_cleanup_requests_job.rb
src/api/app/models/branch_package.rb
src/api/app/models/branch_package/lookup_incident_package.rb
src/api/app/models/concerns/project_maintenance.rb
src/api/app/models/owner_search/base.rb
src/api/app/models/project.rb
src/api/app/services/user_service/involved.rb

It only abstracts what Rails already provides with its Active Record Query interface methods. Also, the `find_by` part of the method is confusing.

Get rid of `find_by_attribute_type` Project class method

---

src/backend/BSPublisher/Diffnotify.pm
src/backend/bs_worker

The code did not set the "used" hash, leading to a crash when the outgoing buildenv was created.

[backend] bs_worker: fix cache handling in _buildenv builds

---

src/api/app/helpers/webui/comment_locks_helper.rb
src/api/app/views/webui/comment/_comment_field.html.haml
src/api/app/views/webui/request/_actions.html.haml
src/api/app/views/webui/request/_lock_unlock_comment.html.haml
src/api/app/views/webui/request/_request_comments.html.haml
src/api/app/views/webui/request/_show_actions.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/show.html.haml
src/api/app/views/webui/shared/_locking_dialog.html.haml
src/api/spec/features/webui/comment_locks_spec.rb

Also tries to address:
- https://github.com/openSUSE/open-build-service/pull/15031#discussion_r1351960786
- https://github.com/openSUSE/open-build-service/pull/15031#discussion_r1354568799

Move "Lock/Unlock Comments" button to the "Action" section

---

src/api/app/policies/bs_request_policy.rb

The author of the submit request, or the maintainers of the source package, can already use the "Revoke request" button.

Don't show "Decline request" button to the maintainers of the source package

---

src/api/app/assets/stylesheets/webui/diff.scss

Fixes #16088
Check the following screenshots. They show the comment in different viewport sizes.
The solution is not ideal as it hard-codes a width of 65% of the viewport. But after a lot of trials and conversations, the proper solution is going to require a bigger refactoring that includes wrapping each line (something that should be done after this [card](https://trello.com/c/E160LMhR) is implemented).

Adapt inline comments to avoid overflow

---

src/api/app/models/user_ldap_strategy.rb

Fix for #16806 
Currently when no `ldap_search_user` and `ldap_search_auth` are provided `try_ldap_con` quietly died.
```log
D, [2024-09-05T02:49:58.019231 #14706] DEBUG -- : [f70496f7-1c56-4935-818b-961930039bb5] [14706:25.37] Using LDAP to find testuser
D, [2024-09-05T02:49:58.019326 #14706] DEBUG -- : [f70496f7-1c56-4935-818b-961930039bb5] [14706:25.37] Looking for testuser using ldap
D, [2024-09-05T02:49:58.020230 #14706] DEBUG -- : [f70496f7-1c56-4935-818b-961930039bb5] [14706:25.37] Connecting to ldap.example.com as ''
D, [2024-09-05T02:49:58.020405 #14706] DEBUG -- : [f70496f7-1c56-4935-818b-961930039bb5] [14706:25.37] testuser not found in LDAP.
```
After these changes:
* in case of `ldap_search_user` and `ldap_search_auth` are set
```log
D, [2024-09-05T03:47:19.464541 #21206] …
```

Fix anonymous bind to LDAP server

---

src/backend/bs_publish

Kiwi image appliances need to match first, regexp is more exact then product composer ones

[backend] fix static links for kiwi appliances

---

src/api/app/components/reports_modal_component.rb
src/api/app/views/webui/comment/_comment_field.html.haml

Right now everyone's canned responses are visible in the dropdown

Make sure only user's own canned responses show up

---

src/api/app/mixins/build_log_support.rb

After doing `CGI.escapeHTML` lines before, the length of the log might have changed from `theend - start`, so we can't use it anymore

Make sure ansi escape codes get parsed

---

src/backend/BSRepServer/Registry.pm
src/backend/bs_dodup

Some of our digest entries had a missing "sha256:" prefix

[backend] bs_dodup: make sure the old entries are valid

---

src/api/app/helpers/webui/staging/workflow_helper.rb

These patchinfos are named "patchinfo.ABC.XYZ" where "ABC" and "XYZ" are sequences of integers, and this naming scheme is considered an implementation detail (to avoid collisions when several maintenance coordinators are working on updates targeting the same codestream).
The numbers are irrelevant for display, the only relevant information is that these packages are patchinfos, so this change rewrites the package name to just "patchinfo" in such cases.

Special-case SLFO maintenance patchinfos when displaying staging requests

---

src/api/app/services/scm_exception_handler.rb
src/api/app/services/scm_exception_message.rb

Exceptions with code 504 were not catched.
Rescuing from generic exceptions in the range of 500..599 with Octokit::ServerError prevents from crashing without notifying back OBS.
See #16691. Related to #12661.
To see exceptions supported by Octokit: https://github.com/octokit/octokit.rb/blob/71e3d209400ff29440d87581db90314b6272355b/lib/octokit/error.rb#L19-L37
Octokit::ServerError exceptions: https://github.com/octokit/octokit.rb/blob/71e3d209400ff29440d87581db90314b6272355b/lib/octokit/error.rb#L343-L356

Catch generic server exceptions when connecting to GitHub

---

src/backend/BSConfig.pm.template

syntactical correct and useful real life example for `$container_custom_opt`

[dist] improve BSConfig.pm

---

src/api/.rubocop_todo.yml
src/api/app/mailers/admin_mailer.rb
src/api/app/mailers/application_mailer.rb
src/api/app/mailers/consistency_mailer.rb
src/api/app/mailers/event_mailer.rb
src/api/app/views/layouts/event_mailer.html.haml
src/api/app/views/layouts/event_mailer.text.erb
src/api/test/fixtures/event_mailer/repo_delete_request
src/api/test/fixtures/event_mailer/request_event
src/api/test/fixtures/event_mailer/set_bugowner_event
src/api/test/fixtures/event_mailer/tom_declined
src/api/test/fixtures/event_mailer/tom_gets_mail_too

- Organize common parts of action mailers on an application mailer:
- This is the recommended way of organizing mailers proposed by the Action Mailer Basics guide: https://guides.rubyonrails.org/action_mailer_basics.html
- Solve the `Rails/ApplicationMailer` RuboCop offenses
- Get rid of this unneded assignment: `@configuration = ::Configuration.fetch`
- Prepare for a further refactoring to get rid of the `@host` variable and use `action_mailer.default_url_options` instead.

Refactoring of action mailers

---

src/api/app/models/bs_request/find_for/project.rb

When filtering by both roles and user, the code crashed as we set the @relation to nil by mistake. When there aren't new conditions to add to the relation, we should return the relation as it was before, not nil.
Fixes #16692
With the data generated by the `test_data` task, you can try the following, which will crash without the change proposed in this PR:
```
curl -H 'accept: application/xml' -u Admin:opensuse -X GET "http://localhost:3000/request?view=collection&user=Admin&roles=creator&project=home:Admin"
```
This is the endpoint documentation: https://api.opensuse.org/apidocs/index#/Requests/get_request_view_collection

Fix request filter from API

---

src/api/app/models/bs_request.rb
src/api/app/models/bs_request_permission_check.rb

`opts` is defined as a reader attribute for `BsRequestPermissionCheck`. Passing the `opts` parameter to all these methods is redundant.
Noticed after working on solving #16832.

Use only one `opts` hash

---

src/api/app/controllers/source_controller.rb
src/api/app/models/concerns/project_maintenance.rb
src/api/public/apidocs/paths/source_createmaintenanceincident.yaml

Passing a value or not to the `attribute` parameter to the `/source?cmd=createmaintenanceincident` API endpoint has never made a difference.

Remove never used parameter `attribute` for creating maintenance incidents

---

src/api/app/controllers/webui/package_controller.rb
src/api/spec/controllers/webui/package_controller_spec.rb

Avoid throwing a 500 error.
Fixes #16855.
Related to #16857.

Show an error message for statistics of a package of a scmsync project

---

src/api/app/models/project.rb

Package kinds are always use from the package model.

Remove package_kinds association from projects

---

src/api/app/views/webui/package/show_actions/_bugzilla_owner.html.haml
src/api/app/views/webui/project/show_actions/_report_bug.html.haml

Handle external report bug links properly

---

src/api/app/models/package.rb
src/api/spec/models/package_spec.rb

This is how it looks like when the url is local
And this is how it looks like when the url is not local

Do not allow local urls for the report bug link

---

src/backend/bs_srcserver

The check for scm errors/in progess was done too late. For a new project where no package has a commit, "no source uploaded" was returned instead of the scm status.

[backend] getprojpack: fix scm error reporting if there is no commit yet

---

src/api/app/models/binary_release.rb
src/api/db/migrate/20240916121900_increase_binary_releases_limit.rb
src/api/db/schema.rb

We reached the integer limit meanwhile, going from int to bigint for index

[api] increase size limit for binary_releases table

---

src/api/app/helpers/webui/request_helper.rb
src/api/app/views/webui/users/notifications/_notification.html.haml

There was an attempt to move it to a helper, but it makes sense to keep it as a ViewComponent, which is re-used from around seven other parts of the code: watchlist, notifications, request page, filters...
- Go to the Notifications page
- Filter by notifications about requests
- Check the state badges look good

Use request state badge as a component

---

src/api/app/views/event_mailer/_actions.text.erb

Prevent from throwing errors like:
```
ActionView::Template::Error
delayed_job#SendEventEmailsJob
Missing partial event_mailer/_release_action with {:locale=>[:en], :formats=>[[Truncated]
```

Add missing "release" action to submit actions mailer

---

src/backend/BSSched/BuildJob/Docker.pm

The code in BuildJob::add_container_deps relies on this to set the correct annotation.

[backend] Docker: make sure the base container cbdep comes last

---

src/api/app/controllers/webui/packages/build_reason_controller.rb

Avoid throwing a 500 error.
Fixes #16901.

Show an error message for build results of an scmsync project

---

src/api/spec/support/capybara.rb

When running feature specs some errors pop up:
1.3) Failure/Error: Unable to infer file and line number from backtrace
Selenium::WebDriver::Error::InvalidSessionIdError:
invalid session id
Disabling the use of shared memory seems to fix those errors because Chrome does not use /dev/shm which can be tight on memory on CI Pipelines or containers, and uses files in /tmp which can be a bit more forgiving in tight environments at the expense of some performance.

Fix capybara session errors

---

dist/Makefile
dist/obs-server.spec
dist/obs-setup
src/backend/BSSetup/Base.pm
src/backend/BSSetup/SUSE.pm
src/backend/bs_setup

* implements `service-container` setup task

First implementation of bs_setup

---

src/api/app/controllers/webui/groups_controller.rb
src/api/app/models/group.rb
src/api/app/views/webui/groups/edit.html.haml
src/api/app/views/webui/groups/index.html.haml
src/api/app/views/webui/groups/new.html.haml
src/api/config/routes/webui.rb
src/api/spec/controllers/webui/groups_controller_spec.rb

In order to improve the group subscriptions to different types of notifications, we start with providing a way to handle groups emails from the UI. Something that was only possible[ through API](https://api.opensuse.org/apidocs/index#/Groups/post_group__group_title_) so far.
Create:
Update email:
Actions column (mail_to and edit emails):

Handle group's email from web UI

---

src/api/app/controllers/source_controller.rb
src/api/public/apidocs/paths/source_project_name_package_name_cmd_copy.yaml

This parameter is implemented and passed directly to the backend for copying projects. But for the case of copying packages, it is not implemented.
See allowed parameters for that endpoint in the backend: https://github.com/openSUSE/open-build-service/blob/8467b52747940f80e6759f6c671cff968f0d0493/src/backend/bs_srcserver#L7784
Passing `withhistory=1` throws an error:
```
> curl -u Admin:opensuse -H 'accept: application/xml; charset=utf-8' -X POST 'http://localhost:3000/source/home:Admin/test?cmd=copy&package=test2&rev=upload&withhistory=1'
<status code="400" origin="backend">
<summary>unknown parameter 'withhistory'</summary>
</status>
```
Passing `withhistory=1` is simply ignored:
```
> curl -u Admin:opensuse -H 'accept: application/xml; charset=utf-8' -X POST …
```

Remove not implemented `withhistory` parameter from the API

---

src/api/app/models/role.rb
src/api/spec/models/role_spec.rb

We should handle exceptions of not found records in the controllers involving roles instead of in the Role model.

Don't override `find_by_title!` in roles

---

src/api/app/controllers/group_controller.rb
src/api/app/controllers/webui/groups_controller.rb
src/api/app/models/group.rb
src/api/spec/models/bs_request/find_for/group_spec.rb
src/api/spec/shared/examples/features/bootstrap_user_tab.rb

Handle exceptions of not found records in the groups controller instead of in the Group model. We want to preserve the text of the exception message: "Couldn't find Group ...".

Don't override `find_by_title!` in groups

---

src/api/app/components/bs_request_comment_component.html.haml

A comment on a line of a diff of a submit request can be outdated when, for example, the source package gets removed.
In those cases, show a message informing that the attachment point of the comment is outdated.

Inform of an outdated inline comment

---

src/api/app/controllers/source_attribute_controller.rb
src/api/public/apidocs/paths/source_project_name_attribute.yaml
src/api/public/apidocs/paths/source_project_name_package_name_attribute.yaml
src/api/test/functional/attributes_test.rb

Instead of return a response code 400, return a 501 Not Implemented response code for source attribute endpoints dealing with remote projects.
Fixes #16944.

Change 400 to 501 Not Implemented response

---

src/api/app/views/webui/comment/_comment_field.html.haml

It is not used anywhere in the file. It was removed in #16776

Remove entity_type local variable

---

src/api/app/models/package_issue.rb

These scopes were introduced in #2497, and substituted by Active Record queries in #10973.

Remove no longer used scopes in model PackageIssue

---

src/api/app/models/package.rb
src/api/app/models/package_issue.rb
src/api/app/models/update_notification_events.rb

We want to have an idea on how often retries of queries are triggered. Then we could take a decision on removing retries or not. See #16954.

Track retries of failed database queries

---

src/api/app/models/comment.rb
src/api/db/migrate/20241016135555_add_diff_columns_to_comments.rb
src/api/db/schema.rb

The final goal is to split the `diff_ref` column into the `diff_file_index` and `diff_line_number` columns. See: https://github.com/openSUSE/open-build-service/pull/16962#issuecomment-2416875280
1. Add new columns :arrow_left:
1. Write to all three columns
2. Backfill data from the old column to the new columns
3. Move reads from the old column to the new columns

Add `diff_file_index` and `diff_line_number` columns to table `comments`

---

src/backend/BSSched/BuildJob/Image.pm

The reason comes last for some reason.

[backend] fix arg order in Image::build

---

src/api/app/components/request_decision_component.html.haml
src/api/app/components/request_decision_component.rb
src/api/app/policies/bs_request_policy.rb
src/api/spec/policies/bs_request_policy_spec.rb

This will make easier to reuse the request policies outside of [RequestDecisionComponent](https://github.com/openSUSE/open-build-service/blob/d0c3746758f71cbc458a970d23283298e01b869c/src/api/app/components/request_decision_component.rb#L32)

Extract request policies out of RequestDecisionComponent

---

src/api/app/controllers/webui/comments_controller.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/views/webui/comment/_comment_field.html.haml
src/api/app/views/webui/request/_inline_comment.html.haml
src/api/app/views/webui/request/inline_comment.js.erb

Follow up to #16965.
1. Add new columns
1. Write to all three columns :arrow_left:
2. Backfill data from the old column to the new columns
3. Move reads from the old column to the new columns

Write to `diff_file_index` and `diff_line_number` columns

---

src/api/db/data/20241017123303_backfill_diff_fields_on_comments.rb
src/api/db/data_schema.rb

Follow up to #16966.
1. Add new columns
1. Write to all three columns
2. Backfill data from the old column to the new columns :arrow_left:
3. Move reads from the old column to the new columns

Backfill `diff_file_index` and `diff_line_number` columns on table `comments`

---

src/api/app/controllers/webui/comments_controller.rb

Some refactorings related to the soon to be removed `diff_ref` field in the `comments` table.

Don't pass unused parameters to `comment_list` partial

---

src/api/app/components/bs_request_activity_timeline_component.rb
src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/bs_request_comment_component.rb
src/api/app/components/comment_component.rb
src/api/app/components/diff_component.html.haml
src/api/app/components/diff_list_component.rb
src/api/app/controllers/webui/comments_controller.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/models/comment.rb
src/api/app/models/event/comment_for_request.rb
src/api/app/views/webui/comment/_comment_field.html.haml
src/api/app/views/webui/comment/_content.html.haml
src/api/app/views/webui/request/_add_inline_comment.html.haml
src/api/app/views/webui/request/_inline_comment.html.haml
src/api/app/views/webui/request/inline_comment.js.erb
src/api/config/routes/webui.rb
src/api/spec/controllers/comments_controller_spec.rb
src/api/spec/features/webui/requests/diff_comments_spec.rb
src/api/spec/features/webui/requests/submissions_spec.rb

Follow up to #16969.
1. Add new columns
1. Write to all three columns
2. Backfill data from the old column to the new columns
3. Move reads from the old column to the new columns :arrow_left:

Move reads from the `diff_ref` column to the new `diff_*` columns

---

src/api/app/models/comment.rb

These changes, somehow, got overlooked. They should have been included in #16971, in this step:
4. Move reads from the old column to the new columns
I noticed this while working on the next step:
5. Stop writing to the old column

Move overlooked reads from the `diff_ref` column to the new `diff_*`  columns

---

src/api/app/assets/stylesheets/webui/bootstrap_variables/options.scss
src/api/app/components/request_decision_component.html.haml

Rebased on top of https://github.com/openSUSE/open-build-service/pull/16960
It may happen that the upper "Pending Review" orange box and its content is not there, so the following box for the comment would have not rounded corners on top. This PR fixes it using rounded borders and moving upper with negative margin the comment box closer to the upper box, otherwise the side borders would be detached to the rounded comment box ones.

Fix decision box border

---

src/api/app/controllers/webui/comments_controller.rb
src/api/app/models/comment.rb
src/api/app/models/event/comment_for_request.rb
src/api/app/views/webui/comment/_comment_field.html.haml
src/api/app/views/webui/request/_inline_comment.html.haml

Follow up to #16971 and overlooked changes in #16992.
1. Add new columns
1. Write to all three columns
2. Backfill data from the old column to the new columns
3. Move reads from the old column to the new columns
4. Stop writing to the old column :arrow_left:

Stop writing to the `diff_ref` column

---

src/api/.rubocop_todo.yml
src/api/app/services/diff_parser.rb

Fixes https://github.com/openSUSE/open-build-service/issues/16997
When _the change_ content is an added **empty** line, the resulting diff is just `''`. This was breaking in the previous code, fixed now by skipping the case when the line change content is `nil`, indeed.
This specific corner case does not affect nor break the rest of the diff though.

Skip if line in nil

---

src/api/app/controllers/webui/request_controller.rb

This only happens when the request_action_changes method is being called and the request_show_redesign flag is off, as the `set_actions` method that fills `@actions` is not called.
One way to trigger this is via curl, simulating an AJAX call to /request/<number>/request_action/<action_id>/changes.
This makes sense as the data collected on those errors presents mostly no User-Agent header.
Fixes #16054

Return a 401 when there are no @actions loaded

---

src/api/app/controllers/webui/requests_listing_controller.rb

Previously, only the creators of a certain page of requests were listed.

Fix creators options for listing requests

---

src/api/app/controllers/concerns/webui/requests_filter.rb
src/api/app/controllers/webui/requests_listing_controller.rb

Only when also searching by text.

Don't pluck always involved requests' ids

---

src/api/app/views/webui/requests_listing/index.html.haml

Prevent from performing a COUNT on a query with `includes` and sorted elements. This will improve the performance of the first query, the one which counts the number of elements.
```
SELECT DISTINCT `bs_requests`.`priority` AS alias_0, `bs_requests`.`id` AS alias_1, number AS
alias_2, `bs_requests`.`id` FROM `bs_requests` INNER JOIN `bs_request_actions` ON `bs_request_actions`.`bs_request_id` = `bs_requests`.`id` LEFT OUTER JOIN `comments` ON `comments`.`commenta
ble_type` = 'BsRequest' AND `comments`.`commentable_id` = `bs_requests`.`id` LEFT OUTER JOIN `reviews` ON `reviews`.`bs_request_id` = `bs_requests`.`id` LEFT OUTER JOIN `labels` ON `labels`.`
labelable_type` = 'BsRequest' AND `labels`.`labelable_id` = `bs_requests`.`id` WHERE `bs_requests`.`state` = 'new' AND (`bs_requests`.`id` …
```

Check for `total_count` instead of `blank?`

---

src/api/app/views/webui/users/notifications/_notifications_list.html.haml

Instead of perfoming another query for checking for empty notifications, use the already cached `total_count` query result.
Related to #17046.

Improve performance of checking for notifications query

---

.github/workflows/create_diffend_io_links.yml

When we added a new gem, REMOVED_GEMS was empty, and the `basename` command crashed. Not anymore.
When there is nothing coming from ADDED_GEMS (because we remove the gem) or REMOVED_GEMS (because we add a new gem) `xargs` will not crash anymore.

Make xargs to ignore commands if stdin is empty

---

src/backend/bs_service

Include the real reason why the directory setup failed in the error so that the automatic retry code will detect that this is a transient error.

[backend] bs_service: fix error reporting

---

src/api/app/models/package_issue.rb

Before, the message got truncated because of too much data of the packages' issues.
Related to #16959.

Improve message for failed database queries

---

src/api/app/views/webui/requests_listing/_breadcrumb_items.html.haml

Before, the project name was shown twice.

Show package name in breadcrumbs of Request page

---

src/backend/bs_publish
src/backend/bs_sched

Early publishing breaks the archsync check done by the publisher.

[backend] bs_sched: disable early publishing if archsync is configured

---

src/api/app/controllers/webui/request_controller.rb

It reduces performance and does nothing useful, let's get rid of it

Remove unnecessary before_action to improve beta request performance

---

src/api/app/services/diff_parser.rb

In case of an unknown scenario, we rather want to be notified about it instead of a silent log line stored.

Raise exception instead of silent log

---

src/backend/bs_worker

The uri to published sources must not contain the multibuild flavor.
OBS-353

[backend] Fix SLSA source url of multibuild's

---

src/api/app/controllers/webui/appeals_controller.rb
src/api/app/controllers/webui/packages/build_log_controller.rb
src/api/app/controllers/webui/workflow_runs_controller.rb

The missed notification types are:
- Build Failures
- Workflow Runs
- Appealed Decisions
~Solves most of~ Fixes #17012.

Show notification toolbar for missed notification types

---

src/api/lib/tasks/dev.rake
src/api/lib/tasks/dev/notifications.rake
src/api/lib/tasks/dev/reports.rake
src/api/lib/tasks/dev/requests.rake

An already set up database must exists ahead (`rake dev:test_data:create`)
Run:
- `bundle exec rake dev:test_data:create_more_data[100]` if inside the container
- `docker compose run --rm frontend rake dev:test_data:create_more_data[100]` if outside of the container
where `[100]` can be any number you desire to flood your db with (the number represents the repetitions the create objects tasks are executed).

Create a large amount of dev data

---

src/api/app/views/webui/request/_action_text.html.haml

This causes a significant load on the backend whenever we try to load a request with many actions. Let's comment it out for now

Remove loading the revision details from the beta request

---

src/api/app/components/request_decision_component.html.haml
src/api/app/components/request_decision_component.rb
src/api/spec/features/beta/webui/maintenance_workflow_spec.rb

The proposal is about keeping separated all the different decision actions, but grouping the `accept request` ones. Accepting request can be made like:
1. Accept
2. Accept & make the submitter a maintainer of the target project/package
Due to the fact that the forward can be submitted to multiple choices, they requires checkboxes to be visible and selectable. The forwarding destinations are shown as checkboxes above the buttons

Request accept buttons into dropdown

---

src/api/app/components/action_seen_by_user_component.rb
src/api/app/views/webui/request/_action_text.html.haml
src/api/app/views/webui/request/_actions_details.html.haml

Reduces the amount of queries to the database for `bs_request_action_seen_by_user` from `bs_request_actions.count` to 1

Make sure seen_by_user only gets queried once for action details

---

src/api/app/components/action_seen_by_user_component.rb

This only worked when the `seen_by_user` value was true, but didn't account for `nil` and `false` being different results

Make sure seen_by_user is set before fetching the database

---

src/backend/BSPGP.pm
src/backend/BSRepServer/BuildInfo.pm
src/backend/BSSched/BuildJob/ProductCompose.pm
src/backend/bs_repserver
src/backend/bs_srcserver

This allows the user to pass a recipe file or a cpio archive with files of the package.
jsc#OBS-352

[backend] add a POST method for sourceinfo

---

src/backend/BSContar.pm

The json from helm charts may contain unicode.

[backend] BSContar: turn of utf8 flag when creating a blob from data

---

src/api/app/views/webui/package/show.html.haml
src/api/app/views/webui/project/show.html.haml
src/api/app/views/webui/request/_request_header.html.haml
src/api/app/views/webui/request/_show_overview.html.haml
src/api/app/views/webui/request/beta_show.html.haml
src/api/app/views/webui/request/show.html.haml
src/api/app/views/webui/watched_items/toggle_watched_item.js.erb

`WatchlistIconComponent` inherits from `WatchlistComponent`. However, that doesn't mean we should pass all the parameters. In fact, `WatchlistIconComponent` never uses the following parameters: `projects`,
`packages` and `bs_requests`.

Don't pass not needed arguments to WatchlistIconComponent

---

src/api/config/routes/api.rb
src/api/config/routes/webui.rb

Those routes are used in the our web ui, even if they serve json they are not specific to the API.

Move requests' json routes to the webui router file

---

src/api/app/views/webui/shared/_open_requests.html.haml

While adapting a link inside, I realized that this partial is nowhere used.

Remove _open_requests partial

---

src/api/app/controllers/webui/project_controller.rb
src/api/app/controllers/webui/projects/bs_requests_controller.rb
src/api/app/views/webui/project/_breadcrumb_items.html.haml
src/api/app/views/webui/project/_tabs.html.haml
src/api/app/views/webui/project/side_links/_incident_project.html.haml
src/api/app/views/webui/project/side_links/_requests.html.haml
src/api/app/views/webui/projects/pulse/_pulse_list_requests_box.html.haml
src/api/app/views/webui/staging/workflows/_infos.html.haml

In order to refactor the request listing controller, and
to move the logic to the appropriate bs_request_controller
we first have to change the paths and redirect to the old
one inside the controller. This enables us to do the changes
in smaller chunks.

Link to beta view for project requests

---

src/api/app/controllers/webui/packages/bs_requests_controller.rb
src/api/app/views/webui/packages/bs_requests/_breadcrumb_items.html.haml
src/api/app/views/webui/packages/bs_requests/index.html.haml

Depends on #17145.
This PR is moving all the logic related to package/requests from `requests_listing_controller` to `packages/bs_requests` controller.

Refactor package requests under packages/bs_request controller

---

src/api/app/assets/javascripts/webui/users_groups.js

Prevent users who may have revoked their own maintainer permissions from continuing to access a page with links they should no longer use. The page will now reload to reflect the updated permission status, ensuring proper access control.
In your development environment, or in the review-app:
- As user `User1`:
- Create a package `package1`
- Give Maintainer and Bugowner roles to `User2` to `package1`
- As user `User2`:
- Remove Maintainer role for user `User2` in users of the package `package1`
After following the steps mentioned above:
- before: `User2` could click on more checkboxes or access more links. This should not be allowed.
- after: the page is reload and `User2` is not able to click on unpermitted links.
This not only happens for packages but also for projects.
Fixes #16433. …

Reload page when maintainer permissions are removed

---

src/api/app/views/layouts/webui/_places.html.haml
src/api/app/views/webui/users/tasks/index.html.haml
src/api/config/routes/webui.rb
src/api/spec/features/beta/webui/requests_index_spec.rb
src/api/spec/routing/webui/users/requests_spec.rb

Moving this since you can currently access a page like https://build.opensuse.org/users/dimstar/requests, which still displays your own requests, which makes no sense

Switch user requests path to my requests

---

src/api/app/views/webui/shared/bs_requests/_form.html.haml

**Note**: within the same context, the waiting time for user inputs and clicks is extended up to 2 seconds.

Freeze filters while submitting form and reloading

---

src/api/app/models/notification.rb
src/api/app/models/notification_bs_request.rb
src/api/app/models/notification_comment.rb
src/api/app/models/notification_group.rb
src/api/app/models/notification_package.rb
src/api/app/models/notification_project.rb
src/api/app/models/notification_report.rb
src/api/app/models/notification_workflow_run.rb
src/api/db/migrate/20241205104819_change_notification_event_payload_to_mediumtext.rb
src/api/db/schema.rb

This change was missing when the payload colum size of table events was changed.
Related to #15649.

Change event_payload column size from TEXT to MEDIUMTEXT

---

src/api/app/assets/stylesheets/webui/requests.scss
src/api/app/views/webui/shared/bs_requests/_form.html.haml
src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml
src/api/spec/features/beta/webui/package_requests_spec.rb
src/api/spec/features/beta/webui/project_requests_spec.rb
src/api/spec/features/beta/webui/requests_index_spec.rb

Flatten filters to render the content at the same level of the title. Due to the fact the filter content may grow a lot and become a very long column, each filter are now collapsible.
**With creator filter** (which is disabled at the moment anyway)

Uniform request filters to be accordion items

---

src/api/app/controllers/webui/request_controller.rb

Substitute the call to the overwritten `Project.find_by_name` finder method with plain ActiveRecord finder methods.
Fix #17176.

Don't error when checking user roles on a project

---

src/api/app/assets/stylesheets/webui/breadcrumbs-component.scss
src/api/app/controllers/webui/packages/binaries_controller.rb
src/api/app/views/webui/package/_breadcrumb_items.html.haml

Add the multibuild flavor to the breadcrumbs as text.
Fixes partially #16234.

Show multibuild flavor in Repository State pages

---

src/api/app/assets/javascripts/webui/project_monitor.js

Instead of linking to a package show page with the form `package_name:multibuild_flavor`, link to `package_name`, without multibuild flavor. Package's show pages for multibuild flavors don't exist as such.
Fix #16234.

Change the link of a package with a multibuild flavor

---

src/api/spec/models/bs_request/embargo_date_spec.rb

The factories use relative dates but the spec use fixed dates, so we use relative dates for all the set up.

Use relative dates to fix time dependent spec

---

src/api/app/datatables/package_datatable.rb

Makes sure they are visually distinct, not to be confused with each other

Distinguish the link badge from labels

---

src/api/docker-files/Dockerfile
src/api/spec/support/capybara.rb

This PR reverts part of the changes from https://github.com/openSUSE/open-build-service/pull/16860
The changes in that PR didn't actually fix anything. The errors we've been hitting in our CI pipelines are probably fixed by the maintenance updates of chromedriver

Revert using the chromedriver set by selenium manager

---

src/api/app/models/package.rb

Follow up to #16956.
We want to deploy these pull requests separately.
This PR is the third of a group of pull requests:
1. #16954
1. #16956
1. **Remove unnecesary retrying on updating a package**

Remove unnecesary retrying on updating a package

---

src/backend/BSXML.pm
src/backend/bs_signer

When building UKIs (unified kernel images) with mkosi we need to do multi-stage signing. First the image is built from packages, with the kernel/initrd/etc being put together. The TPM2 policy digests are calculated, and need to be signed.
After the digests signatures are retrived after the first signing stage, they are inserted in the UKI, which itself needs to be signed for secure boot, hence the second consecutive signing stage.
In order to avoid infinite loops, keep a count of consecutive signing stages in the info file, and stop after 10 no matter what.
Tested on an OBS VM. Example project: https://build.opensuse.org/package/live_build_log/home:bluca:branches:home:bluca:systemd/debian-image/Debian_Testing_images/x86_64
In that build we end with:
```
[   41s] …
```

[backend]: support multi-stage signing for mkosi

---

src/api/app/components/bs_request_priority_badge_component.rb

After last changes, showing labels in the priority filter was broken.
Thanks @ncounter for reporting it.

Show priority labels

---

src/api/app/components/bs_request_action_description_component.rb
src/api/app/components/bs_request_action_source_and_target_component.rb
src/api/app/views/webui/shared/bs_requests/_request_item.html.haml
src/api/spec/components/previews/bs_request_action_description_component_preview.rb

This PR adapts the `BsRequestActionDescriptionComponent` output in order to return the same value shaped in html or text only format.
This addresses all `bs_request` types but only when it is a _single action request_. In case of a _multi action_ one it requires some different customization which is out of this PR scope.

Unify request description of list page and detail page

---

src/api/config/brakeman.ignore

We want to ignore the warning regarding Ruby 3.1.6 EOL for the time being (see [this](https://github.com/openSUSE/open-build-service/actions/runs/13050288201/job/36408851351?pr=17315). Once we have Ruby 3.2 set, we'll revisit this again.
We'll track this ignore in [here](https://trello.com/c/Tg04a4YW/212-ignore-the-brakeman-warning-regarding-ruby-316-eol)

Update brakeman ignore file

---

src/backend/bs_srcserver

patchinfo containers may contain _scmsync.obsinfo files. we must not complain about them when they get comitted.
Esp. after a bugfix in the scm bridge this happens regulary now.

[backend] accept _scmsync.obsinfo in patchinfo's

---

src/api/db/data/20250131094818_nullify_targets_on_bs_request_actions.rb
src/api/db/data_schema.rb

Nullify `target_project_id` and `target_package_id` in `bs_request_actions` if the project or/and package no longer exist.
Follow-up to #17310.

Add data migration to nullify target fields on bs_request_actions

---

src/backend/bs_publish

mkosi DDIs (.raw) and recipe are already published in the main repo directory.
Publishing in a per-arch subdirectory breaks 'Repotype: checksumsfile' which
is needed to publish a SHA256SUMS signed file, so that systemd-sysupdate can
download images from OBS.
mkosi artifacts can be created with the architecture in the filename with a
simple option in the recipe anyway, so there's no clash if that is used.
Manifests, UKIs and more also get an individual shasum file, and it gets
signed, so publish those signatures too. And also publish the ascii signature
for the SHA256SUMS file.

[backend] bs_publish: do not use arch-specific directory for mkosi artifacts and publish mkosi .asc signatures for all files

---

src/api/app/components/bs_request_action_description_component.rb

Fixes https://trello.com/c/cWOnuYAW/88-add-role-requests-overflow
Prevent this from happening:

Show request creator text in request index

---

src/api/db/data/20250131143734_backfill_sources_on_bs_request_actions.rb
src/api/db/data_schema.rb

Backfill `target_project_id` and `target_package_id` in `bs_request_actions` if they were `NULL` and the project or/and package exist.
Follow up to #17335.

Add data migration to backfill source fields on `bs_request_actions`

---

src/api/db/data/20250131094818_nullify_targets_on_bs_request_actions.rb

Prevent from updating bs_requests when updating bs_request_actions.
Related to #17324.

Fix bs_request_actions nullify data migration

---

src/api/db/data/20250131143734_backfill_sources_on_bs_request_actions.rb

Prevent from updating bs_requests when updating bs_request_actions.
Related to #17326.

Fix bs_request_actions backfill data migration

---

src/api/db/data/20250131094818_nullify_targets_on_bs_request_actions.rb

We use left joins to make the script simpler and hopefully faster.
This statement should tell us if the data migration is working, as it should decrease as it runs:
```
BsRequestAction.joins('left join projects on bs_request_actions.target_project_id = projects.id where bs_request_actions.target_project_id IS NOT NULL AND projects.id IS NULL ').count
```

Make the BsRequestAction target nullification simpler

---

src/api/db/data/20250131094818_nullify_targets_on_bs_request_actions.rb

Looks like writing it by hand needs a bit more sql statements to make it compatible with an update statement, so we let ActiveRecord craft it for us.
Fixes #17354

Make the data migration's left join update compatible

---

src/api/app/views/layouts/webui/_places.html.haml
src/api/app/views/layouts/webui/_top_navigation.html.haml

There are a lot of places that are specific to the logged in User. So far they are only reachable through visiting the profile page. Also add them to the personal navigation.

Extend Personal Navigation

---

src/api/lib/tasks/data_backfill.rake

The rake task is a replacement for a data migration. After running it, there is no requirement to perform the data migration. For this reason, we have to mark the data migration as performed after the task has been performed.

Mark data migration as executed after replacing rake task is performed

---

src/api/app/components/card_component.html.haml
src/api/app/components/token_card_component.html.haml
src/api/app/models/token.rb
src/api/app/models/token/rebuild.rb
src/api/app/models/token/release.rb
src/api/app/models/token/service.rb
src/api/app/models/token/workflow.rb
src/api/app/views/webui/users/tokens/show.html.haml
src/api/db/migrate/20250211133315_add_enabled_to_token.rb
src/api/db/schema.rb

Add a column `enabled` to the table `tokens` as the first step to implement token authorization circuit breaker.
Also, modify the list and show views for the tokens of a user to indicate when a token is disabled.
**Note:** I used the rails console to modify the `enabled` field of the tokens to create these screenshots. The pull requests to add the enable/disable functionality will come after this one gets approved and merged.

Add `enabled` column to `tokens` table

---

ReleaseNotes-2.10.24
docs/api/api/obs.rng
docs/api/api/package.rng
src/api/test/functional/source_controller_test.rb
src/backend/BSXML.pm
src/backend/bs_service

Allow to reference remote project or package instance which get fed via scmsync git. The source content is transparent for older OBS instances, but they need to accept the additional xml element.
@DimStar77 could you test if a linkpac to a remote using scmsync is working with this?

2.10 scmsync compability

---

src/api/app/controllers/webui/users/tokens_controller.rb
src/api/app/views/webui/users/tokens/edit.html.haml
src/api/spec/controllers/webui/users/tokens_controller_spec.rb

Follow up to #17363.
Enabled | Disabled
:-------------------------:|:-------------------------:

Allow to disable or enable a token from the web UI

---

src/backend/bs_publish

The UEFI spec for http boot requires that either a file has MIME type of a particular value, which we can't do on published repos, or the image has a '.img' suffix. Mkosi just added support for building UKIs with this suffix, as an option, for this use case.

[backend] bs_publish: also publish mkosi .img files

---

src/api/app/components/workflow_run_row_component.html.haml
src/api/app/views/webui/users/tokens/show.html.haml

Prevents displaying the workflow run repository in the index listing, to avoid visual clutter if possible. The full list of repositories that were ever used is also listed in token show page

Show workflow run repository link only when necessary

---

src/api/app/controllers/source_controller.rb

When the package name is `_pattern` the code does not set the `@package` variable. So we need to avoid calling the command if we have no package to work on.
Fixes #17305

Prevent the linktobranch command to work when there is no @package

---

docs/api/api/token.rng
docs/api/api/token.xml
docs/api/api/tokenlist.rng
docs/api/api/tokenlist.xml
src/api/app/controllers/person/token_controller.rb
src/api/app/models/token.rb
src/api/app/views/person/token/index.xml.builder
src/api/config/routes/api.rb
src/api/public/apidocs/components/schemas/person_tokens.yaml
src/api/public/apidocs/components/schemas/token.yaml
src/api/public/apidocs/paths/person_login_token.yaml
src/api/public/apidocs/paths/person_login_token_id.yaml
src/api/spec/controllers/person/token_controller_spec.rb
src/api/test/functional/backend_test.rb

For reviewers:
- Create a token in your development environment with the user Admin.
- Test the endpoint:
- with `osc`: `osc -A http://localhost:3000 api -X PUT '/person/Admin/token/$TOKEN_ID?enabled=false'`, or
- with `curl`: `curl -u Admin:$PASSWORD -H 'Content-Type: application/octet-stream' -H 'accept: application/xml' -X PUT 'http://localhost:3000/person/Admin/token/$TOKEN_ID?enabled=false'`
You can check the new documented endpoint in the review-app, with this [link](https://obs-reviewlab.opensuse.org/eduardoj-featureworkflow_token_circuit_breaker_api/apidocs/index#/Person/put_person__login__token__id_).

Introduce the `enabled` token attribute into the tokens' API endoints

---

src/api/app/models/workflow_run.rb
src/api/spec/models/workflow_run_spec.rb

~Depends on #17380.~
Mark the token as not enabled if we receive an unauthorized or a forbidden response.

Introduce circuit breaker for tokens with authorization problems

---

.rubocop.yml
src/api/.rubocop.yml

Follow up to #17391.
Prevents from throwing a warning about `rubocop-performance` supporting extension plugin.
See: https://docs.rubocop.org/rubocop/plugin_migration_guide.html

Move rubocop-performance from `require:` to `plugins:`

---

src/api/app/models/bs_request_action.rb

After backfilling the `source_project_id` and `source_package_id` fields, we can rely in this associations instead of performing queries with methods.

Remove source methods from BsRequestAction model

---

src/api/app/controllers/concerns/webui/requests_filter.rb
src/api/app/models/bs_request.rb
src/api/app/models/bs_request/find_for/query.rb
src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml
src/api/spec/features/beta/webui/requests_index_spec.rb

Request index: filter by source/target project

---

src/api/spec/features/beta/webui/requests_index_spec.rb

https://trello.com/c/Ur7ALglM
On local setup:
`time rspec ./spec/features/beta/webui/requests_index_spec.rb`
**Before**
real    0m59.635s
user    0m43.092s
sys     0m7.101s
**After**
real    0m41.460s
user    0m42.139s
sys     0m6.736s

Speed up test: trigger submit form instead of waiting for the timeout

---

src/api/app/controllers/concerns/webui/requests_filter.rb
src/api/app/controllers/webui/project_controller.rb
src/api/app/views/webui/shared/bs_requests/_form.html.haml
src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml
src/api/config/routes/webui.rb

Make the staging project filter an autocomplete async input field under the hood.
https://trello.com/c/D2jLGmTZ
Before, it was a sync loaded list of staging projects at page loading time, then filtered on the frontend side.
After, it is an async list that loads the partial matching names via ajax dynamically

Request filter staging projects autocomplete

---

src/api/app/assets/javascripts/webui/content-selector-filters.js
src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml

Autosubmit gets triggered after the timeout only on certain filter inputs, the ones with `auto-submit-on-change` wrapper class.
Autocomplete searchable inputs instead wait for the user to press the `enter` key or click on the `fa-search` (AKA the lens icon) of the input field.

Let searchable inputs wait user interaction instead of autosubmit

---

src/api/app/controllers/concerns/webui/requests_filter.rb
src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml

Missing a `compact_blank!` cleanup on the returned values.
Fixing a type in the input name

Staging project filter without blank elements

---

dist/t/Makefile

Run OpenQA smoketest, on `build install` it fails with
```
An error occurred while installing racc (1.7.1), and Bundler cannot continue.
Make sure that `gem install racc -v '1.7.1' --source 'https://rubygems.org/'` succeeds before bundling.
In Gemfile:
apparition was resolved to 0.6.0, which depends on
capybara was resolved to 3.39.2, which depends on
xpath was resolved to 3.2.0, which depends on
nokogiri was resolved to 1.15.3, which depends on
racc
```
because it misses the `gcc` lib to compile `racc 1.7.1`
E.g.: https://openqa.opensuse.org/tests/4883480#step/rspec_webui_tests/6
Same as in master https://github.com/openSUSE/open-build-service/pull/15744

Add missing gcc lib to compile racc gem on install

---

src/api/app/components/workflow_run_filter_component.html.haml
src/api/app/views/webui/users/notifications/_notification_filter.html.haml

Fixes https://github.com/openSUSE/open-build-service/issues/17452
We changed the implementation in request index since https://github.com/openSUSE/open-build-service/pull/17414, but the event subscription and behavior for filters is shared across requests/notifications/workflowruns

Bugfix: missing class to autosubmit filters

---

src/api/app/assets/javascripts/webui/content-selector-filters.js

At the moment we wait for user input to submit filters when using the autocomplete component.
Now that we fixed the former undesired behavior of submiting on `keyup` (it was firing the submit too early on typing on the autocomplete input field, the fix introduced by https://github.com/openSUSE/open-build-service/pull/17414), we can now improve it and make it more comfortable by auto-submiting the filters form on `change` of the autocomplete. This can be done now because the `change` event happens only on pressing enter (already handled by default by the form in the browser), or by clicking on an element of the autocomplete dropdown list or losing the focus from the input. These two last events are the target handler of this PR.
As you can see in the example below, typing in the …

Autosubmit on change of autocomplete input too

---

src/api/app/views/webui/shared/bs_requests/_requests_filter.html.haml

In `project/requests` and `package/requests` the page is wrapped by a `div.card` HTML tag, which makes the `h6` title behave a little different in terms of style. Only `Reviewers` filter title is an `h6` others don't. This PR aligns the style of it to the rest of the page.

Fix filter title style for consistency

---

src/backend/bs_mkarchrepo

The `depends` file no longer exists in the ArchLinux repository db file.
```
$ find ./*/ -type f -printf "%f\n" | sort | uniq
desc
```
The corresponding field in the depends file is now provided by desc.
```
$ cat ./*/desc  | grep "^%" | sort | uniq
%ARCH%
%BASE%
%BUILDDATE%
%CHECKDEPENDS%
%CONFLICTS%
%CSIZE%
%DEPENDS%
%DESC%
%FILENAME%
%ISIZE%
%LICENSE%
%MAKEDEPENDS%
%MD5SUM%
%NAME%
%OPTDEPENDS%
%PACKAGER%
%PGPSIG%
%PROVIDES%
%REPLACES%
%SHA256SUM%
%URL%
%VERSION%
```

[backend] bs_mkarchrepo: merge depends fields into desc

---

src/backend/BSSSL.pm

I.e. use a "atomic swap" to get the old context and set it to undef.

[backend] BSSSL: try to the Net::SSLeay::free call in an atomic way

---

src/api/app/models/package.rb
src/api/app/models/project.rb
src/api/app/models/user.rb

We need to ask for distinct bs_requests rows because we're gonna get an extra bs_request row for each action that request is having...

Fix request duplicates

---

src/api/app/controllers/webui/project_controller.rb
src/api/app/helpers/webui/project_helper.rb
src/api/app/views/webui/project/_show_actions.html.haml
src/api/app/views/webui/project/_side_links.html.haml
src/api/app/views/webui/project/show.html.haml
src/api/app/views/webui/project/show_actions/_modify_project.html.haml
src/api/app/views/webui/project/show_actions/_patchinfo.html.haml
src/api/app/views/webui/project/side_links/_incident_project.html.haml
src/api/spec/controllers/webui/project_controller_spec.rb

Make use of the project instance variable to retrieve if a project has patchinfos, instead.

Drop `has_patchinfo` view variable

---

.github/workflows/comment_diffend_io_links_to_pr.yml

This change should have been introduced in #16942.

Fix parameter names for comment-pull-request action

---

.obs/workflows.yml

We use Leap 15.6 since 2.10.23.

Use Leap 15.6 in SCM/CI tests

---

src/api/app/controllers/group_controller.rb
src/api/app/controllers/webui/groups_controller.rb
src/api/app/controllers/webui/users_controller.rb
src/api/app/models/group.rb

Apply sorting by title only when neccessary.
The default scope had a negative impact on some database queries using the `join` clause.

Remove default scope from Group model

---

src/api/app/models/update_notification_events.rb

Also unifies the way database errors are reported. Fixes #16953.
This PR is the first of a group of pull requests:
1. **Remove unnecesary retrying on creating events**
1. #16956
1. #16957

Remove unnecesary retrying on creating events

---

src/backend/BSSrcServer/Remote.pm
src/backend/bs_srcserver

This limits the parallelism of the src server interconnect requests to a number of slots.

[backend] add interconnect_serialize_slots config option

---

src/api/app/models/project.rb

Merging after_initialize and init into a single method `init_defaults`. This ensures more clarity.

Merge after_initialize block and init method

---

src/api/app/assets/stylesheets/webui/application.scss
src/api/app/assets/stylesheets/webui/blame.scss
src/api/app/controllers/webui/packages/files_controller.rb
src/api/app/lib/backend/api/sources/package.rb
src/api/app/views/webui/package/_file.html.haml
src/api/app/views/webui/packages/files/blame.html.haml
src/api/config/routes/webui.rb
src/api/spec/cassettes/Webui_Packages_FilesController/DELETE_destroy/with_no_permissions/1_3_4_1.yml
src/api/spec/cassettes/Webui_Packages_FilesController/DELETE_destroy/with_no_permissions/1_3_4_2.yml
src/api/spec/cassettes/Webui_Packages_FilesController/DELETE_destroy/with_not_successful_backend_call/1_3_2_1.yml
src/api/spec/cassettes/Webui_Packages_FilesController/DELETE_destroy/with_successful_backend_call/1_3_1_1.yml
src/api/spec/cassettes/Webui_Packages_FilesController/DELETE_destroy/with_successful_backend_call/1_3_1_2.yml
src/api/spec/cassettes/Webui_Packages_FilesController/DELETE_destroy/with_successful_backend_call/1_3_1_3.yml
src/api/spec/cassettes/Webui_Packages_FilesController/DELETE_destroy/with_successful_backend_call/1_3_1_4.yml
src/api/spec/cassettes/Webui_Packages_FilesController/GET_blame/groups_lines_correctly.yml
src/api/spec/cassettes/Webui_Packages_FilesController/GET_blame/parses_lines_correctly.yml
src/api/spec/cassettes/Webui_Packages_FilesController/GET_blame/sets_blame_info_instance.yml
src/api/spec/cassettes/Webui_Packages_FilesController/GET_show/the_file_comes_from_an_scmsync_project/1_4_1_1.yml
src/api/spec/cassettes/Webui_Packages_FilesController/GET_show/the_file_comes_from_an_scmsync_project/1_4_1_2.yml
src/api/spec/controllers/webui/packages/files_controller_spec.rb
src/api/spec/fixtures/files/aaa_base.spec.blame

Allows for blaming files in the webui

Implement blame view for files

---

src/api/.database_consistency.todo.yml
src/api/app/models/architecture.rb
src/api/db/data/20250312082028_set_architectures_available_field_to_false.rb
src/api/db/data_schema.rb
src/api/db/migrate/20250312082500_add_not_null_to_architectures_available.rb
src/api/db/schema.rb

That way we stop having three values for that column: true, false and null, and we can get rid of the issue in the
database_consistencty.todo.yml
See https://github.com/djezzzl/database_consistency/wiki/threestatebooleanchecker

Change default value for available column from architectures table to false

---

src/backend/BSServer.pm
src/backend/BSStdServer.pm

We now use a sub-pid when there is a reqid (AJAX) or we have a keepalive request.

[backend] logging: always log the process pid

---

src/api/app/assets/config/manifest.js
src/api/app/assets/javascripts/webui/application.js
src/api/app/assets/javascripts/webui/report.js
src/api/app/views/webui/shared/_report_modal.html.haml

`report.js` is the _source library_ of function definitions for reports, so let's load it only when the context requires it.
Also, use the `$(document).ready` locally where the context requires.

Load js report on purpose

---

dist/obs-bundled-gems.spec
dist/obs-server.spec

SLFO does not provide it anymore and it seems not be needed anymore on first glance.

[dist] drop build dependency to python2

---

src/api/app/controllers/build_controller.rb

The user got an error, if he has maintainer rights only the package sources, but he wanted to operate on a flavor.
Therefore strip flavor part to check for local package object here
Issue: #17548

[api] fix commands on package flavors

---

src/api/app/controllers/webui/request_controller.rb

Fixes #17287
The note mentioned in #17287 is being displayed to users who are part of a group, even if they do not have the maintainer role. This note should only be visible to users who are maintainers, either directly or through a group.

Remove project maintainer hint for non-maintainers

---

src/api/app/views/layouts/webui/_unread_notifications_counter.html.haml

Fix https://github.com/openSUSE/open-build-service/issues/17171
I did not had the chance to reproduce it and see it failing in a complete use case.
But after some investigation my conclusion is that it could it be something like:
- being on Beta Request Index
- load a request page (package, project, my requests.....any of these)
- in another tab, toggle off the Beta Request Index
- back on the request page, reload it or simply change a filter value (it submits the form and reload the page)
- Beta and NON Beta request pages have different URL, so there is an internal redirect to load the correct page
- the NON Beta request page has an ajax call (xhr) for the `datatables`
- the `webui_controller` is set to `before_action :set_unread_notifications_count, unless: -> { request.xhr? }`
- …

Fix: do not crash if counter is nil

---

src/api/app/controllers/webui/webui_controller.rb
src/api/spec/cassettes/User_s_admin_edit_page/remove_admin_rights_from_user.yml
src/api/spec/features/webui/users/user_admin_edit_spec.rb

Prevent a user trying to access a page without admin permissions from performing a redirect to the same page.

Don't redirect back on not required_admin before filter

---

src/api/spec/factories/download_repository_factory.rb

Get rid of unnecessary code. A RepositoryArchitecture will allways be created on an existing Architecture.

Refactor download repository factory

---

src/api/app/controllers/webui/package_controller.rb
src/api/app/models/branch_package.rb
src/api/app/models/branch_package/errors.rb
src/api/app/views/webui/package/_show_actions.html.haml
src/api/app/views/webui/package/show.html.haml
src/api/db/attribute_descriptions.rb
src/api/db/data/20250326100650_add_reject_branch_to_attrib_types.rb
src/api/db/data_schema.rb
src/api/db/seeds.rb
src/api/test/fixtures/attrib_types.yml
src/api/test/functional/attributes_test.rb
src/api/test/functional/source_controller_test.rb

allows to send old time users a helpful message how to proceed.
The webui part is not tested at all by me, it should just hide the branch button in this case.

Reject branching support

---

src/api/app/components/diff_list_component.html.haml
src/api/app/components/sourcediff_component.html.haml
src/api/app/components/sourcediff_component.rb
src/api/spec/cassettes/SourcediffComponent/when_testing_the_preview/renders_the_preview.yml
src/api/spec/cassettes/SourcediffComponent/with_a_request_with_a_submit_action/renders_the_turbo_frame.yml

Since the files inside of the binaries can't be individually loaded from the backend, load them on first load instead.

Only lazy load the files that can be loaded from the backend

---

src/backend/bs_srcserver

Queue them if the repo server is not available instead of dropping them.

[backend] bs_srcserver: make sure project/package events do not get lost

---

codecov.yml

This reverts commit 61e6533fedf04c5d38f8329d2fb42a0d2c7fed33.
It didn't make a difference, after trying this change on master with this pull request https://github.com/openSUSE/open-build-service/pull/17655.

Revert "Make Codecov report a successful status if there is no report"

---

src/api/app/assets/javascripts/webui/comment.js
src/api/app/views/webui/request/request_action_changes.js.erb

- deduplicate handler code for the same event on different elements
- hook the listener to the document instead of retriggering the handler implementation on new elements

Refactor comment js

---

src/api/app/controllers/webui/users/block_controller.rb
src/api/app/models/comment.rb
src/api/app/models/event_subscription/find_for_event.rb
src/api/app/models/user.rb
src/api/app/services/notification_service/web_channel.rb
src/api/spec/services/notification_service/notifier_spec.rb

Ensures that blocked users can't send notifications to people who blocked them

Don't send notifications from blocked users

---

src/api/app/components/reports_modal_component.html.haml
src/api/app/components/request_decision_component.html.haml
src/api/app/policies/canned_response_policy.rb
src/api/app/views/webui/comment/_comment_field.html.haml
src/api/config/initializers/flipper.rb
src/api/spec/controllers/webui/users/canned_responses_controller_spec.rb
src/api/spec/features/webui/canned_responses_spec.rb
src/api/spec/features/webui/comments_spec.rb

Allows for reuse with other opportunities without requiring content moderation

Move canned responses into its own beta feature

---

src/api/app/models/user.rb

Since Rails Version 7.1 an exception is raised when defining an enum that is not backed by the database column.
For reference see:
https://github.com/rails/rails/issues/45668
and
https://github.com/rails/rails/pull/45734
In order to still do this, we can explicitly define the type via `attribute` on the models.
For reference see:
https://github.com/rails/rails/pull/49769
This is currently blocking the `migration_tests` in our CI.
See CI Pipeline of https://github.com/openSUSE/open-build-service/pull/17696

Fix error for enum not backed by database column

---

src/api/app/models/report.rb
src/api/db/migrate/20250410141906_add_reporter_to_reports.rb
src/api/db/schema.rb

The first step to rename the user association on reports to reporter.
In order to not cause any downtime on our production systems, this will be performed in steps:
-> 1. Add the new column to the reports table (can be null for now).
2. Adapt code to write to both columns (user and reporter).
3. Back fill the reporter column.
4. Set not null constraint on reporter column and association.
5. Delete the user column from the reports table.
~**NOTE**: CI currently failing due to the issue fixed by https://github.com/openSUSE/open-build-service/pull/17697~

Add reporter to report db table

---

src/api/app/models/event/base.rb
src/api/spec/models/event/base_spec.rb

Don't send notifications for events outside of notification_events

---

src/api/.database_consistency.todo.yml
src/api/app/components/reports_modal_component.html.haml
src/api/app/controllers/webui/reports_controller.rb
src/api/app/models/report.rb
src/api/app/policies/report_policy.rb
src/api/spec/factories/reports.rb
src/api/spec/features/beta/webui/decisions_spec.rb

The second step to rename the user association on reports to reporter. In order to not cause any downtime on our production systems, this will be performed in steps:
1. Add the new column to the reports table (can be null for now). 
2. Adapt code to write to both columns (user and reporter). <-
3. Back fill the reporter column.
4. Set not null constraint on reporter column and association.
5. Delete the user column from the reports table.
~~Depends on: https://github.com/openSUSE/open-build-service/pull/17696~~

Use reporter association for report creation

---

src/backend/bs_signer

This allows us to deal with rpmv6 packages even if the installed rpm version does not support it.

[backend] bs_signed: use sign --delsign to remove rpm signatures

---

src/api/app/components/reports_modal_component.html.haml
src/api/app/components/reports_notice_component.rb
src/api/app/controllers/webui/reports_controller.rb
src/api/app/helpers/webui/notification_helper.rb
src/api/app/models/event/base.rb
src/api/app/models/report.rb
src/api/app/models/user.rb
src/api/app/policies/appeal_policy.rb
src/api/app/policies/report_policy.rb
src/api/app/views/webui/reports/create.js.erb
src/api/app/views/webui/reports/show.html.haml
src/api/spec/factories/reports.rb
src/api/spec/features/beta/webui/decisions_spec.rb
src/api/spec/mailers/event_mailer_spec.rb
src/api/spec/policies/appeal_policy_spec.rb
src/api/spec/policies/report_policy_spec.rb

Now that we safely migrated to report reporter, we can
remove the usage of report user from the codebase.
1. Add the new column to the reports table (can be null for now). [DONE]
2. Adapt code to write to both columns (user and reporter). [DONE]
3. Back fill the reporter column. [DONE]
4. Switch no null constraint from user to reporter column [DONE]
5. Remove all references to reports user in the codebase and ignore user_id
column. <--
6. Delete the user column from the reports table
~~Depends on: https://github.com/openSUSE/open-build-service/pull/17700~~

Drop usage of user on reports

---

src/api/app/models/report.rb
src/api/db/migrate/20250414154434_drop_user_id_from_reports.rb
src/api/db/schema.rb

Last step of migrating from user to reporter on reports. Now we can safely drop the `user_id` column.
1. Add the new column to the reports table (can be null for now). [DONE]
2. Adapt code to write to both columns (user and reporter). [DONE]
3. Back fill the reporter column. [DONE]
4. Switch no null constraint from user to reporter column. [DONE]
5. Remove all references to reports user in the codebase and ignore user_id column. [DONE]
6. Delete the user column from the reports table. <---
7. Drop `ignored_columns` line 
~~Depends on: https://github.com/openSUSE/open-build-service/pull/17713~~

Drop user_id column from reports table

---

src/api/app/models/report.rb

This is just needed until the `user_id` column is dropped from the reports table to not cause possible interruptions on production. This can be dropped after the migration has run.
Depends on https://github.com/openSUSE/open-build-service/pull/17715 being merged and deployed.

Remove `ignored_columns` line for `user_id` on report model

---

src/api/app/views/webui/projects/pulse/_pulse_list_entry.html.haml

Differentiate the succeeded and failed build results in pulse

---

src/api/app/models/project.rb

Destroy dependent label templates when removing the owning project

---

src/api/app/models/package_issue.rb

We know these database queries happen to fail. We tried to get rid of the loop in #17515, but we will need a different and more complex approach.
See also:
- #16959
- #16956

Stop reporting retried failed database queries to Errbit

---

src/api/app/models/project.rb

We need to remove the dependent Global labels as well when removing a project.
Follows up #17749
Fixes #17745

Destroy dependent global labels when removing the owning project

---

src/api/config/crawler-user-agents.json

The list was updated using `rake voight_kampff:import_user_agents`.
This is a recurring task. Last time we did it in #17709.

Update list of crawler user agents

---

src/backend/BSRepServer/ProjPacks.pm
src/backend/BSSched/ProjPacks.pm
src/backend/bs_srcserver

This macros are meant to be used in the project config. %_is_this_project is true if the project is the same as the config's project. %_is_in_project is true if the project is the same or a sub-project.

[backend] Add support for %_is_this_project and %_is_in_project

---

src/api/app/assets/javascripts/webui/nav_tabs.js

Prevent from throwing this exception where there aren't any elements with the `button_to` class found in the current page:
`Uncaught TypeError: t is undefined`
This should have been included in #17680.

Fix undefined exception when retrieving buttonToAction

---

src/api/app/controllers/webui/packages/meta_controller.rb
src/api/spec/controllers/webui/packages/meta_controller_spec.rb

The package does not exist locally, so we cannot get the meta data like we usually do
Fixes #17690

Do not fetch package's meta data when it's an scmsync project

---

src/backend/BSSrcServer/ScmsyncDB.pm

We must ensure also to remove all package entries when the project get removed.

[backend] fix scmsync database cleanup on project removal

---

src/backend/bs_srcserver

Otherwise we fail with 404 and further references don't get triggered.
This may be caused by out-of-sync database, but it is also in any case racy, since a parallel job may remove the object in parallel.

[backend] check existens for scmsync objects on triggerscmsync

---

src/api/lib/tasks/dev/reports.rake

The user relation was changed to reporter in
[e1446f2b08d2c69a1350c5161609a63d530c68c9](https://github.com/openSUSE/open-build-service/commit/e1446f2b08d2c69a1350c5161609a63d530c68c9)
This fixes the seed data generation to use the new association.

Use the reporter association in seed data.

---

src/api/app/controllers/webui/webui_controller.rb

This is not used any more, for a long time.

Remove `clean_cache` after_action controller callback

---

src/api/app/controllers/webui/repositories_controller.rb
src/api/app/views/webui/repositories/_add_repository_from_project_modal.html.haml
src/api/app/views/webui/repositories/_add_repository_path_modal.html.haml
src/api/spec/controllers/webui/repositories_controller_spec.rb
src/api/spec/features/webui/kiwi/images_spec.rb
src/api/spec/features/webui/repositories_spec.rb

Fixes https://github.com/openSUSE/open-build-service/issues/17775
Make more unique the `id` attribute.
Both `add_repository_path...` and `add_repository_from_project...` reuse the same partial that implements the `autocomplete` functionality targetting the html element by the `id` attribute. If both input fields has the same `id` the autocomplete crashes on the first one and works only on the last one that was implemented in the page.

Fix: autocomplete in the same page with distinct ids

---

src/api/app/controllers/webui/projects/pulse_controller.rb
src/api/app/views/webui/projects/pulse/show.js.erb
src/api/spec/controllers/webui/projects/pulse_controller_spec.rb

- `.*` + `before_action :set_pulse` + `show` to simply render the `show.html.haml`
- `.*` + `before_action :set_pulse` + `show` via ajax to render now the `show.js.erb`
- `.*` + `show` to simply render the `show.html.haml`
- `.*` + `show` + `set_pulse` via ajax to render now the `show.js.erb`
`.*` = this placeholder means _whatever is required and did not change at all by this refactoring_
`show` route was initially rendering the view only (which behaves as a placeholder, it does not render anything), and after that it sends a request (ajax this time) still pointing to `show` route, which reloads the entire data and then it renders them. This makes the `set_pulse` data to be **computed twice**, the first time for the show template, and the second time to really get and present the pulse …

Refactoring pulse routing behavior

---

src/api/app/controllers/labels_controller.rb
src/api/public/apidocs/paths/labels_requests_request_number_label_id.yaml

On the development environment, for an existing request with number 18 and a non-existing label with id 42, this API call:
```
curl -i -u Admin:opensuse -H 'Content-Type: application/octet-stream' -H 'accept: application/xml' \
-X DELETE 'http://localhost:3000/labels/requests/18/42'
```
returns:
```
<status code="not_found">
<summary>Couldn't find Label with 'id'=42 [WHERE `labels`.`labelable_id` = ? AND `labels`.`labelable_type` = ?]</summary>
</status>
```
```
<status code="not_found">
<summary>Unable to find label `42`</summary>
</status>
```

Fix error message for a not found label when deleting a label

---

src/backend/BSSched/BuildRepo.pm

Broken in commit 32c50a37b6d30c81ea3f16c10b219178d5d93b26. We need to use the package list from the gbininfo to calculate the old state.

[backend] fix removal of deleted packages from the :full tree

---

src/api/app/views/webui/repositories/_add_repository_path_modal.html.haml

Fixes https://github.com/openSUSE/open-build-service/issues/17775#issuecomment-2839411026
Former fix https://github.com/openSUSE/open-build-service/pull/17795 **was required** but **not enough**. Initially there were two partials they had conflicting ids. Now that they are solved, another conflict surfaced: `_add_repository_path_modal` is rendered multiple times in the same page, and html ids must be unique across the whole page, otherwise they conflict on each other

Make html input id unique

---

src/backend/BSSched/BuildRepo.pm
src/backend/BSSched/ProjPacks.pm

More investigation revealed that the root cause was the prpcheckuseforbuild flag not being set when the project update contais only package deletions. In this case the source server does not send the project.
Also revert the old change as it leads to needless full tree rebuilds.

[backend] better fix for the deleted packages removal

---

src/api/app/assets/javascripts/webui/nav_tabs.js
src/api/app/assets/stylesheets/webui/user.scss
src/api/app/helpers/webui/user_activity_helper.rb
src/api/app/views/webui/user/_activity.html.haml

Define contribution graph cell colors with Bootstrap table variants. Follow Bootstrap recomendation for customizing tables instead of using fixed colors.
See:
- https://github.com/twbs/bootstrap/blob/v5.3.5/scss/_tables.scss#L148-L155
- https://getbootstrap.com/docs/5.3/content/tables/#css
Also fix switching to the "Contributions" pane after clicking on a date on the Contributions graph.
For details on the changes, please read the sequence of commits and their descriptions.

Fix personal contribution graph

---

src/api/app/assets/stylesheets/webui/bootstrap_variables/colors.scss
src/api/app/assets/stylesheets/webui/tabs.scss

Follow up to #17840.
Previously, the color of the links changed from `$blue` to `$green` when hovering on them. Reproducing this behaviour in different color modes is not an easy task.
Removing the value assigned to the `$link-hover-color` variable, allows Bootstrap link utilities to define a color for hovering on links automatically.
See as reference: https://getbootstrap.com/docs/5.3/helpers/colored-links/#link-utilities
Related to #6539.
| Light mode | Dark mode |
| --- | --- |
| ![Screenshot From 2025-05-07 14-15-48](https://github.com/user-attachments/assets/7d9260c5-645b-4c9a-a0a1-3ba3e2cb4382) | ![Screenshot From 2025-05-07 14-19-03](https://github.com/user-attachments/assets/c246492c-dc21-421d-b721-bdff579abe03) |
| Light mode | Dark mode |
| --- | --- |
| ![Screenshot From …

Remove override of `$link-hover-color` Bootstrap variable

---

src/api/app/jobs/expire_assignments_job.rb

Because we do not want to send notifications when that happens

Do not trigger callbacks when expiring assignments

---

src/backend/bs_srcserver

The old regex matched everything that contained the substring 'mkosi'.

[backend] bs_srcserver: fix mkosi recipe detection in findfiles()

---

src/api/app/assets/stylesheets/webui/application.scss
src/api/app/assets/stylesheets/webui/bootstrap_variables/colors.scss
src/api/app/assets/stylesheets/webui/cm2/bootstrap.scss
src/api/app/assets/stylesheets/webui/coderay.scss
src/api/app/assets/stylesheets/webui/editor-colors.scss

Remove some Bootstrap basic colors definitions overrides. The colors needed by editors are now defined in a separate file, prepending their color variable name with `$editor-`.
Also, prepare the next removal of Bootstrap basic colors overrides making sure that editor colors will not be affected.

Extract colors needed by editors to `editor-colors.scss`

---

src/backend/BSSched/BuildJob/ProductCompose.pm

The code below did not differentiate between the buildenv repos (bprps) and the product repos (aprps). Bring back the aprp array like with the kiwi product builds.

[backend] fix productcompose-onlydirectrepos option

---

src/api/app/controllers/webui/packages/assignments_controller.rb
src/api/app/models/assignment.rb
src/api/app/policies/assignment_policy.rb
src/api/spec/features/beta/webui/assignments_spec.rb
src/api/spec/models/assignment_spec.rb
src/api/spec/policies/assignment_policy_spec.rb

Previously you couldn't create an assignment without being logged in because the Assignment model would complain about an assigner missing, but it's not the proper way to do authorization.

Do proper authorization when assigning someone to a package

---

src/api/app/assets/config/manifest.js
src/api/app/assets/stylesheets/webui/bootstrap_variables/colors.scss
src/api/app/assets/stylesheets/webui/coderay.scss
src/api/app/assets/stylesheets/webui/diff.scss

Prevent from overriding basic Bootstrap color definitions.
Define theme colors as Bootstrap recomends. See:
https://getbootstrap.com/docs/5.3/customize/color/#theme-colors
Follow-up to #17862.

Fix definitions of theme colors for Bootstrap

---

src/api/app/assets/stylesheets/webui/collapsible-text.scss

Fix the following error thrown in the browser console:
"Error in parsing value for ‘max-width’.  Declaration dropped."

Fix passing `none` as parameter

---

src/backend/bs_srcserver

%files contains the files with the _service prefix stripped.

[backend] findfile: use %files instead of %$files for mkosi matching

---

src/api/lib/tasks/dev/assignments.rake

Only for the development enviroment.
Otherwise, we receive the following exception:
```bash
:/obs/src/api> rake dev:assignments
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Package has already been taken (ActiveRecord::RecordInvalid)
/obs/src/api/lib/tasks/dev/assignments.rake:15:in 'block (2 levels) in <top (required)>'
:/obs/src/api>
```

Fix `dev:assignments` rake task

---

src/api/app/models/bs_request_action.rb

missed place on variable rename

[webui] fix crashes when viewing maintenance release requests

---

src/backend/BSRepServer/ProjPacks.pm
src/backend/BSSched/ProjPacks.pm
src/backend/bs_srcserver

This gives us nice error messages with contain the project and the correct line numbers when a config cannot be parsed.

[backend] Add annotations to the concatenated project configs

---

src/api/app/assets/stylesheets/webui/staging-workflow.scss

Follow up to #17910.
| Light mode | Dark mode |
| --- | --- |
| ![Screenshot From 2025-05-22 13-42-22](https://github.com/user-attachments/assets/70f0616f-2660-4422-a4d4-4d965a2d4b17) | ![Screenshot From 2025-05-22 13-42-29](https://github.com/user-attachments/assets/97648cda-df85-43fd-a95f-ec880a132970) |
| Light mode | Dark mode |
| --- | --- |
| ![Screenshot From 2025-05-22 13-42-55](https://github.com/user-attachments/assets/93fdcfda-3fca-4833-8283-a4bd7846b880) | ![Screenshot From 2025-05-22 13-43-06](https://github.com/user-attachments/assets/d6f5f9b8-f614-4590-9ed3-ab051f248acc) |

Preserve staged requests' styles on datatable collapsed columns

---

src/api/app/assets/stylesheets/webui/staging-workflow.scss

Fix rendering of staged requests problems

---

src/api/app/components/request_decision_component.html.haml
src/api/app/components/request_decision_component.rb
src/api/app/policies/bs_request_policy.rb

In the end this is authorization logic and therefore a Pundit policy is the better suited.
Logic is extracted from https://github.com/openSUSE/open-build-service/pull/17595 and turned into a pundit policy.

Turn `forward_allowed` method into a pundit policy

---

src/api/app/controllers/webui/request_controller.rb

This method doesn't accept a request. The `change_state` method called on the `changerequest` endpoint accepts the request. This method is forwarding the request...
Extracted from https://github.com/openSUSE/open-build-service/pull/17595
For sure more refactoring can be done, but I want to scope this PR to just the naming change...

Rename `accept_request` method to `forward_request`

---

src/api/app/controllers/webui/users_controller.rb
src/api/app/views/webui/user/_basic_info.html.haml
src/api/app/views/webui/user/_edit_account_form.html.haml
src/api/config/routes/webui.rb

Make it easier to change the user color theme directly by a toggler instead of editing the entire user profile. Plus, the toggler reloads the page automatically with the new color theme applied ahead.

Color theme toggler

---

src/api/app/controllers/webui/kiwi/images_controller.rb
src/api/app/controllers/webui/package_controller.rb
src/api/app/controllers/webui/packages/binaries_controller.rb
src/api/app/controllers/webui/patchinfo_controller.rb
src/api/app/controllers/webui/projects/maintenance_incident_requests_controller.rb
src/api/app/controllers/webui/projects/maintenance_incidents_controller.rb
src/api/app/controllers/webui/users/bs_requests_controller.rb

Login is required for many actions before processing anything else, such as setting the project or similar. In some controllers, `require_login` appears further down the `before_action` list, causing certain helpers to run before authentication is checked. This PR addresses that issue.

Move require_login to the top of the before_action list

---

src/api/app/views/webui/projects/pulse/_pulse_list_requests.html.haml

Display the right request state badge in Pulse

---

src/api/app/controllers/webui/watched_items_controller.rb

If somehow the item was added to the watchlist in between the existence check and the creation attempt, we return the existing one instead of trying to create it and fail.
Adapt the flash message to fit both cases: just created or previously created.
Fixes #14700.

Avoid duplicated index in watchlist

---

src/api/app/views/webui/packages/bs_requests/_breadcrumb_items.html.haml
src/api/app/views/webui/projects/bs_requests/_breadcrumb_items.html.haml
src/api/app/views/webui/users/bs_requests/_breadcrumb_items.html.haml

- `Project > Requests` did not have a `project` link prefix
- `Package > Requests` had a wrong project icon
- `Your Requests` was missing `Your` prefix

Fix requests index breadcrumbs

---

src/api/app/models/comment.rb
src/api/app/models/event/base.rb
src/api/app/models/event/comment_for_report.rb
src/api/app/models/event_subscription/for_channel_form.rb
src/api/app/models/report.rb
src/api/spec/models/event/comment_for_report_spec.rb

The new CommentForReport event is created. This type of event is tracked every time someone comments on a Report.

Create comments for report event

---

src/backend/bs_regpush

The registry always returns "Not acceptable" even if the content type matches. So allow "application/json" and check the content type later on.

[backend] bs_regpush: tweak so that it works with the rancher registry

---

src/api/app/policies/appeal_policy.rb
src/api/spec/factories/decision_favored_with_user_commenting_restriction.rb
src/api/spec/policies/appeal_policy_spec.rb

There are more decision types then "decision_favored"
which need to be considered in the policy to allow the user to
appeal against.

Adapt appeal decision policy to consider all favored decision types

---

src/api/app/controllers/webui/packages/meta_controller.rb

Do not render the view when trying to access the meta tab from a package belonging to a project managed under SCM.
The package does not exist locally so we cannot render any url for any of the tabs.
Fixes #18009

Skip rendering the view if the packages project is managed under SCM

---

src/backend/BSPGP.pm

The expiry time is offset from the key creation time, not the selfsig time.

[backend] BSPGP: fix key expiry calculation

---

src/backend/BSRepServer/ProjPacks.pm
src/backend/BSSched/ProjPacks.pm
src/backend/bs_srcserver

This makes the code ignore all config parts that came before. It is useful to test new base project configs in a staging area.

[backend] Implement new 'FromScratch' config directive

---

src/api/.database_consistency.todo.yml
src/api/app/models/attrib_default_value.rb
src/api/test/unit/attrib_test.rb

We have a database backed null constraint on that column but no validation in the model.

Add null validation on attrib_type_id column on AttribDefaultValue table

---

src/api/app/models/package.rb
src/api/spec/models/package_spec.rb

When we refactored Package#update_from_xml in
https://github.com/openSUSE/open-build-service/pull/16227 we forgot to clear the develpackage before updating the values coming from an xml.
This commit clears the develpackage before updating the values, so if someone deletes the devel tag from the xml meta, we remove it from the model as well.
Fixes #18084

Fixes deletion of devel tags from a package's meta

---

src/api/app/controllers/source_project_command_controller.rb
src/api/app/models/project.rb

Previously, when the `include_all_packages` parameter was set to true, the `Project#get_by_name` method would raise a `ReadAccessError` exception if there was a package that:
- had the 'sourceaccess' flag,
- belonged to the current project, and
- the current project could not be modified by the current user.
However, the check to determine whether the current project can be modified by the current user is performed immediately after this code anyway. Therefore, we can safely remove the `include_all_packages` parameter and all associated conditional logic.
This commit introduced this parameter: 0abb664c95794416c154f762db39ef70e0a88d14.

Remove unnecesary `include_all_packages` parameter

---

src/api/app/controllers/build_controller.rb
src/api/app/controllers/worker/command_controller.rb

For requiring query parameters on API endpoints we can use the method `require` from action controller parameters.
See: https://api.rubyonrails.org/v7.2.2.1/classes/ActionController/Parameters.html#method-i-require
Follow up to #18079.

Remove `required_parameters` from a couple of controllers

---

src/api/app/controllers/application_controller.rb
src/api/app/controllers/build_controller.rb
src/api/app/controllers/concerns/rescue_handler.rb
src/api/app/controllers/source_package_command_controller.rb
src/api/app/controllers/source_project_command_controller.rb
src/api/app/controllers/worker/command_controller.rb
src/api/test/functional/source_controller_test.rb

For requiring query parameters on API endpoints we can use the method `require` from action controller parameters.
Follow-up to #18104.

Refactoring: remove methods to require parameters

---

src/api/app/assets/javascripts/webui/comment.js
src/api/app/components/bs_request_comment_component.html.haml
src/api/app/components/request_decision_component.html.haml
src/api/app/components/write_and_preview_component.html.haml
src/api/app/components/write_and_preview_component.rb
src/api/app/views/webui/comment/_comment_field.html.haml
src/api/spec/features/webui/comment_locks_spec.rb
src/api/spec/features/webui/comments_spec.rb
src/api/spec/features/webui/packages_spec.rb
src/api/spec/features/webui/projects_spec.rb

Deduplicate code by using always and only `write_and_preview` view component for comment fields for both when there can be canned responses and when  there aren't.
- Edit a News content (AKA StatusMessage) _to make sure the existing code is still working_
- Add a comment to a package|project|request either w/ or w/o canned responses _to make sure the new implementation works as expected_
- Add a **decision** comment to a request either w/ or w/o canned responses _to make sure the new implementation works as expected_
https://trello.com/c/URMPZfJT

Reuse write_and_preview component for canned_responses too

---

src/api/app/models/issue_tracker.rb

This method was commented more than a decade ago in https://github.com/openSUSE/open-build-service/commit/9f77b138e2badab0bb6cbb2d098bb5bad1cd88d1. It's time to remove it.

Remove commented method on IssueTracker model

---

src/api/app/models/bs_request_action_submit.rb

When retrieving the srcmd5 of a source package of a submit request, if this source package has a link, return the xsrcmd5 field from the linkinfo hash stored in the backend package.

Fix comment on diff wrongly marked as outdated

---

dist/obs-bundled-gems.spec

From [OBS:Server:Unstable/obs-server:obs-bundled-gems/15.7/x86_64](https://build.opensuse.org/package/live_build_log/OBS:Server:Unstable/obs-server:obs-bundled-gems/15.7/x86_64)
```
[  249s] obs-bundled-gems.x86_64: E: permissions-world-writable (Badness: 10000) /usr/lib64/obs-api/ruby/3.4.0/specifications/crass-1.0.6.gemspec is packaged with world writable permissions (0666)
[  249s] If the package is intended for inclusion in any SUSE product please open a bug
[  249s] report to request review of the package by the security team. Please refer to
[  249s] https://en.opensuse.org/openSUSE:Package_security_guidelines#audit_bugs for
[  249s] more information.
```

[dist] fix E: permissions-world-writable for gemspec files

---

dist/t/spec/spec_helper.rb
dist/t/spec/support/capybara.rb

This patch makes the result dir of the rspec tests configurable.
In our kanku instance we use a jump host with a running apache2.
Saving the screenshots/html files in `/srv/www/htdocs` will allow easy access to the results.
Here you can find the corresponding patch in kanku's OBSServerTests handler:
https://github.com/M0ses/kanku/commit/ca5abf31a477af7ef3cf3ba4005f263c536b1add
The patch already has been tested successfully in our internal kanku instance.

[dist] make output path for rspec tests configurable

---

docs/api/api/issue_trackers.xml
src/api/db/data/20250707110214_update_cve_issue_tracker.rb
src/api/db/data_schema.rb
src/api/db/seeds.rb
src/api/spec/cassettes/Comments_with_diff/create_diff_comment/displays_the_comment_in_the_conversation_tab.yml
src/api/spec/cassettes/Comments_with_diff/create_diff_comment/displays_the_comment_on_the_file_diff_in_the_changes_tab.yml
src/api/spec/cassettes/Comments_with_diff/diff_comment_in_legacy_view/displays_the_comment_with_a_hint_to_the_corresponding_file_and_line.yml
src/api/spec/cassettes/Comments_with_diff/reply_comment/when_under_the_beta_program/displays_the_changes_after_adding_a_new_comment.yml
src/api/spec/cassettes/Requests_Submissions/submit_package/when_under_the_beta_program/submit_several_packages_at_once_against_a_factory_staging_project/shows_the_beta_version_of_the_requests_page.yml
src/api/spec/controllers/webui/patchinfo_controller_spec.rb
src/api/test/fixtures/issue_trackers.yml
src/api/test/functional/maintenance_test.rb

from mitre.org:
NOTICE: This legacy website is in the process of being retired.
Please use the new [WWW.CVE.ORG](https://www.cve.org/) website.
First step towards replacing cve.mitre.org with cve.org... the rest of the replacement will be done once we work on https://github.com/openSUSE/open-build-service/issues/18105
From patchinfo:
- Go to a project show page
- Click on _Create Patchinfo_ on the _Actions on this page_ menu item
- Fill in the form. Don't forget about the _Issues_ field. Real values: "CVE-2025-52891" or "CVE-2011-3651"
- Save
- Check the added issues are listed in the _Fixed Bugs_ section and point to the new URL.
From a request:
- Branch a package and do some changes
- In the x.changes file, mention one or more issues
- Submit the request
- Check that the issues are …

[issuetracker] Update CVE tracker to point to cve.org

---

src/api/app/controllers/webui/package_controller.rb

We just block the access to the package requests page with an error and redirect to the project index.
Fixes #17618
Related to #18129

It makes no sense to access the package requests page given we have no local packages.

---

src/api/db/migrate/20250708130643_add_status_to_bs_requests.rb
src/api/db/schema.rb

This is the first step to change the type of the field `state` from `string` to `enum`: "Create a new column `status`".
In order to not cause any downtime on our production systems, this will be performed in steps:
1. Create a new column `status` <-
2. Write to both columns
3. Backfill data from the old column to the new column
4. Move reads from the old column to the new column
5. Stop writing to the old column `state`
6. Drop the old column `state`
7. Create a new column `state`
8. Write to both columns
9. Backfill data from the old column to the new column
10. Move reads from the old column to the new column
11. Stop writing to the old column `status`
12. Drop the old column `status`
- https://api.rubyonrails.org/v7.2.2.1/classes/ActiveRecord/Enum.html
- Safe approach to change the …

Add `status` field to table `bs_requests`

---

docs/api/api/aggregate.rng
src/backend/BSSched/BuildJob/Aggregate.pm
src/backend/BSVerify.pm
src/backend/BSXML.pm

This is done with two new attributes of an aggregate element:
- arch: limit the aggregate to the specified architecture
- sourcearch: aggregate from this architecture
Currently we only support cross-arch aggregates from the 'local' architecture.

[backend] implement aggregations from the 'local' architecture

---

src/api/spec/components/diff_subject_component_spec.rb
src/api/spec/components/previews/diff_subject_component_preview.rb

Check the add component previews in [this link](http://obs-reviewlab.opensuse.org/eduardoj-testsdiff_subject_component/rails/view_components/diff_subject_component) of the review app.

Add previews and previews' specs for DiffSubjectComponent

---

src/api/lib/tasks/dev/rake_support.rb

After the refactoring in https://github.com/openSUSE/open-build-service/pull/17913  we no longer have `Review#change_state`. The task is now adapted accordingly.

Adapt task code to change the review state

---

src/api/spec/components/bs_request_action_description_component_spec.rb
src/api/spec/components/previews/bs_request_action_description_component_preview.rb

Also, add specs to test previews of requests' descriptions.
All request action types have been included in previews and specs except for the `release` request action type. This will be addressed in a follow-up pull request.

Add missing previews for request action description component

---

src/api/app/components/request_decision_component.html.haml
src/api/app/components/request_decision_component.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/models/bs_request.rb
src/api/app/views/webui/request/beta_show.html.haml
src/api/spec/cassettes/Comments_with_diff/create_diff_comment/displays_the_comment_in_the_conversation_tab.yml
src/api/spec/cassettes/Comments_with_diff/diff_comment_in_legacy_view/displays_the_comment_with_a_hint_to_the_corresponding_file_and_line.yml
src/api/spec/cassettes/Comments_with_diff/reply_comment/when_under_the_beta_program/displays_the_changes_after_adding_a_new_comment.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_forward_the_request_and_make_the_creator_a_maintainer/shows_an_option_to_accept_and_forward_the_request.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_forward_the_request_and_make_the_creator_a_maintainer/shows_an_option_to_accept_make_the_creator_a_maintainer_and_forward_the_request.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_forward_the_request_and_make_the_creator_a_maintainer/shows_an_option_to_accept_the_request_only.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_forward_the_request_and_make_the_creator_a_maintainer/shows_the_Accept_button_as_a_dropdown.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_forward_the_request_to_the_developed_project/does_not_show_an_option_to_make_maintainer_because_the_author_is_already_a_maintainer.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_forward_the_request_to_the_developed_project/shows_an_option_to_accept_and_forward_the_request.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_forward_the_request_to_the_developed_project/shows_an_option_to_accept_the_request_only.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_forward_the_request_to_the_developed_project/shows_the_Accept_button_as_a_dropdown.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_make_request_creator_a_maintainer_of_the_target_project/does_not_show_an_option_to_forward_the_request_because_there_is_no_developed_project.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_make_request_creator_a_maintainer_of_the_target_project/shows_an_option_to_accept_and_make_the_creator_a_maintainer.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_make_request_creator_a_maintainer_of_the_target_project/shows_an_option_to_accept_the_request_only.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_can_make_request_creator_a_maintainer_of_the_target_project/shows_the_Accept_button_as_a_dropdown.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_cannot_forward_the_request_nor_make_the_creator_a_maintainer/1_1_1.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_cannot_forward_the_request_nor_make_the_creator_a_maintainer/does_not_show_an_option_to_forward_the_request_because_there_is_no_developed_project.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_cannot_forward_the_request_nor_make_the_creator_a_maintainer/does_not_show_an_option_to_make_maintainer_because_the_author_is_already_a_maintainer.yml
src/api/spec/cassettes/RequestDecisionComponent/when_we_cannot_forward_the_request_nor_make_the_creator_a_maintainer/shows_the_Accept_button_as_a_regular_button_only.yml
src/api/spec/components/request_decision_component_spec.rb
src/api/spec/features/beta/webui/maintenance_workflow_spec.rb
src/api/spec/support/view_component.rb

Override https://github.com/openSUSE/open-build-service/pull/17595
Fixes #17281
This PR groups the several options available when accepting a request:
- Plain accept
- Accept the request and make the creator of the request a maintainer on the target project
- Accept and forward the request to the devel project
- All of the above
https://obs-reviewlab.opensuse.org/ncounter-request-accept-button-group/requests/14

Request accept button group

---

src/api/app/helpers/maintenance_helper.rb
src/api/app/models/bs_request_action_maintenance_release.rb
src/api/app/models/bs_request_action_release.rb
src/api/db/attribute_descriptions.rb
src/api/db/data/20220429123314_add_limit_release_source_project.rb
src/api/lib/api_error.rb
src/api/test/fixtures/attrib_types.yml
src/api/test/functional/attributes_test.rb
src/api/test/functional/source_controller_test.rb

Introducing the new OBS:LimitReleaseSourceProject attribute which allows to list
accepted source project.
It has only an effect on projects atm.

[api] support to limit release source project

---

src/api/app/components/sourcediff_component.rb
src/api/config/routes/webui.rb

After resolving #17613, we can enable individual file diffs for binaries.

Enable fetching diffs for individual files from binaries

---

src/api/db/data/20250717112726_add_role_to_limit_release_source_project.rb
src/api/db/data_schema.rb
src/api/db/seeds.rb

This should have been included in #12506.
This is not the first time we forget about this. See #15181.

Add `LimitReleaseSourceProject` attribute type to seeds

---

src/api/app/jobs/cleanup_notifications_job.rb
src/api/app/models/notification.rb
src/api/db/data/20250717142701_delete_orphan_records_from_notified_project.rb
src/api/db/data/20250717152701_delete_orphan_records_from_groups_notifications.rb
src/api/db/data_schema.rb

Previously, the job responsible for cleaning up stale notifications used `delete_all`, which bypassed callbacks and left associated records (in `notified_projects` and `groups_notifications`) orphaned.
Replace `delete_all` with `destroy_all` to ensure that associations are properly cleaned up via callbacks.
Also, add data migrations to remove the orphan entries in the affected tables.
This was the output when running the data migrations in a development environment:
```
:/obs/src/api> rake db:migrate:with_data
== 20250717142701 DeleteOrphanRecordsFromNotifiedProject: migrating ===========
-- Removing orphaned records from notified projects
-> 0.0370s
-> 11 rows
== 20250717142701 DeleteOrphanRecordsFromNotifiedProject: migrated (0.0371s) ==
== 20250717152701 …
```

Fix cleaning up notifications job

---

src/backend/BSConSign.pm
src/backend/BSPublisher/Registry.pm
src/backend/bs_regpush

Also use the attestation_ents instead of the raw attestation data. The attestation data is just the 'data' element from the ent. This will allow a code simplification in a future commit.

[backend] container publishing: move rekor upload into its own function

---

src/api/app/controllers/person/notifications_controller.rb
src/api/app/controllers/webui/users/notifications_controller.rb
src/api/app/models/user.rb

Improve performance of notification queries using the `count` method. Since sorting has no effect on the result of a count, removing unnecessary `ORDER BY` clauses avoids overhead and improves query performance.

Remove `order` on queries using `count` in notifications

---

src/api/app/models/bs_request.rb
src/api/app/models/bs_request/find_for/base.rb
src/api/app/models/project.rb
src/api/app/models/user.rb
src/api/spec/models/project_spec.rb

It included the `distinct` and `order` clauses, which are unnecessary and degrade the performance in counting queries.

Remove `with_actions` BsRequest scope

---

src/api/app/models/project.rb
src/api/test/unit/project_test.rb

Follow-up to #18219.
The `open_requests` method is only called once in the codebase. After this call, the retrieved results are sorted again.

Remove `order` clause in `open_requests`

---

src/api/app/models/bs_request.rb
src/api/app/models/concerns/staging_project.rb
src/api/app/models/user.rb

It included the `distinct` and `order` methods which were not needed and decrease the performance of counting queries.

Remove the `with_actions_and_reviews` BsRequest scope

---

src/api/app/policies/report_policy.rb
src/api/spec/policies/report_policy_spec.rb

Even if there is a user with moderator role, admins and staff will receive report-related notifications and will see the Report filter.
The three roles are always involved to see and manage reports, decisions and appeals. It makes no sense to exclude any of them from the notifications.
**Who can see a report?**
Always admin, staff and moderator
https://github.com/openSUSE/open-build-service/blob/8f3aa3b99dbf0ba48fa34a72b38bc58d00a5b7df/src/api/app/policies/report_policy.rb#L3
**Who can take a decision regarding a report?**
Always admin, staff and moderator
https://github.com/openSUSE/open-build-service/blob/8f3aa3b99dbf0ba48fa34a72b38bc58d00a5b7df/src/api/app/policies/decision_policy.rb#L5
**Who can see an appeal?**
Always admin, staff and moderator …

Admins and staff receive report-related notifications

---

src/api/app/views/webui/users/notifications/_notification.html.haml

User and Group have name and email, so if we check if the object has email its guaranteed to have a name.
Fixes #18224

Stop asking for the name to objects that have no name

---

src/api/app/models/event/added_user_to_group.rb
src/api/app/models/event/group.rb
src/api/app/models/event/removed_user_from_group.rb
src/api/app/models/event_subscription.rb
src/api/app/models/group.rb
src/api/app/models/notification_group.rb
src/api/app/queries/outdated_notifications_finder/group.rb
src/api/app/views/event_mailer/added_user_to_group.html.haml
src/api/app/views/event_mailer/added_user_to_group.text.erb
src/api/app/views/event_mailer/removed_user_from_group.html.haml
src/api/app/views/event_mailer/removed_user_from_group.text.erb
src/api/spec/mailers/event_mailer_spec.rb

Group maintainers will know when someone else add a user to "their"  group.
- Open two sessions with two different users (for example Admin and Iggy)
- Login as Iggy and subscribe it to _Added member to group_ and _Removed member from group_ events
- As Admin go to _Configuration > Manage Group_; mark Iggy as Maintainer of any group you choose, for example group_1
- Add and remove users from the group
- After a few minutes Iggy should see notifications about all the additions and removals Admin did

Notify group managers when a user is added to a group

---

src/api/app/models/package.rb

Authorization is not the place to check for Authentication.
The weak version of this method (`check_source_access?`) uses `User.possibly_nobody`. So only if someone makes the nobody user admin, gives it a `Role` with global `source_access` permission or adds this `User` to it's `Project`/`Package` this would hit. If someone so desperately tries to shoot themselves in the foot, let them.

Remove session checking

---

src/api/app/controllers/webui/webui_controller.rb

This parameter was introduced in 3b9d9020d61003d46858e4c3a38313669a75b002 and later removed in  ced3de2b347c6bd079e129063b48352db887a873. It has not being used for a long time.
Seen while reviewing #18273.

Remove parsing of the no-longer-used `pkgrev` parameter

---

src/api/app/components/rpm_lint_component.html.haml

Fixes #18284.
This change should have been included in the update of view_components to 4.0.0. See #18280.

Fix rendering of RPM lint logs bar chart

---

src/api/app/controllers/webui/comments_controller.rb

There were some missing parameters that prevented this from happening. Now the comments can be deleted again
Fixes #18293.

Make sure the diff comments can be removed

---

src/api/app/components/diff_list_component.html.haml

The added and removed binaries do not have controls to expand diffs, the rest woks as usual:

Do not allow expanding binaries added or removed

---

src/api/app/controllers/webui/attribute_controller.rb
src/api/app/controllers/webui/package_controller.rb
src/api/app/controllers/webui/packages/bs_requests_controller.rb
src/api/app/controllers/webui/packages/trigger_controller.rb
src/api/app/controllers/webui/patchinfo_controller.rb
src/api/app/controllers/webui/repositories_controller.rb
src/api/app/controllers/webui/webui_controller.rb
src/api/spec/controllers/webui/webui_controller_spec.rb

In the majority of controllers we use the `set_package` alias
to call `require_package`. Also the controllers that have their
own logic for this method and overwrite the inheritance of the
method use the `set_package` naming. Lets get rid of the
alias and stick to one name for it.
~~Depends on https://github.com/openSUSE/open-build-service/pull/18294~~

Rename `require_package` method to `set_package`

---

src/api/app/lib/backend/api/sources/package.rb
src/api/app/models/concerns/has_attributes.rb

Don't raise an exception when calling the backend API without a logged-in user. Checking for a logged in user needs to happen before the backend API call.

Avoid crash when calling `write_attributes` if a user is not logged in

---

src/backend/BSPublisher/Container.pm

This can be turned off with the 'repostate_unneeded' registry flag.

[backend] BSPublisher::Container: insist on a successful repostate query

---

.circleci/conditional_config.yml

We run the command from withing the `src/app/` path, so we should not `add` it, we should `strip` it instead

Fix qlty: strip prefix to match paths

---

src/api/lib/tasks/rollout.rake
src/api/spec/lib/tasks/rollout_spec.rb

For users logged in during the last week and the last month.
This helps to make the rollout phases more gradual.

Add more rollout tasks

---

src/api/lib/xpath_engine.rb

This feature was introduced in 66d69b29e10bc9b5acc6a1b3d4f3bb464693c902 and later removed in bcf8de8f8ece584878bb6a703bab65585094a790. The code being removed now is a leftover.
Seen while working on #18173.

Remove no longer used `double` key on definition of XPath table

---

src/api/app/assets/stylesheets/webui/diff.scss
src/api/app/components/diff_list_component.html.haml
src/api/app/components/sourcediff_component.rb
src/api/app/controllers/webui/request_controller.rb

Disable diff requests for newly added or deleted binary files. Also, disable diff requests for files without available diffs, and instead display the number of lines changed when only that information is provided by the backend without the actual diff content.
**This is how it looks now**

Disable diff requests for newly added or deleted binary files

---

src/api/app/views/webui/projects/pulse/show.html.haml

Our application enforces request forgery protection for all HTTP requests, including GET.
Replace the raw `<form>` element with the Rails `form_with` helper, which automatically includes a hidden authenticity token field.
Fixes #17818.
See the official documentation:
https://guides.rubyonrails.org/v7.2/form_helpers.html#working-with-basic-forms

Fix CSRF security warning on the Pulse page

---

src/api/app/components/card_component.html.haml
src/api/app/views/webui/repositories/_repository_entry.html.haml

Fixes #17975.
Go to the review app, here: https://obs-reviewlab.opensuse.org/eduardoj-fixissue_17975/repositories/home:Admin

Fix rendering the architectures of a repository

---

src/api/app/views/webui/request/beta_show_tabs/_review_summary.html.haml

I came across this issue when manually testing requests related to a Staging workflow. 
Sometimes `Review#reviewer` is nil, we shouldn't try to find the corresponding user in those cases.
The Review Summary will end up looking like this:

Show reviewer in the review summary only if any

---

src/api/app/controllers/webui/package_controller.rb

Fix crash when retrieving the revisions of a package belonging to an scmsync project

---

src/api/app/controllers/webui/package_controller.rb

This reverts commit 9f76f2f282f6f940cae35ee8fab4f34391cacde5.
Removes `buildresult` but keep `revisions` which was added later on to the `before_action`.
Fixes: #18377

Revert "Fix crash when retrieving the build results of a package ..."

---

dist/t/spec/features/0030_project_spec.rb

repeat the whole way to the list of distributions
in each iteration of the loop until timeout should ensure that we do not end up in a dead end of the
workflow by just refreshing the last page.

[ci] ensure that we do not refresh a dead end

---

src/backend/bs_signer

if we change the file during signing we also have to update the .digest
currently this contains just the plain sha256 checksum, no sumtype or filename included.

[backend] also update the digest file when signing the appimage

---

src/backend/bs_srcserver

We must not reset $projids via splice here

[backend] fix regexp limit architecture filtering

---

src/api/app/controllers/webui/package_controller.rb
src/api/app/models/package.rb

Instead of calling a file content method with a `nil` file which will perform a file listing, call the file listing method directly.

Call the proper backend method to list files of a package

---

src/api/app/controllers/source_package_controller.rb
src/api/app/lib/backend/api/sources/file.rb

This is another PR of a series of changes to refactor direct calls to `Backend::Connection` into the `Backend::Api` library.
~Depends on:~
- #18427

Move direct calls to the backend of source package controller into `Backend::Api`

---

src/api/app/lib/backend/api/build_results/binaries.rb
src/api/app/lib/backend/api/sources/file.rb
src/api/app/lib/backend/api/sources/package.rb
src/api/app/models/package.rb

This is another PR of a series of changes to refactor direct calls to `Backend::Connection` into the `Backend::Api` library.
~Depends on:~
- #18433
- #18439

Refactor backend calls from Package model using Backend::Api methods (II)

---

src/api/app/controllers/worker/command_controller.rb
src/api/config/routes/api.rb
src/api/spec/controllers/worker/command_controller_spec.rb
src/api/test/functional/status_controller_test.rb

Make use of a parameter constraint in the router instead of checking for values in the controller.
Remove spec and minitest checking for other worker run command paths. These cases should return 404 not found.

Refactor worker checkcontraints route

---

src/api/app/helpers/webui/patchinfo_helper.rb
src/api/app/models/issue.rb

Fixes #18454
We have a bit mess in the management of the CVE issues. There is [a plan](https://trello.com/c/ZSBz3xA7/263-cve-issue-name-format) to unify the code with other types of issues.
But meanwhile, let's fix the links to point to the right URL from both Mentioned Issues and Patchinfo.

Fix CVE issue link

---

src/api/app/helpers/webui/webui_helper.rb

closes #18458
`.blank?` can raise an ArgumentError on strings with invalid UTF-8 bytes. We just need to check for the presence of a string, and the validation has already been handled in the code below.

Fix encoding issues by replacing `.blank?` with `.empty?`

---

src/api/app/controllers/request_controller.rb
src/api/config/routes/api.rb
src/api/test/functional/request_controller_test.rb

Make use of a parameter constraint in the router instead of checking for the value of the `cmd` parameter in the controller.
Follow-up to #18449.

Refactor request create route

---

src/api/app/views/layouts/webui/_top_navigation.html.haml

"Your profile" was the only not titleized item in the dropdown menu (it was in footer, Places and breadcrumbs):

Titleize `Your Profile` menu option

---

src/api/app/models/bs_request/data_table/find_for_user_or_group_query.rb

When joining `bs_requests` and `bs_request_actions` table we need to remove the duplicated rows coming from `bs_requests`, because we're going to get some when having several rows on `bs_request_actions` for the same `bs_request`.
Fix #18509.
1. Go to https://obs-reviewlab.opensuse.org/danidoni-remove-duplicates-from-incoming-requests-datatable/my/tasks
2. It should not show any duplicates, while on master it shows several duplicates in the "Incoming Requests" tab.

Return unique rows for user or group requests

---

src/api/app/models/package.rb

It is not enough to check only the project itself for scmsync
Fixes: https://github.com/openSUSE/open-build-service/issues/18205

[api] Fix usage of scmsync projects via project links

---

src/api/app/models/attrib.rb
src/api/spec/models/attrib_spec.rb

After [this discussion](https://github.com/openSUSE/open-build-service/pull/18518#discussion_r2355290690) we concluded that the AnityaDistribution attribute can only be assigned to a project, not a package. So far we are going to limit is with a validation.

Validate AnityaDistribution attribute only for projects

---

src/backend/bs_srcserver

We already do this for uploadbuild. This is important if the target project has disabled builds (like with release requests), as in that case the multibuild data will not get updated by the scheduler's getprojpack call and the binary copy will then discard the job.

[backend] copybuild: also ensure the flavor is known in the target

---

src/backend/BSRepServer/Registry.pm
src/backend/bs_dodup

We can't use the project data for this, so (mis-)use BSConfig for storing the credentials for now.

[backend] DoD: support registry credentials

---

src/api/public/apidocs/OBS-v2.10.50.yaml
src/api/public/apidocs/components/schemas/lastsuccess.yaml
src/api/public/apidocs/paths/build_project_name_result.yaml
src/api/public/apidocs/paths/build_project_name_result_lastsuccess.yaml

Fix #18103.
Use the review-app browsing [this link](https://obs-reviewlab.opensuse.org/eduardoj-fixissue_18103/apidocs/index#/Build/get_build__project_name___result_lastsuccess_1).

Add `GET /build/<project>/_result?lastsuccess=1` endpoint to API docs

---

src/api/app/models/package_version_local.rb

This is a result of the backend not being able to tell the version of a package because of a macro

Don't accept MACRO version

---

src/api/app/datatables/package_datatable.rb
src/api/app/models/package.rb

Using includes resulted in some issues:
This seems to be fixed by using left_joins instead.

Make sure that the correct latest version is retrieved

---

src/api/app/components/sourcediff_component.html.haml
src/api/app/components/sourcediff_component.rb
src/api/app/controllers/webui/request_controller.rb
src/api/app/jobs/bs_request_action_webui_infos_job.rb
src/api/app/models/bs_request_action.rb
src/api/app/views/webui/request/_changes_delete.html.haml
src/api/app/views/webui/request/_changes_diff.html.haml
src/api/app/views/webui/request/_changes_maintenance_incident.html.haml
src/api/app/views/webui/request/_changes_maintenance_release.html.haml
src/api/app/views/webui/request/_changes_release.html.haml
src/api/app/views/webui/request/_changes_submit.html.haml
src/api/app/views/webui/request/changes.html.haml
src/api/app/views/webui/request/request_action_changes.js.erb
src/api/spec/cassettes/Comments_with_diff/create_diff_comment/displays_the_comment_in_the_conversation_tab.yml
src/api/spec/cassettes/Comments_with_diff/create_diff_comment/displays_the_comment_on_the_file_diff_in_the_changes_tab.yml
src/api/spec/components/sourcediff_component_spec.rb

Allows users to expand changes that weren't covered before

Allow expanding the diff if any changes are collapsed

---

src/backend/bs_publish

New style example: Leap-16.0-Minimal-Image.aarch64-kvm-and-xen-Build14.13.qcow2
Note: 16.0 is part of product name, no version is in the file name
Old style example: opensuse-leap-image.x86_64-1.0.0-lxc-Buildlp151.1.2.tar.xz

[backend] support kiwi file name in old and style for static links
