.rubocop_todo.yml, src/api/app/helpers/webui/webui_helper.rb, src/api/app/models/bs_request.rb, src/api/app/views/webui/request/show.html.erb, src/api/spec/features/webui/requests_spec.rb, src/api/spec/helpers/webui/webui_helper_spec.rb
Add role of person or group is shown including the person/group and role.
This include some refactoring to merge in the view `add_role` and `set_bugowner` code, as they are really similar. :bowtie: (this PR will be follow by more refactoring in this models :smiling_imp:)
=> [webui] Fix request review view for add role

src/api/app/mailers/event_mailer.rb
As there is no information regarding the parameters that cause an `ArgumentError` exception in the `mail` callback in `EventMailer`, this exception is catched. It will only log the parameters to the error log, and then will re-raise the exception.
This will help to know the reasons `ArgumentError` exception is thrown and therefore help to fix #4052.
=> [webui] Rescue mail callbacks in EventMailer

src/api/Gemfile.lock
The previous version has been removed from rubygems.org
=> [frontend] Update parser gem

src/api/app/helpers/webui/webui_helper.rb, src/api/spec/helpers/webui/webui_helper_spec.rb
Show in the request that the previous bigowners will be deleted. This makes more clear the difference between `add_role bugowner` and `set_bugowner`. :bowtie:
=> [webui] Clarify what set_bugowner does

dist/ci/travis_script.sh, src/api/config/environments/test.rb
because otherwise it will print a warning.
In the previous PR is just dropped the setting. However, this will cause a warning to be printed.
So I set it now explicit.
https://github.com/openSUSE/open-build-service/pull/4722
We should also think about
https://github.com/rails/rails/issues/28736#issuecomment-293822999
Because now eager load will load the whole application even if you run only one test, not a problem in Travis but for local development indeed.
=> [ci] Set eager-load explicit

src/api/app/controllers/webui/request_controller.rb
Add the values of variables to the message sent to Errbit that may cause a "Validation failed: Bs request actions is invalid" exception in the Webui::RequestController.
This will help to know why #3730 happens.
=> [webui] Add values of variables to exception

src/api/app/views/layouts/webui/_personal_navigation.html.haml, src/api/spec/features/webui/login_spec.rb, src/api/spec/features/webui/users/users_home_project_spec.rb
There is no other way to get to user_tasks_path, so always show this.
Switch to an icon because this is easier to grasp as text and for most
people the number of tasks is not important, but that there are tasks.
=> [frontend] Always present notification icon

src/api/app/assets/stylesheets/webui/application/bento/base.scss
Owing to the physics of monitors, there is almost no visible
difference between 0x44 gray and actual black. (The lowest gray you
can find in the classic X11 color list even is 0x69, which is
probably reflecting just that fact.)
A block of 0x44 text is perceived as black, and only when 0x00 text
is right next to it, a "boldening" effect on the 0x00 portion is
noticable, at which point it feels like a weird design choice to
mix that "semi-bold" and "non-bold" text.
=> [webui] increase contrast on default text

src/api/app/views/layouts/webui/_personal_navigation.html.haml
When a user does not have any open requests / reviews, the tasks label
was not a link. Since there is no other way to access the page (except
adding the direct url into the browser) users were basically locked out
from seeing their tasks, eg. closed requests.
Fixes #4674
=> [frontend] Always link to users tasks view

src/api/app/controllers/request_controller.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/models/bs_request.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/bs_request_action/differ/for_source.rb, src/api/app/models/bs_request_action/differ/query_builder_for_superseded.rb, src/api/app/views/webui/request/_superseded_by_message.html.erb, src/api/app/views/webui/request/show.html.erb, src/api/spec/cassettes/Webui_RequestController/GET_show/with_diff_to_superseded_set/and_the_superseded_request_is_not_superseded/1_3_7_2_1.yml, src/api/spec/cassettes/Webui_RequestController/GET_show/with_diff_to_superseded_set/and_the_superseded_request_is_not_superseded/1_3_7_2_2.yml, src/api/spec/cassettes/Webui_RequestController/GET_show/with_diff_to_superseded_set/and_the_superseded_request_is_superseded/1_3_7_1_1.yml, src/api/spec/controllers/request_controller_spec.rb, src/api/spec/controllers/webui/request_controller_spec.rb, src/api/spec/models/bs_request_action/differ/for_source_spec.rb, src/api/spec/models/bs_request_action/differ/query_builder_for_superseded_spec.rb, src/api/spec/models/bs_request_action_spec.rb
If a request (submit, maintenance incident or maintenance release) is superseded, it is now possible to
view a diff between the superseded and superseding requests.
In the superseded request, you get a message that this request is superseded and a link to the diff between the superseded and the superseding request:
On the diff page between the superseded and superseding request, you get a message that you're not reviewing the full diff:
I changed the URL to add the parameter ``?diff_to_superseded=:number``. If the supplied number is not superseded by the request, a flash error is rendered in webui and an APIException is raised in the API.
=> [webui][api] Implement diffs for superseded requests

src/api/app/controllers/application_controller.rb, src/api/app/controllers/cloud/upload_jobs_controller.rb, src/api/app/models/cloud/backend/upload_job.rb, src/api/config/routes.rb, src/api/spec/cassettes/Cloud_Backend_UploadJob/_find/with_Timeout_Error/1_2_3_1.yml, src/api/spec/cassettes/Cloud_Backend_UploadJob/_find/with_an_invalid_backend_response/1_2_2_1.yml, src/api/spec/controllers/cloud/upload_jobs_controller_spec.rb, src/api/spec/models/cloud/backend/upload_job_spec.rb
This adds API routes (aka xml responses) for:
* Creation of upload jobs
* Listing all upload jobs a user has access to
=> [frontend] Add an API route to the cloud upload controller

src/api/spec/rails_helper.rb
We only need this for travis to have codecov reports for every pull
request and the master branch.
On our development instances sending the report always fails due to a
timeout (~30sec).
=> [frontend] Prevent codecov reports being send outside of travis

src/api/app/mailers/event_mailer.rb
Re-raise exception instead of raising a new one. This ensures that we
don't loose data related to the exception.
This previously changed with 1f259e35d4eb6c866163530de29ae22bb39204b6
=> [frontend] Update exception handling in event mailer

src/api/app/controllers/webui/patchinfo_controller.rb
Remove leading / trailing whitespaces from rating and category.
Fixes #4662
=> [frontend] Sanitize patchinfo input before saving it

src/api/spec/controllers/webui/package_controller_spec.rb
If the request creator is not confirmed, he might get might not get
logged in. Therefor it's better to user some other request related
validation.
=> [frontend] Refactor request validation test

src/api/spec/helpers/webui/webui_helper_spec.rb
This test currently blocks our package builds because it's constantly
failing there (We run all our tests within the rpm package builds again).
=> [frontend] Temporarely skip test

src/backend/bs_repserver, src/backend/bs_signer
Just like for RPMs, if a Debian package build creates $pkg.cpio.rsasign
trigger a signd signature and a rebuild (look for .dsc other than .spec
for the followup build).
The packages to actually do the sign&repack for kernel, shim and grub
can be found:
https://github.com/bluca/linux-signed/tree/obs
https://github.com/bluca/shim-signed/tree/obs
https://github.com/bluca/grub2-signed/tree/obs
https://build.opensuse.org/project/show/home:bluca:debian_secure_boot
=> [backend] enable EFI binaries signing for Debian packages

src/api/spec/helpers/webui/webui_helper_spec.rb
This test is not adding much value since it's just ensure that the
result of a rails helper (*.ago) is properly shown.
It's also flickering quite often and causes our test suite to fail.
So let's drop it.
=> [frontend] Drop test for fuzzy time

src/api/Gemfile, src/api/Gemfile.lock, src/api/spec/browser_helper.rb
and enable it for feature tests.
Some feature tests fail randomly in the package build in OBS with timeouts.
Hopefully retrying the same test three times will solve this problem.
=> [ci] Add rspec-retry

CONTRIBUTING.md
It won't interfere with the global .gitconfig and have potential side-effects in other projects.
It's a one time setup unlike the previous recommendation. With `cp`, it needs to be copied again whenever the template changes.
Note: This could be automated in the rake task building the development environment (`rake docker:build`). I would do this in a following pull request.
=> [doc] Use local .gitconfig to set commit template

src/api/app/assets/javascripts/webui/application/live_build_log.js, src/api/app/assets/stylesheets/webui/application/package.scss, src/api/app/views/webui/package/live_build_log.html.erb
We added a hint to the live build log to know what is doing: `running`,
`paused` or `finished`. This hint also starts and pause the auto-refresh.
This hint will always follow you
Fixes #4713
=> [webui] Add hint in live build log

src/api/app/mixins/build_log_support.rb, src/api/app/models/event/build_fail.rb
When :undef is configured to ':replace' it's not throwing an exception
but replaces the udnefined char with the configured replacement
character.
=> [frontend] Refactor encoding of buil log file

src/backend/bs_publish, src/backend/bs_repserver, src/backend/bs_signer
Backported from https://github.com/openSUSE/open-build-service/pull/4526 and https://github.com/openSUSE/open-build-service/pull/4639 and https://github.com/openSUSE/open-build-service/pull/4790
=> [backend] backport Debian fixes to 2.9 - publish ONIE binary and hashsum, enable Secure Boot EFI signing for Debian packages

src/api/lib/backend/api/sources/package.rb
There are non UTF-8 encoded chars in source diffs that we can still
represent in the ui (and can be handled by ruby / rails). This will
relax the source diff encoding.
Fixes #4841
=> [frontend] Replace non UTF-8 chars only when neccessary

Rakefile
It prevents error caused by old Docker images
=> [api] Pull newer version of the Docker image in rake docker:build

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/shared/_buildresult_box.html.haml, src/api/app/views/webui/package/_buildstatus.html.haml
`function update_rpmlint_result` and `function update_build_result`where defined more than once for multiple request.
This fixes the broken "Selecting build / rpmlint result" in request show page, reported in https://github.com/openSUSE/open-build-service/issues/4720 :bowtie:
=> [webui] Fix worst JS ever

src/api/app/assets/stylesheets/webui/application/package.scss, src/api/app/views/webui/package/live_build_log.html.erb
Before when a live build log ended a text with "Finished" over green was shown and
it was misleading when a build failed. Now is showing "End of log" over
yellow without any icon to not mislead.
If fixes #4840
=> Change color for the completed live build log hint

ReleaseNotes-2.10
- Delete content copied from version 2.9.
- Add missing "Do not show excluded entries in package build results by default" to features.
=> Update 2.10 release notes

docker-compose.ahm.yml, src/api/app/models/event/base.rb
The simple time based health check depends too much on what else is going
on in the system. If you have a weak system or a high load it would fail.
Switching to a real health check makes this more robust.
=> [dist] Introduces real health check for the rabbitmq service

src/api/app/controllers/webui/request_controller.rb, src/api/app/controllers/webui/user_controller.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui/package/show.html.erb, src/api/app/views/webui/request/_add_role_request_dialog.html.erb, src/api/app/views/webui/request/_change_devel_request_dialog.html.erb, src/api/app/views/webui/request/_delete_request_dialog.html.erb, src/api/config/routes.rb, src/api/spec/controllers/webui/user_controller_spec.rb, src/api/spec/features/webui/users/users_icons_spec.rb, src/api/spec/helpers/webui/webui_helper_spec.rb
Remove  `required_parameters` callbacks from the following controllers: `Webui::RequestController`, `Webui::UserController`.
This will allow us to remove the following class in the future:
``class MissingParameterError < RuntimeError; end``.
=> Refactor Webui controller, part 5

Rakefile, docker-compose.ci.yml
with all the docker Travis changes, it slipped in that we still run the backend tests on the dev tests :man_facepalming:
=> [ci] Run backend tests in SLES12 SP3 container

docker-compose.ci.yml
because I moved the project to another place so that it is easier to follow a common namespace for new base systems
- https://build.opensuse.org/project/show/OBS:Server:Unstable:container:Leap:42.3
- https://build.opensuse.org/project/show/OBS:Server:Unstable:container:SLE12:SP3
- etc...
=> [ci] Update CI container repository links

Rakefile
to make it possible to run several tasks / tests in parallel on the same machine.
Otherwise they would e.g. share the same database.
Adding the project -p paramter will add a prefix to each container name
which will result in starting several databases for instance.
=> [ci] Add project -p parameter to docker-compose tasks

dist/obs-server.spec
These tests tend to fail because of capybara timeouts and we don't
need / use the UI for these architectures anyway.
=> [frontend] Disable feature tests for archs != x86

src/api/app/views/webui/request/show.html.erb
The line break in the `<a>` tag was causing the Javascript check to fail due to the text having leading whitespaces. It doesn't have these whitespaces anymore
Fixes #4889
=> [webui] Fix Show/Hide outdated comments link text

src/api/lib/rabbitmq_bus.rb
as there is no logger variable available which caused a crash when there is no RabbitMQ configured.
=> [frontend] Use Rails logger in RabbitMQ lib

src/api/app/controllers/webui/main_controller.rb, src/api/app/controllers/webui/status_messages_controller.rb, src/api/app/views/webui/main/_status_messages.html.haml, src/api/app/views/webui/main/index.html.haml, src/api/app/views/webui/status_messages/_create_status_message_dialog.html.haml, src/api/app/views/webui/status_messages/_destroy_status_message_dialog.html.haml, src/api/config/routes.rb, src/api/spec/controllers/webui/main_controller_spec.rb, src/api/spec/controllers/webui/status_messages_controller_spec.rb
Status messages don't belong in `webui/main_controller`, so they are now in their own controller. The views and specs were moved too.
Minor changes in the UI for the links to be consistent. It is now always referring to *Status messages*. It was a mix of *message* and *status*.
@hennevogel and @mdeniz, please have a look.
=> [webui] Split main_controller

src/api/app/models/bs_request.rb, src/api/spec/cassettes/BsRequest/_forward_to/only_forwards_submit_requests.yml, src/api/spec/factories/bs_request_actions.rb, src/api/spec/factories/bs_requests.rb, src/api/spec/models/bs_request_spec.rb
Previously any bs request action that was forwarded would be converted
into a submit request. This doesn't really make sense and it's better to
skip such request actions for now.
=> [frontend] Forward only submit requests

dist/t/0100-check_webserver_and_api.ts
test case fail ATM with
```
1..3
ok 1 - Checking if database exists
ok 2 - Checking if tables in database api_production
ok 3 - Checking if database is started under /srv/obs/MySQL
ok
Can't locate XML/Structured.pm in @INC (you may need to install the XML::Structured module) (@INC contains: /usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.18.2 /usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.18.2 /usr/lib/perl5/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/5.18.2 /usr/lib/perl5/site_perl .) at t/0100-check_webserver_and_api.ts line 8.
BEGIN failed--compilation aborted at t/0100-check_webserver_and_api.ts line 8.
t/0100-check_webserver_and_api.ts ..... 
1..4
Dubious, test returned 2 (wstat 512, 0x200)
Failed 4/4 …
```
=> [ci] fix @INC in testcase 0100-check_webserver_and_api

src/api/config.ru
if the relative_url_root configuration (or env variable) is set,
the routes will be prefixed into this namespace.
This is necessary because this configuration only covers
the assets paths by default.
This is a "hack" I needed for deploying review apps and pushing now upstream back.
=> [frontend] Make it possible to run OBS in a subdirectory

dist/t/osc/0200-check_docker_registry.ts
The previous version of this TC relied on an output of bs_publish
'Deleting $temp_file'
With this commit we changed to check the result in the registry and
check if the temp file was removed
=> [ci] fix testcase 0200-check_docker_registry

dist/ci/travis_script.sh
Git cop is always comparing with master instead of the branch we want to
merge. Right now for 2.9 we only do cherry-picks from master that has
passed git-cop checks.
=> [ci] Disable git-cop for 2.9 branch

dist/obs-server.spec, src/api/config/initializers/git.rb
frontend code is just crashing by attempting to chomp and package
builds fail due to hard required last_deployed file in %files
=> [dist] avoid build and runtime failure when not using obs_scm

dist/README.UPDATERS
When updating OBS, it can happen that the delayed jobs table contains
pending jobs. In case that the OBS update includes a code change that
is incompatible with the object stored by delayed jobs, this can cause
breakage when once the delayed job gets executed.
This can either happen when running database migrations (see PR#4969)
or by processing the delayed jobs service.
While this can happen for any deployed OBS instance it is far more
likely this occurs in our Stable releases. This is because of the much
larger delay between creating a migration and running it (= updating the
OBS instance).
Since this can hardly be avoided, we document this limitation and how to
avoid this from happening in the updaters guide.
=> [frontend] Document how to handle delayed jobs queue during updates

dist/obs-server.spec
Include missing azure-cli package dependency needed in obs-cloud-uploader package.
=> [dist] Include azure-cli package dependency

src/api/Gemfile, src/api/Gemfile.lock, src/api/config/environments/production.rb
We wan to have in the logs at least:
* Timestamp
* Request: Method + Controller + Action + Path + Params
* Response status
* Duration: Overall / View / DB
* Remote IP
* User login
Using https://github.com/roidrage/lograge and adding some extra configurations like the following we can have a one liner log with all we need:
```ruby
config.lograge.enabled = true
config.lograge.custom_options = lambda do |event|
exceptions = %w(controller action format id)
{
params: event.payload[:params].except(*exceptions),
host: event.payload[:headers].env['REMOTE_ADDR'],
time: event.time,
user: User.current.try(:login)
}
end
```
Example of output:
```
method=POST path=/comments format=js controller=Webui::CommentsController action=create status=200 duration=1436.57 view=77.25 db=13.92 params={"utf8"=>"✓", …
```
=> Change the way we do logging in production

src/backend/BSConfig.pm.template
Solution: Add IPv6 loopback to the list of allowed addresses.
Also make others IP expressions more strict.
=> [backend] Access to backend doesn't work on IPv6 enabled server

src/api/lib/tasks/databases.rake, src/api/script/compare_structure_sql.sh
in DEFAULT from MariaDB 10.2.2 on.
This is needed to make the migration test pass
for MariaDB > and < 10.2.2.
See https://mariadb.com/kb/en/library/show-create-table/
=> Fix numbers are no longer quoted

src/api/lib/tasks/databases.rake, src/api/script/compare_structure_sql.sh
This PR will normalize the structure.sql for MariaDB > 10.2.1 (SLE15).
From MariaDB 10.2.1 on TEXT and BLOB data types can have a DEFAULT value.
As a result, from MariaDB 10.2.1, SHOW CREATE TABLE will append a DEFAULT NULL to nullable TEXT or BLOB
fields if no specific default is provided.
Therefore We normalize the structure.sql dump for the structure verify test as
long as we support SLE12/Leap 42.3 and SLE15.
https://mariadb.com/kb/en/library/show-create-table/
=> Normalize default values for text types for MariaDB > 10.2.1 (SLE15)

src/api/lib/tasks/databases.rake, src/api/script/compare_structure_sql.sh
There where several issues with the RegEx:
* sed was missing the -i inline option
* file was missing
* RegEx did not cover column names with underscores
* RegEx did not cover lines without a Charset defined
=> [api][ci] Fix normalize DEFAULT NULL values in structure.sql

src/api/app/controllers/build_controller.rb, src/backend/bs_repserver
Support a local build of a local multibuild package (untested).
Fixes: https://github.com/openSUSE/osc/issues/376 ("osc build -M something
does not work with --alternative-project")
=> Support a local build of a local multibuild package

src/api/db/migrate/20151030130011_mark_events.rb
With f558fb2974dab157eada5acb291918a224668ed0 the SendEventEmails class
got renamed.
This happened in quite some time ago (August 2017). Since we don't
backport migrations to our stable release this now caused issues for
users that updated their OBS stable release, eg. 2.8 -> 2.9.
Kudos to @DStape debugging this and pointing us to the root cause.
Fixes #4969
=> [frontend] Adopt migration after renaming class

src/api/app/controllers/webui/patchinfo_controller.rb, src/api/app/views/webui/patchinfo/_form.html.haml, src/api/app/views/webui/patchinfo/show.html.haml
Add missing **message** optional field to show and edit views in patchinfo.
Fixes #4895.
The show patchinfo screen looks like this:
The edit patchinfo screen looks like this:
=> Add missing message field to patchinfo

src/api/app/controllers/webui/package_controller.rb, src/api/config/routes.rb, src/api/test/functional/webui/spider_test.rb
We show a download link per file in the binaries view, but the
calculation of the url is expensive and can end up in performing up to
2 http request to external servers.
Now we use an internal url and there in that action we calculate the url
to redirect the user to the right place.
That way in the lis of binaries we just show simple links
This closes #4736
=> Move calculation of download for binaries to a dedicated action

src/api/lib/backend/connection_helper.rb, src/api/spec/lib/backend/connection_helper_spec.rb
Before we just replaced the provided strings into the template of the
endpoint. We now escape special url chars to not break the endpoint if there is any
in the variables passed to the placeholders.
=> Escape chars from url's path for the backend

src/api/app/controllers/webui/patchinfo_controller.rb, src/api/app/views/webui/patchinfo/_form.html.haml, src/api/app/views/webui/patchinfo/show.html.haml
Add missing **version** optional field to show and edit views in patchinfo.
The show patchinfo screen looks like this, with the version field added:
The edit patchinfo screen looks like this:
=> Add missing optional version field

src/api/app/views/webui/patchinfo/_form.html.haml
Prevent not being capable of selecting binaries in a patchinfo edit form when all the binaries are selected.
Having a set of binaries to select from like this one:
After selecting all of them:
... and saving, it was not possible to edit them any more. This was the next edit screen:
=> Prevent not selecting binaries

.rubocop.yml, dist/obs-server.spec, src/api/db/data_schema.rb
With the recent data-migrate gem update (300232b08f61112535f7001ef384d3b211ee8b2f)
data-migrate is also dumping a schema when Rails is configured that way.
This commit will adapt the OBS code to pass our test suite and rpm
package builds.
=> [frontend] Add data schema file

dist/obs-server.spec
The obs-server package includes a cron script, but does not require
the cron package.
Rpmlint recommends to either require or recommend the cron package
in such a case. Since the cron script is optional we just recommend to
install cron.
=> [dist] Recommend cron in spec file

dist/obs-rpmlintrc
Disable warnings for rpm package descriptions being shorter than the
summary.
This is only the case for the obs-devel package and not an issue to
worry about.
=> [frontend] Add rpmlintrc

dist/obs-server.spec
The obs-server package installs files to /etc/logrotate.d/.
Rpmlint recommends to either require or recommend the logrotate package
in such a case. Since logrotate is optional we just recommend to
install the package.
=> [dist] Recommend logrotate during package installation

docker-compose.yml
as we switched to OBS built docker images in #5041 we need now to specify the
command in the docker-compose file.
The reason is that we do not specify a CMD in the image built in OBS anymore
because this image is used for CI, worker and backend and every use case has a different
CMD.
=> [ci] Start test backend in docker-compose file

dist/README.devel, dist/obs-server.spec
This package contained a readme that pointed users to our github
repository.
It seems fair to assume that anyone who finds and install the obs
packages is also able to find our project page and git repo :smiley:
So let's drop this package.
=> [dist] Drop obs-devel package

dist/Makefile
Follow up of de88da41c0ff2208782... There was some leftover code
in one of our makefiles.
=> [frontend] Cleanup makefile after dropping obs-devel package

src/api/app/controllers/person/token_controller.rb, src/api/spec/controllers/person/token_controller_spec.rb
Users (eg. admins and in case of bot accounts) can request tokens
of other users. Though if the requested user does not exist we
would check the policy of nil and cause a failure.
Instead we are now setting the nobody user when no valid user
could be found.
=> [frontend] Fix policy check in token controller

ReleaseNotes-2.10
* Add features and bugfixes we did since the 2.9 release.
* Replace the regression fix for the build result page by the actual
feature implementation. The regression was caused when the binary
page got refactored and is fiexed by not.
It's not recognizable by users that upgrade from 2.9 to a future 2.10
release.
=> [dist] Update release notes

src/api/app/controllers/webui/patchinfo_controller.rb, src/api/config/routes.rb
- Fix preserving `package` and `releasetarget` elements after editing a patchinfo.
- Remove `get patchinfo/read_patchinfo` route as it is not used in any place.
This is another approach to a work started in #5019.
=> Patchinfo fixes and refactoring

src/api/Gemfile
Until we switch to bundle-gems service or our gem packaging scripts have a way
to deal with conflicting executeables.
=> [dist] Termporarily disable annotate gem

src/api/lib/rabbitmq_bus.rb
There is no need to catch only a subset of exceptions. If the connection
to rabbitmq somehow goes wrong it should never populate to the user.
Log and notify everything instead.
=> [frontend] Never raise an exception in RabbitmqBus

src/api/app/views/webui/users/tasks/index.html.haml
as we only display the overall number of tasks in the header and users do not know
in which group the tasks are.
Fix #4904.
Co-authored-by: Marwin Olschner <marwin01@hotmail.de>
=> [frontend] Add counters for tasks table headers

.circleci/config.yml
because we changed the user inside the container which resulted
in wrong user permission errors.
To invalidate the cache in CircleCI we need to change the cache key.
Supersedes https://github.com/openSUSE/open-build-service/pull/5101
=> [ci] Invalidate CircleCI caches

src/api/app/controllers/source_controller.rb, src/api/app/controllers/source_project_controller.rb, src/api/app/views/source_project/show.xml.builder, src/api/config/routes.rb, src/api/spec/cassettes/SourceController/PUT_update_project_config/1_4_1.yml, src/api/spec/cassettes/SourceController/PUT_update_project_config/1_4_2.yml, src/api/spec/controllers/source_controller_spec.rb, src/api/spec/controllers/source_project_controller_spec.rb, src/api/test/functional/read_permission_test.rb, src/api/test/functional/request_controller_test.rb, src/api/test/functional/source_controller_test.rb
break the huge souce_controller in sub controllers
=> Refactor source controller (second interaction) 

src/api/app/controllers/source_project_controller.rb, src/api/app/controllers/source_project_meta_controller.rb, src/api/config/routes.rb, src/api/spec/cassettes/SourceProjectMetaController/GET_show/1_1_1.yml, src/api/spec/cassettes/SourceProjectMetaController/GET_show/1_1_2.yml, src/api/spec/controllers/source_project_meta_controller_spec.rb, src/api/test/functional/read_permission_test.rb, src/api/test/functional/request_controller_test.rb, src/api/test/functional/source_controller_test.rb
third iteration of source_controller refactoring. Now I moved the "project meta" related code from ```source_project_controller``` to its own controller ```source_project_meta_controller```. 
minispec and rspec suites were updated too.
=> [api] move project meta actions to its own controller and make it REST

src/api/config/initializers/git.rb
instead of the atime (access time).
This caused to show wrong timestamps for the last deployment time.
=> [frontend] Use mtime to show last deployment time

.gitignore, contrib/start_lint, contrib/start_minitest, contrib/start_rspec, contrib/start_spider
because the CI containers install into vendor/bundle and create a bundle config.
This causes gem installation failures in the development container.
We also remove this directories from the .gitignore so that we recognize if something is
odd with the development setup.
=> [ci][frontend] Remove .bundle & vendor/bundle dirs after CI run

src/api/Gemfile, src/api/Gemfile.lock, src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/stylesheets/webui2/sticky-footer.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/webui_controller.rb, src/api/app/views/layouts/webui2/_breadcrumbs.html.haml, src/api/app/views/layouts/webui2/_flash.html.haml, src/api/app/views/layouts/webui2/_footer.html.haml, src/api/app/views/layouts/webui2/_navigation.html.haml, src/api/app/views/layouts/webui2/_personal_navigation.html.haml, src/api/app/views/layouts/webui2/_search.html.haml, src/api/app/views/layouts/webui2/_watchlist.html.haml, src/api/app/views/layouts/webui2/_watchlist_dropdown.html.haml, src/api/app/views/layouts/webui2/webui.html.haml, src/api/config/initializers/assets.rb
For certain actions and certain users we want to switch to a new bootstrap
based layout while for everyone else things should stay the same.
Adding the `switch_to_webui2` method to a controllers `index` action will
1. switch the layout to bootstrap
2. switch the view path to files below `app/views/webui2`
3. call the `webui2_index` method of the controller (if it exists)
That means you are flexible to overwrite only how the action is rendered (by
adding `switch_to_webui2` to the end of your controller method) or can also
overwrite what you do in the action (by putting it on the top of your method).
Co-authored-by: Moises Deniz Aleman <mdeniz@suse.com>
Co-authored-by: Stasiek Michalski <hellcp@opensuse.org>
=> Introduces switch to a new layout

src/api/Gemfile
since I moved the XML Builder from controller to the view https://github.com/openSUSE/open-build-service/commit/ae0966968b96378926076e4f88c4a7e48acae9f5#diff-ef87c76ec3b8d2870b8ddcf9fb2389c1L880 and the eager load in the development environment is turned off, if we try to call the action source#global_branch (which calls branch_package#report_dryrun, the frontend server explodes with the following backtrace:
```
frontend_1  | 08:55:54 web.1         | 
frontend_1  | 08:55:54 web.1         | [a6ce1db3-e142-453d-aa95-8468552b51a8] [62:3563.07]   
frontend_1  | 08:55:54 web.1         | [a6ce1db3-e142-453d-aa95-8468552b51a8] [62:3563.07] NameError (uninitialized constant Builder::XmlMarkup):
frontend_1  | 08:55:54 web.1         | [a6ce1db3-e142-453d-aa95-8468552b51a8] [62:3563.07] …
```
=> [api] require builder gem to avoid issues in the development environment

src/api/Gemfile.lock
We updated the Gemfile by explicitly adding builder there. Since we've
already been using builder and thus having it in Gemfile.lock, we
didn't update our bundle.
But apperently we should have^^
Follow up of 518225f4b3e6c91ed121097af225706164034f52.
=> [frontend] Update Gemfile.lock

contrib/start_lint, contrib/start_minitest, contrib/start_rspec, contrib/start_spider
because in CI it does not matter as we anyway start a new machine with every CI run.
This caused that the CI runs in Travis always succeeded because of the last command (rm)
always returned a succeeded status.
=> [ci] Only remove .bundle & vendor dir outside of CI

src/api/app/controllers/webui/packages/build_reason_controller.rb, src/api/app/models/package.rb, src/api/spec/controllers/webui/packages/build_reason_controller_spec.rb
We've been temporarely converting the xml string, eg. '<a></b>' to
a Nokogiri::XML object before creating a hash from it.
By using Xmlhash#parse we can skip the intermediate step and directly
create a hash.
This reduces the code and slightly improves the performance of that
method.
=> [frontend] Refactor Package#last_build_reason

src/api/app/models/binary_release.rb
When a binary doesn't have a buildtime OBS was causing an exception,
because we were not handling this case.
This fixes the issue.
Fixes #5045
=> [frontend] Fixes undefined method `to_datetime' for nil:NilClass

contrib/start_lint, contrib/start_minitest, contrib/start_rspec, contrib/start_spider, src/api/spec/controllers/source_project_config_controller_spec.rb
otherwise the container exits successfully. This makes it work in Travis and locally.
Co-authored-by: Victor Pereira <vpereirabr@gmail.com>
=> [ci] Return test exit status from Travis start scripts

src/api/Gemfile, src/api/Gemfile.lock
Now that errbit have been released (it only took some months :rofl:) we should be able to update airbrake-ruby to last version:
https://github.com/errbit/errbit/issues/1247
:tada: :tada: 
There is already a package: https://build.opensuse.org/package/show/devel:languages:ruby:extensions/rubygem-airbrake-ruby
=> [ci] Update airbrake-ruby gem

src/api/lib/obsapi/markdown_renderer.rb, src/api/spec/helpers/comment_helper_spec.rb
Since commit c466c65d67cfd01e877aca224dd6aa3dd5fea06c we overwrite
the redcarpet renderer for links and add the OBS domain to relative
links.
The code that would craft these URIs wasn't expecting invalid links
and would fail with an URI::InvalidURIError exception.
This commit catches such exceptions and renders the invalid markdown
in the same format Redcarpet would do.
=> [frontend] Fix rendering invalid markdown links

dist/obs-server.spec
This reverts commit 95b9342defb17ee0939a759a108c4475b61e217d.
The mtime is the buildtime of the RPM package so we can not use it.
The atime is the installation time, so we stick with it.
Seems like sth messed with the atime back then but it general this is what we want.
=> Touch last_deploy file in %post to have correct deploy time

src/api/app/views/webui/request/_superseded_by_message.html.haml
In case of having several superseded requests it was added an unneeded space before commas. This way these spaces are removed.
For example:
=> Remove space before commas

src/api/app/controllers/webui/package_controller.rb, src/api/app/models/repository.rb
Download link was broken. It was trying to download a binary with a
wrong package name.
Fix #4985
=> Fix download link in binaries and details page

src/api/app/models/binary_release.rb
Caused by 536e6dc161d14f34404f17749e38dac8560cf136
=> [frontend] Fix typo in BinaryRelease model

.circleci/config.yml, src/api/app/controllers/webui/webui_controller.rb, src/api/config/feature.yml, src/api/script/api_test_in_spec.sh, src/api/spec/README.md, src/api/spec/browser_helper.rb, src/api/spec/support/features/features_bootstrap.rb, src/api/spec/support/features/features_rspec_retry.rb
During the period of migrating our views to bootstrap, we need to run the feature tests twice.
One time with bootstrap disabled and one time with bootstrap disabled.
This can be triggered by setting the BOOTSTRAP environment variable and
excluding the spec/bootstrap/ directory from rspec (see .circleci/config.yml).
If a test does not run with reasonable effort with bootstrap enabled,
the test can get skipped with skip_if_bootstrap and we can
implement a test in spec/bootstrap/ directory.
I will add more explanation to a dedicated wiki page after this PR is merged.
=> Implement feature test suite for bootstrap theming

src/api/app/views/webui/obs_factory/staging_projects/_problems.html.erb
OBS was not specifying the template when rendering openqa_jobs.
This caused that the application did not find the partial and broke the
staging project page. Explicitly setting the template to render
solves this.
=> [frontend] Fix rendering of openqa_job template

src/api/spec/features/webui/projects_spec.rb
Wait for the repository container to appear before checking
things within it
=> [ci] Fix flaky DoD test

src/api/app/views/webui/request/_superseded_by_message.html.haml
`succeed` appends a string to the end of a Haml block, and `surround` appends strings to the end and the beginning. Because of that, if we already need to use `surround`, it doesn't make sense to use `succeed` as well. It is also more readable, as what we want is just a comma after the closing parenthesis. :nerd_face: 
We want a comma except for the last record, because of that I think that it is more readable to use `superseding.last` than using an index and comparing it with `superseding.length - 1`. This way we also don't need to use `each_with_index`, as we don't really care of what index every record have. This may be a matter of taste, but I find it more elegant. :bowtie:
=> Refactor how we render superseded requests list

src/api/spec/features/webui/packages_spec.rb
This test started to fail constantly because of having multiple whitespaces
instead of one in a sentence show on the bs request page.
Using a regex and allowing newlines / multiple whitespace fixes this.
=> [ci] Make feature test more flexible

src/api/.rubocop_todo.yml, src/api/app/models/user.rb
`Hash#keys.include?` is less efficient than `Hash#key?`
because the former allocates a new array and then performs
an O(n) search through that array, while `Hash#key?` does
not allocate any array and performs a faster O(1) search
for the key.
=> [frontend] Fix slow hash performance (rubocop)

src/api/app/views/webui/obs_factory/staging_projects/_openqa_jobs.html.erb
Sub-projects of the staging projects would cause a 500 due to broken
rendering. We already solved a similiar issue in 46838faab49589d4513cc
and overlooked that this page was broken as well.
F, [2018-06-25T08:09:55.491889 #16020] FATAL -- : [c7807bec-311c-4626-a2d3-dc4d84559596] [16020:673.15] ActionView::Template::Error (Missing partial webui/obs_factory/obs_factory/openqa_jobs/_openqa_job with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :haml]}. Searched in:
* "/srv/www/obs/api/app/views/webui/theme/bento"
* "/srv/www/obs/api/app/views"
* "/usr/lib64/ruby/gems/2.5.0/gems/peek-mysql2-1.2.0/app/views"
* "/usr/lib64/ruby/gems/2.5.0/gems/peek-host-1.0.0/app/views"
* "/usr/lib64/ruby/gems/2.5.0/gems/peek-dalli-1.2.0/app/views"
* …
=> [frontend] Fix rendering of staging project rings

src/api/lib/tasks/dev.rake
Prevent loading `rubocop/rake_task` gem in such tasks as `dev:boostrap`, needed when creating the `obs-api` package.
=> Require rubocop/rake_task gem only when needed

CONTRIBUTING.md
Fixes a documentation regression introduced by 81542e1db.
=> [doc] Fix outdated reference to :frontend in CONTRIBUTING.md

.circleci/config.yml, contrib/start_test_db, docker-compose.ci.yml
Before we used a tmpfs in Travis. As this is not possible in CircleCI
we directly mount the data directory into /dev/shm.
=> [ci] Use in memory database in CI

src/api/spec/README.md, src/api/spec/browser_helper.rb, src/api/spec/features/webui/projects_spec.rb, src/api/spec/support/features/features_rspec_retry.rb
It is now possible to flag a test with retry: 3 to also retry in CI.
Before it was only enabled for package builds in OBS.
However, we had some flaky tests in CI which we now explicit set.
This makes it possible to maintain a list of flaky tests with the advantage
of running these flaky tests nevertheless.
=> [ci] Enable rspec-retry again when explicit set for a feature test

src/api/app/models/obs_factory/staging_project.rb
After updating the initial implementation of RuboCop rake tasks for OBS (#5173)
we switched to using the RuboCop::RakeTask library (#5182).
This change caused that the *:all task was only running one of the two
RuboCop setups in our test suite.
PR#5219 solved that issue and this commit cleans up the remaining
RuboCop offenses.
=> [frontend] Fix rubocop offense: Naming/PredicateName

src/backend/bs_service, src/backend/call-service-in-docker.sh
This is required in to ensure in service, that they were started
by OBS. Services can then try to fix problems like broken caches
automatically.
=> [backend] new env var OBS_SERVICE_DAEMON in bs_service

src/api/.rubocop_todo.yml, src/api/app/helpers/webui/obs_factory/application_helper.rb, src/api/app/models/obs_factory/distribution_strategy_opensuse.rb, src/api/app/views/webui/obs_factory/distributions/show.html.haml, src/api/spec/helpers/webui/obs_factory/application_helper_spec.rb, src/api/spec/models/obs_factory/distribution_strategy_opensuse_spec.rb
For openSUSE Leap 15.1 we want to switch the openQA workflow to mention
the major number or the "codestream" only for openQA job groups to save
the setup effort.
Related progress issue: https://progress.opensuse.org/issues/37105
=> [frontend] Adapt openQA job group version resolution for openSUSE Leap 15

src/api/spec/cassettes/Login/in_kerberos_mode/for_a_request_that_requires_authentication/and_Negotiate_header_is_not_set/informs_the_client_tool_browser_that_kerberos_authentication_is_required.yml, src/api/spec/cassettes/Login/in_kerberos_mode/for_a_request_that_requires_authentication/and_Negotiate_header_is_not_set/informs_users_about_failed_kerberos_authentication_and_possible_cause.yml, src/api/spec/cassettes/Login/in_kerberos_mode/for_a_request_with_valid_kerberos_ticket/authenticates_the_user.yml, src/api/spec/cassettes/Login/login_via_widget.yml, src/api/spec/rails_helper.rb, src/api/spec/support/cache.rb
With things like database_cleaner you really want to make sure that
tests don't pollute each other with stale cache items
(rails defaults to null_store in test environment, but that's a
harsher measure)
=> [ci] Reset the cache before each rspec suite

.circleci/config.yml, contrib/start_minitest, contrib/start_spider, docker-compose.ci.yml, src/api/script/api_test_in_spec.sh, src/api/script/start_test_backend
The rails cache store used is mem_store, which is purely
in process. Dalli is only used in product and development
=> [ci] No need to start memcached for tests

src/api/app/controllers/webui/search_controller.rb, src/api/app/models/package.rb, src/api/spec/models/package_spec.rb
before we ignored multibuild packages when searching with a distribution URL.
Fix #5232.
=> Support search for multibuild packages

src/api/app/models/obs_factory/distribution_strategy_opensuse.rb, src/api/spec/models/obs_factory/distribution_strategy_opensuse_spec.rb
Use a regex with named captures to make it more visible what we print
out for the various *_version methods.
=> [frontend] Refactor parsing of openSUSE Leap version

.circleci/config.yml, Rakefile, docker-compose.ci.yml
This frees the namespace for a backend container that runs
the backend for frontend tests
=> [ci] Rename the backend test to backend_test

src/api/.rubocop_todo.yml, src/api/spec/controllers/webui/session_controller_spec.rb, src/api/spec/features/webui/login_spec.rb
Fiddling with browser headers in feature tests is problematic
(only poltergeist supports it), controller tests are much
better suited for that. Especially as we're hardly interested
in any javascript around kerberos
=> [ci] Migrate kerberos spec to controller spec

src/api/app/assets/javascripts/webui/application/comment.js, src/api/app/views/webui/comment/_reply.html.haml
because otherwise the user needs to do two clicks before he can write a comment.
Fix #5055.
=> [webui] Add focus to reply comment textarea

dist/obs-server.spec, src/api/Gemfile, src/api/Gemfile.lock, src/api/config/unicorn/development.rb
Unicorn was needed in 2012 to merge app and webui as we had
multiple requests on one page and webrick is not multithreaded
But unicorn is pretty much dead by now and puma the default
app server if you start a new rails app
=> [frontend] Switch from unicorn to puma as app server

.circleci/config.yml
I built the docker images now with native docker and used the bundle gems service. Let's see if CI works.
https://build.opensuse.org/project/show/home:cbruckmayer:containers
=> [CI] Try with docker build OBS images

src/backend/BSBuild.pm
It was different to the implementation in perl-BSSolv, leading
to endless rebuilds in some rare cases.
=> [backend] fix implementation of genmetaalgo 1 in BSBuild

CONTRIBUTING.md
This simply is not prepared to be ran with any other uid than
1000 and is not really something that we should point new
contributors to.
=> [dist] Get the CI containers out of the dev environment

docker-compose.yml, src/api/Procfile
After we switched from unicorn to puma in #5284, the rails development server
started to run on port 5000.
This is caused by foreman as it sets the PORT environment variable to 5000.
There is also a bug in puma which does not respect the puma.rb configuration
when the  environment variable is set.
https://github.com/puma/puma/issues/939
Furthermore we need to bind now to 0.0.0.0 as puma binds by default to localhost
which is not exposed by docker.
=> [webui] Run puma on port 3000 in dev

src/api/spec/controllers/webui/session_controller_spec.rb, src/api/spec/features/webui/login_spec.rb
proxy mode works with http headers, that you aren't able to control
as browser. So test the controller code (slightly misusing the
session controller)
=> [ci] Move 2 more login specs from feature to controller spec

src/api/app/helpers/webui/request_helper.rb, src/api/app/views/shared/_sourcediff.html.haml, src/api/spec/helpers/webui/request_helper_spec.rb
We just displayed the new name with changed which was confusing
because it is expected that we show the removed / renamed files.
Fix #4971.
=> [webui] Reflect renaming of files in submit requests

src/api/app/controllers/webui/user_controller.rb
`params[:size].to_i` will always return a truthy value, so whatever comes after is never reached.
=> Remove unreachable code

src/api/app/helpers/webui/request_helper.rb, src/api/app/views/webui/request/show.html.erb
and remove the links from the decision comment tabs.
Because this 'broke' the tabs as half of the tab was a link
to the user/group/package/project show page and
the other half was the actual tab change.
For user reviews it also included the user icon which looked broke the CSS.
The links are now at the top of the page so no need to add it to the tab.
Fix #4679 
Top of the page
Decision comments tab
=> [webui] Show all open reviews at top of request page

src/api/app/models/user.rb, src/api/spec/models/user_spec.rb
Also remove unnecessary ASCII-8BIT encoding.
=> Create tests for gravatar_image in User model

src/api/app/mixins/has_relationships.rb, src/api/app/models/relationship.rb
"Dangerous query method (method whose arguments are used as raw SQL) called
with non-attribute argument(s): "groups.title as title", "roles.title as
role_name". Non-attribute arguments will be disallowed in Rails 6.0."
Fixes #5133
=> [frontend] Fix deprecation warnings for raw sql

.circleci/config.yml
- DRY and use more aliases
- add some whitespace between the jobs and aliases
- fix gem caching (you can't restore files in /usr due to permissions)
- start the workflow with a checkout_code job to
only install dependencies and prepare assets once
- move lint into the same group as the others
The overall workflow time is reduced from ~33 minutes to ~21 minutes
and is prepared to reduce this even more applying parallalism
=> [ci] Several improvements to the circleci config

.travis.yml
No need to lint twice and travis has enough to do without
=> [ci] Disable lint on travis-ci

src/api/app/controllers/attribute_controller.rb, src/api/spec/controllers/attribute_controller_spec.rb
POST needs to be done twice in tests - as :update is both
create and update in the attributes API
Fixes #5290
=> [frontend] Fix update on attribute types

.circleci/config.yml, src/api/.rubocop.yml, src/api/lib/tasks/dev.rake
With proper rubocop caching, it only takes a couple of seconds.
=> Circleci: merge the linting into the checkout_code job

.circleci/config.yml, codecov.yml, src/api/Gemfile, src/api/Gemfile.lock, src/api/lib/tasks/coverage.rake, src/api/spec/support/coverage.rb, src/api/test/test_helper.rb
This allows several benefits:
- we always have HTML reports within circleci artefacts
- we avoid bugs in merges on coverage services
- the coverage services don't have to wait - if we upload,
we're done
- the coverage can be grouped as wildly as we need it,
it can be done within the merge task
Codecov still does not report status back reliable, but coveralls
seems to have no problem with it. It doesn't hurt to report into
both though - if we let coveralls not comment but only report
status we can have codecov comments as optional. It will be 100%
the same coverage we calculated ourselves on circleci
Reused the existing lib/tasks/coverage.rake that wasn't in used
since 2012 (when travis+coveralls became a valid option)
=> [ci] Do not report indivual coverage reports but merge manually

src/api/app/controllers/services/webhooks_controller.rb, src/api/app/models/token/service.rb, src/api/app/views/person/token/create.xml.builder, src/api/config/routes.rb, src/api/spec/cassettes/Services_WebhooksController/_create/with_HTTP_X-Pagure-Signature-256_http_header/behaves_like_it_verifies_the_signature/when_signature_is_valid/1_1_3_1_1_1.yml, src/api/spec/cassettes/Services_WebhooksController/_create/with_HTTP_X_HUB_SIGNATURE_http_header/behaves_like_it_verifies_the_signature/when_signature_is_valid/1_1_2_1_1_1.yml, src/api/spec/cassettes/Services_WebhooksController/_create/with_HTTP_X_OBS_SIGNATURE_http_header/behaves_like_it_verifies_the_signature/when_signature_is_valid/1_1_1_1_1_1.yml, src/api/spec/controllers/services/webhooks_controller_spec.rb, src/api/spec/factories/tokens.rb, src/api/spec/models/token/service_spec.rb
GitHub announced the deprecation of GitHub services in favor of
webhooks (on January 31, 2019 GitHub will stop
delivering services events).
WebHooks are designed different than services, therefore it was necessary to
implement a dedicated controller.
Unlike the OBS GitHub service, webhooks do not deliver the token anymore
in the HTTP Header. Because of that it is not possible to compare
the tokens anymore as part of the authentication process.
We used this opportunity to implement generic webhooks which support
for now GitHub, Pagure and a generic webhook.
To trigger a webhook, it is now necessary to generate a signature
over the payload body with the secret token.
To authorize, OBS verifies this signature.
OBS supports for now three different HTTP header to submit this signature:
* …
=> [api] Implement webhooks

src/backend/bs_service
Service sub-process does not inherit the http_proxy/https_proxy variables, redeclaring from BSConfig.pm information.
=> [backend] Services do not inherit proxy information

src/api/spec/models/service_spec.rb
as this service expects a tar archive. We need to transfer this test
to a more integration like test e.g. in Package#save_file.
=> [ci] Skip broken addKiwiImport service test

src/api/app/helpers/webui/user_helper.rb, src/api/spec/helpers/webui/user_helper_spec.rb
Reference Gravatar avatars from a HTTPS scheme URI. Avoids mixed content warnings.
Fixes #5388
=> Reference Gravatar avatars from a HTTPS scheme URI

.travis.yml, Rakefile, dist/obs-server.spec, docker-compose.ci.yml, docker-compose.selenium.yml, docker-compose.yml, docker-files/base/docker-bootstrap.sh, src/api/Gemfile, src/api/Gemfile.lock, src/api/app/assets/javascripts/webui/application/image_templates.js, src/api/app/views/webui/image_templates/index.html.haml, src/api/spec/cassettes/Projects/locked_projects/fail_to_unlock.yml, src/api/spec/cassettes/Projects/locked_projects/unlock.yml, src/api/spec/cassettes/Sign_up/User.yml, src/api/spec/features/webui/image_templates_spec.rb, src/api/spec/features/webui/packages_spec.rb, src/api/spec/features/webui/projects_spec.rb, src/api/spec/features/webui/sign_up_spec.rb, src/api/spec/support/capybara.rb, src/api/spec/support/vcr.rb
chromium is a beast with many dependencies and as such is pretty expensive within the frontend container. As communication with the driver is through tcp, leaving the chromedriver in a container in itself is possible, if not natural.
This makes it possible to use *any* container, there is no need to build it against the SUT's platform. I picked a debian one from github, but we could replace it also with a Tumbleweed or Leap15 one.
And no, it doesn't work as yet and there are some parts left from my attempts to run chromium within container.
=> Drop phantomjs and run against selenium container with chrome

src/api/spec/support/vcr.rb
If a test case requires new routes, the cassette has to be
recreated from scratch. Only this way you can guarantee that
the test case still works without cassette
=> [rspec] Make it fatal to add to a cassette

dist/setup-appliance.sh
Without this change, the following errors are raise while
generating a gpg key in setup-appliance.sh:
gpg: Generating a default OBS instance key
gpg: agent_genkey failed: End of file
gpg: key generation failed: End of file
later on this will result in hanging publishing/signing process
when containers should be signed:
gpg: skipped "defaultkey@localobs": No secret key
gpg: signing failed: No secret key
sign failed: sign /srv/obs/jobs/x86_64/BaseContainer::images::openSUSE-Leap-Container-Base
=> [dist] enable empty passphrase for autogenerated gpg keys

src/api/app/views/webui/search/_results.html.haml
After fixing the indexes and make it possible to search by title and/or description (see #5385) it is usefull to see in the results of the search the title of a project or a package.
Now ": Foo" is shown as the title, next to "test".
=> Add title field in search results

src/api/app/views/webui/obs_factory/staging_projects/show.html.erb
The `show` view of staging project was unable to found the correct
template for the `requests`, it was taking
`webui/obs_factory/obs_factory/requests/_request` instead of
`webui/obs_factory/requests/_request`.
=> Fix template_path in staging_project show view

src/api/spec/models/obs_factory/staging_project_spec.rb
by stubbing requests to openqa.opensuse.org
Fixes #5404
=> [ci] Make sure the staging_project_spec works offline

src/api/.rubocop.yml, src/api/app/models/obs_factory/distribution.rb, src/api/app/models/obs_factory/distribution_strategy_opensuse_leap15.rb, src/api/spec/helpers/webui/obs_factory/application_helper_spec.rb, src/api/spec/models/obs_factory/distribution_spec.rb, src/api/spec/models/obs_factory/distribution_strategy_opensuse_leap15_spec.rb, src/api/spec/models/obs_factory/distribution_strategy_opensuse_spec.rb, src/api/spec/models/obs_factory/staging_project_spec.rb
The dashboard code was adopted for the product converter
used in Leap 15. As 42.X is no longer in development,
there is no point in maintaining it
Fixes #5410
=> [webui] Rename openSUSE strategy to openSUSE Leap 15

dist/obs-server.spec
(and remove Xvfb not used since introducing phantomjs in 2013)
=> [dist] Add fonts for chromium tests

.circleci/config.yml, src/api/lib/tasks/dev.rake
circleci has the repo in cache and if we change the example
files, they should be used - not the cached ones
=> [ci] Force the copying of example config files on dev:prepare

src/api/spec/support/database_cleaner.rb
As followup on #5327 - reseeding the database on every
test run is super conservative and steals a lot of developer
time for the sake of being safe on very rare test crashes
Truncating the static tables is good enough for normal test
crashes. The model tests run in transactions, so don't
interfere with the database - but are the ones most likely
to break.
And in case the database is busted, recreating it is just
as fast/slow as what we basically did before every test
run.
The reseeding takes on my system ~10 seconds - and according
to dmarcoux's comment in 5327 on his it's a minute. So drop it
=> [ci] Don't reseed the database on every test start

src/api/app/controllers/webui/obs_factory/distributions_controller.rb, src/api/app/controllers/webui/obs_factory/staging_projects_controller.rb
In test environment we don't eagerly load all classes,
so ruby does not know there is a 2nd ApplicationController
class in the module - and takes the one from API.
But this one (for one) requires login - which we don't
want for Staging dashboard.
Fixes #5431
:crossed_fingers:
=> [frontend] Make baseclass of Factory controllers explicit

src/api/app/controllers/webui/obs_factory/staging_projects_controller.rb, src/api/app/views/webui/obs_factory/staging_projects/_infos.html.haml
Commit 515fafba5d0055058b406ff8e00c24e8cec3975f was merging the obs
factory request model into the bs request model. This required some
variable renaming.
Since package and project are very common in OBS some variables got
overlooked and caused breakage.
=> Fix wrong variable names used in staging dashboard

src/api/app/views/webui/obs_factory/requests/_request.html.erb
Recently we integrate `Request` model into `BsRequest`, so now we use
`BsRequest` instead of `Request`.
=> Use BsRequest instead of Request

src/api/spec/models/backend/file_spec.rb
Creating the package and file needs put, so instanciate
it in the backend before breaking/stubing put
#global_write_through_must_die
=> Fix backend/file_spec with global_write_through

src/api/app/models/obs_factory/distribution_strategy_opensuse_leap15.rb, src/api/spec/models/obs_factory/distribution_strategy_opensuse_leap15_spec.rb
Leap's iso has a prefix openSUSE-Leap:15.1-Staging on openQA, da8aa358 changed it to the wrong path, therefore Leap Staging Dashboard unable to find relevant openQA jobs result.
=> [webui] Fix wrong openqa_iso_prefix for Leap 15

.gitmessage, CONTRIBUTING.md
Describe labels in the wiki as a deprecated feature.
@openSUSE/obs-frontend, please review this.
=> Remove reference to label from git message and wiki

dist/t/osc/0200-check_docker_registry.ts
Whithout this patch, integration tests in 2.9 fail, because the old repo schema in 2.9 included the architecture, which is obsolete with "fat manifests"
This patch ensures that both repos
basecontainer/images/opensuse
basecontainer/images/x86_64/opensuse
are accepted in the test case
=> [dist] fix osc checks for upload docker images

src/api/app/helpers/webui/webui_helper.rb
Because in bs_request_actions_delete `source_project` should be `nil'
and the `length` of `nil` raise an exception.
Fix #5472
=> Convert nil to string for links in datatable

src/api/spec/support/vcr.rb
We had repeatedly the case that the packages don't build in
OBS due to tests accessing download.opensuse.org
So make download.opensuse.org unavailable by default - unless
the test stubs a more specific URL
WDYT?
=> Stub download.opensuse.org and gravatar.com globally

ReleaseNotes-2.10, src/api/.rubocop.yml, src/api/config/database.yml.example, src/api/db/migrate/20140624101042_add_package_tracking.rb, src/api/db/migrate/20140627071042_product_media_tracking.rb, src/api/db/migrate/20140709071042_product_medium_tracking.rb, src/api/db/migrate/20140717101042_add_updateinfo_tracking.rb, src/api/db/migrate/20140729101042_updateinfo_tracking_second_attempt.rb, src/api/db/migrate/20140801071042_product_version_tracking.rb, src/api/db/migrate/20140903125426_add_generic_operation_history.rb, src/api/db/migrate/20141110105426_fix_product_media_uniq_index.rb, src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb, src/api/db/migrate/20170619111734_alter_notifications_to_use_polymorphic.rb, src/api/db/migrate/20171218160607_create_ec2_configuration.rb, src/api/db/migrate/20180720082742_switch_to_utf8mb4.rb, src/api/db/structure.sql, src/api/script/api_test_in_spec.sh, src/api/spec/models/comment_spec.rb
Allows emojis and fixes #3547
This charset change requires mysql 5.5, which was released 2012
but is still not the default. See more details about the problem
on https://railsmachine.com/articles/2017/05/19/converting-a-rails-database-to-utf8mb4.html
I borrowed the migration from there - but limited it to comments,
the charset is backward compatible, but requires changes to database.yml
in production (to store emojis not to apply the migration)
=> [frontend] Store comments.body as utf8mb4

src/api/app/models/project.rb, src/api/spec/cassettes/Project/_branch_remote_repositories/kiwi_project/1_6_2_2.yml, src/api/spec/cassettes/Project/_branch_remote_repositories/kiwi_project/1_6_2_3.yml, src/api/spec/cassettes/Project/_branch_remote_repositories/kiwi_project/has_proper_project_xml.yml, src/api/spec/models/project_spec.rb
to_axml reads from Rails.cache but as the function mungles
the XML on a raw base, better use the direct XML not the
cached one.
This avoids races a little better - and fixes #5319
=> [api] Fix branch_remote_repositories not to rely on cache

dist/obs-bundled-gems.spec, dist/obsapidelayed
Removing the uninstalled bins was a little too eager,
the clockword binstub calls the other one as daemon,
so just don't remove any
Fixes #5489
=> Run the proper clockworkd binstub

dist/obs-api-testsuite-rspec.spec, dist/obs-bundled-gems.spec, dist/obs-server.spec, src/api/Makefile, src/api/script/api_minitest.sh, src/api/script/prepare_spec_tests.sh
This allows to accelerate the build time and build disable
the rspec test suite on platforms where we don't want to run
them instead of hiding this in prj config
=> Split rspec test suite into its own spec file

CONTRIBUTING.md
- Make the request for contributions more prominent
- Don't bother people with 'alternate ways' of setting up the git commit message template
- Add commit/PR guidelines (partly stolen from https://github.com/rtbkit/rtbkit)
- Add a nice get-Help section
- split out review section
This should prepare new contributors better for producing changes that we
will actually merge.
=> Add commit/pull-request guidelines

src/api/app/views/layouts/webui2/_search.html.haml
Related to the new framework.
Entering some text in the search box in the main navigation bar and pressing enter din't pass the `search_text` parameter to the search page, an resulted in a search with an empty string.
=> Fix search box in the main navigation bar

docker-files/base/docker-bootstrap.sh
We don't use the mysql2 rubygem package anymore after #5397
=> Fix frontend-base container bootstrap

src/api/.rubocop_todo.yml, src/api/app/controllers/webui/obs_factory/staging_projects_controller.rb
Prefer using YAML.safe_load over YAML.load.
This restricts the kind of objects that will be deserialized by YAML.load
and avoid exploits.
https://ruby-doc.org/stdlib-2.3.3/libdoc/yaml/rdoc/YAML.html#module-YAML-label-Security
http://www.benjaminfleischer.com/2013/03/20/yaml-and-security-in-ruby/
=> Solve Security/YAMLLoad cop

src/api/spec/cassettes/BsRequestAction_Differ_ForSource/_perform/with_error/1_1_2_1.yml, src/api/spec/models/bs_request_action/differ/for_source_spec.rb
The cassettes only contained a 404 for a package that the
test didn't create due to missing global_write_through
#globalwritethroughmustdie
=> Request differ: Fix one more test case that is invalid without cassettes

src/api/spec/cassettes/PublicController/GET_project_index/without_view_specified/1_6_1_1.yml, src/api/spec/cassettes/PublicController/GET_project_index/without_view_specified/1_6_1_2.yml, src/api/spec/cassettes/PublicController/GET_project_index/without_view_specified/1_6_1_3.yml, src/api/spec/cassettes/PublicController/GET_project_index/without_view_specified/1_6_1_4.yml, src/api/spec/controllers/public_controller_spec.rb
The cassette contains a package that the test never
actually generates - blindly assuming another test
creates it, depending on the order
=> Fix PublicControllTest to work reliably without VCR

src/api/spec/cassettes/BsRequestAction_Differ_ForSource/_perform/with_error/1_1_2_1.yml, src/api/spec/models/bs_request_action/differ/for_source_spec.rb
The stub_request was using the project not its name,
which lead to the request appearing in cassettes - which
should have been a warning sign :(
#globalwritethroughmustdie
=> Fix my fix for BsRequestAction_Differ_ForSource

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/package/binary.html.erb, src/api/spec/controllers/webui/package_controller_spec.rb
It fixes #5449.
Added some before_action to require the architecture and the repository. Plus some fixes, the single click redirection wasn't working, also a redirect was missing when an exception is thrown from the backend.
=> Fix issue 5449

src/api/app/views/webui2/webui/package/_commit_item.html.haml
I noticed the gap between the comment section and the `Browse Source` link, which is a bit too much.
Before my changes:
After my changes:
=> Adjust margin-bottom for pre tag in package#revisions

src/api/app/controllers/webui/projects/rebuild_times_controller.rb, src/api/app/models/builddep_info.rb, src/api/app/models/repository.rb, src/api/config/initializers/activexml.rb, src/api/lib/backend/api/build_results/binaries.rb, src/api/spec/controllers/webui/projects/rebuild_times_controller_spec.rb, src/api/spec/models/repository_spec.rb
It's just yet another mapping to a backend route
=> Remove BuilddepInfo 'model'

src/backend/bs_regpush
This patch prevents bs_regpush from crashing if no tags are available
in the registry.
The registry could return a json like the following:
{"name":"home/m0ses/mycontainer","tags":null}
which results in an error message like
Can't use an undefined value as an ARRAY reference at /usr/lib/obs/server/bs_regpush line 233.
and bs_regpush die's
With this patch we set an empty ARRAY reference if $r->{tags} is empty.
=> [backend] prevent bs_regpush from crashing if no tags in registry

src/api/spec/support/logging.rb
Instead of using .around we use .before - this way
we don't have the logging.rb in every spec backtrace
and the actual spec is the first entry in the trace
=> Remove logging.rb from all backtraces

Rakefile, dist/obs-api-testsuite-rspec.spec, docker-compose.minitest.yml, src/api/config/environments/test.rb, src/api/docker-files/Dockerfile.frontend-backend, src/api/lib/tasks/dev.rake, src/api/script/api_minitest.sh, src/api/test/test_helper.rb
To avoid having to patch options.yml forth and back, I moved
the CONFIG patching into the test environment for minitest, so
you can leave the options.yml shared between development and rspec
Fixes #5553
=> Add a way to run minitest in a container

src/api/app/assets/stylesheets/webui2/tabs-component.scss
@openSUSE/open-build-service, we have an open discussion about the colours of the tabs.
The options are the next:
Current:
Proposal:
Please vote :+1:  for the proposal and :-1:  for the current.
=> Switch color tabs

src/api/.rubocop_todo.yml, src/api/app/controllers/webui/package_controller.rb, src/api/app/models/obs_factory/distribution.rb, src/api/app/models/obs_factory/distribution_strategy_factory.rb, src/api/app/models/obs_factory/distribution_strategy_opensuse_leap15.rb, src/api/spec/models/obs_factory/distribution_strategy_factory_spec.rb
Using openURI's open method allows access to Kernel#open, which is
a bad idea when the parsed URIs can be provided by users.
This isn't the case for us right now, but since we plan to make the
staging dashboards configurable it makes sense to solve this now.
Otherwise this might become a problem in the future.
https://sakurity.com/blog/2015/02/28/openuri.html
https://twin.github.io/improving-open-uri/
=> Fix Security/Open Rubocop offense

src/api/app/controllers/webui/package_controller.rb, src/api/app/models/statistic.rb, src/api/config/initializers/activexml.rb, src/api/lib/backend/api/build_results/status.rb, src/api/spec/controllers/webui/package_controller_spec.rb
This is just used in one route and only used to fetch
one XML file. This is a good fit for the backend lib
=> Remove Statistic 'model'

dist/t/Gemfile, dist/t/Gemfile.lock, dist/t/spec/support/capybara.rb
Since we don't package phantomjs for OBS, and it is not used in the CI test suite, we also switch to selenium and headless chromium in smoke tests.
=> Switch to use selenium with chrome instead of phantomjs

src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/requesting_json/1_1_3_1.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/requesting_json/responds_with_a_json_representation_of_the_staging_project.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/with_dashboard_package/with_ignored_requests_file/with_content/1_1_2_1_1_1.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/with_dashboard_package/with_ignored_requests_file/with_content/1_1_2_1_1_2.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/with_dashboard_package/with_ignored_requests_file/with_content/sets_up_the_required_variables.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/with_dashboard_package/with_ignored_requests_file/without_content/1_1_2_1_2_1.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/with_dashboard_package/with_ignored_requests_file/without_content/1_1_2_1_2_2.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/with_dashboard_package/with_ignored_requests_file/without_content/sets_up_the_required_variables.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/without_dashboard_package/1_1_1_1.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/without_dashboard_package/sets_up_the_required_variables.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/requesting_html/1_2_1_1_1.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/requesting_html/1_2_1_1_2.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/requesting_html/1_2_1_1_3.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/requesting_json/1_2_1_2_1.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/requesting_json/responds_with_a_json_representation_of_the_staging_project.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_non-existent_factory_staging_project/1_2_2_1.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_non-existent_factory_staging_project/1_2_2_2.yml, src/api/spec/controllers/webui/obs_factory/staging_projects_controller_spec.rb
There is some overlap in what both tests set up.
Therefore it makes sense to define common code on the top level to
keep the test code DRY.
Add a test to ensure that declined requests are shown
=> Merge test preparation for show and index action

src/api/config/options.yml.example
As long as use cassettes we need to stick to 'backend'
in package builds - minitest hardcodes localhost and
is not affected by this
=> Use backend as default source_host to fix package build

docker-files/base/docker-bootstrap.sh
The Azure and AWS cllent packages can be temporarily not included in the `backend ` dockerfile in order to build the `backend` docker image that is only used in the development environment.
The backend docker image could be created and uploaded to docker hub as soon as this PR is merged. This image is the only one that is not updated in Docker Hub, now since 10 months.
=> Don't require cloud clients in the backend docker image

src/api/Gemfile, src/api/Gemfile.lock
To generate views in `.haml` format instead of `.erb` by default.
=> Add Haml-rails gem

src/api/app/models/event/base.rb
This reverts commit ab5196b6ad9a4f9b0d0572b14054e29de4fc9190.
As discussed in the review meeting.
=> Revert "Notify Errbit for extra payload keys in events"

src/api/Gemfile, src/api/Gemfile.lock
I would like to add the `pry-byebug` gem to improve the debugging experience. I don't know for you all, but when debugging, I set a breakpoint somewhere then move through the code to understand/debug what is going on. With `pry-byebug`, this is possible. This gem adds only one dependency for a lot of value in my opinion.
The gem's source/documentation is at https://github.com/deivid-rodriguez/pry-byebug
=> Add pry-byebug gem

dist/ci/travis_before_install.sh
On 2.9 branch this was pointing to Unstable. This caused not to find packages already deleted in Unstable, and TravisCI to fail.
=> Fix repository URL for running TravisCI

dist/obs-api-testsuite-rspec.spec, src/api/config/options.yml.example
This commit reverts commit 12adeaa6c, because ATM our default
installation is broken. Even it might work in the test suite,
changing source_host to backend breaks real life installations.
=> [dist] revert commit 12adeaa6c

src/api/config/routes.rb
Files with file extensions can cause our routing to reply for a
different format than our standard API format (XML).
For the get_file endpoints this was causing the forgery protection to
kick in when *.js files were requested.
Fixes #5614
=> Set default response for API get_file routes to XML

src/api/.rubocop.yml, src/api/config/application.rb, src/api/config/database.yml.example
All our existing tables use integers as primary key. Using the "new"
default in Rails (bigint) would cause breakage in MySQL.
=> Configure Rails generator to use integer as primary and foreign keys

src/api/config/routes.rb
Set default format for API comments routes to XML. This ensures that
viewing these pages in the browser does not cause an error due to
not existing html views.
Fixes #3180
=> Set default format for comments

src/api/app/controllers/webui/request_controller.rb, src/api/spec/controllers/webui/request_controller_spec.rb, src/api/spec/features/webui/packages_spec.rb
Delete requests are used for deletion of different objects. Hence we
have to make the flash message generic.
Fixes #4897
=> Fix flash message for create delete requests

src/api/.rubocop_todo.yml, src/api/app/models/project.rb, src/api/spec/controllers/webui/download_on_demand_controller_spec.rb, src/api/spec/models/bs_request_action_spec.rb, src/api/spec/models/project_spec.rb, src/api/spec/models/repository_spec.rb, src/api/spec/models/review_spec.rb
Project names are validated in the frontend and backend. Because of that the frontend validation has to cover at least the backend validations.
This wasn't the case for project names that started with '.', ':' or '_' and and project names that
contain a ':' followed by one of the three characters.
=> Update project name validation

src/api/spec/models/project_spec.rb
In 155eb7c181664668363a20cf9f I changed the regex for the first character
of the generated project name and added some chars that would create an
invalid project name.
This commit fixes it.
Kudos to @eduardoj for catching this.
=> Fix property test for project name validations

docker-files/base/docker-bootstrap.sh
Include the `aws-cli` package for building the backend docker image as installing it on a Leap 42.3 was fixed.
=> Include aws-cli again for building backend docker image

src/api/app/assets/stylesheets/webui/obs_factory/application.css, src/api/app/controllers/webui/obs_factory/staging_projects_controller.rb, src/api/app/helpers/webui/obs_factory/application_helper.rb, src/api/app/models/obs_factory/staging_project.rb, src/api/app/models/repository.rb, src/api/app/views/webui/obs_factory/staging_projects/_checks.html.haml, src/api/app/views/webui/obs_factory/staging_projects/show.html.erb, src/api/lib/backend/api/published.rb, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/requesting_html/1_2_1_1_1.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/requesting_html/1_2_1_1_2.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/requesting_html/1_2_1_1_3.yml
Recently we introduced a checks API to add checks to a published repository. With this commit
we now show these checks on the Staging Dashboard.
=> Implement checks in StagingDashboard show view

src/api/app/models/obs_factory/distribution_strategy_factory.rb, src/api/app/models/obs_factory/distribution_strategy_opensuse_leap15.rb
Calling URI($url) lead to a 404 error. For unknown reason this only
would happen in production mode. Hence we did not notice this in
development and test.
Fixes #5599
=> Fix 404 error on project dashboard

src/api/app/controllers/webui/patchinfo_controller.rb
This prevents an exception when binaries or binarylist is empty.
Fixes #5316
=> Ensure that binaries and binarylist are an Array

.circleci/config.yml
Due to security concerns Circle CI disabled[*] saving of caches
for PRs from forked repositories.
In our setup the first CI job ("checking code") creates a cache and
every following test job uses the cached sources.
Without having the cached git checkout all these test jobs started to
fail.
For now we check out the git repo for each test job to get a working
test suite again.
=====
cd ./src/api && bundle install --jobs=4 --retry=3
/bin/bash: line 0: cd: ./src/api: No such file or directory
Exited with code 1
=====
[*] https://discuss.circleci.com/t/saving-cache-stopped-working-warning-skipping-this-step-disabled-in-configuration/24423/3
=> Fix test suite after recent Circle CI change

src/api/app/views/webui2/webui/package/_tabs.html.haml
All other project and package variables are expected to be
local variables, except one occasion of @project.
=> Align variable usage in tabs view

src/api/app/controllers/source/errors.rb, src/api/app/controllers/source_controller.rb
Following the changes in the models ```project.rb``` and
```package.rb```, to reduce the visual pollution, move
the exceptions classes to its own module for source controller
=> Move error classes definition to its own module

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/package/edit.html.erb, src/api/app/views/webui/package/show.html.erb, src/api/app/views/webui/patchinfo/show.html.haml
This feature isn't is currently hidden via a action parameter and
thus is hidden from users.
Moreover it isn't working anymore (if it ever was).
Let's drop it for now. We would have to re-implement this anyway, if
we decide later on to revive this.
=> Drop package controller action: import_spec

src/api/.haml-lint.yml, src/api/app/controllers/webui/webui_controller.rb, src/api/app/views/layouts/webui2/_breadcrumbs.html.haml, src/api/app/views/webui2/webui/main/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml
=> Add Bootstrap breadcrumbs for main, projects and packages

src/api/app/views/webui/user/_save_dialog.html.haml, src/api/app/views/webui/user/show.html.haml, src/api/spec/features/webui/users/user_home_page_spec.rb
Users could not join the beta when a proxy is in place. The page to edit
their account (and join the beta) was not reachable.
Fixes #5667
=> Allow users to join the beta, even with a proxy

src/api/app/views/webui2/webui/package/revisions.html.haml
When checking an array with `if my_array`, it will always be true (no matter if the array is empty or not)
I found this while working on the Bootstrap version of package#attributes.
=> Check if package revisions are present

src/api/app/views/webui/user/show.html.haml
There is already another %br below.
Before changes:
After changes:
=> Be constant in spacing between user#show links

src/api/app/models/bs_request_action_maintenance_release.rb, src/api/app/models/bs_request_action_maintenance_release/errors.rb
move the exceptions classes to its own errors module to better organize code and reduce clutter
=> Bs request action maintenance release errors

src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml
When the current page is not package/revisions, the li tag must not be displayed.
I found this while working on the Bootstrap version of package#attributes.
=> Display li tag only when needed

src/api/app/assets/stylesheets/webui2/breadcrumbs-component.scss
The font size and the padding top is now the same for both components, making them fit better together. It also gives us more room in the breadcrumbs, thanks to the smaller font.
=> Align breadcrumbs' style with personal navigation

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/jobs/bs_request_action_webui_infos_job.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/bs_request_action/differ/for_source.rb, src/api/app/models/bs_request_action/errors.rb, src/api/app/models/bs_request_action_maintenance_release.rb, src/api/app/models/event/request.rb, src/api/spec/controllers/webui/project_controller_spec.rb, src/api/spec/models/bs_request_action/differ/for_source_spec.rb, src/api/spec/models/bs_request_action_delete_spec.rb
To reduce code clutter, following the pattern already used in
other models like ```project.rb``` or ```package.rb```
move the exception classes to its own errors.rb file
=> Move exceptions classes from bs_request_action to its own module

src/api/app/views/webui/obs_factory/staging_projects/_problems.html.erb
- Remove unneeded `if` branch.
- Replace `max` by `num_elements` and subsctract 1 when it is used in a
range in favour of readability.
=> Refactor list of problems in openQA dashboard

src/api/app/views/webui2/shared/bs_requests/index.json.erb
We switched the info icon to something more representative.
=> Add new icon for show request

src/api/app/controllers/webui/package_controller.rb
It is necessary to check if 'linkinfo' exists, not only if its
key-value pairs exit.
Fixes #5718
=> Prevent failure due to missing link to remote info

src/api/app/models/maintained_project.rb
Without validation, it raised an exception whenever trying to create a
non-unique MaintainedProject
Fixes #5639
=> Add validation to MaintainedProject

src/api/app/models/bs_request.rb
Without validation, it raised an exception whenever trying to create a `BsRequest` with a non-unique number
Fixes #5731
=> Add validation to BsRequest for number

SECURITY.md
To better describe our security issues handling, use a standard
way to define it via SECURITY.md
=> Add initial SECURITY.md file

src/api/app/models/kiwi/repository.rb
Without validation, it raised an exception whenever trying to create a non-unique `image_id` + `order` combination for `Kiwi::Repository`
Fixes #5638
=> Add validation to Kiwi::Repository for image_id and order

src/api/app/models/package.rb
Without validation, it raised an exception whenever trying to create a non-unique `name` + `project_id` combination for `Package`
Fixes #5732
=> Add validation to Package for name and project_id

src/api/spec/factories/groups.rb
because it is expected when creating a Group with a User
that the user is fully functional and it is not necessary
to set the state to confirmed first.
This can cause quite some debugging and frustration.
=> Use confirmed_user in Groups factory

src/api/app/controllers/webui/projects/bs_requests_controller.rb
Within respond_to blocks prepending the webui2 path doesn't work.
Therefore we have to explicitly name the partial.
=> Fix rendering of webui2 view in project request tab

src/api/app/controllers/webui/webui_controller.rb
Without this, the links on the _nobody_ user's page are displayed. It doesn't make sense since nobody should be able to edit the _nobody_ user.
Before:
After:
=> Never consider the _nobody_ user as the displayed user

src/api/app/controllers/webui/attribute_controller.rb, src/api/spec/controllers/webui/attribute_controller_spec.rb
When an attribute got deleted from a project or package, or did not
exist in first place, the @attribute variable would unexpectedly be nil.
With this commit we raise an ActiveRecord::RecordNotFound in such a
case.
The exception will be catched by an exception handler which renders
a generic 404 page, in production mode.
=> Fix 500 error on attribute edit page

src/api/app/models/bs_request.rb, src/api/spec/models/bs_request_spec.rb
In 429c1b2 we include some additional data to the json representation of
bs requests. This was needed by the staging controller / openSUSE release tools.
Though when the superseded_by attribute is not defined, eg. by fetching
a subset of attributes from the database, this would cause a 'missing
attribute' error.
Checking whether superseded_by is defined before calling it fixes the
issue.
Fixes #5761
=> Fix missing attribute error in statistics controller

src/api/app/assets/stylesheets/webui/obs_factory/application.css, src/api/app/controllers/status/checks_controller.rb, src/api/app/controllers/status/required_checks_controller.rb, src/api/app/controllers/webui/obs_factory/staging_projects_controller.rb, src/api/app/helpers/status/required_checks_helper.rb, src/api/app/models/project.rb, src/api/app/models/repository.rb, src/api/app/models/status/check.rb, src/api/app/models/status/repository_publish.rb, src/api/app/policies/repository_policy.rb, src/api/app/views/status/checks/_check.xml.builder, src/api/app/views/status/checks/index.xml.builder, src/api/app/views/status/required_checks/index.xml.builder, src/api/app/views/webui/obs_factory/staging_projects/_checks.html.haml, src/api/config/routes.rb, src/api/db/migrate/20180903135535_add_required_checks_to_repository.rb, src/api/db/structure.sql, src/api/spec/controllers/status/checks_controller_spec.rb, src/api/spec/controllers/status/required_checks_controller_spec.rb, src/api/spec/factories/checks.rb, src/api/spec/fixtures/files/required_check.xml, src/api/spec/fixtures/files/required_check_with_additional_params.xml, src/api/spec/fixtures/files/required_checks.xml
A required check can be defined on a checkable
(e.g. project, package, repository). When a check
does not exist, the required check will be displayed instead.
As soon as a check exists with the same name as the required
check, this check will be displayed instead.
In the WebUI this is implemented on the staging project dashboard.
We implemented the required check as an independent model, however, maybe it would make sense to combine it with the Check model. There are some pending refactoring by @hennevogel we maybe should also wait to land first.
=> Implement Status::RequiredChecks 

src/api/spec/bootstrap/features/webui/packages_spec.rb
Because we have more than one modal at the same time in pacakge#show, we need to specify in which modal we are.
=> Fix flickering test in Bootstrap#Package

src/api/app/views/webui2/shared/bs_requests/index.json.erb
Calling the 'icon' helper of font-awesome-sass gem recently started to
fail. Since the partial that contains the method call is cached, it's
not fully clear when this started to happen and what was causing this.
Fixes #5756 again
=> Fix rendering of fontawesome icon on request tab in webui2 mode

src/api/app/views/webui2/webui/attribute/_form.html.haml, src/api/app/views/webui2/webui/attribute/_issue_fields.html.haml, src/api/app/views/webui2/webui/attribute/_value_fields.html.haml
Follow-up to #5713. I just forgot to do it in #5808. 
Values:
Issues:
=> Be consistent with icons in package#attributes form

src/api/app/views/webui2/webui/package/_submit_request_dialog.html.haml, src/api/app/views/webui2/webui/request/_delete_request_dialog.html.haml, src/api/spec/bootstrap/features/webui/packages_spec.rb
Avoiding unnecessary requets also from bootstrap views, we add a text
explaining request's aim and make description field compulsory.
=> Clarify request's aim and require description for webui2

src/api/app/controllers/status_project_controller.rb, src/api/app/models/relationship.rb
This scope is already covered by Rails's where method.
Follow up of f5fee17c3fc04b194e919650efd059d0b2e2b5c1
=> Drop with_packages scope from Relationship model

src/api/app/assets/javascripts/webui/application/package.js, src/api/app/views/webui/package/view_file.html.erb
Since obs-build 20180816 and osc 0.163.0, changes entries are generated
using full author identities. This change makes it so the build service
web UI has the same behavior for new changes entries.
=> webui: Use full author identities in generating changes entries

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui2/shared/_buildresult_box.html.haml
Buildresult box is used in request#show and package#show, because
request#show is not available in bootstrap the buildresult box looks
broken if the user is a beta user.
Fixes: #5834 
=> Add extra parameter in build result to switch to webui2

src/api/app/controllers/request_controller.rb
We had an issue that was adding the `<?xml version="1.0"??>` after the
first node (`<request...>`), now is fixed and is the first node of the XML
It fixes issue #5843
=> Fix issue while adding XML for requests diff

src/api/app/controllers/webui/monitor_controller.rb
The key HTTP_CACHE_CONTROL doesn't live on request.headers but request.env, as you can see here https://api.rubyonrails.org/v5.2.0/classes/ActionDispatch/Request.html
=> Remove the method discard_cache? as it never worked as intended.

src/api/app/views/webui2/webui/package/_show_derived_packages.html.haml, src/api/app/views/webui2/webui/package/_show_devel_package.html.haml, src/api/app/views/webui2/webui/package/_show_developed_packages.html.haml, src/api/app/views/webui2/webui/package/_show_failures.html.haml, src/api/app/views/webui2/webui/package/_show_inherited_from_project.html.haml, src/api/app/views/webui2/webui/package/_show_linkinfo.html.haml, src/api/app/views/webui2/webui/package/_show_patchinfo.html.haml, src/api/app/views/webui2/webui/package/_side_links.html.haml
Refactor the partial _side_links for packages, breaking it in smaller partials
=> Refactor package partial links (_side_links)

src/api/app/assets/stylesheets/webui2/modals.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui2/comments_controller.rb, src/api/app/views/webui2/webui/attribute/_delete_dialog.html.haml, src/api/app/views/webui2/webui/attribute/index.html.haml, src/api/app/views/webui2/webui/comment/_delete_dialog.html.haml, src/api/app/views/webui2/webui/comment/_links.html.haml, src/api/app/views/webui2/webui/comment/create.js.haml, src/api/app/views/webui2/webui/comment/destroy.js.haml, src/api/app/views/webui2/webui/main/_add_status_message_modal.html.haml, src/api/app/views/webui2/webui/package/_branch_dialog.html.haml, src/api/app/views/webui2/webui/package/_delete_dialog.html.haml, src/api/app/views/webui2/webui/package/_delete_file_dialog.html.haml, src/api/app/views/webui2/webui/package/_files_view.html.haml, src/api/app/views/webui2/webui/package/_linking_packages.html.haml, src/api/app/views/webui2/webui/package/_submit_request_dialog.html.haml, src/api/app/views/webui2/webui/request/_add_role_request_dialog.html.haml, src/api/app/views/webui2/webui/request/_change_devel_request_dialog.html.haml, src/api/app/views/webui2/webui/request/_delete_request_dialog.html.haml, src/api/spec/bootstrap/features/webui/maintenance_workflow_spec.rb, src/api/spec/bootstrap/features/webui/packages_spec.rb
Before we have been using the data-confirm behaviour of the browsers, now to be consistent with the rest of the boostrap style we replace this to use a modal dialog.
It will show something like this:
instead of:
BTW, we vertically aligned all of them
=> Bootstrap: modal dialogs instead of confirm boxes to be consistent

src/api/app/views/webui2/webui/package/_bottom_actions.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_branch_package.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_bugzilla_owner.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_cloud_upload.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_delete_package.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_edit_description.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_request_deletion.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_request_devel_project_change.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_request_role_addition.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_submit_package.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_trigger_services.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_view_kiwi.html.haml
- bottom_actions/bugzilla_owner
- bottom_actions/branch_package
- bottom_actions/submit_package
- bottom_actions/edit_description
- bottom_actions/delete_package
- bottom_actions/cloud_upload
- bottom_actions/trigger_services
- bottom_actions/view_kiwi
- bottom_actions/request_deletion
- bottom_action/request_devel_project_change
- bottom_action/request_role_adiction
=> Refactor bottom_actions Package view:  Break it in small partials

src/api/app/controllers/webui/comments_controller.rb, src/api/app/views/webui/comment/_links.html.haml, src/api/app/views/webui/comment/_new.html.haml, src/api/app/views/webui/comment/_reply.html.haml
If you are a beta user, the comments section are rendering the views
from `webui2` in sections that are not migrated like `project#show`.
The `no_switch` parameter was added in `webui` comment views because they  will be
deleted as soon as we migrate everything to Bootstrap,
Fixes #5874
=> Fix comments in old webui

dist/t/osc/fixtures/obs-testpackage-2.8._service, dist/t/osc/fixtures/obs-testpackage._service
Changed to be consistent with
https://github.com/M0ses/obs-testpackage/commit/f43d00d49ffefe2cd3296070e371120041e9d6b2
=> [dist] fix compression in osc test cases

src/api/app/assets/stylesheets/webui2/texts.scss, src/api/app/views/layouts/webui2/_watchlist.html.haml, src/api/app/views/layouts/webui2/_watchlist_dropdown.html.haml
if the name of the project was very long, the container of the watchlist
was also growing.
=> Make watchlist smaller

src/api/app/controllers/webui/request_controller.rb, src/api/app/controllers/webui2/request_controller.rb, src/api/app/views/webui2/webui/package/bottom_actions/_request_devel_project_change.html.haml, src/api/app/views/webui2/webui/package/show.html.haml, src/api/app/views/webui2/webui/request/_change_devel_request_dialog.html.haml, src/api/spec/bootstrap/features/webui/packages_spec.rb, src/api/spec/features/webui/packages_spec.rb
We want to remove this pattern of using render_dialog. Is too generic,
now we answer the ajax call with a JS that creates the modal.
We are not integrating the modal directly in the Package#show because it
will need to load the develpackage and project related to that everytime
we show a package and won't be needed that frecuently.
=> Refactor render_dialog call in request controller for webui2

src/api/app/assets/stylesheets/webui2/comments.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss
The content with `pre` tag was overflowing the comment box.
kudos to @mdeniz
=> Add style for `pre` tag in comments

src/api/spec/controllers/status/required_checks_controller_spec.rb
The tested http requests was only added to the first it-block of
some of the shared examples.
Because of that the following it-blocks were testing the login requests
(test preparation) instead of the actual controller action.
This commit fixes it by moving the tested http request into a subject
and re-using it in every it-block.
=> Fix tests for required checks controller

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/shared/_package_branch_form.html.haml, src/api/app/views/webui2/shared/_package_branch_form.html.haml, src/api/spec/cassettes/Bootstrap_MaintenanceWorkflow/maintenance_workflow.yml, src/api/spec/cassettes/Bootstrap_Packages/branching_a_package_from_another_users_project/with_AutoCleanup.yml, src/api/spec/cassettes/Bootstrap_Packages/branching_a_package_from_another_users_project/without_AutoCleanup.yml, src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_current_revision_parameter_is_provided_but_there_wasn_t_any_revision_before.yml, src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_source_package_does_not_exist.yml, src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_source_package_parameter_not_provided.yml, src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_source_project_does_not_exist.yml, src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_source_project_parameter_not_provided.yml, src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_user_has_no_permissions_for_source_project.yml, src/api/spec/cassettes/Webui_PackageController/POST_branch/with_currrent_revision_parameter/1_4_8_1.yml, src/api/spec/cassettes/Webui_PackageController/POST_branch/with_currrent_revision_parameter/1_4_8_3.yml, src/api/spec/cassettes/Webui_PackageController/POST_branch/with_target_package_name/1_4_7_1.yml, src/api/spec/cassettes/Webui_PackageController/POST_branch/with_target_package_name/redirects_to_the_branched_package.yml, src/api/spec/controllers/webui/package_controller_spec.rb
When we branch a package with a specific revision, it was always
branching the last revision. Now it's having into account the revision shown in the Package#show page.
Fixes #5365
=> Add revision in branch package

src/api/app/views/layouts/webui2/webui.html.haml, src/api/app/views/webui2/webui/main/_breadcrumb_items.html.haml
So it will use the full width of available space, will also kick out personal navigation to row if there is not enough space for it at the top.
Would also be beneficial to consider changing scheme in there to display ":house: Home" instead of ":house: Name of the instance of Open Build Service" because it can get veeeery long and take up way too much space, and conveys message of it coming back to homepage more than name of the instance.
=> Fix scaling of breadcrumbs on low width screens

src/api/app/controllers/webui/project_controller.rb
We are about to announce the bootstrap version of the package show
and package tabs views. Since the other project views are not done
yet, we hide bootstrap version of the project request tab for now.
=> Hide webui 2 version of project request tab

src/api/app/models/user.rb
In proxy mode make sure that the user realname is a proper utf8 string.
Fixes #5872.
=> Force utf8 encoding when updating user realname

src/api/lib/tasks/dev.rake
because otherwise we need to always set it e.g. in a review app if we want to review
the download / binary pages.
=> Set a download_url in the testdata rake job

src/backend/BSConfig.pm.template, src/backend/bs_admin, src/backend/call-service-in-docker.sh
The Problem:
ATM we have the problem, that we use docker_custom_opt's which is then added to every service call, 
even if only needed with the 'bundle_gems'. If the geminabox container doesn`t work correctly
it affects all service. 
This tries to reduce dependencies for the other service to the geminabox container by introducing a new option/variable
```$geminabox_container``` in BSConfig.pm
which is only used in bundle_gems case.
=> Use '--link' option in call-service-in-container.sh only for bundle_gems service

src/api/.jshintignore, src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/cm2/index-diff.js, src/api/app/assets/javascripts/webui2/cm2/index-prjconf.js, src/api/app/assets/javascripts/webui2/cm2/index-xml.js, src/api/app/assets/javascripts/webui2/cm2/index.js, src/api/app/assets/javascripts/webui2/cm2/mode/baselibsconf.js, src/api/app/assets/javascripts/webui2/cm2/mode/dockerfile.js, src/api/app/assets/javascripts/webui2/cm2/mode/prjconf.js, src/api/app/assets/javascripts/webui2/cm2/mode/simple.js, src/api/app/assets/javascripts/webui2/cm2/toolbars.js, src/api/app/assets/javascripts/webui2/cm2/use-codemirror.js, src/api/app/assets/stylesheets/webui2/cm2.scss, src/api/app/assets/stylesheets/webui2/cm2/suse.scss, src/api/app/assets/stylesheets/webui2/cm2/toolbars.css, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/views/layouts/webui2/webui.html.haml, src/api/app/views/webui2/shared/_editor.html.haml, src/api/config/initializers/assets.rb, src/api/spec/bootstrap/features/webui/packages_spec.rb, src/api/spec/code_mirror_helper.rb, src/api/spec/support/code_mirror.rb
- Changes slightly the CSS of the editor's toolbar.
- Refactors the editor code.
- Creates a test helper, `fill_in_editor_field`, to easily write text
inside CodeMirror editor from feature tests.
=> Move CodeMirror to webui2

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui2/webui/package/meta.html.haml, src/api/config/routes.rb, src/api/spec/bootstrap/features/webui/packages_spec.rb
- Uses CodeMirror.
- Includes tests to check CodeMirror editor functionality.
- Fixs redirection after XML validation to webui2 flash view.
=> Migrate Package#meta to bootstrap

src/api/app/assets/stylesheets/webui2/modals.scss
The text was rendered outside the modal. Fixes https://github.com/openSUSE/open-build-service/issues/5921. :bowtie:
=> Prevent text in modals to overlap

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/job_history.js, src/api/app/controllers/webui/packages/job_history_controller.rb, src/api/app/views/webui2/webui/package/_tabs.html.haml, src/api/app/views/webui2/webui/packages/job_history/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/packages/job_history/index.html.haml
We had to explicitly define the package variable in the breadcrumbs to avoid a breakage when rendering the job history page. This is because the job history page does not define all variables we require for the tabs partial.
=> Implement package binary job history in bootstrap

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/live_build_log.js, src/api/app/assets/stylesheets/webui2/live_build_log.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/package/_job_status.html.haml, src/api/app/views/webui2/webui/package/_live_build_log_controls.html.haml, src/api/app/views/webui2/webui/package/live_build_log.html.haml, src/api/app/views/webui2/webui/package/update_build_log.js.haml, src/api/config/routes.rb
We migrate package#live_build_log to bootstrap.
The original screenshot is [here](http://paste.opensuse.org/15277277)
=> Migrate live build log to Bootstrap

src/api/app/controllers/webui/packages/build_reason_controller.rb, src/api/app/models/package_build_reason.rb, src/api/app/views/webui2/webui/package/_tabs.html.haml, src/api/app/views/webui2/webui/packages/build_reason/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/packages/build_reason/index.html.haml, src/api/spec/models/package_spec.rb
Getting the table locally can be tricky because you need a package with a dependency on another package, trigger the dependency and then you would get a table. However, you can just mock this by adding this:
```
def packagechange
[
{ 'key' => 'package1', 'change' => 'changed' },
{ 'key' => 'package2', 'change' => 'changed' },
{ 'key' => 'package3', 'change' => 'changed' },
{ 'key' => 'package1', 'change' => 'changed' }
]
end
```
to ``src/api/app/models/package_build_reason.rb``.
=> Migrate Package#build_reason to bootstrap

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui2/package_controller.rb, src/api/app/models/local_build_statistic/for_package.rb, src/api/app/models/local_build_statistic/package/disk.rb, src/api/app/models/local_build_statistic/package/memory.rb, src/api/app/models/local_build_statistic/package/time.rb, src/api/app/models/local_statistic.rb, src/api/app/models/package.rb, src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/package/statistics.html.haml, src/api/spec/models/local_build_statistic/for_package_spec.rb, src/api/spec/models/package_spec.rb
We adapt package statistics view to Bootstrap
=> Adapt package#statistics to Bootstrap

src/api/app/views/webui/obs_factory/staging_projects/_checks.html.haml
@checks and @missing_checks can be nil so we need to check blank instead of empty.
=> Fix Nil exception in staging dashboard

src/api/app/assets/stylesheets/webui2/webui2.css.scss
There was a strange effect between long and short pages, as the second ones were hiding the scrollbar. Showing always the scrollbar fixes that issue. :bowtie: 
This worked in last version of Firefox because there (at least by default) the scrollbar is always present and it is just disabled when not needed.
Fixes https://github.com/openSUSE/open-build-service/issues/5939
=> Fix flickering views in webui2

src/api/app/views/layouts/webui2/_watchlist_dropdown.html.haml
Small aesthetics fix, aligns dropdown to the right side of the dropdown button
=> Align dropdown menu to the right

src/api/spec/features/webui/packages_spec.rb
This ensures that the new page was loaded before doing further tests.
=> Fix flickering package feature test

src/api/app/views/webui2/webui/package/_submit_request_dialog.html.haml, src/api/app/views/webui2/webui/request/_requests_small.html.haml
Apparently, the number of supersede didn't work properly, and also apparently checkbox inside p inside modal-content causes weird newlines to appear:
=> [webui] Fix checkboxes for supersedeing requests in package view

src/api/app/views/webui2/webui/package/_files_view.html.haml
Before we had the issue that happened when responsiveness of datatables
was happening either by long names of files or whenever the user resizes the page down
until it hides some of the columns.
It fixes #5914.
=> Fix issue about not showing dialogs on bootstrap datatables

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/forms.js, src/api/app/views/webui2/webui/package/add_file.html.haml
for add file view.
Because this is what we decided in the pattern library so we need to change it
to follow.
Please note that this requires also that we have now JS for updating the label / what is in the input field.
vs.
Also note that e.g. chrome does not allow JS to get the whole path to the file and replaces the path e.g. with ``C:\fakepath\...`` for security reasons. From my POV this is fine but I'm also fine if we e.g. drop the path and just show the filename?
=> Use custom file input bootstrap class

src/api/app/views/webui2/webui/package/_files_view.html.haml
The files view of the overview page for a package was having problems of
responsiveness when file names were too long.
It fixes #5949.
Here is how it will look like:
=> Fix responsiveness of datatables when long file names

src/api/app/assets/javascripts/webui2/packages.js, src/api/app/assets/stylesheets/webui2/cm2.scss, src/api/app/controllers/webui/package_controller.rb, src/api/app/helpers/webui/package_helper.rb, src/api/app/views/webui2/shared/_truncated_diff_hint.html.haml, src/api/app/views/webui2/webui/package/_revision_diff_detail.html.haml, src/api/app/views/webui2/webui/package/_revision_diff_footer.html.haml, src/api/app/views/webui2/webui/package/rdiff.html.haml, src/api/spec/helpers/webui/package_helper_spec.rb
To continue our efforts to migrate the whole frontend to bootstrap.
https://github.com/openSUSE/open-build-service/wiki/How-to-work-in-Bootstrap-%28new-UI%29
=> Migrate Package revision diff to bootstrap

src/api/app/assets/javascripts/webui2/attributes.js, src/api/app/views/webui2/webui/attribute/index.html.haml
Before the table was using basic responsive style adding
horizontal scrolls and now is using datatables to hide the
columns.
This fixes #5984
=> Fix the attributes table in mobile size

dist/systemd/obs-clockwork.service
Add missing "bundle exec" command. Without it the clockwork binary cannot find the other executables it depends on.
=> Fix clockwork systemd service

src/api/app/views/webui2/webui/package/_revision_diff_detail.html.haml
On small devices we hide now the the 'jump' buttons (for jumping from diff to diff)
because it does not provide much value on a small device.
Additionally we show an icon for view file on small devices to save space.
Large screen:
Small screen:
(Note that the first view file link is hidden because it is a binary file, I just mocked the filename to make it really long :blush: )
=> Fix revision diff for small devices

src/api/app/controllers/request_controller.rb, src/api/app/models/bs_request.rb
New requests should not include the `id` attribute. If a `<state>` element is provided it will be ignored.
=> Prevent creation of a request with an ID attribute

src/api/app/assets/stylesheets/webui2/links.scss
In modal dialogs, the color of the text inside the cancel button should be the
same as its boder's color or white when hover.
Fixes: #5992
**Before (with hover):**
**After (without hover):**
**After (with hover):**
=> Fix colors for links that emulate outline buttons

src/api/app/views/webui2/webui/attribute/new.html.haml
On top of this, the select is now a custom select from Bootstrap custom
forms.
Fixes #5982
Desktop is still fine:
Mobile is fixed:
=> Display the select without overflowing its container on mobile

src/api/app/assets/stylesheets/webui2/cm2.scss, src/api/app/assets/stylesheets/webui2/diff.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/views/webui2/webui/package/_revision_diff_detail.html.haml, src/api/app/views/webui2/webui/package/_revision_diff_detail_buttons.html.haml, src/api/app/views/webui2/webui/package/rdiff.html.haml
* We always show now the buttons and just disable. This improves usability because the mouse is not suddenly over a different button when using the 'jumping' buttons. Thanks to @hennevogel for suggestion.
* Filename is now limited to not use the whole size of the summary and therefore sometimes overlapping with the view file button
* Expand link is now hidden when there is no diff (e.g. binary files)
* Additionally moved buttons to a partial
Fixes #6011
=> Fix several issues on revision diff page

src/api/app/views/webui2/webui/attribute/index.html.haml, src/api/app/views/webui2/webui/package/_deps.html.haml, src/api/app/views/webui2/webui/packages/build_reason/index.html.haml
See for more context https://github.com/openSUSE/obs-patterns/pull/25
Additionally using bootstraps sizing classes now because the grid system does not work reliable for chrome in tables.
=>  Unify table styling according to OBS pattern library

src/api/app/views/webui2/webui/package/binary.html.haml
It should have been in #6003 with the other changes to follow design decisions
=> Use proper download icon

src/api/app/views/webui2/webui/package/_edit_dialog.html.haml
Because this is similar behavior to what we do on the package show page.
Fix https://github.com/openSUSE/open-build-service/issues/5975
The problem here is that people don't expect that a package has a name and a title (similar to what is in a spec file). On the package show we show the title and if there is no title we show the name because name is presence validated. I think this behaviour makes sense and we should think about to maybe overwrite the title accessor with something like:
```ruby
def title
self[:title].presence || name
end
```
But I don't know the side effects yet and if we want to have it always like this so for now I only change the edit view.
=> Show name when there is no title on package edit

dist/setup-appliance.sh
Without this fix, the registry does not get configured to bind
localhost only. The error message you can see in journalctl:
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
because $0 includes slashes which break the perl regex.
This fix should avoid slashes by only taking the basename.
=> [dist] interims fix for setup-appliance

src/api/app/assets/stylesheets/webui2/package-show.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/views/webui2/shared/_buildresult_box.html.haml, src/api/app/views/webui2/webui/package/show.html.haml
... on package show page, using CSS Grid Layouts.
Fixes partially #5976, only the order, not limiting the size.
=> Change order of fields for small devices

src/api/app/controllers/webui/session_controller.rb, src/api/app/controllers/webui/webui_controller.rb
Record them in proxy mode, do not record too many tags as they are rather
expensive and avoid recording user info.
=> Fix metrics for webui logins

src/api/config/routes.rb
We missed the constrain for those routes and that was leading to routing
errors.
It fixes #6051.
=> Fix routes for published checks and reports of status reports

src/api/spec/bootstrap/features/webui/packages_spec.rb
Disable flickering tests until we fix them. There are failing in all PRs. :tada: 
There is an issue open: https://github.com/openSUSE/open-build-service/issues/6034
=> Disable flickering tests

src/api/app/models/project.rb
The method returned false even when the state was fine.
Fixes #5791
=> Fix build_succeeded? method

src/api/.rubocop.yml, src/api/app/assets/stylesheets/webui2/texts.scss, src/api/app/controllers/webui/repositories_controller.rb, src/api/app/views/webui2/shared/_repositories.html.haml, src/api/app/views/webui2/shared/_repositories_flag_table.html.haml, src/api/app/views/webui2/shared/_repositories_flag_table_column.html.haml, src/api/app/views/webui2/webui/package/binaries.html.haml, src/api/app/views/webui2/webui/repositories/change_flag.js.haml, src/api/app/views/webui2/webui/repositories/index.html.haml
We have added a little gray dot in case the flag value is set by user and nothing if it is calculated. That way the user can see an overview of which flags are inherited/calculated and which are not.
This is a flag set by the user:
This is a flag calculated:
We had the issue of letting any user try to change a flag. Now we use the policy to know if the user can change the repository flags then the popover of the actions appear.
=> Indicate inheritance of repositories

src/api/app/assets/javascripts/webui2/packages.js, src/api/app/views/layouts/webui2/_flash.html.haml
The Javascript for the more info was missing and  `.hidden` was been dropped in Bootrstrap 4: https://getbootstrap.com/docs/4.0/migration. Also, style link in alert using Bootstrap class.  :bowtie: 
Fixes https://github.com/openSUSE/open-build-service/issues/6072
=> Fix more info in package error flash

src/api/app/views/layouts/webui2/_flash.html.haml
Some of the flash icons where confusing, for example the 'x' icon. So
they have been replaced by other icons used in our bootstrap design.
Fixes #6080
Before:
After:
=> Change icons for flash messages in bootstrap

docs/api/api/api.txt, docs/api/api/request.rng, src/api/app/controllers/request_controller.rb, src/api/app/jobs/accept_requests.rb, src/api/app/models/bs_request.rb, src/api/app/models/bs_request_permission_check.rb, src/api/db/migrate/20180924135535_request_approved.rb, src/api/db/structure.sql, src/api/test/functional/request_controller_test.rb
add option to pre-approve a request in review state. It will be accepted
when last review gets accepted.
former way could not work since requests in review state already get
accepted by time.
Also fixed inconsistent behaviour of autoaccept depending on which of the duplicate
autoaccept handling was used.
belongs to Fate 316775
=> [api] support request pre-approval

src/api/app/models/bs_request.rb
There is no `:references` table. Also as the `.where` contains always a hash and not a SQL-fragment the `.references` is not needed.
=> Remove wrong .references(:references) from scope

src/api/app/models/bs_request.rb, src/api/app/models/project.rb, src/api/app/models/staging_workflow.rb, src/api/db/migrate/20181016103905_add_staged_request_id_to_bs_requests.rb, src/api/db/structure.sql, src/api/spec/factories/project.rb, src/api/spec/factories/staging_workflow.rb, src/api/spec/models/staging_workflow_spec.rb
We have created the association between StagingWorkflow, StagingProject
and BsRequest.
Unassigned requests are all the requests related to the StagingWorkflow's main
project that are not associated to any of the staging projects.
Supersedes #6097
=> Unassigned requests for StagingWorkflow

src/api/config/environments/production.rb
We already calculate and store the backend runtime.
However, so we only show it in debug mode and store it to a dedicated file: backend_access.log.
This commit includes the total backend response time in the lograge output as
well to get a quick overview.
Example output:
```
method=GET path=/about format=html controller=AboutController action=index status=200 duration=36.84 view=16.92 db=0.00 params={} host=172.18.0.1 time=2018-10-19 12:21:07 +0000 backend=11.93 user=
```
=> Add backend response time to lograge output

src/api/app/models/staging_workflow.rb
This method retrieves the staging projects of a workflow project that don't have any requests assigned.
=> Add method for retrieving free staging projects

dist/obs-server.spec
We recently changed to use systemd instead of SysV for starting delayed
jobs services. Part of this was adding a script that ensures that the new systemd
service would be added when updating packages (710cd0fe48bb4a63212dee17a3fcb8b2bcdf6cbe).
This was working fine for the initial switch from SysV to systemd, but
once the SysV service is removed any following package update would
cause some additional stdout output due to the way we check if the
service still exists.
This commit adapts the rpm scriptlet to solve the issue.
Tested with current master and latest 2.9 release.
=====
Additional rpm output:
Failed to get unit file state for obsapidelayed.service: No such file or directory
=> Suppress additional rpm output on package update

dist/obs-server.spec
In rails assets get add a hash sum to make caching in browser work.
However, to access the assets from a third party (like obs-patterns) we
need a stable link to access it.
=> Symlink assets to a common name

src/api/app/controllers/webui/staging_workflows_controller.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/models/staging_workflow.rb, src/api/app/policies/staging_workflow_policy.rb, src/api/app/views/webui2/webui/project/_tabs.html.haml, src/api/app/views/webui2/webui/staging_workflows/new.html.haml, src/api/config/routes.rb, src/api/spec/controllers/webui/staging_workflows_controller_spec.rb, src/api/spec/factories/staging_workflow.rb
Now the user will be able to create a StagingWorkflow. By default it creates/uses two subprojects of the main project (*:Staging:A and *:Staging:B)
This is how the new action will look like:
Do you feel that the text here is self explanatory?
=> Staging workflow creation

src/api/app/controllers/webui/projects/bs_requests_controller.rb
as the project request page is not yet migrated this code is not needed and
is causing to not properly show the icons.
Fix #6129.
This needs clarification with @bgeuken & @DavidKang. @bgeuken you seem to have introduced https://github.com/openSUSE/open-build-service/pull/5760 and I'm wondering what issue this PR fixed. The project request page is not yet migrated so this code should not be necessary. I'm wondering if this accidentally slipped in while migration the package show view?
=> Drop switch to bootstrap2 on request show page

src/api/app/helpers/webui/buildresult_helper.rb, src/api/app/helpers/webui/packages/job_history_helper.rb, src/api/app/views/webui2/shared/_flag_popover.html.haml, src/api/app/views/webui2/shared/_open_requests.html.haml, src/api/app/views/webui2/shared/_repositories_flag_table_column.html.haml, src/api/app/views/webui2/status_messages/_item.html.haml, src/api/app/views/webui2/webui/attribute/_form.html.haml, src/api/app/views/webui2/webui/main/_status_messages.html.haml, src/api/app/views/webui2/webui/package/side_links/_show_derived_packages.html.haml, src/api/app/views/webui2/webui/package/side_links/_show_devel_package.html.haml, src/api/app/views/webui2/webui/package/side_links/_show_developed_packages.html.haml, src/api/app/views/webui2/webui/package/side_links/_show_inherited_from_project.html.haml, src/api/app/views/webui2/webui/package/side_links/_show_linkinfo.html.haml, src/api/app/views/webui2/webui/package/side_links/_show_patchinfo.html.haml
This PR replaces usage of
* text-primary by text-success for elements that signaling success, like build state, as well as for the enabled flags icon
* and text-secondary by text-info for elements that provide information
Fixes of the cases of #6091
Screenshot (so you can see the differences in the colors):
- Right side, status messages: `text-success` (green) and `text-info` (blue)
- Bottom, buttons: `text-primary` (green) and `text-secondary` (blue)
=> Replace usage of text-secondary and text-primary for coloring elements that present actions and information

src/api/app/models/staging_workflow.rb
The later staging_projects association was overwriting the correct one.
We also added `autosave: true` missing attribute in the first
association.
=> Remove duplicated has_many staging_projects

src/api/spec/controllers/worker/status_controller_spec.rb, src/api/spec/fixtures/files/worker_status_response.xml
Missed that one while reviewing https://github.com/openSUSE/open-build-service/pull/5779
=> Avoid a cassette trick in worker status

src/api/app/views/webui2/webui/staging_workflows/show.html.haml
Staging Project table was wrongly indented and this was causing that the
table has two `thead` and `tbody`.
=> Fix staging_project table content

src/api/Gemfile, src/api/Gemfile.lock, src/api/lib/rabbitmq_bus.rb, src/api/spec/lib/rabbitmq_bus_spec.rb, src/api/spec/models/update_notification_events_spec.rb, src/api/spec/rails_helper.rb, src/api/spec/support/rabbitmq.rb
I was mildly annoyed that I couldn't cover the new events to
be sent to rabbitmq, so I did a little research on how to test
bunny. It's not so easy, but good enough to mock
=> Cover sending events to rabbitmq

src/api/app/assets/stylesheets/webui2/dashed-list.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/staging_workflows_controller.rb, src/api/app/models/project.rb, src/api/app/models/staging_workflow.rb, src/api/app/views/webui2/webui/staging_workflows/_empty_projects_list.haml, src/api/app/views/webui2/webui/staging_workflows/_infos.html.haml, src/api/app/views/webui2/webui/staging_workflows/_requests_list.haml, src/api/app/views/webui2/webui/staging_workflows/show.html.haml, src/api/spec/factories/bs_requests.rb, src/api/spec/models/project_spec.rb, src/api/spec/models/staging_workflow_spec.rb
The Infos section, on the right side, contains the lists of empty projects and requests available to be associated to the Staging Workflow.
This supersedes #6186
=> Show infos section on Staging Workflow layout

src/api/app/controllers/request_controller.rb, src/api/app/policies/bs_request_policy.rb, src/api/test/functional/request_controller_test.rb
Add pundit policy to the ```RequestController#create``` API endpoint. Move authorization logic to the ```BsRequestPolicy#create?``` method
=> Request create with pundit

src/api/spec/controllers/attribute_controller_spec.rb
Use an explicit reload and eq() instead of be()
Fixes #5454
=> Make attribute controller test more robust

dist/obs-bundled-gems.spec
Rake and Rack need to get installed on the system and not
with the bundled_gems archive because we require them for passenger.
This caused that an update of one of these gems in the Gemfile did not trigger
an update of the system gem when updating the RPM package which causes
a crash of the whole application.
Therefore we require them now. There are only 2 gems so it is reasonable to update
the version in the spec file manually for now when we update the gem. The RPM package
build will fail if we don't do it and prevents us from deploying and breaking our instance.
=> Require system gems in api-deps package

src/api/app/models/binary_release.rb
This was caused by https://github.com/openSUSE/open-build-service/commit/e9f6f907bc6af777fe244745baf3d5067c17ca4d#diff-49563098f1992cafd3f7c8195f53a383. Although the code was wrong at that point, because it didn't return `false` if both build times were nil.
Fixes #6240 :bowtie:
=>  Avoid calling strptime with an empty string

src/api/app/views/webui2/webui/staging/workflows/show.html.haml
Probably introduced by a wrong rebase while we introduced the Staging namespace.
=> Fix partial path in Staging::Workflow#show

src/api/app/models/download_repository.rb, src/api/app/models/repository.rb, src/api/app/models/token.rb, src/api/spec/models/download_repository_spec.rb, src/api/spec/models/repository_spec.rb
Make it fail in the application level instead of in the database. :bowtie:
=> Avoid to create records referencing nonexistent objects

src/api/app/views/webui2/webui/staging/workflows/_breadcrumb_items.html.haml
Adapt breadcrumb to the new namespace and also fix the path to staging workflow show action 
=> Adapt staging workflow's breadcrumb to new namespace

src/api/app/models/bs_request.rb, src/api/app/models/bs_request_permission_check.rb, src/api/test/functional/request_controller_test.rb
- Fix permission check in BsRequest.approval_handling and testcase
- Fix approver specific code in BsRequestPermissionCheck
(Maybe we should also document the "cmd=cancelapproval" semantics in
a testcase...)
=> Request approver fixes

src/api/app/models/event/request_create.rb
This allows us to track creation of new requests in grafana.
=> Send requests creation to rabbitmq bus

dist/t/osc/0200-check_docker_registry.ts
Tests are only enabled if "ENABLE_DOCKER_REGISTRY_TESTS=1", so the bail out should be done if tests are not skipped
=> [ci] fix bail out in 0200-check_docker_registry (2.8)

src/api/app/controllers/source/errors.rb, src/api/app/controllers/source_controller.rb, src/api/app/models/project.rb, src/api/app/models/staging/workflow.rb, src/api/app/views/models/staging/_workflow.xml.builder, src/api/lib/backend/api/sources/project.rb, src/api/spec/controllers/staging/staged_requests_controller_spec.rb, src/api/spec/models/staging/workflow_spec.rb
StagingWorkflow is stored in the backend under `_project` directory with
the name `_staging_workflow`. In this special file, we store a minimal
info of the staging_workflow.
=> Store StagingWorkflow in the backend

.gitignore
The byebug (debugger) history should not be committed.
=> Add byebug history to gitignore

src/api/app/models/staging/staging_project.rb, src/api/app/models/staging/workflow.rb
because otherwise using ActiveRecord query methods will consider
all Projects and not only StagingProjects.
This causes some weird issues like returning Projects without
a Staging::Workflow associated.
=> Add default_scope to StagingProject

src/api/app/views/webui2/webui/staging/workflows/_problems.html.haml
* Don't render collapsible links when there are no additional problems.
* Fix offset in index usage of problems. Array index starts with 0 in Ruby.
=> Fix indexing of the problems of a staging project

src/api/Gemfile, src/api/Gemfile.lock, src/api/config/initializers/influxdb_rails.rb, src/api/config/options.yml.example
to collect performance metrics of the OBS rails app like
* request time
* view render time
* db query time
This information will be collection on metrics.o.o
The influxdb is already reachable on metrics.o.o so we could deploy it. Let me know so I can give you the credentials.
=> Add influxdb-rails

src/api/app/assets/javascripts/webui2/staging_workflow.js, src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/models/group.rb, src/api/app/models/staging/staging_project.rb, src/api/app/models/staging/workflow.rb, src/api/app/policies/staging/workflow_policy.rb, src/api/app/views/models/staging/_workflow.xml.builder, src/api/app/views/webui2/webui/staging/workflows/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/staging/workflows/_delete.html.haml, src/api/app/views/webui2/webui/staging/workflows/_infos.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_managers_group.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_projects_table.html.haml, src/api/app/views/webui2/webui/staging/workflows/edit.html.haml, src/api/app/views/webui2/webui/staging/workflows/new.html.haml, src/api/app/views/webui2/webui/staging/workflows/show.html.haml, src/api/config/routes.rb, src/api/db/migrate/20181113095753_add_staging_managers_group.rb, src/api/db/structure.sql, src/api/spec/controllers/staging/staged_requests_controller_spec.rb, src/api/spec/controllers/webui/staging/projects_controller_spec.rb, src/api/spec/controllers/webui/staging/workflows_controller_spec.rb, src/api/spec/factories/staging_workflow.rb, src/api/spec/models/staging/staging_project_spec.rb
Now a Managers group needs to be attached to the staging workflow in order to let them managing the assignation/exclusion of requests in the staging projects.
Now the Managers group assigned is shown in **Infos** sidebox:
When configuring the Staging you can assign a new group, only one will be assigned:
The field for selecting another group is an autocomplete one:
BTW, I have adapted some of the literals the user see. Now the **Staging Workflow** is referred as **Staging.** The edit action is to configure the Staging.
=> Staging workflow managers group

src/api/app/views/webui2/webui/staging/workflows/_problems.html.haml
The delete icon was much smaller than the problem icon, which made
the table look a bit strange.
Since project deletion is one of the main actions on the edit view,
we increase it's size to make it more visible.
Before:
After:
=> Change size icon for staging project deletion

src/api/spec/factories/groups.rb, src/api/spec/factories/staging_workflow.rb
We need to ensure that there are no conflicts between the
generated group titles, to be able to create multiple staging
workflow factories.
=> Add a factory for staging workflow manager groups

src/api/app/assets/stylesheets/webui2/modals.scss
=> Fix long names in modal's heading

src/api/app/controllers/webui/staging/excluded_requests_controller.rb, src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/models/bs_request.rb, src/api/app/models/staging/request_exclusion.rb, src/api/app/models/staging/workflow.rb, src/api/app/views/webui2/webui/staging/excluded_requests/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/staging/excluded_requests/_create_dialog.html.haml, src/api/app/views/webui2/webui/staging/excluded_requests/_delete_dialog.html.haml, src/api/app/views/webui2/webui/staging/excluded_requests/index.html.haml, src/api/app/views/webui2/webui/staging/workflows/_infos.html.haml, src/api/app/views/webui2/webui/staging/workflows/show.html.haml, src/api/config/locales/en.yml, src/api/config/routes.rb, src/api/db/migrate/20181030114152_create_staging_request_exclusions.rb, src/api/db/structure.sql, src/api/spec/controllers/webui/staging/excluded_requests_controller_spec.rb, src/api/spec/factories/staging_request_exclusions.rb
Create request ignoration model, controller and views to create and delete ignored requests.
Things to do (which will be done in following PRs - some of them are not only specific of this feature):
- API
- link to this page
- Improve factories (the managers can for example be created by default in the factory)
- Add validation and index to ensure that a request can not be excluded twice.
- Consider if project is needed as a parameter and if we want to render a staging workflow without project (independent of the decision there would be changes to make)
- Add staging workflow to breadcrumb
=> Create request exclusion model (for ignored requests)

src/api/app/models/staging/workflow.rb, src/api/app/views/webui2/webui/staging/workflows/_infos.html.haml, src/api/spec/controllers/staging/staged_requests_controller_spec.rb, src/api/spec/models/staging/workflow_spec.rb
The assocation was wrong as it should only consider
* Requests in state :review
* with reviews in state :new and by_group of the staging managers
* with the target project of the distribution
Furthermore it changes the ``unassigned_reqeuests`` method to return an ActiveRecordCollection to be more efficient and make it easier to work with.
Additionally added a link to the GroupShow page which is currently used as Backlog.
=> Fix StagingWorkflow#backlog

src/api/app/views/webui2/webui/staging/excluded_requests/_breadcrumb_items.html.haml
This aligns the breadcrumb for excluded requests with the other
staging workflow breadcrumbs.
=> Update breadcrumb for excluded requests

src/api/app/views/shared/_buildresult_box.html.haml, src/api/app/views/webui/kiwi/images/_build_info.html.haml, src/api/app/views/webui2/shared/_buildresult_box.html.haml
Allow use of accesskey to trigger reload
Because users are often waiting for status to update
and do not want to move their mouse to the tiny reload button
Uses Alt-Shift-R in Linux Firefox to trigger a reload
Only slightly tested with manual firebug patching on project/show and package/show pages (new/Beta style)
=> Allow use of accesskey to trigger reload

src/api/app/assets/stylesheets/webui2/staging-workflow.scss
Add a margin to the staging project identifier to have a
clear seperation from the state type and the border of the outer
part of the "icon".
Before:
After:
=> Improve style of overall state icon

src/api/spec/controllers/webui/staging/excluded_requests_controller_spec.rb
This is now part of the staging workflow factory.
Part of https://trello.com/c/R42utmXv/898-create-an-ignored-request-model
=> Remove creation of staging manager group

src/api/app/controllers/staging/staging_projects_controller.rb, src/api/app/views/staging/staging_projects/_broken_packages.xml.builder, src/api/app/views/staging/staging_projects/_building_repositories.xml.builder, src/api/app/views/staging/staging_projects/_missing_reviews.xml.builder, src/api/app/views/staging/staging_projects/_requests_to_review.xml.builder, src/api/app/views/staging/staging_projects/_staged_requests.xml.builder, src/api/app/views/staging/staging_projects/_untracked_requests.xml.builder, src/api/app/views/staging/staging_projects/show.xml.builder, src/api/config/routes.rb, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
Add XML endpoint similar with:
https://build.opensuse.org/project/staging_projects/openSUSE:Factory/C?format=json
the output:
```
<staging_project name="home:foo:Staging:A">
<staged_requests count="1">
<entry id="3" creator="foo" state="review" package="barbar"/>
</staged_requests>
<untracked_requests count="1">
<entry id="4" creator="bar" state="review" package="barbar"/>
</untracked_requests>
<requests_to_review count="1">
<entry id="4" creator="bar" state="review" package="barbar"/>
</requests_to_review>
<missing_reviews count="1">
<entry id="2" creator="foo" state="new" package="barbar"/>
</missing_reviews>
<broken_package count="2">
<entry package="barbar" project="home:foo:Staging:A"/>
<entry package="barbar" project="home:foo:Staging:A"/>
</broken_package>
</staging_project>
```
=> Add XML endpoint for StagingProjectsController#show action

src/api/app/controllers/webui/staging/excluded_requests_controller.rb, src/api/app/views/webui2/webui/staging/excluded_requests/index.html.haml
As `@requests` is not used in the create_dialog partial it can be removed.
=> Remove unused requests variable

src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/views/webui2/webui/staging/workflows/new.html.haml, src/api/spec/controllers/webui/staging/workflows_controller_spec.rb
We need to use `redirect_to` instead of `render` as otherwise, the value of `action_name` is `create` instead of `new`. This would bring a lot of issues in the rendering of the breadcrumbs.
Before:
After (with an error example in the flash):
=> Staging workflow managers group improvements

src/api/app/views/webui2/webui/staging/workflows/_empty_projects_list.html.haml, src/api/app/views/webui2/webui/staging/workflows/_infos.html.haml
Talking with @bgeuken we realized that inside Infos box there is a list of Empty Projects and in the old UI they pointed to the project show page. We consider they should point to the staging project instead.
=> Empty project link to staging project instead of project

src/api/app/models/staging/staging_project.rb, src/api/app/views/webui2/webui/staging/workflows/_empty_projects_list.html.haml, src/api/app/views/webui2/webui/staging/workflows/_overall_state.html.haml, src/api/spec/cassettes/Staging_StagingProject/_overall_state/when_there_are_failed_checks/1_3_5_1.yml, src/api/spec/cassettes/Staging_StagingProject/_overall_state/when_there_are_missing_checks/1_3_3_1.yml, src/api/spec/cassettes/Staging_StagingProject/_overall_state/when_there_are_pending_checks/1_3_4_1.yml, src/api/spec/models/staging/staging_project_spec.rb
As result of a discussion related to #6308 we decided to drop the
identifier, since there is no fixed naming scheme we could rely on.
=> Drop staging identifier

dist/schedule-obs.sh
OpenQA was failing because it was taken the wrong image name. It was taking
files ending in "*.packages" instead of "*.qcow2".
Now we ensure that it takes only those files ending in ".qcow2" extracting from href attribute which looks like:
```
<a href="obs-server.x86_64-2.9.51-qcow2-Buildlp150.20.34.qcow2">
```
=> OpenQA takes the correct qcow2 filename

src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/views/webui2/webui/staging/workflows/_create_staging_project.html.haml, src/api/spec/controllers/webui/staging/projects_controller_spec.rb
Previously we required the location of the staging projects to be
under the 'Staging' namespace of the staging workflow project
(eg. my_workflow_project:Staging:A).
With this commit it will be possible to create the staging project
anywhere as long as the user has permissions to it's location.
=> Make the location of the staging project flexible

src/api/app/views/webui2/webui/package/rdiff.html.haml
Avoid overlapping UI elements in revision diff
by dropping btn-group class that prevents wrapping of individual buttons
Fixes #6330
=> Avoid overlapping UI elements in revision diff

src/api/config/routes.rb
It makes sense to the routes into the staging namespace. It was required here: #6336 :confounded:
=> Add excluded request routes into staging namespace

src/api/app/controllers/staging/staged_requests_controller.rb, src/api/app/controllers/staging/staging_projects_controller.rb
Staging::StagingProject is a subclass of Project. [`get_by_name`](https://github.com/openSUSE/open-build-service/blob/staging-workflow/src/api/app/models/project.rb#L391) should be used always that a project is required instead of `find_by!` as it considers more cases where an exception should be raised. :bowtie:
=> Use Project#get_by_name instead of #find_by in Staging

src/api/app/controllers/application_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/config/options.yml.example
Peek is helpful for OBS developers, that can do something about
performance. Not so much for OBS admins, so disable it by default.
=> Make peek configurable

src/api/app/views/webui2/webui/staging/workflows/_requests_list.html.haml
Use the same level of indentation for 'Empty' requests placeholder as
we use for actual requests.
Before:
After:
=> Update indentation of requests in staging workflow info box

src/api/app/views/layouts/webui2/_footer.html.haml
We currently don't have any reference to our API documentation
in OBS. This will add one.
=> Add link to the API documentation to our footer

src/api/Gemfile, src/api/Gemfile.lock
because the beta version adds more data.
As this is not production critical we can safely use a beta version.
=> Update influxdb-rails to 1.0.0.beta

src/api/app/controllers/webui/staging/excluded_requests_controller.rb, src/api/spec/controllers/webui/staging/excluded_requests_controller_spec.rb
Authorize RequestExclusion instead of StagingWorkflow in RequestExclusionController. Similarly as how it is done in the API controller.
Improve ExcludeRequestsControllerSpec:
- Add tests for policies
- Improve current tests (naming, use to_change, etc.)
=>  Authorize RequestExclusion instead of StagingWorkflow &&  Improve ExcludeRequestsController tests

src/api/app/assets/stylesheets/webui2/project-show.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/project/show.html.haml
I use the existing partials when possible, so for comments and build results. Everything else is a new partial.
To not make this unusable to beta users, this is available only to beta users which are admins/staff. A notice is displayed to explain what we are doing.
=> Add project show layout

src/backend/BSSrcServer/Link.pm, src/backend/BSSrcServer/Service.pm, src/backend/bs_servicedispatch
Services are run on checkin, which usually works with expanded links
(keeplink mode), so this should not make a difference. What's changed
is if a remoterun is triggered, where the current way of running the
service on the unexpanded link is a source of lots of confusion.
The new way to run on expanded links is way more useful. Lets see
how it works in practice.
Also, the link code was changed to always ignore service results
of the link target if the link itself contains a service result.
This was only done for branches before, it is now more consistent.
=> [backend] always run services on expanded links

src/backend/XML/Structured.pm
It currently defaults to using libexpat. We want libxml because:
- it is faster than libexpat
- it does not get 16 random bytes for every parse from the kernel
We also set $XML::SAX::ParserPackage because we do not want the
slow ini file walk that XML::SAX::ParserFactory does for every
parser instantiation.
=> [backend] XML::Structured: prefer XML::LibXML::SAX as saxparser

src/api/app/assets/stylesheets/webui2/user.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/user_controller.rb, src/api/app/helpers/webui/user_helper.rb, src/api/app/models/user.rb, src/api/app/views/webui2/webui/user/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/user/_edit_dialog.html.haml, src/api/app/views/webui2/webui/user/_info.html.haml, src/api/app/views/webui2/webui/user/_involvement.html.haml, src/api/app/views/webui2/webui/user/_password_dialog.html.haml, src/api/app/views/webui2/webui/user/show.html.haml, src/api/spec/models/user_spec.rb
Create the layout for the user home page and implement the info partial. :bowtie: The involvement partial will be implemented in a separated PR. Until that is done only show this view in development environment.
=> Migrate user home info to Boostrap

src/api/app/controllers/webui/users/subscriptions_controller.rb, src/api/app/views/webui2/webui/subscriptions/_subscriptions_form.html.haml, src/api/app/views/webui2/webui/users/subscriptions/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/users/subscriptions/index.html.haml, src/api/app/views/webui2/webui/users/subscriptions/index.js.erb
The notifications are part of the user infos which gets
migrated to bootstrap
=> Migrate user notifications view to bootstrap

src/api/app/models/staging/staging_project.rb
It is a consuming call and it is being already done. :bowtie:
=> Remove unneeded call to set_buildinfo

src/api/app/models/project/update_from_xml_command.rb, src/api/spec/models/project/update_from_xml_command_spec.rb
Webui starts with 0 and that's also the configured 'top'.
And as we rewrite the positions on update, there is no
migration to worry about either. It's just an offset,
but at least future developers won't have to worry if
the 1 is meaningful
=> Don't start repository architectures with position 1

src/api/app/models/user.rb
Improve efficiency of User model queries using pluck. Plucking the ids generate an extra query with the ids and there could potentially be a lot of ids. This make this query way less efficient. :bowtie:
=> Improve User model efficiency

src/api/app/views/webui2/shared/_editor_modal.html.haml
`prjconf` highlighting was using `projconf` instead of `prjconf`.
Related to #6394
=> Fix prjconf highlight

src/api/app/assets/stylesheets/webui2/card-component.scss
Some card headers were too big.
Should fix #6299
=> Reorganize card-component css and fix header height

src/api/app/assets/stylesheets/webui2/live_build_log.scss, src/api/app/views/webui2/webui/package/_live_build_log_controls.html.haml
We changed the colour of `Trigger Rebuild` button from `green` to `yellow` and we also added more margin between buttons 
This should fix #6099
=> Change `Trigger Rebuild` button colour

src/api/app/views/webui2/webui/project/_side_links.html.haml, src/api/app/views/webui2/webui/project/show.html.haml
As pointed out in #6403 by @bgeuken, the now-removed instance variables are unneeded. The calls are inexpensive and it makes the views more readable. We already have so many instance variables.
=> Remove unneeded instance variables in Bootstrap views

src/api/app/views/webui2/webui/package/_buildstatus.html.haml, src/api/app/views/webui2/webui/project/_buildstatus.html.haml
The build results for each repository are indented to
visually distinguish them from the repository they belong to.
Before we were doing this by adding an empty column. Instead we
now use bootstrap's grid column offset.
=> Update grid for build results

src/api/app/helpers/webui/main_helper.rb, src/api/app/views/webui2/status_messages/_item.html.haml, src/api/app/views/webui2/webui/main/_latest_updates.html.haml
The icons were to large in proportion to the content they
belonged to. Reducing their size also required to drop some
tweaks done via padding and column length.
As a side effect the icons no longer overlap with other elements
for certain screen sizes.
Before
After
=> Fix icon sizes and breakpoints of main page

src/api/app/views/webui2/webui/repositories/_breadcrumb_items.html.haml
Use instance variable as the local one is never defined. :bowtie: 
Co-authored-by: @DavidKang
=> Fix package repositories breadcrumb

src/api/app/models/user.rb
Use `select` instead of `pluck` as it generate a subquery with a select instead of adding all the ids to que query. Potentially there could be a lot of ids, which makes this query inefficient. :bowtie:
=> Improve User model efficiency - select

src/api/app/controllers/webui/groups_controller.rb, src/api/app/views/webui/groups/show.html.haml, src/api/app/views/webui2/shared/_requests_table.html.haml, src/api/app/views/webui2/webui/groups/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/groups/show.html.haml, src/api/spec/features/webui/groups_spec.rb
Updating the group members is not done yet. It will be done in another pull request.
=> Migrate group show to Bootstrap

src/api/app/helpers/webui/project_helper.rb, src/api/app/views/webui2/webui/project/_project_inherited_packages.html.haml, src/api/app/views/webui2/webui/project/_project_packages.html.haml, src/api/app/views/webui2/webui/project/show.html.haml, src/api/config/routes.rb
Since we are moving the project view to bootstrap,
the package table need to be migrated as well
=> Migrate project package table to bootstrap.

src/api/app/assets/stylesheets/webui2/build-results.scss
The 'failed' link for the build results should be red, but it was blue.
This broke when moving the defined result colors to a CSS file (f589a07240b).
=> Fix coloring of build result links in the new webui

src/api/app/views/webui2/webui/project/_delete_project_dialog.html.haml
The project_destroy_path doesn't have parameters, so passing the `project` variable isn't needed. This issue prevented the deletion of remote projects.
Fixes #6449
=> Fix project_destroy_path usage

src/api/app/views/webui/project/status.html.erb
* Use Rails DateHelper, distance_of_time_in_words_to_now.
* Drop conversion of failure time (unix timestamp) to a Time object. The
Rails helper is taking care of this.
This also fixes the wrong time ('Fails since 0 days') when the failure is
less than 24 hours old.
=> Fix & Refactor generation of first failure time for project status page

src/backend/bs_repserver
This will fix issues with local multibuild flavors that are not uploaded to the server yet:
- https://github.com/openSUSE/open-build-service/issues/6199
- https://github.com/openSUSE/open-build-service/issues/3523
- https://github.com/openSUSE/open-build-service/issues/3523
=> [backend] getbuildinfo_post: use getprojpack without flavor and refactor

src/api/app/assets/javascripts/webui2/requests_table.js.erb, src/api/app/views/webui2/shared/_patchinfos_table.html.haml, src/api/app/views/webui2/shared/_requests_table.html.haml, src/api/app/views/webui2/webui/users/tasks/index.html.haml
In the new bootstrap UI the request table takes more space. Hence it's
better show less requests by default.
Fixes #6464
=> Reduce the default number of requests shown on the user tasks page

src/api/app/views/webui2/webui/user/_involvement.html.haml
When a user owns a project the owner search would return a touple of
[nil, 'some_project']. Our code was not checking for non-existant
packages and thus caused an error.
=> Fix 500 error when a user owns a project, but not a package

src/api/spec/support/capybara.rb
Instead of injecting things into chrome, capybara's
AnimationDisabler is a rack middle ware that patches
the HTML to include a script and a style section. This
way we don't need to execute javascript.
Note that this is a beta feature of capybara, but exists
since 3.2.0 release (June) - I only discovered it by
chance though :)
Fixes #6457
=> Disable also transitions in tests

src/api/app/assets/javascripts/webui2/autocomplete.js, src/api/app/assets/stylesheets/webui2/repositories.scss, src/api/app/controllers/webui/repositories_controller.rb, src/api/app/views/webui2/webui/repositories/_add_repository_from_project_modal.html.haml, src/api/app/views/webui2/webui/repositories/_add_repository_path_modal.html.haml, src/api/app/views/webui2/webui/repositories/_delete_repository_modal.html.haml, src/api/app/views/webui2/webui/repositories/_delete_repository_path_modal.html.haml, src/api/app/views/webui2/webui/repositories/_edit_repository_modal.html.haml, src/api/app/views/webui2/webui/repositories/_repository_card_content.html.haml, src/api/app/views/webui2/webui/repositories/_repository_entry.html.haml, src/api/app/views/webui2/webui/repositories/_repository_path_item.html.haml, src/api/app/views/webui2/webui/repositories/_request_delete_repository_modal.html.haml, src/api/app/views/webui2/webui/repositories/index.html.haml, src/api/config/routes.rb
Design of the page has been changed:
- Show repositories in a nicer way, using the space more efficiently
- Integrated expert mode in the page.
- Integrate addition of additional paths the page.
TODO (to be done in a different PR):
- Add DoD Repository
- Add from a distribution page
- Tests
- Improve Javascript
Co-authored-by: @DavidKang and @Ana06
=> Migrate repository page to Boostrap

src/api/app/views/webui2/webui/repositories/_breadcrumb_items.html.haml
project_repository_state_path needs a repository defined in order to find
the right route. When the breadcrumb is used in an view where
no repository is set, it will throw an exception. For example in
the add repository view, which will be added soonish.
=> Prevent exception in repositories breadcrumb

src/api/app/views/webui2/webui/project/show.html.haml
Use badges like other views
Before:
After:
=> Be consistent in displaying counts

src/api/app/views/webui2/webui/project/_new_package_branch_modal.html.haml, src/api/app/views/webui2/webui/project/_new_package_modal.html.haml
Use the same modal buttons as the other forms in which we create records
I realized that we missed that in the review of #6458. I found this while working on the subprojects page and comparing the modals...
So it's now like this:
=> Be consistent in modal buttons

src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/project/_tabs.html.haml
While working on the bootstrap migration for the status tab I got
routing issues due to missing 'project' parameters.
The reason for that is that we explicitly set the 'project' for
some path helper calls, but not for all.
```ruby
No route matches {:action=>"index", :controller=>"webui/repositories",
:format=>"html"}, missing required keys: [:project]
- unless project.defines_remote_instance? || project.is_maintenance?
%li.nav-item
= tab_link('Repositories', repositories_path)
%li.nav-item
= tab_link('Monitor', project_monitor_path(project))
%li.nav-item
```
=> Add project variable to all *_path calls in our breadcrumb partial

src/api/app/views/webui2/webui/user/_info.html.haml
To be consistent with other views
Before:
After:
=> Use badge for group tasks

src/api/app/controllers/webui/repositories_controller.rb, src/api/app/views/webui2/webui/repositories/_add_dod_repository_modal.html.haml, src/api/app/views/webui2/webui/repositories/_add_dod_source_modal.html.haml, src/api/app/views/webui2/webui/repositories/_delete_dod_source_modal.html.haml, src/api/app/views/webui2/webui/repositories/_dod_repository_card_content.html.haml, src/api/app/views/webui2/webui/repositories/_dod_source_fields.html.haml, src/api/app/views/webui2/webui/repositories/_edit_dod_source_modal.html.haml, src/api/app/views/webui2/webui/repositories/_repository_entry.html.haml, src/api/app/views/webui2/webui/repositories/index.html.haml, src/api/config/routes.rb
This part was missed in: #6471.
Also add name of project in repositories page title.
TODO (from Add DoD repository):
- Convert create dod repository to `form_for` and use `dod_source_field` partial.
Co-authored-by: @DavidKang
=> Add DoD repository to Bootstrap repository page 

src/api/spec/controllers/webui/repositories_controller_spec.rb
The new bootstrap view redirects the user after a DoD repository
gets created. The test expects a 200 http code instead of a 302.
Related to https://github.com/openSUSE/open-build-service/pull/6489/files
=> Adjust repositories controller rspec for bootstrap DoD migration

src/api/app/views/webui2/webui/repositories/index.html.haml
We previously used 'text-success', but we actually want the
primary color of OBS for styling these icons.
=> Update bootstrap class we use to color repository icons

src/api/app/assets/stylesheets/webui2/modals.scss
It was in some cases overridden by another rule `.card .card-body h5` which then turned the modal header from black to green. This happened when the modal is rendered inside a `div` with the `card` class
=> Set stricter CSS rule for modal header

src/api/app/views/webui2/webui/groups/_add_user_modal.html.haml
=> Fix autocomplete in group members' Add User modal

src/api/app/views/webui2/shared/user_or_groups_roles/_index.html.haml, src/api/spec/support/shared_examples/features/bootstrap_user_tab.rb
- Use nav-link classes for users/groups page
- Use the correct ID for 'Add Group' link
- Capitalize users/groups links correctly
Before:
After:
=> Align links with users/groups page with other pages to be consistent

src/api/app/views/webui2/webui/project/_project_packages.html.haml, src/api/app/views/webui2/webui/project/show.html.haml
This fixes the color of the headers from green to black, so it's now consistent with other modals
Before:
After:
=> Render project_packages modals in the right location

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/webui_controller.rb
The Rails lookup code otherwise has trouble to identify which
'Project' class or module is meant.
I started to get this error when accessing one of the project
pages (in development mode):
"undefined method `find_by' for Webui::Project:Module"
=> Fix lookup issue due to conflicting namespaces

dist/t/spec/features/0030_project_spec.rb
Adapt smoke tests after subprojects page was migrated to Bootstrap. This should fix openQA tests run for OBS.
=> Adapt smoke tests to Bootstrap migration

.circleci/config.yml
Since 1b2b4e1d426237c2d73dee78cb768973fceff504 in mid of August every minitest and rspec test on circleci recompiled the assets already compiled in checkout job. Circleci still doesn't seem to allow using the cache for PRs, so let''s use workspaces to achieve the same.
Before:
https://circleci.com/workflow-run/f2154a1a-2a7b-486f-b4d0-76eb86d8c6b2 total runtime 15:02
After:
https://circleci.com/workflow-run/36f02c72-2fe5-491b-afcf-472e1c112c08 total runtime 13:55
=> Compile assets only once on circleci

src/backend/BSXML.pm, src/backend/bs_repserver, src/backend/bs_srcserver
The endtime can be filtered with the endtime_start and endtime_end
parameters.
=> [backend] add project wide jobhistory query and add an endtime filter

src/api/app/views/webui/project/_packages_table.html.erb, src/api/app/views/webui/project/edit.html.erb, src/api/app/views/webui/project/new_package.html.erb, src/api/app/views/webui/project/new_package_branch.html.erb, src/api/app/views/webui/project/show.html.erb, src/api/app/views/webui/shared/_dialog_action_buttons.html.haml, src/api/app/views/webui2/webui/comment/_links.html.haml, src/api/app/views/webui2/webui/project/_add_new_subproject_modal.html.haml, src/api/app/views/webui2/webui/project/_new_package_branch_modal.html.haml, src/api/app/views/webui2/webui/project/_new_package_modal.html.haml, src/api/spec/bootstrap/features/webui/maintenance_workflow_spec.rb, src/api/spec/bootstrap/features/webui/projects_spec.rb, src/api/spec/features/webui/comments_spec.rb, src/api/spec/features/webui/maintenance_workflow_spec.rb, src/api/spec/features/webui/packages_spec.rb, src/api/spec/features/webui/patchinfo_spec.rb, src/api/spec/features/webui/projects_spec.rb, src/api/spec/features/webui/requests_spec.rb
We currently have the bootstrap views behind a feature switch. Some of
these bootstrap views require some adaptations of the existing tests in
order to pass.
=> Align the old UI with the new Bootstrap UI to pass the specs

src/api/app/assets/stylesheets/webui2/tabs-component.scss
Fixes: #6525 
In small screens, codemirror toolbar was overlapping dropdown menu.
Toolbar's z-index is set to auto but it seems its value is 1020, so 1021
is enough to show the menu above.
This Bootstrap configuration can be the explanation:
```$zindex-sticky:            1020 !default;```
https://getbootstrap.com/docs/4.1/layout/overview/#z-index
Before:
After:
=> Avoid codemirror toolbar to overlap dropdown menu

src/api/app/assets/stylesheets/webui2/tabs-component.scss
When a dropdown menu link was clicked, the text became green on top of a
green background. Now text is set to white in that case (:active).
Fixes: #6526
Before:
After:
=> Show white text when clicking on dropdown menu link

src/api/app/models/event.rb
PLEs belong to a project so it makes not much sense to track
creation/deletion of Projects with PLEs.
Don't know what Event::Upload is. No events or PLEs like
that in production, we also show this nowhere.
=> Cleanup classes that create ProjectLogEntries

src/api/app/views/webui2/webui/package/_branch_dialog.html.haml, src/api/app/views/webui2/webui/project/_new_package_branch_modal.html.haml, src/api/app/views/webui2/webui/project/_new_package_modal.html.haml
This align the package branch modal with the other modals.
Before:
After:
=> Remove 'close' icon from modal for package branching

src/api/Gemfile, src/api/Gemfile.lock, src/api/config/initializers/influxdb_rails.rb, src/api/config/options.yml.example, src/api/lib/influxdb_obs/obs/middleware/backend_subscriber.rb
We need to use the beta branch because it is fixing an issue which
currently kills our InfluxDB server in production (adding the
path element as tag causes millions of tags which need to get
indexed).
=> Update influxdb-rails gem

src/api/lib/influxdb_obs/obs/middleware/backend_subscriber.rb
It is not necessary as the influxdb gem already does this. This will also fix a flaky spec.
=> Do not run InfluxDB backend subscriber in background

src/api/config/initializers/influxdb_rails.rb
because it is disabled by default and provides useful information.
=> Enable sql series for influxdb-rails gem

src/api/.rubocop.yml
Following a discussion we had here: https://github.com/openSUSE/open-build-service/pull/6502/files#r240317760
=> Disable RuboCop RSpec/MultipleExpectations for feature specs

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/layouts/webui2/_watchlist_dropdown.html.haml, src/api/app/views/webui/project/edit.html.erb, src/api/app/views/webui/project/show.html.erb, src/api/app/views/webui2/webui/project/bottom_actions/_submit_as_update.html.haml, src/api/spec/bootstrap/features/webui/maintenance_workflow_spec.rb, src/api/spec/bootstrap/features/webui/projects_spec.rb, src/api/spec/bootstrap/features/webui/watchlists_spec.rb, src/api/spec/cassettes/Bootstrap_Projects/branching/a_non-existing_package.yml, src/api/spec/cassettes/Bootstrap_Projects/branching/a_package_with_disabled_access_flag.yml, src/api/spec/cassettes/Bootstrap_Projects/branching/a_package_with_disabled_sourceaccess_flag.yml, src/api/spec/cassettes/Bootstrap_Projects/branching/an_existing_package_to_an_invalid_target_package_or_project.yml, src/api/spec/cassettes/Bootstrap_Projects/changing_project_title_and_description.yml, src/api/spec/cassettes/Bootstrap_Watchlists/add_projects_to_watchlist.yml, src/api/spec/cassettes/Bootstrap_Watchlists/remove_projects_from_watchlist.yml, src/api/spec/features/webui/projects_spec.rb, src/api/spec/features/webui/watchlists_spec.rb, src/api/spec/support/features/features_bootstrap.rb
Align the old UI with the new Bootstrap UI for specs:
- Update project feature specs
- Maintenance workflow feature specs
- Watchlist feature specs
These include fixes to existing feature specs to make them pass when
testing the new bootstrap UI. Specs that can't be written for both UIs
got ported to the spec/bootstrap/* directory.
Fix Submit as Update link condition
=> Enable Bootstrap project show to all beta users

src/api/app/helpers/webui/project_helper.rb
I discovered this amazing method today: https://guides.rubyonrails.org/active_support_core_extensions.html#ordinalize
Also put the dates in an ascending order and added the year
Before:
After:
=> Ordinalize the dates on the project pulse page

src/api/app/models/user.rb
Possibly there are other ways but this way mariadb is no
longer using the role_id key but merges user_id and group_id
index hits - which are way less than all maintainers checked
by where
Fixes #6548
500ms -> 10ms
=> Preselect group_ids to ease SQL query for involved_packages

src/api/app/views/webui2/webui/project/monitor.html.haml
=> Center text in project monitor table

src/api/app/views/webui2/webui/projects/pulse/_pulse_list_builds.html.haml
This is an issue which was reported to us following our announcement to the opensuse-buildservice@opensuse.org mailing list.
Take note that normally, the view doesn't display the builds information when no builds are present. However, to prove that it's an issue and to show the fix, I've forced this to be displayed (it's not included in the changes though, it was just to take the screenshots below...)
Before (missing zeroes):
After (with zeroes):
=> Set 0 as a default value for pulse failed/succeeded builds

src/api/lib/influxdb_obs/obs/middleware/backend_subscriber.rb, src/api/spec/lib/influx_db/obs/middleware/backend_subscriber_spec.rb
In 3473cb722e07b3e9235b538777fb1f80e373bb97 we changed from float to int datatype.
In InfluxDB it is not possible to change the field type easily. The easiest approach
is to just use a different field name which we just do now.
=> Change field name for backend influx subscriber

dist/t/spec/features/0030_project_spec.rb, dist/t/spec/features/0040_package_spec.rb
Smoke test, those run in [openQA](https://openqa.opensuse.org/group_overview/17), are adapted to be run in versions 2.8 and 2.9 of OBS, with old literals, and in master branch, with new literals.
=> Fix smoke tests, after some literals got modified

src/api/Gemfile, src/api/Gemfile.lock, src/api/app/assets/javascripts/webui/application.js.erb, src/api/app/assets/javascripts/webui2/application.js, src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/package/_file.html.erb, src/api/app/views/webui/package/_files_view.html.erb, src/api/app/views/webui2/webui/package/_file.html.haml, src/api/app/views/webui2/webui/package/_files_view.html.haml
InfluxDB performance measuring showed that this view is a bottleneck on Package#show with
a mean render time of ~ 280 ms (bootstrap) and 160 ms (bentoo). Therefore we
introduce now collection caching.
We also need to introduce timeago_tag jquery gem to be able to cache the table
otherwise the timeago would be cached as well causing wrong results.
https://metrics.opensuse.org/d/Gpp3B1Pik/package-show-dashboard
=> Improve Package#show performance

src/api/app/views/webui2/webui/package/show.html.haml
because it was hard to see on the same line as the information.
New: 
Old:
=> Move 'unmerged sources' link to next line

src/api/app/views/webui2/webui/project/show.html.haml, src/api/app/views/webui2/webui/user/_involvement.html.haml
because the number of packages is already included in the tab
and this removes some noise from the view.
Old:
=> Remove table info from Package datatable

src/api/app/views/webui/package/_file.html.erb, src/api/app/views/webui/package/_files_view.html.erb, src/api/app/views/webui2/webui/package/_file.html.haml, src/api/app/views/webui2/webui/package/_files_view.html.haml
Because for instance the srcmd5 does change for all files of a package
when the md5 of one file does change which invalidates all file caches.
However, in this case we only want to invalidate the cache of the single
file and not all.
=> Only use md5 and mtime as cache key

src/api/app/views/webui2/webui/package/_delete_file_dialog.html.haml, src/api/app/views/webui2/webui/package/_file.html.haml, src/api/app/views/webui2/webui/package/_files_view.html.haml
Instead of generating html code for each modal that asks for deleting a file, only one modal is created. Arguments for the modal are passed with "data-*" attributes.
=> Refactor delete of files

src/api/app/assets/stylesheets/webui/application/cm2/suse.scss
Undo commit e31f2ca36b ("Use 'Liberation Mono' font for code
blocks"). I want my system's preference to be used again. Using
Liberation only there is also weird, because other places with
preformatted text, like the request review comment box, or the
package build log, still use the default monospace.
The "disappearing underscore" problem is caused by the line-height
directive, and *also* manifests in Chromium(!), starting with a
line-height of 105%. It turns out browsers have this weird idea that
the default line-height is "120%" and, as a result, any value less
than that shrinks the box. Throw out line-height for good. …
=> webui: use system monospace font for patch box again

src/api/app/views/webui2/webui/comment/_content.html.haml
Fixes #6183
Whenever an avatar is not loading somehow, we replace its `img` tag by a default icon. We keep the same classes as the avatar to be consistent.
I'm not entirely sure if this is the best approach, but I don't really have another in mind. If you validate this approach, I will move the Javascript to the assets and use it in the other pages where we also have avatars. This would be all done in this PR.
Example:
=> Use a default icon for avatar loading error

src/api/config/environments/test.rb
This is rails default - and I actually have no idea why it works for anyone else. Without serving public files, I have no assets in tests :question:
=> Serve public assets in tests

src/api/app/views/webui2/shared/user_or_groups_roles/_delete_dialog.html.haml, src/api/app/views/webui2/shared/user_or_groups_roles/_index.html.haml, src/api/app/views/webui2/shared/user_or_groups_roles/_list.html.haml
Instead of generating html code for each modal that asks for deleting a role, only one modal is created. Arguments for the modal are passed with "data-*" attributes.
Following work started in #6608.
=> Refactor delete of roles

src/api/app/views/webui2/webui/attribute/_delete_dialog.html.haml, src/api/app/views/webui2/webui/attribute/index.html.haml, src/api/spec/bootstrap/features/webui/attributes_spec.rb
Instead of generating html code for each modal that asks for removing an attribute, only one modal is created. Arguments for the modal are passed with "data-*" attributes.
Following work started in #6608.
=> Refactor delete of attribute

src/api/app/assets/stylesheets/webui2/breadcrumbs-component.scss, src/api/app/views/webui2/webui/main/_breadcrumb_items.html.haml
On each page the breadcrumb starts with 'openSUSE Build Service'.
This text is taking away quite some space from the breadcrumbs and it
is not adding much value. Users already know that they are looking at
the OBS when they reached this page.
In case they don't we still have the OBS logo in the navbar.
The link to the main page is now part of the 'home' icon that is
part of each breadcrumb.
-------------------
Depending on which page you are this looks a bit different. That's why I added a couple of screenshots:
On the main page:
On the other pages:
=> Remove OBS label from breadcrumbs

src/api/app/views/webui2/webui/package/binaries.html.haml
=> Update subheader for repository states

src/api/app/models/role.rb
Role.hashed uses Rails.all.cache_key - which is rather expensive
SELECT COUNT(*) AS `size`, MAX(`roles`.`updated_at`) AS timestamp FROM `roles`
to avoid querying 8 role titles. The problem is that all the
other code expects Role.hashed to be cheaper than querying the
database directly - which is no longer true with this approach.
E.g.
```
irb(main):001:0> Role.local_roles
(0.2ms)  SELECT COUNT(*) AS `size`, MAX(`roles`.`updated_at`) AS timestamp FROM `roles`
(0.3ms)  SELECT COUNT(*) AS `size`, MAX(`roles`.`updated_at`) AS timestamp FROM `roles`
(0.2ms)  SELECT COUNT(*) AS `size`, MAX(`roles`.`updated_at`) AS timestamp FROM `roles`
(0.2ms)  SELECT COUNT(*) AS `size`, MAX(`roles`.`updated_at`) AS timestamp FROM `roles`
(0.2ms)  SELECT COUNT(*) AS `size`, MAX(`roles`.`updated_at`) AS …
```
=> Do not use expensive hash keys for cheap queries

src/api/app/models/user.rb
is_admin? is called in many places, often 3 and more times
per action.
=> Cache User#is_admin? & User#is_staff?

src/api/app/views/webui2/webui/project/_monitor_control.html.haml
* Give it more emphasive by removing the 'outline' style.
* Make it more explicit that this is an action by updating the
button label.
=> Update styling of monitor filter

src/api/app/views/webui2/shared/_requests_table.html.haml
When we set some filters in requests' page and then click on Refresh,
all the filters get reset (back to default values). We also realized
that the Refresh functionality is not really needed. Therefore, we
decide to remove the button.
=> Remove Refresh button from requests page in bootstrap

src/api/app/controllers/status/checks_controller.rb, src/api/app/views/status/checks/_check.xml.builder, src/api/app/views/status/checks/show.xml.builder, src/api/app/views/status/reports/show.xml.builder
The check's required function actually checks the checkable
of the status_report, which is rather expensive
```
SELECT  `status_reports`.* FROM `status_reports` WHERE `status_reports`.`id` = 32 LIMIT 1  [["id", 32], ["LIMIT", 1]]
SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`id` = 342446 LIMIT 1  [["id", 342446], ["LIMIT", 1]]
```
And this is done for every check in the report. While we already know
the checkable (the repository), so just pass it to the partial.
=> Avoid .required? function in loops

src/api/app/helpers/flag_helper.rb, src/api/app/views/models/_package.xml.builder, src/api/app/views/models/_project.xml.builder
Using .empty? on a relation is a SQL query - but as we want
the flags anyway, querying them into an array and asking ruby
afterwards if the array is empty saves us one trip to the DB
for those flags that exist
```
Flag Exists (0.7ms)  SELECT  1 AS one FROM `flags` WHERE `flags`.`package_id` = 3958965 AND `flags`.`flag` = 'lock' LIMIT 1
Flag Exists (0.6ms)  SELECT  1 AS one FROM `flags` WHERE `flags`.`package_id` = 3958965 AND `flags`.`flag` = 'build' LIMIT 1
Flag Load (0.2ms)  SELECT `flags`.* FROM `flags` WHERE `flags`.`package_id` = 3958965 AND `flags`.`flag` = 'build' ORDER BY `flags`.`position` ASC
Flag Exists (0.6ms)  SELECT  1 AS one FROM `flags` WHERE `flags`.`package_id` = 3958965 AND `flags`.`flag` = 'publish' LIMIT 1
Flag Load (0.2ms)  SELECT `flags`.* FROM `flags` WHERE …
```
=> Just fetch the flags and check if they are empty afterwards

src/api/app/assets/stylesheets/webui2/breadcrumbs-component.scss, src/api/app/views/webui2/webui/main/_breadcrumb_items.html.haml
Style any link within the breadcrumbs the same, regardless of having the 'breadcrumb-item' class or not.
This is just a follow up of #6592 which was already merged when I realized that the CSS could be written in a simpler way.
=> Cleanup breadcrumb CSS

src/api/app/controllers/status/reports_controller.rb
:report_uuid is mandatory but wasn't used in the controller. Instead
it always returned .first - for unknown reason
Fixes https://github.com/openSUSE/open-build-service/issues/6124
=> Report the right status report

src/api/app/views/webui2/webui/staging/excluded_requests/_delete_dialog.html.haml, src/api/app/views/webui2/webui/staging/excluded_requests/index.html.haml
Instead of generating html code for each modal that asks for removing a excluded reques,t only one modal is created. Arguments for the modal are passed with "data-*" attributes.
Following work of #6608.
=> Refactor removing excluded request

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/project.js, src/api/app/controllers/webui/project_controller.rb, src/api/app/views/layouts/webui2/webui.html.haml, src/api/app/views/webui2/webui/project/list.html.haml
The content of the public projects' table is added by javascript. We keep it like
it was with small changes only: the table itself is written by the view not by JS,
we add "Search" placeholder and remove some unnecessary params.
Before:
After:
=> Migrate project index page to bootstrap

src/api/config/environments/test.rb
This allows us to see the backtrace in CircleCI when a feature test fails, which makes debugging   feature tests much easier. :bowtie: 
Before (CircleCI artifact):
After:
=> Enable consider_all_requests_local in test suite

src/api/app/views/webui2/webui/repositories/_repository_card_content.html.haml, src/api/app/views/webui2/webui/repositories/_repository_entry.html.haml, src/api/app/views/webui2/webui/repositories/index.html.haml
This function was called *twice* per repository and is not
exactly cheap:
```
CACHE Flag Exists (0.0ms)  SELECT  1 AS one FROM `flags` WHERE `flags`.`project_id` = 2 AND `flags`.`flag` = 'lock' AND `flags`.`status` = 'enable' LIMIT 1
has_global_permission? change_project
CACHE  (0.0ms)  SELECT `roles_static_permissions`.`role_id` FROM `roles_static_permissions` INNER JOIN `static_permissions` ON `static_permissions`.`id` = `roles_static_permissions`.`s tatic_permission_id` WHERE `static_permissions`.`title` = 'change_project'
running local permission check: user coolo, project home:Admin, permission 'change_project'
CACHE Project Load (0.0ms)  SELECT  `projects`.* FROM `projects` WHERE (projects.id not in (0)) AND `projects`.`name` = 'home' ORDER BY `projects`.`name` DESC LIMIT 1
CACHE …
```
=> Cache user_can_modify_project in repository page

src/api/config/initializers/influxdb_rails.rb
For whatever reason influxdb-rails keeps flooding localhost:8086
if nothing is configured - for every developer, only test environment
is ignored by default
=> If there is no influxdb config, we don't want the default

src/api/app/views/webui2/webui/project/_add_new_subproject_modal.html.haml, src/api/app/views/webui2/webui/project/_form.html.haml, src/api/app/views/webui2/webui/project/_new_project_modal.html.haml, src/api/app/views/webui2/webui/project/list.html.haml, src/api/app/views/webui2/webui/project/subprojects.html.haml
The project creation form is re-designed using bootstrap and it is shown on a modal instead of a page.
The code for creation modal is unified for both projects and subprojects, they are very similar.
Before:
After:
=> Migrate project creation page to bootstrap

src/api/app/models/repository.rb
Architectures don't have a position, so I assume the
relation is pretty much unused, because it would crash
every time - not just in preloads
Fixes #6662
=> Make it possible to preload architectures

src/api/app/models/project.rb
has_remote_repositories? is called from project update? policy, which is called in a lot of places. And it's horribly slow as it loops through an array with N+1 queries looking like this in logs:
```
DownloadRepository Exists (0.1ms)  SELECT  1 AS one FROM `download_repositories` WHERE `download_repositories`.`repository_id` = 357782 LIMIT 1
DownloadRepository Exists (0.2ms)  SELECT  1 AS one FROM `download_repositories` WHERE `download_repositories`.`repository_id` = 157220 LIMIT 1
DownloadRepository Exists (0.1ms)  SELECT  1 AS one FROM `download_repositories` WHERE `download_repositories`.`repository_id` = 214402 LIMIT 1
DownloadRepository Exists (0.1ms)  SELECT  1 AS one FROM `download_repositories` WHERE `download_repositories`.`repository_id` = 289102 LIMIT 1
DownloadRepository …
```
=> Avoid N+1 queries in update policy

src/api/app/views/webui2/webui/project/show.html.haml, src/api/app/views/webui2/webui/user/_involvement.html.haml
To be consistent in all tables. We have some pages where tables don't have any control (pagination, search), we don't display the information in such cases. When only the search is present, we don't either. In these cases, the tables contain only a few rows (examples: users/groups, attributes).
=> Display table information when the pagination is also displayed

src/api/.rubocop_todo.yml, src/api/app/controllers/webui/repositories_controller.rb, src/api/app/controllers/webui2/repositories_controller.rb, src/api/app/mixins/get_flags.rb, src/api/app/models/package.rb, src/api/app/models/project.rb, src/api/spec/controllers/webui/repositories_controller_spec.rb, src/api/spec/models/flag/specified_flags_spec.rb, src/api/test/unit/project_test.rb
The were only supporting the rather crude get_flags, which is only
used in one controller action, which queries architecture and
repositories anyway - so wasteful
=> Remove architecture and repository relationship from project and package

src/api/app/assets/javascripts/webui2/project.js
Use bootstrap's w-* class to get correct column sizes.
It seems that since we rendered the table content as part of the
datatable initialization the relative column width (60% / 40%) was
incorrect.
This caused the first column to be way to small (~ 9px).
Before:
After:
=> Fix size of columns of the projects list

src/api/app/views/webui2/webui/package/_delete_binaries_dialog.html.haml, src/api/app/views/webui2/webui/package/binaries.html.haml, src/api/app/views/webui2/webui/package/binaries/_trigger_rebuild_wipe_binaries.html.haml
Instead of generating html code for each modal that asks for removing the binaries, only one modal is created. Arguments for the modal are passed with "data-*" attributes.
Following work of #6608.
=> Refactor removing binaries

src/api/config/routes.rb
- removes the `release_repository_dialog` routes from routes.rb as it is not
being used
Fixes #6534
=> Remove unused release_repository_dialog route

src/api/app/controllers/webui/architectures_controller.rb, src/api/app/services/architectures_controller_service/architecture_updater.rb
To reduce logic in the controller, move some update relate code
from action ```bulk_update_availability``` to its own service
=> Move code to service

src/api/app/models/project.rb
* Drop unused project scopes
* Make the autocompletion queries more flexible.
We used to only search for matches that would start with the search
string. Since we now limit the search results, we be more flexible
and include results that match with the search string at all.
=> Update autocompletion queries and drop unused scopes

src/api/app/views/webui2/webui/repositories/_delete_repository_modal.html.haml, src/api/app/views/webui2/webui/repositories/_delete_repository_path_modal.html.haml, src/api/app/views/webui2/webui/repositories/_dod_repository_card_content.html.haml, src/api/app/views/webui2/webui/repositories/_repository_card_content.html.haml, src/api/app/views/webui2/webui/repositories/_repository_path_item.html.haml, src/api/app/views/webui2/webui/repositories/_request_delete_repository_modal.html.haml, src/api/app/views/webui2/webui/repositories/index.html.haml, src/api/spec/bootstrap/features/webui/repositories_spec.rb
Instead of generating html code for each modal that asks for deleting something in repositories, only one modal is created.
Following work of #6608.
=> Refactor repositories delete modals

src/api/app/controllers/application_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/app/jobs/application_job.rb, src/api/config/clock.rb, src/api/lib/backend/instrumentation.rb
Several improvements:
* Reset the location otherwise RAW calls will be wrongly tagged
* Remove volley tag as it was useless
* Set RAW tag when we directly call the backend
=> Improve InfluxDB backend reportings

src/api/app/controllers/request_controller.rb, src/api/test/functional/request_controller_test.rb
With that the SQL time shrinks from 25s to 0.6s, the
rendering of all that XML is still taking quite some time,
but hopefully it doesn't stick it out so badly
Fixes #6725
=> Preload request details in view=collection code

src/api/app/models/flag.rb, src/api/db/data/20181214100207_remove_duplicated_flags.rb, src/api/db/data_schema.rb, src/api/spec/db/data/remove_duplicated_flags_spec.rb, src/api/test/unit/build_flag_test.rb, src/api/test/unit/debug_flag_test.rb, src/api/test/unit/publish_flag_test.rb
This has been broken since the introduction as
where('repo = ?', repo) for nil values compares with NULL,
which never exists. On top of that this also checked if
status was duplicated, which means you could have an
enabled and disabled status for the same field, which doesn't
make much sense :bowtie: 
We have a lot of duplicated flags by now, so we need
a data migration :eyes: 
Co-authored-by: @Ana06 
Fixes #6615
=> Fix flag validation catching duplicates

src/api/Gemfile
There is no reason to block this gem in version 1.2.0, version 2.0.0 includes great changes and bug fixes :cupid:
=> Allow depfu to update Rantly

src/api/app/controllers/application_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/app/jobs/application_job.rb, src/api/config/clock.rb, src/api/config/initializers/influxdb_rails.rb, src/api/lib/backend/instrumentation.rb
Several improvements for InfluxDB mostly concerning the (default) tags we sent. We now set default tags in the initializer making sure they're never empty (e.g. for DelayedJob processed in the background).
=> Improve InfluxDB

src/api/app/controllers/application_controller.rb, src/api/test/functional/maintenance_test.rb, src/api/test/functional/source_controller_test.rb, src/api/test/test_consistency_helper.rb
When we authenticate a user, we set User.current = .
Howerver, after the request is processed we never set it to nil.
If the next request does not require authentication and skips the
extract_user before filter, we still have the user from the previous
request set in User.current.
We should clean up what we set in Thread.current.
=> Set nobody when request is processed

src/api/app/views/webui2/webui/package/binary.html.haml
Without this patch,
https://build.opensuse.org/package/binary/home:bmwiedemann/git-deps/openSUSE_Leap_15.0/x86_64/git-deps-1-lp150.5.1.noarch.rpm
had
```html
<h3>
Detailed Information About git-deps-1-lp150.5.1.noarch.rpm
<a title="Download file" href="<a href=&quot;https://api.opensuse.org:443/build/home:bmwiedemann/openSUSE_Leap_15.0/x86_64/git-deps/git-deps-1-lp150.5.1.noarch.rpm&quot;>git-deps-1-lp150.5.1.noarch.rpm</a>"><i class='fas fa-download text-secondary'></i>
</a></h3>
```
=> Fix link for downloading a binary

src/api/app/views/webui2/webui/package/_file.html.haml, src/api/app/views/webui2/webui/project/_project_packages.html.haml
Use the timestamp instead of the generated string in the `Changed` column of
the packages table in the project page and in the files table in the package
page. It is ordered in inverse order in contrast as what it used to be
(incorrectly) done in the old UI. :bowtie: 
Fixes https://github.com/openSUSE/open-build-service/issues/6640
=> Sort changed column by time and not alphabetically

src/api/app/models/project.rb
Fixes https://github.com/openSUSE/open-build-service/issues/6753
before
```
puts Project.autocomplete('openSUSE:Factory')
devel:openSUSE:Factory
devel:openSUSE:Factory:Apps
devel:openSUSE:Factory:for-legal-lhf
devel:openSUSE:Factory:kernel
devel:openSUSE:Factory:legal-queue
devel:openSUSE:Factory:rpmlint
home:1enn0:branches:openSUSE:Factory
home:Guillaume_G:branches:openSUSE:Factory:ARM
home:JERiveraMoya:branches:devel:openSUSE:Factory
home:JRivrain:branches:devel:openSUSE:Factory
home:Jeffreycheung:branches:openSUSE:Factory
home:JonathanKang:branches:openSUSE:Factory
home:MartinMohring:playground:openSUSE:Factory:Base:build:armv5el
home:MartinMohring:playground:openSUSE:Factory:Base:build:stage1
home:SebD:branches:openSUSE:Factory
home:StefanBruens:branches:devel:openSUSE:Factory:rpmlint …
```
=> Order the autocomplete projects by length of match

src/api/Gemfile, src/api/Gemfile.lock, src/api/app/controllers/application_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/lib/influxdb_obs/obs/middleware/backend_subscriber.rb
To move forward with InfluxDB we use now our fork of the influxdb-rails gem. Our focus is still "upstream first" but often enough in the past some of our improvements on the gem turned out to be not practical in production (cardinality of tags, empty tags etc etc). As the bundle gems service currently does not support anything other than rubygems, we created an experimental gem to try out some of our improvements. As long as bundle gems does not support downloads from other services than rubygems.org this is the easiest solution. All other solutions have other trade offs like e.g. not working in CI or development. 
The main feature we would like to try out with production data is adding the request start time and request id. This will enable us to show e.g. the slowest requests of a …
=> Use our fork of the influxdb-rails gem

src/api/app/controllers/staging/staged_requests_controller.rb, src/api/app/models/staging/stage_requests.rb, src/api/app/views/webui2/webui/staging/projects/_history_elements.html.haml, src/api/app/views/webui2/webui/staging/projects/show.html.haml
There is one difference now: The history was before done by comments on the project page. This history is now done with ProjectLogEntries and therefore it is on the staging project page. However, I guess this is an improvement. If it was desired to have it on the project show page, we can move it also there.
=> Add history to staging project show page

src/api/lib/influxdb_obs/obs/middleware/backend_subscriber.rb, src/api/spec/lib/influx_db/obs/middleware/backend_subscriber_spec.rb
This reverts commit a0b183ea52e48bb36898701f17525c0d9bf1dd5b.
Because this was just a workaround to not drop the entire series.
We needed to do this anyway so it makes sense to use value as
field name again to be par with the other series.
=> Revert "Change field name for backend influx subscriber"

src/api/app/models/package.rb, src/api/spec/bootstrap/features/webui/maintenance_workflow_spec.rb
When updating a package in a maintenance project which already exists it crashed
because it tried to create the flags again which caused the uniqueness validation to crash.
This was introduced in #6619.
Fix #6766.
=> Fix maintenance incident release when package already exists

dist/obsscheduler, dist/setup-appliance.sh, dist/systemd/obsscheduler.service
/etc/SUSE-release is no longer on our appliances.
Thats why we see the following error message on freshly installed systems:
head: cannot open '/etc/SuSE-release' for reading: No such file or directory
This patch uses /etc/os-release if /etc/SuSE-release is not present or
sets it to "UNKNOWN" if /etc/os-release isn`t present either
=> [dist] fix for missing /etc/SUSE-release in setup-appliance.sh

src/api/Gemfile, src/api/Gemfile.lock, src/api/app/models/repository.rb, src/api/app/models/staging/staging_project.rb, src/api/spec/cassettes/Staging_StagingProject/_copy/1_6_2.yml, src/api/spec/cassettes/Staging_StagingProject/_copy/copies_flags.yml, src/api/spec/cassettes/Staging_StagingProject/_copy/copies_the_project_config.yml, src/api/spec/cassettes/Staging_StagingProject/_copy/copies_the_relationships.yml, src/api/spec/cassettes/Staging_StagingProject/_copy/copies_the_repositories.yml, src/api/spec/cassettes/Staging_StagingProject/_copy/copies_the_repositories_and_it_s_relations.yml, src/api/spec/cassettes/Staging_StagingProject/_copy/creates_a_new_staging_project.yml, src/api/spec/cassettes/Staging_StagingProject/_copy/when_the_repository_contains_path_elements_that_link_to_repositories_of_the_same_project/ensures_that_the_new_created_path_is_also_self_referencing.yml, src/api/spec/cassettes/Staging_StagingProject/_copy/when_the_repository_contains_path_elements_that_link_to_repositories_of_the_same_project/renames_the_repository_link_if_it_contains_a_reference_to_the_project.yml, src/api/spec/cassettes/Staging_StagingProject/_copy/when_the_repository_contains_path_elements_that_link_to_themself/ensures_that_the_new_created_path_is_also_self_referencing.yml, src/api/spec/factories/project.rb, src/api/spec/factories/staging_projects.rb, src/api/spec/features/webui/projects_spec.rb, src/api/spec/models/repository_spec.rb, src/api/spec/models/staging/staging_project_spec.rb
Follow up of #6759 (The first two commits).
This adds some code to handle staging projects that contain repositories that link to repositories of the project they belong to. In such cases we now clone the self-referencing link.
=> Handle self-referencing repositories when cloning staging projects

src/backend/bs_admin
It is sometimes useful to be able to sign with existing keys, perhaps
due to corporate policies (EG: for EFI Secure Boot).
It is not enough to substitute a project's _signkey and _pubkey on the
filesystem, the database has to be updated or the previous _sslcert
will be used, since that is never stored on the disk.
Add a new --update-project-signing-key option to bs_admin to facilitate
the operation for an administrator.
=> [backend] bs_admin: add option to replace a project's signing key

src/api/spec/models/kiwi/repository_spec.rb
Since last Rantly released wrong ranges return `nil` instead of a wrong value inverting the range (as mentioned in the release notes).
Fixes https://github.com/openSUSE/open-build-service/issues/6773
@dmarcoux  this should fix the flickering tests.
@coolo Rantly was correctly released. The current maintainer did a great job. :stuck_out_tongue_winking_eye:
=> Fix wrong ranges in Rantly tests

src/api/Gemfile, src/api/Gemfile.lock
According to our git history we a couple of gem updates
regardless of the fixed version requirement. There is also
no known reason to lock this gem to an older version.
=> Remove required version for data_migrate gem

src/api/app/models/staging/workflow.rb, src/api/spec/models/staging/workflow_spec.rb
A request is «ready» when its state is «new» and it has some reviews and
at least one of them is in state «accepted».
=> Ready requests take reviews into account

docs/api/api/api.txt, src/api/app/controllers/staging/staging_projects_controller.rb, src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/jobs/staging_project_copy_job.rb, src/api/app/policies/staging/workflow_policy.rb, src/api/app/views/webui2/webui/staging/projects/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/staging/projects/preview_copy.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_projects_table.html.haml, src/api/config/routes.rb, src/api/spec/cassettes/StagingProjectCopyJob/_perform/copies_the_staging_project.yml, src/api/spec/controllers/staging/staging_projects_controller_spec.rb, src/api/spec/controllers/webui/staging/projects_controller_spec.rb, src/api/spec/jobs/staging_project_copy_job_spec.rb
For the WebUI part, I have created a view to preview the copy of a staging project. Right now, it's quite basic and rough, but I prefer to gather feedback before going further (if we decide it's worth it). Anyway, my idea is to provide some information about what is to be copied instead of just copying a staging project without giving any feedback to the user (this would be so if we used a modal for example).
Let me know what you think. Here's how it looks:
Clickable icons to reach the `Copy` page, they are displayed when we are configuring the staging workflow (so after clicking the `Configure` on the staging workflow show page):
The `Copy` page:
=> Add WebUI/API endpoints, documentation and job to copy a staging project

src/api/app/models/staging/staging_project.rb
Since we store the project config in the backend, we should only
copy this content if necessary.
Kudos to @dmarcoux for the idea
=> Only copy the project config when it has any content

dist/systemd/obsscheduler.service
In https://github.com/openSUSE/open-build-service/commit/c682bcd6dcad57b63cd3b0e1020e4349e6b35265#diff-dab5349d410c1037e0345c2a211eb284R5
we ensured that obsapisetup is started before obsscheduler.
As obsapisetup is a long running oneshot service, we`d like to ensure
that obsscheduler is starting "After=" finishing obsapisetup.
"After=" is not relevant if obsapisetup is not enabled.
Further info about Before/After:
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Before=
=> [dist] added obsapisetup to "After" of obsscheduler.service

src/api/app/controllers/staging/staging_projects_controller.rb, src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/jobs/staging_project_copy_job.rb, src/api/spec/controllers/staging/staging_projects_controller_spec.rb, src/api/spec/controllers/webui/staging/projects_controller_spec.rb, src/api/spec/jobs/staging_project_copy_job_spec.rb
Setting the current user is needed in the job as it is performed asynchronously. Therefore, we now pass the current user id to the job to use it later.
=> Fix error in StagingProjectCopyJob

src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/models/staging/workflow.rb
Issue introduced when improving the performance of the workflow
show page, which uses the same partials as the broken pages:
#6760
=> Fix missing groups and users hash on staging

src/api/app/models/event/repo_build_finished.rb
because then the build id changed.
Follow up on https://github.com/openSUSE/open-build-service/pull/6804
=> Drop cache when repository build finished

src/api/app/models/event/build.rb, src/api/app/models/obs_factory/obs_project.rb, src/api/app/models/obs_factory/staging_project.rb, src/api/app/models/staging/staging_project.rb, src/api/lib/backend/api/build_results/status.rb, src/api/lib/backend/instrumentation.rb, src/api/lib/backend/remember_location.rb, src/api/spec/lib/backend/remember_location_spec.rb
because we now started to cache in the Backend API which means when
the backend is not called but fetched from cache, we never reset the
backend location. Now we always reset it after calling the method
which also is the right location to do so.
=> Reset backend location in RememberLocation module

src/api/app/models/event/repo_build_finished.rb
because then also a unresolvable can be fixed.
Follow up on https://github.com/openSUSE/open-build-service/pull/6817
=> Drop failed_results cache when repo finished

src/api/app/models/bs_request.rb, src/api/app/models/obs_factory/staging_project.rb, src/api/app/models/project.rb, src/api/app/presenters/obs_factory/staging_project_presenter.rb, src/api/spec/models/obs_factory/staging_project_spec.rb
Take selected_requests as number array and avoid duplicated queries for stagings without
no difference between open_requests and selected_requests
We still load the requests per project, but this is hard to fix without injecting into objects
```
Before: 8461ms (Views: 1742.5ms | ActiveRecord: 3279.2ms | Backend: 3.8ms)
After:  3054ms (Views: 821.8ms  | ActiveRecord: 689.0ms | Backend: 3.6ms)
```
(the backend is of course lobotomized in the dev environment)
=> OBS_Factory: Improve database queries

src/api/app/controllers/webui2/package_controller.rb, src/api/app/models/package.rb, src/api/spec/models/package_spec.rb
We always passed to the backend the main package. Now we send the
correct package.
Should fix #6606
=> Fix Statistics for multibuild

src/api/app/views/webui2/webui/project/_project_inherited_packages.html.haml, src/api/app/views/webui2/webui/project/show.html.haml
The inherited packages were pointing to the original project and not to
the current one.
Should fix #6621
=> Fix inherited package link

src/api/app/models/event/build.rb, src/api/app/models/event/repo_build_finished.rb, src/api/app/models/event/repo_build_started.rb, src/api/app/models/event/repo_published.rb
Payload is actually a string hash not symbols, even though the payload_keys are listed as symbols. No suprise this went unnoticed :(
=> Fix payload access in clear_caches

src/api/app/assets/stylesheets/webui2/build-results.scss
=> Add background colour in buildresult for blocked state

src/api/app/views/webui2/webui/repositories/distributions.html.haml
=> Add missing images extension to distribution icons

src/api/app/helpers/flag_helper.rb, src/api/app/models/flag/validations.rb, src/api/app/models/package.rb, src/api/app/models/project.rb, src/api/spec/db/data/remove_duplicated_flags_spec.rb, src/api/spec/models/package_spec.rb, src/api/spec/models/project_spec.rb
This can happen either when posting a _meta (in this case an error could be good enough, but isn't really helpful) or when receiving _meta from local or remote backend. In this case we can't error out, but need to recover the situation
Fixes #6823
=> Filter out duplicated flags from user provided XML

CONTRIBUTING.md
Emphesize more that the backend won't run on MacOS and Windows.
=> Update Contribution guide

src/backend/bs_signer
The code reuses entries from the old bininfo files for non-rpm packages,
so the entries will be missing if the .bininfo did not exist before.
But the job handling code in the scheduler relies on the bininfo
containing all entries.
=> [backend] signer: do not write a .bininfo file if it didn't exist yet

src/api/app/views/webui2/webui/project/monitor.html.haml
We need to initialize the DataTable after the page is ready.
Fixes https://github.com/openSUSE/open-build-service/issues/6561
=> Fix monitor page pagination in Firefox

src/backend/BSPublisher/Container.pm
Oops. This should make container publishing a bit faster...
=> [backend] publisher: do not call bs_regpush twice

src/api/spec/factories/upload_job.rb
Use a number generator with higher "randomness" to avoid
cloud jobs with duplicated job_id entries.
The job_id comes from the backend. So we can not use another
factory for this.
Fixes #4958
=> Fix flickering cloud upload job

src/api/spec/support/features/features_attribute.rb
It sometimes happens that we have duplicated attributes available.
In that case we fetch the first one.
Fixes #6837
=> Fix flickering attribute test

src/api/app/views/webui2/webui/comment/_content.html.haml
This allows users to reference to comments by linking to them.
=> Add anchor tag to comments

src/api/app/assets/stylesheets/webui/application/request.scss, src/api/app/controllers/webui/request_controller.rb, src/api/app/helpers/webui/request_helper.rb, src/api/app/views/webui/request/show.html.erb, src/api/spec/controllers/webui/request_controller_spec.rb, src/api/spec/features/webui/requests_spec.rb
* Remove index from parameters. This action always processes one
review at a time. There was no need to add an index to the parameters.
* Move setting of hidden field tags to a helper to dry the code.
* Directly access parameters we need instead of looping over all of
them.
=> Partially re-write modify_review action

src/api/app/views/webui2/webui/request/_issues_table.html.haml, src/api/app/views/webui2/webui/request/show.html.haml
This is the first PR of a serie of PRs for enabling build results in the request show page, and refactor the build result section.
TODO:
- make it work with a request with multiple submits (with tabs).
- make it collapsible.
=> Enable build results in request show page, and also show the issue

src/api/app/presenters/obs_factory/staging_project_presenter.rb
In preparation for upcoming [Origin Manager](https://github.com/openSUSE/openSUSE-release-tools/issues/1643).
=> [frontend] Add origin-manager as code-fork icon in obs_factory.

src/api/app/mixins/has_attributes.rb, src/api/spec/controllers/source_attribute_controller_spec.rb
When including project attributes a package attribute request, we
caused a 500 error by calling a private method.
Fixes #6819
=> Fix rendering of project attributes in API

src/api/app/models/review.rb, src/api/spec/models/review_spec.rb
by_package always implies by_project as well - just the package name matching isn't good enough. See obs request 669918 where it was impossible to approve the sle-workerarounds reviews
CC @lnussel
=> Fix reviewable_by for by_package

src/api/spec/lib/influx_db/obs/middleware/backend_subscriber_spec.rb
Application and webui controller are both setting a request value
in the InfluxDB::Rails.current.values hash.
This was causing the test to fail randomly when run within our CI
(aka running multiple tests) because the request value got set.
=> Fix flickering backend subscriber test

src/api/app/assets/javascripts/webui2/buildresult.js, src/api/app/views/webui2/shared/_buildresult_box.html.haml
Build results box for multiple actions didn't have the needed id to identify the correct subject.
Fix #6896.
=> Fix build results for multiple actions requests

src/api/app/assets/javascripts/webui2/project_monitor.js, src/api/app/views/webui2/webui/project/_monitor_control.html.haml, src/api/app/views/webui2/webui/project/monitor.html.haml
To avoid the overflow until the DataTable with the scroll is loaded.
This is needed because loading the DataTable is slow, as it is creating two
tables and moving the content around. Another alternative could be to stop
using the scroll from DataTables and just add it to the table, but then the
package column would move as well when scrolling what makes the table unusable.
In this case, and taking into account that the page is only big (= slow) in few
cases, makes sense to prioritize ease of use over performance. The user waits a
bit, but at least he gets a nice table.
The double table that DataTable renders is also causing a bug (which disappears
when not using the scroll from DataTable). :bowtie:
=> Hide monitor table while loading it

src/api/app/controllers/webui/request_controller.rb
```check_ajax``` should be called in a before_action, since its not direct connected with the action ```sourcediff``` logic
=> Move check_ajax from sourcediff to a before_action

src/api/app/controllers/webui/kiwi/images_controller.rb, src/api/app/controllers/webui/monitor_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/repositories_controller.rb, src/api/app/controllers/webui/webui_controller.rb
Many controller actions begin with a call to "check_ajax". We move it to
a before_action instead.
=> Call check_ajax from before_action

src/api/app/views/webui2/webui/request/_decision_tab.html.haml, src/api/app/views/webui2/webui/request/show.html.haml
When porting this to the new webui I accidentally ignored
the @is_target_maintainer variable.
This adds it to the new view now, which fixes that the
forward request checkbox and accept request box is shown
for users that don't have the required permissions.
=> Only show request actions the user has permissions for

src/api/app/views/webui2/webui/request/_sourcediff_tab.html.haml
=> Use normal font-weight for diff content header

src/api/app/controllers/webui/package_controller.rb
This way, in the case of multibuild, the url for downloading the binary contains the package and the build section, as needed.
Fix #6847.
=> Pass the package name as a parameter instead of the package object

src/api/app/helpers/webui/request_helper.rb, src/api/spec/helpers/webui/request_helper_spec.rb
Also make it clearer that it's about deleting a repository.
There was a missing test case for request_action_header when
action[:type] == :delete and action[:trepo] is defined.
Fixes #6936
=> Fix undefined method 'repository_index_path' in request_action_header

src/api/app/views/webui2/webui/request/_review_tab.html.haml
The comment wasn't save because we slice the params `comment` in
`modify_review` action.
=> Fix comment in review tab

src/api/app/views/webui2/webui/package/_buildstatus.html.haml
The local variables are used outside the scope of the `if` statement in which they were defined.
Fixes #6957
=> Fix undefined local variables in package build status

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/monitor.html.haml
The page didn't use Bootstrap when the table was empty. Now it uses
Bootstrap and informs that build results are not available.
=> Set empty state for Monitor page with Bootstrap

src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml, src/api/config/routes.rb
Also make the `project` parameter required, instead of optional, in routes where it is always needed with the `set_project` before filter.
=>  Prevent errors in project routes without a project

src/api/app/models/path_element.rb, src/api/app/models/project.rb, src/api/app/models/repository.rb, src/api/spec/cassettes/Project/_restore/on_a_project_with_packages/creates_package_records_in_the_database.yml, src/api/spec/cassettes/Project/_restore/on_a_project_with_packages/verifies_the_meta_of_restored_packages/1_10_3_2_1.yml, src/api/spec/cassettes/Project/_restore/on_a_project_with_packages/verifies_the_meta_of_restored_packages/1_10_3_2_2.yml, src/api/spec/cassettes/Project/_restore/sets_the_user_that_restored_the_project_in_the_history_element.yml, src/api/spec/cassettes/Project/_restore/with_linked_repositories/project_meta_is_properly_restored.yml, src/api/spec/models/project_spec.rb
When we destroy a project we run the `before_action`
`cleanup_before_destroy`  from the project and also from the
repositories. Now when we destroy a project we skip the `before_action`
of the repositories.
Fix #3735
=> Skip before_destroy of repository when we destroy a project

src/api/Gemfile, src/api/Gemfile.lock, src/api/lib/obsapi/markdown_renderer.rb, src/api/spec/helpers/webui/markdown_helper_spec.rb
This reverts commit 82db63b71432f051ed5acf6c9d9fa3bcaec69d62.
Sadly, we're having issues in production with code blocks due to the
changes introduced in this commit. For details, please refer to this
issue: https://github.com/openSUSE/open-build-service/issues/6960
Fix #6960
=> Revert "Add colorful syntax in md code block"

src/api/app/views/webui2/webui/request/_superseded_by_message.html.haml, src/api/app/views/webui2/webui/request/show.html.haml
My only concern with this is that we are repeating the information. As you can see in the screenshot below, we now display twice that the request is superseded. It is once in the alert box and then, once in the side links of the request. I believe this is something we should address when reworking this page more in depth (instead of only migrating and fixing major issues as we agreed upon).
=> Add alert box for superseded request

src/api/spec/factories/kiwi_package.rb, src/api/spec/factories/kiwi_package_group.rb
These messages are thrown when the rspec test suite is run:
`Faker::Cat.name is deprecated; use Faker::Creature::Cat.name instead. It will be removed on or after 2019-01-01.`
=> Prevent Faker deprecation warnings from happening

src/api/app/assets/stylesheets/webui2/datatables.scss
The previous CSS only broke the names in the `-`. If a package name didn't have any (or not enough of them), it broke the table layout.
Co-authored-by: @hennevogel
=> Fix Monitor page for long package names

dist/obs-server.spec, dist/systemd/obs-api-support.target
We shouldn't be calling `obsapisetup.service` in the rpm as this is only needed in the appliance. This was causing the following error when deploying: `Failed to execute operation: No such file or directory`
Also remove duplicated `obs-clockwork.service`
Fixes #6188
Co-authored-by: @eduardoj
=>  Remove obsapisetup.service call and duplicated obs-clockwork.service

src/api/app/views/webui2/webui/project/_monitor_control.html.haml, src/api/config/routes.rb
The mandatory 'project' parameter for the project monitor page was introduced in f795712.
Routes like `/project/monitor?project=my_project` will now be redirected to `/project/monitor/my_project`, so users can keep the same monitor routes they already had, and will not get an 404 error.
Thanks to @darix for reporting it.
=> Provide compat monitor route

src/api/app/views/webui2/webui/request/show.html.haml, src/api/spec/bootstrap/features/webui/requests_spec.rb
The reviewer could still submit reviews, but it was misleading due to the wrong tab header. About the code changes, we use the same helper as the old UI.
Before:
After:
=> Fix decision box tabs header for reviews

src/api/app/assets/javascripts/webui2/project_monitor.js, src/api/app/helpers/webui/buildresult_helper.rb, src/api/app/views/webui2/webui/project/monitor.html.haml
The content of the cell is now processed and rendered by JavaScript.
This improves the performance of the DataTable initialization and it is
needed for the upcoming server-side pagination.
For example, with openSUSE:Tools (74 packages) there is a difference of
approximately 2 seconds (from ~ 5.3 to ~3.2 seconds)
There is an upcoming PR for server pagination.
=> DataTable rendering on Monitor page

src/backend/bs_srcserver
$cgi->{'meta'} already holds and the $cgi hash is not modified during
BSRevision::addrev_meta_replace.
=> Simplify condition in bs_srcserver putfile

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/collapsible_text.js, src/api/app/assets/javascripts/webui2/request.js, src/api/app/assets/stylesheets/webui2/collapsible-text.scss, src/api/app/assets/stylesheets/webui2/requests.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/views/webui2/webui/request/_request_history.html.haml, src/api/app/views/webui2/webui/request/_request_history_description.html.haml, src/api/app/views/webui2/webui/request/_request_history_element.html.haml, src/api/app/views/webui2/webui/request/_show_overview.html.haml, src/api/app/views/webui2/webui/webui/_collapsible_text.html.haml, src/api/spec/bootstrap/features/webui/requests_spec.rb
* Make collapsible text generic so we can use it elsewhere.
* Make request description collapsible.
* Update font size of collapsed text. It's was to small (much smaller than the rest of the page).
=> Make collapsible text generic and use it for request description

src/api/app/views/webui/shared/_truncated_diff_hint.html.erb
This broke when cleaning up the request webui_info hash
in 4abca1854f8d8d2a73bd353b7269c93c86c560c1.
=> Fix setting the request number in truncated_diff_hint partial

src/api/app/views/webui2/webui/request/_request_history.html.haml, src/api/app/views/webui2/webui/request/show.html.haml
Commit 0c791a7499eb4ea964ca828 removed the 'small' class from the
collapsible text so that it uses the default size. Though in the
request history tab we want to have a smaller text size to give it
less emphasize.
=> Make all of the request history "small"

src/api/app/assets/javascripts/webui2/users_groups.js, src/api/app/helpers/webui/user_or_groups_roles_helper.rb, src/api/app/mixins/webui/manage_relationships.rb, src/api/app/views/webui2/shared/user_or_groups_roles/_list.html.haml, src/api/spec/support/shared_examples/features/bootstrap_user_tab.rb
* Add group icons to user & group tab
* Add 'send mail' links to groups table
* Prevent the invisible spinner from being rendered in the DOM. This was causing the table being re-rendered every 200ms. 
Before:
After:
=> Fix minor issues and improve user tab code

src/api/app/controllers/webui/configuration_controller.rb, src/api/app/views/webui2/webui/configuration/index.html.haml, src/api/spec/controllers/webui/configuration_controller_spec.rb
We migrate the configuration page to Bootstrap.
=> Migrate configuration page to Bootstrap

src/api/app/assets/stylesheets/webui2/architectures.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/architectures_controller.rb, src/api/app/services/architectures_controller_service/architecture_updater.rb, src/api/app/views/webui2/webui/architectures/bulk_update_availability.js.erb, src/api/app/views/webui2/webui/architectures/index.html.haml, src/api/app/views/webui2/webui/architectures/update.js.erb, src/api/config/routes.rb, src/api/spec/controllers/webui/architectures_controller_spec.rb
=> Migrate and re-design architectures view for bootstrap UI

src/api/app/assets/stylesheets/webui2/flash.scss, src/api/app/assets/stylesheets/webui2/tabs-component.scss, src/api/app/assets/stylesheets/webui2/watchlist.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/views/layouts/webui2/_flash.html.haml, src/api/app/views/layouts/webui2/webui.html.haml
... and cleanup the flash partial a bit.
When the scrollbar is at the top of the page:
After scrolling down:
I increased the z-index of the flash. So all elements except the watchlist are currently in the back of the flash, when they overlap.
=> Make flash messages stick at the top of the viewpoint

src/api/app/models/bs_request.rb, src/api/app/models/review.rb, src/api/spec/models/bs_request_spec.rb
If a request contains multiple by_user reviews, they shall be accepted one after the other - but for this we need to ignore accepted reviews
=> Fix multiple reviews of the class

src/api/app/views/webui2/webui/main/_user_proceed-list.html.haml
=> Align 'Your Home' link title with href attribute

src/api/app/views/webui2/webui/architectures/index.html.haml
This is to prevent multiple clicks.
A tiny addition to #7029.
=> Toggle disabled state for buttons/checkboxes on architectures AJAX events

src/api/app/views/webui2/webui/request/show.html.haml
Instead of showing a message that 'there's nothing to be done right now'
we hide the decision box.
This prevents reviewers with open reviews from making detours by having
to click on the "reviews" tab. The request decision can still be viewed
in the request history, like it was before.
Fixes #7026
=> Hide decision box when there is nothing to do for the logged in user

src/api/app/views/webui2/webui/project/_linking_projects_dialog.html.haml, src/api/app/views/webui2/webui/project/_side_links.html.haml, src/api/app/views/webui2/webui/project/show.html.haml
The linking projects dialog hadn't been migrated to the new UI.
Fixes https://github.com/openSUSE/open-build-service/issues/6979
=> Fix linking projects in project page

src/api/app/models/user.rb, src/api/spec/factories/users.rb, src/api/spec/models/user_spec.rb
Such users are not allowed to execute any actions. So it doesn't
make sense to offer them in forms, e.g. adding them as maintainer.
Fixes #7022
=> Hide deleted and locked users in autocomplete search

src/api/app/controllers/webui/users/subscriptions_controller.rb, src/api/app/views/webui2/webui/subscriptions/_subscriptions_form.html.haml, src/api/app/views/webui2/webui/users/subscriptions/index.html.haml
=> Update Bootstrap styling for user notifications

src/api/app/views/webui2/webui/subscriptions/index.html.haml
Also set disable_with for UJS
Before:
After:
=> Use correct style for Notifications button

src/api/app/models/obs_factory/staging_project.rb, src/api/app/models/staging/staging_project.rb, src/api/spec/cassettes/Staging_StagingProject/_overall_state/with_disabled_repository/1_3_10_1.yml, src/api/spec/cassettes/Staging_StagingProject/_overall_state/with_disabled_repository/1_3_10_2.yml, src/api/spec/models/obs_factory/staging_project_spec.rb, src/api/spec/models/staging/staging_project_spec.rb
When osc crashes while selecting, sometimes we don't reenable the staging project and then it becomes acceptable - which is an error.
We discussed this in the release manager round and there is no valid use case of having disabled repositories *and* wanting it to be acceptable. Mapping this to 'building' is obviously a little fake, but unacceptable sounds too harsh too. So in building stagings the RM will look from time to time to see what's taking so long and she would notice then.
=> Don't let disabled projects/repos pass stagings as acceptable

src/api/app/controllers/webui/project_controller.rb
In the new UI we used the @linking_projects variable instead of calling the controller again. For more details check: https://github.com/openSUSE/open-build-service/pull/7071
=> Add a bento_only for project#linking_projects

src/api/app/controllers/webui/user_controller.rb, src/api/app/views/layouts/webui2/_personal_navigation.html.haml, src/api/app/views/webui2/shared/_sign_up.html.haml, src/api/app/views/webui2/webui/main/index.html.haml, src/api/app/views/webui2/webui/user/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/user/index.html.haml, src/api/app/views/webui2/webui/user/register_user.html.haml, src/api/app/views/webui2/webui/user/signup.html.haml, src/api/config/routes.rb
We are migrating the configuration section to bootstrap. The
manage user page belongs to this area and includes the user creation.
=> Migrate user creation page to bootstrap

src/backend/bs_repserver
Removing it can make the dispatcher abort jobs with "no compliant
workers found". Instead, move the worker data to "down" for
a short amount of time. This is not optimal, but introducing a new
"resting" state seems a bit overkill...
=> [backend] do not simply remove the worker building data

src/api/app/views/webui2/webui/user/index.html.haml
The user actions dropdown got replaced with linked icons like we
usually do in the new UI.
Some of the actions, like confirming and locking users, got removed
since this is already covered by the user edit page which is linked
from within in this table.
=> Migrate user configuration view to bootstrap

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/packages/build_reason_controller.rb, src/api/app/controllers/webui/packages/job_history_controller.rb, src/api/app/controllers/webui/projects/project_configuration_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/spec/controllers/webui/projects/project_configuration_controller_spec.rb
In 4a505f1b34f37350159b782563eacbc4fd0700a1 the "nextstatus"
code was replaced by raising an exception which is handled by OBS
and causes a 404 view to be rendered.
But since ActionController::RoutingError exceptions also indicate
a bug in OBS we also notify errbit, our exception tracker, about
such errors.
This was causing our exception tracker to be spammed.
Instead we now send ActiveRecord::RecordNotFound exceptions, which
renders a 404 without notifying errbit.
Fixes #7080
=> Use correct exception when a record can not be found

src/api/app/models/event/build.rb, src/api/app/models/event/repo_build_finished.rb, src/api/lib/backend/api/build_results/status.rb, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_index/requesting_json/responds_with_a_json_representation_of_the_staging_project.yml
We have too many edge cases where the caches can't be
deleted, so we're stuck with invalid data. A more generic
solution is WIP, but until then:
Fixes #6959
=> Remove caching of failed repositories

src/api/app/models/obs_factory/staging_project.rb, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/with_checks/published_repo_has_failed_check/with_disabled_project/behaves_like_disabled_checks/returns_testing.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/with_checks/published_repo_has_failed_check/with_disabled_project/returns_testing.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/with_checks/published_repo_has_failed_check/with_disabled_repository/behaves_like_disabled_checks/returns_testing.yml, src/api/spec/cassettes/Webui_ObsFactory_StagingProjectsController/GET_show/with_a_existent_factory_staging_project/with_checks/published_repo_has_failed_check/with_disabled_repository/returns_testing.yml, src/api/spec/controllers/webui/obs_factory/staging_projects_controller_spec.rb, src/api/spec/models/obs_factory/staging_project_spec.rb
Staging projects have more disabled repositories than I thought, we forgot about the bootstrap_copy repository, which led to all staging projects in Factory being 'building' after my last change was deployed.
Now reverting this in parts and leaving the build_state unaffected, but forcing all checks of disabled repositories to 'pending' as such forcing the staging project to 'testing'
=> Fix regression with my previous staging attempt

src/api/app/views/webui2/webui/users/tasks/index.html.haml
Our webui2 layout already wraps a container around the main view
content. This caused the shown content to be more narrow than on
other pages.
Before:
After:
=> Remove duplicated container from user tasks view

src/api/app/assets/stylesheets/webui/application/announcements.scss, src/api/app/assets/stylesheets/webui2/flash.scss, src/api/app/controllers/webui/announcements_controller.rb, src/api/app/controllers/webui/users/announcements_controller.rb, src/api/app/views/layouts/webui2/_announcement.html.haml, src/api/app/views/layouts/webui2/webui.html.haml, src/api/app/views/webui2/webui/announcements/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/announcements/show.html.haml, src/api/app/views/webui2/webui/users/announcements/create.js.haml
Migrates both announcement show page and flash/banner, which is shown
before any other flash.
Shows text and button in the same line.
**Banner before:**
**Banner after:**
**Show view before:**
**Show view after:**
=> Migrate announcement to Bootstrap

src/api/app/views/webui2/webui/request/_request_history.html.haml, src/api/app/views/webui2/webui/request/_request_history_element.html.haml, src/api/app/views/webui2/webui/request/_show_overview.html.haml, src/api/app/views/webui2/webui/webui/_collapsible_text.html.haml
Using only the text length was making the collapsible to inflexible.
This was causing the request description box being collapsed in many
cases where it didn't have to.
By also considering the number of newlines this becomes more flexible.
Part of #7056
=> Consider newlines for collapsible partial

src/api/app/views/webui2/webui/groups/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/groups/edit.html.haml, src/api/app/views/webui2/webui/groups/index.html.haml, src/api/app/views/webui2/webui/groups/new.html.haml, src/api/app/views/webui2/webui/user/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/user/edit.html.haml, src/api/app/views/webui2/webui/user/index.html.haml, src/api/app/views/webui2/webui/user/register_user.html.haml, src/api/app/views/webui2/webui/user/show.html.haml, src/api/app/views/webui2/webui/user/signup.html.haml
To compare the two options regarding the new/edit views, the Groups views have tabs and the Users views don't. I prefer with tabs, but I want your opinion on this. Once we decide, I will do it for both sets of pages. We still have one issue to fix for tabs as the `Manage Groups/Users` is not active when we are on the new/edit views.
Refer to the commits for details on what changed exactly. It's already written there.
Links for review:
- http://obs-reviewlab.opensuse.org/dmarcoux-consistent-manage-groups-users/groups
- http://obs-reviewlab.opensuse.org/dmarcoux-consistent-manage-groups-users/group/new
- http://obs-reviewlab.opensuse.org/dmarcoux-consistent-manage-groups-users/group/edit/review-team
- http://obs-reviewlab.opensuse.org/dmarcoux-consistent-manage-groups-users/users
- …
=> Be consistent in Manage Groups/Users views

src/api/app/jobs/full_text_index_job.rb
From time to time, ThinkingSphinx aborts keeping the guard file there
making impossible to rebuild the index. We want to have the exception on errbit to be able to track this issue
=> Raise exception if TS guard file exists while running FullTextIndexJob

src/api/app/controllers/status/required_checks_controller.rb, src/api/app/helpers/status/required_checks_helper.rb, src/api/app/policies/repository_architecture_policy.rb, src/api/config/routes.rb, src/api/spec/controllers/status/required_checks_controller_spec.rb
The model allowed this for a while and the staging dashboard also supported it, but as the Status API sprint never continued this was never implemented - but as it blocks my work on repository checks, henne and me decided to put a bandaid in place
=> Allow to modify required_checks for RepositoryArchitecture

src/api/app/assets/javascripts/webui2/project_monitor.js, src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/_monitor_control.html.haml, src/api/app/views/webui2/webui/project/monitor.html.haml
The complete page is refreshed when applying filters, so this explains
the solution.
Fixes #6883
=> Remember number of shown entries for project monitor datatable

src/backend/BSSrcServer/Signkey.pm
The shore ones are deprecated because they are not secure enough.
=> [backend] use long gpg keyids instead of the short ones

src/api/app/assets/javascripts/webui2/buildresult.js, src/api/app/assets/javascripts/webui2/popover.js, src/api/app/assets/javascripts/webui2/project_monitor.js, src/api/app/assets/javascripts/webui2/repositories.js
Refactor initialization of popovers to remove duplication and align
behavior of all popovers. In a group of popovers, which is initialized
with a CSS selector, only one popover at a time can be shown. All shown
popovers are removed when a popover group is initialized.
Ignore JSHint errors regarding 'initializePopovers' is not defined.
Fixes #6950
Links for review:
- Build Results: https://obs-reviewlab.opensuse.org/dmarcoux-issue-6950/project/show/home:Admin
- Project Repositories (all flags: https://obs-reviewlab.opensuse.org/dmarcoux-issue-6950/repositories/home:Admin
- Project Monitor: https://obs-reviewlab.opensuse.org/dmarcoux-issue-6950/project/monitor/home:Admin
=> Align behavior of popovers throughout all views

dist/obs-server.spec
`restart_on_update` called `systemctl try-restart`, while
`service_del_postun -r` calls `systemctl force-reload`,
that is what it is expected to be done on each update of
the `obs-api` package.
Thanks to @bugfinder for providing the solution.
=> Reload apache instead of restarting it

src/api/app/assets/javascripts/webui2/collapsible_text.js
In the request show page, the history elements which a long description used to collapse when selecting the text. The user needed most likely to open it again.
Fixes https://github.com/openSUSE/open-build-service/issues/6994
=> Do not collapse request history when selecting

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/interconnect.js, src/api/app/controllers/webui/interconnects_controller.rb, src/api/app/controllers/webui2/interconnects_controller.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui/interconnects/new.html.haml, src/api/app/views/webui2/webui/interconnects/_interconnect_button.html.haml, src/api/app/views/webui2/webui/interconnects/_interconnect_modal.html.haml, src/api/app/views/webui2/webui/interconnects/_tabs.html.haml, src/api/app/views/webui2/webui/interconnects/create.js.haml, src/api/app/views/webui2/webui/interconnects/new.html.haml, src/api/config/routes.rb, src/api/spec/bootstrap/features/webui/interconnects_spec.rb, src/api/spec/bootstrap/features/webui/repositories_spec.rb, src/api/spec/cassettes/Interconnects/creating_custom_interconnect.yml, src/api/spec/controllers/webui/interconnects_controller_spec.rb
Like the other pages, we also migrate the interconnect page to bootstrap.
=> Migrate interconnect to Bootstrap

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/patchinfo_controller.rb, src/api/app/views/layouts/webui2/webui.html.haml, src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/package/add_file.html.haml, src/api/app/views/webui2/webui/package/show.html.haml, src/api/app/views/webui2/webui/package/view_file.html.haml, src/api/app/views/webui2/webui/project/show.html.haml, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/spec/controllers/webui/patchinfo_controller_spec.rb
Shorten long package names.
Fixes #6436
Before:
After
=> Truncate long package names

src/api/app/views/webui2/webui/project/bottom_actions/_patchinfo.html.haml
We switched to use the secondary color for such links. Seems we
forgot this one.
=> Fix icon color of 'Show Patchinfo' link

src/api/app/helpers/webui/request_helper.rb, src/api/app/models/review.rb, src/api/app/views/webui/request/show.html.erb, src/api/app/views/webui2/webui/request/_review_tab.html.haml, src/api/app/views/webui2/webui/request/show.html.haml, src/api/spec/bootstrap/features/webui/requests_spec.rb, src/api/spec/helpers/webui/request_helper_spec.rb
Reviewers need this information to know what is expected from them, aka
why a review was assigned to them.
Fixes #7088
Old UI:
New UI:
=> Show reason and requestor of review requests in the review request field

src/api/app/views/webui2/webui/package/_deps.html.haml
We already fetch this data as part of the package_file variable. So
rendering it here won't cause any performance regression.
And since this data belongs to the package details it makes sense to
include this here.
Fixes #6443
On larger screens:
On smaller screens:
=> Show recommends in package binary page

src/api/app/models/event/comment_event.rb
With 394769ab1230020cd59c743a970a03ba07a2ce38 we changed the
format of the event payload. While we migrated all comment events
that were relying on them, we overlooked that the rss notifications
create temporary events based on their own event_payload.
Until we migrate them we need to add this workaround to prevent
exceptions when RSS Feeds that contain comment events are requested.
=> Add workaround for rss notication events

src/backend/BSSched/BuildJob/Aggregate.pm
The old code did not work if the added tag contained a '/'.
Also changed the code to not duplicate tags anymore.
=> [backend] fix regexp in aggregate-container-add-tag handling

src/api/app/controllers/webui/project_controller.rb, src/api/app/mixins/webui/manage_relationships.rb, src/api/spec/cassettes/Projects/creating_packages_in_projects_not_owned_by_user_eg_global_namespace/as_non-admin_user.yml, src/api/spec/controllers/webui/project_controller_spec.rb, src/api/spec/features/webui/projects_spec.rb
Additionally turn the after_action around and maintain a whitelist instead of a blacklist. This requires new methods authorized by default.
new_package and it's dialog are just informal authorizations, so people do not even try to do this.
=> Authorize move_path

src/api/app/helpers/webui/request_helper.rb, src/api/app/views/webui2/webui/request/_maintainer_link.html.haml, src/api/app/views/webui2/webui/request/_show_package_maintainers.html.haml, src/api/app/views/webui2/webui/request/_show_side_links.html.haml
Allows viewing a request's maintainers without having to open a modal. When more than three maintainers exist, a link to the modal is shown.
In the modal view, links to maintainer's profiles are provided. User icons were added, consistent with the old UI layout.
Fixes #7086
=> Drop "show who" for maintainers in request page

src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml
`@package` is not a Package, but a String when accessing the
live_build_log action for a multibuild package.
https://github.com/openSUSE/open-build-service/blob/93ac2948b9eccc8a9756d2c87329bb229f758beb/src/api/app/controllers/webui/package_controller.rb#L1137-L1138
Fixes #7133
=> Handle multibuild packages in breadcrumbs

src/api/app/helpers/webui/request_helper.rb, src/api/app/models/review.rb, src/api/app/views/webui/request/show.html.erb, src/api/app/views/webui2/webui/request/_review_tab.html.haml, src/api/spec/bootstrap/features/webui/requests_spec.rb, src/api/spec/features/webui/requests_spec.rb, src/api/spec/helpers/webui/request_helper_spec.rb
Reviews added by users have a creator and a reason - reviews added by project/package 'reviewer' role do not. So don't try to show users if there are none.
This reverts quite big parts of #7128 because you don't need an extra function to check the review reason - it's in the model. Unfortunately we're not using the review model, but a hash from it
Fixes #7164
=> Don't crash on default reviews

src/api/app/datatables/user_configuration_datatable.rb, src/api/app/helpers/webui/user_helper.rb, src/api/app/views/webui2/webui/request/_review_tab.html.haml
`user_name_with_icon` was introduced in f246132 when we should have instead used `user_with_realname_and_icon` since they both achieve the same result.
They really do the same thing...
=> Replace user_name_with_icon by user_with_realname_and_icon

src/api/spec/controllers/staging/excluded_requests_controller_spec.rb
Before it was only checked that an empty list was returned when there
weren't any exclusions. Now it is checked that with one exclusion a list
of one element is returned.
Ending work started in #7167.
=> Fix "index" action tests for excluded requests

src/api/app/controllers/webui/webui_controller.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/comment.rb, src/api/app/models/user.rb
There are way too many places requiring a user object but have to treat User.current being nil as a special case.
User.current_or_nobody always returns a user object and as such you can writer simpler code. I only changed examples though to validate the idea (including an alternative fix for #5351)
=> Introduce User.current_or_nobody

src/api/app/controllers/webui/repositories_controller.rb, src/api/app/policies/flag_policy.rb
To keep inline with the api ```SourceController#project_command_set_flag```
just allow admin users to create flags _sourceaccess_ and _access_ (boo#1125782)
=> Just admins are allowed to run Repositories#create_flag

src/backend/bs_publish
The packtrack sending code clears it, so we need to fetch it
again.
=> [backend] bs_publish: re-fetch repoinfo before updating the state

src/api/spec/features/webui/projects_spec.rb, src/api/spec/features/webui/requests_spec.rb
We had fun trying to replicate the error condition, but it's basically that selenium looks for the 'Accept' button and before it can click it, autocomplete moves the button down by adding a '1 result available' text box into the layout. As such actually awaiting it, avoids suprises and makes the test stable
Fixes #6238
Co-authored-by: @Ana06
=> Await autocomplete on review users

src/api/spec/controllers/webui/monitor_controller_spec.rb, src/api/spec/factories/status_history.rb
If the hour switches between creating the test data and querying it (as it happens every 60 minutes, imagine!), the test may skip one data point. So creating it 8000 hours ago and checking 8100 hours should give us some head room for slow hardware
Fixes #7200
=> Stop mixing years and hours in monitor tests

src/api/spec/factories/kiwi_image.rb, src/api/spec/factories/users.rb
Avoids last names containing ' - which breaks some tests
Fixes #7196
=> Just use first names for users

src/api/app/models/package.rb, src/api/app/views/webui2/webui/package/_commit_item.html.haml
This can happen if we pass a disturl of a linked source where there wasn't actually a commit with this revision (but inherited e.g. from Factory).
Support disturl links in package#show :bowtie: 
Co-authored-by: @Ana06
=> Fix #7079:  Catch revision not found in _history

docs/api/api/api.txt, docs/api/api/create_staging_workflow.xml, src/api/app/controllers/staging/excluded_requests_controller.rb, src/api/app/controllers/staging/staging_projects_controller.rb, src/api/app/controllers/staging/workflows_controller.rb, src/api/config/routes.rb, src/api/spec/controllers/staging/excluded_requests_controller_spec.rb, src/api/spec/controllers/staging/staged_requests_controller_spec.rb, src/api/spec/controllers/staging/staging_projects_controller_spec.rb, src/api/spec/controllers/staging/workflows_controller_spec.rb, src/api/test/functional/backend_test.rb
- Add API to create Staging Workflows, which was only possible to do in the WebUI before. :bowtie: 
- Refactor routes to simplify their definition the routes file and follow Rails defaults.
=>  Add API to create Staging Workflows & refactor staging routes

src/api/app/views/webui2/webui/package/_deps.html.haml
Otherwise they are hard to read when packages are
overflowing to the next line.
Before:
After:
=> Use a list for package binaries in binary view

src/api/app/views/webui/project/new_package.html.erb, src/api/app/views/webui2/webui/project/_create_package_modal.html.haml, src/api/app/views/webui2/webui/project/show.html.haml, src/api/spec/bootstrap/features/webui/projects_spec.rb, src/api/spec/features/webui/projects_spec.rb
A small thing which I noticed... It's a bit redundant to have `New` in the modal's title.
=> Remove unneeded word and align filename to modal context

src/api/app/views/webui2/webui/request/show.html.haml
This got lost when we cleaned up instance variables in the
request controller 4abca1854f8d8d2a73bd353b7269c93c86c5.
Fixes #7159
=> Show request id in browser title

src/api/app/views/webui2/webui/project/_tabs.html.haml
The tab Staging is shown when we are in any kind on project unless
the project is already a staging project.
The tab also keeps showing while we are moving through the staging
workflow: creating a staging workflow, showing it, copying staging
projects or showing staging projects inside the workflow.
=> Show staging workflow tab in project tablist

src/api/app/views/webui2/webui/staging/projects/preview_copy.html.haml
In OBS, primary buttons are on the right.
=> Swap buttons for copying staging projects

docs/api/api/staging_projects.xml
This resulted in an [error](https://build.opensuse.org/apidocs/staging_projects.xml).
=> Fix incorrect xml result example file in apidocs

src/api/app/views/webui2/webui/request/show.html.haml
When there is no decision box for the request (the user can not
accept or decline it) we have to mark the first review as
active (= visible).
Since we did not consider the index of the review list, all reviews
were visible when no the request decision box is hidden.
Fixes #7229
=> Fix active review tabs when there is no decision box

src/api/app/controllers/webui/repositories_controller.rb, src/api/app/policies/flag_policy.rb
Webui::RepositoriesController.create_flag allowed creating the access/sourceaccess flags, while in
SourceController#project_command_set_flag this is only allowed for admins.
This was fixed in master in: https://github.com/openSUSE/open-build-service/pull/7169/commits/5f89387c86be9bcefffe64e78125efa88e3c3c4f
=> Only allow admins to create sourceaccess/access repositories flags

src/api/app/views/webui2/webui/groups/_breadcrumb_items.html.haml
Like for the other breadcrumbs we now show a 'Groups' label
for non-admins.
Users with admin rights will see a 'Manage Groups' label which links
to the groups index.
Before:
After:
For non admin users:
For admins
=> Update breadcrumb for group show page

src/api/app/views/webui2/webui/request/_decision_tab.html.haml, src/api/app/views/webui2/webui/request/_review_tab.html.haml
In OBS, primary buttons are on the right and since accepting
a request or review is the default action it makes sense to place
it on the right.
=> Swap accept review / request buttons on request show page

src/backend/bs_publish
Vagrant supports versioned boxes since version 1.5.
Create the needed metadata to make this work.
=> [backend] add support for "vagrant" repository metadata

src/api/app/models/updateinfo.rb
The table is dropped since 2014 in UpdateinfoTrackingSecondAttempt
=> Drop unused UpdateInfo

Dockerfile
This isn't needed anymore as it produces the following error:
```
ln: failed to create symbolic link '/usr/bin/foreman': File exists
```
=> Remove symlink to foreman in Dockerfile

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui2/webui/request/_decision_tab.html.haml, src/api/spec/controllers/webui/request_controller_spec.rb
* Show green background for flash message that show success.
* Enable the forward request checkbox by default
* Make the whole 'request $nr' string clickable instead of just '$nr', for example in "... and forwarded to home:Admin (request 7)"
=> Fix some issues around the request show page for the new UI

src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/views/webui2/webui/staging/workflows/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/staging/workflows/_create_staging_project.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_project.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_projects_table.html.haml, src/api/app/views/webui2/webui/staging/workflows/edit.html.haml, src/api/app/views/webui2/webui/staging/workflows/show.html.haml
This PR supersedes #7276, because I had some troubles trying to fetch it due to its branch name.
It addresses the feedback regarding the name length. Now, long strings will be broken in many lines.
It also adds an explanatory text on the creation modal "If the project already exists, it will simply be assigned to the Staging". 
@vpereira @coolo @bgeuken  could you please have another look?
=> Address feedback: Staging Workflow Configure UX

CONTRIBUTING.md
Following a discussion with srinidhi/@srinidhibs on IRC, I realized that we didn't document this and not fulfilling this requirement causes issues when trying to run feature specs.
=> Document minimal docker-compose version needed

src/api/app/controllers/staging/staged_requests_controller.rb
Make sure that no nil body is passed to Xmlhash.parse
We assume in a lot of places that Xmlhash.parse(nil) won't throw an exception, but it will..
=> Avoid assuming that Xmlhash.parse can work with nil

src/api/app/views/webui2/webui/project/_tabs.html.haml
Clicking on some of the sub tabs of a maintenance project, like 'meta',
was causing an exception. This happened because we generated urls for
maintenance sub tabs without the necessary parameters.
Fixed #7325
=> Fix rendering of project tabs for maintenance projects

src/api/db/seeds.rb
Performing backend actions during db:seed is problematic as the backend is not part of the docker network.
We update the configuration later - which will trigger a background job to write it once the full stack is up
Fixes #7303
=> Disable backend callbacks while creating seeds

src/api/app/views/webui2/shared/user_or_groups_roles/_index.html.haml
This insures that only the visible link text and icon is clickable.
Before all of the whitespace that followed the link was clickable.
=> Fix clickable area of links on project user tab

src/api/app/views/webui2/webui/staging/excluded_requests/index.html.haml
How the views look like with/without permissions
I'm not sure if it's better to show a disabled link (to make the user aware that this option exists) or hide it (simplifying the view to the user). Independently I just followed the approach being done until now: 
"Hide options from the user if he/she has no rights to execute it"
=> Add Policy validation to Add/Remove actions before show create/destroy

src/api/app/services/meta_controller_service/meta_validator.rb
When adding a maintenance project that does not exist, saving the
meta would cause a broken UI because we were not catching the
Project::Errors::UnknownObjectError exception.
=> Catch exception in meta validator

dist/obs-server.spec
%{fillup_and_insserv} clobbers $*, so move it last
=> [dist] fix %post -n obs-common

dist/obs-bundled-gems.spec, src/api/Gemfile.lock
We used a very outdated version that e.g. causes the crash in the rubocop update, so I updated the obs package - but this needs to be aligned with Gemfile.lock (it's soon part of the containers)
=> Update bundler version

dist/openQA_mail_notification.rb, src/api/app/controllers/cloud/upload_jobs_controller.rb, src/api/app/controllers/source_controller.rb, src/api/app/controllers/source_project_controller.rb, src/api/app/controllers/webui/cloud/upload_jobs_controller.rb, src/api/app/controllers/webui/download_on_demand_controller.rb, src/api/app/models/cloud/backend/upload_job.rb, src/api/app/models/group.rb, src/api/app/models/project/remote_url.rb, src/api/app/services/meta_controller_service/meta_xml_validator.rb, src/api/lib/authenticator.rb, src/api/lib/opensuse/validator.rb, src/api/lib/tasks/delayed_job.rake
This is a new default rubocop introduced with 0.67.2 and I agree with it
You can find details at https://rubocop.readthedocs.io/en/latest/cops_naming/#namingrescuedexceptionsvariablename
Please vote @openSUSE/obs-frontend
=> Rename exeption objects to e

src/api/app/assets/javascripts/webui/application/patchinfo.js.erb, src/api/app/controllers/webui/patchinfo_controller.rb, src/api/app/models/patchinfo.rb, src/api/app/views/webui/patchinfo/_form.html.haml, src/api/app/views/webui/patchinfo/new_patchinfo.html.haml, src/api/app/views/webui/patchinfo/show.html.haml, src/api/spec/controllers/webui/patchinfo_controller_spec.rb, src/api/spec/features/webui/maintenance_workflow_spec.rb, src/api/spec/features/webui/patchinfo_spec.rb
Refactor Patchinfo controller and consequently model, views, javascript and specs.
- Moves patchinfo's XML handling to the model.
- Instantiates patchinfo object instead of using instance variables.
- Refactors update action mainly.
- Adapt webui views and javascript.
- Validates attributes in the model in the rails way.
- Simplifies part of the code.
=> Patchinfo refactor

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/package/_deps.html.haml, src/api/app/views/webui2/webui/package/_fileinfo.html.haml, src/api/app/views/webui2/webui/package/binary.html.haml, src/api/app/views/webui2/webui/package/dependency.html.haml, src/api/config/routes.rb
Inside the details of a binary we find some links in the 'Required by' or 'Provided by' columns. The views to which those links point weren't migrated to Bootstrap.
The migrated view had a lot in common with the binary view, so part of the code has been moved to a partial. It also includes some refactoring in HTML and CSS.
Fixes: #7319
**Before:**
**After:**
=> Migrate Package#dependency view to Bootstrap

src/api/app/views/webui2/webui/package/show.html.haml
The URL next to the title made that line too "overloaded".
Fixes: #7365
**Before:**
**After:**
=> Show the package's URL under the title

src/api/app/models/bs_request/find_for/group.rb, src/api/app/models/bs_request/find_for/user.rb, src/api/app/models/bs_request/find_for/user_group_mixin.rb, src/api/app/models/group.rb, src/api/app/views/webui2/webui/groups/show.html.haml, src/api/db/migrate/20190412130831_add_state_group_index_to_reviews.rb, src/api/db/structure.sql, src/api/spec/models/bs_request/find_for/user_spec.rb
The following call done in the group#show page is extremely slow (> 20 seconds):
```
BsRequest::FindFor::Group.new(params).all
```
because of the complex query that it generates. Refactor how the query is generated, writing in the Rail way improving the performance.
We now use the UNION feature of mysql, which allows to avoid the bottleneck of OR avoiding indices. The UNION joins 2 SELECT calls that are technically a OR of a join, but simplifies the way the query optimizer can use indices.
The same applies to FindFor::User, but this code is only used when calling the API with /request?view=collection&user=X.
benchmarks (on production clone of January, just counting the rails time without javascript):
wicked-maintainers:  7077ms -> 312ms
opensuse-review-team: 834ms -> 552ms …
=> Fix performance of group#show 

src/api/app/views/webui2/webui/package/_fileinfo.html.haml
When we access the value, e.g. fileinfo.value(:summary), the argument is
first converted to string (.to_s), so using strings instead of symbols
makes it a little faster.
Related to https://github.com/openSUSE/open-build-service/pull/7417#pullrequestreview-227374850
=> Replace symbols by strings to get fileinfo values

src/api/app/datatables/package_datatable.rb, src/api/app/datatables/project_datatable.rb, src/api/app/datatables/user_configuration_datatable.rb
- Do not filter by timestamp and boolean using like condition
- Remove `cond: :like` as it is the default
=> Improvements in datatables filtering

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/flash.js, src/api/app/assets/stylesheets/webui2/flash.scss
When scrolling, the flash and announcement boxes get stuck on the top and without space between each other.
Fixes: #7216
=> Effect on flash and announcement when scrolling

src/api/app/controllers/webui/request_controller.rb
Render success flag only if there is not an error flag.
Fixes https://github.com/openSUSE/open-build-service/issues/7263
=> Fix flags in RequestController#modify_review

src/api/app/assets/stylesheets/webui2/bootstrap-modal.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss
Avoid flash to move to the right side when a modal is open.
**Before:**
**After:**
Fix #7298
=> Fix flash movement when a modal is open

src/api/app/assets/javascripts/webui2/autocomplete.js, src/api/app/assets/javascripts/webui2/request.js, src/api/app/views/webui2/webui/groups/new.html.haml, src/api/app/views/webui2/webui/request/_add_reviewer_dialog.html.haml, src/api/config/routes.rb
It used the old version of autocomplete. We got rid of many JavaScript
code. Some fields are hidden depending on the review type, we have to
make them "not required" to be able to send the form.
**Before:**
**After:**
Fixes: #7185
=> Add autocomplete for request add reviewer modal

dist/t/spec/features/0020_interconnect_spec.rb
We recently updated the views which caused some failures in our
appliances tests. This fixes them.
=> Fix appliance test: interconnect spec

src/api/app/assets/javascripts/webui2/datatables.js, src/api/app/assets/javascripts/webui2/requests_table.js.erb, src/api/app/views/shared/_involved_users.html.haml, src/api/app/views/webui2/shared/_patchinfos_table.html.haml, src/api/app/views/webui2/webui/project/status.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_projects_table.html.haml
The pagination count will be store in local storage for 2 days.
=> Store the pagination count of DataTables that we use in bootstrap

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/patchinfo.js, src/api/app/controllers/webui/patchinfo_controller.rb, src/api/app/models/patchinfo.rb, src/api/app/views/webui/patchinfo/_form.html.haml, src/api/app/views/webui/patchinfo/edit.html.haml, src/api/app/views/webui2/webui/_autocomplete.html.haml, src/api/app/views/webui2/webui/package/_tabs.html.haml, src/api/app/views/webui2/webui/patchinfo/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/patchinfo/edit.html.haml, src/api/app/views/webui2/webui/patchinfo/form/_binaries.html.haml, src/api/app/views/webui2/webui/patchinfo/form/_block_release.html.haml, src/api/app/views/webui2/webui/patchinfo/form/_issues.html.haml, src/api/app/views/webui2/webui/patchinfo/form/_required_actions.html.haml, src/api/app/views/webui2/webui/patchinfo/show.html.haml, src/api/spec/bootstrap/features/webui/maintenance_workflow_spec.rb, src/api/spec/features/webui/maintenance_workflow_spec.rb, src/api/spec/features/webui/patchinfo_spec.rb
Improved UX:
- It is clear which fields are required and what is the minimal length
- The packager field is providing user auto-completion (which is now clearly marked as required across the Bootstrap UI, not only in patchinfo)
- Clarify help messages
- Buttons in the binaries section have a title to indicate what they do (in case someone isn't sure / doesn't know)
Screenshots:
Autocomplete changes for all Bootstrap views (as explained above)
Patchinfo - Bento (to compare)
Patchinfo - Bootstrap
=> Migrate patchinfo#edit to Bootstrap

src/api/app/views/webui2/shared/user_or_groups_roles/_add_group_dialog.html.haml, src/api/app/views/webui2/shared/user_or_groups_roles/_add_user_dialog.html.haml, src/api/app/views/webui2/webui/groups/_add_group_user_modal.html.haml, src/api/app/views/webui2/webui/repositories/_add_repository_from_project_modal.html.haml, src/api/app/views/webui2/webui/repositories/_add_repository_path_modal.html.haml, src/api/app/views/webui2/webui/staging/workflows/_create_staging_project.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_managers_group.html.haml, src/api/app/views/webui2/webui/staging/workflows/new.html.haml, src/api/config/routes.rb
Now all the autocomplete routes look like "autocomplete_*", we use the
same pattern for all of them.
=> Unify route names on the autocomplete partial calls

dist/t/spec/features/0020_interconnect_spec.rb
Follow up of 01528e4e3aad8aa7625a8ddfb9df067af946c720. The change of the
flash message was so small that I've overlooked it:/
=> Fix appliance test: interconnect spec, part II

src/api/app/controllers/webui/download_on_demand_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/spec/controllers/webui/package_controller_spec.rb
This will catch Backend::Error and Timeout::Error exeptions and
redirect users the previous page. The execption will be send to errbit.
Many of the webui controllers call store without worrying about
possible exceptions that could be raised. This change makes sure
that we have a generic solution for this.
=> Catch unhandled backend errors and show a proper error message in the UI

src/api/app/assets/stylesheets/webui2/comments.scss
=> Fix comment box for long phrases without whitespaces

src/api/app/datatables/maintenance_incident_datatable.rb, src/api/app/helpers/webui/maintenance_incident_helper.rb, src/api/app/views/webui2/webui/projects/maintenance_incidents/index.html.haml
* Merge release targets and build result column
* Make release target project linkable
* Add request creation time next to request flags
Before:
https://build.opensuse.org/projects/openSUSE:Maintenance/maintenance_incidents
After:
=> Update maintenance incidents table

src/api/lib/obsapi/markdown_renderer.rb, src/api/spec/helpers/webui/markdown_helper_spec.rb
When we had "@user1 @user2" it didn't detect the second mention. Only if there were another character between them like in "@user1, @user2".
**Before:**
**After:**
Fixes: #7463
=> Markdown now detects two consecutive mentions to users

src/api/app/helpers/webui/maintenance_incident_helper.rb
Some of the patchinfos in build.o.o have an empty summary.
In such a case the incident summary would look like '6005: {}'.
This patch ensures that we only show the summary when it's not empty.
=> Fix incident summary on index view

src/api/app/assets/javascripts/webui2/request.js, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui2/package_controller.rb, src/api/app/views/webui2/shared/user_or_groups_roles/_add_group_dialog.html.haml, src/api/app/views/webui2/shared/user_or_groups_roles/_add_user_dialog.html.haml, src/api/app/views/webui2/webui/_autocomplete.html.haml, src/api/app/views/webui2/webui/groups/_add_group_user_modal.html.haml, src/api/app/views/webui2/webui/package/_submit_request_dialog.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_submit_package.html.haml, src/api/app/views/webui2/webui/package/show.html.haml, src/api/app/views/webui2/webui/package/submit_request_dialog.js.haml, src/api/app/views/webui2/webui/patchinfo/edit.html.haml, src/api/app/views/webui2/webui/project/_new_package_branch_modal.html.haml, src/api/app/views/webui2/webui/repositories/_add_repository_from_project_modal.html.haml, src/api/app/views/webui2/webui/repositories/_add_repository_path_modal.html.haml, src/api/app/views/webui2/webui/request/_add_reviewer_dialog.html.haml, src/api/app/views/webui2/webui/request/_change_devel_request_dialog.html.haml, src/api/app/views/webui2/webui/staging/workflows/_create_staging_project.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_managers_group.html.haml, src/api/app/views/webui2/webui/staging/workflows/new.html.haml
While submitting a package on OBS, I realized that the submit package modal and its autocomplete are not consistent with other modals/autocompletes.
See the commits for details on what has been done.
Before:
After:
=> Consistent autocomplete style submit package

src/api/.haml-lint.yml, src/api/app/assets/stylesheets/webui2/personal-navigation.scss, src/api/app/views/event_mailer/comment_for_package.html.haml, src/api/app/views/event_mailer/comment_for_project.html.haml, src/api/app/views/event_mailer/comment_for_request.html.haml, src/api/app/views/layouts/event_mailer.html.haml, src/api/app/views/layouts/webui2/_announcement.html.haml, src/api/app/views/layouts/webui2/_breadcrumbs.html.haml, src/api/app/views/layouts/webui2/_flash.html.haml, src/api/app/views/layouts/webui2/_login_form.html.haml, src/api/app/views/layouts/webui2/_navigation.html.haml, src/api/app/views/layouts/webui2/_personal_navigation.html.haml, src/api/app/views/layouts/webui2/_search.html.haml, src/api/app/views/layouts/webui2/webui.html.haml
Following PRs from @vpereira regarding `haml-lint` (#7466, #7468, #7470), I realized that we didn't fully cover the views for the Bootstrap UI and both UIs (mailers, error pages, etc..). They are now covered with this PR, so they will be linted. Other views are for the bento UI only, which we don't want to lint since they will be removed once we complete the Bootstrap migration.
=> haml-lint missing views

src/api/app/views/webui2/webui/project/_projects_table.html.haml, src/api/app/views/webui2/webui/project/list.html.haml
A `w-100` CSS class was missing.
Fixes #7518.
=> Make subproject tables responsive

src/backend/bs_publish
Need to work with a fixed architecture list as last possible anker point
Should also solve issues with custom release tags like SnapshotXXXX
Will still break with dashes in version or release tags, but we can't
help people anymore at that point ...
Not sure if we should also support "noarch" image builds
=> [backend] relax staticlinks regexp for images a bit more

src/api/app/assets/javascripts/webui/application/request.js, src/api/app/assets/javascripts/webui2/cm2/use-codemirror.js, src/api/app/views/webui2/webui/request/show.html.haml
When there's a submission with several packages, the diff highlighting gets partially removed when switching between tabs. This means, the color highlighting is there, but the background color is gone. This PR fixes the issue.
Fixes #7500.
=> Apply background color in the diff section when switching between tabs of a request

src/api/app/views/layouts/webui/webui.html.erb
I saw webui2 already added `lang="en"` to `<html>` root element. https://github.com/openSUSE/open-build-service/blob/master/src/api/app/views/layouts/webui2/webui.html.haml#L2
It will help browser understand the page language and choose proper fonts, time format, spell checking, etc.
=> Add lang="en" to webui page template

src/api/app/controllers/webui/webui_controller.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/user.rb
Deprecate User.current in favor of split usage of User.possibly_nobody and User.required
The later will throw an exception if no user is logged in (controller needs to make sure it requires login), the former behaves like User.current
In addition introduce User.not_required that may return nil if no user is logged in and User.admin_session? as wrapper to simplify checks for admin user being logged in.
=> Extend User's API

src/api/app/controllers/webui/groups/users_controller.rb, src/api/spec/bootstrap/features/webui/groups_spec.rb, src/api/spec/controllers/webui/groups/users_controller_spec.rb
The create action is called synchronously, so we redirect instead of rendering JavaScript. This differs from other actions (update and destroy) since they are called asynchronously. The flash messages now also contain the user/group whenever needed.
Closes #7546
=> Align usage of flash messages for groups/users_controller

src/api/app/assets/javascripts/webui2/project_monitor.js, src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/_monitor_control.html.haml, src/api/app/views/webui2/webui/project/monitor.html.haml
This reverts commit caeef35e173e52c93c57b146e8c9393ee5e831ae.
We now use DataTables state saving which stores the last used pagination
entries count. Therefor we can drop our custom code for this.
https://datatables.net/examples/basic_init/state_save.html
Fixes #7555
=> Revert "Remember number of shown entries for project monitor datatable"

dist/obs-server.spec
[dist] require insserv-compat for rc.status in obs-server and obs-worker packages
=> [dist] require insserv-compat for rc.status in obs-server and obs-worker packages
