openSUSE/open-build-service

src/api/app/views/webui2/webui/staging_workflows/_breadcrumb_items.html.haml
=> Fix breadcrumb for staging_workflow

CONTRIBUTING.md
=> Fixed broken anchor in contribution guide

dist/t/0030-installed-files.t, dist/t/0050-test-appliance.ta, dist/t/0070-check_recommended_services.ts, dist/t/lib/OBS/Test/Utils.pm, dist/t/osc/0200-check_docker_registry.ts
This PR consists of various commits to fix integration tests for version 2.9 and unstable.
=> Make integration test more version independent

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/staging_workflow.js, src/api/app/controllers/webui/staging_workflows_controller.rb, src/api/app/policies/staging_workflow_policy.rb, src/api/app/views/webui2/webui/staging_workflows/_delete.html.haml, src/api/app/views/webui2/webui/staging_workflows/show.html.haml, src/api/config/routes.rb, src/api/spec/controllers/webui/staging_workflows_controller_spec.rb
Authorization through pundit is missing, since i'm not quite sure how to handle it at this point.
I just added the delete button in the show view, just to have it. Nothing tested yet, probably a lot of room for improvements :)
=> Delete Staging Workflows

src/api/app/views/webui2/webui/staging/workflows/_delete.html.haml, src/api/app/views/webui2/webui/staging/workflows/show.html.haml
=> Make staging delete button a link

src/api/app/models/staging/workflow.rb
Kudos to @mdeniz for pointing it out.
=> Fix scope, removing includes and adding left_outer_joins

src/api/app/assets/stylesheets/webui2/staging-workflow.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/views/webui2/webui/staging/workflows/_legend.html.haml
We used bootstrap background colour for the legend.
=> Added legend for staging workflow

src/api/app/controllers/staging/projects_controller.rb, src/api/app/models/project.rb, src/api/app/models/staging/staging_project.rb, src/api/app/models/staging/workflow.rb, src/api/app/models/status/check.rb, src/api/app/views/models/_staging_project.xml.builder, src/api/app/views/webui2/webui/staging/workflows/show.html.haml, src/api/spec/cassettes/Staging_StagingProject/_overall_state/when_there_are_failed_checks/1_3_5_1.yml, src/api/spec/cassettes/Staging_StagingProject/_overall_state/when_there_are_missing_checks/1_3_3_1.yml, src/api/spec/cassettes/Staging_StagingProject/_overall_state/when_there_are_pending_checks/1_3_4_1.yml, src/api/spec/factories/bs_requests.rb, src/api/spec/factories/project.rb, src/api/spec/factories/staging_projects.rb, src/api/spec/models/project_spec.rb, src/api/spec/models/staging/staging_project_spec.rb
=> Add StagingProject model

src/api/app/models/staging/staging_project.rb, src/api/app/models/staging/workflow.rb
No idea how this went into master though ...
cc @bgeuken & @coolo maybe with the merging of master into staging-workflow?
=> Fix rubocop violations

src/api/app/views/models/_staging_project.xml.builder, src/api/app/views/models/staging/_staging_project.xml.builder
=> Fix xml view for staging projects

dist/obs-server.spec
Use sysv compatible version of all choices in the hope that this
stays longer compatible for systemd macro helpers ...
(on command of Rudi)
=> [dist] fix service reload on SLE 12

dist/obs-server.spec
=> [dist] change owner for other logfiles of services converted to systemd

src/api/app/models/staging/staging_project.rb, src/api/spec/cassettes/Staging_StagingProject/_overall_state/when_there_are_failed_checks/1_4_5_1.yml, src/api/spec/cassettes/Staging_StagingProject/_overall_state/when_there_are_missing_checks/1_4_3_1.yml, src/api/spec/cassettes/Staging_StagingProject/_overall_state/when_there_are_pending_checks/1_4_4_1.yml, src/api/spec/models/staging/staging_project_spec.rb
- Remove untracked requests from the list of missing reviews
- Add tests for StagingProject#missing_reviews
=> Missing reviews of staging projects

src/api/app/assets/stylesheets/webui2/staging-workflow.scss, src/api/app/models/staging/staging_project.rb, src/api/app/views/webui2/webui/staging/workflows/_problems.html.haml, src/api/app/views/webui2/webui/staging/workflows/_problems_item.html.haml
List the build problems in the following format: `PACKAGE_NAME: STATUS1(ARCH1, ARCH2,...) STATUS2(ARCH3,..) ...`
**openQA problems are not included**. I will send another PR for that, as it is independent.
Co-authored-by: @Ana06
=>  List build problems in staging project page

src/api/app/models/obs_factory/staging_project.rb
See openSUSE/openSUSE-release-tools#1791 for potential problems
=> Staging Projects: Prefer testing over final state failed

src/api/app/models/project.rb, src/api/app/models/staging/staging_project.rb
`update_staging_workflow_on_backend` callback was moved into `staging_project` model.
=> Move callback into the correct model

src/api/app/controllers/webui/obs_factory/staging_projects_controller.rb, src/api/app/models/bs_request.rb, src/api/app/models/obs_factory/distribution.rb, src/api/spec/models/bs_request_spec.rb
This method is querying reviews. Thus it belongs to the review model.
Since it's also just a query method I converted it into a scope.
=> Move BsRequest#with_reviews to the review model

src/api/app/controllers/staging/projects_controller.rb, src/api/app/controllers/staging/staged_requests_controller.rb, src/api/app/models/staging/stage_requests.rb, src/api/app/models/staging/workflow.rb, src/api/app/policies/staging/staging_project_policy.rb, src/api/config/routes.rb, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/invalid_user/1_3_1_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_and_invalid_request_number/1_3_3_2_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_and_invalid_request_number/1_3_3_2_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_and_invalid_request_number/1_3_3_2_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_request_number/1_3_3_1_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_request_number/1_3_3_1_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_request_number/1_3_3_1_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/with_invalid_staging_project/1_3_2_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/GET_index/1_1_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/GET_index/returns_the_staged_requests_xml.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/invalid_user/1_2_1_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/non-existent_staging_project/1_2_2_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_and_invalid_request_number/1_2_3_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_and_invalid_request_number/1_2_3_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_4_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_4_2.yml, src/api/spec/controllers/staging/staged_requests_controller_spec.rb
Add API endpoint to assign/unassign a request to a staging project.
TODO:
BONUS:
=> Assign and unassigned requests to staging project

src/api/app/assets/stylesheets/webui2/collapse-component.scss, src/api/app/assets/stylesheets/webui2/staging-workflow.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/helpers/webui/staging/workflow_helper.rb, src/api/app/models/staging/staging_project.rb, src/api/app/views/webui2/webui/staging/workflows/_overall_state.html.haml, src/api/app/views/webui2/webui/staging/workflows/_packages_list.html.haml, src/api/app/views/webui2/webui/staging/workflows/_problems.html.haml, src/api/app/views/webui2/webui/staging/workflows/_problems_item.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_projects_table.html.haml, src/api/app/views/webui2/webui/staging/workflows/edit.html.haml, src/api/app/views/webui2/webui/staging/workflows/show.html.haml
=> Show staging projects on staging workflow page

dist/obs-bundled-gems.spec, src/api/Gemfile, src/api/Gemfile.lock
ruby sass is dead, partly fixing #6263
=> Replace sass-rails with sassc-rails

src/api/config/options.yml.example
Not needed, this is done by the SSL configuration.
=> Remove protocoll from Influx example config

src/api/app/models/kiwi/image/xml_builder.rb, src/api/app/models/kiwi/image/xml_parser.rb
Close these issues on Errbit once this is merged
Also unassign myself from the GitHub issues.
=> Fix kiwi editor errors

src/api/app/views/webui2/webui/staging/workflows/_infos.html.haml
=> Link from 'Excluded' requests label to the request page

src/backend/bs_worker
Add power9 detection to bs_worker
=> [backend] Add power9 detection to bs_worker

src/api/app/controllers/staging/excluded_requests_controller.rb, src/api/app/policies/staging/request_exclusion_policy.rb, src/api/config/routes.rb, src/api/spec/controllers/staging/excluded_requests_controller_spec.rb
=>  Create excluded request API

src/api/app/controllers/staging/staged_requests_controller.rb, src/api/app/models/staging/stage_requests.rb
to let the user know what is going wrong:
* Request not found
* Backend exception
* Already branched
=> Implement better error message in Staging::StageRequest

docs/api/api/api.txt
=> Add new excluded requests API routes in apidocs

docs/api/api/api.txt, src/api/app/controllers/staging/staged_requests_controller.rb, src/api/app/models/staging/stage_requests.rb, src/api/app/policies/staging/workflow_policy.rb
Some stuff I have come across while trying this...
=> Bugfix staging workflow

src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_4_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_4_4.yml, src/api/spec/controllers/staging/staged_requests_controller_spec.rb
to test that relationship was created.
=> Add more spec for StagedRequestsController

src/api/app/views/staging/staging_projects/_checks.xml.builder, src/api/app/views/staging/staging_projects/_missing_checks.xml.builder, src/api/app/views/staging/staging_projects/_requests.xml.builder, src/api/app/views/staging/staging_projects/_requests_to_review.xml.builder, src/api/app/views/staging/staging_projects/_staged_requests.xml.builder, src/api/app/views/staging/staging_projects/_staging_project_item.xml.builder, src/api/app/views/staging/staging_projects/_untracked_requests.xml.builder, src/api/app/views/staging/staging_projects/index.xml.builder, src/api/app/views/staging/staging_projects/show.xml.builder, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_4_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_4_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_4_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_4_4.yml
Adding missing pieces to the staging API:
* checks
* missing checks
* overall state
* obsolete requests
Furthermore it does DRY some of the partials.
=> Add missing pieces to Staging API

src/backend/BSRepServer/Registry.pm, src/backend/BSSched/Checker.pm, src/backend/bs_repserver
=> rework repository buildid

docs/api/api/api.txt, docs/api/api/remove_staged_requests.xml, docs/api/api/staged_requests.xml, docs/api/api/status_ok.xml, src/api/test/functional/backend_test.rb
=> API documentation for staged requests

src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/projects/bs_requests_controller.rb
=> Enable bootstrap view of the project request tab

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/project/prjconf.html.haml, src/api/config/routes.rb
Converted the view and changed the controller to show the right thing. This is how it looks like right now:
=> Switch Project config page to bootstrap

dist/Makefile, dist/obs-server.spec, dist/systemd/obsscheduler.service, dist/systemd/obsstoragesetup.service, dist/systemd/obsworker.service
for now just wrapping the old files
=> [dist] convert remaining sysv init scripts to systemd unit files

src/api/app/controllers/webui/project_controller.rb
Following up on our discussions in the standup.
=> Enable Bootstrap in project#show for development/test

dist/obs-server.spec
SLE 15 maintenance update is not new enough...
=> [dist] raise dependency to build package

src/backend/bs_worker
=> [backend] support debian packages in kiwi tracking data

src/api/app/models/architecture.rb, src/api/app/models/project/update_from_xml_command.rb, src/api/spec/factories/repository_architecture.rb, src/api/spec/models/project/update_from_xml_command_spec.rb
=> Preserve IDs of RepositoryArchitectures on _meta updates

src/api/app/assets/stylesheets/webui2/build-results.scss, src/api/app/helpers/webui/buildresult_helper.rb
=> Update build result colors

src/api/app/controllers/webui/project_controller.rb, src/api/app/helpers/webui/user_or_groups_roles_helper.rb, src/api/app/mixins/webui/manage_relationships.rb, src/api/app/views/webui2/shared/user_or_groups_roles/_add_group_dialog.html.haml, src/api/app/views/webui2/shared/user_or_groups_roles/_delete_dialog.html.haml, src/api/app/views/webui2/shared/user_or_groups_roles/_index.html.haml, src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/project/users.html.haml, src/api/config/routes.rb
=> Migrate Project#users page to bootstrap

src/backend/BSSched/Checker.pm, src/backend/BSSrcServer/Service.pm, src/backend/bs_publish, src/backend/bs_sched
=> bs_publish: add support for sleimage iso renaming

src/api/app/controllers/webui/project_controller.rb
Fix an issue introduced in #6373. I found it while working on #6383.
=> Use the correct layout for flash messages

src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/project_controller.rb, src/backend/BSSched/Checker.pm, src/backend/BSSrcServer/Service.pm, src/backend/bs_publish, src/backend/bs_sched
Let's see if this passes rspec
=> (staging workflow) Fix master merge

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/_buildstatus.html.haml
=> Implement build results partial for projects in bootstrap

src/api/app/assets/stylesheets/webui2/webui2.css.scss
=> Remove duplicated 'repositories' sass import

src/api/app/controllers/webui/projects/rebuild_times_controller.rb, src/api/app/views/webui2/webui/projects/rebuild_times/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/projects/rebuild_times/show.html.haml, src/api/config/routes.rb
=> Migrate rebuild time graph to bootstrap

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/project/meta.html.haml, src/api/config/routes.rb, src/api/spec/bootstrap/features/webui/projects_spec.rb, src/api/spec/cassettes/Bootstrap_Projects/DoD_Repositories/adding_DoD_repositories_via_meta_editor.yml, src/api/spec/features/webui/projects_spec.rb
Converted the view and changed the controller to show the right thing. This is how it looks like right now:
=> Switch Project meta page to bootstrap

src/api/app/controllers/webui/repositories_controller.rb, src/api/app/views/webui2/webui/repositories/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/repositories/state.html.haml
=> Migrate repository state to Bootstrap

src/api/app/views/webui2/webui/project/_side_links.html.haml, src/api/app/views/webui2/webui/project/show.html.haml, src/api/app/views/webui2/webui/project/side_links/_incident_project.html.haml, src/api/app/views/webui2/webui/project/side_links/_maintenance_project.html.haml, src/api/app/views/webui2/webui/project/side_links/_patchinfo_present.html.haml, src/api/app/views/webui2/webui/project/side_links/_project_monitor.html.haml, src/api/app/views/webui2/webui/project/side_links/_release_targets.html.haml, src/api/app/views/webui2/webui/project/side_links/_requests.html.haml, src/api/config/routes.rb
Part of https://trello.com/c/VUFpbXye/973-show-description-top-box. The changes for the card need to be split. This is for your sanity as a reviewer.
Some examples of side links:
=> Add side links on show project page for Bootstrap

dist/obsstoragesetup
=> [dist] obsstoragesetup: handle sshd start better for systemd case

src/api/app/views/webui2/webui/project/meta.html.haml
We were using a wrong javascript file.
Related to #6394
=> Use correct javascript for project meta.

src/backend/bs_publish
=> [backend] fix reading milestone file in mapsleimage in bs_publish

src/api/app/assets/stylesheets/webui2/watchlist.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss
=> Add z-index to watchlist

src/api/app/views/webui2/shared/user_or_groups_roles/_index.html.haml, src/api/app/views/webui2/shared/user_or_groups_roles/_list.html.haml
=> Reduce padding in user and group table

src/api/app/assets/stylesheets/webui2/breakpoints.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss
Kudos for providing the breakpoints goes to @hellcp
Fixes #6033
=> Add breakpoint for very larger screens

src/api/app/views/webui2/webui/project/_bottom_actions.html.haml, src/api/app/views/webui2/webui/project/_delete_project_dialog.html.haml, src/api/app/views/webui2/webui/project/_edit_project_dialog.html.haml, src/api/app/views/webui2/webui/project/_project_release_request_dialog.html.haml, src/api/app/views/webui2/webui/project/_project_submit_update_dialog.html.haml, src/api/app/views/webui2/webui/project/_unlock_project_dialog.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_create_maintenance_incident.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_delete_project.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_edit_project.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_gpg_key_ssl_certificate.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_modify_project.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_patchinfo.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_report_bug.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_request_role_addition_and_deletion.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_request_to_release.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_submit_as_update.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_unlock_project.html.haml, src/api/app/views/webui2/webui/project/show.html.haml, src/api/app/views/webui2/webui/request/_add_role_request_dialog.html.haml, src/api/app/views/webui2/webui/request/_delete_request_dialog.html.haml, src/api/config/routes.rb
Part of https://trello.com/c/VUFpbXye/973-show-description-top-box. The changes for the card need to be split. This is for your sanity as a reviewer.
Some screenshots (but it's better if you give it a try, there are like 6-7 modals):
=> Add bottom actions on show project page for Bootstrap

src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/views/webui2/webui/user/_involvement.html.haml
Use a class instead to avoid override the defaults. :bowtie:
=> Do not set table-layout to all datatables

src/api/app/assets/stylesheets/webui2/datatables.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss
=> Move CSS to datatables.scss

src/backend/BSRevision.pm, src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Docker.pm, src/backend/BSSched/BuildJob/KiwiImage.pm, src/backend/BSXML.pm, src/backend/bs_srcserver
=> support more options for view=info

src/api/app/assets/javascripts/webui2/requests_table.js.erb, src/api/app/controllers/webui/mixins/bs_requests_controller_mixin.rb, src/api/app/controllers/webui/users/tasks_controller.rb, src/api/app/views/webui/users/tasks/_breadcrumb_items.html.haml, src/api/app/views/webui2/shared/_patchinfos_table.html.haml, src/api/app/views/webui2/shared/_requests_table.html.haml, src/api/app/views/webui2/webui/users/tasks/index.html.haml
=> Implement user tasks view in bootstrap

src/api/app/controllers/source_controller.rb, src/api/app/controllers/statistics_controller.rb, src/api/app/controllers/webui/groups_controller.rb, src/api/app/controllers/webui/main_controller.rb, src/api/app/controllers/webui/monitor_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/jobs/consistency_check_job.rb, src/api/app/mixins/has_relationships.rb, src/api/app/models/attrib.rb, src/api/app/models/backend_package.rb, src/api/app/models/bs_request/find_for/base.rb, src/api/app/models/bs_request/find_for/user_group_mixin.rb, src/api/app/models/cloud/backend/upload_job.rb, src/api/app/models/kiwi/image.rb, src/api/app/models/obs_factory/openqa_job.rb, src/api/app/models/project.rb, src/api/app/models/repository.rb, src/api/app/models/status_history.rb, src/api/app/models/user.rb, src/api/app/models/user_ldap_strategy.rb, src/api/app/presenters/obs_factory/staging_project_presenter.rb, src/api/lib/statistics_calculations.rb
Inspired by @bgeuken's comment:
https://github.com/openSUSE/open-build-service/pull/6425#discussion_r238106145
The performance gain is most likely unmeasurable but it's still
a good default not to waste another array allocation
=> Use inline array functions for returned arrays

src/backend/BSSched/BuildJob/Docker.pm, src/backend/BSSched/BuildJob/Patchinfo.pm, src/backend/BSSched/Checker.pm
=> support obsrepositories:/ in container annotation

src/api/config/initializers/influxdb_custom_subscriber.rb, src/api/lib/backend/logger.rb, src/api/lib/influxdb_obs/obs/middleware/backend_subscriber.rb, src/api/lib/influxdb_obs/obs/normalizer/location_normalizer.rb, src/api/spec/lib/influx_db/obs/middleware/backend_subscriber_spec.rb, src/api/spec/lib/influx_db/obs/normalizer/location_normalizer_spec.rb
to send performance metrics of the Backend to our InfluxDB.
=> Implement InfluxDB BackendSubscriber

src/api/app/controllers/webui/attribute_controller.rb, src/api/app/views/webui2/webui/attribute/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/attribute/edit.html.haml, src/api/app/views/webui2/webui/attribute/index.html.haml, src/api/app/views/webui2/webui/attribute/new.html.haml, src/api/spec/bootstrap/features/webui/attributes_spec.rb, src/api/spec/browser_helper.rb, src/api/spec/features/webui/attributes_spec.rb, src/api/spec/features/webui/projects_spec.rb, src/api/spec/support/features/features_attribute.rb
=> Project attributes on bootstrap

src/backend/BSRepServer/Checker.pm, src/backend/BSRevision.pm, src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Docker.pm, src/backend/BSSched/BuildJob/KiwiImage.pm, src/backend/BSSched/BuildJob/KiwiProduct.pm, src/backend/BSXML.pm, src/backend/bs_repserver, src/backend/t/0100-BSSched-BuildJob.t
=> Report weakdeps in fileinfo queries

src/api/app/assets/javascripts/webui2/project_monitor.js
https://github.com/openSUSE/open-build-service/issues/6470
=> Add option to show all packages on monitor page

src/api/app/views/webui2/webui/users/tasks/index.html.haml
=> Style the patchinfo count with a badge

src/api/app/controllers/webui/groups_controller.rb, src/api/app/controllers/webui2/groups_controller.rb, src/api/app/views/webui2/webui/groups/_add_user_modal.html.haml, src/api/app/views/webui2/webui/groups/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/groups/_remove_user_modal.html.haml, src/api/app/views/webui2/webui/groups/show.html.haml, src/api/config/routes.rb, src/api/spec/bootstrap/features/webui/groups_spec.rb, src/api/spec/cassettes/Groups/add_a_user.yml, src/api/spec/cassettes/Groups/visit_group_page.yml
=> Migrate group edit to Bootstrap

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui/project/_form.html.erb, src/api/app/views/webui/project/subprojects.html.haml, src/api/app/views/webui2/webui/project/_add_new_subproject_modal.html.haml, src/api/app/views/webui2/webui/project/_form.html.haml, src/api/app/views/webui2/webui/project/subprojects.html.haml, src/api/spec/features/webui/projects_spec.rb
=> Migrate Subprojects to Bootstrap

src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml
Also fix elsif condition in project breadcrumbs.
=> Add monitor breadcrumb for projects

src/api/spec/bootstrap/features/webui/attributes_spec.rb, src/api/spec/cassettes/Bootstrap_Attributes/with_an_attribute/for_a_project/with_permissions/remove_attribute.yml, src/api/spec/cassettes/Bootstrap_Attributes/with_an_attribute/for_a_project/without_permissions/it_is_not_possible_to_add_an_attribute_the_link_is_not_shown.yml, src/api/spec/cassettes/Bootstrap_Attributes/with_an_attribute/for_a_project_with_a_package/add_attribute_with_values.yml
Cassettes were missing.
Kudos to @krauselukas for pointing it out.
=> Fix Bootstrap feature attributes tests

src/api/app/controllers/webui/projects/pulse_controller.rb, src/api/app/jobs/cleanup_project_log_entries.rb, src/api/app/models/project_log_entry.rb, src/api/app/views/webui2/webui/projects/pulse/_pulse_list.html.haml, src/api/app/views/webui2/webui/projects/pulse/_pulse_list_builds.html.haml, src/api/config/clock.rb, src/api/test/models/project_log_entry_test.rb
=> Project log entry cleanup job

src/api/app/views/webui2/shared/_group_members_table.html.haml, src/api/app/views/webui2/webui/groups/show.html.haml
Badges are added to the tabs and part of the show view file is moved to a partial to make it more readable.
=> Add badges to the tabs in the group show page

src/backend/BSSched/BuildJob/Patchinfo.pm
Tested with SUSE:Maintenance:9638 ;)
=> [backend] fix patchinfo handling of containers

src/api/app/views/webui2/webui/user/_involvement.html.haml
For consistency with the rest of the views I have also added badges to the tabs in the user page.
=> Add badges to the tabs in the user page

src/api/app/views/webui2/webui/project/_subprojects_table.html.haml, src/api/app/views/webui2/webui/project/subprojects.html.haml
To reduce the repetition on the subprojects view, move table to partial
=> Extract tables from ProjectController#subprojects view to partial

src/api/app/assets/stylesheets/webui2/repositories.scss, src/api/app/views/webui2/webui/repositories/_dod_repository_card_content.html.haml, src/api/app/views/webui2/webui/repositories/_repository_card_content.html.haml, src/api/app/views/webui2/webui/repositories/_repository_path_item.html.haml
Do not show the user the icon of actions he has not permissions to do & Add request delete repository to DoD repositories.
=> Fix repositories page permissions bug

src/api/app/views/webui2/webui/project/_projects_table.html.haml, src/api/app/views/webui2/webui/project/subprojects.html.haml
This partial is used to list projects in general and is not bound
to subprojects.
=> Rename the subprojects_table partial to projects_table

src/api/spec/bootstrap/features/webui/maintenance_workflow_spec.rb
Fix the failing spec for Maintenance Workflow.
=> Fix test for branch packages in modal

src/api/spec/features/webui/comments_spec.rb
This will fix comment tests for #6502.
=> Write project comment spec for bootstrap

src/api/app/assets/javascripts/webui2/repositories.js, src/api/app/controllers/webui/repositories_controller.rb, src/api/app/views/webui2/shared/_repositories.html.haml, src/api/app/views/webui2/shared/_repositories_flag_table.html.haml, src/api/app/views/webui2/shared/_repositories_flag_table_column.html.haml, src/api/spec/bootstrap/features/webui/repositories_spec.rb, src/api/spec/support/shared_examples/features/boostrap_flag_tables.rb
Adapted Bootstrap tests related to repositories
=> Repositories Flag tests

src/api/app/views/webui2/webui/user/_info.html.haml
=> User show: Use badge for showing the role

src/api/app/views/webui2/shared/_group_members_table.html.haml
=> Check permissions to remove group members

src/api/config/initializers/influxdb_rails.rb
The empty array also defaults to localhost.
=> Fix influx initialization

src/backend/BSHTTP.pm, src/backend/BSRPC.pm, src/backend/BSServer.pm, src/backend/BSServerEvents.pm, src/backend/BSUrlmapper.pm, src/backend/bs_dodup, src/backend/bs_repserver, src/backend/bs_srcserver, src/backend/bs_worker
=> bs_dodup: support deb query strings in URLs

src/api/app/helpers/webui/webui_helper.rb, src/api/spec/helpers/webui/webui_helper_spec.rb
=> Fix issue 6504

src/api/app/views/webui/package/_file.html.erb, src/api/app/views/webui/package/_files_view.html.erb, src/api/app/views/webui2/webui/package/_file.html.haml, src/api/app/views/webui2/webui/package/_files_view.html.haml
We need to use a custom cache key including the locals otherwise the cache will be stale.
Follow up of https://github.com/openSUSE/open-build-service/pull/6590
=> Fix package file list cache

src/backend/BSDispatch.pm, src/backend/BSHTTP.pm, src/backend/BSSched/BuildJob/Docker.pm, src/backend/bs_dodup
=> Docker: do not look at added elements when checking for _obsrepositories

src/api/app/views/webui/package/_files_view.html.erb, src/api/app/views/webui2/webui/package/_files_view.html.haml
Otherwise depending on the stored key it is possible to get bentoo altough the user is part of the bootstrap beta group.
=> Beta needs to be part of the Package file list cache

src/api/app/controllers/webui/staging/excluded_requests_controller.rb
It is already in Webui::WebuiController.
=> Remove duplicated switch_to_webui2 method

src/api/app/views/webui2/webui/project/monitor.html.haml
=> Add repository status to Monitor page columns

src/backend/BSServer.pm, src/backend/BSStdServer.pm
=> [backend] slow request log: log worker requests into a different file

src/api/app/controllers/search_controller.rb
/search/request is one of the slowest routes we have and most time
is not spent in searching, but in rendering the results. Help the
model by prefetching all required elements.
One often request route is all pending requests to openSUSE:Factory
Before:
Completed 200 OK in 14263ms (Views: 0.1ms | ActiveRecord: 2358.7ms | Backend: 0.0ms)
After:
Completed 200 OK in 4725ms (Views: 0.1ms | ActiveRecord: 252.8ms | Backend: 0.0ms)
=> Prefetch all elements required to render requests

src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui/project/_tabs.html.erb, src/api/app/views/webui/project/show.html.erb, src/api/app/views/webui/projects/meta/show.html.erb, src/api/app/views/webui/projects/rebuild_times/show.html.erb, src/api/app/views/webui/repositories/state.html.haml, src/api/app/views/webui2/webui/projects/meta/show.html.haml, src/api/app/views/webui2/webui/projects/pulse/show.html.haml, src/api/app/views/webui2/webui/projects/rebuild_times/show.html.haml, src/api/app/views/webui2/webui/repositories/state.html.haml, src/api/config/routes.rb, src/api/spec/bootstrap/features/webui/repositories_spec.rb, src/api/spec/controllers/webui/projects/meta_controller_spec.rb, src/api/spec/controllers/webui/projects/rebuild_times_controller_spec.rb, src/api/spec/features/webui/projects_spec.rb
=> Use resourceful routing

src/api/app/controllers/webui/packages/job_history_controller.rb, src/api/app/controllers/webui/projects/rebuild_times_controller.rb, src/api/app/models/local_job_history.rb, src/api/app/models/package.rb, src/api/app/models/package_build_status.rb, src/api/app/models/project.rb, src/api/lib/backend/api/build_results/job_history.rb, src/api/lib/backend/connection_helper.rb, src/api/spec/controllers/webui/projects/rebuild_times_controller_spec.rb, src/api/spec/fixtures/files/jobhistory.xml, src/api/spec/models/package_spec.rb
=> Feature job history

src/api/app/controllers/webui/project_controller.rb, src/api/app/models/project.rb, src/api/app/models/user.rb, src/api/spec/controllers/webui/project_controller_spec.rb
=> Solve autocompletion issues

src/backend/BSServer.pm
=> [backend] put maxchild reached messages also in slow log

src/api/app/models/local_build_result.rb, src/api/app/models/local_build_result/for_package.rb, src/api/app/views/webui/package/_buildstatus.html.haml, src/api/app/views/webui2/webui/package/_buildstatus.html.haml
Pre-calculate in the controller if a build result is outdated (not in database but still temporarily in backend) instead of in the view, generating and SQL query per result. :nerd_face: 
real=47.93
real=21.93
--------------------------------------------------------------------
=> Improve efficience of PackageController#buildresults

src/api/app/models/project.rb
This got lost while updating #6591.
=> Add limit to project autocomplete

src/api/app/controllers/webui/projects/pulse_controller.rb, src/api/app/views/webui2/webui/projects/pulse/_pulse_list.html.haml, src/api/app/views/webui2/webui/projects/pulse/_pulse_list_changes.html.haml, src/api/app/views/webui2/webui/projects/pulse/_pulse_list_comments.html.haml, src/api/app/views/webui2/webui/projects/pulse/_pulse_list_commits.html.haml, src/api/app/views/webui2/webui/projects/pulse/_pulse_list_requests.html.haml, src/api/app/views/webui2/webui/projects/pulse/_pulse_list_requests_box.html.haml, src/api/app/views/webui2/webui/projects/pulse/show.html.haml, src/api/app/views/webui2/webui/projects/pulse/show.js.erb
Please refer to the commit messages for details on what changed.
=> Improvements for the pulse page

src/backend/BSHTTP.pm, src/backend/BSRPC.pm, src/backend/BSRegistryServer.pm
=> Small backend cleanups

src/api/app/models/local_build_result/for_package.rb, src/api/app/views/webui/package/_buildstatus.html.haml, src/api/app/views/webui2/webui/package/_buildstatus.html.haml, src/api/spec/models/local_build_result/for_package_spec.rb
=> Not showing disabled build results on default

src/api/config/routes.rb
Reverts openSUSE/open-build-service#6708
=> Revert "Remove unused release_repository_dialog route"

src/api/app/assets/javascripts/webui2/autocomplete.js, src/api/app/assets/javascripts/webui2/staging_workflow.js, src/api/app/views/webui2/shared/user_or_groups_roles/_add_group_dialog.html.haml, src/api/app/views/webui2/shared/user_or_groups_roles/_add_user_dialog.html.haml, src/api/app/views/webui2/webui/_autocomplete.html.haml, src/api/app/views/webui2/webui/project/_new_package_branch_modal.html.haml, src/api/app/views/webui2/webui/repositories/_add_repository_from_project_modal.html.haml, src/api/app/views/webui2/webui/repositories/_add_repository_path_modal.html.haml, src/api/app/views/webui2/webui/request/_change_devel_request_dialog.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_managers_group.html.haml, src/api/app/views/webui2/webui/staging/workflows/new.html.haml, src/api/spec/bootstrap/features/webui/repositories_spec.rb
=> Refactor our javascript autocompletion code

src/api/Gemfile, src/api/Gemfile.lock, src/api/app/controllers/application_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/app/jobs/application_job.rb, src/api/config/clock.rb, src/api/lib/influxdb_obs/obs/middleware/backend_subscriber.rb, src/api/spec/lib/influx_db/obs/middleware/backend_subscriber_spec.rb
This will fix several issues and introduces new features:
Issues:
* Move count and cache_hits tags to values
* Do not track SCHEMA SQL queries
Features:
* Dynamic tags per request (we track for now ``anonymous``, ``beta`` and ``api`` tags).
=> Update influxdb-rails to beta 3

src/api/app/controllers/webui/feeds_controller.rb, src/api/app/policies/project_policy.rb, src/api/spec/controllers/webui/feeds_controller_spec.rb
Refactor the action ```commits``` 
- Do Authorization with Pundit
- Extract controller logic to its own methods
=> Feeds controller refactoring

src/api/app/views/webui2/webui/comment/_content.html.haml
=> Fix comments to show more than 3 levels of comments

src/backend/bs_deltastore, src/backend/bs_servicedispatch, src/backend/bs_srcserver
=> use BSStdRunner framework in bs_deltastore

src/backend/bs_publish
=> [backend] bs_publish: cleanup dead symlinks in createrepo_staticlinks

src/backend/BSDispatcher/Constraints.pm, src/backend/BSRevision.pm, src/backend/BSSched/BuildJob/Aggregate.pm, src/backend/BSSched/BuildResult.pm, src/backend/BSSched/EventSource/RemoteWatcher.pm, src/backend/BSSched/ProjPacks.pm, src/backend/BSUtil.pm, src/backend/BSWatcher.pm, src/backend/bs_dispatch, src/backend/bs_productconvert, src/backend/bs_publish, src/backend/bs_srcserver
=> Implement proxy for lastevents query

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/Checker.pm, src/backend/BSXML.pm, src/backend/bs_worker
=> Support setting of the maxlogidle time in the project config

src/api/lib/tasks/migrate_options_yml.rake
=> Preserve comments when migrating options.yml

src/api/db/migrate/20190111130416_add_event_type_index_to_project_log_entry.rb, src/api/db/structure.sql
Follow up on #6744 to improve performance.
=> Add index for (project_id,event_type) on project_log_entries

src/backend/bs_worker
=> [backend] fix build log limit state export

src/backend/BSSched/Checker.pm, src/backend/BSSched/EventSource/RemoteWatcher.pm
=> do not use the lastevents proxy to proxy our own src server requests

src/api/app/controllers/search_controller.rb
I'm mainly interested in request matches so that the latest (highest ID/number) is last
=> Order search results

src/backend/BSSched/BuildJob/KiwiProduct.pm, src/backend/bs_signer
=> work around newer 'rpm --delsign' sometimes doing inplace removal

src/api/app/controllers/webui/package_controller.rb, src/api/app/helpers/webui/package_helper.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/services/package_controller_service/url_generator.rb, src/api/app/views/webui/package/binary.html.haml, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/spec/helpers/webui/webui_helper_spec.rb, src/api/spec/services/package_controller_service/url_generator_spec.rb
I just broke my last PR #6737, refactoring ```PackageController``` in smallers chunks of change.
=> Refactor package controller

src/api/app/helpers/webui/group_helper.rb, src/api/app/helpers/webui/user_helper.rb, src/api/app/views/webui/request/_reviewer.html.erb
To be consistent with the staging workflow page
Co-authored by @Ana06
=>  Add group icons to request show page 

src/api/app/views/webui2/shared/_repositories.html.haml
https://paste.opensuse.org/view/raw/55501904
Thanks to @SergioAtSUSE for reporting.
=> Drop debug output

src/api/app/models/staging/workflow.rb
It didn't work in https://github.com/openSUSE/open-build-service/pull/6806 :relaxed:
=> Cache groups_hash

src/backend/bs_dispatch, src/backend/bs_repserver, src/backend/bs_srcserver, src/backend/bs_worker
=> send and store the buildlog for badhost builds

src/api/spec/cassettes/EventMailer/_event/for_an_event_of_type_Event_Request/when_source_project_does_not_exist/does_not_get_delivered.yml, src/api/spec/controllers/staging/staging_projects_controller_spec.rb, src/api/spec/factories/bs_requests.rb, src/api/spec/models/bs_request_spec.rb, src/api/spec/models/staging/workflow_spec.rb, src/api/spec/support/shared_contexts/a_set_of_bs_requests.rb
I went too far with the bs_requests factory, reverting some of it
=> rspec: Don't fake the request state

src/api/app/helpers/webui/project_helper.rb, src/api/app/views/webui2/webui/project/show.html.haml
=> Fix syntax error in haml view

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui2/webui/request/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/request/show.html.haml
The migration of the request view to bootstrap, requires
a basic skeleton
Co-authored-by: @bgeuken
=> Add skeleton for request show page in webui2

src/api/app/controllers/webui/request_controller.rb, src/api/spec/bootstrap/features/webui/maintenance_workflow_spec.rb, src/api/spec/bootstrap/features/webui/requests_spec.rb, src/api/spec/features/webui/requests_spec.rb
We need to enable bootstrap in the test environment to
catch failing feature tests.
=> Switch to webui2 in test environment in request show

src/api/app/views/webui2/webui/main/index.html.haml, src/api/app/views/webui2/webui/package/show.html.haml, src/api/app/views/webui2/webui/project/monitor.html.haml, src/api/app/views/webui2/webui/project/show.html.haml, src/api/app/views/webui2/webui/users/subscriptions/index.html.haml
This is a remnant of the old webui.
Follow-up to #6848
=> Remove unneeded instance variable in webui2 views

src/api/lib/tasks/dev.rake
If working on request/show it's brutally benefitial to have requests with review history and comments.
=> Add request 2 to the development data (used in review apps)

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/helpers/webui/project_helper.rb, src/api/app/models/package.rb, src/api/app/models/project.rb, src/api/app/views/webui2/webui/project/_status_comment.html.haml
This will make @coolo happy :laughing:
=>  Get rid of api_obj

src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui2/webui/comment/_content.html.haml
The error handler matches all comments, so repeating it is even harmful
=> Don't repeat the same javascript behind every comment

.gitmessage
I have to write it every time I do something with coolo. :angry:
=> Add coolo to git template

src/api/app/controllers/webui/project_controller.rb, src/api/app/helpers/webui/buildresult_helper.rb, src/api/app/views/webui/project/monitor.html.erb, src/api/app/views/webui2/webui/project/monitor.html.haml, src/api/spec/controllers/webui/project_controller_spec.rb
This is improving both the old UI and the new one (Bootstrap), although it has a much bigger impact in the new one.
Solves https://github.com/openSUSE/open-build-service/issues/6554
Times with 74 packages and 40 repositories:
14151ms (Views: 12719.2ms | ActiveRecord: 191.2ms | Backend: 726.9ms)
3750ms (Views: 2785.9ms | ActiveRecord: 19.9ms | Backend: 724.4ms)
4685ms (Views: 3351.1ms | ActiveRecord: 176.3ms | Backend: 680.2ms)
3653ms (Views: 2681.3ms | ActiveRecord: 21.3ms | Backend: 715.8ms)
=> Improve monitor performance

src/api/app/helpers/webui/request_helper.rb, src/api/app/views/webui/request/show.html.erb, src/api/spec/helpers/webui/request_helper_spec.rb
This commit moves business logic into helpers. We are about to migrate
this view to bootstrap. This change makes it easier to re-use the
existing code.
=> Refactor source diff code in package show view

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui/project/monitor.html.erb, src/api/app/views/webui2/webui/project/monitor.html.haml
This removes quite some nonsense that the code collected over the years
=> Merge fill_status_cache into monitor and split out differently

.gitmessage
=> Change my email

src/backend/BSSched/BuildJob/Channel.pm
=> [backend] allow a :flavor suffix in the channel package definition

src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui2/webui/comment/_content.html.haml, src/api/app/views/webui2/webui/comment/_show.html.haml
=> Update default icon for comments

src/api/app/assets/javascripts/webui2/project_monitor.js, src/api/app/views/webui2/webui/project/_monitor_control.html.haml
- Don't close dropdowns in monitor filtering
- Add select all for monitor filters
:bowtie:
=> Improve monitor filtering

src/backend/bs_regpush, src/backend/bs_worker
This speeds up container uploads even more.
=> [backend] allow one redirect in the blob existance check

src/api/app/assets/stylesheets/webui2/requests.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/helpers/webui/package_helper.rb, src/api/app/helpers/webui/request_helper.rb, src/api/app/views/webui/request/show.html.erb, src/api/app/views/webui2/webui/package/_revision_diff_detail.html.haml, src/api/app/views/webui2/webui/package/_revision_diff_detail_buttons.html.haml, src/api/app/views/webui2/webui/package/rdiff.html.haml, src/api/app/views/webui2/webui/request/_sourcediff_tab.html.haml, src/api/app/views/webui2/webui/request/show.html.haml, src/api/spec/helpers/webui/package_helper_spec.rb, src/api/spec/helpers/webui/request_helper_spec.rb
=> Refactor request show page and implement request diffing for bootstrap UI

src/api/app/controllers/webui/request_controller.rb
Optimize search for changestate and improve ruby dialect
=> Refactor RequestController#changerequest

src/api/Gemfile, src/api/Gemfile.lock, src/api/lib/obsapi/markdown_renderer.rb, src/api/spec/helpers/webui/markdown_helper_spec.rb
Add coderay gem
Add test case to check functionality
Closes #6673 
- screenshot:
=> Add colorful syntax in md code block

src/api/app/assets/javascripts/webui2/request.js, src/api/app/views/webui2/webui/request/_decision_tab.html.haml, src/api/app/views/webui2/webui/request/_review_tab.html.haml, src/api/app/views/webui2/webui/request/show.html.haml
=> Add review and request actions for bs requests

src/api/app/assets/javascripts/webui2/request.js, src/api/app/controllers/webui/packages/bs_requests_controller.rb, src/api/app/controllers/webui/projects/bs_requests_controller.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/show.html.erb, src/api/app/views/webui2/webui/request/_add_reviewer_dialog.html.haml, src/api/app/views/webui2/webui/request/_show_overview.html.haml, src/api/app/views/webui2/webui/request/_show_package_maintainers.html.haml, src/api/app/views/webui2/webui/request/_show_side_links.html.haml, src/api/app/views/webui2/webui/request/show.html.haml, src/api/config/routes.rb, src/api/spec/features/webui/requests_spec.rb
Convert Request#show overview to bootstrap
Overview:
Add Reviewer
Show package maintainers
=> Request show overview

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui2/webui/comment/_new.html.haml, src/api/app/views/webui2/webui/comment/_reply.html.haml, src/api/app/views/webui2/webui/request/_decision_tab.html.haml, src/api/app/views/webui2/webui/request/_review_tab.html.haml, src/api/app/views/webui2/webui/request/show.html.haml
* Implement request forwarding for webui 2
* Fix size of text area fields of comments and request decision box
=> Request forwarding 

src/backend/BSSched/BuildRepo.pm, src/backend/BSSched/ProjPacks.pm, src/backend/bs_worker
=> worker move send_dispatched call after replying to the dispatcher

src/api/app/models/channel_binary.rb, src/api/test/unit/channel_test.rb
=> [api] fix indexing of multibuild flavored builds in channel files

src/api/app/views/webui2/webui/request/_show_overview.html.haml
=> Fix 'Add a Review' link

src/backend/BSSched/BuildJob/Patchinfo.pm
=> [backend] accept .deb files for patchinfos

src/api/app/views/webui2/webui/request/_review_tab.html.haml, src/api/app/views/webui2/webui/request/_show_side_links.html.haml, src/api/spec/bootstrap/features/webui/requests_spec.rb, src/api/spec/cassettes/Bootstrap_Requests/for_role_addition/for_packages/can_be_accepted.yml, src/api/spec/cassettes/Bootstrap_Requests/for_role_addition/for_projects/can_be_accepted.yml, src/api/spec/cassettes/Bootstrap_Requests/for_role_addition/for_projects/can_be_submitted.yml, src/api/spec/cassettes/Bootstrap_Requests/request_show_page/request_history_entries/behaves_like_expandable_element/expanding_a_text_field.yml, src/api/spec/cassettes/Bootstrap_Requests/review/for_group/opens_a_review.yml, src/api/spec/cassettes/Bootstrap_Requests/review/for_invalid_reviewer/opens_no_review.yml, src/api/spec/cassettes/Bootstrap_Requests/review/for_package/opens_a_review.yml, src/api/spec/cassettes/Bootstrap_Requests/review/for_project/opens_a_review.yml, src/api/spec/cassettes/Bootstrap_Requests/review/for_user/opens_a_review_and_accepts_it.yml, src/api/spec/cassettes/Bootstrap_Requests/shows_the_correct_auto_accepted_message/when_request_auto_accept_is_in_the_future_and_not_in_a_final_state.yml, src/api/spec/cassettes/Bootstrap_Requests/shows_the_correct_auto_accepted_message/when_request_auto_accept_is_in_the_past_and_not_in_a_final_state.yml, src/api/spec/cassettes/Bootstrap_Requests/shows_the_correct_auto_accepted_message/when_request_is_in_a_final_state.yml, src/api/spec/features/webui/requests_spec.rb
Because of the migration to bootstrap we copy and adapted the feature
tests for request.
We need to create other PRs to extend the tests for request.
=> Request Feature Tests

src/api/app/assets/javascripts/webui2/project_monitor.js, src/api/app/assets/stylesheets/webui2/datatables.scss, src/api/app/views/webui2/webui/project/monitor.html.haml
The problems are caused by a bug: https://github.com/mkhairi/jquery-datatables/issues/17
Solution provided by @mkhairi
=> Fix DataTable problems in monitor page

.gitmessage
Remove colleagues which aren't active anymore
=> Remove Chris and Moises from .gitmessage :(

src/api/app/assets/javascripts/webui2/buildresult.js, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/package/_buildstatus.html.haml, src/api/app/views/webui2/webui/project/_buildstatus.html.haml
=> Fix collapse repository for multibuilds

src/api/app/views/webui2/webui/request/_decision_tab.html.haml, src/api/app/views/webui2/webui/request/_review_tab.html.haml
=> Add some more space between buttons on request page

src/api/app/assets/javascripts/webui2/packages.js, src/api/app/views/webui2/webui/package/_revision_diff_detail.html.haml, src/api/app/views/webui2/webui/package/rdiff.html.haml, src/api/app/views/webui2/webui/request/_sourcediff_tab.html.haml
Adapt the existing code to make this work with requests containing multiple packages and to reuse what we have already in the package revisions diffs.
=> Add Expand/Collapse all buttons to request#show diffs

src/backend/BSSched/Lookat.pm, src/backend/BSSched/ProjPacks.pm, src/backend/BSXML.pm, src/backend/bs_sched, src/backend/bs_worker
=> do not propagate med events to locked project

src/api/app/controllers/webui/request_controller.rb, src/api/app/models/bs_request.rb, src/api/app/views/webui/request/show.html.erb, src/api/app/views/webui2/webui/request/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/request/_request_comments.html.haml, src/api/app/views/webui2/webui/request/_show_overview.html.haml, src/api/app/views/webui2/webui/request/_show_side_links.html.haml, src/api/app/views/webui2/webui/request/show.html.haml, src/api/test/unit/bs_request_test.rb
- Reduce number of instance variables in the controller
- Avoid using webui_infos when its not necessary
- Move text to its own partial
=> Refactor Request#show controller and view

src/backend/bs_notar, src/backend/bs_regpush, src/backend/bs_srcserver
=> implement config query in bs_regpush

src/api/app/controllers/webui/request_controller.rb
=> Enable the request bootstrap view for beta users

src/api/spec/bootstrap/features/webui/requests_spec.rb, src/api/spec/features/webui/requests_spec.rb
and ensure that an exception is thrown if updating it fails. So
that we get aware of issues in our tests.
=> Simplify updating request attributes

src/api/app/controllers/webui/architectures_controller.rb, src/api/app/controllers/webui/configuration_controller.rb, src/api/app/controllers/webui/groups_controller.rb, src/api/app/controllers/webui/subscriptions_controller.rb, src/api/app/controllers/webui/user_controller.rb, src/api/app/views/webui2/webui/architectures/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/architectures/index.html.haml, src/api/app/views/webui2/webui/configuration/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/configuration/_tabs.html.haml, src/api/app/views/webui2/webui/configuration/index.html.haml, src/api/app/views/webui2/webui/configuration/interconnect.html.haml, src/api/app/views/webui2/webui/groups/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/groups/index.html.haml, src/api/app/views/webui2/webui/subscriptions/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/subscriptions/index.html.haml, src/api/app/views/webui2/webui/user/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/user/index.html.haml, src/api/spec/bootstrap/features/webui/groups_spec.rb, src/api/spec/bootstrap/features/webui/repositories_spec.rb, src/api/spec/features/webui/notifications_spec.rb
=> Add page skeleton for Configuration

src/api/app/views/webui2/webui/users/subscriptions/index.html.haml
=> Add margin between notification and RSS field

src/backend/BSSched/BuildJob.pm
Needs commit 139bb72b804bba06d5144ada4ac8a439f72942bc of obs-build
to work.
We do this so that we can build images/containers without the
"lpxx" prefix used in openSUSE Leap.
=> [backend] Support build-type specific release settings

src/api/app/models/project.rb
Co-authored-by: Lukas Krause <lkrause@suse.com>
=> Update style of sibling iteration

src/api/app/views/webui2/webui/package/_file.html.haml
=> Fix issue 6951

src/api/app/controllers/webui/user_controller.rb, src/api/app/helpers/webui/user_helper.rb, src/api/app/views/webui2/webui/user/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/user/edit.html.haml, src/api/spec/bootstrap/features/webui/users/user_admin_edit_spec.rb
=> Migrate user edit page to bootstrap

src/api/app/controllers/webui/subscriptions_controller.rb, src/api/app/views/webui2/webui/subscriptions/_subscriptions_form.html.haml, src/api/app/views/webui2/webui/subscriptions/index.html.haml
=> Migrate notifications view for Bootstrap UI

src/backend/BSSched/BuildJob.pm
=> [backend] fix typo in build-type specific release settings

src/api/app/assets/javascripts/webui2/project.js, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui2/project_controller.rb, src/api/app/datatables/project_datatable.rb, src/api/app/models/project.rb, src/api/app/views/webui2/webui/project/_projects_table.html.haml, src/api/app/views/webui2/webui/project/subprojects.html.haml
=> Use serverside pagination for rendering projects on the subproject tab

src/api/spec/bootstrap/features/webui/users/admin_configuration_spec.rb
=> Add tests for user configuration tab for new UI

src/api/app/views/webui2/shared/_dialog_action_buttons.html.haml, src/api/app/views/webui2/webui/package/_edit_dialog.html.haml, src/api/app/views/webui2/webui/package/_submit_request_dialog.html.haml, src/api/app/views/webui2/webui/project/_edit_project_dialog.html.haml, src/api/app/views/webui2/webui/project/_new_package_modal.html.haml, src/api/app/views/webui2/webui/project/_project_submit_update_dialog.html.haml, src/api/app/views/webui2/webui/repositories/_edit_repository_modal.html.haml, src/api/app/views/webui2/webui/repositories/_request_delete_repository_modal.html.haml, src/api/app/views/webui2/webui/request/_add_role_request_dialog.html.haml, src/api/app/views/webui2/webui/request/_change_devel_request_dialog.html.haml, src/api/app/views/webui2/webui/request/_delete_request_dialog.html.haml, src/api/app/views/webui2/webui/staging/workflows/_create_staging_project.html.haml, src/api/app/views/webui2/webui/user/_edit_dialog.html.haml, src/api/app/views/webui2/webui/user/_password_dialog.html.haml, src/api/spec/bootstrap/features/webui/packages_spec.rb, src/api/spec/bootstrap/features/webui/projects_spec.rb, src/api/spec/bootstrap/features/webui/requests_spec.rb, src/api/spec/features/webui/projects_spec.rb
Closes #6765
I'm expecting a few feature specs to fail due to buttons having a different text now. I will fix them...
=> Adjust text of submit tags depending on the context

src/api/app/views/webui2/webui/request/show.html.haml
Follow up of e889149d95bc53b79a388f2950a8aac219818ba1 where I forgot
that this could also happen.
=> Hide whole card element when there are no decisions and no reviews open

src/backend/BSSrcdiff.pm, src/backend/BSSrcrep.pm, src/backend/BSStdServer.pm, src/backend/BSUtil.pm, src/backend/bs_srcserver
=> Guard against srcrep aliasing issues

src/backend/BSSrcdiff.pm, src/backend/bs_srcserver
This still shows file states, but does not provide a textual diff.
=> [backend] add 'nodiff' srcdiff option

src/api/spec/features/webui/announcements_spec.rb, src/api/spec/features/webui/notifications_spec.rb
We disabled them while working on the new views.
=> Enable tests for new bootstrap themed views

src/api/app/controllers/webui/subscriptions_controller.rb, src/api/app/controllers/webui/users/subscriptions_controller.rb, src/api/app/models/event_subscription/form.rb, src/api/app/views/webui2/webui/subscriptions/_subscriptions_form.html.haml, src/api/app/views/webui2/webui/subscriptions/index.html.haml, src/api/app/views/webui2/webui/subscriptions/update.js.erb, src/api/app/views/webui2/webui/users/subscriptions/index.html.haml, src/api/app/views/webui2/webui/users/subscriptions/update.js.erb, src/api/spec/bootstrap/features/webui/users/users_notifications_settings_spec.rb
=> Introduce AJAX in notifications and user notifications

src/api/app/controllers/webui/architectures_controller.rb, src/api/app/controllers/webui/configuration_controller.rb, src/api/app/controllers/webui/groups_controller.rb, src/api/app/controllers/webui/subscriptions_controller.rb, src/api/app/controllers/webui/user_controller.rb, src/api/spec/features/webui/announcements_spec.rb, src/api/spec/features/webui/notifications_spec.rb
=> Enable admin configuration views in production mode

src/backend/BSSrcrep.pm, src/backend/BSStdRunner.pm, src/backend/BSStdServer.pm, src/backend/BSUtil.pm, src/backend/bs_sched
=> Add and use logging facitily for critical events

src/api/app/assets/javascripts/webui2/datatables.js, src/api/app/assets/javascripts/webui2/project.js, src/api/app/assets/javascripts/webui2/users_groups.js, src/api/app/controllers/webui/user_controller.rb, src/api/app/datatables/datatable.rb, src/api/app/datatables/project_datatable.rb, src/api/app/datatables/user_configuration_datatable.rb, src/api/app/helpers/webui/user_helper.rb, src/api/app/models/user.rb, src/api/app/views/webui/user/index.html.haml, src/api/app/views/webui2/webui/project/_projects_table.html.haml, src/api/app/views/webui2/webui/user/index.html.haml
=> User configuration tab datatable

src/api/.rubocop_todo.yml, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/datatables/package_datatable.rb, src/api/app/views/webui2/webui/project/_project_packages.html.haml, src/api/app/views/webui2/webui/project/show.html.haml, src/api/config/routes.rb
We created a new endpoint for retrieving the package list, which
was needed for feeding it to datatable.
=> Use server side pagination for package list in project view

ReleaseNotes-2.10, src/api/app/models/comment.rb, src/api/app/models/event/comment_event.rb, src/api/app/models/event/comment_for_package.rb, src/api/app/models/event/comment_for_project.rb, src/api/app/models/event/comment_for_request.rb, src/api/db/data/20190228170655_migrate_comment_payload.rb, src/api/db/data_schema.rb, src/api/spec/db/data/migrate_comment_payload_spec.rb
=> Use User login instead id for comment events

src/backend/BSSrcdiff.pm, src/backend/bs_srcserver
=> Do not run services for expand=1 and emptylink=1

src/api/app/datatables/package_datatable.rb
We now have a datatable class that we can inherit from.
=> Update inheritance of PackageDatatable

src/api/app/controllers/webui/monitor_controller.rb
Search ranges should have upper-limit to avoid long running queries and consequently leading to service degradation. Related with bug https://bugzilla.suse.com/show_bug.cgi?id=1125812
=> Add upper-limit to range to avoid long running queries (boo#1125812)

src/api/app/mixins/webui/manage_relationships.rb
=> Fix #6989. Disable Submit button autocomplete returns nothing

src/backend/bs_publish, src/backend/bs_repserver
=> [backend] fix/support staticlinks for product iso media

src/api/app/controllers/webui/groups_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/user_controller.rb
We forgot those... @openSUSE/obs-frontend
=> Remove environment checks for Bootstrap

src/api/app/controllers/webui/repositories_controller.rb
That should have been part of 3ee580b44f87f060a0f1f68fd4797f6bb96935a0
but I overlooked it.
=> Update exception we throw in case of 404

src/api/app/models/bs_request.rb, src/api/lib/tasks/delayed_job.rake
We had an older OBS instance running 2.3 that we finally upgraded last year. Unfortunately, the request migration failed pretty quickly because one of the users had been deleted. This adds a couple fixes and some logging to make debugging the process nicer. I didn't see any other tasks using `Rails.logger`, but it seems a lot nicer than using `puts`. Let me know if you'd prefer otherwise.
=> Import request fixes

src/backend/BSRepServer/YMP.pm, src/backend/BSSched/BuildJob/Aggregate.pm, src/backend/bs_repserver
=> split YMP handling into BSRepServer::YMP.pm

docs/api/api/api.txt, src/api/app/controllers/staging/excluded_requests_controller.rb, src/api/app/views/staging/excluded_requests/index.xml.builder, src/api/config/routes.rb, src/api/spec/controllers/staging/excluded_requests_controller_spec.rb
Also add documentation in apidocs.
=> List excluded requests via the API

src/api/app/controllers/webui/repositories_controller.rb, src/api/spec/cassettes/Webui_RepositoriesController/POST_create_dod_repository/as_regular_user/with_valid_repository_data/1_6_1_1_1.yml, src/api/spec/controllers/webui/repositories_controller_spec.rb
Just admins are allowed to create DoD repositories, however the ```RepositoriesController#create_dod_repository``` as it is today allows regular users to do it (boo#1125781)
=> Authorize using the DownloadRepositoryPolicy

src/api/app/assets/stylesheets/webui2/comments.scss
=> Fix comments in requests

src/backend/bs_sched, src/backend/bs_srcserver
=> fix source diff for obscpio files

dist/obs-api-testsuite-rspec.spec
This will be obsolete soon hopefully
=> Run all feature tests with bootstrap on OBS

src/api/spec/bootstrap/features/webui/users/admin_configuration_spec.rb
See https://circleci.com/gh/openSUSE/open-build-service/22295#artifacts/containers/3
=> Fix flickering test caused by datatables changing page

src/api/spec/db/data/convert_notifications_event_payload_to_json_spec.rb, src/api/spec/factories/attrib_types.rb, src/api/spec/lib/pretty_nested_errors_spec.rb, src/api/spec/support/database_cleaner.rb
=>  Don't treat AttribNamespace and AttribType as static

src/backend/bs_repserver, src/backend/bs_srcserver, src/backend/bs_worker
=> generate .creatrepo_checksums file for product builds

src/api/app/views/webui2/webui/package/binaries.html.haml
=> Only show delete binaries link to users with permissions for it

src/api/app/controllers/webui/repositories_controller.rb, src/api/spec/cassettes/Webui_RequestController/POST_create_dod_repository/as_regular_user/with_valid_repository_data/1_6_1_1_1.yml, src/api/spec/controllers/webui/repositories_controller_spec.rb
=> 2.9 download repository policy

src/api/app/views/webui2/webui/interconnects/new.html.haml
=> Fix text for Tizen and Packman interconnect

src/api/app/views/staging/staging_projects/_history_elements.xml.builder, src/api/app/views/staging/staging_projects/_staging_project_item.xml.builder, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
Add history elements to the Staging Project show xml view
=> Add history to StagingProjectController#show view

src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/models/concerns/staging_project.rb, src/api/spec/controllers/webui/staging/projects_controller_spec.rb
=> Create staging project from existing project

src/backend/BSSched/BuildJob.pm, src/backend/BSXML.pm, src/backend/bs_repserver, src/backend/bs_worker
=> binarychecksums: use XML for communicating with a remote server

src/api/spec/policies/group_policy_spec.rb
=> Add tests for group policy

src/api/app/models/buildresult.rb, src/api/app/models/status_count.rb
Use a local struct instead. Cheaper, easier, more flavor!
=> Drop StatusCount model

src/api/spec/controllers/group_controller_spec.rb
=> Add tests for the group API routes

src/backend/BSSched/Checker.pm, src/backend/bs_publish
"noversion" is now the default, there is a "withversion" switch
that makes the publisher put the kiwi version into the filename.
=> [backend] vagrant: switch default for box versioning

docs/api/api/api.txt, src/api/app/controllers/staging/workflows_controller.rb, src/api/config/routes.rb, src/api/spec/controllers/staging/workflows_controller_spec.rb
This is already posible in the WebUI. It also provides documentation and tests.
=> Provide an API to destroy a workflow

src/api/.rubocop.yml, src/api/lib/tasks/dev.rake
=> Add a task to generate staging workflow data for development environment

dist/Makefile, dist/obs-server.spec, dist/obs_api_delayed_jobs_monitor.cron, src/api/script/delayed_job_monitor.rb
See the discussion in https://github.com/openSUSE/open-build-service/pull/7282
=> Remove the invalid cron file obs_api_delayed_jobs_monitor

src/api/app/models/concerns/staging_project.rb
This code was a bit confusing. It had a lot of conditions that called
different methods, and some methods called each others. So it has been simplified.
=> Refactor state method for staging project

src/api/app/controllers/webui/webui_controller.rb, src/api/spec/controllers/webui/package_controller_spec.rb
=> Remove use_source from require_package

src/api/app/controllers/webui/webui_controller.rb, src/api/spec/controllers/webui/package_controller_spec.rb
Also improve flash message error and fix some tests
=> Remove `use_source` in require_package from WebuiController

ReleaseNotes-2.9.6
=> Add ReleaseNotes for 2.9.6

src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/models/concerns/staging_project.rb, src/api/app/views/webui2/webui/staging/projects/_history_elements.html.haml, src/api/app/views/webui2/webui/staging/projects/_staging_project_created_history.html.haml, src/api/app/views/webui2/webui/staging/projects/_unstaged_staged_request_history.html.haml, src/api/app/views/webui2/webui/staging/projects/show.html.haml
=> Add the creation of a staging project to its history

docs/api/api/api.txt, docs/api/api/update_staging_workflow.xml, src/api/app/controllers/staging/workflows_controller.rb, src/api/app/models/staging/workflow.rb, src/api/config/routes.rb, src/api/spec/controllers/staging/workflows_controller_spec.rb, src/api/test/functional/backend_test.rb
And also add the documentation.
=> Update the manager group for a staging via the API

docs/api/api/api.txt, docs/api/api/create_excluded_requests.xml, docs/api/api/delete_excluded_requests.xml, docs/api/api/excluded_requests.xml, src/api/test/functional/backend_test.rb
Add missing documentation examples bodies and results of excluded requests API calls.
=> Add missing API documentation examples

docs/api/api/api.txt, docs/api/api/create_staging_projects.xml, src/api/app/controllers/staging/staging_projects_controller.rb, src/api/app/services/staging/staging_project_creator.rb, src/api/app/services/staging/staging_project_validator.rb, src/api/config/routes.rb, src/api/spec/controllers/staging/staging_projects_controller_spec.rb, src/api/spec/services/staging/staging_project_creator_spec.rb, src/api/test/functional/backend_test.rb
- Implemented API (added create action and route).
- Added controller and service tests.
- Added API documentation.
=>  Create staging projects via API

src/api/app/controllers/staging/staging_projects_controller.rb, src/api/app/services/staging/staging_project_creator.rb, src/api/spec/services/staging/staging_project_creator_spec.rb
To follow up on #7214 and #7178.
=> Add the creation of a staging project to its history for the API

src/api/app/assets/stylesheets/webui2/staging-workflow.scss, src/api/app/views/webui2/webui/staging/shared/_legend.html.haml
=> Add a color for the 'accepting' state of the staging workflow

src/api/app/controllers/webui/attribute_controller.rb, src/api/app/controllers/webui/comments_controller.rb, src/api/app/controllers/webui/download_on_demand_controller.rb, src/api/app/controllers/webui/interconnects_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/status_messages_controller.rb, src/api/app/controllers/webui/user_controller.rb, src/api/app/controllers/webui2/comments_controller.rb, src/api/app/mixins/webui/manage_relationships.rb, src/api/spec/controllers/webui/attribute_controller_spec.rb, src/api/spec/controllers/webui/comments_controller_spec.rb, src/api/spec/controllers/webui/download_on_demand_controller_spec.rb, src/api/spec/controllers/webui/interconnects_controller_spec.rb, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/spec/controllers/webui/project_controller_spec.rb
=> Update flash messages that were using incorrect flash message type

src/api/app/models/package.rb, src/api/app/models/project.rb
=> Improve patchinfo related queries

src/api/lib/tasks/dev.rake
=> Move amqp configuration options inside development section

src/api/app/models/bs_request.rb, src/api/app/models/project.rb
=> Fix minor incident issues

ReleaseNotes-2.10, docs/api/api/api.txt, docs/api/api/highest_rated.xml, docs/api/api/rating.xml
=> Deprecate Ratings

dist/t/osc/0030_create_and_build_package.ts
=> [ci] make osc tests more verbose

src/backend/BSSched/BuildResult.pm, src/backend/BSSched/Checker.pm, src/backend/bs_sched
=> change repo state generation to use a random buildid

src/api/config/initializers/influxdb_dj_subscriber.rb
So we can know what's going on in the queue and how jobs perform.
=> Add some DelayedJob instrumentation

src/api/app/assets/javascripts/webui2/cm2/use-codemirror.js, src/api/app/assets/stylesheets/webui2/cm2/suse.scss
Related to #7257
Bento:
Before:
After:
=> Improve diff view

src/backend/BSSrcServer/Link.pm
If there is a link/frozen link to an expanded link in an
inherited package we do not know if the link was expanded in
the origin project or not. This is relevant both for the lsrcmd5
(which might not be available yet) or the linkinfo's srcmd5.
So test where the trees are available and decide which project
to use.
This is a hack, but the information is simply not available so
we need to do some heuristic thing.
=> [backend] linkinfo_addtarget: fix corner case with project links

src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/projects/maintained_projects_controller.rb, src/api/app/datatables/maintained_project_datatable.rb, src/api/app/views/webui/projects/maintained_projects/_breadcrumb_items.html.haml, src/api/app/views/webui/projects/maintained_projects/_create_dialog.html.haml, src/api/app/views/webui/projects/maintained_projects/_delete_dialog.html.haml, src/api/app/views/webui/projects/maintained_projects/index.html.haml, src/api/app/views/webui2/webui/project/_tabs.html.haml, src/api/config/routes.rb, src/api/spec/bootstrap/features/webui/maintained_projects_spec.rb, src/api/spec/controllers/webui/projects/maintained_projects_controller_spec.rb, src/api/spec/features/webui/projects_spec.rb
- Add controllers and views to maintained projects management
- Bootstrap it
- Enable server side pagination using datatable
=> Move maintained projects actions to its own controller

src/api/app/assets/stylesheets/webui2/patchinfo.scss, src/api/app/assets/stylesheets/webui2/requests.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/projects/maintenance_incidents_controller.rb, src/api/app/helpers/webui/maintenance_incident_helper.rb, src/api/app/helpers/webui/project_helper.rb, src/api/app/views/webui2/webui/projects/maintenance_incidents/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/projects/maintenance_incidents/_incident_table_entry.html.haml, src/api/app/views/webui2/webui/projects/maintenance_incidents/_tabs.html.haml, src/api/app/views/webui2/webui/projects/maintenance_incidents/index.html.haml
=> Incident view

src/api/app/datatables/package_datatable.rb, src/api/app/views/webui2/webui/project/_project_packages.html.haml
Do not set the order in the query to allow DataTable to do it.
Fixes #7261
=>  Fix sorting package list in project 

src/api/app/views/webui2/webui/request/show.html.haml
We needed to refresh CodeMirror editor to load the content
Fix #7313
=> Fix CodeMirror content on request

src/backend/bs_publish
=> [backend] createrelease_debian: use utc instead of local time

src/backend/bs_publish
no X.Y.Z version enforcement anymore
=> [backend] Support static links for new kiwi appliance file names

src/api/app/assets/javascripts/webui2/collapsible_text.js, src/api/app/assets/stylesheets/webui2/collapsible-text.scss, src/api/app/assets/stylesheets/webui2/texts.scss, src/api/app/views/webui2/webui/package/show.html.haml, src/api/app/views/webui2/webui/project/show.html.haml, src/api/app/views/webui2/webui/request/_request_history.html.haml, src/api/app/views/webui2/webui/request/_request_history_element.html.haml, src/api/app/views/webui2/webui/request/_show_overview.html.haml, src/api/app/views/webui2/webui/request/show.html.haml, src/api/app/views/webui2/webui/webui/_collapsible_text.html.haml, src/api/spec/bootstrap/features/webui/requests_spec.rb
We added the collapse feature also for project and package description.
=> Add collapsible for description

src/api/app/views/webui2/webui/patchinfo/show.html.haml
=> Fix description collapse on patchinfo show view

src/api/app/controllers/webui/staging/excluded_requests_controller.rb, src/api/app/datatables/excluded_request_datatable.rb, src/api/app/helpers/webui/staging/excluded_requests_helper.rb, src/api/app/views/webui2/webui/staging/excluded_requests/index.html.haml
Add Datatable and json endpoint for the Staging::ExcludedRequestsController
=> Add Datatables remote pagination to ExcludedRequestsController

src/api/app/models/comment.rb, src/api/app/presenters/comments_controller_presenters/comment_presenter.rb, src/api/app/views/comments/_comment.xml.builder, src/api/app/views/comments/index.xml.builder, src/api/spec/models/comment_spec.rb, src/api/spec/presenters/comments_controller_presenters/comment_presenter_spec.rb
Move model rendering to the view, lift some view code to a presenter, remove ```to_xml``` from the model, since it's not model responsibility to know how to render a view.
=> Use render partial to render a collection of comments

src/api/app/datatables/excluded_request_datatable.rb, src/api/app/views/webui2/webui/attribute/_form.html.haml, src/api/app/views/webui2/webui/attribute/new.html.haml, src/api/app/views/webui2/webui/staging/excluded_requests/_create_dialog.html.haml, src/api/app/views/webui2/webui/staging/excluded_requests/index.html.haml
Before:
After:
Before:
After:
Before:
After:
Before:
After:
=> A couple of smaller UI improvements

src/backend/bs_publish
Considered to be a test balloon atm ...
=> [backend] initial support of zypp services

src/api/app/controllers/webui/project_controller.rb, src/api/spec/controllers/webui/project_controller_spec.rb
=> Require login for edit_comment

src/api/test/functional/search_controller_test.rb
Otherwise it requires a user, which we don't want here
=> Don't store test package into backend

src/api/app/controllers/webui/request_controller.rb, src/api/spec/controllers/webui/request_controller_spec.rb
(did I mention I love this word plays)
=> Don't redirect to nobody's home

src/api/spec/controllers/webui/project_controller_spec.rb
=> Remove empty before block

src/api/app/models/bs_request.rb, src/api/app/models/bs_request_action.rb, src/api/spec/models/bs_request_action_spec.rb, src/api/test/fixtures/bs_request_actions.yml
The old code was a little hard to parse
=> Refactor is_target_maintainer

src/api/app/models/history_element.rb, src/api/app/views/webui2/webui/request/_request_history.html.haml, src/api/app/views/webui2/webui/request/_request_history_element.html.haml
=> Provide a link to user's home in request history list

src/backend/bs_publish
=> [backend] support binary tracking of appliances

src/api/app/views/webui/projects/maintained_projects/_create_dialog.html.haml, src/api/app/views/webui/projects/maintained_projects/_delete_dialog.html.haml, src/api/spec/bootstrap/features/webui/maintained_projects_spec.rb
Just reviewed and updated the texts used in the buttons to reflect the action being executed
=> Update text used in the modals

src/backend/BSProductXML.pm, src/backend/bs_srcserver
* Support fallback definitions of BSConfig
* Allow manual specification of url
coauthor: mls
=> [backend] getproductrepositories: support update url handling

src/api/Gemfile.lock
This should have been in the PR #7515 (commit fae7243)
=> Add missing Gemfile.lock changes

src/api/app/views/layouts/webui2/_login_form.html.haml, src/api/app/views/layouts/webui2/_personal_navigation.html.haml
The URL for the proxy login was wrongly constructed.
=> Fix url for proxy login in Bootstrap

src/api/app/views/webui/projects/maintenance_incidents/_incident_table_entries.html.erb
Bento part of 2cefd7abbbc8e3a which I forgot before.
=> Fix incident summary on index view, part II

src/backend/BSSched/BuildJob/Patchinfo.pm, src/backend/BSSched/Checker.pm, src/backend/BSXML.pm, src/backend/bs_repserver
=> write succeeded/failed into the package status instead of done

src/api/config/initializers/influxdb_dj_subscriber.rb
=> Escape a loop, not a method

src/api/app/models/concerns/staging_project.rb, src/api/app/models/obs_factory/obs_project.rb, src/api/app/models/obs_factory/staging_project.rb, src/api/app/models/project.rb, src/api/lib/backend/api/build_results/status.rb
=> Re-write build_succeed? method

src/backend/BSRunner.pm, src/backend/BSUtil.pm
=> BSRunner: do not wait 10 seconds between jobs

src/api/app/views/webui2/webui/package/_revision_diff_footer.html.haml, src/api/app/views/webui2/webui/package/_submit_request_dialog.html.haml, src/api/app/views/webui2/webui/package/rdiff.html.haml
=>  Fix link to submit/revert revision on revision diff view 

src/api/app/controllers/webui/architectures_controller.rb, src/api/app/controllers/webui/configuration_controller.rb, src/api/app/controllers/webui/repositories_controller.rb, src/api/spec/controllers/webui/architectures_controller_spec.rb, src/api/spec/controllers/webui/repositories_controller_spec.rb
=> Fix type / style of flash messages of succeeded requests

src/api/app/controllers/webui/request_controller.rb, src/api/app/models/bs_request.rb, src/api/app/views/webui/request/show.html.erb, src/api/app/views/webui2/webui/request/_review_tab.html.haml, src/api/app/views/webui2/webui/request/_show_side_links.html.haml, src/api/app/views/webui2/webui/request/show.html.haml, src/api/spec/models/bs_request_spec.rb, src/api/test/functional/request_controller_test.rb, src/api/test/unit/bs_request_test.rb
Move the important parts of webui_info into the controller, most work is still in webui_actions for now though
=> Reduce webui_infos usage in request controller

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/image_templates.js, src/api/app/assets/stylesheets/webui2/image_templates.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/image_templates_controller.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui2/webui/image_templates/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/image_templates/index.html.haml, src/api/spec/bootstrap/features/webui/image_templates_spec.rb, src/api/spec/cassettes/Bootstrap_ImageTemplates/branching/branch_Kiwi_image_template.yml, src/api/spec/features/webui/image_templates_spec.rb
We migrate Image Template view to Bootstrap
=> Migrate Image Template to Bootstrap

dist/obs-server.spec, src/backend/BSConfig.pm.template, src/backend/run-service-containerized
refactored shell based wrapper to perl
=> [backend] new wrapper script for docker jailed services

src/api/app/controllers/webui/kiwi/images_controller.rb, src/api/spec/controllers/webui/kiwi/images_controller_spec.rb
It saves a package, this shouldn't be allowed for nobody
=> kiwi import from package should require a login

ReleaseNotes-2.10, docs/api/api/api.txt, docs/api/api/binary_released.rng, docs/api/api/binary_released.xml, docs/api/api/obs.rng, src/api/app/controllers/source_controller.rb, src/api/app/models/binary_release.rb, src/api/app/models/project.rb, src/api/db/migrate/20190215131711_add_binary_id_tracking.rb, src/api/db/migrate/20190328131711_flavor_tracking.rb, src/api/db/structure.sql, src/api/lib/tasks/databases.rake, src/api/lib/xpath_engine.rb, src/api/spec/models/project_spec.rb, src/api/test/fixtures/binary_releases.yml, src/api/test/functional/binary_release_test.rb, src/api/test/functional/channel_maintenance_test.rb, src/api/test/functional/source_controller_test.rb, src/api/test/unit/binary_release.rb, src/backend/bs_publish
we merged an incomplete submission for container maintenance before.
these are the missing bits.
Reviewed together with Bjoern
This needs further review, just here for reference so far.
=> [api][backend] missing bits of binary_id tracking

docs/api/api/api.txt, src/api/app/controllers/person/token_controller.rb, src/api/app/controllers/trigger/errors.rb, src/api/app/controllers/trigger_controller.rb, src/api/app/models/token/rebuild.rb, src/api/app/models/token/release.rb, src/api/app/models/token/rss.rb, src/api/app/models/token/service.rb, src/api/app/models/user.rb, src/api/app/services/trigger_controller_service/token_extractor.rb, src/api/app/views/person/token/index.xml.builder, src/api/config/routes.rb, src/api/spec/cassettes/TriggerController/_rebuild/authentication_token_is_invalid/1_1_1_1.yml, src/api/spec/cassettes/TriggerController/_rebuild/when_token_is_valid_and_packet_rebuild/1_1_2_1.yml, src/api/spec/cassettes/TriggerController/_release/when_project_param_is_given/1_2_1_1.yml, src/api/spec/cassettes/TriggerController/_release/when_token_is_valid_and_package_exists/1_2_2_1.yml, src/api/spec/cassettes/TriggerController/_runservice/1_3_1.yml, src/api/spec/controllers/person/token_controller_spec.rb, src/api/spec/controllers/trigger_controller_spec.rb, src/api/spec/models/token/service_spec.rb, src/api/spec/services/trigger_controller_service/token_extractor_spec.rb, src/api/test/functional/source_controller_test.rb, src/api/test/functional/source_services_test.rb, src/api/test/functional/trigger_controller_test.rb
required for CR releases by automated testing and for openSUSE ports
co-maintainers
=> [api] support rebuild and release triggers

src/api/app/models/project.rb, src/api/app/models/staging/workflow.rb, src/api/app/models/user.rb, src/api/db/data/20170306084550_remove_duplicate_repositories.rb, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/spec/db/data/remove_duplicate_repositories_spec.rb, src/api/spec/factories/project.rb, src/api/spec/factories/staging_workflow.rb, src/api/spec/models/project/staging_project_spec.rb
This is similiar to #7581 but is a PR on its own so I can see what specs it breaks without risking the mergability of #7581
=> Make sure the projects factory sets a user for backend log

src/api/spec/bootstrap/features/webui/packages_spec.rb, src/api/spec/cassettes/Bootstrap_Packages/behaves_like_bootstrap_user_tab/group_roles/Add_an_existing_group.yml, src/api/spec/cassettes/Bootstrap_Packages/behaves_like_bootstrap_user_tab/group_roles/Add_non_existent_group.yml, src/api/spec/cassettes/Bootstrap_Packages/behaves_like_bootstrap_user_tab/group_roles/Add_role_to_group.yml, src/api/spec/cassettes/Bootstrap_Packages/behaves_like_bootstrap_user_tab/group_roles/Remove_role_from_group.yml, src/api/spec/cassettes/Bootstrap_Packages/behaves_like_bootstrap_user_tab/user_roles/Add_an_existing_user.yml, src/api/spec/cassettes/Bootstrap_Packages/behaves_like_bootstrap_user_tab/user_roles/Add_non_existent_user.yml, src/api/spec/cassettes/Bootstrap_Packages/behaves_like_bootstrap_user_tab/user_roles/Add_role_to_user.yml, src/api/spec/cassettes/Bootstrap_Packages/behaves_like_bootstrap_user_tab/user_roles/Remove_role_from_user.yml, src/api/spec/cassettes/Bootstrap_Packages/behaves_like_bootstrap_user_tab/user_roles/Remove_user_from_package_/_project.yml, src/api/spec/cassettes/Bootstrap_Packages/behaves_like_bootstrap_user_tab/user_roles/Viewing_user_roles.yml, src/api/spec/cassettes/Bootstrap_Packages/branching_a_package_from_another_users_project/with_AutoCleanup.yml, src/api/spec/cassettes/Bootstrap_Packages/branching_a_package_from_another_users_project/without_AutoCleanup.yml, src/api/spec/cassettes/Bootstrap_Packages/changing_the_package_s_devel_project.yml, src/api/spec/cassettes/Bootstrap_Packages/deleting_a_package.yml, src/api/spec/cassettes/Bootstrap_Packages/editing_a_package.yml, src/api/spec/cassettes/Bootstrap_Packages/log/download_logfile_succesfully.yml, src/api/spec/cassettes/Bootstrap_Packages/meta_configuration/as_admin/can_edit.yml, src/api/spec/cassettes/Bootstrap_Packages/meta_configuration/as_common_user/can_not_edit.yml, src/api/spec/cassettes/Bootstrap_Packages/requesting_package_deletion.yml
=> Fix flickering test issue 6034

dist/obs-server.spec, src/backend/BSConfiguration.pm, src/backend/BSNotify.pm, src/backend/BSRedis.pm, src/backend/BSRedisnotify.pm, src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Aggregate.pm, src/backend/BSSched/BuildJob/DeltaRpm.pm, src/backend/BSSched/Checker.pm, src/backend/BSSched/EventHandler.pm, src/backend/BSSrcServer/Notify.pm, src/backend/bs_dispatch, src/backend/bs_notifyforward, src/backend/bs_publish, src/backend/bs_redis, src/backend/bs_repserver, src/backend/bs_signer, src/backend/bs_srcserver, src/backend/bs_warden
=> send package status to a redis server if configured

src/backend/BSRedisnotify.pm, src/backend/BSSched/BuildResult.pm, src/backend/bs_redis, src/backend/bs_srcserver
=> project link instantiate: expand links

src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/views/webui2/webui/staging/projects/preview_copy.html.haml
=> Small staging related patches

src/api/app/models/bs_request.rb, src/api/spec/jobs/bs_request_action_webui_infos_job_spec.rb, src/api/spec/models/bs_request_spec.rb
=> Move method calls to callbacks

src/api/app/models/user.rb
This validation wasn't running before.
=> Fix state validation

src/api/app/models/binary_release.rb, src/api/app/models/bs_request.rb
=> Remove reset cache calls

src/api/app/assets/stylesheets/webui2/borders.scss, src/api/app/assets/stylesheets/webui2/search.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/request_controller.rb, src/api/app/helpers/webui/search_helper.rb, src/api/app/models/owner_search/base.rb, src/api/app/views/webui2/webui/search/_request_bugowner_change_dialog.html.haml, src/api/app/views/webui2/webui/search/_results_owner.html.haml, src/api/app/views/webui2/webui/search/owner.html.haml, src/api/spec/controllers/webui/search_controller_spec.rb, src/api/spec/helpers/webui/search_helper_spec.rb, src/api/spec/models/owner_search_spec.rb
Bento:
Bootstrap:
On desktop:
On mobile:
=> Migrate "Search Owners" Page to Bootstrap

src/api/app/views/webui2/webui/kiwi/images/_base_info.html.haml
=> Align 'Cloud Upload' icon on the Kiwi editor with other views

src/backend/BSConfig.pm.template, src/backend/bs_publish
[backend] add BSConfig variable for rsync options in publisher
=> [backend] add BSConfig variable for rsync options in publisher

src/backend/BSXML.pm
=> [backend] add approver to reques structure in BSXML

dist/Makefile, dist/obs-server.spec, dist/systemd/obsnotifyforward.service, dist/systemd/obsredis.service, src/backend/bs_notifyforward, src/backend/bs_redis
* lua has an argument count limit of 8000, so we cannot unpack
the ARGV table for large projects
* fix ipairs usage
* iterating over an array in chunks of two is hard
=> [backend] bs_redis: fix lua code

src/api/app/models/package.rb, src/api/spec/controllers/worker/command_controller_spec.rb, src/api/spec/factories/packages.rb, src/api/spec/lib/statistics_calculations_spec.rb
Now let the real fun start with user handling - everything else was just prep work :)
I put the exception outside the global_write_through so it's checking not just in real life, but also in the test suite
=> Make sure the packages factory sets a user for backend log

src/api/app/views/webui2/webui/cloud/ec2/configurations/_breadcrumb_items.html.haml
=> Add aria-current to cloud ec2 breadcrumbs

src/api/app/controllers/webui/cloud/azure/configurations_controller.rb, src/api/app/views/webui2/webui/cloud/azure/configurations/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/cloud/azure/configurations/show.html.haml
=> Migrate Microsoft Azure configuration page to Bootstrap

src/api/app/controllers/webui/cloud/upload_jobs_controller.rb, src/api/app/views/webui2/webui/cloud/upload_jobs/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/cloud/upload_jobs/index.html.haml
=> Migrate Cloud Upload page to Bootstrap

src/api/app/assets/javascripts/webui/application/kiwi_editor.js, src/api/app/assets/javascripts/webui2/kiwi_editor.js, src/api/app/controllers/webui/kiwi/images_controller.rb, src/api/app/views/webui2/webui/kiwi/images/_package_fields.html.haml, src/api/app/views/webui2/webui/kiwi/images/_packages.html.haml, src/api/app/views/webui2/webui/kiwi/images/_repositories.html.haml, src/api/app/views/webui2/webui/kiwi/images/_repository_fields.html.haml, src/api/config/routes.rb, src/api/spec/bootstrap/features/webui/kiwi/images_spec.rb, src/api/spec/cassettes/Bootstrap_Kiwi_Images/software_tab/add_repository_and_package.yml, src/api/spec/cassettes/Bootstrap_Kiwi_Images/software_tab/edit_package.yml, src/api/spec/cassettes/Bootstrap_Kiwi_Images/software_tab/edit_respository.yml, src/api/spec/support/capybara.rb
Fixed some bugs related with software tab:
* Package autocomplete
* Repository autocomplete
* Edit Package
* Edit Repository
=> Kiwi editor

src/backend/BSRPC.pm, src/backend/bs_notifyforward, src/backend/bs_redis, src/backend/bs_srcserver
=> implement multirequest mode for bs_notifyforward

src/api/app/mixins/webui/manage_relationships.rb, src/api/app/models/relationship.rb, src/api/app/models/relationship/add_role.rb, src/api/spec/models/relationship/add_role_spec.rb, src/api/spec/models/relationship_spec.rb, src/api/test/unit/package_test.rb
codeclimate said it takes 2 hours to fix, so I thought I try
=> Fix code duplication offense in relationship

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/_form.html.haml, src/api/app/views/webui2/webui/project/_new_project_modal.html.haml, src/api/app/views/webui2/webui/project/new.html.haml
=> Migrate new project view to bootstrap

src/api/app/controllers/trigger_controller.rb, src/api/spec/controllers/trigger_controller_spec.rb
Extract code from controller to a new method to simplify the controller.
=> Refactor method release. Extract code to external method

src/api/app/controllers/trigger_controller.rb
It is okay to trigger rebuild of a multibuild container when access to
main container got approved
Also specify explicit behaviour on service and release actions
=> Fix behaviour of triggering multibuild containers

src/api/app/controllers/webui/cloud/configurations_controller.rb
=> Remove unneeded condition in cloud configuration

src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml
=> Fix project breadcrumb for new projects

src/api/app/views/webui2/webui/main/_status_messages.html.haml
=> Consistent "Add status message"

src/api/app/views/webui2/shared/user_or_groups_roles/_delete_dialog.html.haml, src/api/app/views/webui2/webui/attribute/_delete_dialog.html.haml, src/api/app/views/webui2/webui/groups/index.html.haml, src/api/app/views/webui2/webui/groups/new.html.haml, src/api/app/views/webui2/webui/groups/show.html.haml, src/api/app/views/webui2/webui/kiwi/_tabs.html.haml, src/api/app/views/webui2/webui/kiwi/images/edit.html.haml, src/api/app/views/webui2/webui/monitor/_events.html.haml, src/api/app/views/webui2/webui/monitor/_workers_table.html.haml, src/api/app/views/webui2/webui/package/_delete_binaries_dialog.html.haml, src/api/app/views/webui2/webui/package/_delete_file_dialog.html.haml, src/api/app/views/webui2/webui/package/_files_view.html.haml, src/api/app/views/webui2/webui/package/_submit_request_dialog.html.haml, src/api/app/views/webui2/webui/patchinfo/edit.html.haml, src/api/app/views/webui2/webui/project/_project_packages.html.haml, src/api/app/views/webui2/webui/project/show.html.haml, src/api/app/views/webui2/webui/repositories/_delete_repository_modal.html.haml, src/api/app/views/webui2/webui/repositories/_delete_repository_path_modal.html.haml, src/api/app/views/webui2/webui/repositories/_request_delete_repository_modal.html.haml, src/api/app/views/webui2/webui/repositories/distributions.html.haml, src/api/app/views/webui2/webui/request/_add_reviewer_dialog.html.haml, src/api/app/views/webui2/webui/request/show.html.haml, src/api/app/views/webui2/webui/search/owner.html.haml, src/api/app/views/webui2/webui/staging/excluded_requests/_delete_dialog.html.haml, src/api/app/views/webui2/webui/staging/excluded_requests/index.html.haml, src/api/app/views/webui2/webui/staging/workflows/_delete.html.haml, src/api/app/views/webui2/webui/user/_involvement.html.haml
As the `content_for` helper is not inserting any content directly in the call, use `-` instead of `=` for calling the helper.
Also remove the parenthesis on all the calls of `content_for` with the `:ready_function` parameter, as it is more often used without parenthesis in the rest of the code.
=> Use content_for with running ruby code

src/backend/bs_notifyforward, src/backend/bs_redis, src/backend/bs_srcserver
=> redis/notifyforward: log if there is no progress sending data

src/api/config/feature.yml, src/api/lib/feature_switch/feature.rb
Adding this environment, we have more control about what we want to have
under the beta program.
=> Add beta environment for feature switch

src/api/app/assets/javascripts/webui2/datatables.js
=> Store the state of datatables forever

src/api/app/assets/javascripts/webui2/datatables.js
=> Set default page length of 25 for datatables

src/api/app/models/relationship/add_role.rb
The debug statement was discussed as code smell before,
so just remove it
@vpereira want co-author? :)
Fixes #7717
=> relationship/add_role: Remove troublesome debug output

src/api/app/views/webui2/webui/user/_info.html.haml
=> Fix usage of User to detect login

src/api/app/models/event/base.rb, src/api/app/models/user.rb
Both feel like left overs, '0wned' just appeared in my development log and scared and PCJ is some old debugging statement of mine that somehow was never removed
=> Remove 2 more old debug statements

README.md
I noticed this while writing the blog post for the beta of version 2.10.
=> Refresh the installation instructions in the README

src/api/app/assets/javascripts/webui2/request.js, src/api/app/controllers/webui/request_controller.rb, src/api/app/models/event/base.rb, src/api/app/models/user.rb, src/api/app/views/webui/request/_set_bugowner_request_dialog.html.erb, src/api/app/views/webui2/webui/main/_user_proceed-list.html.haml, src/api/app/views/webui2/webui/request/_add_reviewer_dialog.html.haml, src/api/app/views/webui2/webui/search/_request_bugowner_change_dialog.html.haml, src/api/app/views/webui2/webui/user/_info.html.haml, src/api/spec/bootstrap/features/webui/change_bugowner_spec.rb, src/api/spec/fixtures/files/owner_search_bugownership_collection.xml
=> Backport to 2.10

src/backend/bs_publish
=> [backend] support zchunk compression for rpm-md metadata

dist/schedule-obs.sh
=> Add 2.10 to OBS openQA job script

src/api/app/assets/stylesheets/webui2/monitor.scss, src/api/app/models/groups_user.rb, src/api/app/models/relationship.rb, src/api/app/models/review.rb, src/api/app/validators/allowed_user_validator.rb, src/api/app/views/webui2/webui/monitor/_workers_table.html.haml, src/api/spec/models/group_spec.rb, src/api/spec/models/relationship_spec.rb, src/api/spec/models/review_spec.rb
=> Backport avoid nobody and improve wokers on status monitor

src/api/app/controllers/webui/session_controller.rb, src/api/app/views/webui/session/_form.html.haml, src/api/app/views/webui2/webui/session/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/session/_form.html.haml, src/api/app/views/webui2/webui/session/new.html.haml, src/api/spec/features/webui/login_spec.rb, src/api/spec/support/features/features_authentication.rb, src/api/test/test_helper.rb
During the Bootstrap migration we forgot to migrate this page.
We also fixed the tests.
=> Migrate Session#new view to Boostrap

src/api/app/assets/javascripts/webui2/cm2/use-codemirror.js, src/api/app/assets/stylesheets/webui2/cm2.scss, src/api/app/assets/stylesheets/webui2/cm2/bootstrap.scss, src/api/app/views/webui2/webui/request/_sourcediff_tab.html.haml, src/api/app/views/webui2/webui/request/show.html.haml
Please refer to the commit messages/descriptions for details. Fixes #7752
Review link: https://obs-reviewlab.opensuse.org/dmarcoux-issue-7752/request/show/2
=> Fix for Request#show performance issue

src/api/app/assets/javascripts/webui2/cm2/use-codemirror.js, src/api/app/assets/stylesheets/webui2/cm2.scss, src/api/app/assets/stylesheets/webui2/cm2/bootstrap.scss, src/api/app/views/webui2/webui/request/_sourcediff_tab.html.haml, src/api/app/views/webui2/webui/request/show.html.haml
=> Backport PR 7790

README.md
=> Make installation instructions work again

src/api/app/controllers/webui/session_controller.rb, src/api/app/views/webui/session/_form.html.haml, src/api/app/views/webui2/webui/session/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/session/_form.html.haml, src/api/app/views/webui2/webui/session/new.html.haml, src/api/spec/features/webui/login_spec.rb, src/api/spec/support/features/features_authentication.rb, src/api/test/test_helper.rb
=> Backport Session#new view to Boostrap

src/api/app/views/layouts/webui2/_login_form.html.haml, src/api/app/views/layouts/webui2/_personal_navigation.html.haml, src/api/app/views/webui2/webui/comment/_new.html.haml, src/api/spec/cassettes/Sign_up/User_is_denied.yml, src/api/spec/features/webui/sign_up_spec.rb
Due a refactoring of the code the "Sign Up" and "Log In" links in the main page were not shown in some conditions.
Fixes #7829.
Co-authored-by: David Kang <dkang@suse.com> 
=> Fix "Sign Up" and "Log In" links in the main page

src/api/app/views/layouts/webui2/_login_form.html.haml, src/api/app/views/layouts/webui2/_personal_navigation.html.haml, src/api/app/views/webui2/webui/comment/_new.html.haml, src/api/spec/cassettes/Sign_up/User_is_denied.yml, src/api/spec/features/webui/sign_up_spec.rb
=> Fix "Sign Up" and "Log In" links in the main page (backport to 2.10)

src/api/app/views/webui2/webui/project/_monitor_control.html.haml, src/api/app/views/webui2/webui/project/monitor.html.haml
=> Bring the Last time results filter back to the monitor page

src/api/spec/bootstrap/features/webui/kiwi/images_spec.rb
We skip them temporary until we find a solution.
=> Skip kiwi flickering tests

src/api/db/migrate/20190704072437_add_column_in_rollout_to_users.rb, src/api/db/structure.sql
Needed for Rollout Program, used to move new features out of Beta
Program but make it available to users by batches.
=> Add migration for in_rollout field for users

dist/t/spec/features/0010_authentication_spec.rb, dist/t/spec/features/0030_project_spec.rb, dist/t/spec/features/0040_package_spec.rb, dist/t/spec/spec_helper.rb
=> Fix openqa test for 2.10

src/api/app/assets/stylesheets/webui2/cm2/bootstrap.scss
=> Add tab indicator in the codemirror stylesheet

src/api/app/controllers/webui/attribute_controller.rb, src/api/app/models/attrib.rb, src/api/test/functional/attributes_test.rb
The backend got not update on changed attribute values leading to a broken history
Fixes https://github.com/openSUSE/open-build-service/issues/7673
=> Fix attrib storage on changed value

src/backend/BSXML.pm
when requesting a diff in xml format
=> [backend] update BSXML to add sourcediff to request structure used

src/api/test/test_helper.rb, src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Import.pm, src/backend/BSSched/BuildJob/Upload.pm, src/backend/BSSched/Checker.pm, src/backend/BSSched/EventHandler.pm, src/backend/BSXML.pm, src/backend/bs_publish, src/backend/bs_repserver, src/backend/bs_sched, src/backend/bs_worker
=> Support generated build requires

ReleaseNotes-2.11, src/api/app/controllers/cloud/upload_jobs_controller.rb, src/api/app/controllers/webui/cloud/azure/configurations_controller.rb, src/api/app/controllers/webui/cloud/ec2/configurations_controller.rb, src/api/app/controllers/webui/cloud/upload_job/logs_controller.rb, src/api/app/controllers/webui/cloud/upload_jobs_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/cloud/configurations/index.html.haml, src/api/app/views/webui/cloud/upload_jobs/new.html.haml, src/api/app/views/webui/kiwi/images/_base_info.html.haml, src/api/app/views/webui/package/show.html.erb, src/api/app/views/webui2/webui/cloud/configurations/index.html.haml, src/api/app/views/webui2/webui/cloud/upload_jobs/new.html.haml, src/api/app/views/webui2/webui/kiwi/images/_base_info.html.haml, src/api/app/views/webui2/webui/package/_bottom_actions.html.haml, src/api/config/feature.yml, src/api/lib/feature_switch/obs_repository.rb, src/api/spec/controllers/cloud/upload_jobs_controller_spec.rb, src/api/spec/controllers/webui/cloud/azure/configurations_controller_spec.rb, src/api/spec/controllers/webui/cloud/azure/upload_jobs_controller_spec.rb, src/api/spec/controllers/webui/cloud/ec2/configurations_controller_spec.rb, src/api/spec/controllers/webui/cloud/ec2/upload_jobs_controller_spec.rb, src/api/spec/controllers/webui/cloud/upload_job/logs_controller_spec.rb, src/api/spec/controllers/webui/cloud/upload_jobs_controller_spec.rb
=> Remove cloud upload EC2 and Azure from Feature

contrib/git-diff-to-deploy
We switched from SP3 to SP4 and from 2.10 to 2.11
=> Adopt to production/O:S:U changes

src/api/app/models/user.rb
Added scopes to filter users in beta and rollout and improved rails dialect for scope `all_without_nobody`
=> Add scopes in_beta and in_rollout to User model

src/backend/bs_signer
Also sign the checksum data so that checkmedia can do an extra
verification step.
=> [backend] support iso partition checksums when signing isos

src/backend/BSPublisher/Container.pm, src/backend/bs_publish
=> [backend] fix publishing of containers when no registry is configured

src/api/lib/tasks/dev.rake
In the development environment we have Bootstrap feature globally enabled.
=> bootstrap enabled globally in development

src/api/lib/tasks/dev.rake
This way we can see the Bootstrap UI in our review app.
=> Enable Bootstrap feature in dev:development_testdata_create task

src/backend/BSSched/BuildJob.pm, src/backend/bs_publish
=> debian publish: fix BSUtil::cp call

src/api/app/assets/javascripts/webui2/cm2/use-codemirror.js, src/api/app/assets/stylesheets/webui2/cm2.scss, src/api/app/views/webui2/shared/_editor.html.haml, src/api/app/views/webui2/webui/package/_revision_diff_detail.html.haml
Commit taken from @hellcp 's #7924 pull request.
Fixes #7799.
=> Make editor big where needed

dist/obs-server.spec
=> Require perl-XML-Structured in the obs-server package

src/api/app/models/architecture.rb, src/api/app/models/attrib.rb, src/api/app/models/attrib_namespace.rb, src/api/app/models/attrib_type.rb, src/api/app/models/binary_release.rb, src/api/app/models/branch_package.rb, src/api/app/models/bs_request.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/bs_request_action_delete.rb, src/api/app/models/bs_request_action_maintenance_incident.rb, src/api/app/models/bs_request_action_maintenance_release.rb, src/api/app/models/bs_request_permission_check.rb, src/api/app/models/event/base.rb, src/api/app/models/event/build.rb, src/api/app/models/event/build_fail.rb, src/api/app/models/event/commit.rb
There is no need to make public all the methods of a class.
More pull requests like this one will come in the future.
=> Move methods only used in its own class to private 

dist/obs-server.spec
BACKPORT FROM master
From 2.9 to 2.10 obsapidelayed.service changed to
obs-api-support.target. The restart and enabling of obs-api-support.target
was tried in the post script. This is to late as the obsapidelayed.service
is already deinstalled at this point and the systemctl command will return
an error.
This change ensures that "systemctl is-enabled/is-active" will be executed
in the %pre section while upgrading the package and the state will be stored
files in the %_run_dir. In the %post section we check for this files and
try to enable/start obs-api-support.target.
=> [dist] fix for upgrade obs-api 2.9 to 2.10

src/api/app/models/issue.rb, src/api/spec/factories/issue.rb, src/api/spec/factories/issue_tracker.rb, src/api/spec/mixins/parse_package_diff_spec.rb, src/api/spec/models/issue_spec.rb, src/api/test/unit/attrib_test.rb
This patch is extension of PR#4128 in order to fix test failures.
Fixes #1215
=> [frontend] Add validation for Issue.name

CONTRIBUTING.md
Reverts two commits I pushed directly to master by mistake. Sorry for that :pray: And adds one commit instead with guidelines for our contributors to create a good pull request.
=> Add guidelines to create a good pull request

dist/cleanup_scm_cache.cron, dist/obs-server.logrotate, dist/obs-source_service.logrotate
=> some fixes to let logrotate pass again

src/api/app/presenters/obs_factory/staging_project_presenter.rb
New groups which are part of migration.
=> [frontend] Add origin-reviewers[-maintenance] as users icon in obs_factory.

.gitmessage
=> Add Daniel and Lukas in .gitmessage file

src/api/app/assets/stylesheets/webui2/bootstrap_variables/fonts.scss, src/api/app/assets/stylesheets/webui2/collapsible-text.scss, src/api/app/assets/stylesheets/webui2/comments.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/views/webui2/shared/_buildresult_box.html.haml, src/api/app/views/webui2/webui/comment/_reply.html.haml, src/api/app/views/webui2/webui/project/_buildstatus.html.haml
Improve readability by removing some small class modifiers
Some of the pages of the project have readability issues because the text is too
small. We removed the CSS classes to increase the size and improve on that.
=> Improve readability by removing some small class modifiers

src/api/app/views/webui2/shared/_editor.html.haml, src/api/app/views/webui2/shared/_editor_modal.html.haml
=> Typography - Editor

dist/obs-server.logrotate, dist/obs-server.spec, src/backend/Makefile
=> [dist] add '.log' to glob in obs-server.logrotate

dist/obs-server.logrotate, dist/obs-server.spec, src/backend/Makefile
=> Backport 210 fixlogrotate

dist/obs-server.spec
=> [dist] enable obs-api-support.target on update 

ReleaseNotes-2.11
To follow up on the discussion we had this morning in our review.
=> List colors adjustment in 2.11 release notes

src/api/app/views/webui2/webui/configuration/index.html.haml
=> Typography Configuration - label Configuration

CONTRIBUTING.md
=> Add guidelines to review a pull requets

src/api/app/views/webui2/webui/patchinfo/edit.html.haml, src/api/app/views/webui2/webui/patchinfo/form/_binaries.html.haml, src/api/app/views/webui2/webui/patchinfo/form/_block_release.html.haml, src/api/app/views/webui2/webui/patchinfo/form/_issues.html.haml
=> Typography patchinfo edit

src/api/app/views/webui2/webui/architectures/index.html.haml
=> Remove 'btn-sm' class from filter buttons

src/api/app/views/webui2/webui/interconnects/_interconnect_button.html.haml, src/api/app/views/webui2/webui/interconnects/new.html.haml
=> Address typography in interconnects

src/api/lib/obsapi/markdown_renderer.rb
=> Allow for displaying xml in the comments

dist/obs-bundled-gems.spec
This has been addressed upstream.
=> Remove work around for libsass

src/api/app/assets/stylesheets/webui2/collapsible-text.scss, src/api/app/assets/stylesheets/webui2/comments.scss
=> Deal with long words properly in all browsers

src/api/app/assets/stylesheets/webui2/comments.scss
=> Fix excessive padding in the comment

src/api/app/models/buildresult.rb, src/api/app/models/channel.rb, src/api/app/models/comment.rb, src/api/app/models/download_repository.rb, src/api/app/models/flag.rb, src/api/app/models/flag/validations.rb, src/api/app/models/group.rb, src/api/app/models/group_maintainer.rb, src/api/app/models/groups_user.rb, src/api/app/models/issue.rb, src/api/app/models/issue_tracker.rb, src/api/app/models/issue_tracker/cve_parser.rb, src/api/app/models/issue_tracker/issue_summary.rb, src/api/test/unit/issue_test.rb
There is no need to make public all the methods of a class, part II.
Continue the work started in #7980.
=> Move methods only used in its own class to private (II)

CONTRIBUTING.md
When we updated this section we forgot to change the link.
=> Fix link to how to review pull request

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/_create_package_form.html.haml, src/api/app/views/webui2/webui/project/_create_package_modal.html.haml, src/api/app/views/webui2/webui/project/new_package.html.haml
=> Backport project#new_package

src/api/spec/bootstrap/features/webui/factory_dashboard_spec.rb, src/api/spec/cassettes/FactoryDashboard/a_specific_staging_project/bento/behaves_like_bento_layout/images_and_title.yml, src/api/spec/cassettes/FactoryDashboard/a_specific_staging_project/bento/behaves_like_check_assets/imgs.yml, src/api/spec/cassettes/FactoryDashboard/a_specific_staging_project/status_messages_and_icons_classes.yml, src/api/spec/cassettes/FactoryDashboard/a_specific_staging_project/target_package_is_there.yml, src/api/spec/cassettes/FactoryDashboard/the_dashboard/bento/behaves_like_bento_layout/images_and_title.yml, src/api/spec/cassettes/FactoryDashboard/the_dashboard/bento/behaves_like_check_assets/imgs.yml, src/api/spec/cassettes/FactoryDashboard/the_dashboard/title_links_to_staging_projects.yml, src/api/spec/cassettes/FactoryDashboard/the_staging_projects/bento/behaves_like_bento_layout/images_and_title.yml, src/api/spec/cassettes/FactoryDashboard/the_staging_projects/bento/behaves_like_check_assets/imgs.yml, src/api/spec/cassettes/FactoryDashboard/the_staging_projects/it_has_a_link_to_staging_project.yml
The idea isn't to test the functionality per se but to make sure that removing bento won't break it. Therefore I'm testing for bento assets and bento layout elements
=> Add feature spec for Factory dashboard

src/backend/bs_repserver, src/backend/bs_signer
=> [backend] add support for appx signing

src/api/app/controllers/webui/users/announcements_controller.rb, src/api/app/views/webui/users/announcements/create.js.erb, src/api/app/views/webui/users/announcements/create.js.haml
Move the create action to bootstrap.
=> Move Webui::Users::AnnouncementsController to Bootstrap

src/backend/BSSrcServer/Service.pm
=> [backend] service expansion: tweak oldfiles handling

src/api/test/functional/webui/spider_test.rb
We no longer have a way to list all projects nor a way to list
all packages in projects without having javascript due to use
of ajax. This made the spider test a game of luck and certain
packages were only found if they were listed in requests or
rebuild graphs (as it happened in Eduardo's PR for some reason).
But to have reproducible result, it's important to crawl all
pages to find also those we don't normally test in rspec
=> Make the spider test crawl the sitemap (as good bots do)

src/api/app/models/event/request.rb, src/api/spec/cassettes/EventMailer/_event/for_an_event_of_type_Event_Request/when_source_project_does_not_exist/the_email_also_gets_delivered.yml, src/api/spec/mailers/event_mailer_spec.rb
=> Don't throw an exception on a rss notification when a source project can not be found

src/api/app/views/webui/search/owner.html.haml
The issue linked in the comment has been fixed.
=> Remove old irrelevant comment

src/api/app/helpers/webui/group_helper.rb, src/api/app/helpers/webui/user_helper.rb, src/api/app/views/webui/comment/_content.html.haml, src/api/app/views/webui/package/_commit_item.html.haml, src/api/spec/helpers/webui/user_helper_spec.rb
`image_tag_for` is the refactored version of `user_image_tag`.
=> Replace user_image_tag helper by image_tag_for

src/api/app/controllers/webui/user_controller.rb, src/api/app/controllers/webui/users_controller.rb, src/api/spec/controllers/webui/users_controller_spec.rb
Tasks done in this PR:
- Extend the UsersController spec
- Remove unused before_action on UserController
- Rename get_displayed_user to check_displayed_user on UsersController
- Rename UsersController#opt to UsersController#create_params
=> Clean-up UsersController, UserController and specs

src/api/app/views/webui/staging/workflows/edit.html.haml, src/api/app/views/webui/staging/workflows/show.html.haml
- Move 'Change Managers' link to staging_workflow#edit view
- Move links next to header on staging_workflow#show view
Closes #7354
=> Address Issue 7354

src/backend/bs_dodup, src/backend/bs_publish
=> bs_dodup: block all module packages for now

src/api/test/functional/maintenance_test.rb, src/backend/bs_publish
=> tag maintenance repositories

src/backend/bs_service
change default path for bs_service to "/srv/obs/service"
=> [backend] change bsdir for bs_service

src/api/app/views/webui/project/_tabs.html.haml
=> Link to the staging workflow for the 'Staging' tab in the context of a staging project

src/api/Gemfile, src/api/Gemfile.lock, src/api/app/controllers/application_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/config/initializers/influxdb_rails.rb
The latest beta covers everything we need, let's use it.
=> Switch back to upstream influxdb-rails

src/api/app/controllers/staging/staged_requests_controller.rb
Also error messages are thrown in case of a XML request with:
- empty body
- invalid XML
- no parseable requests' numbers
Fixes #7349.
=> Prevent crashing on empty body requests

src/api/app/models/obs_factory/staging_project.rb, src/api/app/views/webui/obs_factory/staging_projects/_infos.html.haml
Some helpers to migrate staging tools
=> obs_factory: support migration

src/api/app/controllers/staging/excluded_requests_controller.rb, src/api/app/controllers/staging/staging_controller.rb, src/api/app/controllers/staging/staging_projects_controller.rb, src/api/app/controllers/staging/workflows_controller.rb, src/api/spec/controllers/staging/excluded_requests_controller_spec.rb
This refactor is to be more consistent with the required parameters like `project` and `staging_workflow`. Now we don't need to define it in each controller.
=> Refactor Staging a little bit

src/api/app/controllers/staging/staged_requests_controller.rb, src/api/app/models/staging/staged_requests.rb
The model represents a StageRequest, something that we persist
StageRequest would be a good name for a Service, since it
represents better an Action
=> Rename StageRequest to StagedRequest

src/api/app/controllers/staging/backlog_controller.rb, src/api/spec/controllers/staging/backlog_controller_spec.rb
Continuing what we started in PR #8560
=> Refactor BacklogController

src/api/app/views/webui/users/_breadcrumb_items.html.haml
=> Add configuration breadcrumbs for User management

src/api/app/controllers/staging/workflows_controller.rb, src/api/spec/controllers/staging/workflows_controller_spec.rb
=> Delete all staging projects of a staging workflow when passing a param

src/api/app/models/branch_package.rb, src/api/app/models/branch_package/dry_run.rb, src/api/app/models/branch_package/errors.rb, src/api/app/models/branch_package/set_target_project.rb, src/api/spec/cassettes/BranchPackage_SetTargetProject/_auto_cleanup/with_target_project_and_autocleanup/1_3_1_1.yml, src/api/spec/cassettes/BranchPackage_SetTargetProject/_new/1_1_1.yml, src/api/spec/cassettes/BranchPackage_SetTargetProject/_target_project/when_request_is_provided/1_2_2_1.yml, src/api/spec/cassettes/BranchPackage_SetTargetProject/_target_project/when_target_project_is_provided/1_2_1_1.yml, src/api/spec/cassettes/BranchPackage_SetTargetProject/_valid_/invalid_name/1_4_2_1.yml, src/api/spec/cassettes/BranchPackage_SetTargetProject/_valid_/valid_name/1_4_1_1.yml, src/api/spec/models/branch_package/set_target_project_spec.rb, src/api/spec/models/branch_package_spec.rb
That's a first iteration on that "model". I want to break it in smaller classes, add specs to that and maybe in the near future merge it with `StagedRequests#link_package`
In This PR:
- Add new specs
- extract the `dryreport` and errors to its own modules
- extract the `set_target_project` method to its own class
=> Refactor BranchPackage model

docs/api/api/patchinfo.rng, src/api/app/models/patchinfo.rb, src/backend/BSSched/BuildJob/Patchinfo.pm, src/backend/BSXML.pm
=> [api][backend] support retracted state for updates

dist/obs-server.spec
for https://github.com/openSUSE/open-build-service/issues/3203
=> add zsync reccomends

src/api/app/controllers/webui/comments_controller.rb, src/api/spec/controllers/webui/comments_controller_spec.rb
=> Handle cases where commentable_type parameter is wrong

src/api/app/models/branch_package/lookup_incident_package.rb, src/api/spec/models/branch_package/lookup_incident_package_spec.rb
Fixes #8651 
Make sure that possible_package is never nil
=> Make sure that possible_package isn't nil

src/api/app/models/project.rb, src/api/spec/models/project_spec.rb
Refactored out some array building tasks, substituting it for enumerator operations and added specs for it.
=> Refactor project model arrays

src/backend/BSRepServer/Remote.pm, src/backend/BSSched/DoD.pm, src/backend/bs_getbinariesproxy, src/backend/bs_worker
=> Add missing module support

src/api/app/models/staging/staged_requests.rb, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/invalid_user/1_3_1_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_revoked_request/1_3_2_3_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_revoked_request/1_3_2_3_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_revoked_request/1_3_2_3_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_and_invalid_request_number/1_3_2_2_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_and_invalid_request_number/1_3_2_2_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_and_invalid_request_number/1_3_2_2_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_request_number/1_3_2_1_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/valid_staging_project_and_valid_user/with_valid_request_number/1_3_2_1_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/with_valid_staging_project_but_staging_project_is_being_merged/1_3_3_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/with_valid_staging_project_but_staging_project_is_being_merged/1_3_3_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/DELETE_destroy/with_valid_staging_project_but_staging_project_is_being_merged/1_3_3_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_and_invalid_request_number/1_2_3_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_and_invalid_request_number/1_2_3_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_5_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_5_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_5_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_valid_staging_project/1_2_5_4.yml
When staging a request, we have to take into account if there are more than one spec in the target package, and if there is, we should create the linking among them accordingly 
TODO:
=> Take local links into account when staging/unstaging requests

docs/api/api/api.txt
=> Fix typo in API docs

dist/obs-server.spec
or backend services will fail to load
=> [dist] require newer build script

src/api/app/models/staging/staged_requests.rb
=> Improve comment when unstaging a project

src/api/app/models/staging/staged_requests.rb, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/1_2_9_1_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/1_2_9_1_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/1_2_9_1_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/1_2_9_1_4.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/with_another_package/1_2_9_1_2_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/with_another_package/1_2_9_1_2_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/with_another_package/1_2_9_1_2_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/with_another_package/1_2_9_1_2_4.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/with_the_same_package/1_2_9_1_1_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/with_the_same_package/1_2_9_1_1_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_one_is_excluded_but_the_other_is_not/when_not_providing_the_remove_exclusion_parameter/1_2_9_2_1_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_an_excluded_request/when_providing_the_remove_exclusion_parameter/1_2_7_2_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_an_excluded_request/when_providing_the_remove_exclusion_parameter/1_2_7_2_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_an_excluded_request/when_providing_the_remove_exclusion_parameter/1_2_7_2_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_an_excluded_request/when_providing_the_remove_exclusion_parameter/1_2_7_2_4.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_delete_request/1_2_6_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_delete_request/1_2_6_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_delete_request/1_2_6_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_delete_request/1_2_6_4.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_non-existent_target_package/1_2_10_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_non-existent_target_package/1_2_10_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_non-existent_target_package/1_2_10_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_non-existent_target_package/1_2_10_4.yml, src/api/spec/controllers/staging/staged_requests_controller_spec.rb
=> Stage all requests, but only link submit requests

src/api/app/controllers/staging/excluded_requests_controller.rb, src/api/app/controllers/staging/staged_requests_controller.rb, src/api/app/controllers/staging/staging_controller.rb
At the moment we only check if the xml is present or is well formed.
The schema validation is planned for the future.
Fix #8756.
=> Add validation for xml on exclude requests

dist/obs-server.spec, src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Patchinfo.pm, src/backend/bs_sched, src/backend/bs_worker, src/backend/obs-ptf.spec
=> [backend] implement automatic ptf package generation

src/backend/bs_dispatch
1. fix entry without timestamp
2. print requested uri on getting rpc errors
=> bs_dispatch: Fix log output

src/backend/BSSched/BuildJob/Patchinfo.pm, src/backend/BSVerify.pm, src/backend/obs-ptf.spec
=> [backend] more tweaks to get ptf package builds running

src/api/spec/factories/attribs.rb
=> Store a timestamp of the past in the cleanup attribute

src/api/app/models/bs_request.rb, src/api/app/models/bs_request/errors.rb
Refactor the errors classes from `BsRequest`  to a related specific error module
=> Move BsRequest error classes to its own module

src/api/spec/cassettes/ChannelBinary/_create_channel_package_into/1_2_1.yml, src/api/spec/cassettes/ChannelBinary/_create_channel_package_into/1_2_2.yml, src/api/spec/cassettes/ChannelBinary/_find_by_project_and_package/1_1_1.yml, src/api/spec/cassettes/ChannelBinary/_find_by_project_and_package/1_1_2.yml, src/api/spec/factories/channels.rb, src/api/spec/models/channel_binary_spec.rb
Add specs for the model `ChannelBinary`
=> Add specs for ChannelBinary and related factories

src/api/app/views/webui/staging/workflows/_problems.html.haml
=> Avoid underflow of build problems to show

src/api/app/controllers/staging/staging_projects_controller.rb, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
Fixes #8806
Co-authored-by:@DavidKang
=> Allow staging managers to add staging projects

src/api/app/models/bs_request_action.rb, src/api/app/models/bs_request_action/errors.rb, src/api/app/models/project.rb, src/api/spec/cassettes/BsRequestAction/create_expand_package/Everything_should_work/1_8_2_1.yml, src/api/spec/cassettes/BsRequestAction/create_expand_package/Should_return_an_array/1_8_3_1.yml, src/api/spec/models/bs_request_action_spec.rb, src/api/spec/models/project_spec.rb
Refactor `create_expand_package` little bit and adding specs to it
=> Refactor BsRequestAction#create_expand_package

src/api/app/controllers/source_controller.rb, src/api/spec/cassettes/Undelete_Package/patchinfo_package/can_be_deleted_and_undeleted.yml, src/api/spec/cassettes/Undelete_Package/plain_package/can_be_deleted_and_undeleted.yml, src/api/spec/rails_helper.rb, src/api/spec/requests/package_undelete_spec.rb, src/api/spec/support/requests/requests_authentification.rb
=> [api] fix data inconsistency after package undelete

src/api/app/controllers/application_controller.rb
Intead of showing "You are not authorized to accept? this Project." show "You are not authorized to accept this Project."
Fixes #8846.
=> Fix error message of an 'accept' permission check

src/backend/bs_publish
to rename the isos but keep the -Media and not rename to -DVD
=> [backend] bs_publish introduce repotype sleimage-media

src/api/app/models/bs_request_action.rb
Codeclimate pointed out that the method `BsRequestAction#create_expand_package` is the most complext method. So to try to reduce it, I extracted some code blocks to methods
=> Extract code blocks from create_expand_package to separated methods

src/api/app/assets/javascripts/webui/patchinfo.js, src/api/app/controllers/webui/patchinfo_controller.rb
Also prevent error when issues are not present in the action's params.
Fixes #8872
=> Cancel Ajax call when there are only duplicated issues

src/api/app/models/issue_tracker.rb, src/api/db/migrate/20200107105426_add_jira_issue_kind.rb, src/api/db/structure.sql
=> add jira issue kind

src/backend/bs_mkarchrepo
=> [backend] support publishing of Arch zst

src/backend/BSConfig.pm.template, src/backend/BSUrlmapper.pm, src/backend/bs_publish
=> Publish redirect sync

src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/jobs/staging_project_accept_job.rb, src/api/app/models/concerns/staging_project.rb, src/api/app/models/project.rb, src/api/spec/cassettes/StagingProjectAcceptJob/_perform/when_the_staging_project_is_in_acceptable_state/should_remove_staging_project_log_entries/1_1_1_2_1.yml, src/api/spec/cassettes/StagingProjectAcceptJob/_perform/when_the_staging_project_is_in_acceptable_state/should_remove_staging_project_log_entries/1_1_1_2_2.yml, src/api/spec/cassettes/StagingProjectAcceptJob/_perform/when_the_staging_project_is_in_acceptable_state/staging_project_should_be_accepted/1_1_1_1_1.yml, src/api/spec/cassettes/StagingProjectAcceptJob/_perform/when_the_staging_project_is_in_acceptable_state/staging_project_should_be_accepted/1_1_1_1_2.yml, src/api/spec/cassettes/StagingProjectAcceptJob/_perform/when_the_staging_project_is_in_acceptable_state/staging_project_should_be_accepted/1_1_1_1_3.yml, src/api/spec/cassettes/StagingProjectAcceptJob/_perform/when_the_staging_project_is_in_acceptable_state/staging_project_should_be_accepted/1_1_1_1_4.yml, src/api/spec/cassettes/StagingProjectAcceptJob/_perform/when_the_staging_project_is_in_acceptable_state/staging_project_should_be_accepted/1_1_1_1_5.yml, src/api/spec/factories/project_log_entry.rb, src/api/spec/jobs/staging_project_accept_job_spec.rb
=> Clean up staging project history once it's accepted

src/backend/BSBearer.pm
fix broken access to the container registry
=> [backend] follow upstream registry rename of "token" to "access_token"

src/api/app/controllers/webui/staging/excluded_requests_controller.rb, src/api/app/controllers/webui/staging/projects_controller.rb, src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/datatables/excluded_request_datatable.rb, src/api/app/helpers/webui/staging/excluded_requests_helper.rb, src/api/app/views/webui/project/_tabs.html.haml, src/api/app/views/webui/staging/excluded_requests/_breadcrumb_items.html.haml, src/api/app/views/webui/staging/excluded_requests/_create_dialog.html.haml, src/api/app/views/webui/staging/excluded_requests/index.html.haml, src/api/app/views/webui/staging/projects/_breadcrumb_items.html.haml, src/api/app/views/webui/staging/projects/preview_copy.html.haml, src/api/app/views/webui/staging/workflows/_breadcrumb_items.html.haml, src/api/app/views/webui/staging/workflows/_create_staging_project.html.haml, src/api/app/views/webui/staging/workflows/_delete_staging_project_modal.html.haml, src/api/app/views/webui/staging/workflows/_empty_projects_list.html.haml, src/api/app/views/webui/staging/workflows/_infos.html.haml, src/api/app/views/webui/staging/workflows/_overall_state.html.haml, src/api/app/views/webui/staging/workflows/_staging_project.html.haml, src/api/app/views/webui/staging/workflows/show.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/staging/excluded_requests_controller_spec.rb, src/api/spec/controllers/webui/staging/projects_controller_spec.rb, src/api/spec/controllers/webui/staging/workflows_controller_spec.rb
Fixes #8791 
We are still have a lot of todo here:
TODO:
=> Fix url format for staging workflow

src/api/app/views/webui/project/_tabs.html.haml
Change the link in the `_tabs.html.haml` to use the project name instead of id in the url
=> Point Staging link to the Staging Workflow project

src/api/app/controllers/webui/staging/workflows_controller.rb
Use the same sort method that was used before for obs_factory.
Fixes #8680.
=> Sort staging projects in staging workflow show page

src/api/app/assets/stylesheets/webui/staging-workflow.scss, src/api/app/helpers/flag_helper.rb, src/api/app/helpers/webui/staging/workflow_helper.rb, src/api/app/views/webui/staging/shared/_legend.html.haml, src/api/lib/tasks/dev.rake
=> Pick less offensive colours for staged requests

src/backend/bs_publish
if a milestone is configured and sleimage is set.
=> [backend] also rename kiwi built images according milestone file

src/api/app/models/package.rb
Refactor `Package` model improving the ruby dialect
=> Package model cleanup

src/api/app/models/relationship.rb, src/api/app/queries/relationships_finder.rb
Extract query to a query object and refactor methods improving ruby dialect and removing repetitions.
=> Refactor relationship model

src/api/Gemfile.lock
=> Remove responders also from the lockfile

src/api/spec/factories/staging_workflow.rb
A project with a staging, staging projects and staged requests
=> Introduces full staging workflow factory

src/api/app/controllers/webui/monitor_controller.rb, src/api/app/services/monitor_controller_service/building_information_updater.rb, src/api/app/services/monitor_controller_service/status_history_fetcher.rb, src/api/spec/services/monitor_controller_service/building_information_updater_spec.rb
That's something that I had on my stash from last week and I would like to push it before start to work on the new deliverable.
Basically I started some refactoring on the `MonitorController` extracting some code to service objects. There are still some actions (like the `MonitorController#events` or partially the `MonitorController#index`) which should be extracted too but, I will do them in another PR later.
=> Refactor monitor controller into services

src/api/app/models/project.rb, src/api/app/queries/attrib_finder.rb, src/api/app/queries/autocomplete_packages_finder.rb, src/api/app/queries/autocomplete_projects_finder.rb, src/api/app/queries/obs_quality_categories_finder.rb, src/api/app/queries/open_requests_finder.rb, src/api/app/queries/open_requests_with_by_project_review_finder.rb, src/api/app/queries/open_requests_with_project_as_source_or_target_finder.rb, src/api/app/queries/projects_with_image_templates_finder.rb, src/api/app/queries/projects_with_very_important_attribute_finder.rb, src/api/spec/factories/attribs.rb, src/api/spec/queries/open_requests_with_by_project_review_finder_spec.rb, src/api/spec/queries/open_requests_with_project_as_source_or_target_finder_spec.rb, src/api/spec/queries/projects_with_image_templates_finder_spec.rb, src/api/spec/queries/projects_with_very_important_attribute_finder_spec.rb
In this PR, I really didn't try to refactor methods, instead I went for organizing it
- Pack all class methods together
- Pack all private methods together
- Extract repeated SQL queries to query objects
- Added specs for it
=> Refactor project model

src/backend/BSSched/BuildJob/KiwiProduct.pm
This makes a difference for maintenance repos where we use the
seen_binary hack to trim the binary list. The old code could end
up with a src rpm from some different higher-version package where
no binary rpm was used at all.
=> [backend] KiwiProduct: take all src rpms if we want one binary

KankuFile, dist/install_rh.sh, dist/obs-server.spec, dist/setup-appliance.sh, dist/t/0060-check_required_services.ts
=> Fix building and fedora

src/api/app/assets/javascripts/webui/responsive_ux.js, src/api/app/assets/stylesheets/webui/responsive_ux/_layout.scss, src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_navigation.html.haml
We added some small improvements like:
- Adjust flash for small viewports.
- Give active style when menus are open.
- Prevent scroll up when opening the menus.
=> Improve responsive_ux layout

src/api/app/models/architecture.rb, src/api/app/models/worker_status.rb, src/api/spec/models/worker_status_spec.rb
Among the changes we did:
- Substituted XmlParse for Nokogiri
- Use when possible XPATH search instead of loop through objects
- Extracted repeated code to a new method
- Improved ruby dialect
=> Refactor WorkerStatus model

src/backend/BSRPC.pm, src/backend/BSWatcher.pm
=> [backend] BSRPC: drop entries from the host lookup cache after a day

src/api/app/views/layouts/webui/_login_form.html.haml, src/api/app/views/layouts/webui/_personal_navigation.html.haml, src/api/app/views/webui/session/_form.html.haml, src/api/app/views/webui/session/new.html.haml
Recently, we added a new helper module regarding authentication
protocol.
=> Refactor login form

src/api/app/models/bs_request_action.rb, src/api/spec/cassettes/BsRequestAction/create_expand_package/Should_return_an_array/1_8_3_1.yml, src/api/spec/models/bs_request_action_spec.rb
Simple refactoring in one of the most problematic methods `create_expand_package`
=> Create expand package refactoring

src/api/app/assets/stylesheets/webui/responsive_ux/_layout.scss
=> Place editor header under the navbar

src/api/app/controllers/trigger_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/services/package_controller_service/rebuild_trigger.rb, src/api/spec/cassettes/Webui_PackageController/POST_trigger_rebuild/when_triggering_a_rebuild_fails/1_14_4_1.yml, src/api/spec/cassettes/Webui_PackageController/POST_trigger_rebuild/when_triggering_a_rebuild_fails/1_14_4_2.yml, src/api/spec/services/package_controller_service/rebuild_trigger_spec.rb
Move PackageCotnroller#trigger_rebuild logic to a Service object. 
Reuse the same service and authorization on the TriggerController#rebuild
=> Refactor PackageController#trigger_rebuild to a Service Object

src/api/app/assets/stylesheets/webui/search.scss
=> Increase size of search box and center it in smaller screens

src/api/config/routes/api_routes.rb, src/api/config/routes/webui_routes.rb
=> Move left api routes from webui to api definitions

.circleci/config.yml, dist/obs-server.spec, hakiri.yml, src/api/Gemfile, src/api/Gemfile.lock, src/api/config/brakeman.ignore
Background: https://brakemanscanner.org/blog/2018/06/28/brakeman-has-been-acquired-by-synopsys/
=> Use brakeman in circleci instead of relying on dead hakiri

docs/api/api/patchinfo.rng, src/api/app/models/patchinfo.rb
=> [api] support patchinfo category 'ptf'

src/backend/BSDBIndex.pm, src/backend/BSSrcServer/SQLite.pm, src/backend/BSXPath.pm, src/backend/BSXPathKeys.pm, src/backend/bs_publish, src/backend/bs_srcserver
Sending just the changed entries is not self-healing if something goes wrong. So always send the complete set of binaries.
=> Support sqlite as backend for the published database

src/api/app/views/webui/main/responsive_ux/_actions.html.haml, src/api/app/views/webui/project/_project_packages.html.haml, src/api/app/views/webui/project/responsive_ux/_actions.html.haml, src/api/app/views/webui/project/responsive_ux/actions/_delete_project.html.haml, src/api/app/views/webui/project/responsive_ux/actions/_edit_project.html.haml, src/api/app/views/webui/project/responsive_ux/actions/_gpg_key_ssl_certificate.html.haml, src/api/app/views/webui/project/responsive_ux/actions/_modify_project.html.haml, src/api/app/views/webui/project/responsive_ux/actions/_patchinfo.html.haml, src/api/app/views/webui/project/responsive_ux/actions/_report_bug.html.haml, src/api/app/views/webui/project/responsive_ux/actions/_request_role_addition_and_deletion.html.haml, src/api/app/views/webui/project/responsive_ux/actions/_request_to_release.html.haml, src/api/app/views/webui/project/responsive_ux/actions/_submit_as_update.html.haml, src/api/app/views/webui/project/responsive_ux/actions/_unlock_project.html.haml, src/api/app/views/webui/project/show.html.haml
On large devices:
On small devices:
=> Create actions menu for project#show

dist/setup-appliance.sh
This commit
* ensures that obssignd gets restarted after config changes
* changes checking of services from "chkconfig" to "systemctl"
chkconfig only works for sysV init scripts. As our service now
transferred to systemd we need to check with "systemctl"
=> [dist] fixes for setup-appliance.sh using systemctl

dist/setup-appliance.sh
=> Fix signd setup

src/api/app/models/user.rb, src/api/spec/factories/users.rb, src/api/spec/models/user_spec.rb
Add new scope to the `User` named ``recently_seen`  to find out the users list who are logged-in since 3 months
=> recently_seen scope

src/api/app/models/group.rb, src/api/app/models/user.rb, src/api/spec/models/notification_spec.rb
Add the basic Polymorphic relationship between `Notification`, `User` and `Group`
no migration is needed
=> Add polymorphic relationship between notifications users and groups

src/api/app/models/notification.rb, src/api/spec/factories/notification.rb, src/api/spec/models/notification_spec.rb
We are going to have a Job which from time to time will clean Notifications older than 3 months.
In this PR we handle the Notifications cleanup
=> Notifications cleanup

src/api/app/assets/javascripts/webui/buildresult.js, src/api/app/assets/stylesheets/webui/responsive_ux/_build-result.scss, src/api/app/views/webui/package/responsive_ux/_buildstatus.html.haml, src/api/app/views/webui/project/responsive_ux/_buildstatus.html.haml
=> Show buildresult information on hover info icon

src/api/app/assets/stylesheets/webui/responsive_ux.scss, src/api/app/assets/stylesheets/webui/responsive_ux/_layout.scss, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_nobody_navigation.html.haml
For the different viewports the height of the navbar wasn't the same.
Changing the size of the icons and other small adjustment, solve this
issue.
=> Fix navigation bar height

dist/obs-server.spec
Create an extra packge for XML::Structured DTD's from BSXML name OBS::XML
=> [dist] initial version of perl-OBS-XML

src/api/app/models/user.rb, src/api/spec/factories/users.rb
Add method User#away? to check if user didn't login in the last 3 months and add User factory `dead_user` to create a "away" confirmed user 
Extracted from #9237
=> Add method User#away? and update User factory dead_user

dist/obs-server.spec, src/backend/BSDB.pm, src/backend/BSRevision.pm, src/backend/BSSrcServer/LinkinfoDB.pm, src/backend/BSSrcServer/SQLite.pm, src/backend/BSXPath.pm, src/backend/BSXPathKeys.pm, src/backend/bs_admin, src/backend/bs_dbtool, src/backend/bs_srcserver, src/backend/t/0020-BSXPath.t, src/backend/t/0021-BSXPathKeys.t
=> Support storing the linkinfo database in sqlite

src/api/app/jobs/send_event_emails_job.rb, src/api/app/models/group.rb, src/api/app/models/notification.rb, src/api/spec/jobs/send_event_emails_job_spec.rb, src/api/spec/models/notification_spec.rb, src/api/test/fixtures/users.yml
To avoid unnecessary notifications and e-mails to been sent, check if the Notification#subscriber isn't away (subscriber didn't log-in within 3 months) 
User#away? -> check if user didn't log-in within 3 months 
Group#away? -> check if in the group all users didn't log-in withing 3 months
=> Create notifications if subscribe isn't away

docs/api/api/api.txt, docs/api/api/configuration.rng
- reword parts of the documentation of configuration.rng
- convert the documentation from xml comments to documentation elements
- expose the configuration route in the main api docs
This fixes #9119
=> Fix configuration docs

docs/api/api/api.txt, docs/api/api/directory.xsd
=> [backend] document commitfilelist command

dist/t/spec/features/0040_package_spec.rb, dist/t/spec/fixtures/hello_world.spec
=> Fix typo and license in the openqa specs

src/api/app/assets/stylesheets/webui/responsive_ux.scss, src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/models/notification.rb, src/api/app/policies/notification_policy.rb, src/api/app/presenters/notification_presenter.rb, src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_navigation.html.haml, src/api/app/views/webui/users/notifications/_breadcrumb_items.html.haml, src/api/app/views/webui/users/notifications/index.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/users/notifications_controller_spec.rb, src/api/spec/factories/notification.rb
=> Create User Notification View

src/api/app/views/webui/users/notifications/index.html.haml
=> Remove unneeded classes in notification list

src/api/Gemfile, src/api/Gemfile.lock, src/api/config/initializers/strong_migrations.rb, src/api/db/migrate/20180110074142_change_handler_to_longtext_in_delayed_jobs.rb, src/api/spec/db/data/remove_duplicate_repositories_spec.rb
Install https://github.com/ankane/strong_migrations and white list all
migrations before `20200318123203`
=> Add strong_migrations to our development environment

src/backend/bs_publish
=> [backend] bs_publish: also include vmx in regexp for renaming

dist/setup-appliance.sh
=> [dist] more messages in setup-appliance.sh for debugging

src/api/app/assets/stylesheets/webui/responsive_ux.scss
=> Fix build log status bar

docs/api/api/api.txt, src/backend/bs_admin
=> Minor debug and doc updates

dist/obs-apache24.conf
=> fix sending compressed assets in apache 2.4 config template

src/backend/BSDB.pm, src/backend/BSSrcServer/SQLite.pm, src/backend/bs_dbtool, src/backend/bs_srcserver
=> bs_dbtool: do not die right away if an entry could not be fetched

src/api/script/import_database.rb
We need to specify the environment to take the data from options.yml
file.
=> Fix import_database script

dist/setup-appliance.sh
fixes problem with rake command db:setup:
```
** Invoke environment
** Execute strong_migrations:safety_assured
rails aborted!
Set SAFETY_ASSURED=1 to run this task in production
```
=> [dist] fix db:setup in setup-appliance.sh

src/api/app/jobs/send_event_emails_job.rb, src/api/app/models/bs_request.rb, src/api/app/models/comment.rb, src/api/app/models/event/base.rb, src/api/app/models/event/comment_event.rb, src/api/app/models/event/request_create.rb, src/api/app/models/event/request_statechange.rb, src/api/app/models/event/review_wanted.rb, src/api/app/models/event_subscription.rb, src/api/app/models/notification.rb, src/api/app/models/package.rb, src/api/app/models/project.rb, src/api/app/models/review.rb, src/api/app/services/notification_creator.rb, src/api/spec/factories/notification.rb, src/api/spec/services/notification_creator_spec.rb
After some refactoring made on the Notifications code and database structure, some data had inconsistent values. So we are going to add some data migration to fix it.
This PR includes some refactoring we had to do in order to make it possible to create notifications from a data migration file. We also took the opportunity to give better names to some methods and improve the code a bit.
Having this refactoring, the next step will be adding the data migration, what will be done in a different PR.
=> Refactor notification's creation code

src/api/app/views/webui/users/notifications/index.html.haml
=> Display a message based on the context when there are no notifications

src/api/app/views/webui/users/notifications/index.html.haml, src/api/app/views/webui/users/notifications/responsive_ux/_actions.html.haml
Add actions menu to Notification page. Add option linking to manage the subscriptions
=> Add action menu to Notifications#index

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/views/webui/users/notifications/index.html.haml, src/api/spec/controllers/webui/users/notifications_controller_spec.rb
=> Rename "State Changes" filter to "Requests"

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/models/notification.rb, src/api/app/models/user.rb, src/api/app/queries/notifications_finder.rb, src/api/spec/db/data/remove_obsolete_notifications_spec.rb
Following up on [@vpereira's comment](https://github.com/openSUSE/open-build-service/pull/9377#pullrequestreview-392849173) in #9377
=> Use the Query Object pattern for notifications

src/api/lib/tasks/dev.rake
Add notifications of different types to the database.
Run this task with `rails "dev:notifications:data[3]"` replacing 3 with any number to indicate how many times you want this code to be executed.
=> Add task to create a bunch of notifications

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/_add_role_request_dialog.html.haml, src/api/app/views/webui/request/_change_devel_request_dialog.html.haml, src/api/app/views/webui/request/_delete_request_dialog.html.haml, src/api/spec/controllers/webui/request_controller_spec.rb, src/api/spec/features/webui/packages_spec.rb, src/api/spec/features/webui/requests_spec.rb
=> Rename identical IDs into unique IDs. Fixes #9331

src/backend/BSSched/Checker.pm
The opposite of onlybuild to blacklist builds of specific packages on project level.
=> excludebuild support in build config

src/api/app/presenters/notification_presenter.rb
=> Link to comment in notifications

src/api/app/views/webui/request/_sourcediff_tab.html.haml, src/api/app/views/webui/request/show.html.haml, src/api/app/views/webui/shared/_buildresult_box.html.haml
=> Display "Build Results"/"RPM Lint" from staging project for staged requests

src/api/app/controllers/webui/staging/workflows_controller.rb
Before, trying to list staging projects that had the state `:accepting` resulted in an exception.
Now, all the staging projects that have a known state are shown, including the `:accepting` state.
Fixes #9004.
=> Show staging projects in state 'accepting'

src/backend/BSXPathKeys.pm
=> [backend] BSXPathKeys: do not limit fetch() calls if cheapfetch is set

src/api/lib/tasks/dev.rake
Add some improvements to the notifications rake tasks.
- The Faker::Lorem.word starts to repeat words after a short while. This leads to validation errors, when creating the packages in the rake task. So both the current time and a counter has been used to get non-repeated names.
- Add a reason (comment) when creating a review, so they will have some text to show as excerpt.
- Ensure admin user has notifications via web enabled in the configuration.
- Create notifications for more than one project to have some options in the filter by project.
- Generates notifications for event type 'RequestStatechange'.
=> Add counter to notifications creation rake task

src/backend/BSPGP.pm, src/backend/BSSrcServer/SQLite.pm, src/backend/BSUtil.pm, src/backend/BSX509.pm
=> Support elliptic curve crypto in the BSPGP/BSX509 modules

ReleaseNotes-2.10.4, src/api/lib/obsapi/markdown_renderer.rb, src/api/spec/helpers/webui/markdown_helper_spec.rb
Backport #9546 from master to branch 2.10
=> Use Redcarpet Safe render to base OBS markdown render

src/api/spec/cassettes/ImageTemplatesBeta/branching/branch_Kiwi_image_template.yml, src/api/spec/cassettes/ImageTemplatesBeta/branching/branch_image_template.yml, src/api/spec/features/beta/webui/image_templates_spec.rb
=> Regenerate ImageTemplate cassettes

src/api/app/views/webui/package/show.html.haml
=> Fix package bottom action for non-beta user

src/api/app/controllers/source_controller.rb, src/api/app/controllers/trigger_controller.rb, src/api/app/helpers/maintenance_helper.rb, src/api/app/models/bs_request_action_maintenance_release.rb, src/api/app/models/project.rb, src/api/lib/backend/api/build/project.rb, src/api/spec/cassettes/Project/_do_project_release/uses_the_package_s_release_target_name_when_releasing_the_package.yml, src/api/spec/cassettes/TriggerController/_release/when_token_is_valid_and_package_exists/1_2_2_1.yml
Stuff you find in old unsubmitted commits while debugging breakages ....
Some code cleanup and more transparency for suspended projects.
=> Project suspend reason

src/backend/bs_signer
=> [backend] do not re-sign isos

src/api/app/controllers/webui/packages/branches_controller.rb
=> Enforce login for packages/branches_controller

src/backend/bs_publish
=> [backend] fix two more cases of missing .asc signature files in publihed repo

src/api/app/controllers/webui/request_controller.rb
See commit messages for details.
=> Refactor request_controller

src/api/app/views/layouts/webui/_footer.html.haml, src/api/app/views/layouts/webui/responsive_ux/_footer.html.haml, src/api/test/functional/webui/spider_test.rb
=> Make API documentation link relative

dist/obs-server.logrotate, dist/obs-server.spec, dist/systemd/obssourcepublish.service, src/backend/BSConfig.pm.template, src/backend/BSStdRunner.pm, src/backend/BSXML.pm, src/backend/bs_admin, src/backend/bs_publish, src/backend/bs_sourcepublish, src/backend/bs_srcserver, src/backend/bs_worker
Allows to specify an rsync module where sources gets published.
The structure is in $rsync/$project/$package/$srcmd5/ directory.
This can be derived from DISTURL from the binaries.
=> [backend] initial dedicated source publishing implementation

ReleaseNotes-2.10.6
Add release notes for release 2.10.6. We have two security issues which were fixed.
=> Add Release Notes for 2.10.6

dist/Makefile, dist/obs-server.spec, dist/setup-appliance.sh
=> [backend] install and package obssourcepublish.service

src/backend/bs_sourcepublish
Fix a couple of bugs and improve the style.
=> [backend] improve bs_sourcepublish code

src/backend/bs_sourcepublish
=> Fix source publishing to remote instance

contrib/git-diff-to-deploy
=> Update git-diff-to-deploy to use SLE_15_SP1

src/api/app/helpers/webui/projects/status_helper.rb, src/api/app/views/webui/projects/status/show.html.haml, src/api/spec/helpers/webui/projects/status_helper_spec.rb
Refactor the method `parse_status` extracting any instance variable usage from that and add specs for that
=> Parse status refactoring

README.md
The reference guide doesn't exist anymore, It was merged with into User
Guide.
=> Update link to User Guide

src/api/.haml-lint.yml, src/api/.rubocop_todo.yml, src/api/db/attribute_descriptions.rb, src/api/db/checker.rb, src/api/db/data/20190228170655_migrate_comment_payload.rb, src/api/db/data/20190307145633_migrate_rss_notification_payload.rb, src/api/db/data/20200326221616_regenerate_notifications.rb, src/api/db/data/20200424080753_generate_web_notifications.rb, src/api/db/migrate/20140213101042_add_admin_email_configuration.rb, src/api/db/migrate/20140908125426_convert_request_history.rb, src/api/db/migrate/20140916135426_project_maintains.rb, src/api/db/migrate/20151030130011_mark_events.rb, src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb, src/api/db/migrate/20180523123532_add_primary_key_to_data_migrations.rb, src/api/test/functional/interconnect_test.rb, src/api/test/functional/maintenance_test.rb, src/api/test/functional/published_controller_test.rb, src/api/test/functional/webui/spider_test.rb, src/api/test/node_matcher.rb, src/api/test/test_consistency_helper.rb, src/api/test/test_helper.rb, src/api/test/unit/schema_test.rb
I quickly realized in #9654 that it's going to be a nightmare to review a whopping 500+ changes in a single PR, so here's the first one.
I setup the exclusions and begin to autocorrect those nasty offenses.
=> Address RuboCop Layout/EmptyLineAfterGuardClause Offenses - Setup and First Fixes 

src/api/.rubocop_todo.yml, src/api/lib/api_error.rb, src/api/lib/authenticator.rb, src/api/lib/backend/api/build_results/binaries.rb, src/api/lib/backend/api/build_results/job_history.rb, src/api/lib/backend/api/cloud.rb, src/api/lib/backend/connection.rb, src/api/lib/backend/connection_helper.rb, src/api/lib/backend/file.rb, src/api/lib/backend/test.rb, src/api/lib/memory_debugger.rb, src/api/lib/opensuse/permission.rb, src/api/lib/opensuse/validator.rb, src/api/lib/rabbitmq_bus.rb, src/api/lib/tasks/delayed_job.rake, src/api/lib/tasks/extract.rake, src/api/lib/xpath_engine.rb, src/api/script/reformat_memprof, src/api/script/start_test_backend
=> Address RuboCop Layout/EmptyLineAfterGuardClause Offenses - script and lib

src/api/.rubocop_todo.yml, src/api/app/jobs/consistency_check_job.rb, src/api/app/jobs/project_create_auto_cleanup_requests.rb, src/api/app/jobs/send_event_emails_job.rb, src/api/app/jobs/update_backend_infos_job.rb, src/api/app/jobs/update_package_meta_job.rb, src/api/app/jobs/update_released_binaries_job.rb, src/api/app/mailers/admin_mailer.rb, src/api/app/mixins/build_log_support.rb, src/api/app/mixins/flipper_feature.rb, src/api/app/mixins/has_attributes.rb, src/api/app/mixins/has_relationships.rb, src/api/app/mixins/parse_package_diff.rb, src/api/app/mixins/webui/manage_relationships.rb
=> Address RuboCop Layout/EmptyLineAfterGuardClause offenses in app/{jobs,mailers,mixins}

src/api/.rubocop_todo.yml, src/api/app/helpers/authentication_protocol_helper.rb, src/api/app/helpers/event_mailer_helper.rb, src/api/app/helpers/flag_helper.rb, src/api/app/helpers/maintenance_helper.rb, src/api/app/helpers/model_helper.rb, src/api/app/helpers/validation_helper.rb, src/api/app/helpers/webui/buildresult_helper.rb, src/api/app/helpers/webui/maintenance_incident_helper.rb, src/api/app/helpers/webui/project_helper.rb, src/api/app/helpers/webui/projects/category_helper.rb, src/api/app/helpers/webui/request_helper.rb, src/api/app/helpers/webui/staging/project_helper.rb, src/api/app/helpers/webui/staging/workflow_helper.rb, src/api/app/helpers/webui/user_helper.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/services/notification_creator.rb, src/api/app/services/package_controller_service/rebuild_trigger.rb, src/api/app/services/package_controller_service/url_generator.rb, src/api/app/services/package_service/schema_verifier.rb, src/api/app/services/session_controller_service/session_creator.rb, src/api/app/services/staging/staging_project_validator.rb
=> Address RuboCop Layout/EmptyLineAfterGuardClause offenses in app/{helpers,services}

src/api/.rubocop_todo.yml, src/api/app/policies/application_policy.rb, src/api/app/policies/package_policy.rb, src/api/app/policies/project_policy.rb, src/api/app/policies/status/report_policy.rb, src/api/app/views/search/owner.xml.builder, src/api/app/views/source/_common_issues.xml.builder, src/api/app/views/source/_package_issues.xml.builder, src/api/app/views/statistics/latest_added.xml.builder, src/api/spec/db/data/migrate_comment_payload_spec.rb, src/api/spec/models/user_ldap_strategy_spec.rb
=> Address remaining RuboCop Layout/EmptyLineAfterGuardClause offenses

src/api/app/models/project/update_from_xml_command.rb, src/api/spec/models/project/update_from_xml_command_spec.rb, src/api/test/functional/source_controller_test.rb
It's not much, but it's at least a bit clearer now.
=> Improve error message in UpdateFromXmlCommand#update_path_elements

src/api/app/controllers/webui/projects/status_controller.rb, src/api/app/models/project_status/calculator.rb, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/1_2_1.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/1_2_2.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/1_2_3.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/1_2_4.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/pure_project/1_2_5_1.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/pure_project/1_2_5_2.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/pure_project/1_2_5_3.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/pure_project/1_2_5_4.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_initialize/1_1_1.yml, src/api/spec/models/project_status/calculator_spec.rb
Initial refactoring of the ProjectStatus stack (model, controller, helper, views). Remove repetition, add specs, make helper methods private and improve ruby dialect
=> Refactor ProjectStatusController and ProjectStatus::Calculator

src/api/Gemfile, src/api/Gemfile.lock, src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/stylesheets/webui/application.scss, src/api/app/controllers/application_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/app/views/layouts/webui/webui.html.haml, src/api/config/environments/development.rb, src/api/config/environments/production.rb, src/api/config/initializers/peek.rb, src/api/config/options.yml.example, src/api/config/routes.rb
=> Remove the peek gem

src/api/app/helpers/webui/projects/status_helper.rb, src/api/spec/helpers/webui/projects/status_helper_spec.rb
Instead of setting manually the icons everywhere, infer it from the
sortkey
=> Choose the icon based in the sortkey

src/api/.rubocop_todo.yml, src/api/spec/models/cloud/upload_job_spec.rb, src/api/spec/models/kiwi/image_spec.rb, src/api/spec/models/project_spec.rb, src/api/spec/models/review_spec.rb, src/api/spec/models/user_spec.rb
The remaining offenses for RSpec/PredicateMatcher will be corrected in the next PR.
=> Auto-correct RuboCop offenses for RSpec/PredicateMatcher

src/api/app/controllers/webui/projects/status_controller.rb, src/api/app/services/project_status_controller_service/attrib_values_finder.rb, src/api/app/services/project_status_controller_service/opensuse_upstream_tarball_url_finder.rb, src/api/app/services/project_status_controller_service/opensuse_upstream_version_finder.rb, src/api/app/services/project_status_controller_service/project_status_fail_comment_finder.rb, src/api/lib/api_error.rb
Move some repeated code to single fetcher services.
=> Project status controller service

src/api/.rubocop_todo.yml, src/api/app/controllers/configurations_controller.rb, src/api/app/controllers/services/webhooks_controller.rb, src/api/app/controllers/source_controller.rb, src/api/app/controllers/webui/attribute_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/patchinfo_controller.rb, src/api/app/controllers/webui/session_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/app/helpers/maintenance_helper.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/jobs/consistency_check_job.rb, src/api/db/migrate/20140908125426_convert_request_history.rb, src/api/db/migrate/20141125105426_add_github_issue_parser.rb, src/api/lib/memory_debugger.rb, src/api/lib/memory_dumper.rb, src/api/lib/xpath_engine.rb, src/api/script/reformat_memprof, src/api/script/start_test_backend, src/api/spec/factories/project.rb, src/api/test/node_matcher.rb
This reverts commit 2d48d8b62cda313f5df7b0a4ca4d494e44a5c5be, reversing changes made to 2e03a4caf6a92b1f94cab0f2678521d078eb27cd.
=> Revert "Merge pull request #9727 from dmarcoux/address-RuboCop-TODOs-18"

src/api/script/compare_structure_sql.sh
This should have been part of #9752
=> Add missing sed command for key charset

src/api/app/jobs/cleanup_notifications.rb, src/api/app/models/notification.rb, src/api/spec/models/notification_spec.rb
=> Delete CleanupNotifications job

src/api/app/queries/notifications_finder.rb, src/api/spec/factories/notification.rb
This is unused. Follow-up to #9785
=> Remove NotificationFinder#stale

src/api/app/models/history_element/base.rb, src/api/app/models/history_element/request_accepted.rb, src/api/app/models/history_element/request_all_reviews_approved.rb, src/api/app/models/history_element/request_declined.rb, src/api/app/models/history_element/request_deleted.rb, src/api/app/models/history_element/request_priority_change.rb, src/api/app/models/history_element/request_reopened.rb, src/api/app/models/history_element/request_review_added.rb, src/api/app/models/history_element/request_revoked.rb, src/api/app/models/history_element/request_set_incident.rb, src/api/app/models/history_element/request_superseded.rb, src/api/app/models/history_element/review_accepted.rb, src/api/app/models/history_element/review_assigned.rb, src/api/app/models/history_element/review_declined.rb, src/api/app/models/history_element/review_obsoleted.rb, src/api/app/models/history_element/review_reopened.rb
=> Update annotations on HistoryElement models

dist/t/Gemfile, dist/t/Gemfile.lock, dist/t/spec/features/0040_package_spec.rb, dist/t/spec/spec_helper.rb, dist/t/spec/support/capybara.rb
=> Fix smoke tests switching to apparition capybara driver

.circleci/config.yml, dist/obs-api-testsuite-rspec.spec, dist/setup-appliance.sh, src/api/lib/tasks/dev.rake, src/api/script/api_minitest.sh
Following up on the changes from #9790
=> Simplify rake db:* calls

src/api/app/views/webui/package/new.html.haml, src/api/app/views/webui/project/_form.html.haml
Autofocus on the first field on the new project form or new package form
=> Autofocus on first field for new project or new package

src/api/app/models/status_message.rb, src/api/db/migrate/20200626095558_remove_deleted_at_from_status_messages.rb, src/api/db/structure.sql
=> Remove deleted_at column from status_messages table

src/api/app/models/status_message.rb
This column was removed in #9840.
=> Stop ignoring status_messages.deleted_at

src/api/app/models/bs_request_action.rb
fixes a regression that releases happens into all target repositories
independend of trigger value. (since 504d33f7256)
=> [api] fix release request filtering

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/package/revisions.html.haml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_an_empty_revision_is_provided/1_9_2_1.yml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_an_empty_revision_is_provided/1_9_2_2.yml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_no_difference_in_sources_diff_is_empty/1_9_1_1.yml, src/api/spec/controllers/webui/package_controller_spec.rb
=> Auth changes for expensive package actions

src/backend/bs_admin, src/backend/bs_publish, src/backend/bs_sourcepublish
- fix filter handling
- add support for manual publishing via bs_admin
=> Fix source publish filtering

docs/api/api/obs.rng
=> [doc] add some comments for DoD schema

src/backend/call-service-in-docker.sh
=> [backend] fixed copy/paste error in call-service-in-docker.sh

src/api/app/controllers/webui/webui_controller.rb
This was an attempt to measure logins with proxy authentication based
on User.session. But User.session is a thread variable that is reset
after each request. So it's basically impossible to check based on this.
The user migh just have authenticated or we might just be on a new
thread ¯\_(ツ)_/¯
It also doesn't make much sense to measure :unauthenticated and
:disabled without measuring the rest of the case.
So let's stop measuring this at all until we find a better way.
For non-proxy auth this is still measured in Webui::SessionController.
=> Remove session tracking in proxy mode

src/backend/bs_worker
Like downloading sources or binary packages.
=> [backend] try to catch disk full errors in bs_worker tasks

ReleaseNotes-2.11
This should have been part of #9668
=> Remove reverted change from release notes

src/backend/BSContar.pm, src/backend/BSPublisher/Container.pm, src/backend/BSPublisher/Helm.pm, src/backend/BSPublisher/Registry.pm, src/backend/bs_publish, src/backend/bs_regpush
=> Support publishing of helm charts

docs/api/api/api.txt
=> document rest of arguments for cmd=diff

src/api/.rubocop.yml, src/api/app/controllers/application_controller.rb, src/api/app/controllers/concerns/rescue_handler.rb
To better organize the exceptions being caught by the `ApplicationController` move it to a `RescueHandler` concern
=> Move ApplicationController rescue_from blocks to a concern

src/api/.rubocop.yml, src/api/app/controllers/concerns/webui/rescue_handler.rb, src/api/app/controllers/webui/webui_controller.rb
Similar with PR #9995 but for Webui Exceptions
=> Move Webui::WebuiController rescue_from blocks to a concern

docs/api/api/binary_released.rng, src/api/app/models/binary_release.rb
=> Fixes and tracking extension for media

src/api/app/mixins/has_relationships.rb, src/api/app/models/relationship.rb, src/api/app/models/user.rb
Instead of use array manipulation, find the emails from bugowners via ActiveRecord.
To test it:
1) Go to https://obs-reviewlab.opensuse.org/vpereira-refactor_has_relationships/package/users/requestor_project/package_1597250507_1
2) Check if the email icon is pointing to an email address
=> Refactor has relationships

src/api/app/models/user.rb, src/api/app/queries/maintained_packages_by_user_finder.rb
- Improve SQL using [left_outer_joins](https://guides.rubyonrails.org/active_record_querying.html#left-outer-joins) active record interface
- Refactor complex query to a [Query Object](https://github.com/openSUSE/open-build-service/wiki/Software-Design-Patterns#query-objects)
- Add new maintainer to a package. It should show it right under Package > Users
=> Refactor method User#user_relevant_packages_for_status

src/backend/BSDispatcher/Constraints.pm, src/backend/testdata/constraint/tensorflow, src/backend/testdata/test_dispatcher, src/backend/testdata/workerinfo/large, src/backend/testdata/workerinfo/medium
=> [backend] fix memoryperjob dispatch constraints handling

src/api/app/assets/stylesheets/webui/responsive_ux/layout.scss, src/api/app/assets/stylesheets/webui/responsive_ux/sponsors.scss, src/api/app/views/layouts/webui/responsive_ux.html.haml, src/api/app/views/layouts/webui/responsive_ux/_footer.html.haml
=> Move footer legal to bottom

src/api/.rubocop_todo.yml, src/api/test/functional/request_controller_test.rb, src/api/test/test_helper.rb, src/api/test/unit/bs_request_test.rb, src/api/test/unit/package_test.rb, src/api/test/unit/project_test.rb, src/api/test/unit/user_test.rb
=> Auto-correct Rubocop Rails/AssertNot offenses

src/api/.rubocop_todo.yml, src/api/spec/support/database_cleaner.rb, src/api/test/functional/source_controller_test.rb
=> Correct Rubocop Style/ConditionalAssignment in specs and tests

src/api/.rubocop_todo.yml, src/api/app/controllers/application_controller.rb, src/api/app/controllers/message_controller.rb, src/api/app/controllers/person_controller.rb, src/api/app/controllers/search_controller.rb, src/api/app/controllers/statistics_controller.rb, src/api/app/controllers/status/checks_controller.rb, src/api/app/controllers/status/reports_controller.rb, src/api/app/controllers/webui/attribute_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/projects/pulse_controller.rb
=> Correct Rubocop Style/ConditionalAssignment in controllers I

src/api/.rubocop_todo.yml, src/api/app/policies/application_policy.rb, src/api/app/services/package_controller_service/url_generator.rb, src/api/app/views/models/_package.xml.builder, src/api/app/views/models/_project.xml.builder, src/api/db/migrate/20170704212201_increase_timestamp_precision.rb, src/api/lib/tasks/extract.rake, src/api/lib/xpath_engine.rb, src/api/script/import_database.rb, src/api/spec/factories/bs_requests.rb, src/api/spec/factories/packages.rb, src/api/spec/factories/project.rb, src/api/spec/features/webui/packages_spec.rb, src/api/spec/rails_helper.rb, src/api/test/functional/maintenance_test.rb, src/api/test/functional/published_controller_test.rb, src/api/test/functional/request_controller_test.rb, src/api/test/functional/webui/spider_test.rb, src/api/test/test_helper.rb, src/api/test/unit/schema_test.rb
=> Correct RuboCop Style/IfUnlessModifier offenses

src/api/app/models/branch_package.rb
No idea why this operation is in a transaction. But `Project.store`
runs in a nested transation then. If something goes wrong with `.store`
exceptions are ignored.
=> Stay away from nested transactions

src/api/.rubocop_todo.yml, src/api/app/controllers/search_controller.rb, src/api/app/controllers/source_controller.rb, src/api/app/controllers/statistics_controller.rb, src/api/app/controllers/webui/feeds_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/projects/rebuild_times_controller.rb, src/api/app/helpers/validation_helper.rb, src/api/app/lib/backend/file.rb, src/api/app/models/package.rb, src/api/app/models/project_log_entry.rb, src/api/app/models/service.rb, src/api/app/models/update_notification_events.rb, src/api/app/models/user.rb, src/api/app/models/user_ldap_strategy.rb, src/api/db/migrate/20140721112346_delayed_job_indexes.rb, src/api/lib/rabbitmq_bus.rb, src/api/lib/tasks/dev.rake, src/api/lib/tasks/extract.rake
=> Correct RuboCop Style/RescueStandardError offenses

src/api/.rubocop_todo.yml, src/api/app/models/branch_package.rb, src/api/app/models/bs_request.rb, src/api/app/models/bs_request/find_for/project.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/bs_request_action_submit.rb, src/api/app/models/event/base.rb, src/api/app/models/event/request.rb, src/api/app/models/group.rb, src/api/app/models/issue_tracker.rb, src/api/app/models/owner_search/assignee.rb, src/api/app/models/owner_search/container.rb, src/api/app/models/package.rb, src/api/app/models/package_build_status.rb, src/api/app/models/project.rb, src/api/app/models/unregistered_user.rb, src/api/app/models/user.rb, src/api/app/models/user_ldap_strategy.rb
=> Correct Rubocop Style/ConditionalAssignment in models II

src/api/.rubocop_todo.yml, src/api/app/views/message/_messages.xml.builder, src/api/app/views/models/_project.xml.builder
=> Correct Rubocop Style/ConditionalAssignment in views III

src/api/.rubocop_todo.yml, src/api/config/initializers/02_apiversion.rb, src/api/config/initializers/airbrake.rb, src/api/lib/rabbitmq_bus.rb, src/api/lib/tasks/extract.rake, src/api/lib/xpath_engine.rb
=> Correct Rubocop Style/ConditionalAssignment in config and lib IV

src/api/.rubocop_todo.yml, src/api/app/helpers/flag_helper.rb, src/api/app/models/bs_request.rb, src/api/lib/memory_debugger.rb, src/api/lib/tasks/extract.rake, src/api/script/reformat_memprof
=> Correct RuboCop Style/MultipleComparison offenses

src/backend/BSConfig.pm.template, src/backend/bs_srcserver
=> One slave less

src/backend/BSSrcServer/Signkey.pm, src/backend/BSXML.pm, src/backend/bs_srcserver
=> Add a recreatesslcert command

src/backend/bs_repserver
=> [backend] remove duplicated code in putjob()

src/backend/BSStdServer.pm
- add writer locking
- remove reader locking
- unlink the memoization file list instead of renaming it
- fix sizechange calculation if a file is changed
- simplify access functions
- do not set $memoize_fn in the AJAX process
=> [backend] tweak memoization code

src/api/app/models/bs_request_action.rb, src/api/test/functional/build_controller_test.rb
Test suite needs to ensure a scheduler state got written when reyling on it.
Also a crash fix when a state got not written yet.
=> Reliability fixes

src/backend/BSXML.pm, src/backend/bs_worker
=> [backend] include license in report files

src/api/app/models/project_status/calculator.rb, src/api/spec/cassettes/ProjectStatus/displays_the_expected_packages_in_the_results_table.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/pure_project/1_2_5_1.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/pure_project/1_2_5_2.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/pure_project/1_2_5_3.yml, src/api/spec/cassettes/ProjectStatus_Calculator/_calc_status/pure_project/1_2_5_4.yml, src/api/spec/features/beta/webui/projects_spec.rb, src/api/spec/features/webui/projects/status_spec.rb, src/api/spec/features/webui/projects_spec.rb
After introducing a wrong condition on [a refactoring](https://github.com/openSUSE/open-build-service/pull/9676/commits/551b27a47b7d059d6bbcc051a39d2a55a9737a36), the failed packages were not displayed in the project status list.
Fixes #9904
=> Fix the refactored condition for pure_project

src/backend/bs_repserver
=> Setrelease fixes

src/api/app/assets/stylesheets/webui/sticky-footer.scss
=> Remove unused class

src/backend/BSProductXML.pm
=> milestone product definition

src/backend/BSPublisher/Registry.pm, src/backend/BSSched/ProjPacks.pm, src/backend/BSTar.pm
=> publisher: get rid of uninitialized value warning

src/api/app/models/unregistered_user.rb, src/api/app/models/user.rb, src/api/db/migrate/20201013143657_add_biography_to_users.rb, src/api/db/migrate/20201014105103_backfill_add_biography_to_users.rb, src/api/db/schema.rb
We would like to allow the users to write a short biography about themself. The bio will be displayed in the redesigned profile page... coming soon. This PR only includes the migration.
=> Add biography for user profile

src/api/app/views/webui/kiwi/images/_base_info.html.haml, src/api/app/views/webui/kiwi/images/_preferences.html.haml, src/api/app/views/webui/main/_user_proceed-list.html.haml, src/api/app/views/webui/main/responsive_ux/_index_actions.html.haml, src/api/app/views/webui/user/_index_actions.html.haml
Before:
Now:
Before:
Now:
Before:
Now:
=> Align icons with obs patterns

src/api/app/controllers/webui/packages/files_controller.rb, src/api/app/models/package.rb, src/api/app/models/service.rb, src/api/spec/cassettes/Package/_save_file/calls_add_kiwi_import_if_filename_ends_with_kiwi_txz.yml, src/api/spec/cassettes/Package/_save_file/does_not_call_add_kiwi_import_if_filename_ends_not_with_kiwi_txz.yml, src/api/spec/cassettes/Service/_add_download_url/1_1_1.yml, src/api/spec/cassettes/Service/_add_kiwi_import/has_a_kiwi_import_service.yml, src/api/spec/cassettes/Service/_add_kiwi_import/posts_mergeservice.yml, src/api/spec/cassettes/Service/_add_kiwi_import/posts_runservice.yml, src/api/spec/cassettes/Service/_add_kiwi_import/posts_waitservice.yml, src/api/spec/cassettes/Service/_add_service/1_2_1.yml, src/api/spec/cassettes/Service/_add_service/1_2_2.yml, src/api/spec/cassettes/Service/_add_service/1_2_3.yml, src/api/spec/models/package_spec.rb, src/api/spec/models/service_spec.rb
- Rename methods from CamelCase to snake_case
- Add specs for the methods
- Refresh or generate new cassettes
- Remove debug information
=> Service model refactoring

src/api/app/models/service.rb, src/api/app/models/service/name_validator.rb, src/api/spec/cassettes/Service/_add_download_url/1_2_1.yml, src/api/spec/cassettes/Service/_add_download_url/1_2_2.yml, src/api/spec/cassettes/Service/_add_kiwi_import/has_a_kiwi_import_service.yml, src/api/spec/cassettes/Service/_add_kiwi_import/posts_mergeservice.yml, src/api/spec/cassettes/Service/_add_kiwi_import/posts_runservice.yml, src/api/spec/cassettes/Service/_add_kiwi_import/posts_waitservice.yml, src/api/spec/cassettes/Service/_add_service/1_3_1.yml, src/api/spec/cassettes/Service/_add_service/1_3_2.yml, src/api/spec/cassettes/Service/_add_service/1_3_3.yml, src/api/spec/models/service/name_validator_spec.rb, src/api/spec/models/service_spec.rb
Refactor Service model:
- extract name validation to an external class
- Add spec for the method `Service.verify_xml!`
- Refresh specs
=> Service name validation

src/api/app/models/service/name_validator.rb
Refactor `Service::NameValidator#valid_name?` method
=> Refactor Service::NameValidator#valid_name?

dist/obs-server.spec, src/backend/BSConfig.pm.template, src/backend/call-service-in-container
* replace docker containers by podman
* Performance improvement in our test cases approx 20-30%
* 2 new packages system-user-obsrun/system-user-obs-servicerun
=> Service in podman

src/api/app/assets/stylesheets/webui/application.scss, src/api/app/assets/stylesheets/webui/user_profile_redesign/user_profile.scss, src/api/app/controllers/webui/users_controller.rb, src/api/app/models/owner_search/owned.rb, src/api/app/models/package.rb, src/api/app/models/project.rb, src/api/app/models/user.rb, src/api/app/views/webui/user/user_profile_redesign/_involvement.html.haml, src/api/app/views/webui/user/user_profile_redesign/_involvement_and_activity.html.haml, src/api/app/views/webui/users/show.html.haml, src/api/spec/controllers/webui/users_controller_spec.rb, src/api/spec/models/user_spec.rb
=> User profile involved projects and packages revamp

src/api/app/jobs/old_status_history_cleaner_job.rb, src/api/app/jobs/status_history_rescaler_job.rb, src/api/config/clock.rb, src/api/spec/jobs/old_status_history_cleaner_job_spec.rb, src/api/spec/jobs/status_history_rescaler_job_spec.rb
Break the StatusHistoryRescalerJob in two and do the statistics using ActiveRecord
=> Refactor status history rescaler job

src/api/app/jobs/measurements_job.rb
=> Introduce metrics for users in rollout

src/backend/BSSched/Checker.pm, src/backend/BSSched/ProjPacks.pm, src/backend/bs_sched
=> Do a simplified setup if all packages are locked

src/api/app/jobs/measurements_job.rb
=> Introduce measurements for user states and user roles

src/api/spec/jobs/status_history_rescaler_job_spec.rb
- Add more cases to make sure that the scale is working as expected
=> Improve spec for StatusHistoryRescalerJob

src/api/app/jobs/measurements_job.rb, src/api/app/models/group.rb, src/api/app/models/notification.rb, src/api/app/models/user.rb, src/api/spec/models/user_spec.rb
This PR adds a new field in the users measurements to track the amount of logged in users in the last 5 minutes
=> Measure the amount of users logged in in the last 5 minutes

src/api/app/models/group.rb, src/api/spec/models/bs_request/find_for/group_spec.rb
Error Message if user not found:
Existing user:
=> Refactor Group model

src/api/app/views/webui/request/_request_comments.html.haml, src/api/app/views/webui/request/show.html.haml
Master: 
Avg (3 Requests): Duration: 1087.9ms | Allocations: 426595
Passing the association to the partial:
Avg (3 Requests): Duration: 908.8ms | Allocations: 302319
=> Pass the association to the partial instead of call it two times

src/api/spec/controllers/person/token_controller_spec.rb
=> Fix flickering spec for Person::TokenController#delete

src/backend/bs_srcserver
=> [backend] support build type 'flatpak'

src/api/app/controllers/webui/package_controller.rb
* Use guard clause instead of long condition blocks
* Extract complex ActiveRecord query to external method
=> Refactor PackageController#find_last_req method

src/api/test/functional/webui/spider_test.rb
also skip links to show home:Iggy/ToBeDeletedTestPack
=> Fix spider test

src/api/app/views/webui/request/responsive_ux/_actions.html.haml, src/api/app/views/webui/request/show.html.haml, src/api/spec/features/beta/webui/requests_spec.rb
=> Migrate 'Add a Review' action to the sidebar

src/api/app/assets/stylesheets/webui/user_profile_redesign/user_profile.scss, src/api/app/helpers/webui/webui_helper.rb
The commit adds the appropriate class to the body tag when
user_profile_redesign feature is enabled.
=> Set body class if user profile redesign is enabled

src/api/app/models/bs_request_action.rb
Need to take target repository into account when it exists or it can
break for release requests
=> [api] fix action uniqness check a bit

src/backend/BSSched/Checker.pm
We only did this for remote errors in the pdata (i.e. source expansion
errors), but not for the info (path expansion errors).
Also treat 5\d\d remote error as transient errors. They can be caused
by proxies that come before the remote instance. (See also the
code in BSSched::RPC::is_transient_error)
=> [backend] Checker: also add an retry event for remote errors in the info

src/api/app/views/webui/kiwi/images/_preferences.html.haml
=> Move "Edit Preferences" icon to bottom of Preferences, in Image Details

src/backend/BSSched/EventSource/Directory.pm, src/backend/BSSched/ProjPacks.pm, src/backend/BSXML.pm, src/backend/bs_publish, src/backend/bs_repserver, src/backend/bs_sched, src/backend/bs_signer
=> Improve backend statistics

src/backend/BSSrcServer/Service.pm, src/backend/bs_dispatch, src/backend/bs_servicedispatch
=> Log statistics in the dispatcher and service dispatcher

docs/api/api/api.txt, docs/api/api/buildresult.rng, docs/api/api/buildresult.xml, docs/api/api/buildstatus.rng, docs/api/api/buildstatus.xml, docs/api/api/jobstatus.rng, docs/api/api/jobstatus.xml, docs/api/api/obs.rng, src/backend/BSXML.pm
- add a schema for the `GET /build/<projectname>/_result` route
- correct `localbuild` -> `locallink`
=> [doc] Add resultslist schema

README.md
This PR contains subtle punctuation fixes and one sentence flow change to the README to improve readability of the content. There are no language updates, nor changes that alter the meaning of the text. If there is interest in further refining the specific language of the README, I can create a follow-on PR.
=> Miscellaneous punctuation updates to README 

src/backend/BSASN1.pm, src/backend/BSX509.pm
=> [backend] BSX509: add pack/unpack_sigalgo functions

docs/api/api/obs.rng, docs/api/api/tokenlist.rng, docs/api/api/tokenlist.xml, src/api/test/functional/backend_test.rb
This schema has been created by guessing, so it might be wrong and incomplete.
=> [doc] Add a schema of the tokenlist response

src/api/public/apidocs-new/components/responses/succeeded.yaml, src/api/public/apidocs-new/components/responses/unauthorized.yaml, src/api/public/apidocs-new/paths/about.yaml, src/api/public/apidocs-new/paths/group.yaml, src/api/public/apidocs-new/paths/group_group_title.yaml
These schemas (.xsd and .rng files) are currently used to validate both requests and responses.
For now we are defining OpenAPI schemas only to create examples, and we are not using OpenAPI schemas yet to validate bodies of requests or responses.
For example, this was the link added to the description of the response of the `/about` route:
=> Add links to schemas used for body validation

src/backend/BSSrcServer/Projlink.pm
This makes it possible to rebuild all packages from a project
link pointing to a maintenance incident project. The packages
are just hidden in the package list, i.e. source links to them
still work.
We can make the behaviour configurable if needed.
=> [backend] hide packages with incident suffix in project links

src/backend/BSSched/ProjPacks.pm
We tested for linked projects at the start of do_fetchprojpacks,
which created a race if the link information was updated while
the getprojpack rpc was running.
We now do the test after the getprojpack call returns.
We also add the linked packages we know about right away to
reduct the number of rpcs needed.
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-yo …
=> [backend] scheduler: move linked project check after getprojpack

src/api/app/controllers/person_controller.rb, src/api/config/routes/api_routes.rb, src/api/test/functional/person_controller_test.rb
=> Remove fake login endpoint in Person controller

src/api/public/apidocs-new/components/schemas/api_response.yaml, src/api/public/apidocs-new/paths/person_login_token.yaml
=> Document 'person/{login}/token' post method

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/person_login_group.yaml
=> Document 'person/{login}/group' endpoint

src/api/app/models/configuration.rb, src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/configuration.yaml, src/api/public/apidocs-new/paths/configuration.yaml
Document _GET configuration_ and _PUT configuration_ endpoints in the API new documentation.
=> Document configuration in the API new documentation

src/backend/BSSched/ProjPacks.pm
Changing the value auto-trigges deep checks of dependant projects.
=> [backend] support experimental "ExpandFlags: macroserial:YYY"

src/backend/bs_publish
these are currently unversioned and unsigned. That needs to change.
=> [backend] add flatpak publishing

src/api/public/apidocs-new/components/schemas/unregistered_person.yaml
Following up on [my comment](https://github.com/openSUSE/open-build-service/pull/10646#discussion_r563775612) in the PR #10646
=> Add example values to the unregistered_person schema

.circleci/config.yml, src/api/docker-files/Dockerfile
This is to have reproducible builds
It's not possible to add the gem to the Gemfile because brakeman's license forbids us from shipping the gem in our appliance.
=> Pin brakeman version

src/api/public/apidocs-new/components/schemas/about.yaml, src/api/public/apidocs-new/paths/person.yaml
Just a couple of missing pieces for the OpenAPI docs.
=> Add xml name to OpenAPI about schema

src/backend/bs_publish
to image endings list in mapsleimage
=> [backend] bs_publish: add vdi and vhdfixed

src/api/app/helpers/webui/request_helper.rb, src/api/spec/helpers/webui/request_helper_spec.rb
=> Add 'expand' parameter to the diffs

src/api/app/helpers/webui/webui_helper.rb
=> Fix typo in responsive_ux comment

dist/t/spec/spec_helper.rb
=> Add required files to fix OpenQA specs

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/projects/pulse_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/config/crawler-user-agents.json
This was never done after the initial commit. Should be done periodically somehow...
=> Update the list of crawlers

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/Bug_report.md
=> point to bugzilla and ml for content related topics

dist/t/spec/support/capybara.rb
We run into our own robot/spider protection otherwise.
=> Use a common http user agent

dist/t/spec/features/0040_package_spec.rb
=> Fix another typo in the smoketest

src/api/config/initializers/airbrake.rb
We can't do anything about them as they are about content in packages and projects.
Fixes #9717 
Fixes #9513 
Fixes #8199
=> Silence Backend::Errors on errbit

src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/views/webui/staging/workflows/_delete.html.haml, src/api/app/views/webui/staging/workflows/show.html.haml, src/api/spec/controllers/webui/staging/workflows_controller_spec.rb
Just something I've noticed while reviewing #10835.
- Use Bootstrap checkboxes (as defined in our patterns library)
- The label of checkboxes are now clickable (this is possible now that
each checkbox has a unique ID)
=> Improve staging workflow delete form

src/api/app/views/webui/staging/workflows/edit.html.haml, src/api/app/views/webui/staging/workflows/show.html.haml
=> Migrate staging workflow views out of responsive_ux

src/api/app/views/webui/users/notifications/index.html.haml
=> Use relative path for notifications partial

src/backend/BSSched/Checker.pm
=> [backend] missing mod check: fix unify usage, tweak message

src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/login-form.js, src/api/app/assets/stylesheets/webui/personal-navigation.scss
=> Remove remains of old login form

src/api/app/views/webui/feeds/notifications.rss.builder, src/api/spec/features/webui/users/user_home_page_spec.rb
See commit descriptions for details.
=> Remove 2 comments containing responsive_ux

.circleci/config.yml
Before, only tests under one subdirectory level were tested.
Fix the file pattern used to run the tests, and include all tests, independent of the subdirectory level.
=> Run all feature tests in CircleCI

src/api/app/views/webui/project/_basic_info.html.haml, src/api/app/views/webui/project/_show_actions.html.haml, src/api/app/views/webui/project/show_actions/_edit_project.html.haml, src/api/spec/cassettes/Projects/changing_project_title_and_description/when_accepting_the_changes/updates_the_project_title_description_and_url.yml, src/api/spec/cassettes/Projects/changing_project_title_and_description/when_cancelling_the_changes/renders_back_the_original_package_s_details.yml, src/api/spec/cassettes/Projects/changing_project_title_and_description/when_cancelling_the_changes/renders_back_the_original_project_s_details.yml, src/api/spec/features/webui/projects_spec.rb
Following the convention used for editing the details of a kiwi image, we're moving the "Edit Project" button close to the edited details.
**Before**
**After**
=> Move project edit action close to the target

src/api/app/views/webui/project/_basic_info.html.haml
=> Reduce excessive margin under project basic info

src/api/app/views/webui/user/_index_actions.html.haml, src/api/app/views/webui/user/user_profile_redesign/_basic_info.html.haml, src/api/app/views/webui/user/user_profile_redesign/_edit_account_form.html.haml, src/api/app/views/webui/user/user_profile_redesign/_info.html.haml, src/api/app/views/webui/users/update.js.haml
=> Move the user profile edit action close to the user details

src/backend/BSSched/ProjPacks.pm
Some buildflags change the dependency parsing so we have to do
a deep check if they are changed.
=> [backend] also check buildflags for critical changes

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui/shared/bs_requests/index.json.erb, src/api/spec/controllers/webui/project_controller_spec.rb
Follow-up improvements to #10961.
=> Requests improvements

src/backend/bs_getbinariesproxy
=> [backend] generate statistics for the getbinariesproxy

src/backend/bs_getbinariesproxy
=> [backend] bs_getbinariesproxy: also log prpa in statistics

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/workers_status.yaml, src/api/public/apidocs-new/paths/worker_status.yaml
=> Document `GET /worker/status` endpoint with OpenAPI

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/responses/execute_cmd_no_permission.yaml, src/api/public/apidocs-new/components/responses/illegal_request.yaml, src/api/public/apidocs-new/components/responses/resultlist.yaml, src/api/public/apidocs-new/components/responses/unknown_project.yaml, src/api/public/apidocs-new/components/schemas/resultlist.yaml, src/api/public/apidocs-new/paths/build.yaml, src/api/public/apidocs-new/paths/build_project_name.yaml, src/api/public/apidocs-new/paths/build_project_name_result.yaml
=> Add /build/* endpoints to swagger api docs

src/api/public/apidocs-new/OBS-v2.10.50.yaml
Provide an example of using request API endpoints by documenting the create submit request workflow.
=> Document create submit request workflow with OpenAPI

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/package_name.yaml, src/api/public/apidocs-new/components/schemas/buildhistory.yaml, src/api/public/apidocs-new/components/schemas/buildinfo.yaml, src/api/public/apidocs-new/components/schemas/buildstatus.yaml, src/api/public/apidocs-new/paths/build_project_repository_arch_package_buildinfo.yaml, src/api/public/apidocs-new/paths/build_project_repository_arch_package_history.yaml, src/api/public/apidocs-new/paths/build_project_repository_arch_package_log.yaml, src/api/public/apidocs-new/paths/build_project_repository_arch_package_status.yaml
This endpoint returns:
- the last build log 
- the build information
- the build status
- and the build history
for a specific artifact.
=> Document the build endpoint

src/api/public/apidocs-new/OBS-v2.10.50.yaml
=> Document "Add a Review" and "Approve a Submit Request" workflows with OpenAPI

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/file_name.yaml, src/api/public/apidocs-new/components/schemas/fileinfo.yaml, src/api/public/apidocs-new/paths/build_project_repository_architecture_package_file.yaml, src/api/public/apidocs-new/paths/build_project_repository_architecture_package_file_view_fileinfo.yaml
This endpoint, given a project, repository, architecture and package:
- Retrieves the given file's content
- Updates the given file's content
- Deletes the given file
=> Document build artifacts files endpoint

src/api/Gemfile, src/api/Gemfile.lock
Also remove the version constraint so depfu does this in the future.
=> Update influxdb-rails to version 1.0.2

src/api/spec/factories/tokens.rb, src/api/spec/policies/token/rebuild_policy_spec.rb
First commit regarding rebuild policy
=> First commit about rebuild token policy

src/api/app/models/token/release.rb
=> Fix linter for release

src/api/spec/cassettes/Token_RebuildPolicy/_create/create_/1_1_1_1.yml, src/api/spec/cassettes/Token_RebuildPolicy/_create/create_/1_1_1_2.yml, src/api/spec/factories/tokens.rb, src/api/spec/policies/token/rebuild_policy_spec.rb, src/api/spec/policies/token/release_policy_spec.rb
=> Working on the policies for rebuild and release

src/api/spec/controllers/trigger_controller_spec.rb
This PR fixes the Trigger Controller's spec failures regarding the `#release` method
=> Fix trigger controller's release method spec failures

src/api/app/controllers/trigger_controller.rb, src/api/spec/controllers/trigger_controller_spec.rb
Fix calling packageless tokens without parameters
Package.get_by_project_and_name will fail without parameters.
This also removes two controller specs that test authorize. But there is no
controller logic involved calling authorize. The policies are tested in policy specs.
Lets just make sure they are applied in every action.
=> Fix calling packageless tokens without parameters

src/api/app/controllers/trigger_controller.rb, src/api/app/models/token.rb, src/api/app/models/token/rebuild.rb, src/api/app/policies/token/rebuild_policy.rb, src/api/spec/factories/tokens.rb, src/api/spec/models/token/release_spec.rb, src/api/spec/policies/token/rebuild_policy_spec.rb, src/api/spec/policies/token/release_policy_spec.rb, src/api/spec/policies/token/service_policy_spec.rb
=> Bugfix 11035

src/api/app/jobs/project_create_auto_cleanup_requests_job.rb
The wording of the last sentence in the AutoCleanup message could be improved.
=> Cudos to Paul Fee for submitting his "feature request" on progress.opensuse.org.
=> Improve description of ProjectCreateAutoCleanupRequestsJob

src/api/Gemfile, src/api/Gemfile.lock, src/api/app/controllers/person/token_controller.rb, src/api/app/controllers/trigger_controller.rb, src/api/app/jobs/report_to_scm_job.rb, src/api/app/models/event_subscription.rb, src/api/app/models/token.rb, src/api/app/models/token/rebuild.rb, src/api/app/models/token/release.rb, src/api/app/models/token/rss.rb, src/api/app/models/token/service.rb, src/api/app/models/token/workflow.rb, src/api/app/services/scm_status_reporter.rb, src/api/config/initializers/zeitwerk.rb, src/api/db/migrate/20210428112249_add_token_id_to_event_subscriptions.rb, src/api/db/migrate/20210428122525_add_scm_token_to_tokens.rb, src/api/db/migrate/20210428132708_add_payload_to_event_subscriptions.rb, src/api/db/schema.rb, src/api/spec/controllers/person/token_controller_spec.rb
=> Workflow token vp

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Package.pm, src/backend/BSSched/Checker.pm, src/backend/BSSched/ProjPacks.pm, src/backend/BSSched/Remote.pm, src/backend/BSVerify.pm, src/backend/BSXML.pm, src/backend/bs_sched, src/backend/bs_srcserver, src/backend/bs_worker, src/backend/t/0001-BSVerify-verify_repo.t
=> Implement cross build support

src/api/app/models/token/workflow.rb, src/api/app/policies/token/workflow_policy.rb, src/api/app/services/trigger_controller_service/scm_extractor.rb
Also rename `extract` method to `call` and sort the pseudocode on Token#call.
=> Fix policy and extractor

src/api/app/controllers/trigger_workflow_controller.rb, src/api/app/models/token/workflow.rb, src/api/app/services/scm_status_reporter.rb
=> Token workflow update

src/api/app/services/scm_status_reporter.rb
Attending to Code Climate complains.
=> Reduce complexity of ScmStatusReporter#initialize

src/api/app/controllers/trigger_workflow_controller.rb, src/api/app/models/token/workflow.rb, src/api/app/services/trigger_controller_service/scm_extractor.rb
Add little improvements
- Drop unnecessary curly brackets from method parameters.
- Don't assign to variable values that are going to be used only once.
- Add .with_indifferent_access to SCMExtractor resulting payload.
- Adjust comments.
- Rename 'accepted*_event_and_action' to 'allowed*_event_and_action'
to be consistent with the constant names (ALLOWED_GITHUB_ACTIONS,
ALLOWED_GITLAB_ACTIONS).
=> Add little improvements

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/KiwiImage.pm, src/backend/BSSched/BuildJob/Package.pm, src/backend/BSSched/Checker.pm, src/backend/bs_publish, src/backend/bs_worker
=> Fix two bugs in the cross build code

src/api/app/services/trigger_controller_service/scm_extractor.rb, src/api/app/services/workflows/yaml_downloader.rb
=> Retrieve the workflows configuration file from the target branch

src/api/Gemfile, src/api/Gemfile.lock
The commits were cherry-picked from #11060 in order to merge changes which can already go on `master`. I reworded the commit for the `Down` gem to fix a typo in the commit message.
=> Add gems needed for OBS workflows

src/api/app/models/event_subscription.rb, src/api/app/models/token.rb, src/api/app/models/token/rebuild.rb, src/api/app/models/token/release.rb, src/api/app/models/token/rss.rb, src/api/app/models/token/service.rb, src/api/db/migrate/20210428112249_add_token_id_to_event_subscriptions.rb, src/api/db/migrate/20210428122525_add_scm_token_to_tokens.rb, src/api/db/migrate/20210428132708_add_payload_to_event_subscriptions.rb, src/api/db/schema.rb
The commits were cherry-picked from #11060 in order to merge changes which can already go on `master`. I had to fix some conflicts in the `db/schema.rb`, so this explains why the commit SHAs are different.
=> Add database migrations needed for OBS workflows

src/api/app/services/scm_status_reporter.rb, src/api/config/initializers/zeitwerk.rb
I added every person who did changes to the service as commit co-authors.
**TODO**:
=> Create SCMStatusReporter service

src/api/app/services/scm_status_reporter.rb
Taken from commit b373773 in PR #11060. Other parts of that commit are in #11099 and #11104.
=> Use GitHub repository full name from webhook payload

src/api/app/models/token.rb, src/api/app/models/token/workflow.rb
I added every person who did changes to the policy as commit co-authors.
=> Create Token::Workflow model

src/api/app/models/event_subscription.rb
=> Add scm channel to EventSubscription model

src/api/app/services/workflows/yaml_downloader.rb, src/api/config/initializers/zeitwerk.rb, src/api/spec/services/workflows/yaml_downloader_spec.rb
=> Create Workflows::YAMLDownloader service

src/api/app/models/workflow.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/spec/models/workflow_spec.rb
=> Create Workflow model

src/api/app/policies/token/workflow_policy.rb, src/api/spec/factories/tokens.rb, src/api/spec/policies/token/workflow_policy_spec.rb
I added every person who did changes to the policy as commit co-authors.
**TODO**:
=> Create Pundit policy for Token::Workflow

src/backend/bs_worker
=> [backend] fix building using docker VM

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/_review_tab.html.haml, src/api/spec/controllers/webui/request_controller_spec.rb
=> Replace "Disregard" by "Decline" in review button

src/api/app/views/webui/package/_buildstatus.html.haml
=> Add missing CSS word break in build results

src/api/app/controllers/trigger_controller.rb
Skip validation of params only if request comes from and supported SCM
(Taken from #11060 in order to merge changes which can already go on master.)
=> Refine validations related to SCM webhooks in trigger controller

src/api/app/models/workflow/step/branch_package_step.rb, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_github/and_the_payload_is_valid/1_2_1_1_1.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_github/and_the_payload_is_valid/1_2_1_1_2.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_github/but_we_don_t_provide_a_source_package/1_2_1_3_1.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_github/but_we_don_t_provide_source_project/1_2_1_2_1.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_gitlab/and_the_payload_is_valid/1_2_2_1_1.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_gitlab/and_the_payload_is_valid/1_2_2_1_2.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_gitlab/but_we_don_t_provide_a_source_package/1_2_2_3_1.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_gitlab/but_we_don_t_provide_a_source_project/1_2_2_2_1.yml, src/api/spec/models/workflow/step/branch_package_step_spec.rb
=> Create Workflow::Step::BranchPackageStep model

src/api/app/models/event_subscription.rb, src/api/app/models/token/workflow.rb, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitHub/behaves_like_successful_workflow_call/creates_a_new_Event_BuildFail_subscription.yml, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitHub/behaves_like_successful_workflow_call/creates_a_new_Event_BuildSuccess_subscription.yml, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitHub/behaves_like_successful_workflow_call/creates_a_new_branched_project_with_PR_suffix.yml, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitLab/behaves_like_successful_workflow_call/creates_a_new_Event_BuildFail_subscription.yml, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitLab/behaves_like_successful_workflow_call/creates_a_new_Event_BuildSuccess_subscription.yml, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitLab/behaves_like_successful_workflow_call/creates_a_new_branched_project_with_PR_suffix.yml, src/api/spec/factories/tokens.rb, src/api/spec/models/token/workflow_spec.rb, src/api/spec/support/files/invalid_steps_workflows.yml
Add some specs for the Token::Workflow model.
~DO NOT MERGE until #11110 is merged, I took the commit [f63282c](https://github.com/openSUSE/open-build-service/pull/11178/commits/f63282ce673585d1b4dde33569249f6b758d93c6) from there.~
=> Token.:Workflow model specs

src/api/app/controllers/trigger_controller.rb, src/api/app/models/token/release.rb, src/api/spec/cassettes/TriggerController/_set_multibuild_flavor/with_a_token_that_allows_multibuild/assigns_flavor_name.yml, src/api/spec/cassettes/TriggerController/_set_multibuild_flavor/with_a_token_that_allows_multibuild/authorizes_package_object.yml, src/api/spec/cassettes/TriggerController/_set_multibuild_flavor/with_a_token_that_does_not_allow_multibuild/raises_not_found.yml, src/api/spec/controllers/trigger_controller_spec.rb
=> [api] fix releaseing multibuild container

src/backend/BSRepServer/Registry.pm, src/backend/bs_dodup
=> [backend] autoprefix container repo with library/ for docker.io

CONTRIBUTING.md, README.md, SUPPORT.md, src/api/public/402.html, src/api/public/403.html, src/api/public/404.html, src/api/public/408.html, src/api/public/500.html, src/api/public/503.html
=> Going Libra.Chat, following openSUSE project

src/api/app/controllers/application_controller.rb, src/api/app/lib/suse/validator.rb, src/api/app/models/project/remote_url.rb
While working on some feature relating to `Distribution` those helped me to understand what is going on with the validator and fetching files from the interconnect.
=> More debug logging

src/api/app/models/workflow/step/branch_package_step.rb, src/api/spec/models/workflow/step/branch_package_step_spec.rb
=> Take user from token in BranchPackageStep.target_project

src/api/app/helpers/webui/user_helper.rb, src/api/app/views/webui/user/user_profile_redesign/_involvement.html.haml
Filter message was hardcoded and was showing the wrong text.
Fixes #10811
=> Fix filter text for involved projects/packages

src/api/.rubocop.yml, src/api/config/initializers/assets.rb, src/api/config/initializers/backtrace_silencers.rb, src/api/config/initializers/filter_parameter_logging.rb, src/api/config/initializers/wrap_parameters.rb, src/api/config/puma.rb
Getting closer to updating Rails version to 6.1.x. It's expected that the CI check `next_rails` is still failing. Those failures will be fixed in other PRs.
See commit messages for details on the changes.
=> More changes from the Rails' update task

.obs/workflows.yml
Setting up the integration between OBS and Github as described here:
https://openbuildservice.org/2021/05/31/scm-integration/
=> Enable integration between OBS and Github

src/api/app/assets/javascripts/webui/request.js
Add a unique class to handle click events on bs_request_action show tabs.
Fixes #11289
=> Add a unique class to handle click events

src/api/app/assets/javascripts/webui/request.js, src/api/app/views/webui/request/show.html.haml
Remove hardcoded path and use data variable to get URL.
=> Move url to data variable

src/api/app/controllers/webui/users/patchinfos_controller.rb, src/api/app/policies/users/patchinfos_policy.rb, src/api/spec/controllers/webui/users/patchinfos_controller_spec.rb, src/api/spec/policies/users/patchinfos_policy_spec.rb
Fixes #11305
Same approach as in #10256
=> Require login for Webui::Users::PatchinfosController

src/api/app/models/relationship.rb, src/api/app/queries/relationships_finder.rb, src/api/db/seeds.rb, src/api/spec/models/relationship_spec.rb
=> Fix Relationship.forbidden_project_ids for groups

src/api/app/models/token/errors.rb, src/api/app/models/token/workflow.rb, src/api/app/services/workflows/yaml_downloader.rb, src/api/spec/cassettes/Token_Workflow/_call/when_the_workflows_yml_do_not_exist_on_the_reference_branch/raises_an_Invalid_workflow_step_definition_error.yml, src/api/spec/controllers/trigger_workflow_controller_spec.rb, src/api/spec/models/token/workflow_spec.rb
=> raise if yaml file doesn't exist

src/api/app/jobs/worker_measurements_job.rb, src/api/app/models/worker_status.rb, src/api/config/clock.rb, src/api/spec/models/worker_status_spec.rb, src/api/test/unit/worker_status_test.rb
There is lots of interesting information about the workers, job pool and schedulers in here.
Also simplifies the caching strategy a bit. It didn't make much sense before.
~~And improves `Rabbitmq` performance.~~
=> Worker metrics

.obs/workflows.yml
Factory for the future, SLES for production, Leap for the appliance.
=> Adopt OBS repositories we CI

dist/obs-server.spec, dist/setup-appliance.sh, dist/system-user-obsrun.conf, dist/system-user-obsservicerun.conf, dist/systemd/obs-clockwork.service, dist/systemd/obs-delayedjob-queue-consistency_check.service, dist/systemd/obs-delayedjob-queue-default.service, dist/systemd/obs-delayedjob-queue-issuetracking.service, dist/systemd/obs-delayedjob-queue-mailers.service, dist/systemd/obs-delayedjob-queue-project_log_rotate.service, dist/systemd/obs-delayedjob-queue-quick@.service, dist/systemd/obs-delayedjob-queue-releasetracking.service, dist/systemd/obs-delayedjob-queue-scm.service, dist/systemd/obs-delayedjob-queue-staging.service, dist/systemd/obs-sphinx.service, dist/systemd/obsapisetup.service, dist/t/0060-check_required_services.ts
* change system-user-* to new mechanism
* Redirect error message in setup-appliance.sh db:migrate as it`s only used for testing and may fail on first startup
* Do not run setup-appliance.sh parallel
*
=> Improve setup appliance

dist/setup-appliance.sh
Improve legibility of the code.
Follow up on #11337.
=> Invert negated condition and swap branches

src/api/app/jobs/report_to_scm_job.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/services/workflows/filter.rb, src/api/spec/jobs/report_to_scm_job_spec.rb, src/api/spec/models/workflow/step/branch_package_step_spec.rb, src/api/spec/services/workflows/filter_spec.rb
We totally overlooked that in #11318 :man_facepalming: :woman_facepalming:
=> Report only for architectures/repositories matching workflow filters

src/api/app/jobs/worker_measurements_job.rb
- Drop measurement of individual jobs, progression doesn't provide much value and we already track performance with build events
- Use single field measurement, they are easier to plot
- Do not send 0 value measurements
- Use value as field name, it's default in grafana
=> Correct queue measurements

src/api/app/controllers/search_controller.rb, src/api/spec/cassettes/SearchController/search_for_package_ids/authenticated/behaves_like_find_package/1_4_2_1_1.yml, src/api/spec/cassettes/SearchController/search_for_package_ids/authenticated/behaves_like_find_package/1_4_2_1_2.yml, src/api/spec/cassettes/SearchController/search_for_package_ids/authenticated/behaves_like_find_package/1_4_2_1_3.yml, src/api/spec/cassettes/SearchController/search_for_package_ids/authenticated/behaves_like_find_package/1_4_2_1_4.yml, src/api/spec/cassettes/SearchController/search_for_package_ids/authenticated/behaves_like_find_package/1_4_2_1_5.yml, src/api/spec/cassettes/SearchController/search_for_package_ids/behaves_like_find_package/1_4_1_1.yml, src/api/spec/cassettes/SearchController/search_for_package_ids/behaves_like_find_package/1_4_1_2.yml, src/api/spec/cassettes/SearchController/search_for_packages/authenticated/behaves_like_find_package/1_3_2_1_1.yml, src/api/spec/cassettes/SearchController/search_for_packages/authenticated/behaves_like_find_package/1_3_2_1_2.yml, src/api/spec/cassettes/SearchController/search_for_packages/authenticated/behaves_like_find_package/1_3_2_1_3.yml, src/api/spec/cassettes/SearchController/search_for_packages/authenticated/behaves_like_find_package/1_3_2_1_4.yml, src/api/spec/cassettes/SearchController/search_for_packages/authenticated/behaves_like_find_package/1_3_2_1_5.yml, src/api/spec/cassettes/SearchController/search_for_packages/behaves_like_find_package/1_3_1_1.yml, src/api/spec/cassettes/SearchController/search_for_packages/behaves_like_find_package/1_3_1_2.yml, src/api/spec/cassettes/SearchController/search_for_project_ids/authenticated/behaves_like_find_project/1_2_2_1_1.yml, src/api/spec/cassettes/SearchController/search_for_project_ids/authenticated/behaves_like_find_project/1_2_2_1_2.yml, src/api/spec/cassettes/SearchController/search_for_project_ids/authenticated/behaves_like_find_project/1_2_2_1_3.yml, src/api/spec/cassettes/SearchController/search_for_project_ids/authenticated/behaves_like_find_project/1_2_2_1_4.yml, src/api/spec/cassettes/SearchController/search_for_project_ids/behaves_like_find_project/1_2_1_1.yml, src/api/spec/cassettes/SearchController/search_for_project_ids/behaves_like_find_project/1_2_1_2.yml, src/api/spec/cassettes/SearchController/search_for_projects/authenticated/behaves_like_find_project/1_1_2_1_1.yml, src/api/spec/cassettes/SearchController/search_for_projects/authenticated/behaves_like_find_project/1_1_2_1_2.yml, src/api/spec/cassettes/SearchController/search_for_projects/authenticated/behaves_like_find_project/1_1_2_1_3.yml, src/api/spec/cassettes/SearchController/search_for_projects/authenticated/behaves_like_find_project/1_1_2_1_4.yml, src/api/spec/cassettes/SearchController/search_for_projects/behaves_like_find_project/1_1_1_1.yml, src/api/spec/cassettes/SearchController/search_for_projects/behaves_like_find_project/1_1_1_2.yml, src/api/spec/controllers/search_controller_spec.rb
Extract code from `SearchController#find_attribute` to methods
There are more refactoring to come, for now, just some cleaning tasks.
=> Search controller refactoring

src/api/app/jobs/worker_measurements_job.rb
=> Convert value to integer

src/api/app/models/branch_package.rb, src/api/spec/cassettes/BranchPackage/_branch/retains_url/for_a_newly_created_package.yml, src/api/spec/cassettes/BranchPackage/_branch/retains_url/for_a_newly_created_project.yml, src/api/spec/models/branch_package_spec.rb
Hi,
In branch_package.rb when creating a new package also copy the url. This addresses the issue #11127 .
To see the changes 
- Goto any package example, http://localhost:3000/package/show/home:Admin/FirstPackage
- Click on Branch Package
- Hit branch
- The newly created branch should also have the URL
Added Rspec Test Case as necessary.
Before
After:
=> When branching a package also copy its url

src/api/app/models/binary_release.rb, src/api/app/models/bs_request.rb, src/api/app/models/configuration.rb, src/api/app/models/flag.rb, src/api/app/models/issue.rb, src/api/app/models/issue_tracker.rb, src/api/app/models/linked_project.rb, src/api/app/models/package_issue.rb, src/api/app/models/package_kind.rb, src/api/app/models/path_element.rb, src/api/app/models/project.rb, src/api/app/models/release_target.rb, src/api/app/models/remote_project.rb, src/api/app/models/repository.rb, src/api/app/models/unregistered_user.rb, src/api/app/models/user.rb, src/api/db/schema.rb
Looks like create_table knows charset/collate options now.
=> Annotate changes

src/api/app/controllers/webui/configuration_controller.rb, src/api/app/models/configuration.rb, src/api/app/views/layouts/webui/_footer.html.haml, src/api/app/views/layouts/webui/webui.html.haml, src/api/app/views/webui/configuration/index.html.haml, src/api/db/migrate/20210719103830_add_tosurl_to_configuration.rb, src/api/db/schema.rb
=> Introduces a Terms (of Service) link

src/api/app/models/workflow/step.rb, src/api/app/models/workflow/step/branch_package_step.rb
This abstract class extract common behavior for Workflow Steps
=> Extract common code into an abstract class

src/api/app/services/trigger_controller_service/scm_extractor.rb, src/api/spec/services/trigger_controller_service/scm_extractor_spec.rb
Merge requests can come from a fork too, not only from a branch.
=> Fix status reporting to gitlab forks

src/api/app/models/workflow/step.rb, src/api/app/models/workflow/step/branch_package_step.rb
There will be some common code in both Workflow::Step::BranchPackageStep and the model Workflow::Step::LinkPackageStep that is to come. We move that code to Workflow::Step for now.
See this discussion to get some context: https://github.com/openSUSE/open-build-service/pull/11413#pullrequestreview-716833890
=> Extract common code from BranchPackageStep
