src/backend/bs_publish
For historical reasons, Ubuntu uses the extension .ddeb instead of .deb
for detached debug symbols (-dbgsym) packages. Ubuntu derivatives built
in OBS will also produce packages with this name. Treat them the same as
.deb and .udeb packages.
=> Publish Ubuntu ddeb files to the repositories

src/backend/bs_publish
Since Debian packaging tooling supports checking upstream tarball
signatures, the signature (.asc) files should be published to the
repositories as well.
=========================== end of the commit message ==============================
To check that the current OBS implementation is not publishing the Debian upstream tarball signature to the repositories you can create a test project/package and configure a DoD project targeting Debian stable, and then try to upload for example the `xz-utils` package [1] which contains an upstream tarball signature. If you have a Debian system you can simple run `apt-get source xz-utils` or `dget http://deb.debian.org/debian/pool/main/x/xz-utils/xz-utils_5.2.4-1.dsc`.
After `xz-utils` package builds successfully you'll see the …
=> Publish Debian upstream tarball signatures to the repositories

src/api/app/models/package.rb, src/api/spec/cassettes/Package/_add_containers/1_26_1.yml, src/api/spec/models/package_spec.rb
When maintnenace updates went out, but container update was left out.
The next maintenancen update canidate will not find the container
candidates still using GA packages.
We come with update project already in that case and need to find the
GA versions via all project links.
=> [api] fix another add container special case

src/api/app/controllers/webui/search_controller.rb, src/api/app/views/webui2/webui/search/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/search/_tabs.html.haml, src/api/app/views/webui2/webui/search/index.html.haml, src/api/app/views/webui2/webui/search/owner.html.haml
This is to prevent us from blocking each other while we work on search views.
=> Add skeleton for search views in Bootstrap

src/api/app/assets/stylesheets/webui2/bootstrap_variables/fonts.scss, src/api/app/assets/stylesheets/webui2/cm2/suse.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss
This way the monospace font defined in the browser will be used instead of those defined in Bootstrap.
Fixes #7253.
=> Override Bootstrap monospace fonts with 'monospace'

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/show.html.erb, src/api/app/views/webui2/webui/request/show.html.haml
Closes #7442
Try it in the review app by submitting a request to the project `home:Iggy` for the package `ruby` by superseding the existing request (Do it [here](https://obs-reviewlab.opensuse.org/dmarcoux-issue-7442/package/show/home:Admin/ruby)). Then add a review for the current user (I suggest using `Admin`). You should see the review tab, but as soon as you supersede the request, the review form won't be visible anymore.
=> Display review box only for requests which are new or in review

src/api/app/models/user.rb
Make sure to raise an exception early on, if there is a problem.
Before this was failing because "You cannot call create unless
the parent is saved". But the actual problem was that the project
name was invalid.
This makes it a bit more obvious and easier to catch what the actual
problem is.
Found while debugging #7564.
=> Use create! instead of create in Update User#create_home_project

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/autocomplete.js, src/api/app/assets/javascripts/webui2/kiwi_editor.js, src/api/app/controllers/webui/kiwi/images_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui/kiwi/images/show.html.haml, src/api/app/views/webui2/shared/_buildresult_box.html.haml, src/api/app/views/webui2/webui/kiwi/_tabs.html.haml, src/api/app/views/webui2/webui/kiwi/images/_base_info.html.haml, src/api/app/views/webui2/webui/kiwi/images/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/kiwi/images/_build_info.html.haml, src/api/app/views/webui2/webui/kiwi/images/_description_form.html.haml, src/api/app/views/webui2/webui/kiwi/images/_details_overview.html.haml, src/api/app/views/webui2/webui/kiwi/images/_package_fields.html.haml, src/api/app/views/webui2/webui/kiwi/images/_packages.html.haml, src/api/app/views/webui2/webui/kiwi/images/_preferences.html.haml, src/api/app/views/webui2/webui/kiwi/images/_preferences_form.html.haml, src/api/app/views/webui2/webui/kiwi/images/_profiles.html.haml, src/api/app/views/webui2/webui/kiwi/images/_repositories.html.haml, src/api/app/views/webui2/webui/kiwi/images/_repository_fields.html.haml, src/api/app/views/webui2/webui/kiwi/images/edit.html.haml, src/api/app/views/webui2/webui/kiwi/images/show.html.haml, src/api/spec/bootstrap/features/webui/image_templates_spec.rb, src/api/spec/cassettes/Bootstrap_ImageTemplates/branching/branch_Kiwi_image_template.yml, src/api/spec/features/webui/image_templates_spec.rb
Supersedes https://github.com/openSUSE/open-build-service/pull/6170
Remember that by now we don't want to refactor/get ride of the horrible JavaScript. It was like that in the old UI and by now we just migrate it and we will refactor if afterwards.
=> Add webui2 version of kiwi images

src/api/app/models/attrib.rb
After deletion of attribute instances we send a request to the backend
to update it there. But if the attribute deletion happens as part of the
project / package deletion we don't want this to happen.
Otherwise it could happen that the attribute deletion (after_commit
callback) is requested from the backend after the project / package
was deleted.
Admittedly this is a shot in the dark, as I couldn't reproduce this
issue. But this seems to be the only possible cause for the reported
failure.
=> Fix issue 7419

dist/setup-appliance.sh
While booting a new appliance we have a short timeframe
where `hostname -f` gives back "localhost", which is invalid
for generating the SSL cert.
With this patch we wait for a FQHN which is not empty and not localhost.
=> [dist] setup-appliance.sh: wait for 'real' FQHN

src/api/app/assets/stylesheets/webui2/bootstrap_variables/fonts.scss, src/api/app/assets/stylesheets/webui2/cm2/suse.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss
Reverts openSUSE/open-build-service#7570.
Related to issue openSUSE/open-build-service#7253.
We prefer to define a fixed group of fonts than to rely on the font configured in the browser. This way the aspect of the page will be more homogeneous.
The user that wants to override the font defined in the web page can also configure the browser accordingly. For users of firefox see [this page](https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use#w_custom-fonts).
=> Revert "Override Bootstrap monospace fonts with 'monospace'"

src/api/app/models/project.rb
Since we use XMLHash to parse image templates of remote instances,
we get a string like '{}' when such an template description is empty.
This commit ensures that we don't show such strings in the UI.
Before:
After:
=> Fix image template description for remote templates

src/api/app/views/webui2/webui/project/bottom_actions/_create_maintenance_incident.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_modify_project.html.haml, src/api/app/views/webui2/webui/projects/maintenance_incidents/index.html.haml, src/api/spec/bootstrap/features/webui/projects_spec.rb, src/api/spec/cassettes/Bootstrap_Projects/maintenance_incidents/visiting_the_maintenance_overview.yml
It seems to fit there better than on the general project view.
Before:
After:
=> Move link for incident creation to maintenance incidents index page

src/api/Gemfile.lock
Beep, boop, I'm the Depfu bot... But seriously, I'm sending this because it's a blocker. It's not possible to bundle right now.
ffi has been removed from RubyGems, so it cannot be found. If you try to bundle, you will get this lovely error:
```
frontend@3b633f0bb5c9:/obs/src/api> bundle
Fetching gem metadata from https://rubygems.org/.........
Your bundle is locked to ffi (1.11.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of ffi (1.11.0) has removed it. You'll need to update your
bundle to a version other than ffi (1.11.0) that hasn't been removed in order to install.
```
For details: https://github.com/ffi/ffi/issues/701
=> Update gem ffi to 1.11.1

src/api/app/models/project/key_info.rb, src/api/spec/controllers/webui/projects/ssl_certificate_controller_spec.rb
As 20ab38d was introduced, a hash with more data than the certificate was returned.
Also adapt the test accordingly, adding attributes to a sslcert.
Remove the 'skip' command in the tests, that was not skipping the code. The 'skip' was not inside an 'example'.
Fixes #7449.
=> Return the ssl certificate as plain text

src/api/app/models/bs_request_permission_check.rb
Currently changing the priorities is only allowed if you can write the target project. This should also be allowed to the creator of the request.
Fixes #7619.
=> Allow a requestor to modify a request

src/api/.haml-lint.yml, src/api/app/assets/stylesheets/webui/application/search.scss, src/api/app/controllers/webui/search_controller.rb, src/api/app/views/webui2/webui/kaminari/_first_page.html.haml, src/api/app/views/webui2/webui/kaminari/_gap.html.haml, src/api/app/views/webui2/webui/kaminari/_last_page.html.haml, src/api/app/views/webui2/webui/kaminari/_next_page.html.haml, src/api/app/views/webui2/webui/kaminari/_page.html.haml, src/api/app/views/webui2/webui/kaminari/_paginator.html.haml, src/api/app/views/webui2/webui/kaminari/_prev_page.html.haml, src/api/app/views/webui2/webui/patchinfo/form/_issues.html.haml, src/api/app/views/webui2/webui/search/_advanced_search.html.haml, src/api/app/views/webui2/webui/search/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/search/_results.html.haml, src/api/app/views/webui2/webui/search/_results_issue.html.haml, src/api/app/views/webui2/webui/search/_search_for.html.haml, src/api/app/views/webui2/webui/search/_tabs.html.haml, src/api/app/views/webui2/webui/search/index.html.haml, src/api/app/views/webui2/webui/search/issue.html.haml, src/api/config/locales/kaminari.en.yml, src/api/config/routes.rb, src/api/spec/features/webui/search_spec.rb
Also modifies kaminari views and locales, so pagination is now more Bootstrap style.
**Before:**
**After - for large screens:**
**- Packages/Projects**
**- Issues**
**After - for small screens:**
=> Migrate search page to Bootstrap

src/api/app/assets/javascripts/webui2/kiwi_editor.js, src/api/spec/bootstrap/features/webui/kiwi/images_spec.rb, src/api/spec/cassettes/Bootstrap_Kiwi_Images/project_with_wiki_image/modify_author.yml
When we migrated to the new UI, the variable isOutdatedUrl was not passed, and this resulted in a 'Save' button that didn't trigger any action.
=> Fix Save button on editing Kiwi image

src/api/app/controllers/webui/monitor_controller.rb, src/api/app/views/webui2/webui/monitor/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/monitor/_events.html.haml, src/api/app/views/webui2/webui/monitor/_lights.html.haml, src/api/app/views/webui2/webui/monitor/_workers_table.html.haml, src/api/app/views/webui2/webui/monitor/index.html.haml
The skeleton is already migrated and includes a partial for each of the three sections on Status Monitor. We now can work on this in parallel.
=> Status Monitor Skeleton in Bootstrap

src/api/app/views/webui2/webui/kiwi/images/edit.html.haml
Switching between the Details and Software tabs (using Javascript) caused the Preferences box not to be shown properly. This fixes this behaviour.
=> Show Preferences box only in Kiwi Details tab

src/api/app/controllers/webui/cloud/configurations_controller.rb, src/api/app/views/webui2/webui/cloud/configurations/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/cloud/configurations/index.html.haml
Migrate the `Cloud::ConfigurationController#index` to boostrap:
=> Migrate Cloud::ConfigurationController#index to bootstrap

src/api/app/assets/javascripts/webui/application.js.erb, src/api/app/helpers/webui/kiwi/image_helper.rb, src/api/app/views/webui2/webui/monitor/_lights.html.haml, src/api/app/views/webui2/webui/monitor/index.html.haml
In the old code there were some JavaSscript that showed some hidden text
when hovering an element with class 'scheduler_status'. However, it's
impossible to find that class in the code, so it seems that
functionality is not used anymore.
=> Migrate Server Status to Bootstrap on status monitor page

src/api/app/views/webui2/webui/search/_results_owner.html.haml, src/api/app/views/webui2/webui/search/owner.html.haml, src/api/spec/factories/attribs.rb, src/api/spec/features/webui/search_spec.rb, src/api/spec/fixtures/files/apache_search.xml
Fixes #7636.
Define id 'search_input' to differentiate from the search at the top right (next to the watchlist)
TODO:
=> Handle cases when no users/groups are returned in search#owner

src/backend/BSSched/EventHandler.pm
(aka ExportFilter).  a72e0962d0e introduced a new validation for the job
arch, but we wrote the origin arch into the job since years.
Changing this to the target arch now
=> [backend] fix cross architecture import jobs

src/api/.jshintignore, src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/monitor.js, src/api/app/assets/stylesheets/webui2/monitor.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/views/webui2/webui/monitor/_events.html.haml, src/api/app/views/webui2/webui/monitor/index.html.haml
Move all the JavaScript code from the view to an assets file.
Instead of passing values to JS as parameters, it uses data attributes now.
**Large screen:**
**Small screen:**
=> Migrate Statistics Plots to Bootstrap on status monitor page

src/api/app/models/bs_request_action.rb, src/api/spec/cassettes/BsRequestAction/_check_maintenance_release/last_patchinfo_is_not_build/1_7_3_1.yml, src/api/spec/cassettes/BsRequestAction/encoding_of_sourcediffs/1_1_1.yml, src/api/spec/cassettes/BsRequestAction/encoding_of_sourcediffs/1_1_2.yml, src/api/spec/models/bs_request_action_spec.rb
The `BsRequestAction` is one of the models with lowest test coverage. Looking in the code, I was able to see some issues with the specs and the cassettes. After making the `User.current` private, some specs should be updated and the cassettes refreshed. Beside it I expanded the test coverage on the `BsRequestAction` model and refactored it little bit. Later on, @hennevogel found out that this test didn't need the VCRs at all.
=> Bs request action (refactoring model and specs)

src/api/app/controllers/webui/cloud/ec2/configurations_controller.rb, src/api/app/views/webui2/webui/cloud/ec2/configurations/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/cloud/ec2/configurations/show.html.haml
=> Migrate Amazon EC2 Configuration page to Bootstrap

src/api/app/views/webui2/webui/cloud/configurations/_breadcrumb_items.html.haml
We removed the unneeded `active` class.
Also `aria-current => page` was added to a final breadcrumb item, as defined in our [pattern library](https://obs-patterns.netlify.com/molecules/breadcrumbs.html).
=> Fix style of breadcrumb items

src/api/app/controllers/trigger_controller.rb
We need to validate the project permissions in that case
for "rebuild" operations instead of the package permissions.
move some checks from generic method in the operation specific ones
therefore
=> fix permission handling for tokens on packages via project links

src/api/app/presenters/obs_factory/staging_project_presenter.rb
Factory changed the setup away from legal-auto, the group, directly to licensdigger, the user. There is basically no gain in having a group over the user. The only acceptable response for legal reviews comes from cavil
=> obs_factory: Licensedigger is the bot user for legal reviews

src/api/app/controllers/webui/monitor_controller.rb, src/api/app/views/webui2/webui/monitor/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/monitor/_building.html.haml, src/api/app/views/webui2/webui/monitor/_building_table.html.haml, src/api/app/views/webui2/webui/monitor/_idle.html.haml, src/api/app/views/webui2/webui/monitor/_stats.html.haml, src/api/app/views/webui2/webui/monitor/old.html.haml
To review, see this [comment from @vpereira](https://github.com/openSUSE/open-build-service/pull/7671#issuecomment-498583815) (thank you!). I find it easier to review locally, but it's also possible in the review app.
**Review link:** https://obs-reviewlab.opensuse.org/dmarcoux-bootstrap-monitor-old/monitor/old
Please keep in mind that I ported the view with minor changes and fixed most of the Rubocop offenses.  I ignored some `InlineStyles` offenses to keep the legend as it is.
Before:
Now:
=> Migrate monitor#old to Bootstrap

src/api/app/assets/javascripts/webui2/monitor.js, src/api/app/assets/stylesheets/webui2/monitor.scss, src/api/app/controllers/webui/monitor_controller.rb, src/api/app/views/webui2/webui/monitor/_workers_table.html.haml, src/api/app/views/webui2/webui/monitor/index.html.haml
This PR is mainly a bento -> bootstrap migration, however some
improvements where done. Among them:
- move javascript to assets
- use bootstrap progress bar
- remove instance variables from partials
- remove inline css styling
Last version of the page, the idea is to show the select box with the `custom-select` applied:
The idea is to show how the progress bar change their color based on the delta:
=> Move Workers section to bootstrap

src/api/app/controllers/webui/monitor_controller.rb
Because we are done with the monitor pages migration, we are removing the constrain to run the bootstrap version just on dev environment
=> Remove Rails.env.development guard for monitor controller

src/api/app/views/webui2/webui/monitor/_building_table.html.haml
The error is `SyntaxError: missing ) after argument list`. It's not so obvious at first, but we need to pass the options as an object.
=> Fix JavaScript syntax error

src/api/app/assets/stylesheets/webui2/cloud_upload.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/controllers/webui/cloud/upload_jobs_controller.rb, src/api/app/views/webui2/webui/cloud/upload_jobs/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/cloud/upload_jobs/new.html.haml
This page includes two buttons that are only visible if, at least, one of the clouds is configured.
**Before:**
**After:**
**Small screen:**
=> Migrate to Bootstrap the page to choose Cloud Upload

src/api/app/controllers/webui/cloud/ec2/upload_jobs_controller.rb, src/api/app/views/webui2/webui/cloud/ec2/upload_jobs/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/cloud/ec2/upload_jobs/new.html.haml
To test this locally, I did this:
1. [Download an EC2 image](https://build.opensuse.org/package/binaries/openSUSE:Templates:Images:42.3:AWS/openSUSE-Leap-42.3-EC2-HVM-Guest/images) from our public instance
2. Add the downloaded image to the `ctris` package in `home:Admin`
3. Go directly to this route: http://localhost:3000/cloud/upload/new/home:Admin/ctris/openSUSE_Tumbleweed/x86_64/openSUSE-Leap-42.3-EC2-HVM.x86_64-0.1.4-Build2.225.raw.xz
4. Click on the `Amazon EC2` button
5. See the form migrated in this PR
It's a workaround to building _Amazon EC2_ images, but I didn't have to disable/comment anything to get there.
Before:
Now:
=> Migrate Cloud Upload EC2 form to Bootstrap

src/api/app/views/webui2/webui/cloud/upload_jobs/index.html.haml
With the migration from the old UI to the new UI the default parameters to initialize the cloud upload jobs DataTable were not included. Now they are added, and also it is added the 'responsive' parameter.
=> Pass default params to cloud upload jobs DataTable

src/api/app/controllers/webui/cloud/azure/upload_jobs_controller.rb, src/api/app/views/webui2/webui/cloud/azure/upload_jobs/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/cloud/azure/upload_jobs/new.html.haml
To test this locally, I did like @dmarcoux did [here](https://github.com/openSUSE/open-build-service/pull/7683#issue-285322443):
1. [Download an Azure image](https://build.opensuse.org/package/binaries/openSUSE:Templates:Images:42.3:Azure/openSUSE-Leap-42.3-Azure-Guest/images) from our public instance.
2. Add the downloaded image to the `ctris` package in `home:Admin`
3. Go directly to this route: http://localhost:3000/cloud/azure/upload/new/home:Admin/ctris/openSUSE_Tumbleweed/x86_64/openSUSE-Leap-42.3-Azure.x86_64-0.1.2-Build1.241.vhdfixed.xz
4. Click on the `Microsoft Azure` button.
5. See the form migrated in this PR.
Before:
After:
=> Migrate Cloud Upload Azure form to Bootstrap

src/api/app/views/webui2/webui/cloud/ec2/upload_jobs/new.html.haml
As the label helpers are prepended with the form object (`upload_job_form.`), it is not needed to include it in the first parameter of the label helper.
=> Fix the object name of the label helpers

src/api/app/assets/stylesheets/webui2/build-results.scss, src/api/app/helpers/webui/webui_helper.rb
Make more clear to know the status of monitor pages and build status results by adding colors. Having all the icons in the same color makes not so easy to distinguish at a glance the status of the builds.
These colors were added for the following states:
- Green: published
- Red: broken
- Dark gray: building, finished, publishing
=> Colorize build status and repository status icons

src/api/app/datatables/maintenance_incident_datatable.rb, src/api/app/helpers/webui/maintenance_incident_helper.rb, src/api/app/models/project.rb, src/api/app/views/webui/projects/maintenance_incidents/_incident_table_entries.html.erb, src/api/spec/bootstrap/features/webui/projects_spec.rb, src/api/spec/cassettes/Bootstrap_Projects/maintenance_incidents/visiting_the_maintenance_overview.yml, src/api/spec/factories/flag.rb, src/api/spec/factories/project.rb, src/api/spec/models/project/maintenance_incidents_spec.rb, src/api/test/unit/project_test.rb
Instead of (sql) querying the data first and then using hashes to map and evaluate the data as needed we now have two separate queries that fetch the incident packages and the release target project names individually.
As a result the code becomes much shorter and more readable.
=> Replace release_targets_ng method with SQL queries

src/api/app/models/owner_search/base.rb, src/api/app/models/user.rb, src/api/spec/models/owner_search_spec.rb
For SLE we have a lot of team accounts that are bugowners for packages.
Those accounts are not confirmed (they are not employees), but they are in state :subaccount - but they still are a valid answer if looking for a owner of a package
=> Return bugowners even if they are a subaccount

src/api/app/views/webui2/webui/monitor/_building_table.html.haml
As pagination was introduced, the option to see all the results of the table was lost. Now both options, pagination and all results, are provided.
Now:
=> Provide an option to show all results in monitor detailed page

src/api/app/assets/javascripts/webui2/requests_table.js.erb, src/api/app/views/webui2/webui/package/_files_view.html.haml
By using `initializeDataTable`, the table is consistent with other datatables. Ordering can be useful here, so we don't disable it anymore. The code is also in the view where the table is defined.
Fixes #7724
=> Initialize '#files-table' with proper defaults

ReleaseNotes-2.10, src/api/lib/feature_switch/feature.rb, src/api/spec/lib/feature_switch/feature_spec.rb
We decide to use the `dig` method to make the `Feature.active?` more robust
if the configuration isn't in a proper format.
=> Handle exception in `Feature.active?` method

src/api/app/views/webui2/webui/user/_info.html.haml, src/api/spec/features/webui/users/user_home_page_spec.rb
Fixes #7744 
This is testable locally:
1. Add `return true` as the first line in [switch_to_webui2?](https://github.com/openSUSE/open-build-service/blob/e896f17e38d3ce5438e907486e0ff69acd4c7f3f/src/api/app/controllers/webui/webui_controller.rb#L305)
2. Visit http://localhost:3000/user/show/Admin as an anonymous user
3. Do not see the email of _Admin_ (as you can see in the screenshot below)
=> Display user email on user#show view only to logged-in users

src/api/app/assets/javascripts/webui2/request.js, src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/_set_bugowner_request_dialog.html.erb, src/api/app/views/webui2/webui/request/_add_reviewer_dialog.html.haml, src/api/app/views/webui2/webui/search/_request_bugowner_change_dialog.html.haml, src/api/spec/bootstrap/features/webui/change_bugowner_spec.rb, src/api/spec/fixtures/files/owner_search_bugownership_collection.xml
In the Search Owner page there is a link to request a new bugowner for the package. The new bugowner can be a user or a group, not both. However, the action was always requiring both fields by mistake. Now only one is required and sent.
Fixes #7616 in both old and new UI.
Reuses the same JavaScript function used to add a reviewer to a requet, which has been slightly improved.
To test it locally:
1. Choose a package from your home project.
2. Go to the package's User tab.
3. Add a user as bugowner.
4. Go to the Search Owner page (http://localhost:3000/search/owner)
5. Search by the name of the package selected in step 1.
6. You should see some results. Now click one link 'Request bugowner change'.
7. Fill in the form.
8. A new request is created.
=> Fix bug on Request bugowner change link

src/api/app/views/webui2/webui/main/_user_proceed-list.html.haml
Now the`new image` link is also visible for none logged users.
=> Show New Image link on the main page

dist/obs-api-testsuite-rspec.spec, dist/obs-bundled-gems.spec, dist/obs-server.spec
OBS source can be either used under GPL version 2.0 _or_ under
GPL version 3.0 terms.
This is not a re-licensing, just a fix of the former tagging in spec
files. (GPL v2.0 only and v3.0 only is basically not fullfillable, due
to the fact that v2.0 and v3.0 are incompatible)
Checked with SUSE legal dept.
=> [dist] Fixing our spec file license tag.

src/api/app/models/groups_user.rb, src/api/app/models/relationship.rb, src/api/app/models/review.rb, src/api/app/validators/allowed_user_validator.rb, src/api/spec/models/group_spec.rb, src/api/spec/models/relationship_spec.rb, src/api/spec/models/review_spec.rb
For now, we ban _nobody_ to have a relationship with project or package (Relationship model) and also to be a member of a group or be a reviewer for a request.
A custom validation was added because it's going to be checked in more than one model.
Fixes: #7749
=> Avoid having associations with user _nodody_

src/api/app/assets/stylesheets/webui2/monitor.scss, src/api/app/views/webui2/webui/monitor/_workers_table.html.haml
Fixes #7742 
I took care of some issues related with that, specially css related. Including:
- removed unused css classes
- wrap all workers progress bars in a flex div, removing the limit of 5 per row
- increased the font-size inside the progress bar
- set initial value of the progress to 0
- fixed usage of `link_to` when linking to the project inside the progress bar
=> Improve boostrap version from monitor

src/api/app/assets/stylesheets/webui2/monitor.scss, src/api/app/views/webui2/webui/monitor/_workers_table.html.haml
A new iteration, now adding more space between the workers progress bars.. 
Before:
After:
=> Add more space between progress bars with bootstrap

dist/t/spec/support/capybara.rb
Chromedriver version 75.0, needed by the last Selenium, needs to explicitly disable the W3C mode. With W3C mode disabled it breaks openQA tests as seen here: https://openqa.opensuse.org/tests/963595/file/rspec_webui_tests-rspec_tests.txt
=> Disable W3C mode for Capybara in the openqa tests

src/api/app/assets/stylesheets/webui2/collapsible-text.scss
Fixes #7796
I believe this will be fine since it's used only for comments and in descriptions of packages, projects, patchinfos and requests.
=> Break lines on words, in the collapsible text component

dist/obsworker
Trying to setup a worker with rpm packages in a bare metal machine resulted in failures creating the log files. The default directory for the log files of workers should be the same as for the other OBS services.
Another reason to change to the default directory is that there is no code to create this log subdirectory.
Some code of the `obsworker` script was also cleaned up.
=> Fix value of worker log directory variable (OBS_LOG_DIR)

src/api/app/assets/stylesheets/webui2/comments.scss
Using `word-break: break-all;` the comment looks nice when we have long words, but it's true that breaking the word at any character is not a good idea. It looks like this:
If we remove the `word-break: break-all;` CSS rule, the comment exceeds the area and looks like follows: 
So, taking into account that with or without `word-break: break-all;` the result is not ideal... I propose to remove that rule and use `hyphens: auto` instead. It doesn't break the normal words but add a hyphen to the long ones.
Fixes #7653
=> Fix comments word break, use hyphens instead

README.md
the url http://download.opensuse.org/repositories/OBS:/Server:/2.10/openSUSE_15/OBS:Server:2.10.repo returns a 404 error, but http://download.opensuse.org/repositories/OBS:/Server:/2.10/openSUSE_15.1/OBS:Server:2.10.repo works
=> Make installation instructions work again

dist/t/spec/features/0020_interconnect_spec.rb, dist/t/spec/features/0030_project_spec.rb, dist/t/spec/features/0040_package_spec.rb, dist/t/spec/spec_helper.rb
As smoke tests for each branch are run in the same branch, it is not neccessary to include code to take in account other branches.
After merging this pull request, [tests for 2.10 in openQA](https://openqa.opensuse.org/group_overview/63) should work again.
To review this pull request works, do like openQA:
- Download the qcow image from 2.10: http://download.opensuse.org/repositories/OBS:/Server:/2.10/images/
- Inside this appliance, execute the lines 18 till 22 run in the script [rspec_webui_tests.pm](https://github.com/os-autoinst/os-autoinst-distri-obs/blob/master/tests/rspec_webui_tests.pm).
=> Simplify and fix smoke tests for 2.10 branch

src/api/app/assets/javascripts/webui/application/cm2/use-codemirror.js, src/api/app/assets/javascripts/webui2/cm2/use-codemirror.js, src/api/app/views/shared/_editor.html.haml, src/api/app/views/webui2/shared/_editor.html.haml
Fixes #3179 
webui: 
- The commit input field is disabled by default or by pressing undo
- After changing any text in the edit field, the commit input field can be edited
- After pressing **Save** the message is added to the revision
webui2:
- The commit input field is disabled by default or by pressing undo
- After changing any text in the edit field, the commit input field can be edited
- After pressing **Save** the message input is disabled again
- and the commit message is added to the revision
=> Allow to specify commit messages when changing files

dist/t/spec/support/capybara.rb, src/api/spec/support/capybara.rb
When tests are run, this message is shown in the console:
```
[DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
```
This commit stops using a deprecated method, and therefore prevents this message to be shown.
=> Get rid of Selenium deprecation

src/api/app/controllers/source_project_meta_controller.rb
If the uploaded XML contains the same relationship that the
source controller wants to create (current user as maintainer),
we get an invalid project and active record aborts the save!.
It took quite a while to debug this as we expected save! to throw
an exception for invalid projects. As this behaviour started
with rails 5.2.1 to trigger, we believe it is a Rails bug.
Fixes #7844
=> Fix saving of project meta if containing current user as maintainer

src/api/db/migrate/20190704072437_add_column_in_rollout_to_users.rb, src/api/db/structure.sql
All new users entries are going to set in_rollout field to true in the
database.
=> Change the default value for in_rollout to true

dist/setup-appliance.sh
When setting up an appliance e.g. with virt-manager, you only get a login prompt
after setup-appliance.sh has finished (if kernelcmdline="... console=ttyS0 ...")
This patch reduces the timeout from 600 sec to 30 sec to avoid the impression,
the appliance is dead or the boot process is stuck.
=> [dist] reduce timeout for fqhn from 600 to 30 sec

dist/t/osc/0030_create_and_build_package.ts
Without this commit, the test cases in
0030_create_and_build_package.ts
will break, even if the result is outdated.
This is a regression that was introduced with #9b9f3a873d .
As we changed from "osc r" to "osc r -v" the output has changed,
but the regex to detect outdated repos was never fixed
With this fix we ensure, not to check as long as we have
outdated results.
=> [ci] wait for outdated repos while testing build

dist/systemd/obsdodup.service
otherwise the following errors could occur:
```
Jun 07 12:14:21 localhost systemd[1]: Started OBS dodup, updates download on demand metadata.
Jun 07 12:14:22 localhost bs_dodup[1414]: BSConfig.pm did not return a true value at /usr/lib/obs/server/BSConfiguration.pm line 27.
Jun 07 12:14:22 localhost bs_dodup[1414]: BEGIN failed--compilation aborted at /usr/lib/obs/server/BSConfiguration.pm line 27.
Jun 07 12:14:22 localhost bs_dodup[1414]: Compilation failed in require at /usr/lib/obs/server/bs_dodup line 19.
Jun 07 12:14:22 localhost bs_dodup[1414]: BEGIN failed--compilation aborted at /usr/lib/obs/server/bs_dodup line 19.
Jun 07 12:14:22 localhost systemd[1]: obsdodup.service: Main process exited, code=exited, status=255/n/a
Jun 07 12:14:22 localhost systemd[1]: obsdodup.service: Unit …
```
=> [dist] obsdodup starts after obsapisetup

src/api/app/assets/stylesheets/webui/application/cm2/suse.scss, src/api/app/assets/stylesheets/webui2/cm2/bootstrap.scss
This patch adds a CSS style to the web editor to see tabs that helps users avoid mixed spaces.
Fixes https://github.com/openSUSE/open-build-service/issues/7849
-> https://obs-reviewlab.opensuse.org/rhabacker-master-display-tab-in-editor/package/view_file/home:Admin/ctris/ctris.spec?expand=1
=> Fix 'No tab display in web editor'

src/api/Gemfile, src/api/Gemfile.lock, src/api/app/models/user.rb, src/api/config/initializers/flipper.rb, src/api/db/migrate/20190710094253_create_flipper_tables.rb, src/api/db/structure.sql
We want to switch the management of the features from the actual [feature](https://github.com/mgsnova/feature) gem to the [flipper](https://github.com/jnunemaker/flipper) gem.
Co-authored-by: Saray Cabrera Padrón <scabrerapadron@suse.de>                                                                                       
=> Add flipper gem and initial setup

src/api/lib/tasks/rollout.rake, src/api/spec/factories/users.rb, src/api/spec/lib/tasks/rollout_spec.rb, src/api/spec/support/shared_contexts/rake.rb
When we want to move a feature out of the Beta Program because it's ready to go live, we can enable it for all the users at the same time or little by little to batches/groups of users. In case we choose the second option, we are talking about the Rollout Program.
We are going to run some tasks every couple of days/weeks to add batches of users to the Rollout Program and let them use the new feature.
We'll move all the users out of the Rollout Program every time we're going to publish a new Rollout Feature and then we will start adding them. New users coming from that time on, are going to be in rollout by default.
Co-authored-by: Saray Cabrera Padrón scabrerapadron@suse.de
Co-authored-by: Eduardo Navarro enavarro@suse.com
=> Create rake tasks for rollout program

src/api/app/assets/stylesheets/webui2/cm2/bootstrap.scss
Reverts openSUSE/open-build-service#7865
Was now handled in #7876, sorry I missed the duplication
=> Revert "Add tab indicator in the codemirror stylesheet"

src/api/config/initializers/flipper.rb
Flipper.register doesn't store anything in the database, so we need to
set the groups when initializing to make it persistent.
=> Add the Flipper groups registry to its initializer

ReleaseNotes-2.11, src/api/app/controllers/webui/image_templates_controller.rb, src/api/app/views/webui/main/index.html.haml, src/api/app/views/webui2/webui/main/_user_proceed-list.html.haml, src/api/config/feature.yml, src/api/lib/feature_switch/obs_repository.rb, src/api/spec/controllers/webui/image_templates_controller_spec.rb
As a finished feature, `image template` shouldn't be behind the FeatureToggle.
=> Remove Image Templates from FeatureToggle

ReleaseNotes-2.11, src/api/app/controllers/webui/kiwi/images_controller.rb, src/api/app/views/webui/package/show.html.erb, src/api/app/views/webui2/webui/package/_bottom_actions.html.haml, src/api/config/feature.yml
As a finished feature, kiwi image editor shouldn't be behind the
FeatureToggle.
=> Remove Kiwi Image Editor from FeatureToggle

.circleci/config.yml
Now that docker images for SLE12SP4 are available, we should use them in CircleCI.
=> Make CircleCI use SLE12SP4 instead of SLE12SP3

src/api/lib/tasks/rollout.rake
The :environment argument was missing in the tasks definitions.
The tests passed without it, but running the tasks manually without it
fails.
=> Add environment argument to rollout tasks

src/api/app/controllers/webui/webui_controller.rb, src/api/app/mixins/flipper_feature.rb
The non-logged users could see the feature in rollout before they log in.
=> Take into account `nobody` user for Feature Toggle

src/api/app/assets/stylesheets/webui2/personal-navigation.scss, src/api/app/views/layouts/webui2/_login_form.html.haml
Announcement is sticky and has z-index 1030. Adding a class with
higher z-index brought the login box back to the top
Fixes #7908
=> Bring login box to the top of all elements

src/api/app/views/webui2/shared/_editor.html.haml
Remove the "go to line" input control because it doesn't provide any additional
value, users can search for the line number using the browser anyway.
Fixes #7863
=> Make more clear what the input is for

src/api/app/controllers/webui/webui_controller.rb
In some views we try to do policy validation, however some views do not
require authentication, therefore no user object is avaliable to pundit
which raises an exception (look app/policies/application_policy.rb)
Fixes #7743
=> Pass user (possibly nobody) to pundit

src/api/app/views/webui2/status_messages/_item.html.haml, src/api/app/views/webui2/webui/main/_latest_updates.html.haml
**Status Message**
After this PR:
Before:
**Last News**
After this PR:
Before:
Related with #7927
=> Remove the .small class from Status Message and Last updates to improve readability

README.md
Fixes: #7938
Fixed our documentation to include the --force option for setup-appliance.sh
in our README.md.
Otherwise the installation as described in README.md will fail with an error
message like this:
```OBS API Autosetup is not enabled in sysconfig, skipping```
"--force" overwrite the variable "OBS_API_AUTOSETUP" taken from
/etc/sysconfig/obs-server to "yes".
=> [doc] "setup-appliance.sh --force" in README.md

src/api/app/controllers/webui/apidocs_controller.rb, src/api/app/views/webui2/webui/apidocs/_breadcrumb_items.html.haml, src/api/app/views/webui2/webui/apidocs/index.html.haml, src/api/spec/bootstrap/features/webui/apidocs_spec.rb
Very simple and straight-forward way to migrate the apidocs to Bootstrap.
Improvements to this page can be added in the future, for example, by overwriting  [restility](https://github.com/openSUSE/restility) HTML generator to use Bootstrap classes.
Fixes: #7909
**Before:**
**After:**
=> Migrate apidocs to Bootstrap

src/api/app/controllers/webui/user_controller.rb, src/api/app/views/webui2/webui/user/show.html.haml, src/api/config/options.yml.example, src/api/spec/bootstrap/features/webui/users_spec.rb
In config/options.yml 'contribution_graph' is set to false by default.
It should be decided by instance if it is enabled or not.
=> Make the contribution graph optional

src/api/app/controllers/webui/webui_controller.rb, src/api/app/services/webui_controller_service/user_checker.rb, src/api/spec/services/webui_controller_service/user_checker_spec.rb
To reduce the amount of unstructured and untested code in the controller level, move partially the code of `check_user` to a service. The calls to `User.session` wasn't moved to the service to make easier to understand the logic flow used to set it
=> Refactor check_user method from WebuiController

dist/t/osc/fixtures/home:Admin.xml
Update Leap 42.2 repository to Leap 15.1.
Use Leap 15.0 instead of Tumbleweed. Building in Tumbleweed is more prone to build errors.
=> Update repositories used in osc system tests

dist/t/osc/fixtures/obs-testpackage._service
obs-service-set_version is no longer built for i586 and leads to an unresolvable error.
=> [ci] removed set_version from test case

src/api/app/models/binary_release.rb, src/api/db/migrate/20190712084813_add_cpeid_to_binary_release.rb, src/api/db/structure.sql, src/api/lib/xpath_engine.rb, src/api/test/functional/binary_release_test.rb, src/api/test/functional/channel_maintenance_test.rb, src/backend/BSXML.pm, src/backend/bs_publish, src/backend/bs_worker, src/backend/worker/BSVerify.pm
- also inside of products
- compat code for old product builders not exporting it
- release binary view and search interface
- tracking inside of products
- tracking inside of kiwi appliances
- tracking inside of publisher repositories
still needs to be done:
- tracking inside of containers
=> track cpeid of rpm release packages

src/api/app/assets/javascripts/webui2/project_monitor.js
When sorting by a certain column, the cells with the same content weren't always placed together. See _unresolvable_ cells in the image:
The problem is that Datatables sorts by the content of the cell, which is not a simple value ('unresolvable', 'failed'...) but an HTML tag to be displayed. So, it's trying to sort by values like "<a href=...".
Now we specify the value to be displayed and the value to sort/filter by.
Useful links:
- https://datatables.net/manual/data/orthogonal-data
- https://datatables.net/examples/advanced_init/html5-data-attributes.html
Fixes: #7916
=> Fix sorting bug on project monitor page

dist/t/osc/fixtures/obs-testpackage._service
=> [dist] fix tests after removal of set_version

dist/t/osc/fixtures/obs-testpackage._service
Without this patch the test build will fail with following error:
[   84s] error: File /home/abuild/rpmbuild/SOURCES/obs-testpackage-0.0.1.tar.gz: No such file or directory
=> [ci] change compression xz to gz in osc based test cases

src/api/spec/bootstrap/features/webui/maintained_projects_spec.rb, src/api/spec/factories/users.rb
The changes to the Configuration regarding user properties do not need to be
sent to the backend.
Doing so, we skip the creation of new cassettes involving backend configuration
calls.
This will make some of the extra cassettes being recorded in https://github.com/openSUSE/open-build-service/pull/7551 to not happen anymore.
=> Configuration updates for users do not need to be propagated to the backend

src/api/app/models/event/request.rb
Prevent notification feeds to fail on notifications with deleted projects.
Fixes #7094.
=>  Don't throw an exception on a rss notification when a target project can not be found

dist/systemd/obsapisetup.service
setup-appliance.sh does datatbase actions. The service "mariadb" needs
to be started before.
mariadb has the
ExecStartPre=/usr/lib/mysql/mysql-systemd-helper  upgrade
condition, which may result in delayed upstart of mariadb after package
upgrade.
HINT: needs to be backported to 2.10 also
=> [dist] start obsapisetup after mariadb

dist/obs-server.spec
From 2.9 to 2.10 obsapidelayed.service changed to
obs-api-support.target. The restart and enabling of obs-api-support.target
was tried in the post script. This is to late as the obsapidelayed.service
is already deinstalled at this point and the systemctl command will return
an error.
This change ensures that "systemctl is-enabled/is-active" will be executed
in the %pre section while upgrading the package and the state will be stored
files in the %_run_dir. In the %post section we check for this files and
try to enable/start obs-api-support.target.
NEEDS BACKPORT TO 2.10
=> [dist] fix for upgrade obs-api 2.9 to 2.10

src/api/app/models/user.rb, src/api/lib/tasks/rollout.rake, src/api/spec/lib/tasks/rollout_spec.rb
Staff users are excluded from common tasks to add/remove users to/from
Rollout Program. We have now new tasks only for Staff users.
=> Change rollout tasks to deal with Staff users

src/api/config/initializers/delayed_job_config.rb
There are too many problems with the optimized SQL for locking jobs,
if there are over 10K jobs it takes about 2 seconds on build.o.o.
=> Switching the reserve SQL strategy for DelayedJob

dist/obs-server.spec, src/backend/Makefile
Setting proper permissions for the top level directories in /srv/obs.
This was formerly done by "obsstoragesetup" only.
As "obsstoragesetup" should not be mandatory to run to get an working OBS
server, now this also done in the package. We also keep the old method in
"obsstoragesetup" as it gives the possibility to change OBS_BASE_DIR to users
needs.
Fixes #7984
NEEDS BACKPORT TO 2.10
=> [dist] Include backend data dirs in package

dist/setup-appliance.sh
As our src/rep server nowadays use native systemd services we need to
use "systemctl restart" instead of trying to reload via the old SysV
init scripts.
Fixes: #7944
=> [dist] changed reload of SysV init to systemd

src/backend/bs_srcserver
Fixes a completly misleading error message when requesting a
build flavor that does not exist.
=> [backend] obey the packages parameter when requesting buildinfo

src/api/app/views/webui2/shared/_editor.html.haml
We've setup some defaults, but only if you do not pass a `style` local to the
editor partial. Also set defaults if they are not passed in with `style`.
=> Fix partial editor option hash defaults

src/api/spec/factories/users.rb
For some changes we need to run the bootstrap specs with the VCR on (#7934). Doing so,
we get a ton of unwanted cassettes of requests going to the `/configuration`
endpoint in the backend.
We tried to fix that (#7968) by using `#update_attribute` instead of the `#update method`
on the user factory so we didn't trigger the callbacks that perform the call to the backend, but `#update_attributes` skips the validations but not the callbacks. `#update_column` skips both the
validations and the callbacks, so its the one we have to use here.
=> Use ActiveRecord's #update_column instead of #update_attribute

Rakefile
It's already in docker-compose.yml, no need to specify it a second time in the
override file.
=> Do not duplicate checkout volume

src/api/app/views/webui2/webui/package/revisions.html.haml
To be consistent with other views
Closes #8001
Before:
After:
=> Display revisions count in a badge

src/api/app/views/webui2/shared/_dialog_action_buttons.html.haml
The bootstrap sm class led to a too small font size in the buttons
Before:
After:
=> Adjust fontsize of dialog action buttons

src/api/app/views/webui2/shared/_repositories_flag_table.html.haml
The name of the project in the repository table is not important enough to be that strong. So we decided to remove it
Before:
After:
=> Remove strong tag from repository tables

src/api/app/views/webui2/webui/project/monitor.html.haml
This class was making the repository icon too small.
=> Remove `fa-xs` class on project monitor

src/api/app/views/webui2/webui/project/status.html.haml
We removed some classes to make the button consistent.
=> Remove 'btn-sm' and 'px-4' class from filter button

CONTRIBUTING.md
The interconnect button name changed, and on a default SUSE system, you need to make sure your user is in the docker group before running  `rake docker build`.
=> Fixed manual for initial interconnect setup, added note about docker

src/api/app/views/webui2/webui/package/_buildstatus.html.haml, src/api/app/views/webui2/webui/package/show.html.haml, src/api/spec/bootstrap/features/webui/packages_spec.rb
The description and comments didn't need to change due to the changes we did together in the mob programming session this Tuesday.
The build results and rpmlint is already taken care of in #8036. We removed an unneeded class in the build results (this is something we noticed when reviewing the changes from @saraycp's and @krauselukas' PR.
Other sections of the package show page were reviewed and we didn't change things there.
The package URL changes:
Before:
After:
=> Package Show - Typography

src/api/app/models/package.rb, src/api/spec/models/package_spec.rb
If a project uses a develproject setting, resolve_devel_package method
crashes, because it's using get_by_name that is not defined on the
collection proxy.
Fixes:  #8047
=> Use find_by instead of get_by_name

src/api/app/views/webui2/webui/attribute/_form.html.haml, src/api/app/views/webui2/webui/attribute/index.html.haml
Use .text-primary for consistency 
Before:
After:
Prevent attributes table from overflowing
Before:
After:
=> Improvements for Package Attributes

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/edit_comment.js.erb
In the status tab/page of a project there is a list of failing packages. A maintainer user can add a comment to each of the failing packages. However, if there were any trouble while adding the comment, the error wasn't visible.
Now the error is visible inside the comment cell.
=> Show the error raised when editting status comment

src/api/app/views/webui2/webui/request/_request_history.html.haml, src/api/app/views/webui2/webui/request/_request_history_element.html.haml, src/api/app/views/webui2/webui/request/show.html.haml
The fontsize was too small. Now it's consistent with
the other content of the page
Before:
After:
=> Adjust fontsize and gravatar in request history box

src/api/app/assets/javascripts/webui2/datatables.js, src/api/app/assets/javascripts/webui2/requests_table.js.erb, src/api/app/views/webui2/webui/project/_project_packages.html.haml
We fix the responsiveness of package table and we also make the pagination consistent
We were using two different paginations in different places. Now we use the default of DataTable (simple_numbers).
=> Fix package table responsiveness and make pagination consistent

src/api/app/assets/stylesheets/webui2/build-results.scss, src/api/app/views/webui2/webui/package/_buildstatus.html.haml, src/api/app/views/webui2/webui/package/_rpmlint_result.html.haml
We changed the Rpmlint and Build Results partials for the package's build result box which appears in the request page as well.
We decided to change the font family of the Rpmlint result, that was in a `<pre>`tag, in order to reduce the number of different font families and increase readability.
**Before:**
**After:**
=> Adjust typography on Rpmlint and Build Result tabs

src/api/app/views/webui2/webui/project/show.html.haml
The URL of the project was too small and inconsistent to other sections like package#show view.
=> Show URL the same way as on Package#show

src/api/app/views/webui2/webui/project/subprojects.html.haml
`@parentproject` was not used in the new UI, then the class `mt-3` was never applied.
=> Add space between parent table and subproject table

src/api/app/views/webui2/webui/repositories/_repository_card_content.html.haml, src/api/app/views/webui2/webui/repositories/_repository_entry.html.haml, src/api/app/views/webui2/webui/repositories/_repository_path_item.html.haml
This page needs a redesign, but for now this will already improve the view a bit. The `Repositories Flags` section is already addressed in #8039.
Reorganize hierarchy of repository paths and put emphasis on a repository's architectures.
Before:
After:
=> Typography - Project Repositories

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/_edit_comment.html.haml, src/api/app/views/webui2/webui/project/edit_comment.js.erb
In the project Status tab, if there was any error while adding a comment, the error was shown in the cell. We have changed this behavior and now is shown as a flash message.
**Before:**
**After:**
=> Replace error in the comment's cell by flash error

src/api/app/assets/stylesheets/webui2/diff.scss, src/api/app/views/webui2/webui/package/_revision_diff_detail.html.haml, src/api/app/views/webui2/webui/package/_revision_diff_detail_buttons.html.haml, src/api/app/views/webui2/webui/request/_sourcediff_tab.html.haml
We fit the paddings for the summary header and the position of the buttons on it. This way we show them in the middle and with enough space around.
**Before:**
**After:**
=> Adjust typography for source diff area in request page

src/api/app/assets/stylesheets/webui2/project-package-show-grid.scss
We gave more space on buildresult section.
=> Change project and package grid

src/api/app/views/webui2/webui/request/_sourcediff_tab.html.haml
On medium sized screens the content of the build result
box started to overflow and overlap.
**Before**
**After**
=> Fix build results box in request view on medium sized screen

src/api/app/views/webui2/webui/projects/pulse/_pulse_list.html.haml, src/api/app/views/webui2/webui/projects/pulse/_pulse_list_requests.html.haml, src/api/app/views/webui2/webui/projects/pulse/show.html.haml
We improve the responsiveness in small and medium break-points of the pulse page.
=> Improve responsiveness on pulse page

src/api/app/helpers/webui/user_helper.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/spec/helpers/webui/user_helper_spec.rb
Robohash looks (IMO) more modern and is less pixelated.
For comparison: 
* Wavatar example: https://www.gravatar.com/avatar/00000000000000000000000000000000?d=wavatar&f=y&size=500
* Robohash example: https://www.gravatar.com/avatar/00000000000000000000000000000000?d=robohash&f=y&size=500
=> Use 'robohash' style of default Gravatars instead of 'wavatar'

src/api/app/assets/stylesheets/webui2/bootstrap_variables/tables.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss
This is especially improving contrast when table cells contain a link.
Before:
After:
=> Improve constrast for striped tables

src/api/app/assets/stylesheets/webui2/sticky-footer.scss, src/api/app/assets/stylesheets/webui2/watchlist.scss, src/api/app/views/layouts/webui2/_footer.html.haml, src/api/app/views/layouts/webui2/webui.html.haml
The text/links were hard to read in the footer/header and didn't
follow the wave recommendation (AA) regarding the contrast.
**Before**
**After**
=> Enhance contrast of footer and header

src/api/app/assets/stylesheets/webui2/breadcrumbs-component.scss
The contrast of the breadcrumbs was too low and didn't
match the wave recommendation.
**Before**
**After**
=> Enhance contrast of the breadcrumbs

src/api/app/assets/stylesheets/webui2/bootstrap_variables/colors.scss, src/api/app/assets/stylesheets/webui2/pulse.scss
The colors had a bad contrast in many areas of the OBS
webui
**Before**
**After**
=> Update colors for obs_green, bootstrap-info and bootstrap-success

src/api/app/assets/stylesheets/webui2/build-results.scss
The new version makes the page pass the WAVE contrast checks. The changes are minor since the contrast was almost already fine. It just needed a small boost :wink:
Before:
After:
=> Improve constrast of red/green for build results in striped tables

dist/obs-server.spec
This patch takes care that obs-api-support.target gets enabled/started if
obsapidelayed.service was enabled/started before updating from 2.9
=> [dist] enable obs-api-support.target on update

src/api/app/assets/stylesheets/webui2/build-results.scss
=> Improve contrast for all states of build results in striped tables

ReleaseNotes-2.11, src/api/Gemfile, src/api/Gemfile.lock, src/api/app/assets/stylesheets/webui2/coderay.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/helpers/application_helper.rb, src/api/app/views/webui2/webui/package/_revision_diff_detail.html.haml
To offer an options  to the users to check a set of one or more diffs, we were using CodeMirror, a javascript based Editor.
However when the request has more than a few diffs, it starts to get
slow. As drop-in solution I'm proposing to go  with [CodeRay](https://github.com/rubychan/coderay).
Fixes #8072
How it looks:
Benchmark loading 50 diffs in one request:
With CodeMirror:
```
Completed 200 OK in 61ms (Views: 3.8ms | ActiveRecord: 7.4ms | Backend: 17.4ms)
```
With CodeRay (with tables or div, no real performance difference among them):
```
Completed 200 OK in 47ms (Views: 0.9ms | ActiveRecord: 5.7ms | Backend: 17.3ms)
```
TODO:
=> Use coderay instead codemirror to present read-only diffs

src/api/app/assets/stylesheets/webui2/comments.scss
Unfortunately the hyphens: auto, doesn't work on Chrome desktop properly
therefore we are falling back to word-break: break-word when hyphens
aren't supported
We can see in the following screenshots how it looks like:
On Firefox:
On Chrome:
With the alternative to `word-break: break-word`: (`word-break: normal;overflow-wrap: anywhere`) 
suggested in https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
On Chrome:
With the `word-break: break-word`
So even if `word-break: break-word` is deprecated it is a temporary solution while Chrome doesn't support it well.
Fixes #8100
=> Use hyphens: auto, just when supported

src/api/app/views/webui2/webui/search/_results.html.haml, src/api/app/views/webui2/webui/search/_results_issue.html.haml, src/api/app/views/webui2/webui/search/_results_owner.html.haml
Stick to default font for results' description in the search (same thing for the search issues page)
Before:
After:
---
Improve text hierarchy in the search owners page. For the user cards, we stick with the emphasis on the user names, so this explains why the user logins are smaller. 
Before:
After:
=> Typography - Search

src/api/app/assets/stylesheets/webui2/bootstrap_variables/fonts.scss
Just a preview for you to see the webui with responsive font-sizes enabled. In this example it scales down to 14px at max (default is to stop at 16px, which needs to be discussed). It starts the scaling at large screens (960px width). Check it out in the review app :)
=> Enable RFS in bootstrap for responsive font-sizes

src/api/app/datatables/package_datatable.rb
Fixes #786
Allows to quickly spot a linked package in between other kinds of packages
=> Display a link badge next to link in the package list

src/api/app/helpers/webui/patchinfo_helper.rb, src/api/app/views/webui2/webui/patchinfo/_side_elements.html.haml, src/api/app/views/webui2/webui/patchinfo/show.html.haml
We removed the `small` class from summary and block reason. This information was too attenuated because of the small font size and and light gray colour.
=> Typography - patchinfo show

src/api/app/views/webui2/webui/project/side_links/_maintenance_project.html.haml
During the migration to the new UI we forgot to change the link of the
maintained projects to point to the new controller.
=> Fix maintained projects link

src/api/app/assets/stylesheets/webui2/card-component.scss, src/api/app/views/webui2/webui/main/index.html.haml
To be consistent with the maximum line-length for text at other places
of obs.
**Before**
**After**
=> Set max line-length for obs description at root page

src/api/app/views/webui2/webui/project/side_links/_maintenance_project.html.haml
During the migration to the new UI we forgot to change the link of the
maintained projects to point to the new controller.
=> Backport - Fix maintained projects link

src/api/app/controllers/webui/webui_controller.rb, src/api/app/models/user.rb, src/api/app/services/webui_controller_service/user_checker.rb, src/api/lib/authenticator.rb, src/api/lib/tasks/rollout.rake, src/api/spec/controllers/webui/session_controller_spec.rb, src/api/spec/lib/authenticator_spec.rb, src/api/spec/lib/tasks/rollout_spec.rb, src/api/spec/models/user_spec.rb, src/api/spec/support/shared_examples/a_confirmed_user_logs_in.rb
When users logged in via proxy `last_logged_in_at` and `login_failure_count` were not updated. Now we do it every time we check the user.
We also set RabbitMQ messages when needed.
Fixes: #8068
=> Update last_logged_in_at when a user logs in via proxy

src/api/app/views/layouts/webui2/_login_form.html.haml
We want to use the `clearfix` CSS class as it is described in the [Bootstrap documentation](https://getbootstrap.com/docs/4.3/utilities/clearfix/):
> Easily clear floats by adding `.clearfix` **to the parent element**.
It is also included a little refactoring related to the submit button.
=> Fix clearfix class in login form

src/api/app/assets/stylesheets/webui2/groups.scss, src/api/app/helpers/webui/user_or_groups_roles_helper.rb, src/api/app/views/webui2/webui/groups/_group_members.html.haml
Adjusts typography
**Before:**
**After:**
And also sets the same width for all the boxes:
**Before:**
**After:**
=> Adjust typography and elements size and position in group show page

dist/t/spec/support/capybara.rb
This PR contains changes to hand over an specific hostname
to the frontend functional tests so we can use the test suite on an
jump host to test our installation from the outside
=> [ci] capybara tests more flexible

src/api/app/assets/stylesheets/webui2/coderay.scss, src/api/lib/obsapi/markdown_renderer.rb
CSS fixes to:
* Bring the style of coderay to how the code looks in codemirror (it isn't the same, but as close as I could get it)
* Make diff styling nicer
=> Syntax highlighting in the comments

src/api/app/assets/stylesheets/webui2/requests.scss
When a comment in the request history is too long, it was floating out of the media-body. 
I set the `max-width` to 30ch to be proportional to the comments section.
Fixes #8130
=> Deal with long words properly in all browsers

src/api/app/assets/stylesheets/webui2/datatables.scss
Deal with long words properly in all browsers
Before:
After:
=> Typography - User/Group Tasks

src/api/app/assets/stylesheets/webui2/bootstrap_variables/tables.scss, src/api/app/assets/stylesheets/webui2/webui2.css.scss, src/api/app/views/webui2/shared/_patchinfos_table.html.haml, src/api/app/views/webui2/shared/_requests_table.html.haml, src/api/app/views/webui2/shared/user_or_groups_roles/_index.html.haml, src/api/app/views/webui2/webui/attribute/index.html.haml, src/api/app/views/webui2/webui/cloud/upload_jobs/index.html.haml, src/api/app/views/webui2/webui/groups/index.html.haml, src/api/app/views/webui2/webui/monitor/_building_table.html.haml, src/api/app/views/webui2/webui/monitor/_idle.html.haml, src/api/app/views/webui2/webui/monitor/_stats.html.haml, src/api/app/views/webui2/webui/package/_deps.html.haml, src/api/app/views/webui2/webui/package/_files_view.html.haml, src/api/app/views/webui2/webui/packages/build_reason/index.html.haml, src/api/app/views/webui2/webui/packages/job_history/index.html.haml, src/api/app/views/webui2/webui/project/_project_inherited_packages.html.haml, src/api/app/views/webui2/webui/project/_project_packages.html.haml, src/api/app/views/webui2/webui/project/_projects_table.html.haml, src/api/app/views/webui2/webui/project/bottom_actions/_gpg_key_ssl_certificate.html.haml, src/api/app/views/webui2/webui/project/index.html.haml, src/api/app/views/webui2/webui/project/monitor.html.haml, src/api/app/views/webui2/webui/project/status.html.haml, src/api/app/views/webui2/webui/projects/maintenance_incidents/index.html.haml, src/api/app/views/webui2/webui/staging/excluded_requests/index.html.haml, src/api/app/views/webui2/webui/staging/projects/show.html.haml, src/api/app/views/webui2/webui/staging/workflows/_staging_projects_table.html.haml, src/api/app/views/webui2/webui/user/_involvement.html.haml, src/api/app/views/webui2/webui/user/index.html.haml
People with limited color vision have issues to read
colored text/items on the stronger gray of the zebra striped
tables.
Fixes #8116
**Before**
**After**
I would suggest to make the zebra effect a bit lighter. Incase people still having issues to read the content, we still can remove it completly.
Here some interesting article regarding this topic:
https://alistapart.com/article/zebrastripingdoesithelp/
I added a hover effect to the datatables, this makes it easier to keep track of the currently selected row.
=> Remove zebra striped rows from datatables 

src/api/lib/obsapi/markdown_renderer.rb, src/api/spec/helpers/webui/markdown_helper_spec.rb
Fixes #8167
Skips over coderay entirely if no language is input, to save on having additional processing for that, and additional classes coderay would insert for text.
=> Make sure language exists

src/api/app/assets/stylesheets/webui2/build-results.scss
Since the zebra striped tables got removed, the darker
colors for the odd rows are not needed anymore.
=> Remove darkened colors for striped tables

src/api/app/assets/stylesheets/webui2/build-results.scss
The old webui used to set a background to states which suppose to change.
** Old Webui**
** Same with colors in our new Webui**
=> Add a background to build states which are still in flux

src/api/app/assets/javascripts/webui2/application.js, src/api/app/assets/javascripts/webui2/users.js, src/api/app/assets/stylesheets/webui2/user.scss, src/api/app/controllers/webui/user_controller.rb, src/api/app/views/webui2/webui/user/_info.html.haml, src/api/spec/features/webui/users/user_home_page_spec.rb
We applied some changes regarding the contrast in the username. Apart from that, we grouped the email with the other elements at the bottom.
**Beta Program Tooltip:**
=> Typography user show

src/api/lib/obsapi/markdown_renderer.rb, src/api/spec/helpers/webui/markdown_helper_spec.rb
Use word boundaries to the regular expression that identifies users. This way a string will not match a user when it has word characters before the "@" character.
A test case for not rendering users inside the text of html links is also added.
Fixes #8178.
=> Improve regular expression for rendering users

src/api/app/views/webui2/webui/user/_info.html.haml
Call users to action by starting the text with a verb.
Before:
After:
=> Improve beta program help text

src/api/spec/bootstrap/features/webui/users/admin_configuration_spec.rb
Accepting the confirmation dialog results in a reload of the table. So the selector defined with "within" doesn't work after deleting. Moving the expectation outside the "within" clause makes the test work again.
Fixes #8154.
=> Reenable delete user test

src/api/app/assets/stylesheets/webui2/datatables.scss
When doing horizontal scrolling in the project monitor page and then mouse over, some of the cells show the info behind. This happens because Bootstrap set a semi-transparent color as background and we have an special feature in the monitor page: two tables, one for the package names and the other one for the states which hides behind the first one.
Making the row highlight color opaque, it doesn't look broken.
Fixes:  #8183
**Before:**
**After:**
=> Fix issue with semi-transparent table highlight

src/api/app/controllers/webui/repositories_controller.rb
Allow a user to enable or disable the repositories of a package he or she is mantainer of.
Fixes #8110.
=> Allow changing repositories for package maintainer

src/api/app/controllers/source_controller.rb, src/api/app/jobs/project_do_project_copy_job.rb, src/api/app/models/project.rb
There is no reason to implement the job in the model just to differ perform_now and perform_later. This simplifies the setup and makes the permission check unique
=>  Move do_project_copy to the active job completely

src/api/app/models/buildresult.rb
In the method `summary` there is no instance of `Buildresult` therefore the method must be a class method.
Fixing https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5d6642a5a98d9a000c965abc
introduced by https://github.com/openSUSE/open-build-service/pull/8174
=> code2index must be a class method

src/api/app/models/owner_search/assignee.rb
a binary which got published via a snapshoted repo, but the
original container got removed later ....
=> fix crash in owner search

src/api/spec/bootstrap/features/webui/users/profile_spec.rb
The original test was skipped in case of Bootstrap (see PR #8140), so a new one specific for Bootstrap is needed.
=> Add test for beta program switch for Bootstrap

ReleaseNotes-2.11, src/api/Gemfile, src/api/Gemfile.lock, src/api/app/assets/javascripts/webui2/airbrake-js.js.erb, src/api/app/assets/javascripts/webui2/application.js, src/api/config/options.yml.example
As a developer you might be interested in exceptions that occur in the
javascript that is running in the users browser. Separate this with another
errbit configuration key because this is getting exposed publicly.
=> Introduces client side javascript error tracking

ReleaseNotes-2.11, dist/Makefile, dist/obs-server.spec, dist/systemd/obs-api-support.target, dist/systemd/obs-delayedjob-queue-sphinx-indexing.service, src/api/app/jobs/full_text_index_job.rb
Thinking Sphinx indexing jobs should not be processed in parallel
since it can lead to conflicts between them.
Fixes #8208
=> Add delayedjob worker for thinking sphinx indexing

.circleci/config.yml, src/api/test/functional/webui/spider_test.rb
As we plan to remove bento, we need to run the tests in the new UI.
=>  Run spider test in the new UI

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui2/webui/project/_create_package_form.html.haml, src/api/app/views/webui2/webui/project/_create_package_modal.html.haml, src/api/app/views/webui2/webui/project/new_package.html.haml
Preview:
The modal which is now using the same partial as `project#new_package` didn't change, except for marking the `name` field as required.
/rant
We have 2 ways to create packages. One with a modal and with project#new_package when a validation fails in the modal. Another case of a modal which is useless.
=> Migrate project#new_package

dist/obs-bundled-gems.spec, src/api/Gemfile, src/api/Gemfile.lock
It reverts:
fc796482d8abac4dd65881ad1b88ab1bc76ac89d
6df0143ecb02a669048cb6bbeaeb9ba8a16d4b28
sassc 2.2.0 throws FFI exception. Reverting it fixes it
=> Revert update from sassc gem

dist/obs-server.spec
It needs to be defined what happens with the thinking sphinx
systemd service at installation, upgrading, deletion etc...
Addition to https://github.com/openSUSE/open-build-service/pull/8218
=> Register thinking sphinx delayed worker systemd unit

src/api/db/data/20190902110039_add_attribute_default_values.rb, src/api/db/data_schema.rb
On certain instances of the Open Build Service the default
attribute values got lost, since they are only created once
at the first setup by the seeds. This causes failing validations
when creating certain attribute, since they rely on the default values.
Fixes #8143
=> Add data migration for attribute default values.

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
I've missed the discussion about changing this, so here is my feedback for CONTRIBUTING.md in the form of a PR :smile: 
I think in general this needs to be as concise **and** as clear as possible because this is mostly for new contributors to learn. We should try not to overwhelm then in the sections.
=> Make Contributing Guide more concise

src/api/app/helpers/webui/request_helper.rb, src/api/app/views/webui2/shared/bs_requests/index.json.erb
Looking at the shortend/trimmed source path of a request
makes it sometimes difficult to identify the source, especially
if its through an interconnect (since its not a link to the source
in this case). Bootstrap handles long text quite well in this case.
So trimming the text after 40 characters is not necessary.
Before:
After:
Related to #7378
This would be sufficient solution for now, until https://github.com/openSUSE/open-build-service/pull/7846 is ready :)
=> Dont shorten request source path text in webui2

src/api/app/assets/javascripts/webui2/airbrake-js.js, src/api/app/views/layouts/webui2/webui.html.haml
Getting data from CONFIG does not work if you compile your assets
before shipping them to production. Use meta tags instead.
=> Fix javascript error reporting

dist/obs-bundled-gems.spec
the useless "-march=native" compile flag unsupported on power when building rubygem-sassc
=> [dist] obs-bundled-gems.spec: fix build on ppc by dropping

src/api/app/views/webui/shared/user_or_groups_roles/_add_group_dialog.html.haml, src/api/app/views/webui/shared/user_or_groups_roles/_add_user_dialog.html.haml, src/api/app/views/webui/shared/user_or_groups_roles/_index.html.haml
During the migration of the shared partials we forgot to change the
namespace to use `webui` instead of `webui2`.
=> Use correct path for partials in shared directory

src/api/app/views/webui2/webui/request/_reviewer.html.haml
The Bento version is src/api/app/views/webui/request/_reviewer.html.erb
Closes #8223 
Preview from the [review app](https://obs-reviewlab.opensuse.org/dmarcoux-bootstrap-reviewer-partial/request/show/1):
=> Migrate request reviewer partial to Bootstrap

src/backend/bs_worker, src/backend/worker-deltagen.spec
It can be set both in BSConfig.pm and in the project config.
The default is still '512'.
=> [backend] make the deltagen -m option configurable

src/api/app/assets/stylesheets/webui2/build-results.scss
The build state disabled is a conscious decision and
therefore it is not necessary/too much to highlight it with
a background color.
**before**
**after**
=> Remove background from build state disabled

dist/t/spec/features/0030_project_spec.rb
The repository openSUSE Leap 42.3 was removed.
=> Fix openqa test for 2.9

dist/t/spec/features/0010_authentication_spec.rb, dist/t/spec/features/0020_interconnect_spec.rb, dist/t/spec/features/0030_project_spec.rb, dist/t/spec/features/0040_package_spec.rb, dist/t/spec/spec_helper.rb
Since the OBS webui changed quite a lot, the feature
tests needed some adjustment.
Big parts of the adjustments are copied over from
the 2.10 branch.
=> Adjust openQA feature tests

src/api/app/assets/javascripts/webui2/request.js, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui2/package_controller.rb, src/api/app/models/project.rb, src/api/app/views/webui2/webui/package/_submit_request_dialog.html.haml, src/api/app/views/webui2/webui/package/bottom_actions/_submit_package.html.haml, src/api/app/views/webui2/webui/package/show.html.haml, src/api/config/routes.rb
After branching and submitting a package, the form was not pre-filled with the
project and package.
This fix, pre-fills the Submit when hitting the Project overview's
"Submit package" link.
Fixes #7551
=> Fix pre-filling of the Submit Request Form

src/backend/worker-deltagen.spec
=> [backend] fix typo in worker-deltagen.spec

src/api/app/views/webui/interconnects/_interconnect_modal.html.haml, src/api/app/views/webui/main/_add_status_message_modal.html.haml, src/api/app/views/webui/patchinfo/edit.html.haml, src/api/app/views/webui/projects/maintained_projects/_create_dialog.html.haml, src/api/app/views/webui/repositories/_add_dod_repository_modal.html.haml, src/api/app/views/webui/repositories/_add_repository_from_project_modal.html.haml, src/api/app/views/webui/repositories/_add_repository_path_modal.html.haml, src/api/app/views/webui/repositories/_dod_source_fields.html.haml, src/api/app/views/webui/repositories/_edit_repository_modal.html.haml, src/api/app/views/webui/repositories/_request_delete_repository_modal.html.haml, src/api/app/views/webui/request/_add_reviewer_dialog.html.haml, src/api/app/views/webui/request/_add_role_request_dialog.html.haml, src/api/app/views/webui/request/_change_devel_request_dialog.html.haml, src/api/app/views/webui/request/_delete_request_dialog.html.haml, src/api/app/views/webui/request/_sourcediff_tab.html.haml, src/api/app/views/webui/request/show.html.haml, src/api/app/views/webui/search/_request_bugowner_change_dialog.html.haml, src/api/app/views/webui/user/_edit_dialog.html.haml, src/api/app/views/webui/user/_password_dialog.html.haml
During the migration we forgot to change the path of the partials to use
the correct shared directoy.
=> Change partials namespace

src/api/app/controllers/webui/user_controller.rb, src/api/config/routes.rb, src/api/spec/controllers/webui/user_controller_spec.rb
`render_dialog` is for Bento modals which we don't need anymore. Their routes and specs were also removed.
=> Remove actions for Bento modals in user_controller.rb

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/show.html.haml, src/api/config/routes.rb, src/api/test/functional/webui/spider_test.rb
As @dmarcoux [pointed out,](https://github.com/openSUSE/open-build-service/pull/8325#issuecomment-530779012) some actions were not removed from the request controller, those ending in _dialog.
=> Remove Bento unused actions in request controller

src/api/app/views/webui/package/rdiff.html.haml
The original package and project were not passed to the full diffs link for a linked package.
Fixes #8360
For reviewers, these pages to see/try the full diffs link for:
- a package's revision:  https://obs-reviewlab.opensuse.org/dmarcoux-issue-8360/package/rdiff/home:Admin:branches:home:Admin/php7?rev=2
- a linked package: https://obs-reviewlab.opensuse.org/dmarcoux-issue-8360/package/rdiff/home:Admin:branches:home:Admin/php7?opackage=php7&oproject=home%3AAdmin&rev=2
=> Correctly link to full diffs of a linked package

src/api/app/views/webui/package/show.html.haml, src/api/app/views/webui/patchinfo/show.html.haml, src/api/app/views/webui/request/_request_history.html.haml, src/api/app/views/webui/request/_request_history_element.html.haml, src/api/app/views/webui/request/_show_overview.html.haml
During the migration this partial was moved into `webui/shared`
directory.
=> Use correct path for collapsible_text partial

src/api/app/views/webui/staging/projects/_unstaged_staged_request_history.html.haml
=> Fix request link on staged request history

src/api/app/assets/javascripts/webui/request.js
We were doing two ajax call one for prefill the form and another for
check if we have request that can by superseded. Most of the time the
prefill hadn't finish when we check the requests, so the supersede
section was never shown.
=> Fix show supersede request on Submit Request modal

src/api/app/controllers/webui/webui_controller.rb
This method was only used in the old UI. Now, that we completly switch
to the new interface, this method is unused.
=> Remove render_dialog method

src/api/app/views/webui/projects/maintained_projects/_create_dialog.html.haml
=> Fix add maintained project autocomplete

src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/mixins/webui/manage_relationships.rb
Due to the migration from bento to bootstrap, certain
methods turned unnecessary and can be removed.
=>  Consolidate duplicated methods from project and package controller 

src/api/app/controllers/webui/users_controller.rb, src/api/spec/controllers/webui/users_controller_spec.rb
It fixes #8382 and #8164 
Both are the same issue, but the #8164 is now invalid since we migrated the user resource to users resources.
How to test:
As Admin:
- Create an user $USER
- Delete this $USER
- Go to /users 
- Find the $USER, click on that or go to /users/$USER/edit
- Set the $USER state to confirm
- Click on update
Expected:
The user should be confirmed and therefore active again
=> Make possible to find deleted users in the UsersController#update

src/api/app/controllers/webui/project_controller.rb, src/api/config/routes.rb
The view wasn't migrated to Bootstrap and it's not accessible without knowing the URL, so this can be removed.
The Bento version of the view was removed in 0991846.
=> Remove unneeded project#packages_simple action

src/api/app/controllers/webui/projects/maintained_projects_controller.rb, src/api/app/views/webui/project/_tabs.html.haml, src/api/app/views/webui/project/side_links/_maintenance_project.html.haml, src/api/app/views/webui/projects/maintained_projects/index.html.haml, src/api/config/routes.rb, src/api/spec/features/webui/maintained_projects_spec.rb
The route helper for `projects/maintained_projects#index` changed from `projects_project_maintained_projects_path` to `project_maintained_projects_path`.
=> Remove Bento specific route definition for maintained projects

src/api/app/controllers/webui/project_controller.rb
Hitting this action redirects to the show action in `projects/rebuild_times_controller.rb`. The filters are therefore not needed in `project_controller.rb`
=> Remove rebuild_time from project controller filters

src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui/project/show.html.haml
These variables `@packages` and `@ipackages` are still used in the new
interfaces.
=> Refactor a little bit

src/api/app/controllers/webui/users/bs_requests_controller.rb, src/api/app/controllers/webui/users_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/config/routes.rb, src/api/spec/controllers/webui/users/bs_requests_controller_spec.rb, src/api/spec/routing/webui/users/requests_spec.rb
There were two similar methods named `WebUIController#check_display_user`
and `UsersController#check_displayed_user` method, just with a different
parameter. Merged both in one and adapted the routes and specs for the
users/requests resource
=> Remove repeated check_display(ed)_user method and refactor user/requests routes

src/api/app/assets/javascripts/webui/packages.js, src/api/app/views/webui/package/_revision_diff_detail.html.haml
In the request diff we changed CodeMirror in favour of CodeRay.
But in the javascript we have some reference to CodeMirror.
Fix #8288
=> Fix expand and collapse in review

src/api/app/controllers/webui/user_controller.rb, src/api/app/controllers/webui/users_controller.rb, src/api/config/routes.rb, src/api/spec/controllers/webui/user_controller_spec.rb, src/api/spec/controllers/webui/users_controller_spec.rb
Move the actions `autocomplete` and `tokens` from `UserController` to `UsersController`
This PR includes:
- route changes and route redirects to the old routes
- adapted specs
- The routes are accessible via json, so a `osc -A $DEV_SERVER api '/users/autocomplete.json` should do the trick.
- Beside it the endpoints are used in the following workflows:
- Add reviewer to a request
- Add user to a group
- Edit patchinfo
- Request bugowner change
=> Move autocomplete and tokens from UserController to UsersController

src/backend/bs_publish
The code assumed that $rsync_extra_options was always set.
Fixes issue #8384
=> [backend] bs_publish: fix $rsync_extra_options handling

src/api/app/assets/javascripts/webui/cm2/toolbars.js
On read only mode, we don't render the toolbar and options on the editor.
So the element is not found.
Fix #8273
=> Check if parenthesis matching element exists

ReleaseNotes-2.11, src/api/app/controllers/webui/user_controller.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/app/views/layouts/webui/_logged_in_user_navigation.html.haml, src/api/app/views/layouts/webui/obs_factory/_personal_navigation.html.haml, src/api/config/routes.rb, src/api/spec/features/webui/users/user_home_page_spec.rb
To accomplish it we did:
- Moved home action to WebuiController and adapted the routes
- Removed the old and unused routes '/home/my_work' and '/home/my_project'
- Removed the UserController
Note:
Since nobody access the following routes, and they were already marked as "old routes" since 2.9, I dropped them. Should I add a note to the release notes?
The routes: 
```
get 'home/my_work' => :home
get 'home/list_my' => :home
get 'home/home_project' => :home_project
```
For me it would be ok  to remove the '/home' endpoint too and instead use the `/users/$USER` directly. What do you think @hennevogel ? I deprecated it,  removing it from the partials `_logged_in_user_navigation.html.haml` and `obs_factory/_personal_navigation.html.haml` but it still accessible.
=> Remove UserController

src/api/app/helpers/webui/projects/status_helper.rb
In 3004f02e43d the variable `c` was renamed to `problem`, but this two occurrences were not renamed.
Fixes #6909.
=> Fix renaming of the 'c' variable to 'problem'

src/api/app/views/webui/request/_decision_tab.html.haml
Fixes #7297 and #8403.
The issue happens, for example, when a user receives a delete request from the Admin bot to remove a project to free resources on our always crowded server. It doesn't make much sense to ask for making the requestor to be maintainer of a project that is going to be deleted in the same request.
To verify the changes:
- Go to https://obs-reviewlab.opensuse.org/eduardoj-fix_8403/request/show/2
- Log in with the user 'Iggy'.
- Verify there isn't any "Add user as maintaner" checkbox at the end of the page.
**Update:**
The pull request was modified to take in account the cases where the requests were not of the type `submit`.
=> Prevent showing "Add user as maintaner" checkbox of a delete request

src/api/app/helpers/webui/buildresult_helper.rb, src/api/app/views/webui/package/_buildstatus.html.haml, src/api/app/views/webui/project/_buildstatus.html.haml
Fixes #8101.
To verify the changes:
- Go to [this page](https://obs-reviewlab.opensuse.org/eduardoj-fix_buildresults/package/show/home:Admin/ctris) of the review app.
- Click on "Hide excluded/disabled results".
- Enter the responsive design mode of your browser (Ctrl + Shift + M in Firefox).
- Play with the width of the display window.
=> Make build results more responsive friendly

src/api/app/views/webui/project/_buildstatus.html.haml
Prevents overlapping of columns in small displays.
Apply the same work done in #8405 in package build results, but this time for project build results.
To verify the changes:
- Go to [this page](https://obs-reviewlab.opensuse.org/eduardoj-fix_buildresults_for_projects/project/show/home:Admin) of the review app.
- Enter the responsive design mode of your browser (Ctrl + Shift + M in Firefox).
- Play with the width of the display window.
=> Remove grid witdth definition of second column in build results for projects

src/api/app/controllers/webui/users/rss_tokens_controller.rb, src/api/app/views/layouts/webui/_announcement.html.haml, src/api/app/views/layouts/webui/_logged_in_user_navigation.html.haml, src/api/app/views/layouts/webui/obs_factory/_announcement.html.haml, src/api/app/views/layouts/webui/obs_factory/_personal_navigation.html.haml, src/api/app/views/webui/announcements/show.html.haml, src/api/app/views/webui/user/_info.html.haml, src/api/app/views/webui/users/subscriptions/_breadcrumb_items.html.haml, src/api/app/views/webui/users/subscriptions/index.html.haml, src/api/config/routes.rb, src/api/spec/controllers/webui/users/rss_tokens_controller_spec.rb, src/api/spec/features/webui/notifications_spec.rb, src/api/spec/features/webui/users/user_home_page_spec.rb, src/api/test/fixtures/event_mailer/another_comment_event, src/api/test/fixtures/event_mailer/comment_event, src/api/test/fixtures/event_mailer/commit_event, src/api/test/fixtures/event_mailer/project_comment, src/api/test/fixtures/event_mailer/repo_delete_request, src/api/test/fixtures/event_mailer/request_event, src/api/test/fixtures/event_mailer/review_wanted, src/api/test/fixtures/event_mailer/set_bugowner_event, src/api/test/fixtures/event_mailer/tom_declined, src/api/test/fixtures/event_mailer/tom_gets_mail_too
Some routes are user specific and they are bounded with User.session! therefore instead of force it to be under /users, we can create the routes like:
- /my/tasks
- /my/notifications
...
=> Move user specific urls under scope 'my'

src/api/config/routes.rb, src/api/config/routes/api_routes.rb, src/api/config/routes/webui_routes.rb
In development environment, after a file change, the routes.rb were
reloaded but the files under config/routes don't. In that way, the `File.read` will run always when `routes.rb` gets reloaded.
- run it locally (yes you have to checkout the branch)
- change a controller, i.e open the webui/project_controller#show and add an instance variable `foo = true` go to your browser and try to reload the application.. all routes should be still accessible.
=> Use File.read to force the new routes files to be reloaded

src/api/app/controllers/staging/staging_projects_controller.rb, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
We improve the user experience adding an error message, giving a clue of
what is happening.
Fix #8298
=> Add error message if a StagingWorkflow doesn't exist

src/api/app/views/webui/project/_tabs.html.haml
When the project isn't a staging project.
The other case is when the 'Staging' tab is active. It doesn't rely on authorization.
Fixes #8409
=> Display the 'Staging' tab only for authorized users

dist/obs-bundled-gems.spec
The new version of obs-service-bundle_gems has the
"force_ruby_platform" enabled. This leads to the following error
while build obs-bundle-gems:
```
[  396s] + chrpath --delete '/home/abuild/rpmbuild/BUILDROOT/obs-bundled-gems-2.11~alpha.20190925T165156.cb40d16c84-8857.1.x86_64/usr/lib64/obs-api/ruby/*/gems/sassc-*-x86_64-linux/lib/sassc/libsass.so'
[  396s] open: No such file or directory
[  396s] elf_open: Invalid argument
```
because "libsass.so" no longer gets packaged.
This patch simply returns a "true" value if chrpath fails so the %install
section does not break anymore.
This PR is a follow up for
https://github.com/openSUSE/obs-service-bundle_gems/pull/14
@bugfinder - Thanks for preparing
=> [dist] chrpath in obs-bundled-gems.spec no longer mandatory

src/api/config/application.rb
Before this changes, if you do a change in a route in `config/routes/*`, in the development environment, the server won't reload it. 
With this change, you are able to add a new route to i.e `config/routes/webui_routes` and it will be reloaded automatically.
=> Make sure that if config/routes/* files are changed, they are reloaded

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/package/rdiff.html.haml, src/api/app/views/webui/request/show.html.haml, src/api/spec/controllers/webui/package_controller_spec.rb
Requesting a full diff can mean loading a shitload of data, only allow this for logged in users.
=> Safeguard against anonymous requesting large diffs

src/api/app/controllers/staging/workflows_controller.rb
If an User deletes a staging workflow via API, it should return the "OK" XML as every other endpoint.
Fixes: #8286
=> Fixes #8286: Return XML if staging workflow was successfully deleted

dist/obsworker, src/backend/bs_worker
After https://github.com/openSUSE/obs-build/pull/287, lxc containers
can now use memory limit.
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>
=> Pass memory limit for lxc workers

src/api/app/controllers/webui/staging/projects_controller.rb
There is no reason to require being logged in to obs, in order
to see the content of the staging project show page.
Fixes #7353
=>  Allow accessing staging project show page without being logged in 

src/backend/bs_worker
=> [backend] fix cpeid fallback code for local worker

src/api/app/views/webui/staging/workflows/_build_problems.html.haml
Linking to the live build log when a package is in state broken
doesn't help, since it's the source of the package which causes
the problem and the build log won't show useful infos.
Fixes #7394
=> Dont link to build log if package is in state broken in staging workflow

src/api/app/controllers/staging/staging_projects_controller.rb, src/api/config/routes/api_routes.rb, src/api/config/routes/routes_helper.rb, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
As was pointed out by @coolo, some routes were returning a 'Not route found' error. After applying constraints to the routes the problem is solved.
Fixes #8473.
=> Fix staging workflow routes

src/api/app/controllers/staging/excluded_requests_controller.rb, src/api/app/controllers/webui/staging/excluded_requests_controller.rb, src/api/app/models/staging/request_excluder.rb, src/api/spec/controllers/staging/excluded_requests_controller_spec.rb, src/api/spec/controllers/webui/staging/excluded_requests_controller_spec.rb
Make API and web UI consistent with the same behaviour and error messages.
Fixes #8355.
=> Show a proper error message when excluding a request

src/api/app/models/concerns/staging_project.rb
While migrating the old staging workflow to the new one, the
broken_packages hash moved from strings to symbols for the keys.
One of the checks still uses strings to access the hash, which
led to wrong results.
Fixes #7351
=> Use symbol instead of string to access broken_packages hash in staging project

src/api/app/controllers/webui/patchinfo_controller.rb, src/api/app/helpers/webui/maintenance_incident_helper.rb, src/api/app/views/webui/package/_tabs.html.haml, src/api/app/views/webui/package/side_links/_show_patchinfo.html.haml, src/api/app/views/webui/patchinfo/edit.html.haml, src/api/app/views/webui/patchinfo/form/_issues.html.haml, src/api/app/views/webui/project/bottom_actions/_patchinfo.html.haml, src/api/app/views/webui/project/side_links/_patchinfo_present.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/patchinfo_controller_spec.rb, src/api/spec/features/webui/patchinfo_spec.rb
Refactor `Patchinfo` related routes to a singular resource, with one exception:  `show` 
The missing route is going to be tackled later by some redirects rules because it follows a special routes naming. It would be done in a follow-up PR
=> Refactor routes patchinfo

src/api/app/models/staging/request_excluder.rb, src/api/app/models/staging/stage_requests.rb
Make it clear that a request was not found in a Staging for a project.
Fixes #7355.
=> Improve error message during staging request

src/api/app/datatables/package_datatable.rb
We use the same convention in some other places.
**Before**
**After**
=> Append ' ago' to the time duration in the package change column

src/backend/bs_publish
issue obs#8488
Don't create static links for links already.
But keep working for directories (for product build names without
matching name)
=> [backend] avoid multiple static link creation

src/api/app/views/webui/project/prjconf.html.haml, src/api/app/views/webui/projects/project_configuration/show.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/projects/project_configuration_controller_spec.rb
Move prjconf related routes inside of `resources :project` and create a redirect to the old routes
=> Make prjconf routes resourceful

src/api/app/models/staging/stage_requests.rb, src/api/spec/controllers/staging/staged_requests_controller_spec.rb
When we stage a request, now we add a review `by_project` and accept the existent review `by_group`. The reverse is done when we unstage a request.
Fix #7344
=> Change reviews for staged and unstaged requests

src/api/app/views/webui/staging/projects/_history_elements.html.haml, src/api/app/views/webui/staging/projects/_staging_project_created_history.html.haml, src/api/app/views/webui/staging/projects/_unstaged_staged_request_history.html.haml
=> WIP: Improve rendering/loading time of staging project show

src/api/app/assets/javascripts/webui/monitor.js
Not setting a width in Y axis labels results in not breaking numbers with more than 4 digits in two lines.
Fixes #8222.
Screenshot of one graphic with test data:
=> Remove Y axis label width in monitor page plot graphics

src/api/Gemfile, src/api/Gemfile.lock
This update is causing problems when setting docker from scratch, so we downgrade it to 2.1.0 again. We are waiting for this issue to be fixed: https://github.com/sass/sassc-ruby/issues/146
=> Revert "Update sassc to version 2.2.1"

src/api/app/views/webui/comment/_comment_field.html.haml
This way we make sure that a string is returned, instead of a class.
Errbit is receiving exceptions where the parameters receive something like this:
```
"commentable_type" => "+HCX3IyBjrtZ6Z3UQhVYa8OT3v7eye52V1jbcILfgWtlzj7...",
```
This should fix #8232.
=> Call explicitly name on a class

src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/login-form.js, src/api/app/views/layouts/webui/_login_form.html.haml
=> Make username field to get focus automatically

src/api/app/models/bs_request/find_for/project.rb
Instead of checking for the project to be blank, we should check for the package to be blank.
Fix #4361.
=> Fix condition in BsRequest::FindFor::Project

src/api/app/assets/javascripts/webui/project_monitor.js
Include 'finished' into the states of a package in the monitor page that link to the build logs.
Fixes #8503.
=> Show build logs for finished builds in monitor page

src/api/app/assets/javascripts/webui/cm2/use-codemirror.js
This PR changes the default CodeMirror editor behavior.
Before: when pressing Tab key, insert a tab indention.
After: when pressing Tab key, insert two spaces indention.
It should fix #8504
=> Let editor insert spaces instead of tabs

src/api/app/models/concerns/staging_project.rb, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
The same package appeared more than once because it failed with
different architectures. However, the list is not making distinction by
architecture and the link always points to the same page. So, we will
show each package only once.
Fixes #7362
=> Avoid duplication in broken packages list

src/api/lib/influxdb_obs/obs/middleware/backend_subscriber.rb, src/api/spec/lib/influx_db/obs/middleware/backend_subscriber_spec.rb
The recent influxdb-rails update moved client configuration. It also started
putting everything into on measuring  + a tag for the kind.
=> Fix our custom backend subscriber

src/api/spec/models/project_spec.rb
This offenses appeared with a PR that was merged in master without rebasing the code that updated rubocop gem.
=> Fix rubocop offenses regarding missing parenthesis

src/api/app/controllers/webui/staging/projects_controller.rb, src/api/spec/controllers/webui/staging/projects_controller_spec.rb
Move log writing operation to a background job.
Non-critical operations, like log writing, shouldn't influence in the user experience.
=> Move log writing operation to a background job

src/api/app/views/staging/staged_requests/index.xml.builder
Because this change avoid going after each of the requests to find out
its type.
```
<staged_requests>
<request id="4" type="submit" creator="Admin" state="review" package="doom"/>
</staged_requests>
```
Fixes #7366
=> Add request action type to the staged requests xml response

src/backend/BSSched/BuildJob/Aggregate.pm, src/backend/BSVerify.pm, src/backend/bs_publish
=> Fix publisher sleeping even if there is something to retry

src/backend/bs_publish
they are signed internal, so no additional sha256 or signatures are
needed
=> [backend] publish appx files

docs/api/api/staged_requests.xml
In the Pull Request #8553, we changed the output of the staged_requests.
But we forgot to update apidocs.
=> Update staged request result in apidocs

docs/api/api/api.txt, docs/api/api/backlog.xml, src/api/app/controllers/staging/backlog_controller.rb, src/api/app/views/staging/backlog/index.xml.builder, src/api/app/views/staging/shared/_requests.xml.builder, src/api/app/views/staging/staged_requests/index.xml.builder, src/api/config/routes/api_routes.rb, src/api/spec/controllers/staging/backlog_controller_spec.rb, src/api/test/functional/backend_test.rb
This PR adds a new API endpoint under `/staging_workflow/:project_name/backlog`
And the output is:
```                                                                                                           
<backlog>
<request id="6" type="delete" creator="Iggy" state="review" package="doom"/>
</backlog>
```
Fixes #7393
=> Add a Backlog API endpoint

src/api/app/models/staging/staged_requests.rb, src/api/spec/controllers/staging/staged_requests_controller_spec.rb
Fixes #8522 
Just update the reviews in a request if the request state is `new` or `review`
Add a spec to test to cover the case where request state is `revoked`
=> Set review for staged requests if request state new or review

src/api/app/controllers/webui/projects/status_controller.rb
Fixes #8568 parameter changed from project to project_name. Looks like our specs doesn't cover it.
=> Use param project_name instead of project

src/api/app/views/staging/staging_projects/_checks.xml.builder, src/api/app/views/status/checks/_check.xml.builder
The 'checkable' param was not passed as locals to the partial.
Fixes #8535 
=> Fix checkable error

docs/api/api/staging_project.xml, src/api/app/views/staging/staging_projects/_broken_packages.xml.builder, src/api/app/views/staging/staging_projects/_missing_checks.xml.builder, src/api/app/views/staging/staging_projects/_missing_reviews.xml.builder, src/api/app/views/staging/staging_projects/_requests.xml.builder, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
Fixes #8542 
In the returned XML uses `request` element instead of `entry`
=> Use request instead of entry in the xml

src/api/app/helpers/webui/staging/workflow_helper.rb, src/api/app/views/webui/request/_reviewer.html.haml
To follow what we already do in the 'Latest Updates' section on the homepage.
Fixes #8480
On the staging workflow page, I couldn't use `text-warning`, so I went with `text-dark` instead.
On the request page:
As a reference, this is what we already do in the `Latest Updates` section:
=> Align usage of icons for projects/packages in the UI

src/api/app/assets/javascripts/webui2/cm2/use-codemirror.js, src/api/app/assets/stylesheets/webui2/cm2.scss, src/api/app/views/webui2/shared/_editor.html.haml, src/api/app/views/webui2/webui/package/_revision_diff_detail.html.haml
This way the editor textarea gets maximized most of the times, that is what users want.
Don't show always the bottom box. We prefer to see more from the editor textarea.
Originally authored by @hellcp and @eduardoj 
Backported from #7958.
(cherry picked from commit eb30e4ad3ca6262c7749905db9fb2dde8efedd91)
=> [2.10 backport] Make editor big where needed

src/api/app/helpers/webui/staging/workflow_helper.rb, src/api/app/models/bs_request.rb, src/api/app/models/concerns/staging_project.rb
A couple of improvements to reduce the rendering/loading time of the staging project show view.
Since the package table is also used in the staging workflow show view, it also improves the loading time there.
**Here some numbers**
A staging project with 200 requests and 200 missing reviews:
Before:
(Views: 2451.375ms | ActiveRecord: 122.6ms | Backend: 5.2ms)
After:
(Views: 1390.375ms | ActiveRecord: 25.15ms | Backend: 5.3ms)
It's the avarage result of 4 loading attempts.
Still not blazing fast, but a step in the right direction I would say. :)
Fixes #7350
=> Get rid of n+1 queries and improve rendering time of staging project/workflow

dist/t/spec/features/0040_package_spec.rb, src/backend/BSRPC.pm
Without this patch only a part of the string 'openSUSE.org:openSUSE:Tools'
gets passed to the backend, which quits with a 404 from the remote side.
This behavior is non-determenistic.
SEE ALSO:
teamcapybara/capybara#1890
Fix taken from here:
teamcapybara/capybara#1890 (comment)
This patch
* adds a sleep after clicking "Branch existing project" before entering the strings
to give jQuery the time to complete the animation
* sends the strings char by char to avoid race conditions with autocompletion
=> Fix smoke tests

src/api/config/application.rb
sassc is not thread safe and there are tons of crashes while building packages. Unfortunately #8555 was merged even though the problem was noted there, so applying workaround from the upstream issue.
=> Disable use of concurrency in asset compilation

src/api/app/assets/stylesheets/webui/staging-workflow.scss, src/api/app/helpers/webui/staging/workflow_helper.rb
It's a small difference, but still noticeable. We now use a flex container to center icons of reviewers on the staging workflow page.
This is a follow-up to #8579.
Before:
After:
=> Improve alignment of reviewers icons in staging workflow

src/backend/BSSSL.pm, src/backend/BSVerify.pm, src/backend/bs_repserver, src/backend/bs_srcserver
=> backend: allow _repository:buildflavor in the buildinfo query

docs/ReleaseNotes-2.10, docs/ReleaseNotes-2.6, docs/ReleaseNotes-2.8, docs/ReleaseNotes-2.9
This warning message should have been removed when the releases were published.
=> Remove warning message from release notes

ReleaseNotes-2.11
After updating the obs-api package including the change of the index configuration files for Thinking Sphinx, running the `ts:rebuild` task is required. A comment in this regard is added in the release notes.
=> Add missing ts:rebuild instructions

src/api/app/views/staging/staging_projects/_broken_packages.xml.builder, src/api/app/views/staging/staging_projects/_building_repositories.xml.builder
When checking the overall state of a staging project through
the api, it's not only interesting to know which packages are
broken, but also for which repository, architecture and the
exact state of it.
The building repositories were missing when checking the
overall state of a staging project through the api. This
was caused by syntactically mistakes
Fixes #8529
=> Add missing informations to broken packages xml api response 

src/api/app/models/branch_package.rb, src/api/app/models/branch_package/lookup_incident_package.rb, src/api/spec/models/branch_package/lookup_incident_package_spec.rb
Refactoring the `BranchPackage` "method"
I extracted one more method in a class, beside it:
- Migrate usage of REXML to Nokogiri 
- Extract and Refactor methods
- Add spec for the new class
- Adapt branch_package
=> Refactor look_incident_package method to its own class

dist/systemd/obs-sphinx.service, src/api/lib/tasks/sphinx.rake
Move the logic of when to build indexes while starting sphinx from the systemd unit
to a rake tasks so it's more robust and easier to understand.
=> Introduces sphinx start task

ReleaseNotes-2.10.1
They should have been added when the release was created.
=> Add missing release notes for 2.10.1

src/backend/BSRepServer/Checker.pm, src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Docker.pm, src/backend/BSSched/BuildJob/KiwiImage.pm, src/backend/BSSched/BuildJob/KiwiProduct.pm, src/backend/BSSched/Checker.pm, src/backend/BSSched/DoD.pm, src/backend/BSSched/Remote.pm, src/backend/BSSched/RepoCache.pm, src/backend/BSSrcServer/Remote.pm, src/backend/BSVerify.pm, src/backend/BSXML.pm, src/backend/bs_dodup, src/backend/bs_repserver, src/backend/bs_srcserver, src/backend/bs_worker
You can select the modules you want by setting one or more
expand flags.
For example, "ExpandFlags: module:perl-5.25" will select the
module named "perl" with stream "5.26".
This needs an obs-build package that includes the modules data
parser and an perl-BSSolv package that supports module filtering.
=> [backend] Support building for different modules

src/backend/BSSched/BuildRepo.pm, src/backend/BSSched/DoD.pm, src/backend/bs_repserver, src/backend/bs_srcserver
=> [backend] make clean_obsolete_dodpackages module aware

docs/api/api/api.txt, src/api/app/controllers/staging/staging_projects_controller.rb, src/api/app/views/staging/staging_projects/_staging_project_item.xml.builder, src/api/app/views/staging/staging_projects/index.xml.builder, src/api/app/views/staging/staging_projects/show.xml.builder, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
When retrieving staging projects via API, only a minimal set of information is going to be shown. Any extra information like history, status or even staged requests can be ordered optionally by setting the corresponding parameter in the URL.
Examples:
- `staging/<project>/staging_projects?requests=1&status=1`
- `staging/<project>/staging_projects/<staging_project>?requests=1&status=1&history=1`
This fixes #8527 and fixes #8534
=> Simplify API staging projects results

dist/systemd/obs-sphinx.service
This way we prevent Sphinx to throw errors of connection to mariadb when the setup of OBS is not finished. This happens the first time the appliance is booted.
=> Run sphinx after OBS api setup is done

src/api/app/models/branch_package/lookup_incident_package.rb
Fixes #8672 
`project.ncident_id` would be the right thing to use, but `project.name` is the safest one
=> Use project name instead of incident_id

src/api/app/models/obs_factory/distribution.rb, src/api/spec/helpers/webui/obs_factory/application_helper_spec.rb, src/api/spec/models/obs_factory/distribution_spec.rb, src/api/spec/models/obs_factory/distribution_strategy_opensuse_leap15_spec.rb, src/api/spec/models/obs_factory/staging_project_spec.rb
We only care for openSUSE Leap 15.2 going forward
Co-authored-by: @lnussel
=> Disable 15.0 and 15.1 as valid distributions

src/api/app/views/staging/shared/_requests.xml.builder, src/api/app/views/staging/staging_projects/_requests.xml.builder, src/api/app/views/staging/staging_projects/_staging_project_item.xml.builder
There are different calls to the API where requests' XML is given as result: when retrieving staged requests, backlog requests or even staging projects with the 'requests' option set to truthy.
For those three cases the code has been unified and the XML include attributes like 'superseded_by' and 'updated_at' in addition to 'id/number', 'type', 'package', 'creator' and 'state'.
Fixes: #8540
Before:
```
<staged_requests count="2">
<request id="1" type="submit" creator="requester_2_1572891366_0" state="new" package="target_package_2_1572891366_0"/>                                                  
<request id="2" type="submit" creator="requester_2_1572891366_1" state="new" package="target_package_2_1572891366_1"/>                                                  
</staged_requests>
``` …
=> Add more attributes to requests' XML

src/api/app/datatables/excluded_request_datatable.rb, src/api/app/views/staging/excluded_requests/index.xml.builder, src/api/spec/controllers/staging/excluded_requests_controller_spec.rb
In both webui and API, excluded requests list shows the package name, before there was only the request number.
Fixes: #8524
How to test?
```
osc api -X GET '/staging/<project>/excluded_requests'
```
or in webui
```
/staging_workflows/<staging_workflow_id>/excluded_requests
```
=> Replace request number by package name in excluded requests

src/backend/BSRepServer/YMP.pm, src/backend/bs_publish, src/backend/bs_srcserver
=> Fix cpeid handling and add support for the ymp distversion attribute

src/api/Procfile, src/api/lib/tasks/sphinx.rake
Provide a way to reindex Sphinx when it is started in `NODETACHED` mode. This is only needed in development environment.
The check for rebuilding the configuration of the index was modified to include the condition of no existence of the `config/*.sphinx.conf` file. That is the case of the development environment.
This is a workaround until pat/thinking-sphinx#1150 is fixed.
=> Create Sphinx start Rails task for development environment

ReleaseNotes-2.11
We don't want this task to be run as `root` user. I would create the index files as user `root`, and they need to belong to user `wwwrun`, group `www`.
Thanks @coolo for reporting it.
=> Run ts:rebuild task as user wwwrun

docs/api/api/api.txt, src/api/app/views/staging/staging_projects/_staging_project_item.xml.builder, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
The "requests_to_review" group has been removed, it contains redundant data.
Untracked requests, obsolete requests and missing reviews have been moved from "status" scope to "requests" scope. So they are shown when retrieving staging projects via API with 'requests=1' and not with 'status=1'.
Related tests and API doc has been updated.
Fixes: #8684 
How to test?
```
osc api -X GET '/staging/<project>/staging_projects/<staging_project>?requests=1'
osc api -X GET '/staging/<project>/staging_projects/<staging_project>?status=1'
```
=> Re-organize staging projects XML results

dist/systemd/obs-sphinx.service, src/api/lib/tasks/sphinx.rake
This pull request contains backports of #8645 and #8667 to 2.10 to fix issues I encountered getting the `obs-sphinx` service working while doing an appliance upgrade from 2.9 to 2.10.
These fixes were originally authored by @eduardoj and @hennevogel.
=> [2.10 backport] Fixes for obs-sphinx.service to fix upgrades from 2.9 to 2.10

src/api/app/controllers/webui/staging/projects_controller.rb, src/api/spec/controllers/webui/staging/projects_controller_spec.rb
In Webui, when trying to access to a non-existent staging project, it was raising a 500 error.
Now it is handled to redirect and show a flash message instead.
Fixes: #8685
=> Show proper error for non-existent staging project

src/backend/bs_worker
This brings the code in sync with the product builder, which
also decodes the cpeid right away.
=> [backend] already decode the cpeid in the worker

docs/api/api/api.txt, src/backend/bs_repserver, src/backend/bs_srcserver
=> [backend] add option to show succeeded logfile

src/api/app/controllers/source/errors.rb, src/api/app/controllers/staging/staging_projects_controller.rb, src/api/spec/cassettes/Staging_StagingProjectsController/POST_accept/when_project_is_in_state_acceptable/1_4_3_1.yml, src/api/spec/controllers/staging/staging_projects_controller_spec.rb
Before, it was raising an exception when the staging project didn't exist. 
```
osc api -X GET '/staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:Fake'                                             
=>                                                                                
Server returned an error: HTTP Error 404: Not Found                                  
Couldn't find Project with [WHERE (projects.id not in (0)) AND `projects`.`staging_wor
kflow_id` = ? AND `projects`.`name` = ?]
```
Now, it shows a proper error.
```
osc api -X GET '/staging/openSUSE:Factory/staging_projects/openSUSE:Factory:Staging:Fake' 
=>
Server returned an error: HTTP Error 404: Not Found
Staging Project openSUSE:Factory:Staging:Fake not found.
```
Fixes: #8700 and also fixes: #8686
=> Add error message for non-existent staging project

src/backend/bs_publish
=> Staticlinks fix for product rebuilds after 9999 time

src/api/app/controllers/webui/packages/job_history_controller.rb, src/api/app/models/package.rb
This way the job history of the project of the actual package is shown, instead of the project that a package inherits.
Fixes #6790.
=> Fix wrong job history

src/api/app/models/staging/staged_requests.rb, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_non-existent_target_package/1_2_9_1.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_non-existent_target_package/1_2_9_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_non-existent_target_package/1_2_9_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/with_non-existent_target_package/1_2_9_4.yml, src/api/spec/controllers/staging/staged_requests_controller_spec.rb
It is not defined how to proceed when a request with local links is staged. Both options are possible:
- Create links from the target package.
- Create links from the source package.
Until this is defined we remove the code to create links from the target package.
Fixes #8712 and fixes #8693.
=> Allow to stage new packages again

dist/obs-bundled-gems.spec, src/api/Gemfile, src/api/Gemfile.lock, src/api/docker-files/Dockerfile
They don't like to play well with each other, so at least update them to their latest version.
For sassc we need to disable the cpu specific optimization to avoid running into issue 146 again
=> Fix package build updating sassc and rake

src/api/app/models/concerns/staging_project.rb, src/api/app/views/staging/staging_projects/_missing_reviews.xml.builder, src/api/spec/models/project/staging_project_spec.rb
Show the request number instead the internal id. Also show the submitter and reviewers (by_group, by_user, by_package and by_package).
Fixes #8575.
=> Change missing review output

src/api/app/controllers/staging/workflows_controller.rb
Verification of a previously existing staging workflow for a project was missing on staging workflow creation.
Fixes #8714.
=> Add check for previously existing staging workflow

src/api/app/models/staging/staged_requests.rb
As code for handling delete requests is not yet implemented, we remove the call to the not defined method `is_delete?`.
Fix #8734.
=> Remove not yet implemented is_delete? method

src/api/app/models/project.rb
When we deleted a project associated to a Staging Workflow, this staging
was not deleted. That caused that we couldn't delete the remaning staging
projects.
Fix #8729.
=> Destroy Staging Workflow when we destroy the main project

src/api/app/assets/stylesheets/webui/staging-workflow.scss
Apart from adding a min-height, we also added a background to the
avatar, to make it more visible.
Fix #8735
=> Fix height between staged requests

src/api/app/views/webui/staging/projects/_history_elements.html.haml
When we staged or unstaged a request we didn't show the submitted, but
the user that performed that action.
Fix #8748.
=> Remove `submitted` literal on StagingProject history

src/api/app/views/webui/staging/workflows/_problems.html.haml
We have project names with `.`, that was causing the issue. Now apart
from replacing `:` in the project name we also substitute `.` with `_`.
Fix #8749.
=> Fix collapse on problems list

src/api/app/assets/stylesheets/webui/staging-workflow.scss, src/api/app/helpers/webui/staging/workflow_helper.rb
Delete requests weren't rendered as specified in the legend.
Fix #8739.
=> Display correctly delete requests

docs/api/api/package.rng, docs/api/api/project.rng
These attributes have been removed in 2007 and shouldn't be used anymore.
This fixes #8725.
=> Drop no longer used attributes created and updated from the documentaion

src/backend/BSConfig.pm.template
To prevent other users from reviewing the code to find out how to define Macros on a global base, that you don't need to define them in every `OBS Project`, I added an example to the `BSConfig.pm.template`
=> [backend] add example for global Macros to BSConfig.pm

src/backend/bs_sched
=> [backend] allow to disable early kiwi publishing

src/api/app/models/staging/request_excluder.rb
We must show the request id (number) and not the internal id.
Fixes #8758.
=> Show correct output when excluding an already excluded request

src/backend/BSSched/ProjPacks.pm
Commit 8ad93245da741b2552f88497ea6afbdc019046f7 changed the code
to not propagate med events to locked projects. Unfortunately
it used 'locked' instead of the correct 'lock' to check for
locked projects.
=> [backend] fix typo in alllocked test

src/api/app/controllers/staging/workflows_controller.rb, src/api/spec/controllers/staging/workflows_controller_spec.rb
We check for empty and well-formed xml, providing a better error message output.
=> Add well-formed xml check for workflows controller

src/api/spec/controllers/webui/status_messages_controller_spec.rb
And strings are mappend in rails 6 sometimes to 0 and sometimes to NULL, which makes a difference
=> Fix status_messages_controller_spec: severity is integer

src/api/app/mixins/can_render_model.rb, src/api/spec/controllers/cloud/upload_jobs_controller_spec.rb, src/api/spec/controllers/services/webhooks_controller_spec.rb, src/api/spec/controllers/source_attribute_controller_spec.rb, src/api/spec/controllers/source_project_config_controller_spec.rb, src/api/spec/controllers/source_project_meta_controller_spec.rb, src/api/spec/controllers/source_project_package_meta_controller_spec.rb, src/api/spec/controllers/webui/cloud/azure/upload_jobs_controller_spec.rb, src/api/spec/controllers/webui/cloud/ec2/upload_jobs_controller_spec.rb, src/api/spec/controllers/webui/cloud/upload_job/logs_controller_spec.rb, src/api/spec/controllers/webui/cloud/upload_jobs_controller_spec.rb, src/api/spec/controllers/webui/groups/users_controller_spec.rb
=> Increase compatibility with rails6

src/backend/BSSched/BuildJob/Patchinfo.pm, src/backend/bs_worker
=> [backend] ptf build: take meta from source dir

src/api/app/models/staging/staged_requests.rb
They may be a remote project and we can query the backend
for it to create a link
Fixes #8779
=> Avoid querying the database for request sources

src/api/app/views/webui/projects/pulse/_pulse_list_requests.html.haml
The list of requests in the Pulse page was always showing the creator
instead of the user who performed the action (accept, revoke, etc.).
Now this is fixed and closes #8656
As an example, all the requests were created by scp, but the first was accepted by Admin, the second revoked by scp and the last one declined by Admin as well:
=> Show the correct user in Pulse page

src/api/app/controllers/staging/staged_requests_controller.rb, src/api/app/policies/staging/staged_request_policy.rb, src/api/spec/policies/staging/staged_request_policy_spec.rb
The users of the manager group could unstaged the requests if they
weren't added as maintainers. Now we use a specific policy for staged an
unstaged a request.
Fix: #8784
=> Use correct policies in StagedRequestController

src/api/app/assets/stylesheets/webui/staging-workflow.scss, src/api/app/helpers/webui/staging/project_helper.rb, src/api/app/views/webui/staging/projects/_checks.html.haml
Closes #8741
Preview:
It's not directly related to the issue, but I'm wondering if we should sort the checks by state... Any thoughts?
=> Display an icon based on the state of a check

src/api/app/jobs/project_create_auto_cleanup_requests.rb, src/api/app/models/project.rb, src/api/spec/cassettes/ProjectCreateAutoCleanupRequests/_perform/with_devel_package_inside_the_project/does_not_create_a_deletion_request.yml, src/api/spec/cassettes/ProjectCreateAutoCleanupRequests/_perform/with_project_without_dependencies/sets_a_deletion_request_on_the_project.yml, src/api/spec/factories/attribs.rb, src/api/spec/jobs/project_create_auto_cleanup_requests_job_spec.rb, src/api/spec/support/delayed_job.rb
The performance of the auto cleanup delayed job failed because the check of dependencies raised an exception. So the delayed job was retried again and again.
The exception was caused by a project with a develpackage inside, that couldn't be removed.
Now, instead of raising an exception, the dependencies are correctly checked.
Fixes: #8762
=> Prevent an exception to be raised in auto cleanup

dist/obs-bundled-gems.spec
[dist] update obs-bundled-gems.spec to use libffi-devel and compile
rubygem-ffi against the system libraries. Explicitly enable building
ffi against the system libs using "--enable-system-libffi"
=> use system libraries for libffi instead of intree copy to avoid crash on arm

src/api/app/models/kiwi/image/xml_parser.rb
Avoid relying on autoload to figure that Repository is in the kiwi namespace
As seen on https://circleci.com/gh/openSUSE/open-build-service/34716
=> Fix yet another random test suite failure

src/api/app/models/cloud/ec2/params.rb
Avoid relying on autoload to figure the class is in the same namespace
Fixes #8812
=> Specify namespace of class

docs/api/api/api.txt, docs/api/api/history.rng, docs/api/api/revisionlist.rng
The schema of the `GET /source/<project>/<package>/_history` route is not defined. I have tried my best to guess it from some API calls.
@adrianschroeter: I need the info what the attribute `vrev` of the `<revision>` element is.
=> Add schema of the GET /source/<project>/<package>/_history route

dist/obs-bundled-gems.spec
[dist] revert workaround for mysql from commit
88e0ddaf9306c4f2ed2bb5c2e639a0d263c4959c
now that rubygem-mysql 0.5.3 is out
=> Drop mysql workaround

src/backend/BSSched/EventHandler.pm, src/backend/bs_admin
The scheduler can how write a Devel::MAT pmat file. The memstats
event also includes statistics from glibc's malloc implementation.
(You need the Devel::MAT::Dumper and Devel::Mallinfo modules for
this, respectively.)
=> [backend] add some more memory debugging aids

src/api/app/controllers/statistics_controller.rb, src/api/config/routes/api_routes.rb, src/api/config/routes/webui_routes.rb
The routes are unusable, since the corresponding controller
methods do not exists. They are most likely leftovers
from refactored views.
Fixes #7003
It's still WIP because I'm not yet complete checking the routes for leftovers.
=> Remove dead routes from project

src/api/app/models/issue.rb, src/api/app/models/issue/errors.rb, src/api/app/models/issue_tracker.rb, src/api/app/models/issue_tracker/issue_summary.rb, src/api/app/models/issue_tracker/issue_tracker_helper.rb, src/api/app/models/patchinfo.rb, src/api/spec/models/issue_tracker/issue_summary_spec.rb, src/api/spec/models/issue_tracker/issue_tracker_helper_spec.rb, src/api/test/unit/patchinfo_test.rb
We realized that the issues' models had unused code. In order to have a better codebase we decided to cleanup the unused code and refactor.
Have a look at the commits' descriptions for a more detailed explanation.
=> Refactor code related to issue models 

src/api/app/models/bs_request/errors.rb, src/api/app/models/bs_request_permission_check.rb
=> Move errors from BsRequestPermissionCheck to BsRequest::Errors

src/backend/bs_srcserver
=> [backend] allow module parameter on non-AJAX routes

src/api/app/models/issue.rb, src/api/app/models/patchinfo.rb, src/api/spec/models/attrib_spec.rb, src/api/spec/models/issue_spec.rb, src/api/test/unit/attrib_test.rb
The creation of an issue should be unique regarding the `name` and the
`issue_tracker_id`.
Fix #4044
=> Add uniqueness validation on Issue

src/api/app/helpers/webui/staging/project_helper.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/models/concerns/staging_project.rb, src/api/app/views/webui/staging/projects/_broken_packages.html.haml, src/api/app/views/webui/staging/projects/_status_items.html.haml, src/api/app/views/webui/staging/projects/show.html.haml, src/api/app/views/webui/staging/workflows/_problems.html.haml, src/api/spec/controllers/staging/staging_projects_controller_spec.rb, src/api/spec/helpers/webui/webui_helper_spec.rb
workflow#show used a different way than project#show leading to fixes for one broke the other.
So this moves the `problems` function from the model to a helper that can is used by both views
Reverts parts of #8521, fixes #7362 differently and fixes #8802
=> Harmonize display of broken packages

src/api/app/assets/javascripts/webui/patchinfo.js
Closes #8798
Submitting at once the same issue multiple times by separating its instance with commas does remove the duplicates which were entered by the user. However, as described in the issue, it was possible to add the same issue multiple times by adding them one by one. These changes prevent this.
Nothing changed visually... so no screenshots.
=> Prevent duplicate issues in patchinfo

src/backend/BSSched/BuildJob.pm
This makes kiwi use the correct scheduler architecture, i.e.
the architecture configured in $BSConfig::localarch.
=> [backend] kiwi builds: use repoarch for builds with arch=local

src/api/app/controllers/webui/package_controller.rb, src/api/app/models/package.rb, src/api/spec/cassettes/Webui_PackageController/POST_trigger_rebuild/when_triggering_a_rebuild_fails/1_14_3_1.yml, src/api/spec/cassettes/Webui_PackageController/POST_trigger_rebuild/when_triggering_a_rebuild_fails/1_14_3_2.yml, src/api/spec/cassettes/Webui_PackageController/POST_trigger_rebuild/when_triggering_a_rebuild_with_maintainer_of_package/1_14_3_1.yml, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/spec/factories/packages.rb
Fix #6758 
Let package maintainers to trigger rebuild.
Use just `pundit` as authorization avoiding any second model authorization.
=> Allow a package maintainer to rebuild packages

src/api/app/models/issue.rb, src/api/app/models/patchinfo.rb, src/api/spec/models/attrib_spec.rb, src/api/spec/models/issue_spec.rb, src/api/test/unit/attrib_test.rb
Reverts openSUSE/open-build-service#8796
This PR broke the patchinfo generation for the Maintenance Team. Reverting it
=> Revert "Add uniqueness validation on Issue"

src/api/app/controllers/webui/project_controller.rb
This is already handled by column sorting in datatables.
Fixes #8328.
=> Remove unneeded default sorting of project results

src/api/app/views/webui/shared/user_or_groups_roles/_index.html.haml, src/api/app/views/webui/shared/user_or_groups_roles/_list.html.haml
Datatable javascript was raising an exception because the action column was missing the column header.
The action column is now rendered when a user is logged in.
Fixes #8681.
=> Show action column when user is logged in

src/api/app/models/bs_request_action.rb, src/api/app/models/bs_request_action/errors.rb
Follow-up PR of #8861 and #8848 
Cleaned the method `create_expand_package` little bit leading to a reduction in the `Metrics/PerceivedComplexity` score (From 73 to 65) and `Metrics/CyclomaticComplexity` score (from 67 to 61). Both are still far from threshold (45) allowed by Rubocop.
=> Refactor create expand package

src/api/app/models/staging/staged_requests.rb, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/with_the_same_package/1_2_9_1_1_2.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/with_the_same_package/1_2_9_1_1_3.yml, src/api/spec/cassettes/Staging_StagedRequestsController/POST_create/when_providing_two_request/and_none_is_excluded/with_the_same_package/1_2_9_1_1_4.yml, src/api/spec/controllers/staging/staged_requests_controller_spec.rb
In #8736 an error was thrown when a second request for the same target package wanted to be added, preventing the creation of the linked package. But the request was still staged.
Now both, the linked package and the staged request are not created.
Fixes #8730.
=> Prevent staging a request with errors

src/backend/BSRepServer.pm, src/backend/BSRepServer/YMP.pm, src/backend/BSSrcServer/Remote.pm, src/backend/bs_getbinariesproxy, src/backend/bs_publish, src/backend/bs_repserver, src/backend/bs_sched, src/backend/bs_srcserver, src/backend/bs_worker
requires build script support as well
=> [backend] support zstd arch binaries

src/api/script/start_test_backend
Test log produced by testsuite contains messages from frontend and backend.
Sometimes it's not obvious which backend server produced some message.
This change makes log messages produced by backend during tests
to be prefixed by the name of the server which produced the message.
Also, a message is logged when backend server has stopped running.
Signed-off-by: Oleg Girko <ol@infoserver.lv>
=> [api] Log server name to test log for backend log messages.

src/api/Makefile
This allows installing OBS API correctly when OBS_API_PREFIX variable
defined in Makefile.include has value different than "/srv/www/obs/api".
Signed-off-by: Oleg Girko <ol@infoserver.lv>
=> [api] Use $OBS_API_PREFIX instead of explicit pathname for installing.

src/api/test/unit/active_support_test_case_extensions.rb, src/api/test/unit/validator_test.rb
Instead of testing for specific Nokogiri error messages, that change from
version to version, let's test what is important for us: That invalid things
don't go through the validator.
Also move out the ActiveSupport::TestCase monkey patch tests to their own file.
They have little to do with the validator.
Fixes #8934
=> Refactor validator test

src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/helpers/webui/staging/workflow_helper.rb, src/api/app/views/webui/staging/workflows/_infos.html.haml, src/api/app/views/webui/staging/workflows/_requests_list.html.haml
The reason for the request exclusion is shown in the info list.
=> Show excluded request description on info list

src/api/app/controllers/trigger_controller.rb, src/api/spec/controllers/trigger_controller_spec.rb
Triggering package release via a token did only release one project,
because .any? does not continue after first successful evaluation.
Also remove superflous permission check for target, release_package does that
already. And throw a 404 if the project has no release targets.
Co-authored-by: Stefan Seyfried <stefan.seyfried@sap.com>
Supersedes #8945
=> Fixes releasing for multiple targets via trigger

src/api/lib/obsapi/markdown_renderer.rb
CodeRay throws an exception if you give it a language it doesn't find a plugin
for. Reported as rubychan/coderay#245
Fixes #6960
=> Catch CodeRay exception for invalid language

src/backend/BSSched/BuildJob/Patchinfo.pm
The retracted element is empty, so one has to use an existance
check to find out if it is present or not.
=> [backend] Patchinfo.pm: fix check of retracted status

src/backend/BSSched/BuildResult.pm
Same as https://github.com/openSUSE/open-build-service/pull/8950 , but github disallows a reopen..
=> [backend] fix package lock check on wipe event

src/api/app/assets/stylesheets/webui/staging-workflow.scss
Fixes #7352 partially, not the part of paginating the history.
This is how it will look like:
=> Use the whole screen instead of using only a half

src/api/app/controllers/webui/package_controller.rb
`require 'project'` was unnecessary and dubious
=> Remove unnecessary require call

src/api/app/helpers/webui/staging/workflow_helper.rb
The [original piece of code](https://github.com/openSUSE/open-build-service/blob/675c1238d2c467f6720f9dd8e78f22c3841454d7/src/api/app/presenters/obs_factory/staging_project_presenter.rb#L133) returns 0% when there are no checks.
Also refactor a little piece of code.
Fixes #8794.
=>  Show 0% of tests done where there are no checks 

src/api/app/views/webui/project/_tabs.html.haml
It should only point to new_staging_workflow_path if there isn't a staging
workflow.
Fixes #8951
=> Fix staging tab link

src/api/app/assets/stylesheets/webui/staging-workflow.scss, src/api/app/decorators/staging/project_decorator.rb, src/api/app/views/webui/staging/workflows/_empty_projects_list.html.haml, src/api/app/views/webui/staging/workflows/_overall_state.html.haml, src/api/app/views/webui/staging/workflows/_staging_project.html.haml, src/api/app/views/webui/staging/workflows/_staging_projects_table.html.haml, src/api/spec/decorators/staging/project_decorator_spec.rb
Fixes #8787  
Showing the full project name again in the staging projects
table is redundant and usually not needed.
Now in case a project title is set, it will use it in the staging projects table instead of
the project name. This allows the staging managers to customize the naming.
Also, since some staging projects are meant for specific packages the description
of the project is now shown in a tooltip when hovering over the link to the staging project 
in the table. This makes it easier to get an quick overview.
=> Show project title in staging projects table

src/api/app/models/package.rb, src/api/app/queries/packages_finder.rb, src/api/spec/cassettes/PackagesFinder/_by_package_and_project/package_and_project_exist/1_1_1_1.yml, src/api/spec/cassettes/PackagesFinder/_by_package_and_project/package_or_project_doesn_t_exist/1_1_2_1.yml, src/api/spec/cassettes/PackagesFinder/_find_by_attribute_type/when_package_is_invalid/1_2_3_1.yml, src/api/spec/cassettes/PackagesFinder/_find_by_attribute_type/when_package_is_nil/1_2_1_1.yml, src/api/spec/cassettes/PackagesFinder/_find_by_attribute_type/when_package_is_valid/1_2_2_1.yml, src/api/spec/cassettes/PackagesFinder/find_by_attribute_type_and_value/when_package_is_nil/1_3_1_1.yml, src/api/spec/cassettes/PackagesFinder/find_by_attribute_type_and_value/when_package_is_nil/1_3_1_2.yml, src/api/spec/factories/attribs.rb, src/api/spec/queries/packages_finder_spec.rb
In the quest of reduce the complexity and size of controllers and models, we introduced long time ago services objects, which reside in `app/services`, now following the design patterns, we are introducing the query object pattern, which the implementation will be located under `app/queries`.
The idea is to extract complex SQL queries or scopes to it's own PORO class, where we can better manage and test, removing some code which the implementation isn't so relevant to the models or controllers. 
The reasoning behind it is to use the battle tested design patterns to try to keep the base sane and avoid 700+ lines of models/controllers. 
References: 
https://www.martinfowler.com/eaaCatalog/queryObject.html
https://mkdev.me/en/posts/how-to-use-query-objects-to-refactor-rails-sql-queries …
=> Add Query objects to Package model

src/backend/BSSched/PublishRepo.pm, src/backend/bs_publish
First part as a proposal. Usecase are esp :Update repositories which must be there from the beging but can be empty. Otherwise QA checks for the distro my fail.
This rule allows the publisher to create a repo neverthless even though there are now binaries. Second part would be to trigger the publish from scheduler if that flag is set.
I think @bugfinder will love that feature and be done just by setting up the publish rule in prjconf altogether with the rest....
=> [backend] allow publishing of empty repository

dist/obs-server.spec
It is needed to query arch linux packages. Having it
not installed will result in hard to debug error messages.
=> [dist] add dependency to zstd

src/api/.rubocop_todo.yml, src/api/db/seeds.rb, src/api/spec/controllers/source_project_package_meta_controller_spec.rb, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/spec/controllers/webui/search_controller_spec.rb, src/api/spec/features/webui/packages_spec.rb, src/api/spec/helpers/webui/flash_helper_spec.rb, src/api/spec/models/backend_info_spec.rb, src/api/spec/models/branch_package_spec.rb, src/api/spec/models/bs_request/find_for/user_spec.rb, src/api/spec/models/bs_request_spec.rb, src/api/spec/models/download_repository_spec.rb, src/api/spec/models/group_spec.rb, src/api/spec/models/project_spec.rb, src/api/spec/models/review_spec.rb, src/api/spec/rails_helper.rb, src/api/spec/support/database_cleaner.rb, src/api/spec/support/shared_examples/features/flags_tables.rb, src/api/test/functional/attributes_test.rb, src/api/test/functional/maintenance_test.rb, src/api/test/functional/search_controller_test.rb, src/api/test/unit/package_test.rb, src/api/test/unit/project_test.rb, src/api/test/unit/schema_test.rb
Fix some RuboCop cops' offenses with: rake task dev:lint:rubocop:auto_correct. These RuboCop cops' offenses are not related with style cops.
=> Fix some other RuboCop offenses with autocorrect

src/api/Gemfile, src/api/app/controllers/distributions_controller.rb, src/api/app/controllers/mail_handler_controller.rb, src/api/app/controllers/webui/obs_factory/distributions_controller.rb, src/api/app/controllers/webui/obs_factory/staging_projects_controller.rb, src/api/spec/controllers/public_controller_spec.rb, src/api/spec/controllers/source/key_info_controller_controller_spec.rb, src/api/spec/controllers/statistics/maintenance_statistics_controller_spec.rb, src/api/spec/controllers/status_project_controller_spec.rb, src/api/spec/controllers/trigger_controller_spec.rb, src/api/spec/controllers/webui/image_templates_controller_spec.rb
The gem was only used in the tests, as rails 4.2 was introduced.
=> Remove not needed/used "responders" ruby gem

src/api/spec/controllers/staging/staged_requests_controller_spec.rb, src/api/spec/factories/bs_requests.rb, src/api/spec/factories/staging_workflow.rb, src/api/spec/jobs/bs_request_action_webui_infos_job_spec.rb, src/api/spec/models/bs_request_spec.rb
Do not set the session in a factory. Especially if you don't reset it afterward! This is something you should do inside your test. I ran into weird permission problems in another factory because User.session changed to some random user...
=> Save the bs_request factory always as the creator

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/DeltaRpm.pm
the job history hash can be reused for storing stats.
=> split addjobhist into two parts

src/api/lib/tasks/dev.rake
As default the development environment will be running with `responsive_ux`
toggle enabled.
=> Enable responsive_ux for development environment

src/backend/bs_publish
Makes it possible to define project global milestones in prjconf
=> [backend] support milestone publishing using macros

src/backend/bs_redis
bs_redis does not use the BSStdRunner framework, so it is not
set up as default. So set up a logging to /bs/log/redis.crit.log.
=> [backend] bs_redis: set a critlogger for critical events

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildResult.pm, src/backend/BSSched/PublishRepo.pm, src/backend/BSXML.pm, src/backend/bs_check_consistency
THe stats are stored in the simple file format, so external processsing
can be easy. This allows changes to the format and structure. The
xml from _statistics file parsed into an hash and is flattened into an
array. This xml template used to parse the _statistics file is also
flattened into an array. This array acts as an overlay to store the
stats.
Since the same xml template is used to parse xml and as layout of
storage, this patch acts like a converter from xml to tabular format.
A simple and implementation independent file format is chosen to allow
easy enhancement to the schema without affecting the application code
=> start storing build stats whenever possible.

src/backend/BSSched/BuildJob.pm, src/backend/BSXML.pm, src/backend/bs_repserver, src/backend/bs_srcserver, src/backend/bs_worker
If the "obsgendiff" build flag is set and the repository has at
least one release target, we get all published files with the
suffix ".obsgendiff" from the first target.
It is up to the build job to do the diff and create new .obsgendiff
files.
=> [backend] add support for buildflags:obsgendiff for diff generation

src/backend/BSSched/BuildJob.pm, src/backend/BSXML.pm
Fix flat_hash documentation, it returns a hash ref.
Simplify flat_hash implementation.
Switch arguments in flat_hash so that it can be called with just
the hash ref.
Simplify flat_hash usage by running it just once and not multiple
times.
=> [backend] simplify stats writing

src/api/app/views/webui/package/_revision_diff_footer.html.haml
The url to ask the data to prefill was not provided and so the form was unable to work properly.
Fixes #7551
Note the target project, target package, supersede request check and package clean up check in the screenshots below
**Before**
**After**
=> Provide the url to get the required data for the form prefilling

src/backend/bs_redis
We did not account for the length of such events, leading to
corrupt data if another error happened.
=> [backend] fix handling of marked-as-done events in bs_redis

src/backend/BSSched/BuildJob.pm, src/backend/BSXML.pm, src/backend/bs_repserver, src/backend/bs_srcserver, src/backend/bs_worker
=> [backend] get obsgendiff working

src/api/app/helpers/proxy_mode_helper.rb, src/api/app/views/webui/session/_form.html.haml
=> Tell the proxy where to redirect to after login

src/api/app/views/layouts/webui/webui.html.haml
~~To remove the jumping effect of the containers depending on the size of
the viewport. We made the container fluid for all the viewports with
width < 1540px.~~
We made the container responsive for all the viewports with
width < 1540px. So the container doesn't take anymore different
max-width depending on the viewport, profiting better the horizontal
space.
=> Make the container fluid

src/api/app/views/webui/main/_user_proceed-list.html.haml, src/api/app/views/webui/user/_breadcrumb_items.html.haml, src/api/app/views/webui/users/_breadcrumb_items.html.haml, src/api/app/views/webui/users/show.html.haml
To avoid confusion between the concepts "Your Home" and "Your Home Project",
the first one has been renamed to "Profile".
The icon for "Profile" is now a user icon instead of a house, which
is commonly used for the main page (a.k.a landing or home page).
=> Replace "Your Home" by "Profile"

src/backend/BSSched/BuildJob.pm, src/backend/bs_worker
this patch moves some of the code around into a new function . It adds a
few lines for the real work of creating file when there is no change.
The code for the new function `updatestatsfromfile` add stats to the
passed in hash after reading it from file. The function is not
responsible for checking the existence of file and its format.
=> [backend] generate _statistics file when the result is no-change

docs/api/validate_xml.py
Python 2 has been EOL since January 2020, and distributions like Fedora
are intending to remove Python 2 soon. Thus, this is minimally ported
to Python 3 to remove the Python 2 dependency.
Reference: https://fedoraproject.org/wiki/Changes/RetirePython2
=> [docs] Port validate_xml.py to Python 3

dist/Makefile, dist/obs-server.spec
This logic only makes sense on SUSE Linux distributions, where the
packaging policy indicates this preference. The links don't work
at all on Fedora or any other distribution.
=> [dist] Migrate SUSE-specific rcFOO link creation from Makefile to spec

src/backend/BSPublisher/Registry.pm, src/backend/BSRepServer/Containertar.pm, src/backend/BSRepServer/Registry.pm, src/backend/bs_regpush
Esp. to avoid armv6 and v7 conflicts
The kiwi/umoci/docker/podman tooling seems not to support it yet, but that are independend bugs.
Could not test it for real therefore yet.
=> [backend] support container architecture variants

src/api/app/models/worker_status.rb, src/api/app/queries/project_names_finder.rb, src/api/spec/models/worker_status_spec.rb
Related with https://github.com/openSUSE/open-build-service/pull/9010
Refactoring and improvements being done in the model `WorkerStatus`:
- Focus on the method `WorkerStatus.hidden`
- Added spec for it
- Extracted sql query to a query object
- Instead of loop through all entries on worker_status trying to match for a name, filter the results using "XML XPATH"
- Extract small methods from it
=> WorkerStatus refactoring

src/backend/bs_srcserver
=> [backend] support rpm's %include statement

dist/obs-server.spec
This way OBS installed in SUSE and openSUSE distributions, and also the OBS appliances will find again the OBS apache configuration file.
openQA tests for OBS appliances are failing. Applying this patch would fix them.
=> Fix virtual hosts apache subdirectory in spec file

src/backend/bs_dispatch
The nativeonly flag was checked in the body of two nested loops,
taking way too much time if there are many jobs and many idle
workers. Add a cache so that we can prune workers that we know
cannot build the job.
Also remove the worker from the idle list if its file is gone.
Not removing it led to lots of unneccessary constrain checks.
=> [backend] bs_dispatch: speed up nativeonly handling

dist/obs-server.spec, src/backend/BSRepServer/Checker.pm, src/backend/BSRepServer/Remote.pm, src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Docker.pm, src/backend/BSSched/BuildJob/KiwiImage.pm, src/backend/BSSched/BuildJob/KiwiProduct.pm, src/backend/BSSched/BuildRepo.pm, src/backend/BSSched/Checker.pm, src/backend/BSSched/DoD.pm, src/backend/BSSched/Remote.pm, src/backend/BSSched/RepoCache.pm, src/backend/BSSrcServer/Remote.pm, src/backend/BSVerify.pm, src/backend/BSXML.pm, src/backend/bs_dodup, src/backend/bs_getbinariesproxy, src/backend/bs_repserver, src/backend/bs_srcserver, src/backend/bs_worker
This pull request backports the changes needed to support using modules on OBS 2.10 from git master. Thus, this still has the same quirks as the support in OBS git master (no module dependency resolution, ignorance of content shadowing, no build environment property propagation, etc.). Essentially, modules are treated _solely_ as sub repositories (similar to sections in Debian repositories).
<strike>This PR is marked as draft because I'm still testing the functionality with my internal instance. Moreover, there's no released version of [perl-BSSolv](https://github.com/openSUSE/perl-BSSolv) with module support.</strike>
**EDIT: The only thing missing now is a released version of [perl-BSSolv](https://github.com/openSUSE/perl-BSSolv) with module support.**
This is derived from the following …
=> [2.10 Backport] Add support for handling modules (Fedora Modularity)

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/Checker.pm
This means that every source change leads to an extra build, but
it matches the most likely use case of generated build dependencies.
We may want to revisit this in the future. An idea would be to
only do this is there the build dependencies are unresolvable.
=> [backend] put verifymd5 into the genbuildreqs result

src/backend/BSRepServer/Containertar.pm, src/backend/bs_repserver
We need a variant for the publishing of arm container. Unfortunately
no container build tool writes the variant in the container config,
so we're using the scheduler architecture as a hint.
=> [backend] fake container variant by looking at the scheduler arch

src/backend/BSXML.pm, src/backend/bs_repserver
this access is very similar to jobhistory route. This patch also add and
extra datastructure to BSXML. This structure acts as dtd for returned
data
=> [backend] give api access to .stats file

src/api/app/assets/javascripts/webui/datatables.js, src/api/app/assets/javascripts/webui/project.js, src/api/app/assets/stylesheets/webui/datatables.scss
- Change the pagination style (globally) to fit better in smaller resolutions
- Remove the number of elements per page for the `Projects#index`
- Center pagination controls for the `Projects#index`
=> Projects#index improvements 

docs/api/api/constraints.rng, docs/api/api/obs.rng
instead of fixed choice list. dispatcher code is dealing them as strings
anyway
=> [api] handle cpu flags as strings in schema

src/api/script/prepare_spec_tests.sh
Different distributions have the mysqld binaries in different places.
This change makes api test to search for these binaries in
`/usr/bin`, `/usr/sbin` and `/usr/libexec` directories.
Additionally, set the pidfile so that MariaDB/MySQL runs
on Fedora.
=> [api] Detect the correct mysqld binary for tests

dist/obsscheduler, dist/sysconfig.obs-server
=> [backend] add option to preload jemalloc for schedulers

dist/obs-server.spec, dist/obsscheduler, dist/obsstoragesetup, dist/obsworker, dist/rc.status
As systemd is being used to manage OBS services, systemV method calls are no longer needed. Removing systemV code and compatibility packages (as insserv-compat) makes it more clear OBS services handling.
Labelling as "DO NOT MERGE" untill the changes in the service scripts are tested. The pull request was created to receive feedback about removing systemV from the OBS codebase.
=> Get rid of systemV

src/api/app/assets/javascripts/webui/datatables.js, src/api/spec/features/webui/groups_spec.rb, src/api/spec/features/webui/users/admin_configuration_spec.rb
Reducing redundant text from Datatables information as described: https://datatables.net/reference/option/language
=> Change the datatables information text

src/backend/BSSched/Checker.pm, src/backend/BSSched/EventHandler.pm, src/backend/bs_repserver, src/backend/bs_sched
This is a bit of a hack. The purpose of this is so that the scheduler does not send a repo finished event if there is still some copying going on in the background.
=> Suspend the scheduler if we do binary copies in the background

src/api/app/models/channel.rb
@msmeissn code is deployed and data is re-indexed.
=> [api] fix channel indexing for multibuild references

src/api/app/assets/stylesheets/webui/project-package-show-grid.scss, src/api/app/views/webui/shared/_buildresult_box.html.haml
Make it easier to trigger a refresh of the build results, without the need of scrolling up and down on pages with lots of build results elements.
=> Make refresh button sticky on top of build results

src/api/app/assets/stylesheets/webui/build-results.scss, src/api/app/views/webui/package/_buildstatus.html.haml, src/api/app/views/webui/project/_buildstatus.html.haml
This way we prevent the elements to wrap when there is still enough space, or to overlap. This change is applied both to the build results of a project and a package.
**Before:**
**After:**
=> Use flex in build results elements

src/api/config/routes/api_routes.rb, src/api/config/routes/webui_routes.rb
=> [api] move api routes from webui to api definitions

src/api/app/assets/javascripts/webui/buildresult.js, src/api/app/assets/stylesheets/webui/build-results.scss, src/api/app/controllers/webui/package_controller.rb, src/api/app/helpers/webui/buildresult_helper.rb, src/api/app/views/webui/package/_buildstatus.html.haml, src/api/app/views/webui/project/_buildstatus.html.haml
The collapse/uncollapse status is kept for each element between refreshes of build results.
Also make the clickable area bigger for collapse/uncollapse icons. These icons were moved to the right.
All these changes contribute to the navigation experience related to build results.
=> Provide a collapse icon for multibuild packages

docs/api/api/configuration.rng
=> [doc] add api_url element

src/api/app/controllers/webui/package_controller.rb, src/api/lib/backend/api/sources/package.rb, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_an_empty_revision_is_provided/1_12_2_1.yml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_an_empty_revision_is_provided/1_12_2_2.yml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_no_difference_in_sources_diff_is_empty/1_12_1_1.yml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/with_diff_truncation/full_diff_not_requested/for_ASCII_files/shows_the_truncated_diff.yml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/with_diff_truncation/full_diff_not_requested/for_archives/shows_the_truncated_diff.yml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/with_diff_truncation/full_diff_not_requested/shows_a_hint.yml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/with_diff_truncation/full_diff_requested/does_not_show_a_hint.yml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/with_diff_truncation/full_diff_requested/for_ASCII_files/shows_the_complete_diff.yml, src/api/spec/cassettes/Webui_PackageController/GET_rdiff/with_diff_truncation/full_diff_requested/for_archives/shows_the_complete_diff.yml, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/test/functional/webui/spider_test.rb, src/backend/bs_srcserver
We'll use this in the API to defer source diffing to a delay job,
so that the WebUI does not clog up all source server slots.
=> [backend] add 'cacheonly' option for diffing sources

src/api/app/models/issue.rb, src/api/app/models/issue_tracker.rb, src/api/db/data/20190130115727_add_github_issue_tracker.rb, src/api/db/seeds.rb, src/api/spec/factories/issue_tracker.rb, src/api/test/fixtures/issue_trackers.yml, src/api/test/functional/issue_controller_test.rb, src/api/test/functional/issue_trackers_controller_test.rb
write as
gh#$project/$repo#$issue
eg
gh#openSUSE/build#123
needs unfortunality a special hack, since github URLs expect /issues/
inside.
=> [api] support generic github issues

src/api/db/data/20190307145633_migrate_rss_notification_payload.rb
In PR#6879 we converted the commenter and commenters entries of
event payloads. Since the RSS Notification payload is relying
on some of the event views and methods, this broke our RSS feeds.
This commit adds a data migration that converts existing RSS feeds.
Fixes #7134
=> Convert rss notification payload

dist/README.UPDATERS
- correct commands to avoid failures
- we did not recommend to use zypper services yet
- drop lines only needed to 2.9 in 2.10 section
- recommend to reboot instead just to restart some frontend parts only
=> Fix updater notes to 2.10

src/api/app/services/trigger_controller_service/token_extractor.rb
When validating Gitlab webhook triggers the authentication token
is only valid for "Push Hook" events.  Gitlab has multiple events
that could be valid.  Choosing to accept the Gitlab authentication
header does not need to be dependent on the webhook event.
This single line patch only checks for the http header X-GITLAB-TOKEN
and removes the dependency on the X-GITLAB-EVENT.
=> Remove Gitlab webhook event restriction during authentication.

src/api/app/models/user.rb, src/api/spec/controllers/webui/users_controller_spec.rb, src/api/test/functional/person_controller_test.rb
also fix code which may remove other users home projects with
starting with same login string
should be backported to 2.10 therefore.
=> [api] remove personal data on user delete

src/api/app/models/project/remote_url.rb
As apache does not have proxy env vars with systemd #6810, http_proxy is broken is some places: #3143 #3133 #3935 #2958
Current code does try to workaround the issue by settings http_proxy env when it is missing. However, it is not used by https:// URI. Accessing https://api.opensuse.org (when adding a new repo) generates:
```
I, [2020-01-15T18:55:36.628560 #4291]  INFO -- : [a76ce02a-fb1a-4bcc-b9af-7716766173c0] [4291:998.17] method=GET path=/project/add_repository_from_default_list/tresc format=html controller=Webui::RepositoriesController action=distributions status=500 error='Errno::EHOSTUNREACH: Failed to open TCP connection to api.opensuse.org:443 (No route to host - connect(2) for "api.opensuse.org" port 443)' duration=193.70 view=0.00 db=5.02 params={"project"=>"tresc"} …
```
=> Also set https_proxy if missing

src/api/app/controllers/webui/package_controller.rb
When we're triggering the build from a linked project, the Pundit Policy checker
for the package fetches the package's project, not the one we're rebuilding
from.
This PR detects if we're triggering the build from a linked project and then
passes that project to Pundit to perform the authorization.
Fixes #6289
=> Authorize against the linked project instead of the package's project

src/api/app/assets/javascripts/webui/datatables.js
Enable the responsive extension to be able to control datatables in different query medias https://datatables.net/extensions/responsive/
=> Enable datatable responsive plugin as default

ReleaseNotes-2.11, src/backend/BSDispatcher/Constraints.pm
Instead of accepting only one match of cpu flags while
constraints validation all flags must be present in the
worker
=> [backend] fix oracle to match multiple cpu flags

src/backend/BSSched/Checker.pm, src/backend/BSSched/EventHandler.pm, src/backend/bs_repserver
Now that those events stack they are no longer idempotent. Thus we
need to randomize the event name.
=> [backend] do not overwrite suspendproject/resumeproject events

src/backend/bs_srcserver
=> [backend] add _buildstats api to src_server to handle partitioning and queryparam

src/api/app/views/webui/main/index.html.haml
The "latest_updates" card is only displayed if allow_anonymous configuration
option is allowed.  This patch allows authenticated users to get the
"latest_updates" card even if allow_anonymous is not allowed.
=> Allow authenticated users to see latest_updates card on the main page.

dist/setup-appliance.sh
Without this patch starting apache in a setup with setup-appliance.sh runs into the following error:
```
Feb 27 08:09:55 wizard-install start_apache2[5138]: AH00526: Syntax error on line 86 of /etc/apache2/vhosts.d/obs.conf:
Feb 27 08:09:55 wizard-install start_apache2[5138]: Invalid command 'XForward', perhaps misspelled or defined by a module not included in the server configuration
```
=> [dist] enable xforward in setup-appliance.sh

src/api/app/assets/javascripts/webui/project_monitor.js
Following #9136, datatables are all responsive by default and this causes
issues for datatables with many columns like project#monitor, which is often
huge. Eventually, pages with such datatables will have to be redesigned. For
now, disabling the responsiveness will do.
Fixes #9145
=> Disable responsiveness on project#monitor datatable

src/api/app/controllers/webui/session_controller.rb
If anonymous access is not allowed and a user logs out the
user is redirected back to the referring page prior to logout.  This
redirection produces a error since anything other than the root path
is now unavailable to the user.
This patch will redirect the use to the root path on logout if anonymous
access is not allowed.
=> Fixed logout redirection when anonymous access is not allowed.

src/api/app/models/issue_tracker.rb
=> fix crash while evaluating github show url

src/api/app/assets/javascripts/webui/requests_table.js
Both tables have the same column widths defined with column.width option.
However table in “Tab 2” has column widths different from the table in “Tab 1”.
After click we have to adjust the columns
Before:
After:
=> Fix table width when tab is switched in small screens

docs/api/api/api.txt, src/api/app/controllers/issue_trackers_controller.rb, src/api/test/functional/issue_trackers_controller_test.rb
eg. via
` # osc api -e /issue_trackers/$tracker
`
we need to backport in case 2.10 is also affected.
Also all other places in test suite where "put ...., params: $body_data"
is used needs to be checked if we broke the api there as well.
needs to become raw_put again...
=> [api] fix editing of issue tracker entries

src/api/app/assets/stylesheets/webui/project-package-show-grid.scss, src/api/app/assets/stylesheets/webui/responsive_ux.scss, src/api/app/helpers/webui/buildresult_helper.rb, src/api/app/views/webui/package/_buildstatus.html.haml
Align project and package buildresult:
- Collapse icon placed on the right.
- Fix sticky refresh button when user are not in beta.
- Use flex instead of col and row.
Fix #9157
=> Align project and package buildresult

src/api/app/assets/javascripts/webui/requests_table.js
This javascript snippet was used in the old UI. This class `.result_reload` doesn't exist anymore.
=> Remove left-over javascript from old UI

src/api/app/assets/javascripts/webui/buildresult.js, src/api/app/assets/stylesheets/webui/build-results.scss, src/api/app/assets/stylesheets/webui/responsive_ux.scss, src/api/app/assets/stylesheets/webui/responsive_ux/_build-result.scss, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/helpers/webui/buildresult_helper.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui/package/responsive_ux/_buildstatus.html.haml, src/api/app/views/webui/project/responsive_ux/_buildstatus.html.haml
Using tooltips in buildresult are not every usable for small viewports,
even on a big viewport, due to it can contain a considerable amount on
the content.
=> BuildResult Tooltip

src/api/app/models/user.rb, src/api/spec/models/user_spec.rb
The construction ` Project.where("name LIKE '#{home_project_name}:%'")` even though safe in the context being used, should be avoided.
=> Fix brakeman complain on user model

src/api/app/helpers/webui/sponsor_helper.rb
Before, when displaying the sponsor's logos we used `icons_stripe.png` which included them.
Now, after some refactoring and under beta program, we are displaying the logos using its own image files, like `sponsor_suse.png`.
However, they weren't correctly displayed in production. This PR adds their extensions, that were missing, in order to solve the problem.
Fixes:  #9183
=> Add extension to sponsor's images

.circleci/config.yml, dist/obs-server.spec, hakiri.yml, src/api/Gemfile, src/api/config/brakeman.ignore
We moved to brakeman, to check the codebase for security
vulnerabilities, on the open-build-service master branch (>2.10).
In order to get rid of hakiri for the whole project, we need
to backport those changes, which only affect the CI setup.
=> Use brakeman instead of unmaintained hakiri for 2.10

src/api/app/assets/stylesheets/webui/responsive_ux.scss, src/api/app/assets/stylesheets/webui/responsive_ux/_layout.scss, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_nobody_navigation.html.haml
In top and bottom navigation bars, having only icons wasn't clear enough, so we add texts under them.
For consistency, we also add icons to those which didn't have, like _Sign Up_ and _Log In_.
Therefore, the bars height and elements sizes and spacing had to be adapted.
=> Align navigation items adding always icons and texts for consistency and clarity

src/api/app/assets/javascripts/webui/responsive_ux.js, src/api/app/assets/stylesheets/webui/responsive_ux.scss, src/api/app/assets/stylesheets/webui/responsive_ux/_layout.scss, src/api/app/views/layouts/webui/responsive_ux/_actions.html.haml, src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_nobody_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_user_navigation.html.haml, src/api/app/views/webui/main/_actions.html.haml, src/api/app/views/webui/main/_status_messages.html.haml, src/api/app/views/webui/main/index.html.haml
Before with actions and generic links all over the page.
Now, the actions are in their own menu and generic links in the existing menu where we already have `Profile` and other links. The icons don't have a color anymore as more colors didn't fit well on a dark background. The menu with generic links is also available to anonymous users whenever links make sense for such users (like `All Projects` or `Status Monitor`). The button for the actions menu is hidden whenever it's empty or for anonymous users. Depending on the role of the user, the actions and the generic links will vary to follow the user's permissions.
------
Actions
Large devices:
Small devices:
-----
Generic menu
Large devices:
Small devices:
=> Actions for main#index

src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_nobody_navigation.html.haml
Following up on #9188, we now have the same icon for the generic menu. Other
changes were done to have a consistent look.
The changes are for large devices only. Small devices didn't need them since it's already done.
Menu as an anonymous user
Before:
Now:
Menu as an authenticated user
Before:
Now:
=> Align structure of the generic menu for all devices and users

src/backend/call-service-in-docker.sh
listing all files with local temporary filenames is confusing.
Also the shell wrapper debug should not be needed, we should
give proper messages in the tooling instead
=> [backend] avoid debug lines in call service wrapper

src/api/script/api_minitest.sh, src/api/script/prepare_spec_tests.sh
build using the current user and try not to break older mariadb
revisions in the process where socket auth was not loaded by default.
=> [api] fix build for mariadb-10.4

src/api/db/migrate/20200311132129_make_notifications_polymorphic.rb, src/api/db/structure.sql
This commit is one of a serie of commits to make notifications a polymorphic association. Later on we will adapt the existing code, and remove the fields that will be not needed, to make a smooth
transition.
=> Add "notifiable" polymorphic fields to table "notifications"

src/api/app/assets/stylesheets/webui/responsive_ux/_layout.scss
=> Reduce the gap between flash and top navigation bar

src/api/app/views/webui/user/_involvement.html.haml
After turning the tabs into horizontally scrollable tabs
for the beta program, there were a few mistakes in the
structure of the haml file and some bootstrap classes got lost.
Fixes #9215
=> Fix tabs in users profile view.

src/api/app/assets/stylesheets/webui/responsive_ux/_layout.scss, src/api/app/assets/stylesheets/webui/responsive_ux/_tabs.scss
This results in modals appearing on top of the off-canvas menu since they have a `z-index` of 1050.
It prevent the tabs' scrollbar to appear on top of modals with a `z-index` of 1050 and the off-canvas menu with a `z-index` of 1040.
Fixes #9216
Before (modal not visible, it's under the off-canvas menu)
Before (the tabs' scrollbar is on top of the modal)
Now (the modal is visible on top of the off-canvas menu and the scrollbar isn't visible anymore on top of the modal)
=> Adjust z-index of off-canvas menu and scrollable tabs

ReleaseNotes-2.11, src/backend/bs_publish, src/backend/bs_signer
incompatible change, but solves the issue with sha256sum -c failures
We try to get rid away without additional configuration option, but it is known that the sha256 files are not identical anymore. We will see if we need to make it optional...
=> [backend] create detached gpg signatures of .sha256 files

src/api/.rubocop_todo.yml, src/api/app/jobs/send_event_emails_job.rb, src/api/app/models/bs_request.rb, src/api/app/models/comment.rb, src/api/app/models/event/comment_event.rb, src/api/app/models/event/request.rb, src/api/app/models/notification.rb
We want to store notification data in the newly created polymorphic fields from the notifications table. We don't modify yet the existing way of reading the notifications table.
=> Write data into the new polymorphic fields from the notifications table

src/api/app/jobs/send_event_emails_job.rb, src/api/db/migrate/20200313143312_add_bs_request_status_to_notification.rb, src/api/db/structure.sql
At the time we access the state, it could already have been changed. We need to store this field when the notification is created.
We store the "state" only when it is needed, for notifications coming from events with type "RequestStatechange". The other request and comment notifications don't make use of this "state" field.
Related to #9206 and #9220.
=> Add request state field to notifications table

src/api/app/assets/stylesheets/webui/responsive_ux/_tabs.scss
The `z-index` which was set for tabs in #9218 was higher than the navigation elements and other values set by [Bootstrap](https://getbootstrap.com/docs/4.4/layout/overview/#z-index).
=> Lower z-index of tabs so they don't appear on top of navigation elements

src/api/app/models/bs_request.rb, src/api/app/models/comment.rb, src/api/app/models/notification.rb
In order to query the comments and request related to a
notification, the polymorphic association needs to be
indicated in the models.
Related to #9206 and #9220.
=> Add polymorphic association between BsRequest, Comment and Notification Model

src/api/app/jobs/send_event_emails_job.rb
Due to a typo `notification_id` field was introduced when trying to add data to the notifications table. The correct name should have been `notifiable_id`.
=> Fix notifiable id fields in notifications table

src/api/db/migrate/20200317120346_add_title_to_notification.rb, src/api/db/structure.sql
We want to store the subject of an event in the notifications table when a notification is inserted in the table, so we add this new `title` field.
=> Add title field to notifications table

src/backend/BSSSL.pm
The leak was introduced when we modernized the file handle
usage in commit 30b5fa2a25bcacf237c9a2ec61b97dde2f182585.
This led to a cyclic reference which meant that https
sockets were no longer closed automatically.
We now use 'local' again in BSSSL as a workaround. I hope that
this works with all perl versions.
=> [backend] BSSSL: fix potential file descriptor leak

src/api/db/migrate/20200318123203_rename_status_to_state_in_notifications.rb, src/api/db/structure.sql
The original name of the field in the `bs_requests` table ~was~ is `state`, not `status`.
=> Rename bs_request_status column to bs_request_state in notifications table

src/api/app/jobs/send_event_emails_job.rb
Fix storing `comments` and `bs_requests` in notifications. The complete name of the class, starting with `Event::`, was needed.
The `title` field of notifications is filled with the result of calling the `subject` method of the event.
=> Fix inserting comments and requests, and fill title in notifications

src/backend/bs_dodup
=> [backend] bs_dodup: support xz compressed Packages files

src/api/app/models/user.rb, src/api/spec/models/user_spec.rb
We have some users which have the field `last_logged_in` `nil` which was leading to break the method `User.away?` 
We fall back the `last_logged_in` to the `created_at` if it's nil
=> User#last_logged_in should fallback to create_at in case it is nil

src/api/app/assets/javascripts/webui/collapsible_text.js, src/api/app/assets/javascripts/webui/responsive_ux.js, src/api/app/controllers/webui/project_controller.rb, src/api/app/views/webui/project/_basic_info.html.haml, src/api/app/views/webui/project/_bottom_actions.html.haml, src/api/app/views/webui/project/_edit.html.haml, src/api/app/views/webui/project/edit.js.erb, src/api/app/views/webui/project/responsive_ux/actions/_edit_project.html.haml, src/api/app/views/webui/project/show.html.haml, src/api/app/views/webui/project/show.js.erb, src/api/app/views/webui/project/update.js.haml, src/api/config/routes/webui_routes.rb
This is our suggestion:
- in-place edition for the **project**'s basic information
- instead of editing each form element, we propose to edit the whole form (including Title, URL and Description)
- we use Rails UJS
- we add some JavaScript animations for the transitions from content to form and the other way around
It looks like:
Validations are going to be shown in the form as well:
Something similar will be done for packages, after we have a quite stable version for projects.
Please take into account that we tried to add little commits to make it easier for you to follow our reasoning. They will be squashed before becoming a real PR.
=> In-place edition for project basic information

src/api/app/jobs/send_event_emails_job.rb, src/api/app/models/comment.rb, src/api/app/models/notification.rb, src/api/app/models/review.rb, src/api/app/views/notifications/_actions.text.erb, src/api/app/views/notifications/_add_role_action.text.erb, src/api/app/views/notifications/_change_devel_action.text.erb, src/api/app/views/notifications/_delete_action.text.erb, src/api/app/views/notifications/_group_action.text.erb, src/api/app/views/notifications/_set_bugowner_action.text.erb, src/api/app/views/notifications/_submit_action.text.erb, src/api/app/views/notifications/comment_for_package.text.erb, src/api/app/views/notifications/comment_for_project.text.erb, src/api/app/views/notifications/comment_for_request.text.erb, src/api/app/views/notifications/request_create.text.erb, src/api/app/views/notifications/request_statechange.text.erb, src/api/app/views/notifications/review_wanted.text.erb, src/api/app/views/webui/feeds/notifications.rss.builder, src/api/spec/controllers/webui/feeds_controller_spec.rb
As part of our proccess of migrating notifications to new polymorphic columns with zero downtime, here we read RSS feeds also from the new polymorphic columns.
=> Read RSS feeds also from new polymorphic notification columns

src/backend/BSSched/BuildJob.pm, src/backend/BSSrcServer/SQLite.pm, src/backend/bs_dbtool
This is a better match for the content of the table.
=> [backend] sqlite: rename prp_ext table to repoinfo while we can

dist/obs-server.spec, src/backend/BSSched/BuildJob/Patchinfo.pm, src/backend/modifyrpmheader, src/backend/obs-ptf.spec, src/backend/t/0021-BSXPathKeys.t
This makes sure that generated subpackages like debuginfo
also have the needed requires. It also adds a reference
to the master ptf package to the description.
=> [backend] automatically add requires to ptf packages

dist/t/spec/features/0040_package_spec.rb
Fix openQA failure because of a typo :roll_eyes:
=> Fix typo on expect to have content

src/backend/bs_repserver
WSL applicance for TW currently has three components as it also embeds
the TW version number.
=> bs_repserver: allow more than to components in appliance build numbers

docs/api/api/api.txt
The API docs were omitting the detail, that the `DELETE /source/<project>/<package>/<filename>` also makes a commit.
=> [doc] Add note that filename deletion makes a commit

src/api/app/presenters/notification_presenter.rb
The notifications for ReviewWanted and CommentForRequest
are taking the wrong object.
=> Fix notification link for Notification

src/backend/bs_worker
=> [backend] allow running the worker without ssl support

src/backend/bs_worker
=> [backend] fix cleanup chroot code to not fail without chroot

src/backend/BSSched/Remote.pm
We used the unfiltered modules when calculating the modulestr,
leading to setting the wrong cache element. This caused the
scheduler to request the repository state over and over again
if the repository used a module that did not exist.
=> [backend] remote cache: fix typo in modulestr calculation code

src/backend/BSConSign.pm, src/backend/BSPGP.pm, src/backend/BSPublisher/Registry.pm, src/backend/bs_repserver, src/backend/bs_srcserver
=> Implement project atomic style container signatures

src/api/app/models/event/build.rb, src/backend/bs_repserver
this count will help track long failing packages
=> [backend] include count of cumulative build failures in notifications

src/api/app/mailers/event_mailer.rb, src/api/spec/mailers/event_mailer_spec.rb
The corner case of sending a mail to only a group, that hasn't an email defined, was not taken into account.
This patch makes the code not to send an email in this case.
Fixes #9114.
=> Don't send emails to groups without an email

src/api/app/views/webui/users/notifications/index.html.haml
The names was not break words like 'home:bar:foo:..'
breaking the responsiveness of the page
Fix #9276
=> Fix notification list with large project names

src/api/app/helpers/webui/package_helper.rb, src/api/spec/helpers/webui/package_helper_spec.rb
=> [webui] Show full humanized time

src/backend/BSSrcServer/Multibuild.pm, src/backend/BSSrcServer/Projlink.pm, src/backend/bs_srcserver
=> findpackages: move multibuild processing after project link processing

src/backend/bs_repserver
openSUSE Leap 15.2 product releases use "-BuildX.Y" as setrelease.
This leads to double match which breaks the name and adds unwanted X.Y.Z
result.
=> [backend] solve double match special case for setrelease

ReleaseNotes-2.10.2
The gem rails was updated in branch 2.10. We should add a note in the release notes for the next 2.10.2 minor release.
=> Add security update note for rails gem in release notes

src/api/.jshintrc, src/api/Gemfile, src/api/Gemfile.lock, src/api/app/assets/javascripts/webui/application.js
While working on the [Webpacker card](https://trello.com/c/Gg2gJcwH/1346-try-webpacker-again), I've found out that we have a few JS dependencies which we don't use anymore. Let's remove them.
=> Remove unneeded JS dependencies

src/backend/BSPublisher/Registry.pm, src/backend/bs_regpush
The variant is not in the image config, but only in the containerinfo
data.
=> [backend] fix container variant handling

src/backend/bs_worker
this buildflag is to be manually added in project config as
BuildFlags: useccache:package-name
along with this ccache has be included as BuildRequires in the spec file
for ccache to be installable.
If buildflag is added but ccache is not present it will result in error
=> [backend]pass --ccache param if usecache:packid is present as buildflag

src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_user_navigation.html.haml, src/api/app/views/webui/users/notifications/index.html.haml
This implies removing the `All Requests` workaround we had in the `Notifications` page. The link to the `Notifications` page in the top-level navigation is now correctly named.
The changes on desktop and mobile:
=> Link to Tasks in the Places menu

dist/obs-server.spec
where it belongs according to package conventions
=> [dist] move memcached restart to postun of obs-api package

src/backend/bs_worker
it is racy by design, since a job can get aborted at any time in parallel.
The method name (rm_rf) is a bit questionable, since "rm -rf" would never return an error.
=> [backend] fix dying workers in cleanup_chroot mode

src/api/db/data/20200326170855_remove_obsolete_notifications.rb, src/api/db/data/20200326221616_regenerate_notifications.rb, src/api/spec/db/data/regenerate_notifications_spec.rb, src/api/spec/db/data/remove_obsolete_notifications_spec.rb, src/api/spec/factories/event_subscriptions.rb
After some refactoring made on the Notifications code and database structure, some data had inconsistent values.
Therefore, we have added data migrations to remove the affected notifications and re-generate them based on the objects existing in the database. For example, if we find in the database a request with state new, we are adding a notification to announce its creation even if it was created some weeks ago.
The data migrations affects notifications related to: RequestCreate, ReviewStatechange, ReviewWanted and CommentForProject.
The migration for removal and re-generation are in different files and has independent tests. It's been made like this to simplify understanding and testing.
This is a follow-on #9307. Which includes some refactoring needed to be able to create …
=> Notifications data migration

src/api/app/models/notification.rb
We always want to see the most recent notifications.
=> Add descendent order in notification

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/controllers/webui/users/rss_tokens_controller.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_navigation.html.haml, src/api/app/views/webui/user/_info.html.haml, src/api/app/views/webui/users/subscriptions/_breadcrumb_items.html.haml, src/api/app/views/webui/users/subscriptions/index.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/users/notifications_controller_spec.rb, src/api/spec/controllers/webui/users/rss_tokens_controller_spec.rb, src/api/spec/features/webui/notifications_spec.rb, src/api/test/fixtures/event_mailer/another_comment_event, src/api/test/fixtures/event_mailer/comment_event, src/api/test/fixtures/event_mailer/commit_event, src/api/test/fixtures/event_mailer/project_comment, src/api/test/fixtures/event_mailer/repo_delete_request, src/api/test/fixtures/event_mailer/request_event, src/api/test/fixtures/event_mailer/review_wanted, src/api/test/fixtures/event_mailer/set_bugowner_event, src/api/test/fixtures/event_mailer/tom_declined, src/api/test/fixtures/event_mailer/tom_gets_mail_too
Today we have the `SubscriptionsController` pointing to the `/my/notifications` routes and the `/users/:username/notifications` pointing to the `Users::NotificationsController` which should point to `/my/notifications` 
after this PR we are going to have the following routes:
`/my/notifications` and `/my/submissions`. One pointing to the users notifications and the other to manage the notification submissions.
=> Notifications routes

src/api/app/models/bs_request.rb, src/api/app/models/user.rb, src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_navigation.html.haml
We don't rely on a cache for this since it's only a simple count.
Preview on desktop and mobile:
In case you wonder, this would fit 999 999 notifications before it breaks. It's even more on desktop, so we should be alright!
=> Display the number of unread notifications in the top-level navigation

src/api/app/views/webui/users/notifications/index.html.haml
This slipped through in the routing changes in 1e7c46c09060c7a6412c0340513da56442d89e2a
=> Fix notification update path

src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_navigation.html.haml
We added a missing bootstrap class to align the badge with the bell icon.
=> Add vertical alignment to notification badge

src/backend/bs_repserver, src/backend/bs_worker
=> [backend] filter out ccache archive while listing package binaries

.circleci/config.yml
The new ci docker containers project has been created with the idea of creating the containers used in the CI test suite for Unstable. So upgrading the version of the underlying system of the containers doesn't affect the CirleCI configuration any more.
This new ci docker containers repo is now using SLE15 SP1 docker base images, instead of SLE12 SP4.
=> Change CircleCI config to use new ci docker containers repo

src/backend/BSUrlmapper.pm
=> [backend] urlmapper: match both http and https when mapping urls

.circleci/config.yml
We should run the CI of releases against the OS we release with.
=> Switch CI containers to openSUSE Leap 15.1

src/api/app/views/webui/users/subscriptions/index.html.haml, src/api/config/routes/webui_routes.rb
Add a custom name for the update route, to be able to use `/subscriptions/update` without id and keep the `my_subscriptions_path` pointing to the `SubscriptionsController#index`
Visit the Profile -> Change your notifications (update your notifications should work as expected)
Notifications -> Actions -> Manage Subscriptions (should bring you to your subscriptions index, and there you could update your notifications)
=> SubscriptionsController update route

Makefile.include
The correct ruby version should be 2.5 instead of 25.
This issue was found trying to generate the apidocs in the development environment.
=> Fix typos in ruby variables in Makefile

src/backend/BSSched/PublishRepo.pm
files starting with .(dot) are ignored already
=> [backend] ignore ccache.tar.gz before publishing; remove .stats

src/api/app/views/webui/package/_files_view.html.haml
In certain cases, the md5 and mtime value of a file is the same
for multiple files. Only the file name differs in those cases.
This needs to be considered, in order to have uniq data in the
cache.
In the past this lead to not show certain files in the
webui due to this rails/rails#35145
Since this got fixed, it now does the opposite (showing duplicated entries),
which is more obvious.
Since osc shows the correct files, and missing files are less
obvious than duplicates, this probably took a while to be reported
as an issue.
Fixes #9352
**Example data:**
```
{:name=>"cross-i386-gcc7.changes", :size=>"21895", :mtime=>"1586940815", :md5=>"8cb7fb57285bc929b7bc0ffa5edc6b29", :viewable=>true, …
```
=> Take file name into account for file partial caching

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/models/notification.rb, src/api/app/models/user.rb, src/api/app/views/webui/users/notifications/index.html.haml, src/api/spec/controllers/webui/users/notifications_controller_spec.rb
`Inbox` is now `Unread` and `Done` is now `Read`.
=> Mark notification as `unread`

src/api/app/views/webui/apidocs/index.html.haml
After upgrading to Rails 6, rendering the raw content of a html file needed to use the `raw` method.
Fixes #9382.
=> Fix apidocs rendering

src/api/app/controllers/request_controller.rb, src/api/app/jobs/project_create_auto_cleanup_requests.rb, src/api/app/models/bs_request.rb, src/api/app/models/event/comment_for_request.rb, src/api/app/models/review.rb
The BsRequest method is renamed for consistency with the rest of the
equivalent methods added to models related to notifications.
This is a follow-up to the refactoring PR #9307 (starting from [this line](https://github.com/openSUSE/open-build-service/pull/9307/files#diff-d476b59ba5326de67e0c155e8e226d6fR1070)).
=> Rename notify_parameters to event_parameters

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/helpers/webui/notification_helper.rb, src/api/app/views/webui/kaminari/_paginator.html.haml, src/api/app/views/webui/users/notifications/index.html.haml, src/api/config/locales/kaminari.en.yml
Notifications are now paginated.
A `Show all` link is provided to display the notifications all at once. But there is a limit set by `MAX_PER_PAGE`. In case of exceeding this limit, a flash message will be shown and the results will be paginated with `MAX_PER_PAGE` notifications per page.
=> Add pagination to notifications

src/backend/bs_publish
When kiwi produces install.tar
files (eg. minimal-sle-15-sp1.x86_64-0.1.1-oem-Build25.15.install.tar),
also create static links for theses files. Otherwise, only the
versioned file is available.
Fixes #9398
=> bs_publish: Create staticlinks for install.tar files

src/api/app/models/user.rb, src/api/app/views/webui/users/tasks/index.html.haml
Since Ruby on Rails introduced recycable cache keys, which
we enabled with the migration to Rails 6.0, we need to pass
the cache_version in combination with the cache_key (which
now is a stable value) in order to receive the most
recent data.
Related to #9352
=> Use cache version to fetch cached users tasks

src/api/app/models/user.rb, src/api/app/views/webui/users/tasks/index.html.haml, src/api/config/application.rb, src/api/spec/models/bs_request_spec.rb, src/api/spec/models/review_spec.rb
Since we lately experienced some issues related to the newly
introduced cache versioning, we should disable it for now and
first adjust/check our codebase accordingly.
=> Disable cache versioning

src/api/app/views/webui/kaminari/_paginator.html.haml, src/api/app/views/webui/package/revisions.html.haml, src/api/app/views/webui/search/_results.html.haml, src/api/app/views/webui/search/_results_issue.html.haml
Some pages use [kaminari](https://github.com/amatsuda/kaminari) for pagination. However, they weren't taking the right generated views for them.
We have to specify that the views are inside `webui` with `views_prefix: 'webui'`. Otherwise, kaminari would try to find them in  `app/views/kaminari` instead of `app/views/webui/kaminari`.
**Before:**
**After:**
=> Adjust pagination in some pages

src/api/app/assets/stylesheets/webui/application.scss, src/api/app/assets/stylesheets/webui/project-monitor.scss
When there are many repositories to render in the Repositories dropdown the
topmost options were being rendered behind the top navbar.
Raising the z-index of the dropdown's content, we make them visible again.
Fixes #9350
**Before**
**After**
=> Show Project monitor's repository dropdown's topmost options

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/SimpleImage.pm
We do not want to create images with broken dependencies. So
we add --ignoreignore-- both for the meta expansion and the
build expansion.
=> [backend] do not ignore dependencies for simpleimage builds

src/api/app/models/event/request_statechange.rb, src/api/app/presenters/notification_presenter.rb, src/api/app/views/webui/users/notifications/index.html.haml, src/api/spec/db/data/regenerate_notifications_spec.rb, src/api/test/fixtures/event_mailer/tom_declined, src/api/test/functional/request_events_test.rb
According to the type, the notifications list will also show an excerpt
of the description (requests), body (comments) or reason (reviews).
On `RequestStatechange` notifications, both old and new states are included in the title.
=> Preview on notification

src/api/app/presenters/notification_presenter.rb
For a while, the notifiable_id values were wrong in the database, so we couldn't rely on it to get the "notifiable" object (review, comment) and its request.
As a temporary solution we took the request number from the event payload. PR #9286.
Now that the values in the database are correct (after a data migration) the workaround is reverted.
=> Use back notifiable to get the corresponding object

src/backend/BSSched/BuildJob.pm
The buildflags:useccache substitute can be used in the project
config to add different packages.
=> [backend] automatically add the ccache package if useccache is set

src/api/app/controllers/webui/projects/pulse_controller.rb
Now we only set the pulse data for ajax requests.
When bots hit a project's pulse page, the before_action is not called
and then the page breaks.
Fixes #9370
=> Set pulse data for all request types

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/jobs/send_event_emails_job.rb, src/api/app/models/event/base.rb, src/api/app/models/event_subscription/find_for_event.rb, src/api/app/models/group.rb, src/api/app/models/notification.rb, src/api/app/models/user.rb, src/api/app/services/notification_creator.rb, src/api/db/data/20200424080753_generate_web_notifications.rb, src/api/db/data_schema.rb, src/api/db/migrate/20200422134122_add_rss_and_web_to_notification.rb, src/api/db/structure.sql, src/api/spec/controllers/webui/users/notifications_controller_spec.rb, src/api/spec/db/data/generate_web_notifications_spec.rb, src/api/spec/db/data/regenerate_notifications_spec.rb, src/api/spec/factories/notification.rb, src/api/spec/jobs/send_event_emails_job_spec.rb, src/api/spec/models/user_spec.rb, src/api/spec/services/notification_creator_spec.rb
Following with the PR #9405. This PR affects `send_event_emails_job` job (a job for creating the notifications and send email) and user notifications view.
We also added a data migration to duplicate the existent notifications to create Notification::WebItem records and also create subscriptions for `rss` and `web`.
=> Adapt Job to handle new notification channels

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/helpers/webui/notification_helper.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/models/notified_project.rb, src/api/app/queries/notifications_finder.rb, src/api/app/services/notification_creator.rb, src/api/app/views/webui/users/notifications/index.html.haml
This PR is a follow-up to #9433.
The notifications can be now filtered by the projects associated to them.
To do so, a list of project names and a the number of notifications per project are displayed.
=> Notifications filtered by projects

src/api/app/jobs/consistency_check_job.rb, src/api/app/services/consistency_check_job_service/backend_package_importer.rb, src/api/app/services/consistency_check_job_service/backend_project_importer.rb, src/api/app/services/consistency_check_job_service/base_consistency_checker.rb, src/api/app/services/consistency_check_job_service/package_consistency_checker.rb, src/api/app/services/consistency_check_job_service/project_consistency_checker.rb, src/api/app/services/consistency_check_job_service/project_meta_checker.rb, src/api/lib/tasks/delayed_job.rake, src/api/spec/cassettes/ConsistencyCheckJob/_check_one_project/1_2_1.yml, src/api/spec/cassettes/ConsistencyCheckJob/_check_project/fix_false/1_3_1_1.yml, src/api/spec/cassettes/ConsistencyCheckJob/_check_project/fix_true/project_should_call_store.yml, src/api/spec/cassettes/ConsistencyCheckJobService_BackendPackageImporter/_call/it_raises_ActiveRecord_RecordInvalid/1_1_1_1.yml, src/api/spec/cassettes/ConsistencyCheckJobService_BackendPackageImporter/_call/it_raises_Backend_NotFoundError/1_1_2_1.yml, src/api/spec/cassettes/ConsistencyCheckJobService_BackendProjectImporter/_call/it_raises_APIError/1_1_1_1.yml, src/api/spec/cassettes/ConsistencyCheckJobService_BackendProjectImporter/_call/it_raises_ActiveRecord_RecordInvalid/1_1_2_1.yml, src/api/spec/cassettes/ConsistencyCheckJobService_BackendProjectImporter/_call/it_raises_Backend_NotFoundError/1_1_3_1.yml, src/api/spec/cassettes/ConsistencyCheckJobService_ProjectMetaChecker/_call/everything_goes_well/1_1_1_1.yml, src/api/spec/jobs/consistency_check_job_spec.rb, src/api/spec/services/consistency_check_job_service/backend_package_importer_spec.rb, src/api/spec/services/consistency_check_job_service/backend_project_importer_spec.rb, src/api/spec/services/consistency_check_job_service/base_consistency_checker_spec.rb, src/api/spec/services/consistency_check_job_service/package_consistency_checker_spec.rb, src/api/spec/services/consistency_check_job_service/project_consistency_checker_spec.rb, src/api/spec/services/consistency_check_job_service/project_meta_checker_spec.rb
This PR looks big, but actually it's not.
It's basic a refactoring of two rake tasks from [delayed_job.rake](https://github.com/openSUSE/open-build-service/blob/master/src/api/lib/tasks/delayed_job.rake#L33), `check_project` and `fix_project`
The changes are:
- Removed two checks: if there are packages and projects with invalid names. We have name validation for both, on frontend and backend. 
- Added spec for the the `ConsistencyCheckJob` class itself
- Extracted auxiliary code to services 
- Added spec to the services
- Changed the `ConsistencyCheckJob` class without change it's API
- Improved documentation
=> Refactor ConsistencyCheckJob job

src/backend/bs_notifyforward, src/backend/bs_redis
=> [backend] ping when exiting/restarting the redis services

src/backend/bs_worker
=> [backend] link_or_copy ccache tar for followup mode, if it exists

src/api/spec/models/bs_request_action/differ/source_package_finder_spec.rb
The test was checking the result elements in a specific order. As the result elements are returned unsorted, changing the matcher to the collection membership matcher `match_array` makes the
test not to flick any more.
Fixes #9457.
=> Solve RSpec SourcePackageFinder flickering test

src/api/app/views/webui/staging/workflows/_infos.html.haml
This isn't fixing #8745, it's only a slight improvement.
=> Go to the "Incoming Reviews" of a group when clicking on "Backlog" link

src/api/app/views/webui/project/_tabs.html.haml
This applies to the beta UI (under `responsive_ux`) and the default UI.
Preview:
=> Don't mark the Staging tab as active for a staging project

src/api/config/initializers/airbrake.rb
Those won't work against an errbit server, which is the error reporting
server we support. Fixes #9455
=> Disable airbrake server features

src/api/app/models/concerns/staging_project.rb
The list of requests in a staging project was sorted by name.
Now it is sorted by state and then by name. This way, the requests that require more attention will be on the top of the list.
=> Sort staging requests by state and name

src/backend/bs_repserver
=> [backend] tighten condition for successive_failcount

src/backend/BSRepServer/Checker.pm, src/backend/BSSched/Checker.pm
=> [backend] buildinfo expansion: translate ldep repodata to testcase format

src/api/lib/tasks/dev.rake
We no longer use the id but the name of the project to access to its staging workflow.
=> Correct output of the staging rake task

src/api/app/controllers/staging/staging_projects_controller.rb
In the previous, PR #9470 we changed the build flags, but we forgot to apply these changes in the backend.
=> Write to backend after change build flags of a StagingProject

src/api/spec/features/webui/packages_spec.rb
Before, the test was returning false positives because asking for `tr` elements returned also the `tr` element of the `thead` section of the table. The part `"Created Source Target Requester Type Priority"` was the clue on the error message:
```
expected to find visible css "table#all_requests_table tr" 1 time, found 2 matches: "Created Source Target Requester Type Priority", "now source_project / package_764 home:package_test_user / test_package user_1047 submit moderate"
```
The fix was making the css finder more explicit, searching only for the `tr` elements of the `tbody` part of the table.
Fixes #7533.
=> Fix requests flickering test

src/api/db/structure.sql, src/api/lib/tasks/databases.rake
In our CI test suite we have a check for diffs in the `structure.sql` file.
The `git diff` check was not working properly. There were three cases:
1. When there were no differences: it worked properly.
2. When the diff output was too small: it gave a false positive.
3. When the diff output was big enough: it gave a false negative. It errored because of a timeout, and not because of an exit code of `git diff`.
The fix in this pull request makes the `git diff` command return the proper exit code:
- `1` when there are diffs.
- `0` when there are no diffs
=>  Fix checking for diffs between structure.sql files 

src/api/app/controllers/webui/staging/excluded_requests_controller.rb, src/api/app/models/staging/workflow.rb, src/api/app/views/webui/staging/excluded_requests/_create_dialog.html.haml, src/api/app/views/webui/staging/excluded_requests/index.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/models/staging/workflow_spec.rb
Add method autocomplete to model Staging::Workflow
The method look exclusively for unassigned requests (backlog)
and filter by id containing specific digits
To see it working, either you change the value of `minLength` in the `autocomple.js` to 1 or you create more than 10 requests
=> Add autocomplete functionality to Staging::ExcludedRequests controller

src/api/app/views/webui/subscriptions/index.html.haml, src/api/app/views/webui/users/subscriptions/index.html.haml, src/api/spec/features/webui/notifications_spec.rb
Since the notification settings can be configured
for different channels now, the description needs to be
adjusted a bit.
=> Adjust description in notification configuration pages

src/api/db/data/20200430112548_remove_notifications_without_notifiable.rb, src/api/db/data_schema.rb
Previously, we excluded the events `Event::BuildFail` and
`Event::ServiceFail` for creating rss and web notifications.
We also regenerated the notifications for the users except for
those with event_type `Event::BuildFail` and `Event::ServiceFail`.
This commit, will remove the notifications without notfiable, fixing
at the same time the inconsistency in the DB and also the notifications
web counter.
Fix #9443
=> Remove notifications without notifiable

src/api/lib/tasks/dev.rake
Without this, the rake task fails.
Follow-up to #9270
=> Use correct fixture file for test_package

src/api/lib/tasks/dev.rake
- Fixes the following:
* When the admin home project does not exist, calling the
'create_and_assign_project' with 'admin.home_project' fails
since it is nil.
* The 'create_and_assign_project' returned the relationship,
not the project
=> Fix notification creation rake task for development

src/api/app/views/webui/project/responsive_ux/_subprojects_actions.html.haml, src/api/app/views/webui/project/subprojects.html.haml
The subproject creation link should be part of the actions
menu, which contains actions related to the current view.
For now, only shown in the beta program.
=> Add subproject creation link to actions menu

src/api/app/views/webui/attribute/index.html.haml, src/api/app/views/webui/attribute/responsive_ux/_index_actions.html.haml, src/api/spec/features/webui/attributes_spec.rb, src/api/spec/features/webui/projects_spec.rb, src/api/spec/support/features/features_attribute.rb
Under beta program, the general actions related to attribute are
moved to the Actions menu.
=> Move attribute actions to Actions menu

src/api/app/queries/notifications_finder.rb, src/api/db/data/20200421121610_backfill_notified_projects.rb, src/api/lib/tasks/rollout.rake
NOT conditions will no longer behave as NOR in Rails 6.1.
Instead of using where.not with multiple attributes, they are replaced
by many chained where.not (one per attribute).
Closes #9444.
=> Ensure NOT conditions act as NOR

src/api/app/controllers/configurations_controller.rb, src/api/app/controllers/issue_trackers_controller.rb, src/api/app/controllers/webui/download_on_demand_controller.rb, src/api/app/controllers/webui/kiwi/images_controller.rb, src/api/app/controllers/webui/repositories_controller.rb, src/api/app/jobs/send_event_emails_job.rb, src/api/app/models/configuration.rb, src/api/app/models/user.rb, src/api/db/data/20170831143534_convert_notifications_event_payload_to_json.rb, src/api/db/data/20180214132015_project_log_entry_user_name.rb, src/api/spec/controllers/status/reports_controller_spec.rb, src/api/spec/controllers/webui/request_controller_spec.rb, src/api/spec/controllers/webui/session_controller_spec.rb, src/api/spec/controllers/webui/webui_controller_spec.rb, src/api/spec/db/data/regenerate_notifications_spec.rb, src/api/spec/decorators/staging/project_decorator_spec.rb, src/api/spec/factories/bs_requests.rb, src/api/spec/features/webui/requests_spec.rb, src/api/spec/jobs/bs_request_action_webui_infos_job_spec.rb, src/api/spec/lib/statistics_calculations_spec.rb, src/api/spec/models/download_repository_spec.rb, src/api/spec/models/owner_search_spec.rb, src/api/spec/models/user_spec.rb
Method update_attributes is deprecated and will be removed from Rails 6.1.
Closes #9441
=> Replace deprecated update_attribute by update 

src/backend/BSSched/PublishRepo.pm, src/backend/bs_repserver, src/backend/bs_worker
drop the suffix as the archive is no longer compressed but compression
is handled by ccache itself
=> [backend] ccache archive no longer has .gz suffix

src/api/app/views/webui/attribute/index.html.haml
Remove attribute modal wasn't available for beta users.
=> Fix remove attribute

src/api/app/views/webui/shared/_buildresult_box.html.haml
When we are in a request for package deletion, it makes no sense to
build the package which no longer exists.
Using 'defined?' to ckeck if the project or package exist is not a good
idea because it always returns truthy (returns "local-variable") even if they are nil.
Therefore, 'defined?' has been replaced by '||='.
Even if it is not going to display build results, just the text "No build results available" I decided to give it the same aspect: a card with the `Build Results` tab inside.
Fixes #9514
=> Hide build results for delete requests

src/api/app/views/webui/main/_status_message.html.haml, src/api/app/views/webui/main/_status_messages.html.haml, src/api/app/views/webui/main/index.html.haml
It's normally a bad idea to loop through objects and call inside the loop the render. The Rails way to do it is to pass the collection to the `render` method.
=> Render collection of status_messages instead of render with loop

src/api/app/views/layouts/webui/webui.html.haml
There is no need to retrieve the RSS token for a non logged user. It isn't defined. This prevents querying the database on each page request for an anonymous user.
This was found in the logs of the development environment:
```
Token::Rss Load (1.0ms)  SELECT `tokens`.* FROM `tokens` WHERE `tokens`.`type` = 'Token::Rss' AND `tokens`.`user_id` = 1 LIMIT 1
```
=> Don't query for the rss feed for a non logged user

src/api/app/views/webui/package/responsive_ux/_show_actions.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_branch_package.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_bugzilla_owner.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_cloud_upload.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_delete_package.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_edit_description.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_request_deletion.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_request_devel_project_change.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_request_role_addition.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_submit_package.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_trigger_services.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_view_kiwi.html.haml, src/api/app/views/webui/package/show.html.haml
The bottom actions of the page package#show are moved to the responsive Actions menu.
Only available in the beta program.
=> Move action links to Actions menu for package#show

src/api/app/helpers/authentication_protocol_helper.rb
Dunno why it was extended with ?" it seems not to be needed with Microfocus
site, but was not harmful there. It breaks with our new site however.
=> [webui] fix create account link

src/backend/bs_srcserver
this option is forwarded to repserver which does the main job
=> [backend] add withccache option to getbinarylist call

src/api/app/views/webui/users/subscriptions/index.html.haml, src/api/spec/features/beta/webui/notifications_spec.rb, src/api/spec/features/webui/notifications_spec.rb
Updating subscription group wasn't working because we were pointing
to index instead of update.
Fix #9556
=> Disable notifications for group

src/api/app/controllers/source_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/models/bs_request_permission_check.rb, src/api/app/models/user.rb, src/api/app/policies/package_policy.rb, src/api/app/policies/project_policy.rb, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/spec/features/webui/packages_spec.rb, src/api/spec/policies/package_policy_spec.rb
Refactoring `can_create_package_in?` out of existence.
Following up on #9551.
=> Authorize package creation with a Pundit policy

src/api/app/helpers/webui/webui_helper.rb, src/api/spec/helpers/webui/webui_helper_spec.rb
This is a remnant of the Bento UI.
I found this while transferring the `Request Role Addition` modal to its own page.
=> Remove sprited_text helper method

src/backend/BSRepServer/Checker.pm, src/backend/BSSched/BuildJob.pm, src/backend/bs_repserver
This is a much saner approach than calling Build::readdeps and fixing up
the dependencies of the packages.
=> [backend] maintain the history of the last failed jobs

dist/t/spec/features/0040_package_spec.rb
The smoketests were failing in openQA due to changes
in our webui.
=> Adjust smoketests to the latest webui changes

src/api/.rubocop_todo.yml, src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/package/_basic_info.html.haml, src/api/app/views/webui/package/_bottom_actions.html.haml, src/api/app/views/webui/package/_edit.html.haml, src/api/app/views/webui/package/edit.js.erb, src/api/app/views/webui/package/responsive_ux/_show_actions.html.haml, src/api/app/views/webui/package/responsive_ux/actions/_edit_package.html.haml, src/api/app/views/webui/package/responsive_ux/show_actions/_edit_description.html.haml, src/api/app/views/webui/package/show.html.haml, src/api/app/views/webui/package/show.js.erb, src/api/app/views/webui/package/update.js.haml, src/api/config/routes/webui_routes.rb, src/api/spec/browser_helper.rb, src/api/spec/controllers/webui/package_controller_spec.rb, src/api/spec/features/beta/webui/packages_spec.rb, src/api/spec/support/wait_for_ajax.rb
This PR changes the existing modal to change the description and title
of the package to an in-place editing feature, like the one found in
Project.
**Before**
**After**
=> Implement the in-place package editing

src/api/app/assets/stylesheets/webui/responsive_ux/_layout.scss
After introducing Bootstrap 4.5.0, the breadcrumb icons weren't aligned
anymore.
=> Fix beta breadcrumb

src/api/config/options.yml.example
`:simulate` option was removed from the codebase years ago. It should have been removed then.
=> Remove :simulate as a value for proxy_auth_mode

.circleci/config.yml, src/api/spec/features/beta/webui/attributes_spec.rb, src/api/spec/features/beta/webui/groups_spec.rb, src/api/spec/features/beta/webui/login_spec.rb, src/api/spec/features/beta/webui/packages_spec.rb, src/api/spec/features/beta/webui/users/admin_configuration_spec.rb, src/api/spec/features/beta/webui/users/user_home_page_spec.rb, src/api/spec/spec_helper.rb, src/api/spec/support/capybara.rb, src/api/spec/support/features/features_beta.rb, src/api/spec/support/shared_examples/features/beta/user_tab.rb
We register a new driver called `:mobile`, where we emulate a mobile viewport. We also renamed the default driver to `:desktop`.
To run the tests for mobile, set the environment variable. For example:
```
CAPYBARA_DRIVER=mobile rspec spec/features/beta/webui/example_spec.rb
```
Without specifying the environment variable, tests should run within the desktop driver, as always.
In CircleCI we run the feature beta tests for desktop and mobile in the last container for the `rspec` CircleCI job.
=> Introduce beta feature tests for mobile

ReleaseNotes-2.11, src/backend/bs_publish
These files are just intermediate files for the .report files.
The .report files get not published either yet, but we should
not confuse users with internal build artefacts.
Better creating something useful in future if needed.
=> [backend] do not publish .packages files anymore

src/api/spec/features/beta/webui/image_templates_spec.rb
We skip a `scenario` that is flickering only on mobile.
=> Skip flickering test on mobile

src/backend/BSSched/BuildJob.pm, src/backend/BSXML.pm, src/backend/bs_worker
Maintenance projects have linked packages. These packages could shared
their ccache archive for initial builds allowing faster rebuilds.
releasename is added as param to job file allowing worker to know that
it should use ccache archive of the (release)named packages part of the
projects mentioned in its own repository paths. Here the first hit
wins.
=> Download 1st ccache archive for linked packages in maintenance prjs

src/api/app/controllers/source_controller.rb, src/api/app/models/package.rb, src/api/app/services/package_service/file_verifier.rb, src/api/app/services/package_service/link_verifier.rb, src/api/app/services/package_service/schema_verifier.rb, src/api/spec/services/package_service/file_verifier_spec.rb, src/api/spec/services/package_service/schema_verifier_spec.rb
We split this method in a set of services:
- FileVerifier
- LinkVerifier
- SchemaVerifier
Beside it there were some optimizations proposed by @marcus-h in the method `Package.verify_file` which was implemented too.
How to test it manually:
visit the review app and upload a file via browser
or via cli:
```osc copypac openSUSE:Factory hello -t dosc home:Admin```
and
```osc -A dosc api -X PUT -d "<pattern xmlns="http://novell.com/package/metadata/suse/pattern"><name>OBS</name></pattern>" /source/home:Admin/_pattern/obs-test```
where `dosc` is equal the review app address
=> Extract method Package.verify_file! to a set of Services

src/backend/BSSQLite.pm, src/backend/BSSrcServer/SQLite.pm
This makes it possible to reuse the sqlite code outside of the
source server.
=> Split sqlite interfacing from BSSrcServer/SQLite.pm into BSSQLite.pm

dist/t/spec/features/0030_project_spec.rb, src/api/spec/features/beta/webui/groups_spec.rb, src/api/spec/features/beta/webui/maintenance_workflow_spec.rb, src/api/spec/features/beta/webui/notifications_spec.rb, src/api/spec/features/beta/webui/projects_spec.rb, src/api/spec/features/beta/webui/requests_spec.rb, src/api/spec/features/beta/webui/search_spec.rb, src/api/spec/features/beta/webui/users/user_admin_edit_spec.rb, src/api/spec/features/webui/groups_spec.rb, src/api/spec/features/webui/maintenance_workflow_spec.rb, src/api/spec/features/webui/notifications_spec.rb, src/api/spec/features/webui/projects_spec.rb, src/api/spec/features/webui/requests_spec.rb, src/api/spec/features/webui/search_spec.rb, src/api/spec/features/webui/users/user_admin_edit_spec.rb, src/api/spec/support/capybara.rb
This is especially useful for Bootstrap custom controls, since Capybara cannot check/click them since they aren't visible.
=> Try to click the associated label of a non-visible checkbox/radio button

src/api/app/views/webui/requests/role_additions/new.html.haml
This should have been in #9579. This was still working since both routes are based on the same controller, only the route parameters vary.
We have feature specs covering this, so there were no regression.
=> Use correct form path for request/role_additions#new

dist/t/spec/support/capybara.rb, src/api/test/test_helper.rb
This should have been part of #9600. The minitest suite was already passing, but now it's just like the others.
=> Use automatic_label_click for Capybara inside openQA/minitest suite

dist/obsworker
- configure z/VM to use IUCV for console messages
- update mkinitrd call
- make SWAP device for z/VM configurable
- use xz to update initrd
- remove PAV aliases from initrd
=> Update z/VM setup to work with current mkinitrd

src/backend/BSRepServer/Containertar.pm
Instead, use the uploaddir in our partition.
=> [backend] do not reconstruct containers in the root filesystem

src/backend/BSFileDB.pm, src/backend/bs_repserver
This patch allows fdb_getall_reverse to return undecoded line to filter.
This raw line can be filtered out earlier without the need of decoding
over the layout.
This is useful for large and long maintained projects. Projects
(Factory, Devel..)  have a long build history, decoding every
line in the jobhistory file only to be filtered out based on filter
conditions (package type, result code, buildtimes) is expensive. This
patch facilitates skipping those costs reach the result faster.
Tested on IBS/SUSE:FACTORY:HEAD/standard/i586/MozillaThunderbird
without patch:
100 results: 6 sec
1000 results: 53 sec
with patch:
100 results: 1 sec
1000 results: 13 sec
=> [backend] Speedup jobhistory route by 4-6x

src/backend/bs_srcserver
By passing the "rev=repository" query parameter to the "copy"
route, the source files of the origin package are just made available
in the target package (for instance, for later processing). No commit
to the target package is made during this operation (see the addrev
with "rev=repository" semantics).
For a potential use case, see [1].
[1] https://github.com/openSUSE/open-build-service/issues/9615
=> [backend] Support a source copy without creating a commit

docs/api/api/api.txt, src/api/app/controllers/request_controller.rb, src/api/app/models/bs_request.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/bs_request_action_maintenance_incident.rb, src/api/app/models/project.rb, src/api/app/queries/projects_with_delegate_request_target_finder.rb, src/api/db/attribute_descriptions.rb, src/api/db/data/20200627135426_request_delegate_attribute.rb, src/api/db/seeds.rb, src/api/spec/factories/attribs.rb, src/api/spec/queries/projects_with_delegate_request_target_finder_spec.rb, src/api/spec/support/database_cleaner.rb, src/api/test/fixtures/attrib_types.yml, src/api/test/fixtures/linked_projects.yml, src/api/test/fixtures/projects.yml, src/api/test/functional/attributes_test.rb, src/api/test/unit/bs_request_test.rb
[api] support request delegation to package origin project.
Adds an option to let the server delegate the request for
a target project to the project where the packages is actual
living.
This works when source has no package link, eg from submitting
from a base distro project to another one.
This is needed for Jump submissions in first place (jsc#OBS-59)
=> Request delegation

src/api/config/environments/production.rb
They have no value in production, the admin can't do anything
about them.
=> Silence deprecation warnings in production

src/api/app/models/user.rb, src/api/db/data/20200528135241_dump_announcements_into_status_messages.rb, src/api/db/data_schema.rb, src/api/spec/db/data/dump_announcements_into_status_messages_spec.rb
As announcement functionality has been merged to status message, we also dump the existing data from the old to the new table.
This PR is part of a series, the previous ones were: #9590 and #9613
=> Dump announcement into status message

src/api/db/data/20200528135241_dump_announcements_into_status_messages.rb
The data migration to dump announcements into status messages has been
modified to make it work even after the Announcement model is removed
(something that is planned for the near future).
Inside the data migration file, we define "fake" models to use the
tables involved. The tables will be removed, but this data migrations is
going to be executed first.
=> Modify data migration for announcements

src/api/app/controllers/source_controller.rb, src/api/test/functional/source_controller_test.rb
This is just the rework of #9554
As of now, if a file is PUTed to a _pattern package, the file is
only verified if the _pattern package was non-existent. Instead, the
the file should be always verified (regardless whether the _pattern
package was created or already existed).
Since @pack is not set in check_permissions_for_file in case of a
_pattern package (which is perfectly fine), it is set up in
update_file (the code also takes a potential race into account).
Hence, @pack is always defined when it is passed to
Package.verify_file!.
The new behavior is documented in a testcase.
Co-authored-by: Marcus Hüwe <suse-tux@gmx.de>
=> Always verify an uploaded file in case of a _pattern package

src/backend/bs_worker
=> [backend] use releasename for comparison to useccache when available

dist/obs-bundled-gems.spec
We need to update the rack version to make obs-bundled-gems works
=> Update rack version in obs-bundled-gems.spec file

src/backend/bs_publish
- fix handling of debug repositories
- use packtrack cache to speed up generation of the source data
=> [backend] clean up publisher side of source publishing feature

src/api/lib/tasks/dev.rake
It's easy to understand what options do.
The option `-D` is used to display cop names in offense message, but [this is already the default](https://rubocop.readthedocs.io/en/latest/basic_usage/#command-line-flags). It's redundant, so we removed it.
=> Use long options in rake tasks dev:lint:rubocop:{rails,root}

src/backend/bs_publish
basically reverting 444280b0b8647df36010d81d15b0ab2146eae750
=> [backend] bs_publish bring back packages files for now

src/api/app/views/layouts/webui/webui.html.haml
The break-all style just breaks the lines between letters. This
makes the annoucements unpleasent to read.
Leaving the default and breaking the lines between the words
is the better option.
**Before**
**After**
=> Remove word-break break-all from flash messages and announcement

src/backend/BSSched/BuildJob.pm, src/backend/bs_worker
Commit 1:
use releasename too to decide ccache as buildrequirement
this is in continuation to d5352ff
Commit 2:
store the first _ccache.tar for unchanged results
it is better to store ccache archive even in case of unchanged builds if
it is the first archive created.
this is a corner case - ccache is enabled, but the built result is same as
last successful result when ccache was not enabled.
=> Ccache relasename and first archive

src/api/Gemfile, src/api/Gemfile.lock
They aren't used anymore after the merge of #9688.
=> Remove gems chunky_png and sprite-factory

docs/api/api/api.txt, docs/api/api/directory.xsd, docs/api/api/directory_filelist.xml, src/api/test/functional/backend_test.rb
- The directory element can contain the `vrev` attribute
- The example for the `/source/<project>/<package>` route is a `_meta` and not the list of files as would be expected.
=> Fix the API docs involving the directory schema

.circleci/config.yml
On 2.9, our continuous integration is Travis CI.
While working on #9629, I've noticed that CircleCI is trying to start even though we don't have a config for it in the branch. This is somewhat confusing, so we instead disable CircleCI since we're not using it anyway for any branch targeting `2.9`.
=> Disable CircleCI completely on the 2.9 branch

src/backend/bs_worker
The build package nowadays also creates .packages files for
docker builds, so it makes to also create a corresponding
.report file.
=> [backend] also create .report files for docker builds

src/api/app/jobs/status_history_rescaler_job.rb
Get rid of the raw SQL call "DISTINCT \`key\`".
Closes #9445
=> Prevent SQL injection

src/api/app/controllers/webui/request_controller.rb
To be consistent with changes introduced in #9690
=> Raise AbstractMethodCalled error in Webui::RequestController#bs_request_params

.rubocop.yml, src/api/.rubocop.yml
Since we enable pending cops by default (commit 1484283), this isn't needed anymore.
=> Remove unneeded enabling of RuboCop pending cops

src/api/Gemfile, src/api/Gemfile.lock
We don't use it.
This is how it's used and we don't do that:
https://github.com/rgrove/cssmin/blob/60e7050744a0fc18ecd79ad49c64f250ad28e0a7/lib/cssmin.rb#L43-L46
=> Remove gem cssmin

src/api/config/application.rb
One line was commented with a description of what it does and the other was not commented, but it didn't have any description.
=> Remove duplication of config.active_record.schema_format = :sql

dist/obs-bundled-gems.spec, src/api/Gemfile, src/api/Gemfile.lock
We don't use it.
Going through its documentation makes it pretty clear that we use none of its features: https://kugaevsky.github.io/mousetrap-rails/
=> Remove gem mousetrap-rails

dist/t/spec/features/0040_package_spec.rb, src/api/app/views/webui/package/_files_view.html.haml, src/api/spec/features/beta/webui/packages_spec.rb, src/api/spec/features/webui/packages_spec.rb
For consistency we renamed `Add file` to `Add File`.
We also adapted the features tests and openQA tests.
=> Align `Add file` link text and adapt tests

src/api/Gemfile, src/api/Gemfile.lock
We don't have any CoffeeScript files.
There are some CoffeeScript-related files for CodeMirror, but it's a mode for editing CoffeeScript which is completely unrelated.
=> Remove gem coffee-rails

src/api/Gemfile, src/api/Gemfile.lock, src/api/lib/obsapi/markdown_renderer.rb
This allows us to remove the gem "sanitize" since it's now unused.
We don't remove anymore the content of tags which are removed, so the inner text stays. It could be done, but it would involve using `Loofah` which is what `rails-html-sanitizer` builds upon. I prefer to keep it simple and keeping the inner text is fine.
I've used the same tags as `Sanitize::Config::RESTRICTED[:elements] + ['pre']`.
=> Replace sanitize with rails-html-sanitizer

src/api/app/controllers/webui/comments_controller.rb
- Improve ruby dialect
- Remove  `respond_to`. We just respond to html.
=> Refactor Webui::CommentsController

src/api/app/mixins/can_render_model.rb
Closes #9617 and #9438
Message:
"DEPRECATION WARNING: ActionView::Base instances must implement
compiled_method_container or use the class method
with_empty_template_cache for constructing an ActionView::Base instance
that has an empty cache. (called from render_xml at
/srv/www/obs/api/app/mixins/can_render_model.rb:8)"
=> Address deprecation warning on render_xml

src/api/app/models/architecture.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/cloud/ec2/configuration.rb, src/api/app/models/download_repository.rb, src/api/app/models/flag.rb, src/api/app/models/group.rb, src/api/app/models/issue_tracker.rb, src/api/app/models/kiwi/profile.rb, src/api/app/models/kiwi/repository.rb, src/api/app/models/project.rb, src/api/app/models/repository.rb, src/api/app/models/static_permission.rb, src/api/app/models/status/check.rb, src/api/app/models/user.rb, src/api/spec/models/architecture_spec.rb, src/api/spec/models/download_repository_spec.rb
Uniqueness validation has been `case_sensitive: true` by default. From Rails 6.1 on, the default will be false so we have to specify the opposite to avoid deprecation warnings and malfunction in the future.
The concept can be a bit confusing, but `case_sensitive: true` means: the validation is going to check if an object with the same value and the **same capitalization** already exists.
Example:
If we have this validation in the Project's model
```validates :name, uniqueness: { case_sensitive: true }```
This means a project with "lorem" name and another project with "LOREM" name can be both created. Because the validation is taking capitalization into account.
Some has been considered case insensitive for the following reasons.
- it makes sense according to the values and usage,
- they …
=> Specify case_sensitive on uniqueness validations

src/api/app/models/user.rb, src/api/app/queries/projects_with_image_templates_finder.rb
Having the following warning:
"[...] Class level methods will no longer inherit scoping
from `<scope name>` in Rails 6.1.
To continue using the scoped relation, pass it into the block directly.
To instead access the full set of models, as Rails 6.1 will, use
`<model>.unscoped`, or `<model>.default_scoped` if a model has default scopes.
[...]"
It is addressed by adding .unscoped or .default_scoped when needed.
Closes #9442
This PR addresses two of the three deprecation warnings included in the issue. As soon as this gets approved, I can apply the same fix to other similar existing scopes.
=> Address deprecation warning regarding scoping

src/backend/BSSrcServer/Projlink.pm
We ignored sections that contained no package entry before.
=> [backend] Projlink: do not ignore empty frozenlink sections

.circleci/config.yml, dist/Makefile, dist/run_shellcheck.sh, dist/t/0000-check_users_and_group.ts
We want to benefit from having a linter that checks our script files (bash or sh).
Initially it is only run on only one file. The second commit of this pull request is an example of including a file into the list of files to be checked by the linter.
=> Add ShellCheck scripts linter

src/api/app/controllers/webui/status_messages_controller.rb, src/api/app/models/status_message.rb, src/api/spec/controllers/webui/status_messages_controller_spec.rb, src/api/spec/models/status_message_spec.rb
Now an exception is raised when acknowledging an already acknowledged status message.
This PR makes OBS ignore a re-acknowledging. OBS will show an error to the user only when the failure is something else.
Fixes #9714
=> Do not fail when acknowledging twice

src/api/app/controllers/webui/main_controller.rb
Instead of `map.uniq` in the array level, use DISTINCT on name to reduce the architectures in the database level.
=> Use distinct on activerecord instead of uniq on Array

src/api/app/models/project.rb, src/api/app/models/user.rb, src/api/app/queries/projects_with_delegate_request_target_finder.rb, src/api/app/queries/projects_with_very_important_attribute_finder.rb
Other scope definitions are affected by the deprecation warnings related to scoping.
Message:
```
DEPRECATION WARNING: Class level methods will no longer inherit scoping from 
`for_project` in Rails 6.1. To continue using the scoped relation, 
pass it into the block directly. 
To instead access the full set of models, as Rails 6.1 will, use `BsRequest.unscoped`, 
or `BsRequest.default_scoped` if a model has default scopes. 
(called from initialize at /srv/www/obs/api/app/models/bs_request/find_for/base.rb:4)
```
Follow-up of #9742
Co-authored-by:  Quang Tran <quang.tran@suse.com>
PS: this skips BsRequest and Package scopes, there is an specific issue for them: #9748
=> Prevent deprecation warnings on scopes

src/api/app/controllers/webui/package_controller.rb, src/api/app/models/package.rb
Looks like when we removed the `foreign_key: :package_id` from the `has_one :backend_package`
here (https://github.com/openSUSE/open-build-service/pull/9701), we hit an Rails/ActiveRecord bug (https://github.com/rails/rails/issues/38709).
This PR is a workaround.
As an alternative we can revert https://github.com/openSUSE/open-build-service/pull/9701, or reload the `linked_package`
Fixes #9763
=> Keep the redundant `foreign_key` option in the association

src/api/app/models/binary_release.rb, src/api/app/models/bs_request.rb, src/api/app/models/group.rb, src/api/app/models/package.rb, src/api/app/models/project/key_info.rb, src/api/app/models/project_status/calculator.rb, src/api/app/models/staging/workflow.rb, src/api/app/models/user.rb, src/api/app/services/monitor_controller_service/status_history_fetcher.rb, src/api/app/views/webui/users/tasks/index.html.haml, src/api/config/application.rb, src/api/spec/models/bs_request_spec.rb, src/api/spec/models/review_spec.rb
Before cache versioning, `cache_key` contained the key and the version.
Introducing cache versioning makes `cache_key` to contain only the key. In order to have the same content as before, we have to use `cache_key_with_version`.
This is a follow up of #9392.
Have a look at this [blog entry](https://blog.bigbinary.com/2019/08/06/rails-adds-support-for-recyclable-cache-keys.html) as reference.
=> Introduce cache versioning

src/api/app/jobs/cleanup_notifications.rb
Instead of keeping at most 10 notifications for groups and active users, we keep notifications if they were created up to 3 months ago.
There are no specs for this job, but it's one line and that one line is covered in the specs for the Notification model.
=> Clean up notifications with Notification.cleanup

src/backend/BSSched/BuildJob/Aggregate.pm, src/backend/BSSched/BuildJob/Channel.pm, src/backend/BSSched/BuildJob/Docker.pm, src/backend/BSSched/BuildJob/KiwiImage.pm, src/backend/BSSched/BuildJob/KiwiProduct.pm, src/backend/BSSched/BuildJob/Package.pm, src/backend/BSSched/BuildJob/Patchinfo.pm, src/backend/BSSched/BuildJob/PreInstallImage.pm, src/backend/bs_notifyforward, src/backend/bs_redis
It does not make sense to show hundreds of packages to the user.
This just leads to the packstatus and the redis updates being way
too big.
=> [backend] trim list of blocking packages to at most 10 entries

src/api/db/data/20200527135426_request_delegate_attribute.rb
Do not crash if the attribute already exists. Can happen when seeds are loaded
and then people apply migrations.
Fixes #9762
=> Fix DelegateRequestTarget migration

src/api/config/clock.rb
Following the discussion we had in #9774 and offline, we agreed that this job isn't needed since there aren't many notifications.
=> Stop enqueueing CleanupNotifications job

src/api/app/lib/backend/api/search.rb, src/api/spec/cassettes/Backend_Api_Search/_projects/with_projects/1_1_1_1.yml, src/api/spec/cassettes/Backend_Api_Search/_projects/with_unexistent_projects/1_1_3_1.yml, src/api/spec/lib/backend/api/search_spec.rb
We need a better way to search for a set of projects on backend. Therefore the `Backend::Api::Search` now supports it. passing an array of names to the method `.projects` it will create a xpath and search for it on backend.
=> Add method .projects for Backend::Api::Search

docker-files/home/.pryrc, src/api/Gemfile, src/api/Gemfile.lock
Use the way more sophisticated pry, instead of irb, as the rails console. Brings features like `show-model Project`
```ruby
[6] pry(main)> show-model Project
Project
id: integer
name: string
title: string
description: text
created_at: datetime
updated_at: datetime
remoteurl: string
remoteproject: string
develproject_id: integer
delta: boolean
kind: string
url: string
required_checks: string
staging_workflow_id: integer
belongs_to :develproject (class_name :Project)
belongs_to :staging_workflow (class_name :Staging::Workflow)
has_many :attribs
has_many :comments
has_many :develprojects (class_name :Project, foreign_key :develproject_id)
has_many :flags
has_many :incident_updateinfo_counter_values
has_many :issues (through :packages)
has_many :linked_by (class_name :LinkedProject, …
```
=> Add pry and awesome print to the rails console

docker-compose.yml
That way you do not *have* to set CONTAINER_USERID
=> Set a default UID for the frontend user

src/api/app/models/notification.rb, src/api/db/migrate/20200618152542_set_default_value_for_type_in_notifications.rb, src/api/db/structure.sql
`attribute :type, default: ''` won't make it when we need to ignore the column before removing it. The column would then be empty and the database doesn't accept this.
=> Set column default to an empty string for notifications.type

.circleci/config.yml
Only run the spider test of everything else is green. Will make this test run
less frequent and the whole cycle faster a bit.
=> Run spider test only after functional tests

.circleci/config.yml, src/api/Gemfile
brakeman is a linter, we should run it where we run all the other linters too.
Firing up a container is too expensive just for this.
=> Run brakeman in checkout_code CI step

src/api/app/jobs/consistency_check_job.rb, src/api/app/mailers/admin_mailer.rb, src/api/app/mailers/consistency_mailer.rb, src/api/app/views/consistency_mailer/errors.text.erb, src/api/config/environments/development.rb
In this PR we did three things:
- Instead of using `mailercatcher` use the `:test` mailer delivery method in development
- Create a custom Mailer and use ERB template to generate the mail message
- Adapt `ConsistencyCheckJob` to use the new mailer
=> Adapt ConsistencyCheckJob to use its own mailer

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/helpers/webui/notification_helper.rb, src/api/app/views/webui/users/notifications/index.html.haml
Currently we only show the amount of notifications,
for the project filter links.
In order to enable the user to get a quick overview
about the amount of pending notifications,
we now show a badge with the amount also for notifications
related to review, comments, request and overall unread.
=> Add counter to notification filter links

contrib/Procfile.ha, src/api/Procfile
Mailcatcher is not used anymore in the dev environment
Last usage got removed by https://github.com/openSUSE/open-build-service/pull/9807
=> Drop mailcatcher from Procfile

.circleci/config.yml, dist/README.UPDATERS, dist/obs-api-testsuite-rspec.spec, dist/setup-appliance.sh, src/api/lib/tasks/databases.rake, src/api/lib/tasks/dev.rake, src/api/script/api_minitest.sh
`redefine_task` was used to redefine the `db:setup` task. We prefer to be explicit about having to run `db:structure:load:with_data db:seed` and to avoid monkey patching Rake::Task.
While looking into #9779 and talking with @hennevogel and @saraycp about it, we found this nice :monkey: patch.
Sadly, we cannot use `db:structure:load:with_data`. For some obscure reasons, specs fail due to missing seeds, even if seeds are added after calling `db:structure:load:with_data`. We can still remove the monkey patch.
~~To take data migrations into account when setting up a new database, we need to run `db:structure:load:with_data`, not `db:structure:load`. This will prevent issues like #9779 if somehow data migrations are ran against a new database. It shouldn't happen, but if it does, it's simply …
=> Remove Rake::Task monkey patch

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/views/webui/users/notifications/_notifications_filter.html.haml, src/api/app/views/webui/users/notifications/_notifications_list.html.haml, src/api/app/views/webui/users/notifications/_update.js.erb, src/api/app/views/webui/users/notifications/index.html.haml, src/api/spec/controllers/webui/users/notifications_controller_spec.rb
Mark notifications read or unread asynchronously.
Now, when you are reviewing your notifications and you tick one as read, the whole page reloads and you lose the point in the page you were working on. This change allows you to keep working in place.
=> Mark notifications read or unread asynchronously

src/api/Gemfile, src/api/Gemfile.lock
We don't use this gem anymore. If we did, searching for `EscapeUtils` or `escape_utils` would return at least one result. This is the gem's documented usage: https://github.com/brianmario/escape_utils#usage
=> Remove escape_utils gem

src/api/Gemfile, src/api/Gemfile.lock
Following the merge of #9816, this gem isn't in use anymore.
=> Remove colorize gem

src/backend/bs_srcserver
This can be used for doing fast existance checks.
=> [backend] add a project filter to the /source route

src/api/app/models/notification.rb, src/api/db/migrate/20200623084234_remove_type_from_notifications.rb, src/api/db/structure.sql, src/api/spec/factories/notification.rb
The column cannot be ignored since it's the reserved `type` column for Single Table Inheritance. See my [comment](https://github.com/openSUSE/open-build-service/pull/9801#issuecomment-647984689) for details.
**DO NOT MERGE**: This forces us to deploy and migrate during on maintenance window this upcoming Thursday.
=> Remove column type from notifications table

src/api/app/views/webui/users/notifications/_update.js.erb
Without this change, the flash message is only shown after reloading the page.
=> Show the flash message after marking a notification as read/unread

src/api/app/assets/stylesheets/webui/responsive_ux.scss, src/api/app/views/webui/users/notifications/index.html.haml
The PR is work in progress because the colors of the filter box need to be adjusted.
=> Make notifications filter sticky on mobile

src/api/app/models/attrib_namespace_modifiable_by.rb, src/api/spec/factories/attrib_namespace_modifiable_bies.rb, src/api/spec/policies/attrib_namespace_policy_spec.rb, src/api/test/policies/attrib_policy_test.rb
We want to move away from Minitest.
=> Migrate AttribNamespacePolicy tests from Minitest to RSpec

src/api/app/controllers/status_messages_controller.rb, src/api/app/controllers/webui/feeds_controller.rb, src/api/app/controllers/webui/main_controller.rb, src/api/app/controllers/webui/status_messages_controller.rb, src/api/app/models/status_message.rb, src/api/spec/controllers/status_messages_controller_spec.rb, src/api/spec/controllers/webui/status_messages_controller_spec.rb
We don't need this feature. We are going to remove the `deleted_at` column in an upcoming PR.
=> Remove soft deletion of StatusMessage

src/backend/BSSrcServer/Remote.pm, src/backend/bs_srcserver
=> Chunk binaryversion requests when querying a remote server

dist/t/Gemfile, dist/t/Gemfile.lock, dist/t/spec/features/0040_package_spec.rb, dist/t/spec/spec_helper.rb, dist/t/spec/support/capybara.rb
Smoke tests where fixed for Unstable in #9809. This does the same for branch 2.10.
The capybara gem had to be updated to support apparition.
=> Fix smoke tests switching to apparition capybara driver

src/backend/bs_publish
=> [backend] support single medium slepool setup

src/api/test/unit/attrib_test.rb
Test `should have an attrib_type` is checking if validations work. This
is tested upstream.
Tests `should show full name`, `should have no values` and `should have
one value` are already present in our RSpec test suite:
https://github.com/openSUSE/open-build-service/blob/8b4e070412c610de9084ff325dc563791ed96510/src/api/spec/models/attrib_spec.rb#L9-L11
https://github.com/openSUSE/open-build-service/blob/8b4e070412c610de9084ff325dc563791ed96510/src/api/spec/models/attrib_spec.rb#L156-L162
=> Remove unneeded tests for Attrib model

src/api/app/assets/stylesheets/webui/responsive_ux.scss
* Add shadow to the filter button to differntiate it better from the
notifications list below.
* Change the fixed height of the shown filter to a screen size
dependable height.
* Resize height in landscape mode.
**Screenshots**
Before and after screenshots of portrait mode
Before and after screenshots of landscape mode
=> Improve responsive UX of the notifiations page

src/backend/BSConfiguration.pm, src/backend/bs_publish, src/backend/bs_sourcepublish, src/backend/bs_srcserver
=> [backend] report source publisher in server status

src/backend/BSSched/BuildJob.pm, src/backend/bs_repserver
=> [backend] Fix handling of build time services with 'osc build'

src/api/test/functional/source_services_test.rb, src/backend/bs_srcserver
We must not drop _service file, but write these services back instead.
=> [backend] support buildtime services in mergeservice call
