openSUSE/open-build-service

- src/backend/bs_worker
Requires updated build that supports Docker.
Signed-off-by: Oleg Girko <ol@infoserver.lv>
> [backend] Add support for using Docker for virtualisation (master branch).

- src/backend/bs_worker
Requires updated build that supports Docker.
Signed-off-by: Oleg Girko <ol@infoserver.lv>
> [backend] Add support for using Docker for virtualisation (2.6 branch).

- docs/api/api/obs.rng
- src/api/test/fixtures/backend/source/buildtime_service_source/_service
- src/api/test/fixtures/backend/source/buildtime_service_source/pack.spec
- src/api/test/functional/source_services_test.rb
- src/backend/bs_repserver
- src/backend/bs_service
- src/backend/bs_srcserver
build script part should be merged first
> [backend] support buildtime source services

- src/api/app/mixins/statistics_calculations.rb
Trying to figure out the statistics at the moment and bumped into this. The change is mostly cosmetic. At least i didn't see a huge performance improvement, but on the other hand our database is quite small. Anyways, for me it seems a lot more pretty this way. :)
> Shaving off some extra from StatisticsCalculations::get_latest_updated

- src/api/config/options.yml.example
cleanup_after_days is maintained in /configuration.xml
> [api] auto_cleanup_after_days was never used

- src/api/app/views/webui/package/show.html.erb
Fixes: https://github.com/openSUSE/open-build-service/issues/801
> [webui] Add link to upstream homepage on package page

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/webui_project.rb
- src/api/app/views/webui/project/_edit_repository.html.erb
- src/api/app/views/webui/project/add_repository.html.erb
- src/api/config/routes.rb
- src/api/test/functional/webui/project_controller_test.rb
fixes: https://github.com/openSUSE/open-build-service/issues/923
> [webui] Repository path editing

- src/api/app/controllers/application_controller.rb
- src/api/test/unit/code_quality_test.rb
Fixes: https://github.com/openSUSE/open-build-service/issues/587
> [api] Replace use of removed method #each_full

- src/api/app/assets/javascripts/webui/bratwurst.js
- src/api/app/assets/stylesheets/webui/application/style.css.scss
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/bs_request_collection.rb
- src/api/app/models/user.rb
- src/api/app/views/shared/_requests.html.erb
- src/api/app/views/shared/_single_request.json.erb
- src/api/app/views/webui/project/_packages_table.html.erb
- src/api/app/views/webui/user/show.html.erb
Added a list with the last requests at user's home (upto 100, paginated if needed).
Fixes #928.
> [webui] Added a tab with the last requests at user's home

- src/api/app/controllers/webui/project_controller.rb
Fixes: https://github.com/openSUSE/open-build-service/issues/850
> [webui] Fix ignoring pending packages in status view

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/helpers/maintenance_helper.rb
- src/api/app/models/owner.rb
- src/api/app/models/project.rb
- src/api/app/models/user.rb
- src/api/app/views/webui/project/subprojects.html.haml
- src/api/test/functional/webui/package_branch_test.rb
> [webui] More Refactoring of the Project Controller

- src/api/app/controllers/webui/user_controller.rb
Fixing error found in production tracker system:
http://errbit-opensuse.herokuapp.com/apps/53219aa9153eb8000a000005/problems/55b6891c1925e3c25a00004e
> [webui] Fixing error in User Controller, at requests action.

- docs/dev/GUIDE.md
- docs/dev/controller_template_example.rb
- docs/dev/model_empty_template.rb
- docs/dev/model_template_example.rb
- src/api/app/policies/application_policy.rb
- src/api/lib/templates/active_record/model/model.rb
- src/api/lib/templates/rails/scaffold_controller/controller.rb
- src/api/test/unit/code_quality_test.rb
Let's have some place to put our rules in a style guide. I have created some templates for model & controller generators, so will be easy to have the structure for the code as we want to.
Please, take a look at the /docs/dev/GUIDE.md file and throw out your thoughts into the comments here.
Thanks
> [webui+api] Added style guide into docs dir for RoR

- src/api/config/initializers/01_monkeypatches.rb
This should die as soon as we update ruby again
> [api][webui] Monkeypatching AR to fix #992

- src/api/app/assets/javascripts/webui/application/project.js
- src/api/app/controllers/webui/attribute_controller.rb
- src/api/app/controllers/webui/patchinfo_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/mixins/webui/requires_project.rb
- src/api/app/views/layouts/webui/webui.html.erb
- src/api/app/views/webui/main/index.html.erb
- src/api/app/views/webui/project/list.html.erb
- src/api/config/routes.rb
- src/api/test/functional/webui/project_controller_test.rb
- src/api/test/functional/webui/project_create_test.rb
- src/api/test/functional/webui/spider_test.rb
First batch of commits from group refactoring with Moises and Henne
> [Group refactoring] Refactor webui project indexer

- docs/dev/controller_template_example.rb
- docs/dev/model_template_example.rb
- src/api/app/models/architecture.rb
- src/api/app/models/attrib.rb
- src/api/app/models/attrib_issue.rb
- src/api/app/models/attrib_namespace.rb
- src/api/app/models/attrib_type.rb
- src/api/app/models/attrib_value.rb
- src/api/app/models/backend_info.rb
- src/api/app/models/backend_package.rb
- src/api/app/models/binary_release.rb
- src/api/app/validators/attrib_allowed_values_validator.rb
- src/api/app/validators/attrib_issue_validator.rb
- src/api/app/validators/attrib_value_length_validator.rb
- src/api/lib/templates/active_record/model/model.rb
- src/api/lib/templates/rails/scaffold_controller/controller.rb
- src/api/test/functional/attributes_test.rb
- src/api/test/unit/binary_release.rb
Sort methods and other stuff inside some models. Not to much refactoring there.
> [webui] Adapt models to template

- src/api/app/controllers/webui/apidocs_controller.rb
- src/api/app/controllers/webui/package_controller.rb
It might even be that the backend is guarding against such attacks. But we don't know that in the frontend. So better be save than sorry.
> Hakiri file access

- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_action_accept_info.rb
- src/api/app/models/bs_request_action_add_role.rb
- src/api/app/models/bs_request_action_change_devel.rb
- src/api/app/models/bs_request_action_delete.rb
- src/api/app/models/bs_request_action_group.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/app/models/bs_request_action_maintenance_release.rb
- src/api/app/models/bs_request_action_set_bugowner.rb
- src/api/app/models/bs_request_action_submit.rb
Just moving stuff inside the models to fit the template
> [webui] Adapt models to template part 2

- src/api/app/models/bs_request.rb
- src/api/test/functional/request_controller_test.rb
- src/api/test/unit/code_quality_test.rb
> [api] allow to revert assigned reviews (FATE#319411)

- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/helpers/maintenance_helper.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/maintenance_incident.rb
- src/api/db/migrate/20150903084813_remove_request_from_maintenance_incident.rb
- src/api/db/structure.sql
* Use build_maintenance_incident factory instead of sending XML to API
* Moved helper code to model
* Some small refactorings
> [webui] Refactor new maintenance incident action

- src/api/test/functional/webui/patchinfo_create_test.rb
Some preparational steps to ease removing the FrontendCompat related code from webui/patchinfo_controller.rb
> Refactor patchinfo controller tests

- src/api/app/models/project.rb
Introduced by a merge conflict.
> [api] Fix infinite recursion for update_from_xml

- src/backend/bs_srcserver
> [backend] handle nonexistent rev in getprojectservices more gracefully

- src/api/app/assets/javascripts/webui/application/cm2/index.js
- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/project.rb
- src/api/app/models/user.rb
- src/api/app/policies/project_policy.rb
- src/api/test/unit/project_test.rb
- Removed ActiveXML call from save_meta action and using Project model
functions instead
- Moved functions from controller to model
- Handle permissions in policy
> [webui] Refactor project save_meta action

- src/api/app/controllers/webui/driver_update_controller.rb
- src/api/app/models/package.rb
- src/api/app/views/webui/driver_update/create.html.erb
- src/api/test/fixtures/repositories.yml
- src/api/test/functional/webui/driver_update_controller_test.rb
Moved the Service and BuildResult use from the DriverUpdate controller to Package model. No need to use FrontendCompat in the controller.
> [webui] Refactor DriverUpdate controller

- src/api/test/unit/package_test.rb
I separated this test from  #1133 to show that the test works with the old and new code!
> [api] Add a explicit test for the package default scope

- src/api/app/models/package.rb
Previously we selected all packages which are not included in a given range (forbidden projects) which caused performance issues. This commit goes now the other way around and removes the forbidden projects from all projects. This is a performance tweak which assumes that there are more allowed projects than forbidden ones.
Example query for package search by issue.name and issue_tracker.name.
New Query
```sql
SELECT DISTINCT `packages`.`id` FROM packages
LEFT JOIN package_issues ON packages.id = package_issues.package_id 
LEFT JOIN issues ON issues.id = package_issues.issue_id 
LEFT JOIN issue_trackers ON issues.issue_tracker_id = issue_trackers.id 
LEFT JOIN attribs ON attribs.package_id = packages.id 
LEFT JOIN attrib_issues ON attrib_issues.attrib_id = attribs.id 
LEFT JOIN issues AS …
```
> [api] Optimize default_scope for packages

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/tag_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/helpers/branch_package.rb
- src/api/app/helpers/maintenance_helper.rb
- src/api/app/jobs/project_create_auto_cleanup_requests.rb
- src/api/app/mixins/has_ratings.rb
- src/api/app/mixins/has_relationships.rb
- src/api/app/mixins/webui/manage_relationships.rb
- src/api/app/models/binary_release.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/app/models/owner.rb
- src/api/app/models/package.rb
- src/api/app/models/project.rb
- src/api/app/models/project_log_entry.rb
- src/api/config/initializers/wrap_parameters.rb
- src/api/test/activexml_matcher.rb
- src/api/test/unit/code_quality_test.rb
Fixed rubocop offenses for cop Lint/AssignmentInCondition.
> [ci][api][webui] Refactor rubocop offenses

- src/api/app/controllers/webui/project_controller.rb
> [webui] Add save_prjconf to set_project before filter

- src/backend/README
see:
https://github.com/openSUSE/open-build-service/blob/master/src/backend/BSConfig.pm.template#L78
> User and group name should be "obsrun" in README

- src/api/app/models/distribution.rb
Actually, the fact that we modify `self.attributes` in place worries me a bit too, but let's leave it for now. This PR doesn't change the behaviour of the app, it is pure refactoring aimed for better code readability.
> Simplify `Distribution#to_hash` a little

- src/api/test/functional/webui/project_controller_test.rb
Follow up on 1009b0a92eba8ca384a
> [ci] Tests for uniqueness of arch entries in the project repository view (issue#1140)

- src/api/app/controllers/webui/user_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/user.rb
- src/api/test/functional/source_controller_test.rb
- src/api/test/functional/webui/user_controller_test.rb
- src/api/test/unit/user_test.rb
The workaround for users without home project should get removed as soon
as issue#1090 get's fixed.
> [webui] Fix redirect after registering as new user

- src/api/Gemfile
- src/api/Gemfile.lock
$ TESTOPTS="--fail-fast" bundle exec rake test:api
> [ci] Make it possible to fail the test suite fast

- src/api/app/models/group.rb
[Enumerable#index_by](http://apidock.com/rails/Enumerable/index_by)
> Group#update_from_xml: replace a loop by a single method call

- src/api/test/unit/webui_helper_test.rb
This is a follow up on PR#1174
> [ci][webui] Add a test for format_projectname (PR#1174)

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/project.rb
- src/api/test/functional/webui/project_controller_test.rb
- src/api/test/unit/project_test.rb
> Remove package from inherited packages if project overrides it

- src/api/test/unit/user_test.rb
This got introduced by 3b6e7100a3e31b07da354128e8c7f7c122346d33
> [ci] Remove unused variable from test

- src/api/app/controllers/webui/user_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/test/functional/webui/user_controller_test.rb
* Additional tests
* Fix for require_login and require_admin before filter
> Some smaller things I stumbled over while debugging issue 1199

- src/api/app/controllers/person_controller.rb
- src/api/test/functional/person_controller_test.rb
This might be causing issue#1204
> Add tests for updating project watchlist via API and address issue 1204

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/helpers/webui/project_helper.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/views/webui/user/show.html.erb
Project.title can contain html / js tags which will be rendered.
Close #1218
> [webui] Fix possible XSS attack on project title

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/views/webui/project/list.html.erb
- src/api/app/views/webui/user/show.html.erb
- src/api/test/unit/webui/webui_helper_test.rb
Added simple helper test, my initial approach in testing it as a functional test doesn't work because of several reasons (eg #1231).
> Make escape_project_list more generic and add test for it!

- src/api/Gemfile
- src/api/Gemfile.lock
- src/api/test/test_helper.rb
> [ci] Use minitest-reporters for spec like test reporting

- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/controllers/webui/patchinfo_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_action_delete.rb
- src/api/app/models/package.rb
- src/api/app/models/project.rb
- src/api/app/policies/package_policy.rb
- src/api/test/functional/request_controller_test.rb
- src/api/test/functional/webui/patchinfo_controller_test.rb
- src/api/test/functional/webui/user_controller_test.rb
- src/api/test/test_helper.rb
- src/api/test/unit/attribute_test.rb
- src/api/test/unit/package_test.rb
- src/api/test/unit/project_test.rb
- src/api/test/unit/watched_project_test.rb
Same as #1161 just without writing commit_opts into the database...
> [webui][api] Refactor destroying Project/Package objects

- src/api/test/functional/request_controller_test.rb
> [webui] Reintroduce test for not_existing_target

- src/api/app/controllers/webui/monitor_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/controllers/webui/patchinfo_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/patchinfo.rb
- src/api/test/unit/code_quality_test.rb
Instead of authenticating on the backend for every method of every controller we are only doing it when needed.
> Refactoring webui authentification

- src/api/app/controllers/webui/request_controller.rb
- src/api/app/controllers/webui/search_controller.rb
some minor  bits during reviewing Package/Project find method usages in webui
> Webui review

- docs/api/api/api.txt
- src/api/app/controllers/source_controller.rb
- src/api/app/models/project.rb
- src/api/test/functional/source_controller_test.rb
fixes also a 500 crash regression on unlocking a not locked project
> [api] project lock command (for osc)

- src/api/app/helpers/webui/search_helper.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/views/webui/groups/index.html.erb
- src/api/app/views/webui/home/index.html.erb
- src/api/app/views/webui/package/update_build_log.js.erb
- src/api/app/views/webui/project/_packages_table.html.erb
- src/api/app/views/webui/project/status.html.erb
- src/api/app/views/webui/search/_owners.html.erb
- src/api/app/views/webui/user/edit.html.erb
- src/api/test/unit/webui/webui_helper_test.rb
Some refactoring and cosmetics, no change in functionality!
> Refactoring search and webui_helper

- src/api/app/controllers/source_controller.rb
- src/api/app/models/package.rb
- src/api/test/functional/source_controller_test.rb
> [api] fix enforced package deletion ignoring devel defintion

- src/api/app/controllers/source_controller.rb
- src/api/app/helpers/branch_package.rb
- src/api/app/models/project.rb
- src/api/app/models/user.rb
- src/api/app/policies/project_policy.rb
- src/api/test/functional/webui/project_controller_test.rb
first part of fixes, some more to come, but that need a bit more time
> Permission handling cleanup

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/package.rb
- src/api/app/views/webui/package/view_file.html.erb
- src/api/config/routes.rb
- src/api/test/functional/webui/package_branch_test.rb
- src/api/test/functional/webui/project_controller_test.rb
Get rid of save_modified_file and replace it using save_file at package_controller
> [webui] Mix save_modified_file and save_file at package_controller

- .travis.yml
- dist/ci/obs_testsuite_travis.sh
- src/api/app/controllers/application_controller.rb
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/middleware/proxy_mode_faker.rb
- src/api/config/environments/development.rb
- src/api/config/environments/test.rb
- src/api/lib/tasks/test_webui.rake
- src/api/test/functional/webui/proxy_mode_test.rb
This might be an option to test proxy mode. Let's discuss!
> proxy_auth_mode testing

- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/controllers/webui/patchinfo_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_permission_check.rb
- src/api/app/models/package.rb
- src/api/app/models/project.rb
- src/api/test/functional/source_controller_test.rb
- src/api/test/functional/webui/package_controller_test.rb
- src/api/test/functional/webui/patchinfo_controller_test.rb
- src/api/test/functional/webui/project_controller_test.rb
- src/api/test/unit/package_test.rb
and some small refactoring. webui test cases still missing unfortunatly
> Package destroy fixes

- src/api/test/functional/webui/package_controller_test.rb
Was disabled because of issue #408.
> [webui] Enable test for comment on remote project

- src/api/app/controllers/request_controller.rb
- src/api/app/jobs/project_create_auto_cleanup_requests.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/comment_request.rb
- src/api/app/models/package.rb
- src/api/app/models/project.rb
due to inconsitent data or delayed job use of models
> fixing todays crashes

- ReleaseNotes-2.6.7
@hennevogel @adrianschroeter please review!
> [dist] Update ReleaseNotes for 2.6.7

- src/api/app/controllers/webui/package_controller.rb
- src/api/test/functional/webui/package_controller_test.rb
Moved the functionality from source controller and created some test
> [webui] Get rid of ActiveXML in package_controller#save_meta

- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/models/package.rb
- src/api/app/views/webui/package/_live_log_controls.html.erb
- src/api/app/views/webui/package/binaries.html.erb
Calls now the backend directly!
> Refactor trigger_rebuild action

- ReleaseNotes-2.6.7
- src/api/app/assets/stylesheets/webui/application/cm2/suse.css.scss
- src/api/app/helpers/webui/package_helper.rb
- src/api/app/views/shared/_editor.html.erb
Basically cherry picked from 8ba617d5324f5d1e71fa80bbcca670c573973da9.
Will fix #1273.
> [webui] Implement .spec / .changes file support for codemirror

- src/api/app/controllers/webui/user_controller.rb
There is no need to call clone before count.
> [webui] Cleanup of user requests action

- src/api/app/mixins/test_backend_tasks.rb
- src/api/script/start_test_backend
- src/api/test/test_helper.rb
Implemented function "run_scheduler" as mixin which can be used in
the class ActionDispatch::IntegrationTest and script/start_test_backend
> [testing] unified functions to start scheduler in testing

- src/api/app/models/user.rb
- src/api/test/fixtures/attribs.yml
- src/api/test/fixtures/relationships.yml
- src/api/test/functional/search_controller_test.rb
- src/api/test/functional/webui/user_controller_test.rb
The ordering in the array was wrong. First package, then project.
> [webui] Fix user show

- src/api/app/models/event/base.rb
Error message was:
ArgumentError in Webui::PackageController#submit_request
wrong number of arguments (1 for 0)
> [webui][api] Fix ArgumentError EventBase model

- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/project.rb
- src/api/db/migrate/20151030130011_mark_events.rb
- src/api/script/start_test_backend
- src/api/test/fixtures/packages.yml
- src/api/test/functional/webui/project_controller_test.rb
- src/api/test/unit/code_quality_test.rb
- src/api/test/unit/project_test.rb
> Fix expand packages

- src/api/app/mixins/webui/has_flags.rb
- src/api/test/functional/webui/has_flags_test.rb
> [webui] Store Project/Package after changing flags

- README.md
- src/api/test/fixtures/users.yml
- src/api/test/functional/build_controller_test.rb
- src/api/test/functional/channel_maintenance_test.rb
- src/api/test/functional/comments_controller_test.rb
- src/api/test/functional/interconnect_test.rb
- src/api/test/functional/maintenance_test.rb
- src/api/test/functional/read_permission_test.rb
- src/api/test/functional/request_controller_test.rb
- src/api/test/functional/source_controller_test.rb
- src/api/test/functional/statistics_controller_test.rb
- src/api/test/functional/webui/maintenance_workflow_test.rb
- src/api/test/functional/webui/package_branch_test.rb
- src/api/test/functional/webui/package_controller_test.rb
- src/api/test/functional/webui/project_controller_test.rb
- src/api/test/functional/webui/project_lock_test.rb
- src/api/test/functional/webui/user_controller_test.rb
- src/api/test/functional/webui/users_test.rb
- src/api/test/functional/wizard_controller_test.rb
- src/api/test/test_helper.rb
- src/api/test/unit/user_test.rb
Password is 'buildservice'. Admin user king is still 'sunflower'.
> [ci] Use a single password for our test users

- src/api/app/controllers/webui/user_controller.rb
We don't used the stored pw anymore. So we can stop storing it.
> [webui] Stop storing password in a session

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_action_maintenance_release.rb
- src/api/lib/opensuse/permission.rb
patches are applied on out live instances already. Using :except instead of :only would be better, but we are currently in the transition
> Fix permission handling

- README.md
- Vagrantfile
- bootstrap-appliance-finalize.sh
- bootstrap-appliance.sh
- bootstrap.sh
* one for developing the frontend
** fixed output of provisioner script (RAILS_ENV=development was missing)
* one for testing deploment and appliance
* added code to make Vagrantfile more usable with vagrant-libvirt
> [vagrant] implemented 2 independent vagrant vms

- src/api/app/helpers/admin_helper.rb
- src/api/app/jobs/consistency_check.rb
- src/api/config/clock.rb
- src/api/test/fixtures/projects.yml
- src/api/test/fixtures/repositories.yml
- src/api/test/functional/aaa_pre_consistency_test.rb
- src/api/test/functional/source_controller_test.rb
- src/api/test/functional/zzz_post_consistency_test.rb
- src/api/test/test_consistency_helper.rb
- src/api/test/unit/code_quality_test.rb
- src/backend/BSXML.pm
Working on making backend and api xml rendering more similar.
> Improve admin check

- .travis.yml
- dist/ci/obs_testsuite_travis.sh
- src/api/lib/tasks/test_webui.rake
- src/api/script/api_test_in_spec.sh
* Split of the spider test and remove it from test coverage
> [ci] Split the test suite again

- src/api/app/helpers/webui/webui_helper.rb
We always need an element or CSS won't apply
> [webui] fix highlighting of some status like "scheduled"

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/views/webui/project/add_repository.html.erb
- src/api/test/functional/webui/project_controller_test.rb
https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/5677d233b05aeb0006000000
> [webui] TypoFix: Activerecord::RecordNotFound -> ActiveRecord::RecordNotFound

- src/api/app/models/role.rb
This was cherry picked from an older, stalled branch
> Small cleanup of role model

- .gitignore
- src/api/.rspec
- src/api/Gemfile
- src/api/Gemfile.lock
- src/api/config/application.rb
- src/api/lib/templates/rspec/feature/feature_spec.rb
- src/api/spec/README.md
- src/api/spec/browser_helper.rb
- src/api/spec/cassettes/Repositories/add.yml
- src/api/spec/cassettes/Sign_up/User.yml
- src/api/spec/cassettes/Sign_up/User_with_confirmation.yml
- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/spec/factories/users.rb
- src/api/spec/features/webui/repositories_spec.rb
- src/api/spec/features/webui/sign_up_spec.rb
- src/api/spec/features/webui/webui_project_create_spec.rb
- src/api/spec/helpers/webui/project_helper_spec.rb
- src/api/spec/models/project_spec.rb
- src/api/spec/rails_helper.rb
- src/api/spec/spec_helper.rb
- src/api/spec/support/backend.rb
- src/api/spec/support/capybara.rb
- src/api/spec/support/coverage.rb
- src/api/spec/support/factory_girl.rb
- src/api/spec/support/functional/authentification.rb
- src/api/spec/support/vcr.rb
> Get an RSpec test suite going

- dist/obs-server.spec
tested fix locally with "osc build"
> [dist] fixed BuildRequires for SLE_11_SP3/4

- src/api/spec/README.md
- src/api/spec/controllers/webui/webui_controller_spec.rb
- src/api/spec/helpers/webui/webui_helper_spec.rb
- src/api/spec/rails_helper.rb
- src/api/spec/routing/api_matcher_spec.rb
- src/api/spec/routing/webui_matcher_spec.rb
- src/api/spec/support/controllers/authentification.rb
- src/api/test/functional/webui/add_repo_test.rb
- src/api/test/functional/webui/anonymous_test.rb
- src/api/test/functional/webui/apiroutes_test.rb
- src/api/test/functional/webui/signup_test.rb
* Transformed anonymous access test
* Transformed webui helper test
* Added routing test
> Transform minitests to rspec

- src/backend/bs_worker
Fix for #1487 as discussed with @mlschroe
> [backend] manage_cache: mark rename error as internal server error

- src/backend/BSSched/EventQueue.pm
- src/backend/t/0017-BSSched-EventQueue.t
- src/backend/t/0018-BSSched-EventQueue-real_data.t
- src/backend/t/data/0018/events/finished:devel:languages:perl::perl-Test-Finished-Package
- src/backend/t/data/0018/events/package:devel:languages:perl::perl-Devel-Cover
- src/backend/t/data/0018/jobs/devel:languages:perl::perl-Test-Finished-Package
- src/backend/t/data/0018/jobs/devel:languages:perl::perl-Test-Finished-Package:status
> [backend] more testing and docu for EventQueue

- src/api/config/environments/test.rb
- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/test/functional/webui/csrf_test.rb
> [ci] Migrate CSRF test to RSpec

- src/api/Gemfile
- src/api/Gemfile.lock
- src/api/spec/rails_helper.rb
- src/api/spec/support/shoulda_matchers.rb
for testing Rails functionality in simple one liners.
https://github.com/thoughtbot/shoulda-matchers
> [ci] Add shoulda-matchers gem

- Vagrantfile
> [dist] Always mount the src/api/tmp in Vagrant

- src/api/spec/README.md
- src/api/spec/cassettes/User_s_home_project_creation/creating_a_home_project.yml
- src/api/spec/controllers/webui/user_controller_spec.rb
- src/api/spec/controllers/webui/webui_controller_spec.rb
- src/api/spec/factories/users.rb
- src/api/spec/features/webui/users/users_home_project_spec.rb
- src/api/spec/models/user_spec.rb
- src/api/spec/spec_helper.rb
- src/api/test/functional/webui/user_controller_test.rb
- src/api/test/unit/user_test.rb
Just started with user controller, it was getting too complex and just wanted to split the work
> User controller spec (part 1)

- src/api/spec/features/webui/notifications_spec.rb
@ChrisBr I merged your PR (I saw the green tick) and then realized that Travis was complaining about some rubocop failures... this just fixed it
> [ci] Fix some rubocop failures

- src/api/app/models/user.rb
- src/api/spec/cassettes/Watchlists/add_projects_to_watchlist.yml
- src/api/spec/cassettes/Watchlists/remove_projects_from_watchlist.yml
- src/api/spec/factories/watched_projects.rb
- src/api/spec/features/webui/watchlists_spec.rb
- src/api/test/functional/webui/watchlists_test.rb
* Migrate project watchlist tests to rspec test suite
* Fix caching issue that appears when changing watched projects within a second,
first found in 82e34072cd0e6dd2600e5360...
> [ci] Add rspec test for project watchlist

- src/api/spec/models/user_spec.rb
Use now a shared example for testing update_notifications instance and class method.
> [ci] Refactor user model spec

- src/api/spec/controllers/webui/project_controller_spec.rb
* Split preparation of test from actual test
* Ensure that allow_forgery_protection get's set back to false after test run
> [ci] Cleanup project controller spec

- src/backend/bs_worker
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
> Kill job if stuck in SLOF

- src/api/spec/models/relationship_spec.rb
> [ci] Fix relationship factory name

- docs/api/api/api.txt
- src/api/app/controllers/source_controller.rb
- src/api/app/models/package.rb
- src/api/app/models/service.rb
- src/api/spec/cassettes/FileUpload/uploading_a_kiwi_txz_file_creates_and_runs_kiwi_import_service.yml
- src/api/spec/features/webui/file_upload_spec.rb
- src/api/test/functional/source_services_test.rb
Creates kiwi_import service and runs waitservice followed by mergeservice command when
uploaded filename ends with kiwi.txz
> [webui] Implements kiwi import feature

- src/api/Gemfile
- src/api/Gemfile.lock
to fire up a browser in feature tests.
https://github.com/copiousfreetime/launchy
> [ci] Add launchy gem

- src/backend/bs_repserver
- filter *.sdeb files in filtersources
- fixed typo in filtersources
> Filtersources sdeb

- ReleaseNotes-2.6.9
As discussed with @adrianschroeter
> [dist] Update ReleaseNotes

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/webui_project.rb
- src/api/app/views/webui/project/_edit_repository.html.erb
- src/api/app/views/webui/project/add_repository.html.erb
- src/api/config/routes.rb
- src/api/test/functional/webui/project_controller_test.rb
Cherry picked from #962 to resolve #1177 and #923 for 2.6 branch!
> Fixes repo path

- src/api/app/views/shared/_involved_users.html.erb
- src/api/spec/README.md
- src/api/spec/browser_helper.rb
- src/api/spec/cassettes/Packages/behaves_like_user_tab/Add_role_to_group.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/Remove_role_from_group.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/Viewing_group_roles.yml
- src/api/spec/cassettes/Projects/behaves_like_user_tab/Add_role_to_group.yml
- src/api/spec/cassettes/Projects/behaves_like_user_tab/Remove_role_from_group.yml
- src/api/spec/cassettes/Projects/behaves_like_user_tab/Viewing_group_roles.yml
- src/api/spec/features/webui/packages_spec.rb
- src/api/spec/features/webui/projects_spec.rb
- src/api/spec/support/shared_examples/features/groups_tab.rb
Errbit error:
http://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/56d98026a117cf0006000000
> [webui] Fix adding / removal of roles to / from groups

- dist/t/Gemfile
- dist/t/Gemfile.lock
- dist/t/spec/features/login_spec.rb
- dist/t/spec/spec_helper.rb
- dist/t/spec/support/capybara.rb
@shyukri can use this to develop simple click tests against the running appliance.
> [ci] Start a simple spec for the appliance click tests

- src/api/config/routes.rb
- src/api/spec/controllers/webui/main_controller_spec.rb
- src/api/test/functional/webui/main_controller_test.rb
> Main controller spec

- src/api/app/controllers/webui/package_controller.rb
- src/api/spec/cassettes/Webui_PackageController/submit_request/not_successful/1_1_1_1.yml
- src/api/spec/cassettes/Webui_PackageController/submit_request/not_successful/1_1_1_2.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
> [webui] Show submit request ApiExceptions in flash

- dist/openQA_mail_notification.rb
- use mail gem (spam check complaint about wrong headers)
- made script more robust
> [ci] Some improvements on the openQA mail notification

- dist/setup-appliance.sh
- dist/t/0020-test-appliance.ts
- dist/t/bash-tap
should fix false positives in openQA
@shyukri , @adrianschroeter , @coolo : Please review and comment
> Fix tests networking

- src/api/app/views/webui/package/_live_log_controls.html.erb
- src/api/config/routes.rb
to make it possible to download the logfile for anonymous users again. Fixes #1603.
> [webui][api] Move logfile action to public controller

- docs/api/api/obs.rng
- src/api/db/migrate/20160321104000_add_k1om.rb
- src/api/db/seeds.rb
- src/api/db/structure.sql
- src/api/test/functional/published_controller_test.rb
- src/backend/BSCando.pm
- src/backend/bs_publish
Updated code with DB migration.
> [api] [backend] Add support for k1om

- src/api/script/start_test_backend
- src/api/test/fixtures/flags.yml
- src/api/test/fixtures/packages.yml
- src/api/test/fixtures/projects.yml
- src/api/test/fixtures/relationships.yml
- src/api/test/fixtures/repositories.yml
- src/api/test/fixtures/repository_architectures.yml
- src/api/test/functional/build_controller_test.rb
- src/backend/BSSched/PublishRepo.pm
Related to the already closed issue #1274
> [ci] Added testcase for errors at publishing

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/controllers/webui/request_controller.rb
- src/api/app/views/webui/package/_delete_dialog.html.erb
- src/api/test/test_helper.rb
> Bugfix 374

- src/api/test/functional/maintenance_test.rb
- src/backend/bs_repserver
- src/backend/bs_sched
> Backport 1608

- src/api/app/models/channel_binary.rb
- src/api/app/models/package.rb
Channel binary projects need to match with the channel binary's repository
project.
> [api][webui] Add validation for channel binary

- dist/README.UPDATERS
@adrianschroeter : as discussed before - only a first draft
> [docu] initial version of 2.7 section in README.UPDATERS

- dist/setup-appliance.sh
- dist/t/0020-test-appliance.ts
- dist/t/0060-check_required_services.ts
- dist/t/0070-check_recommended_services.ts
- dist/t/0080-check_ssl_certs.ts
- dist/t/0090-check_database.ts
- dist/t/0100-check_webserver_and_api.ts
@adrianschroeter : Please review
> recommend services in setup_appliance.sh and restructured system tests

- src/api/app/models/repository.rb
- src/api/spec/models/repository_spec.rb
This fixes a regression in commit e1f4858.
> [api][webui] Don't reject single character repository names

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/helpers/branch_package.rb
- src/api/app/models/user.rb
avoid left overs in backend when branching fails
> Fix backend sync issue

- src/api/lib/activexml/transport.rb
Respect no_proxy settings in API.
> [api] Adds implementation for respecting the no_proxy settings.

- src/backend/BSRPC.pm
> [backend] fix BSRPC noproxy handling

- src/api/lib/activexml/transport.rb
@tuminoid This is a forward port of your fix.  Can you please review my commit? I haven't tested it at all, but it should not affect the functionality...
> Noproxy handling

- ReleaseNotes-2.7
based on Henne's work.
Not sure if we shouldn't wipe out the "Other small changes" in the bottom ... or complete them (there is lot's more on this level).
Also dropped features only important to SUSE internal teams.
> Release notes

- src/api/app/controllers/public_controller.rb
- src/api/config/routes.rb
- src/api/test/functional/public_controller_test.rb
> [api] public api for simple request xml

- dist/t/0060-check_required_services.ts
- dist/t/0070-check_recommended_services.ts
@shyukri : Please Review
obsdodup might fail - but this is for other reasons and not concerning to this commit - i`m investigating
> [ci] checking services now in parallel

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/views/webui/project/add_repository.html.erb
> [webui] allow to add a repository with empty target project/repository

- dist/setup-appliance.sh
* new cli option --enable-optional-service
* to make testing easier
* to make it easier for documentation of "wizard install"
* added obssignd to optional services
> [dist] improvements for setup-appliance.sh

- dist/obs-server.spec
- src/backend/bs_cleanup
bs_cleanup script replaces bs_admin --cleanup-old-sources with extended and corrected functionality.
> [backend] bs_cleanup script

- src/backend/bs_repserver
- src/backend/bs_sched
- src/backend/bs_srcserver
This is the backport of the projectcopy with binaries fixes from master to 2.6 to fix  issue #1608
> [backend]Projectcopy backport2.6

- dist/obsstoragesetup
@adrianschroeter Please review
> [dist] check/create backendir in obsstoragesetup befor mounting lv 

- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/project.rb
- src/api/app/views/models/_project.xml.builder
- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/spec/factories/comment_projects.rb
- src/api/spec/factories/distribution.rb
- src/api/spec/factories/project.rb
- src/api/spec/support/controllers/controllers_authentification.rb
- src/api/test/unit/project_test.rb
Some cleanup and fixes rspec login for controllers setting User.current that was missing and lead to failures depending on the order of executions of the specs
> Project controller test part 3

- src/api/app/views/webui/monitor/_building.html.erb
- src/api/app/views/webui/monitor/old.html.erb
forward port from 2.6 branch fixes
> Webui monitor fixes

- src/api/app/controllers/webui/request_controller.rb
return in rescue returns only out of rescue ;)
> [webui] fix double render error

- ReleaseNotes-2.8
- src/api/app/views/webui/project/_incident_table_entries.html.erb
- src/api/app/views/webui/request/show.html.erb
> One more crash fix

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/models/user.rb
- src/api/app/views/layouts/webui/_personal_navigation.html.erb
- src/api/app/views/layouts/webui/webui.html.erb
- src/api/spec/controllers/webui/attributes_spec.rb
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/spec/controllers/webui/user_controller_spec.rb
- src/api/spec/features/webui/attributes_spec.rb
- src/api/spec/features/webui/login_spec.rb
- src/api/spec/features/webui/packages_spec.rb
- src/api/spec/features/webui/projects_spec.rb
- src/api/spec/features/webui/requests_spec.rb
- src/api/spec/features/webui/users/users_home_project_spec.rb
- src/api/spec/features/webui/watchlists_spec.rb
- src/api/spec/models/package_spec.rb
- src/api/spec/models/service_spec.rb
- src/api/spec/models/user_spec.rb
Some cleanup and migration of test to Rspec
> Project controller test part 4

- src/api/spec/controllers/webui/project_controller_spec.rb
Both are being created from the same factory and don't differ in any way
except their name.
> [ci] Merge user_tom and user_moi

- src/api/app/controllers/source_controller.rb
- src/api/config/routes.rb
- src/api/test/functional/source_controller_test.rb
@kkeil please test this one. I will backport if it solves your issue.
> [api] fix checkout of revisioned project _meta file

- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/spec/factories/repository.rb
Fix name creation for repository factory
> Project controller RSpec (part 5)

- src/api/app/views/webui/main/_news.html.erb
use the comment_body helper to avoid XSS issues.
> [webui] Update _news.html.erb

- src/api/app/models/issue_tracker.rb
the cve case is big since you can only parse the entire database ... should maybe become a clockword or delayed job instead in future.
> [api] fix upstream CVE database parsing

- src/api/app/helpers/flag_helper.rb
- src/api/app/models/flag.rb
- src/api/app/models/project.rb
- src/api/app/views/models/_package.xml.builder
- src/api/app/views/models/_project.xml.builder
- src/api/test/functional/source_controller_test.rb
- src/api/test/unit/build_flag_test.rb
- src/api/test/unit/debug_flag_test.rb
- src/api/test/unit/package_test.rb
- src/api/test/unit/project_test.rb
- src/api/test/unit/publish_flag_test.rb
Some flag related refactoring I did a while ago.
> Fun with flags

- src/api/spec/factories/bs_requests.rb
- src/api/spec/factories/configuration.rb
- src/api/spec/factories/groups.rb
- src/api/spec/factories/packages.rb
- src/api/spec/factories/project.rb
- src/api/spec/factories/project_log_entry.rb
- src/api/spec/factories/repository.rb
- src/api/spec/factories/status_message.rb
- src/api/spec/factories/users.rb
Drop the FAKER part from 'primary identifiers' in factories and use sequence only.
Check if we use curly brackets around things that need to be executed e.g. Faker etc.
> [ci] Improve and fix some factories

- src/backend/BSConfiguration.pm
- src/backend/bs_admin
- src/backend/bs_repserver
we collect endless event files otherwise.
Tired of manual cleanups :/
> [backend] avoid sending events to disabled archs

- src/api/app/controllers/build_controller.rb
- src/api/lib/api_exception.rb
* support local packages via project link
* report error for now when living on remote instance
> [api] fix lastsuccess call

- src/api/app/controllers/application_controller.rb
- src/api/app/controllers/person_controller.rb
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/owner.rb
- src/api/app/models/unregistered_user.rb
- src/api/app/models/user.rb
- src/api/app/views/models/_user.xml.builder
- src/api/app/views/webui/user/edit.html.erb
- src/api/app/views/webui/user/index.html.haml
- src/api/db/migrate/20160610105300_simplify_user_states.rb
- src/api/db/seeds.rb
- src/api/db/structure.sql
- src/api/script/import
- src/api/spec/models/user_spec.rb
- src/api/test/fixtures/users.yml
- src/api/test/functional/person_controller_test.rb
- src/api/test/functional/search_controller_test.rb
- src/api/test/unit/code_quality_test.rb
- src/api/test/unit/user_test.rb
- src/api/test/unit/watched_project_test.rb
* drop not anymore used user states
* drop User::STATES array and use an enum instead
* drop some over designed code
> [api] simplify user state code

- ReleaseNotes-2.8
- docs/api/api/api.txt
- src/api/app/controllers/person_controller.rb
- src/api/app/models/user.rb
- src/api/test/functional/person_controller_test.rb
> [api] add command to lock or delete users

- src/api/app/models/project.rb
https://errbit-opensuse.herokuapp.com/apps/5620ca2bdc71fa00b1000000/problems/576b5d9c3c01180006000000
Follow up of 94371415d7ab74286
> [api] Fix NoMethodError caused by non existant release target project

- src/api/app/assets/javascripts/webui/application.js
These functions are not used anywhere, just dropping them.
> [webui] application.js: drop unused functions

- src/api/app/mixins/request_source_diff.rb
- src/api/app/models/bs_request_action_delete.rb
Reverts openSUSE/open-build-service#1913
Asked by @bgeuken.
> Revert "[api][webui] Use default limit defined by backend for xml size(s)"

- dist/t/0060-check_required_services.ts
- dist/t/0070-check_recommended_services.ts
> fixed test case 0060 and 0070 to work on Tumbleweed

- src/api/Rakefile
- src/api/app/controllers/application_controller.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/project.rb
- src/api/test/fixtures/history_elements.yml
- src/api/test/functional/issue_trackers_controller_test.rb
- src/api/test/functional/status_controller_test.rb
Collection of patches required for Rails 5 that won't break with current rails version
> Things needed to be fixed for rails5

- src/api/spec/controllers/webui/project_controller_spec.rb
Little add 
[ci] Added ProjectController#remove_path_from_target spec to RSpec
> Project controller RSpec (part 9)

- src/api/app/assets/stylesheets/webui/application/bento/base.scss
* Drop vendor prefixes for box-shadow and border-radius
* Use nesting feature of sass for clarity
* Drop empty rulesets
* Group related selectors together that were previously spread out
-----
There is more to be done, but I wanted to get some feedback before continuing - is this ok so far?
> [webui] base.scss: cleanup

- src/api/app/models/bs_request.rb
Thanks @hennevogel for the tip :+1:
> [api] Require the worker/accept_request properly

- src/api/app/helpers/webui/buildstatus_helper.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/views/webui/project/_buildstatus.html.erb
- src/api/app/views/webui/project/monitor.html.erb
- src/api/spec/helpers/webui/buildstatus_helper_spec.rb
> Add titles/popovers for build states

- src/api/app/views/shared/_requests.html.erb
> [api] show requests in reversed order on profile pages

- src/api/app/views/webui/package/_no_repositories.html.erb
Introduced by 7d33c55d45eccb10e501ff6a59a7bb7ea45ab157.
> Fixes broken distributions link in no_repositories view

- src/backend/t/0004-BSUtil.t
@M0ses @adrianschroeter please review
> [backend] extend unit test 0004-BSUtil.t

- src/backend/t/0005-BSFileDB.t
@M0ses @adrianschroeter please review
> [backend] added unit test for BSFileDB.pm (0005-BSFileDB.t)

- src/api/app/views/shared/_repositories_flag_table_column.html.erb
- src/api/config/routes.rb
flag wasn't found in the controller because of broken package route.
fixes #2007.
> [webui] Fix broken flags routes

- src/api/app/controllers/webui/webui_controller.rb
> [webui] Introduces proxy_mode user active check

- src/backend/BSStdServer.pm
This is needed to give the daemon the possiblity
to remove the action files from the
> [backend] drop privs before touching .exit/.restart files

- src/api/spec/cassettes/Webui_PackageController/GET_binaries/with_a_failure_in_the_backend/1_5_1_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_binaries/with_a_failure_in_the_backend/1_5_1_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_binaries/with_build_results_and_binaries/1_5_4_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_binaries/with_build_results_and_binaries/1_5_4_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_binaries/with_build_results_and_no_binaries/1_5_3_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_binaries/with_build_results_and_no_binaries/1_5_3_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_binaries/without_build_results/1_5_2_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_binaries/without_build_results/1_5_2_2.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/test/functional/webui/package_controller_test.rb
`CONFIG['global_write_through'] = true` was needed because I render the views in some spec, it renders a partial that call the backend... that's also why there are  some new cassettes for VCR.
> Migrate package_controller_test#test_show_package_binary_as_user

- src/backend/call-service-in-docker.sh
* temporary dir is now generated by mktempdir in none world writeable directory
* debug mode for docker (start with bash) can now be enable by 'export DEBUG_DOCKER=1'
> [backend] fixed tmpdir problem in docker wrapper

- src/api/app/controllers/webui/repositories_controller.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/views/webui/repositories/distributions.html.erb
- src/api/spec/helpers/webui/webui_helper_spec.rb
supersedes 3815422644b4e176b905e8d26708c9fa5ab23914.
Finally fixes #1986.
> [webui] Fix replace_jquery_meta_characters

- src/backend/bs_dodup
Signed-off-by: Héctor Orón Martínez <hector.oron@collabora.co.uk>
> bs_dodup: fix up typo in usage text

- src/api/db/migrate/20160824132643_fix_bs_request_counter.rb
change method needs to be an instance method.
> [api][webui] Fix broken BsRequestCounter migration

- src/api/spec/cassettes/Package/_delete_file/file_not_found/raises_NotFoundError.yml
- src/api/spec/cassettes/Package/_delete_file/with_delete_permission/with_custom_options/sets_options_correct.yml
- src/api/spec/cassettes/Package/_delete_file/with_delete_permission/with_default_options/deletes_file.yml
- src/api/spec/cassettes/Package/_delete_file/with_delete_permission/with_default_options/sets_options_correct.yml
- src/api/spec/cassettes/Package/_delete_file/with_no_delete_permission/does_not_delete_file.yml
- src/api/spec/cassettes/Package/_delete_file/with_no_delete_permission/raises_DeleteFileNoPermission_exception.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/models/package_spec.rb
- src/api/test/functional/webui/package_controller_test.rb
I will rebase on #2065 as soon as it is merged ...
> Remove file test

- src/api/app/views/webui/project/show.html.erb
- Use ignoreLock only for locked projects permissions
- don't offer requests to locked projects
> [webui] fix checks for project options

- src/backend/BSConfig.pm.template
- src/backend/bs_publish
It is configurable in BSConfig.pm. Default is to use the non c versions.
@mlschroe: please review
> [backend] bs_publish: integrate createrepo_c / modifyrepo_c

- src/api/app/mixins/has_relationships.rb
- src/api/app/models/relationship.rb
Pairprogramming with Manuel;-)
> [api][webui] Replace mixin code by scopes for relationship model

- CONTRIBUTING.md
> Correct typo in CONTRIBUTING.md

- src/api/app/controllers/webui/project_controller.rb
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/_remove_maintained_project_fails_without_maintenance_kind_for_a_valid_maintained_project/1_29_2_1.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/with_maintained_kind/_remove_maintained_project_raise_excepction_with_invalid_maintained_project.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/with_maintained_kind/maintained_project_successfully_removed/1_29_1_1_1.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/with_maintained_kind/maintained_project_successfully_removed/1_29_1_1_2.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/with_maintained_kind/with_an_invalid_maintained_project/1_29_1_2_1.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/with_maintained_kind/with_an_invalid_maintained_project/1_29_1_2_2.yml
- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/spec/factories/maintained_project.rb
Write test for `app/controllers/webui/project_controller.rb#remove_maintained_project` and for some functions used in the before filter for `remove_maintained_project`.
I also modified `project_controller#remove_maintained_project` function by rendering an error when the MaintainedProject is not found and by using `destroy` in the if condition instead of `save` after doing `delete`.
> Write test for app/controllers/webui/project_controller.rb#remove_maintained_project

- src/api/spec/cassettes/Webui_ProjectController/POST_add_maintained_project/with_a_maintenance_project_kind_maintenance_/_add_maintained_project_raise_excepction_with_invalid_maintained_project.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_add_maintained_project/with_a_maintenance_project_kind_maintenance_/adding_a_valid_maintained_project/1_30_1_1_1.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_add_maintained_project/with_a_maintenance_project_kind_maintenance_/adding_a_valid_maintained_project/1_30_1_1_2.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_add_maintained_project/with_a_maintenance_project_kind_maintenance_/adding_a_valid_maintained_project/1_30_1_1_3.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_add_maintained_project/without_a_maintenance_project_kind_maintenance_/1_30_2_1.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_add_maintained_project/without_a_maintenance_project_kind_maintenance_/1_30_2_2.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/_remove_maintained_project_fails_without_maintenance_kind_for_a_valid_maintained_project/1_29_2_1.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/with_maintained_kind/maintained_project_successfully_removed/1_29_1_1_1.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/with_maintained_kind/maintained_project_successfully_removed/1_29_1_1_2.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/with_maintained_kind/with_an_invalid_maintained_project/1_29_1_2_1.yml
- src/api/spec/cassettes/Webui_ProjectController/POST_remove_maintained_project/with_maintained_kind/with_an_invalid_maintained_project/1_29_1_2_2.yml
- src/api/spec/controllers/webui/project_controller_spec.rb
- Test for app/controllers/webui/project_controller.rb#add_maintained_project
- Normal adding case.
- Thanks Ana, Björn and Moisés!
> [ci] project_controller.rb#add_maintained_project

- src/api/Gemfile
- src/api/Gemfile.lock
- src/api/spec/spec_helper.rb
@adrianschroeter please review it.
I saw you in other PRs lowering/changing the version for some gems, please be sure that this doesn't revert any of your changes :smile:
> Revert changes to recover nyan-cat-formatter and use UnicornFormatter

- contrib/start_development_backend
-w <num>: Define the amount of workers that will be started. (default: 1)
Example will start 3 workers: 
```
start_development_backend -w 3
```
> [vagrant] added option to start multiple workers

- src/api/Gemfile
- src/api/Gemfile.lock
- src/api/spec/spec_helper.rb
Reverts openSUSE/open-build-service#2158
> Revert "Revert "Revert changes to recover nyan-cat-formatter and use UnicornFormatter""

- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/wizard_controller.rb
- src/api/app/helpers/maintenance_helper.rb
- src/api/app/models/branch_package.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/app/models/bs_request_action_maintenance_release.rb
- src/api/app/models/bs_request_action_submit.rb
- src/api/app/models/owner.rb
- src/api/app/models/package.rb
- src/api/app/models/project.rb
- src/api/app/models/service.rb
- src/api/lib/opensuse/backend.rb
- src/api/script/start_test_backend
Add `nil` as default for the second argument of `Suse::Backend#post` as it is used a lot of times with `nil` or `''`.
> [api][webui] Add nil as default for Backend#post

- src/backend/BSSrcServer/Partition.pm
- src/backend/bs_dispatch
Use projid2reposerver function of BSSrcServer instead of the local one.
@mlschroe: please review
> [backend] use projid2reposerver from BSSrcServer

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/views/webui/package/show.html.erb
- src/api/config/environments/test.rb
- src/api/config/routes.rb
- src/api/spec/cassettes/Webui_PackageController/GET_trigger_services/with_right_params/1_10_1_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_trigger_services/with_right_params/1_10_1_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_trigger_services/with_right_params/1_10_1_3.yml
- src/api/spec/cassettes/Webui_PackageController/GET_trigger_services/without_a_service_file_in_the_package/1_10_2_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_trigger_services/without_a_service_file_in_the_package/1_10_2_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_trigger_services/without_a_service_file_in_the_package/1_10_2_3.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/factories/packages.rb
Trigger services from the UI.
Closes #1971
> Services ui

- src/api/app/controllers/webui/project_controller.rb
The variable `@update` defined in `project_controller#edit_comment` is not used.
> [webui] Remove unused variable

- src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_an_empty_revision_is_provided/1_11_2_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_an_empty_revision_is_provided/1_11_2_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_an_empty_revision_is_provided/1_12_2_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_an_empty_revision_is_provided/1_12_2_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_no_difference_in_sources_diff_is_empty/1_11_1_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_rdiff/when_no_difference_in_sources_diff_is_empty/1_12_1_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_show/with_a_package_that_have_derived_packages/1_7_3_1.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/test/functional/webui/package_controller_test.rb
Migrate functional tests to RSpec:
- test_diff_is_empty
- test_revision_is_empty
- test_derived_packages
> Migrate package_controller_test.rb (diff, revision, derived packages)

- src/api/spec/controllers/webui/project_controller_spec.rb
Write test for `app/controllers/webui/project_controller.rb#edit_comment`
> [ci] Write test for edit_comment

- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/spec/factories/packages.rb
Write test for app/controllers/webui/project_controller.rb#clear_failed_comment
> [webui][ci] #clear_failed_comment

- ReleaseNotes-2.8
- src/api/app/assets/stylesheets/webui/application/style.css.scss
- src/api/app/controllers/webui/request_controller.rb
- src/api/app/mixins/has_relationships.rb
- src/api/app/models/relationship.rb
- src/api/app/views/webui/request/_package_maintainers_dialog.html.erb
- src/api/app/views/webui/request/show.html.erb
- src/api/config/routes.rb
- src/api/spec/cassettes/Webui_RequestController/GET_show/does_not_show_a_hint_to_project_maintainers_if_the_target_package_has_no_maintainers.yml
- src/api/spec/cassettes/Webui_RequestController/GET_show/shows_a_hint_to_project_maintainers_when_there_are_package_maintainers.yml
- src/api/spec/controllers/webui/request_controller_spec.rb
- src/api/spec/factories/relationship.rb
- src/api/spec/models/package_spec.rb
- src/api/spec/models/user_spec.rb
- src/api/test/unit/code_quality_test.rb
I'll refactor the commits before merge.
This closes #1970
Screenshots:
> [webui] Submit Requests: Add hint for project maintainers, when target package has maintainers

- src/api/spec/controllers/webui/repositories_controller_spec.rb
Getting rid of 'DEPRECATION WARNING: xhr and xml_http_request
methods are deprecated' messages.
> [webui][ci] Deprecated xhr method

- dist/obs-server.spec
@adrianschroeter : Please review
> obsrun now created by obs-common

- src/api/app/models/comment.rb
The column `type` of `Comment` is reserved for storing the the class in case of inheritance and it is `nil` otherwise. As we validate that it is present it can not be `nil`. So that means that it is not possible to create a `Comment `directly, only instances of `Comment` children can be created. In case that we try to create an` Comment` with a non `nil` type which is not a name of any of the `Comment `children the following error is raised in the database level:
`ActiveRecord::SubclassNotFound: The single-table inheritance mechanism failed to locate the subclass: 'foo'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite …
> [api][webui] Add validation for Comment type

- src/api/app/views/shared/_single_request.json.erb
Related to 894a4abc30775d238cdfb9604e6459d70b327f94
> [webui] Don't verify if source packages are available in json response

- src/api/.rubocop_todo.yml
- src/api/app/controllers/build_controller.rb
- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/tag_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/mixins/has_attributes.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_permission_check.rb
- src/api/app/models/linked_project.rb
- src/api/app/models/user.rb
- src/api/app/models/user_ldap_strategy.rb
- src/api/lib/activexml/transport.rb
- src/api/lib/login_system.rb
- src/api/lib/xpath_engine.rb
- src/api/script/import
Enable the Style/Not cop in Rubocop and solve the offenses. :bowtie:
> [api][webui] Enable the Style/Not cop in Rubocop

- src/api/spec/cassettes/Packages/access_live_build_log/the_build_finished_succesfully.yml
- src/api/spec/cassettes/Packages/log/download_logfile_succesfully.yml
- src/api/spec/cassettes/Packages/log/live_build_finishes_succesfully.yml
- src/api/spec/cassettes/Webui_PackageController/GET_package_live_build_log/successfully/1_13_1_1.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/features/webui/packages_spec.rb
- src/api/test/functional/webui/package_controller_test.rb
Migrate` test/functional/webui/package_controller_test.rb` (build log) to the new test suite
- test_access_live_build_log
- test_live_build_log_doesnt_cause_500_error
- test_download_logfile
> Migrate package_controller_test to the new test suite

- src/api/Gemfile
- src/api/Gemfile.lock
As travis is getting more busy all the time, the occurance of
Capybara::Poltergeist::TimeoutError increased. Let's see if
an update of the test clickers works...
> [ci] update capybara and poltergeist

- src/api/app/controllers/build_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/models/package.rb
- src/api/script/start_test_backend
- src/api/test/functional/build_controller_test.rb
- src/api/test/functional/channel_maintenance_test.rb
- src/api/test/functional/maintenance_test.rb
- src/api/test/test_helper.rb
Support some routes for multibuild packages:
- list built binaries
- get logfile
- get binary
- get buildinfo (for local build)
> [api] basic multibuild support

- src/api/app/controllers/webui/package_controller.rb
- src/api/spec/cassettes/Requests/superseed/other_requests.yml
- src/api/test/functional/webui/package_controller_test.rb
- src/api/test/unit/code_quality_test.rb
> Revert package webui fix

- src/api/app/models/flag.rb
- src/api/test/unit/code_quality_test.rb
- src/api/test/unit/project_test.rb
This tests some of the cases which will fail with the current git master. The inheritance of flags from project to package in the API and thus in the WebUI is currently borked. There is a separate patch to fix the API.
> [api] added fix and test for build flag inheritance project to package

- ReleaseNotes-2.8
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/user.rb
- src/api/app/views/shared/_requests.html.erb
- src/api/app/views/webui/user/show.html.erb
- src/api/spec/controllers/webui/user_controller_spec.rb
- src/api/spec/factories/bs_requests.rb
- src/api/spec/models/user_spec.rb
- src/api/test/functional/webui/request_controller_test.rb
Pair programming with @mdeniz 
This must close #2201 
Performance measurement test in my local machine with ~1000 records was this:
and turned into this:
> [webui] Server side pagination

- src/api/app/controllers/webui/package_controller.rb
- src/api/test/functional/webui/package_controller_test.rb
- src/api/test/unit/code_quality_test.rb
> Revert package webui fix 2.6

- src/api/.rubocop.yml
I've ordered the cops alphabetically in `.rubocop.yml` and by categories. I've also added some comments to clarify what every cop does. :bowtie:
> [ci] Order and improve Rubocop config file

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/public_controller.rb
- src/api/app/helpers/public_helper.rb
- src/api/app/models/backend_file.rb
- src/api/app/models/project_log_entry.rb
- src/api/app/models/unregistered_user.rb
Enable the TernaryParentheses cop in Rubocop. :bowtie:
> [ci][api] Enable the TernaryParentheses cop

- src/api/app/controllers/webui/configuration_controller.rb
- src/api/app/controllers/webui/driver_update_controller.rb
- src/api/app/controllers/webui/monitor_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/views/webui/driver_update/create.html.erb
- src/api/app/views/webui/monitor/_events.html.erb
Hardcode default to "x86_64" as most used architecture. We may want an
instance or user default setting here in future. The default was not really
defined yet, since it depended on internal database index number.
The list was just random, means neither the arm, nor ppc architectures stuck together.
> [webui] sort architecture by name in monitor, set default

- src/api/app/controllers/webui/monitor_controller.rb
- src/api/app/views/webui/monitor/_events.html.erb
We draw x86_64 graphs, but combobox selection still picked the first arch.
> [webui] fix default architecture setting

- src/api/app/views/webui/package/_submit_request_dialog.html.haml
In SR dialog, add a label to the "Remove local package if request is accepted" text.
> [webui] Add label tag to "Remove local package if request is accepted"

- .jshintignore
- .travis.yml
- dist/ci/obs_testsuite_travis.sh
- dist/ci/obs_testsuite_travis_before.sh
- dist/ci/obs_testsuite_travis_install.sh
- src/api/app/assets/javascripts/webui/bratwurst.js
Also modified the install script and the before script to run the needed parts only depending on the job running
> Add JSHint analysis to Travis CI 

- src/api/app/helpers/maintenance_helper.rb
- src/api/test/functional/channel_maintenance_test.rb
* Supports manual and request release
* Only supports to release all multibuilds, no picking yet
> [api] support releasing multibuild results

- src/api/script/start_test_backend
- src/api/test/functional/source_controller_test.rb
And in-validate a bugreport that we don't support meta history of packages ;)
> [ci] write fixtures with comment

- src/api/app/models/issue_tracker.rb
we are just a cache, so take it from bugzilla
> [api] fix handling of issue creation date

- src/api/spec/factories/packages.rb
otherwise create will fail if backend is not running.
> [ci] Add global_write_through to package_with_service factory

- src/api/app/models/maintenance_incident.rb
- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/spec/factories/attribs.rb
- src/api/spec/factories/packages.rb
- src/api/spec/factories/project.rb
- src/api/spec/models/branch_package_spec.rb
Superseedes #2340 pull request.
> Maintenance factories

- src/api/spec/factories/bs_request_actions.rb
otherwise type attribute in render_xml is BsRequest and new_from_xml will fail.
> [ci] Add class name to bs_request_action_submit factory

- src/api/app/controllers/webui/request_controller.rb
> [webui] Do not change passed instance variable

- src/api/app/views/webui/package/live_build_log.html.erb
one more place where wrong container was used
> [webui] fix log file display of multibuild containers

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/lib/wizard.rb
This cop checks for space after `!`. :bowtie:
> [ci] Enable Style/SpaceAfterNot rubocop cop

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/application_controller.rb
- src/api/app/controllers/build_controller.rb
- src/api/app/controllers/person_controller.rb
- src/api/app/controllers/webui/monitor_controller.rb
- src/api/app/controllers/webui/patchinfo_controller.rb
- src/api/app/controllers/webui/search_controller.rb
- src/api/app/jobs/project_status_calculator.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/app/models/event_find_subscribers.rb
- src/api/app/models/package.rb
- src/api/app/models/package_build_status.rb
- src/api/app/models/project.rb
- src/api/app/models/unregistered_user.rb
- src/api/config/deploy.rb
- src/api/lib/wizard.rb
- src/api/test/functional/source_controller_test.rb
- src/api/test/functional/webui/attributes_test.rb
- src/api/test/functional/webui/spider_test.rb
Enable `Style/NegatedIf` Robocop cop and solve the offenses. :bowtie: 
This cop checks for uses of if with a negated condition. Only ifs without else are considered.
> [ci] Enable Style/NegatedIf Rubocop cop

- src/api/spec/factories/project.rb
> [ci] Write to the backend when linking project

- src/backend/t/0007-XML-Structured.t
fixed 0007-XML-Structured.t to match output of newer xml parser
fixes #2418 
@M0ses: please review
> [backend] fix backend test for CentOS

- src/api/app/controllers/webui/request_controller.rb
- src/api/app/models/bs_request.rb
- src/api/app/views/webui/project/_incident_table_entries.html.erb
> Fix issue #1874

- src/api/app/assets/stylesheets/webui/application/request.scss
> [webui] Improve accept/decline buttons styling

- dist/obs-server.spec
- src/backend/BSDispatch/Constraints.pm
- src/backend/bs_dispatch
moved the oracle and getmbsize function to a new module called Constraints.pm in subfolder BSDispatch/
This module will include all constraint related backend functions that they can be used by other backend services as well. 
Unit Tests will follow.
@mlschroe @M0ses please review
> [backend] moved oracle function to own module

- src/api/.rubocop.yml
Order` .rubocop.yml` alphabetically again :bowtie:
> [ci] Order .rubocop.yml alphabetically again

- src/api/app/controllers/request_controller.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/test/functional/maintenance_test.rb
- src/api/test/functional/request_controller_test.rb
- src/api/test/unit/code_quality_test.rb
We ignored the specified revision of maintenance incident actions since some time
> Maintenance incident revision fix

- src/api/db/migrate/20161122121211_move_comments_data.rb
- src/api/db/migrate/20161128115942_add_when_attribute_to_bs_request.rb
This was fixing 90% of my problems.
I will copy out an old database dump for verification
> [api] fix migration of request comments

- src/api/app/assets/javascripts/webui/application.js
- src/api/app/views/webui/request/_package_maintainers_dialog.html.erb
This broke with 23dedb58d9923fb7d9389a39d23acac90c71be8b
> [webui] Fix closing of package maintainer list

- src/api/app/models/project.rb
- src/api/spec/models/project_spec.rb
- src/api/test/unit/project_test.rb
Migrate `project#self.valid_name? `to the new test suite and refactor `project#self.valid_name?` :bowtie:
> project#self.valid_name?

- dist/obs-server.spec
- src/api/script/api_test_in_spec.sh
- src/api/test/functional/webui/download_on_demand_controller_test.rb
and drop test case from old test suite which works not reliable there.
> [dist][webui] enable new webui test suite

- src/api/app/assets/stylesheets/webui/application/package.scss
- src/api/app/views/webui/package/_buildstatus.html.erb
- src/api/app/views/webui/project/_buildstatus.html.erb
Change project page build result appearance similar to package build results, and add link for easy access to selected repo/arch build results
> [webui] project page build result UI changes

- src/backend/BSDispatcher/Constraints.pm
- src/backend/bs_dispatch
- src/backend/bs_repserver
- src/backend/bs_srcserver
* added function to get the capabilities from one worker
* added function to check a given _constraints file for compliant workers (also against the project constraints and dispatch constraints. 
* therefore moved some functions from bs_dispatch to BSDispatcher::Constraints.pm and BSDispatcher.pm
For the capability query of one worker only the workerid is needed.
For the _constraints file checking the following information are needed:
1. project
2. repository
3. arch
4. package
@mlschroe @M0ses @adrianschroeter please review
> [backend] new worker capabilities functions

- dist/obs-server.spec
- src/api/test/fixtures/event_mailer/review_wanted
- src/api/test/models/event_test.rb
require or recommends, this is the question.... @mlschroe ?
Fixes issue #2473
> [dist] default to libXDiff usage

- src/backend/bs_repserver
- src/backend/bs_srcserver
* added hostarch check in checkconstraintsfile
* fixed route to worker capability. 
@mlschroe: please review
> [backend] Respect hostarch on checkconstraintssfile and repair route 

- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/views/webui/image_templates/index.html.haml
Now the radio button is checked in the first package of the first
project with packages
Before:
After:
> [webui] minor change in Image Template

- src/api/app/controllers/source_controller.rb
> [api] Update variable names, error[:error] -> result[:error]

- src/api/spec/cassettes/ImageTemplates/branch_image_template.yml
- src/api/spec/factories/attribs.rb
- src/api/spec/features/webui/image_templates_spec.rb
> [ci] Tests for Image Templates

- src/backend/t/0230-BSDispatcher-Constraints.t
more unit tests for BSDispatcher/Constraints.pm 
@M0ses or @mlschroe please review
> [backend] unit tests for Constraints.pm

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/webui/driver_update_controller.rb
Checks for chaining of a block after another block that spans multiple
lines.
> [ci] Enable the Style/MultilineBlockChain cop in Rubocop

- src/backend/t/0230-BSDispatcher-Constraints.t
> [backend] fixed failing test

- src/api/app/controllers/application_controller.rb
- src/api/app/controllers/message_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/controllers/webui/patchinfo_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/helpers/maintenance_helper.rb
- src/api/app/models/branch_package.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/app/models/event/request.rb
- src/api/app/models/issue_tracker.rb
- src/api/app/models/owner.rb
- src/api/app/models/package.rb
- src/api/app/models/project.rb
- src/api/app/models/project_log_entry.rb
- src/api/app/models/repository.rb
- src/api/app/models/token.rb
- src/api/app/models/user.rb
- src/api/app/models/user_ldap_strategy.rb
- src/api/lib/activexml/node.rb
- src/api/lib/activexml/transport.rb
- src/api/lib/opensuse/validator.rb
- src/api/lib/wizard.rb
- src/api/lib/xpath_engine.rb
- src/api/test/test_helper.rb
Replace `return nil` by `return` as they are equivalent.
> [api] Replace return nil by return

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/models/bs_request_permission_check.rb
Checks the indentation of the first line of the right-hand-side of a
multi-line assignment.
> [ci] Enable Style/IndentAssignment cop

- docs/api/api/api.txt
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/models/branch_package.rb
- src/api/app/models/project.rb
- src/api/app/views/webui/image_templates/index.html.haml
- src/api/test/functional/source_controller_test.rb
- src/api/test/unit/code_quality_test.rb
Copy the rebuild strategy from the template when branching a image template.
> [api][webui] Copy the rebuild strategy

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/person_controller.rb
- src/api/app/controllers/search_controller.rb
- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/mixins/parse_package_diff.rb
- src/api/app/mixins/request_source_diff.rb
- src/api/app/models/branch_package.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/app/models/bs_request_permission_check.rb
- src/api/app/models/flag.rb
- src/api/app/models/package.rb
- src/api/app/models/project.rb
- src/api/spec/support/capybara.rb
> [ci] Enable the Style/IfInsideElse cop in Rubocop

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/helpers/validation_helper.rb
- src/api/app/helpers/webui/monitor_helper.rb
- src/api/app/models/package.rb
- src/api/lib/activexml/node.rb
- src/api/test/functional/webui/attributes_test.rb
- src/api/test/functional/webui/login_test.rb
- src/api/test/functional/webui/package_branch_test.rb
- src/api/test/functional/webui/package_create_test.rb
- src/api/test/functional/webui/package_edit_test.rb
- src/api/test/functional/webui/patchinfo_controller_test.rb
- src/api/test/functional/webui/search_controller_test.rb
- src/api/test/functional/webui/signup_test.rb
- src/api/test/functional/webui/users_test.rb
- src/api/test/test_helper.rb
Checks for parentheses around the arguments in method definitions
> [ci] Enable Style/MethodDefParentheses cop

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/models/branch_package.rb
- src/api/app/views/webui/image_templates/index.html.haml
- src/api/app/views/webui/package/_branch_dialog.html.erb
- src/api/app/views/webui/project/new_package_branch.html.erb
- src/api/config/routes.rb
- src/api/spec/cassettes/ImageTemplates/branch_image_template.yml
- src/api/spec/cassettes/Projects/branching/a_package_and_select_current_revision.yml
- src/api/spec/cassettes/Projects/branching/an_existing_package_to_an_invalid_target_package_or_project.yml
- src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_source_package_does_not_exist.yml
- src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_source_package_parameter_not_provided.yml
- src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_source_project_does_not_exist.yml
- src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_source_project_parameter_not_provided.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/features/webui/image_templates_spec.rb
- src/api/spec/features/webui/projects_spec.rb
- src/api/test/unit/code_quality_test.rb
- Moved save_new_link functionality to branch action
- Removed save_new_link action and route
- Changed route from /branch/:project/:package to /branch
- Preparation for image template branching
> [webui] Unite branch and save_new_link revision

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/mixins/build_log_support.rb
* Directly set @finished variable based on Buildresult.final_status?
* Simplify parsing hash for getting status code
> [webui] Small cleanup of build log related code

- docs/api/api/api.txt
- src/api/app/controllers/build_controller.rb
- src/backend/bs_repserver
remove packages from the publishing stage. 
Either specific packages or all packages are removed. 
At the end a scanrepo event and a publish event is triggered. 
@mlschroe please review
> [backend] [api] unpublish from :repo/

- src/api/.rubocop.yml
- src/api/Gemfile
- src/api/Gemfile.lock
- src/api/spec/models/project_spec.rb
- src/api/spec/spec_helper.rb
Add [Rantly](https://github.com/abargnesi/rantly) gem and its configuration and write property tests for `project#valid_name?`
> Property tests

- src/api/app/controllers/webui/user_controller.rb
- src/api/app/models/package_issue.rb
- src/api/app/models/user.rb
- src/api/app/views/shared/_requests.html.erb
- src/api/app/views/webui/user/index.html.haml
- src/api/app/views/webui/user/show.html.erb
- src/api/spec/controllers/webui/user_controller_spec.rb
We removed some instance variables that are not used.
Move some queries to scopes.
> Enhance queries by only fetching required attributes

- src/api/.rubocop.yml
- src/api/app/models/package.rb
- src/api/spec/models/package_spec.rb
Property tests package for package#self.valid_name? and refactor package#self.valid_name? :bowtie:
> Property tests package for package#self.valid_name?

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/search_controller.rb
- src/api/app/controllers/webui/request_controller.rb
- src/api/app/controllers/webui/search_controller.rb
- src/api/app/helpers/webui/project_helper.rb
- src/api/app/jobs/consistency_check.rb
- src/api/app/models/binary_release.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_action_maintenance_release.rb
- src/api/app/models/channel.rb
- src/api/app/models/owner.rb
- src/api/app/models/product.rb
- src/api/app/models/project.rb
- src/api/app/models/repository.rb
- src/api/app/models/status_history_rescaler.rb
- src/api/app/policies/group_policy.rb
- src/api/script/import
- src/api/test/functional/webui/spider_test.rb
Checks for receiver.length == 0 predicates and the negated versions receiver.length > 0 and receiver.length != 0.
> [ci][webui] Enable Style/ZeroLengthPredicate rubocop cop

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/models/architecture.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/distribution.rb
- src/api/app/models/distribution_icon.rb
- src/api/app/models/flag.rb
- src/api/app/models/group.rb
- src/api/app/models/issue_tracker.rb
- src/api/app/models/review.rb
- src/api/app/models/role.rb
- src/api/app/models/static_permission.rb
- src/api/app/models/user.rb
Checks for the use of old-style attribute validation macros.
> [ci][api] Enable Rails/Validation rubocop cop

- dist/obs-server.spec
- src/api/Makefile
and fail build when they fail. (we had no presets compiled anymore)
> [dist] fix bundle calls during package build

- src/api/.rubocop.yml
- src/api/app/controllers/webui/request_controller.rb
- src/api/app/models/channel.rb
- src/api/app/models/owner.rb
- src/api/app/models/repository.rb
- src/api/app/models/status_history_rescaler.rb
- src/api/app/policies/group_policy.rb
> [ci][api][webui] replace !receiver.empty? by receiver.present?

- src/api/app/controllers/webui/project_controller.rb
> [webui] Do not remove repos if there are errors

- ReleaseNotes-2.8
update release notes to mention this new feature:
https://github.com/openSUSE/open-build-service/pull/2544
> [webui][api] update release notes for public key/ssl cert download

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/public_controller.rb
- src/api/app/controllers/trigger_controller.rb
- src/api/app/controllers/webui/patchinfo_controller.rb
- src/api/app/helpers/webui/package_helper.rb
- src/api/app/mixins/parse_package_diff.rb
- src/api/app/models/issue.rb
- src/api/app/models/project.rb
- src/api/app/models/user.rb
- src/api/app/views/webui/package/_files_view.html.erb
- src/api/app/views/webui/package/rpmlint_log.html.haml
- src/api/app/views/webui/project/status.html.erb
- src/api/lib/tasks/databases.rake
- src/api/test/unit/code_quality_test.rb
Rubocop seems not to find all the offenses. :confounded:
> Enable the Performance/RedundantMatch cop

- src/api/app/helpers/webui/webui_helper.rb
- src/api/spec/helpers/webui/webui_helper_spec.rb
> [webui] Fix P1: toggle_sliced_text called with nil

- ReleaseNotes-2.8
- dist/obs-server.spec
- src/api/Gemfile
- src/api/Gemfile.lock
- src/api/app/assets/javascripts/webui/application.js.erb
- src/api/app/assets/stylesheets/webui/application.css.erb
- src/api/app/views/webui/main/index.html.erb
- src/api/config/feature.yml
- src/api/config/initializers/feature.rb
- src/api/config/routes.rb
- src/api/lib/feature_switch/obs_repository.rb
- src/api/spec/cassettes/ImageTemplates/branching/branch_image_template.yml
- src/api/spec/cassettes/ImageTemplates/feature_switch/disabled.yml
- src/api/spec/cassettes/ImageTemplates/feature_switch/enabled.yml
- src/api/spec/features/webui/image_templates_spec.rb
- src/api/spec/rails_helper.rb
- src/api/spec/routing/webui/projects/image_templates.rb
Now we have a YAML file to enable/disable features, we used the https://github.com/mgsnova/feature gem. 
The image templates feature is enabled by default.
> Multi switch for features + Hide/Show image templates feature

- dist/obs-server.spec
eg. via prjconf for debugging packaging issues
> [dist] allow to disable test suite

- src/api/spec/README.md
Developer documentation for property tests.
> Document property tests

- src/backend/BSXML.pm
added new element owner to person DTD
> [backend] added element owner to BSXML.pm

- src/api/lib/feature_switch/obs_repository.rb
Merging a hash with symbols and a yml file with strings as keys is not good
> [api][webui] Fix feature switching

- src/api/app/views/shared/_buildresult_box.html.erb
> [webui] show result_display__1 after succesful ajax call

- src/api/db/migrate/20170123115500_remove_duplicate_indexes.rb
- src/api/db/structure.sql
hopefully also fixes package builds
> Fix migration

- .travis.yml
- dist/ci/travis_before_install.sh
- dist/ci/travis_script.sh
- src/backend/t/0015-BSSched-EventSource-Directory.t
This is the integration of the backend tests into Travis CI
- libdevel-cover-perl is needed
- the cleanup in test 0015 will not fail the test
@M0ses: Please discuss :)
> [dist] [RFC] integrated backend tests in Travis-CI

- src/api/app/controllers/public_controller.rb
- src/api/spec/cassettes/PublicController/GET_source_file_history/with_history_limited_to_1/1_13_2_1.yml
- src/api/spec/cassettes/PublicController/GET_source_file_history/with_history_limited_to_1/1_13_2_2.yml
- src/api/spec/cassettes/PublicController/GET_source_file_history/with_history_unlimited/1_13_1_1.yml
- src/api/spec/cassettes/PublicController/GET_source_file_history/with_history_unlimited/1_13_1_2.yml
- src/api/spec/controllers/public_controller_spec.rb
fixes issue #2545 reported by @lnussel
> [api] fixed issue 2545 with test (limit not passed over interconnect)

- src/backend/bs_admin
just a minimal feature
@mlschroe Please Review ;-)
> [backend] --drop-badhosts for obs_admin

- src/api/app/models/package.rb
(in release projects or when some other problem caused a out of sync situation)
> [api] fix permission check when _product master object does not exist

- dist/systemd/obsapidelayed.service
Let's append OBS api delayed service file for Systemd based Linux distribution.
Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>
> [dist] Added OBS api delayed service for Systemd

- src/api/app/controllers/webui/search_controller.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/views/layouts/webui/webui.html.erb
- src/api/app/views/webui/main/_sponsors.html.haml
- src/api/app/views/webui/monitor/_stats.html.haml
- src/api/app/views/webui/monitor/_workers_table.html.haml
- src/api/app/views/webui/project/_buildstatus.html.erb
- src/api/app/views/webui/project/_packages_table.html.erb
- src/api/app/views/webui/request/show.html.erb
- src/api/app/views/webui/search/index.html.erb
- src/api/app/views/webui/search/owner.html.erb
- src/api/app/views/webui/search/project.html.erb
We already have a Rubocop cop for these but it is not working properly and it doesn't cover the views neither. :bowtie:
> [webui][api] Use empty? when possible

- src/api/app/controllers/request_controller.rb
- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/webui/request_controller.rb
- src/api/app/helpers/webui/buildresult_helper.rb
- src/api/app/helpers/webui/package_helper.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/mixins/webui/load_buildresults.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_permission_check.rb
- src/api/app/models/buildresult.rb
- src/api/app/models/configuration.rb
- src/api/app/models/package_build_status.rb
- src/api/app/models/project.rb
- src/api/app/models/user.rb
- src/api/app/views/webui/request/show.html.erb
- src/api/lib/xpath_engine.rb
eg. my_var.in?(["a", "b", "c"]) vs ["a", "b", "c"].include?(my_var)
The latter versions puts the focus on ["a", "b", "c"], while we actually
care about the content of my_var.
http://api.rubyonrails.org/classes/Object.html#method-i-in-3F
> [api] Use in? instead of include? where it makes sense

- src/api/.rubocop_todo.yml
- src/api/app/assets/javascripts/webui/application/project.js
- src/api/app/assets/stylesheets/webui/application.css.erb
- src/api/app/assets/stylesheets/webui/application/datatable.css.scss
- src/api/app/assets/stylesheets/webui/application/project.scss
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/helpers/webui/project_helper.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/models/project.rb
- src/api/app/views/webui/project/subprojects.html.haml
- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/spec/helpers/webui/webui_helper_spec.rb
> show sibling projects in subprojects view

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/Gemfile
> Ordered gems

- src/api/app/views/webui/monitor/_building_table.html.haml
This fixes the broken _building_table.html.haml .
> [webui] fix borked /monitor/old which got broken with HAML conversion

- src/api/app/controllers/statistics/maintenance_statistics_controller.rb
- src/api/spec/controllers/statistics/maintenance_statistics_controller_spec.rb
Fixes issue https://github.com/openSUSE/open-build-service/issues/2696
> [api] fix maintenance_statistics response when a project is not found

- src/api/script/start_test_backend
- src/backend/BSConfig.pm.template
needs to be added to 2.9 release notes, but the other pull request for that needs to be merged first.
> [backend] enable service dispatcher by default

- src/backend/call-service-in-docker.sh
* OBS_SERVICE_API must be in environment in docker container
* kiwi_import needs network connection to access api
> OBS_SERVICE_APIURL in call service in docker

- src/api/app/controllers/about_controller.rb
- src/api/config/routes.rb
- src/api/lib/tasks/errbit.rake
- src/api/spec/controllers/about_controller_spec.rb
- src/api/spec/controllers/public_controller_spec.rb
https://trello.com/c/DZznQC1Q/273-1-p4-app-controllers-about-controller-rb
> Write spec for AboutController

- src/api/app/models/bs_request_action_maintenance_incident.rb
makes it hard to debug stuff from the past otherwise
> [api] log the choosen way of branching in history

- src/api/app/views/webui/patchinfo/_form.html.erb
makes checkbox labels clickable
> [webui] In Edit Patchinfo dialog, add labels

- src/api/app/helpers/webui/webui_helper.rb
> [webui] replace anchor with void in review comment toggle to avoid scrolling

- docs/api/api/api.txt
- src/api/app/controllers/comments_controller.rb
- src/api/app/models/comment.rb
- src/api/spec/models/comment_spec.rb
* implemented function to reply to parent comments
* changed tests to satisfy new validator
* added test
> [api] reply to comment function

- src/api/app/controllers/webui/main_controller.rb
- src/api/app/views/webui/main/_systemstatus.html.haml
count is way to expensive for every page load
> [webui] Cache app statistics on frontpage

- src/api/lib/xpath_engine.rb
- src/api/test/functional/search_controller_test.rb
slightly modified version of https://github.com/openSUSE/open-build-service/pull/2612
> [api] xpath_engine: support project.remoteurl.

- dist/setup-appliance.sh
- dist/t/0060-check_required_services.ts
obsservicedispatch now enabled per default in version > 2.8
@adrianschroeter Please review
> [dist] check service obsservicedispatch

- src/api/app/models/package.rb
- src/api/app/views/webui/image_templates/index.html.haml
- src/api/spec/cassettes/ImageTemplates/branching/branch_image_template.yml
- src/api/spec/features/webui/image_templates_spec.rb
- src/api/spec/models/package_spec.rb
for image templates.
The controller needs to be accessible for not logged in users otherwise interconnect won't work.
However, the create button needs to be disabled and the icons hidden, otherwise it would require login
to create and access the page at all.
Fixes #2619.
Supersedes #2620
> [webui] Disable create button and hide icons

- dist/t/0060-check_required_services.ts
- dist/t/0070-check_recommended_services.ts
* moved test from
0060-check_required_services.ts -> 0070-check_recommended_services.ts
> [ci] changed tests for obsservicedispatch

- src/api/config/routes.rb
- src/api/spec/requests/webui/apidocs_spec.rb
> [webui] Redirects /apidocs to /apidocs/index

- src/api/app/assets/javascripts/webui/application/package.js
- src/api/app/assets/stylesheets/webui/application/package.scss
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/models/package.rb
- src/api/app/models/package_service_error_file.rb
- src/api/app/views/layouts/webui/_flash.html.erb
- src/api/spec/cassettes/MaintenanceWorkflow/maintenance_workflow.yml
- src/api/spec/cassettes/Package/_service_error/with_error/1_7_2_1.yml
- src/api/spec/cassettes/Package/_service_error/without_error/1_7_1_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_show/with_a_package_that_has_a_broken_service/1_7_4_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_show/with_a_package_that_has_a_broken_service/1_7_4_2.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/successfully/1_13_1_1_1_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/successfully/1_13_2_1_1_1.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/factories/packages.rb
- src/api/spec/models/package_spec.rb
before
after
showing more info
> [webui] Add link 'more info' in package flash error

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
Checks for nested method definitions
> [ci] Enable Lint/NestedMethodDefinition Rubocop cop

- src/api/app/controllers/application_controller.rb
not_authorized becomes create_attrib_not_authorized or delete_attrib_namespace_not_authorized
> [api] Introduce action/class to pundit errorcode

- src/api/app/assets/javascripts/webui/application/user.js
- src/api/app/views/webui/user/show.html.erb
This is a leftover from #2680.
> [webui] Use new DataTable class for user reviews

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/request_controller.rb
- src/api/app/controllers/tag_controller.rb
- src/api/app/helpers/status_helper.rb
- src/api/app/helpers/webui/project_helper.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/jobs/project_create_auto_cleanup_requests.rb
- src/api/app/models/owner.rb
- src/api/app/models/package.rb
- src/api/app/models/package_issue.rb
- src/api/app/models/project.rb
- src/api/app/models/tag.rb
- src/api/app/models/update_notification_events.rb
- src/api/db/migrate/20131027122410_add_primary_to_repository_architectures.rb
- src/api/db/migrate/20131209103450_add_primary_to_groups_users.rb
- src/api/lib/activexml/node.rb
- src/api/lib/opensuse/backend.rb
- src/api/spec/support/capybara.rb
- src/api/test/unit/code_quality_test.rb
This cop enforces the use the shorthand for self-assignment.
> Enable Style/SelfAssignment Rubocop cop

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/configurations_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/helpers/webui/project_helper.rb
- src/api/app/mixins/build_log_support.rb
- src/api/app/models/issue_tracker.rb
- src/api/config/application.rb
- src/api/config/initializers/activexml.rb
- src/api/config/unicorn/development.rb
This cop checks for methods invoked via the . operator (like FileUtils::rmdir instead of FileUtils.rmdir).
> Enable Style/ColonMethodCall Rubocop cop

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/models/project_log_entry.rb
Enable Security/YAMLLoad Rubocop cop and autocorrect the offenses. :bowtie:
> Enable Security/YAMLLoad Rubocop cop

- src/api/app/controllers/webui/user_controller.rb
- src/api/app/views/webui/user/show.html.erb
A user should only see his own requests. 
Got introduced by 71a665e.
> User hide requests

- src/api/Procfile
Foreground starting thinking sphinx has been fixed in the gem.
> [dist] Also start search with foreman

- src/api/app/views/webui/user/show.html.erb
Introduced in f6eeff042ba4be38277a80b286343f4f61a3dd3d.
> [webui] Use is_displayed_user variable in User#show view

- dist/ci/travis_before_script.sh
- src/api/spec/controllers/webui/apidocs_controller_spec.rb
Tests for apidocs controller has been changed to work without a previous build
of apidocs.
> [ci] Travis CI doesn't need to build apidocs any more

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
I'm not sure if this is the correct way to implement this. Would appreciate some feedback.
> Enable the Rails/NotNullColumn Rubocop cop

- dist/obs-server.spec
- src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb
We need this for production deploy or we will be done for a longer time
> Speed up migration

- src/api/spec/controllers/webui/architectures_controller_spec.rb
We missed to cover the index action in the specs
> Create ArchitecturesController#index spec

- src/backend/bs_service
- src/backend/bs_servicedispatch
- src/backend/call-service-in-docker.sh
set the service event to become due again in 10 minutes when:
- a service 500 error is returned
- an error is returned that does not begin with a digit
> [backend] retrigger service run after 10 minutes

- src/api/app/models/issue_tracker.rb
> [api] fix crash on parsing bugzilla time stamps

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/models/package.rb
- src/api/app/views/webui/package/live_build_log.html.erb
- src/api/spec/features/webui/packages_spec.rb
- src/api/spec/models/package_spec.rb
on live log view to determine to trigger a rebuild or not.
#2130.
> [webui] Show what depends on information

- src/api/app/models/user.rb
Found by looking at code coverage of that model and grep'ing through the
code.
https://coveralls.io/builds/10625313/source?filename=app%2Fmodels%2Fuser.rb
> [api] Remove dead code from user model

- src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb
Handle existing double entries of repositories in DB
> [api] don't fail on existing double repository entries

- src/api/spec/controllers/webui/attributes_spec.rb
'update' and 'delete' actions are now tested.
> [ci] Add more tests to attrib controller tests

- src/api/.rubocop.yml
- src/api/.rubocop_todo.yml
- src/api/app/controllers/group_controller.rb
- src/api/app/controllers/search_controller.rb
- src/api/app/controllers/webui/request_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/helpers/webui/package_helper.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_permission_check.rb
- src/api/app/models/cache_line.rb
- src/api/app/models/user_ldap_strategy.rb
- src/api/db/migrate/20140908125426_convert_request_history.rb
- src/api/lib/opensuse/backend.rb
- src/api/lib/opensuse/validator.rb
This cop checks how the *when*s of a case expression are indented in relation to its `case` or `end` keyword.
> Enable Style/CaseIndentation Rubocop cop

- src/api/app/mixins/has_relationships.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/event/base.rb
- src/api/app/models/group.rb
- src/api/app/models/maintenance_incident.rb
- src/api/app/models/review.rb
- src/api/app/models/role.rb
- src/api/app/models/user.rb
- src/api/db/migrate/20170320151300_add_updated_at_to_role.rb
- src/api/db/structure.sql
- src/api/spec/factories/role.rb
- src/api/spec/models/role_spec.rb
- src/api/test/functional/request_events_test.rb
Uses Rails native caching instead of a number of self-implemented methods.
> [api][webui] Update caching of all roles

- src/api/spec/controllers/webui/attributes_spec.rb
'new' and 'edit' actions are now tested.
> [ci] Add even more tests to attrib controller tests

- src/api/spec/helpers/validation_helper_spec.rb
This implements the missing tests for the rspec test suite.
Related to card:
https://trello.com/c/CJtlSMoy/268-app-helpers-validation-helper-rb
> [ci] Add validation_helper_spec.rb

- src/api/lib/activexml/transport.rb
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/successfully_with_a_package_which_name_that_includes_/1_13_1_1_2_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/successfully_with_a_project_which_name_that_includes_/1_13_1_1_3_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/with_a_non_existant_package/1_13_1_1_4_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/with_a_non_existant_package/1_13_1_1_4_2.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/with_a_non_existant_package/1_13_1_1_5_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/with_a_non_existant_package/1_13_1_1_5_2.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/with_a_protected_package/1_13_1_1_3_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/with_a_protected_package/1_13_1_1_3_2.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/with_a_protected_package/1_13_1_1_4_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_package_live_build_log/it_should_behave_like_build_log/with_a_protected_package/1_13_1_1_4_2.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/successfully_with_a_package_which_name_that_includes_/1_13_2_1_2_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/successfully_with_a_project_which_name_that_includes_/1_13_2_1_3_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/with_a_non_existant_package/1_13_2_1_4_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/with_a_non_existant_package/1_13_2_1_4_2.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/with_a_non_existant_package/1_13_2_1_5_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/with_a_non_existant_package/1_13_2_1_5_2.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/with_a_protected_package/1_13_2_1_3_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/with_a_protected_package/1_13_2_1_3_2.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/with_a_protected_package/1_13_2_1_4_1.yml
- src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/it_should_behave_like_build_log/with_a_protected_package/1_13_2_1_4_2.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
> [api][webui] Encode url to permit '+' into project or package name

- src/api/app/models/full_text_search.rb
- src/api/lib/workers/accept_requests.rb
> Fix crashes

- src/api/spec/helpers/webui/project_helper_spec.rb
This will test the `format_seconds` and the `incident_issue_color` methods in the project helper.
> [ci] Add new rspec test cases for project helper

- codecov.yml
- src/api/Gemfile
- src/api/Gemfile.lock
- src/api/spec/rails_helper.rb
- src/api/spec/support/coverage.rb
- src/api/test/test_helper.rb
coveralls stopped merging results, try out a new service....
> [api][webui] Switch from coveralls to codecov

- src/api/app/controllers/webui/package_controller.rb
> Catch service running exception

- src/api/spec/controllers/webui/main_controller_spec.rb
Also added some test for other uncovered lines
> Main controller specs covering missed lines in RSpec

- src/api/config/routes.rb
Remove duplicate (api) route entries from the config/routes.rb.
> [api] Remove duplicate routes

- src/api/spec/controllers/statistics/maintenance_statistics_controller_spec.rb
Verifies that projects with access flag set to 'disable' are hidden to
other users.
> [ci] Add rspec maintenance statistics test for hidden projects

- src/api/app/controllers/attribute_controller.rb
- src/api/app/controllers/build_controller.rb
- src/api/app/controllers/message_controller.rb
- src/api/app/controllers/person_controller.rb
- src/api/app/controllers/published_controller.rb
- src/api/app/controllers/statistics_controller.rb
- src/api/app/controllers/tag_controller.rb
- src/api/app/helpers/validation_helper.rb
- src/api/spec/cassettes/Webui_PackageController/DELETE_trigger_rebuild/1_14_1.yml
- src/api/spec/cassettes/Webui_PackageController/DELETE_trigger_rebuild/1_14_2.yml
- src/api/spec/cassettes/Webui_PackageController/DELETE_trigger_rebuild/lets_the_user_know_there_was_an_error.yml
- src/api/spec/cassettes/Webui_PackageController/DELETE_trigger_rebuild/redirects_to_the_package_binaries_path.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/models/package_spec.rb
- src/api/test/unit/code_quality_test.rb
In order to not tightly couple the app controllers with the authentication logic. This will allow us to separate the authentication logic into an encapsulated component and hence make adding kerberos authentication support easier.
https://trello.com/c/3r54CGQ6/338-8-p4-getting-kerberos-support-in
> [api] replace @http_user with User.current

- src/api/app/controllers/application_controller.rb
- src/api/app/controllers/public_controller.rb
- src/api/app/controllers/request_controller.rb
- src/api/app/mixins/forbids_anonymous_users.rb
- src/api/app/models/package.rb
- src/api/lib/authenticator.rb
In order to make adding new authentication methods (i.e. kerberos) easier.
> Refactor: encapsulate authentication code into Authenticator class

- src/api/Gemfile
- src/api/Gemfile.lock
- src/api/app/assets/javascripts/webui/application.js.erb
- src/api/app/assets/stylesheets/webui/application.css.erb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/user.rb
- src/api/app/views/layouts/webui/webui.html.erb
- src/api/config/environments/development.rb
- src/api/config/initializers/peek.rb
- src/api/config/routes.rb
- src/api/db/seeds.rb
to profile SQL and memcache.
https://github.com/peek/peek.
> [Proposal] Add peek status bar

- dist/obsworker
- dist/openstack/README.txt
- dist/openstack/create-grub-image.sh
- dist/openstack/create-secgroups.sh
- dist/openstack/create-vm-volumes.sh
- dist/sysconfig.obs-server
- src/backend/bs_worker
@adrianschroeter @mlschroe Please Review
Sorry, messed up build_in_openstack branch and opened a new one.
> New building in openstack feature

- src/api/app/controllers/source_controller.rb
- src/api/app/models/project.rb
I put this changes out https://github.com/openSUSE/open-build-service/pull/2932 as they are unrelated to fixing remote branching :bowtie:
> [api] Fix typos in comments

- ReleaseNotes-2.9
- src/api/config/initializers/activexml.rb
- src/api/config/options.yml.example
- src/api/lib/activexml/transport.rb
> Get rid of dead option api_relative_url_root

- src/api/app/views/webui/user/login.html.erb
Poltergeist tests really have problems with clicking on
&#187;
> [webui] Give the login button an id

- dist/find-requires.sh
Signed-off-by: Dinar Valeev <k0da@opensuse.org>
> Fix typo in find-requires.sh

- src/backend/BSSched/Checker.pm
- src/backend/BSSched/EventHandler.pm
- src/backend/bs_repserver
added event to single publish a publish disabled repository. 
As discussed with @adrianschroeter the per package publish settings are overwritten. Which means that all packages inside a repository get published even if a package is publish disabled. 
@mlschroe @M0ses: Please review
> [backend] added single publish event

- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/user.rb
- src/api/spec/models/user_spec.rb
Add basic tests for the new method.
Pair programming with @bgeuken
> [api][ci] Move creation of user with fake pw to model

- dist/munin/obs_dispatcher
- dist/munin/obs_scheduler_buildavg
- dist/munin/obs_scheduler_projects
- dist/munin/obs_scheduler_queue
- dist/munin/obs_scheduler_repositories
- dist/munin/obs_scheduler_worker_state
- dist/munin/obs_srcserver_filesizes
- dist/munin/obs_srcserver_packages
- dist/munin/obs_worker_cpu_mem
This PR is a munin-obs plugin files that we are using in munin
(http://munin-monitoring.org/) to support a fined-grained obs
monitoring service. It is to support a fined-grained obs monitoring
service to administrators that are maintaining a obs server.
Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>
> [dist] Initial support for munin-based fine-grained obs monitoring

- ReleaseNotes-2.8.1
- src/api/config/initializers/activexml.rb
- src/api/config/options.yml.example
- src/api/lib/activexml/transport.rb
The PR #2962 that fixed #2948 is now in 2.8 release branch.
> Backported PR #2962 to 2.8

- src/api/app/assets/javascripts/webui/application.js.erb
- src/api/app/assets/stylesheets/webui/application/dialog.scss
- src/api/app/views/layouts/webui/webui.html.erb
- src/api/app/views/webui/main/_add_news_dialog.html.haml
- src/api/app/views/webui/main/_delete_message_dialog.html.haml
- src/api/app/views/webui/package/_delete_dialog.html.erb
- src/api/app/views/webui/package/_linking_packages.html.erb
- src/api/app/views/webui/package/_submit_request_dialog.html.haml
- src/api/app/views/webui/patchinfo/_delete_dialog.html.haml
- src/api/app/views/webui/project/_add_maintained_project_dialog.html.erb
- src/api/app/views/webui/project/_delete_dialog.html.erb
- src/api/app/views/webui/project/_incident_request_dialog.html.erb
- src/api/app/views/webui/project/_linking_projects.html.erb
- src/api/app/views/webui/project/_release_request_dialog.html.erb
- src/api/app/views/webui/project/_remove_target_request_dialog.html.erb
- src/api/app/views/webui/project/_unlock_dialog.html.erb
- src/api/app/views/webui/request/_add_reviewer_dialog.html.erb
- src/api/app/views/webui/request/_add_role_request_dialog.html.erb
- src/api/app/views/webui/request/_change_devel_request_dialog.html.erb
- src/api/app/views/webui/request/_delete_request_dialog.html.erb
- src/api/app/views/webui/request/_set_bugowner_request_dialog.html.erb
- src/api/app/views/webui/request/_set_incident_dialog.html.erb
- src/api/app/views/webui/user/_password_dialog.html.haml
- src/api/app/views/webui/user/_save_dialog.html.haml
- src/api/app/views/webui/webui/_dialog.js.erb
Fix branch and submit dialogs conflict. :slightly_smiling_face: 
Before:
After:
> [webui] Branch and submit dialogs conflict

- src/api/Makefile
to not install the gems from development, test and assets group.
Otherwise starting the rails server will fail as the gems are not installed.
> [dist] Set bundle config variable

- dist/find-requires.sh
otherwise frontend will not start because of missing dependencies.
> [dist] Add :production group to find_requires script

- src/api/app/models/branch_package.rb
- src/api/app/models/project.rb
- src/api/app/models/project_meta_file.rb
- src/api/spec/cassettes/Project/_branch_remote_repositories/kiwi_project/1_6_2_1.yml
- src/api/spec/cassettes/Project/_branch_remote_repositories/kiwi_project/1_6_2_2.yml
- src/api/spec/cassettes/Project/_branch_remote_repositories/kiwi_project/with_correct_path_links.yml
- src/api/spec/models/project_spec.rb
Add repositories when branching from a remote project to the local one. Kiwi images are also supported.
Pair programmed with @ChrisBr. We used some of the changes from: #2932
> [api] Add repositories when branching from remote

- src/api/app/models/repository.rb
> [frontend] Skip self referencing repos

- dist/systemd/obsworker@.service
Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>
> [dist] Add OBS Worker for Systemd

- dist/t/spec/spec_helper.rb
Fix tests
https://github.com/openSUSE/open-build-service/commit/0bb309ca502b6fac55da44d68901682e41925252#diff-e8d594f6a0657e520cdf751cf2f4227dR4
> [ci] fix ids in dist tests

- src/api/Gemfile.lock
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/helpers/maintenance_helper.rb
- src/api/spec/controllers/webui/user_controller_spec.rb
Message wording, crash fix on typo and clean re-generated Gemfile.lock
> Minor Fixes

- src/backend/t/0170-BSSched-BuildJob-Package.t
- src/backend/t/data/0170/srcserver/fixtures_0001
Fixes failing backend tests with new perl-BSSolv versions
> [backend] fix backend test suite

- src/api/app/assets/javascripts/webui/application.js.erb
- src/api/app/assets/javascripts/webui/application/requests_table.js
- src/api/app/assets/javascripts/webui/application/user.js
- src/api/app/controllers/webui/users/bs_requests_controller.rb
- src/api/app/models/bs_request/data_table/find_for_user_query.rb
- src/api/app/models/bs_request/data_table/params_parser.rb
- src/api/app/views/webui/shared/_requests_table.html.haml
- src/api/app/views/webui/user/show.html.haml
This PR makes the user requests table code more generic so it can be re-used by other associated objects like projects and packages.
> Make requests table code generic

- src/api/app/assets/javascripts/webui/application/requests_table.js
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/controllers/webui/projects/bs_requests_controller.rb
- src/api/app/controllers/webui/request_controller.rb
- src/api/app/models/bs_request/data_table/find_for_project_query.rb
- src/api/app/models/bs_request/data_table/params_parser.rb
- src/api/app/views/webui/project/requests.html.erb
- src/api/app/views/webui/projects/bs_requests/index.json.erb
- src/api/config/routes.rb
- src/api/spec/controllers/webui/projects/bs_requests_controller_spec.rb
- src/api/spec/controllers/webui/users/bs_requests_controller_spec.rb
- src/api/spec/spec_helper.rb
- src/api/spec/support/shared_contexts/a_set_of_bs_requests.rb
- src/api/spec/support/shared_examples/a_bs_requests_data_table_controller.rb
- src/api/test/functional/webui/request_controller_test.rb
- src/api/test/unit/code_quality_test.rb
As part of this card: https://trello.com/c/ABmVsXfI/377-5-p4-refactor-package-project-requests-page
> [webui] make requests for project table use DataTable js plugin

- src/api/app/assets/javascripts/webui/application/package.js
- src/api/app/assets/stylesheets/webui/application/package.scss
- src/api/app/controllers/webui/packages/job_history_controller.rb
- src/api/app/helpers/webui/package_helper.rb
- src/api/app/models/local_job_history.rb
- src/api/app/models/package.rb
- src/api/app/views/webui/package/binaries.html.erb
- src/api/app/views/webui/packages/job_history/_tabs.html.erb
- src/api/app/views/webui/packages/job_history/index.html.haml
- src/api/config/routes.rb
- src/api/spec/cassettes/Package/_jobhistory_list/when_response_fails/1_14_2_1.yml
- src/api/spec/cassettes/Package/_jobhistory_list/when_response_is_successful/1_14_1_1.yml
- src/api/spec/cassettes/Package/_jobhistory_list/when_response_is_successful/1_14_1_2.yml
- src/api/spec/cassettes/Package/_jobhistory_list/when_response_is_successful/1_14_1_3.yml
- src/api/spec/cassettes/Package/_jobhistorylist/when_response_fails/1_14_2_1.yml
- src/api/spec/cassettes/Package/_jobhistorylist/when_response_is_successful/1_14_1_1.yml
- src/api/spec/cassettes/Webui_Packages_JobHistoryController/GET_index/with_job_history/1_1_3_1.yml
- src/api/spec/cassettes/Webui_Packages_JobHistoryController/GET_index/with_job_history/1_1_3_2.yml
- src/api/spec/cassettes/Webui_Packages_JobHistoryController/GET_index/with_job_history/1_1_3_3.yml
- src/api/spec/cassettes/Webui_Packages_JobHistoryController/GET_index/with_job_history/1_1_3_4.yml
- src/api/spec/cassettes/Webui_Packages_JobHistoryController/GET_index/with_job_history/1_1_3_5.yml
- src/api/spec/cassettes/Webui_Packages_JobHistoryController/GET_index/without_a_valid_architecture/1_1_2_1.yml
- src/api/spec/cassettes/Webui_Packages_JobHistoryController/GET_index/without_a_valid_architecture/should_redirect_to_package_binaries_path.yml
- src/api/spec/cassettes/Webui_Packages_JobHistoryController/GET_index/without_a_valid_respository/1_1_1_1.yml
- src/api/spec/cassettes/Webui_Packages_JobHistoryController/GET_index/without_a_valid_respository/1_1_1_2.yml
- src/api/spec/controllers/webui/packages/job_history_controller_spec.rb
- src/api/spec/helpers/webui/package_helper_spec.rb
- src/api/spec/models/package_spec.rb
Now we can see the history of build for a specific repository and architecture of a package :smiley: 
For this, we can access to the jobhistory view through binaries views of a package.
> [webui][api] Show jobhistory

- src/api/app/controllers/webui/package_controller.rb
- src/api/spec/cassettes/Webui_PackageController/POST_submit_request/sending_a_submit_request_without_target/1_1_4_2.yml
- src/api/spec/cassettes/Webui_PackageController/POST_submit_request/sending_a_submit_request_without_target/1_1_4_3.yml
- src/api/spec/cassettes/Webui_PackageController/POST_submit_request/sending_a_submit_request_without_target/creates_a_submit_request_with_correct_sourceupdate_attibute.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/test/unit/code_quality_test.rb
When the target project does not exist we can not redirect to it. In
that case we either redirect back or to the main page.
> [ci] Fix redirect when target project of submit request does not exist

- ReleaseNotes-2.9
- src/api/app/controllers/webui/projects/public_key_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/project/key_info.rb
- src/api/app/views/webui/project/show/_encryption_key_download_links.html.erb
- src/api/app/views/webui/projects/public_key/_key_dialog.html.erb
- src/api/config/routes.rb
To show extended key information to the user.
Not sure what to test here, `KeyInfo` maybe? Or the view?
> [webui] Introduces a GPG key dialog

- src/api/spec/controllers/webui/request_controller_spec.rb
Add test for action 'sourcediff' of 'request' controller.
> [ci] Add test for action sourcediff

- src/api/app/models/bs_request.rb
- src/api/app/models/history_element.rb
- src/api/spec/models/bs_request_spec.rb
- src/api/spec/models/history_element_spec.rb
> Add request HistoryElement for deleted state

- src/api/spec/cassettes/Requests/accept/can_add_submitter_as_maintainer.yml
This started to cause test failures
> [ci] Update VCR cassette

- src/api/app/models/branch_package.rb
- src/api/app/models/project.rb
- src/api/app/models/project_meta_file.rb
- src/api/spec/cassettes/Project/_branch_remote_repositories/kiwi_project/1_7_2_1.yml
- src/api/spec/cassettes/Project/_branch_remote_repositories/kiwi_project/1_7_2_2.yml
- src/api/spec/cassettes/Project/_branch_remote_repositories/kiwi_project/with_correct_path_links.yml
- src/api/spec/models/project_spec.rb
> Implement branching from remote project

- src/api/app/controllers/webui/request_controller.rb
> [webui] Revert index calculation for Request#show

- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_action_add_role.rb
- src/api/app/models/bs_request_action_change_devel.rb
- src/api/app/models/bs_request_action_delete.rb
- src/api/app/models/bs_request_action_group.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/app/models/bs_request_action_maintenance_release.rb
- src/api/app/models/bs_request_action_set_bugowner.rb
- src/api/app/models/bs_request_action_submit.rb
- src/api/app/models/package.rb
- src/api/app/models/project.rb
- src/api/db/migrate/20170509123922_add_references_to_bs_request_action.rb
- src/api/db/structure.sql
- src/api/spec/models/bs_request_action_spec.rb
for target_package, target_project and source_package and source_project.
To refactor code and improve ActiveRecord queries.
> [webui][api] Add references to BsRequestAction

- src/api/app/models/user.rb
- src/api/spec/models/user_spec.rb
and use ActiveRecord associations instead of BsRequest#collection.
> [webui][api] Refactor User#declined_requests

- src/api/app/controllers/webui/package_controller.rb
This method is only called from this class, so it should be private.
Also, `match?` (introduced in Ruby 2.4.0) is equivalent to `match` when `MatchData` is not used and it is faster.
:bowtie:
> [webui] Refactor package_controller#package_files

- Vagrantfile
This is to make it possible to use tools like MySQL workbench etc
> Forward MySQL port from vagrant box

- src/api/app/models/service.rb
Creating a git service by adding a git repo url in the package add file
view stopped working.
This re-enables it.
> [webui] Fix creating a git service via webui

- dist/Makefile
- dist/obs-server.spec
- dist/systemd/obsdeltastore.service
- src/backend/BSConfiguration.pm
- src/backend/BSStdServer.pm
- src/backend/BSUtil.pm
- src/backend/bs_deltastore
* new cli option --logfile
* new default values in BSConfiguration for bsdir and logdir
* parse @ARGV with Getopt::Long
* new BSStdServer::openlog to redirect STDOUT/STDERR to logfile
> [backend] refactoring bs_deltastore

- .rubocop.yml
- src/api/app/controllers/webui/kiwi/images_controller.rb
- src/api/app/controllers/webui/kiwi/repositories_controller.rb
- src/api/app/helpers/webui/package_helper.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/models/kiwi.rb
- src/api/app/models/kiwi/image.rb
- src/api/app/models/kiwi/repository.rb
- src/api/app/models/package.rb
- src/api/app/views/webui/kiwi/_tabs.html.erb
- src/api/app/views/webui/kiwi/repositories/_repository_entry.html.haml
- src/api/app/views/webui/kiwi/repositories/index.html.haml
- src/api/app/views/webui/package/show.html.erb
- src/api/config/feature.yml
- src/api/config/routes.rb
- src/api/db/migrate/20170412121601_create_kiwi_images.rb
- src/api/db/migrate/20170412121957_create_kiwi_repositories.rb
- src/api/db/migrate/20170511120355_add_image_reference_to_packages.rb
- src/api/db/migrate/20170516140442_add_several_fields_to_kiwi_repositories.rb
- src/api/db/structure.sql
- src/api/spec/models/kiwi/image_spec.rb
- src/api/spec/models/kiwi/repository_spec.rb
- src/api/spec/support/shared_contexts/a_kiwi_image_xml.rb
- src/api/spec/support/shared_contexts/an_invalid_kiwi_image_xml.rb
Mobprogrammed by: @Ana06, @eduardoj, @mdeniz and @DavidKang
> Kiwi Repository Editor: Display repository related data

- src/api/app/views/webui/kiwi/repositories/_repository_entry.html.haml
Fix username and password fields in repositories view.
Mobprogrammed by: @Ana06, @bgeuken, @eduardoj, @mdeniz and @DavidKang
> [webui] Fix username and password fields

- src/api/db/structure.sql
- src/api/lib/tasks/databases.rake
This commit drops all custom code except the removal of
AUTO_INCREMENT=*.
> [rake] Reduce code of custom rake task (db:structure:dump)

- dist/OBS-statistics.R
- src/api/lib/tasks/statistics/bs_requests.rake
- src/api/lib/tasks/statistics/current.rake
- src/api/lib/tasks/statistics/users.rake
Add rake tasks to take data from OBS database and a R file to paint graphs and calculate things such as correlations. :chart_with_upwards_trend: :1234: 
The OBS-statistics.R can be latter improved, but I think it is important that we have this in master already so we can easily generate/get some statistics and numbers. :bowtie:
> OBS numbers

- src/api/app/controllers/webui/project_controller.rb
do not show only "Internal error" with no further hint
> [webui] Handle exception

- src/api/lib/tasks/statistics/current.rake
Refactor this horrible code I introduced in https://github.com/openSUSE/open-build-service/pull/3148 :bowtie:
> Refactor current.rake task

- .rubocop.yml
- .rubocop_todo.yml
- dist/t/Gemfile
Enable Bundler/OrderedGems Rubocop cop and fix offenses. :bowtie:
> Enable Bundler/OrderedGems Rubocop cop

- src/api/app/views/webui/project/_form.html.erb
- src/api/app/views/webui/project/new_package.html.erb
> [webui] Add missing checkbox label tags for project/package settings

- src/api/app/controllers/webui/packages/build_reason_controller.rb
- src/api/app/helpers/webui/packages/build_reason_helper.rb
- src/api/app/models/build_reason_file.rb
- src/api/app/models/package.rb
- src/api/app/models/package_build_reason.rb
- src/api/app/views/webui/package/binaries.html.erb
- src/api/app/views/webui/packages/build_reason/index.html.haml
- src/api/config/routes.rb
- src/api/spec/cassettes/Webui_Packages_BuildReasonController/GET_index/for_valid_requests/has_build_reason.yml
- src/api/spec/cassettes/Webui_Packages_BuildReasonController/GET_index/for_valid_requests/responds_with_200_OK.yml
- src/api/spec/cassettes/Webui_Packages_BuildReasonController/GET_index/without_a_valid_architecture/1_1_2_1.yml
- src/api/spec/cassettes/Webui_Packages_BuildReasonController/GET_index/without_a_valid_architecture/should_redirect_to_package_binaries_path.yml
- src/api/spec/cassettes/Webui_Packages_BuildReasonController/GET_index/without_a_valid_respository/1_1_1_1.yml
- src/api/spec/cassettes/Webui_Packages_BuildReasonController/GET_index/without_a_valid_respository/1_1_1_2.yml
- src/api/spec/controllers/webui/packages/build_reason_controller_spec.rb
- src/api/spec/models/package_spec.rb
We'd like to show the user more details about the last scheduled build for his package.
> Create new package last build details page

- src/api/db/structure.sql
Adds a needed new empty line at the end of the file for our test
environment for testing migrations.
Pair programming with @bgeuken
> [api] Fix structure.sql file

- src/api/app/helpers/maintenance_helper.rb
- src/api/app/models/package.rb
- src/api/app/models/user.rb
Introduce the class method `User#current_login` to avoid code repetition and make `User#nobody_login` private, as now it is only used in the User class. :bowtie:
> [api] Introduce User#current_login

- dist/obs-server.spec
- src/api/app/models/user_ldap_strategy.rb
Hi, this is a proposed fix for the issue #3159
> Fix for issue https://github.com/openSUSE/open-build-service/issues/3159

- src/api/app/jobs/update_backend_infos.rb
- src/api/spec/cassettes/UpdateBackendInfos/properly_set/1_1_1.yml
- src/api/spec/cassettes/UpdateBackendInfos/properly_set/1_1_3.yml
- src/api/spec/jobs/update_backend_infos_spec.rb
BTW I refactored a little bit the UpdateBackendInfos class
> UpdateBackendInfos job spec

- src/api/app/models/bs_request.rb
- src/api/app/models/user.rb
- src/api/spec/models/user_spec.rb
- src/api/test/unit/code_quality_test.rb
> [webui][ci] Refactor User#requests

- src/api/app/mailers/event_mailer.rb
- src/api/app/views/event_mailer/_actions.text.erb
- src/api/app/views/event_mailer/branch_command.text.erb
- src/api/app/views/event_mailer/build_fail.text.erb
- src/api/app/views/event_mailer/build_success.text.erb
- src/api/app/views/event_mailer/comment_for_package.html.erb
- src/api/app/views/event_mailer/comment_for_package.text.erb
- src/api/app/views/event_mailer/comment_for_project.html.erb
- src/api/app/views/event_mailer/comment_for_project.text.erb
- src/api/app/views/event_mailer/comment_for_request.html.erb
- src/api/app/views/event_mailer/comment_for_request.text.erb
- src/api/app/views/event_mailer/commit.text.erb
- src/api/app/views/event_mailer/create_package.text.erb
- src/api/app/views/event_mailer/create_project.text.erb
- src/api/app/views/event_mailer/delete_package.text.erb
- src/api/app/views/event_mailer/delete_project.text.erb
- src/api/app/views/event_mailer/request_change.text.erb
- src/api/app/views/event_mailer/request_create.text.erb
- src/api/app/views/event_mailer/request_delete.text.erb
- src/api/app/views/event_mailer/request_statechange.text.erb
- src/api/app/views/event_mailer/review_wanted.text.erb
- src/api/app/views/event_mailer/update_package.text.erb
- src/api/app/views/event_mailer/update_project.text.erb
- src/api/app/views/event_mailer/update_project_config.text.erb
- src/api/app/views/event_mailer/upload.text.erb
- src/api/app/views/event_mailer/version_change.text.erb
... so that they can be re-used by other mailers (this is needed for the daily digest email).
> [webui][api] EventMailer views use local variables

- src/api/app/jobs/cleanup_events.rb
- src/api/test/models/event_test.rb
I fixed the existing tests and introduced one new test. Since @adrianschroeter requested to get it merged really fast, I took the work from @hennevogel over.
Original work was done by @hennevogel in #3322 
Closes #3322
> [frontend] Do not delete Events with unsent mails [tests fixed]

- src/api/app/models/event/comment.rb
- src/api/spec/mailers/event_mailer_spec.rb
- src/api/test/fixtures/event_mailer/project_comment
> [api][webui] Add commenter to mail notification header

- src/api/spec/helpers/webui/build_result_helper.rb
Add tests for `app/helpers/webui/buildresult_helper.rb`. :bowtie:
> [ci] Test buildresult_helper

- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_action_add_role.rb
- src/api/app/models/bs_request_action_change_devel.rb
- src/api/app/models/bs_request_action_delete.rb
- src/api/app/models/bs_request_action_group.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/app/models/bs_request_action_maintenance_release.rb
- src/api/app/models/bs_request_action_set_bugowner.rb
- src/api/app/models/bs_request_action_submit.rb
- src/api/db/migrate/20170630121602_add_index_bs_requests_action.rb
- src/api/db/structure.sql
We add again the indexes that were removed in the following PR
https://github.com/openSUSE/open-build-service/pull/3212
> [api] Add migration of BsRequestAction

- src/api/app/models/project.rb
by using the already adapted code in product model.
> [api] fix listing of new products via project expand

- .travis.yml
to have same version as in our vagrant setup and O:S:U.
> [ci] Update ruby to 2.4.1 for travis

- src/api/app/models/bs_request.rb
- src/api/app/models/project.rb
- src/api/spec/factories/bs_request_actions.rb
- src/api/spec/factories/bs_requests.rb
- src/api/spec/models/project_spec.rb
- src/api/test/fixtures/bs_request_actions.yml
- src/api/test/unit/code_quality_test.rb
Project#open_requests has been refactored to get rid of BsRequest.collection
> Refactor Project#open_requests

- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/review.rb
- src/api/app/models/user.rb
to use subselects to improve performance
> Refactor User#requests and User#incoming_requests

- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/relationship.rb
- src/api/app/models/review.rb
- src/api/app/models/user.rb
- src/api/app/views/layouts/webui/_personal_navigation.html.erb
- src/api/app/views/layouts/webui/webui.html.erb
- src/api/spec/models/bs_request_spec.rb
- src/api/spec/models/review_spec.rb
- src/api/test/fixtures/bs_request_actions.yml
- src/api/test/fixtures/reviews.yml
- src/api/test/unit/user_test.rb
- Use introduced ActiveRecord methods instead of BsRequest#collection
- Implemented proper caching instead of invalidating the cache every two minutes
- Renamed method to User#tasks
- Show tasks in the page title
> Refactor User#number_of_requests_that_need_work

- src/api/test/functional/webui/login_test.rb
- src/api/test/unit/binary_release.rb
- src/api/test/unit/package_test.rb
Pair programmed with: @mdeniz, @DavidKang and @eduardoj
> [webui] Remove not needed requires for 'faker'

- src/api/app/assets/javascripts/webui/application/requests_table.js
to go back to the first page again because staying on the same page on a reload does not make much sense.
> [webui] Remove reset_paginate option

- src/api/app/controllers/person_controller.rb
- src/api/app/controllers/request_controller.rb
- src/api/app/controllers/webui/request_controller.rb
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/models/user_ldap_strategy.rb
- src/api/lib/activexml/transport.rb
- src/api/lib/backend/connection.rb
- src/api/lib/tasks/statistics/github/code_frequency.rake
- src/api/lib/tasks/statistics/github/commit_activity.rake
- src/api/lib/tasks/statistics/github/issues.rake
- src/api/lib/tasks/statistics/github/pull_requests.rake
- src/api/test/unit/user_ldap_strategy_test.rb
Mobprogrammed with: @mdeniz, @DavidKang and @eduardoj
> Remove not needed requires

- src/api/app/controllers/webui/webui_controller.rb
> [webui] Fix redirect in WebuiController#require_login

- src/api/app/views/webui/kiwi/_tabs.html.erb
`-%>` is deprecated. :bowtie: 
Pair-programmed by @DavidKang and @Ana06.
> [webui] Replace -%> by %>

- src/api/app/views/layouts/webui/webui.html.erb
This partially reverts commit 41e5d2e093fbc0a0eaf7ea6b1581166568e818b8.
Fixes #3407
> Revert "[webui] Show user tasks in page title"

- src/api/app/models/issue_tracker.rb
So that we can more easily debug this error based on the response from github:
https://github.com/openSUSE/open-build-service/issues/3349
> [api] send more info to errbit when IssueTracker#parse_github_issue fails

- src/backend/bs_worker
> [backend] fix for new linux version format in bs_worker

- src/api/spec/cassettes/Webui_Kiwi_ImagesController/POST_update/with_invalid_package_empty_name/1_4_3_1.yml
- src/api/spec/cassettes/Webui_Kiwi_ImagesController/POST_update/with_invalid_package_empty_name/1_4_3_2.yml
- src/api/spec/cassettes/Webui_Kiwi_ImagesController/POST_update/with_valid_packages_data/1_4_4_1.yml
- src/api/spec/cassettes/Webui_Kiwi_ImagesController/POST_update/with_valid_packages_data/1_4_4_2.yml
- src/api/spec/cassettes/Webui_Kiwi_ImagesController/POST_update/with_valid_packages_data/1_4_4_3.yml
- src/api/spec/controllers/webui/kiwi/images_controller_spec.rb
- src/api/spec/factories/kiwi_package.rb
- src/api/spec/factories/kiwi_package_group.rb
Add controller tests missed in https://github.com/openSUSE/open-build-service/pull/3416 :bowtie: 
Mob-programmed by @DavidKang, @mdeniz and @Ana06.
> [ci] Test Kiwi::ImageController#update

- src/api/app/models/kiwi/repository.rb
- src/api/spec/models/kiwi/package_group_spec.rb
- src/api/spec/models/kiwi/package_spec.rb
- src/api/spec/models/kiwi/repository_spec.rb
BTW, small refactoring at **Kiwi::Repository** to use the **REPO_TYPES** array
> Add / Improve specs for some Kiwi models

- src/api/spec/models/kiwi/image_spec.rb
- src/api/spec/support/shared_contexts/a_kiwi_image_xml.rb
There was only one packages section for the kiwi images.
Pair-programmed by @mdeniz and @Ana06.
> [ci] Add extra packages section to Kiwi tests

- src/api/app/jobs/update_packages_if_dirty_job.rb
- src/api/app/models/backend_package.rb
- src/api/config/environments/test.rb
- src/api/spec/cassettes/BackendPackage/_refresh_dirty/1_1_1.yml
- src/api/spec/cassettes/UpdatePackagesIfDirtyJob/_perform/creates_a_BackendPackge_for_the_Package.yml
- src/api/spec/jobs/update_packages_if_dirty_job_spec.rb
- src/api/spec/models/backend_package_spec.rb
As part of https://trello.com/c/Tx9d3bUb/467-5-p4-event-system-change-delayed-jobs-to-be-created-with-activejobs
> [api] use ActiveJob for BackendPackage.refresh_dirty method

- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/models/bs_request.rb
- src/api/app/views/webui/request/show.html.erb
- src/api/config/locales/en.yml
- src/api/spec/features/webui/requests_spec.rb
> [webui] Do not show auto-accept when request is in final state

- src/api/app/jobs/package_update_if_dirty_job.rb
- src/api/app/models/package.rb
- src/api/spec/cassettes/Package/_delete_file/file_not_found/raises_NotFoundError.yml
- src/api/spec/cassettes/Package/_sources_changed/creates_a_BackendPackge_for_the_Package.yml
- src/api/spec/cassettes/Package/_sources_changed/queues_a_job.yml
- src/api/spec/cassettes/PackageUpdateIfDirtyJob/_perform/creates_a_BackendPackge_for_the_Package.yml
- src/api/spec/features/webui/packages_spec.rb
- src/api/spec/jobs/package_update_if_dirty_job_spec.rb
- src/api/spec/models/package_spec.rb
Part of this card: https://trello.com/c/Tx9d3bUb/467-5-p4-event-system-change-delayed-jobs-to-be-created-with-activejobs
> [api] Package#sources_changed uses ActiveJob

- src/api/app/jobs/issue_tracker_update_issues_job.rb
- src/api/app/jobs/issue_tracker_write_to_backend_job.rb
- src/api/app/models/issue_tracker.rb
- src/api/spec/cassettes/IssueTrackerUpdateIssuesJob/_perform/updates_the_issues.yml
- src/api/spec/cassettes/IssueTrackerWriteToBackendJob/_perform/writes_to_the_backend.yml
- src/api/spec/jobs/issue_tracker_update_issues_job_spec.rb
- src/api/spec/jobs/issue_tracker_write_to_backend_job_spec.rb
- src/api/spec/models/issue_tracker_spec.rb
Part of this card: https://trello.com/c/Tx9d3bUb/467-5-p4-event-system-change-delayed-jobs-to-be-created-with-activejobs
> [api] IssueTracker uses ActiveJob

- src/api/app/jobs/issue_tracker_fetch_issues_job.rb
- src/api/app/models/issue.rb
- src/api/spec/cassettes/IssueTrackerFetchIssuesJob/_perform/creates_a_BackendPackge_for_the_Package.yml
- src/api/spec/jobs/issue_tracker_fetch_issues_job_spec.rb
- src/api/spec/models/issue_spec.rb
Part of this card: https://trello.com/c/Tx9d3bUb/467-5-p4-event-system-change-delayed-jobs-to-be-created-with-activejobs
> [api] Issue#fetch_issues uses ActiveJob

- src/api/app/controllers/webui/kiwi/images_controller.rb
- src/api/app/policies/kiwi/image_policy.rb
- src/api/app/views/webui/package/show.html.erb
Restrict the users who can modify a kiwi image. :bowtie: 
Pair-programmed by @DavidKang and @Ana06.
> [api] Kiwi image permission

- src/api/app/models/kiwi/image.rb
- src/api/app/models/kiwi/package.rb
- src/api/app/models/kiwi/package_group.rb
- src/api/spec/factories/kiwi_package.rb
- src/api/spec/factories/kiwi_package_group.rb
- src/api/spec/models/kiwi/image_spec.rb
After editing the packages in the kiwi image, the changes are now written to the kiwi file.
Pair-programmed by @DavidKang and @Ana06.
> [webui] Write kiwi packages to file

- src/api/app/views/shared/_editor.html.haml
= is output, we want - otherwise the content gets printed to the view twice.
> [webui] Fix editor haml view

- src/api/app/assets/javascripts/webui/application/kiwi_editor.js
Because new repositories don't have order, so we add it via js.
@Ana06 and @DavidKang broke @mdeniz code :disappointed: 😭
> [webui] Add order to repository

- src/api/app/models/bs_request.rb
> [webui] Make it possible to search for package

- src/api/app/models/kiwi/repository.rb
- src/api/spec/models/kiwi/repository_spec.rb
When writing the changes from the kiwi image editor to the file, we
forgot some of the parameters.
Pair-programmed by @DavidKang and @Ana06.
> [webui] Add unstored kiwi parameters

- src/api/config/environments/test.rb
- src/api/config/initializers/airbrake.rb
This is useful for debugging CI failures you can not reproduce locally. CC @ChrisBr
> [ci] Make it possible to configure errbit for the test env

- src/api/app/models/user_ldap_strategy.rb
- src/api/spec/models/user_ldap_strategy_spec.rb
- src/api/spec/support/shared_contexts/setup_ldap_mock.rb
Part of this card:
https://trello.com/c/9kDKaI22/465-8-p1-improve-tests-for-ldap
> [ci] write tests for UserLdapStrategy.find_with_ldap

- src/api/spec/features/webui/login_spec.rb
https://trello.com/c/9kDKaI22/465-8-p1-improve-tests-for-ldap
> ldap login feature spec

- src/api/app/jobs/update_package_meta_job.rb
- src/api/spec/cassettes/UpdatePackageMetaJob/_perform/should_remove_BackendPackage_with_links_to_ids_is_nil_and_package_kind_is_patchinfo.yml
- src/api/spec/cassettes/UpdatePackageMetaJob/_scan_links/with_a_BranchPackage_that_does_have_an_entry_in_BackendPackage/1_3_1_1.yml
- src/api/spec/cassettes/UpdatePackageMetaJob/_scan_links/with_a_BranchPackage_that_doesn_t_have_an_entry_in_BackendPackage/1_3_2_1.yml
- src/api/spec/cassettes/UpdatePackageMetaJob/is_in_default_queue.yml
- src/api/spec/jobs/update_package_meta_job_spec.rb
This job updates the BackendPackage table, it will delete all the entries
with links_to_id at nil and update those which entries that have package_id
at nil, which is set as not null and primary in the schema, so it
not possible to happen.
> [ci] Add test for update_package_meta_job

- src/api/app/jobs/update_packages_if_dirty_job.rb
- src/api/spec/cassettes/UpdatePackagesIfDirtyJob/_perform/the_project_is_found/creates_a_BackendPackge_for_the_Package.yml
- src/api/spec/jobs/update_packages_if_dirty_job_spec.rb
Because otherwise it will raise ActiveRecordNotFoundError if the project
doesn't exist which is not what we want.
> [api] Use find_by instead of find in UpdatePackagesIfDirtyJob

- ReleaseNotes-2.8.3
- src/api/app/models/user_ldap_strategy.rb
- src/api/spec/features/webui/login_spec.rb
- src/api/spec/models/user_ldap_strategy_spec.rb
- src/api/spec/spec_helper.rb
- src/api/spec/support/shared_contexts/setup_ldap_mock.rb
- src/api/spec/support/shared_examples/a_ldap_connection.rb
Part of this card:
https://trello.com/c/9kDKaI22/465-8-p1-improve-tests-for-ldap
> [webui] backport LDAP authentication support to 2.8

- src/api/app/models/update_notification_events.rb
When an event from the backend is broken (e.g. invalid character like emjoi in commit message),
this job tries to create the event over and over again in an infinite loop.
The problem was that the rescue was outside of the loop.
This commit moved the rescue again inside the loop and partially reverts commit
2bee297917a01ece4f00804a1b581b9e04e563f9.
> [api][webui] Fix sending broken event over and over again

- src/api/app/assets/stylesheets/webui/application/dialog.scss
- src/api/app/views/shared/_package_branch_form.html.haml
- src/api/app/views/webui/package/_submit_request_dialog.html.haml
We added the same style in dialogs buttons.
> [webui] Change buttons style in dialogs

- src/api/app/models/comment.rb
> [frontend] Validate that body fits into DB

- src/api/spec/features/webui/projects_spec.rb
- src/api/test/functional/webui/package_create_test.rb
Fixes #3612
This drops a flickering test and replaces it with an rspec test.
> [ci] Replace flickering test by rspec test

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/models/package.rb
- src/api/app/views/webui/package/_submit_request_dialog.html.haml
- src/api/spec/cassettes/Package/_commit_message/of_a_package_with_more_than_one_changes_file/1_19_4_1.yml
- src/api/spec/cassettes/Package/_commit_message/of_a_package_without_a_changes_file/1_19_3_1.yml
- src/api/spec/cassettes/Package/_commit_message/with_a_diff_to_the_target_package_changes_file/1_19_1_1.yml
- src/api/spec/cassettes/Package/_commit_message/with_a_diff_to_the_target_package_changes_file/1_19_1_2.yml
- src/api/spec/cassettes/Package/_commit_message/with_a_diff_to_the_target_package_changes_file/1_19_1_3.yml
- src/api/spec/cassettes/Package/_commit_message/with_a_diff_to_the_target_package_changes_file/1_19_1_4.yml
- src/api/spec/cassettes/Package/_commit_message/with_a_diff_to_the_target_package_changes_file/1_19_1_5.yml
- src/api/spec/cassettes/Package/_commit_message/with_no_diff_to_the_target_package_changes_file/1_19_2_1.yml
- src/api/spec/cassettes/Package/_commit_message/with_no_diff_to_the_target_package_changes_file/1_19_2_2.yml
- src/api/spec/cassettes/Package/_commit_message/with_no_diff_to_the_target_package_changes_file/1_19_2_3.yml
- src/api/spec/cassettes/Package/_commit_message/with_no_diff_to_the_target_package_changes_file/1_19_2_4.yml
- src/api/spec/cassettes/Package/_commit_message/with_no_diff_to_the_target_package_changes_file/1_19_2_5.yml
- src/api/spec/cassettes/Webui_PackageController/GET_submit_request_dialog/1_19_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_submit_request_dialog/1_19_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_submit_request_dialog/1_19_3.yml
- src/api/spec/cassettes/Webui_PackageController/GET_submit_request_dialog/1_19_4.yml
- src/api/spec/cassettes/Webui_PackageController/GET_submit_request_dialog/1_19_5.yml
- src/api/spec/cassettes/Webui_PackageController/GET_submit_request_dialog/1_20_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_submit_request_dialog/1_20_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_submit_request_dialog/1_20_3.yml
- src/api/spec/cassettes/Webui_PackageController/GET_submit_request_dialog/1_20_4.yml
- src/api/spec/cassettes/Webui_PackageController/GET_submit_request_dialog/1_20_5.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/factories/packages.rb
- src/api/spec/models/package_spec.rb
> [webui] Add changes file diff to submit package description

- src/api/app/controllers/comments_controller.rb
- src/api/app/views/comments/index.xml.builder
- src/api/app/views/comments/show_package_comments.xml.builder
- src/api/app/views/comments/show_project_comments.xml.builder
- src/api/config/routes.rb
- src/api/spec/controllers/comments_controller_spec.rb
- src/api/test/functional/comments_controller_test.rb
- src/api/test/functional/maintenance_test.rb
- Refactor to get rid of unnecessary templates
- Implemented user route
- Implemented specs
- Renamed url parameter to reflect what it actually is
Part of #3618
> Refactor api comments

- src/api/test/test_helper.rb
> [ci] Trying fix flickering test in test_helper

- ReleaseNotes-2.9
- src/api/app/models/channel.rb
- src/api/app/models/project.rb
- src/api/app/models/repository.rb
- src/api/test/functional/source_controller_test.rb
- src/api/test/unit/code_quality_test.rb
Create a more likely working setup when path elements refer repositories
of the same project.
> [api] handle repository creation on branch for local references

- src/api/spec/controllers/statistics/maintenance_statistics_controller_spec.rb
In order to try and stop this test from intermittently failing due to
being unable to connect to the remote url.
Trying to fix: https://github.com/openSUSE/open-build-service/issues/3607
> [ci] Have static url for remote_project in spec & stub_request in before block

- src/api/app/assets/javascripts/webui/application/kiwi_editor.js
- src/api/app/assets/stylesheets/webui/application/kiwi_image.scss
- src/api/app/views/webui/kiwi/images/_package_fields.html.haml
- src/api/app/views/webui/kiwi/images/show.html.haml
If the package has an architecture defined, we show it next to the package name and we also have added a button to revert all the unsaved changes .
> [webui] Add architecture and revert button

- src/api/app/assets/javascripts/webui/application/kiwi_editor.js
- src/api/app/assets/stylesheets/webui/application/dialog.scss
- src/api/app/views/webui/kiwi/images/_package_fields.html.haml
- src/api/app/views/webui/kiwi/images/_repository_fields.html.haml
We added a cancel button to revert last changes.
> [webui] Add cancel button in dialog

- ReleaseNotes-2.8.3
- src/api/app/models/configuration.rb
Fixes failure on modifying filter rules via api
> [api] fix config change of some /configuration values

- src/api/app/controllers/person_controller.rb
- src/api/spec/controllers/person_controller_spec.rb
- src/api/test/unit/code_quality_test.rb
https://trello.com/c/ljYDOGC7/478-3-p1-drop-editing-ldap-user-accounts
> [ci][api] Disallow user password change in LDAP mode.

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/helpers/validation_helper.rb
- src/api/app/models/package_meta_file.rb
- src/api/lib/backend/api.rb
More work on this direction, added some more calls to the new class and some minor refactoring.
> Movin Backend::Connection calls to Backend::Api (part 2)

- src/api/app/models/project_log_entry.rb
This made the delayed job daemon crash. Fixes #3674
> [frontend] Fix additional info length

- ReleaseNotes-2.8.3
Add a note about the drop of editing user data in LDAP mode
(3fa216ffe9b54efc98d944265c4dec9b88e8abb).
> [doc] Update release notes for 2.8.3

- src/api/app/controllers/build/file_controller.rb
- src/api/app/models/directory.rb
- src/api/app/models/project_status/calculator.rb
- src/api/app/models/repository.rb
- src/api/app/models/service.rb
- src/api/app/models/update_notification_events.rb
- src/api/lib/backend/api.rb
More refactoring and moves of Backend::Connection calls to the Backend::Api
> Refactor Backend::Connection calls (part 4)

- src/api/spec/cassettes/Packages/log/download_logfile_succesfully.yml
- src/api/spec/cassettes/Packages/log/live_build_finishes_succesfully.yml
- src/api/spec/cassettes/Packages/triggering_package_rebuild/via_binaries_view.yml
- src/api/spec/cassettes/Packages/triggering_package_rebuild/via_live_build_log.yml
- src/api/spec/features/webui/packages_spec.rb
Add name and project parameters to repository factory to avoid modification of the cassettes.
Fix involved cassettes accordingly.
This change prevents modification of the cassettes when the test suite runs.
> [ci] Fix cassettes of package feature tests

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/models/package.rb
- src/api/config/routes.rb
- src/api/spec/controllers/webui/package_controller_spec.rb
This validates the length of package descriptions and shows an error message when it fails.
> Validate package description length

- src/api/app/controllers/webui/request_controller.rb
- src/api/spec/controllers/webui/request_controller_spec.rb
Validations can go wrong too, make sure everybody knows about it...
> [webui] Tell people about not forwarded requests

- src/api/app/controllers/request_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request/data_table/find_for_package_query.rb
- src/api/app/models/bs_request/data_table/find_for_project_query.rb
- src/api/app/models/bs_request/find_for/base.rb
- src/api/app/models/bs_request/find_for/group.rb
- src/api/app/models/bs_request/find_for/project.rb
- src/api/app/models/bs_request/find_for/query.rb
- src/api/app/models/bs_request/find_for/user.rb
- src/api/app/models/bs_request/find_for/user_group_mixin.rb
Refactoring to split the functionality into single classes.
> [api][webui] Move BsRequest.collection to own class

- src/api/app/models/project.rb
On multiple reuse of repositories in same project in the right order:
Current code will find the new created path again and again, so
we need a cycle detection here.
It would be possible to simplify the code a lot, if we just could update
a single entry instead, but we don't guarantee single entry for position
atm.
> [api] avoid an endless loop in special situations

- src/api/app/mixins/webui/load_buildresults.rb
- src/api/app/models/buildresult.rb
Fixes https://github.com/openSUSE/open-build-service/issues/3386
> [webui] Show outdated icon when the build result is dirty.

- src/api/spec/models/project_spec.rb
https://trello.com/c/wMupiONm/536-2-p10-app-mixins-hasrelationshipsrb
> [ci] test HasRelationships mixin.

- src/api/app/models/local_job_history.rb
- src/api/app/models/package.rb
- src/api/app/views/webui/packages/job_history/index.html.haml
- src/api/config/routes.rb
- src/api/spec/models/package_spec.rb
https://trello.com/c/PdwjNatu/531-2-p5-make-source-change-clickable
> [webui] Make "source change" a link in job history.

- ReleaseNotes-2.9
Added the changes introduced by
https://github.com/openSUSE/open-build-service/pull/3773
> [doc] Update Release Notes for Kiwi editor

- src/api/spec/rails_helper.rb
- src/api/spec/support/coverage.rb
We moved the simplecov setup at the top because is imperative.
Related to #3595
> [ci] Move coverage requirements at top

- dist/ci/travis_before_install.sh
Reverts openSUSE/open-build-service#3771
> Revert "[ci] Switch to a different mirror of our packages"

- src/api/app/models/bs_request_action_maintenance_incident.rb
This error made me (and some others) spend some time wondering what
was happening. This way the error message also gives a solution
to the problem.
> [api][webui] Improve error message to be more useful

- src/api/spec/mixins/build_log_support_spec.rb
Pair-programmed by @mdeniz and @eduardoj.
> [ci] Create RSpec Tests for BuilLogSupport mixins

- src/api/app/jobs/bs_request_action_webui_infos_job.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/event/request.rb
> [frontend] Skip diff generation if source is on remote

- src/api/app/assets/stylesheets/webui/application/our-own-jquery-ui.scss
Introduced in ca1c351f95bbf8f6b7ccf433dae0cd9611e6753a.
> [webui] Fix broken datatables on project#show

- src/api/app/jobs/package_update_if_dirty_job.rb
.find raises RecordNotFound, find_by not.
> [frontend] Do not raise when Package does not exist

- src/api/app/assets/javascripts/webui/application/kiwi_editor.js
- src/api/app/models/kiwi/image.rb
- src/api/app/models/kiwi/repository.rb
- src/api/app/views/webui/kiwi/images/show.html.haml
- src/api/spec/cassettes/Webui_Kiwi_ImagesController/POST_update/with_valid_repositories_data/without_use_project_repositories/1_3_2_1_1.yml
- src/api/spec/cassettes/Webui_Kiwi_ImagesController/POST_update/with_valid_repositories_data/without_use_project_repositories/1_3_2_1_2.yml
- src/api/spec/models/kiwi/image_spec.rb
- src/api/spec/models/kiwi/repository_spec.rb
It fixes #3830 and fixes #3829 
Also other bug not reported that caused a 500 when importing a non xml file content in a *.kiwi file
> Fix some bugs in the Kiwi editor

- contrib/test-airbrake
- src/backend/BSAirBrake.pm
- src/backend/BSRPC.pm
- src/backend/BSUtil.pm
> [backend] initial version of BSAirBrake

- src/api/app/models/user_ldap_strategy.rb
- src/api/spec/models/user_ldap_strategy_spec.rb
- src/api/test/unit/code_quality_test.rb
Fixes https://github.com/openSUSE/open-build-service/issues/3861
> [api][webui] LDAP retries when connection fails.

- dist/obs-server.spec
- src/api/config/crawler-user-agents.json
We used to continuously fetch the crawler-user-agents.json from
upstream. This recently started to cause build failures, because a new
Phantomjs bot got add to the config.
Since our test suite is using phantomsjs and we run the test suite
during the package build, this broke our builds.
This commit solves this by
* Stopping to fetch the config continuously and instead add the
crawler-user-agents.json file into our git repo
* Dropping the phantomjs entry from the configuration
> [dist][api] Update handling of user-agents config

- src/api/app/views/webui/image_templates/index.html.haml
Because people complain that the wrong template is first ;)
> [webui] get a defined order of templates

- src/api/app/assets/javascripts/webui/application/cm2/index.js
- src/api/app/assets/javascripts/webui/application/cm2/mode/dockerfile.js
- src/api/app/assets/javascripts/webui/application/cm2/mode/simple.js
- src/api/app/helpers/webui/package_helper.rb
- src/api/spec/helpers/webui/package_helper_spec.rb
also adds the simple mode the dockfile mode relies on.
> [webui] Enable Dockerfile mode for code mirror

- src/api/test/functional/webui/project_controller_test.rb
They change depending on the nokogiri version, input and moon phase...
> [ci] Do not test nokogiri validation line numbers

- src/api/app/models/groups_user.rb
> [webui] Add missing change in comments in groups_user model

- src/api/app/models/backend_info.rb
to use a attr_accessor like class method.
> [api] Refactor BackendInfo class

- src/api/app/controllers/webui/kiwi/images_controller.rb
- src/api/app/views/webui/kiwi/images/show.html.haml
We only show packages from first package groups with type image.
Related with PR #3888
> [webui] Show first package group with type `image`

- src/api/app/controllers/statistics_controller.rb
- src/api/app/controllers/webui/feeds_controller.rb
- src/api/app/controllers/webui/main_controller.rb
- src/api/lib/statistics_calculations.rb
- src/api/spec/lib/statistics_calculations_spec.rb
There is not used as a mixin and can be handled as a simple lib.
> [api][ci] Make statistics mixin a class

- src/api/spec/factories/event_subscriptions.rb
- src/api/spec/models/event_find_subscriptions_spec.rb
I add many more use cases for the class to the spec in order to get full
coverage and to better document the logic of the class.
> [ci] Improve EventFindSubscriptions model spec.

- src/api/app/models/attrib_value.rb
- src/api/spec/controllers/webui/attributes_spec.rb
- src/api/spec/factories/attrib_default_values.rb
- src/api/spec/factories/attrib_types.rb
- src/api/spec/factories/attrib_values.rb
- src/api/spec/factories/attribs.rb
- src/api/spec/features/webui/attributes_spec.rb
- src/api/spec/models/attrib_spec.rb
- src/api/spec/models/attrib_value_spec.rb
Supersedes https://github.com/openSUSE/open-build-service/pull/3923
> Specs for AttribValue model

- src/api/app/models/kiwi/image.rb
- src/api/spec/cassettes/Webui_Kiwi_ImagesController/GET_import_from_package/with_a_kiwi_file/with_multiple_package_groups/with_the_same_type/1_1_2_4_1_2.yml
- src/api/spec/cassettes/Webui_Kiwi_ImagesController/GET_import_from_package/with_a_kiwi_file/with_multiple_package_groups/with_the_same_type/redirect_to_package_view_file_path.yml
- src/api/spec/controllers/webui/kiwi/images_controller_spec.rb
- src/api/spec/support/shared_contexts/a_kiwi_image_xml.rb
- src/api/spec/support/shared_contexts/an_invalid_kiwi_image_xml.rb
We only allow package groups with different types in the same kiwi file.
> [webui][ci] Only allow different package groups

- src/api/app/models/project.rb
Sort local and remote image templates by name.
> [frontend] Sort local and remote image templates

- src/api/app/models/event/base.rb
- src/api/app/models/event/build.rb
- src/api/app/models/event/comment.rb
- src/api/app/models/event/request.rb
- src/api/app/models/event_subscription.rb
- src/api/app/views/webui/subscriptions/_subscriptions_form.html.haml
- src/api/spec/features/webui/notifications_spec.rb
- src/api/spec/models/event_subscription/find_for_event_spec.rb
- src/api/spec/models/event_subscription/generate_hash_for_subscriber_spec.rb
- src/api/test/models/event_test.rb
https://trello.com/c/9zrMSjfW/571-5-p7-watchlist-as-notification-filter
> [webui] Add notifications for projects in watchlist.

- src/api/app/views/webui/request/show.html.erb
> [webui] Only show superseded comment box if there are comments

- dist/setup_source_service_docker.sh
With this patch setup_source_service_docker.sh configures docker to take care of setup LV thinpool (new in docker since version 17.06)
> [dist] added install-docker-vg.sh to setup_source_service_docker.sh

- src/api/app/models/kiwi/image.rb
- src/api/app/models/kiwi/image/xml_builder.rb
- src/api/app/models/kiwi/image/xml_parser.rb
Move the contents of the build_from_xml method into its own class
using instance methods to seperate indiviudal units of work.
> [webui] Refactor Kiwi:Image.build_from_xml.

- CONTRIBUTING.md
Just found this on an etherpad :-)
> [dist] Add our definition of review

- src/api/app/jobs/issue_tracker_write_to_backend_job.rb
- src/api/app/jobs/update_package_meta_job.rb
- src/api/app/models/branch_package.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/app/models/bs_request_action_maintenance_release.rb
- src/api/app/models/bs_request_action_submit.rb
- src/api/lib/backend/api/build_results/binaries.rb
- src/api/lib/backend/api/issue_trackers.rb
- src/api/lib/backend/api/search.rb
- src/api/lib/backend/api/sources/package.rb
- src/api/lib/backend/api/sources/project.rb
- src/api/spec/jobs/issue_tracker_write_to_backend_job_spec.rb
Keep going with the moving of the Backend::Connection calls to its modules.
> Refactor backend connection calls 

- src/api/app/assets/stylesheets/webui/application/notifications.scss
- src/api/app/models/event/base.rb
- src/api/app/models/event_subscription.rb
- src/api/app/views/webui/subscriptions/_subscriptions_form.html.haml
- src/api/app/views/webui/subscriptions/index.html.haml
- src/api/app/views/webui/users/subscriptions/index.html.haml
- src/api/spec/features/webui/notifications_spec.rb
- src/api/spec/features/webui/users/users_notifications_settings_spec.rb
This is how is actually looks like:
This is how it will look like:
Top Part:
Bottom part:
> Improve notifications configuration page

- src/api/db/structure.sql
This table was removed accidentally in PR #4041
> [webui][api] Add missing table in structure.sql

- src/api/app/models/project.rb
- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/test/functional/source_controller_test.rb
> [webui] Handle not existing repositories in save_meta action

- src/api/app/models/project.rb
- src/api/spec/controllers/webui/project_controller_spec.rb
> Remove subprojects from autocomplete

- src/api/app/assets/javascripts/webui/application/package.js
- src/api/app/views/webui/packages/job_history/index.html.haml
Fix sorting in job history table:
- Disable sorting in first (Revision) and last column.
- Enable sorting by default with "Time" column, descending.
- fix sorting by "Time" column.
- Also fix sorting in "Build time" column.
- Prevent searching for the introduced hidden columns with no formatted
data.
- Minor code styling changes.
This should fix #3986.
> [webui] Fix sorting in job history table

- src/api/spec/controllers/webui/comments_controller_spec.rb
* combined two `before do` blocks
Together with @alexandergraul and @eduardoj
> [ci] Refactor comments_controller_spec.rb

- src/api/app/assets/javascripts/webui/application/kiwi_editor.js
- src/api/app/assets/javascripts/webui/application/project.js
- src/api/app/assets/javascripts/webui/application/request.js
- src/api/app/assets/stylesheets/webui/application/style.scss
- src/api/app/views/shared/_add_group.html.haml
- src/api/app/views/shared/_add_user.html.haml
- src/api/app/views/webui/patchinfo/_form.html.haml
- src/api/app/views/webui/project/_add_maintained_project_dialog.html.erb
- src/api/app/views/webui/project/new_package_branch.html.erb
- src/api/app/views/webui/request/_change_devel_request_dialog.html.erb
- src/api/app/views/webui/request/_set_bugowner_request_dialog.html.erb
- src/api/app/views/webui/request/_set_incident_dialog.html.erb
Using a CSS class that add a background spinner on the right side of the
input
> Add spinners in every autocomplete input

- src/api/app/models/download_repository.rb
- src/api/app/models/flag.rb
- src/api/app/models/group.rb
- src/api/app/models/kiwi/image.rb
- src/api/app/models/kiwi/repository.rb
- src/api/app/models/remote_project.rb
- src/api/app/models/repository.rb
- src/api/app/models/review.rb
- src/api/app/models/role.rb
- src/api/app/models/static_permission.rb
- src/api/app/models/unregistered_user.rb
- src/api/app/models/user.rb
- src/api/spec/controllers/webui/groups_controller_spec.rb
- src/api/spec/controllers/webui/kiwi/images_controller_spec.rb
- src/api/spec/controllers/webui/user_controller_spec.rb
- src/api/spec/models/download_repository_spec.rb
- src/api/spec/models/group_spec.rb
- src/api/spec/models/kiwi/image_spec.rb
- src/api/spec/models/repository_spec.rb
- src/api/spec/models/review_spec.rb
- src/api/spec/models/role_spec.rb
- src/api/spec/models/user_spec.rb
- src/api/test/unit/flag_test.rb
The old error message can be seen in #2868
Here is how the new one would look like:
> Fix Issue 2868

- src/api/app/assets/stylesheets/webui/application/dialog.scss
Now all the buttons have the same style and font-family.
> [webui] Fix dialog buttons

- src/api/app/controllers/webui/feeds_controller.rb
- src/api/config/routes.rb
- Rss format was tested in the controller. Now the format is tested in the routes configuration.
Pair-programmed with @mdeniz.
This should fix #3990.
> Test rss format in the routes config

- src/api/app/controllers/webui/project_controller.rb
- src/api/app/views/webui/project/edit.html.erb
- src/api/app/views/webui/project/show.html.erb
> [webui] add project URL editing

- src/api/app/jobs/consistency_check_job.rb
- src/api/lib/backend/api/sources/package.rb
- src/api/lib/backend/api/sources/project.rb
Keep moving Backend::Connection calls to the lib
> Refactor Backend::Connection calls

- src/api/app/models/bs_request.rb
- src/api/app/models/review.rb
- src/api/spec/models/review_spec.rb
This wraps some review related code of the request model into a method
and moves it to the review model.
> [frontend] DRY request code by moving it to review model

- .rubocop_todo.yml
- src/api/app/controllers/request_controller.rb
- src/api/app/helpers/webui/main_helper.rb
- src/api/app/models/bs_request_permission_check.rb
- src/api/app/models/event/base.rb
- src/api/app/models/user.rb
- src/api/lib/api_exception.rb
- src/api/lib/xpath_engine.rb
- src/api/test/activexml_matcher.rb
@openSUSE/open-build-service Please review
The affected cops are:
* http://rubocop.readthedocs.io/en/latest/cops_lint/#lintemptywhen
* http://rubocop.readthedocs.io/en/latest/cops_lint/#lintunderscoreprefixedvariablename
> Rubocop - Lint

- src/api/spec/models/review_spec.rb
Replaces @DavidKang  and @bgeuken  commit to fix this yet
> Fix BracesAroundHashParameters offenses

- src/api/app/views/shared/_repositories_flag_table_column.html.haml
This pull request replaces #4150, testsuite was hopefully fixed with #4284.
> [webui] allow enable and disable to be set for a default flag

- src/api/app/models/bs_request.rb
This should fix #4299.
Mobprogrammed with @mdeniz and @DavidKang.
> [webui] Fix retrive of show in sourcediff files

- dist/clouduploader.rb
this is the initial prototype which gets called by the backend.
> [backend] Initial cloud uploader backend script

- src/api/app/assets/javascripts/webui/application/upload_jobs.js
- src/api/app/models/cloud/backend/upload_job.rb
- src/api/app/views/webui/cloud/upload_jobs/index.html.haml
- src/api/spec/models/cloud/backend/upload_job_spec.rb
and add the created at timestamp to it!
> Fix UploadJob index page ordering

- docs/api/api/api.txt
- src/api/app/controllers/source_controller.rb
Just hand it to the backend, functionality is already tested in maintenance
> [api] enable support for withvrev copy

- src/api/script/import_database.rb
Now it uses the host specified in the config so we can use it in docker.
Get rid of the vagrant part.
> Modify script to download and import the db backup

- src/api/lib/backend/api/cloud.rb
- src/api/spec/controllers/webui/cloud/upload_jobs_controller_spec.rb
it is cmd and not call as params and not POST data.
> [webui] Fix Backend::Api::Cloud.destroy backend call

- .rubocop_todo.yml
- src/api/app/controllers/statistics_controller.rb
- src/api/app/controllers/webui/patchinfo_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/helpers/flag_helper.rb
- src/api/app/jobs/project_create_auto_cleanup_requests.rb
- src/api/app/mixins/has_relationships.rb
- src/api/app/models/owner.rb
- src/api/spec/features/webui/projects_spec.rb
- src/api/spec/models/repository_spec.rb
- src/api/test/unit/issue_test.rb
- src/api/test/unit/user_test.rb
This offenses were auto-corrected
> Fix Layout/MultilineMethodCallIndentation offenses

- src/api/lib/backend/api/cloud.rb
- src/api/spec/cassettes/Webui_Cloud_UploadJob_LogsController/_show/with_cloud_upload_feature_enabled/with_an_EC2_configuration/and_an_upload_job/1_1_1_2_1_1.yml
- src/api/spec/cassettes/Webui_Cloud_UploadJob_LogsController/_show/with_cloud_upload_feature_enabled/with_an_EC2_configuration/and_an_upload_job/1_1_1_2_1_2.yml
- src/api/spec/controllers/webui/cloud/ec2/upload_job/logs_controller_spec.rb
Otherwise it won't stream the log file.
> [webui] Fix Backend::Api::Cloud.log to use nostream and start parameters

- Dockerfile.old_test_suite
- contrib/start_old_tests
- docker-compose.ci_old.yml
Prevent the old_test_suite docker image from modifying the working directory.
Pairprogrammed with @DavidKang.
> [dist] Improve the old_test_suite docker image

- src/api/app/jobs/cleanup_events.rb
I think there is no real need for a transaction or a lock. 🤔
> [frontend] Remove transaction in CleanupEvents

- .rubocop_todo.yml
- src/api/app/models/attrib_namespace.rb
- src/api/app/models/attrib_type.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_permission_check.rb
- src/api/app/models/flag.rb
- src/api/app/models/owner.rb
- src/api/app/models/project.rb
- src/api/lib/activexml/transport.rb
- src/api/lib/api_exception.rb
- src/api/lib/memory_debugger.rb
- src/api/lib/memory_dumper.rb
- src/api/lib/opensuse/permission.rb
- src/api/lib/xpath_engine.rb
- src/api/test/functional/build_controller_test.rb
- src/api/test/functional/source_controller_test.rb
- src/api/test/functional/webui/spider_test.rb
- src/api/test/functional/zzz_post_consistency_test.rb
- src/api/test/unit/schema_test.rb
@openSUSE/open-build-service Please review
The affected cops are:
* http://rubocop.readthedocs.io/en/latest/cops_style/#styleredundantexception
* http://rubocop.readthedocs.io/en/latest/cops_style/#styleredundantparentheses
* http://rubocop.readthedocs.io/en/latest/cops_style/#stylesemicolon
* http://rubocop.readthedocs.io/en/latest/cops_style/#stylespecialglobalvars
* http://rubocop.readthedocs.io/en/latest/cops_style/#stylestderrputs
> Rubocop friendly cops - Part 12

- .rubocop_todo.yml
- src/api/app/controllers/source_controller.rb
- src/api/app/controllers/statistics_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/controllers/webui/patchinfo_controller.rb
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/models/branch_package.rb
- src/api/app/models/bs_request/find_for/project.rb
- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_action_maintenance_incident.rb
- src/api/app/models/bs_request_action_maintenance_release.rb
- src/api/app/models/bs_request_permission_check.rb
- src/api/app/models/buildresult.rb
- src/api/app/models/package.rb
- src/api/app/models/patchinfo.rb
- src/api/app/models/project.rb
- src/api/app/models/user_ldap_strategy.rb
- src/api/lib/activexml/transport.rb
- src/api/lib/authenticator.rb
- src/api/lib/tasks/databases.rake
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/spec/features/webui/login_spec.rb
- src/api/spec/helpers/webui/build_result_helper.rb
- src/api/spec/helpers/webui/webui_helper_spec.rb
- src/api/spec/lib/authenticator_spec.rb
- src/api/spec/models/kiwi/repository_spec.rb
- src/api/spec/models/package_spec.rb
@openSUSE/open-build-service Please review
The affected cop is:
* http://rubocop.readthedocs.io/en/latest/cops_style/#stylelineendconcatenation
> Rubocop - Fix Style/LineEndConcatenation offenses

- src/api/app/views/webui/cloud/ec2/configurations/show.html.haml
* Add label element for input field
* Add margin to elements
Before:
After:
> [frontend] Update styling of ARN input field

- src/api/app/views/webui/cloud/upload_jobs/index.html.haml
which got removed in refactoring.
> [webui] Fix s/platform/target

- src/api/lib/xpath_engine.rb
happens with inconsitent utf8 encodings in database
This should resolve #4341
> [api] fix 500 on binary release search

- .rubocop.yml
- src/api/app/models/event_subscription.rb
- src/api/app/models/kiwi/description.rb
- src/api/app/models/kiwi/package_group.rb
- src/api/app/models/kiwi/preference.rb
Thoses offenses were auto-corrected.
> [frontend] Fix Style/String Array offenses

- src/api/app/controllers/webui/package_controller.rb
> [webui] Fix package rdiff

- dist/stable_project_meta.xml.example
- dist/staging_project_meta.xml.example
We make use of the while releasing new major versions. See
https://github.com/openSUSE/open-build-service/wiki/OBS-Major-Release-HOWTO
> [dist] Adds examples for stable/staging meta files

- src/api/app/controllers/webui/package_controller.rb
> [frontend] catch ActiveXML::Transport::Error

- src/api/lib/authenticator.rb
- src/api/spec/lib/authenticator_spec.rb
Adds a test for proxy mode when registration is disabled.
> [frontend] Add rspec test for authenticator class

- src/api/app/controllers/webui/user_controller.rb
- src/api/app/models/unregistered_user.rb
- src/api/app/models/user.rb
- src/api/app/views/shared/_sign_up.html.haml
- src/api/spec/features/webui/sign_up_spec.rb
> Registration confirmation fields

- dist/schedule-obs.sh
Improve regular expression to allow the retrieval of images files ending in 'alpha' or 'beta'.
> [dist] Retrieve beta versions of images

- dist/ec2utils.conf.example
- dist/obs-server.spec
Creation of a sub-package with all the tools needed to upload images to the cloud. 
Pair-programming with: @bgeuken
> [dist] Create obs-cloud-uploader subpackage

- src/api/app/models/issue_tracker.rb
> [webui] Catch Errno::ECONNRESET exception in issue tracker

- ReleaseNotes-2.9
> Add features to release notes

- ReleaseNotes-2.9
Collecting some more new features & changes.
> [dist] Add more features to release notes

- src/api/lib/pretty_nested_errors/key_and_messages_parser.rb
- src/api/spec/lib/pretty_nested_errors_spec.rb
- src/api/spec/models/kiwi/image_spec.rb
Before PrettyNestedErrors only worked for nested associations which are
2 levels deep, now it can work for n-levels deep.
> [webui] Make PrettyNestedErrors work for n-level associations.

- .dockerignore
- Dockerfile.42.3
- Dockerfile.backend
- Dockerfile.frontend-base
- Dockerfile.mariadb
- Dockerfile.memcached
- Dockerfile.old-test-suite
* Remove some workarounds needed for previously not fixed bugs
* Add a dockerignore file to reduce build context size
* Layer existing docker files to reduce duplicated commands
> Docker refactoring

- docs/api/api/api.txt
- src/api/app/controllers/build_controller.rb
- src/api/app/models/package.rb
- src/backend/bs_repserver
- src/backend/bs_srcserver
- src/backend/bs_worker
Needed for kernel people in first place
No test case atm since you would need a running KVM build
> [api][backend] allow to send sysrq to running jobs for maintainers

- src/api/app/mixins/webui/manage_relationships.rb
- src/api/app/models/relationship.rb
- src/api/spec/cassettes/Projects/behaves_like_user_tab/user_roles/Remove_non_existant_role.yml
- src/api/spec/controllers/webui/project_controller_spec.rb
- src/api/spec/models/relationship_spec.rb
Some cleanup was made and also some fixes. Added specs for the `Relationship` model that cover the `add_group` and the `add_user` methods.
> Extend tests for user and group administration for projects and packages

- src/api/app/controllers/webui/repositories_controller.rb
* old code did not handle the fact when a package was in multiple
cycles and did not show these cycles at all.
* new code still tries to find groups, but ensures that all packages got listed
some code is enabled in test mode only. Not so useful there because it
only makes sense with larger cycle information, but I want to keep
the code for debugging purposes.
> [webui] fix repository cycle view

- src/api/app/models/event_subscription.rb
> [frontend] Fix typo: Mantainer -> Maintainer

- dist/setup_source_service_docker.sh
not the final solution, but one step forward
> [dist] docker image for source service configurable

- src/api/spec/features/webui/requests_spec.rb
I'm tired of this flickering test. Skip it until someone fixes this
weird test and/or feature...
> [ci] Skip flickering request spec

- dist/ci/travis_after_failure.sh
https://transfer.sh/ is a free, public, awesome service to share files
> [ci] Use transfer.sh to share logs

- src/api/app/assets/javascripts/webui/application/comment.js
- src/api/app/assets/javascripts/webui/application/kiwi_editor.js
- src/api/app/assets/javascripts/webui/application/request.js
Use === instead of ==. The == and != operator are not only comparing two
values. But also trying to convert the variable on the right side, if their
types are not identical. This can be quite a complex logic due to the
various combinations[*] that are possible.
To simplify things and avoid confusion for people that are js experts,
who is?, it's better to stick with ===.
[*] https://dorey.github.io/JavaScript-Equality-Table/
> [frontend] Update javascript style: equality operator

- src/api/app/assets/stylesheets/webui/application/package.scss
> [webui] Fixes to display of binary sources

- dist/clouduploader.rb
The subnet id was added to the wrong command. This should fix it.
Caused by 6197835f954ddc52abe3352a6594911ee02acd89
> [backend] Fix vpc subnet handling in cloud uploader script

- docker-compose.yml
- docker-files/base/docker-bootstrap.sh
- src/api/Dockerfile.frontend-base
- src/api/Procfile
- src/api/app/models/configuration.rb
- src/api/app/models/linked_project.rb
- src/api/config/environments/development.rb
- src/api/db/migrate/20180221175514_change_configuration_obs_url_default.rb
- src/api/db/structure.sql
> Introduces mailcatcher into development mode

- src/api/db/migrate/20180221175514_change_configuration_obs_url_default.rb
> [frontend] Fix rollback of migration 20180221175514

- src/api/app/models/bs_request.rb
Knowing when a review is finished is important for people. Fixes #4131
> [frontend] Send new->review & review->new notifications

- dist/clouduploader.rb
there are sometimes two whitespaces
> [backend] Update details RegEx for EC2 upload

- src/api/app/models/bs_request.rb
This reverts commit 723731704d751a6fb893e076db667c6b449604c4.
See discussions in
* https://github.com/openSUSE/open-build-service/pull/4565
* https://github.com/openSUSE/open-build-service/issues/4131
> Revert "[frontend] Send new->review & review->new notifications"

- dist/README.UPDATERS
Update README.UPDATERS according to recent feedback from users that
tested our RC 1 release.
> [frontend] Update README.UPDATERS

- src/api/app/assets/stylesheets/webui/application/dialog.scss
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/models/branch_package.rb
- src/api/app/views/shared/_package_branch_form.html.haml
- src/api/app/views/webui/package/_branch_dialog.html.erb
- src/api/app/views/webui/project/new_package_branch.html.erb
- src/api/spec/cassettes/Packages/branching_a_package_from_another_users_project/with_AutoCleanup.yml
- src/api/spec/cassettes/Packages/branching_a_package_from_another_users_project/without_AutoCleanup.yml
- src/api/spec/features/webui/maintenance_workflow_spec.rb
- src/api/spec/features/webui/packages_spec.rb
- src/api/spec/features/webui/projects_spec.rb
> [webui] add branch destination project field

- dist/clouduploader.rb
We used the wrong directory to store the result file. Now the backend will pass the path of the result file as an argument so we also don't need to parse the ID out of the filename.
> [backend] Pass result file path as argument to clouduploader

- dist/README.UPDATERS
Spotted by one of our users:-)
> [doc] Fix url in ../../dist/README.UPDATERS

- src/api/.jshintrc
- src/api/app/assets/javascripts/webui/application/kiwi_editor.js
- src/api/app/assets/javascripts/webui/application/package.js
- src/api/app/assets/javascripts/webui/application/project.js
- src/api/app/assets/javascripts/webui/application/request.js
- src/api/app/controllers/webui/kiwi/images_controller.rb
- src/api/app/views/webui/kiwi/images/edit.html.haml
- src/api/app/views/webui/project/list.html.erb
- src/api/app/views/webui/project/subprojects.html.haml
- src/api/app/views/webui/user/show.html.haml
- src/api/spec/models/branch_package_spec.rb
This rule complains about any undefined js varaible. This helps to
prevent having global variables (leaks).
> [ci] Add jshint rule: undef & camelcase

- SUPPORT.md
Linked when creating the first PR in Github. :bowtie: :green_heart: 
Closes https://github.com/openSUSE/open-build-service/issues/4486.
> [doc] Add SUPPORT file

- src/api/app/controllers/webui/package_controller.rb
- src/api/spec/controllers/webui/package_controller_spec.rb
> Make rpmlint log downloadable

- src/api/app/controllers/webui/attribute_controller.rb
- src/api/app/controllers/webui/main_controller.rb
- src/api/app/controllers/webui/monitor_controller.rb
- src/api/app/controllers/webui/patchinfo_controller.rb
- src/api/app/views/webui/main/_delete_message_dialog.html.haml
- src/api/app/views/webui/monitor/_events.html.haml
- src/api/app/views/webui/patchinfo/_form.html.haml
- src/api/config/routes.rb
Refactor `Webui::AttributeController`, `Webui::MainController`, `Webui::PatchinfoController`, and `Webui::MonitorController`.
> Refactor Webui controller, part 4

- src/api/app/controllers/person_controller.rb
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/models/configuration.rb
- src/api/app/models/unregistered_user.rb
- src/api/app/models/user.rb
- src/api/app/views/models/_user.xml.builder
- src/api/app/views/webui/user/_dropdown_menu.html.haml
- src/api/app/views/webui/user/edit.html.haml
- src/api/app/views/webui/user/index.html.haml
- src/api/app/views/webui/user/show.html.haml
- src/api/db/migrate/20180307074538_add_local_user_flag.rb
- src/api/db/structure.sql
- src/api/spec/controllers/person_controller_spec.rb
- src/api/spec/controllers/webui/user_controller_spec.rb
- src/api/spec/models/configuration_spec.rb
- src/api/spec/models/user_spec.rb
User index page (only visible for admins):
Dropdown menu (part of the index page):
User edit page (admin view):
> Allow local users in LDAP mode

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/views/shared/_repositories_flag_table.html.haml
- src/api/app/views/webui/cloud/upload_jobs/index.html.haml
- src/api/app/views/webui/kiwi/images/_build_status.html.erb
- src/api/app/views/webui/package/_buildstatus.html.erb
- src/api/app/views/webui/package/binaries.html.erb
- src/api/app/views/webui/package/binary.html.erb
- src/api/app/views/webui/package/dependency.html.erb
- src/api/app/views/webui/package/statistics.html.erb
- src/api/app/views/webui/packages/build_reason/index.html.haml
- src/api/config/routes.rb
- src/api/spec/cassettes/Webui_PackageController/POST_trigger_rebuild/when_triggering_a_rebuild_fails/lets_the_user_know_there_was_an_error.yml
- src/api/spec/cassettes/Webui_PackageController/POST_trigger_rebuild/when_triggering_a_rebuild_fails/redirects_to_the_package_binaries_path.yml
- src/api/spec/cassettes/Webui_PackageController/POST_wipe_binaries/when_wiping_binaries_fails/1_16_1_2.yml
- src/api/spec/cassettes/Webui_PackageController/POST_wipe_binaries/when_wiping_binaries_fails/lets_the_user_know_there_was_an_error.yml
- src/api/spec/cassettes/Webui_PackageController/POST_wipe_binaries/when_wiping_binaries_fails/redirects_to_package_binaries.yml
- src/api/spec/cassettes/Webui_PackageController/POST_wipe_binaries/when_wiping_binaries_succeeds/1_16_2_1.yml
- src/api/spec/cassettes/Webui_PackageController/POST_wipe_binaries/when_wiping_binaries_succeeds/1_16_2_2.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
Mob-programmed with @Ana06, @DavidKang and @mdeniz.
> Remove required_parameters from Package Controller

- .gitignore
- dist/obs-server.spec
- docs/api/api/about.xml
- docs/api/api/about.xsd
- src/api/app/controllers/about_controller.rb
- src/api/app/views/about/index.xml.builder
I'm not only interested in the last git revision but also on the last deployment date.
Let me know if you have other / better idea how to do that, I'm open to suggestions!
> [api] Show date of last deployment

- src/api/app/views/webui/package/dependency.html.erb
In the process we remove accidentaly the action binary.
> [webui] Fix breadcrumb

- src/api/app/controllers/webui/package_controller.rb
it is architecture and not arch.
> [webui] Fix rpmlint action

- src/api/spec/features/webui/requests_spec.rb
Follow up of 2e73b4a269731267d262d2c8d0334dc2154bec1d
> [frontend] Fix failed attempt to skip a test

- src/api/app/views/webui/user/_dropdown_menu.html.haml
Such users are already "local users".
Fixes #4678
> [frontend] Hide "Make user local" link when ignore_auth_services is true

- src/api/app/assets/javascripts/webui/application/bento/script.js
- src/api/app/assets/stylesheets/webui/application/bento/base.scss
Co-authored-by: Stefan Knorr <sknorr@suse.de>
> [webui] Make login form clearly distinguishable from search form.

- src/api/config/environments/test.rb
to be as close as possible to production.
> [ci] Enable eager_load for tests

- src/api/script/api_test_in_spec.sh
- src/api/script/update_bento.sh
* Remove empty fixtures
* Run asset precompilation only once (not for each test suite)
* Add missing shebang to script
> Cleanup package builds a bit

- src/api/spec/rails_helper.rb
as it is recommended in the docs to get accurate results
> [ci] Move require simplecov to the top of file

- src/api/app/controllers/webui/user_controller.rb
- src/api/app/models/user.rb
- src/api/spec/controllers/webui/user_controller_spec.rb
- src/api/spec/models/user_spec.rb
* Moved out code from controller to User model
* Remove User call from self.autocomplete method
* Moved code to its own scope and changed rspec match strategy for autocomplete
* Refactored autocomplete method and tests
> refactored list_users method

- src/api/spec/cassettes/Webui_PackageController/POST_branch/shows_an_error_if_current_revision_parameter_is_provided_but_there_wasn_t_any_revision_before.yml
- src/api/spec/cassettes/Webui_PackageController/POST_branch/with_currrent_revision_parameter/1_4_8_1.yml
- src/api/spec/cassettes/Webui_PackageController/POST_branch/with_currrent_revision_parameter/redirects_to_the_branched_package.yml
- src/api/spec/cassettes/Webui_PackageController/POST_branch/with_target_package_name/1_4_7_1.yml
- src/api/spec/cassettes/Webui_PackageController/POST_branch/with_target_package_name/redirects_to_the_branched_package.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
The following tests were added:
- Change of revision.
- Change of package name.
> [webui][ci] Add missing tests for action 'branch' in controller Webui::PackageController

- src/api/app/assets/stylesheets/webui/application/project.scss
- src/api/app/controllers/webui/project_controller.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/models/project_log_entry.rb
- src/api/app/views/webui/project/_tabs.html.erb
- src/api/app/views/webui/project/pulse.html.haml
- src/api/config/routes.rb
- src/api/db/data/20180214132015_project_log_entry_user_name.rb
If you just want to check what happened project wide in the last couple of
hours to find the cause of some problem. There is already the RSS feed of this
but it's harder to skim than a nice *cough* web view.
> Introduces ProjectLogEntry view

- src/api/app/controllers/cloud/upload_jobs_controller.rb
- src/api/config/routes.rb
- src/api/spec/controllers/cloud/upload_jobs_controller_spec.rb
Add API route that allows to abort cloud upload jobs.
> [frontend] Abort cloud uploads via API

- src/api/spec/helpers/webui/webui_helper_spec.rb
Give the test a little time so it does not jump to 4 hrs
> [ci] fix failing fuzzy time test

- src/api/spec/helpers/webui/webui_helper_spec.rb
Freeze time to avoid race condition.
Fixes #4619
> [frontend] Fix flickering test

- src/api/db/data/20180214132015_project_log_entry_user_name.rb
- src/api/spec/db/data/project_log_entry_user_name.rb
- src/api/spec/factories/project_log_entry.rb
The migration did not work. Let's test this so it won't happen again.
@openSUSE/open-build-service frontend peepz. please have a look at the data migration test, as it's the first one we did...
> Fix ProjectLogEntryUserName migration

- src/api/app/assets/javascripts/webui/application/project.js
This broke with a439c3e6a5bfa181bfda5eb5f29e16ca8197838a
Fixes #4740
> [frontend] Fix expert mode for adding repositories

- src/api/app/views/webui/patchinfo/_form.html.haml
This broke with 0a90a75265b391ef2bf5199954666dedc995090a
Fixes #4764
> [frontend] Fix adding issues to patchinfo

- src/api/db/data/20170306084550_remove_duplicate_repositories.rb
- src/api/spec/db/data/remove_duplicate_repositories_spec.rb
@Ana06 this implements your feedback, please review!
> Additions to RemoveDuplicateRepositories migration

- src/api/app/jobs/consistency_check_job.rb
- src/api/app/mailers/admin_mailer.rb
should go to 2.9 branch as well
> Fix consistency check crash

- ReleaseNotes-2.9.2
- src/api/app/jobs/consistency_check_job.rb
- src/api/app/mailers/admin_mailer.rb
- src/api/db/data/20170306084550_remove_duplicate_repositories.rb
- src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb
- src/api/spec/db/data/remove_duplicate_repositories_spec.rb
- src/api/spec/support/database_cleaner.rb
Fix #4761.
Cherry picked from master
https://github.com/openSUSE/open-build-service/pull/4800
> Fix duplicate repositories migration for 2.9

- src/api/app/controllers/group_controller.rb
- src/api/app/models/group.rb
Superseded https://github.com/openSUSE/open-build-service/pull/4707
> Order groups alphabetically 

- src/api/app/views/event_mailer/_set_bugowner_action.text.erb
> [frontend] Fix event mailer template

- src/api/app/jobs/bs_request_action_webui_infos_job.rb
- src/api/app/models/bs_request_action/differ/query_builder_for_superseded.rb
- src/api/app/models/bs_request_action/differ/source_package_finder.rb
- src/api/spec/cassettes/BsRequestActionWebuiInfosJob/_perform/for_a_superseded_request/1_1_3_1.yml
- src/api/spec/cassettes/BsRequestActionWebuiInfosJob/_perform/for_a_superseded_request/1_1_4_1.yml
- src/api/spec/cassettes/BsRequestActionWebuiInfosJob/_perform/for_a_target_package/creates_the_diff.yml
- src/api/spec/cassettes/BsRequestActionWebuiInfosJob/_perform/with_non_existing_source_package/1_1_3_1.yml
- src/api/spec/cassettes/BsRequestActionWebuiInfosJob/_perform/with_non_existing_source_package/1_1_3_2.yml
- src/api/spec/cassettes/BsRequestActionWebuiInfosJob/_perform/with_non_existing_target_project/1_1_2_1.yml
- src/api/spec/cassettes/BsRequestActionWebuiInfosJob/_perform/with_non_existing_target_project/1_1_2_2.yml
- src/api/spec/jobs/bs_request_action_webui_infos_job.rb
- src/api/spec/models/bs_request_action/differ/query_builder_for_superseded_spec.rb
as we implemented diffs between superseded requests it is necessary to warm up the cache in the backend for these diffs.
See #4741.
> Implemented caching of superseded requests in BsRequestActionWebuiInfosJob

- src/api/app/assets/javascripts/webui/application.js.erb
- src/api/app/assets/javascripts/webui/application/groups.js
- src/api/app/assets/javascripts/webui/application/tabs.js
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/views/shared/_buildresult_box.html.haml
- src/api/app/views/webui/groups/show.html.haml
It partially solves the broken JavaScript for multi requests (#4719). :bowtie: 
This is affecting code in other places and not only in multiple request. But I would say it is more likely that I fix with it something somewhere else as that I break it. :rofl: I checked the UI and I didn't find anything broken, but it would be great if someone can double check it. :smile:
>  [webui] Fix highlighting of headers in nested tabs

- src/api/app/controllers/webui/request_controller.rb
- src/api/spec/cassettes/Webui_RequestController/POST_changerequest/with_valid_parameters/forwards.yml
- src/api/spec/controllers/webui/request_controller_spec.rb
This test was failing with a MissingAction exception when the VCR cassettes
where not used. To fix this we had to ensure that the target package of
the forwarded request has different source content than the original
package.
In our test suite this test was still passing because of the recorded
cassettes.
> [frontend] Fix test for forwarding bs requests

- src/api/app/controllers/webui/request_controller.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/bs_request_action.rb
- src/api/spec/cassettes/BsRequest/_forward_to/with_a_project_as_parameter/creates_a_new_submit_request_open_for_review.yml
- src/api/spec/cassettes/BsRequest/_forward_to/with_a_project_as_parameter/creates_a_submit_request_action_with_the_correct_target.yml
- src/api/spec/cassettes/BsRequest/_forward_to/with_a_project_as_parameter/sets_the_logged_in_user_as_creator_of_the_request.yml
- src/api/spec/cassettes/BsRequest/_forward_to/with_options/creates_a_submit_request_action_with_the_correct_target.yml
- src/api/spec/cassettes/BsRequest/_forward_to/with_options/sets_the_given_description.yml
- src/api/spec/cassettes/BsRequest/_forward_to/with_project_and_package_as_parameter/creates_a_submit_request_action_with_the_correct_target.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/models/bs_request_spec.rb
* DRY existing request tests
* Move controller code for forwarding requests to model
* Include validation error messages of bs request actions to bs request validation messages
* Add tests for request forwarding and propagating validation errors
* Refactor request related code
> Refactor request forwarding and improve propagation of validation errors

- dist/setup-appliance.sh
> [dist] fix appliance upgrade

- contrib/start_lint
- src/api/lib/tasks/databases.rake
- src/api/lib/tasks/dev.rake
the test never really tested anything because we always setted up the database with db:structure:load
so the migrations never run. We need to drop the database before we run the migrations.
Otherwise it only compares the structure.sql with itself which is not really what we want :/
> [ci] Fix not running database migration test

- src/api/app/helpers/webui/request_helper.rb
- src/api/app/models/history_element.rb
> Change color of revoked requests to ornage (issue #2945)

- src/api/app/controllers/webui/session_controller.rb
- src/api/app/models/user.rb
This allows us more fine grained graphs.
> [frontend] Track result of login attempts

- .gitmessage
I have to comment them every time I write a commit. :angry:
> [doc] Comment annoying lines in git file

- .github/ISSUE_TEMPLATE.md
I realized this could be a bit improved when I opened an issue.
> [doc] Fix typos and title case in ISSUE_TEMPLATE.md

- src/api/app/controllers/webui/feeds_controller.rb
- src/api/app/controllers/webui/main_controller.rb
> [frontend] Solve n+1 query on the main page

- dist/obs-server.spec
- docs/api/api/about.xml
- docs/api/api/about.xsd
- src/api/app/controllers/about_controller.rb
- src/api/app/views/about/index.xml.builder
- src/api/config/initializers/git.rb
to know which revision gets installed. 
We also display now the revision on the /about route
> Write git revision into last_deploy file

- dist/t/0100-check_webserver_and_api.ts
- dist/t/osc/0200-check_docker_registry.ts
new xml element "commit" in 'osc api about' broke tests
> Fix testcase 0100-check_webserver_and_api.ts

- contrib/git-diff-to-deploy
- to use the revision from the latest available package
- transformed to Ruby
- added optional launch in browser option to show diff in GitHub
> [dist] Update git diff to deploy script

- src/api/app/controllers/webui/package_controller.rb
> Refactor download_url_for_file_in_repo to be easier to understand

- .rubocop_todo.yml
- dist/clouduploader.rb
- dist/obs_mirror_project
- dist/openQA_mail_notification.rb
- src/api/app/controllers/webui/main_controller.rb
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/mixins/parse_package_diff.rb
- src/api/app/models/bs_request.rb
- src/api/app/models/package.rb
- src/api/app/models/project.rb
- src/api/app/models/repository.rb
- src/api/lib/authenticator.rb
- src/api/lib/pretty_nested_errors/key_and_messages_parser.rb
- src/api/lib/tasks/databases.rake
- src/api/script/import
- src/api/test/unit/schema_test.rb
Autocorrect this Rubocop 0.55.0 cops:
- Style/BlockDelimiters
- Layout/TrailingWhitespace
- Performance/RegexpMatch
- Rails/Present
> Autocorrect some Rubocop cops

- src/api/app/models/bs_request_action.rb
- src/api/app/models/bs_request_action_delete.rb
- src/api/app/models/project.rb
- src/api/lib/backend/api/sources/project.rb
- src/api/spec/cassettes/StatusController/GET_project/with_a_develpackage/1_1_4_1.yml
- src/api/spec/cassettes/StatusController/GET_project/with_a_develpackage/1_1_4_2.yml
- src/api/spec/cassettes/StatusController/GET_project/with_a_link/to_a_package_in_a_different_project/1_1_8_2_1.yml
- src/api/spec/cassettes/StatusController/GET_project/with_a_link/to_a_package_in_the_same_project/1_1_8_1_1.yml
- src/api/spec/cassettes/StatusController/GET_project/with_default_attributes/1_1_1_1.yml
- src/api/spec/cassettes/StatusController/GET_project/with_default_attributes/1_1_1_2.yml
- src/api/spec/cassettes/StatusController/GET_project/with_default_attributes/1_1_1_3.yml
- src/api/spec/cassettes/StatusController/GET_project/with_default_attributes/1_1_1_4.yml
- src/api/spec/cassettes/StatusController/GET_project/with_default_attributes/1_1_1_5.yml
- src/api/spec/cassettes/StatusController/GET_project/with_default_attributes/1_1_1_6.yml
- src/api/spec/cassettes/StatusController/GET_project/with_default_attributes/1_1_1_7.yml
- src/api/spec/cassettes/StatusController/GET_project/with_default_attributes/1_1_1_8.yml
- src/api/spec/cassettes/StatusController/GET_project/with_errors/1_1_7_1.yml
- src/api/spec/cassettes/StatusController/GET_project/with_failures/1_1_3_1.yml
- src/api/spec/cassettes/StatusController/GET_project/with_groups/1_1_6_1.yml
- src/api/spec/cassettes/StatusController/GET_project/with_groups/1_1_6_2.yml
- src/api/spec/cassettes/StatusController/GET_project/with_persons/1_1_5_1.yml
- src/api/spec/cassettes/StatusController/GET_project/with_persons/1_1_5_2.yml
- src/api/spec/cassettes/StatusController/GET_project/with_verifymd5_attribute/1_1_2_1.yml
Some refactoring to move Backend::Connection calls to the proper Backend::Api... method were needed.
> Refactor Backend::Connection calls 

- ReleaseNotes-2.10
We fixed the issue #4736 in the PR.
> Add the bugfix #5000 to the release notes

- src/api/app/controllers/source_controller.rb
- src/api/app/views/source/index.xml.builder
- src/api/app/views/source/package_command_showlinked.xml.builder
- src/api/app/views/source/project_command_showlinked.xml.builder
- src/api/app/views/source/show_project.xml.builder
- src/api/app/views/source/verboseproductlist.xml.builder
Hi,
To reduce the amount of code on the controllers, I've changed the XML generation to use XML builder
> Use xml builder to render xml response

- dist/obsapisetup
- dist/obsclouduploadserver
- dist/obsclouduploadworker
- dist/obsdeltastore
- dist/obsdispatcher
- dist/obsdodup
- dist/obspublisher
- dist/obsrepserver
- dist/obsscheduler
- dist/obsservice
- dist/obsservicedispatch
- dist/obssigner
- dist/obssrcserver
- dist/obsstoragesetup
- dist/obswarden
- dist/obsworker
This was causing some offenses from Rpmlint.
> [dist] Add short descriptions to our service files

- src/api/lib/tasks/dev.rake
to make it easy to popullate the database with some useful testdata.
> [ci] Add dev:development_testdata:create task 

- .circleci/config.yml
- src/api/Gemfile
- src/api/Gemfile.lock
- src/api/spec/rails_helper.rb
- src/api/spec/support/coverage.rb
- src/api/test/test_helper.rb
> [ci] Extract setup alias in CircleCI config

- src/api/app/views/layouts/webui2/_personal_navigation.html.haml
unless x.blank? -> if x.present?
> [frontend] Cleanup condition in view

- src/api/lib/obsapi/markdown_renderer.rb
- src/api/spec/mailers/event_mailer_spec.rb
> [frontend] Render markdown links in its absolute form

- src/api/app/models/obs_factory/distribution.rb
- src/api/app/models/obs_factory/distribution_strategy_sle15.rb
(1:1 port of https://github.com/openSUSE/obs_factory/pull/139)
> [frontend] Support SLE15 service packs in staging dashboard

- .circleci/config.yml
- src/api/spec/support/capybara.rb
> [ci] Store capybara screenshots as artifacts in CircleCI

- src/api/spec/cassettes/Webui_PackageController/POST_submit_request/not_successful/1_1_7_1.yml
- src/api/spec/cassettes/Webui_PackageController/POST_submit_request/not_successful/1_1_7_2.yml
- src/api/spec/cassettes/Webui_PackageController/POST_submit_request/not_successful/1_1_7_3.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/controllers/webui/project_controller_spec.rb
Cherry picking from my experiment with regenerating cassettes
> Testsuite picks

- src/api/lib/tasks/dev.rake
> [dist] Don't load rubocop in production

- src/api/test/test_helper.rb
Not using it for quite a while
> [ci] Cleanup poltergeist from minitest

- src/api/spec/factories/bs_requests.rb
- src/api/spec/models/obs_factory/distribution_spec.rb
- src/api/spec/models/obs_factory/distribution_strategy_factory_ppc_spec.rb
- src/api/spec/models/obs_factory/distribution_strategy_factory_spec.rb
- src/api/spec/models/obs_factory/distribution_strategy_sle15_spec.rb
- src/api/spec/support/shared_contexts/a_opensuse_product.rb
> Extend and add tests for factory models

- src/api/app/controllers/source_project_meta_controller.rb
- src/api/spec/cassettes/SourceProjectMetaController/GET_show/1_1_1.yml
- src/api/spec/cassettes/SourceProjectMetaController/GET_show/1_1_2.yml
- src/api/spec/controllers/source_project_meta_controller_spec.rb
refactored some repeated code to its own methods and refreshed the cassetes
> [api] refactored method from source_project_meta_controller

- src/api/app/models/obs_factory/distribution_strategy_factory.rb
- src/api/app/models/obs_factory/staging_project.rb
- src/api/app/presenters/obs_factory/staging_project_presenter.rb
- src/api/app/views/webui/obs_factory/distributions/show.html.haml
- src/api/app/views/webui/obs_factory/staging_projects/_overall_state.html.haml
- src/api/app/views/webui/obs_factory/staging_projects/show.html.erb
- src/api/spec/models/obs_factory/distribution_spec.rb
- src/api/spec/models/obs_factory/distribution_strategy_factory_spec.rb
> Factory dashboard: remove ring2 

- src/api/app/models/bs_request_action_delete.rb
- src/api/spec/cassettes/BsRequestActionDelete/_sourcediff/for_package/1_1_2_1.yml
- src/api/spec/cassettes/BsRequestActionDelete/_sourcediff/for_project/1_1_1_1.yml
- src/api/spec/cassettes/BsRequestActionDelete/_sourcediff/for_repository/1_1_3_1.yml
- src/api/spec/factories/bs_requests.rb
- src/api/spec/models/bs_request_action_delete_spec.rb
The if statements were completely messed up.
This got introduced by a refactoring in
214ba835ddcb6fc02a216dd3108c27c1ad12f724.
The DiffError should only raise if there is no
package and no repository (messed with the unless).
Also the guard clause should only return and empty
string if there is no target_package.
In case there is package, we can do a normal diff.
Fix #5107
> [webui][api] Fix delete request diff for packages

- .gitmessage
> Add Saray, Victor and Dany to .gitmessage

- src/api/spec/controllers/webui/user_controller_spec.rb
> [ci] Expect the icon size instead of the PNG data size

- src/api/app/controllers/webui/request_controller.rb
- src/api/app/models/bs_request.rb
- src/api/spec/cassettes/Webui_RequestController/POST_set_bugowner_request/with_valid_parameters/1_7_1_3.yml
- src/api/spec/controllers/webui/request_controller_spec.rb
- src/api/spec/models/bs_request_spec.rb
added testcase for missing action, added the necessaries factories and refactored some repeated code to it's own method
> [webui] refactoring request_controller and improve spec coverage

- src/api/spec/cassettes/Project/_restore/sets_the_user_that_restored_the_project_in_the_history_element.yml
- src/api/spec/models/project_spec.rb
The original author of the test had the test running on a backend
with multiple runs of delete/undelete on the same backend and
recorded this into a VCR. Making it impossible to run the test
on a fresh backend to regenerate the cassette
> [ci] Fix project_spec to work on fresh backend

- docker-compose.ci.yml
to keep all docker-compose configuration file in the same version in all enviroments
> [ci] update version from docker-compose.ci.yml to 2.1

- src/api/Gemfile
- src/api/Gemfile.lock
> [ci] Relax rspec dependency

- src/api/spec/controllers/webui/user_controller_spec.rb
> Rewrite icon action test in user controller

- src/api/.rubocop_todo.yml
- src/api/app/controllers/webui/user_controller.rb
- src/api/app/helpers/webui/user_helper.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/models/user.rb
- src/api/app/views/webui/package/_commit_item.html.erb
- src/api/app/views/webui/user/show.html.haml
- src/api/config/routes.rb
- src/api/spec/controllers/webui/user_controller_spec.rb
- src/api/spec/helpers/webui/search_helper_spec.rb
- src/api/spec/helpers/webui/user_helper_spec.rb
- src/api/spec/helpers/webui/webui_helper_spec.rb
- src/api/spec/models/user_spec.rb
- src/api/test/unit/user_test.rb
I had hoped you can also remove the load_external_url function, but it's also used for interconnect
> [frontend] Remove icon action and merge into helper

- .circleci/config.yml
- src/api/lib/tasks/test_webui.rake
master: group 1: 4:25 minutes, group 2: 22:09 minutes
this PR: group1: 12:36 minutes, group 2: 13:54 minutes
-> 8 minutes win
> Move a little more tests between the minitest groups on circleci

- src/api/spec/controllers/webui/cloud/azure/upload_jobs_controller_spec.rb
- src/api/spec/controllers/webui/cloud/ec2/upload_jobs_controller_spec.rb
- src/api/spec/models/cloud/backend/upload_job_spec.rb
- src/api/spec/models/cloud/upload_job_spec.rb
Having this in cassettes makes them unreproducible. So stub them manually in code
> Fix 4 specs that require a misconfigured backend

- src/api/app/indices/package_index.rb
- src/api/app/indices/project_index.rb
> Fix definition of search indexes

- src/api/app/models/obs_factory/openqa_api.rb
- src/api/spec/models/obs_factory/openqa_api_spec.rb
> Openqa api tests

- src/api/app/models/bs_request.rb
- src/api/spec/models/bs_request_spec.rb
'Reviews invalid' is little helpful, 'User not found' makes
it more obvious you had a typo
Fixes #5152
> [frontend] Report review validation details

- src/api/spec/controllers/webui/obs_factory/distributions_controller_spec.rb
- src/api/spec/controllers/webui/obs_factory/staging_projects_controller_spec.rb
- src/api/spec/factories/bs_requests.rb
We added some tests to cover the OBS Factory controllers
> Test obs factory controllers (Distribution and Staging Project)

- src/api/spec/models/obs_factory/distribution_strategy_factory_spec.rb
> Add tests for DistributionStrategyFactory#project_iso

- src/api/spec/support/capybara.rb
Before:
Packages
editing package files
Capybara starting Puma...
* Version 3.12.0 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://0.0.0.0:3005
editing an existing file
After:
Packages
editing package files
editing an existing file
> [ci] Don't spam the rspec progress with puma startup

- src/api/spec/cassettes/Packages/editing_package_files/editing_an_existing_file.yml
- src/api/spec/features/webui/packages_spec.rb
- src/api/spec/features/webui/projects_spec.rb
> [ci] Remove skip from 'editing an existing file'

- src/api/app/models/issue_tracker.rb
- src/api/spec/cassettes/Issue/_fetch_issues/fetches_the_issues.yml
- src/api/spec/factories/issue_tracker.rb
- src/api/test/unit/issue_test.rb
The syntax of a class shouldn't depend on Config options
Fixes #5439
> Fix validation of IssueTracker and its Factory

- src/api/spec/rails_helper.rb
- src/api/spec/support/migration.rb
> [ci] Silence migration tests

- src/api/app/assets/javascripts/webui2/application.js
- src/api/app/assets/javascripts/webui2/plotbusyworkers.js
- src/api/app/controllers/webui/main_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/helpers/webui/main_helper.rb
- src/api/app/helpers/webui/status_message_helper.rb
- src/api/app/views/layouts/webui2/_logged_in_user_navigation.html.haml
- src/api/app/views/layouts/webui2/_personal_navigation.html.haml
- src/api/app/views/layouts/webui2/_proxy_auth_navigation.html.haml
- src/api/app/views/layouts/webui2/webui.html.haml
- src/api/app/views/webui2/status_messages/_card.html.haml
- src/api/app/views/webui2/webui/main/_add_status_message_modal.html.haml
- src/api/app/views/webui2/webui/main/_admin_proceed-list.html.haml
- src/api/app/views/webui2/webui/main/_latest_updates.html.haml
- src/api/app/views/webui2/webui/main/_proceed-list.html.haml
- src/api/app/views/webui2/webui/main/_sponsors.html.haml
- src/api/app/views/webui2/webui/main/_status_messages.html.haml
- src/api/app/views/webui2/webui/main/_systemstatus.html.haml
- src/api/app/views/webui2/webui/main/_user_proceed-list.html.haml
- src/api/app/views/webui2/webui/main/about.html.haml
- src/api/app/views/webui2/webui/main/index.html.haml
- src/api/spec/features/webui/image_templates_spec.rb
> Style main in bootstrap

- .codeclimate.yml
Disable warnings about webui2 code and other places
> Add a configuration for codeclimate

- src/api/app/models/attrib_value.rb
- src/api/spec/features/webui/attributes_spec.rb
> [webui] Trim carriage return characters from attribute values

- src/api/spec/support/capybara.rb
I only tested locally, but without wanting to
I put the silence code in the if section only
running against selenium container
> Extend the puma silencing to circleci

- src/api/spec/models/obs_factory/distribution_spec.rb
> Add missing tests for Distribution model

- src/api/test/test_helper.rb
As in minitest we only have the spider test left, there is
a lot of code unnecessary
> Remove a lot of unused code in test_helper

- src/api/app/assets/images/images/forward_disabled.png
> Remove stale symlink breaking package

- src/api/app/models/obs_factory/distribution_strategy_casp.rb
- src/api/app/models/obs_factory/distribution_strategy_factory.rb
Both DistributionStrategyFactory and DistributionStrategyCasp had some
unused code.
> Refactor casp and factory strategies models

- src/api/app/models/obs_factory/openqa_api.rb
@Ana06, better now? Please check :eye:
> Refactor slightly OpenqaApi model

- CONTRIBUTING.md
> Fix link to pull request instructions on CONTRIBUTING page

- src/api/app/models/binary_release.rb
one match is okay, multiple are not (regression from 9c0bc2cce4)
> Avoid invalid warning

- src/api/spec/controllers/source_attribute_controller_spec.rb
- src/api/spec/controllers/webui/search_controller_spec.rb
> Fix 3 more bugs happening without vcr

- src/api/app/controllers/webui/search_controller.rb
- src/api/spec/controllers/webui/search_controller_spec.rb
> Don't crash if the disturl is incomplete

- src/api/spec/controllers/webui/obs_factory/staging_projects_controller_spec.rb
- src/api/spec/models/bs_request_spec.rb
> Use the Rspec's one liner syntax where possible

- .travis.yml
They are just spam on the IRC channel
> Disable IRC 'notifications' from travis

- ReleaseNotes-2.10
- src/api/.rubocop.yml
- src/api/config/database.yml.example
- src/api/db/migrate/20140624101042_add_package_tracking.rb
- src/api/db/migrate/20140627071042_product_media_tracking.rb
- src/api/db/migrate/20140709071042_product_medium_tracking.rb
- src/api/db/migrate/20140717101042_add_updateinfo_tracking.rb
- src/api/db/migrate/20140729101042_updateinfo_tracking_second_attempt.rb
- src/api/db/migrate/20140801071042_product_version_tracking.rb
- src/api/db/migrate/20140903125426_add_generic_operation_history.rb
- src/api/db/migrate/20141110105426_fix_product_media_uniq_index.rb
- src/api/db/migrate/20170306084558_change_repositories_remote_project_name_to_not_null.rb
- src/api/db/migrate/20170619111734_alter_notifications_to_use_polymorphic.rb
- src/api/db/migrate/20171218160607_create_ec2_configuration.rb
- src/api/db/migrate/20180720082742_switch_to_utf8mb4.rb
- src/api/db/structure.sql
- src/api/script/prepare_spec_tests.sh
- src/api/spec/models/comment_spec.rb
Reverts openSUSE/open-build-service#5491
> [frontend] Store comments.body as utf8mb4

- src/api/app/models/comment.rb
- src/api/spec/mailers/event_mailer_spec.rb
I wonder why it throws exceptions in production - but it seems to work in test env
> Test emoji emails

- src/api/app/models/event/base.rb
Instead of raising
Fixes #5564
> Notify Errbit for extra payload keys in events

- src/api/app/views/webui2/webui/main/_admin_proceed-list.html.haml
- src/api/app/views/webui2/webui/main/_proceed-list.html.haml
doesn't make sense to hide it for admins.
> [webui] Show user proceed list for Admin

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/models/package.rb
- src/api/app/models/service.rb
- src/api/config/initializers/activexml.rb
- src/api/lib/backend/api/sources/package.rb
- src/api/spec/cassettes/Service/_addKiwiImport/has_a_kiwi_import_service.yml
- src/api/spec/cassettes/Service/_addKiwiImport/posts_mergeservice.yml
- src/api/spec/cassettes/Service/_addKiwiImport/posts_runservice.yml
- src/api/spec/cassettes/Service/_addKiwiImport/posts_waitservice.yml
- src/api/spec/cassettes/Webui_PackageController/POST_save_file/as_ajax_request/uploading_a_file_from_remote_URL/1_7_1_5_1.yml
- src/api/spec/cassettes/Webui_PackageController/POST_save_file/as_ajax_request/uploading_a_file_from_remote_URL/1_7_1_5_2.yml
- src/api/spec/cassettes/Webui_PackageController/POST_save_file/as_ajax_request/uploading_a_file_from_remote_URL/creates_a_valid_service_file.yml
- src/api/spec/cassettes/Webui_PackageController/POST_save_file/as_non-ajax_request/uploading_a_file_from_remote_URL/1_7_2_5_1.yml
- src/api/spec/cassettes/Webui_PackageController/POST_save_file/as_non-ajax_request/uploading_a_file_from_remote_URL/1_7_2_5_2.yml
- src/api/spec/cassettes/Webui_PackageController/POST_save_file/as_non-ajax_request/uploading_a_file_from_remote_URL/creates_a_valid_service_file.yml
- src/api/spec/models/service_spec.rb
Make it use backend library to read, save and delete _service
and use Nokogiri directly to manipulate it
> Stop using ActiveXML::Node in Service 'model'

- src/backend/BSPublisher/Container.pm
- src/backend/BSServer.pm
- src/backend/BSServerEvents.pm
- src/backend/bs_repserver
So that our registry proxy knows that it can cache the result.
> [backend] add Cache-Control header for registry blobs

- src/api/app/controllers/webui/obs_factory/staging_projects_controller.rb
- src/api/app/models/package.rb
- src/api/app/models/project.rb
- src/api/spec/cassettes/Package/_ignored_requests/when_the_package_has_an_ignored_requests_file/parses_the_content_as_YAML_and_returns_a_hash.yml
- src/api/spec/cassettes/Package/_ignored_requests/when_the_package_has_no_ignored_requests_file/1_22_2_1.yml
- src/api/spec/factories/packages.rb
- src/api/spec/models/package_spec.rb
* Moves fetching the dashboard package of staging project to the project
model.
* Moves reading of the ignored_requests YAML file to the package model.
> Move dashboard related code from controller to model

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/views/webui/package/_deps.html.erb
- src/api/app/views/webui/package/dependency.html.erb
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_a_valid_project_and_an_invalid_architecture/1_22_2_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_a_valid_project_and_an_invalid_architecture/1_22_2_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_an_invalid_project/1_22_1_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_an_invalid_project/1_22_1_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture/repositories_and_a_filename/1_22_5_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture/repositories_and_a_filename/1_22_5_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture/repositories_and_a_filename/1_22_5_3.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture/repositories_and_a_filename/1_22_5_4.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture/repositories_and_a_filename/1_22_5_5.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture/repositories_and_a_filename/1_22_5_6.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture/repositories_and_a_filename/and_fileinfo_is_nil/1_22_5_7_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture/repository_and_an_invalid_repository/1_22_4_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture/repository_and_an_invalid_repository/1_22_4_2.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture_and_an_invalid_repository/1_22_3_1.yml
- src/api/spec/cassettes/Webui_PackageController/GET_dependency/when_passing_params_referring_to_valid_project/architecture_and_an_invalid_repository/1_22_3_2.yml
- src/api/spec/controllers/webui/package_controller_spec.rb
I added a `FIXME` in `package#dependency` because right now, it's not possible to list repositories of a remote project (without increasing the scope of this PR). So at least right now, remote projects are taken into account (unlike before).
> Improvements for package#dependency

- src/api/app/models/event/repo_published.rb
- src/backend/bs_publish
Including changes from #5561 as discussed with @mlschroe
> Status API - Add build_id to Event::RepoPublished

- src/api/app/views/webui/package/_deps.html.erb
> Use repository/arch's name if available

- src/api/config/environment.rb
This adds support for the old format of options.yml files.
Follow up of #5622
> Make change of options.yml backward compatible

- src/api/spec/controllers/webui/patchinfo_controller_spec.rb
for action ```new_tracker``` move repeated code out to the before block
> Refactor patchinfo controller spec

- src/api/app/models/package.rb
- src/api/app/models/package/errors.rb
As in ```project.rb``` model, I moved the exceptions classes declared in ```package.rb``` to it's own ```errors.rb```
> Move Exceptions class to its own file (package.rb)

- src/api/lib/feature_switch/obs_repository.rb
With this approach, we only change what is needed instead of changing complete methods
> Reduce the amount of monkey patching for the 'feature' gem

- src/api/spec/factories/users.rb
This slipped in with the last PR merge (427f81d7c4e31045531de9).
> Fixes FactoryBot/AttributeDefinedStatically offense

- src/api/app/models/bs_request.rb
- src/api/spec/models/bs_request_spec.rb
fix for the race condition found on https://github.com/openSUSE/open-build-service/issues/5594
- move permissions check to transaction
- add test case to check if the  "state machine"  works correctly
> fix for the issue#5594

- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/views/webui2/webui/package/_tabs.html.haml
* Reduces duplication when dealing with *_path helpers
* Wraps setting of 'active' class
> Wrap creation of tab links in a helper

- src/api/.rubocop_todo.yml
- src/api/app/assets/stylesheets/webui/application.css.erb
- src/api/app/assets/stylesheets/webui/application/announcements.scss
- src/api/app/controllers/webui/announcements_controller.rb
- src/api/app/controllers/webui/users/announcements_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/helpers/webui/markdown_helper.rb
- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/mailers/event_mailer.rb
- src/api/app/models/announcement.rb
- src/api/app/views/event_mailer/comment_for_package.html.haml
- src/api/app/views/event_mailer/comment_for_project.html.haml
- src/api/app/views/event_mailer/comment_for_request.html.haml
- src/api/app/views/layouts/webui/_announcement.html.haml
- src/api/app/views/layouts/webui/webui.html.erb
- src/api/app/views/layouts/webui2/_footer.html.haml
- src/api/app/views/webui/announcements/show.html.haml
- src/api/app/views/webui/comment/_show.html.haml
- src/api/app/views/webui/main/_status_messages.html.haml
- src/api/app/views/webui/users/announcements/create.js.erb
- src/api/app/views/webui2/status_messages/_item.html.haml
- src/api/config/routes.rb
- src/api/spec/cassettes/Announcements_for_users/logged_in_users_see_a_new_announcements_notification_and_can_acknowledge_it.yml
- src/api/spec/controllers/webui/users/announcements_controller_spec.rb
- src/api/spec/features/webui/announcements_spec.rb
- src/api/spec/helpers/webui/markdown_helper_spec.rb
Only the last version of the terms is shown. The user should accept it.
I might open the PR, but kudos goes to @saraycp for driving this :bowtie:.
> Add Terms of Service to the views

- src/api/app/models/user.rb
> Add a metric to track users joining / leaving the beta group

- src/api/test/functional/source_services_test.rb
should fix https://github.com/openSUSE/open-build-service/issues/5651
but I am unable to run the test suite atm, so 100% untested.
> [api] fix flickering test, wait for source service

- src/backend/BSConfig.pm.template
- src/backend/bs_clouduploadserver
Fix https://github.com/openSUSE/open-build-service/issues/5548
> [backend] make pub key for cloud upload configurable

- src/api/app/controllers/webui/packages/bs_requests_controller.rb
- src/api/spec/cassettes/Packages/Viewing_a_package_that/has_a_mime_like_suffix_in_it_s_name.yml
- src/api/spec/cassettes/Packages/Viewing_a_package_that/has_derived_packages.yml
- src/api/spec/cassettes/Packages/Viewing_a_package_that/was_branched.yml
- src/api/spec/cassettes/Packages/adding_an_invalid_file.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/group_roles/Add_group_to_package_/_project.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/group_roles/Add_role_to_group.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/group_roles/Remove_role_from_group.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/group_roles/Viewing_group_roles.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/user_roles/Add_role_to_user.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/user_roles/Add_user_to_package_/_project.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/user_roles/Remove_role_from_user.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/user_roles/Remove_user_from_package_/_project.yml
- src/api/spec/cassettes/Packages/behaves_like_user_tab/user_roles/Viewing_user_roles.yml
- src/api/spec/cassettes/Packages/branching_a_package_from_another_users_project/with_AutoCleanup.yml
- src/api/spec/cassettes/Packages/branching_a_package_from_another_users_project/without_AutoCleanup.yml
- src/api/spec/cassettes/Packages/changing_the_package_s_devel_project.yml
- src/api/spec/cassettes/Packages/deleting_a_package.yml
- src/api/spec/cassettes/Packages/log/download_logfile_succesfully.yml
- src/api/spec/cassettes/Packages/log/live_build_finishes_succesfully.yml
- src/api/spec/cassettes/Packages/requesting_package_deletion.yml
- src/api/spec/cassettes/Packages/triggering_package_rebuild/via_binaries_view.yml
- src/api/spec/cassettes/Packages/triggering_package_rebuild/via_live_build_log.yml
- src/api/spec/features/webui/requests_spec.rb
This adds a feature test for using the type and state dropdowns,
which is implemented via javascript, when searching for a request.
javascript.
> Add a feature test for using the request tab

- README.md
Will show if our dependencies are stale in master.
> Add a depfu badge

- src/api/app/controllers/status_controller.rb
- src/api/config/routes.rb
Make the `_from_cache` & `find_relationships_for_packages` methods private and remove the public routes. They are methods not actions.
> Make StatusController methods private & remove routes

- src/api/lib/xpath_engine.rb
The produced query condition produced
did not negate the query and queried for a true
condition.
Fix #5571
> Fix xpath search for not() function

- src/api/app/controllers/status_controller.rb
- src/api/app/controllers/worker/capability_controller.rb
- src/api/app/controllers/worker/command_controller.rb
- src/api/app/controllers/worker/status_controller.rb
- src/api/config/routes.rb
- src/api/spec/cassettes/Worker_StatusController/GET_/index/1_1_1.yml
- src/api/spec/cassettes/Worker_StatusController/GET_/index/1_1_2.yml
- src/api/spec/controllers/worker/command_controller_spec.rb
- src/api/spec/controllers/worker/status_controller_spec.rb
Move worker related actions from ```StatusController``` to its own controllers
> StatusController worker related actions refactoring

- src/api/app/helpers/webui/webui_helper.rb
- src/api/app/views/webui2/webui/package/_buildstatus.html.haml
Break up into simpler methods so it's easier to understand.
> Refactor webui2_repo_status_icon

- src/api/app/controllers/source_project_controller.rb
Follow-up to #5767 after our discussions in the review meeting this morning.
> Use required_parameters to check presence of cmd

- src/api/app/views/webui2/webui/attribute/index.html.haml
Follow-up to #5713 after our discussions in the review meeting this morning.
> Be consistent in icons colors

- src/api/app/controllers/webui/packages/job_history_controller.rb
- src/api/app/models/package.rb
- src/api/lib/backend/api/build_results/job_history.rb
- src/api/spec/models/package_spec.rb
The PR was merged before I submit the review: https://github.com/openSUSE/open-build-service/pull/5161#pullrequestreview-130364161 :sob:
> [api] Refactor option assignation as in PR review

- src/api/app/controllers/status_controller.rb
- src/api/config/routes.rb
All actions of this controller got moved elsewhere. So we can drop it
now.
> Good bye status controller

- src/api/app/models/event/comment_for_package.rb
- src/api/app/models/event/comment_for_project.rb
- src/api/spec/models/event_subscription/generate_hash_for_subscriber_spec.rb
If you are (only) the bugowner of a project/package you should
also be able to receive comment notifications.
> Comment notifications for bugowners

- src/api/app/controllers/status_project_controller.rb
- src/api/app/models/relationship.rb
* Break the method `find_relationship_for_packages` in smaller methods
* Add memoization for `package_hash`
* Improve ruby dialect for `role_from_cache`, `user_from_cache`,
`group_from_cache`
> Refactor StatusProjectController

- src/api/app/controllers/webui/main_controller.rb
- src/api/app/controllers/webui/monitor_controller.rb
- src/api/app/controllers/webui/webui_controller.rb
- src/api/app/models/architecture.rb
- src/api/spec/models/architecture_spec.rb
Remove method from controller and move it to the model. 
add test case for that
> Move map_to_workers to the Architecture#worker

- src/api/app/controllers/announcements_controller.rb
- src/api/app/controllers/application_controller.rb
- src/api/app/controllers/issue_trackers_controller.rb
- src/api/app/controllers/message_controller.rb
- src/api/app/controllers/request_controller.rb
- src/api/app/controllers/status_messages_controller.rb
- src/api/app/helpers/maintenance_helper.rb
- src/api/app/models/branch_package.rb
- src/api/app/models/patchinfo.rb
- src/api/app/models/project.rb
- src/api/app/models/service.rb
- src/api/lib/opensuse/validator.rb
- src/api/spec/controllers/public_controller_spec.rb
- src/api/spec/controllers/webui/sitemaps_controller_spec.rb
- src/api/spec/models/bs_request_spec.rb
- src/api/test/functional/channel_maintenance_test.rb
- src/api/test/functional/maintenance_test.rb
- src/api/test/functional/source_controller_test.rb
- src/api/test/test_helper.rb
We could have found the request diff problem this way
> Be strict with XML documents

- src/api/app/controllers/webui/project_controller.rb
to fix can't convert nil into Integer when converting to_i with a default value.
Fix #5774.
> Fix can't convert nil in monitor

- src/api/app/views/webui/package/show.html.erb
- src/api/app/views/webui2/webui/package/_show_failures.html.haml
Use the rails helper instead of custom code to form plural
thank you @dmarcoux !
> Use pluralize instead of custom code

- src/api/app/helpers/webui/user_helper.rb
The no_icon variable had no effect
Fixes #4926
> Do not return image tag if no_icon var is set

- src/api/app/views/webui/comment/_new.html.haml
- src/api/app/views/webui2/webui/comment/_new.html.haml
Users might wonder why commenting isn't available
Fixes #4775
> Ask for login or signup in comment section

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/policies/package_policy.rb
- src/api/spec/controllers/webui/package_controller_spec.rb
- src/api/spec/policies/package_policy_spec.rb
Enable pundit action helper verfiy_authorized to make sure that
the action is being authorized. The action `branch` still missing,
even if it calls authorize, it still raising the AuthorizationNotPerformedError
> Enable verify_authorized in Package controller actions

- src/api/app/controllers/webui/obs_factory/staging_projects_controller.rb
> Change build_id to uuid

- src/api/config/routes.rb
- src/api/spec/controllers/status/checks_controller_spec.rb
because appearently it was discussed as this with the stakeholder.
> Drop /checks from end of route

- src/api/app/views/webui2/webui/attribute/index.html.haml
- src/api/app/views/webui2/webui/package/revisions.html.haml
This was used in the old webui views
> Remove unneeded package_bread_crumb

- src/api/app/assets/javascripts/webui2/application.js
- src/api/app/assets/javascripts/webui2/packages.js
- src/api/app/controllers/webui/package_controller.rb
- src/api/app/views/webui/package/add_file.html.erb
- src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml
- src/api/app/views/webui2/webui/package/add_file.html.haml
- src/api/spec/features/webui/packages_spec.rb
> Implement Package#add_file view in bootstrap

- src/api/app/controllers/webui/package_controller.rb
- src/api/app/views/webui2/webui/package/_breadcrumb_items.html.haml
- src/api/app/views/webui2/webui/package/_deps.html.haml
- src/api/app/views/webui2/webui/package/binary.html.haml
> Port binary view to webui2

- src/api/app/views/webui2/shared/_package_branch_form.html.haml
- src/api/app/views/webui2/webui/package/_delete_dialog.html.haml
- src/api/app/views/webui2/webui/package/_rpmlint_result.html.haml
- src/api/app/views/webui2/webui/package/_submit_request_dialog.html.haml
- src/api/app/views/webui2/webui/request/_requests_small.html.haml
- src/api/lib/tasks/dev.rake
- src/api/spec/features/webui/packages_spec.rb
They look nicer on more devices, blend better with current theme (and with any theme in the future).
> Use custom forms with package/show in webui2

- src/api/app/views/layouts/webui2/webui.html.haml
Duplicated code added by mistake is removed from the layout.
> Remove duplicated code related to CodeMirror

- src/api/app/assets/stylesheets/webui2/build-results.scss
- src/api/app/assets/stylesheets/webui2/comments.scss
- src/api/app/assets/stylesheets/webui2/live_build_log.scss
- src/api/app/assets/stylesheets/webui2/texts.scss
- src/api/app/views/webui2/webui/package/_commit_item.html.haml
- src/api/app/views/webui2/webui/package/_rpmlint_result.html.haml
- src/api/app/views/webui2/webui/package/live_build_log.html.haml
> Fix issue 5954

- src/api/app/helpers/webui/webui_helper.rb
When nil is passed as the text it fails
> Fix helper force_utf8_and_transform_nonprintables

- src/api/app/assets/javascripts/webui2/forms.js
- src/api/app/assets/javascripts/webui2/packages.js
- src/api/app/assets/stylesheets/webui2/cm2.scss
- src/api/app/views/webui2/webui/package/add_file.html.haml
* Fix package add file validations  (#5980)
* Hide overflow of long filenames (#5979)
> Fix several file upload issues

- src/api/app/assets/stylesheets/webui2/comments.scss
- src/api/app/views/webui2/webui/comment/_content.html.haml
> Fix several bootstrap issues for comments

- src/api/app/views/webui2/shared/_buildresult_box.html.haml
- src/api/app/views/webui2/webui/package/_buildstatus.html.haml
> Remove unneeded classes in buildresult box

- ReleaseNotes-2.9.5
- src/api/app/models/comment.rb
> Fix xml output for comments

- src/api/app/models/project.rb
- src/api/app/models/staging_workflow.rb
First steps in StagingWorkflow. Still WIP.
> Add basis for Staging workflow

- src/api/app/controllers/webui/staging_workflows_controller.rb
- src/api/app/models/project.rb
- src/api/app/models/staging_workflow.rb
- src/api/db/migrate/20181008150453_create_staging_workflows.rb
- src/api/db/structure.sql
This is on work in progress, we added all the basic models and controller
related to staging workflow.
> Add StagingWorkflow basis

- src/api/app/controllers/webui/webui_controller.rb
Those comments don't add useful information as the code is self-explanatory. :unamused: 
It is also not clear why all users are thought to be women. :confused:
> Remove unneded comments

- src/api/app/assets/javascripts/webui2/package-view_file.js
Avoid repeating code and use `slice` instead of `if` and conversion to string in the case of `day` for readability. Add some extra variables, indent and join some strings to help reading template string. Remove the _// FIXME: Refactor this code_, it can not be improved more. :muscle: :bowtie:
>  Refactor package-view_file.js

- src/api/app/controllers/webui/staging_workflows_controller.rb
- src/api/app/models/project.rb
- src/api/app/models/staging_workflow.rb
- src/api/db/migrate/20181008150453_create_staging_workflows.rb
- src/api/db/structure.sql
This is on work in progress, we added all the basic models and controller
related to staging workflow.
> Add StagingWorkflow base

- src/api/app/controllers/webui/staging_workflows_controller.rb
- src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml
- src/api/app/views/webui2/webui/project/_tabs.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_breadcrumb_items.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_infos.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_legend.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_overall_state.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_packages_list.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_problems.html.haml
- src/api/app/views/webui2/webui/staging_workflows/show.html.haml
- src/api/config/routes.rb
Still WIP but at least now we have a basic layout to be able to work in
parallel on every part of this page
This is how it will be:
> Add StagingWorkflow#show action with a basic layout

- src/api/spec/support/capybara.rb
This is just the javascript part - but you can also inject custom css through js
> Disable Animations in Chrome

- src/api/app/views/webui/package/revisions.html.erb
> Fix package#revisions show all

- src/backend/BSSched/Checker.pm
- src/backend/BSSched/EventHandler.pm
- src/backend/bs_dispatch
- src/backend/bs_repserver
- src/backend/bs_sched
- src/backend/bs_srcserver
> Implement buildid for unpublished repos

- src/backend/BSSched/Checker.pm
- src/backend/BSSched/ProjPacks.pm
- src/backend/BSSched/PublishRepo.pm
- src/backend/BSServer.pm
- src/backend/bs_sched
- src/backend/bs_srcserver
> replace haveinterrepodep code with something more useful

- src/api/app/controllers/staging_project/staged_requests_controller.rb
- src/api/app/controllers/staging_project_controller.rb
- src/api/app/views/staging_project/staged_requests/index.xml.builder
- src/api/config/routes.rb
- src/api/spec/controllers/staging_project/staged_requests_controller_spec.rb
XML API endpoint to list all staged requests in a staging project/staging workflow
> Add API endpoint for staged_requests

- src/backend/BSContar.pm
- src/backend/BSPublisher/Container.pm
- src/backend/BSRepServer/Containertar.pm
> Take container with the highest version/release if there is a conflict over a tag

- src/api/app/models/repository.rb
The model was removed in 3e226956eb594acaa8cf875bd61dbafa8498c0da
as was the table
> Remove status_repository_publishes

- dist/t/0060-check_required_services.ts
> [ci] fix tests for 2.8/2.9

- src/api/app/models/obs_factory/distribution.rb
- src/api/app/models/obs_factory/staging_project.rb
- src/api/app/views/webui2/webui/project/_breadcrumb_items.html.haml
- src/api/app/views/webui2/webui/project/_tabs.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_breadcrumb_items.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_infos.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_legend.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_overall_state.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_packages_list.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_problems.html.haml
- src/api/db/migrate/20181008150453_create_staging_workflows.rb
This was removed by mistake in the rebase on master.
> Add back removed files after rebase of staging-workflow

- src/api/app/models/staging_workflow.rb
Staging projects were created but not stored in the Backend.
> Store Staging Projects in the Backend

- src/api/app/controllers/webui/staging_workflows/staging_projects_controller.rb
- src/api/app/controllers/webui/staging_workflows_controller.rb
- src/api/app/models/project.rb
- src/api/app/policies/staging_workflow_policy.rb
- src/api/app/views/webui2/webui/staging_workflows/_breadcrumb_items.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_create_staging_project.html.haml
- src/api/app/views/webui2/webui/staging_workflows/_delete_staging_project_modal.html.haml
- src/api/app/views/webui2/webui/staging_workflows/edit.html.haml
- src/api/app/views/webui2/webui/staging_workflows/show.html.haml
- src/api/config/routes.rb
- src/api/spec/controllers/webui/staging_workflows/staging_projects_controller_spec.rb
- src/api/spec/controllers/webui/staging_workflows_controller_spec.rb
We added the ability to create and destroy staging projects from a staging workflow.
> Create and destroy staging projects

- src/api/app/controllers/webui/staging_workflows_controller.rb
Some of the instance variables calculated in the show ended up in the
edit LoL
> Fix a wrongly merge in StagingWorkflowController
