src/api/public/robots.txt
The route `/package/dependency` is too expensive to be hit by crawlers. 
Closes #9872
=> Add /package/dependency route to robots.txt

src/api/app/models/owner_search/assignee.rb
When searching the backend for binaries it often returns
the src package. Those can belong to any of the multibuild
package container names.
Fixes #9837
=> Handle multibuild in owner search

dist/obs-server.spec
With this commit we change $HOME of the user 'obsservicerun' from
/usr/lib/obs to /srv/obs/service. /srv/obs/service is owned by 'obsservicerun'
by default. It should avoid problems for services using git via ssh.
=> [dist] change homedir of user 'obsservicerun'

src/api/app/models/notification.rb, src/api/db/migrate/20200703110429_add_last_seen_at_to_notifications.rb, src/api/db/schema.rb
In order to show the avatars of the users involved in the notifiable of the notification since the user last time checked the notification, we need to save the date and time the user lastly did so.
In other words:
One of the improvements in notifications is unifying/merging notifications affecting the same notifiable. Keeping all the information in one single line.
When many users write comments in my project, instead of receiving many notifications, I'll receive only one notification summarizing what's new since last time I checked.
Among others, we need to track who are the new commenters. To do so, we decided to store the date we last checked the notifications `last_seen_at` and then iterate over the list of comments created from that time to the present in order to take the needed …
=> Add last_seen_at column to notifications table

src/api/db/data/20200702145811_adapt_review_and_duplicated_notifications.rb, src/api/spec/db/data/adapt_review_and_duplicated_notifications_spec.rb
Instead of having dedicated notification for `Event::ReviewWanted`,
we will from now on unify this with the request notifications.
The association to the review will be dropped. Therefore we
need to associate the review notifications to the corresponding
request through a data migration.
Also, we are going to show only the latest state of a request
or comment through the notifications. The data migration
needs to remove duplicated/outdated notifications that already
exist.
DO NOT MERGE: The data migration will cause a downtime, we need to wait for the maintenance window. This should
be merged close to it.
=> Create data migration to adapt review and duplicated notifications 

src/api/app/models/review.rb
Review notifications are going to disappear, meanwhile, we create
Review#number method to take the request number instead.
Fixes error caused by this lines: https://github.com/openSUSE/open-build-service/pull/9873/files#diff-1fc6031128e8767883b805cc36ea1d95R9-R10
=> Define Review#number temporarily

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/views/webui/users/notifications/index.html.haml
For small devices the notification filter box now displays the project
name instead of 'Inbox'.
Fixes #9882  
**Before**
**After**
=> Display selected project name for mobile

src/api/app/views/webui/feeds/notifications.rss.builder
The recent changes on the notification system, included
dropping the creation of dedicated notifications of type
review for 'ReviewWanted' events. Instead they are also
associated to the corresponding BsRequest.
This is not handled by the new RSS feed templates, which leads
to an exception. To prevent the exception on ReviewWanted events,
we can switch back to the older version of the templates, which
base on the event payload itself. Since the event payload
hasn't changed, the older templated are still working as expected.
Fixes #9899
=> Prevent exception on review wanted rss feeds

src/api/app/models/notification.rb, src/api/app/services/notification_service/web_channel.rb, src/api/spec/services/notification_service/web_channel_spec.rb
Copy the last_seen_at over to the new notification upon cleanup
We need the last_seen_at field being copied over the new notifications
so we can show the avatars of the people commenting on a request since
the last time you marked a notification as read.
=> Notification last seen at

src/api/app/controllers/webui/search_controller.rb, src/api/spec/controllers/webui/search_controller_spec.rb, src/api/spec/features/beta/webui/search_spec.rb, src/api/spec/features/webui/search_spec.rb
@search_where and @search_what have defaults, no need
to error out
Fixes #9890
=> Do not throw an error on missing search defaults

src/api/app/models/notification.rb
`unread_date` was defined twice.
=> Remove duplicated unread_date method

src/api/app/views/webui/users/notifications/_notifications_list.html.haml
This fixes the errors saying `The asset "icons/request-icon" is not present in the asset pipeline.`.
=> Add missing extension to the request icon

src/api/app/controllers/webui/users/notifications_controller.rb
Hello all! 
This PR fixes an error at the notifications controller.
The error is that the reference to `@notifications` at the notifications controller is being called before any value is assign to it.
This PR proposes to pass the `notifications` as parameter to the private method `show_all` instead of referencing them as `@notifications` from the `show_all`.
To verify this fix
- Using the master branch, navigate to http://localhost:3000/my/notifications?show_all=1
- Verify that you saw the error 
- Using this branch, navigate to http://localhost:3000/my/notifications?show_all=1
- Verify that you see the notifications page
Fix #9909 
Error:
After the fix:
=> Fix error at notifications index with show_all

dist/t/0110-check_signd.ta
Re-written 0110-check_signd.ta in perl.
This patch checks if the function "create_sign_cert" exists in
/usr/lib/obs/server/setup-appliance.sh which was introduced in 2.11.
We do not compare version of obs-server package to be more flexible
if this feature gets backported.
Without this patch our test cases for 2.10 are failing.
=> [dist] fix test case 0110-check_signd.ta for obs < 2.11

src/backend/bs_publish
=> [backend] bs_publish deal with another digit when renaming to milestone

src/backend/BSConfig.pm.template, src/backend/call-service-in-docker.sh
This patch adds the possibilty to specify a user/password combination
in BSConfig.pm and export to ENV in the container to use for basic auth
at the API server (specified in api_url).
This is required e.g. for kiwi_import.
Without this patch the service fails with '401 - Unauthorized' when using
e.g. 'https://build.opensuse.org' as api url.
=> [backend] user/pass for obs services called in docker

src/api/lib/tasks/dev.rake
In the default configuration, influxdb_hosts is configured to `['localhost']` and it doesn't work following this [HOWTO](https://github.com/openSUSE/open-build-service/wiki/Application-Health-Monitoring)
The other thing that it doesn't work is trying to access the influxdb ´rails` if it doesn't exist. [influxdb-rails](https://github.com/influxdata/influxdb-rails) as far as I can see doesn't do it
We need in the initializers something (assuming all options.yml configuration were already evaluated) like:
```
influxdb = InfluxDB::Client.new host:'influx'
influxdb.create_database('rails')
```
After that you are able to write on `rails.exceptions`, with something like: 
```
pry(main)> InfluxDB::Rails.client.write_point('rails.exceptions', values: { value: 1, error_type: …
```
=> Add influx host to influxdb_hosts options section

src/backend/BSDispatcher/Constraints.pm, src/backend/bs_dispatch, src/backend/bs_repserver
Add overwriteconstraints call to bs_repserver function checkconstraints.
As this is used by bs_repserver and bs_dispatcher move the
function to BSDispatcher/Constraints.pm
Otherwise _constraints files with <overwrite> statements will not work correctly with
`osc checkconstraints`
=> [backend] add overwriteconstraints to repserver

src/backend/bs_regpush
=> [backend] support oci content types in bs_regpush -l

src/backend/bs_sourcepublish
=> [backend] fix syncing of source sym links to remote

dist/setup_source_service_docker.sh, src/backend/BSConfig.pm.template, src/backend/call-service-in-docker.sh
Some of our services like bundle_gems use a local proxy/cache like geminabox.
So far we used the "--link" option to make the geminabox container accessible
by name for the service container.
Using "--link" on a bridge is deprecated and only worked so far because we
patched the docker package on the service server.
* The first patch makes the network name configurable so we can use user-defined networks in the future.
* The second patch makes it possible to set a custom MTU size for docker which is required in our test setup
=> Use user-defined network in call-services-in-docker.sh for service which need local proxies

src/backend/bs_signer
We forgot to update the big endian size entry (bsc#1094761)
=> [backend] bs_signer: fix content length patching for iso files

src/api/app/services/notification_service/notifier.rb
Group model doesn't have `rss_token`, using `try` will return `nil` if the method doesn't exist.
Fix #9900
=> Fix rss notifications creation

src/api/app/models/relationship.rb
The update to `rubocop 0.87.1` in #9892 addressed the false positive and the `rubocop:{disable,enable}` comments were removed. This comment also needs to be removed since it's now outdated.
=> Remove outdated comment

docs/api/api/obs.rng, src/backend/bs_service
It is just an alias for "disabled" on the server side, but osc may
make a difference here in future.
It is the better name for the todays usage of "disabled", while
"disabled" may mean in future really the original documented purpose
of keeping it disabled, just for reference.
=> [api] introduce "manual" service mode

src/api/app/controllers/webui/packages/branches_controller.rb, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/shows_an_error_if_current_revision_parameter_is_provided_but_there_wasn_t_any_revision_before.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/shows_an_error_if_source_package_does_not_exist.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/shows_an_error_if_source_package_parameter_not_provided.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/shows_an_error_if_source_project_does_not_exist.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/shows_an_error_if_source_project_parameter_not_provided.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/shows_an_error_if_the_target_package_exists_already.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/shows_an_error_if_user_has_no_permissions_for_source_project.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/with_currrent_revision_parameter/1_1_10_1.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/with_currrent_revision_parameter/1_1_10_3.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/with_currrent_revision_parameter/redirects_to_the_branched_package.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/with_default_parameters/1_1_8_1.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/with_default_parameters/redirects_to_the_branched_package.yml, src/api/spec/cassettes/Webui_Packages_BranchesController/POST_create/with_target_package_name/1_1_9_1.yml, src/api/spec/controllers/webui/packages/branches_controller_spec.rb, src/api/spec/features/beta/webui/projects_spec.rb, src/api/spec/features/webui/projects_spec.rb
Package::UnknownObjectError and Project::UnknownObjectError also
have nice error messages that tell you exactly what is not found.
Show that to people, instead of a generic message.
Makes #9970 a bit more clear
=> Always show the message while branching failed

src/api/app/lib/backend/error.rb, src/api/app/lib/backend/not_found_error.rb
After the introduction of zeitwerk the subclasses of a module
need to be in a dedicated file when using subdirectories
to structure the project.
Supersedes #9955
=> Move backend exception class to separate file

src/backend/bs_worker
newline after finished removing
=> bs_worker log output improvement

src/backend/bs_repserver
=> [backend] kiwitree: reset timeout after receiving a file

src/api/public/robots.txt
Web robots try to access these routes, causing a bunch of auth request errors (401).
Update also the link to the documentation page in the comment.
=> Disallow '/source/*' routes for web robots

src/backend/bs_signer
=> [backend] signer: add a workaround for rpm --delsign clobbering the lead

src/backend/BSPublisher/Registry.pm, src/backend/bs_srcserver, src/backend/bs_worker
the mediaType change is as expected by helm documented here:
https://helm.sh/docs/topics/registries/
and
https://github.com/helm/helm/blob/d6f6184351f7aecd9d0efdfb8aba7da5664031eb/internal/experimental/registry/constants.go
=> [backend] allow building helm chart

src/api/config/routes/webui_routes.rb, src/api/spec/cassettes/Packages/Viewing_a_package_that/has_a_mime_like_suffix_in_it_s_name.yml, src/api/spec/cassettes/Packages/editing_a_package_s_details/updates_the_package_title_and_description.yml, src/api/spec/cassettes/Packages/editing_the_package_description/updated_the_package_description.yml, src/api/spec/features/beta/webui/packages_spec.rb, src/api/spec/features/webui/packages_spec.rb
While implementing the in-place editing for the packages, we removed
the explicit format constraints that allowed package names to have
extension-like names like `python-aspy.yaml`.
This PR brings those format constraints back.
- Create a package with a name like `ctris.yaml`
- You should be able to access the show page.
Fixes #9998
=> Add explicit format constraints to show, edit and update package

src/api/app/views/webui/attribute/responsive_ux/_index_actions.html.haml
I've found this inconsistency while working on something else. It's only a bit different, but it's now consistent with the other action links.
Before:
After:
=> Fix indentation and add missing nav-link class of "Add Attribute" link

src/api/app/controllers/webui/feeds_controller.rb, src/api/app/controllers/webui/main_controller.rb, src/api/app/models/status_message.rb, src/api/spec/controllers/webui/feeds_controller_spec.rb, src/api/spec/factories/status_message.rb
The RSS feed is showing all status messages, ignoring its scope, so
everybody sees everything. This PR enforces the propper roles so the
RSS feed shows appropriate content to each user.
Fixes #9926
=> Restrict status messages showing on the rss feed

src/backend/bs_check_consistency
* Add warnings, strict
* Add Getopt::Long usage to avoid parsing params manually.
The feature for multiple params 'foo=s{2}' has been added in version 2.35.
Despite still being described as experimental, 2.35 was released in 2005.
So I think it's safe to use it.
* use FindBin for getting the current script path (better to read and portable)
* use a here-doc for the usage() sub (more readable)
* exit() directly in usage() (less code)
I don't know if there are tests covering the script, though.
=> Modernize bs_check_consistency

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/helpers/webui/notification_helper.rb, src/api/app/presenters/notifications_filter_presenter.rb, src/api/app/views/webui/users/notifications/_notifications_filter.html.haml, src/api/app/views/webui/users/notifications/_notifications_list.html.haml, src/api/app/views/webui/users/notifications/_update.js.erb, src/api/app/views/webui/users/notifications/index.html.haml, src/api/spec/features/beta/webui/users/notifications_controller_spec.rb
Instead of picking the notification type from the `params` variable,
this PR makes the notification type explicitly available as a partial
local variable and function parameters.
Before this PR, the user was losing the selected notifiable type from the
notifications filter when marking a notification as 'read'.
This was due to the notifications/update remote partial not getting
the `params[:type]` when rendering.
It's also fixed in small devices
Fixes #9908
=> Keep the filter when marking a notification read or unread 

src/api/app/assets/stylesheets/webui/responsive_ux/responsive_ux.scss, src/api/app/helpers/webui/webui_helper.rb
Reverting the change in `feature_css_class` from #10007
This fixes issues which were caused by CSS rules leaking out of the responsive-ux layout when they are targeting elements not specific to this layout.
Before:
_Flash messages_
_Footer_
After:
_Flash messages_
_Footer_
=> Encapsulate responsive-ux styles

docs/api/api/api.txt
Document this required argument, it was missing before.
Example:
```
> osc --debug workerinfo x86_64:goat01:1
GET https://api.opensuse.org/worker/x86_64:goat01:1
<worker hostarch="x86_64" registerserver="..." workerid="goat01:1">
```
=> [api] worker info requires prefixed hostarch

src/api/app/assets/stylesheets/webui/responsive_ux/navbar.scss
Watchlist menu was displaying a close button that should be only
visible for small and medium viewports. And the menu didn't reach to
bottom of the page.
=> Fix off-canvas menu for desktop

src/api/app/assets/stylesheets/webui/responsive_ux/grid.scss, src/api/app/assets/stylesheets/webui/responsive_ux/tabs.scss
This is something which was somewhat addressed in #10007. The tabs didn't break the layout anymore, but other elements still do. Limiting the width of specific elements could turn out to be a long process. It's better and simpler to tackle this issue for the content container.
Just like before, tabs are not overflowing:
As for the other elements, like the diffs on the request show page, they were overflowing. It's now fixed.
Before:
After:
=> Prevent content from breaking the responsive-ux layout

docs/api/api/request.rng, src/api/.rubocop_todo.yml, src/api/app/helpers/webui/request_helper.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/bs_request_action_release.rb, src/api/spec/helpers/webui/request_helper_spec.rb, src/api/test/functional/request_controller_test.rb
This is basically the same functionality as release command for
packages, but it allows to involve review workflows.
A very much stripped down version of maintenance_release action,
not relying on incident setups.
OBS-51
=> [api] support plain release request

docs/api/api/constraints.rng, src/backend/BSDispatcher/Constraints.pm, src/backend/BSXML.pm, src/backend/testdata/test_dispatcher
To increase the memory need per used job on the worker. This can be
potentionally racy, because parallel builds may happened on different
times so the need of memory might differ depending on build speed.
=> [backend] support memory per job constraint

src/backend/BSConfig.pm.template, src/backend/bs_srcserver
No way to specifiy this per project yet, not sure if there
is a usecase.
=> [backend] allow to blacklist packages from source publishing

src/backend/bs_regpush
in case config has no rootfs then there are diff_ids to match against
the layers. Since helm charts have only 1 layer
So ignore checking diff_ids == layers
=> [backend] bs_publish fix layers-check for helm chart

src/api/.rubocop_todo.yml, src/api/app/models/group.rb, src/api/app/models/package.rb, src/api/app/models/review.rb, src/api/app/queries/open_requests_finder.rb
=> Fix RuboCop offenses for Rails/PluckInWhere

src/api/app/views/webui/package/_file.html.haml, src/api/app/views/webui/package/_files_view.html.haml
Downloading files requires people to log in. Even if it goes through
the `/source` API route.
Offering this makes some web spiders that do not pay attention to robots.txt
produce lots of 401s.
=> Hide file action column for anonymous

src/api/.rubocop_todo.yml, src/api/app/controllers/application_controller.rb, src/api/app/controllers/person_controller.rb, src/api/app/controllers/public_controller.rb, src/api/app/controllers/webui/monitor_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/sitemaps_controller.rb, src/api/app/controllers/webui/webui_controller.rb
Regular expresiones can be wrapped by // or %r{}.
Rubocop proposes to use only one of them and // is the preference.
Only if the regular expression contains any slash, it should use %r{}.
=> Correct Rubocop Style/RegexpLiteral offences in controllers

src/api/.rubocop_todo.yml, src/api/app/helpers/webui/webui_helper.rb, src/api/app/mixins/build_log_support.rb, src/api/app/services/package_service/file_verifier.rb, src/api/app/services/trigger_controller_service/token_extractor.rb, src/api/config/routes/webui_routes.rb, src/api/lib/api_error.rb, src/api/lib/tasks/coverage.rake, src/api/lib/tasks/extract.rake, src/api/lib/tasks/test_webui.rake
Corrections in helpers, mixins, services, routes and libs.
Using // by default and %r{} just in case the regular expression
contains slashes.
=> Correct Rubocop Style/RegexpLiteral in various files

src/backend/BSPublisher/Registry.pm, src/backend/bs_regpush
=> [backend] container publishing: support oci fat manifests as well

src/api/app/mixins/populate_sphinx.rb, src/api/app/models/concerns/append_sphinx_callbacks.rb, src/api/app/models/package.rb, src/api/app/models/project.rb, src/api/spec/models/full_text_search_spec.rb
Deleted packages/projects are now removed from Sphinx indices. Before, we were missing the `after_destroy` callback from
`ThinkingSphinx::ActiveRecord::Callbacks::DeleteCallbacks`. This resulted in having deleted packages/projects in our Sphinx indices. The error was `ThinkingSphinx::Search::StaleIdsException` with the message `Record IDs found by Sphinx but not by ActiveRecord : 123, 456, 789`.
See upstream:
https://github.com/pat/thinking-sphinx/blob/df2746b5679c8009527ac87b761357d536d48c05/lib/thinking_sphinx/callbacks.rb#L10
https://github.com/pat/thinking-sphinx/blob/7622e5e40fe8a79a3329ddc78d54390cfe7a7f02/lib/thinking_sphinx/callbacks/appender.rb#L16
This fixes #9436.
**TODO after merging this PR:**
We will have to cleanup the indices and to do so, we need to rebuild them.
```shell …
```
=> Append ThinkingSphinx callbacks to Package and Project models

src/api/app/controllers/status_messages_controller.rb, src/api/app/controllers/webui/status_messages_controller.rb, src/api/app/policies/status_message_policy.rb, src/api/app/views/webui/main/_status_message.html.haml, src/api/app/views/webui/main/_status_messages.html.haml, src/api/app/views/webui/main/responsive_ux/_index_actions.html.haml, src/api/spec/policies/status_message_policy_spec.rb
We often have the need to create (and sometimes destroy) status messages on our reference server. Allowing staff users to do this is much better than turning everybody into an admin.
=> Allow staff users to create/update/destroy status messages

src/backend/bs_publish, src/backend/bs_repserver, src/backend/bs_signer
This generates provenance files for the charts.
We also no longer remove helm charts from the publish area if
a registry is configured. Helm charts are small and do not
contain layers from the blobstore like containers.
=> [backend] implement signing of helm charts

contrib/grafana-datasource.yml, contrib/influxdb-init.iql, contrib/telegraf.conf, docker-compose.sre.yml, src/api/config/initializers/influxdb_rails.rb
This makes it possible to start an environment with all monitoring
services enabled. I think it make little sense to seperate AHM/APM.
`docker-compose -f docker-compose.yml -f docker-compose.sre.yml up`
=> Merge the docker-compose AHM/APM setups

src/backend/BSPublisher/Helm.pm, src/backend/bs_publish
This generates a helm chart index from all published charts.
=> [backend] publisher: implement repotype 'helm'

src/api/app/views/webui/package/_file.html.haml
In the past we showed the download link for files with
a size of less than 4 megabytes also to non authenticated users.
Now we show the link only to authenticated users no matter which
sizes the file has. A forgotten if statement led to the problem
that we didn't showed the download link to anyone anymore when
the file exceeds the 4 megabytes.
Fixes #10096
=> Show download link for files that exceed 4 megabytes

src/backend/BSContar.pm, src/backend/BSPublisher/Registry.pm, src/backend/bs_regpush
Also use the oci mime types for the config/layers if
we're creating an oci manifest.
=> [backend] move mime type definitions into BSContar.pm

src/backend/BSConfig.pm.template, src/backend/BSPublisher/Container.pm
along with the project in BSConfig::publish_containers
=> [backend] BSPublisher/Container.pm allow to specify repo

src/backend/BSSched/Checker.pm, src/backend/BSXML.pm, src/backend/bs_srcserver
The old implementation made projects not in the limit list
look like not existing projects leading to all kinds of
hard to debug issues.
We now return the project but with an error status.
=> [backend] implement limit_projects in a sane way

src/api/app/views/webui/main/_status_message.html.haml, src/api/app/views/webui/main/_status_message_delete_dialog.html.haml
There were no confirmation while removing a status message. To prevent
accidental removing, all the destructive actions should contain a
confirmation.
The commit adds the appropriate modal dialog.
Fixes #10087
1. Log in to local instance of OBS;
2. Create new status message (if there are no existing ones on the Home Page);
3. Click 'X' (Delete status message) icon for the status message.
"Delete status message?" confirmation dialog is shown. After clicking "Delete", the dialog should disappear, status message should be deleted.
Here is the screenshot of how it looks:
=> Show confirmation dialog on status message delete

dist/obsworker
This will allow the workers to run in the foreground without detaching.
=> dist/obsworker: Add run command

src/api/.rubocop_todo.yml, src/api/app/controllers/webui/monitor_controller.rb, src/api/app/helpers/webui/notification_helper.rb, src/api/app/views/staging/staging_projects/_staging_project_item.xml.builder
Auto-correct only those RuboCop Performance cops that are marked as safe auto-correct.
Follow-up to #10120.
=> Auto-correct RuboCop Performance cops offenses for `src/api/`

src/api/app/models/bs_request_action.rb, src/api/test/functional/build_controller_test.rb, src/api/test/unit/bs_request_test.rb
=> Use update project on request delegation

src/api/app/assets/javascripts/webui/comment.js, src/api/app/controllers/webui/comments_controller.rb, src/api/app/policies/comment_policy.rb, src/api/app/views/webui/comment/_comment_field.html.haml, src/api/app/views/webui/comment/_new.html.haml, src/api/app/views/webui/comment/_reply.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/comments_controller_spec.rb, src/api/spec/features/beta/webui/comments_spec.rb, src/api/spec/features/webui/comments_spec.rb, src/api/spec/policies/comment_policy_spec.rb
Hey everyone,
This Pull Request enables users to edit their comments on the webui namespace,  __not__ the api one.
The issue being addressed is #6674.
__NOTE:__ I know that the initial commit is a bit large, sorry for this :-(.
To verify the feature:
- Open a package, project, or any other commentable entity in the project
- If you have already made comments then you will see an __edit__ button now available on your comments
- Else add a comment and you will see the __edit__ button available on the comment that you made
- Click the edit button, a text area containing the previous comment should appear
- Edit the comment and click on the __Update comment__ button
- You should be able to see the new comment now
=> Edit comments feature

src/api/app/views/webui/users/notifications/_notifications_filter.html.haml
Projects filter title was shown even if there were no unread
notifications. That was confusing.
The commit adds the behavior to hide the filter when there are no unread
notifications.
Fixes #9461
To verify the feature:
1. Generate notifications:
- SSH into running _frontend_ container;
- Execute `bundle exec rake ts:start`;
- Then run `bundle exec rake dev:notifications:data[2]`.
2. Log in to the application;
3. Go to Notifications Page (e.g. click on the bell in the top-right or proceed by the link: http://localhost:3000/my/notifications);
4. Focus on the Projects filter, it should show several projects, as there are unread notifications;
5. Mark all the notifications as "Read";
6. Focus on the Projects fitler.
Projects filter disappears when there are no unread …
=> Hide Projects filter when it is empty

src/api/app/views/webui/users/notifications/_notifications_list.html.haml
The wording of the filters for the notifications changed a while
ago, but this wasn't adapted in the code that shows you a message
when no notifications exist.
=> Fix handling of selected filters for empty notification page

src/api/app/helpers/webui/notification_helper.rb
Previously, when a filter project was selected, clicking in "Show all" made the project filter go away. This behaviour is now fixed.
Fixes #10122.
To test this change:
- create lots of notifications (in development environment: `rake dev:notifications:data[400]`)
- go to User Notifications
- filter by a project
- click in "Show all"
- check that the project filter still applies
=> Enable "Show all" in project filter for notifications

src/api/app/views/webui/users/notifications/_notifications_list.html.haml
After marking a notification as read, the pagination links point to the update URL. This commit makes sure that the pagination links always create notification index links.
Fixes #10171.
=> Fix pagination links after marking a notification as read

src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/helpers/webui/notification_helper.rb, src/api/app/views/webui/users/notifications/_notifications_list.html.haml
Preserve `page` and `show_all` parameters after marking a notification as read. Fixes #10173 and fixes #10181.
Also related, take the user to the last pagination page, when the only notification of the last page is marked as read. Reported  in [#10173](https://github.com/openSUSE/open-build-service/issues/10173#issuecomment-696027112).
And last, after clicking in a page of several notifications (not the first page), and then clicking on the "Show all" button, show the first page of all the results. It makes no sense to preserve the `page` paramenter in the "Show all"/"Show less" button link.
I will setup a lot of notifications on the review-app instance, to make it easier to do a review.
=> Marking a notification as read: couple of fixes

src/api/app/models/bs_request_action.rb, src/backend/bs_repserver
=> [backend] repserver: also dirty repos for project/package events

src/backend/bs_repserver
sign events can overwrite each other if multiple archs finish at same
time. Regression from e0e0fb49220
=> [backend] fix hanging signing jobs

src/api/app/controllers/webui/users/notifications_controller.rb
Using `flash[:some_key]` will keep the flash for the next request, so this means that when we set the flash in an action called through an AJAX request, the flash will still be displayed when we reload the page.
=> Render flash message now in notifications#update

src/api/app/models/bs_request_action.rb, src/api/db/attribute_descriptions.rb, src/api/db/data/20200922135426_allow_submit_to_maintenance_release.rb, src/api/db/seeds.rb
This makes almost never sense, except you have a project where
you want to mirror the requests to somehere else ... (SUSE:SLE-*Update)
=> [api] allow to create submit requests to maintenance_release projects

src/backend/bs_srcserver
Our release managers store information in _project/_staging_workflow,
which led to everything doing a deep check for the project.
Check if the config changed or stayed the same.
Also forbid a _link file in _project.
=> [backend] do not treat a commit to _project as project config change

ReleaseNotes-2.11, src/backend/bs_publish
RepoType: withreports   will also publish OBS internal .report files.
We will also keep publishing .packages files for now with that flag,
but we plan to remove that part when testing infrastructure has been adapted.
=> [backend] introduce publish flag to publish tracking report files

src/api/app/presenters/notification_presenter.rb
In case of multi-line descriptions of notifications, joining the first lines of notifications' descriptions is confusing.
Truncate the excerpt to the first line, showing three dots at the end of the excerpt. This provides a more understandable message.
=> Truncate multi-line notification excerpts to the first line

src/backend/BSSched/Checker.pm
This makes publishing fail if a packge build has not succeeded.
=> [backend] support "nofailedpackages" publishing flag

src/api/app/helpers/webui/markdown_helper.rb, src/api/app/presenters/notification_presenter.rb, src/api/spec/helpers/webui/markdown_helper_spec.rb, src/api/spec/mailers/event_mailer_spec.rb
Use a render that strips the markdown tags. This way, we show a more understandable excerpt in the list of notifications.
**Before:**
**After:**
To verify the changes, I will setup a couple of examples in the review-app.
=> Remove markdown tags in notifications' excerpts

src/api/app/views/layouts/webui/_search.html.haml, src/api/app/views/layouts/webui/responsive_ux/_top_navigation_search.html.haml, src/api/config/routes/webui_routes.rb, src/api/public/404.html
The search#index endpoint doesnt modify or
store and any data. Therefore we shouldn't allow
or use POST request to access the resource.
This will also prevent issues with our 404 page
which is a static html file that doesn't include a
CSRF token (which would be require for POST).
Fixes #10196
=> Only use GET for search index endpoint

src/api/app/assets/stylesheets/webui/flash.scss, src/api/app/assets/stylesheets/webui/personal-navigation.scss, src/api/app/assets/stylesheets/webui/project-monitor.scss, src/api/app/assets/stylesheets/webui/responsive_ux/layout.scss, src/api/app/assets/stylesheets/webui/responsive_ux/navbar.scss, src/api/app/assets/stylesheets/webui/responsive_ux/tabs.scss, src/api/app/assets/stylesheets/webui/tabs-component.scss, src/api/app/assets/stylesheets/webui/watchlist.scss, src/api/app/views/layouts/webui/_login_form.html.haml
We have issues with components, overlapping each other in the wrong way.
This pull request changes the z-index hierarchy of the navigation bars and side panels, using default values provided by Bootstrap, and removing z-index changes that were considered unnecessary.
In the case of the old UI, only the watchlist panel was changed, to use a z-index lower than the one used by default in Bootstrap for modals.
In the case of the new responsive UI:
- fixed elements (fixed-top and fixed-bottom) in the top navigation bar and the bottom navigation bar were overwritten to a z-index lower than the one used by default in Bootstrap for modals.
- the watchlist panel z-index has a even lower value, to allow to show at the same time the user dropdown, located at the upper-right corner.
The value of a …
=> Implement new z-index hierarchy

src/api/app/views/webui/users/notifications/_notifications_list.html.haml, src/api/app/views/webui/users/notifications/index.html.haml
Currently we have the same padding both on small and big
viewports. By reducing the padding on small viewports, we
save up a lot of valuable space.
**Before**
**After**
=> Reduce padding for notifications list on small viewports

src/api/app/views/layouts/webui/responsive_ux/_top_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_unread_notifications_counter.html.haml, src/api/app/views/webui/users/notifications/_update.js.erb
Notifications counter did not update in real-time, when marking a
notification as read/unread. Only when page was refreshed, it was
updated.
The commit changes the behavior to use AJAX and update the counter every
time when action on notification is performed, so that there is no need
to update the page to see the actual amount of unread notifications in
the counter.
Fixes #10169
1. Generate notifications:
- SSH into running _frontend_ container;
- Execute `bundle exec rake ts:start`;
- Then run `bundle exec rake dev:notifications:data[2]`.
2. Log in to the application;
3. Go to Notifications Page (e.g. click on the bell in the top-right or proceed by the link: http://localhost:3000/my/notifications);
4. Remember the number, that is shown in Notifications counter in …
=> Update notifications counter in Top Nav with AJAX

src/api/app/presenters/notification_presenter.rb, src/api/app/queries/notifications_finder.rb, src/api/app/services/notified_projects.rb, src/api/spec/controllers/webui/users/notifications_controller_spec.rb, src/api/spec/db/data/backfill_notified_projects_spec.rb, src/api/spec/factories/notification.rb
Notifications with the notifiable_type 'Review' and the event_type 'Event::ReviewWanted' were migrated to the notifiable_type 'BsRequest' in #9883. Code specific to the notifiable_type 'Review' is since then unneeded.
=> Remove unneeded code for notification.notifiable_type 'Review'

src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/_decision_tab.html.haml, src/api/app/views/webui/request/_handle_request.html.haml, src/api/app/views/webui/request/_update.js.erb, src/api/app/views/webui/request/show.html.haml
Update BS request with AJAX call
The commit introduces asynchronous update for BS Requests.
This was implemented in scope of adding notification toolbar feature (#10220).
Previously, when the request got updated (e.g. approved/rejected), the page was refreshed and notification toolbar was removed, because it relies on 'notification_id' query parameter, but that parameter got removed after action was made on BS request.
To test the feature:
1. Log in as user that has notifications;
2. Proceed to the Notifications List Page;
3. Open Request notification which is in "review" or "declined" state;
4. Scroll the Request Page to the bottom;
5. Press "Decline"/"Approve"/"Reopen" button.
The page is updated asynchronously.  (Overview, Decision, Request History sections are …
=> Update BS Request with AJAX call

src/api/app/assets/stylesheets/webui/application.scss, src/api/app/assets/stylesheets/webui/notification_toolbar.scss, src/api/app/assets/stylesheets/webui/responsive_ux/responsive_ux.scss, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/helpers/webui/notification_helper.rb, src/api/app/presenters/notification_presenter.rb, src/api/app/queries/notifications_finder.rb, src/api/app/views/layouts/webui/_notification_toolbar.html.haml, src/api/app/views/layouts/webui/responsive_ux.html.haml
The PR adds a toolbar on the top of the page, which adds ability to mark notification as read from Request, Project and Package Pages.
The feature was requested in #9279
Steps to test the feature:
1. Log in as Admn that has notifications;
2. Proceed to the Notifications List Page;
3. Click on the title of any of the noifications;
4. When presented with the Request/Package/Project Page, focus on the top of the page.
Notification Toolbar is shown on the top, just below the Top Nav.
Here are the screenshots of how it looks:
**Desktop**
**Mobile**
=> Show Notification Toolbar when opening notification from Notifications List Page

src/backend/bs_repserver
fix wrong line order after beautification....
=> [backend] fix hanging signing jobs again

src/api/app/helpers/webui/notification_helper.rb
Rubocop detects this offense on the master branch.
This leads to a failing CI for other PR's
=> Fix rubocop Style/MethodCallWithArgsParentheses in notification helper

src/api/app/assets/stylesheets/webui/notifications_redesign/notifications.scss, src/api/app/helpers/webui/notification_helper.rb, src/api/app/presenters/notification_presenter.rb, src/api/app/views/webui/users/notifications/_notifications_list.html.haml
In this new round of redesign, we've tried to avoid having the notifications' information spread all over the area. So we've put together the information which answers to these two questions respectively: Where does the notification happen? What is happening there? The goal is making it easier to understand at a glance.
**Improvements:**
- We ensure we display relevant information like source and target project/package when needed.
- Change the position of the elements to group them logically.
- Specify the kind of requests in the link's text. Example: _"Add Role Request # 222"_
- The link's text for comments is changed from project/package name or request Id to something more clear like: _"Comment on Package"_ or _"Comment on Add Role Request"_. Needed to distinguish where the comment …
=> Notifications accurate redesign

src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/notification.js, src/api/app/assets/stylesheets/webui/notifications_redesign/notifications.scss, src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/helpers/webui/notification_helper.rb, src/api/app/policies/notification_policy.rb, src/api/app/views/webui/users/notifications/_notification_action_bar.html.haml, src/api/app/views/webui/users/notifications/_notifications_list.html.haml, src/api/app/views/webui/users/notifications/_update.js.erb, src/api/config/locales/kaminari.en.yml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/users/notifications_controller_spec.rb, src/api/spec/features/beta/webui/users/notifications_controller_spec.rb
When dealing with a big amount of notifications, it is very
time consuming to mark them one by one.
Therefore a way to update multiple notifications at once
is required.
**Desktop**
**Mobile**
This PR is work in progress since I want to implement a way that enables the user to literally mark everything as read (not just the items that are paginated in the notification list)
=> Add ability to mark multiple notifications as read/unread

src/api/app/models/event/build.rb, src/api/app/models/event/build_fail.rb, src/api/app/models/event/build_success.rb, src/api/app/models/event/build_unchanged.rb
There are also some interesting times and tags in the build events.
Let's measure them.
=> Publish build events to the metrics bus

src/api/app/views/webui/request/_show_overview.html.haml, src/api/spec/features/beta/webui/requests_spec.rb, src/api/spec/features/webui/requests_spec.rb
Hi there,
this fixes #10238. It shows the state in request#show as a badge to make it more consistent looking.
=> [api] change request state to badge

src/api/.rubocop_todo.yml, src/api/app/models/bs_request.rb, src/api/app/models/history_element/base.rb, src/api/spec/models/bs_request_action/differ/for_source_spec.rb, src/api/test/unit/issue_test.rb
The PR addresses RuboCop TODOs for:
- Lint/BinaryOperatorWithIdenticalOperands
- Lint/DuplicateMethods
- Lint/EmptyFile
- Naming/ConstantName
=> Address RuboCop TODOs

src/api/app/models/history_element/base.rb
The commit returns back the attr, that was mistakenly removed in #10247
=> Return back raw_type attr in HistoryElement Base

src/backend/BSSched/Checker.pm
=> [backend] fix details message for the new nofailedpackages flag

src/api/app/views/layouts/webui/responsive_ux/_bottom_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_top_navigation.html.haml, src/api/app/views/layouts/webui/responsive_ux/_unread_notifications_counter.html.haml, src/api/app/views/webui/users/notifications/_update.js.erb
Notifications counter did not update in real-time, when marking a
notification as read/unread. Only when page was refreshed, it was
updated.
The commit changes the behavior to use AJAX and update the counter every
time when action on notification is performed, so that there is no need
to update the page to see the actual amount of unread notifications in
the counter.
=> Update notifications counter in Bottom Nav with AJAX

src/api/app/assets/stylesheets/webui/notifications_redesign/notifications.scss
Notifications counter badge shifted bell icon when appeared/disappeared
or when amount of digits was changed.
The commit adjusts CSS styles to show the badge on top of icon, so that
the position of icon is not changed when counter is updated.
How to test the changes:
1. Log in as any user that has notifications;
2. Proceed to the Notifications Page;
3. Mark several notifications as "Read", so that amount of digits in notifications counter badge is changed (or mark all as read o make the badge disappear);
4. Focus on the bell icon.
Bell icon does not change its position.
Here are screenshots of how it looks:
**Before**
**After**
=> Show notifications counter on top of bell icon

src/api/app/controllers/webui/users/tasks_controller.rb, src/api/app/policies/users/task_policy.rb, src/api/spec/controllers/webui/users/tasks_controller_spec.rb, src/api/spec/policies/users/task_policy_spec.rb
Tackles `Webui::Users::TasksController`
Ref #10083
=> Replace `require_login` with Pundit in Webui::Users::TasksController

src/api/app/views/webui/patchinfo/form/_issues.html.haml
This typo was introduced in #10120 when we addressed a RuboCop offense
Fixes #10260
In the error message, you can see that `issuesum` is a permitted parameter, but `issuesumi` is not.
=> Fix typo in issue types

src/api/app/assets/stylesheets/webui/responsive_ux/grid.scss
Sidebar items were hidden over the viewport boundaries when sidebar does
not fit into the screen.
The commit adds CSS styles to show scrollbar when the items in sidebar
go over the viewport boundaries.
To verify the feature:
1. Log in to the application;
2. Decrease browser's height, so that sidebar items go out of viewport boundaries;
3. Focus on the sidebar.
Scrollbar appears. All the previous behavior remains same (e.g. scrollbar is not moving when scrolling the content area).
Here are screenshots of how it looks:
**Before**
**After**
=> Make sidebar scrollable if it does not fit into viewport

src/api/app/views/webui/projects/pulse/_pulse_list_requests_box.html.haml
=> Fix typo on pulse page

src/api/lib/obsapi/markdown_renderer.rb, src/api/spec/helpers/webui/markdown_helper_spec.rb
An empty URL part in markdown text leads to an exception
in the mardown renderer. When a comment
includes such an empty URL string, it ends up with a
code 500. This happens when people post code examples
which contain the same syntax as a markdown link.
Instead of throwing an exception, we can just render
the original content incase of an empty URL part.
Kudos to @eduardoj
Fixes #10259
=> Prevent exception on empty URL in markdown text

src/api/app/assets/javascripts/webui/notification.js, src/api/app/views/webui/users/notifications/_notification_action_bar.html.haml, src/api/app/views/webui/users/notifications/_notifications_list.html.haml
The button on the notification page was disabled through
a CSS class, which only lead to a disabled look, but still
allowed to submit the form.
Fixes #10248
There was no feedback to the user when marking notifications
as read and unread. When marking a bigger amount of notifications
it can take a bit to update the view, which might lead to additional
submit attempts. By showing a spinner and disabling the button
we can prevent this from happening.
=> Disable buttons properly and show spinner on submit in notifications list

src/api/app/controllers/webui/users/subscriptions_controller.rb, src/api/app/policies/event_subscription/form_policy.rb, src/api/spec/controllers/webui/users/subscriptions_controller_spec.rb, src/api/spec/policies/event_subscription/form_policy_spec.rb
Tackles `Webui::Users::SubscriptionsController`
Ref #10083
=> Replace `require_login` with Pundit in Webui::Users::SubscriptionsController

src/api/app/controllers/webui/users/rss_tokens_controller.rb, src/api/app/policies/token/rss_policy.rb, src/api/spec/controllers/webui/users/rss_tokens_controller_spec.rb, src/api/spec/policies/token/rss_policy_spec.rb
Tackles `Webui::Users::RssTokensController`
Ref #10083
=> Replace `require_login` with Pundit in Webui::Users::RssTokensController

src/api/app/views/webui/project/index.html.haml
**Create Project from the Actions menu**
=> Move Create Project actions to the sidebar under the Actions section

src/api/app/views/webui/groups/index.html.haml, src/api/app/views/webui/users/index.html.haml, src/api/spec/features/beta/webui/groups_spec.rb, src/api/spec/features/beta/webui/users/admin_configuration_spec.rb
**Create Users from the Actions menu**
**Create Groups from the Actions menu**
=> Move actions to sidebar on the configuration page

src/api/app/views/webui/user/user_profile_redesign/_involvement_and_activity.html.haml, src/api/app/views/webui/users/show.html.haml, src/api/lib/tasks/dev.rake
New layout for the user profile page. Distributing _Involved Projects/Packages_ and _Contribution Graph_ in tabs when both are present.
**No tabs when Contribution Graph is disabled:**
**Tabs when Contribution Graph is enabled:**
**No tabs on small viewports no matter if the Contribution Graph is desabled or enabled**
=> User profile layout redesign

src/api/app/lib/backend/logger.rb
This should have been included in #10283. It was overlooked in the review process.
=> Fix TypeError in Backend::Logger

src/api/config/environments/test.rb
=> Enable extended_backend_log in test environment

src/api/config/initializers/nokogiri_builder.rb, src/api/spec/cassettes/SourceProjectPackageMetaController/GET_show/package_description_includes_carriage_return_characters/1_1_3_1.yml, src/api/spec/cassettes/SourceProjectPackageMetaController/GET_show/package_do_not_exist/1_1_2_1.yml, src/api/spec/cassettes/SourceProjectPackageMetaController/GET_show/package_exist/1_1_1_1.yml, src/api/spec/controllers/source_project_package_meta_controller_spec.rb
The carriage return character '\r' gets escaped by
nokogiri/libxml which causes the character to be
rendered in the xml output.
https://github.com/sparklemotion/nokogiri/issues/1356
Since this is a valid xml char we can workaround this problem
by unescaping it again.
Fixes #10272
=> Unescape carriage return char in nokogiri xml output

src/api/app/controllers/request_controller.rb, src/api/app/models/bs_request_permission_check.rb, src/api/lib/api_error.rb
This exception class got overlooked on the move to Zeitwerk
Fixes #10299
=> Correctly load PostRequestMissingParameter exception class

src/api/app/views/webui/user/_change_password.html.haml, src/api/app/views/webui/user/_edit_account.html.haml, src/api/app/views/webui/user/_index_actions.html.haml, src/api/app/views/webui/user/_info.html.haml, src/api/spec/features/beta/webui/users/user_home_page_spec.rb
We want to move all user's profile page action links into the left menu, inside the Actions area.
Those actions are, **Edit your account** and **Change your password**
This is how it looks like on small screens:
This is how it looks like on large screens:
=> Move the actions present in the user's profile page to the left menu

src/api/app/views/webui/package/binaries/_show_statistics_job_history_build_reason.html.haml
This is to avoid using the same `fa-list` icon as the `All Projects` link in the `Places` links.
Before:
Now:
=> Use history icon for 'Job History' link

src/api/Gemfile.lock
All 0.1.x versions got yanked. Let's avoid this for the forseeable
future.
=> Update codecov to 0.2.12

src/api/app/views/webui/user/_edit_account.html.haml, src/api/app/views/webui/user/_index_actions.html.haml, src/api/app/views/webui/user/_info.html.haml, src/api/spec/features/beta/webui/users/user_home_page_spec.rb
The PR #10263 moved links for account managing to sidebar. Since sidebar
became collapsible in #10293, those links have to be wrapped into
span.nav-item-name. Also, title should be specified for them.
The commit adds those missing wrappers and titles, and also capitalizes
the links to make them consistent with the other links in sidebar.
Here are the screenshots of how it looks:
**Before**
**After**
=> Wrap sidebar links with span.nav-item-name

src/api/app/views/webui/groups/index.html.haml, src/api/app/views/webui/project/index.html.haml, src/api/app/views/webui/users/index.html.haml
Some of wrappers for links were mistakenly added in the PR #10293. Since
the links are not used in sidebar, they do not need to be wrapped into
span.nav-item-name.
The commit removes the extra wrappers.
=> Remove wrapper from links that are not in sidebar

src/api/app/views/webui/staging/workflows/edit.html.haml
While [editing a Staging Project](https://github.com/openSUSE/open-build-service/pull/10277), this is how it looked like before:
And this is how it looks like now:
=> Move relevant Staging Projects Management actions under the Actions section on the left menu

src/api/app/views/webui/users/index.html.haml, src/api/spec/features/beta/webui/users/admin_configuration_spec.rb
The action is now on the right of the Manage User's heading
This is how it looked like before:
=> Move Create User action next to the heading of the Manage Users page

src/api/app/views/webui/main/_status_messages.html.haml, src/api/app/views/webui/main/responsive_ux/_index_actions.html.haml
The Create Status Message action is best placed near its context, the News box,
where the status messages live.
This is how it looked like before:
And this is how it looks like now:
=> Move the Create Status Message back to the News box

src/api/app/assets/javascripts/webui/application.js, src/api/app/assets/javascripts/webui/user_profile.js, src/api/app/views/webui/user/_involvement.html.haml, src/api/app/views/webui/user/user_profile_redesign/_involvement_and_activity.html.haml
If the Contribution Graph is enabled, the 'Involved Projects/Packages' list can be displayed inside a simple card or inside a tab according to the viewport size.
Instead of rendering the same partial ('_involvement.html.haml') twice and using CSS to show/hide one or the other according to the viewport size, now we inject the content of the partial in the right place using JavaScript.
Preventing duplication is needed because it brings conflicts when selecting other elements in the view by JavaScript.
Follow-up of: #10271
=> Prevent duplication for involved projects/packages

src/api/app/views/webui/groups/_group_members.html.haml, src/api/app/views/webui/groups/show.html.haml
While managing members of a group, this is how it looked like before:
And this is how it looks like now:
=> Move "Add Group Member" action next to heading of group#show page.

src/api/app/views/webui/user/_edit_account.html.haml
The link shows still shows the text when the navigation
is collapsed
=> Use correct css class for edit account link in collapsible nav

src/api/app/controllers/webui/users_controller.rb, src/api/app/models/user.rb, src/api/app/views/webui/user/_edit_dialog.html.haml, src/api/app/views/webui/user/user_profile_redesign/_info.html.haml, src/api/app/views/webui/users/show.html.haml
This time we try to improve the user profile page adjusting positions, margins/paddings and sizes of the different elements. Paying special attention to the avatar and displaying related information together.
The Contribution Graph is now embedded in a tab.
The same happens with the list(s) of projects/packages where the user is involved. How we display this list(s) is going to be changed, but not in this PR.
**Before:**
**After:**
The animation shows the user biography, however, the field will be really added to this PR as soon as [this one](https://github.com/openSUSE/open-build-service/pull/10292) is merged.
TODO:
- Make fields like `biography`, `name` and `email` editable inline when that's possible. In another PR.
**NOTE:** This PR requires to enable the feature flag in production …
=> User profile page redesign

src/api/app/controllers/webui/users_controller.rb, src/api/app/views/webui/user/_edit_account.html.haml, src/api/app/views/webui/user/user_profile_redesign/_basic_info.html.haml, src/api/app/views/webui/user/user_profile_redesign/_edit_account_form.html.haml, src/api/app/views/webui/user/user_profile_redesign/_info.html.haml, src/api/app/views/webui/users/edit_account.js.erb, src/api/app/views/webui/users/show.js.erb, src/api/app/views/webui/users/update.js.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/users_controller_spec.rb
When the authentication is handled by a proxy, biography is the only attribute editable. Otherwise, biography, name and email can be edited.
**Without proxy:**
**With proxy:**
Co-authored-by: Oleksandr Orlov <oorlov@suse.com>
DO NOT MERGE until #10295 is merged.
=> Allow inline edition for user profile page

src/api/app/controllers/webui/users_controller.rb, src/api/app/views/webui/user/user_profile_redesign/_involvement.html.haml
Fix P2: #10332 
An aftermath from #10313, calls to `User#involved_items` or `User#involved_items_as_owner` could be probably cached.
Pagination looks like:
=> Add Pagination for WebUI::UsersController#show involved items

src/api/config/environments/production.rb
We want DJ logs to only appear as debug logs. And ActiveJob logs
as info logs.
=> Change Delayed::Worker.default_log_level to debug

src/api/app/jobs/project_create_auto_cleanup_requests_job.rb
Order the validations by complexity. The fastest validation should run first
=> Refactor method project_ready_to_autoclean?

src/api/app/jobs/project_create_auto_cleanup_requests_job.rb, src/api/spec/jobs/project_create_auto_cleanup_requests_job_spec.rb
Date.parse is more robust when dealing with empty strings or
out of the range dates
Some projects in production set an invalid value to the `OBS:AutoCleanup` to avoid being auto cleaned. Examples:
Project: home:mvdlinde_ger:tiefflieger
Project: home:lenovo-lico:lico-dep:5.1:el6
Project: home:Coollinux101:branches:openSUSE:Templates:Images:42.3
Project: home:maelhabashy
Project: home:taslim.tanim
=> Use Date.parse instead of Time.now.parse to parse user controlled date

src/api/app/jobs/measurements_job.rb, src/api/config/clock.rb
Measure the number of groups ~every time a group is created or destroyed~, ~hourly~, each five minutes.
Tḧe number of groups changes not so often. However, we need to measure frequently to avoid graphic panels with "No data" in Grafana.
=> Introduce group measurements

src/api/app/jobs/measurements_job.rb, src/api/app/models/user.rb
Before we measured if a user left or joined the beta program, that didn't provide the total amount of beta users.
=> Change measurement of the number of beta users

src/api/app/controllers/application_controller.rb, src/api/app/controllers/webui/webui_controller.rb
If they report the same things with the same tag names and content,
it's easier to visualize things that go across namespaces.
=> Syncronize UI and API measurement tags

src/backend/call-service-in-container, src/backend/call-service-in-docker.sh
This patch should enable network access for the node_modules service
in containers (docker/podman).
service passed audit successfully, SEE
https://bugzilla.suse.com/show_bug.cgi?id=1177576
=> [backend] enable network access for node_modules

dist/obs-server.spec
Also move preinstall scripts to the same section in the
specfile where all other pre scripts are
=> [dist] in obs-server.spec prereq shadow for system-user packages

src/backend/BSPublisher/Container.pm, src/backend/bs_publish
We already switched to sha256 if the project contains a RSA key.
This does not work for the default signkey, as we do not get
the pubkey algorithm in this case.
We now derive the algo from the pubkey if the default signkey
is used.
=> [backend] try to use sha256 when the default signkey is used

src/api/app/jobs/daily_user_activity_measurement_job.rb, src/api/app/jobs/measurements_job.rb, src/api/config/clock.rb
As the `last_logged_in_at` user's field does not track the time, measuring this
every 5 minutes makes no sense.
=> Run the job that tracks the amount of user log ins once a day

src/api/app/views/webui/shared/_sign_up.html.haml
Only show the "or Log In" option if no user is logged in
Fixes #10326 
Before Screenshot:
After Screenshots:
=> Only show log in option if no user is logged in

src/backend/BSConfig.pm.template, src/backend/BSSched/ProjPacks.pm, src/backend/bs_srcserver
=> [backend] bs_srcserver allow tuning maxchilds via config

src/backend/bs_worker
=> [backend] support exitstatus 4 as unrecoverable worker failure

src/backend/BSXML.pm, src/backend/bs_worker
This allows in reproducible builds to build with the prjconf used for the old build.
Fixes #10020.
Co-authored-by: Sumit Jamgade <sjamgade@suse.de>
=> [backend] Include the expanded buildconfig inside buildenv

src/backend/BSSched/EventHandler.pm, src/backend/BSSched/ProjPacks.pm, src/backend/bs_admin
=> Speed up removal of projpacks_linked entries in get_projpacks_postprocess_projects

src/api/app/controllers/webui/groups/users_controller.rb, src/api/app/views/webui/groups/_group_members.html.haml, src/api/app/views/webui/groups/_group_members_delete_dialog.html.haml, src/api/spec/controllers/webui/groups/users_controller_spec.rb, src/api/spec/features/beta/webui/groups_spec.rb, src/api/spec/features/webui/groups_spec.rb
Add a confirmation dialog when you delete a user from a group
Fixes #10316
1. Log into admin account
2. Go to a group (Configuration -> Manage Group -> go to group or create a new one)
3. Delete a member of the group (first add a user if none is present)
You should now see this dialog:
=> Add confirmation dialog to group members delete

src/backend/BSSched/ProjPacks.pm, src/backend/bs_sched
We now maintain a new projpacks_linked_blks hash that stores
the size of the same-project blocks in the corresponding
projpacks_linked entry. Using this we can for one skip the
blocks much faster if the project does not match and we
also can remove the block with one single splice call.
This speeds up the removal phase considerably. It no
longer dominates the time used in setup_projects.
=> [backend] speed up removal of old projpacks_linked data

src/api/app/helpers/webui/user_helper.rb, src/api/app/views/webui/users/_delete_dialog.html.haml, src/api/spec/features/beta/webui/users/admin_configuration_spec.rb, src/api/spec/features/webui/users/admin_configuration_spec.rb
The confirmation for deleting a user was a plain `confirm()` . This changes it to use the standard confirmation dialog.
Fixes #10383
1. Log into admin account
2. Go to manage users (Configuration -> Manage Users)
3. Delete a user
Before:
After:
=> Change user plain delete confirmation to use standard dialog

src/api/app/views/webui/staging/workflows/_staging_project.html.haml
Make the staging muted delete icon a popover so the reason why it isn't available stays readable. Works better for mobile.
Fixes #10302
1. Create a staging workflow with `bundle exec rake dev:staging:data`
2. Start the application with `bundle exec rails s -b 0.0.0.0`
3. Go to http://localhost:3000/staging_workflows/name-of-project-created-in-step-1/edit
4. Click on delete icon and a popover should appear which explains why it is disabled
=> Make staging muted delete icon a popover

src/backend/BSSched/EventQueue.pm, src/backend/bs_repserver
=> [backend] also log when processing 'built' events

src/api/app/models/role.rb, src/api/db/data/20201112083506_remove_role_user.rb, src/api/db/data_schema.rb, src/api/spec/models/role_spec.rb
At the commit https://github.com/openSUSE/open-build-service/commit/4204a68c21941b477b61dbfaa6ba6ac330d2a4d4 in the database seeds, the role "User" is associated to the "Admin" user, but not to the "nobody" user.
From this, I'm guessing that this role was used only on "real" users. We can also see that in the commit https://github.com/openSUSE/open-build-service/commit/e523b55785b0714fa658868fee629056b64c1bf7. Users are created, then are assigned the role "User".
In the commit https://github.com/openSUSE/open-build-service/commit/ae9bba8076117282e03bc47665d26c92e9e23c70, the role "User" was commented out in the database seeds.
Why? I don't know, but it might be related to the next paragraph.
In the commit https://github.com/openSUSE/open-build-service/commit/5ae5084e9e63469c9303d6f1baf1af0 …
=> Create data migration to remove role "User"

src/api/app/helpers/webui/markdown_helper.rb, src/api/spec/mailers/event_mailer_spec.rb
After a long debugging section with @eduardoj and @krauselukas we were able to pin-point a problem: In the [SendEventEmailsJobs](https://github.com/openSUSE/open-build-service/blob/master/src/api/app/jobs/send_event_emails_job.rb#L9) the `send_mail` call was changing the value of the variable `event`. We found out that our custom Markdown Render is mutating a variable exactly here https://github.com/openSUSE/open-build-service/blob/master/src/api/lib/obsapi/markdown_renderer.rb#L14
Beside it, we fixed a wrong assumption in the `event_mailer_spec.rb`. The text part from the multipart email shouldnt have any rendered markdown present.
=> Refactor event mailer

src/backend/BSSched/EventQueue.pm
=> [backend] remove superflous newline in log message

src/backend/BSSrcServer/SQLite.pm, src/backend/bs_srcserver
No need to use a global variable. What was I thinking...
=> [backend] sqlite: cleanup up package caching code

src/api/app/assets/javascripts/webui/comment.js, src/api/app/assets/stylesheets/webui/comments.scss, src/api/app/controllers/webui/comments_controller.rb, src/api/app/views/webui/comment/_comment_field.html.haml, src/api/app/views/webui/comment/_new.html.haml, src/api/app/views/webui/comment/_reply.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/comments_controller_spec.rb, src/api/spec/features/beta/webui/comments_spec.rb, src/api/spec/features/webui/comments_spec.rb
It is easy for a MD formatted text to come out looking wrong due to a
typo.
The PR adds Preview tab for comment section, so that it is possible
to view the formatted with markdown comment before saving it.
Fixes #10019
1. Log in to the application;
2. Go to any page, where comments section exists (e.g. select "Your Home Project" in the sidebar);
3. Type any comment with markdown in "Write" tab of comment section;
4. Select "Preview" Tab.
The comment is shown with rendered markdown. Please, see the GIF below on how it looks:
=> Add preview for the comment markdown

src/api/lib/tasks/dev.rake
For the rake tasks to be searchable with `rake -T` they must have a description.
This PR adds the missing descriptions for those rake tasks.
=> Add description to the development tasks that miss them

src/api/app/controllers/trigger/errors.rb
The `/trigger/runservice` route will respond with an error if used with an improper authorization (e.g. plain http auth). The error message was not a complete sentence, which is now fixed.
=> [api] Improve error message of /trigger/runservice route

src/api/app/views/webui/request/show.html.haml
This changes the title that gets displayed for a request to include the action name if only one action exists for that request. Otherwise it only displays the request number.
Fixes #1655
To verify this feature:
1. Start sphinx `bundle exec rake ts:start`
2. Create development test data `bundle exec rake dev:development_testdata:create`
3. Open rails console `bundle exec rails c`
4. Create another action for a request e.g. like this `BsRequestAction.create(bs_request_id: 7, type: "submit", target_project: Project.first, target_package: Package.first, source_project: Project.second, source_package: Package.second)`
5. Start the rails server `bundle exec rails s -b 0.0.0.0`
6. Visit the requests page to see one with multiple actions (http://localhost:3000/request/show/7) and another without …
=> Show request action name in the page title if only one action exists

src/backend/BSPublisher/Container.pm, src/backend/bs_publish, src/backend/bs_signer
The code used to be different in the publisher and the signer.
The publisher used to ignore bad signkeys (i.e. too small
signkeys), whereas the signer just used the keys. This was
changed in commit 27cfcb1aaffbf0e0ba2c0cf06ce87a0373c0a563
which made both versions of the code ignore bad signkeys.
It turned out that doing this has the disadvantage that we
do not catch configuration errors anymore which used to
result in the signer complaining about a bad signkey.
So this coomit changes the code in both the signer and the
publisher to again pass bad signkeys to the signer.
=> [backend] allow calling the sign tool with a bad signkey

src/api/lib/xpath_engine.rb, src/api/test/functional/binary_release_test.rb
not($attribute) is basically an existens check as defined by w3
real test case is
/search/released/binary/id?match=[starts-with(repository/@project,"project")+and+not(@medium)]
but we do not have iso media in fixtures yet
patch created by adrian, applied in IBS since Mach 2019
=> [api] fix behaviour of not() operation in xpath query

src/api/app/assets/javascripts/webui/comment.js, src/api/app/assets/javascripts/webui/tabs.js, src/api/app/views/webui/comment/_comment_field.html.haml, src/api/app/views/webui/comment/_new.html.haml, src/api/app/views/webui/comment/_reply.html.haml
It is not clear how to collapse comment section once it is expanded
while editing or replying.
The PR adds "Cancel" button for this purpose.
1. Log in to the application;
2. Go to any page, where comments section exists (e.g. select "Your Home Project" in the sidebar);
3. Create a comment if there are no ones;
4. Press "Reply" or "Edit" buttons;
5. When the comment section is expanded, press "Cancel" button.
Comment section is collapsed.
**Before**
**After**
=> Add Cancel button to comment section

src/api/app/views/webui/projects/maintained_projects/index.html.haml
**Before this change:**
**After this change:**
=> Move 'Add Maintained Project' action next to Maintained Projects Header

src/api/app/views/webui/kiwi/images/_base_info.html.haml, src/api/app/views/webui/kiwi/images/_package_fields.html.haml, src/api/app/views/webui/kiwi/images/_preferences.html.haml, src/api/app/views/webui/kiwi/images/responsive_ux/_actions.html.haml
Before:
After:
In the screenshot below, the `Add package` link cannot be migrated next to the header `Packages` since it's depending on the data from `fields_for`: https://github.com/openSUSE/open-build-service/blob/3ce10d89bdefb05fa8ea6c75e12c2247c8905a4b/src/api/app/views/webui/kiwi/images/_packages.html.haml#L6
=> Migrate actions for Kiwi Images

src/api/app/views/webui/projects/maintained_projects/index.html.haml, src/api/spec/features/beta/webui/maintained_projects_spec.rb
As this is a page action and not a contextual action it should be in the left Actions Sidebar.
=> Move the 'Add Project to Maintain' action to the left sidebar

src/api/app/views/webui/projects/maintenance_incidents/index.html.haml, src/api/spec/features/beta/webui/projects_spec.rb
=> Move Add Maintenance Incidents actions next to the Maintenance Incidents Header

src/api/app/controllers/webui/users_controller.rb, src/api/app/policies/webui/user_policy.rb, src/api/spec/controllers/webui/users_controller_spec.rb, src/api/spec/policies/webui/user_policy_spec.rb
Tackles `Webui::UsersController`
Ref #10083
=> Replace `require_login` with Pundit in Webui::UsersController

src/api/app/views/webui/groups/show.html.haml
Without this change, the `+` icon next to the `Group Members` heading would always be displayed in the responsive_ux UI. This is wrong when the currently logged-in user cannot update the group.
So the icon was still rendered, but clicking on it would do nothing since the modal was not rendered in the view, which is totally expected since the user shouldn't be able to see the icon in the first place.
The fix is to display the icon only when the user can update the group.
To reproduce that bug, visit https://build.opensuse.org/group/show/obs-developers and see the icon next to the `Group Members` heading. Click on it and nothing happens (unless you're allowed to update the group, it's not the case unless you're an admin or a maintainer in the group).
=> Display 'Add Group Members' link if the group can be updated

src/api/app/assets/javascripts/webui/user_profile.js, src/api/app/assets/stylesheets/webui/user.scss, src/api/app/views/webui/user/_edit_dialog.html.haml, src/api/app/views/webui/user/user_profile_redesign/_edit_account_form.html.haml, src/api/app/views/webui/users/show.html.haml
There is a limit of characters that can be typed in Biography textarea.
After the limit is reached, no characters can be entered. But there is
no visual hint on how many characters remaining.
The commit adds a counter that updates in real-time to show to the user
on how many characters remaining.
How to test the feature:
1. Login to the application;
2. Go to User Profile Page;
3. Press "Edit Your Account" in sidebar menu;
4. Type any characters to Biography textarea.
Once textarea become in focus, the counter is appeared in the bottom-right corner of the textarea. It shows how many characters remaining when typing.
**When responsive_ux is disabled**
**When responsive_ux is enabled**
=> Add characters count for User Biography

src/api/app/views/webui/project/_project_packages.html.haml, src/api/app/views/webui/project/responsive_ux/_show_actions.html.haml, src/api/spec/features/beta/webui/projects_spec.rb
The "Create Package" and "Branch Package" are contextual actions.
This change moves close to the "Packages" list that is their context.
**Before**
**After**
-->
=> Move "Create Package" and "Branch Package" from Project overview into the Packages section

ReleaseNotes-2.11, src/api/app/models/bs_request_action.rb
maintenance_release request actions takes default reviewers only from package
and update project. Not from GA project anymore.
patch from adrian, applied in IBS since Jul 2019
=> [api] maintenance_release request action default reviewer change

src/backend/BSSrcServer/Projlink.pm
Unfortunately the ':missing_packages' marker is hit by the regexp
catching multibuild packages. So special case it.
=> [backend] bs_srcserver: do not strip out the missing packages marker

src/api/app/assets/stylesheets/webui/sidebar-collapsible.scss, src/api/app/views/webui/project/responsive_ux/show_actions/_patchinfo.html.haml, src/api/app/views/webui/repositories/responsive_ux/_index_actions.html.haml, src/api/app/views/webui/shared/user_or_groups_roles/responsive_ux/_actions.html.haml
In some places we have multiple add/create actions in the
collapsible sidebar. In the collapsed state, there is no
distinction between the icons. Therefore we stacked
some icons to create a little more visiual separation
between them.
Co-authored-by: Oleksandr Orlov <oorlov@suse.com>
**Patchinfo**
**Users/Groups**
**Repositories**
Should we decide to go with the proposed solution, we will add this also to our pattern library
=> Stack action and corresponding resource icon

src/api/app/models/branch_package.rb
we ignore Update projects in one case but not the other with
ignoredevel=1. We ignored update project when no target was
specified, but we did not when a target project was specified.
We ignore always update project definitions now with ignoredevel=1
=> [api] fix inconsistency in branch handling

docs/api/api/api.txt
=> [api] fix runservice api docu via token

src/api/app/views/webui/project/side_links/_patchinfo_present.html.haml
To align with our pattern library.
Before:
Now:
=> Change the patchinfo icon

src/api/app/views/webui/groups/_group_members.html.haml, src/api/app/views/webui/groups/show.html.haml
As we're moving contextual actions close to their context, the 'Add Member'
action should go below the members list.
**Before**
**After**
=> Move the 'Add Member' action to the bottom of the group members list

src/api/app/views/webui/main/_status_messages.html.haml
=> Move the link to create new status messages

src/api/app/views/webui/attribute/index.html.haml, src/api/app/views/webui/attribute/responsive_ux/_index_actions.html.haml, src/api/spec/features/beta/webui/attributes_spec.rb, src/api/spec/features/beta/webui/projects_spec.rb, src/api/spec/support/features/features_attribute.rb
Before (responsive_ux)
Now (responsive_ux)
Now (without responsive_ux, nothing changed beside using an inline list instead of a paragraph)
=> Remove 'Add Attribute' action from sidebar

src/api/app/views/webui/users/index.html.haml
We move the "Create User" action next to the users list because both elements
are related to each other, so they should be next to each other.
**Before**
**After**
=> Move "Create User" from Manage Users tab to the bottom of the users list

src/api/app/views/webui/groups/index.html.haml
We are moving the "Add Group" action next to the group list because both
elements are related, so they should be next to each other.
**Before**
**After**
=> Move "Add Group" to the bottom of the group list

src/api/app/views/webui/projects/maintained_projects/index.html.haml, src/api/spec/features/beta/webui/maintained_projects_spec.rb
We move the "Add Projects to Maintain" action next to the maintained projects
because they are closely related to each other.
**Before**
**After**
=> Move "Add Projects to Maintain" below the list of maintained projects

src/api/app/views/webui/cloud/upload_jobs/index.html.haml
**Before (responsive_ux)**
**After (responsive_ux)**
=> Move action 'Cloud upload configuration' to sidebar

src/api/app/assets/javascripts/webui/kiwi_editor.js, src/api/app/views/webui/kiwi/images/_base_info.html.haml, src/api/app/views/webui/kiwi/images/responsive_ux/_actions.html.haml
Fixes an strange behaviour of showing different description elements. This happened not when the Details section was accessed directly with an URL, but when it was accessed clicking in the Details tab after clicking the Software tab.
Now this behaviour is assured:
- Show always the description (specification) of an image.
- Show Author and Contact fields only in Details tab.
=> Fix strange behaviour in image tabs

src/api/app/views/webui/projects/maintenance_incidents/index.html.haml, src/api/spec/features/beta/webui/projects_spec.rb
**Before (responsive_ux)**
**After(responsive_ux)**
=> Remove 'Create Maintenance Incident' from sidebar

ReleaseNotes-2.10.8, src/api/app/helpers/webui/markdown_helper.rb, src/api/spec/helpers/webui/markdown_helper_spec.rb, src/api/spec/mailers/event_mailer_spec.rb
Displaying the user input in a comment is now safer, using sanitize helper to prevent potential Cross-Site Scripting.
Tests are adapted accordingly.
Added Release Notes for 2.10.8.
This PR is an adaptation of: https://github.com/openSUSE/open-build-service/commit/ae51b7cd507954b41ace6b2688b856e63d12e33a
=> Prevent potential Cross-Site Scripting in markdown rendering

dist/obs-bundled-gems.spec
rework obs-bundled-gems.spec to do all compile and install
in the install section of the specfile as future rpm versions
will clean buildroot at the start of the install section
and bundle does not properly decouple compile and install
=> [dist] drop rpath from mysql2.so and move operations to install section

src/api/app/models/bs_request.rb
=> Fix tabs in Request#show for plain release requests

src/api/app/models/event/build.rb, src/backend/bs_repserver
=> [backend] repserver: also log the build type of finished jobs

src/api/app/models/worker_status.rb, src/api/spec/models/worker_status_spec.rb
A previous code refactoring introduced a change in the amount of registers inserted to be used in the system status graphic. This change made the graphic not to update correctly. See 1bde603dd744325de326e501bc27151ca65d5f37.
Revert part of this refactoring, to ensure that '0' values are inserted. This way the `resample` helper will work again with datasets with the same time limits.
Fixes #10517.
=> Fix worker status data inserted in status_history table, used in system status graphic in main page

dist/t/0060-check_required_services.ts
new version of systemd on Tumbleweed returns "alias" instead of "enabled" when running "systemctl is-enabled mysql.service
=> [dist] changed required service name from mysql to mariadb

dist/obs-bundled-gems.spec
After applying the changes to introduce the new minor release 2.10.8, we realized these changes introduced by Rüdiger Oertel are also necessary.
> Rework obs-bundled-gems.spec to do all compile and install in the install section of the specfile as future rpm versions
> will clean buildroot at the start of the install section and bundle does not properly decouple compile and install section.
Adaptation of 086e86379 by Rüdiger Oertel <ro@suse.de>. In the current version, we also needed to require `chrpath` for openSUSE 15.2.
=> [dist] drop rpath from mysql2.so and move operations to install

src/api/app/controllers/webui/main_controller.rb
Add missing section of reverting changes of 1bde603. The method `add_arrays` should not be called if one of the arrays is empty. This can happen when there aren't any workers defined for a certain architecture.
Also revert a refactoring in the architecture loop, in the same commit, preventing a duplication of the data retrieved for architectures that return the same value for the `Architecture#worker` method (for example: `x86_64` and `i586`).
Fixes #10517, again.
=> Fix system status graphic in main page, again

src/backend/bs_service, src/backend/bs_servicedispatch
This patch ensures that the BSConfig::service_timeout confiured on the
src_server is also used by servicedispatcher and service server.
=> [backend] global timeout for services

src/backend/BSDispatcher/Constraints.pm, src/backend/testdata/test_dispatcher
We try do something intelligent if we need to merge an include
and an exclude.
=> [backend] mergeconstraints: implement sandbox merging

src/backend/BSPublisher/Container.pm, src/backend/BSPublisher/Registry.pm
=> Use goarch instead of the scheduler arch when collecting containers

.github/PULL_REQUEST_TEMPLATE.md
Some PRs introduce changes that require special actions in the reference server. Actions that sometimes should be performed at a specific point of time.
This checklist can help us to identify if this PR needs special attention.
=> Add a checklist for deployment consideration to the PR template

src/api/config/clock.rb
We send all exceptions happening in the application to errbit. But we forgot to
capture exception in the Clockworkd service, and any exception not explicitly
handled is logged into the clockword.log only.
Fixes #10523
=> Capture exceptions and send them to errbit

src/api/app/controllers/webui/main_controller.rb
Add a guard clause to prevent doing calculations on empty ActiveRecord::Relation results.
Follow up to #10520.
=> Avoid exception when resampling busy workers

src/api/app/services/monitor_controller_service/status_history_fetcher.rb
The 'shared' option for Rails.cache was introduced in 8d02d03c with the DomainCacheStore definition, but in f5435b14 that definition was removed. So the 'shared' option cannot be used any longer.
=> Remove no longer needed Rails.cache 'shared' option

docs/api/api/api.txt
add /source/$project/$package?view=productrepositories to api.txt file
=> [api] add missing productrepositories view

docs/api/api/channel.rng, src/api/app/models/channel.rb, src/api/app/models/package.rb, src/api/db/migrate/20201209105103_add_channel_disable_flag.rb, src/api/db/schema.rb
this disables the entire branching and not just skips repository
creation
=> [api] allow to disable entire channels

src/api/lib/tasks/make_user_an_admin.rake, src/api/lib/tasks/user_admin_rights.rb, src/api/spec/lib/tasks/user_admin_rights_spec.rb
In order to avoid repeating some mistakes made previously when dealing with data
on production, we've automated the process of granting and removing admin rights
to some specific user.
Fixes #10524
=> Add role removal rake task

src/api/app/controllers/webui/status_messages_controller.rb, src/api/app/policies/webui/status_message_policy.rb, src/api/spec/controllers/webui/status_messages_controller_spec.rb, src/api/spec/policies/webui/status_message_policy_spec.rb
Tackles `Webui::StatusMessagesController`
Ref #10083
=> Replace `require_login` with Pundit in Webui::StatusMessagesController

src/api/app/models/status/check.rb, src/api/db/migrate/20201210165142_add_unique_index_name_to_status_checks_table.rb, src/api/db/schema.rb
This PR addresses the [cop regarding an unique index missing](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsuniquevalidationwithoutindex) detected by [this depfu PR](https://github.com/openSUSE/open-build-service/pull/10545)
=> Adds a unique index on the name column on the status_checks table

src/api/config/options.yml.example, src/api/script/import_database.rb
In our reference server we always have a daily dump of the database available. Its compression format has changed from .bz2 to .xz. So we adapt the import_database script and config/options.yml.example.
=> Change compression format in import_database script

src/api/public/402.html, src/api/public/403.html, src/api/public/404.html, src/api/public/408.html, src/api/public/500.html, src/api/public/503.html
openFATE has been discontinued and should no longer be linked to as
there is no archive.
This commit is replacing the outdated references with the same text as
used in https://github.com/openSUSE/obs-landing/pull/276 referencing
github issues as the correct place for features as well as used for
issue reports.
Fixes #10566
=> Remove mentions of openFATE on error pages

src/api/public/402.html, src/api/public/403.html, src/api/public/404.html, src/api/public/408.html, src/api/public/500.html, src/api/public/503.html
Reverts the backend submodule update from openSUSE/open-build-service#10567
=> Revert "Remove mentions of openFATE on error pages"

dist/obs-bundled-gems.spec
I totally forgot to include this change in the PR https://github.com/openSUSE/open-build-service/pull/10588
=> Set rake version to 13.0.3 for obs-bundled-gems

CONTRIBUTING.md
The old link to the OBS team (https://github.com/orgs/openSUSE/teams/open-build-service)
in `CONTRIBUTING.md` returns HTTP 404.
I've just updated it.
=> Update broken link to OBS team in documentation.

src/api/app/models/status/check.rb, src/api/db/migrate/20201210165142_add_unique_index_name_to_status_checks_table.rb, src/api/db/schema.rb
This reverts commit 531e4d853ea57c2b9fd8d376ff94c0368fed9747.
This is causing issues in production. It crashes with duplicate entries... although they don't even exist.
This migration is not live on any system. On OBS, it was executed, but since it crashed, it was reverted. On IBS, a package containing the migration wasn't deployed yet, so it's definitely not executed!
=> Revert "Adds a unique index on the name column on the status_checks table

src/api/app/models/staging/workflow.rb, src/api/spec/models/staging/workflow_spec.rb
This fixes #7175.
I've added one validation with corresponding tests.
=> Validate presence of project on Staging::Workflow.

src/api/app/assets/stylesheets/webui/notifications_redesign/notifications.scss, src/api/app/models/user.rb, src/api/app/views/layouts/webui/responsive_ux/_top_navigation.html.haml
This includes a counter. All of this is displayed when the notifications_redesign feature is not enabled, so for users not in the
beta program.
The Tasks link in the Places menu is not changed.
Fixes #10611
Example with a lot of tasks (so yes, it scales):
=> Add Tasks link to the top navigation for users not in the beta program

dist/t/spec/features/0030_project_spec.rb
OpenQA tests were failing because we no longer have openSUSE Leap 15.1 in the
Repositories to add from.
See [OpenQA tests for Unstable](https://openqa.opensuse.org/group_overview/62)
=> Use an up to date distribution name

src/backend/BSSched/Remote.pm, src/backend/BSSrcServer/SQLite.pm, src/backend/bs_repserver, src/backend/bs_signer, src/backend/bs_srcserver
This should fix the issue where `.pkg.tar.gz` and `.pkg.tar.xz` Arch Linux packages are signed, but `.pkg.tar.zst` packages are not.
I believe the root cause was that some regexes were missed when support for zstd-compressed packages was added, specifically in `src/backend/bs_signer`. I added `zst` where needed and fixed `zstd` -> `zst` in a few other places (`.pkg.tar.zst` is the official file extension: https://github.com/archlinux/svntogit-packages/blob/81c75751713eba68479dab00b7d598be99e5e024/trunk/makepkg.conf#L146).
This is an example of a repo I created that exhibits the problem: https://download.opensuse.org/repositories/home:/chenxiaolong:/test/Arch/x86_64/. The repo metadata is signed, but the packages are not (missing `.sig` file).
This is another 3rd party repo I found where …
=> [archlinux] Update filename regexes to fix .pkg.tar.zst signing

src/backend/bs_publish
=> [backend] publish all ChangeLog.* files

docs/api/api/api.txt, src/api/app/controllers/issue_trackers_controller.rb, src/api/app/controllers/issues_controller.rb, src/api/config/routes/api_routes.rb
The `POST` route for issue trackers doesn't require an issue tracker id in path parameters. And the `create` method in the controller doesn't make use of any path parameters.
This is how issue_trackers routes looks like now:
```
issue_tracker_issue GET    /issue_trackers/:issue_tracker_id/issues/:id(.:format) issues#show                                                            
issue_trackers GET    /issue_trackers(.:format)                              issue_trackers#index                                                   
POST   /issue_trackers(.:format)                              issue_trackers#create                                                  
issue_tracker GET    /issue_trackers/:id(.:format)                          issue_trackers#show …
```
=> Remove unneeded path parameter for creating an issue tracker from apidocs documentation

src/api/lib/tasks/rollout.rake, src/api/spec/lib/tasks/rollout_spec.rb
Most of the rollout tasks like "all_on" or "from_beta" excluded the staff users. Semantically speaking it was confusing. As we no longer need that restriction, the staff are not excluded anymore.
We also add tasks to move the anonymous user (_nobody_) into or out of the rollout program. Something that is usually needed at the beginning or end of the rollout process.
This PR comes with an update of the developer documentation: [Steps for Rolling Out](https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-(Flipper)#steps-for-rolling-out)
[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-t …
=> Adjust the rollout tasks

src/backend/BSSched/EventSource/Directory.pm
Because of the typo the event generation time was missing, leading
to the publish statistics always having a wait time of zero.
=> [backend] fix typo in publish event generation

src/api/app/jobs/published_repositories_cleanup_job.rb, src/api/app/models/bs_request_action_maintenance_release.rb, src/api/config/options.yml.example, src/api/test/functional/maintenance_test.rb
After accepting maintenance release requests, the corresponding published repositories were removed inmediately. This broke some automated maintenance tests because the repositories were removed before the tests finished.
We have moved the cleanup to a delayed job, so the repositories will be removed some specific time after they are published.
=> Add job to delay the published repositories cleanup

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/person.yaml, src/api/public/apidocs-new/paths/person_register.yaml
The OpenAPI documentation for the `person#show` action.
=> Document person show endpoint

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/attribute_name.yaml, src/api/public/apidocs-new/components/parameters/namespace.yaml, src/api/public/apidocs-new/components/schemas/attribute.yaml, src/api/public/apidocs-new/components/schemas/namespace.yaml, src/api/public/apidocs-new/paths/attribute.yaml, src/api/public/apidocs-new/paths/attribute_namespace.yaml, src/api/public/apidocs-new/paths/attribute_namespace_attribute_name.yaml, src/api/public/apidocs-new/paths/attribute_namespace_attribute_name_meta.yaml, src/api/public/apidocs-new/paths/attribute_namespace_meta.yaml
Introduce the new "Attributes" group of operations. This group contains the documentation of all operations with API routes starting by '/attribute'.
To verify the documetation that has been introduced:
- Start the development environment
- Go to http://localhost:3000/apidocs-new/
=> Document '/attribute' API routes with OpenAPI

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/issue_name.yaml, src/api/public/apidocs-new/components/parameters/issue_tracker_name.yaml, src/api/public/apidocs-new/components/schemas/issue.yaml, src/api/public/apidocs-new/components/schemas/issue_tracker.yaml, src/api/public/apidocs-new/components/schemas/list_issue_trackers.yaml, src/api/public/apidocs-new/paths/issue_trackers.yaml, src/api/public/apidocs-new/paths/issue_trackers_issue_tracker_name.yaml, src/api/public/apidocs-new/paths/issue_trackers_issue_tracker_name_issues_issue_name.yaml
Introduce the new "Issue Trackers" group of operations. This group contains the documentation of all operations with API routes starting by '/issue_trackers'.
To verify the documetation that has been introduced:
- Start the development environment
- Go to http://localhost:3000/apidocs-new/
=> Document '/issue_trackers' API routes with OpenAPI 

src/api/public/apidocs-new/paths/issue_trackers_issue_tracker_name_issues_issue_name.yaml
Add double quotes to the sentence. This prevented the whole endpoint to be shown in the OpenAPI documetation.
=> Fix example of a not found response example, in issue trackers

src/api/config/routes/api_routes.rb
In the commit d759517, schedulers was added to the configuration resource in the routes. Its corresponding action was never created in ConfigurationsController. It could also never work since schedulers is not one of the default RESTful actions. It cannot be simply passed to the `only` option like that.
=> Remove configuration schedulers route for inexistent code

src/api/app/views/layouts/webui/responsive_ux/_login_form.html.haml
Do not redirect from the login modal. You are already on the page
you want to be on. Fixes #10654
=> Fix login modal redirection

src/api/public/apidocs-new/paths/issue_trackers_issue_tracker_name_issues_issue_name.yaml
I forgot to add a reference to this parameter `issue_tracker_name`, required for the "Show an issue of an issue tracker" endpoint:
`GET /issue_trackers/{issue_tracker_name}/issues/{issue_name}`
=> Add missing issue tracker name path parameter in OpenAPI documentation

src/api/app/controllers/person_controller.rb
This PR fixes the misleading error message thrown in [this endpoint](https://github.com/openSUSE/open-build-service/pull/10646)
=> Fix misleading error message

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/login.yaml, src/api/public/apidocs-new/components/schemas/person_tokens.yaml, src/api/public/apidocs-new/paths/person_login_token.yaml
Document get method for 'person/{login}/token' endpoint using OpenAPI.
You can go to http://localhost:3000/apidocs-new/ to check it out.
=> Document 'person/{login}/token' get method

docs/api/api/api.txt
The post method does not use the 'cmd' parameter.
The 'project' is only used in combination with the 'package'. This action will never create a token for a specific project, only for a package.
=> Correct 'person/<userid>/token' post method in apidocs

src/api/public/apidocs-new/OBS-v2.10.50.yaml
Is something missing?
Preview:
=> Add general documentation to API new documentation

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/unregisteredperson.yaml, src/api/public/apidocs-new/paths/person.yaml
The OpenAPI documentation for the `person#register` action.
You can test it in [our review-app](https://obs-reviewlab.opensuse.org/danidoni-document-person-register-endpoint/apidocs-new/#/Person/post_person_register)
=> Document person register endpoint

src/api/public/apidocs-new/paths/person_register.yaml
Just realized while reviewing another PR that the 403 response is missing
=> Add 403 response to person register endpoint OpenAPI docs

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/person_login_token_id.yaml
=> Document 'person/{login}/token/{id}' delete method

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/responses/bad_request_error.yaml, src/api/public/apidocs-new/components/responses/not_found.yaml, src/api/public/apidocs-new/components/responses/update_user_not_authorized.yaml, src/api/public/apidocs-new/paths/person_login.yaml
Document `person#post_userinfo` action.
=> Document person post_userinfo action

src/api/public/apidocs-new/components/responses/unknown_command_error.yaml, src/api/public/apidocs-new/components/schemas/unregistered_person.yaml, src/api/public/apidocs-new/paths/person.yaml
The OpenAPI documentation for the `person#command` action.
You can test it in [our review-app](https://obs-reviewlab.opensuse.org/danidoni-document-person-command-action/apidocs-new/#/Person/post_person)
=> Document person command action

src/api/app/controllers/distributions_controller.rb, src/api/app/views/distributions/_distribution.xml.builder, src/api/app/views/distributions/index.xml.builder, src/api/app/views/distributions/show.xml.builder, src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/distribution_id.yaml, src/api/public/apidocs-new/components/responses/distributions.yaml, src/api/public/apidocs-new/components/schemas/distributions.yaml, src/api/public/apidocs-new/paths/distributions.yaml, src/api/public/apidocs-new/paths/distributions_distribution_id.yaml, src/api/public/apidocs-new/paths/distributions_include_remotes.yaml, src/api/test/functional/distributions_controller_test.rb
This adds the "distributions" group to the new OpenAPI documentation.
Note that I found the old documentation to be at times outdated. So I tried to also update the documentation with more up to date information.
To verify the new addition to the documentation:
- Start the development environment
- Go to http://localhost:3000/apidocs-new/
=> Document '/distributions' API routes with OpenAPI

src/backend/bs_repserver
It can be different if the metadata changes in weird ways, e.g.
if a package is moved into a module.
=> [backend] make sure that the local dod package matches our expectations

src/api/public/apidocs-new/components/responses/person/not_found.yaml, src/api/public/apidocs-new/components/schemas/person.yaml, src/api/public/apidocs-new/components/schemas/watchlist.yaml, src/api/public/apidocs-new/paths/person_login.yaml
The OpenAPI documentation for the `person#get_userinfo` action.
=> Document person get_userinfo action

src/api/public/apidocs-new/components/schemas/group.yaml
Preview in the documentation:
Before:
Now:
=> Add name to the group schema

src/api/public/apidocs-new/components/schemas/about.yaml
The title, description and revision elements are always present according to https://build.opensuse.org/schema/about.xsd, so I've marked them as such.
=> Mark properties of the /about route as required

src/api/config/brakeman.ignore
Following the update to [version 5.0.0](https://github.com/presidentbeef/brakeman/releases/tag/v5.0.0)
One false positive for "HTTP Verb Confusion" is now ignored. We don't want to pass the build to the backend if someone sends a HEAD request.
It was done with the following command: `brakeman -I`
=> Regenerate brakeman.ignore

src/api/app/views/webui/users/subscriptions/index.html.haml
A small thing I've noticed while we talked about the notifications this morning. Without the changes from this PR, the group titles are "humanized" (with [humanize](https://api.rubyonrails.org/classes/String.html#method-i-humanize)) in the _subscriptions#index_ view.
In the example below, the HTML stays the same: `<label class="custom-control-label" for="checkbox-group_1">`. The group is the following:
```
#<Group:0x000055d9652a7738 id: 1, created_at: Mon, 18 Jan 2021 15:45:19 UTC +00:00, updated_at: Mon, 18 Jan 2021 15:45:24 UTC +00:00, title: "group_1", parent_id: nil, email: "duane@jaskolski-nitzsche.co">
```
Before:
After:
Notes: Documentation for [label_tag](https://api.rubyonrails.org/classes/ActionView/Helpers/FormTagHelper.html#method-i-label_tag) if you are like me and don't …
=> Do not "humanize" group titles in subscriptions#index view

src/api/public/apidocs-new/paths/person_register.yaml
It's not needed, following the source code:
https://github.com/openSUSE/open-build-service/blob/436ce907fd7d6e2abc201410922d1aa87444883f/src/api/app/controllers/person_controller.rb#L11
=> Remove authentication requirement from POST /person/register documentation endpoint

src/api/public/apidocs-new/paths/person.yaml
Overlooked in a previous PR that this endpoint skips
the authentication
=> Remove authentication requirement from person POST OpenAPI docs

docs/api/api/obs.rng, src/api/db/migrate/20210201105103_linkedbuild_alldirect.rb, src/api/db/schema.rb, src/backend/BSSched/Checker.pm, src/backend/bs_srcserver
To allow rebuilds from directly linked projects only, excluding package
sources from indirect linked projects.
This is for example required to rebuild ServicePack layers only.
=> [api][backend] add linkedbuild=alldirect functionality

src/api/app/models/bs_request.rb
When a request is removed, its associated comments are removed.
But the notifications about those comments should be removed too, otherwise, the notifications page will raise an error.
To fix that, we replace `dependent: delete_all` by `dependent: destroy`.
=> Change the deletion option for comments of requests

src/backend/BSSched/Checker.pm
I messed it up on rebase it seems :/
=> [backend] fix linkedbuild=alldirect

src/api/app/jobs/cleanup_notifications_job.rb, src/api/app/queries/notifications_finder.rb, src/api/config/clock.rb, src/api/config/options.yml.example, src/api/spec/factories/notification.rb, src/api/spec/jobs/cleanup_notifications_job_spec.rb
Remove notifications older than a year with a daily job.
A `notifications_lifetime` config option can be set, to specify the number of days a notification persists before being removed.
=> Reintroduce CleanupNotifications job

.rubocop.yml, src/api/.rubocop.yml
This removes the following output when running RuboCop:
> Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
>   * rubocop-minitest (http://github.com/rubocop-hq/rubocop-minitest)
> 
> You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
>   AllCops:
>     SuggestExtensions: false
=> Opt out of suggestions for rubocop-minitest

src/api/app/helpers/webui/buildresult_helper.rb
Please refer to commits for details on the changes. This PR fixes #9936.
_Note: I didn't change this for the non-responsive_ux UI since this version isn't displayed anymore on our reference server._
Before:
Now:
=> Toggle build info when {click,hover}ing on build state 

src/api/app/views/webui/package/_job_status.html.haml, src/api/app/views/webui/package/live_build_log.html.haml
Previously architecture and repository were only shown to users in the
build log while the job was running. This commit changes this behavior,
so that they are displayed independently of the job status.
Fixes #10738
=> Unconditionally show architecture and repository

dist/t/spec/features/0020_interconnect_spec.rb, dist/t/spec/support/wait_for_ajax.rb
This is done in order to fix the OpenQA failures in
[here](https://openqa.opensuse.org/tests/1601017#step/rspec_webui_tests/13).
=> Wait for the Connect button to finish before checking the page content

src/api/app/assets/javascripts/webui/buildresult.js
After introducing another element with CSS class 'toggle-build-info' in a previous commit, clicking in one of this elements should change the title for all elements which have this class.
Prevent having one build info element with title 'Click to keep it open' and another element with title 'Click to close it' at the same time.
This is a follow-up of PR #10748.
**Before:**
**After:**
=> Show correct message when hovering build info elements

src/api/db/data/20210205131609_remove_notifications_for_missing_notifiables.rb, src/api/spec/db/data/remove_notifications_for_missing_notifiables_spec.rb
Add a data migration to remove dangling notifications that should have been removed when their associated comments where removed.
This is a follow-up of PR #10735.
**NOTE:** This PR contains a data migration but it won't cause any inconsistency or downtime.
=> Remove notifications for missing notifiables

dist/t/spec/features/0010_authentication_spec.rb, dist/t/spec/features/0020_interconnect_spec.rb, dist/t/spec/features/0030_project_spec.rb, dist/t/spec/features/0040_package_spec.rb, dist/t/spec/support/wait_for_ajax.rb
Doing so, the module under dist/t/spec/support/wait_for_ajax gets included
automatically on those feature specs
=> Mark all feature specs under dist directory as type: :feature

src/api/app/jobs/measurements_job.rb, src/api/app/models/notification.rb
Every newly created notification is tracked _in situ_.
Some other metrics like the amount of different kind of notifications are tracked every 5 minutes.
MeasurementsJob has been slightly refactored.
=> Track some metrics about notifications

src/backend/BSRPC.pm, src/backend/BSSSL.pm
Some servers will not work unless SNI is used to send the hostname.
=> [backend] support SSL SNI in BSSSL and BSRPC

src/api/app/assets/stylesheets/webui/comments.scss
Block quotes are not styled in web ui markdown comments.
The commit adds the appropriate styles in scss.
Fixes #10645
How to test the fix:
1. Go to any request;
2. Make a comment using markdown block quotes, eg.:
`> this is a block quote`
3. Submit the comment / click on preview tab.
Here are the screenshots of how it looks:
**Before**
**After**
=> Add style for markdown block quotes

docs/api/api/distributions.rng, src/api/app/controllers/distributions_controller.rb, src/api/app/models/distribution.rb, src/api/spec/controllers/distributions_controller_spec.rb
This PR is related to #10695
It fixes the POST endpoint of /distributions
It also introduces a spec to test the endpoint
To verify this feature:
1. Start dev environment
2. Look at current distributions `curl --user Admin:opensuse http://api.localhost:3000/distributions`
3. Make use of the POST /distributions endpoint for example like this:
Write these contents into a file e.g. `post.yml`:
```
<distributions>
<distribution vendor="opensuse" version="Tumbleweed">
<name>openSUSE Tumbleweed</name>
<project>openSUSE:Factory</project>
<reponame>openSUSE_Tumbleweed</reponame>
<repository>snapshot</repository>
<link>http://www.opensuse.org/</link>
<icon width="8" height="8" url="https://static.opensuse.org/distributions/logos/opensuse.png"/>
<icon width="16" height="16" …
```
=> Fix distributions POST endpoint

src/backend/BSConfig.pm.template, src/backend/bs_getbinariesproxy
=> [backend] make maxchilds also configurable for binaries proxy

dist/t/spec/features/0040_package_spec.rb
The aim of this pull request is to provide more information when the smoke tests fail building a package.
Now, when the build does not return with `succeeded`, there is no log or screenshot generated.
This pull request makes the tests fail when building a package does not return a `succeded` state. So log files and the screenshot will be generated, and will give more information about what failed.
To verify the changes, for the `succeed` status:
- Run the smoke tests locally, using this branch instead of master
- Run the test suite once, with `bundle.ruby2.5 exec rspec`
For next runs of the tests:
- Modfy the `spec/features/0040_package_spec.rb` file, comenting all the tests sections but the last one: `"should be able to successfully build"`.
- Run only that test, with `bundle.ruby2.5 …
=> Improve erroring in smoke tests

src/api/app/helpers/webui/user_helper.rb, src/api/app/views/webui/user/user_profile_redesign/_involvement.html.haml
Fix the "Clear current search ..." link when looking at another user's profile.
Fixes #10604
To verify this feature:
1. Start dev environment and make sure to start sphinx with `rake ts:start`
2. Log in as Admin and make sure 'Public beta program' is activated
3. Create another user
4. Go to that user's profile
5. Apply a filter
6. Click the "Clear current search..." link and observe that it now links the correct profile
=> Fix clear filters link on profiles

src/backend/BSRevision.pm, src/backend/bs_worker
When a package is deleted, all build results are lost including
the rebuild counter. So we habe to bump the vrev to make sure that
new builds get a higher revision.
=> [backend] bump vrev when undeleting a package

docs/api/api/api.txt, src/api/config/routes/api_routes.rb, src/api/script/start_test_backend, src/api/test/functional/channel_maintenance_test.rb, src/backend/BSConfig.pm.template, src/backend/BSXML.pm, src/backend/bs_check_consistency, src/backend/bs_srcserver
also enabling sqlite database on by default for new installations.
=> Repoinfo search interface

src/api/app/models/package.rb
The user can not guess which project is meaned in api error otherwise.
=> [api] report valid project name instead of internal database id

src/backend/bs_worker
Also use 'metamd5' instead of 'hdrmd5' when checking for the meta file.
=> [backend] bs_worker: clean up getbinaries_cache

src/api/test/functional/channel_maintenance_test.rb, src/backend/BSXPathKeys.pm, src/backend/bs_srcserver
=>  [backend] speed up repoinfo search, support repository searches

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Docker.pm, src/backend/BSSched/BuildJob/KiwiImage.pm, src/backend/BSSched/BuildJob/KiwiProduct.pm, src/backend/bs_sched
A download on demand repo can be on another partition or even
on a remote instance. So we need to always do the dodcheck so
that all needed dod binaries are available if a build job is
created.
Otherwise the workers do the dod fetching which leads to the
getbinaryversion calls blocking everything else.
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-fea …
=> Do dodfetch/dodcheck even if download_on_demand is not enabled

src/api/app/models/event/upload.rb, src/backend/bs_srcserver
=> [backend] add notification on data meta change

docs/api/api/api.txt, docs/ichain.txt, src/api/app/helpers/webui/user_helper.rb, src/api/app/lib/suse/permission.rb, src/api/app/models/bs_request_action.rb, src/api/app/models/user.rb, src/api/spec/controllers/webui/users/notifications_controller_spec.rb, src/api/spec/helpers/webui/user_helper_spec.rb, src/api/spec/helpers/webui/webui_helper_spec.rb, src/api/spec/models/package_spec.rb, src/api/spec/policies/comment_policy_spec.rb, src/api/test/fixtures/bs_requests.yml, src/api/test/functional/comments_controller_test.rb, src/api/test/functional/maintenance_test.rb, src/api/test/functional/person_controller_test.rb, src/api/test/functional/request_controller_test.rb, src/api/test/functional/search_controller_test.rb, src/api/test/functional/source_controller_test.rb
Replacing gendered terms 'he', 'his', 'guy' and 'he/she' with 'they', 'their' and 'person'. 
=> removed-gendered-terms

dist/obs-apache2.conf, dist/obs-apache24.conf
When Apache enters MAINTENANCE mode, the `/503.html` page is rendered. This page contains an image, that until now could not be rendered because of the Apache configuration. This pull request fixes this behaviour.
Apache MAINTENANCE mode is described in detail in our development wiki, as a step of deployments with migrations: https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org
To verify the fix:
- Download an OBS appliance.
- Inside the appliance:
- Set apache in maintenance mode: edit the `/etc/sysconfig/apache2` file and modify the line with the apache server flags to have: `APACHE_SERVER_FLAGS="SSL MAINTENANCE"`
- Modify the `/etc/apache2/vhosts.d/obs.conf` adding the line `RewriteCond %{REQUEST_URI} !=/obs-down.png`.
- Restart apache: `systemctl …
=> Show obs-down.png image when Apache is in MAINTENANCE mode

src/backend/bs_publish
=> [backend] bs_publish also rename ChangeLog files along with images

src/backend/bs_repserver
If we use http status code 200, apache will happily cache the
answer thinking it is the complete file.
=> [backend] use '206 Partial Content' to answer range requests

src/backend/bs_getbinariesproxy, src/backend/bs_repserver, src/backend/bs_srcserver, src/backend/bs_worker
log if the call stays in the queue for more than one minute
=> [backend] log if accepting getbinaries hangs

dist/obs-bundled-gems.spec
until upstream has fixed the code
=> [dist] workaround compiler warnings building nio4r

src/api/app/assets/stylesheets/webui/collapsible-text.scss, src/api/app/assets/stylesheets/webui/requests.scss, src/api/app/views/webui/request/_show_side_links.html.haml, src/api/app/views/webui/request/_update.js.erb, src/api/app/views/webui/request/show.html.haml
See commits for details. Fixes #10840
Before (the first request history element is partially hidden):
Now (the first request history element is fully visible):
=> Improve request history section

src/api/app/controllers/webui/staging/workflows_controller.rb, src/api/app/policies/staging/workflow_policy.rb, src/api/app/views/webui/project/_tabs.html.haml, src/api/spec/controllers/webui/staging/workflows_controller_spec.rb, src/api/spec/policies/staging/workflow_policy_spec.rb
This is a PR of a series which replaces require_login with Pundit.
Tackles `Webui::Staging::WorkflowsController`
Ref #10083
=> Replace `require_login` with Pundit in Webui::Staging::WorkflowsController

src/api/app/views/webui/package/responsive_ux/_buildstatus.html.haml
Add a bit of spacing to separate different information and use colors to highlight important information about the build state.
Fixes #10837
Before:
Now:
=> Improve how build status details are displayed

src/api/app/assets/stylesheets/webui/application.scss, src/api/app/assets/stylesheets/webui/bootstrap_variables/sizes.scss, src/api/app/assets/stylesheets/webui/responsive_ux/responsive_ux.scss
These variables used to define specific sizes in Bootstrap. They can be moved out, to a main file, now that we are going to get rid of the responsive_ux namespace.
=> Move SCSS variables out of responsive_ux namespace

src/api/app/models/user.rb
A case-sensitivity in the search create overhead since the
user needs to remember the exact case/capitalization of
packages/projects in order to find them.
Fixes #10833
**NOTE**: I considered directly using `Arel` to do the query since this way it is possible to get the default behavior of the `LIKE` query which is case-insensitve. Although the collation of our database is set to `utf8mb4_unicode_ci` (so case-insensitve) the `:name` column of project/package is `utf8_bin` (so case-sensitive) on the DB level. I would not change it for now, since this might introduce side-effects in other parts of OBS. I don't expect any performance issues with the provided solution, so I would avoid to use the sledgehammer to crack a nut;
=> Make involved packages/projects search case-insensitive

src/api/app/controllers/webui/repositories_controller.rb
To test it:
Visit https://obs-reviewlab.opensuse.org/opensuse-refactor_repositories_controller_distributions/project/add_repository_from_default_list/home:Admin
and all distributions should be there as usual.
=> Use group_by instead of iterate manually over all distributions

src/backend/bs_worker
Based on feedback from the linked mailing list post.
=> [backend] Add another ampere variant for aarch32 support

src/backend/BSSched/Checker.pm, src/backend/BSSched/DoD.pm, src/backend/bs_dodup
This data will be used by perl-BSSolv.
=> [backend] support moduleinfo data returned by the modules.yaml parser

src/backend/bs_signer
If we just copy the readytime, the followup jobs will appear
to have waited the build time of the first job.
=> [backend] reset readytime when creating followup jobs

src/backend/call-service-in-container
Without this patch on a service timeout call-service-in-container
process gets killed but container is still running. Some services
use locking and will block other service forever if the container
does not get removed properly
This patch ensures that the container gets stopped and removed
if call-service-in-container process gets killed by bs_service.
=> [backend] remove container on service timeout

src/backend/BSSched/RPC.pm, src/backend/bs_sched
We reduce our memory consumtion with two changes:
- we free the pool after we checked all packages (the pool is part of
the context, which is stored in the waiting handle)
- we do not enqueue entries that we already have
=> [backend] do not use so much memory when waiting for busy resources

src/api/app/views/webui/project/_basic_info.html.haml, src/api/app/views/webui/project/_breadcrumb_items.html.haml
Remove non-responsive code from the project basic_info partial and project breadcrumbs.
In project breadcrumbs, RuboCop complained with: "Style/IfInsideElse: Convert `if` nested inside `else` to `elsif`.". Moving the `if` clause inside the `else` to an `elsif`, fixed the linter.
=> Migrate projects to only responsive, 3rd round

src/api/app/controllers/webui/package_controller.rb, src/api/app/views/webui/kiwi/images/_base_info.html.haml, src/api/app/views/webui/main/index.html.haml, src/api/app/views/webui/package/show.html.haml
@eduardoj, @saraycp and I realized that we forgot to remove this in some of the recent responsive_ux PRs.
=> Remove unneeded path for `render partial: ...` calls

src/api/app/assets/javascripts/webui/notification.js
Without this change, the word "all" flickers since it's first rendered as "All", then replaced by "all" in the JavaScript code.
Just something I've noticed while working on something else... see for yourself below in this recording of the notifications overview page refreshing:
=> Capitalize select-all-label properly in the JavaScript code

src/backend/bs_sched
Publishing may create delta jobs, so the pool is still needed.
=> [backend] move pool freeing after the publish call

src/backend/bs_srcserver
Catch cases where the build type expects a specific filename.
Do no fall back to a suffix in that case.
Eg. only accept Dockerfile for docker type.
=> [backend] simplify build recipie detection code

src/backend/bs_worker
=> [backend] bs_worker fix up passing now= argument for binaries proxy

src/api/app/helpers/webui/webui_helper.rb
repository_info is still in use since it's for the responsive UI.
responsive_namespace isn't anymore in use, so it can be safely removed.
=> Remove non-responsive_ux code from helpers

src/api/lib/tasks/dev.rake
It's easier to join the beta and test changes related to feature flags while also being able to test changes for non-beta users, so without any feature flag enabled.
=> Enable feature flags for beta users in rake task dev:bootstrap

src/api/lib/tasks/dev.rake
The rake task uses an array of the enabled feature flags. We no longer need responsive_ux on it.
=> Drop responsive_ux flag from the rake task

src/api/spec/rails_helper.rb
It was a temporary solution during the migration.
Now that the code under responsive_ux is completely merged in the codebase, we can remove this.
=> Stop enabling responsive_ux feature flag for specs

src/api/app/assets/stylesheets/webui/layout.scss, src/api/app/assets/stylesheets/webui/sidebar-collapsible.scss
The specific CSS for the stack icons now affects both left and bottom navigation.
The rule for fa-warehouse is removed since that icon is no longer used.
=> Fix patchinfo stack icons for bottom navigation

src/backend/bs_srcserver
=> [backend] unbreak Arch build type

src/api/spec/features/beta/webui/users/user_contributions_spec.rb, src/api/spec/support/beta.rb
This feature flag is already enabled in the beta program. Let's enable it in the tests for beta features.
Only tests for the contribution graph had to be adapted.
=> Add user_profile_redesign flag to beta features' tests 

src/api/app/assets/stylesheets/webui/collapsible-text.scss, src/api/app/views/webui/user/user_profile_redesign/_involvement.html.haml
The description was displayed completely before, taking too much space.
Now it is reduced to two visible lines and a link to show more or less.
Part of #10831
**Before:**
**After:**
=> Make involved projects/packages description collapsible

src/api/config/initializers/airbrake.rb
A loop about enumerable returns the enumerable which is always something,
so true.
=> Fix airbrake ignore rules

src/api/app/views/webui/package/_basic_info.html.haml, src/api/app/views/webui/project/_basic_info.html.haml, src/api/app/views/webui/user/user_profile_redesign/_basic_info.html.haml
The links are now left-aligned with the rest of the elements, and there is not excessive space at the bottom nor between the icon and the text.
Follow-up of: #10905 
**Result:**
=> Adjust margin and padding on edit links

src/backend/bs_srcserver
This is highly experimental and tailored for our use case, so we do not
put it into the BSConfig.pm.template file.
=> [backend] add config option to disable sslcert caching for some projects

src/api/app/views/webui/user/_index_actions.html.haml, src/api/app/views/webui/user/user_profile_redesign/_basic_info.html.haml
I forgot the permission check to show the user profile form :facepalm:
Thanks to @dmarcoux for reporting it.
=> Fix the permission checks to show the edit user profile form

src/api/app/views/webui/user/_info.html.haml, src/api/app/views/webui/user/user_profile_redesign/_info.html.haml
The "Action on this page" for a user's profile shows:
- A link to "Edit Your Account", when that really changes the details of the
user on the page, even if its someone else than me.
- A link to "Change Your Password", that really changes "my" password.
This is confusing. I'm gonna hide that menu when visiting someone else's profile.
=> Hide the "Actions on this page" menu when visiting other user's page

src/api/app/views/webui/users/show.js.erb
This file  (_app/views/webui/users/show.js.erb_) should have been removed when the inline editing was modified and the cancel button no longer redirected to show.js.erb.
Moreover, the show.js.erb called a partial but one of the locals was missing.
Keeping this file causes errors when bots try to visit the former URL.
Fixes: #10934
=> Remove remaining show JS view file

src/api/app/views/webui/users/_breadcrumb_items.html.haml, src/api/app/views/webui/users/show.html.haml
Sometimes it's not clear if the user is on their own profile page or in someone else's one. This little change can give a clue.
=> Make clear that the user is on their own profile page

src/api/.rubocop_todo.yml, src/api/app/services/user_service/involved.rb
Superseds: #10918
Part of #10831
=> Sort involved projects/packages alphabetically

src/backend/call-service-in-container
The redirect of STDOUT/STDERR in call-service-in-container causes an
error in bs_service like
refcnt: fd -1 < 0
This patch removes the redirection.
=> [backend] remove redirect from call-service-in-container

src/api/app/lib/routes_helper/routes_constraints.rb, src/api/app/views/webui/groups/_group_members.html.haml, src/api/app/views/webui/groups/_group_members_delete_dialog.html.haml, src/api/config/routes/webui_routes.rb
Fixes #10955
Before, the `Delete group member` modal didn't appear for a user which has dots in their login.
The routes /groups/<group>/users/<user> were also not handling dots correctly, treating them as separators. Having a constraint for the user login solves this. This is documented in Rails, see https://guides.rubyonrails.org/routing.html#dynamic-segments
=> Handle dots in user logins for group members page/route

src/api/public/apidocs-new.html
Requests to /public/apidocs-new should be redirected to
/public/apidocs-new/. This fixes just in production, where we have the Apache webserver serving static content. It doesn't work in development mode.
Fixes #10631
=> Add file /public/apidocs-new.html to fix requests to /apidocs-new

src/api/app/controllers/request_controller.rb, src/api/app/models/bs_request.rb, src/api/app/models/bs_request/data_table/find_for_user_or_group_query.rb
Sorting the requests by the Source, Target or Type columns led to missing results.
This was caused by a wrong DISTINCT clause, that was taking fields from two tables (`bs_request_actions` and `requests`) instead of one (`requests`). Those extra fields in the DISTINCT clause were introduced by an `includes` finder method.
The problem was fixed by replacing the `includes` in the `.with_action` scope with a `joins` finder method, so the fields from
`bs_requests_actions` are no longer part of the DISTINCT modifier in the SQL sentence.
Additionally, the `includes` in the BsRequest::DataTable::FindForUserOrGroup#requests method was redundant. We add `preload(:bs_request_actions)` instead.
Fixes #10950.
If this PR …
=> Remove unnecessary `includes` in requests query

src/api/app/controllers/webui/users/patchinfos_controller.rb, src/api/app/datatables/tasks_maintenance_requests_datatable.rb, src/api/app/models/user.rb, src/api/app/views/webui/shared/_patchinfos_table.html.haml, src/api/app/views/webui/users/tasks/index.html.haml, src/api/config/routes/webui_routes.rb
Prevent N+1 queries for IssueTracker and User (it wasn't needed to load users, so this was dealt with by not fetching users anymore).
Fetch maintenance requests once the page is loaded.
Fixes #10959
=> Use server-side pagination for the maintenance requests table on the user tasks page

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/published.yaml
This `published/` endpoint ends up in the `SourceController#index` not in `PublishedController#index` as can be supposed.
It returns a list of the (published) projects.
~**NOTE:** The `published/`endpoint is going to list projects, repositories, architectures or binaries depending on the passed parameters. I can't find an appropriate Tag name for this group: `Published Elements`? `Published Sources` ? ... That's why I left the same name used in the old documentation: `Published Binary Package Tree`.~
**Edit:**
The group or tag name is finally going to be `Published Binaries`.
[1] https://github.com/openSUSE/open-build-service/wiki/Deployment- …
=> Document 'published/' get method

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/project_name.yaml, src/api/public/apidocs-new/components/parameters/repository_name.yaml, src/api/public/apidocs-new/paths/published_project_name.yaml, src/api/public/apidocs-new/paths/published_project_name_repository_name.yaml, src/api/public/apidocs-new/paths/published_project_name_repository_name_architecture_name.yaml
Different endpoints to get to the binaries list (projects -> repositories -> architectures -> binaries).
=> Published Binaries API documentation

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/worker_capabilities.yaml, src/api/public/apidocs-new/paths/worker_architecture_name_worker_id.yaml
Document `GET /worker/{architecture_name}:{worker_id}` endpoint with the OpenAPI definition.
This operation is the same as `GET /worker/capability/{architecture_name}:{worker_id}`.
=> Document worker capabilities endpoint with OpenAPI

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/binary_filename.yaml, src/api/public/apidocs-new/components/responses/download_binary_forbidden.yaml, src/api/public/apidocs-new/components/schemas/api_response.yaml, src/api/public/apidocs-new/components/schemas/ymp_pattern.yaml, src/api/public/apidocs-new/paths/published_project_name.yaml, src/api/public/apidocs-new/paths/published_project_name_repository_name.yaml, src/api/public/apidocs-new/paths/published_project_name_repository_name_architecture_name.yaml, src/api/public/apidocs-new/paths/published_project_name_repository_name_architecture_name_binary_filename.yaml, src/api/public/apidocs-new/paths/published_project_name_repository_name_architecture_name_binary_filename_view_ymp.yaml, src/api/public/apidocs-new/paths/published_project_name_repository_name_view_status.yaml
Document the rest of the `published/*` endpoints to:
- get the status of the building process
- download the binary
- generate a ymp pattern
Add a missing 403 error response that can happen on every `published/*` endpoint when the binary download is blocked.
=> Published binary, status and ymp endpoints

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/constraints.yaml, src/api/public/apidocs-new/paths/worker_cmd_checkconstraints.yaml
Document `POST /worker?cmd=checkconstraints` endpoint with OpenAPI.
This operation is the same as `POST /worker/command/run?cmd=checkconstraints`.
=> Document checkconstraints command for workers with OpenAPI

docs/api/api/obs.rng, src/api/app/models/project/update_from_xml_command.rb, src/api/app/views/models/_project.xml.builder
Esp. important for debian based distributions which are checked via GPG
=> [api] DoD: make sslfingerprint attribute optional

src/api/Gemfile, src/api/Gemfile.lock
See commit descriptions for details about each gem.
The only gem (beside rails) with a version constraint is jquery-ui-rails. I would like to get rid of the gem if possible, but if I manage to do this, I'll do it in another PR. Updating the gem also involves changes to the code.
=> Remove version constraints for gems

src/api/app/controllers/webui/groups/bs_requests_controller.rb, src/api/app/controllers/webui/groups/users_controller.rb, src/api/app/helpers/webui/group_helper.rb, src/api/app/helpers/webui/user_or_groups_roles_helper.rb, src/api/app/views/webui/groups/index.html.haml, src/api/app/views/webui/groups/new.html.haml, src/api/app/views/webui/search/_results_owner.html.haml, src/api/app/views/webui/shared/user_or_groups_roles/_list.html.haml, src/api/app/views/webui/staging/workflows/_infos.html.haml, src/api/app/views/webui/user/_info.html.haml, src/api/app/views/webui/user/user_profile_redesign/_info.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/groups/bs_requests_controller_spec.rb, src/api/spec/controllers/webui/groups/users_controller_spec.rb, src/api/spec/features/webui/groups_spec.rb
They are now all defined with resources and grouped together. Some route helpers slightly changed and were replaced with the following GNU sed commands:
```shell
sed -i -e 's/group_show_path/group_path/g' src/api/**/*{.rb,.haml}
sed -i -e 's/group_new_path/new_group_path/g' src/api/**/*{.rb,.haml}
sed -i -e 's/group_create_path/groups_path/g' src/api/**/*{.rb,.haml}
```
I didn't find any `_url` version of the route helpers for those routes, so nothing had to change for this.
=> Simplify how webui routes are defined for groups

src/api/app/controllers/person_controller.rb, src/api/app/controllers/webui/architectures_controller.rb, src/api/app/controllers/webui/groups/users_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb
Do case insensitive string comparison as suggested by rubocop.
=>  Do case insensitive comparison on string parameter

src/api/app/views/webui/architectures/index.html.haml
Without this change, it isn't possible to enable a single architecture since the `available` param was never sent.
**Edit:**
To reproduce the bug log in as Admin, go to _Configuration > Architectures_, try to add a new architecture (check), refresh the page, and then you'll see it appears unchecked again.
With this fix, the added architecture keeps checked.
=> Fix broken checkboxes for architectures

src/api/spec/controllers/trigger_controller_spec.rb
Quick fix to make the circleci green. Who is working in this spec, should fix it
=> Disable locally the rubocop to make circleci green

src/api/app/controllers/trigger/errors.rb, src/api/app/models/token.rb, src/api/app/models/token/errors.rb, src/api/app/models/token/release.rb
The location of the exception class definition
was wrong and therefore an uninitialized constant error
was thrown by the release token model.
The naming of the exception class did not quite fit
as well.
=> Fix exception class handling for release token model

src/api/spec/factories/tokens.rb, src/api/spec/policies/token/rebuild_policy_spec.rb, src/api/spec/policies/token/release_policy_spec.rb, src/api/spec/policies/token/service_policy_spec.rb, src/api/spec/support/shared_examples/tokens.rb
Refactor repeated code from specs to a shared example
=> Token policies

src/api/app/models/token.rb
On the database level we already ensure the uniqueness
of the token string through an uniq index. In order to
properly test this in the model specs and to have better
exception handling, the validation should also be present
in the token model.
=> Add uniqueness validation for token string

src/api/spec/cassettes/TriggerController/_runservice/1_3_1.yml, src/api/spec/controllers/trigger_controller_spec.rb
This PR fixes the spec failures coming from the `#runservice` method in the TriggerController.
The rest of the spec failure come from the and `#create` method specs that will be tacked in follow up PR's
=> Fix trigger controller's `#runservice` method spec failures

src/api/app/services/trigger_controller_service/token_extractor.rb, src/api/spec/controllers/trigger_controller_spec.rb, src/api/spec/factories/tokens.rb, src/api/spec/services/trigger_controller_service/token_extractor_spec.rb
Some specs are still failing, but they are related to the trigger controller and Token models.
=> Fix TokenExtractor and write specs

src/api/app/controllers/trigger_controller.rb, src/api/test/functional/source_services_test.rb
Fixes:
1. Instead of raising the error NoPermissionForActive when authorization isn't passing, we're doing it with Pundit now. This explains why the tests had to be changed.
2. `ActionController::UnfilteredParameters: unable to convert unpermitted parameters to hash` was happening since we didn't run permit on the params.
=> Fix Minitest tests related to trigger_controller

src/backend/bs_srcserver
=> [backend] support delivering sslcert via _keyinfo route when wrapper

src/backend/BSSched/BuildJob.pm, src/backend/BSXML.pm, src/backend/bs_worker
=> [backend] refactor getbinaries() function, add new 'crossarch' job element

src/backend/bs_srcserver
This seems to be the one place where we forgot to allow both
'flavor' and 'package' as elements in _multibuild.
=> [backend] fix view=getmultibuild not working for flavor elements

src/api/app/controllers/trigger_controller.rb, src/api/app/services/trigger_controller_service/token_extractor.rb, src/api/spec/services/trigger_controller_service/token_extractor_spec.rb
All SCMs send data in there that is parsed to hashes for instance.
We removed this in the last refactoring...
=> Stop validating parameters in TriggerController

src/api/app/controllers/trigger_controller.rb, src/api/app/models/token/workflow.rb, src/api/app/services/trigger_controller_service/scm_extractor.rb
- Stop passing `request` to the `Token::Workflow#call`
- Skip `validate_params` for both GitHub and GitLab 
=> Add some fixes and improvements

src/api/app/models/token/workflow.rb, src/api/app/models/workflow.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/services/workflows/yaml_to_workflows_service.rb
After downloading the workflow's configuration file we execute the
workflow's steps against the configured project and package.
Then, validate the steps inside the Step model.
Depending on each kind of step, we know which kind of event and actions
we expect from the webhooks and what actions we want to perform or
ignore (i.e. branch a packae in OBS, just rebuild the package, etc.)
That's why we moved the checks about webhook events and actions to the
Step class.
=> Execute the workflow's steps

docs/api/api/obs.rng, src/api/.rubocop.yml, src/api/.rubocop_todo.yml, src/api/app/models/path_element.rb, src/api/app/models/project.rb, src/api/app/models/project/update_from_xml_command.rb, src/api/app/models/repository.rb, src/api/app/views/models/_project.xml.builder, src/api/db/data/20210505155012_backfill_add_kind_to_path_element.rb, src/api/db/migrate/20210505155931_add_kind_to_path_element.rb, src/api/db/migrate/20210505160725_add_kind_to_path_element_uniq_indexes.rb, src/api/db/schema.rb, src/api/spec/models/project/update_from_xml_command_spec.rb, src/api/test/functional/source_controller_test.rb
backend supports multiple entries. They are just a different kind of
path elements. So handling them via a flag in path elements instead
of heaving a single fixed entry per repository (actually per project
due to bug in former implementation).
=> [api] fix hostsystem repository handling

docs/api/api/api.txt, src/api/app/controllers/person/token_controller.rb, src/api/public/apidocs-new/paths/person_login_token.yaml, src/api/spec/controllers/person/token_controller_spec.rb
The commit was cherry-picked from #11060 in order to merge changes which can already go on `master`.
=> Add support for token.scm_token in POST /person/<login>/token

src/api/db/migrate/20210505160725_add_kind_to_path_element_uniq_indexes.rb
We ran into some mariadb problem when not doing this.
```
SHOW ENGINE INNODB STATUS;
...
------------------------
LATEST FOREIGN KEY ERROR
------------------------
...
DELETE FROM `repositories` WHERE `repositories`.`id` = 3229851
Foreign key constraint fails for table `obs_production`.`repositories`:
...
CONSTRAINT `path_elements_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `repositories` (`id`)
...
But the referencing table `obs_production`.`path_elements`
or its .ibd file or the required index does not currently exist!
```
=> Recreate the foreign key after recreating the index

docs/api/api/obs.rng, src/api/app/models/download_repository.rb, src/api/spec/models/download_repository_spec.rb
Also adapting the xml schema to have a choice instead of a free string.
=> [api] extend DoD repository type for (container) registry

src/api/app/jobs/report_to_scm_job.rb, src/api/app/models/event_subscription.rb, src/api/config/initializers/zeitwerk.rb, src/api/spec/jobs/report_to_scm_job_spec.rb
=> ReportToScm job spec

src/backend/BSRepServer/DoD.pm, src/backend/BSSched/BuildJob.pm, src/backend/bs_repserver
=> [backend] use correct arch for dodcheck in the cross build case

src/api/app/assets/stylesheets/webui/collapsible-text.scss, src/api/app/helpers/webui/webui_helper.rb, src/api/app/views/webui/request/_issues_table.html.haml, src/api/spec/helpers/webui/webui_helper_spec.rb
In the _Mentioned Issues_ section, collapsing the summary of the issue was broken. It was implemented by `Webui::WebuiHelper#toggle_sliced_text`. The helper has been removed and the text is now collapsed in the same way as any other text in the application, with "Show more/less" link.
Improve the style of the section too.
Fixes #10829.
**Before:**
**After:**
=> Fix the style and the collapse of Mentioned Issues

src/backend/BSRepServer/BuildInfo.pm, src/backend/BSRepServer/Checker.pm, src/backend/BSRepServer/ProjPacks.pm, src/backend/BSRepServer/Remote.pm, src/backend/BSSched/BuildJob/Package.pm, src/backend/bs_srcserver
Co-authored-by: Michael Schröder <mls@suse.de>
=> [backend] support local build for cross builds

src/api/app/assets/stylesheets/webui/coderay.scss, src/api/app/views/webui/package/_revision_diff_detail.html.haml
=> Apply the background color all the way to the right in request diffs

src/backend/bs_worker
=> [backend] fix docker build in getbinaries_containers

src/api/app/assets/stylesheets/webui/coderay.scss
Creating a CSS grid on code inside comments breaks the rendering of the content. This PR prevents creating a CSS grid for code inside comments.
Fixes #11154.
=> Only create a CSS grid on code inside diffs

src/api/db/migrate/20210511201658_add_data_migrations_table.rb, src/api/db/schema.rb
This table is usually created once you run some data_migrate rake task. Let's be more explicit about this.
=> Create the data_migrations table unless it exists

src/api/app/views/webui/projects/maintained_projects/index.html.haml, src/api/app/views/webui/shared/_patchinfos_table.html.haml
The Actions column contains icons that are links to perform some action. It makes no sense to sort by that column. From now on, the DataTable's column is configured to not be "orderable".
Actions column without ordering:
as we do in other tables too:
Fixes #10608
=> Avoid sorting Actions DataTable's column

src/api/app/models/distribution.rb, src/api/db/data/20210520160000_set_default_for_distro_remote.rb, src/api/db/data_schema.rb, src/api/db/migrate/20210520150000_add_remote_to_distribution.rb, src/api/db/schema.rb
In preparation to move remote Distributions from memcache to a database cache so we can use ActiveRecord for them.
We should not merge this together with the rest of the refactoring (coming later).
=> Add a remote boolean for Distribution

src/api/app/controllers/webui/staging/projects_controller.rb, src/api/spec/controllers/webui/staging/projects_controller_spec.rb
This is a PR of a series which replaces require_login with Pundit.
Tackles `Webui::Staging::ProjectsController`
Ref #10083
=> Replace `require_login` with Pundit in Webui::Staging::ProjectsController

dist/Makefile, dist/obs-server.spec, dist/systemd/obs-api-support.target, dist/systemd/obs-delayedjob-queue-scm.service
The `ReportToScmJob` (responsible for reporting back the resulting
build states of a Workflow to GitHub/GitLab) queues the jobs
in a dedicated delayedjob queue.
(Taken from #11060 in order to merge changes which can already go on master.)
=> Add systemd service for scm delayed job queue

src/api/app/models/event_subscription.rb, src/api/app/models/event_subscription/for_role_form.rb, src/api/spec/models/event_subscription/for_role_form_spec.rb
The scm channel in the event system is not meant to be
set by hand, its only used internally to report the state of a
workflow (at least for now). Therefore we should not allow
to set it by hand (since it doesnt bring any value).
=> Hide scm channel from subscription configuration page

src/backend/BSBearer.pm, src/backend/BSRepServer/DoD.pm, src/backend/BSRepServer/Registry.pm, src/backend/BSSched/BuildJob/Docker.pm, src/backend/BSSched/BuildJob/KiwiImage.pm, src/backend/BSSched/BuildRepo.pm, src/backend/BSSched/Checker.pm, src/backend/BSSched/DoD.pm, src/backend/BSSched/ProjPacks.pm, src/backend/BSWatcher.pm, src/backend/bs_dodup, src/backend/bs_repserver
Those DoD resources are different to repositories because there is no way to request the complete state from the server.
Thus we collect the needed DoD resources in the scheduler and put them into a "doddata.needed" file. The bs_dodup server then uses this information to request data for each resource.
=> [backend] support DoD container registries

src/api/config/initializers/airbrake.rb
Those are content problems, developers can't do anything about them.
=> Ignore signer related backend exceptions

src/api/app/jobs/create_job.rb, src/api/app/jobs/report_to_scm_job.rb, src/api/app/models/event/base.rb, src/api/app/models/event/build_fail.rb, src/api/app/models/event/build_success.rb, src/api/app/queries/event_subscriptions_finder.rb, src/api/app/services/scm_status_reporter.rb, src/api/spec/jobs/report_to_scm_job_spec.rb
=> Create job to report build status to SCM via SCMStatusReporter

src/api/.rubocop.yml
This encourages change_table that isn't inspectable by strong_migrations
and threfore less safe. I rather have one too many SQL command executed than
one too many unsafe migration.
=> Disable Rails/BulkChangeTable

src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/services/scm_status_reporter.rb, src/api/app/services/trigger_controller_service/scm_extractor.rb, src/api/app/services/workflows/yaml_downloader.rb, src/api/spec/services/trigger_controller_service/scm_extractor_spec.rb, src/api/spec/services/workflows/yaml_downloader_spec.rb
We were using the head (source) repository instead of
the base (target) repository to report back the
build state of a workflow. This is wrong since the
state is reported using the scm token of the target
repo owner/maintainer, which leads to permission
problems (since it doesn't associate the reported
state to the PR, but directly to the commit on the
source repository).
We also changed the download url, we should only
take the "workflow.yml" file from the target
repository.
=> Report back build state to the correct scm repository

src/backend/obs-ptf.spec
As the rpm in SLE12 does not understand rich dependencies we need
to encode them as provides prefixed with "ptfdep-". Libsolv will
later translate the provides to the correct requires.
We also add a new ptf-package() provides to every package belonging
to a ptf.
=> [backend] tweak ptf package generator for project Lotus

src/backend/BSSched/DoD.pm, src/backend/bs_srcserver
This is the only POST request from the scheduler to a repo server.
It currently gets rejected due to our access configuration, so
use the src server as proxy.
=> [backend] proxy the missingdodresources request through the src server

src/api/app/models/event/base.rb
Ignoring the package_id columns was only needed prior
to a db migration which removed the corresponding column.
After the migration is successfully applied this line can
be removed again.
=> Remove package_id from ignored_columns in event base model

src/api/app/services/trigger_controller_service/scm_extractor.rb
Right now, we should only accept open/opened actions for  `pull_request` or `Merge Request Hook` events. The rest of the actions should be ignored for now.
We avoid raising exceptions when checking if the `step` is present and is valid.
Fixes #11207
=> Limit the webhook actions we accept

src/api/.rubocop.yml
=> Fix rubocop toggle

src/api/app/controllers/application_controller.rb, src/api/app/controllers/concerns/set_current_request_details.rb, src/api/app/controllers/webui/webui_controller.rb, src/api/app/lib/backend/connection_helper.rb, src/api/app/models/current.rb
Pass X-Request-ID with each request to the backend
Once we also log this in the backend log, this will
make it easier to find all requests that were triggered
by a certain user request.
patch from @darix
=> Pass X-Request-ID with each request to the backend

src/api/app/views/webui/package/_basic_info.html.haml, src/api/app/views/webui/package/_edit.html.haml
If you try to edit the package description/title/URL and press the cancel button. When you try to edit again, the updated text stays there unless you reload the page. 
Fixes #11055
=> Reset package update form on cancel.

src/api/app/models/token/workflow.rb, src/api/spec/support/files/invalid_steps_workflows.yml
Right now we have only one workflow and one or zero steps in it. But in the near future will need to loop over many of them.
Starting looping already will save us to check if the step exists. It usually happens when the incoming event is one that we don't want to handle. So, in this case, we just ignore it and do nothing.
From now on, an exception is raised when OBS isn't able to branch the package for any reason.
=> Refactor Token::Workflow model and add exception

src/api/app/models/token/workflow.rb, src/api/app/models/workflow.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/services/workflows/yaml_to_workflows_service.rb, src/api/spec/models/workflow/step/branch_package_step_spec.rb, src/api/spec/models/workflow_spec.rb, src/api/spec/services/workflows/yaml_to_workflows_service_spec.rb
It belongs in this class since we only want to report back to SCMs whenever we branch a package. A workflow without this step won't report to the SCM. At least, not for now.
=> Create/Update event subscriptions in Workflow::Step::BranchPackageStep

src/api/app/models/workflow/step/branch_package_step.rb, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitHub/behaves_like_successful_workflow_call/creates_a_new_Event_BuildFail_subscription.yml, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitHub/behaves_like_successful_workflow_call/creates_a_new_Event_BuildSuccess_subscription.yml, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitHub/behaves_like_successful_workflow_call/creates_a_new_branched_project_with_PR_suffix.yml, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitLab/behaves_like_successful_workflow_call/creates_a_new_Event_BuildFail_subscription.yml, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitLab/behaves_like_successful_workflow_call/creates_a_new_Event_BuildSuccess_subscription.yml, src/api/spec/cassettes/Token_Workflow/_call/when_the_webhook_and_configuration_is_correct/when_the_SCM_is_GitLab/behaves_like_successful_workflow_call/creates_a_new_branched_project_with_PR_suffix.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_github/and_the_payload_is_valid/1_2_1_1_1.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_github/and_the_payload_is_valid/1_2_1_1_2.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_gitlab/and_the_payload_is_valid/1_2_2_1_1.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_we_feed_an_extractor_payload_for_gitlab/and_the_payload_is_valid/1_2_2_1_2.yml, src/api/spec/models/token/workflow_spec.rb, src/api/spec/models/workflow/step/branch_package_step_spec.rb
As requested, namespace `target_project` under `home:$USER` 
At least for testing, to create the home project was necessary.
To test, I'm setting the `User.session!` to `user`, however this information should come from `token.user`
TODO:
https://trello.com/c/F014licj/1688-place-the-branched-package-under-home
=> Use home project as namespace for branched package

src/api/app/services/scm_status_reporter.rb
This information is superfluous, so it can be removed.
=> Remove 'Workflows' and project from status_options

src/api/app/jobs/report_to_scm_job.rb, src/api/app/models/token/workflow.rb
We don't know the multibuild flavors before doing the initial report, so they will only be reported back to the SCM once the builds are done.
=> Report build results of multibuild flavors to SCM

src/backend/BSRPC.pm, src/backend/BSStdServer.pm, src/backend/BSWatcher.pm, src/backend/bs_repserver
This allows us to track the origin of requests more easily.
The api was changed to set this header in commit
863e09b8d2e2e88ddd953e201ce84230b84ea44a.
=> [backend] forward and log X-Request-ID headers

dist/t/osc/fixtures/obs-testpackage-2.8._service, dist/t/osc/fixtures/obs-testpackage._service
The OBS test suite should not rely on my private github repos. Therefore I
transferred the obs-testpackage repo to the openSUSE project.
This patch changes the url parameter in the tests `_service` files from
https://github.com/M0ses/obs-testpackage
to
https://github.com/openSUSE/obs-testpackage
to reflect this change an fix our test-suite
=> changed github link obs-testpackage.*_service from M0ses to openSUSE

dist/t/0060-check_required_services.ts
This fix checks if mysql.service or mariadb.service is installed on
the OS. This fixes testing while upgrading (e.g. from 42.3)
=> fix tests for older distros

src/api/app/models/workflow/step/branch_package_step.rb
GitHub actions like `synchronize` are not handled by `check_for_branch_request` method in [obs-service-tar_scm](https://github.com/openSUSE/obs-service-tar_scm/blob/2319f50e741e058ad599a6890ac5c710112d5e48/TarSCM/tasks.py#L145). Only `opened` action.
For now, we are going to make the `_branch_request` file contain `'opened'` action to ensure the source files are updated correctly in the OBS package.
There is nothing to change on the GitLab part in this regard, as  `check_for_branch_request` checks ` 'object_kind'` which is always `'merge_request'`, it doesn't change on different actions (there is a `object_attributes > action` key in GiLab's payload  for that)
=> Hardcode 'opened' on _branch_request file

src/api/config/initializers/airbrake.rb, src/api/config/initializers/nokogiri_builder.rb
Getting closer to updating Rails version to 6.1.x. It's expected than the CI check `next_rails` is failing. Those failures will be fixed in other PRs.
See commit messages for details on the changes.
=> Undo uneeded changes and adapt Nokogiri template handler

src/backend/bs_srcserver, src/backend/obs-ptf.spec
Adding provides to src rpms will confuse old versions of libsolv
and maybe other tools.
=> [backend] ptf generation: do not add provides/requires for src rpms

src/api/.rubocop.yml, src/api/Gemfile, src/api/Gemfile.lock, src/api/Gemfile.next.lock, src/api/app/lib/routes_helper/webui_matcher.rb, src/api/bin/rails, src/api/bin/rake, src/api/bin/setup, src/api/config.ru, src/api/config/environments/development.rb, src/api/config/locales/en.yml
Getting closer to updating Rails version to 6.1.x. It's expected that the CI check `next_rails` is still failing. Those failures will be fixed in other PRs.
See commit messages for details on the changes.
The changes work both in Rails 6.0.x and Rails 6.1.x.
=> Changes from Rails' update task

src/api/config/cable.yml, src/api/config/environments/development.rb, src/api/config/environments/production.rb, src/api/config/environments/test.rb, src/api/config/initializers/application_controller_renderer.rb, src/api/config/initializers/content_security_policy.rb, src/api/config/initializers/inflections.rb, src/api/config/initializers/new_framework_defaults_6_0.rb, src/api/config/initializers/new_framework_defaults_6_1.rb, src/api/config/initializers/permissions_policy.rb
Other changes like ActiveStorage configuration were included, but since we're not using this feature of Rails, I didn't include them in this PR.
Getting closer to updating Rails version to 6.1.x. It's expected that the CI check next_rails is still failing. Those failures will be fixed in other PRs.
See commit messages for details on the changes.
=> Remaining changes from the Rails' update task

src/api/app/mixins/flipper_feature.rb, src/api/app/models/cloud/ec2/configuration.rb
See commit messages for details.
The failing specs were (I took the output from previous next_rails PRs):
```
12) Webui::Users::NotificationsController with feature flag not enabled GET #index returns not_found status
Failure/Error: render file: Rails.root.join('public/404'), status: :not_found, layout: false
ArgumentError:
`render file:` should be given the absolute path to a file. '/home/frontend/project/src/api/public/404' was given instead
```
and 
```
11) Cloud::Ec2::Configuration validations is expected to validate that :external_id is case-sensitively unique
Failure/Error: it { is_expected.to validate_uniqueness_of(:external_id) }
Expected Cloud::Ec2::Configuration to validate that :external_id is
case-sensitively unique, but this could not be proved.
After taking the given …
```
=> Fix failing specs for Rails 6.1.x

src/api/app/controllers/webui/search_controller.rb
When the connection to the search service drops, shows an error message instead of crashing and logs the exception as well.
=> Recover from Sphinx connection errors on search

src/api/app/controllers/distributions_controller.rb, src/api/app/controllers/public_controller.rb, src/api/app/controllers/webui/interconnects_controller.rb, src/api/app/controllers/webui/repositories_controller.rb, src/api/app/jobs/fetch_remote_distributions_job.rb, src/api/app/models/distribution.rb, src/api/app/views/distributions/_distribution.xml.builder, src/api/app/views/webui/repositories/distributions.html.haml, src/api/config/clock.rb, src/api/spec/cassettes/Interconnects/creating_custom_interconnect.yml, src/api/spec/cassettes/Interconnects/creating_openSUSE_org_interconnect.yml, src/api/spec/controllers/public_controller_spec.rb
We render/display `Distribution`s from a hash because the `Distribution`s from the interconnect are from an XML.
This PR changes `Distribution`s to be fully based on records. Including the in-memory cache for `Distribution`s from remote.
=> Remove distro hashing

src/api/spec/support/database_cleaner.rb
Create the `Configuration` in the database if it doesn't exist
a `rake db:seed` still necessary before running any spec
=> Create the Configuration singleton in the database cleaner if necessary

src/api/app/models/bs_request_action.rb, src/api/db/attribute_descriptions.rb, src/api/db/data/20210409135426_add_enforce_revision.rb, src/api/spec/cassettes/BsRequestAction/check_expand_errors/RevisionEnforcing_enabled/adds_revision.yml, src/api/spec/cassettes/BsRequestAction/check_expand_errors/RevisionEnforcing_enabled/with__link_in_submitted_source/adds_revision.yml, src/api/spec/cassettes/BsRequestAction/check_expand_errors/RevisionEnforcing_enabled/with__link_in_submitted_source/freezes_revision.yml, src/api/spec/cassettes/BsRequestAction/check_expand_errors/RevisionEnforcing_enabled/with__link_in_submitted_source/with_updatelink/throws_exception.yml, src/api/spec/cassettes/BsRequestAction/check_expand_errors/Without_RevisionEnforcing/doesn_t_add_revision.yml, src/api/spec/factories/bs_requests.rb, src/api/spec/models/bs_request_action_spec.rb, src/api/test/fixtures/attrib_types.yml, src/api/test/functional/attributes_test.rb, src/api/test/functional/request_controller_test.rb
Continuing on https://github.com/openSUSE/open-build-service/pull/10992
This is a security flaw in our development flow so we want to have this fixed asap - but the original PR didn't move in the last 2 months.
=> Add revision enforcement

src/api/Gemfile, src/api/Gemfile.lock, src/api/Gemfile.next.lock, src/api/config/environments/development.rb
This reverts commit 9b9e38912b57d2d680e55461af75dd0d7c402ff0.
The changes are causing the following error in the delayed jobs in our
development environment:
ERROR -- : Exception rescued in listen-run_thread: IOError: closed stream
=> Revert "Install listen gem"

src/api/app/controllers/webui/request_controller.rb
Don't include request_action in require_login list.
fixes #11278
=> Remove request_action from require login before action

src/api/.rubocop_todo.yml, src/api/app/models/unregistered_user.rb, src/api/app/models/user.rb, src/api/db/migrate/20180814112739_add_in_beta_to_user.rb, src/api/db/migrate/20190704072437_add_column_in_rollout_to_users.rb, src/api/db/migrate/20210623134455_add_missing_indices_to_users.rb, src/api/db/schema.rb
These fields were not indexed before.
Fix Rails/AddColumnIndex RuboCop offenses.
Follow-up to #11270.
=> Index in_beta and in_rollout fields in users table

src/api/app/models/bs_request_action.rb
The issue was discovered while adding source revision enforcement.
Fixes #11273, but I'm not really sure where to test this. Suggestions?
=> Do not allow requests where the rev equals to 'upload'

src/api/app/models/bs_request.rb, src/api/app/models/bs_request/find_for/query.rb
Since Rails 6.1, named scope chains will no longer leak the scope to class level querying methods.  As a result of this, the
"BsRequest::FindFor::Query#all" starts to perform some of its queries again on the unscoped relation instead of keeping them chained. This resulted in unexpected/wrong results.
See https://guides.rubyonrails.org/6_1_release_notes.html#active-record-notable-changes
Related to #9748
=> Do not rely on named scope chain for BsRequest::FindFor::Query

.circleci/config.yml, src/api/config/application.rb
This is needed because they need a different setup.
=> Split RSpec and Minitest in two next_rails CI jobs

src/backend/BSSrcServer/Link.pm
When trying to expand the upload rev, a bogus tree files is written
(if the upload rev contains a _link file). For instance, a tree file
can look like this:
c157a79031e1c40f85931829bc5fc552  foo
f9079d5de256dd593c7eabdb29699e53  /LINK
upload  /LOCAL
Since the upload rev has no "real" srcmd5, the format of the tree
file is corrupted. Such a corrupted tree file can be used to generate
a <directory/> xml that has an <entry/> whose "name" attribute is the
empty string and whose "md5" attribute contains 32 "garbage" bytes
(that is, an illegal md5). For instance,
marcus@linux:~> curl http://localhost:5352/source/home:mallory/lnk2?expand=1
<directory name="lnk2" rev="4fc0e0e48934e51692aeec749600d854" vrev="10" srcmd5="4fc0e0e48934e51692aeec749600d854">
<linkinfo project="home:mallory" …
=> Do no expand the upload rev

src/backend/BSProductXML.pm
bsc#1187425
Allows zypper to guess the repository name a bit more reliable.
=> [backend] add a field in product spec for default repository name

src/backend/BSProductXML.pm
=> [backend] define default OBS download resource URL in product files

src/backend/BSConfig.pm.template
This is useful when you want to remove the project prefix from official containers. Thanks to mls for sharing the example from OBS.
=> [backend] Add an example for the default_container_mapper function

src/api/app/models/bs_request.rb
It hasn't been in use since c843b1dcb562579834f4140e7c52486ad2e3b993 (look for changes in `src/api/app/controllers/webui/obs_factory/staging_projects_controller.rb`)
=> Remove unused scope new_with_reviews_for

src/api/app/models/token/workflow.rb
We always need an SCM token for a Token::Workflow record, so we should check that it's present. We don't want to valid its format or anything else for now.
=> Validate presence of scm_token for Token::Workflow

docs/api/api/constraints.rng, docs/api/api/constraints.xml, src/backend/BSDispatcher/Constraints.pm, src/backend/BSXML.pm, src/backend/bs_worker, src/backend/testdata/constraint/kernel, src/backend/testdata/test_dispatcher, src/backend/testdata/workerinfo/large
New hardware supports 32bit user land, but no 32bit kernels anymore. We need to be able to destinguish build jobs without breaking remote interconnect. 
A OBS version compare expresion for prjconf will be provided by mls to complete this.
=> Support for handling ARM 32bit userland only hardware

src/backend/BSSched/BuildJob/Docker.pm, src/backend/BSSched/BuildJob/KiwiImage.pm
We only need the vminstall packages for the setup of the build
environment. If the repo has a configured path, we can skip it
in the image/container content expansion.
=> [backend] skip unneeded vminstall expansion in kiwi/docker builds

src/api/app/models/token/workflow.rb
In case we want to give a hint that the problem happens when we are downloading the `workflows.yml`
follow-up of #11321
=> Improve error message in case workflows.yml is not found

src/api/app/models/token/errors.rb, src/api/app/models/token/workflow.rb
Improve the error handling and user feedback in case the SCM token of the user is invalid
=> Raise APIError subclass if SCM Token is unauthorized

src/api/app/views/layouts/webui/_flash.html.haml, src/api/app/views/webui/patchinfo/show.html.haml, src/api/app/views/webui/request/_review_tab.html.haml, src/api/app/views/webui/shared/_collapsible_text.html.haml
simple_format marks output as html safe. All of this data includes user input.
Through XML parsing we even store HTML in the database.
```ruby
Xmlhash.parse('<project name="hans"><description>&lt;h2&gt;Hello World&lt;/h2&gt;</description></project>')
=> {"name"=>"hans", "description"=>"<h2>Hello World</h2>"}
```
So better sanitize the simple_format output.
=> Sanitize simple_format

src/api/app/models/token/workflow.rb, src/api/app/services/workflows/yaml_downloader.rb, src/api/spec/controllers/trigger_workflow_controller_spec.rb, src/api/spec/models/token/workflow_spec.rb
It's better to handle everything in the class itself. Other classes relying on this class can rescue if needed.
Following up on #11331
=> Avoid leaking Workflows::YAMLDownloader errors outside the class

src/backend/BSDispatcher/Constraints.pm, src/backend/bs_dispatch
We now fail jobs if we cannot parse the package or
project constraints. Before, a job with a bad package
constraints simply was never dispatched. Bad project
constraints were ignored.
This commit also implements a cache for parsed project
constraints.
=> [backend] rework constraints handling in the dispatcher

src/api/app/models/token/workflow.rb, src/api/app/services/scm_status_reporter.rb, src/api/app/services/trigger_controller_service/scm_extractor.rb, src/api/app/services/workflows/yaml_downloader.rb, src/api/spec/controllers/trigger_workflow_controller_spec.rb, src/api/spec/models/token/workflow_spec.rb, src/api/spec/services/trigger_controller_service/scm_extractor_spec.rb, src/api/spec/services/workflows/yaml_downloader_spec.rb
Remove hardcoded URLs and pass the hostname in the payload to generate URLs.
Fixes #11198
=> SCM integration - Support for private instances (Github and Gitlab)

src/api/config/thinking_sphinx.yml.example
This will clean up real-time orphan records after reindexing. As the first step, to ensure this is not causing any error, we are going to enable it only in development environment.
=> Add real_time_tidy to ThinkingSphinx dev configuration

src/api/db/data/20210707102506_add_api_endpoints_to_payload.rb, src/api/db/data_schema.rb
We need to migrate SCM event_subscriptions according to the new payload structure.
Co-authored-by: @saraycp 
Fixes #11346
=> Add data migration to handle old event_subscriptions

src/api/app/models/token/errors.rb, src/api/app/models/token/workflow.rb, src/api/app/models/workflow.rb, src/api/spec/models/token/workflow_spec.rb, src/api/spec/models/workflow_spec.rb
This change aborts the whole step running when there is an unsupported step.
This is how it will respond if there are unsupported specs:
=> Do not run the workflow steps if some are unsupported

src/api/app/models/token/errors.rb, src/api/app/models/token/workflow.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/spec/models/workflow/step/branch_package_step_spec.rb
=> Improve report of branched package errors for the Branch Package step of Workflows

src/api/app/models/token/errors.rb, src/api/app/models/token/workflow.rb, src/api/app/models/workflow.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitHub/for_a_new_PR_event/behaves_like_successful_new_PR_or_MR_event/only_reports_for_repositories_and_architectures_matching_the_filters.yml, src/api/spec/cassettes/Workflow_Step_BranchPackageStep/_call/when_the_SCM_is_GitLab/for_a_new_MR_event/behaves_like_successful_new_PR_or_MR_event/only_reports_for_repositories_and_architectures_matching_the_filters.yml, src/api/spec/models/workflow/step/branch_package_step_spec.rb, src/api/spec/models/workflow_spec.rb
We are going to report back the build results to the SCM according to the architectures and repositories defined in the filters of OBS workflows.
While we're happy with the code as it is now, there are still some potential improvements like validating values provided to the filters. As noted in comments, we could also use a query object for some methods. We could gather all errors together before raising if any error is present. All of this is nice to have, but not a blocker to delivering this feature. We're going to tackle as much as possible in the remaining days of the deliverable.
=> Implement architectures and repositories filters for OBS workflows

src/api/app/models/branch_package/errors.rb, src/api/app/models/token/errors.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/spec/models/workflow/step/branch_package_step_spec.rb
The errors classes are related with branching and have nothing to do with `Token` therefore lets move it to `BranchPackage/errors.rb`
=> Move error classes from Token to BranchPackage errors module

.obs/workflows.yml
To use the feature implemented in #11318.
The architectures and repositories are the same as the ones from the CI check `OBS Package Build`.
Once we merge this, following PRs will only report what we defined in the filters.
=> Setup filters in .obs/workflows.yml

src/api/app/jobs/project_create_auto_cleanup_requests_job.rb
To avoid code repetition reuse well tested query objects whenever possible
=> Use query objects when possible

src/api/app/jobs/worker_measurements_job.rb
Field sets are, like tag sets, separated with a comma and no spaces.
=> Fix field set format

src/api/app/assets/javascripts/webui/request.js, src/api/app/controllers/webui/request_controller.rb, src/api/app/views/webui/request/show.html.haml
After recent changes introduced in #11260, the diffs in supersede requests were not correct.
Fixes #11353
=> Add missing parameter for diffs in supersede

src/api/config/thinking_sphinx.yml.example
This will clean up real-time orphan records after reindexing.
This time will be enabled for the production environment.
=> Add real_time_tidy to ThinkingSphinx

src/api/app/services/workflows/yaml_downloader.rb, src/api/spec/controllers/trigger_workflow_controller_spec.rb, src/api/spec/models/token/workflow_spec.rb
When the file doesn't exist in the default branch of the SCM repository,
is Octokit which fails first. So we handle the exception at this point.
=> Adjust error handling for non-existent workflows.yml

.codeclimate.yml
This is to avoid reporting twice the same thing due to having two standards for various code quality metrics. RuboCop is the standard whenever CodeClimate and RuboCop have the same checks/cops.
The CodeClimate checks are described here https://docs.codeclimate.com/docs/maintainability#section-checks
I compared them to the cops provided by RuboCop to see which ones are overlapping. This is how I came up with a list of CodeClimate checks to disable.
=> Disable CodeClimate checks which have RuboCop equivalents

dist/systemd/obs-clockwork.service, dist/systemd/obs-delayedjob-queue-consistency_check.service, dist/systemd/obs-delayedjob-queue-default.service, dist/systemd/obs-delayedjob-queue-issuetracking.service, dist/systemd/obs-delayedjob-queue-mailers.service, dist/systemd/obs-delayedjob-queue-project_log_rotate.service, dist/systemd/obs-delayedjob-queue-quick@.service, dist/systemd/obs-delayedjob-queue-releasetracking.service, dist/systemd/obs-delayedjob-queue-scm.service, dist/systemd/obs-delayedjob-queue-staging.service, dist/systemd/obs-sphinx.service, dist/systemd/obsscheduler.service
"Wants=" will start the configured service, if disabled or not. This is
not we want with our obscheduler or OBS API services.
In a distributed setup like build.opensuse.org it is not common that the
database runs on the same host like the API, therefor starting mariadb
or running obsapisetup is not recommended.
=> [dist] remove Wants= from most of our systemd service files

dist/obs-bundled-gems.spec
After merge we need to link to [devel:languages:ruby:extensions/rubygem-rack](https://build.opensuse.org/package/show/devel:languages:ruby:extensions/rubygem-rack) in 2.10:Staging.
=> Require rack version we have in the bundle

src/api/app/views/webui/groups/_group_members.html.haml, src/api/app/views/webui/package/_file.html.haml
Move the `title` attribute out from the data section of links. They are meant to be displayed as tooltips, and not needed inside the data section.
=> Fix HTML links' tooltips

src/backend/BSDispatcher/Constraints.pm, src/backend/bs_repserver
The old code modified the old entry instead. Thus, a prjconstraint
of
hardware:cpu:flag exclude=true EL0
hardware:cpu:flag cpuid
resulted in the EL0 exclude being ignored. We now default to
"add" mode for leaf elements. You can force the old "overwrite last
entry" mode by adding a '!' character, like:
hardware:cpu:flag! cpuid
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real …
=> [backend] BSDispatcher::list2struct: add to arrays in leaf elements

src/api/config/environments/development.rb
Enable annotation in development mode to make easier to identify which file we have to change when updating views.
More info: https://www.bigbinary.com/blog/rails-6-1-adds-annotate_rendered_view_with_filenames-to-annotate-html-output
=> Enable rendered_view_with_filenames annotation in development

src/backend/BSSched/Checker.pm
We usually write it only if the project is finished, but that
means a server restart will only see the old data for projects
that are big and do not finish often enough.
=> [backend] write lastcheck file if we spent more than 2 minutes

docker-compose.yml, src/api/docker-files/Dockerfile, src/api/docker-files/Dockerfile.minitest
Move our development environment from Leap 15.1 to Leap 15.3
To test it:
checkout the branch and run `docker-compose down && rake docker:build && docker-compose up`
=> Move from Leap 15.1 to Leap 15.3

ReleaseNotes-2.11
Following up on #11422 and #11423. Just in case someone wonders.
=> Add removal of statistics#{download_counter,newest_stats} to release notes

src/api/.rubocop.yml
1 expectation per example is way too strict.
=> Have a maximum of 2 expectations per example in specs

dist/t/0060-check_required_services.ts
* only add obs-delayedjob-queue-scm to the list to check if unit exists (missing in 2.10 and older)
* log service state to logfile to get the noise out of the test results
=> Fix testing for 210

src/api/app/views/webui/package/_side_links.html.haml, src/api/app/views/webui/package/side_links/_checkout_package.html.haml
Without this patch, thousands of OBS users had to spend multiple seconds for many packages to type or copy the right parts of the URL into a shell window.
We want do it like github and gitlab and make it easy for them.
Fixes #63
=> Display copypastable checkout instructions

src/api/app/assets/javascripts/webui/autocomplete.js, src/api/app/assets/javascripts/webui/request.js, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/users/rss_tokens_controller.rb, src/api/app/controllers/webui/users/tokens_controller.rb, src/api/app/models/project.rb, src/api/app/models/token.rb, src/api/app/policies/webui/token/rebuild_policy.rb, src/api/app/policies/webui/token/release_policy.rb, src/api/app/policies/webui/token/rss_policy.rb, src/api/app/policies/webui/token/service_policy.rb, src/api/app/policies/webui/token/workflow_policy.rb, src/api/app/policies/webui/token_policy.rb, src/api/app/views/webui/packages/branches/into.html.haml, src/api/app/views/webui/user/_index_actions.html.haml, src/api/app/views/webui/user/index_actions/_manage_tokens.haml, src/api/app/views/webui/users/notifications/_notifications_list.html.haml, src/api/app/views/webui/users/tokens/_actions.html.haml, src/api/app/views/webui/users/tokens/_breadcrumb_items.html.haml, src/api/app/views/webui/users/tokens/_create.js.erb, src/api/app/views/webui/users/tokens/index.html.haml, src/api/app/views/webui/users/tokens/new.html.haml, src/api/config/locales/kaminari.en.yml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/person/token_controller_spec.rb, src/api/spec/controllers/webui/users/tokens_controller_spec.rb, src/api/spec/features/webui/projects_spec.rb, src/api/spec/features/webui/requests_spec.rb
Manage user tokens from the web user interface.
This new option can  be accessed from "User Profile", "Manage Your Tokens".
This option will be shown only if the ~`user_profile_redesign`~ `trigger_workflow` feature flag is enabled.
This pull request only implements listing and deleting tokens.
Policies for using tokens from the web-ui were created under `app/policies/webui/tokens/`, to not colide with the existing token policies, under `app/policies/token/`.
Switching to Draft. Things to be done before switching to "Ready for review":
[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#wh …
=> Introduce tokens in web UI

src/api/db/data/20190130115727_add_github_issue_tracker.rb, src/api/db/data/20210730130616_change_issuetracker_github_regex.rb, src/api/db/data_schema.rb, src/api/db/seeds.rb
rename migration to re-apply. fixed missing entry in structure.sql
=> allow more chars for github tracker identifier

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Package.pm, src/backend/BSSched/Checker.pm, src/backend/BSSched/Modulemd.pm, src/backend/BSSrcServer/Modulemd.pm, src/backend/BSXML.pm, src/backend/bs_srcserver, src/backend/bs_worker
This consists of the parsing of the modulemd data, the setup
of the modules and macros, and the generation of a _modulemd.pst
file at build time.
=> [backend] implement first part of modulemd data creation

src/api/app/controllers/webui/users/tokens_controller.rb, src/api/app/policies/webui/token_policy.rb, src/api/app/views/webui/users/tokens/_breadcrumb_items.html.haml, src/api/app/views/webui/users/tokens/edit.html.haml, src/api/app/views/webui/users/tokens/index.html.haml, src/api/app/views/webui/users/tokens/new.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/users/tokens_controller_spec.rb
As a first step, only the SCM token of workflow tokens can be updated. Updating other token types isn't possible right now, so the `Edit` icon isn't displayed for non-workflow tokens. Regenerating the string of a token is going to happen later.
Also made some changes to be consistent throughout the Create/Edit forms and with other forms like having breadcrumbs for the `Create Token` and `Edit Token` pages.
=> Update the SCM token of workflow tokens in the UI

src/api/app/views/webui/users/tokens/edit.html.haml, src/api/app/views/webui/users/tokens/new.html.haml
We forgot to do this in PRs which introduced those pages.
Without this change, those two pages have the default title, which is `Open Build Service` on our production instance.
=> Set page titles for create/edit token pages

src/api/.haml-lint.yml, src/api/app/views/webui/apidocs/index.html.haml, src/api/app/views/webui/cloud/azure/configurations/show.html.haml, src/api/app/views/webui/cloud/configurations/index.html.haml, src/api/app/views/webui/cloud/ec2/configurations/show.html.haml, src/api/app/views/webui/cloud/upload_jobs/index.html.haml, src/api/app/views/webui/kiwi/images/edit.html.haml, src/api/app/views/webui/kiwi/images/show.html.haml, src/api/app/views/webui/package/binaries.html.haml, src/api/app/views/webui/staging/excluded_requests/index.html.haml, src/api/app/views/webui/timeout.html.haml, src/api/app/views/webui/users/notifications/index.html.haml, src/api/lib/haml-lint/custom_linters/set_pagetitle_in_view.rb
We need to set the instance variable `@pagetitle` in views to have a page title when the view is rendered. This custom haml-lint linter is there to remind us if we forget. A PR like #11449 wouldn't need to be created since it would be caught by this custom linter.
`@pagetitle` is used in the [webui layout](https://github.com/openSUSE/open-build-service/blob/032494fd268578c4dfe6f7b77a7b0bd71bef61fe/src/api/app/views/layouts/webui/webui.html.haml#L10).
I ran some simple benchmarks on my computer in our Docker development environment by executing `time haml-lint` with the custom linter enabled and disabled.
When the custom linter `SetPagetitleInView` is:
- enabled: 29.2 seconds to 30 seconds
- disabled: 29.6 seconds to 30.9 seconds
I'm okay with this super minor time increase in the CI if …
=> Create SetPagetitleInView linter for haml-lint and enable it

dist/obs-server.spec
%service_del_postun_without_restart is not available in SLE15_SP1/2.
We have our own macro in the spec file "%service_del_postun -r" to make
this backward compatible.
=> remove %service_del_postun_without_restart from spec file

src/backend/BSRepServer.pm, src/backend/BSSched/BuildJob/KiwiProduct.pm, src/backend/BSSched/BuildResult.pm, src/backend/BSSched/Remote.pm, src/backend/bs_repserver, src/backend/bs_worker
=> [backend] support modulemd generation for product builds

src/api/app/controllers/source_controller.rb, src/api/app/models/bs_request_action_maintenance_incident.rb, src/api/app/models/channel_binary.rb, src/api/app/models/project.rb
Sometimes we want to call this without an exception if there
is no project with that attribute.
=> Introduces Project.get_maintenance_project!

.github/labeler.yml
This is done with the help of the GitHub action [pull request labeler](https://github.com/actions/labeler).
We sometimes forget to apply labels. Having labels on PRs is useful to categorize them and knowing what they changed.
=> Automatically apply labels to PRs based on the changed files

.github/workflows/pull_request_labeler.yml
I totally forgot this part in #11461. That PR configured the pull request labeler, but it didn't run since there was no GitHub workflow... Oopsie!
=> Add GitHub workflow to apply labels to PRs

.circleci/config.yml, docker-compose.yml, src/api/docker-files/Dockerfile, src/api/docker-files/Dockerfile.minitest, src/api/spec/support/capybara.rb, src/api/spec/support/shared_examples/features/beta/user_tab.rb
Taking advantage of the binary compatibility of both distributions, SLE 15 SP3 and openSUSE Leap 15.3, and after creating a new source of docker images based in SLE 15 SP3 (see https://build.opensuse.org/project/show/OBS:Server:Unstable:Containers ), we use those docker images for both, our CI setup and our development environment.
Upgrading the version of the distribution also upgraded the Chromium version. Two issues rised:
1. All feature tests failed: this was fixed by adding the `--disable-gpu` flag to the options of Chromium.
1. A false positive in feature package tests was fixed, making the tests for adding a user and adding a group fail. The bad
behavior was, that clicking the links 'Add User' or 'Add Group' was possible, even if the link was outside the visual area. ~Skipping~ …
=> Unify containers images used by CI and development environment 

.obs/workflows.yml
We aren't using openSUSE Leap 15.1 and SLE15 SP1 distributions in our CI or in our development environment any more.
Follow up to #11468.
=> Remove openSUSE Leap 15.1 and SLE15 SP1 distributions from workflows

src/backend/BSSched/Checker.pm, src/backend/BSSched/Modulemd.pm, src/backend/BSSrcServer/Modulemd.pm, src/backend/BSXML.pm, src/backend/bs_srcserver, src/backend/bs_worker
Support additional modulemd-defaults documents in the modulemd input.
Also support preset version/context elements. The version prefix
is still prepended, though, as we still want to differentiate
between platforms.
=> [backend] improve modulemd support

src/api/config/application.rb, src/api/config/boot.rb
This gem disables Bundler's enforcement of exact gem versions in favour of basic constraint checks written in `Gemfile.in` file.
It's not included in `Gemfile`, so it should be installed explicitly by your system's package manager (as a dependency of OBS API package, for example) in order to allow system manager to take over responsibility of gem management from Bundler.
Also, it's packager's responsibility to place appropriate `Gemfile.in` file to enable this feature.
This is needed for installations where Ruby gems are managed by system package manager (like RPM or APT),
so bundler should not interfere with that and refuse to start application if gems with versions slightly different than ones mentioned in `Gemfile.lock` are installed in the system.
=> Use bundler_ext instead of bundler if Gemfile.in file present

src/api/spec/factories/attribs.rb, src/api/spec/queries/packages_finder_spec.rb, src/api/spec/support/database_cleaner.rb
`OBS:EmbargoDate` is a basic AttribType from OBS and we should always assume it exists.
=> Add OBS:EmbargoDate AttribType to DatabaseCleaner

src/api/app/models/bs_request.rb, src/api/app/models/event/request_statechange.rb
How many seconds have passed between request creation and reaching a final state? Useful to measure the impact of
our UI for instance.
=> Measure request duration

src/api/app/models/bs_request.rb, src/api/app/models/event/request.rb, src/api/app/models/event/request_statechange.rb
If a request against a project that is maintainer changes it's state, record
the full project name as namespace tag. Allows us to have finer grained
measurements for important projects.
=> Measure finer grained namespaces for requests

src/api/app/models/concerns/project_maintenance.rb, src/api/app/models/event/build.rb, src/api/spec/models/project/project_maintained_namespace_spec.rb
If a build happens in a project that is maintained, record the full project
name as namespace tag. Allows us to have finer grained measurements for
important projects.
Additionally start measuring the new buildtype payload.
=> Measure finer grained namespaces for builds

src/backend/BSXML.pm
The OBS frontend introduced an new field to the configuration
table (https://github.com/openSUSE/open-build-service/pull/11437)
in order to save a URL for the terms of services.
The frontend writes this configuration to the backend through
a delayed job. The backend currently throws an 400 http code,
since it is not aware of the new field.
Fixes #11436
=> [backend] Add `tos_url` to configuration

src/api/app/jobs/delete_from_sphinx_job.rb, src/api/app/models/package.rb, src/api/app/models/project.rb
At the moment we only populate new records to sphinx. But we
don't remove those indexes after those records get deleted from
the database.
Usually the Thinking Sphinx gem is taking care of this automatically,
but since we differ from the regular setup by writing to the sphinx
index in a delayed job, we also have to consider the deletion.
There are still other issues, when updating/deleting associated attributes on the package/project. But this needs still more investigation, and will be part of another PR.
=> Remove deleted project and package records from sphinx indexes

dist/Makefile, dist/functions.setup-appliance.sh, dist/obs-server.spec, dist/obsstoragesetup, dist/setup-appliance.sh, dist/t/0010-obs-bootstrap-api.t, dist/t/0080-check_ssl_certs.ts, dist/t/0110-check_signd.ta, dist/t/osc/fixtures/home:Admin.xml
Without this patch obsstoragesetup tries to source setup-appliance.sh.
Due to changes in systemd it is no longer only sourcing the file.
Instead setup-appliance.sh gets executed. This generates a dependency loop of
services:
obsstoragesetup -> setup-appliance.sh -> obssignd -> obsstoragesetup
This patch splits out the function definition from setup-appliance.sh
into functions.setup-appliance.sh to
* fix the current error
* remove error prone descisions in setup-appliance.sh
=> [dist] split functions out of setup-appliance.sh

src/api/app/models/bs_request.rb, src/api/app/views/webui/request/_show_side_links.html.haml
The `state` getter if overloaded and transforms the string to a symbol
(why???), we cover for that now.
Also simplifying the method a bit.
=> Fix measuring request duration

src/backend/BSRepServer/DoD.pm, src/backend/bs_dodup
our download infrastructure currently needs 7 hops..
=> [backend] increase maxredirects to 10 for DoD downloads

src/backend/BSSched/BuildJob/Docker.pm
This should have been in commit b68f9727161ad5e1e007e53ba26def6be5739d12
=> [backend] create fake annotation for docker builds with DoD containers

src/api/Gemfile.lock, src/api/Gemfile.next.lock
CI will never pass as the version of bundler is hardcoded in the CI containers. Changing it would make this PRs CI pass and everyone elses fail. 
You need to trust me and let me commit without CI :)
=> Update bundler version to a recent one

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/Checker.pm, src/backend/BSSched/Modulemd.pm, src/backend/BSSrcServer/Modulemd.pm, src/backend/BSXML.pm
This can be done with the non-standard "distindex" tag in the
modulemd.yaml input file.
=> [backend] modularity: allow to pin the distindex in the modulemd file

src/api/Gemfile.lock, src/api/Gemfile.next.lock
Reverts openSUSE/open-build-service#11550
We need @M0ses to understand why [obs-service-bundle_gems](https://build.opensuse.org/package/show/OBS:Server:Unstable/obs-service-bundle_gems) was reverted.
=> Revert "Update bundler version to a recent one"

src/backend/BSRepServer/Checker.pm, src/backend/BSSrcServer/Modulemd.pm, src/backend/bs_srcserver
Osc still needs to be adapted to make use of the data.
=> [backend] support modularity in the repserver

src/backend/BSSched/Modulemd.pm
If the version is already complete, verify that it matches
the defined version prefix.
=> [backend] allow to have the versionprefix in the modulemd input

src/api/app/services/workflows/yaml_downloader.rb
Until this change, we always use the workflow configuration file from the default branch of a repository.
Add a missing "ref" attribute to the Octokit call, with the branch that must be used, to be able to retrieve the correct workflow configuration file.
=> Use workflow configuration file from the base branch for GitHub

src/api/app/controllers/trigger_controller.rb, src/api/app/models/token/workflow.rb
It's possible to trigger a workflow token via the API. But doing so makes no sense as we cannot provide a payload (the token gets the required data from the payload. If there is no payload, we can't get the required data).
This PR ensures the API gets a proper error when trying to trigger a Workflow Token without a payload.
Fixes #11535
=> Fail if the Workflow token does not have a payload

src/backend/BSRepServer/BuildInfo.pm, src/backend/BSXML.pm, src/backend/bs_srcserver
Clients like osc should put the yaml data into _modulemd.yaml so
that the build tool an pick it up and create the correct modulemd
data as build result.
=> [backend] external buildinfo: include modulemd yaml data

src/backend/BSSched/Checker.pm
They are currently set to broken with a "no recipe found" error.
=> [backend] exclude modulemd packages

src/api/app/controllers/issue_trackers_controller.rb
IssueTracker.create will always return an IssueTracker object,
even if it's not valid.
=> Fix IssueTracker validation errors

src/api/app/jobs/staging_project_accept_job.rb
This can happen when at the same time of scheduling the job
there will be a new request selected to the staging project.
Or somehow a staged request changes state in the same time.
If we discard the job on this error, the staging project state
calcuclation will be done again.
Partially addresses #10636
=> Discard StagingProjectAcceptJob on InvalidStateError

src/api/app/models/scm_webhook.rb, src/api/app/validators/scm_webhook_event_validator.rb, src/api/spec/models/scm_webhook_spec.rb, src/api/spec/validators/scm_webhook_event_validator_spec.rb
This allows us to implement different logic for workflow steps depending on the webhook events. This will be in upcoming PRs.
=> Support closed, merged and reopened pull/merge requests in OBS workflows 

src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/models/workflow/step/configure_repositories.rb, src/api/app/models/workflow/step/link_package_step.rb
This is to avoid errors while we adapt workflow steps to support closed, merged and reopened PRs/MRs.
=> Ignore temporarily closed, merged and reopened PRs/MRs

src/api/app/models/event_subscription/find_for_event.rb, src/api/app/models/event_subscription/form.rb, src/api/app/models/group.rb
eg. do not send out mails anymore when a user got locked
=> [api] avoid delivering notifications to unconfirmed users

.github/labeler.yml, .rubocop.yml, src/api/.rubocop.yml
Using an empty case is sometimes clearer than `if/elsif/elsif/else`.
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EmptyCaseCondition
=> Disable RuboCop Style/EmptyCaseCondition cop

src/api/app/controllers/webui/package_controller.rb, src/api/app/services/package_controller_service/rebuild_trigger.rb, src/api/spec/services/package_controller_service/rebuild_trigger_spec.rb
We need to pass the full package name (including the multibuild suffix) to the backend
when retriggering a package build through the webui.
Currently we pass the package name of the package object
to the backend, which will cause a rebuild of all
multibuild flavors.
Fixes #11598
=> Consider multibuild suffix when retriggering package build through webui

src/api/app/models/token/workflow.rb, src/api/app/models/workflow/step.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/models/workflow/step/configure_repositories.rb, src/api/app/models/workflow/step/link_package_step.rb, src/api/spec/models/token/workflow_spec.rb
Whenever the webhook event is for a closed, merged or reopened pull/merge requests, we handle this at the workflow level in the `Token::Workflow` model. There is no need to handle this in every step since we can already tell what has to be restored/deleted.
=> Handle closed, merged and reopened pull/merge requests in OBS workflows

src/api/app/views/webui/users/token_triggers/_breadcrumb_items.html.haml, src/api/app/views/webui/users/tokens/_breadcrumb_items.html.haml
=> Add missing "Tokens" link in breadcrumbs in "Trigger Token" page

src/api/Gemfile.lock
Here is everything you need to know about this update. Please take a good look at what changed and the test results before merging this pull request.
<details>
<summary>Release Notes</summary>
This release changes how the status of requests that end up in an exception are measured. The ActionController measurement will set the status just like Rails.logger does for some "standard" exceptions like ActiveRecord::RecordNotFound or ActionController::RoutingError. Everything that isn't handled by default in Rails is reported as with a 500 status tag. This makes it easier to distinguish "standard' exceptions from "real" exceptional things.
After dropping support for Ruby 2.4 a while ago, we now require Ruby 2.5.
</details>
=> Update influxdb-rail: 1.0.2 → 1.0.3 (minor)

src/api/app/validators/scm_webhook_event_validator.rb, src/api/spec/validators/scm_webhook_event_validator_spec.rb
Documentation for the push events:
- [GitHub](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push)
- [GitLab](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#push-events)
Adapting workflow steps to support push events on branches is out of scope for this PR. This happens later.
=> Allow push events on branches in ScmWebhookEventValidator

src/api/app/models/workflow/step.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/models/workflow/step/link_package_step.rb
Refactor BranchPackageStep the same way we did with LinkPackageStep.
- Unify variable names
- Simplify methods
- Split creation and update code following the [KISS principle](https://www.interaction-design.org/literature/topics/keep-it-simple-stupid). Except for `create_or_update_subscriptions`.
- Move common code to Workflow::Step
Follow up of #11413
*NOTE:* I tried to make every commit as simple as possible, they can be squash before merging.
=> Refactor BranchPackageStep and LinkPackageStep

src/api/app/models/workflow/step.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/models/workflow/step/configure_repositories.rb, src/api/app/models/workflow/step/link_package_step.rb, src/api/spec/models/workflow/step/configure_repositories_spec.rb, src/api/spec/models/workflow_spec.rb
Replace `source_project` by `project` in ConfigureRepositoriesStep 
The 'source_project_name' shouldn't be required for ConfigureRepositoriesStep anymore. For this step, I create a new method `project_name` and add the corresponding validation.
As a consequence, the `target_project_name` method is affected so the definition is moved to each type of step: BranchPackageStep, LinkPackageStep and ConfigureRepositoriesStep
=> Rename source project to project for workflows

src/backend/BSSched/BuildJob.pm, src/backend/BSSched/BuildJob/Package.pm, src/backend/BSSched/Checker.pm, src/backend/BSSched/Modulemd.pm, src/backend/BSXML.pm, src/backend/bs_worker
This always uses the binary id instead of the sourcemd5 in
the meta file. Turning this on easily leads to endless rebuilds
if the project contains build cycles and there is no other
means like build compare to end builds.
=> [backend] Add experimental forcebinaryidmeta build flag

src/api/app/models/scm_webhook.rb, src/api/spec/models/scm_webhook_spec.rb
We need those helper methods to identify push events when
running the workflows
=> Add helper methods for push events to SCMWebhook model

src/api/app/models/workflow/step.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/models/workflow/step/configure_repositories.rb, src/api/app/models/workflow/step/link_package_step.rb, src/api/spec/models/workflow/step/configure_repositories_spec.rb, src/api/spec/validators/workflow_steps_validator_spec.rb
The super class of the steps already takes care of validating
the presence of the source package and source project names through
the REQUIRED_KEYS constant.
=> Remove duplicated validation in branch and link package step

src/backend/BSRepServer/BuildInfo.pm
This is fixing the osc download from mirrors.
=> [backend] bs_repserver: deliver path url in buildinfo for foreign partitions

src/api/app/services/trigger_controller_service/scm_extractor.rb, src/api/spec/models/token/workflow_spec.rb, src/api/spec/services/trigger_controller_service/scm_extractor_spec.rb
Details on the webhook payloads:
- [GitHub push](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push)
- [GitLab push](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#push-events)
=> Adapt ScmExtractor to support push events

src/api/app/controllers/webui/webui_controller.rb, src/api/app/services/webui_controller_service/user_checker.rb, src/api/spec/services/webui_controller_service/user_checker_spec.rb
The logic of WebuiControllerService::UserChecker isn't leaking out of the service anymore. This is to reuse the service.
=> Refactor Webui::WebuiController#check_user

src/backend/bs_repserver, src/backend/bs_srcserver
This can be used to trigger a package rebuild even if the package
is currently blocked (e.g. because of cycle builds).
=> [backend] suppor the 'lastbuild' option in docommand

dist/obsstoragesetup
According to lvcreate man, --wipesignature, "there is a prompt for
each signature detected to confirm its wiping (unless --yes is used to
override confirmations.)". However, obsstoragesetup is executed as a
service and it will abort if an interactive prompt is requested.
The result is that workers are started without a proper storage and
they will start to use rootfs, that might not be prepared to handle
the amount of worker data.
Use --yes for lvcreate to avoid interactve prompts.
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>
=> [dist] obsstoragesetup: do not prompt before wipe

src/api/Gemfile, src/api/Gemfile.lock, src/api/app/lib/routes_helper/role_matcher.rb, src/api/config/routes/webui_routes.rb, src/api/spec/lib/routes_helper/role_matcher_spec.rb
This UI is only available to users with the Staff or Admin roles. It allows us to quickly manage which feature toggles are enabled/disabled without having to run commands directly on the server where our application is hosted. 
Upstream docs for the Flipper UI:
https://github.com/jnunemaker/flipper/blob/4da0b9a596465310882c368fa5292dcbbde48399/docs/ui/README.md
Once this PR is merged, this will have to be documented in our developer wiki: https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles
=> Enable UI for Flipper

.github/labeler.yml
Quotes are needed to prevent a `YAMLException: unidentified alias` error.
=> Label PRs with Markdown files

src/api/Gemfile.lock, src/api/Gemfile.next.lock
The [package in O:S:U](https://build.opensuse.org/package/show/OBS:Server:Unstable/rubygem-bundler) is updated, the container is on it's way.
=> Update bundler version 2.2.27

src/api/Gemfile.lock, src/api/Gemfile.next.lock
Reverts openSUSE/open-build-service#11682
Again some problems with obs-service-bundle_gems that need fixing there first....
=> Revert "Update bundler version 2.2.27"

src/api/docker-files/Dockerfile
We use [brakeman](https://github.com/presidentbeef/brakeman) in the code checkout pipeline. It throws false positive warnings for view components that are fixed in the later version. For more details see this [issue](https://github.com/presidentbeef/brakeman/issues/1616)
=> Update brakeman to fix false positive warnings for view components

src/api/public/robots.txt
This route is really expensive to call and does not bring
much value for search engine results.
=> Add view_file path to robots.txt

src/api/app/queries/notifications_finder.rb
This is more efficient than fetching all group attributes to only take IDs.
=> Fetch only the group IDs in NotificationsFinder

src/api/app/controllers/webui/request_controller.rb
We do not catch the exception from the backend when a submit
request, created through the webui, fails due to a running service
on the target.
Fixes #11683
=> Prevent silent failure on submit request when service is in progress

.circleci/conditional_config.yml
In this PR, we improved the caching among jobs, dropping around 2 minutes in average while running `minitest`, `specs` and `feature` jobs.
i.e: https://app.circleci.com/pipelines/github/vpereira/open-build-service/817/workflows/a4476512-e2e7-4260-b59f-9b3747e357ee/jobs/14592
Beside that now, we just start `rspec`, `minitest` and `feature` jobs if `linter` runs successfully.
=> Improve gem caching circleci and make linters job mandatory before rspec, minitest and feature jobs

.gitmodules
More details: https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
=> Since 1/9/2021, github won't accept unauthenticated git

src/api/lib/tasks/dev.rake
We introduced in our CI pipeline an apidocs linter. 
This PR introduces a command to run it via rake.
To run it: `rake dev:lint:apidocs`
=> Add apidocs linter to the development rake tasks

src/api/app/controllers/trigger_workflow_controller.rb, src/api/app/models/token/errors.rb, src/api/app/models/token/workflow.rb, src/api/app/services/workflows/yaml_to_workflows_service.rb, src/api/spec/controllers/trigger_workflow_controller_spec.rb, src/api/spec/models/token/workflow_spec.rb
This will help users debug their workflows if something is wrong in their `.obs/workflows.yml`.
=> Run validations upfront, then report any error back to the SCM

src/backend/BSVerify.pm
Nowadays ^ is allowed to be in versions, i.e. also in filenames.
=> [backend] allow ^ in verify_simple

.github/labeler.yml, dist/t/spec/features/0020_interconnect_spec.rb, dist/t/spec/features/0040_package_spec.rb, dist/t/spec/support/capybara.rb
Increase maximum number of seconds from 2 to 6 that Capybara waits for asynchronous processes to finish.
=> Increase Capybara maximum wait time in smoke tests

src/api/app/models/workflow/step.rb, src/api/app/models/workflow/step/configure_repositories.rb, src/api/app/models/workflow/step/rebuild_package.rb, src/api/spec/validators/workflow_steps_validator_spec.rb
Validating a project/package should happen only if the key is present in the step instructions to avoid duplication in error messages.
=> Don't run project/package name validations if the keys are missing

.circleci/conditional_config.yml
Reverts parts of openSUSE/open-build-service#11803
We are already caching the gems in the container images we build ourselves. The frontend-base-ci container rebuilds every time we push to master. No need to cache gems again on circle.
=> Revert gem caching on circleci

dist/t/0060-check_required_services.ts
Searching for mariadb and mysql services resulted sometimes in `mariadb`, and some other times in `mysql`.
`systemctl list-units` always return the services in alphabetical order. Rely on this, to stop searching on the first match from `mariadb` or `mysql`.
This will prevent this flickering errors to happen in [openQA tests](https://openqa.opensuse.org/group_overview/62).
=> Fix flickering smoke test

.circleci/conditional_config.yml
To speed up our CI pipeline, just download the image containing chromium
when necessary
=> Use frontend-base-ci when chromium isnt necessary

dist/t/0060-check_required_services.ts
Fixes the syntax error introduced in #11829.
=> Add missing parenthesis in if condition

src/api/app/views/webui/users/tokens/_create.js.erb, src/api/app/views/webui/users/tokens/new.html.haml
I was tempted to refactor the code to display a kind of a show view right after the token is created. Then the view wouldn't contain read-only text fields but text values.
However, I opted to follow the easy path and simply add the ID value in the current version of the code. The refactoring can be done in the near future.
=> Show token id after creation

src/api/app/validators/workflow_filters_validator.rb
The method `valid_filters?` wasn't returning a boolean, therefore the name was adapted to `validate_filters`
=> Rename method valid_filters? to validate_filters

src/api/lib/xpath_engine.rb, src/api/test/functional/channel_maintenance_test.rb, src/api/test/functional/maintenance_test.rb
Support xpath search for
review/@when
review/history/@when
history/@when
attributes (OBS-149)
=> [api] support request history search by time

.obs/workflows.yml
To be able to restrict the building architectures and repositories,
switch the SCM integration strategy from branch package to link package
Reference:
https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration#link-a-package-to-a-project
=> Move SCM integration from branch package to link package

src/api/app/models/token/errors.rb, src/api/app/services/workflows/yaml_downloader.rb
Give users the right feedback in case the repository doesnt exist
anymore when trying to download the `workflows.yml`
The issue https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/60bff83684bf4607a946599e has two root causes (to investigate them, just navigate through them, clicking on Older/Newer): 
a) When the repository doesn't exist while downloading the YAML file
b) When the repository was removed, but OBS still reporting to github, i.e PR is open, but the repository was deleted. 
This PR fixes just the first case
=> Handle Octokit::InvalidRepository on YAMLDownloader

src/api/app/models/workflow_run.rb, src/api/db/migrate/20211112134215_remove_response_url_from_workflow_runs.rb, src/api/db/schema.rb
Initially, we thought that we needed the field response_url to report
back to SCM.  We just realise we are not responding back to SCM.
=> Drop response_url from workflow_runs

src/api/app/models/workflow_run.rb, src/api/db/migrate/20211116111900_add_response_url_to_workflow_runs.rb, src/api/db/schema.rb
After the discussion, we decided to keep this field in the table so it's easier for users to recognize the SCM instance which triggered the workflow.
=> Add response_url back to workflow_runs

src/api/app/models/workflow.rb
This is following up on the two cards we ended up closing last week:
- [Turn Workflow#branch_matches_branches_filter? into a ActiveModel::Validator](https://trello.com/c/K8AXlIvb/1798-turn-workflowbranchmatchesbranchesfilter-into-a-activemodelvalidator)
- [Turn Workflow#event_matches_event_filter? into a ActiveModel::Validator](https://trello.com/c/4U9DYiNb/1799-turn-workfloweventmatcheseventfilter-into-a-activemodelvalidator)
Those methods shouldn't be custom validators since they wouldn't produce validation errors on which the users can act. Informing users why workflows are run/skipped would be nice, but this is too much work for now.
=> Remove outdated comments in Workflow model

src/api/app/models/workflow/step.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/models/workflow/step/configure_repositories.rb, src/api/app/models/workflow/step/link_package_step.rb, src/api/spec/models/workflow/step/configure_repositories_spec.rb, src/api/spec/models/workflow/step_spec.rb
Fixes #11854
The `Workflow::Step::ConfigureRepositories#target_project_name` method was a redefinition of the `Workflow::Step#target_project_name`.
They should be identical except for the YAML key containing the project name. So there is no need to keep both. In fact, this is leading to inconsistencies. For example with the format of the name (using "-" or ":").
Now we only have one definition of the method. The only part we redefine is the project name. For this, we have the `target_project_base_name` method implemented on each step.
=> Fix inconsistent target project name

src/api/app/services/trigger_controller_service/scm_extractor.rb, src/api/spec/services/trigger_controller_service/scm_extractor_spec.rb
This will be used in #11832, but it's easy to review here without all the other changes.
This is safe to be merged since it doesn't change how workflows run.
=> Support push events for tags in TriggerControllerService::ScmExtractor

src/api/app/models/workflow/step.rb, src/api/spec/models/workflow/step_spec.rb
This will be used in #11832, but it's easy to review here without all the other changes.
This is safe to be merged since it doesn't change how workflows run.
=> Support push events for tags in Workflow::Step#target_{project,package}_name

src/api/app/components/token_card_component.html.haml, src/api/app/controllers/webui/workflow_runs_controller.rb, src/api/app/models/workflow_run.rb, src/api/app/policies/workflow_run_policy.rb, src/api/app/views/webui/workflow_runs/_breadcrumb_items.html.haml, src/api/app/views/webui/workflow_runs/index.html.haml, src/api/config/routes/webui_routes.rb, src/api/spec/components/token_card_component_spec.rb, src/api/spec/controllers/webui/workflow_runs_controller_spec.rb, src/api/spec/policies/workflow_run_policy_spec.rb
We are tracking executed workflow runs and the current state of them
through the `WorkflowRun` model.
Now that this data is available for the users we need the corresponding
webui elements in order to access those infos.
TODO:
Example screenshots (data is fake):
=> Create workflow runs index view

src/api/app/assets/stylesheets/webui/application.scss, src/api/app/assets/stylesheets/webui/workflow_runs.scss, src/api/app/views/webui/workflow_runs/index.html.haml
=> Pretty print request payload of workflow runs

src/api/app/views/layouts/webui/_top_navigation_search.html.haml
So we can just start searching for something when the page loads instead of having to click on it
=> Autofocus into the search input field

src/api/app/services/trigger_controller_service/token_extractor.rb, src/api/spec/services/trigger_controller_service/token_extractor_spec.rb
Token authentication can be performed by passing a token string through an 'Authorization' HTTP header. The format to pass this token follows this expression:
`Token TOKEN_STRING`
This changed in commit deea2dfcd9eea704eaed0532793160f7c7ba88b6, where the check for the 'Token' string was removed.
Reintroduce the check for the 'Token' string, as was initially defined, and is described in the API documentation.
=> Reintroduce checking for `Token` string

src/backend/BSSched/BuildJob.pm, src/backend/BSXML.pm, src/backend/bs_worker
This specifies the compiler cache type to use. We also put the
type in the job file, so that the worker does not need to guess
what thr scheduler used for dependency expansion.
=> [backend] support a new "ccachetype" build flag

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/request.yaml, src/api/public/apidocs-new/paths/request_id.yaml, src/api/public/apidocs-new/paths/request_id_cmd_diff.yaml, src/api/public/apidocs-new/paths/request_view_collection.yaml
We are using plural tags when possible, so we pluralize the request tag for consistency.
=> Pluralize request tag name in API docs

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_addchannels.yaml
This is the new ApiDoc endpoint that will eventually replace the current endpoint here https://build.opensuse.org/apidocs/index#44
=> Add source project name Apidoc endpoint

.obs/workflows.yml
In order to resolve all dependencies properly when building the
obs_server package in our CI workflows, we need to setup the
repositories through the obs unstable project, since a lot of
dependencies live in this project. We cannot directly use
the 15.3/SLE-SP3 repos.
=> Derive repositories through OBS:Server:Unstable project in our CI workflows

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_copy.yaml
This PR documents the `POST /source/<project>?cmd=copy` endpoint
with the new OpenAPI specification.
The `copy` command copies the entire project from the source project
provided by `oproject` to the target project provided by `project`.
The params `makeolder` and `makeoriginolder` update the relevant vrev.
The param `withbinaries` ensures we copy also the binaries.
=> Add source project name copy cmd apidoc endpoint

src/backend/BSSrcServer/Service.pm, src/backend/BSSrcrep.pm, src/backend/bs_service, src/backend/bs_servicedispatch, src/backend/bs_srcserver
An obsscm service is a pseudo service that is not based on
a commit. The service result is not prefixed with _service,
but committed as is.
We currently mis-use the 'title' field in the package meta
to configure the obsscm url, this will be changed to some
extra package element.
=> [backend] implement an obsscm service type

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_lock.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_unlock.yaml
Document these two endpoints following OpenAPI specifications:
=> Document endpoints regarding project lock and unlock

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/schemas/missing_owner_collection.yaml, src/api/public/apidocs-new/components/schemas/owner_collection.yaml, src/api/public/apidocs-new/paths/missing_owner.yaml, src/api/public/apidocs-new/paths/search_owner.yaml
FYI: The current api documentation lists the `limit` and `devel` parameter also for the missing owner search. Both are not used in the code and therefore not documented with openapi
=> Document owner/missing_owner search endpoint with openapi

src/api/app/controllers/source_controller.rb
This way, the endpoint will render a `200 OK` response instead of a `204 No Content` response when the 'undelete' is correctly performed.
=> [api] Set 200 OK response for undelete action on project

src/api/public/apidocs-new/paths/source_branch.yaml
The enum values were missing the comma separator.
=> Fix enum values

src/api/public/apidocs-new/paths/source_project_name_cmd_createkey.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_extendkey.yaml
GPG refers to a proper noun, so it needs to be capitalized.
=> Capitalize GPG in API documentation

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_freezelink.yaml
This PR documents the `POST /source/<project>?cmd=freezelink` endpoint
with the new OpenAPI specification.
This endpoint freezes a project link, either creating the freeze or updating it.
=> Add source project name with freezelink command

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_undelete.yaml
Document the endpoint following the OpenAPI specifications.
**NOTE**: The responses of this endpoint are not like the ones we see in other endpoints. We don't get a `200 OK` even if the `undelete` is performed correctly.
And one of the error responses looks weird since it's embedding a XML inside another.
=> Add '/source/{project_name}?cmd=undelete' endpoint

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/components/parameters/limit.yaml, src/api/public/apidocs-new/components/parameters/withdownloadurl.yaml, src/api/public/apidocs-new/components/responses/search/published_binary_id.yaml, src/api/public/apidocs-new/components/responses/search/published_pattern_id.yaml, src/api/public/apidocs-new/components/responses/search/published_repoinfo_id.yaml, src/api/public/apidocs-new/paths/search_published_binary_id.yaml, src/api/public/apidocs-new/paths/search_published_pattern_id.yaml, src/api/public/apidocs-new/paths/search_published_repoinfo_id.yaml
=> Document various endpoints under '/search' with OpenAPI, part I

src/api/Gemfile
Requiring the enigne isn't needed anymore since view_component 2.43.0 and the deprecation message was added in 2.45.0.
This was the deprecation message:
> DEPRECATION WARNING: This manually engine loading is deprecated and will be removed in v3.0.0. Remove `require "view_component/engine"`. (called from <top (required)> at /obs/src/api/config/application.rb:29)
=> Fix deprecation warning for view_component

src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/source_project_name_cmd_release.yaml
This PR documents the POST /source/<project>?cmd=release endpoint with the new OpenAPI specification.
=> Add source project name with release command

src/backend/BSSrcServer/Service.pm, src/backend/bs_service
It's much easier and less error prone to let bs_service do
the _service: prefixing like with all other services and
unprefix again in the file receiver code.
=> [backend] remove special casing of the obs-scm-bridge in bs_service

src/api/app/models/workflow/step/configure_repositories.rb
In order to properly set the repositories on a project through
the workflows, we need to tell the backend about the changes as well,
otherwise the packages won't start to build against those repos.
=> Store changes on the backend in repositories_configuration step

src/api/app/controllers/person/notifications_controller.rb, src/api/app/views/person/notifications/index.xml.builder
The total refers to the count of all notifications of a user. It's not the count of the notifications to be returned to the user. `@notifications_per_page` isn't a valid name here since it refers to how many notifications are returned per page. This changes depending on the `show_all` query parameter.
=> Rename @notifications_total to @notifications_count

src/api/public/apidocs-new/components/schemas/notifications.yaml
Have `<notifications>` instead of `<notifications.yaml>`
Before:
Preview:
=> Fix XML tag name for notifications schema

src/api/app/controllers/person/notifications_controller.rb, src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/helpers/webui/notification_helper.rb, src/api/app/views/webui/users/notifications/_notifications_list.html.haml, src/api/public/apidocs-new/paths/my_notifications.yaml
It never showed all notifications. The "Show all" link and parameter show a maximum number of notifications (300 right now).
=> Rename "Show all" in notifications API and web UI

src/api/test/unit/project_test.rb
In case a test fails, the message returned is the opposite of what is expected.
Taken this example:
```
expected = { error: 'We are expecting some error.' }
actual = {}
assert_equal(actual, expected)
```
this will return the following error message:
```
--- expected
+++ actual
@@ -1 +1 @@
-{}
+{:error=>"We are expecting some error."}
```
Chaging the order of the assert_equal parameters to the following:
```
assert_equal(expected, actual)
```
will return the correct message:
```
--- expected
+++ actual
@@ -1 +1 @@
-{:error=>"We are expecting some error."}
+{}
```
See [assert_equal documentation](http://docs.seattlerb.org/minitest/Minitest/Assertions.html#method-i-assert_equal).
=> Fix order of parameters in `assert_equal` calls, in project minitests

.circleci/conditional_config.yml
We use workspaces to save transfer artifacts between CircleCI jobs
steps.
On the [install dependencies](https://github.com/openSUSE/open-build-service/blob/23d535ca29ed957b578b607f735c6b139fccf8b0/.circleci/conditional_config.yml#L55) step of the `checkout_code` job we
install the gems present on the `Gemfile.lock` system wide, on
`/usr/lib64/ruby2.5.0`. That directory is not being taken into account
when performing the [persist_to_workspace](https://github.com/openSUSE/open-build-service/blob/23d535ca29ed957b578b607f735c6b139fccf8b0/.circleci/conditional_config.yml#L194) step, and that's why we get
errors regarding missing gems on the linters.
Changing the vendoring path so it will be included in the workspace
persitence fixes that. When the workspace is …
=> Change the bundle install vendoring path on CircleCI jobs

src/api/public/apidocs-new/paths/my_notifications.yaml
All are query parameters and the `notifications_type` parameter, used to filter, was missing.
Follow-up #11960.
=> Adjust notifications endpoint API docs

.circleci/conditional_config.yml
This reverts commit cc2a0cff6ed91212b402fb26b8da9ef5f6be7979.
With CircleCI failing in the `linters` step due to a missing gem, the root cause isn't the `bundle install` path and how gems are cached in CircleCI, but the Docker image not being up to date. This can happen if somehow those images aren't building on OBS. This is what happened last time when a server was down, preventing new images from being built for our CI.
=> Revert "Change the vendoring path"

src/api/app/components/notification_action_bar_component.html.haml
=> Improve "Mark all as 'Read'" button position on small viewports in Notifications

src/api/app/controllers/person/notifications_controller.rb, src/api/app/policies/notification_policy.rb, src/api/config/routes/api_routes.rb, src/api/public/apidocs-new/OBS-v2.10.50.yaml, src/api/public/apidocs-new/paths/my_notifications_id.yaml, src/api/spec/controllers/person/notifications_controller_spec.rb
Since there is only one attribute for notifications were it makes
sense to change it by hand, the update endpoint doesn't work
with xml payload or a query parameter, but simply toggles the
`delivered` attribute of a notification to mark it as read/unread.
=> Create notification update api endpoint

src/api/app/controllers/person/notifications_controller.rb, src/api/spec/controllers/person/notifications_controller_spec.rb
Removing this code is needed to be able to roll out the notifications_redesign feature toggle. Otherwise, users in the rollout group would still need to be part of the beta program to use this feature... which is nullifying the purpose of rolling out a feature.
=> Rely only on Flipper to check if feature toggle is enabled

src/backend/bs_srcserver
This type will be used for git-buildpackage debian builds.
=> [backend] enable debian.control builds

src/api/app/views/webui/users/notifications/_index_actions.html.haml
We have the same link in two places (notifications and profile pages) but they have different texts. We change the text to unify them and also to stop using "subscriptions" in favour of "notifications".
=> Unify texts for links to Notifications Configuration

src/api/public/apidocs-new/paths/my_notifications_id.yaml
Just like GET /my/notifications
=> Mark PUT /my/notifications/{id} endpoint as beta/unstable in API docs

src/api/public/apidocs-new/paths/my_notifications.yaml, src/api/public/apidocs-new/paths/my_notifications_id.yaml
The `notifications_redesign` is no longer a beta feature, now it's rolled out for every single user.
=> Remove mention to Beta in notifications API docs

src/api/app/models/search_finder.rb
The `@preloaded_classes` class variable was never modified.
The `@preloads` variable was only assigned for "request" searches. Even if it considered a typo, and `@preloads` is substituted by `@preloaded_classes`, this could led to always apply a `preload` to the final query. This can improve the `GET /search/request` endpoint, but it is not the desirable behavior for the `GET /search/request/id` endpoint.
=> Remove unused code in SearchFinder

src/api/app/models/owner_search/assignee.rb, src/api/test/functional/search_controller_test.rb
This parameter is not documented, and it is not used in the rest of the codebase.
=> Remove unused parameter `webui_mode` in owner search

src/api/app/models/binary_release.rb
when the image/container contains binaries provided via DoD
=> [api] fix a crash in package tracking

src/api/app/controllers/source_controller.rb
api can not update backend_data since no package object exists for "_project" package
=> [api] fix crash on project runservice command

src/api/app/views/webui/users/notifications/_notifications_list.html.haml
When we filter notifications by group and then mark them all as read, we only want to mark those affected by the filter, not every single notification.
The bug was found thanks to this issue: https://github.com/openSUSE/open-build-service/issues/12007
=> Fix combination of Group filter and Mark all as read

src/api/app/views/webui/users/notifications/_notifications_list.html.haml
When filtering by group and marking one notification as read, we want to see the same filtered list after the action is done.
Before this fix, we displayed the "Unread" list instead of the list filtered by group.
=> Keep filter after marking a notification as read

src/api/app/models/binary_release.rb, src/api/spec/factories/binary_releases.rb, src/api/spec/models/binary_release_spec.rb
The `BinaryRelease` model has no spec. So I'm adding some specs and did a light refactoring around some methods. The main idea of this PR, however is to spec the public API.
=> Add spec to BinaryRelease model

src/api/app/models/binary_release.rb, src/api/spec/models/binary_release_spec.rb
In this PR i removed some unnecessary comments (which should be done as well in other models) and expanded the spec for the `BinaryRelease` model
=> Clean BinaryRelease and add Spec for BinaryRelease.update_binary_releases

src/api/config/routes.rb
This fix is already present in the main branch, but 2.10 is missing constraints for this endpoint, which breaks with usernames with dots in them. Tested on a local installation, fixes #10951
=> Add constraints to user requests endpoint

src/backend/bs_signer
No need for backward compatibility hopefully since there are no old
Arch Linux systems out there?
current distro seem not to support v3 anymore
=> [backend] use GPG v4 for ArchLinux

src/api/app/models/branch_package.rb, src/api/app/models/bs_request_action_maintenance_incident.rb
This makes it possible to submit a package to a higher service pack level again.
Also fixed a crash when using a remote package as source here.
=> [api] fix ignore releasetarget project on maintenance_incident requests

src/api/app/components/workflow_run_detail_component.html.haml, src/api/app/components/workflow_run_detail_component.rb, src/api/app/components/workflow_run_row_component.html.haml, src/api/app/components/workflow_run_row_component.rb, src/api/app/models/workflow_run.rb, src/api/app/views/webui/workflow_runs/index.html.haml, src/api/spec/components/workflow_run_detail_component_spec.rb, src/api/spec/components/workflow_run_row_component_spec.rb
This PR changes the Workflow Run index page to show a bit more of detail on each displayed item to quickly identify each run.
Missing:
=> Show meaningful data for each workflow run

src/api/app/controllers/trigger_workflow_controller.rb, src/api/app/models/scm_webhook.rb, src/api/app/models/token/workflow.rb, src/api/spec/controllers/trigger_workflow_controller_spec.rb, src/api/spec/models/token/workflow_spec.rb
=> Check pull/merge request actions before initializing dependencies

src/api/app/components/workflow_run_row_component.rb, src/api/spec/components/workflow_run_row_component_spec.rb
We do not want to show anything if the action is not supported.
This fixes #12077 showing "unsupported" tags in the view.
=> Hide unsupported actions in WorkflowRun's index page

src/api/app/components/workflow_run_row_component.html.haml, src/api/app/components/workflow_run_row_component.rb, src/api/spec/components/workflow_run_row_component_spec.rb
This is a follow up/fix for openSUSE#12077 where the logic to render the improved information for a Workflow Run is done also for GitLab-triggered workflows.
Also Fixes openSUSE#12105
This is how it looks now:
Note the Merge requests coming from GitLab
=> Implement the improvements in the UI for GitLab too

src/api/app/components/copy_to_clipboard_input_component.html.haml, src/api/app/components/copy_to_clipboard_input_component.rb, src/api/app/components/token_card_component.html.haml, src/api/app/controllers/webui/users/tokens_controller.rb, src/api/app/policies/token_policy.rb, src/api/app/views/webui/users/tokens/_actions.html.haml, src/api/app/views/webui/users/tokens/_breadcrumb_items.html.haml, src/api/app/views/webui/users/tokens/_create.js.erb, src/api/app/views/webui/users/tokens/edit.html.haml, src/api/app/views/webui/users/tokens/new.html.haml, src/api/app/views/webui/users/tokens/show.html.haml, src/api/spec/controllers/webui/users/tokens_controller_spec.rb, src/api/spec/policies/token_policy_spec.rb
Right now, we don't have `token#show` and the only way to view a token is using `tokens#edit`. And we reuse the view `tokens/new` to show the token after creating a token, it is full of hidden fields and it's confusing.
This PR introduces `tokens#show` to simplify the token creation process and to have a new page to view tokens.
The token creation code is much simpler now and it's following Rails convention.
=> Simplify token creation code

src/backend/bs_warden
Remove :status files if they contain invalid xml and are older
than one hour.
=> [backend] bs_warden: remove unreadable :status files

src/api/app/models/product.rb
We get an empty hash with current XMLHash which leads to an activerecord
exception meanhwile.
=> [api] fix crash when product defines remote update url

src/api/app/controllers/person_controller.rb, src/api/lib/xpath_engine.rb
The DB entry must remain, as re-creating the same user would cause
a security/trust breach. But personal data got already removed.
However, do not list these accounts anymore
bnc#1106763
=> [api] do not list deleted users

src/api/app/models/token/workflow.rb, src/api/app/models/workflow.rb, src/api/app/models/workflow/step.rb, src/api/app/models/workflow_artifacts_per_step.rb, src/api/app/models/workflow_run.rb, src/api/app/services/workflows/artifacts_collector.rb, src/api/app/services/workflows/yaml_to_workflows_service.rb, src/api/db/migrate/20220126155601_create_workflow_artifacts_per_steps.rb, src/api/db/schema.rb, src/api/spec/cassettes/Workflow/_steps/with_a_supported_step/1_2_1_2.yml, src/api/spec/cassettes/Workflow/_steps/with_no_steps_specified/1_2_4_2.yml, src/api/spec/cassettes/Workflow/_steps/with_one_unsupported_step/1_2_3_2.yml, src/api/spec/cassettes/Workflow/_steps/with_several_supported_steps/creates_no_artifacts_because_an_exception_is_raised.yml, src/api/spec/cassettes/Workflow/_steps/with_step_with_invalid_intructions/1_2_5_2.yml, src/api/spec/cassettes/Workflow/_steps/with_step_with_invalid_project_name/1_2_6_2.yml, src/api/spec/models/token/workflow_spec.rb, src/api/spec/models/workflow_artifacts_per_step_spec.rb, src/api/spec/models/workflow_spec.rb, src/api/spec/services/workflows/artifacts_collector_spec.rb, src/api/spec/services/workflows/yaml_to_workflows_service_spec.rb
On every webhook OBS receives from an SCM, OBS follows the instructions given by `workflows.yml` performing the steps on it.
Those steps can handle or create different bunches of artifacts. For example, _repositories_ and _architectures_ if the step is `configure_repositories` or _projects_ and _packages_ in steps like `link_package` etc.
After each workflow run, we want to display all the artifacts involved so the user can better understand what was going on.
In this PR, we are collecting the main information about the artifacts we get on every step and storing them in DB with JSON format.
The JSON for a _link_package_ step can look like this:
```
{
"source_project": "<source project name>",
"source_package": "<source package name>",
"target_project": "<target project name>", …
```
=> Collect artifacts created on every run worflow step

src/api/app/models/workflow.rb
Rubocop started to complain about this on the master branch,
guess because of some PR that got merged without being rebased
before. This is just a quick fix to prevent future PRs failing
in the CI.
=> Fix Metrics/ClassLength rubocop offense in workflow model

src/api/app/services/workflows/artifacts_collector.rb, src/api/spec/components/previews/workflow_artifacts_per_step_component_preview.rb, src/api/spec/services/workflows/artifacts_collector_spec.rb
We were collecting the wrong project as artifact of a `configure_repositories` step.
Caught by @dmarcoux in this PR: https://github.com/openSUSE/open-build-service/pull/12157#pullrequestreview-871906406
=> Fix artifacts for configure_repositories

src/api/app/models/token/workflow.rb, src/api/app/models/workflow/step/branch_package_step.rb, src/api/app/models/workflow/step/link_package_step.rb, src/api/app/services/scm_initial_status_reporter.rb, src/api/spec/models/token/workflow_spec.rb, src/api/spec/models/workflow/step/branch_package_step_spec.rb
To give a feedback to the users as soon as possible, we are setting initially a generic status to the PR. Package name, multibuild flavors and other details are going to be reported by OBS later with the delayed job `ReportToSCMJob`.
Screenshot when we first create the PR:
Screenshot when the build process reported back:
Another thing being changed in this PR is the way that we report back to SCM. Until now we were adding to specific steps, the ability to report back. Now we are trying to come up with a more holistic approach to the problem.
From this card, we have some TODO that should become cards in our backlog:
- ~~[ ] Handle event filtering in the workflow level, not in the steps level. The filters aren't just for reporting~~.
=> Create an initial generic status

src/api/app/assets/stylesheets/webui/workflow_runs.scss, src/api/app/components/workflow_run_filter_component.html.haml, src/api/app/components/workflow_run_filter_component.rb, src/api/app/components/workflow_run_filter_link_component.html.haml, src/api/app/components/workflow_run_filter_link_component.rb, src/api/app/components/workflow_run_row_component.rb, src/api/app/controllers/webui/workflow_runs_controller.rb, src/api/app/models/workflow_run.rb, src/api/app/queries/workflow_runs_finder.rb, src/api/app/views/webui/workflow_runs/index.html.haml, src/api/spec/components/workflow_run_filter_component_spec.rb, src/api/spec/components/workflow_run_filter_link_component_spec.rb, src/api/spec/components/workflow_run_row_component_spec.rb, src/api/spec/queries/workflow_runs_finder_spec.rb
This PR implements several filters to help you narrow down your search
for a specific workflow run.
It filters by workflow run status (success, running, failure) and by
source event (pull request, push, both GitHub and GitLab).
*TODO*
=> Implement filters for Workflow Runs

src/api/app/controllers/person/notifications_controller.rb, src/api/public/apidocs-new/paths/my_notifications.yaml, src/api/spec/controllers/person/notifications_controller_spec.rb
Currently, we don't have a way to get `read` notifications, we can only get unread notifications through the API. This PR adds a possibility to get read notifications.
=> List read notifications through API

src/api/app/controllers/webui/projects/status_controller.rb
Hello,
Fixes #7380.
The status page only listed submit requests so far, it should now also list delete requests.
To verify this, please create a delete requests for any package that has failed, then go to the status page for this project. In the summary tab there should now be a link to this delete request.
**Before**:
**After**:
=> Show delete requests in status page

src/api/app/helpers/webui/notification_helper.rb
This is what ActionView uses to associate records with DOM elements. Let's use it too!
https://api.rubyonrails.org/classes/ActionView/RecordIdentifier.html#method-i-dom_id
The generated ID is slightly different, `dom_id` uses underscores instead of dashes. So before, it was `update-notification-123`, now it's `update_notification_123`. It's not an issue, as we don't refer to this ID in any code.
Nothing changes visually, but here's the helper in use with the new ID:
=> Use dom_id for mark_as_read_or_unread_button

src/api/app/models/kiwi/preference.rb, src/api/spec/models/kiwi/preference_spec.rb
Kiwi just allows numbers and dots. This fixes errors when working on our
official templates for Leap, using just "15.3" as version for example.
=> allow kiwi versions not strictly x.y.z scheme

src/api/.rubocop.yml, src/api/app/lib/rubocop/cop/view_component/avoid_global_state.rb, src/api/config/initializers/zeitwerk.rb, src/api/spec/lib/rubocop/cop/view_component/avoid_global_state_spec.rb, src/api/spec/rails_helper.rb, src/api/spec/support/rubocop.rb
To enforce what we've defined in our developer wiki: https://github.com/openSUSE/open-build-service/wiki/View-Components#avoid-global-state
Two nice articles to understand how custom cops for RuboCop work:
- https://thoughtbot.com/blog/rubocop-custom-cops-for-custom-needs
- https://evilmartians.com/chronicles/custom-cops-for-rubocop-an-emergency-service-for-your-codebase
=> Create RuboCop cop to avoid global state in view components

src/api/app/components/notification_component.html.haml, src/api/app/components/notification_component.rb, src/api/app/presenters/notification_presenter.rb, src/api/app/views/webui/users/notifications/_notifications_list.html.haml
`NotificationComponent` renders a notification with the help of a few small view components, each having a single responsibility.
Fixes #11558
=> Retire NotificationPresenter in favor of view components

src/api/app/models/bs_request_action_submit.rb
It failed in the case when the source package should got re-setup as
devel branch.
Since this is managed in git, we must not touch it in that case.
Fixes #12222
=> [api] fix accepting of submit request of scmsync packages

src/api/app/components/notification_excerpt_component.rb, src/api/spec/components/notification_excerpt_component_spec.rb
=> Prevent errors for a BsRequest without a description in NotificationExcerptComponent

src/api/app/components/notification_action_description_component.rb
Closes #12227
`bs_request_action.target_project` already returns a string. It's not an ActiveRecord object that's why we can't use `.name` on it.
=> Use target_project instead of target_project.name

src/api/spec/components/notification_action_description_component_spec.rb
Having this spec would have prevented the issue from happening. It also proves that the fix included in #12229 works.
In the screenshot below, I reverted the fix locally in my development environment to show that the spec does fail:
=> Add spec to reproduce issue #12227

src/api/app/components/notification_avatars_component.rb, src/api/app/controllers/person/notifications_controller.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/controllers/webui/project_controller.rb, src/api/app/controllers/webui/request_controller.rb, src/api/app/controllers/webui/users/notifications_controller.rb, src/api/app/models/review.rb, src/api/app/policies/notification_policy.rb, src/api/app/queries/notifications_finder.rb
The PR removes most of the n+1 queries from the notification index view. The bullet gem now complains about unnecessary eager loads. For me this looks like a false positives. I tested to load some of the associations separate to check if the bullet gem would stop complaining, but ended up with the same result.
=> Avoid n+1 queries for notification index view

src/api/spec/features/webui/projects_spec.rb
According to the CircleCI insights about flickering specs, this spec was failing in about 3% of the last 100 CI runs. It failed when, for an obscure reason, the flash wasn't set. I have no idea why, but checking for the project's title on the project#show page of the newly created maintenance incident is sufficient to test the whole workflow.
Link to the CircleCI insights:
https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests
Fixes #10233
=> Fix flickering spec in features/webui/projects_spec.rb

src/api/spec/features/webui/maintenance_workflow_spec.rb
According to the CircleCI insights about flickering specs, this spec was failing in about 2% of the last 100 CI runs. It failed when, for an obscure reason, the flash wasn't set. I have no idea why, but checking for the request's number and state on the request#show page of the newly accepted BsRequest is sufficient to test the whole workflow.
Link to the CircleCI insights:
https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests
=> Fix flickering spec in features/webui/maintenance_workflow_spec.rb

src/api/app/models/event/build_fail.rb, src/api/spec/mailers/event_mailer_spec.rb
Sometimes the build log contains invalid UTF-8 characters that raise an exception during email composing.
Fixes #6872
=> Fix invalid byte sequence in UTF-8 in event mailer

src/api/app/components/watchlist_component.rb, src/api/app/controllers/webui/watched_items_controller.rb, src/api/config/routes/webui_routes.rb, src/api/spec/controllers/webui/watched_items_controller_spec.rb
Right now we use custom routes for creating/deleting watched items. Following Rails conventions for routing, we should update the custom routes for watched items toggle to resourceful routes.
We can't use `member` for some of these new routes because we have `param: :name` for both projects and package nested routes and it's not possible to distinguish if the name is for `project` or `package`. 
The [last paragraph of this article](https://guides.rubyonrails.org/v6.1/routing.html#adding-member-routes) describes that we can ommit `member` to obtain the same result but using the param names we need.
=> resourceful routes for watched items

src/api/app/components/watchlist_component.rb, src/api/app/controllers/webui/package_controller.rb, src/api/app/mixins/build_log_support.rb, src/api/app/views/webui/package/_live_build_log_controls.html.haml, src/api/app/views/webui/package/live_build_log.html.haml, src/api/spec/cassettes/Webui_PackageController/build_logs/GET_update_build_log/for_multibuild_package/1_10_2_4_5.yml, src/api/spec/controllers/webui/package_controller_spec.rb
With the new watchlist implementation, an error was thrown when browsing the live build log for a multibuild package. The guilty was `@package` returning a string instead of an object.
This PR includes the following changes:
- In case of a multibuild package: `@package` used to be a string, now `@package` contains an object.
- `@package_name` is introduced and contains the package string.
- The retrieval of build logs of remote projects was not supported. This code was removed. This means that `@package` is no longer nil.
- Thanks to the previous changes, checking for the permissions is more straight forward, as `@package` is no longer nil.
These changes imply some improvements in the UI for the live build log page for a multibuild package.
**Before:**
- The tabs where not shown
- The …
=> Show link to add a package to the watchlist for multibuild packages

src/api/app/components/watchlist_component.rb, src/api/app/views/layouts/webui/webui.html.haml, src/api/spec/components/watchlist_component_spec.rb
Add support in this component handle @package being a multibuild flavor instead
of being a `Package` object.
Do not support adding packages to the watchlist that come in via project links.
EventSubscription based on the watchlist and things like Notifications,
ProjectLogEntry, Mails etc. on top of EventSubscription, do not take project
links into account currently.
=> Support multibuild, do not support project links

src/backend/BSContar.pm
see https://github.com/helm/community/blob/main/hips/hip-0006.md#what-is-the-correct-media-type-to-use-for-the-chart-content-layer
=> [backend] update to new helm chart mimetype

src/api/spec/components/notification_avatars_component_spec.rb
This is otherwise still flickering, even after the changes from #12249.
Flickering specs are listed in CircleCI:
https://app.circleci.com/insights/github/openSUSE/open-build-service/workflows/test_all/tests
=> Do not stub constant for NotificationAvatarsComponent specs

src/api/app/models/review.rb
This method could have been removed in 9616040fc5f6f3c9811a9755fede5556263bba44.
I just cherry-picked one commit from #9935.
=> Remove unused method `webui_infos`

src/api/app/models/patchinfo.rb, src/api/test/functional/maintenance_test.rb
We need to html encode given text for _patchinfo xml element text
=> [api] fix encoding on patchinfo creation

src/api/app/models/event/base.rb, src/api/app/models/event/build_fail.rb, src/api/app/models/event/comment_for_package.rb, src/api/app/models/event/comment_for_request.rb, src/api/app/models/event/request.rb, src/api/app/models/event/request_create.rb, src/api/app/models/event/request_statechange.rb, src/api/app/models/event_subscription.rb, src/api/app/models/event_subscription/for_event_form.rb, src/api/app/views/webui/subscriptions/_subscriptions_form.html.haml, src/api/spec/models/event/base_spec.rb, src/api/spec/models/event/request_spec.rb, src/api/spec/models/event_subscription/for_event_form_spec.rb
This PR adds the functionality to subscribe to events triggered for watched packages and request, recently added under the beta program.
*HOW TO TEST:*
1. Navigate to the subscription page http://localhost:3000/my/subscriptions
2. Check some of the new added event subscription like `Watching the request` under the `Request state was changed` section
3. Create a request and add it to your watchlist (make sure your user is part of the beta program)
4. Change the state of the request
5. Enter the rails console and run `SendEventEmailsJob.perform_now` to trigger the creation of the notifications
6. Check in the webui if the notification appears
*TODO:*
=> Add new watchable items in the subscription page

src/api/app/models/review.rb, src/api/db/data/20200730163910_set_changed_state_at_to_reviews.rb, src/api/db/migrate/20200730153057_add_changed_state_at_to_reviews.rb, src/api/db/schema.rb, src/api/test/functional/request_controller_test.rb
It was never updated which made the information in most
cases identical to request creation time always.
The attribute is supposed same as the when attriute
of the request itself, where it is the last time the
request changed.
=> [api] fix change time in reviews (when attriute)

src/backend/bs_servicedispatch
Esp git managed projects can cause a flood of events at once
=> [backend] servicedispatch: limit on project level and not on package level

src/api/app/assets/stylesheets/webui/flash.scss
Extending a class with the same class has no effect if nothing else is changed.
=> Remove unneeded `@extend .alert-success`

src/api/app/controllers/webui/package_controller.rb
Whether the log chunk size is zero or the request is not the first, the live log must not stop. Only rely on the list of returning codes recognized as final states to stop the live log.
This prevents the case of stopping the live log when the log chunk size is zero, the request is not the first one, and the code returned by the API is "finished". "finished" is not a final state, and the live log page should keep requesting AJAX calls until the code returned is a final one (like "succeeded", "failed", ...).
References:
- Definition of the state `finished`: https://github.com/openSUSE/open-build-service/blob/97e3faa92a6b090b9b07c94b5102ec14763027de/src/api/app/models/buildresult.rb#L32-L33
- List of final states: https://github.com/openSUSE/open-build-service/blob/97e3faa92a6b090b9b07c94b510 …
=> Don't rely on other conditions to stop a live log

src/api/app/assets/javascripts/webui/live_build_log.js, src/api/app/views/webui/package/_live_build_log_controls.html.haml, src/api/app/views/webui/package/update_build_log.js.haml
Now it is possible to receive browser notifications from the live build log.
Fixes #7920
Example of a notification of a succeeded build:
Example of a notification of a failed build:
A button "Browser Notifications" was added to ask for permission to receive browser notifications:
- It will appear enabled when notifications are not yet allowed or denied.
- It will appear disabled when the permission is already granted or revoked. In this case, the permission could be deleted through the browser configuration.
To test this PR:
- Go to a live log page of a package in the [review app](https://obs-reviewlab.opensuse.org/eduardoj-live_build_log_browser_notifications/package/live_build_log/home:Admin/hello_world/openSUSE_Tumbleweed/x86_64).
- Enable your browser notifications:
- Click in the …
=> Introduce browser notifications for live build logs

src/api/lib/tasks/dev.rake, src/api/spec/factories/workflow_artifacts_per_step.rb, src/api/spec/factories/workflow_runs.rb
With this task, we can easily fill in our development database with a workflow token and some workflow runs.
Data that helps us to try out things during development and in review-app.
=> Add rails task to create workflow token and runs

src/api/app/models/package_file.rb, src/api/app/models/project_config_file.rb, src/api/app/models/project_file.rb, src/api/app/models/project_meta_file.rb, src/api/spec/models/backend/file_spec.rb, src/api/test/functional/request_controller_test.rb
See https://github.com/ruby/uri/commit/61c6a47ebf1f2726b60a2bbd70964d64e14b1f98
`URI.escape` is deprecated in Ruby 3.1. This PR helps to reduce the size of the `ruby31` branch, the upcoming changeset to make OBS compatible with Ruby 3.1.
See #12302
=> URI.encode is removed, use Addressable::URI.encode

src/api/app/helpers/maintenance_helper.rb, src/api/app/helpers/webui/webui_helper.rb, src/api/app/models/package.rb, src/api/app/models/project.rb, src/api/spec/factories/packages.rb, src/api/spec/models/package_spec.rb
In order to prepare for the update of Ruby 3.1, we're extracting as many changes as possible and pushing them to master. 
`URI.escape` will be deprecated in Ruby 3.1 (see #12304)
=> Replace URI.escape with Addressable::URI.escape 

src/api/app/controllers/webui/package_controller.rb
It is unnecessary to repeat the request of a log chunk after reaching a final state. This is a follow up to fixing the live build log not to stop in a not final state.
Follow up to #12294.
=> Don't retry requesting the last chunk on live build log

src/api/lib/tasks/dev.rake
Faker sometimes generates names of cats that have spaces, but Group
does not allow spaces in the title.
=> Ensure faker-generated data is valid

src/api/app/controllers/status/reports_controller.rb
Most of the times status reports are nil for bs_requests and `GET '/status_reports/requests/<id>/reports'` results in an error 500. This PR avoids the 500 error and returns 404 instead.
```
Server returned an error: HTTP Error 404: Not Found
Couldn't find Status::Report with [WHERE `status_reports`.`checkable_id` = ? AND `status_reports`.`checkable_type` = ?]
```
=> Do not check for checks and missing_checks for empty status_reports
